(function(){/*
 https://www.pcjs.org/machines/lib/defs.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/numio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/stdio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/webio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/device.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/input.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/led.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/time.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/bus/bus.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/bus/memory.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/bus/rom.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/cpu/cpu.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/ti/lib/cpu1500.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/machine.js (C) 2012-2020 Jeff Parsons
*/
var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function q(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={Ua:!0},fa={};try{fa.__proto__=ea;da=fa.Ua;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function v(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var ia="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ja(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var x=ja(this);function z(a,b){if(b){var c=x;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ia(c,a,{configurable:!0,writable:!0,value:b})}}
z("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});z("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});function ka(){ka=function(){};x.Symbol||(x.Symbol=la)}function ma(a,b){this.a=a;ia(this,"description",{configurable:!0,writable:!0,value:b})}ma.prototype.toString=function(){return this.a};
var la=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ma("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function na(){ka();var a=x.Symbol.iterator;a||(a=x.Symbol.iterator=x.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ia(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}});na=function(){}}function oa(a){na();a={next:a};a[x.Symbol.iterator]=function(){return this};return a}
function pa(a,b){na();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}z("Array.prototype.keys",function(a){return a?a:function(){return pa(this,function(b){return b})}});
z("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});z("Number.parseInt",function(a){return a||parseInt});z("Array.prototype.values",function(a){return a?a:function(){return pa(this,function(b,c){return c})}});var qa=new ArrayBuffer(2);(new DataView(qa)).setUint16(0,256,!0);new Uint16Array(qa);function ra(){}var B={};B.Defs=ra;
function sa(){}v(sa,ra);function ta(a,b){var c=a/C|0,d=b/C|0;return(a&b)==(b|0)&&(c&d)==d}function ua(a){for(var b=0,c=0,d=[];b<a.length;){for(var e=a[b],f=b+1;f<a.length&&a[f]===e;)f++;d[c++]=f-b;d[c++]=e;b=f}return d.length>=a.length?a:d}var C=Math.pow(2,32);B.NumIO=sa;function D(){this.Ca={};for(var a=0;22>a;a++)this.Ca["ACDFHIMNSTWYbdfjcsoXx%"[a]]=null}v(D,sa);p=D.prototype;p.flush=function(){var a=va;va="";this.na(a)};
function wa(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}p.Bc=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,q(b)))};
p.na=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),xa||(xa=b),a=((b-xa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(va+a.substr(0,c)),va="",a=a.substr(c+1)),xa=null);va+=a;return a.length};function E(a,b,c){a.na(b+"\n",c)}p.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.na(this.L.apply(this,[a].concat(q(c))))};
p.L=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(!c||!c.length)return a;d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var k=e[g+5];if(void 0===this.Ca[k])d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+k;else{if(f<c.length){var h=c[f];"%"!=k&&f++}else h=c[c.length-1];var m=e[g+1],l=0<=m.indexOf("#"),r=0<=m.indexOf("0"),n=e[g+2];"*"==n?(n=h,h=f<c.length?c[f++]:c[c.length-1]):n=+n||0;var t=e[g+3];t=t?+t.substr(1):
-1;var y=null,w=0,A="";var u=0<="ACDFHIMNSTWY".indexOf(k)&&"object"!=typeof h?this.Bc(h):h;switch(k){case "C":h=l?"#":"";d+=isNaN(u.getTime())?void 0:this.L(this.L("%%%sW, %%%sF %%%sD, %%%sY",h),u);continue;case "D":h=l?u.getUTCDate():u.getDate();k="d";break;case "A":case "H":case "I":h=l?u.getUTCHours():u.getHours();"A"==k?(h=12>h?"am":"pm",k="s"):("I"==k&&(h=h?12<h?h-12:h:12),k="d");break;case "F":case "M":h=l?u.getUTCMonth():u.getMonth();"F"==k?(h=ya[h],k="s"):(h++,k="d");break;case "N":h=l?u.getUTCMinutes():
u.getMinutes();k="d";break;case "S":h=l?u.getUTCSeconds():u.getSeconds();k="d";break;case "T":h=l?"#":"";d+=isNaN(u.getTime())?void 0:this.L(this.L("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),u);continue;case "W":h=za[l?u.getUTCDay():u.getDay()];k="s";break;case "Y":h=l?u.getUTCFullYear():u.getFullYear(),0<t&&(h%=Math.pow(10,t),t=-1),k="d"}switch(k){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=t&&(r=!0,n<t&&(n=t),t=-1);case "f":h=+h;u=h+"";0<=t&&(u=h.toFixed(t));u.length<
n&&(r?(0>h&&(n--,u=u.substr(1)),u=("0000000000"+u).slice(-n),0>h&&(u="-"+u)):u=("          "+u).slice(-n));d+=u;break;case "j":d+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=t&&(h=h.substr(0,t));h.length<n;)h=0<=m.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":w=8,l&&(A="0");case "X":y=Aa;case "x":u="";w||(w=16);!A&&l&&(A="0x");y||(y=Ba);h=Math.trunc(h);0<=t&&(r=!0,n<t&&(n=t));r&&!n&&
(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9,n+=A.length);n-=A.length;do l=h&w-1,h>>>=16==w?4:3,r||!u||l||h?u=y[l]+u:(A&&(u=A+u,A=""),0<n&&(u=" "+u));while(0<--n||h);d+=A+u;break;case "%":d+="%";break;default:this.Ca[k]?d+=this.Ca[k](k,m,n,t,h):d+="(unimplemented sprintf type: %"+k+")"}}}return d+=e[g]};var va="",xa=null,Ba="0123456789abcdef",Aa="0123456789ABCDEF",za="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ya="January February March April May June July August September October November December".split(" ");
B.StdIO=D;function F(a){D.call(this);this.M={};this.aa=0;this.J=this;a&&(this.J.aa=0,this.J.oa=[],this.J.ea=0,this.J.Da={},this.J.Wd=!1)}var Ca;v(F,D);p=F.prototype;p.ua=function(a,b){var c=this,d=this;switch(a){case Da.Pb:b.onclick=function(){var e=c.wa(Da.Ra,!0);e&&(e.value="")};break;case Da.Ra:Ea(b),b.addEventListener("keydown",function(e){Fa(d,e,!0)}),b.addEventListener("keypress",function(e){Fa(d,e)})}};
function Ga(a,b){b=void 0===b?{}:b;a.s.M||(a.s.M=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.V);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.M[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.M[d].push(e)}while(1);continue}if(f=document.getElementById(e))a.M[d]=f,a.ua(d,f)}}
function Ea(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}p.error=function(a,b){b=this.L.apply(this,[a].concat(q(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.L.apply(this,[c].concat(q(b))))E(this,b),a||alert(b)};p.wa=function(a){return this.M[a]};
function Ha(a){var b=window;if(b){do{for(var c=0;c<Ia.length;c++){var d=Ia[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ja(a){var b=Ka;return a.s.bindings&&a.s.bindings[b]}function La(a){if(a=a.M[Ma])var b=a.textContent;return b}function Na(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function G(a,b,c,d){a=a.s[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Oa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Pa(a){if(void 0===H.Oa){var b=!1;if(window)try{window.localStorage.setItem(H.ta,H.ta),b=window.localStorage.getItem(H.ta)==H.ta,window.localStorage.removeItem(H.ta)}catch(c){E(a,c.message),b=!1}H.Oa=b}return!!H.Oa}function I(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.aa;return-1==(b|1)||ta(a.J.aa,b)?!0:!1}
function Qa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ra(a){var b=null;if(Pa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.I))&&(b=JSON.parse(c))}catch(d){E(a,d.message)}}return b}
function Fa(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.J,f=b.target;if(c){a=!1;var g;c=f.value;var k=c.lastIndexOf("\n");d==J.Za&&f.selectionStart<=k+1&&(a=!0);d==J.sc?(a=!0,0<e.ea&&(g=e.oa[--e.ea])):d==J.Tb&&(a=!0,e.ea<e.oa.length&&(g=e.oa[++e.ea]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,k+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ea&&c+1==g.length&&
(f.value+=e.oa[--e.ea],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Sa(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&E(a,b.replace(/\n$/,""),!1))}}
function Ta(a,b){if(void 0!=b){var c=a.J;try{if(b=b.trim())c.ea<c.oa.length&&b==c.oa[c.ea]?c.ea++:(c.oa.push(b),c.ea=c.oa.length);var d=b.split(" "),e=d[0],f=a.J.Da[Ua.bb];switch(e[0]){case "m":if("?"==e[1]){var g="";Va.forEach(function(r){g+=r+"\n"});g&&(g="message commands:\n"+g);break}g="";var k=void 0;e=d[d.length-1].toLowerCase();var h="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=h&&d.pop();1>=d.length&&(void 0!=h&&(k=h,h=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(K));for(f=
1;f<d.length;f++){e=d[f];var m=K[e];if(!m){g+="unrecognized message: "+e+"\n";break}void 0!=h&&Wa(a,m,h);if(void 0==k||k==I(a,m))g+=a.L("%8s: %b\n",e,I(a,m))}I(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Xa.forEach(function(r){g+=r+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var l=f[a](d);if(void 0!=l){g=g?g+l:l;break}}}}catch(r){g="error: "+r.message+"\n"}}return g}
function Sa(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Ta(a,b[d])}return c}p.na=function(a,b){void 0==b&&(b=I(this,0x800000000000));if(!b){var c=this.wa(Da.Ra,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Qa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return D.prototype.na.call(this,a,b)};
p.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return I(this,d)?D.prototype.w.call.apply(D.prototype.w,[this,a].concat(q(c))):0};function Ya(a,b){if(Pa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.I,b)}catch(c){E(a,c.message)}}}function L(a,b,c){(a=a.M[b])&&a.textContent!=c&&(a.textContent=c)}
function Wa(a,b,c){var d=!1;c?(c=a.J.aa,a.J.aa=(c|b)+(c/C|0|b/C|0)*C):(d=ta(a.J.aa,0x800000000000)&&ta(b,0x800000000000),c=a.J.aa,a.J.aa=(c&~b)+((c/C|0)&~(b/C|0))*C);d&&a.flush()}
var Da={Pb:"clear",Ra:"print"},Xa=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Va=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],K={all:0xffffffffffff,buffer:0x800000000000},Ua={bb:"command"},Za={cb:13,Na:65,Ya:66,$a:67,eb:68,E:69,fb:70,gb:71,hb:72,ib:73,kb:74,lb:75,mb:76,ob:77,qb:78,rb:79,sb:80,Q:81,
tb:82,vb:83,wb:84,xb:85,yb:86,zb:87,Ab:88,Bb:89,Ta:90,Ua:97,Zd:98,$d:99,d:100,e:101,de:102,ee:103,ge:104,he:105,ie:106,k:107,je:108,ke:109,n:110,le:111,p:112,q:113,r:114,me:115,t:116,ne:117,oe:118,pe:119,x:120,y:121,z:122},J={Za:8,pc:9,bc:10,cb:13,mc:16,Rb:17,Nb:18,Md:19,Pa:20,Nc:27,oc:32,Pd:33,Od:34,Mc:35,hd:36,nb:37,sc:38,Sa:39,ed:39,Tb:40,bd:44,Qd:44,jd:45,Lc:46,dd:46,gd:47,ZERO:48,ONE:49,rc:50,qc:51,ac:52,$b:53,nc:54,lc:55,Ub:56,cc:57,Zb:59,Yb:61,Na:65,Ya:66,$a:67,eb:68,E:69,fb:70,gb:71,hb:72,
ib:73,kb:74,lb:75,mb:76,ob:77,qb:78,rb:79,sb:80,Q:81,tb:82,vb:83,wb:84,xb:85,yb:86,zb:87,Ab:88,Bb:89,Ta:90,ab:91,cd:91,ad:92,Td:93,fd:93,nd:96,Ed:96,$c:96,od:97,Cd:97,pd:98,Bd:98,qd:99,Hd:99,rd:100,Fd:100,sd:101,yd:101,td:102,Jd:102,ud:103,Dd:103,vd:104,Ld:104,wd:105,Id:105,Gd:106,xd:107,Kd:109,zd:110,Ad:111,Oc:112,Sc:113,Tc:114,Uc:115,Vc:116,Wc:117,Xc:118,Yc:119,Zc:120,Pc:121,Qc:122,Rc:123,dc:144,jc:145,Xb:173,kc:186,Vb:187,Kc:188,Sb:189,Nd:190,Vd:191,Ic:192,kd:219,Jc:220,Sd:221,Rd:222,Wb:224,ld:901,
Xd:1E3},$a={},ab=($a[J.Zb]=J.kc,$a[J.Yb]=J.Vb,$a[J.Xb]=J.Sb,$a[J.Wb]=J.ab,$a),bb={nb:1,Sa:2,md:3},M={},cb=(M[J.Za]="\b",M[J.pc]="\t",M[J.bc]="\n",M[J.cb]="\r",M[J.oc]=" ",M[J.ZERO]="0",M[J.ONE]="1",M[J.rc]="2",M[J.qc]="3",M[J.ac]="4",M[J.$b]="5",M[J.nc]="6",M[J.lc]="7",M[J.Ub]="8",M[J.cc]="9",M[J.Na]="A",M[J.Ya]="B",M[J.$a]="C",M[J.eb]="D",M[J.E]="E",M[J.fb]="F",M[J.gb]="G",M[J.hb]="H",M[J.ib]="I",M[J.kb]="J",M[J.lb]="K",M[J.mb]="L",M[J.ob]="M",M[J.qb]="N",M[J.rb]="O",M[J.sb]="P",M[J.Q]="Q",M[J.tb]=
"R",M[J.vb]="S",M[J.wb]="T",M[J.xb]="U",M[J.yb]="V",M[J.zb]="W",M[J.Ab]="X",M[J.Bb]="Y",M[J.Ta]="Z",M[J.nb]="Left",M[J.Sa]="Right",M),Ia=["","moz","ms","webkit"],db={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",
cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",
floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",
lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",
mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",
sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},H={Oa:void 0,ta:"PCjs.localStorage"};B.WebIO=F;
function N(a,b,c,d){F.call(this,a==b);this.I=a;this.V=b;O[this.I]||(O[this.I]={});O[this.I][this.V]&&this.w("warning: machine configuration contains multiple '%s' devices\n",this.V);O[this.I][this.V]=this;this.id=this.I+"."+this.V;eb.push(this);this.J=P(this,this.I);this.ready=!0;fb(this,c,d);this.hc={};this.jb=[]}v(N,F);
function fb(a,b,c){b=void 0===b?{}:b;c=void 0===c?[]:c;c=b.overrides||c;if(c.length){var d,e=Ca;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,k=/([^&=]+)=?([^&]*)/g;f=k.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ca=e}d=e;for(var h in d)if(0<=c.indexOf(h)){e=d[h];f=void 0;var m;g=void 0;k=e;var l=10;if(k){l||(l=10);var r=0<k.indexOf(",");r&&(k=k.replace(/,/g,""));var n=m=k.charAt(0);"#"==m?(l=8,m=""):
"$"==m&&(l=16,m="");n!=m?k=k.substr(1):(n=m=k.substr(0,2),"0b"==m&&r||"^B"==m?(l=2,m=""):"0o"==m||"^O"==m?(l=8,m=""):"^D"==m?(l=10,m=""):"0x"==m&&(l=16,m=""),n!=m&&(k=k.substr(2)));n=m=k.slice(-1);"Y"==m||"y"==m?(l=2,m=""):"."==m?(l=10,m=""):"H"==m||"h"==m?(l=16,m=""):"K"==m?m="000":"M"==m?m="000000":"G"==m&&(m="000000000");n!=m&&(k=k.slice(0,-1)+m);n=0;10>=l&&(m=k.match(/(-?[0-9]+)B([0-9]*)$/))&&(k=m[1],n=35-((m[2]||35)&255));(l&&10!=l?16==l?null===k.match(/^-?[0-9a-f]+$/i):8==l?null===k.match(/^-?[0-7]+$/):
2!=l||null===k.match(/^-?[01]+$/):null===k.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(k,l))||(n&&(0>f&&(f+=Math.pow(2,36)),f=0<n?f*Math.pow(2,n):Math.trunc(f/Math.pow(2,-n))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[h]=f;E(a,"overriding "+a.V+" property '"+h+"' with "+e)}}a.s=b;Ga(a,b.bindings);b=void 0===b?{}:b;a.version=2;if(a.version){c="";var t;a.I!=a.V&&(t=P(a,a.I).version)&&t!=a.version&&(c="Machine");c||(t=b.version)&&t>a.version&&(c="Config");c&&(t=a.L("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.ae,a.version,c,t),a.error("%s\n\nClearing your browser's cache may resolve the issue.",t))}}function gb(a,b){var c;try{var d=O[a.I];if(d)for(c in d){var e=d[c];if(e.V!=e.I&&!b(e))return!1}return!0}catch(f){a.w("error while enumerating device '%s': %s\n",c,f.message)}return!1}N.prototype.wa=function(a,b){b=void 0===b?!1:b;if(a){var c=F.prototype.wa.call(this,a,b);if(void 0===c&&b){b=O[this.I];for(var d in b)if(c=b[d].M[a])break;c||(c=null);this.M[a]=c}}return c};
function P(a,b,c){var d=b,e=a.I,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=O[e])&&f[b]||null;if(!b){for(f=0;f<eb.length;f++)if(eb[f].id===d){b=eb[f];break}if(!b&&(void 0===c||c))throw Error(a.L('no "%s" device',d));}return b}function Q(a,b,c){var d=null,e=O[a.I];if(e)for(var f in e)if(e[f].s["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.L("no %s device",b));return d}function hb(a){return a==a.J&&a.ready?gb(a,function(b){return hb(b)}):a.ready}
function ib(a,b){b=void 0===b?a.ready:b;a.ready=b;if(hb(a)){for(;b=a.jb.pop();)b();a!=a.J&&ib(a.J)}}function jb(a,b){if(hb(a))return b(),!0;a.jb.push(b);return!1}
N.prototype.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&I(this,a)&&(void 0===this.ja&&(this.ja=Q(this,"Debugger",!1)),this.J.aa&kb&&(void 0===this.Y&&(this.Y=Q(this,"CPU")),this.Y))?(a=c.shift(),F.prototype.w.call(this,"%#06x: %s.%s\n",this.Y.Ka,this.V,this.L.apply(this,[a].concat(q(c))).trim())):F.prototype.w.call.apply(F.prototype.w,[this,a].concat(q(c)))};function lb(a,b){(a=O[a.I])&&delete a[b]}
N.prototype.Ib=function(a,b){(a=this.hc[a])&&a.set&&a.set(b)};window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]));var O=window?window.PCjs.Machines:{},eb=window?window.PCjs.Components:[],kb=1;K.addr=kb;K.bus=2;K.fault=4;K.memory=8;K.ports=16;K.chips=32;K.kbd=64;K.serial=128;K.misc=256;K.cpu=512;K.mmu=1024;K["int"]=2048;K.trap=4096;K.video=8192;K.monitor=16384;K.screen=32768;K.time=65536;K.timer=131072;
K.event=262144;K.input=524288;K.key=1048576;K.mouse=2097152;K.touch=4194304;K.warn=8388608;K.halt=16777216;B.Device=N;
function mb(a,b,c){N.call(this,a,b,c);this.aa=524288;this.u=this.H=null;this.time=Q(this,"Time");this.J=Q(this,"Machine");this.X=G(this,"drag",!1);this.S=G(this,"scroll",!1);this.W=G(this,"hexagonal",!1);this.h=G(this,"releaseDelay",0,void 0);this.j=!1;a=this.s.map;this.b=this.c=null;if(a)if(a.length)this.b=a;else{this.c={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.c[f]={keys:g,
fe:e,state:0}}}this.K=[];this.N=[];this.g=this.O=null;(a=this.M[nb])&&ob(this,a,this.wa(c.focusBinding,!0),this.s.location);this.ka()}v(mb,N);function pb(a,b){a.H=b}function qb(a,b,c){for(var d=0;d<a.K.length;d++){var e=a.K[d];e.id===b&&e.Gb(b,c)}}
function ob(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.b||a.c){var e={};e.Gc=d[0]||0;e.Hc=d[1]||0;e.va=d[2]||b.clientWidth;e.Ga=d[3]||b.clientHeight;e.Ha=d[4]||1;e.La=d[5]||1;e.wc=d[6]||b.naturalWidth||e.va;e.yc=d[7]||b.naturalHeight||e.Ga;e.Lb=d[8]||0;e.Mb=d[9]||0;e.vc=d[10]||0;e.xc=d[11]||0;a.b?(e.Ja=a.b.length,e.xa=a.b[0].length):(e.xa=e.Ha,e.Ja=e.La,e.Ha=e.La=0);e.Cb=e.va/(e.xa+e.xa*e.Ha)|0;e.Db=e.Ga/(e.Ja+e.Ja*e.La)|0;e.uc=e.Cb*e.Ha|0;e.Eb=e.Db*e.La|0;e.Ba=e.Ma=-1;rb(a,b,e);sb(a,b,e);a.time&&
a.h&&(a.U=tb(a.time,"timerInputRelease",function(){0>e.Ba&&0>e.Ma&&ub(a,-1,-1)}))}if(a.b||a.c)a.time&&a.h&&(a.Z=tb(a.time,"timerKeyRelease",function(){vb(a)})),a.l=0,a.v="",a.m=[],d=b,c&&(d=c,a.g||"BUTTON"!=c.nodeName||(d=document,a.g=c,wb(a,b),a.O=b)),wb(a,d),a.g||(a.g=d)}function xb(a){a.h?yb(a.time,a.Z,a.h):vb(a)}
function wb(a,b){function c(e,f,g){var k=document.activeElement;a.w(1310720,"%s.onKey%s(%d): %5.2f (%s)\n",k.id||k.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.g&&e!=a.g&&e!=a.O?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=zb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=zb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=zb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function rb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.j){var e=a.g;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,Ab,d,c)}});b.addEventListener("mousemove",function(d){a.j||R(a,b,Bb,d,c)});b.addEventListener("mouseup",function(d){a.j||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.j||(0>c.Ba?R(a,b,Bb,d,c):R(a,b,S,d,c))})}
function sb(a,b,c){b.addEventListener("touchstart",function(d){a.S&&(a.j=!0);R(a,b,Ab,d,c)});b.addEventListener("touchmove",function(d){R(a,b,Bb,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function zb(a,b,c,d){if(void 0!=c){var e=ab[b]||b;var f=cb[b];var g=Cb[e];d=d&&d.location==bb.Sa;g&Db&&d&&(g>>=1);g&&(g&Eb&&(c=!(a.a&g)),a.a=c?a.a|g:a.a&~g,qb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=Za.Na&&b<=Za.Ta?a.a&(Fb|Gb)||(a.a|=Gb,qb(a,J.Pa,!0)):b>=Za.Ua&&b<=Za.z&&a.a&Gb&&(a.a&=~Gb,qb(a,J.Pa,!1));if(a.b){if(void 0!=c)return!1;for(e=0;e<a.b.length;e++)for(g=a.b[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.l?16>a.m.length&&a.m.push(b):(a.l=1,a.v=f,ub(a,d,e),qb(a,
f,!0),xb(a)),!0}if(a.c){if(void 0==c)return!0;b=Object.keys(a.c);for(e=0;e<b.length;e++)if(g=b[e],0<=a.c[g].keys.indexOf(f))return qb(a,g,c),a.c[g].state=c?1:0,!0}return!1}function vb(a){1==a.l?(a.l++,qb(a,a.v,!1),a.v="",ub(a,-1,-1),xb(a)):(a.l=0,a.m.length&&zb(a,a.m.shift()))}mb.prototype.ka=function(){this.a=0;this.R=this.T=-1};
function R(a,b,c,d,e){var f=-1,g=-1,k=!1,h=-1,m=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(h=d.targetTouches[0].clientX,m=d.targetTouches[0].clientY,k=1<d.targetTouches.length):(h=d.clientX,m=d.clientY);var l=d.target.getBoundingClientRect();h-=l.left;m-=l.top;h=e.wc/b.offsetWidth*h|0;m=e.yc/b.offsetHeight*m|0;var r=h-e.Gc;var n=m-e.Hc;var t=l=!1;var y=h>=e.Lb&&h<e.Lb+e.vc&&m>=e.Mb&&m<e.Mb+e.xc;if(0<=r&&r<e.va&&0<=n+e.Eb||y)if(k||a.S||d.preventDefault(),0<=r&&r<e.va&&0<=
n&&n<e.Ga){t=!0;d=e.va/e.xa|0;var w=e.Ga/e.Ja|0,A=r/d|0,u=n/w|0;!a.W||u&1||(r-=d>>1,A=r/d|0,A==e.xa-1&&(r=-1));w=u*w+(e.Eb>>1);r-=A*d+(e.uc>>1);n-=w;0<=r&&r<e.Cb&&0<=n&&n<e.Db&&(f=A,g=u,l=!0)}}r=r||0;n=n||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Ab||c==S)for(A=0;A<a.N.length;A++)u=a.N[A],c==S?u.Gb(u.id,!1):(w=n/(b/u.ce|0)|0,(r/(d/u.be|0)|0)==u.qe&&w==u.re&&u.Gb(u.id,!0));if(!k)if(c==Ab)e.Ba=h,e.Ma=m,t?(ub(a,f,g),l&&a.h&&yb(a.time,a.U,a.h,!0)):y&&a.J.ca();else if(c==Bb)0<=e.Ba&&0<=e.Ma&&a.X?ub(a,f,
g):a.H&&a.H(f,g);else if(c==S){if(c=a.h)c=a.time,f=a.U,c=c.a&&0<f&&f<=c.b.length?0<=c.b[f-1].ba:!1;c||ub(a,-1,-1);e.Ba=e.Ma=-1}else E(a,"unrecognized action: "+c)}function ub(a,b,c){if(b!=a.R||c!=a.T)a.R=b,a.T=c,a.u&&a.u(b,c)}var Ab=1,Bb=2,S=3,nb="surface",Fb=3,Db=170,Gb=512,Eb=3584,T={},Cb=(T[J.mc]=2,T[J.Rb]=8,T[J.Nb]=32,T[J.ab]=128,T[J.Pa]=Gb,T[J.dc]=1024,T[J.jc]=2048,T);B.Input=mb;
function Hb(a,b,c){N.call(this,a,b,c,["color","backgroundColor"]);a=this.M[Ib];if(!a)throw Error("LED "+this.s.M[Ib]+" binding for '"+Ib+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Qa=a;this.type=Na(G(this,"type",Jb,Kb),Lb,Mb);this.g=Nb[this.type][0];this.m=Nb[this.type][1];this.width=G(this,"width",this.g,void 0);this.height=G(this,"height",this.m,void 0);this.h=
G(this,"cols",1,void 0);this.K=this.h+G(this,"colsExtra",0,void 0);this.X=G(this,"rows",1,void 0);this.R=this.X+G(this,"rowsExtra",0,void 0);this.$=this.width*this.h;this.T=this.height*this.X;this.l=Ob("black",0);this.c=Pb(this.s.color)||this.l;this.ha=Ob(this.c,1,.25);this.ga=Ob(this.c,1,2);this.j=Pb(this.s.backgroundColor);this.ma=G(this,"fixed",!1);this.ma||(b.style.width="100%",b.style.height="auto");this.fa=G(this,"hexagonal",!1);this.pa=G(this,"highlight",!0);this.S=G(this,"persistent",this.type<
Mb);b.setAttribute("width",this.$.toString());b.setAttribute("height",this.T.toString());b.style.backgroundColor=this.l;a.appendChild(b);this.da=b.getContext("2d");if(this.u=document.createElement("canvas"))this.u.width=this.Z=this.g*this.h,this.u.height=this.v=this.m*this.X,this.b=this.u.getContext("2d");this.qa=(this.R+1)*this.K*4;this.a=Array(this.qa);this.ra=this.h<this.K?4*(this.K-this.h):0;this.N=this.O=!1;this.H=this.W=0;this.U=-1;var d=this;this.time=Q(this,"Time");Qb(this.time,function(e){Rb(d,
!1,e)});Sb(d)}v(Hb,N);function Sb(a){for(var b=a.a,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Mb?Tb:" ";e[f+1]=d.c==d.l?null:d.c;e[f+2]=0;e[f+3]=Ub}a.N=a.O=!0;Rb(a,!0)}function Vb(a){a.j?(a.b.fillStyle=a.j,a.b.fillRect(0,0,a.Z,a.v)):a.b.clearRect(0,0,a.Z,a.v)}
function Rb(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.N||b){if(a.type<Mb){var d=0;if(!a.S||b)Vb(a);else if(a.H){d=a.h-a.H;var e=a.g*d;a.b.drawImage(a.u,a.g*a.H,0,e,a.v,0,0,e,a.v)}for(var f=e=0;f<a.R;f++){for(var g=0;g<a.h;g++){var k=a.a[e],h=a.a[e+1]||a.l,m=a.pa&&e==a.U;if(a.a[e+3]&Ub||m||b){if(g>=d)a:{var l=a,r=k;k=h;var n=g;h=f;var t=m;n=void 0===n?0:n;h=void 0===h?0:h;t=void 0===t?!1:t;var y=0;if(l.fa&&!(h&1)&&(y=l.g>>1,n==l.h-1))break a;if(k&&k!=l.c){t=t?Ob(k,1,2):k;var w=Ob(k,1,.25)}else t=
t?l.ga:l.c,w=l.ha;k=!1;r=r?t:w;t==l.l&&(r=l.j,k=!0);t=n*l.g+y;w=h*l.m;l.S&&(n=n*l.g+y,h*=l.m,l.j?(l.b.fillStyle=l.j,l.b.fillRect(n,h,l.g,l.m)):l.b.clearRect(n,h,l.g,l.m));l.b.fillStyle=r;h=Wb[l.type];3==h.length?(l.b.beginPath(),l.b.arc(t+h[0],w+h[1],h[2],0,2*Math.PI),k?(l.b.globalCompositeOperation="destination-out",l.b.fill(),l.b.globalCompositeOperation="source-over"):l.b.fill()):l.b.fillRect(t+h[0],w+h[1],h[2],h[3])}a.a[e+3]=m?a.a[e+3]|Ub:a.a[e+3]&~Ub}e+=4}e+=a.ra}a.H=0}else{b="";for(d=0;d<a.a.length;d+=
4)b+=a.a[d]||" ",a.a[d+3]&Xb&&(b+=".");Vb(a);for(f=e=d=0;d<b.length;d++){h=b[d];"."==h&&e&&e--;g=a;m=e;l=f;m=void 0===m?0:m;l=void 0===l?0:l;if(h=Yb[h])for(k=0;k<h.length;k++)if(n=g,y=Zb[h[k]]){r=(void 0===m?0:m)*n.g;t=(void 0===l?0:l)*n.m;n.b.fillStyle=n.c;n.b.beginPath();if(3==y.length)n.b.arc(r+y[0],t+y[1],y[2],0,2*Math.PI);else for(w=0;w<y.length;w+=2)w?n.b.lineTo(r+y[w],t+y[w+1]):n.b.moveTo(r+y[w],t+y[w+1]);n.b.closePath();n.b.fill()}if(++e==a.h&&(e=0,++f==a.R))break}}a.da.globalCompositeOperation=
a.j&&a.c!=a.l?"source-over":"copy";a.da.drawImage(a.u,0,0,a.Z,a.v,0,0,a.$,a.T);a.N=!1;a.U=-1}else a.S||a.O||(!c||!a.W||c-a.W>=(1E3/60|0))&&Sb(a);a.O=!1;c&&(a.W=c)}function Pb(a){return(a=a||void 0)&&db[a]||a}
function Ob(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=db[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Hb.prototype.ia=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.c&&c==this.j&&a&&a.length==this.a.length){this.a=a;for(b=0;b<=this.a.length-4;b+=4)this.a[b+1]==this.l&&(this.a[b+1]=null);Rb(this,!0);return!0}return!1};Hb.prototype.la=function(a){this.a&&(a.push(this.c),a.push(this.j),a.push(this.a))};
function $b(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&ac;b=4*(c*a.K+b);if(b<=a.a.length-4){if(a.a[b]!==d||(a.a[b+3]&ac)!==e)a.a[b]=d,a.a[b+3]=a.a[b+3]&~ac|e|Ub,a.N=f=!0;a.U=b;a.O=!0;a.H=0}return f}
var Lb=0,Jb=1,Mb=3,Kb={small:Lb,round:Jb,square:2,digit:Mb},Ib="container",Tb=0,ac=129,Xb=1,Ub=128,bc={},Wb=(bc[Lb]=[4,4,4],bc[Jb]=[16,16,14],bc[2]=[2,2,28,28],bc),Nb=[[8,8],[32,32],[32,32],[96,128]],Zb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Yb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};B.LED=Hb;
function cc(a,b,c){N.call(this,a,b,c);this.ga=G(this,"cyclesMinimum",1E5,void 0);this.ra=G(this,"cyclesMaximum",1E9,void 0);this.ha=Na(G(this,"cyclesPerSecond",1E6,void 0),this.ga,this.ra);this.R=1E3/60;this.gc=G(this,"updatesPerSecond",2,void 0)||2;this.fc=1E3/this.gc;this.qa=0;this.ic=G(this,"timeLock",!0);this.da=this.K=0;this.$=this.l=1;this.pa=this.u=this.ha/1E4/100;this.X=[];this.v=[];this.b=[];this.Z=[];this.ma=this.a=this.W=this.m=!1;this.H=this.g=0;a=Ha("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.R}this.Qa=window[a].bind(window,this.Dc.bind(this),d);this.ec=window[Ha("cancelAnimationFrame")||"clearTimeout"].bind(window);this.U=this.T=this.h=this.c=this.fa=0;dc(this)||ec(this,this.$)}v(cc,N);function Qb(a,b){a.X.push(b)}p=cc.prototype;
p.ua=function(a,b){var c=this;switch(a){case fc:b.onclick=function(){gc(c)&&(c.a?U(c):c.start())};break;case hc:b.onclick=function(){ec(c,c.l<<1);ic(c,jc(c.u))};break;case kc:b.onclick=function(){lc(c)};break;case mc:b.addEventListener("mousedown",function(){c.m=!0}),b.addEventListener("mouseup",function(){dc(c);c.m=!1}),b.addEventListener("mousemove",function(){c.m&&dc(c)}),b.addEventListener("change",function(){c.m=!0;dc(c);c.m=!1})}N.prototype.ua.call(this,a,b)};
function tb(a,b,c){var d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,tc:c,Ia:d,ba:-1});0<=d&&yb(a,e,d);return e}
function nc(a,b,c,d){var e=0,f=a.u,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.w(65536,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.R&&(1<a.l&&(a.l>>=1,a.w(8388608,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.R,a.l)),e=d));a.K=f;a.da=f/a.pa;b=a.da/a.l;a.fa=g/b/60+1E-8;a.w(65536,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.fa,g,b,60);return e}
function oc(a,b){a.T=a.h=b;if(!a.v.length)return a.h=0,a.T;for(var c=0;0<a.h;){if(c<a.v.length){var d=a.v[c++];b=d.Ec.call(d,b)||1}else c=b=0;a.h-=b}return a.T-a.h}function pc(a,b){var c=Date.now();b()&&(a.S+=Date.now()-c)}function qc(a,b){b=void 0===b?a.T-a.h:b;if(!a.a){if(a.c)for(var c=0;c<a.v.length;c++){var d=a.v[c];d.Jb.call(d)}a.c=b}a.c-=b;1>a.c&&(a.W=!0);a.U+=b;a.T=a.h=0;a.a||(a.U=0);return b}
function rc(a,b){b=void 0===b?0:b;if(b){var c=b;a.c+=b}else for(c=a.c,1>c&&(c=a.c+=a.fa),0>c&&(a.w(8388608,"warning: cycle count dropped below zero: %f\n",c),c=a.c=0),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.ba)&&c>d.ba&&(c=d.ba)}return c}function jc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function gc(a){return a.ma?!0:(E(a,"not powered"),!1)}
function sc(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.ba||(d.ba-=b,0>=d.ba&&(d.ba=-1,d.tc(),0<=d.Ia&&yb(a,c,d.Ia)))}}p.ca=function(a){this.ma=a;void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};function lc(a,b){gc(a)&&(a.a?E(a,"already running"):a.g?U(a):tc(a,b))}
p.Dc=function(a){a=void 0===a?Date.now():a;this.H=0;if(this.a){var b=Date.now();if(this.N){var c=b-this.O-this.R;c>this.R&&(this.j+=c,this.w(8388608,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.O=b;this.j||(this.j=b);this.S=0;try{this.W=!1;do sc(this,qc(this,oc(this,rc(this))));while(this.a&&!this.W)}catch(d){E(this,d.message),U(this)}this.N=Date.now();this.S&&(this.j+=this.S,this.O+=this.S);this.O+=nc(this,this.U,this.N-this.j,this.N-this.O);this.N-this.qa>=this.fc&&
this.update();for(b=0;b<this.X.length;b++)this.X[b](a);this.H=this.Qa()}};function ec(a,b){if(void 0!==b){if(1>b||!a.m&&0<a.K&&a.K<.9*a.u)b=a.$;a.l=b;b=a.pa*a.l;a.u!=b&&(a.u=b,ic(a,jc(a.u)))}a.j=a.N=0;a.c=a.U=0;nc(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Ia&&yb(a,b,c.Ia,!0)}}function dc(a){var b=a.M[mc];return b?(ec(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.ra-a.ga)+a.ga)/a.ha|0),!0):!1}
function yb(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.ba)&&(c=Math.ceil(a.ha*(a.ic?a.$:a.da)/1E3*(void 0===c?1E3:c)),a.a&&(c+=qc(a)),b.ba=c)}p.start=function(){if(this.a||this.g)return!1;this.a=!0;this.j=this.N=0;this.update(!0);this.H=this.Qa();return!0};function tc(a,b){b=void 0===b?1:b;a.a||(b&&!a.g&&(a.g=b),a.g&&(a.g--,sc(a,qc(a,oc(a,rc(a,1)))),a.update(!1),a.g&&setTimeout(function(){tc(a,0)},0)))}
function U(a){return a.a?(a.a=!1,qc(a),a.H&&(a.ec(a.H),a.H=0),a.update(!0),!0):a.g?(a.g=0,a.update(!0),!0):!1}p.update=function(a){a&&E(this,this.a?"started with "+jc(this.u)+" target":"stopped");L(this,fc,this.a?"Halt":"Run");L(this,kc,this.g?"Stop":"Step");this.m||(this.w(65536,"getSpeedCurrent(%5.3fhz)\n",1E6*this.K),ic(this,this.a&&this.K?jc(this.K):"Stopped"));for(var b=0;b<this.Z.length;b++){var c=this.Z[b];c.Ac.call(c,void 0!=a)}this.qa=Date.now();this.W=!0};
function ic(a,b){L(a,uc,b);L(a,hc,b)}var fc="run",hc="setSpeed",uc="speed",kc="step",mc="throttle";B.Time=cc;
function vc(a,b,c){N.call(this,a,b,c);this.type="static"==this.s.type?wc:xc;this.l=this.s.addrWidth||16;this.g=Math.pow(2,this.l);this.u=this.g-1|0;this.b=this.s.blockSize||(16<this.l?4096:1024);this.b>this.g&&(this.b=this.g);this.v=this.g/this.b|0;this.c=Math.log2(this.b)|0;this.h=(1<<this.c)-1;this.m=this.s.dataWidth||8;this.a=Array(this.v);this.j=0;a=new V(a,b+"[NONE]",{size:this.b,bus:this.V});for(b=0;b<this.g;b+=this.b)yc(this,b,this.b,W.NONE,a);a=this.j;this.j+=this.type;a&&this.j||(this.ya=
this.Ob,this.za=this.Aa)}v(vc,N);
function yc(a,b,c,d,e){for(var f=b>>>a.c;0<c&&f<a.a.length;){var g=f*a.b,k=a.b-(b-g);k>c&&(k=c);var h=a.a[f];if(b!=g||k!=a.b||h&&h.type!=W.NONE)break;var m=h=void 0,l=b,r=a.l,n=16;r=void 0===r?0:r;h=void 0===h?0:h;var t="",y="",w=-1;n||(n=a.H||10);r&&(w=Math.ceil(r/Math.log2(n)));if(void 0==m)switch(n){case 8:m="0o";break;case 16:m="0x";break;case 10:y=".";default:m=""}isNaN(l)||"number"!=typeof l?(l=void 0,m=y=""):(0>l&&-1<l&&(l=-1),r&&(0>l&&(l+=Math.pow(2,r)),l>=Math.pow(2,r)&&(w=Math.ceil(Math.log(l)/
Math.log(n)))));for(r=h||-1;w--;){r||(t=","+t,r=h);if(void 0==l){if(t="?"+t,0>w)break}else{var A=l%n;l=Math.trunc(l/n);A+=0<=A&&9>=A?48:55;t=String.fromCharCode(A)+t;if(!l&&0>w)break}r--}h=a.V+"["+(m+t+y)+"]";b=e?e.size==a.b?e:new V(a.I,h,{type:d,Fa:b,size:k,bus:a.V}):new V(a.I,h,{type:d,Fa:b,size:k,bus:a.V});a.a[f]=b;b=g+a.b;c-=k;f++}}p=vc.prototype;p.ca=function(){void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};p.ka=function(){};p.Va=function(a){return a&&this.ia(a)?!0:!1};p.Wa=function(a){this.la(a)};
p.ia=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if((this.type==xc||c.type&W.Ea)&&c.ia){var d=a.shift();if(!c.ia(d))return!1}}return!0};p.la=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if((this.type==xc||c.type&W.Ea)&&c.la){var d=[];c.la(d);a.push(d)}}};p.sa=function(a){return this.a[a>>>this.c].sa(a&this.h)};p.Ob=function(a){return this.a[a>>>this.c].ya(a&this.h)};p.Xa=function(a,b){this.a[a>>>this.c].Xa(a&this.h,b)};
p.Aa=function(a,b){this.a[a>>>this.c].za(a&this.h,b)};var wc=0,xc=1;B.Bus=vc;
function V(a,b,c){N.call(this,a,b,c);this.Fa=this.s.addr;this.size=this.s.size;this.type=this.s.type||W.NONE;this.g=(a=this.s.bus)?P(this,a):Q(this,a="Bus");if(!this.g)throw Error(this.L("unable to find bus '%s'",a));this.j=this.g.m;this.u=Math.pow(2,this.j)-1;this.h=this.m=!1;this.values=this.c=null;a=this.pb;b=this.Aa;if(this.g.type==wc){b=this.Fc;if(c=8==this.j)c=P(this,this.I),c=!1!==(c&&c.s&&c.s.ArrayBuffer||this.s.ArrayBuffer);c&&(this.m=!0)}switch(this.type){case W.NONE:this.ya=this.Cc;this.za=
this.Kb;break;case W.ub:this.ya=a;this.za=this.Kb;break;case W.Ea:this.ya=a,this.za=b}zc(this,this.s.values);Ac(this)}v(V,N);function zc(a,b){"string"==typeof b?(ib(a,!1),Oa(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);zc(a,g.values)}catch(k){a.w("error (%s) parsing resource: %s\n",k.message,c)}ib(a,!0)}else a.w("error (%d) loading resource: %s\n",f,c)})):a.s.values=b}
function Ac(a,b){if(a.type>W.NONE&&(a.m?(a.c=new ArrayBuffer(a.size),new DataView(a.c,0,a.size),a.values=new Uint8Array(a.c,0,a.size),new Uint16Array(a.c,0,a.size>>1),new Int32Array(a.c,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}p=V.prototype;
p.ka=function(){if(this.s.values)a:{var a=this.g,b=this.Fa,c=this.size,d=this.s.values,e=0,f=b&a.h;b>>>=a.c;c>d.length&&(c=d.length);for(;0<c&&b<a.a.length;){var g=a.a[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Aa(f++,d[e++]),c--;f=0}}else this.type&W.Ea&&this.values&&this.values.fill(0)};p.Cc=function(){return this.u};p.sa=function(a){return this.values?this.values[a]:0};p.pb=function(a){return this.values[a]};p.Kb=function(){};p.Xa=function(a,b){this.values&&(this.values[a]=b)};
p.Aa=function(a,b){this.values[a]=b};p.Fc=function(a,b){this.values[a]=b;this.h=!0;this.za=this.Aa};p.ia=function(a){var b=a.shift();if(this.V==b){this.h=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}Ac(this,a)}return!0}return!1};p.la=function(a){a.push(this.V);a.push(this.h);a.push(!1);a.push(this.values?ua(this.values):this.values)};var W={NONE:1,ub:2,Ea:4,Ud:14,Yd:12};
B.Memory=V;
function Bc(a,b,c){c.type=W.ub;V.call(this,a,b,c);yc(this.g,this.s.addr,this.s.size,this.s.type,this);jb(this,this.ka.bind(this));this.Y=this.ja=void 0;if(B.LED&&this.M[Ka]){var d=this;this.b=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.l=this.values.length/this.b|0;this.a=new Hb(a,b+"LEDs",{"class":"LED",bindings:{container:Ja(this)},type:Jb,cols:this.b,rows:this.l,color:G(this,"colorROM","green"),backgroundColor:G(this,"backgroundColorROM","black"),persistent:!0}),Sb(this.a);this.v=
new mb(a,b+"Input",{"class":"Input",location:[0,0,this.a.$,this.a.T,this.b,this.l],bindings:{surface:Ja(this)}});this.H=La(this)||"";pb(this.v,function(e,f){if(d.Y){var g=d.H;0<=e&&0<=f&&(e=f*d.b+e,g=Cc(d.Y,d.Fa+e,d.values[e]));L(d,Ma,g)}})}}v(Bc,V);
Bc.prototype.ia=function(a){var b=!0,c=a.shift();if(c&&this.a){var d=c.length;this.a.a.length==d?(this.a.a=c,Rb(this.a,!0)):(this.w("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.w("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};Bc.prototype.ca=function(){void 0===this.Y&&(this.Y=Q(this,"CPU"));void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};
Bc.prototype.pb=function(a){this.a&&$b(this.a,a%this.b,a/this.b|0,1,Ub);return this.values[a]};Bc.prototype.la=function(a){this.a&&(a.push(this.a.a),a.push(this.values))};var Ka="array",Ma="cellDesc";B.ROM=Bc;function Dc(a,b,c){c["class"]="CPU";N.call(this,a,b,c);this.ja=void 0;this.b=this.Ka=0;this.time=Q(this,"Time");this.time.v.push(this);this.time.Z.push(this);this.T=this.j=0}v(Dc,N);p=Dc.prototype;p.abort=function(a){this.b=this.Ka;E(this,a.message);U(this.time)};p.Fb=function(){};
p.Ec=function(a){this.T=this.j=a=void 0===a?0:a;try{this.Fb(a)}catch(b){this.abort(b)}return this.Hb()};p.Jb=function(){this.T-=this.j;this.j=0};p.Hb=function(){return this.T-this.j};function X(a,b,c){N.call(this,a.I,b);this.Y=a;this.name=b;this.f=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.ha[c]=[this,-1];for(var d=0;d<this.f.length;d++)c=this.L("reg%s-%02d",this.name,d),b.push(c),a.ha[c]=[this,d];Ga(a,b)}}v(X,N);p=X.prototype;
p.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.f[f]=a.f[f]+b.f[f]+e,e=0,this.f[f]>=d&&(this.f[f]-=d,e=1);e&&(this.Y.l=!0);Ec(this,c)};p.get=function(){return this.f};function Fc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.f.length;d++)a.f[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.f[d]=b&15,b>>>=4;return a}p.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.f[e]=a.f[e]+d,d=0,this.f[e]>=c&&(this.f[e]-=c,d=1);Ec(a,b)};
p.set=function(a){if(a&&a.length==this.f.length)for(var b=0;b<this.f.length;b++)this.f[b]=a[b]};p.store=function(a){for(var b=0,c=this.f.length;b<c;b++)this.f[b]=a.f[b]};p.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.f[f]=a.f[f]-b.f[f]-e,e=0,0>this.f[f]&&(this.f[f]+=d,e=1);e&&(this.Y.l=!0);Ec(this,c)};p.toString=function(a){a=void 0===a?!1:a;var b=this.V+"=";a&&3>b.length&&(b+=" ");for(var c=this.f.length-1;0<=c;c--)b=a?b+Aa[this.f[c]]:b+(Ba[this.f[c]]+(c%4?"":" "));return b};
function Ec(a,b){a.Y.h=a.f[b[0]];b[0]<b[1]&&(a.Y.h|=a.f[b[0]+1]<<4)}
function Gc(a,b,c){Dc.call(this,a,b,c);this.type=Number.parseInt(G(this,"type","1501").slice(-4),10);this.ha={};this.a=Array(4);for(a=0;4>a;a++)this.a[a]=new X(this,String.fromCharCode(65+a));this.O=this.a[0];this.U=this.a[1];this.pa=this.a[2];this.ra=this.a[3];this.K=Array(8);for(a=0;8>a;a++)this.K[a]=new X(this,"X"+a);this.R=Array(8);for(a=0;8>a;a++)this.R[a]=new X(this,"Y"+a);this.ma=new X(this,"Supp",!0);this.X=new X(this,"Temp",!0);this.H=10;this.l=!1;this.W=this.h=this.u=0;this.g=[-1,-1,-1];
this.qa=P(this,this.s.input);this.qa.u=this.Qb.bind(this);this.c=P(this,this.s.output,!1);this.v=Q(this,"Bus");this.m=Q(this,"ROM");this.fa=this.ga=this.S=void 0;this.da=this.Z=-1;this.N={};this.$=Hc;a=this.zc.bind(this);b=Ua.bb;this.J.Da[b]||(this.J.Da[b]=[]);this.J.Da[b].push(a)}v(Gc,Dc);function Ic(a,b){a.N[b]&&(a.N[b]=!1,E(a,"break on "+Jc[b]),U(a.time))}function Kc(a){a.c&&Sb(a.c);if(a.m){var b=a.m;b.a&&Sb(b.a)}Lc(a,!1)}p=Gc.prototype;
p.Fb=function(a){for(;0<this.j;){if(this.da==this.b){this.da=-1;E(this,"break");U(this.time);break}var b=this.v.ya(this.b);this.b=(this.Ka=this.b)+1&this.v.u;if(void 0==b||!Mc(this,b)){this.b=this.Ka;E(this,"unimplemented opcode");U(this.time);break}this.j-=Nc}if(0>=a){var c=this;pc(this.time,function(){var d=c.m;d.a&&Rb(d.a);c.na(c.toString())})}};p.Jb=function(){this.j=0};p.Hb=function(){return this.T-this.j};
function Mc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.l&&(a.b=a.b&1024|b&1023):(a.push(a.b),a.b=b&2047),a.l=!1,!0;var c;var d=b&Oc;switch(d){case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:d=ad[d];var e=(b&bd)>>cd;var f=(b&dd)>>ed;var g=(b&fd)>>gd;var k=(c=b&hd)?id:jd;b=b>=Wc?16:a.H;switch(f){case 0:case 1:case 2:case 3:var h=a.a[f];break;case 4:h=Fc(a.X,1,d);break;case 5:k=c?kd:ld;break;case 6:h=Fc(a.X,a.h&15,d);break;case 7:h=Fc(a.X,a.h&255,d)}switch(g){case 0:var m=
a.a[e];break;case 1:m=4>f?a.a[f]:void 0;break;case 2:m=5>f?a.ma:5==f?a.a[e]:void 0;break;case 3:if(c)a.a[e].move(h,d,b);else{a=a.O;e=h;b=d[0];for(h=d[1];b<=h;b++)m=a.f[b],a.f[b]=e.f[b],e.f[b]=m;Ec(e,d)}return!0}if(!m)break;switch(k){case jd:m.add(a.a[e],h,d,b);break;case id:m.sub(a.a[e],h,d,b);break;case ld:b=m;a=a.a[e];e=d[1];for(h=d[0];e>h;e--)b.f[e]=a.f[e-1];b.f[e]=0;Ec(b,d);break;case kd:b=m;a=a.a[e];e=d[0];for(h=d[1];e<h;e++)b.f[e]=a.f[e+1];b.f[e]=0;Ec(b,d)}return!0;case md:e=(b&nd)>>od;d=(b&
pd)>>qd;h=1<<((b&rd)>>sd);if(!d)break;d+=12;switch(b&td){case ud:a.a[e].f[d]|=h;break;case vd:a.a[e].f[d]&=~h;break;case wd:a.a[e].f[d]&h&&(a.l=!0);break;case xd:a.a[e].f[d]^=h}return!0;case yd:switch(b&zd){case Ad:a.O.store(a.R[a.u]);break;case Bd:a.u=b>>4&7;break;case Cd:a.b=a.h;break;case Dd:a.l=!1;d=a.g[0];e=0;for(b=a.g.length-1;e<b;)a.g[e]=a.g[++e];a.g[e]=-1;a.b=d;break;case Ed:a.K[a.u].store(a.O);break;case Fd:a.O.store(a.K[a.u]);break;case Gd:a.R[a.u].store(a.O);break;case Hd:Ic(a,"o");if(a.c){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.U.f[e]&8?b=" ":a.U.f[e]&1?b="-":b=Aa[a.O.f[e]],$b(a.c,d,0,b,a.U.f[e]&2?Xb:0)&&Ic(a,"om");Lc(a)}a.j-=31*Nc;a.W&&(a.h=a.W,a.l=!0,Ic(a,"i"));break;case Id:a.H=10;break;case Jd:a.H=16;break;case Kd:a.u=a.h&7;break;default:return!1}return!0}return!1}
p.ia=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return E(this,"invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.w("saved state version mismatch: %3.2f\n",c),!1;try{this.a.forEach(function(d){return d.set(b.shift())}),this.K.forEach(function(d){return d.set(b.shift())}),this.R.forEach(function(d){return d.set(b.shift())}),this.ma.set(b.shift()),this.X.set(b.shift()),this.H=b.shift(),this.l=b.shift(),this.u=b.shift(),this.h=b.shift(),this.b=b.shift(),this.g=b.shift(),this.W=
b.shift()}catch(d){return E(this,"CPU state error: "+d.message),!1}return(a=a.stateROM||a[1])&&this.m&&!this.m.ia(a)?!1:!0};
p.zc=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,k=3;k<a.length;k++)d.push(Number.parseInt(a[k],16));this.$=Hc;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Jc)c=Jc[f],b+="break on "+c+" (b"+f+"): "+(this.N[f]||!1)+"\n";break}(c=Jc[f])?(this.N[f]=!this.N[f],b="break on "+c+" (b"+f+"): "+this.N[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.v.sa(f);if(void 0==
a)break;this.v.Xa(f,d[g]);b+=this.L("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.L("%d locations updated\n",c);break;case "g":this.time.start()?this.da=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.$=Ld);g=Number.parseInt(a[2],10)||1;lc(this.time,g);break;case "r":"c"==e[1]&&(this.$=Ld);this.Ib(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.Z?this.Z:this.b;g--;){c=this.m&&this.v.sa(f);if(void 0==
c)break;b+=Cc(this,f++,c)}this.Z=f;break;case "?":b="additional commands:\n";Md.forEach(function(h){b+=h+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};p.Qb=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.W=c};p.Va=function(a){return a&&this.ia(a)?!0:!1};p.ca=function(a){a?this.time.start():(U(this.time),Kc(this))};p.ka=function(){E(this,"reset");this.b=0;Kc(this);this.time.a||this.na(this.toString())};p.Wa=function(a){this.la(a)};
p.Ac=function(a){for(var b in this.M){var c=this.ha[b];if(c){var d=c[0];c=c[1];L(this,b,0>c?d.toString():Aa[d.f[c]])}}a&&!this.time.a&&(a=this.m,a.a&&Rb(a.a),this.na(this.toString()))};p.push=function(a){for(var b=this.g.length-1;0<b;)this.g[b]=this.g[--b];this.g[0]=a};
p.la=function(a){var b=[],c=[];b.push(2);this.a.forEach(function(d){return b.push(d.get())});this.K.forEach(function(d){return b.push(d.get())});this.R.forEach(function(d){return b.push(d.get())});b.push(this.ma.get());b.push(this.X.get());b.push(this.H);b.push(this.l);b.push(this.u);b.push(this.h);b.push(this.b);b.push(this.g);b.push(this.W);this.m&&this.m.la(c);a.push(b);a.push(c)};p.Ib=function(a,b){if(a&&0<=b)switch(a){case "pc":this.b=b;break;default:E(this,"unrecognized register: "+a)}};
function Cc(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.L("%#06x",f);else if(0<=c){var g=c&Oc;var k;switch(g){case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:f="";e=ad[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&bd)>>cd;var h=(c&dd)>>ed;var m=(c&fd)>>gd;var l=c&hd;e="LOAD";var r=k="?";var n=l?5==h?">>":"-":5==h?"<<":"+";switch(m){case 0:k=
Y[g];break;case 1:4>h&&(k=Y[h]);break;case 2:6>h&&(k="NUL");break;case 3:l?(e="MOVE",k=Y[g],r=Y[h]):(e="XCHG",g||(k="A"),4>h&&(r=Y[h])),h=-1}switch(h){case 0:case 1:case 2:case 3:r=Y[g]+n+Y[h];break;case 4:case 5:r=Y[g]+n+"1";break;case 6:r=Y[g]+n+"R5L";break;case 7:r=Y[g]+n+"R5"}f=k+","+r+","+f;break;case md:switch(c&td){case ud:e="SET";break;case vd:e="CLR";break;case wd:e="TST";break;case xd:e="NOT"}f=a.a[(c&nd)>>od].name;g=(c&pd)>>qd;f+="["+(g?g+12:"?")+":"+((c&rd)>>sd)+"]";break;case yd:switch(c&
zd){case Ad:e="STORE";f="A,Y[RAB]";break;case Bd:e="STORE";f="RAB,"+((c&112)>>4);break;case Cd:e="BR";f="R5";break;case Dd:e="RET";break;case Ed:e="STORE";f="X[RAB],A";break;case Fd:e="STORE";f="A,X[RAB]";break;case Gd:e="STORE";f="Y[RAB],A";break;case Hd:e="DISP";break;case Id:e="BCDS";break;case Jd:e="BCDR";break;case Kd:e="STORE",f="RAB,R5L"}}}return a.L(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
p.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.$){this.m&&(d+=Cc(this,this.b,this.v.sa(this.b),!0));d+="  ";b=0;for(a=this.a.length;b<a;b++)d+=this.a[b].toString()+" ";d+="\n ";d+=" COND="+(this.l?1:0);d+=" BASE="+this.H;d+=" R5="+this.L("%02X",this.h);d+=" RAB="+this.u+" ST=";this.g.forEach(function(f){d+=c.L("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.a);0<=a.indexOf("a")&&(d+=this.toString(a,this.K),d+=this.toString(a,this.R));d+="COND="+(this.l?1:0);d+=" BASE="+this.H;d+=" R5="+this.L("%#04x",this.h);d+=" RAB="+this.u+" ";this.g.forEach(function(f,g){d+=c.L("ST%d=%#06x ",g,f&65535)});this.m&&(d+="\n"+Cc(this,this.b,this.v.sa(this.b)));this.Z=this.b;return d};
function Lc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Nd?!!(a.pa.f[14]&8):!!(a.U.f[15]&4));if(a.fa!==d){if(c=a.M["2nd"])c.style.opacity=d?"1":"0",void 0===a.fa&&a.c&&(c.style.color=a.c.color);a.fa=d}d=b&&(a.type==Nd?!!(a.U.f[15]&4):!!(a.ra.f[15]&8));if(a.ga!==d){if(c=a.M.INV)c.style.opacity=d?"1":"0",void 0===a.ga&&a.c&&(c.style.color=a.c.color);a.ga=d}c=a.type==Nd?a.K[4].f[15]>>2:a.pa.f[15];b=b?c?1==c?Od:Pd:Qd:Rd;if(a.S!==b){if(c=a.M.Deg)c.style.opacity=b==Qd?"1":"0",void 0===a.S&&a.c&&(c.style.color=
a.c.color);if(c=a.M.Rad)c.style.opacity=b==Od?"1":"0",void 0===a.S&&a.c&&(c.style.color=a.c.color);if(c=a.M.Grad)c.style.opacity=b==Pd?"1":"0",void 0===a.S&&a.c&&(c.style.color=a.c.color);a.S=b}}
var Oc=3840,Pc=0,Qc=256,Rc=512,Sc=768,Tc=1024,Uc=1280,Vc=1792,Wc=2048,Xc=2304,Yc=2560,md=3072,Zc=3328,yd=3584,$c=3840,bd=192,cd=6,dd=56,ed=3,fd=6,gd=1,hd=1,td=3,ud=0,vd=1,wd=2,xd=3,nd=192,od=6,pd=48,qd=4,rd=12,sd=2,zd=15,Ad=0,Bd=1,Cd=2,Dd=3,Ed=4,Fd=5,Gd=6,Hd=7,Id=8,Jd=9,Kd=10,Z={},ad=(Z[Pc]=[12,12],Z[Qc]=[0,15],Z[Rc]=[2,12],Z[Sc]=[0,12],Z[Tc]=[2,2],Z[Uc]=[0,1],Z[Vc]=[0,13],Z[Wc]=[14,14],Z[Xc]=[13,15],Z[Yc]=[14,15],Z[Zc]=[13,13],Z[$c]=[15,15],Z),Nc=128,jd=0,id=1,ld=2,kd=3,Nd=1501,Rd=0,Qd=1,Od=2,Pd=
3,Jc={i:"input",o:"output",om:"output modification"},Hc=0,Ld=1,Y="A B C D 1 ? R5L R5".split(" "),Md="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");B.CPU1500=Gc;
function Sd(a,b,c){N.call(this,a,a);var d=this;this.c=!1;this.l=c;this.b="";this.j=this.h=!1;ib(this,!1);this.aa=0;b=b.trim();"{"==b[0]?Td(this,b):(this.b=b,Oa(this.b,function(e,f,g,k){4==g&&(!k&&f?(Td(d,f),Ud(d)):d.w("error (%d) loading configuration: %s\n",k,e))}));window.addEventListener("load",function(){d.j=!0;Ud(d)});window.addEventListener(Qa("iOS")?"pagehide":Qa("Opera")?"unload":"beforeunload",function(){Vd(d)});window.addEventListener("pageshow",function(){d.c||d.ca(!0)})}v(Sd,N);
Sd.prototype.ua=function(a,b){var c=this;switch(a){case Wd:b.onclick=function(){c.ca()};break;case Xd:b.onclick=function(){c.ka()}}N.prototype.ua.call(this,a,b)};
function Ud(a){var b=!0;if(a.h&&a.j){for(var c in a.a){var d=void 0,e=a.a[c];try{d=e["class"],B[d]?"Machine"==d?(a.w("PCjs %s v%3.2f\n%s\n",e.name,2,Yd),a.b&&a.w("Configuration: %s\n",a.b)):new B[d](a.I,c,e):a.w('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.w('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),lb(a,c)}}if(a.g){var f=Ra(a);gb(a,function(g){return g.Va&&!g.Va(f)?(g.w('unable to restore state for device "%s"\n',g.V),!1):!0})}ib(a,!0);jb(a,a.ca.bind(a,b))||a.w("machine %s not ready to power, waiting for device(s)\n",
a.I)}}function Td(a,b){try{a.a=JSON.parse(b);var c=a.a[a.I];if(!c){c=a.a[wa(a.b)];if(!c)throw Error("configuration missing machine ID");a.a[a.I]=c}fb(a,c,["autoSave","autoStart"]);a.g=!1!==a.s.autoSave;a.m=!1!==a.s.autoStart;if(a.l){var d=eval("("+a.l+")"),e;for(e in d)a.s[e]=d[e]}a.h=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),E(a,"machine '"+a.I+"' initialization error: "+c)}}
Sd.prototype.ca=function(a){a=void 0===a?!this.c:a;if(hb(this)){var b=this;a&&E(this,"power on");gb(this,function(c){c.ca&&c!=b&&("CPU"!=c.s["class"]||b.m||hb(b)?c.ca(a):c.time.update(!0));return!0});(this.c=a)||E(this,"power off")}};Sd.prototype.ka=function(){if(hb(this)){var a=this;gb(this,function(b){b.ka&&b!=a&&b.ka();return!0});E(this,"reset")}};function Vd(a){if(a.g){var b=[];gb(a,function(c){c.Wa&&c.Wa(b);return!0});Ya(a,b)}a.ca(!1)}var Wd="power",Xd="reset",Yd="Copyright \u00a9 2012-2020 Jeff Parsons <Jeff@pcjs.org>";
window.TMS1500=function(a,b,c){var d=new Sd(a,b,c);window.command=function(e){return Sa(d,e)};return d};B.Machine=Sd;})()

//# sourceMappingURL=ti57.js.map
