(function(){/*
 https://www.pcjs.org/machines/shared/lib/dumpapi.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/shared/lib/reportapi.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/shared/lib/strlib.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/shared/lib/weblib.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/shared/lib/embed.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/shared/lib/defines.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/shared/lib/usrlib.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/shared/lib/component.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/defines.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/panel.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/cpu.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/rom.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/ram.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/keyboard.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/video.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/serial.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/disk.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/debugger.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/lib/computer.js (C) 2012-2020 Jeff Parsons
*/
var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ea;
if("function"==typeof Object.setPrototypeOf)ea=Object.setPrototypeOf;else{var fa;a:{var ha={Mb:!0},ia={};try{ia.__proto__=ha;fa=ia.Mb;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function u(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function la(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var ma=la(this);function na(a,b){if(b){var c=ma;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}
na("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});function oa(){}
function v(a,b,c){b?9<b&&(b=9):(b=Math.abs(a),b=65535>=b?4:4294967295>=b?8:9);c=c?"0x":"";var d=void 0===d?0:d;var e="";isNaN(a)||"number"!=typeof a?a=null:(0>a&&-1<a&&(a=-1),0>a&&(a+=Math.pow(16,b)),a>=Math.pow(16,b)&&(b=Math.ceil(Math.log(a)/Math.log(16))));for(var g=d||-1;0<b--;){g||(e=","+e,g=d);if(null==a)e="?"+e;else{var h=a%16;h+=0<=h&&9>=h?48:55;e=String.fromCharCode(h)+e;a=Math.trunc(a/16)}g--}return(void 0===c?"":c)+e}function w(a){return v(a,2,!0)}function z(a){return v(a,4,!0)}
function pa(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));return b}function qa(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase());return b}function ra(a){return a.replace(/[&<>"'$]/g,function(b){return sa[b]})}
function ta(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,b instanceof Array?b:ca(ba(b))))}
function ua(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(!c||!c.length)return a;d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),g=0,h;for(h=0;h<e.length-6;h+=6){d+=e[h];var l=e[h+5],k="ACDFHIMNSTWYbdfjcsoXx%".indexOf(l);if(0>k)d+="%"+e[h+1]+e[h+2]+e[h+3]+e[h+4]+l;else{if(g<c.length){var m=c[g];"%"!=l&&g++}else m=c[c.length-1];var n=e[h+1],p=0<=n.indexOf("#"),t=0<=n.indexOf("0"),q=e[h+2];"*"==q?(q=m,m=g<c.length?c[g++]:c[c.length-1]):q=+q||0;var r=
e[h+3];r=r?+r.substr(1):-1;var D=null,y=0,x="";k=12>k&&"object"!=typeof m?ta(m):m;switch(l){case "C":m=p?"#":"";d+=isNaN(k.getTime())?void 0:ua(ua("%%%sW, %%%sF %%%sD, %%%sY",m),k);continue;case "D":m=p?k.getUTCDate():k.getDate();l="d";break;case "A":case "H":case "I":m=p?k.getUTCHours():k.getHours();"A"==l?(m=12>m?"am":"pm",l="s"):("I"==l&&(m=m?12<m?m-12:m:12),l="d");break;case "F":case "M":m=p?k.getUTCMonth():k.getMonth();"F"==l?(m=va[m],l="s"):(m++,l="d");break;case "N":m=p?k.getUTCMinutes():k.getMinutes();
l="d";break;case "S":m=p?k.getUTCSeconds():k.getSeconds();l="d";break;case "T":m=p?"#":"";d+=isNaN(k.getTime())?void 0:ua(ua("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",m),k);continue;case "W":m=wa[p?k.getUTCDay():k.getDay()];l="s";break;case "Y":m=p?k.getUTCFullYear():k.getFullYear(),0<r&&(m%=Math.pow(10,r),r=-1),l="d"}switch(l){case "b":d+=m?"true":"false";break;case "d":m=Math.trunc(m),0<=r&&(t=!0,q<r&&(q=r),r=-1);case "f":l=m+"";0<=r&&(l=m.toFixed(r));l.length<q&&(t?(0>m&&(q--,l=l.substr(1)),
l=("0000000000"+l).slice(-q),0>m&&(l="-"+l)):l=("          "+l).slice(-q));d+=l;break;case "j":d+=JSON.stringify(m,null,q||void 0);break;case "c":m="string"==typeof m?m[0]:String.fromCharCode(m);case "s":if(void 0!=m)for("string"!=typeof m&&(m=m.toString()),0<=r&&(m=m.substr(0,r));m.length<q;)m=0<=n.indexOf("-")?m+" ":" "+m;d+=m;break;case "o":y=8,p&&(x="0");case "X":D=xa;case "x":l="";y||(y=16);!x&&p&&(x="0x");D||(D=ya);m=Math.trunc(m);0<=r&&(t=!0,q<r&&(q=r));t&&!q&&(q=Math.abs(m),q=255>=q?2:65535>=
q?4:4294967295>=q?8:9,q+=x.length);q-=x.length;do p=m&y-1,m>>>=16==y?4:3,t||!l||p||m?l=D[p]+l:(x&&(l=x+l,x=""),0<q&&(l=" "+l));while(0<--q||m);d+=x+l;break;case "%":d+="%";break;default:d+="(unimplemented printf type %"+l+")"}}}return d+=e[h]}
var sa={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;",$:"&dollar;"},ya="0123456789abcdef",xa="0123456789ABCDEF",wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" "),za=Date.now||function(){return+new Date};
function A(a,b){var c=null,d=!0;c=void 0===c?"text":c;d=void 0===d?!1:d;var e=0,g=null;if("object"==typeof resources&&(g=resources[a]))b&&b(a,g,e);else if(d&&"function"==typeof resources)resources(a,function(p,t){b&&b(a,p,t)});else{a=a.replace(/^\/(diskettes|gamedisks|harddisks|decdisks|pcsig[0-9a-z]*-disks|private)\//,"https://$1.pcjs.org/").replace(/^\/disks-cds\/([^/]*)\//,"https://$1.pcjs.org/");var h=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP"),
l=!1,k="string"===typeof h.responseType,m=function(){if(4!==h.readyState)return null;try{g=l?h.response:h.responseText}catch(t){}if(null==g||200!=h.status&&(h.status||!g.length||"file:"!=(window?window.location.protocol:"file:")))if(e=h.status||-1,!h.status&&!Aa){var p=a.match(/(^https?:\/\/[^/]+)(.*)/);p&&(Aa=!0,B("PCjs was unable to perform a cross-origin resource request to '"+p[1]+"'.\n\nIf you're running an ad blocker, try adding '"+Ba()+"' to your whitelist (or find a smarter ad blocker)."))}b&&
b(a,g,e);return[g,e]};d&&(h.onreadystatechange=m);if(c&&"object"==typeof c){k="";for(var n in c)c.hasOwnProperty(n)&&(k&&(k+="&"),k+=n+"="+encodeURIComponent(c[n]));k=k.replace(/%20/g,"+");h.open("POST",a,d);h.setRequestHeader("Content-type","application/x-www-form-urlencoded");h.send(k)}else h.open("GET",a,d),"arraybuffer"==c&&(k?(l=!0,h.responseType=c):h.overrideMimeType("text/plain; charset=x-user-defined")),h.send();d||(h.readyState=4,m())}}
function Ba(){return window?window.location.protocol+"//"+window.location.host:"https://www.pcjs.org"}function C(a){if(window){var b=window?window.navigator.userAgent:"";return"iOS"==a&&!!b.match(/(iPod|iPhone|iPad)/)&&!!b.match(/AppleWebKit/)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ca(){var a,b=Da("mobile");if(b)return"true"==b;if(C("Mobi")){if(!a)return!0;(b="!"==a[0])&&(a=a.substr(1));return C(a)!=b}return!1}
function Da(a){if(!Ea){var b,c={};if(window){b||(b=window.location.search.substr(1));for(var d,e=/\+/g,g=/([^&=]+)=?([^&]*)/g;d=g.exec(b);)c[decodeURIComponent(d[1].replace(e," "))]=decodeURIComponent(d[2].replace(e," "))}Ea=c}return Ea[a]||Ea[a.toLowerCase()]}function Fa(a,b,c){function d(){--a;0<=a&&(b()||(a=0));0<a?setTimeout(d,0):c()}d()}
function Ga(a,b){function c(){b(100===d)&&(e=setTimeout(c,d),d=100)}var d=0,e=null,g=!1;a.onmousedown=function(){g||e||(d=500,c())};a.ontouchstart=function(){e||(d=500,c())};a.onmouseup=a.onmouseout=function(){e&&(clearTimeout(e),e=null)};a.ontouchend=a.ontouchcancel=function(){e&&(clearTimeout(e),e=null);g=!0}}function Ha(a,b){if(window){var c=window[a];window[a]="function"!==typeof c?b:function(){c&&c();b()}}}function E(a){F.init.push(a)}
function Ia(a){if(Ja)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){B("An unexpected error occurred: "+c.message+"\n\nIf it happens again, please send the URL to support@pcjs.org. Thanks.")}}function Ka(a){!Ja&&a?(Ja=!0,La&&Ma("init"),Na&&Ma("show")):Ja=a}function Ma(a){F[a]&&Ia(F[a])}var Ea=null,F={init:[],show:[],exit:[]},La=!1,Na=!1,Ja=!0,Aa=!1;Ha("onload",function(){La=!0;Ia(F.init)});Ha("onpageshow",function(){Na=!0;Ia(F.show)});
Ha(C("iOS")?"onpagehide":C("Opera")?"onunload":"onbeforeunload",function(){Ia(F.exit)});function G(a,b,c){this.type=a;b||(b={id:"",name:""});this.name=b.name;this.id=this.id=b.id||"";this.exports={};this.H=this.bindings={};a=this.id.indexOf(".");0>a?this.eb="PCjs":this.eb=this.id.substr(0,a);this.D={ready:!1,La:!1,ab:!1,Ue:!1,O:!1,Ne:!1,error:!1};this.cb=null;this.D.error=!1;this.ma=c||0;this.v=this.u=this.V=null;H.push(this)}function B(a){window&&window.alert(a)}
function Oa(a,b){a.value+=b;b=a.value;8192<b.length&&(a.value=b.substr(b.length-4096));a.scrollTop=a.scrollHeight}function I(a,b){b=J(b.parentNode,"c1p-control");for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,e=0;e<d.length;e++){var g=d[e];if(1===g.nodeType){var h=g.getAttribute("class");if(h)for(var l=h.split(" "),k=0;k<l.length;k++)switch(h=l[k],h){case "c1p-binding":(h=K(g))&&void 0!==h.binding&&a.T(h.type,h.binding,g,h.value),k=l.length}}}}
function Pa(a,b){if(void 0!==a){var c;b&&0<(c=b.indexOf("."))&&(a=b.substr(0,c+1)+a);for(c=0;c<H.length;c++)if(H[c].id===a)return H[c]}return null}function Qa(a,b){var c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");for(d=0;d<H.length;d++)if(c)c==H[d]&&(c=null);else if(!(a!=H[d].type||b&&H[d].id.indexOf(b)))return H[d]}return null}function K(a){var b=null;if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(c){B(c.message+" ("+a+")")}return b}
function J(a,b,c){c&&(b+="-"+c+"-object");if(a.getElementsByClassName)return a.getElementsByClassName(b);var d;c=[];a=a.getElementsByTagName("*");var e=new RegExp("(^| )"+b+"( |$)");b=0;for(d=a.length;b<d;b++)e.test(a[b].className)&&c.push(a[b]);return c}
function Ra(a){for(var b=!0,c=Sa[a];c&&c.length;){var d=c.splice(0,1)[0],e=d[0],g=null;0<=Ua.indexOf(e)&&(g=function(){return function(){Ra(a)}}());var h=Va[e];if(h)if(!g)b=h(d[1],d[2],d[3]);else{if(!h(g,d[1],d[2],d[3]))break}else{b=!1;var l=Qa(d[1],a);if(l)if(h=Wa[e])b=h(l,d[2],d[3]);else{var k=l.exports;if(k&&(h=k[e]))if(b=!0,!g)b=h.call(l,d[2],d[3]);else if(!h.call(l,g,d[2],d[3]))break}}if(!b){B("Script error: '"+e+"' command "+(h?" failed":" not recognized"));break}}c&&!c.length&&delete Sa[a];
return b}f=G.prototype;f.toString=function(){return this.name?this.name:this.id||this.type};function Xa(a){var b=1;a.eb&&(a=a.eb.match(/\d+/),null!==a&&(b=parseInt(a[0],10)));return b}
f.T=function(a,b,c){switch(b){case "clear":return this.H[b]||(this.H[b]=c,c.onclick=function(d){return function(){d.H.print&&(d.H.print.value="")}}(this)),!0;case "print":return this.H[b]||(this.H[b]=c,this.Wa=function(d){this.l(d,this.type);return!0},c.value="",this.print=function(d){return function(e){Oa(d,e)}}(c),this.l=function(d,e){return function(g,h){g||(g="");if(h!=Ya||"..."!=g.slice(-3))h&&(g=h+": "+g),Oa(e,g+"\n");else{h=e.value;var l=h.lastIndexOf(g);h=0>l?h+(g+"\n"):h.substr(0,l)+(g+".")+
h.substr(l+g.length);8192<h.length&&(h=h.substr(h.length-4096));e.value=h;e.scrollTop=e.scrollHeight}}}(this,c)),!0;default:return!1}};f.log=function(){};f.print=function(){};f.l=function(){};f.status=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.l(this.type+": "+ua.apply(oa,[a].concat(c instanceof Array?c:ca(ba(c)))))};
f.Wa=function(a,b,c){if(!b){var d=Qa("Computer",this.id);if(d&&d.D.Ne)return console.log("ignoring notice during unload: "+a),!1}c=c||this.type;b||B((c?c+": ":"")+a);return!0};function Za(a,b){a.D.error=!0;a.Wa(b)}function M(a,b){b&&(a.D.ready?b():a.cb=b);return a.D.ready}f.U=function(){if(!this.D.error&&(this.D.ready=!0,this.D.ready)){var a=this.cb;this.cb=null;a&&a()}};function $a(a,b){a.D.La&&(b?a.D.ab=!0:void 0===b&&a.l(a.toString()+" busy"));return a.D.La}
function N(a,b){if(a.D.ab)return a.D.La=!1,a.D.ab=!1;if(a.D.error)return a.l(a.toString()+" error"),!1;a.D.La=b;return a.D.La}function O(a,b){b=void 0===b?0:b;if(a.v){b%2&&b--;b=b||a.ma;var c;if(!(c=-1==(b|1))){a=a.v.ma;c=Math.pow(2,32);var d=b/c|0;c=(a&b)==(b|0)&&((a/c|0)&d)==d}if(c)return!0}return!1}var Ya="progress";
window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]),window.PCjs.Commands||(window.PCjs.Commands={}));
var ab=window?window.PCjs.Machines:{},H=window?window.PCjs.Components:[],Sa=window?window.PCjs.Commands:{},Ua=["hold","sleep","wait"],Va={alert:function(a){B(a);return!0},sleep:function(a,b){setTimeout(a,+b);return!1}},Wa={select:function(a,b,c){var d=!1;if(a=a.bindings[b])for(b=0;b<a.options.length;b++)if(a.options[b].textContent==c){a.selectedIndex!=b&&(a.selectedIndex=b);d=!0;break}return d}};
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});
Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return e.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),e=this;c.prototype=this.prototype;b.prototype=new c;return b});function bb(a){G.call(this,"C1PPanel",a);this.D.O=!1}u(bb,G);
bb.prototype.T=function(a,b,c,d){return this.V&&this.V.T(a,b,c,d)||this.u&&this.u.T(a,b,c,d)||this.b&&this.b.T(a,b,c,d)||this.v&&this.v.T(a,b,c,d)?!0:G.prototype.T.call(this,a,b,c,d)};bb.prototype.ja=function(a,b){a&&!this.D.O&&(this.D.O=!0,this.V=b,this.u=P(b,"cpu"),this.b=P(b,"keyboard"),this.v=P(b,"debugger"),cb())};function cb(){for(var a=!1,b=J(document,"c1p","panel"),c=0;c<b.length;c++){var d=b[c],e=K(d),g=Pa(e.id);g||(a=!0,g=new bb(e));I(g,d);a&&g.U()}}E(cb);
function db(a){G.call(this,"C1PCPU",a);eb(this);this.D.O=!1;this.D.oa=!1;var b=Da("autoStart");"true"==b||"false"==b?this.ta=JSON.parse(b):this.ta=a.autoStart;this.Qa=0;this.Pe=1;this.Qe=2;this.speed=this.Qa;this.Fa=30;this.Ea=5;this.Ja=8;this.Ua=["Slow","Fast","Max"];this.ib=["(1Mhz)","(up to "+this.Ja+"Mhz)","(unlimited)"];this.N=[];this.I=[];this.qa=65536;this.ra=0;this.fa=65536;this.ga=0;this.Pa=32;this.$a=2;this.Oe=1;this.m=[this.tc,this.Nd,this.Ee,this.o,this.o,this.Pd,this.jc,this.o,this.Sd,
this.Md,this.ic,this.o,this.o,this.Jd,this.gc,this.o,this.sc,this.Od,this.o,this.o,this.o,this.Qd,this.kc,this.o,this.wc,this.Ld,this.o,this.o,this.o,this.Kd,this.hc,this.o,this.kd,this.cc,this.o,this.o,this.pc,this.ec,this.Yd,this.o,this.Ud,this.bc,this.Xd,this.o,this.oc,this.Zb,this.Vd,this.o,this.qc,this.dc,this.o,this.o,this.o,this.fc,this.Zd,this.o,this.oe,this.ac,this.o,this.o,this.o,this.$b,this.Wd,this.o,this.ee,this.Yc,this.o,this.o,this.o,this.$c,this.Gd,this.o,this.Rd,this.Xc,this.Fd,this.o,
this.jd,this.Uc,this.Dd,this.o,this.uc,this.Zc,this.o,this.o,this.o,this.ad,this.Hd,this.o,this.yc,this.Wc,this.o,this.o,this.o,this.Vc,this.Ed,this.o,this.fe,this.sb,this.o,this.o,this.o,this.ub,this.ce,this.o,this.Td,this.rb,this.be,this.o,this.hd,this.ob,this.$d,this.o,this.vc,this.tb,this.o,this.o,this.o,this.vb,this.de,this.o,this.qe,this.qb,this.o,this.o,this.o,this.pb,this.ae,this.o,this.o,this.ue,this.o,this.o,this.Ce,this.we,this.ze,this.o,this.Tc,this.o,this.Ie,this.o,this.Be,this.re,this.ye,
this.o,this.lc,this.ve,this.o,this.o,this.De,this.xe,this.Ae,this.o,this.Ke,this.te,this.Je,this.o,this.o,this.se,this.o,this.o,this.Ad,this.pd,this.vd,this.o,this.Bd,this.rd,this.wd,this.o,this.Ge,this.od,this.Fe,this.o,this.yd,this.ld,this.td,this.o,this.mc,this.qd,this.o,this.o,this.Cd,this.sd,this.xd,this.o,this.zc,this.nd,this.He,this.o,this.zd,this.md,this.ud,this.o,this.Mc,this.Ec,this.o,this.o,this.Nc,this.Gc,this.Qc,this.o,this.gd,this.Dc,this.Sc,this.o,this.Lc,this.Ac,this.Oc,this.o,this.rc,
this.Fc,this.o,this.o,this.o,this.Hc,this.Rc,this.o,this.xc,this.Cc,this.o,this.o,this.o,this.Bc,this.Pc,this.o,this.Jc,this.Ab,this.o,this.o,this.Kc,this.Cb,this.dd,this.o,this.fd,this.zb,this.Id,this.o,this.Ic,this.wb,this.bd,this.o,this.nc,this.Bb,this.o,this.o,this.o,this.Db,this.ed,this.o,this.pe,this.yb,this.o,this.o,this.o,this.xb,this.cd,this.o];this.hb=[7,6,0,0,0,3,5,0,3,2,2,0,0,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,3,6,0,0,3,3,5,0,4,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,
0,3,5,0,3,2,2,0,3,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,4,2,2,0,5,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,0,6,0,0,3,3,3,0,2,0,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,0,4,0,0,2,6,2,0,3,3,3,0,2,2,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,4,4,4,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0]}u(db,G);f=db.prototype;
f.reset=function(a){this.D.oa&&this.ba();eb(this);this.f=this.a[65532]|this.a[65533]<<8;this.D.error=!1;this.v?this.v.reset():a&&(!0===this.ta||null===this.ta&&!this.v&&void 0===this.H.run)&&this.va()};
f.T=function(a,b,c){a=!1;switch(b){case "run":this.H[b]=c;c.onclick=function(d){return function(){d.D.oa?d.ba():d.va()}}(this);a=!0;break;case "A":case "X":case "Y":case "S":case "PC":case "C":case "Z":case "I":case "D":case "B":case "V":case "N":case "speed":this.H[b]=c;a=!0;break;case "setSpeed":this.H[b]=c,c.onclick=function(d){return function(){Q(d,2<=d.speed?d.Qa:d.speed+1,!0)}}(this),a=!0}return a};
f.ca=function(a,b,c){this.a=a;this.K=b;this.sa=c-b+1;this.Ha=this.K+this.sa;this.K?B("unsupported CPU address buffer offset ("+this.K+")"):this.U()};f.ja=function(a,b){if(a&&!this.D.O){this.V=b;(this.v=P(b,"debugger"))&&this.v.l("Type ? for list of debugger commands\n");if(a=P(b,"video"))this.bb=function(c){return function(){fb(c)}}(a),this.da=function(c){return function(){c.da()}}(a);this.D.O=!0;this.reset(!0);this.update()}};
function gb(a,b,c,d,e){0>hb(a.N,b,c,d,e)&&(a.qa>b&&(a.qa=b),a.ra<c&&(a.ra=c),a.N.push([b,c,d,e]))}function ib(a,b,c){for(var d=0;d<a.N.length;d++)b>=a.N[d][0]&&b<=a.N[d][1]&&a.N[d][3].call(a.N[d][2],b,c)}function R(a,b,c,d,e){0>hb(a.I,b,c,d,e)&&(a.fa>b&&(a.fa=b),a.ga<c&&(a.ga=c),a.I.push([b,c,d,e]))}function jb(a,b,c){for(var d=0;d<a.I.length;d++)b>=a.I[d][0]&&b<=a.I[d][1]&&a.I[d][3].call(a.I[d][2],b,c)}
function hb(a,b,c,d,e){for(var g=0;g<a.length;g++)if(a[g][0]==b&&a[g][1]==c&&a[g][2]==d&&a[g][3]==e)return g;return-1}function Q(a,b,c){void 0!==b&&(a.speed=b,a.H.setSpeed&&(a.H.setSpeed.innerHTML=a.Ua[2<=b?0:b+1]),a.l("running at "+a.Ua[b].toLowerCase()+" speed "+a.ib[b]),c&&a.da());a.W=0;a.Va=za();kb(a)}f.bb=function(){};f.da=function(){};function T(a,b,c,d){void 0!==a.H[b]&&(void 0===d&&(d=1),c="0000"+c.toString(16),a.H[b].innerHTML=c.slice(c.length-d).toUpperCase())}
function lb(a){T(a,"A",a.h,2);T(a,"X",a.A,2);T(a,"Y",a.F,2);var b=mb(a);T(a,"C",b&1?1:0);T(a,"Z",b&2?1:0);T(a,"I",b&4?1:0);T(a,"D",b&8?1:0);T(a,"B",b&16?1:0);T(a,"V",b&64?1:0);T(a,"N",b&128?1:0);T(a,"S",a.G,4);T(a,"PC",a.f,4);a.H.speed&&a.M&&(a.H.speed.innerHTML=a.M.toFixed(1)+"Mhz")}
function kb(a,b){var c=30;c<a.Fa&&(c=a.Fa);c<a.Ea&&(c=a.Ea);var d=1;b&&a.speed>a.Qa&&a.M&&(d=a.M);d>a.Ja&&2>a.speed&&(d=a.Ja);a.jb=Math.round(1E3/30);a.ka=Math.floor(1E6/c*d);a.Ba=Math.floor(1E6/30*d);a.Ya=Math.floor(1E6/a.Fa*d);a.Xa=Math.floor(1E6/a.Ea*d);b||(a.R=a.Ba,a.Y=a.Ya,a.X=a.Xa);a.Da=0}
function nb(a){var b=za(),c=a.jb;a.Z&&(c=Math.round(c*a.Z/a.Ba));c-=b-a.kb;if(b-=a.Va)a.M=Math.round(a.W/(100*b))/10,864E5<=b&&Q(a);0>c?c=0:1==a.speed?a.M<=a.Ja&&(c=0):2==a.speed&&(c=0);a.Da+=a.Z;return c}
f.va=function(){if(N(this,!0)){this.D.oa||(Q(this),this.V&&this.V.start(),this.D.oa=!0,this.H.run&&(this.H.run.innerHTML="Halt"),this.da());1E6<=this.Da&&kb(this,!0);this.Z=0;this.kb=za();try{do{this.step(this.ka);var a=this.L-this.C;this.W+=a;this.Z+=a;this.L=this.C=0;this.Y-=this.ka;0>=this.Y&&(this.Y+=this.Ya,this.bb());this.X-=this.ka;0>=this.X&&(this.X+=this.Xa,lb(this));this.R-=this.ka;if(0>=this.R){this.R+=this.Ba;break}}while(this.D.oa)}catch(b){this.ba();this.update();N(this,!1);Za(this,
b.stack||b.message);return}setTimeout(function(b){return function(){b.va()}}(this),nb(this))}else this.update(),this.V&&this.V.stop(this.Va,this.W)};
f.step=function(a){var b=!0;this.b=this.g=-1;var c;if(c=a&&this.v)c=this.v,c=0<c.pa.length||0<c.wa.length||0<c.ya.length;this.L=this.C=a;do{a=this.a[this.f];var d;if(d=c){d=this.v;var e=a,g=!1;ob(d,this.f,d.pa,"exec")?g=!0:(d.L++,d.B[e][1]++,d.xa[d.Ma++]=d.u.f,d.Ma>=d.xa.length&&(d.Ma=0));d=!!g}if(d){b=void 0;this.ba();break}this.f++;this.m[a].call(this);if(0<=this.b){this.b>=this.qa&&this.b<=this.ra&&ib(this,this.b,this.f);if(d=c)d=this.v,e=!1,ob(d,this.b,d.wa,"read")&&(e=!0),d=!!e;if(d){b=!1;this.ba();
break}this.b=-1}else if(0<=this.g){this.g>=this.fa&&this.g<=this.ga&&jb(this,this.g,this.f);if(d=c){d=this.v;e=this.g;g=this.a[this.g];var h=!1;(g&255)!=g&&(d.l("invalid value at "+z(e)+": "+g),h=!0);ob(d,e,d.ya,"write")&&(h=!0);d=!!h}if(d){b=!1;this.ba();break}this.g=-1}this.C-=this.hb[a]}while(0<this.C);return b};function pb(a){a.R=0;a.L-=a.C;a.C=0}f.ba=function(){$a(this,!0);this.L-=this.C;this.C=0;this.D.oa&&(this.D.oa=!1,this.H.run&&(this.H.run.innerHTML="Run"))};
f.update=function(){this.bb();lb(this)};function qb(a){return a.D.oa?a.W+a.L-a.C:0}f.S=function(a){return this.a[a]};function mb(a){var b=a.c&256?1:0;b|=a.j&255?0:2;b|=(a.s&255^a.w^a.s>>1)&128?64:0;b|=a.i&128?128:0;return a.B&60|b}function rb(a){a.B|=8;a.m[97]=a.Vb;a.m[101]=a.Xb;a.m[105]=a.Ub;a.m[109]=a.Rb;a.m[113]=a.Wb;a.m[117]=a.Yb;a.m[121]=a.Tb;a.m[125]=a.Sb;a.m[225]=a.ke;a.m[229]=a.me;a.m[233]=a.je;a.m[237]=a.ge;a.m[241]=a.le;a.m[245]=a.ne;a.m[249]=a.ie;a.m[253]=a.he}
function sb(a){a.B&=-9;a.m[97]=a.sb;a.m[101]=a.ub;a.m[105]=a.rb;a.m[109]=a.ob;a.m[113]=a.tb;a.m[117]=a.vb;a.m[121]=a.qb;a.m[125]=a.pb;a.m[225]=a.Ab;a.m[229]=a.Cb;a.m[233]=a.zb;a.m[237]=a.wb;a.m[241]=a.Bb;a.m[245]=a.Db;a.m[249]=a.yb;a.m[253]=a.xb}function U(a,b,c){var d=a.c&256?1:0,e=(b&15)+(c&15)+d;10<=e&&(e=e+6&15|16);e+=(b&240)+(c&240);a.w=b^c;a.s=e;a.i=e&255;160<=e&&(e+=96);512<=e&&(e-=256);a.c=e;a.j=b+c+d&255;a.C--;return e&255}
function V(a,b,c){var d=a.c&256?0:1,e=(b&15)-(c&15)-d;0>e&&(e=(e-6&15)-16);e+=(b&240)-(c&240);0>e&&(e-=96);a.i=a.j=(a.c=b-c-d)&255;a.w=b^c;a.s=a.c;a.c^=256;a.C--;return e&255}function eb(a){a.h=0;a.A=0;a.F=0;a.G=256;a.B=0;a.i=0;a.j=0;a.w=0;a.s=0;a.c=0;a.f=0;a.b=-1;a.g=-1;a.M=0;a.W=a.L=a.C=0}
f.tc=function(){this.f++;this.a[this.G--]=this.f>>8;this.G|=256;this.a[this.G--]=this.f&255;this.G|=256;this.B|=16;this.B=mb(this);this.a[this.G--]=this.B;this.G|=256;this.B&=239;this.b=65534;this.f=this.a[this.b]|this.a[this.b+1]<<8};f.Nd=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.h|=this.a[this.b]};f.Pd=function(){this.b=this.a[this.f++];this.i=this.j=this.h|=this.a[this.b]};
f.jc=function(){this.g=this.a[this.f++];this.c=this.a[this.g]<<1;this.i=this.j=this.a[this.g]=this.c&255};f.Sd=function(){this.B=mb(this);this.a[this.G--]=this.B;this.G|=256};f.Md=function(){this.b=this.f++;this.i=this.j=this.h|=this.a[this.b]};f.ic=function(){this.c=this.h<<1;this.i=this.j=this.h=this.c&255};f.Jd=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.h|=this.a[this.b]};
f.gc=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.a[this.g]<<1;this.i=this.j=this.a[this.g]=this.c&255};f.sc=function(){this.f+=(this.i&128?0:(this.C--,this.a[this.f]<<24>>24))+1};f.Od=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.h|=this.a[this.b]};f.Qd=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.h|=this.a[this.b]};
f.kc=function(){this.g=this.a[this.f++]+this.A&255;this.c=this.a[this.g]<<1;this.i=this.j=this.a[this.g]=this.c&255};f.wc=function(){this.c=0};f.Ld=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.h|=this.a[this.b]};f.Kd=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.h|=this.a[this.b]};f.hc=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.a[this.g]<<1;this.i=this.j=this.a[this.g]=this.c&255};
f.kd=function(){this.b=this.f++;this.a[this.G--]=this.f>>8;this.G|=256;this.a[this.G--]=this.f&255;this.G|=256;this.f=this.a[this.b]|this.a[this.b+1]<<8};f.cc=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.h&=this.a[this.b]};f.pc=function(){this.b=this.a[this.f++];this.j=this.h&this.a[this.b];this.i=this.i&127|this.a[this.b]&128;this.s=0;this.w=this.a[this.b]&64?128:0};f.ec=function(){this.b=this.a[this.f++];this.i=this.j=this.h&=this.a[this.b]};
f.Yd=function(){this.g=this.a[this.f++];this.c=this.c&65280|this.a[this.g];this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.a[this.g]=this.c&255};f.Ud=function(){this.G=this.G+1&255|256;this.B=this.a[this.G];this.c=this.B&1?256:0;this.j=this.B&2?0:1;this.i=this.B&128;this.s=0;this.w=this.B&64?128:0};f.bc=function(){this.b=this.f++;this.i=this.j=this.h&=this.a[this.b]};
f.Xd=function(){this.c=this.c&65280|this.h;this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.h=this.c&255};f.oc=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.j=this.h&this.a[this.b];this.i=this.i&127|this.a[this.b]&128;this.s=0;this.w=this.a[this.b]&64?128:0};f.Zb=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.h&=this.a[this.b]};
f.Vd=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.c&65280|this.a[this.g];this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.a[this.g]=this.c&255};f.qc=function(){this.f+=(this.i&128?(this.C--,this.a[this.f]<<24>>24):0)+1};f.dc=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.h&=this.a[this.b]};f.fc=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.h&=this.a[this.b]};
f.Zd=function(){this.g=this.a[this.f++]+this.A&255;this.c=this.c&65280|this.a[this.g];this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.a[this.g]=this.c&255};f.oe=function(){this.c=256};f.ac=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.h&=this.a[this.b]};f.$b=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.h&=this.a[this.b]};
f.Wd=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.c&65280|this.a[this.g];this.c<<=1;this.c=this.c&65534|(this.c&512?1:0);this.i=this.j=this.a[this.g]=this.c&255};f.ee=function(){this.G=this.G+1&255|256;this.B=this.a[this.G];this.c=this.B&1?256:0;this.j=this.B&2?0:1;this.i=this.B&128;this.s=0;this.w=this.B&64?128:0;this.G=this.G+2&255|256;this.f=this.a[this.G-1|256]|this.a[this.G]<<8};
f.Yc=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.h^=this.a[this.b]};f.$c=function(){this.b=this.a[this.f++];this.i=this.j=this.h^=this.a[this.b]};f.Gd=function(){this.g=this.a[this.f++];this.c=this.c&65279|(this.a[this.g]&1?256:0);this.a[this.g]=(this.c=this.c&65280|this.a[this.g]>>1)&255;this.i=this.j=this.c&255};f.Rd=function(){this.a[this.G--]=this.h;this.G|=256};f.Xc=function(){this.b=this.f++;this.i=this.j=this.h^=this.a[this.b]};
f.Fd=function(){this.c=this.c&65279|(this.h&1?256:0);this.h=(this.c=this.c&65280|this.h>>1)&255;this.i=this.j=this.c&255};f.jd=function(){this.b=this.f;this.f=this.a[this.b]|this.a[this.b+1]<<8};f.Uc=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.h^=this.a[this.b]};f.Dd=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.c&65279|(this.a[this.g]&1?256:0);this.a[this.g]=(this.c=this.c&65280|this.a[this.g]>>1)&255;this.i=this.j=this.c&255};
f.uc=function(){this.f+=((this.s&255^this.w^this.s>>1)&128?0:(this.C--,this.a[this.f]<<24>>24))+1};f.Zc=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.h^=this.a[this.b]};f.ad=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.h^=this.a[this.b]};f.Hd=function(){this.g=this.a[this.f++]+this.A&255;this.c=this.c&65279|(this.a[this.g]&1?256:0);this.a[this.g]=(this.c=this.c&65280|this.a[this.g]>>1)&255;this.i=this.j=this.c&255};
f.yc=function(){this.B&=251};f.Wc=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.h^=this.a[this.b]};f.Vc=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.h^=this.a[this.b]};f.Ed=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.c&65279|(this.a[this.g]&1?256:0);this.a[this.g]=(this.c=this.c&65280|this.a[this.g]>>1)&255;this.i=this.j=this.c&255};
f.fe=function(){this.G=this.G+2&255|256;this.f=(this.a[this.G-1|256]|this.a[this.G]<<8)+1};f.sb=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Vb=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.h=U(this,this.h,this.a[this.b])};
f.ub=function(){this.b=this.a[this.f++];this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Xb=function(){this.b=this.a[this.f++];this.h=U(this,this.h,this.a[this.b])};f.ce=function(){this.g=this.a[this.f++];this.c=this.c&65280|this.a[this.g];this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.a[this.g]=this.c&255};f.Td=function(){this.G=this.G+1&255|256;this.i=this.j=this.h=this.a[this.G]};
f.rb=function(){this.b=this.f++;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Ub=function(){this.b=this.f++;this.h=U(this,this.h,this.a[this.b])};f.be=function(){this.c=this.c&65280|this.h;this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.h=this.c&255};f.hd=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.f=this.a[this.b]|this.a[this.b+1]<<8};
f.ob=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Rb=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.h=U(this,this.h,this.a[this.b])};f.$d=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.c&65280|this.a[this.g];this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.a[this.g]=this.c&255};
f.vc=function(){this.f+=((this.s&255^this.w^this.s>>1)&128?(this.C--,this.a[this.f]<<24>>24):0)+1};f.tb=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Wb=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.h=U(this,this.h,this.a[this.b])};
f.vb=function(){this.b=this.a[this.f++]+this.A&255;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Yb=function(){this.b=this.a[this.f++]+this.A&255;this.h=U(this,this.h,this.a[this.b])};f.de=function(){this.g=this.a[this.f++]+this.A&255;this.c=this.c&65280|this.a[this.g];this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.a[this.g]=this.c&255};f.qe=function(){this.B|=4};
f.qb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};f.Tb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.h=U(this,this.h,this.a[this.b])};f.pb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.h+this.a[this.b]+(this.c&256?1:0);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255};
f.Sb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.h=U(this,this.h,this.a[this.b])};f.ae=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.c&65280|this.a[this.g];this.c=this.c&65023|(this.c&1?512:0);this.c>>=1;this.i=this.j=this.a[this.g]=this.c&255};f.ue=function(){this.g=this.a[this.f++]+this.A&255;this.g=this.a[this.g]|this.a[this.g+1]<<8;this.a[this.g]=this.h};f.Ce=function(){this.g=this.a[this.f++];this.a[this.g]=this.F};
f.we=function(){this.g=this.a[this.f++];this.a[this.g]=this.h};f.ze=function(){this.g=this.a[this.f++];this.a[this.g]=this.A};f.Tc=function(){this.i=this.j=this.F=this.F-1&255};f.Ie=function(){this.i=this.j=this.h=this.A};f.Be=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.a[this.g]=this.F};f.re=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.a[this.g]=this.h};f.ye=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.a[this.g]=this.A};
f.lc=function(){this.f+=(this.c&256?0:(this.C--,this.a[this.f]<<24>>24))+1};f.ve=function(){this.g=this.a[this.f++];this.g=(this.a[this.g]|this.a[this.g+1]<<8)+this.F;this.a[this.g]=this.h};f.De=function(){this.g=this.a[this.f++]+this.A&255;this.a[this.g]=this.F};f.xe=function(){this.g=this.a[this.f++]+this.A&255;this.a[this.g]=this.h};f.Ae=function(){this.g=this.a[this.f++]+this.F&255;this.a[this.g]=this.A};f.Ke=function(){this.i=this.j=this.h=this.F};
f.te=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.a[this.g]=this.h};f.Je=function(){this.G=this.A|256};f.se=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.a[this.g]=this.h};f.Ad=function(){this.b=this.f++;this.i=this.j=this.F=this.a[this.b]};f.pd=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.h=this.a[this.b]};f.vd=function(){this.b=this.f++;this.i=this.j=this.A=this.a[this.b]};
f.Bd=function(){this.b=this.a[this.f++];this.i=this.j=this.F=this.a[this.b]};f.rd=function(){this.b=this.a[this.f++];this.i=this.j=this.h=this.a[this.b]};f.wd=function(){this.b=this.a[this.f++];this.i=this.j=this.A=this.a[this.b]};f.Ge=function(){this.i=this.j=this.F=this.h};f.od=function(){this.b=this.f++;this.i=this.j=this.h=this.a[this.b]};f.Fe=function(){this.i=this.j=this.A=this.h};f.yd=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.F=this.a[this.b]};
f.ld=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.h=this.a[this.b]};f.td=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.A=this.a[this.b]};f.mc=function(){this.f+=(this.c&256?(this.C--,this.a[this.f]<<24>>24):0)+1};f.qd=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.h=this.a[this.b]};f.Cd=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.F=this.a[this.b]};
f.sd=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.h=this.a[this.b]};f.xd=function(){this.b=this.a[this.f++]+this.F&255;this.i=this.j=this.A=this.a[this.b]};f.zc=function(){this.w=this.s=0};f.nd=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.h=this.a[this.b]};f.He=function(){this.i=this.j=this.A=this.G&255};f.zd=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.F=this.a[this.b]};
f.md=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.h=this.a[this.b]};f.ud=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.A=this.a[this.b]};f.Mc=function(){this.b=this.f++;this.i=this.j=this.c=this.F-this.a[this.b];this.c^=256};f.Ec=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};
f.Nc=function(){this.b=this.a[this.f++];this.i=this.j=this.c=this.F-this.a[this.b];this.c^=256};f.Gc=function(){this.b=this.a[this.f++];this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Qc=function(){this.g=this.a[this.f++];this.i=this.j=this.a[this.g]=this.a[this.g]-1&255};f.gd=function(){this.i=this.j=this.F=this.F+1&255};f.Dc=function(){this.b=this.f++;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Sc=function(){this.i=this.j=this.A=this.A-1&255};
f.Lc=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.c=this.F-this.a[this.b];this.c^=256};f.Ac=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Oc=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.a[this.g]=this.a[this.g]-1&255};f.rc=function(){this.f+=(this.j&255?(this.C--,this.a[this.f]<<24>>24):0)+1};
f.Fc=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Hc=function(){this.b=this.a[this.f++]+this.A&255;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Rc=function(){this.g=this.a[this.f++]+this.A&255;this.i=this.j=this.a[this.g]=this.a[this.g]-1&255};f.xc=function(){sb(this)};
f.Cc=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Bc=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.c=this.h-this.a[this.b];this.c^=256};f.Pc=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.a[this.g]=this.a[this.g]-1&255};f.Jc=function(){this.b=this.f++;this.i=this.j=this.c=this.A-this.a[this.b];this.c^=256};
f.Ab=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.ke=function(){this.b=this.a[this.f++]+this.A&255;this.b=this.a[this.b]|this.a[this.b+1]<<8;this.h=V(this,this.h,this.a[this.b])};f.Kc=function(){this.b=this.a[this.f++];this.i=this.j=this.c=this.A-this.a[this.b];this.c^=256};
f.Cb=function(){this.b=this.a[this.f++];this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.me=function(){this.b=this.a[this.f++];this.h=V(this,this.h,this.a[this.b])};f.dd=function(){this.g=this.a[this.f++];this.i=this.j=this.a[this.g]=this.a[this.g]+1&255};f.fd=function(){this.i=this.j=this.A=this.A+1&255};
f.zb=function(){this.b=this.f++;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.je=function(){this.b=this.f++;this.h=V(this,this.h,this.a[this.b])};f.Id=function(){};f.Ic=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.c=this.A-this.a[this.b];this.c^=256};
f.wb=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.ge=function(){this.b=this.a[this.f++]|this.a[this.f++]<<8;this.h=V(this,this.h,this.a[this.b])};f.bd=function(){this.g=this.a[this.f++]|this.a[this.f++]<<8;this.i=this.j=this.a[this.g]=this.a[this.g]+1&255};f.nc=function(){this.f+=(this.j&255?0:(this.C--,this.a[this.f]<<24>>24))+1};
f.Bb=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.le=function(){this.b=this.a[this.f++];this.b=(this.a[this.b]|this.a[this.b+1]<<8)+this.F;this.h=V(this,this.h,this.a[this.b])};
f.Db=function(){this.b=this.a[this.f++]+this.A&255;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.ne=function(){this.b=this.a[this.f++]+this.A&255;this.h=V(this,this.h,this.a[this.b])};f.ed=function(){this.g=this.a[this.f++]+this.A&255;this.i=this.j=this.a[this.g]=this.a[this.g]+1&255};f.pe=function(){rb(this)};
f.yb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.ie=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.F;this.h=V(this,this.h,this.a[this.b])};
f.xb=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.c=this.h-this.a[this.b]-(this.c&256?0:1);this.w=this.h^this.a[this.b];this.s=this.c;this.i=this.j=this.h=this.c&255;this.c^=256};f.he=function(){this.b=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.h=V(this,this.h,this.a[this.b])};f.cd=function(){this.g=(this.a[this.f++]|this.a[this.f++]<<8)+this.A;this.i=this.j=this.a[this.g]=this.a[this.g]+1&255};
f.Ee=function(){var a=this.a[this.f++];switch(a){case 0:this.l("HALT");this.ba();break;case 1:a=this.f;for(var b="";a<this.a.length;){var c=this.a[a++];if(!c)break;b+=String.fromCharCode(c)}this.f=a;b=b.replace(/%A/g,v(this.h,2)).replace(/%X/g,v(this.A,2)).replace(/%Y/g,v(this.F,2));this.l(b);pb(this);break;default:this.f-=2,this.l("undefined opSim: "+w(a)+" at "+z(this.f)),this.ba()}};f.o=function(){var a=this.a[--this.f];this.l("undefined opcode: "+w(a)+" at "+z(this.f));this.ba()};
E(function(){for(var a=J(document,"c1p","cpu"),b=0;b<a.length;b++){var c=a[b],d=K(c);d=new db(d);I(d,c)}});function tb(a){G.call(this,"C1PROM",a);this.b=this.a=null;this.g=+a.size;if(this.m=a.file||a.image){a=this.m;var b=qa(this.m);"json"!=b&&"hex"!=b&&(a=Ba()+"/api/v1/dump?file="+this.m+"&format=bytes");var c=this;A(a,function(d,e,g){ub(c,d,e,g)})}else this.U()}u(tb,G);
tb.prototype.ca=function(a,b,c,d){this.a=a;this.s=b;a=c-b+1;this.g||(this.g=a);a!=this.g?Za(this,"computer-specified ROM size ("+z(a)+") does not match component-specified size ("+z(this.g)+")"):(d&&(this.u=d,R(d,b,c,this,this.w)),vb(this))};tb.prototype.ja=function(a,b){a&&!this.D.O&&(this.D.O=!0,this.v=P(b,"debugger"))};tb.prototype.w=function(a,b){void 0!==b&&(this.v&&W(this.v,this,a,b,this.v.mb,!0),a-=this.s,this.a[this.s+a]=this.b?this.b[a]:0)};
function ub(a,b,c,d){if(d)a.l('Error loading ROM "'+b+'" ('+d+")");else{if("["==c.charAt(0)||"{"==c.charAt(0))try{var e=eval("("+c+")"),g=e.bytes;g?a.b=g:a.b=e}catch(h){a.l('Error processing ROM "'+b+'": '+h.message);return}else for(b=c.replace(/\n/gm," ").replace(/ +$/,"").split(" "),a.b=Array(b.length),c=0;c<b.length;c++)a.b[c]=parseInt(b[c],16);vb(a)}}
function vb(a){if(!M(a))if(!a.m)a.U();else if(a.b&&a.a){var b=a.b.length;if(b!=a.g)Za(a,"ROM image size ("+z(b)+") does not match component-specified size ("+z(a.g)+")");else{for(var c=0;c<b;c++)a.a[a.s+c]=a.b[c];a.U()}}}E(function(){for(var a=J(document,"c1p","rom"),b=0;b<a.length;b++){var c=a[b],d=K(c);d=new tb(d);I(d,c)}});function wb(a){G.call(this,"C1PRAM",a)}u(wb,G);wb.prototype.ca=function(a){this.a=a;this.U()};
E(function(){for(var a=J(document,"c1p","ram"),b=0;b<a.length;b++){var c=a[b],d=K(c);d=new wb(d);I(d,c)}});
function xb(a){G.call(this,"C1PKeyboard",a);this.D.O=!1;this.Ua=a.model;this.qa=8;this.kb=10;this.jb=13;this.ra=27;this.hb=this.qa;this.ib=this.kb;this.Va=this.jb;this.ga=this.ra;this.w=224;this.g=16+this.w;this.N=17+this.w;this.R=18+this.w;this.ka=20+this.w;this.fa=this.w;this.Xa=3;this.Ya=15;this.L=1;this.I={};this.I["break"]=this.fa;this.I.esc=this.ga;this.I["ctrl-c"]=this.Xa;this.I["ctrl-o"]=this.Ya;this.b=[];this.b[49]=30464;this.b[33]=30464+this.g;this.b[50]=30208;this.b[34]=30208+this.g;this.b[51]=
29952;this.b[35]=29952+this.g;this.b[52]=29696;this.b[36]=29696+this.g;this.b[53]=29440;this.b[37]=29440+this.g;this.b[54]=29184;this.b[38]=29184+this.g;this.b[55]=28928;this.b[39]=28928+this.g;this.b[56]=26368;this.b[40]=26368+this.g;this.b[57]=26112;this.b[41]=26112+this.g;this.b[48]=25856;this.b[58]=25600;this.b[42]=25600+this.g;this.b[45]=25344;this.b[61]=25344+this.g;this.b[46]=22272;this.b[62]=22272+this.g;this.b[108]=22016;this.b[76]=22016+this.g;this.b[92]=22016+this.g;this.b[111]=21760;this.b[79]=
21760+this.g;this.b[this.hb]=21760+this.g;this.b[this.ib]=21504;this.b[this.Va]=21248;this.b[119]=18176;this.b[87]=18176+this.g;this.b[101]=17920;this.b[69]=17920+this.g;this.b[114]=17664;this.b[82]=17664+this.g;this.b[116]=17408;this.b[84]=17408+this.g;this.b[121]=17152;this.b[89]=17152+this.g;this.b[117]=16896;this.b[85]=16896+this.g;this.b[105]=16640;this.b[73]=16640+this.g;this.b[115]=14080;this.b[83]=14080+this.g;this.b[100]=13824;this.b[68]=13824+this.g;this.b[102]=13568;this.b[70]=13568+this.g;
this.b[103]=13312;this.b[71]=13312+this.g;this.b[104]=13056;this.b[72]=13056+this.g;this.b[106]=12800;this.b[74]=12800+this.g;this.b[107]=12544;this.b[75]=12544+this.g;this.b[91]=12544+this.g;this.b[120]=9984;this.b[88]=9984+this.g;this.b[99]=9728;this.b[67]=9728+this.g;this.b[118]=9472;this.b[86]=9472+this.g;this.b[98]=9216;this.b[66]=9216+this.g;this.b[110]=8960;this.b[78]=8960+this.g;this.b[94]=8960+this.g;this.b[109]=8704;this.b[77]=8704+this.g;this.b[93]=8704+this.g;this.b[44]=8448;this.b[60]=
8448+this.g;this.b[113]=5888;this.b[81]=5888+this.g;this.b[97]=5632;this.b[65]=5632+this.g;this.b[122]=5376;this.b[90]=5376+this.g;this.b[32]=5120;this.b[47]=4864;this.b[63]=4864+this.g;this.b[59]=4608;this.b[43]=4608+this.g;this.b[112]=4352;this.b[80]=4352+this.g;this.b[64]=4352+this.g;this.b[this.N]=1536;this.b[this.ga]=1280;this.b[this.g]=512;this.b[this.R]=256;this.b[this.ka]=0;this.reset()}u(xb,G);f=xb.prototype;
f.reset=function(){this.Na(this.Ua);this.m=this.L;this.ta=0;this.s=[this.L,0,0,0,0,0,0,0];this.W=[];if(this.B)for(var a in this.B)isNaN(+a)||this.B[a]&&clearTimeout(this.B[a]);this.B=[];this.Fa=this.C=0;this.Ba=-1;this.sa=this.s;this.Da=this.Z=0;this.K=""};
f.T=function(a,b,c){if(void 0===this.H[b])switch(b){case "keyDown":return this.H[b]=c,c.onkeydown=function(d){return function(e){return yb(d,e,!0)}}(this),!0;case "keyPress":return this.H[b]=c,c.onkeypress=function(d){return function(e){var g=!0;e=e||window.event;e=e.which||e.keyCode;d.K="";d.m&8?d.m&=-9:g=!zb(d,e);d.v&&O(d.v,d.v.za)&&d.v.message("keyPress("+w(e)+"): "+(g?"pass":"consume"));return g}}(this),!0;case "keyUp":return this.H[b]=c,c.onkeyup=function(d){return function(e){return yb(d,e,
!1)}}(this),!0;case "break":return this.H[b]=c,c.onclick=function(d){return function(){d.V&&d.V.reset(!0)}}(this),!0;default:if(void 0!==this.I[b])return this.H[b]=c,c.onclick=function(d,e,g){return function(){d.u&&d.u.da();return!zb(d,g)}}(this,b,this.I[b]),!0}return!1};f.ca=function(a,b,c,d){this.a=a;this.Ea=b;this.Re=c-b+1;this.Hb=this.Ea+this.Re;d&&(this.u=d,R(d,b,c,this,this.Jb));this.U()};f.Na=function(a){this.M=a;this.X=255;600!=this.M&&(this.X=0,this.l("updated keyboard model: "+this.M))};
f.ja=function(a,b){a&&!this.D.O&&(this.D.O=!0,this.V=b,this.v=P(b,"debugger"))};f.U=function(){this.Y=(this.Se=C("iOS"))||C("Android");this.v&&O(this.v,this.v.za)&&this.v.message("mobile keyboard support: "+(this.Y?"true":"false")+" ("+window.navigator.userAgent+")");G.prototype.U.call(this)};function Ab(a,b){b=b?100:250;a.u&&a.u.M&&(b/=a.u.M);return b}function Bb(a,b){!a.C||void 0!==b&&b==a.C||(a.v&&O(a.v,a.v.za)&&a.v.message("autoClear("+w(a.C)+")"),clearTimeout(a.B[a.C]),Cb(a,a.C,!1,4))}
function Db(a,b,c){a.K=b;Eb(a,c||300)}function Eb(a,b){if(0<a.K.length){var c=a.K.charCodeAt(0);10==c&&(c=13);65<=c&&90>=c&&(c+=32);a.K=a.K.substr(1);zb(a,c)}0<a.K.length&&setTimeout(function(d){return function(){Eb(d,b)}}(a),b)}
function yb(a,b,c){var d=!c;b=b.keyCode;c&&(a.Fa=b);if(b==a.g-a.w)a.m&=-5,c&&(a.m|=4),b+=a.w,d=!1;else if(b==a.R-a.w)a.m&=-3,c&&(a.m|=2),b+=a.w,d=!1;else if(b==a.N-a.w)a.m&=-65,c&&(a.m|=64),b+=a.w,d=!1;else if(b==a.ka-a.w)c=!c,a.m&=~a.L,c&&(a.m|=a.L),b+=a.w,d=!1;else if(91==b){a.m&=-9;c&&(a.m|=8);d=!1;var e=!0}else e=9==b?d=!1:b==a.ra||b==a.qa?c?!zb(a,b):!1:!0;d&&(a.m&=-9,a.Y||b!=a.Fa||Bb(a));void 0===e&&(e=!Cb(a,b,c,2));a.v&&O(a.v,a.v.za)&&a.v.message("key"+(c?"Down":"Up")+"("+w(b)+"): "+(e?"pass":
"consume"));return e}function zb(a,b){var c=!1;b==a.fa?a.V&&(a.V.reset(!0),c=!0):(a.Y&&65<=b&&90>=b&&(b+=32),Bb(a,b),Cb(a,b,!0,0)&&(2==a.u.speed?Cb(a,b,!1,1):(c=!1,a.B[b]&&(clearTimeout(a.B[b]),c=!0),c=Ab(a,c),a.B[a.C=b]=setTimeout(function(d){return function(){Cb(d,b,!1,3)}}(a),c),a.v&&O(a.v,a.v.za)&&a.v.message("keyPressSimulate("+w(b)+"): setTimeout()")),c=!0));a.v&&O(a.v,a.v.za)&&a.v.message("keyPressSimulate("+w(b)+"): "+(c?"true":"false"));return c}
function Cb(a,b,c,d){var e=!1;c||(a.B[b]=null,a.C==b&&(a.C=0));var g=0,h=a.b[b];void 0===h&&(1<=b&&26>=b&&(b+=64,g=a.N),h=a.b[b]);void 0!==h&&(b=h>>12,e=h>>8&15,g||(g=h&255),c?(a.s[b]|=1<<e,a.s[0]=g==a.N?a.s[0]|64:g==a.g?a.s[0]|4:g==a.R?a.s[0]|2:a.s[0]&-71):(a.s[b]&=~(1<<e),a.s[0]&=-71,a.s[0]|=a.m&70),c=0==d&&!a.W.length,a.W.push(a.s.slice()),Fb(a,c),e=!0);return e}f.S=function(){};f.Jb=function(a){this.ta=this.u.S(a)^this.X;this.Z++;Fb(this,!1,a)};
function Fb(a,b,c){var d=qb(a.u);b||(2==a.u.speed?b=void 0!==c&&32<=a.Z:(b=d-a.Da,b=0>b||8192<=b));b&&(b=a.W.shift(),void 0!==b&&(a.sa=b),a.Z=0,a.Da=d);for(b=d=0;8>b;b++)a.ta&1<<b&&(d|=a.sa[b]);d^=a.X;if(void 0!==c)a.a[c]=d;else if(c=a.Ea,d!=a.Ba)for(;c<a.Hb;c++)a.a[c]=d;a.Ba=d}E(function(){for(var a=J(document,"c1p","keyboard"),b=0;b<a.length;b++){var c=a[b],d=K(c);d=new xb(d);I(d,c)}});
function Gb(a,b,c,d){G.call(this,"C1PVideo",a);this.ka=a.model;this.Z=a.charCols;this.fa=a.charRows;this.ra=a.screenWidth;this.sa=a.screenHeight;this.B=a.charWidth;this.C=a.charHeight;Hb(this);this.w=b;this.N=c;this.m=d;b=["","moz","ms","webkit"];a=a.smoothing;(c=Da("smoothing"))&&(a="true"==c);if(null!=a)for(c=0;c<b.length;c++)if(d=(d=b[c])?d+"ImageSmoothingEnabled":"imageSmoothingEnabled",void 0!==this.N[d]){this.N[d]=a;break}}u(Gb,G);f=Gb.prototype;
f.reset=function(a){this.Na(this.ka);if(this.a)for(var b=this.I;b<this.R;b++)this.a[b]=a?Math.floor(256*Math.random()):32};f.T=function(a,b,c){switch(b){case "refresh":return this.H[b]=c,c.onclick=function(d){return function(){Ib(d);fb(d)}}(this),!0}return!1};f.ca=function(a,b,c,d){this.a=a;this.I=b;this.qa=c-b+1;this.R=this.I+this.qa;d&&(this.u=d,gb(d,56832,56832,this,this.S),R(d,56832,56832,this,this.Lb));this.reset(!0)};
function Hb(a,b,c,d,e){a.K=void 0!==b?b:a.Z;a.ta=void 0!==c?c:a.fa;a.g=a.K*a.ta;a.R=a.I+a.g;a.Y=void 0!==d?d:0;a.ga=void 0!==e?e:c;a.W=Math.floor(a.ra/a.K);a.X=Math.floor(a.sa/a.ga)}f.da=function(){this.w.focus()};f.Na=function(a){this.M=a;600==this.M?(Hb(this,this.Z,this.fa,3,25),1024==this.g&&this.u&&(this.s=this.R+this.g-1,R(this.u,this.s,this.s,this,this.Gb))):(this.l("updated video model: "+this.M),Hb(this,64,32));Ib(this);fb(this)};
f.ja=function(a,b){if(a&&!this.D.O&&M(this)){if(this.D.O=!0,this.v=P(b,"debugger"),this.b=P(b,"keyboard"))this.b.T("canvas","keyDown",this.w),this.b.T("canvas","keyPress",this.w),this.b.T("canvas","keyUp",this.w)}else!a&&this.D.O&&(this.D.O=!1)};f.U=function(){this.B||(this.B=Math.floor(this.m.width/16));this.C||(this.C=Math.floor(this.m.height/16));G.prototype.U.call(this)};
f.S=function(a,b){var c=this.u.S(a);void 0!==b&&this.v&&W(this.v,this,a,b,this.v.Za);this.u.a[a]=c&127|(Math.floor(qb(this.u)/8333)&1?128:0)};f.Lb=function(a,b){void 0!==b&&this.v&&W(this.v,this,a,b,this.v.Za)};
f.Gb=function(a,b){if(void 0!==b){this.v&&W(this.v,this,a,b,this.v.Za,!0);this.Na(540);this.b&&this.b.Na(542);a=this.u;b=a.I;var c=[],d=hb(b,this.s,this.s,this,this.Gb);if(0<=d){c.push(b[d][0]);c.push(b[d][1]);b.splice(d,1);var e=65536,g=0;for(d=0;d<b.length;d++)e>b[d][0]&&(e=b[d][0]),g<b[d][1]&&(g=b[d][1]);c.push(e);c.push(g)}4==c.length&&(a.fa=c[2],a.ga=c[3])}};function Ib(a){a.L=Array(a.g);for(var b=0;b<=a.g;b++)a.L[b]=-1}
function fb(a){var b=0;if(a.D.O)for(;b<a.g;){var c=a.a[a.I+b];if(a.L[b]!=c){var d=Math.floor(b/a.K);if(d>=a.Y&&(d-=a.Y,d<a.ga)){var e=c*a.B;a.N.drawImage(a.m,e%a.m.width,Math.floor(e/a.m.width)*a.C,a.B,a.C,b%a.K*a.W,d*a.X,a.W,a.X)}a.L[b]=c}b++}}
E(function(){for(var a=J(document,"c1p","video"),b=0;b<a.length;b++){var c=a[b],d=K(c),e=J(c,"pcjs-canvas");if(e&&e.length)var g=e[0];else if(g=document.createElement("canvas"))g.setAttribute("class","pcjs-canvas"),g.setAttribute("width",d.screenWidth),g.setAttribute("height",d.screenHeight),g.style.backgroundColor=d.screenColor,g.style.height="auto",c.appendChild(g);if(!g||!g.getContext){c.innerHTML="<br/>Missing &lt;canvas&gt; support. Please try a newer web browser.";break}g.setAttribute("contenteditable",
"true");g.setAttribute("autocapitalize","off");g.setAttribute("autocorrect","off");0<=(window?window.navigator.userAgent:"").indexOf("MSIE")&&(g.style.height=(c.clientWidth*d.screenHeight/d.screenWidth|0)+"px",c.onresize=function(l,k,m,n){return function(){k.style.height=(l.clientWidth*n/m|0)+"px"}}(c,g,d.screenWidth,d.screenHeight));e=new Image;var h=g.getContext("2d");g=new Gb(d,g,h,e);d=d.fontROM||d.charSet;e.onload=function(l){return function(){l.U()}}(g,d);e.src=d;I(g,c)}});
function Jb(a){G.call(this,"C1PSerialPort",a);this.D.O=!1;this.w=a.demo;this.L='10 PRINT "HELLO OSI #'+Xa(this)+'"\n';this.s=Kb;this.m=Da("autoMount")||a.autoMount;if("string"==typeof this.m)try{this.m=eval("("+this.m+")")}catch(c){B(this.type+" auto-mount error: "+c.message+" ("+this.m+")"),this.m=null}if(a=this.m&&this.m.path){var b=this;this.w=!0;A(a,function(c,d,e){Lb(b,c,d,e);b.L=d;b.m=null;b.a&&b.U()})}this.reset(!0)}u(Jb,G);
function Lb(a,b,c,d){if(c){a.C=0;a.g=c;a.K=!0;if(0<b.indexOf(".json"))try{d="";var e=eval("("+c+")").bytes;for(c=0;c<e.length;c++)d+=String.fromCharCode(e[c]);a.g=d;a.K=!1}catch(g){a.l('Error processing file "'+b+'": '+g.message);return}a.V&&a.b&&a.u.D.oa?(a.l("auto-loading "+b),a.w||Mb(a,!0)):a.l(b+" ready to load")}else a.l('Error loading file "'+b+'" ('+d+")")}f=Jb.prototype;f.reset=function(a){if(a||this.s!=Nb)this.B=-1,this.C=0,this.g="",this.w&&(this.g=this.L),this.K=!0,this.s=Kb};
f.start=function(){this.b&&this.w&&("."==this.g[0]?(this.w=!1,Mb(this)):(Db(this.b," C\n\n",1E3),setTimeout(function(a){return function(){a.w=!1;Mb(a)}}(this),5E3)))};
f.T=function(a,b,c){var d=this;switch(b){case "listSerial":return this.H[b]=c,!0;case "loadSerial":return this.H[b]=c,c.onclick=function(){d.H.listSerial&&A(d.H.listSerial.value,function(e,g,h){Lb(d,e,g,h)})},!0;case "mountSerial":return!Ca()&&window&&"FileReader"in window?(this.H[b]=c,c.onchange=function(){var e=c.children[0];e.children[1].disabled=!e.children[0].files.length},c.onsubmit=function(e){var g=e.currentTarget[1].files[0],h=new FileReader;h.onload=function(){Lb(d,g.name,h.result.toString(),
0)};h.readAsText(g);return!1}):c.parentNode.removeChild(c),!0}return!1};f.ca=function(a,b,c,d){this.a=a;this.I=b;this.N=c-b+1;this.M=this.I+this.N;if(this.u=d)gb(d,b,c,this,this.S),R(d,b,c,this,this.Kb);this.m||this.U()};f.ja=function(a,b){a&&!this.D.O&&(this.D.O=!0,this.V=b,this.b=P(b,"keyboard"),this.v=P(b,"debugger"))};function Mb(a,b){a.g&&(a.u.da(),"."!=a.g.charAt(0)?(a.s=Ob,Db(a.b,"NEW\nLOAD\n")):(a.s=Nb,b&&a.V.reset(!0),Db(a.b,"ML")))}
f.S=function(a,b){void 0!==b&&(a&1?Pb(this):this.g&&!this.C&&Pb(this))};f.Kb=function(a,b){void 0!==b&&this.v&&W(this.v,this,a,b,this.v.Me,!0)};function Pb(a){if(void 0!==a.g){a.B=-1;if(a.C<a.g.length){var b=a.g.charCodeAt(a.C++)&255;a.K&&10==b&&(b=13);a.B=b}else a.g="",a.C=0,a.s==Ob&&a.b&&Db(a.b," \nRUN\n"),a.s=Kb;for(b=a.I+0;b<a.M;b+=2)a.a[b]=0<=a.B?Qb:Rb;for(b=a.I+1;b<a.M;b+=2)a.a[b]=0<=a.B?a.B:0}}var Rb=0,Qb=1,Kb=0,Ob=1,Nb=2;
E(function(){for(var a=J(document,"c1p","serial"),b=0;b<a.length;b++){var c=a[b],d=K(c);d=new Jb(d);I(d,c)}});function Sb(a){G.call(this,"C1PDiskController",a);this.D.O=!1;this.reset(!0)}u(Sb,G);f=Sb.prototype;f.reset=function(a){Tb(this);this.b=-1;a&&(this.g=[],this.g[0]={Te:0,nb:40,Pb:!0,Ga:20,na:0,Ca:-1,Sa:[]})};
function Tb(a){a.M={J:64,read:function(){},update:function(b){return function(c){void 0!==c&&(this.J=c);b.B.J&4||X(b,0,this)}}(a)};a.m={J:255,read:function(){this.update()},update:function(b){return function(c){void 0===c?c=b.m.J:Ub(b,c,b.w.J);c=(c|190)&-2;if(0<=b.b&&b.g[b.b].Sa.length){var d=b.g[b.b];d.Pb&&(c&=-33);d.na||(c&=-3);10>=--d.Ga&&(0<d.Ga?(c&=-129,Vb(b)):(d.Ga=100,0<=b.b&&(b.g[b.b].Ca=0,Wb(b))))}this.J=c;b.B.J&4&&X(b,0,this)}}(a)};a.B={J:0,read:function(){},update:function(b){return function(c){void 0!==
c&&(this.J=c&-193);X(b,1,this);b.m.update();b.M.update()}}(a)};a.L={J:255,read:function(){},update:function(b){return function(c){void 0!==c&&(this.J=c);b.C.J&4||X(b,2,this)}}(a)};a.w={J:255,read:function(){},update:function(b){return function(c){void 0===c?c=b.w.J:Ub(b,b.m.J,c);if(0<=b.b&&b.b<b.g.length){var d=b.g[b.b];d.Sa.length&&b.w.J&8&&!(c&8)&&(c&4?d.na--:d.na++,b.v&&O(b.v,b.v.Ia)&&b.v.message("stepping "+(c&4?"down":"up")+" to track "+d.na),d.na>=d.nb&&(d.na=d.nb),0>d.na&&(d.na=0),d.Ga=20,
b.m.update(b.m.J|128),Vb(b))}this.J=c;b.C.J&4&&X(b,2,this)}}(a)};a.C={J:0,read:function(){},update:function(b){return function(c){void 0!==c&&(this.J=c&-193);X(b,3,this);b.w.update();b.L.update()}}(a)};a.N={J:0,read:function(){},update:function(b){return function(c){void 0!==c&&(3==(c&3)&&(b.s.J=14),this.J=c);b.s.update()}}(a)};a.s={J:14,read:function(){},update:function(b){return function(c){void 0===c&&(c=b.s.J);c&=-2;0<=b.b&&0<=b.g[b.b].Ca&&(c|=1);this.J=c;X(b,16,this)}}(a)};a.I={J:0,read:function(b){return function(){Wb(b)}}(a),
update:function(b){return function(c){void 0!==c&&(this.J=c);X(b,17,this)}}(a)};a.R={J:0,read:function(){},update:function(){return function(){}}(a)}}f.T=function(a,b,c){switch(b){case "listDisk":return this.H[b]=c,!0;case "loadDisk":return this.H[b]=c,c.onclick=function(d){return function(){if(d.H.listDisk){var e=d.H.listDisk.value,g=e;".json"!=e.substr(e.length-5)&&(g="http://"+window.location.host+"/api/v1/dump?disk="+e);d.l("loading  "+pa(e)+"...");A(g,function(h,l,k){Xb(d,h,l,k)})}}}(this),!0}return!1};
f.ca=function(a,b,c,d){this.a=a;this.K=b;if(this.u=d)gb(d,b,c,this,this.S),R(d,b,c,this,this.Ib);this.U()};f.ja=function(a,b){a&&!this.D.O&&(this.D.O=!0,this.v=P(b,"debugger"))};
function Xb(a,b,c,d){if(d)a.l("disk load error ("+d+")");else{d=[];a.l("mounting "+b+"...");try{if(d=eval("("+c+")"),d.length)if(d[0].length){var e=d[0];if(void 0===e[0].trackNum)a.l("data error: "+e[0]);else if(a.g[0]){for(c=0;c<e.length;c++){var g,h=e[c],l=h.sectors;if(void 0===(g=h.trackNum)||void 0===l)throw Error("track "+c+" missing data");g!=c&&B("track "+g+" out of order (expected "+c+")");d=[];var k;if(g){Yb(d,h,"trackSig");Zb(d,h);$b(d,h,"trackType");for(var m=0;m<l.length;m++){var n=l[m];
var p=n.sectorData;$b(d,n,"sectorSig");$b(d,n,"sectorNum");$b(d,n,"sectorPages");for(k=0;k<p.length;k++)d.push(p[k]);Yb(d,n,"sectorEndSig")}}else for(n=l[0],p=n.sectorData,$b(d,h,"trackLoad",2),$b(d,n,"sectorPages"),k=0;k<p.length;k++)d.push(p[k]);e[g].Fb=d;a.v&&O(a.v,a.v.Ia)&&a.v.message("track "+g+": "+d.length+" bytes")}a.g[0].Sa=e;a.l("mount of "+b+" complete")}else a.l("no available drives")}else a.l("no tracks: "+b);else a.l("no data: "+b)}catch(t){a.l("disk data error: "+t.message)}}}
function Zb(a,b){b=b.trackNum;if(void 0===b)throw Error("missing bcd value: trackNum");a.push(Math.floor(b/10)<<4|b%10)}function $b(a,b,c,d){b=b[c];if(void 0===b)throw Error("missing binary value: "+c);2==d&&a.push(b>>8&255);a.push(b&255)}function Yb(a,b,c){b=b[c];if(void 0===b)throw Error("missing signature: "+c);for(c=0;c<b.length;c++)a.push(b.charCodeAt(c))}
function ac(a,b,c){b&=63;16>b?b&=3:32>b&&(b&=17);switch(b){case 0:a=a.B.J&4?a.m:a.M;break;case 1:a=a.B;break;case 2:a=a.C.J&4?a.w:a.L;break;case 3:a=a.C;break;case 16:a=c?a.N:a.s;break;case 17:a=a.I;break;default:a=a.R}return a}f.S=function(a,b){if(void 0!==b){var c=ac(this,a-this.K,!1);this.v&&W(this.v,this,a,b,this.v.Ia,!1,c.Eb);c.read()}};
f.Ib=function(a,b){if(void 0!==b){var c=this.u.S(a),d=ac(this,a-this.K,!0);if(this.v&&O(this.v,this.v.Ia|this.v.mb)&&(W(this.v,this,a,b,this.v.Ia,!0,d.Eb),d.Nb))for(a=128,b=d.J^c;b&&a;)b&a&&this.v.message("  changed "+d.Eb+"."+d.Nb[a]+" to "+(c&a?"1":"0")),a>>=1;d.update(c)}};function Ub(a,b,c){var d=-1;void 0!==b&&void 0!==c&&(d=0,c&32||(d|=2),a.m.J&64||(d|=1));a.b!=d&&(a.b=d,a.s.update())}function Vb(a){0<=a.b&&(a.g[a.b].Ca=-1,a.I.update(255),a.s.update())}
function Wb(a){if(0<=a.b){var b=a.g[a.b];var c=b.Sa[b.na];void 0!==c&&(0<=b.Ca&&b.Ca<c.Fb.length?(b.Ga=100,b=c.Fb[b.Ca++],a.I.update(b),a.s.update()):(b.Ga=10,Vb(a)))}}function X(a,b,c){a.u.a[b+a.K]=c.J}E(function(){for(var a=J(document,"c1p","disk"),b=0;b<a.length;b++){var c=a[b],d=K(c);d=new Sb(d);I(d,c)}});
function bc(a){G.call(this,"C1PDebugger",a);this.v=this;this.L=-1;this.ua=0;this.gb=null;this.Ta=!1;this.ia=0;this.pa=[];this.wa=[];this.ya=[];this.Ma=0;this.xa=[];this.B=[];this.mb=1;this.za=16;this.Za=32;this.Ia=64;this.Me=128;this.ma=this.Y=0;this.Ra={port:1,kbd:16,video:32,disk:64,serial:128};this.Pa=28;this.$a=56;this.Ka="ADC AND ASL BCC BCS BEQ BIT BMI BNE BPL BRK BVC BVS CLC CLD CLI CLV CMP CPX CPY DEC DEX DEY EOR INC INX INY JMP JSR LDA LDX LDY LSR NOP ORA PHA PHP PLA PLP ROL ROR RTI RTS SBC SEC SED SEI STA STX STY TAX TAY TSX TXA TXS TYA SIM .DB".split(" ");
this.X=["HLT","MSG"];cc(this,!0);this.ha=[[10],[34,1,this.C],[this.$a,1],[],[],[34,1,this.b],[2,1,this.b],[],[36],[34,1,this.s],[2,0,this.N],[],[],[34,2,this.P],[2,2,this.P],[],[9,1,this.ea],[34,1,this.I],[],[],[],[34,1,this.g],[2,1,this.g],[],[13],[34,2,this.w],[],[],[],[34,2,this.m],[2,2,this.m],[],[this.Pa,2,this.Oa],[1,1,this.C],[],[],[6,1,this.b],[1,1,this.b],[39,1,this.b],[],[38],[1,1,this.s],[39,0,this.N],[],[6,2,this.P],[1,2,this.P],[39,2,this.P],[],[7,1,this.ea],[1,1,this.I],[],[],[],[1,
1,this.g],[39,1,this.g],[],[44],[1,2,this.w],[],[],[],[1,2,this.m],[39,2,this.m],[],[41],[23,1,this.C],[],[],[],[23,1,this.b],[32,1,this.b],[],[35],[23,1,this.s],[32,0,this.N],[],[27,2,this.Oa],[23,2,this.P],[32,2,this.P],[],[11,1,this.ea],[23,1,this.I],[],[],[],[23,1,this.g],[32,1,this.g],[],[15],[23,2,this.w],[],[],[],[23,2,this.m],[32,2,this.m],[],[42],[0,1,this.C],[],[],[],[0,1,this.b],[40,1,this.b],[],[37],[0,1,this.s],[40,0,this.N],[],[27,2,this.lb],[0,2,this.P],[40,2,this.P],[],[12,1,this.ea],
[0,1,this.I],[],[],[],[0,1,this.g],[40,1,this.g],[],[46],[0,2,this.w],[],[],[],[0,2,this.m],[40,2,this.m],[],[],[47,1,this.C],[],[],[49,1,this.b],[47,1,this.b],[48,1,this.b],[],[22],[],[53],[],[49,2,this.P],[47,2,this.P],[48,2,this.P],[],[3,1,this.ea],[47,1,this.I],[],[],[49,1,this.g],[47,1,this.g],[48,1,this.W],[],[55],[47,2,this.w],[54],[],[],[47,2,this.m],[],[],[31,1,this.s],[29,1,this.C],[30,1,this.s],[],[31,1,this.b],[29,1,this.b],[30,1,this.b],[],[51],[29,1,this.s],[50],[],[31,2,this.P],[29,
2,this.P],[30,2,this.P],[],[4,1,this.ea],[29,1,this.I],[],[],[31,1,this.g],[29,1,this.g],[30,1,this.W],[],[16],[29,2,this.w],[52],[],[31,2,this.m],[29,2,this.m],[30,2,this.w],[],[19,1,this.s],[17,1,this.C],[],[],[19,1,this.b],[17,1,this.b],[20,1,this.b],[],[26],[17,1,this.s],[21],[],[19,2,this.P],[17,2,this.P],[20,2,this.P],[],[8,1,this.ea],[17,1,this.I],[],[],[],[17,1,this.g],[20,1,this.g],[],[14],[17,2,this.w],[],[],[],[17,2,this.m],[20,2,this.m],[],[18,1,this.s],[43,1,this.C],[],[],[18,1,this.b],
[43,1,this.b],[24,1,this.b],[],[25],[43,1,this.s],[33],[],[18,2,this.P],[43,2,this.P],[24,2,this.P],[],[5,1,this.ea],[43,1,this.I],[],[],[],[43,1,this.g],[24,1,this.g],[],[45],[43,2,this.w],[],[],[],[43,2,this.m],[24,2,this.m],[]]}u(bc,G);f=bc.prototype;
f.T=function(a,b,c){var d=this;switch(b){case "debugInput":return this.R=this.H[b]=c,this.R.focus(),c.onkeypress=function(e,g){return function(h){13==h.keyCode&&(b=g.value,g.value="",dc(e,b))}}(this,c),!0;case "debugEnter":return this.H[b]=c,Ga(c,function(){return d.R?(b=d.R.value,dc(d,b),!0):!1}),!0;case "step":return this.H[b]=c,Ga(c,function(e){var g=!1;$a(d,!0)||(N(d,!0),g=d.step(e?1:0),N(d,!1));return g}),!0}return!1};
f.ca=function(a,b,c){this.a=a;this.K=b;this.sa=c-b+1;this.Ha=this.K+this.sa;this.U()};f.ja=function(a,b){a&&!this.D.O&&(this.D.O=!0,this.u=P(b,"cpu"))};f.da=function(){this.R.focus()};
function cc(a,b){a.N=0;a.s=1;a.m=2;a.w=3;a.Oa=4;a.lb=5;a.g=6;a.W=7;a.C=8;a.I=9;a.P=10;a.b=11;a.ea=a.Oa;var c="";if(b)for(a.la="A #$nn $nnnn,X $nnnn,Y $nnnn ($nnnn) $nn,X $nn,Y ($nn,X) ($nn),Y $nnnn $nn".split(" "),b=0;b<a.la.length;b++){var d=a.la[b];c+="("+d.replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\$/g,"\\$")+"|)"}else for(a.la="A nn [nnnn+X] [nnnn+Y] nnnn [nnnn] [nn+X] [nn+Y] [[nn+X]] [[nn]+Y] [nnnn] [nn]".split(" "),
b=0;b<a.la.length;b++)d=a.la[b],c+="("+d.replace(/\[/g,"\\[").replace(/]/g,"\\]").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\+/g,"\\+")+"|)";a.Le=new RegExp(c);a.Ob=[27,a.Pa,9,7,11,12,3,4,8,5]}f.ba=function(){this.u.ba()};function W(a,b,c,d,e,g,h){(a.ma&e)==e&&(e=a.u.S(c),a.message(b.id+"."+(g?"setByte":"getByte")+"("+z(c)+")"+(void 0!==d?" @"+z(d):"")+": "+(h?h+"=":"")+w(e)))}f.message=function(a){this.l(a);pb(this.u)};
f.va=function(){if(!ec(this))return!1;this.u.va();return!0};f.step=function(a){if(!ec(this))return!1;try{var b=this.u.step(a)}catch(c){b=void 0,Za(this.u,c.stack||c.message)}void 0!==b&&this.L++;this.u.update(!0);this.update(!0);return b};f.update=function(a){this.ua=this.u.f;a||this.Aa?fc(this):gc(this)};function ec(a){a.u&&M(a.u)&&!$a(a.u)?(a=a.u,a.D.error?(a.l(a.toString()+" error"),a=!0):a=!1,a=!a):a=!1;return a}
f.reset=function(){var a;this.xa.length||(this.xa=Array(1E3));for(a=0;a<this.xa.length;a++)this.xa[a]=-1;this.B.length||(this.B=Array(256));for(a=0;a<this.B.length;a++)this.B[a]=[a,0];this.L&&this.update();this.L=0};f.start=function(){this.Aa||this.l("running")};f.stop=function(a,b){this.Aa||(this.l("stopped"),b&&this.l(za()-a+"ms ("+b+" cycles)"));this.update();this.da();this.Aa||(this.L=0);hc(this,this.u.f)};function ic(a,b){return a+(b<<24>>24)}
f.S=function(a){if(a>=this.K&&a<this.Ha){ib(this.u,a);var b=this.a[this.K+a];b&=255}return b};function jc(a,b,c){b<a.K||b>=a.Ha?a.l("invalid address: "+z(b)):(a.a[a.K+b]=c&255,jb(a.u,b),a.u.update())}function kc(a,b){Y(a.pa,b,void 0)||a.pa.push(b);return!0}function Y(a,b,c){for(var d=!1,e=0;e<a.length;e++)if(a[e]==b){c&&a.splice(e,1);d=!0;break}return d}function lc(a,b){void 0!==b&&(hc(a,a.M),kc(a,b)&&(a.M=b))}function hc(a,b){void 0!==a.M&&b==a.M&&Y(a.pa,a.M,!0)&&(a.M=void 0);a.Aa=!1}
function ob(a,b,c,d){for(var e=!1,g=0;g<c.length;g++)if(c[g]==b){b!=a.M&&a.l("breakpoint hit: "+z(b)+" ("+d+")");e=!0;break}return e}
function mc(a,b,c){var d=v(b,4),e=a.S(b++),g=void 0===e?0:e,h=a.ha[g],l=[],k=void 0===h[1]?0:h[1];do{d+=" "+v(g,2);if(!k--)break;g=a.S(b++);if(void 0===g)break;l.push(g)}while(1);void 0===h[0]&&(h=[57,1,a.s],l.push(e));d=(d+"        ").substr(0,15);d+=a.Ka[h[0]];var m=null;if(void 0!==h[2]){k=h[2];m=a.la[k];if(1==h[1]&&k==a.ea)m=m.replace(/nnnn/,v(ic(b,g=l.pop()),4));else for(;l.length;)m=m.replace(/nn/,v(g=l.pop(),2));k==a.s&&1==h[1]&&32<=g&&128>g&&(m+=" ;'"+String.fromCharCode(g)+"'")}if(e==a.u.$a&&
(g<a.X.length&&(m=a.X[g]),g==a.u.Oe)){k=0;for(m='"';g=a.S(b++);)16>k?m+=String.fromCharCode(g):16==k&&(m+="\u2026"),k++;m+='"'}m&&(d+=" "+m);c&&(d=(d+"               ").substr(0,30),d+=";"+c.toString());a.Z=b;return d}
function Z(a,b){var c=a.ua;if(void 0!==b){var d=16;"$"==b.charAt(0)?b=b.substr(1):"0x"==b.substr(0,2)?b=b.substr(2):"."==b.charAt(b.length-1)&&(d=10,b=b.substr(0,b.length-1));c=parseInt(b,d);isNaN(c)&&(a.l("invalid base-"+d+" address: "+b),c=void 0)}void 0!==c&&(c<a.K||c>=a.Ha)&&(a.l("address out of range: "+v(c)),c=void 0);return c}
function nc(a,b){if("?"==b)a.l("\nfrequency commands:"),a.l("clear\tclear all frequency counts");else{var c=0;if(a.B)if("clear"==b){for(b=0;b<a.B.length;b++)a.B[b]=[b,0];a.l("frequency data cleared");c++}else if(void 0!==b)a.l("unknown frequency command: "+b),c++;else{var d=a.B.slice();d.sort(function(h,l){return l[1]-h[1]});for(b=0;b<d.length;b++){var e=d[b][0],g=d[b][1];g&&(a.l(a.Ka[a.ha[e][0]]+" ("+w(e)+"): "+g+" times"),c++)}}c||a.l("no frequency data available")}}
function fc(a,b,c,d){var e=Z(a,b);if(void 0!==e){void 0===d&&(d=1);b=a.Ha;if(void 0!==c){b=Z(a,c);if(void 0===b||b<e)return;if(256<b-e){a.l("range too large");return}b++;d=-1}for(e!=a.ua&&a.l();d--&&e<b;)c=mc(a,e,$a(a,!1)||a.Aa?a.L:0),a.l(c),a.ua=e=a.Z}}
function gc(a,b){if(b&&"?"==b[1])a.l("\nregister commands:"),a.l("r to display all"),a.l("r [target=value] to modify"),a.l("supported targets:"),a.l("A,X,Y,S,PC and flags C,Z,D,V,N");else{var c=!0;if(void 0!==b&&1<b.length){c=!1;var d=b[1],e=d.indexOf("=");if(0<e)b=d.substr(e+1),d=d.substr(0,e);else if(2<b.length)b=b[2];else{a.l("missing value for "+b[1]);return}e=parseInt(b,16);if(isNaN(e)){a.l("invalid value: "+b);return}switch(d.toUpperCase()){case "A":a.u.h=e&255;break;case "X":a.u.A=e&255;break;
case "Y":a.u.F=e&255;break;case "C":a.u.c=e?256:0;break;case "Z":a.u.j=e?0:1;break;case "D":e?rb(a.u):sb(a.u);break;case "V":e?(d=a.u,d.s=0,d.w=128):(d=a.u,d.s=0,d.w=0);break;case "N":a.u.i=e?128:0;break;case "S":if(256!=(e&-256)){a.l("invalid stack pointer: "+b);return}a.u.G=e;break;case "PC":c=!0;a.u.f=e&65535;a.ua=a.u.f;break;default:a.l("unknown register: "+d);return}a.u.update()}a.l("A="+v(a.u.h,2)+" X="+v(a.u.A,2)+" Y="+v(a.u.F,2)+" P="+v(mb(a.u),2)+" S="+v(a.u.G,4)+" PC="+v(a.u.f,4));c&&fc(a,
v(a.ua=a.u.f,4))}}function oc(a,b){b=void 0===b?1:parseInt(b,10);var c=1==b?0:1;Fa(b,function(d){return function(){return N(d,!0)&&d.step(c)}}(a),function(d){return function(){N(d,!1)}}(a))}
function dc(a,b){b.length||(a.Ta?(a.l("ended assemble @"+v(a.ia,4)),a.ua=a.ia,a.Ta=!1):a.gb&&(b=a.gb));if(M(a)&&!$a(a,!0)&&0<b.length){a.Ta?b="a "+v(a.ia,4)+" "+b:1<b.length&&1!=b.indexOf(" ")&&(b=b.charAt(0).toLowerCase()+" "+b.substr(1));var c=b.split(" ");a.gb=c[0];switch(c[0].toLowerCase()){case "a":var d=Z(a,c[1]);if(void 0!==d)if(a.ia=d,void 0===c[2])a.l("begin assemble @"+z(a.ia)),a.Ta=!0,a.u.update();else{b=c[2];var e=c[3];c=a.ia;d=[];if(void 0!==b){var g;b=b.toUpperCase();"?"==b.charAt(b.length-
1)&&(e="?",b=b.substr(0,b.length-1));for(g=0;g<a.Ka.length&&b!=a.Ka[g];g++);g==a.Ka.length&&(a.l("unknown operation: "+b),g=-1);var h="",l;if(0<=g&&void 0!==e)if(h=e.toUpperCase(),"?"==h){for(e=l=0;e<a.ha.length;e++)a.ha[e][0]===g&&(l||a.l("supported opcodes:"),a.l("     "+v(e,2)+": "+b+(void 0!==a.ha[e][2]?" "+a.la[a.ha[e][2]]:"")),l++);g=-1}else if(l=h.match(a.Le),null!==l&&l[0]==h){for(e=1;e<l.length;e++)if(l[e]==h)if(void 0===k)var k=e-1;else{a.l("too many operand matches (both "+a.la[k]+" and "+
a.la[e-1]+")");g=-1;break}k==a.Oa&&0>a.Ob.indexOf(g)&&(k=a.P);k==a.lb&&27!=g&&(k=a.P)}else a.l("unknown operand: "+h),g=-1;if(0<=g){l=-1;for(e=0;e<a.ha.length;e++)if(a.ha[e][0]===g&&a.ha[e][2]===k)if(0>l)l=e;else{a.l("too many instruction matches (both "+w(l)+" and "+w(e)+")");l=-2;break}if(0<=l){if(d.push(l),void 0!==k)if(b=a.ha[l][1],h=h.match(/[0-9A-F]+/),null!==h)for(h=parseInt(h[0],16),1==b&&k==a.ea&&(h-=c+2,-128>h||127<h)&&(a.l("branch out of range ("+h+")"),d=[],b=0),e=0;e<b;e++)d.push(h&255),
h>>>=8;else b&&a.l("instruction missing "+b+" bytes")}else a.l("unknown instruction: "+b+" "+h)}}k=d;if(k.length){for(c=0;c<k.length;c++)jc(a,a.ia+c,k[c]);a.l(mc(a,a.ia));a.ia+=k.length}}break;case "b":k=c[1];c=c[2];if(void 0===k||"?"==k)a.l("\nbreakpoint commands:"),a.l("bp [a]\tset exec breakpoint at [a]"),a.l("br [a]\tset read breakpoint at [a]"),a.l("bw [a]\tset write breakpoint at [a]"),a.l("bc [a]\tclear breakpoint at [a]"),a.l("bl\tlist all breakpoints");else if(void 0===c&&1<k.length&&(c=
k.substr(1),k=k.charAt(0)),"l"==k){k=0;d=a.pa;for(c=0;c<d.length;c++)a.l("breakpoint enabled: "+z(d[c])+" (exec)"),k++;d=a.wa;for(c=0;c<d.length;c++)a.l("breakpoint enabled: "+z(d[c])+" (read)"),k++;d=a.ya;for(c=0;c<d.length;c++)a.l("breakpoint enabled: "+z(d[c])+" (write)"),k++;k||a.l("no breakpoints")}else void 0===c?a.l("missing breakpoint address"):"c"==k&&"*"==c?(a.pa=[],a.wa=[],a.ya=[],a.l("all breakpoints cleared")):(c=Z(a,c),void 0!==c&&("p"==k?kc(a,c)?a.l("breakpoint enabled: "+z(c)+" (exec)"):
a.l("breakpoint not set: "+z(c)):"c"==k?Y(a.pa,c,!0)?a.l("breakpoint cleared: "+z(c)+" (exec)"):Y(a.wa,c,!0)?a.l("breakpoint cleared: "+z(c)+" (read)"):Y(a.ya,c,!0)?a.l("breakpoint cleared: "+z(c)+" (write)"):a.l("breakpoint missing: "+z(c)):"r"==k?(Y(a.wa,c,void 0)||a.wa.push(c),a.l("breakpoint enabled: "+z(c)+" (read)")):"w"==k?(Y(a.ya,c,void 0)||a.ya.push(c),a.l("breakpoint enabled: "+z(c)+" (write)")):a.l("unknown breakpoint command: "+k)));break;case "d":k=c[1];d=c[2];if("?"==k)a.l("\ndump commands:"),
a.l("d [a] [#]    dump # lines of memory");else if(k=Z(a,k),void 0!==k){c=0;void 0!==d&&("l"==d.charAt(0)&&(d=d.substr(1)),c=parseInt(d,10));c||(c=1);for(d=0;d<c;d++){h=b="";e=k;for(g=0;8>g&&k<a.Ha;g++)l=a.S(k),void 0===l&&(l=0),b+=v(l,2)+" ",h+=32<=l&&127>l?String.fromCharCode(l):".",k++;a.l(v(e,4)+" "+b+h)}a.ua=k}break;case "e":k=c[1];if(void 0===k)a.l("missing address");else if(k=Z(a,k),void 0!==k)for(d=2;d<c.length;d++)b=parseInt(c[d],16),jc(a,k++,b);break;case "f":nc(a,c[1]);break;case "g":k=
c[1];void 0!==k&&lc(a,Z(a,k));a.va()||a.u.da();break;case "h":a.ba();break;case "o":if(void 0===c[1]||"?"==c[1])a.l("\noption commands:"),a.l("max\trun at maximum speed"),a.l("fast\trun faster (up to "+a.u.Ja+"Mhz)"),a.l("slow\trun at normal speed (1Mhz)"),a.l("classic\tuse classic operand syntax"),a.l("modern\tuse modern operand syntax"),a.l("msg\tenable message categories");else switch(k=c[1],k){case "slow":Q(a.u,a.u.Qa);break;case "fast":Q(a.u,a.u.Pe);break;case "max":Q(a.u,a.u.Qe);break;case "classic":cc(a,
!0);a.l("classic syntax enabled");break;case "modern":cc(a,!1);a.l("modern syntax enabled");break;case "msg":k=0;void 0!==c[2]&&("all"==c[2]?k=255:void 0!==a.Ra[c[2]]&&(k=a.Ra[c[2]]),k&&("on"==c[3]?a.ma|=k:"off"==c[3]&&(a.ma&=~k)));for(d in a.Ra)if(void 0===c[2]||"all"==c[2]||c[2]==d)k=a.Ra[d],a.l(d+" messages: "+(a.ma&k?"on":"off"));break;default:a.l("unknown option: "+k)}break;case "p":h=c[1];k=10;c=a.Ma;d=a.xa;if(void 0!==d){b=void 0===h?a.Qb:parseInt(h,10);void 0===b&&(b=10);b>d.length&&(a.l("note: only "+
d.length+" available"),b=d.length);void 0!==h&&(a.fb=0,a.l(b+" instructions earlier:"));h=a.fb?a.fb:1;c-=b;for(0>c&&(c=d.length-1);k&&c!=a.Ma;){e=d[c];if(0>e)break;a.l(mc(a,e,h++));++c==d.length&&(c=0);k--;b--}a.Qb=b;a.fb=h}10==k&&a.l("no history available");break;case "r":gc(a,c);break;case "s":a.S(a.u.f)==a.u.Pa?(lc(a,a.u.f+3),a.Aa=!0,a.va()||a.u.da()):oc(a);break;case "t":oc(a,c[1]);break;case "u":fc(a,c[1],c[2],8);break;case "?":case "help":a.l("\ncommands:\n?\thelp\na [#]\tassemble\nb [#]\tbreakpoint\nd [#]\tdump memory\ne [#]\tedit memory\nf\tdump frequencies\ng [#]\trun to [#]\nh\thalt\no\toptions\np [#]\tdump history\nr\tdump/edit registers\ns\tstep over instruction\nt [#]\tstep instruction(s)\nu [#]\tunassemble");
a.l("note: frequency and history commands operate only when breakpoints are set");break;default:a.l("unknown command: "+b)}}}E(function(){for(var a=J(document,"c1p","debugger"),b=0;b<a.length;b++){var c=a[b],d=K(c);d=new bc(d);I(d,c)}});function pc(a,b){G.call(this,"C1PComputer",a);this.aa=b}u(pc,G);pc.prototype.reset=function(a){var b=null,c;for(c in this.aa)for(var d=0;d<this.aa[c].length;d++){var e=this.aa[c][d];e&&e.reset&&(e.reset(),"cpu"==c&&(b=e))}b&&(b.update(),a&&b.va())};
pc.prototype.start=function(){for(var a in this.aa)if("cpu"!=a)for(var b=0;b<this.aa[a].length;b++){var c=this.aa[a][b];c&&c.start&&c.start()}};pc.prototype.stop=function(a,b){for(var c in this.aa)if("cpu"!=c)for(var d=0;d<this.aa[c].length;d++){var e=this.aa[c][d];e&&e.stop&&e.stop(a,b)}};pc.prototype.T=function(a,b,c){switch(b){case "reset":return this.H[b]=c,c.onclick=function(d){return function(){d.reset()}}(this),!0}return!1};function P(a,b){return a.aa[b]?a.aa[b][0]:null}
function qc(a){var b=null,c;for(c in a.aa)for(var d=0;d<a.aa[c].length;d++){var e=a.aa[c][d];if(e){if(!M(e)){M(e,function(g){return function(){qc(g)}}(a));return}"cpu"==c?b=e:e.ja&&e.ja(!0,a)}}a.U();a.l("C1Pjs v2.00\nCopyright \u00a9 2012-2020 Jeff Parsons <Jeff@pcjs.org>");b&&b.ja(!0,a)}
E(function(){for(var a=J(document,"c1p","computer"),b=0;b<a.length;b++){for(var c=a[b],d=K(c),e,g={},h,l=0,k=0,m=0;m<d.modules.length;m++){var n=d.modules[m];if(!m){if("cpu"!=n.type)break;l=+n.start;k=+n.end;h=Array(k+1-l);for(e=l;e<h.length;e++)h[e]=0}if(e=Pa(n.refID,d.id)){var p=n.type;void 0===g[p]&&(g[p]=[]);g[p].push(e);e.ca&&void 0!==n.start&&e.ca(h,+n.start,+n.end,g.cpu[0])}else{B('no component for <module refid="'+n.refID+'">');return}}if(void 0===h){B('<module type="cpu"> definition must appear first in the <computer> specification');
break}if(e=Pa("debugger",d.id))g["debugger"]=[e],e.ca&&e.ca(h,l,k,g.cpu[0]);l=new pc(d,g);if(k=Pa("panel",d.id))if(g.panel=[k],k.H.print){e=void 0;d=d.id;g=[];d&&(d=0<(e=d.indexOf("."))?d.substr(0,e+1):"");for(e=0;e<H.length;e++)m=H[e],d&&m.id.indexOf(d)||g.push(m);d=g;for(g=0;g<d.length;g++)e=d[g],e!=k&&(e.Wa=k.Wa,e.print=k.print,e.l=k.l)}I(l,c);qc(l)}});var rc=0;
function sc(a,b,c,d,e,g){e("Loading "+a+"...");A(a,function(h,l,k){k?(l||(l="unable to load "+a+" ("+k+")"),g(h,l,null)):tc(l,a,b,c,d,e,g)})}
function tc(a,b,c,d,e,g,h){function l(m,n,p){if(p)h(m,p,null);else{c&&(ab[c]&&b&&(ab[c][b]=n),(p=b)&&0>p.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(p=window.location.pathname+p),k?"}"==k.slice(-1)?(k=k.slice(0,-1),1<k.length&&(k+=",")):k='{state:"'+k+'",':k="{",k+='url:"'+p+'"}',"object"==typeof resources&&(p=null),k=k.replace(/\$/g,"$$$$").replace(/'/g,"&apos;"),d&&(m=n.match(/(<machine[^>]*\sclass=)(['"])(.*?)(\2[^>]*>)/))&&(n=n.replace(m[0],m[1]+m[2]+d+m[4]),d=""),(m=n.match(/(<machine[^>]*\sdebugger=)(['"])(available)(\2[^>]*>)/))&&
(n=n.replace(m[0],m[1]+m[2]+"optional"+m[4])),n=n.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(d?' class="'+d+'"':"")+(k?" parms='"+k+"'":"")+(p?' url="'+p+'"':"")));e||(n=n.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1C1Pjs$2"),n=n.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1c1p$2"));m=null;if("<"==n.charAt(0))try{e||(n=n.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(m=new window.ActiveXObject("Microsoft.XMLDOM"),
m.async=!1,m.loadXML(n)):m=(new window.DOMParser).parseFromString(n,"text/xml")}catch(t){m=null,n=t.message}else n="unrecognized XML: "+(255<n.length?n.substr(0,255)+"...":n);h(b,n,m)}}var k="";a?e?uc(b,a,g,l):l(b,a,""):h(b,"no data",null)}
function uc(a,b,c,d){var e;if(e=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(b)){var g=e[2];c("Loading "+g+"...");A(g,function(h,l,k){if(k||!l)d(h,b,"unable to resolve XML reference: "+e[0]+" ("+k+")");else{if(k=e[3]){var m=l.match(new RegExp("<"+e[1]+"[^>]*>"));if(m){for(var n=m[0],p,t=/( [a-z]+=)(['"])(.*?)\2/gi;p=t.exec(k);)n=0>n.toLowerCase().indexOf(p[1].toLowerCase())?n.replace(">",p[0]+">"):n.replace(new RegExp(p[1]+"(['\"])(.*?)\\1"),p[0]);m[0]!=n&&(l=l.replace(m[0],n))}else{d(h,b,"missing <"+
e[1]+"> in "+g);return}}l=l.replace(/<\?xml[^>]*>[\r\n]*/,"");b=b.replace(e[0],l);uc(h,b,c,d)}})}else d(a,b,"")}
function vc(a,b,c,d){function e(q){if(void 0===k){var r=l&&J(l,"machine-warning");k=r&&r[0]||l}k&&(k.innerHTML=ra(q))}function g(q,r){if("string"==typeof r&&0<=r.indexOf("<!DOCTYPE html>")){var D=r.match(/<title>(?:PCjs: |)(.*?)<\/title>/);D&&(r=D[1])}e("Error: "+r+(q?" ("+q+")":""));m&&h();m=!1}function h(){--rc||Ka(!0)}var l,k,m=!0;rc++;ab[a]={};if(!b)return h(),m;"true"==Da("debugger")&&0>b.indexOf("/debugger")&&(b=b.replace("/machine.xml","/debugger/machine.xml"));try{if(l=document.getElementById(a)){var n;
if("object"==typeof resources&&(n=resources.css)){var p=document.head||document.getElementsByTagName("head")[0],t=document.createElement("style");t.type="text/css";t.styleSheet?t.styleSheet.cssText=n:t.appendChild(document.createTextNode(n));p.appendChild(t)}c||(c="/configs/c1p/xsl/components.xsl");n=function(q,r,D){D?sc(c||"","","",!1,e,function(y,x,L){if(L){var S=c||"";ab[a]&&S&&(ab[a][S]=x);e("Processing "+b+"...");if(window.ActiveXObject||"ActiveXObject"in window)(L=D.transformNode(L))?(l.outerHTML=
L,h()):g(y,"transformNodeToObject failed");else if(document.implementation&&document.implementation.createDocument)if(x=new XSLTProcessor,x.importStylesheet(L),L=x.transformToFragment(D,document))if(x=l.parentNode){S=y=0;var Ta=l.getBoundingClientRect();0>Ta.bottom&&(y=window.scrollX,S=window.scrollY);x.replaceChild(L,l);(l=document.getElementById(a))&&0>Ta.bottom&&(L=l.getBoundingClientRect(),S=window.performance&&window.performance.navigation.type==window.performance.navigation.TYPE_RELOAD?0:S+
Math.ceil(L.height-Ta.height),window.scrollTo(y,S));h()}else g(y,"invalid machine element: "+a);else g(y,"transformToFragment failed");else g(y,"unable to transform XML: unsupported browser")}else g(y,x)}):g(q,r)};"<"!=b.charAt(0)?sc(b,a,d||"",!0,e,n):tc(b,"",a,d||"",!1,e,n)}else g(b,"missing machine element: "+a)}catch(q){g(b,q.message)}return m}window.embedC1P=function(a,b,c,d,e){Ka(!1);return vc(a,b,c,e)};
window.commandMachine=function(a,b,c,d,e,g){if("script"==e){d=!1;c+=".machine";if(!g)delete Sa[c],d=!0;else if("string"==typeof g&&!Sa[c]){d=!0;e=Sa;for(var h=c,l=g.length,k=[],m=[],n="",p=null,t=0;t<l;t++){var q=g[t];if('"'==q||"'"==q)p&&q!=p?n+=q:(p?p=null:p=q,n&&(m.push(n),n=""));else{if(!p){if("\r"==q||"\n"==q)q=";";if(" "==q||"\t"==q||";"==q){n&&(m.push(n),n="");";"==q&&m.length&&(k.push(m),m=[]);continue}}n+=q}}n&&m.push(n);m.length&&k.push(m);e[h]=k;Ra(c)||(d=!1)}return d?(b&&(a.disabled=!0),
!0):!1}if(d&&(h=Qa(d,c+".machine"))&&(l=h.exports)&&(l=l[e]))return l.call(h,g)?(b&&(a.disabled=!0),!0):!1;console.log("unimplemented: commandMachine('"+c+"','"+d+"','"+e+"','"+g+"')");return!1};window.enableEvents=Ka;window.sendEvent=Ma;})()

//# sourceMappingURL=c1p.js.map
