(function(){/*
 https://www.pcjs.org/modules/defs.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/numio.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/stdio.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/webio.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/device.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/input.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/led.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/time.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/bus.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/memory.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/rom.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/cpu.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/cpu1500.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/machine.js (C) 2012-2025 Jeff Parsons
*/
var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function r(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function t(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function v(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.We=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
t("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});t("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
t("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
t("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}t("Array.prototype.keys",function(a){return a?a:function(){return na(this,function(b){return b})}});
t("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function y(a){return a?a:Array.prototype.fill}t("Int8Array.prototype.fill",y);t("Uint8Array.prototype.fill",y);t("Uint8ClampedArray.prototype.fill",y);t("Int16Array.prototype.fill",y);t("Uint16Array.prototype.fill",y);t("Int32Array.prototype.fill",y);
t("Uint32Array.prototype.fill",y);t("Float32Array.prototype.fill",y);t("Float64Array.prototype.fill",y);t("Number.parseInt",function(a){return a||parseInt});t("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});function oa(){}var pa=new ArrayBuffer(2);(new DataView(pa)).setUint16(0,256,!0);new Uint16Array(pa);var A={$b:0xffffffffffff,NONE:0,ic:0,ya:0x800000000000},C={};C.Defs=oa;function qa(){}v(qa,oa);
function ra(a,b){var c=a/D|0,d=b/D|0;return(a&b)==(b|0)&&(c&d)==d}var D=Math.pow(2,32);C.NumIO=qa;function E(){this.Ia={};for(var a=0;22>a;a++)this.Ia["ACDFHGMNSTWYbdfjcsoXx%"[a]]=null}v(E,qa);p=E.prototype;p.flush=function(){var a=sa;sa="";this.ta(a)};function ta(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}
p.nd=function(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,r(a)));return a};
p.ta=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),ua||(ua=b),a=((b-ua)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(sa+a.substr(0,c)),sa="",a=a.substr(c+1)),ua=null);sa+=a;return a.length};function F(a,b,c){a.ta(b+"\n",c)}p.K=function(a){return this.ta(this.S.apply(this,[a].concat(r(la.apply(1,arguments)))))};
p.S=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(void 0===this.Ia[g])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];"%"!=g&&e++}else h=b[b.length-1];var k=d[f+1],l=0<=k.indexOf("#"),m=0<=k.indexOf("0"),n=d[f+2];"*"==n?(n=h,h=e<b.length?b[e++]:b[b.length-1]):n=+n||0;var q=d[f+3];q=q?+q.substr(1):-1;var w=d[f+4],z=null,x=0,B=
"";var u=0<="ACDFHGMNSTWY".indexOf(g)&&"object"!=typeof h?this.nd(h):h;switch(g){case "C":h=l?"#":"";c+=isNaN(u.getTime())?void 0:this.S(this.S("%%%sW, %%%sF %%%sD, %%%sY",h),u);continue;case "D":h=l?u.getUTCDate():u.getDate();g="d";break;case "A":case "G":case "H":h=l?u.getUTCHours():u.getHours();"A"==g?(h=12>h?"am":"pm",g="s"):("G"==g&&(h=h?12<h?h-12:h:12),g="d");break;case "F":case "M":h=l?u.getUTCMonth():u.getMonth();"F"==g?(h=va[h],g="s"):(h++,g="d");break;case "N":h=l?u.getUTCMinutes():u.getMinutes();
g="d";break;case "S":h=l?u.getUTCSeconds():u.getSeconds();g="d";break;case "T":h=l?"#":"";c+=isNaN(u.getTime())?void 0:this.S(this.S("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),u);continue;case "W":h=wa[l?u.getUTCDay():u.getDay()];g="s";break;case "Y":h=l?u.getUTCFullYear():u.getFullYear(),0<q&&(h%=Math.pow(10,q)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=q&&(m=!0,n<q&&(n=q),q=-1);case "f":h=+h;u=h+"";0<=q&&(u=h.toFixed(q));u.length<n&&(m?(0>h&&(n--,u=u.substr(1)),
u=("0".repeat(n)+u).slice(-n),0>h&&(u="-"+u)):u=(" ".repeat(n)+u).slice(-n));c+=u;break;case "j":c+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=q&&(h=h.substr(0,q));h.length<n;)h=0<=k.indexOf("-")?h+" ":" "+h;c+=h;break;case "o":x=8,l&&(B="0");case "X":z=xa;case "x":u="";x||(x=16);!B&&l&&(B="0x");z||(z=ya);h=Math.trunc(h);0<=q&&(m=!0,n<q&&(n=q));m&&!n&&("b"==w?n=2:"h"==w||"w"==w?
n=4:"l"==w?n=8:(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9),n+=B.length);n-=B.length;do l=h&x-1,h>>>=16==x?4:3,m||!u||l||h?u=z[l]+u:(B&&(u=B+u,B=""),0<n&&(u=" "+u));while(0<--n||h);c+=B+u;break;case "%":c+="%";break;default:c=this.Ia[g]?c+this.Ia[g](g,k,n,q,h):c+("(unimplemented sprintf type: %"+g+")")}}}return c+=d[f]};var sa="",ua=null,ya="0123456789abcdef",xa="0123456789ABCDEF",wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" ");
C.StdIO=E;function G(a){E.call(this);this.T={};this.fa=0;this.O=this;a&&(this.O.fa=0,this.O.ua=[],this.O.ja=0,this.O.Ja={},this.O.Ie=!1)}var za;v(G,E);p=G.prototype;p.Aa=function(a,b){var c=this,d=this;switch(a){case Aa.dc:b.onclick=function(){var e=c.Ca(Aa.$a,!0);e&&(e.value="")};break;case Aa.$a:Ba(b),b.addEventListener("keydown",function(e){Ca(d,e,!0)}),b.addEventListener("keypress",function(e){Ca(d,e)})}};
function Da(a,b){b=void 0===b?{}:b;if("undefined"!=typeof document){a.I.T||(a.I.T=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.X);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.T[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.T[d].push(e)}while(1);continue}if(f=document.getElementById(e))a.T[d]=f,a.Aa(d,f)}}}
function Ba(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}p.error=function(a,b){b=this.S.apply(this,[a].concat(r(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.S.apply(this,[c].concat(r(b))))F(this,b),a||alert(b)};p.Ca=function(a){return this.T[a]};
function Ea(a){var b=window;if(b){do{for(var c=0;c<Fa.length;c++){var d=Fa[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ga(a,b){return a.I.bindings&&a.I.bindings[b]}function Ha(a){if(a=a.T[Ia])var b=a.textContent;return b}function Ja(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function H(a,b,c,d){a=a.I[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Ka(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function La(a){if(void 0===I.Xa){var b=!1;if(window)try{window.localStorage.setItem(I.za,I.za),b=window.localStorage.getItem(I.za)==I.za,window.localStorage.removeItem(I.za)}catch(c){F(a,c.message),b=!1}I.Xa=b}return!!I.Xa}function J(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.fa;return-1==(b|1)||ra(a.O.fa,b)?!0:!1}
function Ma(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Na(a){var b=null;if(La(a)){var c;if(window)try{(c=window.localStorage.getItem(a.L))&&(b=JSON.parse(c))}catch(d){F(a,d.message)}}return b}
function Ca(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.O,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==K.ib&&f.selectionStart<=h+1&&(a=!0);d==K.cd?(a=!0,0<e.ja&&(g=e.ua[--e.ja])):d==K.kc&&(a=!0,e.ja<e.ua.length&&(g=e.ua[++e.ja]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ja&&c+1==g.length&&
(f.value+=e.ua[--e.ja],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Oa(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&F(a,b.replace(/\n$/,""),!1))}}
function Pa(a,b){if(void 0!=b){var c=a.O;try{if(b=b.trim())c.ja<c.ua.length&&b==c.ua[c.ja]?c.ja++:(c.ua.push(b),c.ja=c.ua.length);var d=b.split(" "),e=d[0],f=a.O.Ja[Qa.lb];switch(e[0]){case "m":if("?"==e[1]){var g="";Ra.forEach(function(n){g+=n+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var k="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=k&&d.pop();1>=d.length&&(void 0!=k&&(h=k,k=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(L));for(f=
1;f<d.length;f++){e=d[f];var l=L[e];if(!l){g+="unrecognized message: "+e+"\n";break}void 0!=k&&Sa(a,l,k);if(void 0==h||h==J(a,l))g+=a.S("%8s: %b\n",e,J(a,l))}J(a,A.ya)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ta.forEach(function(n){g+=n+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var m=f[a](d);if(void 0!=m){g=g?g+m:m;break}}}}catch(n){g="error: "+n.message+"\n"}}return g}
function Oa(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Pa(a,b[d])}return c}p.ta=function(a,b){void 0==b&&(b=J(this,A.ya));if(!b){var c=this.Ca(Aa.$a,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Ma("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return E.prototype.ta.call(this,a,b)};
p.K=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return J(this,c)?E.prototype.K.call.apply(E.prototype.K,[this,a].concat(r(b))):0};function Ua(a,b){if(La(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.L,b)}catch(c){F(a,c.message)}}}function M(a,b,c){(a=a.T[b])&&a.textContent!=c&&(a.textContent=c)}
function Sa(a,b,c){var d=!1;c?(c=a.O.fa,a.O.fa=(c|b)+(c/D|0|b/D|0)*D):(d=ra(a.O.fa,A.ya)&&ra(b,A.ya),c=a.O.fa,a.O.fa=(c&~b)+((c/D|0)&~(b/D|0))*D);d&&a.flush()}
var Aa={dc:"clear",$a:"print"},Ta=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Ra=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],L={all:A.$b,buffer:A.ya},Qa={lb:"command"},Va={mb:13,Wa:65,hb:66,jb:67,nb:68,E:69,pb:70,qb:71,rb:72,sb:73,ub:74,wb:75,zb:76,Bb:77,Cb:78,Db:79,Fb:80,Q:81,Gb:82,Ib:83,Jb:84,
Kb:85,Lb:86,Mb:87,Nb:88,Ob:89,bb:90,a:97,b:98,c:99,d:100,e:101,f:102,Oe:103,Pe:104,Qe:105,Re:106,k:107,Se:108,Te:109,n:110,Ue:111,p:112,q:113,r:114,Ve:115,t:116,Xe:117,Ye:118,w:119,x:120,y:121,z:122},K={ib:8,Wc:9,Bc:10,mb:13,Sc:16,fc:17,ac:18,ye:19,Ya:20,Ad:27,Uc:32,Be:33,Ae:34,zd:35,Vd:36,Ab:37,cd:38,ab:39,Sd:39,kc:40,Pd:44,Ce:44,Wd:45,yd:46,Rd:46,Ud:47,ZERO:48,ONE:49,ad:50,Xc:51,vc:52,uc:53,Tc:54,Rc:55,lc:56,Hc:57,sc:59,rc:61,Wa:65,hb:66,jb:67,nb:68,E:69,pb:70,qb:71,rb:72,sb:73,ub:74,wb:75,zb:76,
Bb:77,Cb:78,Db:79,Fb:80,Q:81,Gb:82,Ib:83,Jb:84,Kb:85,Lb:86,Mb:87,Nb:88,Ob:89,bb:90,kb:91,Qd:91,Od:92,Fe:93,Td:93,$d:96,qe:96,Nd:96,ae:97,oe:97,be:98,ne:98,ce:99,te:99,de:100,re:100,ee:101,ke:101,fe:102,ve:102,ge:103,pe:103,he:104,xe:104,ie:105,ue:105,se:106,je:107,we:109,le:110,me:111,Bd:112,Fd:113,Gd:114,Hd:115,Id:116,Jd:117,Kd:118,Ld:119,Md:120,Cd:121,Dd:122,Ed:123,Ic:144,Oc:145,qc:173,Pc:186,mc:187,wd:188,hc:189,ze:190,He:191,ud:192,Xd:219,vd:220,Ee:221,De:222,pc:224,Yd:901,Je:1E3},Wa={},Xa=(Wa[K.sc]=
K.Pc,Wa[K.rc]=K.mc,Wa[K.qc]=K.hc,Wa[K.pc]=K.kb,Wa),Ya={Ab:1,ab:2,Zd:3},N={},Za=(N[K.ib]="\b",N[K.Wc]="\t",N[K.Bc]="\n",N[K.mb]="\r",N[K.Uc]=" ",N[K.ZERO]="0",N[K.ONE]="1",N[K.ad]="2",N[K.Xc]="3",N[K.vc]="4",N[K.uc]="5",N[K.Tc]="6",N[K.Rc]="7",N[K.lc]="8",N[K.Hc]="9",N[K.Wa]="A",N[K.hb]="B",N[K.jb]="C",N[K.nb]="D",N[K.E]="E",N[K.pb]="F",N[K.qb]="G",N[K.rb]="H",N[K.sb]="I",N[K.ub]="J",N[K.wb]="K",N[K.zb]="L",N[K.Bb]="M",N[K.Cb]="N",N[K.Db]="O",N[K.Fb]="P",N[K.Q]="Q",N[K.Gb]="R",N[K.Ib]="S",N[K.Jb]=
"T",N[K.Kb]="U",N[K.Lb]="V",N[K.Mb]="W",N[K.Nb]="X",N[K.Ob]="Y",N[K.bb]="Z",N[K.Ab]="Left",N[K.ab]="Right",N),Fa=["","moz","ms","webkit"],$a={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},I={Xa:void 0,za:"PCjs.localStorage"};C.WebIO=G;
function O(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;G.call(this,a==b);this.L=a;this.X=b;P[this.L]||(P[this.L]={});P[this.L][this.X]&&this.K("warning: machine configuration contains multiple '%s' devices\n",this.X);P[this.L][this.X]=this;this.id=this.L==this.X?this.L:this.L+"."+this.X;ab.push(this);this.O=bb(this,this.L);this.ready=!0;cb(this,c,d);this.Vc={};this.yb=[]}v(O,G);
function cb(a,b,c){c=b.overrides||c;if(c.length){var d,e=za;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,h=/([^&=]+)=?([^&]*)/g;f=h.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}za=e}d=e;for(var k in d)if(0<=c.indexOf(k)){e=d[k];f=void 0;var l;g=void 0;h=e;var m=10;if(h){m||(m=10);var n=0<h.indexOf(",");n&&(h=h.replace(/,/g,""));var q=l=h.charAt(0);"#"==l?(m=8,l=""):"$"==l&&(m=16,l="");q!=l?h=h.substr(1):
(q=l=h.substr(0,2),"0b"==l&&n||"^B"==l?(m=2,l=""):"0o"==l||"^O"==l?(m=8,l=""):"^D"==l?(m=10,l=""):"0x"==l&&(m=16,l=""),q!=l&&(h=h.substr(2)));q=l=h.slice(-1);"Y"==l||"y"==l?(m=2,l=""):"."==l?(m=10,l=""):"H"==l||"h"==l?(m=16,l=""):"K"==l?l="000":"M"==l?l="000000":"G"==l&&(l="000000000");q!=l&&(h=h.slice(0,-1)+l);q=0;10>=m&&(l=h.match(/(-?[0-9]+)B([0-9]*)$/))&&(h=l[1],q=35-((l[2]||35)&255));(m&&10!=m?16==m?null===h.match(/^-?[0-9a-f]+$/i):8==m?null===h.match(/^-?[0-7]+$/):2!=m||null===h.match(/^-?[01]+$/):
null===h.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(h,m))||(q&&(0>f&&(f+=Math.pow(2,36)),f=0<q?f*Math.pow(2,q):Math.trunc(f/Math.pow(2,-q))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[k]=f;F(a,"overriding "+a.X+" property '"+k+"' with "+e)}}a.I=b;Da(a,b.bindings);b=void 0===b?{}:b;a.version=2;if(a.version){c="";var w;a.L!=a.X&&(w=bb(a,a.L).version)&&w!=a.version&&(c="Machine");c||(w=b.version)&&w>a.version&&(c="Config");c&&(w=a.S("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.Le,a.version,c,w),a.error("%s\n\nClearing your browser's cache may resolve the issue.",w))}}function db(a,b){var c;try{var d=P[a.L];if(d)for(c in d){var e=d[c];if(e.X!=e.L&&!b(e))return!1}return!0}catch(f){a.K("error while enumerating device '%s': %s\n",c,f.message)}return!1}O.prototype.Ca=function(a,b){b=void 0===b?!1:b;if(a){var c=G.prototype.Ca.call(this,a,b);if(void 0===c&&b){b=P[this.L];for(var d in b)if(c=b[d].T[a])break;c||(c=null);this.T[a]=c}}return c};
function bb(a,b,c){var d=b,e=a.L,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=P[e])&&f[b]||null;if(!b){for(f=0;f<ab.length;f++)if(ab[f].id===d){b=ab[f];break}if(!b&&(void 0===c||c))throw Error(a.S('no "%s" device',d));}return b}function Q(a,b,c){var d=null,e=P[a.L];if(e)for(var f in e)if(e[f].I["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.S("no %s device",b));return d}function eb(a){return a==a.O&&a.ready?db(a,function(b){return eb(b)}):a.ready}
function fb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(eb(a)){for(;b=a.yb.pop();)b();a!=a.O&&fb(a.O)}}function gb(a,b){if(eb(a))return b(),!0;a.yb.push(b);return!1}
O.prototype.K=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&J(this,a)&&(void 0===this.pa&&(this.pa=Q(this,"Debugger",!1)),this.O.fa&A.gb&&(void 0===this.da&&(this.da=Q(this,"CPU")),this.da))?(a=b.shift(),G.prototype.K.call(this,"%#06x: %s.%s\n",this.da.Ta,this.X,this.S.apply(this,[a].concat(r(b))).trim())):G.prototype.K.call.apply(G.prototype.K,[this,a].concat(r(b)))};function hb(a,b){(a=P[a.L])&&delete a[b]}O.prototype.Vb=function(a,b){(a=this.Vc[a])&&a.set&&a.set(b)};
"undefined"!=typeof window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]));var P="undefined"!=typeof window?window.PCjs.Machines:{},ab="undefined"!=typeof window?window.PCjs.Components:[];A.gb=1;A.bc=2;A.oc=4;A.Cc=8;A.Jc=16;A.cc=32;A.Ac=64;A.Qc=128;A.Dc=256;A.ec=512;A.Ec=1024;A.INT=2048;A.$c=4096;A.dd=8192;A.Fc=16384;A.Nc=32768;A.jc=65536;A.tc=131072;A.Ma=262144;A.Yc=524288;A.ob=1048576;A.tb=2097152;A.xb=4194304;
A.Gc=8388608;A.Zc=16777216;A.xc=33554432;A.Na=67108864;A.nc=134217728;A.wc=268435456;A.xd=4294967296;L.addr=A.gb;L.bus=A.bc;L.fault=A.oc;L.memory=A.Cc;L.ports=A.Jc;L.chips=A.cc;L.kbd=A.Ac;L.serial=A.Qc;L.misc=A.Dc;L.cpu=A.ec;L.mmu=A.Ec;L["int"]=A.INT;L.trap=A.$c;L.video=A.dd;L.monitor=A.Fc;L.screen=A.Nc;L.disk=A.jc;L.file=A.tc;L.time=A.Ma;L.timer=A.Yc;L.event=A.ob;L.input=A.tb;L.key=A.xb;L.mouse=A.Gc;L.touch=A.Zc;L.info=A.xc;L.warn=A.Na;L.error=A.nc;L.halt=A.wc;C.Device=O;
function ib(a,b,c){O.call(this,a,b,c);this.fa=A.tb;this.J=this.N=null;this.time=Q(this,"Time");this.O=Q(this,"Machine");this.ba=H(this,"drag",!1);this.Y=H(this,"scroll",!1);this.aa=H(this,"hexagonal",!1);this.s=H(this,"releaseDelay",0);this.u=!1;a=this.I.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.j[f]={keys:g,grid:e,
state:0}}}this.R=[];this.U=[];this.m=this.V=null;(a=this.T[jb])&&kb(this,a,this.Ca(c.focusBinding,!0),this.I.location);this.qa()}v(ib,O);function lb(a,b){a.N=b}function mb(a,b,c){for(var d=0;d<a.R.length;d++){var e=a.R[d];e.id===b&&e.Tb(b,c)}}
function kb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.sd=d[0]||0;e.td=d[1]||0;e.Ba=d[2]||b.clientWidth;e.Pa=d[3]||b.clientHeight;e.Qa=d[4]||1;e.Ua=d[5]||1;e.hd=d[6]||b.naturalWidth||e.Ba;e.kd=d[7]||b.naturalHeight||e.Pa;e.Yb=d[8]||0;e.Zb=d[9]||0;e.gd=d[10]||0;e.jd=d[11]||0;a.h?(e.Sa=a.h.length,e.Da=a.h[0].length):(e.Da=e.Qa,e.Sa=e.Ua,e.Qa=e.Ua=0);e.Pb=e.Ba/(e.Da+e.Da*e.Qa)|0;e.Qb=e.Pa/(e.Sa+e.Sa*e.Ua)|0;e.fd=e.Pb*e.Qa|0;e.Rb=e.Qb*e.Ua|0;e.Ha=e.Va=-1;nb(a,b,e);ob(a,b,e);a.time&&
a.s&&(a.$=pb(a.time,"timerInputRelease",function(){0>e.Ha&&0>e.Va&&qb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.s&&(a.ca=pb(a.time,"timerKeyRelease",function(){rb(a)})),a.v=0,a.M="",a.H=[],d=b,c&&(d=c,a.m||"BUTTON"!=c.nodeName||(d=document,a.m=c,sb(a,b),a.V=b)),sb(a,d),a.m||(a.m=d)}function tb(a){a.s?ub(a.time,a.ca,a.s):rb(a)}
function sb(a,b){function c(e,f,g){var h=document.activeElement;a.K(A.xb+A.ob,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.m&&e!=a.m&&e!=a.V?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=vb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=vb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=vb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function nb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.u){var e=a.m;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,wb,d,c)}});b.addEventListener("mousemove",function(d){a.u||R(a,b,xb,d,c)});b.addEventListener("mouseup",function(d){a.u||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.u||(0>c.Ha?R(a,b,xb,d,c):R(a,b,S,d,c))})}
function ob(a,b,c){b.addEventListener("touchstart",function(d){a.Y&&(a.u=!0);R(a,b,wb,d,c)});b.addEventListener("touchmove",function(d){R(a,b,xb,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function vb(a,b,c,d){if(void 0!=c){var e=Xa[b]||b;var f=Za[b];var g=yb[e];d=d&&d.location==Ya.ab;g&zb&&d&&(g>>=1);g&&(g&Ab&&(c=!(a.g&g)),a.g=c?a.g|g:a.g&~g,mb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=Va.Wa&&b<=Va.bb?a.g&(Bb|Cb)||(a.g|=Cb,mb(a,K.Ya,!0)):b>=Va.a&&b<=Va.z&&a.g&Cb&&(a.g&=~Cb,mb(a,K.Ya,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(g=a.h[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.v?16>a.H.length&&a.H.push(b):(a.v=1,a.M=f,qb(a,d,e),mb(a,
f,!0),tb(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(g=b[e],0<=a.j[g].keys.indexOf(f))return mb(a,g,c),a.j[g].state=c?1:0,!0}return!1}function rb(a){1==a.v?(a.v++,mb(a,a.M,!1),a.M="",qb(a,-1,-1),tb(a)):(a.v=0,a.H.length&&vb(a,a.H.shift()))}ib.prototype.qa=function(){this.g=0;this.W=this.Z=-1};
function R(a,b,c,d,e){var f=-1,g=-1,h=!1,k=-1,l=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,l=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(k=d.clientX,l=d.clientY);var m=d.target.getBoundingClientRect();k-=m.left;l-=m.top;k=e.hd/b.offsetWidth*k|0;l=e.kd/b.offsetHeight*l|0;var n=k-e.sd;var q=l-e.td;var w=m=!1;var z=k>=e.Yb&&k<e.Yb+e.gd&&l>=e.Zb&&l<e.Zb+e.jd;if(0<=n&&n<e.Ba&&0<=q+e.Rb||z)if(h||a.Y||d.preventDefault(),0<=n&&n<e.Ba&&0<=
q&&q<e.Pa){w=!0;d=e.Ba/e.Da|0;var x=e.Pa/e.Sa|0,B=n/d|0,u=q/x|0;!a.aa||u&1||(n-=d>>1,B=n/d|0,B==e.Da-1&&(n=-1));x=u*x+(e.Rb>>1);n-=B*d+(e.fd>>1);q-=x;0<=n&&n<e.Pb&&0<=q&&q<e.Qb&&(f=B,g=u,m=!0)}}n=n||0;q=q||0;d=b.offsetWidth;b=b.offsetHeight;if(c==wb||c==S)for(B=0;B<a.U.length;B++)u=a.U[B],c==S?u.Tb(u.id,!1):(x=q/(b/u.Ne|0)|0,(n/(d/u.Me|0)|0)==u.Ze&&x==u.$e&&u.Tb(u.id,!0));if(!h)if(c==wb)e.Ha=k,e.Va=l,w?(qb(a,f,g),m&&a.s&&ub(a.time,a.$,a.s,!0)):z&&a.O.ha();else if(c==xb)0<=e.Ha&&0<=e.Va&&a.ba?qb(a,
f,g):a.N&&a.N(f,g);else if(c==S){if(c=a.s)c=a.time,f=a.$,c=c.g&&0<f&&f<=c.h.length?0<=c.h[f-1].ga:!1;c||qb(a,-1,-1);e.Ha=e.Va=-1}else F(a,"unrecognized action: "+c)}function qb(a,b,c){if(b!=a.W||c!=a.Z)a.W=b,a.Z=c,a.J&&a.J(b,c)}var wb=1,xb=2,S=3,jb="surface",Bb=3,zb=170,Cb=512,Ab=3584,T={},yb=(T[K.Sc]=2,T[K.fc]=8,T[K.ac]=32,T[K.kb]=128,T[K.Ya]=Cb,T[K.Ic]=1024,T[K.Oc]=2048,T);C.Input=ib;
function Db(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.T[Eb];if(!a)throw Error("LED "+this.I.T[Eb]+" binding for '"+Eb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.va=Ga(this,Eb)+".canvas";b.setAttribute("id",this.va);this.Za=a;this.type=Ja(H(this,"type",Fb,Gb),Hb,Ib);this.m=Jb[this.type][0];this.H=Jb[this.type][1];this.width=H(this,"width",
this.m);this.height=H(this,"height",this.H);this.s=H(this,"cols",1);this.R=this.s+H(this,"colsExtra",0);this.ba=H(this,"rows",1);this.W=this.ba+H(this,"rowsExtra",0);this.ea=this.width*this.s;this.Z=this.height*this.ba;this.v=Kb("black",0);this.j=Lb(this.I.color)||this.v;this.ma=Kb(this.j,1,.25);this.la=Kb(this.j,1,2);this.u=Lb(this.I.backgroundColor);this.na=H(this,"fixed",!1);this.na||(b.style.width="100%",b.style.height="auto");this.ka=H(this,"hexagonal",!1);this.sa=H(this,"highlight",!0);this.Y=
H(this,"persistent",this.type<Ib);b.setAttribute("width",this.ea.toString());b.setAttribute("height",this.Z.toString());b.style.backgroundColor=this.v;a.appendChild(b);this.ia=b.getContext("2d");if(this.J=document.createElement("canvas"))this.J.width=this.ca=this.m*this.s,this.J.height=this.M=this.H*this.ba,this.h=this.J.getContext("2d");this.wa=(this.W+1)*this.R*4;this.g=Array(this.wa);this.Ka=this.s<this.R?4*(this.R-this.s):0;this.U=this.V=!1;this.N=this.aa=0;this.$=-1;var d=this;this.time=Q(this,
"Time");Mb(this.time,function(e,f){Nb(d,!1,e,f)});Ob(d)}v(Db,O);function Ob(a){for(var b=a.g,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Ib?Pb:" ";e[f+1]=d.j==d.v?null:d.j;e[f+2]=0;e[f+3]=Qb}a.U=a.V=!0;Nb(a,!0)}function Rb(a){a.u?(a.h.fillStyle=a.u,a.h.fillRect(0,0,a.ca,a.M)):a.h.clearRect(0,0,a.ca,a.M)}
function Nb(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.U||b){if(a.type<Ib){d=0;if(!a.Y||b)Rb(a);else if(a.N){d=a.s-a.N;var e=a.m*d;a.h.drawImage(a.J,a.m*a.N,0,e,a.M,0,0,e,a.M)}for(var f=e=0;f<a.W;f++){for(var g=0;g<a.s;g++){var h=a.g[e],k=a.g[e+1]||a.v,l=a.sa&&e==a.$;if(a.g[e+3]&Qb||l||b){if(g>=d)a:{var m=a,n=h;h=k;var q=g;k=f;var w=l;q=void 0===q?0:q;k=void 0===k?0:k;w=void 0===w?!1:w;var z=0;if(m.ka&&!(k&1)&&(z=m.m>>1,q==m.s-1))break a;if(h&&h!=m.j){w=w?Kb(h,1,2):h;var x=
Kb(h,1,.25)}else w=w?m.la:m.j,x=m.ma;h=!1;n=n?w:x;w==m.v&&(n=m.u,h=!0);w=q*m.m+z;x=k*m.H;m.Y&&(q=q*m.m+z,k*=m.H,m.u?(m.h.fillStyle=m.u,m.h.fillRect(q,k,m.m,m.H)):m.h.clearRect(q,k,m.m,m.H));m.h.fillStyle=n;k=Sb[m.type];3==k.length?(m.h.beginPath(),m.h.arc(w+k[0],x+k[1],k[2],0,2*Math.PI),h?(m.h.globalCompositeOperation="destination-out",m.h.fill(),m.h.globalCompositeOperation="source-over"):m.h.fill()):m.h.fillRect(w+k[0],x+k[1],k[2],k[3])}a.g[e+3]=l?a.g[e+3]|Qb:a.g[e+3]&~Qb}e+=4}e+=a.Ka}a.N=0}else{b=
"";for(d=0;d<a.g.length;d+=4)b+=a.g[d]||" ",a.g[d+3]&Tb&&(b+=".");Rb(a);for(f=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;g=a;l=e;m=f;l=void 0===l?0:l;m=void 0===m?0:m;if(k=Ub[k])for(h=0;h<k.length;h++)if(q=g,z=Vb[k[h]]){n=(void 0===l?0:l)*q.m;w=(void 0===m?0:m)*q.H;q.h.fillStyle=q.j;q.h.beginPath();if(3==z.length)q.h.arc(n+z[0],w+z[1],z[2],0,2*Math.PI);else for(x=0;x<z.length;x+=2)x?q.h.lineTo(n+z[x],w+z[x+1]):q.h.moveTo(n+z[x],w+z[x+1]);q.h.closePath();q.h.fill()}if(++e==a.s&&(e=0,++f==a.W))break}}a.ia.globalCompositeOperation=
a.u&&a.j!=a.v?"source-over":"copy";a.ia.drawImage(a.J,0,0,a.ca,a.M,0,0,a.ea,a.Z);a.U=!1;a.$=-1}else a.Y||a.V||(!c||!a.aa||c-a.aa>=(1E3/d|0))&&Ob(a);a.V=!1;c&&(a.aa=c)}function Lb(a){return(a=a||void 0)&&$a[a]||a}
function Kb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=$a[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Db.prototype.oa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.j&&c==this.u&&a&&a.length==this.g.length){this.g=a;for(b=0;b<=this.g.length-4;b+=4)this.g[b+1]==this.v&&(this.g[b+1]=null);Nb(this,!0);return!0}return!1};Db.prototype.ra=function(a){this.g&&(a.push(this.j),a.push(this.u),a.push(this.g))};
function Wb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&Xb;b=4*(c*a.R+b);if(b<=a.g.length-4){if(a.g[b]!==d||(a.g[b+3]&Xb)!==e)a.g[b]=d,a.g[b+3]=a.g[b+3]&~Xb|e|Qb,a.U=f=!0;a.$=b;a.V=!0;a.N=0}return f}
var Hb=0,Fb=1,Ib=3,Gb={small:Hb,round:Fb,square:2,digit:Ib},Eb="container",Pb=0,Xb=129,Tb=1,Qb=128,Yb={},Sb=(Yb[Hb]=[4,4,4],Yb[Fb]=[16,16,14],Yb[2]=[2,2,28,28],Yb),Jb=[[8,8],[32,32],[32,32],[96,128]],Vb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Ub={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};C.LED=Db;
function Zb(a,b,c){O.call(this,a,b,c);this.na=H(this,"cyclesMinimum",1E5);this.Za=H(this,"cyclesMaximum",1E9);this.sa=Ja(H(this,"cyclesPerSecond",1E6),this.na,this.Za);this.aa=60;this.ca=0;this.W=1E3/this.aa;this.Mc=H(this,"updatesPerSecond",2)||2;this.Lc=1E3/this.Mc;this.Ka=0;this.bd=H(this,"timeLock",!0);this.la=this.R=0;this.ka=this.v=1;this.wa=this.J=this.sa/1E4/100;this.ea=[];this.M=[];this.h=[];this.ia=[];this.va=this.g=this.ba=this.H=!1;this.N=this.m=0;a=Ea("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.W}this.Eb=window[a].bind(window,this.pd.bind(this),d);this.Kc=window[Ea("cancelAnimationFrame")||"clearTimeout"].bind(window);this.$=this.Z=this.s=this.j=this.ma=0;$b(this)||ac(this,this.ka)}v(Zb,O);function Mb(a,b){a.ea.push(b)}p=Zb.prototype;
p.Aa=function(a,b){var c=this;switch(a){case bc:b.onclick=function(){cc(c)&&(c.g?U(c):c.start())};break;case dc:b.onclick=function(){ac(c,c.v<<1);ec(c,fc(c.J))};break;case gc:b.onclick=function(){hc(c)};break;case ic:b.addEventListener("mousedown",function(){c.H=!0}),b.addEventListener("mouseup",function(){$b(c);c.H=!1}),b.addEventListener("mousemove",function(){c.H&&$b(c)}),b.addEventListener("change",function(){c.H=!0;$b(c);c.H=!1})}O.prototype.Aa.call(this,a,b)};
function pb(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,ed:c,Ra:d,ga:-1});0<=d&&ub(a,e,d);return e}
function jc(a,b,c,d){var e=0,f=a.J,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.K(A.Ma,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.W&&(1<a.v&&(a.v>>=1,a.K(A.Na,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.W,a.v)),e=d));a.R=f;a.la=f/a.wa;b=a.la/a.v;a.ma=g/b/a.aa+1E-8;a.K(A.Ma,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.ma,g,b,a.aa);return e}
function kc(a,b){a.Z=a.s=b;if(!a.M.length)return a.s=0,a.Z;for(var c=0;0<a.s;){if(c<a.M.length){var d=a.M[c++];b=d.qd.call(d,b)||1}else c=b=0;a.s-=b}return a.Z-a.s}function lc(a,b){var c=Date.now();b()&&(a.Y+=Date.now()-c)}function mc(a,b){b=void 0===b?a.Z-a.s:b;if(!a.g){if(a.j)for(var c=0;c<a.M.length;c++){var d=a.M[c];d.Wb.call(d)}a.j=b}a.j-=b;1>a.j&&(a.ba=!0);a.$+=b;a.Z=a.s=0;a.g||(a.$=0);return b}
function nc(a,b){b=void 0===b?0:b;if(b){var c=b;a.j+=b}else for(c=a.j,1>c&&(c=a.j+=a.ma),0>c&&(a.K(A.Na,"warning: cycle count dropped below zero: %f\n",c),c=a.j=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.ga)&&c>d.ga&&(c=d.ga)}return c}function fc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function cc(a){return a.va?!0:(F(a,"not powered"),!1)}
function oc(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.ga||(d.ga-=b,0>=d.ga&&(d.ga=-1,d.ed(),0<=d.Ra&&ub(a,c,d.Ra)))}}p.ha=function(a){this.va=a;void 0===this.pa&&(this.pa=Q(this,"Debugger",!1))};function hc(a,b){cc(a)&&(a.g?F(a,"already running"):a.m?U(a):pc(a,b))}
p.pd=function(a){a=void 0===a?Date.now():a;this.N=0;if(this.g){if(this.ca){var b=a-this.ca;1>b&&(b=16.67);this.aa=1E3/b}this.ca=a;a=Date.now();this.U&&(b=a-this.V-this.W,b>this.W&&(this.u+=b,this.K(A.Na,"warning: browser throttling detected, compensating by %5.3fms\n",b)));this.V=a;this.u||(this.u=a);this.Y=0;try{this.ba=!1;do oc(this,mc(this,kc(this,nc(this))));while(this.g&&!this.ba)}catch(c){F(this,c.message),U(this)}this.U=Date.now();this.Y&&(this.u+=this.Y,this.V+=this.Y);this.V+=jc(this,this.$,
this.U-this.u,this.U-this.V);this.U-this.Ka>=this.Lc&&this.update();for(a=0;a<this.ea.length;a++)this.ea[a](this.ca,this.aa);this.N=this.Eb()}};function ac(a,b){if(void 0!==b){if(1>b||!a.H&&0<a.R&&a.R<.9*a.J)b=a.ka;a.v=b;b=a.wa*a.v;a.J!=b&&(a.J=b,ec(a,fc(a.J)))}a.u=a.U=0;a.j=a.$=0;jc(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.Ra&&ub(a,b,c.Ra,!0)}}function $b(a){var b=a.T[ic];return b?(ac(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Za-a.na)+a.na)/a.sa|0),!0):!1}
function ub(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.ga)&&(c=Math.ceil(a.sa*(a.bd?a.ka:a.la)/1E3*(void 0===c?1E3:c)),a.g&&(c+=mc(a)),b.ga=c)}p.start=function(){if(this.g||this.m)return!1;this.g=!0;this.u=this.U=0;this.update(!0);this.N=this.Eb();return!0};function pc(a,b){b=void 0===b?1:b;a.g||(b&&!a.m&&(a.m=b),a.m&&(a.m--,oc(a,mc(a,kc(a,nc(a,1)))),a.update(!1),a.m&&setTimeout(function(){pc(a,0)},0)))}
function U(a){return a.g?(a.g=!1,mc(a),a.N&&(a.Kc(a.N),a.N=0),a.update(!0),!0):a.m?(a.m=0,a.update(!0),!0):!1}p.update=function(a){a&&F(this,this.g?"started with "+fc(this.J)+" target":"stopped");M(this,bc,this.g?"Halt":"Run");M(this,gc,this.m?"Stop":"Step");this.H||(this.K(A.Ma,"getSpeedCurrent(%5.3fhz)\n",1E6*this.R),ec(this,this.g&&this.R?fc(this.R):"Stopped"));for(var b=0;b<this.ia.length;b++){var c=this.ia[b];c.md.call(c,void 0!=a)}this.Ka=Date.now();this.ba=!0};
function ec(a,b){M(a,qc,b);M(a,dc,b)}var bc="run",dc="setSpeed",qc="speed",gc="step",ic="throttle";C.Time=Zb;
function rc(a,b,c){O.call(this,a,b,c);this.type="static"==this.I.type?sc:tc;this.u=this.I.addrWidth||16;this.j=Math.pow(2,this.u);this.H=this.j-1|0;this.blockSize=this.I.blockSize||(16<this.u?4096:1024);this.blockSize>this.j&&(this.blockSize=this.j);this.J=this.j/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.m=(1<<this.h)-1;this.v=this.I.dataWidth||8;this.g=Array(this.J);this.s=0;a=new V(a,b+"[NONE]",{size:this.blockSize,bus:this.X});for(b=0;b<this.j;b+=this.blockSize)uc(this,b,this.blockSize,
W.NONE,a);a=this.s;this.s+=this.type;a&&this.s||(this.Ea=this.yc,this.Fa=this.Ga)}v(rc,O);
function uc(a,b,c,d,e){for(var f=b>>>a.h;0<c&&f<a.g.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var k=a.g[f];if(b!=g||h!=a.blockSize||k&&k.type!=W.NONE)break;var l=k=void 0,m=b,n=a.u,q=16;n=void 0===n?0:n;k=void 0===k?0:k;var w="",z="",x=-1;q||(q=a.M||10);n&&(x=Math.ceil(n/Math.log2(q)));if(void 0==l)switch(q){case 8:l="0o";break;case 16:l="0x";break;case 10:z=".";default:l=""}isNaN(m)||"number"!=typeof m?(m=void 0,l=z=""):(0>m&&-1<m&&(m=-1),n&&(0>m&&(m+=Math.pow(2,n)),m>=Math.pow(2,
n)&&(x=Math.ceil(Math.log(m)/Math.log(q)))));for(n=k||-1;x--;){n||(w=","+w,n=k);if(void 0==m){if(w="?"+w,0>x)break}else{var B=m%q;m=Math.trunc(m/q);B+=0<=B&&9>=B?48:55;w=String.fromCharCode(B)+w;if(!m&&0>x)break}n--}k=a.X+"["+(l+w+z)+"]";b=e?e.size==a.blockSize?e:new V(a.L,k,{type:d,Oa:b,size:h,bus:a.X}):new V(a.L,k,{type:d,Oa:b,size:h,bus:a.X});a.g[f]=b;b=g+a.blockSize;c-=h;f++}}p=rc.prototype;p.ha=function(){void 0===this.pa&&(this.pa=Q(this,"Debugger",!1))};p.qa=function(){};
p.cb=function(a){return a&&this.oa(a)?!0:!1};p.eb=function(a){this.ra(a)};p.oa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==tc||c.type&W.La)&&c.oa){var d=a.shift();if(!c.oa(d))return!1}}return!0};p.ra=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==tc||c.type&W.La)&&c.ra){var d=[];c.ra(d);a.push(d)}}};p.xa=function(a){return this.g[a>>>this.h].xa(a&this.m)};p.yc=function(a){return this.g[a>>>this.h].Ea(a&this.m)};
p.fb=function(a,b){this.g[a>>>this.h].fb(a&this.m,b)};p.Ga=function(a,b){this.g[a>>>this.h].Fa(a&this.m,b)};var sc=0,tc=1;C.Bus=rc;
function V(a,b,c){O.call(this,a,b,c);this.Oa=this.I.addr;this.size=this.I.size;this.type=this.I.type||W.NONE;this.m=(a=this.I.bus)?bb(this,a):Q(this,a="Bus");if(!this.m)throw Error(this.S("unable to find bus '%s'",a));this.u=this.m.v;this.J=Math.pow(2,this.u)-1;this.s=this.H=!1;this.values=this.j=null;a=this.vb;b=this.Ga;if(this.m.type==sc){b=this.rd;if(c=8==this.u)c=bb(this,this.L),c=!1!==(c&&c.I&&c.I.ArrayBuffer||this.I.ArrayBuffer);c&&(this.H=!0)}switch(this.type){case W.NONE:this.Ea=this.od;this.Fa=
this.Xb;break;case W.Hb:this.Ea=a;this.Fa=this.Xb;break;case W.La:this.Ea=a,this.Fa=b}vc(this,this.I.values);wc(this)}v(V,O);function vc(a,b){"string"==typeof b?(fb(a,!1),Ka(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);vc(a,g.values)}catch(h){a.K("error (%s) parsing resource: %s\n",h.message,c)}fb(a,!0)}else a.K("error (%d) loading resource: %s\n",f,c)})):a.I.values=b}
function wc(a,b){if(a.type>W.NONE&&(a.H?(a.j=new ArrayBuffer(a.size),new DataView(a.j,0,a.size),a.values=new Uint8Array(a.j,0,a.size),new Uint16Array(a.j,0,a.size>>1),new Int32Array(a.j,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}p=V.prototype;
p.qa=function(){if(this.I.values)a:{var a=this.m,b=this.Oa,c=this.size,d=this.I.values,e=0,f=b&a.m;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var g=a.g[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Ga(f++,d[e++]),c--;f=0}}else this.type&W.La&&this.values&&this.values.fill(0)};p.od=function(){return this.J};p.xa=function(a){return this.values?this.values[a]:0};p.vb=function(a){return this.values[a]};p.Xb=function(){};p.fb=function(a,b){this.values&&(this.values[a]=b)};
p.Ga=function(a,b){this.values[a]=b};p.rd=function(a,b){this.values[a]=b;this.s=!0;this.Fa=this.Ga};p.oa=function(a){if(a){var b=a.shift();if(this.X==b){this.s=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}wc(this,a)}return!0}}return!1};
p.ra=function(a){a.push(this.X);a.push(this.s);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var W={NONE:1,Hb:2,La:4,Ge:14,Ke:12};C.Memory=V;
function xc(a,b,c){c.type=W.Hb;V.call(this,a,b,c);uc(this.m,this.I.addr,this.I.size,this.I.type,this);gb(this,this.qa.bind(this));this.da=this.pa=void 0;if(C.LED&&this.T[yc]){var d=this;this.h=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.v=this.values.length/this.h|0;this.g=new Db(a,b+"LEDs",{"class":"LED",bindings:{container:Ga(this,yc)},type:Fb,cols:this.h,rows:this.v,color:H(this,"colorROM","green"),backgroundColor:H(this,"backgroundColorROM","black"),persistent:!0}),Ob(this.g);
this.M=new ib(a,b+"Input",{"class":"Input",location:[0,0,this.g.ea,this.g.Z,this.h,this.v],bindings:{surface:Ga(this,yc)}});this.N=Ha(this)||"";lb(this.M,function(e,f){if(d.da){var g=d.N;0<=e&&0<=f&&(e=f*d.h+e,g=zc(d.da,d.Oa+e,d.values[e]));M(d,Ia,g)}})}}v(xc,V);
xc.prototype.oa=function(a){var b=!0,c=a.shift();if(c&&this.g){var d=c.length;this.g.g.length==d?(this.g.g=c,Nb(this.g,!0)):(this.K("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.K("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};xc.prototype.ha=function(){void 0===this.da&&(this.da=Q(this,"CPU"));void 0===this.pa&&(this.pa=Q(this,"Debugger",!1))};
xc.prototype.vb=function(a){this.g&&Wb(this.g,a%this.h,a/this.h|0,1,Qb);return this.values[a]};xc.prototype.ra=function(a){this.g&&(a.push(this.g.g),a.push(this.values))};var yc="array",Ia="cellDesc";C.ROM=xc;function Ac(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.pa=void 0;this.h=this.Ta=0;this.time=Q(this,"Time");this.time.M.push(this);this.time.ia.push(this);this.Z=this.u=0}v(Ac,O);p=Ac.prototype;p.abort=function(a){this.h=this.Ta;F(this,a.message);U(this.time)};p.Sb=function(){};
p.qd=function(a){this.Z=this.u=a=void 0===a?0:a;try{this.Sb(a)}catch(b){this.abort(b)}return this.Ub()};p.Wb=function(){this.Z-=this.u;this.u=0};p.Ub=function(){return this.Z-this.u};function X(a,b,c){O.call(this,a.L,b);this.da=a;this.name=b;this.l=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.ma[c]=[this,-1];for(var d=0;d<this.l.length;d++)c=this.S("reg%s-%02d",this.name,d),b.push(c),a.ma[c]=[this,d];Da(a,b)}}v(X,O);p=X.prototype;
p.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]+b.l[f]+e,e=0,this.l[f]>=d&&(this.l[f]-=d,e=1);e&&(this.da.v=!0);Bc(this,c)};p.get=function(){return this.l};function Cc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.l.length;d++)a.l[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.l[d]=b&15,b>>>=4;return a}p.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.l[e]=a.l[e]+d,d=0,this.l[e]>=c&&(this.l[e]-=c,d=1);Bc(a,b)};
p.set=function(a){if(a&&a.length==this.l.length)for(var b=0;b<this.l.length;b++)this.l[b]=a[b]};p.store=function(a){for(var b=0,c=this.l.length;b<c;b++)this.l[b]=a.l[b]};p.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]-b.l[f]-e,e=0,0>this.l[f]&&(this.l[f]+=d,e=1);e&&(this.da.v=!0);Bc(this,c)};p.toString=function(a){a=void 0===a?!1:a;var b=this.X+"=";a&&3>b.length&&(b+=" ");for(var c=this.l.length-1;0<=c;c--)b=a?b+xa[this.l[c]]:b+(ya[this.l[c]]+(c%4?"":" "));return b};
function Bc(a,b){a.da.s=a.l[b[0]];b[0]<b[1]&&(a.da.s|=a.l[b[0]+1]<<4)}
function Dc(a,b,c){Ac.call(this,a,b,c);this.type=Number.parseInt(H(this,"type","1501").slice(-4),10);this.ma={};this.g=Array(4);for(a=0;4>a;a++)this.g[a]=new X(this,String.fromCharCode(65+a));this.V=this.g[0];this.$=this.g[1];this.sa=this.g[2];this.wa=this.g[3];this.R=Array(8);for(a=0;8>a;a++)this.R[a]=new X(this,"X"+a);this.W=Array(8);for(a=0;8>a;a++)this.W[a]=new X(this,"Y"+a);this.na=new X(this,"Supp",!0);this.ba=new X(this,"Temp",!0);this.N=10;this.v=!1;this.aa=this.s=this.J=0;this.m=[-1,-1,-1];
this.va=bb(this,this.I.input);this.va.J=this.zc.bind(this);this.j=bb(this,this.I.output,!1);this.M=Q(this,"Bus");this.H=Q(this,"ROM");this.ka=this.la=this.Y=void 0;this.ia=this.ca=-1;this.U={};this.ea=Ec;a=this.ld.bind(this);b=Qa.lb;this.O.Ja[b]||(this.O.Ja[b]=[]);this.O.Ja[b].push(a)}v(Dc,Ac);function Fc(a,b){a.U[b]&&(a.U[b]=!1,F(a,"break on "+Gc[b]),U(a.time))}function Hc(a){a.j&&Ob(a.j);if(a.H){var b=a.H;b.g&&Ob(b.g)}Ic(a,!1)}p=Dc.prototype;
p.Sb=function(a){for(;0<this.u;){if(this.ia==this.h){this.ia=-1;F(this,"break");U(this.time);break}var b=this.M.Ea(this.h);this.h=(this.Ta=this.h)+1&this.M.H;if(void 0==b||!Jc(this,b)){this.h=this.Ta;F(this,"unimplemented opcode");U(this.time);break}this.u-=Kc}if(0>=a){var c=this;lc(this.time,function(){var d=c.H;d.g&&Nb(d.g);c.ta(c.toString())})}};p.Wb=function(){this.u=0};p.Ub=function(){return this.Z-this.u};
function Jc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.v&&(a.h=a.h&1024|b&1023):(a.push(a.h),a.h=b&2047),a.v=!1,!0;var c;var d=b&Lc;switch(d){case Mc:case Nc:case Oc:case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:d=Yc[d];var e=(b&Zc)>>$c;var f=(b&ad)>>bd;var g=(b&cd)>>dd;var h=(c=b&ed)?fd:gd;b=b>=Tc?16:a.N;switch(f){case 0:case 1:case 2:case 3:var k=a.g[f];break;case 4:k=Cc(a.ba,1,d);break;case 5:h=c?hd:id;break;case 6:k=Cc(a.ba,a.s&15,d);break;case 7:k=Cc(a.ba,a.s&255,d)}switch(g){case 0:var l=
a.g[e];break;case 1:l=4>f?a.g[f]:void 0;break;case 2:l=5>f?a.na:5==f?a.g[e]:void 0;break;case 3:if(c)a.g[e].move(k,d,b);else{a=a.V;e=k;b=d[0];for(k=d[1];b<=k;b++)l=a.l[b],a.l[b]=e.l[b],e.l[b]=l;Bc(e,d)}return!0}if(!l)break;switch(h){case gd:l.add(a.g[e],k,d,b);break;case fd:l.sub(a.g[e],k,d,b);break;case id:b=l;a=a.g[e];e=d[1];for(k=d[0];e>k;e--)b.l[e]=a.l[e-1];b.l[e]=0;Bc(b,d);break;case hd:b=l;a=a.g[e];e=d[0];for(k=d[1];e<k;e++)b.l[e]=a.l[e+1];b.l[e]=0;Bc(b,d)}return!0;case jd:e=(b&kd)>>ld;d=(b&
md)>>nd;k=1<<((b&od)>>pd);if(!d)break;d+=12;switch(b&qd){case rd:a.g[e].l[d]|=k;break;case sd:a.g[e].l[d]&=~k;break;case td:a.g[e].l[d]&k&&(a.v=!0);break;case ud:a.g[e].l[d]^=k}return!0;case vd:switch(b&wd){case xd:a.V.store(a.W[a.J]);break;case yd:a.J=b>>4&7;break;case zd:a.h=a.s;break;case Ad:a.v=!1;d=a.m[0];e=0;for(b=a.m.length-1;e<b;)a.m[e]=a.m[++e];a.m[e]=-1;a.h=d;break;case Bd:a.R[a.J].store(a.V);break;case Cd:a.V.store(a.R[a.J]);break;case Dd:a.W[a.J].store(a.V);break;case Ed:Fc(a,"o");if(a.j){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.$.l[e]&8?b=" ":a.$.l[e]&1?b="-":b=xa[a.V.l[e]],Wb(a.j,d,0,b,a.$.l[e]&2?Tb:0)&&Fc(a,"om");Ic(a)}a.u-=31*Kc;a.aa&&(a.s=a.aa,a.v=!0,Fc(a,"i"));break;case Fd:a.N=10;break;case Gd:a.N=16;break;case Hd:a.J=a.s&7;break;default:return!1}return!0}return!1}
p.oa=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return F(this,"invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.K("saved state version mismatch: %3.2f\n",c),!1;try{this.g.forEach(function(d){return d.set(b.shift())}),this.R.forEach(function(d){return d.set(b.shift())}),this.W.forEach(function(d){return d.set(b.shift())}),this.na.set(b.shift()),this.ba.set(b.shift()),this.N=b.shift(),this.v=b.shift(),this.J=b.shift(),this.s=b.shift(),this.h=b.shift(),this.m=b.shift(),this.aa=
b.shift()}catch(d){return F(this,"CPU state error: "+d.message),!1}return(a=a.stateROM||a[1])&&this.H&&!this.H.oa(a)?!1:!0};
p.ld=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,h=3;h<a.length;h++)d.push(Number.parseInt(a[h],16));this.ea=Ec;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Gc)c=Gc[f],b+="break on "+c+" (b"+f+"): "+(this.U[f]||!1)+"\n";break}(c=Gc[f])?(this.U[f]=!this.U[f],b="break on "+c+" (b"+f+"): "+this.U[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.M.xa(f);if(void 0==
a)break;this.M.fb(f,d[g]);b+=this.S("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.S("%d locations updated\n",c);break;case "g":this.time.start()?this.ia=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.ea=Id);g=Number.parseInt(a[2],10)||1;hc(this.time,g);break;case "r":"c"==e[1]&&(this.ea=Id);this.Vb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.ca?this.ca:this.h;g--;){c=this.H&&this.M.xa(f);if(void 0==
c)break;b+=zc(this,f++,c)}this.ca=f;break;case "?":b="additional commands:\n";Jd.forEach(function(k){b+=k+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};p.zc=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.aa=c};p.cb=function(a){return a&&this.oa(a)?!0:!1};p.ha=function(a){a?this.time.start():(U(this.time),Hc(this))};p.qa=function(){F(this,"reset");this.h=0;Hc(this);this.time.g||this.ta(this.toString())};p.eb=function(a){this.ra(a)};
p.md=function(a){for(var b in this.T){var c=this.ma[b];if(c){var d=c[0];c=c[1];M(this,b,0>c?d.toString():xa[d.l[c]])}}a&&!this.time.g&&(a=this.H,a.g&&Nb(a.g),this.ta(this.toString()))};p.push=function(a){for(var b=this.m.length-1;0<b;)this.m[b]=this.m[--b];this.m[0]=a};
p.ra=function(a){var b=[],c=[];b.push(2);this.g.forEach(function(d){return b.push(d.get())});this.R.forEach(function(d){return b.push(d.get())});this.W.forEach(function(d){return b.push(d.get())});b.push(this.na.get());b.push(this.ba.get());b.push(this.N);b.push(this.v);b.push(this.J);b.push(this.s);b.push(this.h);b.push(this.m);b.push(this.aa);this.H&&this.H.ra(c);a.push(b);a.push(c)};p.Vb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.h=b;break;default:F(this,"unrecognized register: "+a)}};
function zc(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.S("%#06x",f);else if(0<=c){var g=c&Lc;var h;switch(g){case Mc:case Nc:case Oc:case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:f="";e=Yc[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&Zc)>>$c;var k=(c&ad)>>bd;var l=(c&cd)>>dd;var m=c&ed;e="LOAD";var n=h="?";var q=m?5==k?">>":"-":5==k?"<<":"+";switch(l){case 0:h=
Y[g];break;case 1:4>k&&(h=Y[k]);break;case 2:6>k&&(h="NUL");break;case 3:m?(e="MOVE",h=Y[g],n=Y[k]):(e="XCHG",g||(h="A"),4>k&&(n=Y[k])),k=-1}switch(k){case 0:case 1:case 2:case 3:n=Y[g]+q+Y[k];break;case 4:case 5:n=Y[g]+q+"1";break;case 6:n=Y[g]+q+"R5L";break;case 7:n=Y[g]+q+"R5"}f=h+","+n+","+f;break;case jd:switch(c&qd){case rd:e="SET";break;case sd:e="CLR";break;case td:e="TST";break;case ud:e="NOT"}f=a.g[(c&kd)>>ld].name;g=(c&md)>>nd;f+="["+(g?g+12:"?")+":"+((c&od)>>pd)+"]";break;case vd:switch(c&
wd){case xd:e="STORE";f="A,Y[RAB]";break;case yd:e="STORE";f="RAB,"+((c&112)>>4);break;case zd:e="BR";f="R5";break;case Ad:e="RET";break;case Bd:e="STORE";f="X[RAB],A";break;case Cd:e="STORE";f="A,X[RAB]";break;case Dd:e="STORE";f="Y[RAB],A";break;case Ed:e="DISP";break;case Fd:e="BCDS";break;case Gd:e="BCDR";break;case Hd:e="STORE",f="RAB,R5L"}}}return a.S(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
p.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.ea){this.H&&(d+=zc(this,this.h,this.M.xa(this.h),!0));d+="  ";b=0;for(a=this.g.length;b<a;b++)d+=this.g[b].toString()+" ";d+="\n ";d+=" COND="+(this.v?1:0);d+=" BASE="+this.N;d+=" R5="+this.S("%02X",this.s);d+=" RAB="+this.J+" ST=";this.m.forEach(function(f){d+=c.S("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.g);0<=a.indexOf("a")&&(d+=this.toString(a,this.R),d+=this.toString(a,this.W));d+="COND="+(this.v?1:0);d+=" BASE="+this.N;d+=" R5="+this.S("%#04x",this.s);d+=" RAB="+this.J+" ";this.m.forEach(function(f,g){d+=c.S("ST%d=%#06x ",g,f&65535)});this.H&&(d+="\n"+zc(this,this.h,this.M.xa(this.h)));this.ca=this.h;return d};
function Ic(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Kd?!!(a.sa.l[14]&8):!!(a.$.l[15]&4));if(a.ka!==d){if(c=a.T["2nd"])c.style.opacity=d?"1":"0",void 0===a.ka&&a.j&&(c.style.color=a.j.color);a.ka=d}d=b&&(a.type==Kd?!!(a.$.l[15]&4):!!(a.wa.l[15]&8));if(a.la!==d){if(c=a.T.INV)c.style.opacity=d?"1":"0",void 0===a.la&&a.j&&(c.style.color=a.j.color);a.la=d}c=a.type==Kd?a.R[4].l[15]>>2:a.sa.l[15];b=b?c?1==c?Ld:Md:Nd:Od;if(a.Y!==b){if(c=a.T.Deg)c.style.opacity=b==Nd?"1":"0",void 0===a.Y&&a.j&&(c.style.color=
a.j.color);if(c=a.T.Rad)c.style.opacity=b==Ld?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);if(c=a.T.Grad)c.style.opacity=b==Md?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);a.Y=b}}
var Lc=3840,Mc=0,Nc=256,Oc=512,Pc=768,Qc=1024,Rc=1280,Sc=1792,Tc=2048,Uc=2304,Vc=2560,jd=3072,Wc=3328,vd=3584,Xc=3840,Zc=192,$c=6,ad=56,bd=3,cd=6,dd=1,ed=1,qd=3,rd=0,sd=1,td=2,ud=3,kd=192,ld=6,md=48,nd=4,od=12,pd=2,wd=15,xd=0,yd=1,zd=2,Ad=3,Bd=4,Cd=5,Dd=6,Ed=7,Fd=8,Gd=9,Hd=10,Z={},Yc=(Z[Mc]=[12,12],Z[Nc]=[0,15],Z[Oc]=[2,12],Z[Pc]=[0,12],Z[Qc]=[2,2],Z[Rc]=[0,1],Z[Sc]=[0,13],Z[Tc]=[14,14],Z[Uc]=[13,15],Z[Vc]=[14,15],Z[Wc]=[13,13],Z[Xc]=[15,15],Z),Kc=128,gd=0,fd=1,id=2,hd=3,Kd=1501,Od=0,Nd=1,Ld=2,Md=
3,Gc={i:"input",o:"output",om:"output modification"},Ec=0,Id=1,Y="A B C D 1 ? R5L R5".split(" "),Jd="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");C.CPU1500=Dc;
function Pd(a,b,c){O.call(this,a,a);var d=this;this.j=!1;this.v=c;this.h="";this.u=this.s=!1;fb(this,!1);this.fa=A.ic;b=b.trim();"{"==b[0]?Qd(this,b):(this.h=b,Ka(this.h,function(e,f,g,h){4==g&&(!h&&f?(Qd(d,f),Rd(d)):d.K("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.u=!0;Rd(d)});window.addEventListener(Ma("iOS")?"pagehide":Ma("Opera")?"unload":"beforeunload",function(){Sd(d)});window.addEventListener("pageshow",function(){d.j||d.ha(!0)})}v(Pd,O);
Pd.prototype.Aa=function(a,b){var c=this;switch(a){case Td:b.onclick=function(){c.ha()};break;case Ud:b.onclick=function(){c.qa()}}O.prototype.Aa.call(this,a,b)};
function Rd(a){var b=!0;if(a.s&&a.u){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],C[d]?"Machine"==d?(a.K("PCjs %s v%3.2f\n%s\n",e.name,2,"Copyright \u00a9 2012-2023 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.K("Configuration: %s\n",a.h)):new C[d](a.L,c,e):a.K('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.K('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),hb(a,c)}}if(a.m){var f=Na(a);db(a,function(g){return g.cb&&!g.cb(f)?(g.K('unable to restore state for device "%s"\n',
g.X),!1):!0})}fb(a,!0);gb(a,a.ha.bind(a,b))||a.K("machine %s not ready to power, waiting for device(s)\n",a.L)}}
function Qd(a,b){try{a.g=JSON.parse(b);var c=a.g[a.L];if(!c){c=a.g[ta(a.h)];if(!c)throw Error("configuration missing machine ID");a.g[a.L]=c}cb(a,c,["autoSave","autoStart"]);a.m=!1!==a.I.autoSave;a.H=!1!==a.I.autoStart;if(a.v){var d=eval("("+a.v+")"),e;for(e in d)a.I[e]=d[e]}a.s=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),F(a,"machine '"+a.L+"' initialization error: "+c)}}
Pd.prototype.ha=function(a){a=void 0===a?!this.j:a;if(eb(this)){var b=this;a&&F(this,"power on");db(this,function(c){c.ha&&c!=b&&("CPU"!=c.I["class"]||b.H&&eb(b)?c.ha(a):c.time.update(!0));return!0});(this.j=a)||F(this,"power off")}};Pd.prototype.qa=function(){if(eb(this)){var a=this;db(this,function(b){b.qa&&b!=a&&b.qa();return!0});F(this,"reset")}};function Sd(a){if(a.m){var b=[];db(a,function(c){c.eb&&c.eb(b);return!0});Ua(a,b)}a.ha(!1)}var Td="power",Ud="reset";
window.TMS1500=function(a,b,c){var d=new Pd(a,b,c);window.command=function(e){return Oa(d,e)};return d};C.Machine=Pd;})()

//# sourceMappingURL=ti55.js.map
