(function(){/*
 https://www.pcjs.org/machines/modules/v2/message.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/dumpapi.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/reportapi.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/embed.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/defines.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/pcfs.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/strlib.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/usrlib.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/weblib.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/component.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/defines.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/panel.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/cpu.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/rom.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/ram.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/keyboard.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/video.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/serial.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/disk.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/debugger.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/computer.js (C) 2012-2025 Jeff Parsons
*/
var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ca(a){if(!(a instanceof Array)){a=ba(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ea="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ha(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ia=ha(this);function t(a,b){if(b)a:{var c=ia;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ea(c,a,{configurable:!0,writable:!0,value:b})}}var ja;
if("function"==typeof Object.setPrototypeOf)ja=Object.setPrototypeOf;else{var ka;a:{var la={a:!0},ma={};try{ma.__proto__=la;ka=ma.a;break a}catch(a){}ka=!1}ja=ka?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var na=ja;
function v(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(na)na(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Me=b.prototype}function oa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
t("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
t("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});t("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
t("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});t("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,h){this.g=f;ea(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ia[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ea(d.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}})}return a});function pa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function qa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}t("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});
var ra="undefined"!=typeof window,sa="undefined"!=typeof window?{}:global,x="undefined"!=typeof window?window:global,ta="undefined"!=typeof document?document:{},y={machines:{},components:[],commands:{},files:null};x.PCjs?y=x.PCjs:x.PCjs=y;x.LOCALDISKS=!1;function ua(){this.g={};for(var a=0;23>a;a++)this.g["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
function va(){var a=oa.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,ca(a)));return a}
ua.prototype.h=function(a){var b=oa.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var h=d[f+5];if(void 0===this.g[h])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+h;else{if(e<b.length){var k=b[e];"%"!=h&&e++}else k=b[b.length-1];var l=!1,q=d[f+1],m=0<=q.indexOf("#"),p=0<=q.indexOf("0"),n=d[f+2];"*"==n?(n=k,k=e<b.length?b[e++]:b[b.length-1]):n=+n||0;var r=d[f+3];r=r?+r.substr(1):-1;var J=d[f+4],
V=null,A=0,w="",u=0<="ACDFGHMNSTWY".indexOf(h)&&"object"!=typeof k?va(k):k;switch(h){case "C":c+=isNaN(u.getTime())?void 0:this.h("%#W, %#F %#D, %#Y".replaceAll("#",m?"#":""),u);continue;case "D":k=m?u.getUTCDate():u.getDate();h="d";break;case "A":case "G":case "H":k=m?u.getUTCHours():u.getHours();"A"==h?(k=12>k?"am":"pm",h="s"):("G"==h&&(k=k?12<k?k-12:k:12),h="d");break;case "F":case "M":k=m?u.getUTCMonth():u.getMonth();"F"==h?(k=wa[k],h="s"):(k++,h="d");break;case "N":k=m?u.getUTCMinutes():u.getMinutes();
h="d";break;case "S":k=m?u.getUTCSeconds():u.getSeconds();h="d";break;case "T":c+=isNaN(u.getTime())?void 0:this.h("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",m?"#":""),u);continue;case "W":k=xa[m?u.getUTCDay():u.getDay()];h="s";break;case "Y":k=m?u.getUTCFullYear():u.getFullYear(),0<r&&(k%=Math.pow(10,r)),h="d"}switch(h){case "b":c+=k?"true":"false";break;case "d":k=Math.trunc(k),0<=r&&(p=!0,n<r&&(n=r),r=-1);case "f":k=+k;h=k+"";0<=r&&(h=k.toFixed(r));h.length<n&&(p?(0>k&&(n--,h=h.substr(1)),
h=("0".repeat(n)+h).slice(-n),0>k&&(h="-"+h)):h=(" ".repeat(n)+h).slice(-n));c+=h;break;case "j":c+=JSON.stringify(k,null,n||void 0);break;case "c":k="string"==typeof k?k[0]:String.fromCharCode(k);case "s":if(void 0!=k)for("string"!=typeof k&&(k=k.toString()),0<=r&&(k=k.substr(0,r));k.length<n;)k=0<=q.indexOf("-")?k+" ":" "+k;c+=k;break;case "B":A=2,m&&(w="0b");case "o":A||(A=8),!w&&m&&(w="0o");case "X":V=za;case "x":h="";A||(A=16);!w&&m&&(w="0x");V||(V=Aa);"string"==typeof k&&"-"==k[0]&&(l=!0,k=
k.slice(1));k=Math.trunc(k);l&&(k=-k);0>k&&((k|0)==k?k>>>=0:Math.abs(k)<=Math.pow(2,53)&&(k+=Math.pow(2,53)));0<=r&&(p=!0,n<r&&(n=r));p&&!n&&("b"==J?n=2:"h"==J||"w"==J?n=4:"l"==J?n=8:(n=Math.abs(k),n=255>=n?2:65535>=n?4:4294967295>=n?8:9),n+=w.length);n-=w.length;do l=16,Number.isNaN(k)||(l=k&A-1,k=Math.trunc(k/A)),p||!h||l||k?h=V[l]+h:(w&&(h=w+h,w=""),0<n&&(h=" "+h));while(0<--n||k);c+=w+h;break;case "%":c+="%";break;default:c=this.g[h]?c+this.g[h](h,q,n,r,k):c+("(unimplemented sprintf type: %"+
h+")")}}}return c+=d[f]};var xa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),wa="January February March April May June July August September October November December".split(" "),Aa="0123456789abcdef?",za="0123456789ABCDEF?";
function Ba(a){var b=null,c=0==a.indexOf(Ca)?y.files:null;if(c){a=a.slice(Ca.length+1).split("/");var d,e;for(d=0;d<a.length;d++){var f=a[d],h=!1;if(!f){b=c;break}for(e=0;e<c.files.length;e++){var k=c.files[e];if(k.name.toLowerCase()==f.toLowerCase()){if(d==a.length-1){b=k;break}if(k.files){c=k;h=!0;break}}}if(b)break;if(!h&&d<a.length-1)break}}return b}var Ca="/pcfs",Da={Fe:1,De:2,Ge:4,He:8,Ee:15,Db:16,Ce:32};y.files||(y.files={name:"",size:0,Ie:Da.Db,Je:new Date,files:[]});function Ea(){}
function z(a,b,c){b?9<b&&(b=9):(b=Math.abs(a),b=255>=b?2:65535>=b?4:4294967295>=b?8:9);c=c?"0x":"";var d=void 0===d?0:d;var e="";isNaN(a)||"number"!=typeof a?a=null:(0>a&&-1<a&&(a=-1),0>a&&(a+=Math.pow(16,b)),a>=Math.pow(16,b)&&(b=Math.ceil(Math.log(a)/Math.log(16))));for(var f=d||-1;0<b--;){f||(e=","+e,f=d);if(null==a)e="?"+e;else{var h=a%16;h+=0<=h&&9>=h?48:55;e=String.fromCharCode(h)+e;a=Math.trunc(a/16)}f--}return(void 0===c?"":c)+e}
function Fa(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));return b}function Ga(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase(),"json5"==b&&(b="json"));return b}function Ha(a){return a.replace(/[&<>"'$]/g,function(b){return Ia[b]})}var Ia={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;",$:"&dollar;"},Ja=new ua,Ka=Ja.h.bind(Ja);
function B(a,b){var c=null,d=!0;c=void 0===c?"text":c;d=void 0===d?!1:d;var e=0,f=null,h=x.resources;if("object"==typeof h&&(f=h[a]))b&&b(a,f,e);else if(d&&"function"==typeof h)h(a,function(p,n){b&&b(a,p,n)});else{a=x.LOCALDISKS&&(x.location?x.location.hostname:"localhost").match(/^(.+\.local|localhost|0\.0\.0\.0|pcjs)$/)?a.replace(/^\/(diskettes|gamedisks|miscdisks|harddisks|decdisks|pcsigdisks|pcsig[0-9a-z]*-disks|private)\//,"/disks/$1/").replace(/^\/discs\/([^/]*)\//,"/disks/cdroms/$1/"):a.replace(/^\/(disks\/|)(diskettes|gamedisks|miscdisks|harddisks|decdisks|pcsigdisks|pcsig[0-9a-z]*-disks|private)\//,
"https://$2.pcjs.org/").replace(/^\/(disks\/cdroms|discs)\/([^/]*)\//,"https://$2.pcjs.org/");C(2199023255552,"getResource(%s)\n",a);if(sa.Be&&0!=a.indexOf("http")){try{h="arraybuffer"==c?null:"utf8",f=sa.Be(a,h),h||(f=f.buffer,f.buffer&&(f=f.buffer))}catch(p){e=p.errno}if(void 0!==f){b&&b(a,f,e);return}}if(0==a.indexOf(Ca)&&(h=Ba(a))){f=h.data;b&&b(a,f,e);return}!a.match(/^[A-Z]:/i)&&0>a.indexOf("?")&&(a=encodeURI(a));if(x.XMLHttpRequest)var k=new x.XMLHttpRequest;else if(x.ActiveXObject)k=new x.ActiveXObject("Microsoft.XMLHTTP");
else if(x.fetch){fetch(a).then(function(p){switch(c){case "json":case "text":return p.text();case "arraybuffer":return p.arrayBuffer();default:throw Error("unsupported response type: "+c);}}).then(function(p){C(2267742732288,"getResource(%s): fetched %d bytes\n",a,p.length);b&&b(a,p,e)}).catch(function(){C(68719476736,"getResource(%s) fetch error: %d\n",a,e);b&&b(a,f,e)});return}var l=!1,q="string"===typeof k.responseType;h=function(){if(4!==k.readyState)return null;try{f=l?k.response:k.responseText}catch(n){C(68719476736,
"getResource(%s) exception: %s\n",a,n.message)}if(null!=f&&(200==k.status||!k.status&&f.length&&"file:"==(x.location?x.location.protocol:"file:")))C(2267742732288,"getResource(%s): returned %d bytes\n",a,f.length);else if(e=k.status||-1,C(2199023255552,"getResource(%s) error: %d\n",a,e),!k.status&&!La){var p=a.match(/(^https?:\/\/[^/]+)(.*)/);p&&(La=!0,Ma("PCjs was unable to perform a cross-origin resource request to '"+p[1]+"'.\n\nIf you're running an ad blocker, try adding '"+Na()+"' to your whitelist (or find a smarter ad blocker)."))}b&&
b(a,f,e);return[f,e]};d&&(k.onreadystatechange=h);if(c&&"object"==typeof c){q="";for(var m in c)c.hasOwnProperty(m)&&(q&&(q+="&"),q+=m+"="+encodeURIComponent(c[m]));q=q.replace(/%20/g,"+");C(2267742732288,"getResource(%s): posted %d bytes\n",a,q.length);k.open("POST",a,d);k.setRequestHeader("Content-type","application/x-www-form-urlencoded");k.send(q)}else k.open("GET",a,d),"arraybuffer"==c&&(q?(l=!0,k.responseType=c):k.overrideMimeType("text/plain; charset=x-user-defined")),k.send();d||(k.readyState=
4,h())}}function Na(){return x.location?x.location.protocol+"//"+x.location.host:"https://www.pcjs.org"}function D(a){if(x.navigator){var b=x.navigator?x.navigator.userAgent:"";return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===x.navigator.platform&&1<x.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Oa(){var a,b=Pa("mobile");if(b)return"true"==b;if(D("Mobi")){if(!a)return!0;(b="!"==a[0])&&(a=a.substr(1));return D(a)!=b}return!1}
function Pa(a){if(!Qa){var b,c={};if(x.location){b||(b=x.location.search.substr(1));for(var d,e=/\+/g,f=/([^&=]+)=?([^&]*)/g;d=f.exec(b);)c[decodeURIComponent(d[1].replace(e," "))]=decodeURIComponent(d[2].replace(e," "))}Qa=c}return Qa[a]||Qa[a.toLowerCase()]}function Ra(a,b,c){function d(){--a;0<=a&&(b()||(a=0));0<a?setTimeout(d,0):c()}d()}
function Sa(a,b){function c(){b(100===d)&&(e=setTimeout(c,d),d=100)}var d=0,e=null,f=!1;a.onmousedown=function(){f||e||(d=500,c())};a.ontouchstart=function(){e||(d=500,c())};a.onmouseup=a.onmouseout=function(){e&&(clearTimeout(e),e=null)};a.ontouchend=a.ontouchcancel=function(){e&&(clearTimeout(e),e=null);f=!0}}function E(a){Ta.init.push(a)}
function F(a){if((a=Ta[a])&&Ua)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){C(274877906944,"%s\n\nIf it happens again, please send the URL to support@pcjs.org. Thanks.\n","An unexpected error occurred: "+c.message)}}function G(a){!Ua&&a?(Ua=!0,Va&&F("init"),Wa&&F("show")):Ua=a}var Qa=null,Ta={init:[],show:[],exit:[]},Va=!1,Wa=!1,Ua=!0,La=!1;function Xa(){Va=!0;F("init",!0)}x.addEventListener&&x.addEventListener("load",Xa);function Za(){Wa=!0;F("show",!0)}
x.addEventListener&&x.addEventListener("pageshow",Za);var $a=D("iOS")?"pagehide":D("Opera")?"unload":"beforeunload";function ab(){F("exit",!0)}x.addEventListener&&x.addEventListener($a,ab);
function H(a,b,c){this.type=a;b||(b={id:"",name:""});this.name=b.name;++bb;this.id=this.id=b.id||"";this.exports={};this.M=this.bindings={};a=this.id.indexOf(".");0>a?this.Xa="PCjs":this.Xa=this.id.substr(0,a);this.J={ready:!1,Ia:!1,Sa:!1,Le:!1,V:!1,Ne:!1,error:!1};this.Wa=null;this.J.error=!1;this.ta=c||0;this.C=this.D=this.fa=null;y.components.push(this)}function cb(a,b,c){y.machines[a]&&b&&(y.machines[a][b]=c,"parms"==b&&"string"==typeof c&&(y.machines[a].config=eval("("+c+")")))}
function db(){return Date.now()||+new Date}function C(a){var b=oa.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());if(68719476736<=c&&1099511627776>=c){var d=!1;1099511627776==c?(d=!0,a="Error: "+a):549755813888==c?(d=!0,a="Warning: "+a):274877906944==c&&(d=!0);b=Ka.apply(Ea,[a].concat(ca(b))).trim();d?Ma(b):console.log(b)}}function Ma(a){x.alert&&x.alert(a);console.log(a)}
function I(a,b){b=L("c1p-control","",b.parentNode);for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,e=0;e<d.length;e++){var f=d[e];if(1===f.nodeType){var h=f.getAttribute("class");if(h)for(var k=h.split(" "),l=0;l<k.length;l++)switch(h=k[l],h){case "c1p-binding":(h=M(f))&&void 0!==h.binding?a.da(h.type,h.binding,f,h.value):h&&"description"==h.type||C(549755813888,'Component "%s" missing binding%s\n',a.toString(),h?" for "+h.type:""),l=k.length}}}}
function eb(a,b){if(void 0!==a){var c;b&&0<(c=b.indexOf("."))&&(a=b.substr(0,c+1)+a);var d=y.components;for(c=0;c<d.length;c++)if(d[c].id===a)return d[c];d.length&&!1!==b&&C(549755813888,'Component ID "%s" not found\n',a)}return null}function fb(a,b,c){c=void 0===c?null:c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");var e=y.components;for(d=0;d<e.length;d++)if(c)c==e[d]&&(c=null);else if(!(a!=e[d].type||b&&e[d].id.indexOf(b)))return e[d]}return null}
function M(a){var b=null;if(a.getAttribute){if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(d){C(1099511627776,d.message+" ("+a+")")}}else if(b=a.config||null){a=a.id;var c=b.id;a&&c&&0>c.indexOf(".")&&(b.id=a+"."+c)}return b}
function L(a,b,c){b=void 0===b?"":b;c=void 0===c?ta:c;var d=[];b&&(a+="-"+b,"machine"!=b&&(a+="-object"));if(ra)if(c.getElementsByClassName)d=c.getElementsByClassName(a);else{if(c.getElementsByTagName){b=c.getElementsByTagName("*");var e=new RegExp("(^| )"+a+"( |$)");a=0;for(c=b.length;a<c;a++)e.test(b[a].className)&&d.push(b[a])}}else for(a=Object.keys(y.machines),c=0;c<a.length;c++){e=a[c];var f=y.machines[e].config;if(f&&(f=f[b])){Array.isArray(f)||(f=[f]);f=ba(f);for(var h=f.next();!h.done;h=
f.next())d.push({id:e,config:h.value})}}return d}
function gb(a){for(var b=!0,c=y.commands[a];c&&c.length;){var d=c.splice(0,1)[0],e=d[0];C(8796093022208,d.join(" "));var f=null;0<=hb.indexOf(e)&&(f=function(){return function(){gb(a)}}());var h=ib[e];if(h)if(!f)b=h(d[1],d[2],d[3]);else{if(!h(f,d[1],d[2],d[3]))break}else{b=!1;var k=fb(d[1],a);if(k)if(h=jb[e])b=h(k,d[2],d[3]);else{var l=k.exports;if(l&&(h=l[e]))if(b=!0,!f)b=h.call(k,d[2],d[3]);else if(!h.call(k,f,d[2],d[3]))break}}if(!b){Ma("Script error: '"+e+"' command "+(h?" failed":" not recognized"));
break}}c&&!c.length&&delete y.commands[a];return b}g=H.prototype;g.toString=function(){return this.name?this.name:this.id||this.type};function kb(a){var b=1;a.Xa&&(a=a.Xa.match(/\d+/),null!==a&&(b=parseInt(a[0],10)));return b}
g.da=function(a,b,c){switch(b){case "clear":return this.M[b]||(this.M[b]=c,c.onclick=function(d){return function(){d.M.print&&(d.M.print.value="")}}(this)),!0;case "print":return this.M[b]||(this.M[b]=c,c.value="",this.print=function(d,e){return function(f,h){f||(f="");if(4398046511104==(void 0===h?0:h)&&"...\n"==f.slice(-4)){h=f.slice(0,-1);var k=e.value,l=k.lastIndexOf(h);k=0>l?k+(h+"\n"):k.substr(0,l)+(f.slice(0,-1)+".")+k.substr(l+h.length);8192<k.length&&(k=k.substr(k.length-4096));e.value=k}else e.value+=
f,f=e.value,8192<f.length&&(e.value=f.substr(f.length-4096));e.scrollTop=e.scrollHeight}}(this,c)),!0;default:return!1}};g.print=function(a,b){C(void 0===b?0:b,a)};function lb(a,b){a.J.error=!0;a.u(274877906944,"%s\n",b)}function N(a,b){b&&(a.J.ready?b():a.Wa=b);return a.J.ready}g.ea=function(){if(!this.J.error&&(this.J.ready=!0,this.J.ready)){var a=this.Wa;this.Wa=null;a&&a()}};function mb(a,b){a.J.Ia&&(b?a.J.Sa=!0:void 0===b&&a.print(a.toString()+" busy\n"));return a.J.Ia}
function nb(a,b){if(a.J.Sa)return a.J.Ia=!1,a.J.Sa=!1;if(a.J.error)return a.print(a.toString()+" error\n"),!1;a.J.Ia=b;return a.J.Ia}function ob(a,b){var c=Math.pow(2,32),d=b/c|0;return(a&b)==(b|0)&&((a/c|0)&d)==d}function P(a,b){b=void 0===b?0:b;b&1&&--b;b=b||a.ta;return!ob(b,2199023255552)&&(ob(0xff000000000-(a.C?618475290624:0),b)||a.C&&ob(a.C.ta,b))?!0:!1}
g.u=function(a){var b=oa.apply(1,arguments),c=0;"number"==typeof a&&(c=a||4398046511104,a=b.shift(),ob(c,68719476736)?a=(this.id||this.type||"log")+": "+a:ob(c,137438953472)&&(a=this.type+": "+a));P(this,c)&&(b=Ka.apply(Ea,[a].concat(ca(b))),this.C&&this.C.message?this.C.message(b,c):this.print(b,c))};
var hb=["hold","sleep","wait"],ib={alert:function(a){Ma(a);return!0},sleep:function(a,b){setTimeout(a,+b);return!1}},jb={select:function(a,b,c){var d=!1;if(a=a.bindings[b])for(b=0;b<a.options.length;b++)if(a.options[b].textContent==c){a.selectedIndex!=b&&(a.selectedIndex=b);d=!0;break}return d}},bb=0;Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});
Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return e.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),e=this;c.prototype=this.prototype;b.prototype=new c;return b});
function pb(a){H.call(this,"C1PPanel",a);this.J.V=!1}v(pb,H);pb.prototype.da=function(a,b,c,d){return this.fa&&this.fa.da(a,b,c,d)||this.D&&this.D.da(a,b,c,d)||this.h&&this.h.da(a,b,c,d)||this.C&&this.C.da(a,b,c,d)?!0:H.prototype.da.call(this,a,b,c,d)};pb.prototype.sa=function(a,b){a&&!this.J.V&&(this.J.V=!0,this.fa=b,this.D=Q(b,"cpu"),this.h=Q(b,"keyboard"),this.C=Q(b,"debugger"),qb())};
function qb(){for(var a=!1,b=L("c1p","panel"),c=0;c<b.length;c++){var d=b[c],e=M(d),f=eb(e.id,!1);f||(a=!0,f=new pb(e));I(f,d);a&&f.ea()}}E(qb);
function rb(a){H.call(this,"C1PCPU",a);sb(this);this.J.V=!1;this.J.xa=!1;var b=Pa("autoStart");this.va="true"==b||"false"==b?JSON.parse(b):a.autoStart;this.Pa=0;this.vb=1;this.wb=2;this.speed=this.Pa;this.oa=30;this.na=5;this.Ka=8;this.ra=["Slow","Fast","Max"];this.Fa=["(1Mhz)","(up to "+this.Ka+"Mhz)","(unlimited)"];this.T=[];this.N=[];this.ha=65536;this.ia=0;this.aa=65536;this.ba=0;this.Oa=32;this.Va=2;this.ub=1;this.v=[this.jc,this.Dd,this.ue,this.A,this.A,this.Fd,this.Zb,this.A,this.Id,this.Cd,
this.Yb,this.A,this.A,this.zd,this.Wb,this.A,this.ic,this.Ed,this.A,this.A,this.A,this.Gd,this.$b,this.A,this.mc,this.Bd,this.A,this.A,this.A,this.Ad,this.Xb,this.A,this.$c,this.Sb,this.A,this.A,this.ec,this.Ub,this.Od,this.A,this.Kd,this.Rb,this.Nd,this.A,this.dc,this.Ob,this.Ld,this.A,this.fc,this.Tb,this.A,this.A,this.A,this.Vb,this.Pd,this.A,this.ee,this.Qb,this.A,this.A,this.A,this.Pb,this.Md,this.A,this.Vd,this.Oc,this.A,this.A,this.A,this.Qc,this.wd,this.A,this.Hd,this.Nc,this.vd,this.A,this.Zc,
this.Kc,this.td,this.A,this.kc,this.Pc,this.A,this.A,this.A,this.Rc,this.xd,this.A,this.oc,this.Mc,this.A,this.A,this.A,this.Lc,this.ud,this.A,this.Wd,this.cb,this.A,this.A,this.A,this.fb,this.Td,this.A,this.Jd,this.bb,this.Sd,this.A,this.Yc,this.Za,this.Qd,this.A,this.lc,this.eb,this.A,this.A,this.A,this.gb,this.Ud,this.A,this.ge,this.ab,this.A,this.A,this.A,this.$a,this.Rd,this.A,this.A,this.ke,this.A,this.A,this.se,this.me,this.pe,this.A,this.Jc,this.A,this.ye,this.A,this.re,this.he,this.oe,this.A,
this.ac,this.le,this.A,this.A,this.te,this.ne,this.qe,this.A,this.Ae,this.je,this.ze,this.A,this.A,this.ie,this.A,this.A,this.qd,this.ed,this.ld,this.A,this.rd,this.gd,this.md,this.A,this.we,this.dd,this.ve,this.A,this.od,this.ad,this.jd,this.A,this.bc,this.fd,this.A,this.A,this.sd,this.hd,this.nd,this.A,this.pc,this.cd,this.xe,this.A,this.pd,this.bd,this.kd,this.A,this.Cc,this.uc,this.A,this.A,this.Dc,this.wc,this.Gc,this.A,this.Xc,this.tc,this.Ic,this.A,this.Bc,this.qc,this.Ec,this.A,this.hc,this.vc,
this.A,this.A,this.A,this.xc,this.Hc,this.A,this.nc,this.sc,this.A,this.A,this.A,this.rc,this.Fc,this.A,this.zc,this.lb,this.A,this.A,this.Ac,this.nb,this.Uc,this.A,this.Wc,this.kb,this.yd,this.A,this.yc,this.hb,this.Sc,this.A,this.cc,this.mb,this.A,this.A,this.A,this.ob,this.Vc,this.A,this.fe,this.jb,this.A,this.A,this.A,this.ib,this.Tc,this.A];this.Ea=[7,6,0,0,0,3,5,0,3,2,2,0,0,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,3,6,0,0,3,3,5,0,4,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,
3,2,2,0,3,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,4,2,2,0,5,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,0,6,0,0,3,3,3,0,2,0,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,0,4,0,0,2,6,2,0,3,3,3,0,2,2,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,4,4,4,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0]}v(rb,H);g=rb.prototype;
g.reset=function(a){this.J.xa&&this.la();sb(this);this.j=this.g[65532]|this.g[65533]<<8;this.J.error=!1;this.C?this.C.reset():a&&(!0===this.va||null===this.va&&!this.C&&void 0===this.M.run)&&this.ya()};
g.da=function(a,b,c){a=!1;switch(b){case "run":this.M[b]=c;c.onclick=function(d){return function(){d.J.xa?d.la():d.ya()}}(this);a=!0;break;case "A":case "X":case "Y":case "S":case "PC":case "C":case "Z":case "I":case "D":case "B":case "V":case "N":case "speed":this.M[b]=c;a=!0;break;case "setSpeed":this.M[b]=c,c.onclick=function(d){return function(){tb(d,2<=d.speed?d.Pa:d.speed+1,!0)}}(this),a=!0}return a};
g.pa=function(a,b,c){this.g=a;this.R=b;this.La=c-b+1;this.ma=this.R+this.La;this.R?C(1099511627776,"unsupported CPU address buffer offset ("+this.R+")"):this.ea()};g.sa=function(a,b){if(a&&!this.J.V){this.fa=b;(this.C=Q(b,"debugger"))&&this.C.u("Type ? for list of debugger commands\n\n");if(a=Q(b,"video"))this.Ta=function(c){return function(){ub(c)}}(a),this.qa=function(c){return function(){c.qa()}}(a);this.J.V=!0;this.reset(!0);this.update()}};
function vb(a,b,c,d,e){0>wb(a.T,b,c,d,e)&&(a.ha>b&&(a.ha=b),a.ia<c&&(a.ia=c),a.T.push([b,c,d,e]))}function xb(a,b,c){for(var d=0;d<a.T.length;d++)b>=a.T[d][0]&&b<=a.T[d][1]&&a.T[d][3].call(a.T[d][2],b,c)}function yb(a,b,c,d,e){0>wb(a.N,b,c,d,e)&&(a.aa>b&&(a.aa=b),a.ba<c&&(a.ba=c),a.N.push([b,c,d,e]))}function zb(a,b,c){for(var d=0;d<a.N.length;d++)b>=a.N[d][0]&&b<=a.N[d][1]&&a.N[d][3].call(a.N[d][2],b,c)}
function wb(a,b,c,d,e){for(var f=0;f<a.length;f++)if(a[f][0]==b&&a[f][1]==c&&a[f][2]==d&&a[f][3]==e)return f;return-1}function tb(a,b,c){void 0!==b&&(a.speed=b,a.M.setSpeed&&(a.M.setSpeed.innerHTML=a.ra[2<=b?0:b+1]),a.u("running at %s speed %s\n",a.ra[b].toLowerCase(),a.Fa[b]),c&&a.qa());a.W=0;a.wa=db();Ab(a)}g.Ta=function(){};g.qa=function(){};function R(a,b,c,d){void 0!==a.M[b]&&(void 0===d&&(d=1),c="0000"+c.toString(16),a.M[b].innerHTML=c.slice(c.length-d).toUpperCase())}
function Bb(a){R(a,"A",a.m,2);R(a,"X",a.G,2);R(a,"Y",a.K,2);var b=Cb(a);R(a,"C",b&1?1:0);R(a,"Z",b&2?1:0);R(a,"I",b&4?1:0);R(a,"D",b&8?1:0);R(a,"B",b&16?1:0);R(a,"V",b&64?1:0);R(a,"N",b&128?1:0);R(a,"S",a.L,4);R(a,"PC",a.j,4);a.M.speed&&a.S&&(a.M.speed.innerHTML=a.S.toFixed(1)+"Mhz")}
function Ab(a,b){var c=30;c<a.oa&&(c=a.oa);c<a.na&&(c=a.na);var d=1;b&&a.speed>a.Pa&&a.S&&(d=a.S);d>a.Ka&&2>a.speed&&(d=a.Ka);a.Ga=Math.round(1E3/30);a.ga=Math.floor(1E6/c*d);a.ja=Math.floor(1E6/30*d);a.Aa=Math.floor(1E6/a.oa*d);a.za=Math.floor(1E6/a.na*d);b||(a.U=a.ja,a.Y=a.Aa,a.X=a.za);a.ka=0}
function Db(a){var b=db(),c=a.Ga;a.Z&&(c=Math.round(c*a.Z/a.ja));c-=b-a.Ha;var d=a.W;if(b-=a.wa)a.S=Math.round(d/(100*b))/10,864E5<=b&&tb(a);0>c?c=0:1==a.speed?a.S<=a.Ka&&(c=0):2==a.speed&&(c=0);a.ka+=a.Z;return c}
g.ya=function(){if(nb(this,!0)){this.J.xa||(tb(this),this.fa&&this.fa.start(),this.J.xa=!0,this.M.run&&(this.M.run.innerHTML="Halt"),this.qa());1E6<=this.ka&&Ab(this,!0);this.Z=0;this.Ha=db();try{do{this.step(this.ga);var a=this.P-this.I;this.W+=a;this.Z+=a;this.P=this.I=0;this.Y-=this.ga;0>=this.Y&&(this.Y+=this.Aa,this.Ta());this.X-=this.ga;0>=this.X&&(this.X+=this.za,Bb(this));this.U-=this.ga;if(0>=this.U){this.U+=this.ja;break}}while(this.J.xa)}catch(b){this.la();this.update();nb(this,!1);lb(this,
b.stack||b.message);return}setTimeout(function(b){return function(){b.ya()}}(this),Db(this))}else this.update(),this.fa&&this.fa.stop(this.wa,this.W)};
g.step=function(a){var b=!0;this.h=this.l=-1;var c;if(c=a&&this.C)c=this.C,c=0<c.X.length||0<c.Z.length||0<c.ba.length;this.P=this.I=a;do{a=this.g[this.j];var d;if(d=c){d=this.C;var e=a,f=!1;Eb(d,this.j,d.X,"exec")?f=!0:(d.ha++,d.T[e][1]++,d.aa[d.ka++]=d.D.j,d.ka>=d.aa.length&&(d.ka=0));d=!!f}if(d){b=void 0;this.la();break}this.j++;this.v[a].call(this);if(0<=this.h){this.h>=this.ha&&this.h<=this.ia&&xb(this,this.h,this.j);if(d=c)d=this.C,e=!1,Eb(d,this.h,d.Z,"read")&&(e=!0),d=!!e;if(d){b=!1;this.la();
break}this.h=-1}else if(0<=this.l){this.l>=this.aa&&this.l<=this.ba&&zb(this,this.l,this.j);if(d=c){d=this.C;e=this.l;f=this.g[this.l];var h=!1;(f&255)!=f&&(d.u("invalid value at %#06x: %s\n",e,f),h=!0);Eb(d,e,d.ba,"write")&&(h=!0);d=!!h}if(d){b=!1;this.la();break}this.l=-1}this.I-=this.Ea[a]}while(0<this.I);return b};function Fb(a){a.U=0;a.P-=a.I;a.I=0}g.la=function(){mb(this,!0);this.P-=this.I;this.I=0;this.J.xa&&(this.J.xa=!1,this.M.run&&(this.M.run.innerHTML="Run"))};
g.update=function(){this.Ta();Bb(this)};function Gb(a){return a.J.xa?a.W+a.P-a.I:0}g.ca=function(a){return this.g[a]};function Cb(a){var b=a.i&256?1:0;b|=a.s&255?0:2;b|=(a.B&255^a.F^a.B>>1)&128?64:0;b|=a.o&128?128:0;return a.H&60|b}function Hb(a){a.H|=8;a.v[97]=a.Kb;a.v[101]=a.Mb;a.v[105]=a.Jb;a.v[109]=a.Gb;a.v[113]=a.Lb;a.v[117]=a.Nb;a.v[121]=a.Ib;a.v[125]=a.Hb;a.v[225]=a.ae;a.v[229]=a.ce;a.v[233]=a.$d;a.v[237]=a.Xd;a.v[241]=a.be;a.v[245]=a.de;a.v[249]=a.Zd;a.v[253]=a.Yd}
function Ib(a){a.H&=-9;a.v[97]=a.cb;a.v[101]=a.fb;a.v[105]=a.bb;a.v[109]=a.Za;a.v[113]=a.eb;a.v[117]=a.gb;a.v[121]=a.ab;a.v[125]=a.$a;a.v[225]=a.lb;a.v[229]=a.nb;a.v[233]=a.kb;a.v[237]=a.hb;a.v[241]=a.mb;a.v[245]=a.ob;a.v[249]=a.jb;a.v[253]=a.ib}function S(a,b,c){var d=a.i&256?1:0,e=(b&15)+(c&15)+d;10<=e&&(e=e+6&15|16);e+=(b&240)+(c&240);a.F=b^c;a.B=e;a.o=e&255;160<=e&&(e+=96);512<=e&&(e-=256);a.i=e;a.s=b+c+d&255;a.I--;return e&255}
function T(a,b,c){var d=a.i&256?0:1,e=(b&15)-(c&15)-d;0>e&&(e=(e-6&15)-16);e+=(b&240)-(c&240);0>e&&(e-=96);a.o=a.s=(a.i=b-c-d)&255;a.F=b^c;a.B=a.i;a.i^=256;a.I--;return e&255}function sb(a){a.m=0;a.G=0;a.K=0;a.L=256;a.H=0;a.o=0;a.s=0;a.F=0;a.B=0;a.i=0;a.j=0;a.h=-1;a.l=-1;a.S=0;a.W=a.P=a.I=0}
g.jc=function(){this.j++;this.g[this.L--]=this.j>>8;this.L|=256;this.g[this.L--]=this.j&255;this.L|=256;this.H|=16;this.H=Cb(this);this.g[this.L--]=this.H;this.L|=256;this.H&=239;this.h=65534;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.Dd=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m|=this.g[this.h]};g.Fd=function(){this.h=this.g[this.j++];this.o=this.s=this.m|=this.g[this.h]};
g.Zb=function(){this.l=this.g[this.j++];this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.Id=function(){this.H=Cb(this);this.g[this.L--]=this.H;this.L|=256};g.Cd=function(){this.h=this.j++;this.o=this.s=this.m|=this.g[this.h]};g.Yb=function(){this.i=this.m<<1;this.o=this.s=this.m=this.i&255};g.zd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m|=this.g[this.h]};
g.Wb=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.ic=function(){this.j+=(this.o&128?0:(this.I--,this.g[this.j]<<24>>24))+1};g.Ed=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m|=this.g[this.h]};g.Gd=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m|=this.g[this.h]};
g.$b=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.mc=function(){this.i=0};g.Bd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m|=this.g[this.h]};g.Ad=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m|=this.g[this.h]};g.Xb=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};
g.$c=function(){this.h=this.j++;this.g[this.L--]=this.j>>8;this.L|=256;this.g[this.L--]=this.j&255;this.L|=256;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.Sb=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m&=this.g[this.h]};g.ec=function(){this.h=this.g[this.j++];this.s=this.m&this.g[this.h];this.o=this.o&127|this.g[this.h]&128;this.B=0;this.F=this.g[this.h]&64?128:0};g.Ub=function(){this.h=this.g[this.j++];this.o=this.s=this.m&=this.g[this.h]};
g.Od=function(){this.l=this.g[this.j++];this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.Kd=function(){this.L=this.L+1&255|256;this.H=this.g[this.L];this.i=this.H&1?256:0;this.s=this.H&2?0:1;this.o=this.H&128;this.B=0;this.F=this.H&64?128:0};g.Rb=function(){this.h=this.j++;this.o=this.s=this.m&=this.g[this.h]};
g.Nd=function(){this.i=this.i&65280|this.m;this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.m=this.i&255};g.dc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.s=this.m&this.g[this.h];this.o=this.o&127|this.g[this.h]&128;this.B=0;this.F=this.g[this.h]&64?128:0};g.Ob=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m&=this.g[this.h]};
g.Ld=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.fc=function(){this.j+=(this.o&128?(this.I--,this.g[this.j]<<24>>24):0)+1};g.Tb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m&=this.g[this.h]};g.Vb=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m&=this.g[this.h]};
g.Pd=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.ee=function(){this.i=256};g.Qb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m&=this.g[this.h]};g.Pb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m&=this.g[this.h]};
g.Md=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.Vd=function(){this.L=this.L+1&255|256;this.H=this.g[this.L];this.i=this.H&1?256:0;this.s=this.H&2?0:1;this.o=this.H&128;this.B=0;this.F=this.H&64?128:0;this.L=this.L+2&255|256;this.j=this.g[this.L-1|256]|this.g[this.L]<<8};
g.Oc=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m^=this.g[this.h]};g.Qc=function(){this.h=this.g[this.j++];this.o=this.s=this.m^=this.g[this.h]};g.wd=function(){this.l=this.g[this.j++];this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};g.Hd=function(){this.g[this.L--]=this.m;this.L|=256};g.Nc=function(){this.h=this.j++;this.o=this.s=this.m^=this.g[this.h]};
g.vd=function(){this.i=this.i&65279|(this.m&1?256:0);this.m=(this.i=this.i&65280|this.m>>1)&255;this.o=this.s=this.i&255};g.Zc=function(){this.h=this.j;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.Kc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m^=this.g[this.h]};g.td=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.kc=function(){this.j+=((this.B&255^this.F^this.B>>1)&128?0:(this.I--,this.g[this.j]<<24>>24))+1};g.Pc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m^=this.g[this.h]};g.Rc=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m^=this.g[this.h]};g.xd=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.oc=function(){this.H&=251};g.Mc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m^=this.g[this.h]};g.Lc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m^=this.g[this.h]};g.ud=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.Wd=function(){this.L=this.L+2&255|256;this.j=(this.g[this.L-1|256]|this.g[this.L]<<8)+1};g.cb=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.Kb=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.m=S(this,this.m,this.g[this.h])};
g.fb=function(){this.h=this.g[this.j++];this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.Mb=function(){this.h=this.g[this.j++];this.m=S(this,this.m,this.g[this.h])};g.Td=function(){this.l=this.g[this.j++];this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.Jd=function(){this.L=this.L+1&255|256;this.o=this.s=this.m=this.g[this.L]};
g.bb=function(){this.h=this.j++;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.Jb=function(){this.h=this.j++;this.m=S(this,this.m,this.g[this.h])};g.Sd=function(){this.i=this.i&65280|this.m;this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.m=this.i&255};g.Yc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.j=this.g[this.h]|this.g[this.h+1]<<8};
g.Za=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.Gb=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.m=S(this,this.m,this.g[this.h])};g.Qd=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};
g.lc=function(){this.j+=((this.B&255^this.F^this.B>>1)&128?(this.I--,this.g[this.j]<<24>>24):0)+1};g.eb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.Lb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.m=S(this,this.m,this.g[this.h])};
g.gb=function(){this.h=this.g[this.j++]+this.G&255;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.Nb=function(){this.h=this.g[this.j++]+this.G&255;this.m=S(this,this.m,this.g[this.h])};g.Ud=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.ge=function(){this.H|=4};
g.ab=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.Ib=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.m=S(this,this.m,this.g[this.h])};g.$a=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};
g.Hb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.m=S(this,this.m,this.g[this.h])};g.Rd=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.ke=function(){this.l=this.g[this.j++]+this.G&255;this.l=this.g[this.l]|this.g[this.l+1]<<8;this.g[this.l]=this.m};g.se=function(){this.l=this.g[this.j++];this.g[this.l]=this.K};
g.me=function(){this.l=this.g[this.j++];this.g[this.l]=this.m};g.pe=function(){this.l=this.g[this.j++];this.g[this.l]=this.G};g.Jc=function(){this.o=this.s=this.K=this.K-1&255};g.ye=function(){this.o=this.s=this.m=this.G};g.re=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.K};g.he=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.m};g.oe=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.G};
g.ac=function(){this.j+=(this.i&256?0:(this.I--,this.g[this.j]<<24>>24))+1};g.le=function(){this.l=this.g[this.j++];this.l=(this.g[this.l]|this.g[this.l+1]<<8)+this.K;this.g[this.l]=this.m};g.te=function(){this.l=this.g[this.j++]+this.G&255;this.g[this.l]=this.K};g.ne=function(){this.l=this.g[this.j++]+this.G&255;this.g[this.l]=this.m};g.qe=function(){this.l=this.g[this.j++]+this.K&255;this.g[this.l]=this.G};g.Ae=function(){this.o=this.s=this.m=this.K};
g.je=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.g[this.l]=this.m};g.ze=function(){this.L=this.G|256};g.ie=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.g[this.l]=this.m};g.qd=function(){this.h=this.j++;this.o=this.s=this.K=this.g[this.h]};g.ed=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m=this.g[this.h]};g.ld=function(){this.h=this.j++;this.o=this.s=this.G=this.g[this.h]};
g.rd=function(){this.h=this.g[this.j++];this.o=this.s=this.K=this.g[this.h]};g.gd=function(){this.h=this.g[this.j++];this.o=this.s=this.m=this.g[this.h]};g.md=function(){this.h=this.g[this.j++];this.o=this.s=this.G=this.g[this.h]};g.we=function(){this.o=this.s=this.K=this.m};g.dd=function(){this.h=this.j++;this.o=this.s=this.m=this.g[this.h]};g.ve=function(){this.o=this.s=this.G=this.m};g.od=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.K=this.g[this.h]};
g.ad=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m=this.g[this.h]};g.jd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.G=this.g[this.h]};g.bc=function(){this.j+=(this.i&256?(this.I--,this.g[this.j]<<24>>24):0)+1};g.fd=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m=this.g[this.h]};g.sd=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.K=this.g[this.h]};
g.hd=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m=this.g[this.h]};g.nd=function(){this.h=this.g[this.j++]+this.K&255;this.o=this.s=this.G=this.g[this.h]};g.pc=function(){this.F=this.B=0};g.cd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m=this.g[this.h]};g.xe=function(){this.o=this.s=this.G=this.L&255};g.pd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.K=this.g[this.h]};
g.bd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m=this.g[this.h]};g.kd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.G=this.g[this.h]};g.Cc=function(){this.h=this.j++;this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.uc=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};
g.Dc=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.wc=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Gc=function(){this.l=this.g[this.j++];this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.Xc=function(){this.o=this.s=this.K=this.K+1&255};g.tc=function(){this.h=this.j++;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Ic=function(){this.o=this.s=this.G=this.G-1&255};
g.Bc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.qc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Ec=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.hc=function(){this.j+=(this.s&255?(this.I--,this.g[this.j]<<24>>24):0)+1};
g.vc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.xc=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Hc=function(){this.l=this.g[this.j++]+this.G&255;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.nc=function(){Ib(this)};
g.sc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.rc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Fc=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.zc=function(){this.h=this.j++;this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.lb=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.ae=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.m=T(this,this.m,this.g[this.h])};g.Ac=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.nb=function(){this.h=this.g[this.j++];this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.ce=function(){this.h=this.g[this.j++];this.m=T(this,this.m,this.g[this.h])};g.Uc=function(){this.l=this.g[this.j++];this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.Wc=function(){this.o=this.s=this.G=this.G+1&255};
g.kb=function(){this.h=this.j++;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.$d=function(){this.h=this.j++;this.m=T(this,this.m,this.g[this.h])};g.yd=function(){};g.yc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.hb=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.Xd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.m=T(this,this.m,this.g[this.h])};g.Sc=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.cc=function(){this.j+=(this.s&255?0:(this.I--,this.g[this.j]<<24>>24))+1};
g.mb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.be=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.m=T(this,this.m,this.g[this.h])};
g.ob=function(){this.h=this.g[this.j++]+this.G&255;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.de=function(){this.h=this.g[this.j++]+this.G&255;this.m=T(this,this.m,this.g[this.h])};g.Vc=function(){this.l=this.g[this.j++]+this.G&255;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.fe=function(){Hb(this)};
g.jb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.Zd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.m=T(this,this.m,this.g[this.h])};
g.ib=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.Yd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.m=T(this,this.m,this.g[this.h])};g.Tc=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};
g.ue=function(){var a=this.g[this.j++];switch(a){case 0:this.u("HALT\n");this.la();break;case 1:a=this.j;for(var b="";a<this.g.length;){var c=this.g[a++];if(!c)break;b+=String.fromCharCode(c)}this.j=a;b=b.replace(/%A/g,z(this.m,2)).replace(/%X/g,z(this.G,2)).replace(/%Y/g,z(this.K,2));this.u("%s\n",b);Fb(this);break;default:this.j-=2,this.u("undefined opSim: %#04x at %#06x\n",a,this.j),this.la()}};g.A=function(){var a=this.g[--this.j];this.u("undefined opcode: %#04x at %#06x\n",a,this.j);this.la()};
E(function(){for(var a=L("c1p","cpu"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new rb(d);I(d,c)}});function Jb(a){H.call(this,"C1PROM",a);this.h=this.g=null;this.l=+a.size;if(this.v=a.file||a.image){a=this.v;var b=Ga(this.v);"json"!=b&&"hex"!=b&&(a=Na()+"/api/v1/dump?file="+this.v+"&format=bytes");var c=this;B(a,function(d,e,f){Kb(c,d,e,f)})}else this.ea()}v(Jb,H);
Jb.prototype.pa=function(a,b,c,d){this.g=a;this.B=b;a=c-b+1;this.l||(this.l=a);a!=this.l?lb(this,"computer-specified ROM size ("+z(a,4,!0)+") does not match component-specified size ("+z(this.l,4,!0)+")"):(d&&(this.D=d,yb(d,b,c,this,this.F)),Lb(this))};Jb.prototype.sa=function(a,b){a&&!this.J.V&&(this.J.V=!0,this.C=Q(b,"debugger"))};Jb.prototype.F=function(a,b){void 0!==b&&(this.C&&W(this.C,this,a,b,this.C.sb,!0),a-=this.B,this.g[this.B+a]=this.h?this.h[a]:0)};
function Kb(a,b,c,d){if(d)a.u('Error loading ROM "%s" (%d)\n',b,d);else{if("["==c.charAt(0)||"{"==c.charAt(0))try{var e=eval("("+c+")"),f=e.bytes;a.h=f?f:e}catch(h){a.u('Error processing ROM "%s": %s\n',b,h.message);return}else for(b=c.replace(/\n/gm," ").replace(/ +$/,"").split(" "),a.h=Array(b.length),c=0;c<b.length;c++)a.h[c]=parseInt(b[c],16);Lb(a)}}
function Lb(a){if(!N(a))if(!a.v)a.ea();else if(a.h&&a.g){var b=a.h.length;if(b!=a.l)lb(a,"ROM image size ("+z(b,4,!0)+") does not match component-specified size ("+z(a.l,4,!0)+")");else{for(var c=0;c<b;c++)a.g[a.B+c]=a.h[c];a.ea()}}}E(function(){for(var a=L("c1p","rom"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Jb(d);I(d,c)}});function Mb(a){H.call(this,"C1PRAM",a)}v(Mb,H);Mb.prototype.pa=function(a){this.g=a;this.ea()};
E(function(){for(var a=L("c1p","ram"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Mb(d);I(d,c)}});
function Nb(a){H.call(this,"C1PKeyboard",a);this.J.V=!1;this.Ea=a.model;this.ha=8;this.Ga=10;this.Fa=13;this.ia=27;this.za=this.ha;this.Aa=this.Ga;this.va=this.Fa;this.ba=this.ia;this.F=224;this.l=16+this.F;this.T=17+this.F;this.U=18+this.F;this.ga=20+this.F;this.aa=this.F;this.wa=3;this.La=15;this.P=1;this.R={};this.R["break"]=this.aa;this.R.esc=this.ba;this.R["ctrl-c"]=this.wa;this.R["ctrl-o"]=this.La;this.h=[];this.h[49]=30464;this.h[33]=30464+this.l;this.h[50]=30208;this.h[34]=30208+this.l;this.h[51]=
29952;this.h[35]=29952+this.l;this.h[52]=29696;this.h[36]=29696+this.l;this.h[53]=29440;this.h[37]=29440+this.l;this.h[54]=29184;this.h[38]=29184+this.l;this.h[55]=28928;this.h[39]=28928+this.l;this.h[56]=26368;this.h[40]=26368+this.l;this.h[57]=26112;this.h[41]=26112+this.l;this.h[48]=25856;this.h[58]=25600;this.h[42]=25600+this.l;this.h[45]=25344;this.h[61]=25344+this.l;this.h[46]=22272;this.h[62]=22272+this.l;this.h[108]=22016;this.h[76]=22016+this.l;this.h[92]=22016+this.l;this.h[111]=21760;this.h[79]=
21760+this.l;this.h[this.za]=21760+this.l;this.h[this.Aa]=21504;this.h[this.va]=21248;this.h[119]=18176;this.h[87]=18176+this.l;this.h[101]=17920;this.h[69]=17920+this.l;this.h[114]=17664;this.h[82]=17664+this.l;this.h[116]=17408;this.h[84]=17408+this.l;this.h[121]=17152;this.h[89]=17152+this.l;this.h[117]=16896;this.h[85]=16896+this.l;this.h[105]=16640;this.h[73]=16640+this.l;this.h[115]=14080;this.h[83]=14080+this.l;this.h[100]=13824;this.h[68]=13824+this.l;this.h[102]=13568;this.h[70]=13568+this.l;
this.h[103]=13312;this.h[71]=13312+this.l;this.h[104]=13056;this.h[72]=13056+this.l;this.h[106]=12800;this.h[74]=12800+this.l;this.h[107]=12544;this.h[75]=12544+this.l;this.h[91]=12544+this.l;this.h[120]=9984;this.h[88]=9984+this.l;this.h[99]=9728;this.h[67]=9728+this.l;this.h[118]=9472;this.h[86]=9472+this.l;this.h[98]=9216;this.h[66]=9216+this.l;this.h[110]=8960;this.h[78]=8960+this.l;this.h[94]=8960+this.l;this.h[109]=8704;this.h[77]=8704+this.l;this.h[93]=8704+this.l;this.h[44]=8448;this.h[60]=
8448+this.l;this.h[113]=5888;this.h[81]=5888+this.l;this.h[97]=5632;this.h[65]=5632+this.l;this.h[122]=5376;this.h[90]=5376+this.l;this.h[32]=5120;this.h[47]=4864;this.h[63]=4864+this.l;this.h[59]=4608;this.h[43]=4608+this.l;this.h[112]=4352;this.h[80]=4352+this.l;this.h[64]=4352+this.l;this.h[this.T]=1536;this.h[this.ba]=1280;this.h[this.l]=512;this.h[this.U]=256;this.h[this.ga]=0;this.reset()}v(Nb,H);g=Nb.prototype;
g.reset=function(){this.Ma(this.Ea);this.v=this.P;this.ja=0;this.B=[this.P,0,0,0,0,0,0,0];this.W=[];if(this.H)for(var a in this.H)isNaN(+a)||this.H[a]&&clearTimeout(this.H[a]);this.H=[];this.ra=this.I=0;this.ka=-1;this.ma=this.B;this.na=this.Z=0;this.N=""};
g.da=function(a,b,c){if(void 0===this.M[b])switch(b){case "keyDown":return this.M[b]=c,c.onkeydown=function(d){return function(e){return Ob(d,e,!0)}}(this),!0;case "keyPress":return this.M[b]=c,c.onkeypress=function(d){return function(e){var f=!0;e=e||window.event;e=e.which||e.keyCode;d.N="";d.v&8?d.v&=-9:f=!Pb(d,e);d.C&&P(d.C,d.C.Ba)&&d.C.u("keyPress(%#04x): %s\n",e,f?"pass":"consume");return f}}(this),!0;case "keyUp":return this.M[b]=c,c.onkeyup=function(d){return function(e){return Ob(d,e,!1)}}(this),
!0;case "break":return this.M[b]=c,c.onclick=function(d){return function(){d.fa&&d.fa.reset(!0)}}(this),!0;default:if(void 0!==this.R[b])return this.M[b]=c,c.onclick=function(d,e,f){return function(){d.D&&d.D.qa();return!Pb(d,f)}}(this,b,this.R[b]),!0}return!1};g.pa=function(a,b,c,d){this.g=a;this.oa=b;this.Ha=c-b+1;this.Ra=this.oa+this.Ha;d&&(this.D=d,yb(d,b,c,this,this.zb));this.ea()};g.Ma=function(a){this.S=a;this.X=255;600!=this.S&&(this.X=0,this.u("updated keyboard model: %d\n",this.S))};
g.sa=function(a,b){a&&!this.J.V&&(this.J.V=!0,this.fa=b,this.C=Q(b,"debugger"))};g.ea=function(){this.Y=(this.Qa=D("iOS"))||D("Android");this.C&&P(this.C,this.C.Ba)&&this.C.u("mobile keyboard support: %b (%s)\n",this.Y,window.navigator.userAgent);H.prototype.ea.call(this)};function Qb(a,b){b=b?100:250;a.D&&a.D.S&&(b/=a.D.S);return b}function Rb(a,b){!a.I||void 0!==b&&b==a.I||(a.C&&P(a.C,a.C.Ba)&&a.C.u("autoClear(%#04x)\n",a.I),clearTimeout(a.H[a.I]),Sb(a,a.I,!1,4))}
function Tb(a,b,c){a.N=b;Ub(a,c||300)}function Ub(a,b){if(0<a.N.length){var c=a.N.charCodeAt(0);10==c&&(c=13);65<=c&&90>=c&&(c+=32);a.N=a.N.substr(1);Pb(a,c)}0<a.N.length&&setTimeout(function(d){return function(){Ub(d,b)}}(a),b)}
function Ob(a,b,c){var d=!c;b=b.keyCode;c&&(a.ra=b);if(b==a.l-a.F)a.v&=-5,c&&(a.v|=4),b+=a.F,d=!1;else if(b==a.U-a.F)a.v&=-3,c&&(a.v|=2),b+=a.F,d=!1;else if(b==a.T-a.F)a.v&=-65,c&&(a.v|=64),b+=a.F,d=!1;else if(b==a.ga-a.F)c=!c,a.v&=~a.P,c&&(a.v|=a.P),b+=a.F,d=!1;else if(91==b){a.v&=-9;c&&(a.v|=8);d=!1;var e=!0}else e=9==b?d=!1:b==a.ia||b==a.ha?c?!Pb(a,b):!1:!0;d&&(a.v&=-9,a.Y||b!=a.ra||Rb(a));void 0===e&&(e=!Sb(a,b,c,2));a.C&&P(a.C,a.C.Ba)&&a.C.u("key%s(%#04x): %s\n",c?"Down":"Up",b,e?"pass":"consume");
return e}function Pb(a,b){var c=!1;b==a.aa?a.fa&&(a.fa.reset(!0),c=!0):(a.Y&&65<=b&&90>=b&&(b+=32),Rb(a,b),Sb(a,b,!0,0)&&(2==a.D.speed?Sb(a,b,!1,1):(c=!1,a.H[b]&&(clearTimeout(a.H[b]),c=!0),c=Qb(a,c),a.H[a.I=b]=setTimeout(function(d){return function(){Sb(d,b,!1,3)}}(a),c),a.C&&P(a.C,a.C.Ba)&&a.C.u("keyPressSimulate(%#04x): setTimeout()\n",b)),c=!0));a.C&&P(a.C,a.C.Ba)&&a.C.u("keyPressSimulate(%#04x): %b\n",b,c);return c}
function Sb(a,b,c,d){var e=!1;c||(a.H[b]=null,a.I==b&&(a.I=0));var f=0,h=a.h[b];void 0===h&&(1<=b&&26>=b&&(b+=64,f=a.T),h=a.h[b]);void 0!==h&&(b=h>>12,e=h>>8&15,f||(f=h&255),c?(a.B[b]|=1<<e,a.B[0]=f==a.T?a.B[0]|64:f==a.l?a.B[0]|4:f==a.U?a.B[0]|2:a.B[0]&-71):(a.B[b]&=~(1<<e),a.B[0]&=-71,a.B[0]|=a.v&70),c=0==d&&!a.W.length,a.W.push(a.B.slice()),Vb(a,c),e=!0);return e}g.ca=function(){};g.zb=function(a){this.ja=this.D.ca(a)^this.X;this.Z++;Vb(this,!1,a)};
function Vb(a,b,c){var d=Gb(a.D);b||(2==a.D.speed?b=void 0!==c&&32<=a.Z:(b=d-a.na,b=0>b||8192<=b));b&&(b=a.W.shift(),void 0!==b&&(a.ma=b),a.Z=0,a.na=d);for(b=d=0;8>b;b++)a.ja&1<<b&&(d|=a.ma[b]);d^=a.X;if(void 0!==c)a.g[c]=d;else if(c=a.oa,d!=a.ka)for(;c<a.Ra;c++)a.g[c]=d;a.ka=d}E(function(){for(var a=L("c1p","keyboard"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Nb(d);I(d,c)}});
function Wb(a,b,c,d){H.call(this,"C1PVideo",a);this.ga=a.model;this.Z=a.charCols;this.aa=a.charRows;this.ia=a.screenWidth;this.ma=a.screenHeight;this.H=a.charWidth;this.I=a.charHeight;Xb(this);this.F=b;this.T=c;this.v=d;b=["","moz","ms","webkit"];a=a.smoothing;(c=Pa("smoothing"))&&(a="true"==c);if(null!=a)for(c=0;c<b.length;c++)if(d=(d=b[c])?d+"ImageSmoothingEnabled":"imageSmoothingEnabled",void 0!==this.T[d]){this.T[d]=a;break}}v(Wb,H);g=Wb.prototype;
g.reset=function(a){this.Ma(this.ga);if(this.g)for(var b=this.R;b<this.U;b++)this.g[b]=a?Math.floor(256*Math.random()):32};g.da=function(a,b,c){switch(b){case "refresh":return this.M[b]=c,c.onclick=function(d){return function(){Yb(d);ub(d)}}(this),!0}return!1};g.pa=function(a,b,c,d){this.g=a;this.R=b;this.ha=c-b+1;this.U=this.R+this.ha;d&&(this.D=d,vb(d,56832,56832,this,this.ca),yb(d,56832,56832,this,this.Ab));this.reset(!0)};
function Xb(a,b,c,d,e){a.N=void 0!==b?b:a.Z;a.ja=void 0!==c?c:a.aa;a.l=a.N*a.ja;a.U=a.R+a.l;a.Y=void 0!==d?d:0;a.ba=void 0!==e?e:c;a.W=Math.floor(a.ia/a.N);a.X=Math.floor(a.ma/a.ba)}g.qa=function(){this.F.focus()};g.Ma=function(a){this.S=a;600==this.S?(Xb(this,this.Z,this.aa,3,25),1024==this.l&&this.D&&(this.B=this.U+this.l-1,yb(this.D,this.B,this.B,this,this.rb))):(this.u("updated video model: %d\n",this.S),Xb(this,64,32));Yb(this);ub(this)};
g.sa=function(a,b){if(a&&!this.J.V&&N(this)){if(this.J.V=!0,this.C=Q(b,"debugger"),this.h=Q(b,"keyboard"))this.h.da("canvas","keyDown",this.F),this.h.da("canvas","keyPress",this.F),this.h.da("canvas","keyUp",this.F)}else!a&&this.J.V&&(this.J.V=!1)};g.ea=function(){this.H||(this.H=Math.floor(this.v.width/16));this.I||(this.I=Math.floor(this.v.height/16));H.prototype.ea.call(this)};
g.ca=function(a,b){var c=this.D.ca(a);void 0!==b&&this.C&&W(this.C,this,a,b,this.C.Ua);this.D.g[a]=c&127|(Math.floor(Gb(this.D)/8333)&1?128:0)};g.Ab=function(a,b){void 0!==b&&this.C&&W(this.C,this,a,b,this.C.Ua)};
g.rb=function(a,b){if(void 0!==b){this.C&&W(this.C,this,a,b,this.C.Ua,!0);this.Ma(540);this.h&&this.h.Ma(542);a=this.D;b=a.N;var c=[],d=wb(b,this.B,this.B,this,this.rb);if(0<=d){c.push(b[d][0]);c.push(b[d][1]);b.splice(d,1);var e=65536,f=0;for(d=0;d<b.length;d++)e>b[d][0]&&(e=b[d][0]),f<b[d][1]&&(f=b[d][1]);c.push(e);c.push(f)}4==c.length&&(a.aa=c[2],a.ba=c[3])}};function Yb(a){a.P=Array(a.l);for(var b=0;b<=a.l;b++)a.P[b]=-1}
function ub(a){var b=0;if(a.J.V)for(;b<a.l;){var c=a.g[a.R+b];if(a.P[b]!=c){var d=a,e=b%a.N,f=Math.floor(b/a.N);if(f>=d.Y&&(f-=d.Y,f<d.ba)){var h=c*d.H;d.T.drawImage(d.v,h%d.v.width,Math.floor(h/d.v.width)*d.I,d.H,d.I,e*d.W,f*d.X,d.W,d.X)}a.P[b]=c}b++}}
E(function(){for(var a=L("c1p","video"),b=0;b<a.length;b++){var c=a[b],d=M(c),e=L("pcjs-canvas","",c);if(e&&e.length)var f=e[0];else if(f=document.createElement("canvas"))f.setAttribute("class","pcjs-canvas"),f.setAttribute("width",d.screenWidth),f.setAttribute("height",d.screenHeight),f.style.backgroundColor=d.screenColor,f.style.height="auto",c.appendChild(f);if(!f||!f.getContext){c.innerHTML="<br>Missing &lt;canvas&gt; support. Please try a newer web browser.";break}f.setAttribute("contenteditable",
"true");f.setAttribute("autocapitalize","off");f.setAttribute("autocorrect","off");f.setAttribute("spellcheck","false");0<=(x.navigator?x.navigator.userAgent:"").indexOf("MSIE")&&(f.style.height=(c.clientWidth*d.screenHeight/d.screenWidth|0)+"px",c.onresize=function(k,l,q,m){return function(){l.style.height=(k.clientWidth*m/q|0)+"px"}}(c,f,d.screenWidth,d.screenHeight));e=new Image;var h=f.getContext("2d");f=new Wb(d,f,h,e);d=d.fontROM||d.charSet;e.onload=function(k){return function(){k.ea()}}(f,
d);e.src=d;I(f,c)}});function Zb(a){H.call(this,"C1PSerialPort",a);this.J.V=!1;this.F=a.demo;this.P='10 PRINT "HELLO OSI #'+kb(this)+'"\n';this.B=$b;this.v=Pa("autoMount")||a.autoMount;if("string"==typeof this.v)try{this.v=eval("("+this.v+")")}catch(c){C(1099511627776,this.type+" auto-mount error: "+c.message+" ("+this.v+")"),this.v=null}if(a=this.v&&this.v.path){var b=this;this.F=!0;B(a,function(c,d,e){ac(b,c,d,e);b.P=d;b.v=null;b.g&&b.ea()})}this.reset(!0)}v(Zb,H);
function ac(a,b,c,d){if(c){a.I=0;a.l=c;a.N=!0;if(0<b.indexOf(".json"))try{d="";var e=eval("("+c+")").bytes;for(c=0;c<e.length;c++)d+=String.fromCharCode(e[c]);a.l=d;a.N=!1}catch(f){a.u('Error processing file "%s": %s\n',b,f.message);return}a.fa&&a.h&&a.D.J.xa?(a.u("auto-loading %s\n",b),a.F||bc(a,!0)):a.u("%s ready to load\n",b)}else a.u('Error loading file "%s" (%d)\n',b,d)}g=Zb.prototype;g.reset=function(a){if(a||this.B!=cc)this.H=-1,this.I=0,this.l="",this.F&&(this.l=this.P),this.N=!0,this.B=$b};
g.start=function(){this.h&&this.F&&("."==this.l[0]?(this.F=!1,bc(this)):(Tb(this.h," C\n\n",1E3),setTimeout(function(a){return function(){a.F=!1;bc(a)}}(this),5E3)))};
g.da=function(a,b,c){var d=this;switch(b){case "listSerial":return this.M[b]=c,!0;case "loadSerial":return this.M[b]=c,c.onclick=function(){d.M.listSerial&&B(d.M.listSerial.value,function(e,f,h){ac(d,e,f,h)})},!0;case "mountSerial":return!Oa()&&window&&"FileReader"in window?(this.M[b]=c,c.onchange=function(){var e=c.children[0];e.children[1].disabled=!e.children[0].files.length},c.onsubmit=function(e){var f=e.currentTarget[1].files[0],h=new FileReader;h.onload=function(){ac(d,f.name,h.result.toString(),
0)};h.readAsText(f);return!1}):c.parentNode.removeChild(c),!0}return!1};g.pa=function(a,b,c,d){this.g=a;this.R=b;this.T=c-b+1;this.S=this.R+this.T;if(this.D=d)vb(d,b,c,this,this.ca),yb(d,b,c,this,this.Bb);this.v||this.ea()};g.sa=function(a,b){a&&!this.J.V&&(this.J.V=!0,this.fa=b,this.h=Q(b,"keyboard"),this.C=Q(b,"debugger"))};function bc(a,b){a.l&&(a.D.qa(),"."!=a.l.charAt(0)?(a.B=dc,Tb(a.h,"NEW\nLOAD\n")):(a.B=cc,b&&a.fa.reset(!0),Tb(a.h,"ML")))}
g.ca=function(a,b){void 0!==b&&(a&1?ec(this):this.l&&!this.I&&ec(this))};g.Bb=function(a,b){void 0!==b&&this.C&&W(this.C,this,a,b,this.C.tb,!0)};function ec(a){if(void 0!==a.l){a.H=-1;if(a.I<a.l.length){var b=a.l.charCodeAt(a.I++)&255;a.N&&10==b&&(b=13);a.H=b}else a.l="",a.I=0,a.B==dc&&a.h&&Tb(a.h," \nRUN\n"),a.B=$b;for(b=a.R+0;b<a.S;b+=2)a.g[b]=0<=a.H?fc:gc;for(b=a.R+1;b<a.S;b+=2)a.g[b]=0<=a.H?a.H:0}}var gc=0,fc=1,$b=0,dc=1,cc=2;
E(function(){for(var a=L("c1p","serial"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Zb(d);I(d,c)}});function hc(a){H.call(this,"C1PDiskController",a);this.J.V=!1;this.reset(!0)}v(hc,H);g=hc.prototype;g.reset=function(a){ic(this);this.h=-1;a&&(this.l=[],this.l[0]={Ke:0,Ya:40,Fb:!0,Da:20,ua:0,Ca:-1,Na:[]})};
function ic(a){a.S={O:64,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c);b.H.O&4||X(b,0,this)}}(a)};a.v={O:255,read:function(){this.update()},update:function(b){return function(c){void 0===c?c=b.v.O:jc(b,c,b.F.O);c=(c|190)&-2;if(0<=b.h&&b.l[b.h].Na.length){var d=b.l[b.h];d.Fb&&(c&=-33);d.ua||(c&=-3);10>=--d.Da&&(0<d.Da?(c&=-129,kc(b)):(d.Da=100,0<=b.h&&(b.l[b.h].Ca=0,lc(b))))}this.O=c;b.H.O&4&&X(b,0,this)}}(a)};a.H={O:0,read:function(){},update:function(b){return function(c){void 0!==
c&&(this.O=c&-193);X(b,1,this);b.v.update();b.S.update()}}(a)};a.P={O:255,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c);b.I.O&4||X(b,2,this)}}(a)};a.F={O:255,read:function(){},update:function(b){return function(c){void 0===c?c=b.F.O:jc(b,b.v.O,c);if(0<=b.h&&b.h<b.l.length){var d=b.l[b.h];d.Na.length&&b.F.O&8&&!(c&8)&&(c&4?d.ua--:d.ua++,b.C&&P(b.C,b.C.Ja)&&b.C.u("stepping %s to track %d\n",c&4?"down":"up",d.ua),d.ua>=d.Ya&&(d.ua=d.Ya),0>d.ua&&(d.ua=0),d.Da=20,b.v.update(b.v.O|
128),kc(b))}this.O=c;b.I.O&4&&X(b,2,this)}}(a)};a.I={O:0,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c&-193);X(b,3,this);b.F.update();b.P.update()}}(a)};a.T={O:0,read:function(){},update:function(b){return function(c){void 0!==c&&(3==(c&3)&&(b.B.O=14),this.O=c);b.B.update()}}(a)};a.B={O:14,read:function(){},update:function(b){return function(c){void 0===c&&(c=b.B.O);c&=-2;0<=b.h&&0<=b.l[b.h].Ca&&(c|=1);this.O=c;X(b,16,this)}}(a)};a.R={O:0,read:function(b){return function(){lc(b)}}(a),
update:function(b){return function(c){void 0!==c&&(this.O=c);X(b,17,this)}}(a)};a.U={O:0,read:function(){},update:function(){return function(){}}(a)}}
g.da=function(a,b,c){switch(b){case "listDisk":return this.M[b]=c,!0;case "loadDisk":return this.M[b]=c,c.onclick=function(d){return function(){if(d.M.listDisk){var e=d.M.listDisk.value,f=e;".json"!=e.substr(e.length-5)&&(f="http://"+window.location.host+"/api/v1/dump?disk="+e);d.u("loading  %s...\n",Fa(e));B(f,function(h,k,l){mc(d,h,k,l)})}}}(this),!0}return!1};g.pa=function(a,b,c,d){this.g=a;this.N=b;if(this.D=d)vb(d,b,c,this,this.ca),yb(d,b,c,this,this.Cb);this.ea()};
g.sa=function(a,b){a&&!this.J.V&&(this.J.V=!0,this.C=Q(b,"debugger"))};
function mc(a,b,c,d){if(d)a.u("disk load error (%d)\n",d);else{d=[];a.u("mounting %s...\n",b);try{if(d=eval("("+c+")"),d.length)if(d[0].length){var e=d[0];if(void 0===e[0].trackNum)a.u("data error: %d\n",e[0]);else if(a.l[0]){for(c=0;c<e.length;c++){var f,h=e[c],k=h.sectors;if(void 0===(f=h.trackNum)||void 0===k)throw Error("track "+c+" missing data");f!=c&&C(549755813888,"track "+f+" out of order (expected "+c+")");d=[];var l;if(f){nc(d,h,"trackSig");oc(d,h);pc(d,h,"trackType");for(var q=0;q<k.length;q++){var m=
k[q];var p=m.sectorData;pc(d,m,"sectorSig");pc(d,m,"sectorNum");pc(d,m,"sectorPages");for(l=0;l<p.length;l++)d.push(p[l]);nc(d,m,"sectorEndSig")}}else for(m=k[0],p=m.sectorData,pc(d,h,"trackLoad",2),pc(d,m,"sectorPages"),l=0;l<p.length;l++)d.push(p[l]);e[f].qb=d;a.C&&P(a.C,a.C.Ja)&&a.C.u("track %d: %d bytes\n",f,d.length)}a.l[0].Na=e;a.u("mount of %s complete\n",b)}else a.u("no available drives\n")}else a.u("no tracks: %s\n",b);else a.u("no data: %s\n",b)}catch(n){a.u("disk data error: %s\n",n.message)}}}
function oc(a,b){b=b.trackNum;if(void 0===b)throw Error("missing bcd value: trackNum");a.push(Math.floor(b/10)<<4|b%10)}function pc(a,b,c,d){b=b[c];if(void 0===b)throw Error("missing binary value: "+c);2==d&&a.push(b>>8&255);a.push(b&255)}function nc(a,b,c){b=b[c];if(void 0===b)throw Error("missing signature: "+c);for(c=0;c<b.length;c++)a.push(b.charCodeAt(c))}
function qc(a,b,c){b&=63;16>b?b&=3:32>b&&(b&=17);switch(b){case 0:a=a.H.O&4?a.v:a.S;break;case 1:a=a.H;break;case 2:a=a.I.O&4?a.F:a.P;break;case 3:a=a.I;break;case 16:a=c?a.T:a.B;break;case 17:a=a.R;break;default:a=a.U}return a}g.ca=function(a,b){if(void 0!==b){var c=qc(this,a-this.N,!1);this.C&&W(this.C,this,a,b,this.C.Ja,!1,c.pb);c.read()}};
g.Cb=function(a,b){if(void 0!==b){var c=this.D.ca(a),d=qc(this,a-this.N,!0);if(this.C&&P(this.C,this.C.Ja|this.C.sb)&&(W(this.C,this,a,b,this.C.Ja,!0,d.pb),d.Eb))for(a=128,b=d.O^c;b&&a;)b&a&&this.C.u("  changed %s.%s to %s\n",d.pb,d.Eb[a],c&a?"1":"0"),a>>=1;d.update(c)}};function jc(a,b,c){var d=-1;void 0!==b&&void 0!==c&&(d=0,c&32||(d|=2),a.v.O&64||(d|=1));a.h!=d&&(a.h=d,a.B.update())}function kc(a){0<=a.h&&(a.l[a.h].Ca=-1,a.R.update(255),a.B.update())}
function lc(a){if(0<=a.h){var b=a.l[a.h];var c=b.Na[b.ua];void 0!==c&&(0<=b.Ca&&b.Ca<c.qb.length?(b.Da=100,b=c.qb[b.Ca++],a.R.update(b),a.B.update()):(b.Da=10,kc(a)))}}function X(a,b,c){a.D.g[b+a.N]=c.O}E(function(){for(var a=L("c1p","disk"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new hc(d);I(d,c)}});
function rc(a){H.call(this,"C1PDebugger",a);this.C=this;this.ha=-1;this.Y=0;this.Aa=null;this.wa=!1;this.N=0;this.X=[];this.Z=[];this.ba=[];this.ka=0;this.aa=[];this.T=[];this.sb=1;this.Ba=16;this.Ua=32;this.Ja=64;this.tb=128;this.ta=this.Ha=0;this.ra={port:1,kbd:16,video:32,disk:64,serial:128};this.Oa=28;this.Va=56;this.ja="ADC AND ASL BCC BCS BEQ BIT BMI BNE BPL BRK BVC BVS CLC CLD CLI CLV CMP CPX CPY DEC DEX DEY EOR INC INX INY JMP JSR LDA LDX LDY LSR NOP ORA PHA PHP PLA PLP ROL ROR RTI RTS SBC SEC SED SEI STA STX STY TAX TAY TSX TXA TXS TYA SIM .DB".split(" ");
this.Ga=["HLT","MSG"];sc(this,!0);this.I=[[10],[34,1,this.U],[this.Va,1],[],[],[34,1,this.l],[2,1,this.l],[],[36],[34,1,this.F],[2,0,this.na],[],[],[34,2,this.h],[2,2,this.h],[],[9,1,this.H],[34,1,this.W],[],[],[],[34,1,this.v],[2,1,this.v],[],[13],[34,2,this.S],[],[],[],[34,2,this.B],[2,2,this.B],[],[this.Oa,2,this.oa],[1,1,this.U],[],[],[6,1,this.l],[1,1,this.l],[39,1,this.l],[],[38],[1,1,this.F],[39,0,this.na],[],[6,2,this.h],[1,2,this.h],[39,2,this.h],[],[7,1,this.H],[1,1,this.W],[],[],[],[1,
1,this.v],[39,1,this.v],[],[44],[1,2,this.S],[],[],[],[1,2,this.B],[39,2,this.B],[],[41],[23,1,this.U],[],[],[],[23,1,this.l],[32,1,this.l],[],[35],[23,1,this.F],[32,0,this.na],[],[27,2,this.oa],[23,2,this.h],[32,2,this.h],[],[11,1,this.H],[23,1,this.W],[],[],[],[23,1,this.v],[32,1,this.v],[],[15],[23,2,this.S],[],[],[],[23,2,this.B],[32,2,this.B],[],[42],[0,1,this.U],[],[],[],[0,1,this.l],[40,1,this.l],[],[37],[0,1,this.F],[40,0,this.na],[],[27,2,this.Ea],[0,2,this.h],[40,2,this.h],[],[12,1,this.H],
[0,1,this.W],[],[],[],[0,1,this.v],[40,1,this.v],[],[46],[0,2,this.S],[],[],[],[0,2,this.B],[40,2,this.B],[],[],[47,1,this.U],[],[],[49,1,this.l],[47,1,this.l],[48,1,this.l],[],[22],[],[53],[],[49,2,this.h],[47,2,this.h],[48,2,this.h],[],[3,1,this.H],[47,1,this.W],[],[],[49,1,this.v],[47,1,this.v],[48,1,this.Fa],[],[55],[47,2,this.S],[54],[],[],[47,2,this.B],[],[],[31,1,this.F],[29,1,this.U],[30,1,this.F],[],[31,1,this.l],[29,1,this.l],[30,1,this.l],[],[51],[29,1,this.F],[50],[],[31,2,this.h],[29,
2,this.h],[30,2,this.h],[],[4,1,this.H],[29,1,this.W],[],[],[31,1,this.v],[29,1,this.v],[30,1,this.Fa],[],[16],[29,2,this.S],[52],[],[31,2,this.B],[29,2,this.B],[30,2,this.S],[],[19,1,this.F],[17,1,this.U],[],[],[19,1,this.l],[17,1,this.l],[20,1,this.l],[],[26],[17,1,this.F],[21],[],[19,2,this.h],[17,2,this.h],[20,2,this.h],[],[8,1,this.H],[17,1,this.W],[],[],[],[17,1,this.v],[20,1,this.v],[],[14],[17,2,this.S],[],[],[],[17,2,this.B],[20,2,this.B],[],[18,1,this.F],[43,1,this.U],[],[],[18,1,this.l],
[43,1,this.l],[24,1,this.l],[],[25],[43,1,this.F],[33],[],[18,2,this.h],[43,2,this.h],[24,2,this.h],[],[5,1,this.H],[43,1,this.W],[],[],[],[43,1,this.v],[24,1,this.v],[],[45],[43,2,this.S],[],[],[],[43,2,this.B],[24,2,this.B],[]]}v(rc,H);g=rc.prototype;
g.da=function(a,b,c){var d=this;switch(b){case "debugInput":return this.va=this.M[b]=c,this.va.focus(),c.onkeypress=function(e,f){return function(h){13==h.keyCode&&(b=f.value,f.value="",tc(e,b))}}(this,c),!0;case "debugEnter":return this.M[b]=c,Sa(c,function(){return d.va?(b=d.va.value,tc(d,b),!0):!1}),!0;case "step":return this.M[b]=c,Sa(c,function(e){var f=!1;mb(d,!0)||(nb(d,!0),f=d.step(e?1:0),nb(d,!1));return f}),!0}return!1};
g.pa=function(a,b,c){this.g=a;this.R=b;this.La=c-b+1;this.ma=this.R+this.La;this.ea()};g.sa=function(a,b){a&&!this.J.V&&(this.J.V=!0,this.D=Q(b,"cpu"))};g.qa=function(){this.va.focus()};
function sc(a,b){a.na=0;a.F=1;a.B=2;a.S=3;a.oa=4;a.Ea=5;a.v=6;a.Fa=7;a.U=8;a.W=9;a.h=10;a.l=11;a.H=a.oa;var c="";if(b)for(a.P="A #$nn $nnnn,X $nnnn,Y $nnnn ($nnnn) $nn,X $nn,Y ($nn,X) ($nn),Y $nnnn $nn".split(" "),b=0;b<a.P.length;b++){var d=a.P[b];c+="("+d.replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\$/g,"\\$")+"|)"}else for(a.P="A nn [nnnn+X] [nnnn+Y] nnnn [nnnn] [nn+X] [nn+Y] [[nn+X]] [[nn]+Y] [nnnn] [nn]".split(" "),
b=0;b<a.P.length;b++)d=a.P[b],c+="("+d.replace(/\[/g,"\\[").replace(/]/g,"\\]").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\+/g,"\\+")+"|)";a.yb=new RegExp(c);a.Qa=[27,a.Oa,9,7,11,12,3,4,8,5]}g.la=function(){this.D.la()};g.info=function(){};g.message=function(a){this.print(a);Fb(this.D)};function W(a,b,c,d,e,f,h){(a.ta&e)==e&&(e=a.D.ca(c),a.u("%s.%s(%#06x) @%#06x %s=%#04x\n",b.id,f?"setByte":"getByte",c,d,h||"unknown",e))}
g.ya=function(){if(!uc(this))return!1;this.D.ya();return!0};g.step=function(a){if(!uc(this))return!1;try{var b=this.D.step(a)}catch(c){b=void 0,lb(this.D,c.stack||c.message)}void 0!==b&&this.ha++;this.D.update(!0);this.update(!0);return b};g.update=function(a){this.Y=this.D.j;a||this.ia?vc(this):wc(this)};function uc(a){a.D&&N(a.D)&&!mb(a.D)?(a=a.D,a.J.error?(a.print(a.toString()+" error\n"),a=!0):a=!1,a=!a):a=!1;return a}
g.reset=function(){var a;this.aa.length||(this.aa=Array(1E3));for(a=0;a<this.aa.length;a++)this.aa[a]=-1;this.T.length||(this.T=Array(256));for(a=0;a<this.T.length;a++)this.T[a]=[a,0];this.ha&&this.update();this.ha=0};g.start=function(){this.ia||this.u("running\n")};g.stop=function(a,b){this.ia||(this.u("stopped\n"),b&&this.u("%dms (%d cycles)\n",db()-a,b));this.update();this.qa();this.ia||(this.ha=0);xc(this,this.D.j)};
g.ca=function(a){if(a>=this.R&&a<this.ma){xb(this.D,a);var b=this.g[this.R+a];b&=255}return b};function yc(a,b,c){b<a.R||b>=a.ma?a.u("invalid address: %#06x\n",b):(a.g[a.R+b]=c&255,zb(a.D,b),a.D.update())}function zc(a,b){Y(a.X,b)||a.X.push(b);return!0}function Y(a,b,c){for(var d=!1,e=0;e<a.length;e++)if(a[e]==b){c&&a.splice(e,1);d=!0;break}return d}function Ac(a,b){void 0!==b&&(xc(a,a.ga),zc(a,b)&&(a.ga=b))}function xc(a,b){void 0!==a.ga&&b==a.ga&&Y(a.X,a.ga,!0)&&(a.ga=void 0);a.ia=!1}
function Eb(a,b,c,d){for(var e=!1,f=0;f<c.length;f++)if(c[f]==b){b!=a.ga&&a.u("breakpoint hit: %#06x (%s)\n",b,d);e=!0;break}return e}
function Bc(a,b,c){var d=z(b,4),e=a.ca(b++),f=void 0===e?0:e,h=a.I[f],k=[],l=void 0===h[1]?0:h[1];do{d+=" "+z(f,2);if(!l--)break;f=a.ca(b++);if(void 0===f)break;k.push(f)}while(1);void 0===h[0]&&(h=[57,1,a.F],k.push(e));d=(d+"        ").substr(0,15);d+=a.ja[h[0]];var q=null;if(void 0!==h[2]){l=h[2];q=a.P[l];if(1==h[1]&&l==a.H){var m=q.replace,p=b;k=f=k.pop();q=m.call(q,/nnnn/,z(p+(k<<24>>24),4))}else for(;k.length;)q=q.replace(/nn/,z(f=k.pop(),2));l==a.F&&1==h[1]&&32<=f&&128>f&&(q+=" ;'"+String.fromCharCode(f)+
"'")}if(e==a.D.Va&&(f<a.Ga.length&&(q=a.Ga[f]),f==a.D.ub)){l=0;for(q='"';f=a.ca(b++);)16>l?q+=String.fromCharCode(f):16==l&&(q+="\u2026"),l++;q+='"'}q&&(d+=" "+q);c&&(d=(d+"               ").substr(0,30),d+=";"+c.toString());a.xb=b;return d}
function Z(a,b){var c=a.Y;if(void 0!==b){var d=16;"$"==b.charAt(0)?b=b.substr(1):"0x"==b.substr(0,2)?b=b.substr(2):"."==b.charAt(b.length-1)&&(d=10,b=b.substr(0,b.length-1));c=parseInt(b,d);isNaN(c)&&(a.u("invalid base-%d address: %s\n",d,b),c=void 0)}void 0!==c&&(c<a.R||c>=a.ma)&&(a.u("address out of range: %x\n",c),c=void 0);return c}
function Cc(a,b){if("?"==b)a.u("\nfrequency commands:\n"),a.u("clear\tclear all frequency counts\n");else{var c=0;if(a.T)if("clear"==b){for(b=0;b<a.T.length;b++)a.T[b]=[b,0];a.u("frequency data cleared\n");c++}else if(void 0!==b)a.u("unknown frequency command: %s\n",b),c++;else{var d=a.T.slice();d.sort(function(h,k){return k[1]-h[1]});for(b=0;b<d.length;b++){var e=d[b][0],f=d[b][1];f&&(a.u("%s (%#04x): %d times\n",a.ja[a.I[e][0]],e,f),c++)}}c||a.u("no frequency data available\n")}}
function vc(a,b,c,d){var e=Z(a,b);if(void 0!==e){void 0===d&&(d=1);b=a.ma;if(void 0!==c){b=Z(a,c);if(void 0===b||b<e)return;if(256<b-e){a.u("range too large\n");return}b++;d=-1}for(e!=a.Y&&a.u("\n");d--&&e<b;)c=Bc(a,e,mb(a,!1)||a.ia?a.ha:0),a.u("%s\n",c),a.Y=e=a.xb}}
function wc(a,b){if(b&&"?"==b[1])a.u("\nregister commands:\n"),a.u("r to display all\n"),a.u("r [target=value] to modify\n"),a.u("supported targets:\n"),a.u("A,X,Y,S,PC and flags C,Z,D,V,N\n");else{var c=!0;if(void 0!==b&&1<b.length){c=!1;var d=b[1],e=d.indexOf("=");if(0<e)b=d.substr(e+1),d=d.substr(0,e);else if(2<b.length)b=b[2];else{a.u("missing value for %s\n",b[1]);return}e=parseInt(b,16);if(isNaN(e)){a.u("invalid value: %s\n",b);return}switch(d.toUpperCase()){case "A":a.D.m=e&255;break;case "X":a.D.G=
e&255;break;case "Y":a.D.K=e&255;break;case "C":a.D.i=e?256:0;break;case "Z":a.D.s=e?0:1;break;case "D":e?Hb(a.D):Ib(a.D);break;case "V":e?(d=a.D,d.B=0,d.F=128):(d=a.D,d.B=0,d.F=0);break;case "N":a.D.o=e?128:0;break;case "S":if(256!=(e&-256)){a.u("invalid stack pointer: %s\n",b);return}a.D.L=e;break;case "PC":c=!0;a.D.j=e&65535;a.Y=a.D.j;break;default:a.u("unknown register: %s\n",d);return}a.D.update()}a.u("%s\n","A="+z(a.D.m,2)+" X="+z(a.D.G,2)+" Y="+z(a.D.K,2)+" P="+z(Cb(a.D),2)+" S="+z(a.D.L,4)+
" PC="+z(a.D.j,4));c&&vc(a,z(a.Y=a.D.j,4))}}function Dc(a,b){b=void 0===b?1:parseInt(b,10);var c=1==b?0:1;Ra(b,function(d){return function(){return nb(d,!0)&&d.step(c)}}(a),function(d){return function(){nb(d,!1)}}(a))}
function tc(a,b){b.length||(a.wa?(a.u("ended assemble @%04x\n",a.N),a.Y=a.N,a.wa=!1):a.Aa&&(b=a.Aa));if(N(a)&&!mb(a,!0)&&0<b.length){a.wa?b="a "+z(a.N,4)+" "+b:1<b.length&&1!=b.indexOf(" ")&&(b=b.charAt(0).toLowerCase()+" "+b.substr(1));var c=b.split(" ");a.Aa=c[0];switch(c[0].toLowerCase()){case "a":var d=Z(a,c[1]);if(void 0!==d)if(a.N=d,void 0===c[2])a.u("begin assemble @%#06x\n",a.N),a.wa=!0,a.D.update();else{b=c[2];var e=c[3];c=a.N;d=[];if(void 0!==b){var f;b=b.toUpperCase();"?"==b.charAt(b.length-
1)&&(e="?",b=b.substr(0,b.length-1));for(f=0;f<a.ja.length&&b!=a.ja[f];f++);f==a.ja.length&&(a.u("unknown operation: %s\n",b),f=-1);var h="",k;if(0<=f&&void 0!==e)if(h=e.toUpperCase(),"?"==h){for(e=k=0;e<a.I.length;e++)a.I[e][0]===f&&(k||a.u("supported opcodes:\n"),a.u("     %02x: %s%s\n",e,b,void 0!==a.I[e][2]?" "+a.P[a.I[e][2]]:""),k++);f=-1}else if(k=h.match(a.yb),null!==k&&k[0]==h){for(e=1;e<k.length;e++)if(k[e]==h)if(void 0===l)var l=e-1;else{a.u("too many operand matches (both %s and %s)\n",
a.P[l],a.P[e-1]);f=-1;break}l==a.oa&&0>a.Qa.indexOf(f)&&(l=a.h);l==a.Ea&&27!=f&&(l=a.h)}else a.u("unknown operand: %s\n",h),f=-1;if(0<=f){k=-1;for(e=0;e<a.I.length;e++)if(a.I[e][0]===f&&a.I[e][2]===l)if(0>k)k=e;else{a.u("too many instruction matches (both %#04x and %#04x)\n",k,e);k=-2;break}if(0<=k){if(d.push(k),void 0!==l)if(b=a.I[k][1],h=h.match(/[0-9A-F]+/),null!==h)for(h=parseInt(h[0],16),1==b&&l==a.H&&(h-=c+2,-128>h||127<h)&&(a.u("branch out of range (%d)\n",h),d=[],b=0),e=0;e<b;e++)d.push(h&
255),h>>>=8;else b&&a.u("instruction missing %d bytes\n",b)}else a.u("unknown instruction: %s %s%s\n",b,h,"")}}l=d;if(l.length){for(c=0;c<l.length;c++)yc(a,a.N+c,l[c]);a.u("%s\n",Bc(a,a.N));a.N+=l.length}}break;case "b":l=c[1];c=c[2];if(void 0===l||"?"==l)a.u("\nbreakpoint commands:\n"),a.u("bp [a]\tset exec breakpoint at [a]\n"),a.u("br [a]\tset read breakpoint at [a]\n"),a.u("bw [a]\tset write breakpoint at [a]\n"),a.u("bc [a]\tclear breakpoint at [a]\n"),a.u("bl\tlist all breakpoints\n");else if(void 0===
c&&1<l.length&&(c=l.substr(1),l=l.charAt(0)),"l"==l){l=0;d=a.X;for(c=0;c<d.length;c++)a.u("breakpoint enabled: %#06x (exec)\n",d[c]),l++;d=a.Z;for(c=0;c<d.length;c++)a.u("breakpoint enabled: %#06x (read)\n",d[c]),l++;d=a.ba;for(c=0;c<d.length;c++)a.u("breakpoint enabled: %#06x (write)\n",d[c]),l++;l||a.u("no breakpoints\n")}else void 0===c?a.u("missing breakpoint address\n"):"c"==l&&"*"==c?(a.X=[],a.Z=[],a.ba=[],a.u("all breakpoints cleared\n")):(c=Z(a,c),void 0!==c&&("p"==l?zc(a,c)?a.u("breakpoint enabled: %#06x (exec)\n",
c):a.u("breakpoint not set: %#06x\n",c):"c"==l?Y(a.X,c,!0)?a.u("breakpoint cleared: %#06x (exec)\n",c):Y(a.Z,c,!0)?a.u("breakpoint cleared: %#06x (read)\n",c):Y(a.ba,c,!0)?a.u("breakpoint cleared: %#06x (write)\n",c):a.u("breakpoint missing: %#06x\n",c):"r"==l?(Y(a.Z,c)||a.Z.push(c),a.u("breakpoint enabled: %#06x (read)\n",c)):"w"==l?(Y(a.ba,c)||a.ba.push(c),a.u("breakpoint enabled: %#06x (write)\n",c)):a.u("unknown breakpoint command: %s\n",l)));break;case "d":l=c[1];d=c[2];if("?"==l)a.u("\ndump commands:\n"),
a.u("d [a] [#]    dump # lines of memory\n");else if(l=Z(a,l),void 0!==l){c=0;void 0!==d&&("l"==d.charAt(0)&&(d=d.substr(1)),c=parseInt(d,10));c||(c=1);for(d=0;d<c;d++){h=b="";e=l;for(f=0;8>f&&l<a.ma;f++)k=a.ca(l),void 0===k&&(k=0),b+=z(k,2)+" ",h+=32<=k&&127>k?String.fromCharCode(k):".",l++;a.u("%04x %s%s\n",e,b,h)}a.Y=l}break;case "e":l=c[1];if(void 0===l)a.u("missing address\n");else if(l=Z(a,l),void 0!==l)for(d=2;d<c.length;d++)b=parseInt(c[d],16),yc(a,l++,b);break;case "f":Cc(a,c[1]);break;case "g":l=
c[1];void 0!==l&&Ac(a,Z(a,l));a.ya()||a.D.qa();break;case "h":a.la();break;case "o":if(void 0===c[1]||"?"==c[1])a.u("\noption commands:\n"),a.u("max\trun at maximum speed\n"),a.u("fast\trun faster (up to %dMhz)\n",a.D.Ka),a.u("slow\trun at normal speed (1Mhz)\n"),a.u("classic\tuse classic operand syntax\n"),a.u("modern\tuse modern operand syntax\n"),a.u("msg\tenable message categories\n");else switch(l=c[1],l){case "slow":tb(a.D,a.D.Pa);break;case "fast":tb(a.D,a.D.vb);break;case "max":tb(a.D,a.D.wb);
break;case "classic":sc(a,!0);a.u("classic syntax enabled\n");break;case "modern":sc(a,!1);a.u("modern syntax enabled\n");break;case "msg":l=0;void 0!==c[2]&&("all"==c[2]?l=255:void 0!==a.ra[c[2]]&&(l=a.ra[c[2]]),l&&("on"==c[3]?a.ta|=l:"off"==c[3]&&(a.ta&=~l)));for(d in a.ra)if(void 0===c[2]||"all"==c[2]||c[2]==d)l=a.ra[d],a.u("%s messages: %s\n",d,a.ta&l?"on":"off");break;default:a.u("unknown option: %s\n",l)}break;case "p":h=c[1];l=10;c=a.ka;d=a.aa;if(void 0!==d){b=void 0===h?a.Ra:parseInt(h,10);
void 0===b&&(b=10);b>d.length&&(a.u("note: only %d available\n",d.length),b=d.length);void 0!==h&&(a.za=0,a.u("%d instructions earlier:\n",b));h=a.za?a.za:1;c-=b;for(0>c&&(c=d.length-1);l&&c!=a.ka;){e=d[c];if(0>e)break;a.u("%s\n",Bc(a,e,h++));++c==d.length&&(c=0);l--;b--}a.Ra=b;a.za=h}10==l&&a.u("no history available\n");break;case "r":wc(a,c);break;case "s":a.ca(a.D.j)==a.D.Oa?(Ac(a,a.D.j+3),a.ia=!0,a.ya()||a.D.qa()):Dc(a);break;case "t":Dc(a,c[1]);break;case "u":vc(a,c[1],c[2],8);break;case "?":case "help":a.u("\ncommands:\n?\thelp\na [#]\tassemble\nb [#]\tbreakpoint\nd [#]\tdump memory\ne [#]\tedit memory\nf\tdump frequencies\ng [#]\trun to [#]\nh\thalt\no\toptions\np [#]\tdump history\nr\tdump/edit registers\ns\tstep over instruction\nt [#]\tstep instruction(s)\nu [#]\tunassemble\n");
a.u("note: frequency and history commands operate only when breakpoints are set\n");break;default:a.u("unknown command: %s\n",b)}}}E(function(){for(var a=L("c1p","debugger"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new rc(d);I(d,c)}});function Ec(a,b){H.call(this,"C1PComputer",a);this.g=b}v(Ec,H);Ec.prototype.reset=function(a){var b=null,c;for(c in this.g)for(var d=0;d<this.g[c].length;d++){var e=this.g[c][d];e&&e.reset&&(e.reset(),"cpu"==c&&(b=e))}b&&(b.update(),a&&b.ya())};
Ec.prototype.start=function(){for(var a in this.g)if("cpu"!=a)for(var b=0;b<this.g[a].length;b++){var c=this.g[a][b];c&&c.start&&c.start()}};Ec.prototype.stop=function(a,b){for(var c in this.g)if("cpu"!=c)for(var d=0;d<this.g[c].length;d++){var e=this.g[c][d];e&&e.stop&&e.stop(a,b)}};Ec.prototype.da=function(a,b,c){switch(b){case "reset":return this.M[b]=c,c.onclick=function(d){return function(){d.reset()}}(this),!0}return!1};function Q(a,b){return a.g[b]?a.g[b][0]:null}
function Fc(a){var b=null,c;for(c in a.g)for(var d=0;d<a.g[c].length;d++){var e=a.g[c][d];if(e){if(!N(e)){N(e,function(f){return function(){Fc(f)}}(a));return}"cpu"==c?b=e:e.sa&&e.sa(!0,a)}}a.ea();a.u(0,"%s v%s\n%s\n","C1Pjs","2.21","Copyright \u00a9 2012-2025 Jeff Parsons <Jeff@pcjs.org>");b&&b.sa(!0,a)}
E(function(){for(var a=L("c1p","computer"),b=0;b<a.length;b++){for(var c=a[b],d=M(c),e,f={},h,k=0,l=0,q=0;q<d.modules.length;q++){var m=d.modules[q];if(!q){if("cpu"!=m.type)break;k=+m.start;l=+m.end;h=Array(l+1-k);for(e=k;e<h.length;e++)h[e]=0}if(e=eb(m.refID,d.id)){var p=m.type;void 0===f[p]&&(f[p]=[]);f[p].push(e);e.pa&&void 0!==m.start&&e.pa(h,+m.start,+m.end,f.cpu[0])}else{C(1099511627776,'no component for <module refid="'+m.refID+'">');return}}if(void 0===h){C(1099511627776,'<module type="cpu"> definition must appear first in the <computer> specification');
break}if(e=fb("C1PDebugger",d.id,!1))f["debugger"]=[e],e.pa&&e.pa(h,k,l,f.cpu[0]);k=new Ec(d,f);if(l=fb("C1PPanel",d.id,!1))if(f.panel=[l],l.M.print){e=void 0;d=d.id;f=[];d&&0<(e=d.indexOf("."))&&(d=d.substr(0,e+1));q=y.components;for(e=0;e<q.length;e++)m=q[e],d&&0!=m.id.indexOf(d)||f.push(m);d=f;for(f=0;f<d.length;f++)e=d[f],e!=l&&(e.print=l.print)}I(k,c);Fc(k)}});var Gc=0;
function Hc(a,b,c,d,e,f,h,k,l){k("Loading "+a+"...");B(a,function(q,m,p){p?(m||(m="unable to load "+a+" ("+p+")"),l(q,m,null)):Ic(m,a,b,c,d,e,f,h,k,l)})}
function Ic(a,b,c,d,e,f,h,k,l,q){function m(p,n,r){if(r)q(p,r,null);else{c&&(cb(c,b,n),(r=b)&&0>r.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(r=window.location.pathname+r),f?"}"==f.slice(-1)?(f=f.slice(0,-1),1<f.length&&(f+=",")):f='{state:"'+f+'",':f="{",f+='url:"'+r+'"}',"object"==typeof resources&&(r=null),f=f.replace(/\$/g,"$$$$").replace(/'/g,"&apos;"),h&&(p=n.match(/(<machine[^>]*\sclass=)(['"])(.*?)(\2[^>]*>)/))&&(n=n.replace(p[0],p[1]+p[2]+h+p[4]),h=""),(p=n.match(/(<machine[^>]*\sdebugger=)(['"])(available)(\2[^>]*>)/))&&
(n=n.replace(p[0],p[1]+p[2]+"optional"+p[4])),n=n.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(h?' class="'+h+'"':"")+(f?" parms='"+f+"'":"")+(r?' url="'+r+'"':"")));k||(n=n.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1"+d+"$2"),n=n.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1"+e+"$2"),n=n.replace(/<xsl:variable name="APPVERSION"(\/>|>[^<]*<\/xsl:variable>)/,'<xsl:variable name="APPVERSION">2.21</xsl:variable>'));p=null;if("<"==n.charAt(0))try{k||
(n=n.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(p=new window.ActiveXObject("Microsoft.XMLDOM"),p.async=!1,p.loadXML(n)):p=(new window.DOMParser).parseFromString(n,"text/xml")}catch(J){p=null,n=J.message}else n="unrecognized XML: "+(255<n.length?n.substr(0,255)+"...":n);q(b,n,p)}}a?k?Jc(b,a,l,m):m(b,a,""):q(b,"no data",null)}
function Jc(a,b,c,d){var e;if(e=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(b)){var f=e[2];c("Loading "+f+"...");B(f,function(h,k,l){if(l||!k)d(h,b,"unable to resolve XML reference: "+e[0]+" ("+l+")");else{if(l=e[3]){var q=k.match(new RegExp("<"+e[1]+"[^>]*>"));if(q){for(var m=q[0],p,n=/( [a-z]+=)(['"])(.*?)\2/gi;p=n.exec(l);)m=0>m.toLowerCase().indexOf(p[1].toLowerCase())?m.replace(">",p[0]+">"):m.replace(new RegExp(p[1]+"(['\"])(.*?)\\1"),p[0]);q[0]!=m&&(k=k.replace(q[0],m))}else{d(h,b,"missing <"+
e[1]+"> in "+f);return}}k=k.replace(/<\?xml[^>]*>[\r\n]*/,"");b=b.replace(e[0],k);Jc(h,b,c,d)}})}else d(a,b,"")}
function Kc(a,b,c,d,e,f,h){function k(w){if(void 0===p){var u=m&&L("machine-warning","",m);p=u&&u[0]||m}p&&(p.innerHTML=Ha(w))}function l(w,u){if("string"==typeof u&&0<=u.indexOf("<!DOCTYPE html>")){var fa=u.match(/<title>(?:PCjs: |)(.*?)<\/title>/);fa&&(u=fa[1])}C(1099511627776,"%s\n",u);k("Error: "+u+(w?" ("+w+")":""));n&&q();n=!1}function q(){--Gc||G(!0)}var m,p,n=!0;Gc++;y.machines[c]={};if(!d)return f&&cb(c,"parms",f),q(),n;"true"==Pa("debugger")&&0>d.indexOf("/debugger")&&(d=d.replace("/machine.xml",
"/debugger/machine.xml"));try{if(m=document.getElementById(c)){var r,J=x.resources;if("object"==typeof J&&(r=J.css)){var V=document.head||document.getElementsByTagName("head")[0],A=document.createElement("style");A.type="text/css";A.styleSheet?A.styleSheet.cssText=r:A.appendChild(document.createTextNode(r));V.appendChild(A)}e||(e="/machines/"+b+"/xsl/components.xsl");b=b.split("/").pop();r=function(w,u,fa){fa?Hc(e||"","",a,b,"","",!1,k,function(O,U,K){if(K)if(cb(c,e||"",U),k("Processing "+d+"..."),
window.ActiveXObject||"ActiveXObject"in window)(K=fa.transformNode(K))?(m.outerHTML=K,q()):l(O,"transformNodeToObject failed");else if(document.implementation&&document.implementation.createDocument)if(U=new XSLTProcessor,U.importStylesheet(K),K=U.transformToFragment(fa,document))if(U=m.parentNode){var ya=O=0,Ya=m.getBoundingClientRect();0>Ya.bottom&&(O=window.scrollX,ya=window.scrollY);U.replaceChild(K,m);(m=document.getElementById(c))&&0>Ya.bottom&&(K=m.getBoundingClientRect(),ya=window.performance&&
window.performance.navigation.type==window.performance.navigation.TYPE_RELOAD?0:ya+Math.ceil(K.height-Ya.height),window.scrollTo(O,ya));q()}else l(O,"invalid machine element: "+c);else l(O,"transformToFragment failed");else l(O,"unable to transform XML: unsupported browser");else l(O,U)}):l(w,u)};"<"!=d.charAt(0)?Hc(d,c,a,b,f||"",h||"",!0,k,r):Ic(d,"",c,a,b,f||"",h||"",!1,k,r)}else l(d,"missing machine element: "+c)}catch(w){l(d,w.message)}return n}
function Lc(a,b,c,d,e){G(!1);return Kc("PCx86","pcx86",a,b,c,d,e)}x.embedC1P=function(a,b,c,d,e){G(!1);return Kc("C1Pjs","osi/c1p",a,b,c,void 0,e)};x.embedPC=Lc;x.embedPCx86=Lc;x.embedPCx80=function(a,b,c,d,e){G(!1);return Kc("PCx80","pcx80",a,b,c,d,e)};x.embedPDP10=function(a,b,c,d,e){G(!1);return Kc("PDPjs","dec/pdp10",a,b,c,d,e)};x.embedPDP11=function(a,b,c,d,e){G(!1);return Kc("PDPjs","dec/pdp11",a,b,c,d,e)};
x.commandMachine=function(a,b,c,d,e,f){if("script"==e){d=!1;e=y.commands;c+=".machine";if(!f)delete e[c],d=!0;else if("string"==typeof f&&!e[c]){d=!0;for(var h=c,k=f.length,l=[],q=[],m="",p=null,n=0;n<k;n++){var r=f[n];if('"'==r||"'"==r)p&&r!=p?m+=r:(p?p=null:p=r,m&&(q.push(m),m=""));else{if(!p){if("\r"==r||"\n"==r)r=";";if(" "==r||"\t"==r||";"==r){m&&(q.push(m),m="");";"==r&&q.length&&(l.push(q),q=[]);continue}}m+=r}}m&&q.push(m);q.length&&l.push(q);e[h]=l;gb(c)||(d=!1)}return d?(b&&(a.disabled=
!0),!0):!1}if(d&&(h=fb(d,c+".machine"))&&(k=h.exports)&&(k=k[e]))return k.call(h,f)?(b&&(a.disabled=!0),!0):!1;console.log("unimplemented: commandMachine('"+c+"','"+d+"','"+e+"','"+f+"')");return!1};x.enableEvents=G;x.sendEvent=F;})()

//# sourceMappingURL=c1p.js.map
