(function(){/*
 https://www.pcjs.org/machines/modules/v2/message.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/dumpapi.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/reportapi.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/embed.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/defines.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/pcfs.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/strlib.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/usrlib.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/weblib.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/component.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/defines.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/panel.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/cpu.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/rom.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/ram.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/keyboard.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/video.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/serial.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/disk.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/debugger.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/osi/c1p/modules/v2/computer.js (C) 2012-2026 Jeff Parsons
*/
var g,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function t(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}var ea;
if(typeof Object.setPrototypeOf=="function")ea=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}ea=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=ea;
function v(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Je=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function ma(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function na(a){if(!(a instanceof Array)){a=ma(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function oa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
t("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
t("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});t("String.prototype.repeat",function(a){return a?a:function(b){if(this==null)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(b<0||b>1342177279)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
t("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});t("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,h){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(la(this))}});return a});function pa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}function qa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}
t("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});var ra=typeof window!="undefined",sa=typeof window!="undefined"?{}:global,x=typeof window!="undefined"?window:global,ta=typeof document!="undefined"?document:{},y={machines:{},components:[],commands:{},files:null};x.PCjs?y=x.PCjs:x.PCjs=y;x.LOCALDISKS=!1;function ua(){this.g={};for(var a=0;a<23;a++)this.g["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
function va(){var a=oa.apply(0,arguments);if(a[0]===void 0)a=new Date(Date.now());else if(typeof a[0]==="string"){var b=a[0];b.indexOf(":")<0?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=a[1]===void 0?new Date(a[0]):new Date(Date.UTC.apply(Date,na(a)));return a}
ua.prototype.h=function(a){var b=oa.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var h=d[f+5];if(this.g[h]===void 0)c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+h;else{if(e<b.length){var k=b[e];h!="%"&&e++}else k=b[b.length-1];var l=!1,q=d[f+1],m=q.indexOf("#")>=0,p=q.indexOf("0")>=0,n=d[f+2];n=="*"?(n=k,k=e<b.length?b[e++]:b[b.length-1]):n=+n||0;var r=d[f+3];r=r?+r.substr(1):-1;var J=d[f+4],
V=null,A=0,w="",u="ACDFGHMNSTWY".indexOf(h)>=0&&typeof k!="object"?va(k):k;switch(h){case "C":c+=isNaN(u.getTime())?void 0:this.h("%#W, %#F %#D, %#Y".replaceAll("#",m?"#":""),u);continue;case "D":k=m?u.getUTCDate():u.getDate();h="d";break;case "A":case "G":case "H":k=m?u.getUTCHours():u.getHours();h=="A"?(k=k<12?"am":"pm",h="s"):(h=="G"&&(k=k?k>12?k-12:k:12),h="d");break;case "F":case "M":k=m?u.getUTCMonth():u.getMonth();h=="F"?(k=wa[k],h="s"):(k++,h="d");break;case "N":k=m?u.getUTCMinutes():u.getMinutes();
h="d";break;case "S":k=m?u.getUTCSeconds():u.getSeconds();h="d";break;case "T":c+=isNaN(u.getTime())?void 0:this.h("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",m?"#":""),u);continue;case "W":k=xa[m?u.getUTCDay():u.getDay()];h="s";break;case "Y":k=m?u.getUTCFullYear():u.getFullYear(),r>0&&(k%=Math.pow(10,r)),h="d"}switch(h){case "b":c+=k?"true":"false";break;case "d":k=Math.trunc(k),r>=0&&(p=!0,n<r&&(n=r),r=-1);case "f":k=+k;h=k+"";r>=0&&(h=k.toFixed(r));h.length<n&&(p?(k<0&&(n--,h=h.substr(1)),
h=("0".repeat(n)+h).slice(-n),k<0&&(h="-"+h)):h=(" ".repeat(n)+h).slice(-n));c+=h;break;case "j":c+=JSON.stringify(k,null,n||void 0);break;case "c":k=typeof k=="string"?k[0]:String.fromCharCode(k);case "s":if(k!=void 0)for(typeof k!="string"&&(k=k.toString()),r>=0&&(k=k.substr(0,r));k.length<n;)k=q.indexOf("-")>=0?k+" ":" "+k;c+=k;break;case "B":A=2,m&&(w="0b");case "o":A||(A=8),!w&&m&&(w="0o");case "X":V=za;case "x":h="";A||(A=16);!w&&m&&(w="0x");V||(V=Aa);typeof k=="string"&&k[0]=="-"&&(l=!0,k=
k.slice(1));k=Math.trunc(k);l&&(k=-k);k<0&&((k|0)==k?k>>>=0:Math.abs(k)<=9007199254740992&&(k+=9007199254740992));r>=0&&(p=!0,n<r&&(n=r));p&&!n&&(J=="b"?n=2:J=="h"||J=="w"?n=4:J=="l"?n=8:(n=Math.abs(k),n=n<=255?2:n<=65535?4:n<=4294967295?8:9),n+=w.length);n-=w.length;do l=16,Number.isNaN(k)||(l=k&A-1,k=Math.trunc(k/A)),p||!h||l||k?h=V[l]+h:(w&&(h=w+h,w=""),n>0&&(h=" "+h));while(--n>0||k);c+=w+h;break;case "%":c+="%";break;default:c=this.g[h]?c+this.g[h](h,q,n,r,k):c+("(unimplemented sprintf type: %"+
h+")")}}}return c+=d[f]};var xa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),wa="January February March April May June July August September October November December".split(" "),Aa="0123456789abcdef?",za="0123456789ABCDEF?";
function Ba(a){var b=null,c=a.indexOf(Ca)==0?y.files:null;if(c){a=a.slice(Ca.length+1).split("/");var d,e;for(d=0;d<a.length;d++){var f=a[d],h=!1;if(!f){b=c;break}for(e=0;e<c.files.length;e++){var k=c.files[e];if(k.name.toLowerCase()==f.toLowerCase()){if(d==a.length-1){b=k;break}if(k.files){c=k;h=!0;break}}}if(b)break;if(!h&&d<a.length-1)break}}return b}var Ca="/pcfs";y.files||(y.files={name:"",size:0,Fe:16,Ge:new Date,files:[]});function Da(){}
function z(a,b,c){b?b>9&&(b=9):(b=Math.abs(a),b=b<=255?2:b<=65535?4:b<=4294967295?8:9);c=c?"0x":"";var d=d===void 0?0:d;var e="";isNaN(a)||typeof a!="number"?a=null:(a<0&&a>-1&&(a=-1),a<0&&(a+=Math.pow(16,b)),a>=Math.pow(16,b)&&(b=Math.ceil(Math.log(a)/Math.log(16))));for(var f=d||-1;b-- >0;){f||(e=","+e,f=d);if(a==null)e="?"+e;else{var h=a%16;h+=h>=0&&h<=9?48:55;e=String.fromCharCode(h)+e;a=Math.trunc(a/16)}f--}return(c===void 0?"":c)+e}
function Ea(a){var b=a,c=a.lastIndexOf("/");c>=0&&(b=a.substr(c+1));c=b.indexOf("&");c>0&&(b=b.substr(0,c));return b}function Fa(a){var b="",c=a.lastIndexOf(".");c>=0&&(b=a.substr(c+1).toLowerCase(),b=="json5"&&(b="json"));return b}function Ga(a){return a.replace(/[&<>"'$]/g,function(b){return Ha[b]})}var Ha={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;",$:"&dollar;"},Ia=new ua,Ja=Ia.h.bind(Ia);
function B(a,b){var c=null,d=!0;c=c===void 0?"text":c;d=d===void 0?!1:d;var e=0,f=null,h=x.resources;if(typeof h=="object"&&(f=h[a]))b&&b(a,f,e);else if(d&&typeof h=="function")h(a,function(p,n){b&&b(a,p,n)});else{a=x.LOCALDISKS&&(x.location?x.location.hostname:"localhost").match(/^(.+\.local|localhost|0\.0\.0\.0|pcjs)$/)?a.replace(/^\/(diskettes|gamedisks|miscdisks|harddisks|decdisks|pcsigdisks|pcsig[0-9a-z]*-disks|private)\//,"/disks/$1/").replace(/^\/discs\/([^/]*)\//,"/disks/cdroms/$1/"):a.replace(/^\/(disks\/|)(diskettes|gamedisks|miscdisks|harddisks|decdisks|pcsigdisks|pcsig[0-9a-z]*-disks|private)\//,
"https://$2.pcjs.org/").replace(/^\/(disks\/cdroms|discs)\/([^/]*)\//,"https://$2.pcjs.org/");C(2199023255552,"getResource(%s)\n",a);if(sa.Ee&&a.indexOf("http")!=0){try{h=c=="arraybuffer"?null:"utf8",f=sa.Ee(a,h),h||(f=f.buffer,f.buffer&&(f=f.buffer))}catch(p){e=p.errno}if(f!==void 0){b&&b(a,f,e);return}}if(a.indexOf(Ca)==0&&(h=Ba(a))){f=h.data;b&&b(a,f,e);return}!a.match(/^[A-Z]:/i)&&a.indexOf("?")<0&&(a=encodeURI(a));if(x.XMLHttpRequest)var k=new x.XMLHttpRequest;else if(x.ActiveXObject)k=new x.ActiveXObject("Microsoft.XMLHTTP");
else if(x.fetch){fetch(a).then(function(p){switch(c){case "json":case "text":return p.text();case "arraybuffer":return p.arrayBuffer();default:throw Error("unsupported response type: "+c);}}).then(function(p){C(2267742732288,"getResource(%s): fetched %d bytes\n",a,p.length);b&&b(a,p,e)}).catch(function(){C(68719476736,"getResource(%s) fetch error: %d\n",a,e);b&&b(a,f,e)});return}var l=!1,q=typeof k.responseType==="string";h=function(){if(k.readyState!==4)return null;try{f=l?k.response:k.responseText}catch(n){C(68719476736,
"getResource(%s) exception: %s\n",a,n.message)}if(f!=null&&(k.status==200||!k.status&&f.length&&(x.location?x.location.protocol:"file:")=="file:"))C(2267742732288,"getResource(%s): returned %d bytes\n",a,f.length);else if(e=k.status||-1,C(2199023255552,"getResource(%s) error: %d\n",a,e),!k.status&&!Ka){var p=a.match(/(^https?:\/\/[^/]+)(.*)/);p&&(Ka=!0,La("PCjs was unable to perform a cross-origin resource request to '"+p[1]+"'.\n\nIf you're running an ad blocker, try adding '"+Ma()+"' to your whitelist (or find a smarter ad blocker)."))}b&&
b(a,f,e);return[f,e]};d&&(k.onreadystatechange=h);if(c&&typeof c=="object"){q="";for(var m in c)c.hasOwnProperty(m)&&(q&&(q+="&"),q+=m+"="+encodeURIComponent(c[m]));q=q.replace(/%20/g,"+");C(2267742732288,"getResource(%s): posted %d bytes\n",a,q.length);k.open("POST",a,d);k.setRequestHeader("Content-type","application/x-www-form-urlencoded");k.send(q)}else k.open("GET",a,d),c=="arraybuffer"&&(q?(l=!0,k.responseType=c):k.overrideMimeType("text/plain; charset=x-user-defined")),k.send();d||(k.readyState=
4,h())}}function Ma(){return x.location?x.location.protocol+"//"+x.location.host:"https://www.pcjs.org"}function D(a){if(x.navigator){var b=x.navigator?x.navigator.userAgent:"";return a=="iOS"&&(!!b.match(/(iPod|iPhone|iPad)/)||x.navigator.platform==="MacIntel"&&x.navigator.maxTouchPoints>1)||a=="MSIE"&&!!b.match(/(MSIE|Trident)/)||b.indexOf(a)>=0}return!1}function Na(){var a,b=Oa("mobile");if(b)return b=="true";if(D("Mobi")){if(!a)return!0;(b=a[0]=="!")&&(a=a.substr(1));return D(a)!=b}return!1}
function Oa(a){if(!Pa){var b,c={};if(x.location){b||(b=x.location.search.substr(1));for(var d,e=/\+/g,f=/([^&=]+)=?([^&]*)/g;d=f.exec(b);)c[decodeURIComponent(d[1].replace(e," "))]=decodeURIComponent(d[2].replace(e," "))}Pa=c}return Pa[a]||Pa[a.toLowerCase()]}function Qa(a,b,c){function d(){--a;a>=0&&(b()||(a=0));a>0?setTimeout(d,0):c()}d()}
function Ra(a,b){function c(){b(d===100)&&(e=setTimeout(c,d),d=100)}var d=0,e=null,f=!1;a.onmousedown=function(){f||e||(d=500,c())};a.ontouchstart=function(){e||(d=500,c())};a.onmouseup=a.onmouseout=function(){e&&(clearTimeout(e),e=null)};a.ontouchend=a.ontouchcancel=function(){e&&(clearTimeout(e),e=null);f=!0}}function E(a){Sa.init.push(a)}
function F(a){if((a=Sa[a])&&Ta)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){C(274877906944,"%s\n\nIf it happens again, please send the URL to support@pcjs.org. Thanks.\n","An unexpected error occurred: "+c.message)}}function G(a){!Ta&&a?(Ta=!0,Ua&&F("init"),Va&&F("show")):Ta=a}var Pa=null,Sa={init:[],show:[],exit:[]},Ua=!1,Va=!1,Ta=!0,Ka=!1;function Wa(){Ua=!0;F("init",!0)}x.addEventListener&&x.addEventListener("load",Wa);function Xa(){Va=!0;F("show",!0)}
x.addEventListener&&x.addEventListener("pageshow",Xa);var Za=D("iOS")?"pagehide":D("Opera")?"unload":"beforeunload";function $a(){F("exit",!0)}x.addEventListener&&x.addEventListener(Za,$a);
function H(a,b,c){this.type=a;b||(b={id:"",name:""});this.name=b.name;++ab;this.id=this.id=b.id||"";this.exports={};this.N=this.bindings={};a=this.id.indexOf(".");a<0?this.Ya="PCjs":this.Ya=this.id.substr(0,a);this.K={ready:!1,Ja:!1,Ta:!1,Ie:!1,W:!1,Ke:!1,error:!1};this.Xa=null;this.K.error=!1;this.ua=c||0;this.D=this.F=this.ga=null;y.components.push(this)}function bb(a,b,c){y.machines[a]&&b&&(y.machines[a][b]=c,b=="parms"&&typeof c=="string"&&(y.machines[a].config=eval("("+c+")")))}
function cb(){return Date.now()||+new Date}function C(a){var b=oa.apply(1,arguments),c=0;typeof a=="number"&&(c=a,a=b.shift());if(c>=68719476736&&c<=1099511627776){var d=!1;c==1099511627776?(d=!0,a="Error: "+a):c==549755813888?(d=!0,a="Warning: "+a):c==274877906944&&(d=!0);b=Ja.apply(Da,[a].concat(na(b))).trim();d?La(b):console.log(b)}}function La(a){x.alert&&x.alert(a);console.log(a)}
function I(a,b){b=L("c1p-control","",b.parentNode);for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,e=0;e<d.length;e++){var f=d[e];if(f.nodeType===1){var h=f.getAttribute("class");if(h)for(var k=h.split(" "),l=0;l<k.length;l++)switch(h=k[l],h){case "c1p-binding":(h=M(f))&&h.binding!==void 0?a.ea(h.type,h.binding,f,h.value):h&&h.type=="description"||C(549755813888,'Component "%s" missing binding%s\n',a.toString(),h?" for "+h.type:""),l=k.length}}}}
function db(a,b){if(a!==void 0){var c;b&&(c=b.indexOf("."))>0&&(a=b.substr(0,c+1)+a);var d=y.components;for(c=0;c<d.length;c++)if(d[c].id===a)return d[c];d.length&&b!==!1&&C(549755813888,'Component ID "%s" not found\n',a)}return null}function eb(a,b,c){c=c===void 0?null:c;if(a!==void 0){var d;b&&(b=(d=b.indexOf("."))>0?b.substr(0,d+1):"");var e=y.components;for(d=0;d<e.length;d++)if(c)c==e[d]&&(c=null);else if(!(a!=e[d].type||b&&e[d].id.indexOf(b)))return e[d]}return null}
function M(a){var b=null;if(a.getAttribute){if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(d){C(1099511627776,d.message+" ("+a+")")}}else if(b=a.config||null){a=a.id;var c=b.id;a&&c&&c.indexOf(".")<0&&(b.id=a+"."+c)}return b}
function L(a,b,c){b=b===void 0?"":b;c=c===void 0?ta:c;var d=[];b&&(a+="-"+b,b!="machine"&&(a+="-object"));if(ra)if(c.getElementsByClassName)d=c.getElementsByClassName(a);else{if(c.getElementsByTagName){b=c.getElementsByTagName("*");var e=new RegExp("(^| )"+a+"( |$)");a=0;for(c=b.length;a<c;a++)e.test(b[a].className)&&d.push(b[a])}}else for(a=Object.keys(y.machines),c=0;c<a.length;c++){e=a[c];var f=y.machines[e].config;if(f&&(f=f[b])){Array.isArray(f)||(f=[f]);f=ma(f);for(var h=f.next();!h.done;h=
f.next())d.push({id:e,config:h.value})}}return d}
function fb(a){for(var b=!0,c=y.commands[a];c&&c.length;){var d=c.splice(0,1)[0],e=d[0];C(8796093022208,d.join(" "));var f=null;gb.indexOf(e)>=0&&(f=function(){return function(){fb(a)}}());var h=hb[e];if(h)if(!f)b=h(d[1],d[2],d[3]);else{if(!h(f,d[1],d[2],d[3]))break}else{b=!1;var k=eb(d[1],a);if(k)if(h=ib[e])b=h(k,d[2],d[3]);else{var l=k.exports;if(l&&(h=l[e]))if(b=!0,!f)b=h.call(k,d[2],d[3]);else if(!h.call(k,f,d[2],d[3]))break}}if(!b){La("Script error: '"+e+"' command "+(h?" failed":" not recognized"));
break}}c&&!c.length&&delete y.commands[a];return b}g=H.prototype;g.toString=function(){return this.name?this.name:this.id||this.type};function jb(a){var b=1;a.Ya&&(a=a.Ya.match(/\d+/),a!==null&&(b=parseInt(a[0],10)));return b}
g.ea=function(a,b,c){switch(b){case "clear":return this.N[b]||(this.N[b]=c,c.onclick=function(d){return function(){d.N.print&&(d.N.print.value="")}}(this)),!0;case "print":return this.N[b]||(this.N[b]=c,c.value="",this.print=function(d,e){return function(f,h){f||(f="");if((h===void 0?0:h)==4398046511104&&f.slice(-4)=="...\n"){h=f.slice(0,-1);var k=e.value,l=k.lastIndexOf(h);k=l<0?k+(h+"\n"):k.substr(0,l)+(f.slice(0,-1)+".")+k.substr(l+h.length);k.length>8192&&(k=k.substr(k.length-4096));e.value=k}else e.value+=
f,f=e.value,f.length>8192&&(e.value=f.substr(f.length-4096));e.scrollTop=e.scrollHeight}}(this,c)),!0;default:return!1}};g.print=function(a,b){C(b===void 0?0:b,a)};function kb(a,b){a.K.error=!0;a.v(274877906944,"%s\n",b)}function N(a,b){b&&(a.K.ready?b():a.Xa=b);return a.K.ready}g.fa=function(){if(!this.K.error&&(this.K.ready=!0,this.K.ready)){var a=this.Xa;this.Xa=null;a&&a()}};function lb(a,b){a.K.Ja&&(b?a.K.Ta=!0:b===void 0&&a.print(a.toString()+" busy\n"));return a.K.Ja}
function mb(a,b){if(a.K.Ta)return a.K.Ja=!1,a.K.Ta=!1;if(a.K.error)return a.print(a.toString()+" error\n"),!1;a.K.Ja=b;return a.K.Ja}function nb(a,b){var c=b/4294967296|0;return(a&b)==(b|0)&&((a/4294967296|0)&c)==c}function P(a,b){b=b===void 0?0:b;b&1&&--b;b=b||a.ua;return!nb(b,2199023255552)&&(nb(0xff000000000-(a.D?618475290624:0),b)||a.D&&nb(a.D.ua,b))?!0:!1}
g.v=function(a){var b=oa.apply(1,arguments),c=0;typeof a=="number"&&(c=a||4398046511104,a=b.shift(),nb(c,68719476736)?a=(this.id||this.type||"log")+": "+a:nb(c,137438953472)&&(a=this.type+": "+a));P(this,c)&&(b=Ja.apply(Da,[a].concat(na(b))),this.D&&this.D.message?this.D.message(b,c):this.print(b,c))};
var gb=["hold","sleep","wait"],hb={alert:function(a){La(a);return!0},sleep:function(a,b){setTimeout(a,+b);return!1}},ib={select:function(a,b,c){var d=!1;if(a=a.bindings[b])for(b=0;b<a.options.length;b++)if(a.options[b].textContent==c){a.selectedIndex!=b&&(a.selectedIndex=b);d=!0;break}return d}},ab=0;Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});
Array.isArray||(Array.isArray=function(a){return Object.prototype.toString.call(a)==="[object Array]"});Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return e.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if(typeof this!="function")throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),e=this;c.prototype=this.prototype;b.prototype=new c;return b});
function ob(a){H.call(this,"C1PPanel",a);this.K.W=!1}v(ob,H);ob.prototype.ea=function(a,b,c,d){return this.ga&&this.ga.ea(a,b,c,d)||this.F&&this.F.ea(a,b,c,d)||this.h&&this.h.ea(a,b,c,d)||this.D&&this.D.ea(a,b,c,d)?!0:H.prototype.ea.call(this,a,b,c,d)};ob.prototype.ta=function(a,b){a&&!this.K.W&&(this.K.W=!0,this.ga=b,this.F=Q(b,"cpu"),this.h=Q(b,"keyboard"),this.D=Q(b,"debugger"),pb())};
function pb(){for(var a=!1,b=L("c1p","panel"),c=0;c<b.length;c++){var d=b[c],e=M(d),f=db(e.id,!1);f||(a=!0,f=new ob(e));I(f,d);a&&f.fa()}}E(pb);
function qb(a){H.call(this,"C1PCPU",a);rb(this);this.K.W=!1;this.K.ya=!1;var b=Oa("autoStart");this.wa=b=="true"||b=="false"?JSON.parse(b):a.autoStart;this.Qa=0;this.xb=1;this.yb=2;this.speed=this.Qa;this.pa=30;this.oa=5;this.La=8;this.sa=["Slow","Fast","Max"];this.Ha=["(1Mhz)","(up to "+this.La+"Mhz)","(unlimited)"];this.U=[];this.O=[];this.ia=65536;this.ja=0;this.ba=65536;this.ca=0;this.Pa=32;this.Wa=2;this.wb=1;this.A=[this.lc,this.Gd,this.xe,this.B,this.B,this.Id,this.$b,this.B,this.Ld,this.Fd,
this.Zb,this.B,this.B,this.Cd,this.Xb,this.B,this.kc,this.Hd,this.B,this.B,this.B,this.Jd,this.ac,this.B,this.oc,this.Ed,this.B,this.B,this.B,this.Dd,this.Yb,this.B,this.cd,this.Tb,this.B,this.B,this.fc,this.Vb,this.Rd,this.B,this.Nd,this.Sb,this.Qd,this.B,this.ec,this.Pb,this.Od,this.B,this.hc,this.Ub,this.B,this.B,this.B,this.Wb,this.Sd,this.B,this.he,this.Rb,this.B,this.B,this.B,this.Qb,this.Pd,this.B,this.Yd,this.Rc,this.B,this.B,this.B,this.Tc,this.zd,this.B,this.Kd,this.Qc,this.yd,this.B,this.bd,
this.Nc,this.wd,this.B,this.mc,this.Sc,this.B,this.B,this.B,this.Uc,this.Ad,this.B,this.rc,this.Pc,this.B,this.B,this.B,this.Oc,this.xd,this.B,this.Zd,this.eb,this.B,this.B,this.B,this.gb,this.Wd,this.B,this.Md,this.cb,this.Vd,this.B,this.ad,this.$a,this.Td,this.B,this.nc,this.fb,this.B,this.B,this.B,this.hb,this.Xd,this.B,this.je,this.bb,this.B,this.B,this.B,this.ab,this.Ud,this.B,this.B,this.ne,this.B,this.B,this.ve,this.pe,this.se,this.B,this.Mc,this.B,this.Be,this.B,this.ue,this.ke,this.re,this.B,
this.bc,this.oe,this.B,this.B,this.we,this.qe,this.te,this.B,this.De,this.me,this.Ce,this.B,this.B,this.le,this.B,this.B,this.td,this.hd,this.od,this.B,this.ud,this.kd,this.pd,this.B,this.ze,this.gd,this.ye,this.B,this.rd,this.dd,this.md,this.B,this.cc,this.jd,this.B,this.B,this.vd,this.ld,this.qd,this.B,this.sc,this.fd,this.Ae,this.B,this.sd,this.ed,this.nd,this.B,this.Fc,this.xc,this.B,this.B,this.Gc,this.zc,this.Jc,this.B,this.$c,this.wc,this.Lc,this.B,this.Ec,this.tc,this.Hc,this.B,this.jc,this.yc,
this.B,this.B,this.B,this.Ac,this.Kc,this.B,this.qc,this.vc,this.B,this.B,this.B,this.uc,this.Ic,this.B,this.Cc,this.mb,this.B,this.B,this.Dc,this.ob,this.Xc,this.B,this.Zc,this.lb,this.Bd,this.B,this.Bc,this.ib,this.Vc,this.B,this.dc,this.nb,this.B,this.B,this.B,this.pb,this.Yc,this.B,this.ie,this.kb,this.B,this.B,this.B,this.jb,this.Wc,this.B];this.Ga=[7,6,0,0,0,3,5,0,3,2,2,0,0,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,3,6,0,0,3,3,5,0,4,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,
3,2,2,0,3,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,4,2,2,0,5,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,0,6,0,0,3,3,3,0,2,0,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,0,4,0,0,2,6,2,0,3,3,3,0,2,2,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,4,4,4,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0]}v(qb,H);g=qb.prototype;
g.reset=function(a){this.K.ya&&this.ma();rb(this);this.j=this.g[65532]|this.g[65533]<<8;this.K.error=!1;this.D?this.D.reset():a&&(this.wa===!0||this.wa===null&&!this.D&&this.N.run===void 0)&&this.za()};
g.ea=function(a,b,c){a=!1;switch(b){case "run":this.N[b]=c;c.onclick=function(d){return function(){d.K.ya?d.ma():d.za()}}(this);a=!0;break;case "A":case "X":case "Y":case "S":case "PC":case "C":case "Z":case "I":case "D":case "B":case "V":case "N":case "speed":this.N[b]=c;a=!0;break;case "setSpeed":this.N[b]=c,c.onclick=function(d){return function(){sb(d,d.speed>=2?d.Qa:d.speed+1,!0)}}(this),a=!0}return a};
g.qa=function(a,b,c){this.g=a;this.S=b;this.Ma=c-b+1;this.na=this.S+this.Ma;this.S?C(1099511627776,"unsupported CPU address buffer offset ("+this.S+")"):this.fa()};g.ta=function(a,b){if(a&&!this.K.W){this.ga=b;(this.D=Q(b,"debugger"))&&this.D.init();if(a=Q(b,"video"))this.Ua=function(c){return function(){tb(c)}}(a),this.ra=function(c){return function(){c.ra()}}(a);this.K.W=!0;this.reset(!0);this.update()}};
function ub(a,b,c,d,e){vb(a.U,b,c,d,e)<0&&(a.ia>b&&(a.ia=b),a.ja<c&&(a.ja=c),a.U.push([b,c,d,e]))}function wb(a,b,c){for(var d=0;d<a.U.length;d++)b>=a.U[d][0]&&b<=a.U[d][1]&&a.U[d][3].call(a.U[d][2],b,c)}function xb(a,b,c,d,e){vb(a.O,b,c,d,e)<0&&(a.ba>b&&(a.ba=b),a.ca<c&&(a.ca=c),a.O.push([b,c,d,e]))}function yb(a,b,c){for(var d=0;d<a.O.length;d++)b>=a.O[d][0]&&b<=a.O[d][1]&&a.O[d][3].call(a.O[d][2],b,c)}
function vb(a,b,c,d,e){for(var f=0;f<a.length;f++)if(a[f][0]==b&&a[f][1]==c&&a[f][2]==d&&a[f][3]==e)return f;return-1}function sb(a,b,c){b!==void 0&&(a.speed=b,a.N.setSpeed&&(a.N.setSpeed.innerHTML=a.sa[b>=2?0:b+1]),a.v("running at %s speed %s\n",a.sa[b].toLowerCase(),a.Ha[b]),c&&a.ra());a.X=0;a.xa=cb();zb(a)}g.Ua=function(){};g.ra=function(){};function R(a,b,c,d){a.N[b]!==void 0&&(d===void 0&&(d=1),c="0000"+c.toString(16),a.N[b].innerHTML=c.slice(c.length-d).toUpperCase())}
function Ab(a){R(a,"A",a.m,2);R(a,"X",a.H,2);R(a,"Y",a.L,2);var b=Bb(a);R(a,"C",b&1?1:0);R(a,"Z",b&2?1:0);R(a,"I",b&4?1:0);R(a,"D",b&8?1:0);R(a,"B",b&16?1:0);R(a,"V",b&64?1:0);R(a,"N",b&128?1:0);R(a,"S",a.M,4);R(a,"PC",a.j,4);a.N.speed&&a.T&&(a.N.speed.innerHTML=a.T.toFixed(1)+"Mhz")}
function zb(a,b){var c=30;c<a.pa&&(c=a.pa);c<a.oa&&(c=a.oa);var d=1;b&&a.speed>a.Qa&&a.T&&(d=a.T);d>a.La&&a.speed<2&&(d=a.La);a.Ca=Math.round(1E3/30);a.ha=Math.floor(1E6/c*d);a.ka=Math.floor(1E6/30*d);a.Ba=Math.floor(1E6/a.pa*d);a.Aa=Math.floor(1E6/a.oa*d);b||(a.V=a.ka,a.Z=a.Ba,a.Y=a.Aa);a.la=0}
function Cb(a){var b=cb(),c=a.Ca;a.aa&&(c=Math.round(c*a.aa/a.ka));c-=b-a.Ia;var d=a.X;if(b-=a.xa)a.T=Math.round(d/(b*100))/10,b>=864E5&&sb(a);c<0?c=0:a.speed==1?a.T<=a.La&&(c=0):a.speed==2&&(c=0);a.la+=a.aa;return c}
g.za=function(){if(mb(this,!0)){this.K.ya||(sb(this),this.ga&&this.ga.start(),this.K.ya=!0,this.N.run&&(this.N.run.innerHTML="Halt"),this.ra());this.la>=1E6&&zb(this,!0);this.aa=0;this.Ia=cb();try{do{this.step(this.ha);var a=this.R-this.J;this.X+=a;this.aa+=a;this.R=this.J=0;this.Z-=this.ha;this.Z<=0&&(this.Z+=this.Ba,this.Ua());this.Y-=this.ha;this.Y<=0&&(this.Y+=this.Aa,Ab(this));this.V-=this.ha;if(this.V<=0){this.V+=this.ka;break}}while(this.K.ya)}catch(b){this.ma();this.update();mb(this,!1);kb(this,
b.stack||b.message);return}setTimeout(function(b){return function(){b.za()}}(this),Cb(this))}else this.update(),this.ga&&this.ga.stop(this.xa,this.X)};
g.step=function(a){var b=!0;this.h=this.l=-1;var c;if(c=a&&this.D)c=this.D,c=c.Y.length>0||c.aa.length>0||c.ca.length>0;this.R=this.J=a;do{a=this.g[this.j];var d;if(d=c){d=this.D;var e=a,f=!1;Db(d,this.j,d.Y,"exec")?f=!0:(d.ia++,d.U[e][1]++,d.ba[d.la++]=d.F.j,d.la>=d.ba.length&&(d.la=0));d=!!f}if(d){b=void 0;this.ma();break}this.j++;this.A[a].call(this);if(this.h>=0){this.h>=this.ia&&this.h<=this.ja&&wb(this,this.h,this.j);if(d=c)d=this.D,e=!1,Db(d,this.h,d.aa,"read")&&(e=!0),d=!!e;if(d){b=!1;this.ma();
break}this.h=-1}else if(this.l>=0){this.l>=this.ba&&this.l<=this.ca&&yb(this,this.l,this.j);if(d=c){d=this.D;e=this.l;f=this.g[this.l];var h=!1;(f&255)!=f&&(d.v("invalid value at %#06x: %s\n",e,f),h=!0);Db(d,e,d.ca,"write")&&(h=!0);d=!!h}if(d){b=!1;this.ma();break}this.l=-1}this.J-=this.Ga[a]}while(this.J>0);return b};function Eb(a){a.V=0;a.R-=a.J;a.J=0}g.ma=function(){lb(this,!0);this.R-=this.J;this.J=0;this.K.ya&&(this.K.ya=!1,this.N.run&&(this.N.run.innerHTML="Run"))};
g.update=function(){this.Ua();Ab(this)};function Fb(a){return a.K.ya?a.X+a.R-a.J:0}g.da=function(a){return this.g[a]};function Bb(a){var b=a.i&256?1:0;b|=a.u&255?0:2;b|=(a.C&255^a.G^a.C>>1)&128?64:0;b|=a.o&128?128:0;return a.I&60|b}function Gb(a){a.I|=8;a.A[97]=a.Lb;a.A[101]=a.Nb;a.A[105]=a.Kb;a.A[109]=a.Hb;a.A[113]=a.Mb;a.A[117]=a.Ob;a.A[121]=a.Jb;a.A[125]=a.Ib;a.A[225]=a.de;a.A[229]=a.fe;a.A[233]=a.ce;a.A[237]=a.$d;a.A[241]=a.ee;a.A[245]=a.ge;a.A[249]=a.be;a.A[253]=a.ae}
function Hb(a){a.I&=-9;a.A[97]=a.eb;a.A[101]=a.gb;a.A[105]=a.cb;a.A[109]=a.$a;a.A[113]=a.fb;a.A[117]=a.hb;a.A[121]=a.bb;a.A[125]=a.ab;a.A[225]=a.mb;a.A[229]=a.ob;a.A[233]=a.lb;a.A[237]=a.ib;a.A[241]=a.nb;a.A[245]=a.pb;a.A[249]=a.kb;a.A[253]=a.jb}function S(a,b,c){var d=a.i&256?1:0,e=(b&15)+(c&15)+d;e>=10&&(e=e+6&15|16);e+=(b&240)+(c&240);a.G=b^c;a.C=e;a.o=e&255;e>=160&&(e+=96);e>=512&&(e-=256);a.i=e;a.u=b+c+d&255;a.J--;return e&255}
function T(a,b,c){var d=a.i&256?0:1,e=(b&15)-(c&15)-d;e<0&&(e=(e-6&15)-16);e+=(b&240)-(c&240);e<0&&(e-=96);a.o=a.u=(a.i=b-c-d)&255;a.G=b^c;a.C=a.i;a.i^=256;a.J--;return e&255}function rb(a){a.m=0;a.H=0;a.L=0;a.M=256;a.I=0;a.o=0;a.u=0;a.G=0;a.C=0;a.i=0;a.j=0;a.h=-1;a.l=-1;a.T=0;a.X=a.R=a.J=0}
g.lc=function(){this.j++;this.g[this.M--]=this.j>>8;this.M|=256;this.g[this.M--]=this.j&255;this.M|=256;this.I|=16;this.I=Bb(this);this.g[this.M--]=this.I;this.M|=256;this.I&=239;this.h=65534;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.Gd=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.u=this.m|=this.g[this.h]};g.Id=function(){this.h=this.g[this.j++];this.o=this.u=this.m|=this.g[this.h]};
g.$b=function(){this.l=this.g[this.j++];this.i=this.g[this.l]<<1;this.o=this.u=this.g[this.l]=this.i&255};g.Ld=function(){this.I=Bb(this);this.g[this.M--]=this.I;this.M|=256};g.Fd=function(){this.h=this.j++;this.o=this.u=this.m|=this.g[this.h]};g.Zb=function(){this.i=this.m<<1;this.o=this.u=this.m=this.i&255};g.Cd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.m|=this.g[this.h]};
g.Xb=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.g[this.l]<<1;this.o=this.u=this.g[this.l]=this.i&255};g.kc=function(){this.j+=(this.o&128?0:(this.J--,this.g[this.j]<<24>>24))+1};g.Hd=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.o=this.u=this.m|=this.g[this.h]};g.Jd=function(){this.h=this.g[this.j++]+this.H&255;this.o=this.u=this.m|=this.g[this.h]};
g.ac=function(){this.l=this.g[this.j++]+this.H&255;this.i=this.g[this.l]<<1;this.o=this.u=this.g[this.l]=this.i&255};g.oc=function(){this.i=0};g.Ed=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.o=this.u=this.m|=this.g[this.h]};g.Dd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.o=this.u=this.m|=this.g[this.h]};g.Yb=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.i=this.g[this.l]<<1;this.o=this.u=this.g[this.l]=this.i&255};
g.cd=function(){this.h=this.j++;this.g[this.M--]=this.j>>8;this.M|=256;this.g[this.M--]=this.j&255;this.M|=256;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.Tb=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.u=this.m&=this.g[this.h]};g.fc=function(){this.h=this.g[this.j++];this.u=this.m&this.g[this.h];this.o=this.o&127|this.g[this.h]&128;this.C=0;this.G=this.g[this.h]&64?128:0};g.Vb=function(){this.h=this.g[this.j++];this.o=this.u=this.m&=this.g[this.h]};
g.Rd=function(){this.l=this.g[this.j++];this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.u=this.g[this.l]=this.i&255};g.Nd=function(){this.M=this.M+1&255|256;this.I=this.g[this.M];this.i=this.I&1?256:0;this.u=this.I&2?0:1;this.o=this.I&128;this.C=0;this.G=this.I&64?128:0};g.Sb=function(){this.h=this.j++;this.o=this.u=this.m&=this.g[this.h]};
g.Qd=function(){this.i=this.i&65280|this.m;this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.u=this.m=this.i&255};g.ec=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.u=this.m&this.g[this.h];this.o=this.o&127|this.g[this.h]&128;this.C=0;this.G=this.g[this.h]&64?128:0};g.Pb=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.m&=this.g[this.h]};
g.Od=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.u=this.g[this.l]=this.i&255};g.hc=function(){this.j+=(this.o&128?(this.J--,this.g[this.j]<<24>>24):0)+1};g.Ub=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.o=this.u=this.m&=this.g[this.h]};g.Wb=function(){this.h=this.g[this.j++]+this.H&255;this.o=this.u=this.m&=this.g[this.h]};
g.Sd=function(){this.l=this.g[this.j++]+this.H&255;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.u=this.g[this.l]=this.i&255};g.he=function(){this.i=256};g.Rb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.o=this.u=this.m&=this.g[this.h]};g.Qb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.o=this.u=this.m&=this.g[this.h]};
g.Pd=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.u=this.g[this.l]=this.i&255};g.Yd=function(){this.M=this.M+1&255|256;this.I=this.g[this.M];this.i=this.I&1?256:0;this.u=this.I&2?0:1;this.o=this.I&128;this.C=0;this.G=this.I&64?128:0;this.M=this.M+2&255|256;this.j=this.g[this.M-1|256]|this.g[this.M]<<8};
g.Rc=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.u=this.m^=this.g[this.h]};g.Tc=function(){this.h=this.g[this.j++];this.o=this.u=this.m^=this.g[this.h]};g.zd=function(){this.l=this.g[this.j++];this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.u=this.i&255};g.Kd=function(){this.g[this.M--]=this.m;this.M|=256};g.Qc=function(){this.h=this.j++;this.o=this.u=this.m^=this.g[this.h]};
g.yd=function(){this.i=this.i&65279|(this.m&1?256:0);this.m=(this.i=this.i&65280|this.m>>1)&255;this.o=this.u=this.i&255};g.bd=function(){this.h=this.j;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.Nc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.m^=this.g[this.h]};g.wd=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.u=this.i&255};
g.mc=function(){this.j+=((this.C&255^this.G^this.C>>1)&128?0:(this.J--,this.g[this.j]<<24>>24))+1};g.Sc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.o=this.u=this.m^=this.g[this.h]};g.Uc=function(){this.h=this.g[this.j++]+this.H&255;this.o=this.u=this.m^=this.g[this.h]};g.Ad=function(){this.l=this.g[this.j++]+this.H&255;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.u=this.i&255};
g.rc=function(){this.I&=251};g.Pc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.o=this.u=this.m^=this.g[this.h]};g.Oc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.o=this.u=this.m^=this.g[this.h]};g.xd=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.u=this.i&255};
g.Zd=function(){this.M=this.M+2&255|256;this.j=(this.g[this.M-1|256]|this.g[this.M]<<8)+1};g.eb=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255};g.Lb=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.m=S(this,this.m,this.g[this.h])};
g.gb=function(){this.h=this.g[this.j++];this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255};g.Nb=function(){this.h=this.g[this.j++];this.m=S(this,this.m,this.g[this.h])};g.Wd=function(){this.l=this.g[this.j++];this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.u=this.g[this.l]=this.i&255};g.Md=function(){this.M=this.M+1&255|256;this.o=this.u=this.m=this.g[this.M]};
g.cb=function(){this.h=this.j++;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255};g.Kb=function(){this.h=this.j++;this.m=S(this,this.m,this.g[this.h])};g.Vd=function(){this.i=this.i&65280|this.m;this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.u=this.m=this.i&255};g.ad=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.j=this.g[this.h]|this.g[this.h+1]<<8};
g.$a=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255};g.Hb=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.m=S(this,this.m,this.g[this.h])};g.Td=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.u=this.g[this.l]=this.i&255};
g.nc=function(){this.j+=((this.C&255^this.G^this.C>>1)&128?(this.J--,this.g[this.j]<<24>>24):0)+1};g.fb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255};g.Mb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.m=S(this,this.m,this.g[this.h])};
g.hb=function(){this.h=this.g[this.j++]+this.H&255;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255};g.Ob=function(){this.h=this.g[this.j++]+this.H&255;this.m=S(this,this.m,this.g[this.h])};g.Xd=function(){this.l=this.g[this.j++]+this.H&255;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.u=this.g[this.l]=this.i&255};g.je=function(){this.I|=4};
g.bb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255};g.Jb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.m=S(this,this.m,this.g[this.h])};g.ab=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255};
g.Ib=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.m=S(this,this.m,this.g[this.h])};g.Ud=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.u=this.g[this.l]=this.i&255};g.ne=function(){this.l=this.g[this.j++]+this.H&255;this.l=this.g[this.l]|this.g[this.l+1]<<8;this.g[this.l]=this.m};g.ve=function(){this.l=this.g[this.j++];this.g[this.l]=this.L};
g.pe=function(){this.l=this.g[this.j++];this.g[this.l]=this.m};g.se=function(){this.l=this.g[this.j++];this.g[this.l]=this.H};g.Mc=function(){this.o=this.u=this.L=this.L-1&255};g.Be=function(){this.o=this.u=this.m=this.H};g.ue=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.L};g.ke=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.m};g.re=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.H};
g.bc=function(){this.j+=(this.i&256?0:(this.J--,this.g[this.j]<<24>>24))+1};g.oe=function(){this.l=this.g[this.j++];this.l=(this.g[this.l]|this.g[this.l+1]<<8)+this.L;this.g[this.l]=this.m};g.we=function(){this.l=this.g[this.j++]+this.H&255;this.g[this.l]=this.L};g.qe=function(){this.l=this.g[this.j++]+this.H&255;this.g[this.l]=this.m};g.te=function(){this.l=this.g[this.j++]+this.L&255;this.g[this.l]=this.H};g.De=function(){this.o=this.u=this.m=this.L};
g.me=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.g[this.l]=this.m};g.Ce=function(){this.M=this.H|256};g.le=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.g[this.l]=this.m};g.td=function(){this.h=this.j++;this.o=this.u=this.L=this.g[this.h]};g.hd=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.u=this.m=this.g[this.h]};g.od=function(){this.h=this.j++;this.o=this.u=this.H=this.g[this.h]};
g.ud=function(){this.h=this.g[this.j++];this.o=this.u=this.L=this.g[this.h]};g.kd=function(){this.h=this.g[this.j++];this.o=this.u=this.m=this.g[this.h]};g.pd=function(){this.h=this.g[this.j++];this.o=this.u=this.H=this.g[this.h]};g.ze=function(){this.o=this.u=this.L=this.m};g.gd=function(){this.h=this.j++;this.o=this.u=this.m=this.g[this.h]};g.ye=function(){this.o=this.u=this.H=this.m};g.rd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.L=this.g[this.h]};
g.dd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.m=this.g[this.h]};g.md=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.H=this.g[this.h]};g.cc=function(){this.j+=(this.i&256?(this.J--,this.g[this.j]<<24>>24):0)+1};g.jd=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.o=this.u=this.m=this.g[this.h]};g.vd=function(){this.h=this.g[this.j++]+this.H&255;this.o=this.u=this.L=this.g[this.h]};
g.ld=function(){this.h=this.g[this.j++]+this.H&255;this.o=this.u=this.m=this.g[this.h]};g.qd=function(){this.h=this.g[this.j++]+this.L&255;this.o=this.u=this.H=this.g[this.h]};g.sc=function(){this.G=this.C=0};g.fd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.o=this.u=this.m=this.g[this.h]};g.Ae=function(){this.o=this.u=this.H=this.M&255};g.sd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.o=this.u=this.L=this.g[this.h]};
g.ed=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.o=this.u=this.m=this.g[this.h]};g.nd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.o=this.u=this.H=this.g[this.h]};g.Fc=function(){this.h=this.j++;this.o=this.u=this.i=this.L-this.g[this.h];this.i^=256};g.xc=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.u=this.i=this.m-this.g[this.h];this.i^=256};
g.Gc=function(){this.h=this.g[this.j++];this.o=this.u=this.i=this.L-this.g[this.h];this.i^=256};g.zc=function(){this.h=this.g[this.j++];this.o=this.u=this.i=this.m-this.g[this.h];this.i^=256};g.Jc=function(){this.l=this.g[this.j++];this.o=this.u=this.g[this.l]=this.g[this.l]-1&255};g.$c=function(){this.o=this.u=this.L=this.L+1&255};g.wc=function(){this.h=this.j++;this.o=this.u=this.i=this.m-this.g[this.h];this.i^=256};g.Lc=function(){this.o=this.u=this.H=this.H-1&255};
g.Ec=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.i=this.L-this.g[this.h];this.i^=256};g.tc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.i=this.m-this.g[this.h];this.i^=256};g.Hc=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.g[this.l]=this.g[this.l]-1&255};g.jc=function(){this.j+=(this.u&255?(this.J--,this.g[this.j]<<24>>24):0)+1};
g.yc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.o=this.u=this.i=this.m-this.g[this.h];this.i^=256};g.Ac=function(){this.h=this.g[this.j++]+this.H&255;this.o=this.u=this.i=this.m-this.g[this.h];this.i^=256};g.Kc=function(){this.l=this.g[this.j++]+this.H&255;this.o=this.u=this.g[this.l]=this.g[this.l]-1&255};g.qc=function(){Hb(this)};
g.vc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.o=this.u=this.i=this.m-this.g[this.h];this.i^=256};g.uc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.o=this.u=this.i=this.m-this.g[this.h];this.i^=256};g.Ic=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.o=this.u=this.g[this.l]=this.g[this.l]-1&255};g.Cc=function(){this.h=this.j++;this.o=this.u=this.i=this.H-this.g[this.h];this.i^=256};
g.mb=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255;this.i^=256};g.de=function(){this.h=this.g[this.j++]+this.H&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.m=T(this,this.m,this.g[this.h])};g.Dc=function(){this.h=this.g[this.j++];this.o=this.u=this.i=this.H-this.g[this.h];this.i^=256};
g.ob=function(){this.h=this.g[this.j++];this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255;this.i^=256};g.fe=function(){this.h=this.g[this.j++];this.m=T(this,this.m,this.g[this.h])};g.Xc=function(){this.l=this.g[this.j++];this.o=this.u=this.g[this.l]=this.g[this.l]+1&255};g.Zc=function(){this.o=this.u=this.H=this.H+1&255};
g.lb=function(){this.h=this.j++;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255;this.i^=256};g.ce=function(){this.h=this.j++;this.m=T(this,this.m,this.g[this.h])};g.Bd=function(){};g.Bc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.i=this.H-this.g[this.h];this.i^=256};
g.ib=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255;this.i^=256};g.$d=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.m=T(this,this.m,this.g[this.h])};g.Vc=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.u=this.g[this.l]=this.g[this.l]+1&255};g.dc=function(){this.j+=(this.u&255?0:(this.J--,this.g[this.j]<<24>>24))+1};
g.nb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255;this.i^=256};g.ee=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.L;this.m=T(this,this.m,this.g[this.h])};
g.pb=function(){this.h=this.g[this.j++]+this.H&255;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255;this.i^=256};g.ge=function(){this.h=this.g[this.j++]+this.H&255;this.m=T(this,this.m,this.g[this.h])};g.Yc=function(){this.l=this.g[this.j++]+this.H&255;this.o=this.u=this.g[this.l]=this.g[this.l]+1&255};g.ie=function(){Gb(this)};
g.kb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255;this.i^=256};g.be=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.L;this.m=T(this,this.m,this.g[this.h])};
g.jb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.G=this.m^this.g[this.h];this.C=this.i;this.o=this.u=this.m=this.i&255;this.i^=256};g.ae=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.m=T(this,this.m,this.g[this.h])};g.Wc=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.H;this.o=this.u=this.g[this.l]=this.g[this.l]+1&255};
g.xe=function(){var a=this.g[this.j++];switch(a){case 0:this.v("HALT\n");this.ma();break;case 1:a=this.j;for(var b="";a<this.g.length;){var c=this.g[a++];if(!c)break;b+=String.fromCharCode(c)}this.j=a;b=b.replace(/%A/g,z(this.m,2)).replace(/%X/g,z(this.H,2)).replace(/%Y/g,z(this.L,2));this.v("%s\n",b);Eb(this);break;default:this.j-=2,this.v("undefined opSim: %#04x at %#06x\n",a,this.j),this.ma()}};g.B=function(){var a=this.g[--this.j];this.v("undefined opcode: %#04x at %#06x\n",a,this.j);this.ma()};
E(function(){for(var a=L("c1p","cpu"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new qb(d);I(d,c)}});function Ib(a){H.call(this,"C1PROM",a);this.h=this.g=null;this.l=+a.size;if(this.A=a.file||a.image){a=this.A;var b=Fa(this.A);b!="json"&&b!="hex"&&(a=Ma()+"/api/v1/dump?file="+this.A+"&format=bytes");var c=this;B(a,function(d,e,f){Jb(c,d,e,f)})}else this.fa()}v(Ib,H);
Ib.prototype.qa=function(a,b,c,d){this.g=a;this.C=b;a=c-b+1;this.l||(this.l=a);a!=this.l?kb(this,"computer-specified ROM size ("+z(a,4,!0)+") does not match component-specified size ("+z(this.l,4,!0)+")"):(d&&(this.F=d,xb(d,b,c,this,this.G)),Kb(this))};Ib.prototype.ta=function(a,b){a&&!this.K.W&&(this.K.W=!0,this.D=Q(b,"debugger"))};Ib.prototype.G=function(a,b){b!==void 0&&(this.D&&W(this.D,this,a,b,this.D.tb,!0),a-=this.C,this.g[this.C+a]=this.h?this.h[a]:0)};
function Jb(a,b,c,d){if(d)a.v('Error loading ROM "%s" (%d)\n',b,d);else{if(c.charAt(0)=="["||c.charAt(0)=="{")try{var e=eval("("+c+")"),f=e.bytes;a.h=f?f:e}catch(h){a.v('Error processing ROM "%s": %s\n',b,h.message);return}else for(b=c.replace(/\n/gm," ").replace(/ +$/,"").split(" "),a.h=Array(b.length),c=0;c<b.length;c++)a.h[c]=parseInt(b[c],16);Kb(a)}}
function Kb(a){if(!N(a))if(!a.A)a.fa();else if(a.h&&a.g){var b=a.h.length;if(b!=a.l)kb(a,"ROM image size ("+z(b,4,!0)+") does not match component-specified size ("+z(a.l,4,!0)+")");else{for(var c=0;c<b;c++)a.g[a.C+c]=a.h[c];a.fa()}}}E(function(){for(var a=L("c1p","rom"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Ib(d);I(d,c)}});function Lb(a){H.call(this,"C1PRAM",a)}v(Lb,H);Lb.prototype.qa=function(a){this.g=a;this.fa()};
E(function(){for(var a=L("c1p","ram"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Lb(d);I(d,c)}});
function Mb(a){H.call(this,"C1PKeyboard",a);this.K.W=!1;this.Ga=a.model;this.ia=8;this.Ca=10;this.Ha=13;this.ja=27;this.Aa=this.ia;this.Ba=this.Ca;this.wa=this.Ha;this.ca=this.ja;this.G=224;this.l=16+this.G;this.U=17+this.G;this.V=18+this.G;this.ha=20+this.G;this.ba=this.G;this.xa=3;this.Ma=15;this.R=1;this.S={};this.S["break"]=this.ba;this.S.esc=this.ca;this.S["ctrl-c"]=this.xa;this.S["ctrl-o"]=this.Ma;this.h=[];this.h[49]=30464;this.h[33]=30464+this.l;this.h[50]=30208;this.h[34]=30208+this.l;this.h[51]=
29952;this.h[35]=29952+this.l;this.h[52]=29696;this.h[36]=29696+this.l;this.h[53]=29440;this.h[37]=29440+this.l;this.h[54]=29184;this.h[38]=29184+this.l;this.h[55]=28928;this.h[39]=28928+this.l;this.h[56]=26368;this.h[40]=26368+this.l;this.h[57]=26112;this.h[41]=26112+this.l;this.h[48]=25856;this.h[58]=25600;this.h[42]=25600+this.l;this.h[45]=25344;this.h[61]=25344+this.l;this.h[46]=22272;this.h[62]=22272+this.l;this.h[108]=22016;this.h[76]=22016+this.l;this.h[92]=22016+this.l;this.h[111]=21760;this.h[79]=
21760+this.l;this.h[this.Aa]=21760+this.l;this.h[this.Ba]=21504;this.h[this.wa]=21248;this.h[119]=18176;this.h[87]=18176+this.l;this.h[101]=17920;this.h[69]=17920+this.l;this.h[114]=17664;this.h[82]=17664+this.l;this.h[116]=17408;this.h[84]=17408+this.l;this.h[121]=17152;this.h[89]=17152+this.l;this.h[117]=16896;this.h[85]=16896+this.l;this.h[105]=16640;this.h[73]=16640+this.l;this.h[115]=14080;this.h[83]=14080+this.l;this.h[100]=13824;this.h[68]=13824+this.l;this.h[102]=13568;this.h[70]=13568+this.l;
this.h[103]=13312;this.h[71]=13312+this.l;this.h[104]=13056;this.h[72]=13056+this.l;this.h[106]=12800;this.h[74]=12800+this.l;this.h[107]=12544;this.h[75]=12544+this.l;this.h[91]=12544+this.l;this.h[120]=9984;this.h[88]=9984+this.l;this.h[99]=9728;this.h[67]=9728+this.l;this.h[118]=9472;this.h[86]=9472+this.l;this.h[98]=9216;this.h[66]=9216+this.l;this.h[110]=8960;this.h[78]=8960+this.l;this.h[94]=8960+this.l;this.h[109]=8704;this.h[77]=8704+this.l;this.h[93]=8704+this.l;this.h[44]=8448;this.h[60]=
8448+this.l;this.h[113]=5888;this.h[81]=5888+this.l;this.h[97]=5632;this.h[65]=5632+this.l;this.h[122]=5376;this.h[90]=5376+this.l;this.h[32]=5120;this.h[47]=4864;this.h[63]=4864+this.l;this.h[59]=4608;this.h[43]=4608+this.l;this.h[112]=4352;this.h[80]=4352+this.l;this.h[64]=4352+this.l;this.h[this.U]=1536;this.h[this.ca]=1280;this.h[this.l]=512;this.h[this.V]=256;this.h[this.ha]=0;this.reset()}v(Mb,H);g=Mb.prototype;
g.reset=function(){this.Na(this.Ga);this.A=this.R;this.ka=0;this.C=[this.R,0,0,0,0,0,0,0];this.X=[];if(this.I)for(var a in this.I)isNaN(+a)||this.I[a]&&clearTimeout(this.I[a]);this.I=[];this.sa=this.J=0;this.la=-1;this.na=this.C;this.oa=this.aa=0;this.O=""};
g.ea=function(a,b,c){if(this.N[b]===void 0)switch(b){case "keyDown":return this.N[b]=c,c.onkeydown=function(d){return function(e){return Nb(d,e,!0)}}(this),!0;case "keyPress":return this.N[b]=c,c.onkeypress=function(d){return function(e){var f=!0;e=e||window.event;e=e.which||e.keyCode;d.O="";d.A&8?d.A&=-9:f=!Ob(d,e);d.D&&P(d.D,d.D.Da)&&d.D.v("keyPress(%#04x): %s\n",e,f?"pass":"consume");return f}}(this),!0;case "keyUp":return this.N[b]=c,c.onkeyup=function(d){return function(e){return Nb(d,e,!1)}}(this),
!0;case "break":return this.N[b]=c,c.onclick=function(d){return function(){d.ga&&d.ga.reset(!0)}}(this),!0;default:if(this.S[b]!==void 0)return this.N[b]=c,c.onclick=function(d,e,f){return function(){d.F&&d.F.ra();return!Ob(d,f)}}(this,b,this.S[b]),!0}return!1};g.qa=function(a,b,c,d){this.g=a;this.pa=b;this.Ia=c-b+1;this.Sa=this.pa+this.Ia;d&&(this.F=d,xb(d,b,c,this,this.Ab));this.fa()};g.Na=function(a){this.T=a;this.Y=255;this.T!=600&&(this.Y=0,this.v("updated keyboard model: %d\n",this.T))};
g.ta=function(a,b){a&&!this.K.W&&(this.K.W=!0,this.ga=b,this.D=Q(b,"debugger"))};g.fa=function(){this.Z=(this.Ra=D("iOS"))||D("Android");this.D&&P(this.D,this.D.Da)&&this.D.v("mobile keyboard support: %b (%s)\n",this.Z,window.navigator.userAgent);H.prototype.fa.call(this)};function Pb(a,b){b=b?100:250;a.F&&a.F.T&&(b/=a.F.T);return b}function Qb(a,b){!a.J||b!==void 0&&b==a.J||(a.D&&P(a.D,a.D.Da)&&a.D.v("autoClear(%#04x)\n",a.J),clearTimeout(a.I[a.J]),Rb(a,a.J,!1,4))}
function Sb(a,b,c){a.O=b;Tb(a,c||300)}function Tb(a,b){if(a.O.length>0){var c=a.O.charCodeAt(0);c==10&&(c=13);c>=65&&c<=90&&(c+=32);a.O=a.O.substr(1);Ob(a,c)}a.O.length>0&&setTimeout(function(d){return function(){Tb(d,b)}}(a),b)}
function Nb(a,b,c){var d=!c;b=b.keyCode;c&&(a.sa=b);if(b==a.l-a.G)a.A&=-5,c&&(a.A|=4),b+=a.G,d=!1;else if(b==a.V-a.G)a.A&=-3,c&&(a.A|=2),b+=a.G,d=!1;else if(b==a.U-a.G)a.A&=-65,c&&(a.A|=64),b+=a.G,d=!1;else if(b==a.ha-a.G)c=!c,a.A&=~a.R,c&&(a.A|=a.R),b+=a.G,d=!1;else if(b==91){a.A&=-9;c&&(a.A|=8);d=!1;var e=!0}else e=b==9?d=!1:b==a.ja||b==a.ia?c?!Ob(a,b):!1:!0;d&&(a.A&=-9,a.Z||b!=a.sa||Qb(a));e===void 0&&(e=!Rb(a,b,c,2));a.D&&P(a.D,a.D.Da)&&a.D.v("key%s(%#04x): %s\n",c?"Down":"Up",b,e?"pass":"consume");
return e}function Ob(a,b){var c=!1;b==a.ba?a.ga&&(a.ga.reset(!0),c=!0):(a.Z&&b>=65&&b<=90&&(b+=32),Qb(a,b),Rb(a,b,!0,0)&&(a.F.speed==2?Rb(a,b,!1,1):(c=!1,a.I[b]&&(clearTimeout(a.I[b]),c=!0),c=Pb(a,c),a.I[a.J=b]=setTimeout(function(d){return function(){Rb(d,b,!1,3)}}(a),c),a.D&&P(a.D,a.D.Da)&&a.D.v("keyPressSimulate(%#04x): setTimeout()\n",b)),c=!0));a.D&&P(a.D,a.D.Da)&&a.D.v("keyPressSimulate(%#04x): %b\n",b,c);return c}
function Rb(a,b,c,d){var e=!1;c||(a.I[b]=null,a.J==b&&(a.J=0));var f=0,h=a.h[b];h===void 0&&(b>=1&&b<=26&&(b+=64,f=a.U),h=a.h[b]);h!==void 0&&(b=h>>12,e=h>>8&15,f||(f=h&255),c?(a.C[b]|=1<<e,a.C[0]=f==a.U?a.C[0]|64:f==a.l?a.C[0]|4:f==a.V?a.C[0]|2:a.C[0]&-71):(a.C[b]&=~(1<<e),a.C[0]&=-71,a.C[0]|=a.A&70),c=d==0&&!a.X.length,a.X.push(a.C.slice()),Ub(a,c),e=!0);return e}g.da=function(){};g.Ab=function(a){this.ka=this.F.da(a)^this.Y;this.aa++;Ub(this,!1,a)};
function Ub(a,b,c){var d=Fb(a.F);b||(a.F.speed==2?b=c!==void 0&&a.aa>=32:(b=d-a.oa,b=b<0||b>=8192));b&&(b=a.X.shift(),b!==void 0&&(a.na=b),a.aa=0,a.oa=d);for(b=d=0;b<8;b++)a.ka&1<<b&&(d|=a.na[b]);d^=a.Y;if(c!==void 0)a.g[c]=d;else if(c=a.pa,d!=a.la)for(;c<a.Sa;c++)a.g[c]=d;a.la=d}E(function(){for(var a=L("c1p","keyboard"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Mb(d);I(d,c)}});
function Vb(a,b,c,d){H.call(this,"C1PVideo",a);this.ha=a.model;this.aa=a.charCols;this.ba=a.charRows;this.ja=a.screenWidth;this.na=a.screenHeight;this.I=a.charWidth;this.J=a.charHeight;Wb(this);this.G=b;this.U=c;this.A=d;b=["","moz","ms","webkit"];a=a.smoothing;(c=Oa("smoothing"))&&(a=c=="true");if(a!=null)for(c=0;c<b.length;c++)if(d=(d=b[c])?d+"ImageSmoothingEnabled":"imageSmoothingEnabled",this.U[d]!==void 0){this.U[d]=a;break}}v(Vb,H);g=Vb.prototype;
g.reset=function(a){this.Na(this.ha);if(this.g)for(var b=this.S;b<this.V;b++)this.g[b]=a?Math.floor(Math.random()*256):32};g.ea=function(a,b,c){switch(b){case "refresh":return this.N[b]=c,c.onclick=function(d){return function(){Xb(d);tb(d)}}(this),!0}return!1};g.qa=function(a,b,c,d){this.g=a;this.S=b;this.ia=c-b+1;this.V=this.S+this.ia;d&&(this.F=d,ub(d,56832,56832,this,this.da),xb(d,56832,56832,this,this.Bb));this.reset(!0)};
function Wb(a,b,c,d,e){a.O=b!==void 0?b:a.aa;a.ka=c!==void 0?c:a.ba;a.l=a.O*a.ka;a.V=a.S+a.l;a.Z=d!==void 0?d:0;a.ca=e!==void 0?e:c;a.X=Math.floor(a.ja/a.O);a.Y=Math.floor(a.na/a.ca)}g.ra=function(){this.G.focus()};g.Na=function(a){this.T=a;this.T==600?(Wb(this,this.aa,this.ba,3,25),this.l==1024&&this.F&&(this.C=this.V+this.l-1,xb(this.F,this.C,this.C,this,this.sb))):(this.v("updated video model: %d\n",this.T),Wb(this,64,32));Xb(this);tb(this)};
g.ta=function(a,b){if(a&&!this.K.W&&N(this)){if(this.K.W=!0,this.D=Q(b,"debugger"),this.h=Q(b,"keyboard"))this.h.ea("canvas","keyDown",this.G),this.h.ea("canvas","keyPress",this.G),this.h.ea("canvas","keyUp",this.G)}else!a&&this.K.W&&(this.K.W=!1)};g.fa=function(){this.I||(this.I=Math.floor(this.A.width/16));this.J||(this.J=Math.floor(this.A.height/16));H.prototype.fa.call(this)};
g.da=function(a,b){var c=this.F.da(a);b!==void 0&&this.D&&W(this.D,this,a,b,this.D.Va);this.F.g[a]=c&127|(Math.floor(Fb(this.F)/8333)&1?128:0)};g.Bb=function(a,b){b!==void 0&&this.D&&W(this.D,this,a,b,this.D.Va)};
g.sb=function(a,b){if(b!==void 0){this.D&&W(this.D,this,a,b,this.D.Va,!0);this.Na(540);this.h&&this.h.Na(542);a=this.F;b=a.O;var c=[],d=vb(b,this.C,this.C,this,this.sb);if(d>=0){c.push(b[d][0]);c.push(b[d][1]);b.splice(d,1);var e=65536,f=0;for(d=0;d<b.length;d++)e>b[d][0]&&(e=b[d][0]),f<b[d][1]&&(f=b[d][1]);c.push(e);c.push(f)}c.length==4&&(a.ba=c[2],a.ca=c[3])}};function Xb(a){a.R=Array(a.l);for(var b=0;b<=a.l;b++)a.R[b]=-1}
function tb(a){var b=0;if(a.K.W)for(;b<a.l;){var c=a.g[a.S+b];if(a.R[b]!=c){var d=a,e=b%a.O,f=Math.floor(b/a.O);if(f>=d.Z&&(f-=d.Z,f<d.ca)){var h=c*d.I;d.U.drawImage(d.A,h%d.A.width,Math.floor(h/d.A.width)*d.J,d.I,d.J,e*d.X,f*d.Y,d.X,d.Y)}a.R[b]=c}b++}}
E(function(){for(var a=L("c1p","video"),b=0;b<a.length;b++){var c=a[b],d=M(c),e=L("pcjs-canvas","",c);if(e&&e.length)var f=e[0];else if(f=document.createElement("canvas"))f.setAttribute("class","pcjs-canvas"),f.setAttribute("width",d.screenWidth),f.setAttribute("height",d.screenHeight),f.style.backgroundColor=d.screenColor,f.style.height="auto",c.appendChild(f);if(!f||!f.getContext){c.innerHTML="<br>Missing &lt;canvas&gt; support. Please try a newer web browser.";break}f.setAttribute("contenteditable",
"true");f.setAttribute("autocapitalize","off");f.setAttribute("autocorrect","off");f.setAttribute("spellcheck","false");(x.navigator?x.navigator.userAgent:"").indexOf("MSIE")>=0&&(f.style.height=(c.clientWidth*d.screenHeight/d.screenWidth|0)+"px",c.onresize=function(k,l,q,m){return function(){l.style.height=(k.clientWidth*m/q|0)+"px"}}(c,f,d.screenWidth,d.screenHeight));e=new Image;var h=f.getContext("2d");f=new Vb(d,f,h,e);d=d.fontROM||d.charSet;e.onload=function(k){return function(){k.fa()}}(f,
d);e.src=d;I(f,c)}});function Yb(a){H.call(this,"C1PSerialPort",a);this.K.W=!1;this.G=a.demo;this.R='10 PRINT "HELLO OSI #'+jb(this)+'"\n';this.C=Zb;this.A=Oa("autoMount")||a.autoMount;if(typeof this.A=="string")try{this.A=eval("("+this.A+")")}catch(c){C(1099511627776,this.type+" auto-mount error: "+c.message+" ("+this.A+")"),this.A=null}if(a=this.A&&this.A.path){var b=this;this.G=!0;B(a,function(c,d,e){$b(b,c,d,e);b.R=d;b.A=null;b.g&&b.fa()})}this.reset(!0)}v(Yb,H);
function $b(a,b,c,d){if(c){a.J=0;a.l=c;a.O=!0;if(b.indexOf(".json")>0)try{d="";var e=eval("("+c+")").bytes;for(c=0;c<e.length;c++)d+=String.fromCharCode(e[c]);a.l=d;a.O=!1}catch(f){a.v('Error processing file "%s": %s\n',b,f.message);return}a.ga&&a.h&&a.F.K.ya?(a.v("auto-loading %s\n",b),a.G||ac(a,!0)):a.v("%s ready to load\n",b)}else a.v('Error loading file "%s" (%d)\n',b,d)}g=Yb.prototype;g.reset=function(a){if(a||this.C!=bc)this.I=-1,this.J=0,this.l="",this.G&&(this.l=this.R),this.O=!0,this.C=Zb};
g.start=function(){this.h&&this.G&&(this.l[0]=="."?(this.G=!1,ac(this)):(Sb(this.h," C\n\n",1E3),setTimeout(function(a){return function(){a.G=!1;ac(a)}}(this),5E3)))};
g.ea=function(a,b,c){var d=this;switch(b){case "listSerial":return this.N[b]=c,!0;case "loadSerial":return this.N[b]=c,c.onclick=function(){d.N.listSerial&&B(d.N.listSerial.value,function(e,f,h){$b(d,e,f,h)})},!0;case "mountSerial":return!Na()&&window&&"FileReader"in window?(this.N[b]=c,c.onchange=function(){var e=c.children[0];e.children[1].disabled=!e.children[0].files.length},c.onsubmit=function(e){var f=e.currentTarget[1].files[0],h=new FileReader;h.onload=function(){$b(d,f.name,h.result.toString(),
0)};h.readAsText(f);return!1}):c.parentNode.removeChild(c),!0}return!1};g.qa=function(a,b,c,d){this.g=a;this.S=b;this.U=c-b+1;this.T=this.S+this.U;if(this.F=d)ub(d,b,c,this,this.da),xb(d,b,c,this,this.Cb);this.A||this.fa()};g.ta=function(a,b){a&&!this.K.W&&(this.K.W=!0,this.ga=b,this.h=Q(b,"keyboard"),this.D=Q(b,"debugger"))};function ac(a,b){a.l&&(a.F.ra(),a.l.charAt(0)!="."?(a.C=cc,Sb(a.h,"NEW\nLOAD\n")):(a.C=bc,b&&a.ga.reset(!0),Sb(a.h,"ML")))}
g.da=function(a,b){b!==void 0&&(a&1?dc(this):this.l&&!this.J&&dc(this))};g.Cb=function(a,b){b!==void 0&&this.D&&W(this.D,this,a,b,this.D.ub,!0)};function dc(a){if(a.l!==void 0){a.I=-1;if(a.J<a.l.length){var b=a.l.charCodeAt(a.J++)&255;a.O&&b==10&&(b=13);a.I=b}else a.l="",a.J=0,a.C==cc&&a.h&&Sb(a.h," \nRUN\n"),a.C=Zb;for(b=a.S+0;b<a.T;b+=2)a.g[b]=a.I>=0?ec:fc;for(b=a.S+1;b<a.T;b+=2)a.g[b]=a.I>=0?a.I:0}}var fc=0,ec=1,Zb=0,cc=1,bc=2;
E(function(){for(var a=L("c1p","serial"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Yb(d);I(d,c)}});function hc(a){H.call(this,"C1PDiskController",a);this.K.W=!1;this.reset(!0)}v(hc,H);g=hc.prototype;g.reset=function(a){ic(this);this.h=-1;a&&(this.l=[],this.l[0]={He:0,Za:40,Gb:!0,Fa:20,va:0,Ea:-1,Oa:[]})};
function ic(a){a.T={P:64,read:function(){},update:function(b){return function(c){c!==void 0&&(this.P=c);b.I.P&4||X(b,0,this)}}(a)};a.A={P:255,read:function(){this.update()},update:function(b){return function(c){c===void 0?c=b.A.P:jc(b,c,b.G.P);c=(c|190)&-2;if(b.h>=0&&b.l[b.h].Oa.length){var d=b.l[b.h];d.Gb&&(c&=-33);d.va||(c&=-3);--d.Fa<=10&&(d.Fa>0?(c&=-129,kc(b)):(d.Fa=100,b.h>=0&&(b.l[b.h].Ea=0,lc(b))))}this.P=c;b.I.P&4&&X(b,0,this)}}(a)};a.I={P:0,read:function(){},update:function(b){return function(c){c!==
void 0&&(this.P=c&-193);X(b,1,this);b.A.update();b.T.update()}}(a)};a.R={P:255,read:function(){},update:function(b){return function(c){c!==void 0&&(this.P=c);b.J.P&4||X(b,2,this)}}(a)};a.G={P:255,read:function(){},update:function(b){return function(c){c===void 0?c=b.G.P:jc(b,b.A.P,c);if(b.h>=0&&b.h<b.l.length){var d=b.l[b.h];d.Oa.length&&b.G.P&8&&!(c&8)&&(c&4?d.va--:d.va++,b.D&&P(b.D,b.D.Ka)&&b.D.v("stepping %s to track %d\n",c&4?"down":"up",d.va),d.va>=d.Za&&(d.va=d.Za),d.va<0&&(d.va=0),d.Fa=20,
b.A.update(b.A.P|128),kc(b))}this.P=c;b.J.P&4&&X(b,2,this)}}(a)};a.J={P:0,read:function(){},update:function(b){return function(c){c!==void 0&&(this.P=c&-193);X(b,3,this);b.G.update();b.R.update()}}(a)};a.U={P:0,read:function(){},update:function(b){return function(c){c!==void 0&&((c&3)==3&&(b.C.P=14),this.P=c);b.C.update()}}(a)};a.C={P:14,read:function(){},update:function(b){return function(c){c===void 0&&(c=b.C.P);c&=-2;b.h>=0&&b.l[b.h].Ea>=0&&(c|=1);this.P=c;X(b,16,this)}}(a)};a.S={P:0,read:function(b){return function(){lc(b)}}(a),
update:function(b){return function(c){c!==void 0&&(this.P=c);X(b,17,this)}}(a)};a.V={P:0,read:function(){},update:function(){return function(){}}(a)}}
g.ea=function(a,b,c){switch(b){case "listDisk":return this.N[b]=c,!0;case "loadDisk":return this.N[b]=c,c.onclick=function(d){return function(){if(d.N.listDisk){var e=d.N.listDisk.value,f=e;e.substr(e.length-5)!=".json"&&(f="http://"+window.location.host+"/api/v1/dump?disk="+e);d.v("loading  %s...\n",Ea(e));B(f,function(h,k,l){mc(d,h,k,l)})}}}(this),!0}return!1};g.qa=function(a,b,c,d){this.g=a;this.O=b;if(this.F=d)ub(d,b,c,this,this.da),xb(d,b,c,this,this.Db);this.fa()};
g.ta=function(a,b){a&&!this.K.W&&(this.K.W=!0,this.D=Q(b,"debugger"))};
function mc(a,b,c,d){if(d)a.v("disk load error (%d)\n",d);else{d=[];a.v("mounting %s...\n",b);try{if(d=eval("("+c+")"),d.length)if(d[0].length){var e=d[0];if(e[0].trackNum===void 0)a.v("data error: %d\n",e[0]);else if(a.l[0]){for(c=0;c<e.length;c++){var f,h=e[c],k=h.sectors;if((f=h.trackNum)===void 0||k===void 0)throw Error("track "+c+" missing data");f!=c&&C(549755813888,"track "+f+" out of order (expected "+c+")");d=[];var l;if(f){nc(d,h,"trackSig");oc(d,h);pc(d,h,"trackType");for(var q=0;q<k.length;q++){var m=
k[q];var p=m.sectorData;pc(d,m,"sectorSig");pc(d,m,"sectorNum");pc(d,m,"sectorPages");for(l=0;l<p.length;l++)d.push(p[l]);nc(d,m,"sectorEndSig")}}else for(m=k[0],p=m.sectorData,pc(d,h,"trackLoad",2),pc(d,m,"sectorPages"),l=0;l<p.length;l++)d.push(p[l]);e[f].rb=d;a.D&&P(a.D,a.D.Ka)&&a.D.v("track %d: %d bytes\n",f,d.length)}a.l[0].Oa=e;a.v("mount of %s complete\n",b)}else a.v("no available drives\n")}else a.v("no tracks: %s\n",b);else a.v("no data: %s\n",b)}catch(n){a.v("disk data error: %s\n",n.message)}}}
function oc(a,b){b=b.trackNum;if(b===void 0)throw Error("missing bcd value: trackNum");a.push(Math.floor(b/10)<<4|b%10)}function pc(a,b,c,d){b=b[c];if(b===void 0)throw Error("missing binary value: "+c);d==2&&a.push(b>>8&255);a.push(b&255)}function nc(a,b,c){b=b[c];if(b===void 0)throw Error("missing signature: "+c);for(c=0;c<b.length;c++)a.push(b.charCodeAt(c))}
function qc(a,b,c){b&=63;b<16?b&=3:b<32&&(b&=17);switch(b){case 0:a=a.I.P&4?a.A:a.T;break;case 1:a=a.I;break;case 2:a=a.J.P&4?a.G:a.R;break;case 3:a=a.J;break;case 16:a=c?a.U:a.C;break;case 17:a=a.S;break;default:a=a.V}return a}g.da=function(a,b){if(b!==void 0){var c=qc(this,a-this.O,!1);this.D&&W(this.D,this,a,b,this.D.Ka,!1,c.qb);c.read()}};
g.Db=function(a,b){if(b!==void 0){var c=this.F.da(a),d=qc(this,a-this.O,!0);if(this.D&&P(this.D,this.D.Ka|this.D.tb)&&(W(this.D,this,a,b,this.D.Ka,!0,d.qb),d.Fb))for(a=128,b=d.P^c;b&&a;)b&a&&this.D.v("  changed %s.%s to %s\n",d.qb,d.Fb[a],c&a?"1":"0"),a>>=1;d.update(c)}};function jc(a,b,c){var d=-1;b!==void 0&&c!==void 0&&(d=0,c&32||(d|=2),a.A.P&64||(d|=1));a.h!=d&&(a.h=d,a.C.update())}function kc(a){a.h>=0&&(a.l[a.h].Ea=-1,a.S.update(255),a.C.update())}
function lc(a){if(a.h>=0){var b=a.l[a.h];var c=b.Oa[b.va];c!==void 0&&(b.Ea>=0&&b.Ea<c.rb.length?(b.Fa=100,b=c.rb[b.Ea++],a.S.update(b),a.C.update()):(b.Fa=10,kc(a)))}}function X(a,b,c){a.F.g[b+a.O]=c.P}E(function(){for(var a=L("c1p","disk"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new hc(d);I(d,c)}});
function rc(a){H.call(this,"C1PDebugger",a);this.D=this;this.ia=-1;this.Z=0;this.Ba=null;this.xa=!1;this.O=0;this.Y=[];this.aa=[];this.ca=[];this.la=0;this.ba=[];this.U=[];this.tb=1;this.Da=16;this.Va=32;this.Ka=64;this.ub=128;this.ua=this.Ia=0;this.sa={port:1,kbd:16,video:32,disk:64,serial:128};this.Pa=28;this.Wa=56;this.ka="ADC AND ASL BCC BCS BEQ BIT BMI BNE BPL BRK BVC BVS CLC CLD CLI CLV CMP CPX CPY DEC DEX DEY EOR INC INX INY JMP JSR LDA LDX LDY LSR NOP ORA PHA PHP PLA PLP ROL ROR RTI RTS SBC SEC SED SEI STA STX STY TAX TAY TSX TXA TXS TYA SIM .DB".split(" ");
this.Ca=["HLT","MSG"];sc(this,!0);this.J=[[10],[34,1,this.V],[this.Wa,1],[],[],[34,1,this.l],[2,1,this.l],[],[36],[34,1,this.G],[2,0,this.oa],[],[],[34,2,this.h],[2,2,this.h],[],[9,1,this.I],[34,1,this.X],[],[],[],[34,1,this.A],[2,1,this.A],[],[13],[34,2,this.T],[],[],[],[34,2,this.C],[2,2,this.C],[],[this.Pa,2,this.pa],[1,1,this.V],[],[],[6,1,this.l],[1,1,this.l],[39,1,this.l],[],[38],[1,1,this.G],[39,0,this.oa],[],[6,2,this.h],[1,2,this.h],[39,2,this.h],[],[7,1,this.I],[1,1,this.X],[],[],[],[1,
1,this.A],[39,1,this.A],[],[44],[1,2,this.T],[],[],[],[1,2,this.C],[39,2,this.C],[],[41],[23,1,this.V],[],[],[],[23,1,this.l],[32,1,this.l],[],[35],[23,1,this.G],[32,0,this.oa],[],[27,2,this.pa],[23,2,this.h],[32,2,this.h],[],[11,1,this.I],[23,1,this.X],[],[],[],[23,1,this.A],[32,1,this.A],[],[15],[23,2,this.T],[],[],[],[23,2,this.C],[32,2,this.C],[],[42],[0,1,this.V],[],[],[],[0,1,this.l],[40,1,this.l],[],[37],[0,1,this.G],[40,0,this.oa],[],[27,2,this.Ga],[0,2,this.h],[40,2,this.h],[],[12,1,this.I],
[0,1,this.X],[],[],[],[0,1,this.A],[40,1,this.A],[],[46],[0,2,this.T],[],[],[],[0,2,this.C],[40,2,this.C],[],[],[47,1,this.V],[],[],[49,1,this.l],[47,1,this.l],[48,1,this.l],[],[22],[],[53],[],[49,2,this.h],[47,2,this.h],[48,2,this.h],[],[3,1,this.I],[47,1,this.X],[],[],[49,1,this.A],[47,1,this.A],[48,1,this.Ha],[],[55],[47,2,this.T],[54],[],[],[47,2,this.C],[],[],[31,1,this.G],[29,1,this.V],[30,1,this.G],[],[31,1,this.l],[29,1,this.l],[30,1,this.l],[],[51],[29,1,this.G],[50],[],[31,2,this.h],[29,
2,this.h],[30,2,this.h],[],[4,1,this.I],[29,1,this.X],[],[],[31,1,this.A],[29,1,this.A],[30,1,this.Ha],[],[16],[29,2,this.T],[52],[],[31,2,this.C],[29,2,this.C],[30,2,this.T],[],[19,1,this.G],[17,1,this.V],[],[],[19,1,this.l],[17,1,this.l],[20,1,this.l],[],[26],[17,1,this.G],[21],[],[19,2,this.h],[17,2,this.h],[20,2,this.h],[],[8,1,this.I],[17,1,this.X],[],[],[],[17,1,this.A],[20,1,this.A],[],[14],[17,2,this.T],[],[],[],[17,2,this.C],[20,2,this.C],[],[18,1,this.G],[43,1,this.V],[],[],[18,1,this.l],
[43,1,this.l],[24,1,this.l],[],[25],[43,1,this.G],[33],[],[18,2,this.h],[43,2,this.h],[24,2,this.h],[],[5,1,this.I],[43,1,this.X],[],[],[],[43,1,this.A],[24,1,this.A],[],[45],[43,2,this.T],[],[],[],[43,2,this.C],[24,2,this.C],[]]}v(rc,H);g=rc.prototype;
g.ea=function(a,b,c){var d=this;switch(b){case "debugInput":return this.wa=this.N[b]=c,this.wa.focus(),c.onkeypress=function(e,f){return function(h){h.keyCode==13&&(b=f.value,f.value="",tc(e,b))}}(this,c),!0;case "debugEnter":return this.N[b]=c,Ra(c,function(){return d.wa?(b=d.wa.value,tc(d,b),!0):!1}),!0;case "step":return this.N[b]=c,Ra(c,function(e){var f=!1;lb(d,!0)||(mb(d,!0),f=d.step(e?1:0),mb(d,!1));return f}),!0}return!1};
g.qa=function(a,b,c){this.g=a;this.S=b;this.Ma=c-b+1;this.na=this.S+this.Ma;this.fa()};g.ta=function(a,b){a&&!this.K.W&&(this.K.W=!0,this.F=Q(b,"cpu"))};g.ra=function(){this.wa.focus()};
function sc(a,b){a.oa=0;a.G=1;a.C=2;a.T=3;a.pa=4;a.Ga=5;a.A=6;a.Ha=7;a.V=8;a.X=9;a.h=10;a.l=11;a.I=a.pa;var c="";if(b)for(a.R="A #$nn $nnnn,X $nnnn,Y $nnnn ($nnnn) $nn,X $nn,Y ($nn,X) ($nn),Y $nnnn $nn".split(" "),b=0;b<a.R.length;b++){var d=a.R[b];c+="("+d.replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\$/g,"\\$")+"|)"}else for(a.R="A nn [nnnn+X] [nnnn+Y] nnnn [nnnn] [nn+X] [nn+Y] [[nn+X]] [[nn]+Y] [nnnn] [nn]".split(" "),
b=0;b<a.R.length;b++)d=a.R[b],c+="("+d.replace(/\[/g,"\\[").replace(/]/g,"\\]").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\+/g,"\\+")+"|)";a.Eb=new RegExp(c);a.Ra=[27,a.Pa,9,7,11,12,3,4,8,5]}g.ma=function(){this.F.ma()};g.info=function(){};g.message=function(a){this.print(a);Eb(this.F)};function W(a,b,c,d,e,f,h){(a.ua&e)==e&&(e=a.F.da(c),a.v("%s.%s(%#06x) @%#06x %s=%#04x\n",b.id,f?"setByte":"getByte",c,d,h||"unknown",e))}g.init=function(){this.v("Type ? for list of debugger commands\n\n")};
g.za=function(){if(!uc(this))return!1;this.F.za();return!0};g.step=function(a){if(!uc(this))return!1;try{var b=this.F.step(a)}catch(c){b=void 0,kb(this.F,c.stack||c.message)}b!==void 0&&this.ia++;this.F.update(!0);this.update(!0);return b};g.update=function(a){this.Z=this.F.j;a||this.ja?vc(this):wc(this)};function uc(a){a.F&&N(a.F)&&!lb(a.F)?(a=a.F,a.K.error?(a.print(a.toString()+" error\n"),a=!0):a=!1,a=!a):a=!1;return a}
g.reset=function(){var a;this.ba.length||(this.ba=Array(1E3));for(a=0;a<this.ba.length;a++)this.ba[a]=-1;this.U.length||(this.U=Array(256));for(a=0;a<this.U.length;a++)this.U[a]=[a,0];this.ia&&this.update();this.ia=0};g.start=function(){this.ja||this.v("running\n")};g.stop=function(a,b){this.ja||(this.v("stopped\n"),b&&this.v("%dms (%d cycles)\n",cb()-a,b));this.update();this.ra();this.ja||(this.ia=0);xc(this,this.F.j)};
g.da=function(a){if(a>=this.S&&a<this.na){wb(this.F,a);var b=this.g[this.S+a];b&=255}return b};function yc(a,b,c){b<a.S||b>=a.na?a.v("invalid address: %#06x\n",b):(a.g[a.S+b]=c&255,yb(a.F,b),a.F.update())}function zc(a,b){Y(a.Y,b)||a.Y.push(b);return!0}function Y(a,b,c){for(var d=!1,e=0;e<a.length;e++)if(a[e]==b){c&&a.splice(e,1);d=!0;break}return d}function Ac(a,b){b!==void 0&&(xc(a,a.ha),zc(a,b)&&(a.ha=b))}function xc(a,b){a.ha!==void 0&&b==a.ha&&Y(a.Y,a.ha,!0)&&(a.ha=void 0);a.ja=!1}
function Db(a,b,c,d){for(var e=!1,f=0;f<c.length;f++)if(c[f]==b){b!=a.ha&&a.v("breakpoint hit: %#06x (%s)\n",b,d);e=!0;break}return e}
function Bc(a,b,c){var d=z(b,4),e=a.da(b++),f=e===void 0?0:e,h=a.J[f],k=[],l=h[1]===void 0?0:h[1];do{d+=" "+z(f,2);if(!l--)break;f=a.da(b++);if(f===void 0)break;k.push(f)}while(1);h[0]===void 0&&(h=[57,1,a.G],k.push(e));d=(d+"        ").substr(0,15);d+=a.ka[h[0]];var q=null;if(h[2]!==void 0){l=h[2];q=a.R[l];if(h[1]==1&&l==a.I){var m=q.replace,p=b;k=f=k.pop();q=m.call(q,/nnnn/,z(p+(k<<24>>24),4))}else for(;k.length;)q=q.replace(/nn/,z(f=k.pop(),2));l==a.G&&h[1]==1&&f>=32&&f<128&&(q+=" ;'"+String.fromCharCode(f)+
"'")}if(e==a.F.Wa&&(f<a.Ca.length&&(q=a.Ca[f]),f==a.F.wb)){l=0;for(q='"';f=a.da(b++);)l<16?q+=String.fromCharCode(f):l==16&&(q+="\u2026"),l++;q+='"'}q&&(d+=" "+q);c&&(d=(d+"               ").substr(0,30),d+=";"+c.toString());a.zb=b;return d}
function Z(a,b){var c=a.Z;if(b!==void 0){var d=16;b.charAt(0)=="$"?b=b.substr(1):b.substr(0,2)=="0x"?b=b.substr(2):b.charAt(b.length-1)=="."&&(d=10,b=b.substr(0,b.length-1));c=parseInt(b,d);isNaN(c)&&(a.v("invalid base-%d address: %s\n",d,b),c=void 0)}c!==void 0&&(c<a.S||c>=a.na)&&(a.v("address out of range: %x\n",c),c=void 0);return c}
function Cc(a,b){if(b=="?")a.v("\nfrequency commands:\n"),a.v("clear\tclear all frequency counts\n");else{var c=0;if(a.U)if(b=="clear"){for(b=0;b<a.U.length;b++)a.U[b]=[b,0];a.v("frequency data cleared\n");c++}else if(b!==void 0)a.v("unknown frequency command: %s\n",b),c++;else{var d=a.U.slice();d.sort(function(h,k){return k[1]-h[1]});for(b=0;b<d.length;b++){var e=d[b][0],f=d[b][1];f&&(a.v("%s (%#04x): %d times\n",a.ka[a.J[e][0]],e,f),c++)}}c||a.v("no frequency data available\n")}}
function vc(a,b,c,d){var e=Z(a,b);if(e!==void 0){d===void 0&&(d=1);b=a.na;if(c!==void 0){b=Z(a,c);if(b===void 0||b<e)return;if(b-e>256){a.v("range too large\n");return}b++;d=-1}for(e!=a.Z&&a.v("\n");d--&&e<b;)c=Bc(a,e,lb(a,!1)||a.ja?a.ia:0),a.v("%s\n",c),a.Z=e=a.zb}}
function wc(a,b){if(b&&b[1]=="?")a.v("\nregister commands:\n"),a.v("r to display all\n"),a.v("r [target=value] to modify\n"),a.v("supported targets:\n"),a.v("A,X,Y,S,PC and flags C,Z,D,V,N\n");else{var c=!0;if(b!==void 0&&b.length>1){c=!1;var d=b[1],e=d.indexOf("=");if(e>0)b=d.substr(e+1),d=d.substr(0,e);else if(b.length>2)b=b[2];else{a.v("missing value for %s\n",b[1]);return}e=parseInt(b,16);if(isNaN(e)){a.v("invalid value: %s\n",b);return}switch(d.toUpperCase()){case "A":a.F.m=e&255;break;case "X":a.F.H=
e&255;break;case "Y":a.F.L=e&255;break;case "C":a.F.i=e?256:0;break;case "Z":a.F.u=e?0:1;break;case "D":e?Gb(a.F):Hb(a.F);break;case "V":e?(d=a.F,d.C=0,d.G=128):(d=a.F,d.C=0,d.G=0);break;case "N":a.F.o=e?128:0;break;case "S":if((e&-256)!=256){a.v("invalid stack pointer: %s\n",b);return}a.F.M=e;break;case "PC":c=!0;a.F.j=e&65535;a.Z=a.F.j;break;default:a.v("unknown register: %s\n",d);return}a.F.update()}a.v("%s\n","A="+z(a.F.m,2)+" X="+z(a.F.H,2)+" Y="+z(a.F.L,2)+" P="+z(Bb(a.F),2)+" S="+z(a.F.M,4)+
" PC="+z(a.F.j,4));c&&vc(a,z(a.Z=a.F.j,4))}}function Dc(a,b){b=b===void 0?1:parseInt(b,10);var c=b==1?0:1;Qa(b,function(d){return function(){return mb(d,!0)&&d.step(c)}}(a),function(d){return function(){mb(d,!1)}}(a))}
function tc(a,b){b.length||(a.xa?(a.v("ended assemble @%04x\n",a.O),a.Z=a.O,a.xa=!1):a.Ba&&(b=a.Ba));if(N(a)&&!lb(a,!0)&&b.length>0){a.xa?b="a "+z(a.O,4)+" "+b:b.length>1&&b.indexOf(" ")!=1&&(b=b.charAt(0).toLowerCase()+" "+b.substr(1));var c=b.split(" ");a.Ba=c[0];switch(c[0].toLowerCase()){case "a":var d=Z(a,c[1]);if(d!==void 0)if(a.O=d,c[2]===void 0)a.v("begin assemble @%#06x\n",a.O),a.xa=!0,a.F.update();else{b=c[2];var e=c[3];c=a.O;d=[];if(b!==void 0){var f;b=b.toUpperCase();b.charAt(b.length-
1)=="?"&&(e="?",b=b.substr(0,b.length-1));for(f=0;f<a.ka.length&&b!=a.ka[f];f++);f==a.ka.length&&(a.v("unknown operation: %s\n",b),f=-1);var h="",k;if(f>=0&&e!==void 0)if(h=e.toUpperCase(),h=="?"){for(e=k=0;e<a.J.length;e++)a.J[e][0]===f&&(k||a.v("supported opcodes:\n"),a.v("     %02x: %s%s\n",e,b,a.J[e][2]!==void 0?" "+a.R[a.J[e][2]]:""),k++);f=-1}else if(k=h.match(a.Eb),k!==null&&k[0]==h){for(e=1;e<k.length;e++)if(k[e]==h)if(l===void 0)var l=e-1;else{a.v("too many operand matches (both %s and %s)\n",
a.R[l],a.R[e-1]);f=-1;break}l==a.pa&&a.Ra.indexOf(f)<0&&(l=a.h);l==a.Ga&&f!=27&&(l=a.h)}else a.v("unknown operand: %s\n",h),f=-1;if(f>=0){k=-1;for(e=0;e<a.J.length;e++)if(a.J[e][0]===f&&a.J[e][2]===l)if(k<0)k=e;else{a.v("too many instruction matches (both %#04x and %#04x)\n",k,e);k=-2;break}if(k>=0){if(d.push(k),l!==void 0)if(b=a.J[k][1],h=h.match(/[0-9A-F]+/),h!==null)for(h=parseInt(h[0],16),b==1&&l==a.I&&(h-=c+2,h<-128||h>127)&&(a.v("branch out of range (%d)\n",h),d=[],b=0),e=0;e<b;e++)d.push(h&
255),h>>>=8;else b&&a.v("instruction missing %d bytes\n",b)}else a.v("unknown instruction: %s %s%s\n",b,h,"")}}l=d;if(l.length){for(c=0;c<l.length;c++)yc(a,a.O+c,l[c]);a.v("%s\n",Bc(a,a.O));a.O+=l.length}}break;case "b":l=c[1];c=c[2];if(l===void 0||l=="?")a.v("\nbreakpoint commands:\n"),a.v("bp [a]\tset exec breakpoint at [a]\n"),a.v("br [a]\tset read breakpoint at [a]\n"),a.v("bw [a]\tset write breakpoint at [a]\n"),a.v("bc [a]\tclear breakpoint at [a]\n"),a.v("bl\tlist all breakpoints\n");else if(c===
void 0&&l.length>1&&(c=l.substr(1),l=l.charAt(0)),l=="l"){l=0;d=a.Y;for(c=0;c<d.length;c++)a.v("breakpoint enabled: %#06x (exec)\n",d[c]),l++;d=a.aa;for(c=0;c<d.length;c++)a.v("breakpoint enabled: %#06x (read)\n",d[c]),l++;d=a.ca;for(c=0;c<d.length;c++)a.v("breakpoint enabled: %#06x (write)\n",d[c]),l++;l||a.v("no breakpoints\n")}else c===void 0?a.v("missing breakpoint address\n"):l=="c"&&c=="*"?(a.Y=[],a.aa=[],a.ca=[],a.v("all breakpoints cleared\n")):(c=Z(a,c),c!==void 0&&(l=="p"?zc(a,c)?a.v("breakpoint enabled: %#06x (exec)\n",
c):a.v("breakpoint not set: %#06x\n",c):l=="c"?Y(a.Y,c,!0)?a.v("breakpoint cleared: %#06x (exec)\n",c):Y(a.aa,c,!0)?a.v("breakpoint cleared: %#06x (read)\n",c):Y(a.ca,c,!0)?a.v("breakpoint cleared: %#06x (write)\n",c):a.v("breakpoint missing: %#06x\n",c):l=="r"?(Y(a.aa,c)||a.aa.push(c),a.v("breakpoint enabled: %#06x (read)\n",c)):l=="w"?(Y(a.ca,c)||a.ca.push(c),a.v("breakpoint enabled: %#06x (write)\n",c)):a.v("unknown breakpoint command: %s\n",l)));break;case "d":l=c[1];d=c[2];if(l=="?")a.v("\ndump commands:\n"),
a.v("d [a] [#]    dump # lines of memory\n");else if(l=Z(a,l),l!==void 0){c=0;d!==void 0&&(d.charAt(0)=="l"&&(d=d.substr(1)),c=parseInt(d,10));c||(c=1);for(d=0;d<c;d++){h=b="";e=l;for(f=0;f<8&&l<a.na;f++)k=a.da(l),k===void 0&&(k=0),b+=z(k,2)+" ",h+=k>=32&&k<127?String.fromCharCode(k):".",l++;a.v("%04x %s%s\n",e,b,h)}a.Z=l}break;case "e":l=c[1];if(l===void 0)a.v("missing address\n");else if(l=Z(a,l),l!==void 0)for(d=2;d<c.length;d++)b=parseInt(c[d],16),yc(a,l++,b);break;case "f":Cc(a,c[1]);break;case "g":l=
c[1];l!==void 0&&Ac(a,Z(a,l));a.za()||a.F.ra();break;case "h":a.ma();break;case "o":if(c[1]===void 0||c[1]=="?")a.v("\noption commands:\n"),a.v("max\trun at maximum speed\n"),a.v("fast\trun faster (up to %dMhz)\n",a.F.La),a.v("slow\trun at normal speed (1Mhz)\n"),a.v("classic\tuse classic operand syntax\n"),a.v("modern\tuse modern operand syntax\n"),a.v("msg\tenable message categories\n");else switch(l=c[1],l){case "slow":sb(a.F,a.F.Qa);break;case "fast":sb(a.F,a.F.xb);break;case "max":sb(a.F,a.F.yb);
break;case "classic":sc(a,!0);a.v("classic syntax enabled\n");break;case "modern":sc(a,!1);a.v("modern syntax enabled\n");break;case "msg":l=0;c[2]!==void 0&&(c[2]=="all"?l=255:a.sa[c[2]]!==void 0&&(l=a.sa[c[2]]),l&&(c[3]=="on"?a.ua|=l:c[3]=="off"&&(a.ua&=~l)));for(d in a.sa)if(c[2]===void 0||c[2]=="all"||c[2]==d)l=a.sa[d],a.v("%s messages: %s\n",d,a.ua&l?"on":"off");break;default:a.v("unknown option: %s\n",l)}break;case "p":h=c[1];l=10;c=a.la;d=a.ba;if(d!==void 0){b=h===void 0?a.Sa:parseInt(h,10);
b===void 0&&(b=10);b>d.length&&(a.v("note: only %d available\n",d.length),b=d.length);h!==void 0&&(a.Aa=0,a.v("%d instructions earlier:\n",b));h=a.Aa?a.Aa:1;c-=b;for(c<0&&(c=d.length-1);l&&c!=a.la;){e=d[c];if(e<0)break;a.v("%s\n",Bc(a,e,h++));++c==d.length&&(c=0);l--;b--}a.Sa=b;a.Aa=h}l==10&&a.v("no history available\n");break;case "r":wc(a,c);break;case "s":a.da(a.F.j)==a.F.Pa?(Ac(a,a.F.j+3),a.ja=!0,a.za()||a.F.ra()):Dc(a);break;case "t":Dc(a,c[1]);break;case "u":vc(a,c[1],c[2],8);break;case "?":case "help":a.v("\ncommands:\n?\thelp\na [#]\tassemble\nb [#]\tbreakpoint\nd [#]\tdump memory\ne [#]\tedit memory\nf\tdump frequencies\ng [#]\trun to [#]\nh\thalt\no\toptions\np [#]\tdump history\nr\tdump/edit registers\ns\tstep over instruction\nt [#]\tstep instruction(s)\nu [#]\tunassemble\n");
a.v("note: frequency and history commands operate only when breakpoints are set\n");break;default:a.v("unknown command: %s\n",b)}}}E(function(){for(var a=L("c1p","debugger"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new rc(d);I(d,c)}});function Ec(a,b){H.call(this,"C1PComputer",a);this.g=b}v(Ec,H);Ec.prototype.reset=function(a){var b=null,c;for(c in this.g)for(var d=0;d<this.g[c].length;d++){var e=this.g[c][d];e&&e.reset&&(e.reset(),c=="cpu"&&(b=e))}b&&(b.update(),a&&b.za())};
Ec.prototype.start=function(){for(var a in this.g)if(a!="cpu")for(var b=0;b<this.g[a].length;b++){var c=this.g[a][b];c&&c.start&&c.start()}};Ec.prototype.stop=function(a,b){for(var c in this.g)if(c!="cpu")for(var d=0;d<this.g[c].length;d++){var e=this.g[c][d];e&&e.stop&&e.stop(a,b)}};Ec.prototype.ea=function(a,b,c){switch(b){case "reset":return this.N[b]=c,c.onclick=function(d){return function(){d.reset()}}(this),!0}return!1};function Q(a,b){return a.g[b]?a.g[b][0]:null}
function Fc(a){var b=null,c;for(c in a.g)for(var d=0;d<a.g[c].length;d++){var e=a.g[c][d];if(e){if(!N(e)){N(e,function(f){return function(){Fc(f)}}(a));return}c=="cpu"?b=e:e.ta&&e.ta(!0,a)}}a.fa();a.v(0,"%s v%s\n%s\n","C1Pjs","2.21","Copyright \u00a9 2012-2026 Jeff Parsons <Jeff@pcjs.org>");b&&b.ta(!0,a)}
E(function(){for(var a=L("c1p","computer"),b=0;b<a.length;b++){for(var c=a[b],d=M(c),e,f={},h,k=0,l=0,q=0;q<d.modules.length;q++){var m=d.modules[q];if(!q){if(m.type!="cpu")break;k=+m.start;l=+m.end;h=Array(l+1-k);for(e=k;e<h.length;e++)h[e]=0}if(e=db(m.refID,d.id)){var p=m.type;f[p]===void 0&&(f[p]=[]);f[p].push(e);e.qa&&m.start!==void 0&&e.qa(h,+m.start,+m.end,f.cpu[0])}else{C(1099511627776,'no component for <module refid="'+m.refID+'">');return}}if(h===void 0){C(1099511627776,'<module type="cpu"> definition must appear first in the <computer> specification');
break}if(e=eb("C1PDebugger",d.id,!1))f["debugger"]=[e],e.qa&&e.qa(h,k,l,f.cpu[0]);k=new Ec(d,f);if(l=eb("C1PPanel",d.id,!1))if(f.panel=[l],l.N.print){e=void 0;d=d.id;f=[];d&&(e=d.indexOf("."))>0&&(d=d.substr(0,e+1));q=y.components;for(e=0;e<q.length;e++)m=q[e],d&&m.id.indexOf(d)!=0||f.push(m);d=f;for(f=0;f<d.length;f++)e=d[f],e!=l&&(e.print=l.print)}I(k,c);Fc(k)}});var Gc=0;
function Hc(a,b,c,d,e,f,h,k,l){k("Loading "+a+"...");B(a,function(q,m,p){p?(m||(m="unable to load "+a+" ("+p+")"),l(q,m,null)):Ic(m,a,b,c,d,e,f,h,k,l)})}
function Ic(a,b,c,d,e,f,h,k,l,q){function m(p,n,r){if(r)q(p,r,null);else{c&&(bb(c,b,n),(r=b)&&r.indexOf("/")<0&&window.location.pathname.slice(-1)=="/"&&(r=window.location.pathname+r),f?f.slice(-1)=="}"?(f=f.slice(0,-1),f.length>1&&(f+=",")):f='{state:"'+f+'",':f="{",f+='url:"'+r+'"}',typeof resources=="object"&&(r=null),f=f.replace(/\$/g,"$$$$").replace(/'/g,"&apos;"),h&&(p=n.match(/(<machine[^>]*\sclass=)(['"])(.*?)(\2[^>]*>)/))&&(n=n.replace(p[0],p[1]+p[2]+h+p[4]),h=""),(p=n.match(/(<machine[^>]*\sdebugger=)(['"])(available)(\2[^>]*>)/))&&
(n=n.replace(p[0],p[1]+p[2]+"optional"+p[4])),n=n.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(h?' class="'+h+'"':"")+(f?" parms='"+f+"'":"")+(r?' url="'+r+'"':"")));k||(n=n.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1"+d+"$2"),n=n.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1"+e+"$2"),n=n.replace(/<xsl:variable name="APPVERSION"(\/>|>[^<]*<\/xsl:variable>)/,'<xsl:variable name="APPVERSION">2.21</xsl:variable>'));p=null;if(n.charAt(0)=="<")try{k||
(n=n.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(p=new window.ActiveXObject("Microsoft.XMLDOM"),p.async=!1,p.loadXML(n)):p=(new window.DOMParser).parseFromString(n,"text/xml")}catch(J){p=null,n=J.message}else n="unrecognized XML: "+(n.length>255?n.substr(0,255)+"...":n);q(b,n,p)}}a?k?Jc(b,a,l,m):m(b,a,""):q(b,"no data",null)}
function Jc(a,b,c,d){var e;if(e=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(b)){var f=e[2];c("Loading "+f+"...");B(f,function(h,k,l){if(l||!k)d(h,b,"unable to resolve XML reference: "+e[0]+" ("+l+")");else{if(l=e[3]){var q=k.match(new RegExp("<"+e[1]+"[^>]*>"));if(q){for(var m=q[0],p,n=/( [a-z]+=)(['"])(.*?)\2/gi;p=n.exec(l);)m=m.toLowerCase().indexOf(p[1].toLowerCase())<0?m.replace(">",p[0]+">"):m.replace(new RegExp(p[1]+"(['\"])(.*?)\\1"),p[0]);q[0]!=m&&(k=k.replace(q[0],m))}else{d(h,b,"missing <"+
e[1]+"> in "+f);return}}k=k.replace(/<\?xml[^>]*>[\r\n]*/,"");b=b.replace(e[0],k);Jc(h,b,c,d)}})}else d(a,b,"")}
function Kc(a,b,c,d,e,f,h){function k(w){if(p===void 0){var u=m&&L("machine-warning","",m);p=u&&u[0]||m}p&&(p.innerHTML=Ga(w))}function l(w,u){if(typeof u=="string"&&u.indexOf("<!DOCTYPE html>")>=0){var fa=u.match(/<title>(?:PCjs: |)(.*?)<\/title>/);fa&&(u=fa[1])}C(1099511627776,"%s\n",u);k("Error: "+u+(w?" ("+w+")":""));n&&q();n=!1}function q(){--Gc||G(!0)}var m,p,n=!0;Gc++;y.machines[c]={};if(!d)return f&&bb(c,"parms",f),q(),n;Oa("debugger")=="true"&&d.indexOf("/debugger")<0&&(d=d.replace("/machine.xml",
"/debugger/machine.xml"));try{if(m=document.getElementById(c)){var r,J=x.resources;if(typeof J=="object"&&(r=J.css)){var V=document.head||document.getElementsByTagName("head")[0],A=document.createElement("style");A.type="text/css";A.styleSheet?A.styleSheet.cssText=r:A.appendChild(document.createTextNode(r));V.appendChild(A)}e||(e="/machines/"+b+"/xsl/components.xsl");b=b.split("/").pop();r=function(w,u,fa){fa?Hc(e||"","",a,b,"","",!1,k,function(O,U,K){if(K)if(bb(c,e||"",U),k("Processing "+d+"..."),
window.ActiveXObject||"ActiveXObject"in window)(K=fa.transformNode(K))?(m.outerHTML=K,q()):l(O,"transformNodeToObject failed");else if(document.implementation&&document.implementation.createDocument)if(U=new XSLTProcessor,U.importStylesheet(K),K=U.transformToFragment(fa,document))if(U=m.parentNode){var ya=O=0,Ya=m.getBoundingClientRect();Ya.bottom<0&&(O=window.scrollX,ya=window.scrollY);U.replaceChild(K,m);(m=document.getElementById(c))&&Ya.bottom<0&&(K=m.getBoundingClientRect(),ya=window.performance&&
window.performance.navigation.type==window.performance.navigation.TYPE_RELOAD?0:ya+Math.ceil(K.height-Ya.height),window.scrollTo(O,ya));q()}else l(O,"invalid machine element: "+c);else l(O,"transformToFragment failed");else l(O,"unable to transform XML: unsupported browser");else l(O,U)}):l(w,u)};d.charAt(0)!="<"?Hc(d,c,a,b,f||"",h||"",!0,k,r):Ic(d,"",c,a,b,f||"",h||"",!1,k,r)}else l(d,"missing machine element: "+c)}catch(w){l(d,w.message)}return n}
function Lc(a,b,c,d,e){G(!1);return Kc("PCx86","pcx86",a,b,c,d,e)}x.embedC1P=function(a,b,c,d,e){G(!1);return Kc("C1Pjs","osi/c1p",a,b,c,void 0,e)};x.embedPC=Lc;x.embedPCx86=Lc;x.embedPCx80=function(a,b,c,d,e){G(!1);return Kc("PCx80","pcx80",a,b,c,d,e)};x.embedPDP10=function(a,b,c,d,e){G(!1);return Kc("PDPjs","dec/pdp10",a,b,c,d,e)};x.embedPDP11=function(a,b,c,d,e){G(!1);return Kc("PDPjs","dec/pdp11",a,b,c,d,e)};
x.commandMachine=function(a,b,c,d,e,f){if(e=="script"){d=!1;e=y.commands;c+=".machine";if(!f)delete e[c],d=!0;else if(typeof f=="string"&&!e[c]){d=!0;for(var h=c,k=f.length,l=[],q=[],m="",p=null,n=0;n<k;n++){var r=f[n];if(r=='"'||r=="'")p&&r!=p?m+=r:(p?p=null:p=r,m&&(q.push(m),m=""));else{if(!p){if(r=="\r"||r=="\n")r=";";if(r==" "||r=="\t"||r==";"){m&&(q.push(m),m="");r==";"&&q.length&&(l.push(q),q=[]);continue}}m+=r}}m&&q.push(m);q.length&&l.push(q);e[h]=l;fb(c)||(d=!1)}return d?(b&&(a.disabled=
!0),!0):!1}if(d&&(h=eb(d,c+".machine"))&&(k=h.exports)&&(k=k[e]))return k.call(h,f)?(b&&(a.disabled=!0),!0):!1;console.log("unimplemented: commandMachine('"+c+"','"+d+"','"+e+"','"+f+"')");return!1};x.enableEvents=G;x.sendEvent=F;})()

//# sourceMappingURL=c1p.js.map
