(function(){/*
 https://www.pcjs.org/modules/v3/defines.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/numio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v1/format.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/stdio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/webio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/device.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/input.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/led.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/time.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/bus.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/memory.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/rom.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/cpu.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/cpu1500.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/machine.js (C) 2012-2023 Jeff Parsons
*/
var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function r(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function t(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function u(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ve=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
t("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});t("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
t("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
t("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});t("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});
t("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}t("Array.prototype.keys",function(a){return a?a:function(){return na(this,function(b){return b})}});
t("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function y(a){return a?a:Array.prototype.fill}t("Int8Array.prototype.fill",y);t("Uint8Array.prototype.fill",y);t("Uint8ClampedArray.prototype.fill",y);t("Int16Array.prototype.fill",y);t("Uint16Array.prototype.fill",y);t("Int32Array.prototype.fill",y);
t("Uint32Array.prototype.fill",y);t("Float32Array.prototype.fill",y);t("Float64Array.prototype.fill",y);t("Number.parseInt",function(a){return a||parseInt});t("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});function oa(){}var pa=new ArrayBuffer(2);(new DataView(pa)).setUint16(0,256,!0);new Uint16Array(pa);var B={$b:0xffffffffffff,NONE:0,ic:0,ya:0x800000000000};
"undefined"!=typeof window&&(window.PCjs||(window.PCjs={}),window.PCjs.machines||(window.PCjs.machines={}),window.PCjs.components||(window.PCjs.components=[]));var C="undefined"!=typeof window?window.PCjs.machines:{},qa="undefined"!=typeof window?window.PCjs.components:[],D={};D.Defines=oa;function ra(){}u(ra,oa);function sa(a,b){var c=a/E|0,d=b/E|0;return(a&b)==(b|0)&&(c&d)==d}var E=Math.pow(2,32);D.NumIO=ra;function ta(){this.g={};for(var a=0;22>a;a++)this.g["ACDFGHMNSTWYbdfjcsoXx%"[a]]=null}
function ua(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,r(a)));return a}
ta.prototype.L=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(void 0===this.g[g])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];"%"!=g&&e++}else h=b[b.length-1];var l=d[f+1],k=0<=l.indexOf("#"),m=0<=l.indexOf("0"),n=d[f+2];"*"==n?(n=h,h=e<b.length?b[e++]:b[b.length-1]):n=+n||0;var q=d[f+3];q=q?+q.substr(1):-1;var v=d[f+4],z=null,
w=0,A="",x=0<="ACDFGHMNSTWY".indexOf(g)&&"object"!=typeof h?ua(h):h;switch(g){case "C":c+=isNaN(x.getTime())?void 0:this.L("%#W, %#F %#D, %#Y".replaceAll("#",k?"#":""),x);continue;case "D":h=k?x.getUTCDate():x.getDate();g="d";break;case "A":case "G":case "H":h=k?x.getUTCHours():x.getHours();"A"==g?(h=12>h?"am":"pm",g="s"):("G"==g&&(h=h?12<h?h-12:h:12),g="d");break;case "F":case "M":h=k?x.getUTCMonth():x.getMonth();"F"==g?(h=va[h],g="s"):(h++,g="d");break;case "N":h=k?x.getUTCMinutes():x.getMinutes();
g="d";break;case "S":h=k?x.getUTCSeconds():x.getSeconds();g="d";break;case "T":c+=isNaN(x.getTime())?void 0:this.L("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",k?"#":""),x);continue;case "W":h=wa[k?x.getUTCDay():x.getDay()];g="s";break;case "Y":h=k?x.getUTCFullYear():x.getFullYear(),0<q&&(h%=Math.pow(10,q),q=-1),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=q&&(m=!0,n<q&&(n=q),q=-1);case "f":h=+h;g=h+"";0<=q&&(g=h.toFixed(q));g.length<n&&(m?(0>h&&(n--,g=g.substr(1)),
g=("0".repeat(n)+g).slice(-n),0>h&&(g="-"+g)):g=(" ".repeat(n)+g).slice(-n));c+=g;break;case "j":c+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=q&&(h=h.substr(0,q));h.length<n;)h=0<=l.indexOf("-")?h+" ":" "+h;c+=h;break;case "o":w=8,k&&(A="0o");case "X":z=xa;case "x":g="";w||(w=16);!A&&k&&(A="0x");z||(z=ya);h=Math.trunc(h);0<=q&&(m=!0,n<q&&(n=q));m&&!n&&("b"==v?n=2:"h"==v||"w"==v?
n=4:"l"==v?n=8:(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9),n+=A.length);n-=A.length;do k=16,Number.isNaN(h)||(k=h&w-1,h=Math.trunc(h/w)),m||!g||k||h?g=z[k]+g:(A&&(g=A+g,A=""),0<n&&(g=" "+g));while(0<--n||h);c+=A+g;break;case "%":c+="%";break;default:c=this.g[g]?c+this.g[g](g,l,n,q,h):c+("(unimplemented sprintf type: %"+g+")")}}}return c+=d[f]};var ya="0123456789abcdef?",xa="0123456789ABCDEF?",wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" ");
function F(){this.vb=new ta;this.W=this.vb.L.bind(this.vb)}u(F,ra);F.prototype.flush=function(){var a=za;za="";this.ua(a)};function Aa(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}F.prototype.ua=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),Ba||(Ba=b),a=((b-Ba)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(za+a.substr(0,c)),za="",a=a.substr(c+1)),Ba=null);za+=a;return a.length};
F.prototype.u=function(a){return this.ua(this.W.apply(this,[a].concat(r(la.apply(1,arguments)))))};var za="",Ba=null;D.StdIO=F;function G(a){F.call(this);this.S={};this.fa=0;this.L=this;a&&(this.L.fa=0,this.L.ta=[],this.L.ja=0,this.L.Ja={},this.L.Ie=!1)}var Ca;u(G,F);p=G.prototype;
p.Ba=function(a,b){var c=this,d=this;switch(a){case Da.dc:b.onclick=function(){var e=c.Da(Da.Ya,!0);e&&(e.value="")};break;case Da.Ya:Ea(b),b.addEventListener("keydown",function(e){Fa(d,e,!0)}),b.addEventListener("keypress",function(e){Fa(d,e)})}};
function Ga(a,b){b=void 0===b?{}:b;if("undefined"!=typeof document){a.J.S||(a.J.S=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.X);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.S[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.S[d].push(e)}while(1);continue}if(f=document.getElementById(e))a.S[d]=f,a.Ba(d,f)}}}
function Ea(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}p.error=function(a,b){b=this.W.apply(this,[a].concat(r(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.W.apply(this,[c].concat(r(b))))this.u("%s\n",b),a||alert(b)};p.Da=function(a){return this.S[a]};
function Ha(a){var b=window;if(b){do{for(var c=0;c<Ia.length;c++){var d=Ia[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ja(a,b){return a.J.bindings&&a.J.bindings[b]}function Ka(a){if(a=a.S[La])var b=a.textContent;return b}function Ma(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function H(a,b,c,d){a=a.J[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Na(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Oa(a){if(void 0===I.Va){var b=!1;if(window)try{window.localStorage.setItem(I.Aa,I.Aa),b=window.localStorage.getItem(I.Aa)==I.Aa,window.localStorage.removeItem(I.Aa)}catch(c){a.u("%s\n",c.message),b=!1}I.Va=b}return!!I.Va}function J(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.fa;return-1==(b|1)||sa(a.L.fa,b)?!0:!1}
function Pa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Qa(a){var b=null;if(Oa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.M))&&(b=JSON.parse(c))}catch(d){a.u("%s\n",d.message)}}return b}
function Fa(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.L,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==K.hb&&f.selectionStart<=h+1&&(a=!0);d==K.bd?(a=!0,0<e.ja&&(g=e.ta[--e.ja])):d==K.kc&&(a=!0,e.ja<e.ta.length&&(g=e.ta[++e.ja]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ja&&c+1==g.length&&
(f.value+=e.ta[--e.ja],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ra(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&a.u("%s\n",b.replace(/\n$/,"")))}}
function Sa(a,b){if(void 0!=b){var c=a.L;try{if(b=b.trim())c.ja<c.ta.length&&b==c.ta[c.ja]?c.ja++:(c.ta.push(b),c.ja=c.ta.length);var d=b.split(" "),e=d[0],f=a.L.Ja[Ta.kb];switch(e[0]){case "m":if("?"==e[1]){var g="";Ua.forEach(function(n){g+=n+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var l="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=l&&d.pop();1>=d.length&&(void 0!=l&&(h=l,l=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(L));for(f=
1;f<d.length;f++){e=d[f];var k=L[e];if(!k){g+="unrecognized message: "+e+"\n";break}void 0!=l&&Va(a,k,l);if(void 0==h||h==J(a,k))g+=a.W("%8s: %b\n",e,J(a,k))}J(a,B.ya)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Wa.forEach(function(n){g+=n+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var m=f[a](d);if(void 0!=m){g=g?g+m:m;break}}}}catch(n){g="error: "+n.message+"\n"}}return g}
function Ra(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Sa(a,b[d])}return c}p.ua=function(a,b){void 0==b&&(b=J(this,B.ya));if(!b){var c=this.Da(Da.Ya,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Pa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return F.prototype.ua.call(this,a,b)};
p.u=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return J(this,c)?F.prototype.u.call.apply(F.prototype.u,[this,a].concat(r(b))):0};function Xa(a,b){if(Oa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.M,b)}catch(c){a.u("%s\n",c.message)}}}function M(a,b,c){(a=a.S[b])&&a.textContent!=c&&(a.textContent=c)}
function Va(a,b,c){var d=!1;c?(c=a.L.fa,a.L.fa=(c|b)+(c/E|0|b/E|0)*E):(d=sa(a.L.fa,B.ya)&&sa(b,B.ya),c=a.L.fa,a.L.fa=(c&~b)+((c/E|0)&~(b/E|0))*E);d&&a.flush()}
var Da={dc:"clear",Ya:"print"},Wa=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Ua=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],L={all:B.$b,buffer:B.ya},Ta={kb:"command"},Ya={lb:13,Ua:65,gb:66,ib:67,mb:68,E:69,ob:70,pb:71,qb:72,rb:73,tb:74,wb:75,yb:76,Bb:77,Cb:78,Db:79,Eb:80,Q:81,Gb:82,Ib:83,Jb:84,
Kb:85,Lb:86,Mb:87,Nb:88,Ob:89,ab:90,a:97,b:98,c:99,d:100,e:101,f:102,Ne:103,Oe:104,Pe:105,Qe:106,k:107,Re:108,Se:109,n:110,Te:111,p:112,q:113,r:114,Ue:115,t:116,We:117,Xe:118,w:119,x:120,y:121,z:122},K={hb:8,Vc:9,Bc:10,lb:13,Rc:16,fc:17,ac:18,xe:19,Wa:20,zd:27,Tc:32,Ae:33,ze:34,yd:35,Ud:36,zb:37,bd:38,Za:39,Rd:39,kc:40,Od:44,Be:44,Vd:45,xd:46,Qd:46,Td:47,ZERO:48,ONE:49,$c:50,Wc:51,vc:52,uc:53,Sc:54,Qc:55,lc:56,Hc:57,sc:59,rc:61,Ua:65,gb:66,ib:67,mb:68,E:69,ob:70,pb:71,qb:72,rb:73,tb:74,wb:75,yb:76,
Bb:77,Cb:78,Db:79,Eb:80,Q:81,Gb:82,Ib:83,Jb:84,Kb:85,Lb:86,Mb:87,Nb:88,Ob:89,ab:90,jb:91,Pd:91,Nd:92,Ee:93,Sd:93,Zd:96,pe:96,Md:96,$d:97,ne:97,ae:98,me:98,be:99,se:99,ce:100,qe:100,de:101,je:101,ee:102,ue:102,fe:103,oe:103,ge:104,we:104,he:105,te:105,re:106,ie:107,ve:109,ke:110,le:111,Ad:112,Ed:113,Fd:114,Gd:115,Hd:116,Id:117,Jd:118,Kd:119,Ld:120,Bd:121,Cd:122,Dd:123,Ic:144,Nc:145,qc:173,Oc:186,mc:187,vd:188,hc:189,ye:190,Ge:191,td:192,Wd:219,ud:220,De:221,Ce:222,pc:224,Xd:901,He:1E3},Za={},$a=(Za[K.sc]=
K.Oc,Za[K.rc]=K.mc,Za[K.qc]=K.hc,Za[K.pc]=K.jb,Za),ab={zb:1,Za:2,Yd:3},N={},bb=(N[K.hb]="\b",N[K.Vc]="\t",N[K.Bc]="\n",N[K.lb]="\r",N[K.Tc]=" ",N[K.ZERO]="0",N[K.ONE]="1",N[K.$c]="2",N[K.Wc]="3",N[K.vc]="4",N[K.uc]="5",N[K.Sc]="6",N[K.Qc]="7",N[K.lc]="8",N[K.Hc]="9",N[K.Ua]="A",N[K.gb]="B",N[K.ib]="C",N[K.mb]="D",N[K.E]="E",N[K.ob]="F",N[K.pb]="G",N[K.qb]="H",N[K.rb]="I",N[K.tb]="J",N[K.wb]="K",N[K.yb]="L",N[K.Bb]="M",N[K.Cb]="N",N[K.Db]="O",N[K.Eb]="P",N[K.Q]="Q",N[K.Gb]="R",N[K.Ib]="S",N[K.Jb]=
"T",N[K.Kb]="U",N[K.Lb]="V",N[K.Mb]="W",N[K.Nb]="X",N[K.Ob]="Y",N[K.ab]="Z",N[K.zb]="Left",N[K.Za]="Right",N),Ia=["","moz","ms","webkit"],cb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},I={Va:void 0,Aa:"PCjs.localStorage"};D.WebIO=G;
function O(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;G.call(this,a==b);this.M=a;this.X=b;C[this.M]||(C[this.M]={});C[this.M][this.X]&&this.u("warning: machine configuration contains multiple '%s' devices\n",this.X);C[this.M][this.X]=this;this.id=this.M==this.X?this.M:this.M+"."+this.X;qa.push(this);this.L=P(this,this.M);this.ready=!0;db(this,c,d);this.ad={};this.Ab=[]}u(O,G);
function db(a,b,c){c=b.overrides||c;if(c.length){var d,e=Ca;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,h=/([^&=]+)=?([^&]*)/g;f=h.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ca=e}d=e;for(var l in d)if(0<=c.indexOf(l)){e=d[l];f=void 0;var k;g=void 0;h=e;var m=10;if(h){m||(m=10);var n=0<h.indexOf(",");n&&(h=h.replace(/,/g,""));var q=k=h.charAt(0);"#"==k?(m=8,k=""):"$"==k&&(m=16,k="");q!=k?h=h.substr(1):
(q=k=h.substr(0,2),"0b"==k&&n||"^B"==k?(m=2,k=""):"0o"==k||"^O"==k?(m=8,k=""):"^D"==k?(m=10,k=""):"0x"==k&&(m=16,k=""),q!=k&&(h=h.substr(2)));q=k=h.slice(-1);"Y"==k||"y"==k?(m=2,k=""):"."==k?(m=10,k=""):"H"==k||"h"==k?(m=16,k=""):"K"==k?k="000":"M"==k?k="000000":"G"==k&&(k="000000000");q!=k&&(h=h.slice(0,-1)+k);q=0;10>=m&&(k=h.match(/(-?[0-9]+)B([0-9]*)$/))&&(h=k[1],q=35-((k[2]||35)&255));(m&&10!=m?16==m?null===h.match(/^-?[0-9a-f]+$/i):8==m?null===h.match(/^-?[0-7]+$/):2!=m||null===h.match(/^-?[01]+$/):
null===h.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(h,m))||(q&&(0>f&&(f+=Math.pow(2,36)),f=0<q?f*Math.pow(2,q):Math.trunc(f/Math.pow(2,-q))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[l]=f;a.u("overriding %s property '%s' with %s\n",a.X,l,e)}}a.J=b;Ga(a,b.bindings);b=void 0===b?{}:b;a.version=3;if(a.version){c="";var v;a.M!=a.X&&(v=P(a,a.M).version)&&v!=a.version&&(c="Machine");c||(v=b.version)&&v>a.version&&(c="Config");c&&(v=a.W("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.Ke,a.version,c,v),a.error("%s\n\nClearing your browser's cache may resolve the issue.",v))}}function eb(a,b){var c;try{var d=C[a.M];if(d)for(c in d){var e=d[c];if(e.X!=e.M&&!b(e))return!1}return!0}catch(f){a.u("error while enumerating device '%s': %s\n",c,f.message)}return!1}O.prototype.Da=function(a,b){b=void 0===b?!1:b;if(a){var c=G.prototype.Da.call(this,a,b);if(void 0===c&&b){b=C[this.M];for(var d in b)if(c=b[d].S[a])break;c||(c=null);this.S[a]=c}}return c};
function P(a,b,c){var d=b,e=a.M,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=C[e])&&f[b]||null;if(!b){for(f=0;f<qa.length;f++)if(qa[f].id===d){b=qa[f];break}if(!b&&(void 0===c||c))throw Error(a.W('no "%s" device',d));}return b}function Q(a,b,c){var d=null,e=C[a.M];if(e)for(var f in e)if(e[f].J["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.W("no %s device",b));return d}function fb(a){return a==a.L&&a.ready?eb(a,function(b){return fb(b)}):a.ready}
function gb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(fb(a)){for(;b=a.Ab.pop();)b();a!=a.L&&gb(a.L)}}function hb(a,b){if(fb(a))return b(),!0;a.Ab.push(b);return!1}
O.prototype.u=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&J(this,a)&&(void 0===this.pa&&(this.pa=Q(this,"Debugger",!1)),this.L.fa&B.fb&&(void 0===this.da&&(this.da=Q(this,"CPU")),this.da))?(a=b.shift(),G.prototype.u.call(this,"%#06x: %s.%s\n",this.da.Ra,this.X,this.W.apply(this,[a].concat(r(b))).trim())):G.prototype.u.call.apply(G.prototype.u,[this,a].concat(r(b)))};function ib(a,b){(a=C[a.M])&&delete a[b]}O.prototype.Vb=function(a,b){(a=this.ad[a])&&a.set&&a.set(b)};B.fb=1;
B.bc=2;B.oc=4;B.Cc=8;B.Jc=16;B.cc=32;B.Ac=64;B.Pc=128;B.Dc=256;B.ec=512;B.Ec=1024;B.INT=2048;B.Zc=4096;B.dd=8192;B.Fc=16384;B.Mc=32768;B.jc=65536;B.tc=131072;B.za=262144;B.Xc=524288;B.nb=1048576;B.sb=2097152;B.xb=4194304;B.Gc=8388608;B.Yc=16777216;B.xc=33554432;B.$a=67108864;B.nc=134217728;B.wc=268435456;B.wd=4294967296;L.addr=B.fb;L.bus=B.bc;L.fault=B.oc;L.memory=B.Cc;L.ports=B.Jc;L.chips=B.cc;L.kbd=B.Ac;L.serial=B.Pc;L.misc=B.Dc;L.cpu=B.ec;L.mmu=B.Ec;L["int"]=B.INT;L.trap=B.Zc;L.video=B.dd;
L.monitor=B.Fc;L.screen=B.Mc;L.disk=B.jc;L.file=B.tc;L.time=B.za;L.timer=B.Xc;L.event=B.nb;L.input=B.sb;L.key=B.xb;L.mouse=B.Gc;L.touch=B.Yc;L.info=B.xc;L.warn=B.$a;L.error=B.nc;L.halt=B.wc;D.Device=O;
function jb(a,b,c){O.call(this,a,b,c);this.fa=B.sb;this.K=this.O=null;this.time=Q(this,"Time");this.L=Q(this,"Machine");this.ba=H(this,"drag",!1);this.Y=H(this,"scroll",!1);this.aa=H(this,"hexagonal",!1);this.s=H(this,"releaseDelay",0);this.v=!1;a=this.J.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.j[f]={keys:g,grid:e,
state:0}}}this.R=[];this.T=[];this.m=this.U=null;(a=this.S[kb])&&lb(this,a,this.Da(c.focusBinding,!0),this.J.location);this.qa()}u(jb,O);function mb(a,b){a.O=b}function nb(a,b,c){for(var d=0;d<a.R.length;d++){var e=a.R[d];e.id===b&&e.Tb(b,c)}}
function lb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.rd=d[0]||0;e.sd=d[1]||0;e.Ca=d[2]||b.clientWidth;e.Na=d[3]||b.clientHeight;e.Oa=d[4]||1;e.Sa=d[5]||1;e.hd=d[6]||b.naturalWidth||e.Ca;e.kd=d[7]||b.naturalHeight||e.Na;e.Yb=d[8]||0;e.Zb=d[9]||0;e.gd=d[10]||0;e.jd=d[11]||0;a.h?(e.Qa=a.h.length,e.Ea=a.h[0].length):(e.Ea=e.Oa,e.Qa=e.Sa,e.Oa=e.Sa=0);e.Pb=e.Ca/(e.Ea+e.Ea*e.Oa)|0;e.Qb=e.Na/(e.Qa+e.Qa*e.Sa)|0;e.fd=e.Pb*e.Oa|0;e.Rb=e.Qb*e.Sa|0;e.Ia=e.Ta=-1;ob(a,b,e);pb(a,b,e);a.time&&
a.s&&(a.$=qb(a.time,"timerInputRelease",function(){0>e.Ia&&0>e.Ta&&rb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.s&&(a.ca=qb(a.time,"timerKeyRelease",function(){sb(a)})),a.H=0,a.N="",a.I=[],d=b,c&&(d=c,a.m||"BUTTON"!=c.nodeName||(d=document,a.m=c,tb(a,b),a.U=b)),tb(a,d),a.m||(a.m=d)}function ub(a){a.s?vb(a.time,a.ca,a.s):sb(a)}
function tb(a,b){function c(e,f,g){var h=document.activeElement;a.u(B.xb+B.nb,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.m&&e!=a.m&&e!=a.U?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=wb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=wb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=wb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function ob(a,b,c){b.addEventListener("mousedown",function(d){if(!a.v){var e=a.m;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,xb,d,c)}});b.addEventListener("mousemove",function(d){a.v||R(a,b,yb,d,c)});b.addEventListener("mouseup",function(d){a.v||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.v||(0>c.Ia?R(a,b,yb,d,c):R(a,b,S,d,c))})}
function pb(a,b,c){b.addEventListener("touchstart",function(d){a.Y&&(a.v=!0);R(a,b,xb,d,c)});b.addEventListener("touchmove",function(d){R(a,b,yb,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function wb(a,b,c,d){if(void 0!=c){var e=$a[b]||b;var f=bb[b];var g=zb[e];d=d&&d.location==ab.Za;g&Ab&&d&&(g>>=1);g&&(g&Bb&&(c=!(a.g&g)),a.g=c?a.g|g:a.g&~g,nb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=Ya.Ua&&b<=Ya.ab?a.g&(Cb|Db)||(a.g|=Db,nb(a,K.Wa,!0)):b>=Ya.a&&b<=Ya.z&&a.g&Db&&(a.g&=~Db,nb(a,K.Wa,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(g=a.h[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.H?16>a.I.length&&a.I.push(b):(a.H=1,a.N=f,rb(a,d,e),nb(a,
f,!0),ub(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(g=b[e],0<=a.j[g].keys.indexOf(f))return nb(a,g,c),a.j[g].state=c?1:0,!0}return!1}function sb(a){1==a.H?(a.H++,nb(a,a.N,!1),a.N="",rb(a,-1,-1),ub(a)):(a.H=0,a.I.length&&wb(a,a.I.shift()))}jb.prototype.qa=function(){this.g=0;this.V=this.Z=-1};
function R(a,b,c,d,e){var f=-1,g=-1,h=!1,l=-1,k=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(l=d.targetTouches[0].clientX,k=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(l=d.clientX,k=d.clientY);var m=d.target.getBoundingClientRect();l-=m.left;k-=m.top;l=e.hd/b.offsetWidth*l|0;k=e.kd/b.offsetHeight*k|0;var n=l-e.rd;var q=k-e.sd;var v=m=!1;var z=l>=e.Yb&&l<e.Yb+e.gd&&k>=e.Zb&&k<e.Zb+e.jd;if(0<=n&&n<e.Ca&&0<=q+e.Rb||z)if(h||a.Y||d.preventDefault(),0<=n&&n<e.Ca&&0<=
q&&q<e.Na){v=!0;d=e.Ca/e.Ea|0;var w=e.Na/e.Qa|0,A=n/d|0,x=q/w|0;!a.aa||x&1||(n-=d>>1,A=n/d|0,A==e.Ea-1&&(n=-1));w=x*w+(e.Rb>>1);n-=A*d+(e.fd>>1);q-=w;0<=n&&n<e.Pb&&0<=q&&q<e.Qb&&(f=A,g=x,m=!0)}}n=n||0;q=q||0;d=b.offsetWidth;b=b.offsetHeight;if(c==xb||c==S)for(A=0;A<a.T.length;A++)x=a.T[A],c==S?x.Tb(x.id,!1):(w=q/(b/x.Me|0)|0,(n/(d/x.Le|0)|0)==x.Ye&&w==x.Ze&&x.Tb(x.id,!0));if(!h)if(c==xb)e.Ia=l,e.Ta=k,v?(rb(a,f,g),m&&a.s&&vb(a.time,a.$,a.s,!0)):z&&a.L.ha();else if(c==yb)0<=e.Ia&&0<=e.Ta&&a.ba?rb(a,
f,g):a.O&&a.O(f,g);else if(c==S){if(c=a.s)c=a.time,f=a.$,c=c.g&&0<f&&f<=c.h.length?0<=c.h[f-1].ga:!1;c||rb(a,-1,-1);e.Ia=e.Ta=-1}else a.u("unrecognized action: %d\n",c)}function rb(a,b,c){if(b!=a.V||c!=a.Z)a.V=b,a.Z=c,a.K&&a.K(b,c)}var xb=1,yb=2,S=3,kb="surface",Cb=3,Ab=170,Db=512,Bb=3584,T={},zb=(T[K.Rc]=2,T[K.fc]=8,T[K.ac]=32,T[K.jb]=128,T[K.Wa]=Db,T[K.Ic]=1024,T[K.Nc]=2048,T);D.Input=jb;
function Eb(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.S[Fb];if(!a)throw Error("LED "+this.J.S[Fb]+" binding for '"+Fb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.va=Ja(this,Fb)+".canvas";b.setAttribute("id",this.va);this.Xa=a;this.type=Ma(H(this,"type",Gb,Hb),Ib,Jb);this.m=Kb[this.type][0];this.I=Kb[this.type][1];this.width=H(this,"width",
this.m);this.height=H(this,"height",this.I);this.s=H(this,"cols",1);this.R=this.s+H(this,"colsExtra",0);this.ba=H(this,"rows",1);this.V=this.ba+H(this,"rowsExtra",0);this.ea=this.width*this.s;this.Z=this.height*this.ba;this.H=Lb("black",0);this.j=Mb(this.J.color)||this.H;this.ma=Lb(this.j,1,.25);this.la=Lb(this.j,1,2);this.v=Mb(this.J.backgroundColor);this.na=H(this,"fixed",!1);this.na||(b.style.width="100%",b.style.height="auto");this.ka=H(this,"hexagonal",!1);this.sa=H(this,"highlight",!0);this.Y=
H(this,"persistent",this.type<Jb);b.setAttribute("width",this.ea.toString());b.setAttribute("height",this.Z.toString());b.style.backgroundColor=this.H;a.appendChild(b);this.ia=b.getContext("2d");if(this.K=document.createElement("canvas"))this.K.width=this.ca=this.m*this.s,this.K.height=this.N=this.I*this.ba,this.h=this.K.getContext("2d");this.wa=(this.V+1)*this.R*4;this.g=Array(this.wa);this.Ka=this.s<this.R?4*(this.R-this.s):0;this.T=this.U=!1;this.O=this.aa=0;this.$=-1;var d=this;this.time=Q(this,
"Time");Nb(this.time,function(e,f){Ob(d,!1,e,f)});Pb(d)}u(Eb,O);function Pb(a){for(var b=a.g,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Jb?Qb:" ";e[f+1]=d.j==d.H?null:d.j;e[f+2]=0;e[f+3]=Rb}a.T=a.U=!0;Ob(a,!0)}function Sb(a){a.v?(a.h.fillStyle=a.v,a.h.fillRect(0,0,a.ca,a.N)):a.h.clearRect(0,0,a.ca,a.N)}
function Ob(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.T||b){if(a.type<Jb){d=0;if(!a.Y||b)Sb(a);else if(a.O){d=a.s-a.O;var e=a.m*d;a.h.drawImage(a.K,a.m*a.O,0,e,a.N,0,0,e,a.N)}for(var f=e=0;f<a.V;f++){for(var g=0;g<a.s;g++){var h=a.g[e],l=a.g[e+1]||a.H,k=a.sa&&e==a.$;if(a.g[e+3]&Rb||k||b){if(g>=d)a:{var m=a,n=h;h=l;var q=g;l=f;var v=k;q=void 0===q?0:q;l=void 0===l?0:l;v=void 0===v?!1:v;var z=0;if(m.ka&&!(l&1)&&(z=m.m>>1,q==m.s-1))break a;if(h&&h!=m.j){v=v?Lb(h,1,2):h;var w=
Lb(h,1,.25)}else v=v?m.la:m.j,w=m.ma;h=!1;n=n?v:w;v==m.H&&(n=m.v,h=!0);v=q*m.m+z;w=l*m.I;m.Y&&(q=q*m.m+z,l*=m.I,m.v?(m.h.fillStyle=m.v,m.h.fillRect(q,l,m.m,m.I)):m.h.clearRect(q,l,m.m,m.I));m.h.fillStyle=n;l=Tb[m.type];3==l.length?(m.h.beginPath(),m.h.arc(v+l[0],w+l[1],l[2],0,2*Math.PI),h?(m.h.globalCompositeOperation="destination-out",m.h.fill(),m.h.globalCompositeOperation="source-over"):m.h.fill()):m.h.fillRect(v+l[0],w+l[1],l[2],l[3])}a.g[e+3]=k?a.g[e+3]|Rb:a.g[e+3]&~Rb}e+=4}e+=a.Ka}a.O=0}else{b=
"";for(d=0;d<a.g.length;d+=4)b+=a.g[d]||" ",a.g[d+3]&Ub&&(b+=".");Sb(a);for(f=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;g=a;k=e;m=f;k=void 0===k?0:k;m=void 0===m?0:m;if(l=Vb[l])for(h=0;h<l.length;h++)if(q=g,z=Wb[l[h]]){n=(void 0===k?0:k)*q.m;v=(void 0===m?0:m)*q.I;q.h.fillStyle=q.j;q.h.beginPath();if(3==z.length)q.h.arc(n+z[0],v+z[1],z[2],0,2*Math.PI);else for(w=0;w<z.length;w+=2)w?q.h.lineTo(n+z[w],v+z[w+1]):q.h.moveTo(n+z[w],v+z[w+1]);q.h.closePath();q.h.fill()}if(++e==a.s&&(e=0,++f==a.V))break}}a.ia.globalCompositeOperation=
a.v&&a.j!=a.H?"source-over":"copy";a.ia.drawImage(a.K,0,0,a.ca,a.N,0,0,a.ea,a.Z);a.T=!1;a.$=-1}else a.Y||a.U||(!c||!a.aa||c-a.aa>=(1E3/d|0))&&Pb(a);a.U=!1;c&&(a.aa=c)}function Mb(a){return(a=a||void 0)&&cb[a]||a}
function Lb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=cb[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Eb.prototype.oa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.j&&c==this.v&&a&&a.length==this.g.length){this.g=a;for(b=0;b<=this.g.length-4;b+=4)this.g[b+1]==this.H&&(this.g[b+1]=null);Ob(this,!0);return!0}return!1};Eb.prototype.ra=function(a){this.g&&(a.push(this.j),a.push(this.v),a.push(this.g))};
function Xb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&Yb;b=4*(c*a.R+b);if(b<=a.g.length-4){if(a.g[b]!==d||(a.g[b+3]&Yb)!==e)a.g[b]=d,a.g[b+3]=a.g[b+3]&~Yb|e|Rb,a.T=f=!0;a.$=b;a.U=!0;a.O=0}return f}
var Ib=0,Gb=1,Jb=3,Hb={small:Ib,round:Gb,square:2,digit:Jb},Fb="container",Qb=0,Yb=129,Ub=1,Rb=128,Zb={},Tb=(Zb[Ib]=[4,4,4],Zb[Gb]=[16,16,14],Zb[2]=[2,2,28,28],Zb),Kb=[[8,8],[32,32],[32,32],[96,128]],Wb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Vb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};D.LED=Eb;
function $b(a,b,c){O.call(this,a,b,c);this.na=H(this,"cyclesMinimum",1E5);this.Xa=H(this,"cyclesMaximum",1E9);this.sa=Ma(H(this,"cyclesPerSecond",1E6),this.na,this.Xa);this.aa=60;this.ca=0;this.V=1E3/this.aa;this.Uc=H(this,"updatesPerSecond",2)||2;this.Lc=1E3/this.Uc;this.Ka=0;this.cd=H(this,"timeLock",!0);this.la=this.R=0;this.ka=this.H=1;this.wa=this.K=this.sa/1E4/100;this.ea=[];this.N=[];this.h=[];this.ia=[];this.va=this.g=this.ba=this.I=!1;this.O=this.m=0;a=Ha("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.V}this.Fb=window[a].bind(window,this.od.bind(this),d);this.Kc=window[Ha("cancelAnimationFrame")||"clearTimeout"].bind(window);this.$=this.Z=this.s=this.j=this.ma=0;ac(this)||bc(this,this.ka)}u($b,O);function Nb(a,b){a.ea.push(b)}p=$b.prototype;
p.Ba=function(a,b){var c=this;switch(a){case cc:b.onclick=function(){dc(c)&&(c.g?U(c):c.start())};break;case ec:b.onclick=function(){bc(c,c.H<<1);fc(c,gc(c.K))};break;case hc:b.onclick=function(){ic(c)};break;case jc:b.addEventListener("mousedown",function(){c.I=!0}),b.addEventListener("mouseup",function(){ac(c);c.I=!1}),b.addEventListener("mousemove",function(){c.I&&ac(c)}),b.addEventListener("change",function(){c.I=!0;ac(c);c.I=!1})}O.prototype.Ba.call(this,a,b)};
function qb(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,ed:c,Pa:d,ga:-1});0<=d&&vb(a,e,d);return e}
function kc(a,b,c,d){var e=0,f=a.K,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.u(B.za,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.V&&(1<a.H&&(a.H>>=1,a.u(B.$a,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.V,a.H)),e=d));a.R=f;a.la=f/a.wa;b=a.la/a.H;a.ma=g/b/a.aa+1E-8;a.u(B.za,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.ma,g,b,a.aa);return e}
function lc(a,b){a.Z=a.s=b;if(!a.N.length)return a.s=0,a.Z;for(var c=0;0<a.s;){if(c<a.N.length){var d=a.N[c++];b=d.pd.call(d,b)||1}else c=b=0;a.s-=b}return a.Z-a.s}function mc(a,b){var c=Date.now();b()&&(a.Y+=Date.now()-c)}function nc(a,b){b=void 0===b?a.Z-a.s:b;if(!a.g){if(a.j)for(var c=0;c<a.N.length;c++){var d=a.N[c];d.Wb.call(d)}a.j=b}a.j-=b;1>a.j&&(a.ba=!0);a.$+=b;a.Z=a.s=0;a.g||(a.$=0);return b}
function oc(a,b){b=void 0===b?0:b;if(b){var c=b;a.j+=b}else for(c=a.j,1>c&&(c=a.j+=a.ma),0>c&&(a.u(B.za,"warning: cycle count dropped below zero: %f\n",c),c=a.j=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.ga)&&c>d.ga&&(c=d.ga)}return c}function gc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function dc(a){return a.va?!0:(a.u("not powered\n"),!1)}
function pc(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.ga||(d.ga-=b,0>=d.ga&&(d.ga=-1,d.ed(),0<=d.Pa&&vb(a,c,d.Pa)))}}p.ha=function(a){this.va=a;void 0===this.pa&&(this.pa=Q(this,"Debugger",!1))};function ic(a,b){dc(a)&&(a.g?a.u("already running\n"):a.m?U(a):qc(a,b))}
p.od=function(a){a=void 0===a?Date.now():a;this.O=0;if(this.g){if(this.ca){var b=a-this.ca;1>b&&(b=16.67);this.aa=1E3/b}this.ca=a;a=Date.now();this.T&&(b=a-this.U-this.V,b>this.V&&(this.v+=b,this.u(B.$a,"warning: browser throttling detected, compensating by %5.3fms\n",b)));this.U=a;this.v||(this.v=a);this.Y=0;try{this.ba=!1;do pc(this,nc(this,lc(this,oc(this))));while(this.g&&!this.ba)}catch(c){this.u("%s\n",c.message),U(this)}this.T=Date.now();this.Y&&(this.v+=this.Y,this.U+=this.Y);this.U+=kc(this,
this.$,this.T-this.v,this.T-this.U);this.T-this.Ka>=this.Lc&&this.update();for(a=0;a<this.ea.length;a++)this.ea[a](this.ca,this.aa);this.O=this.Fb()}};function bc(a,b){if(void 0!==b){if(1>b||!a.I&&0<a.R&&a.R<.9*a.K)b=a.ka;a.H=b;b=a.wa*a.H;a.K!=b&&(a.K=b,fc(a,gc(a.K)))}a.v=a.T=0;a.j=a.$=0;kc(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.Pa&&vb(a,b,c.Pa,!0)}}function ac(a){var b=a.S[jc];return b?(bc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Xa-a.na)+a.na)/a.sa|0),!0):!1}
function vb(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.ga)&&(c=Math.ceil(a.sa*(a.cd?a.ka:a.la)/1E3*(void 0===c?1E3:c)),a.g&&(c+=nc(a)),b.ga=c)}p.start=function(){if(this.g||this.m)return!1;this.g=!0;this.v=this.T=0;this.update(!0);this.O=this.Fb();return!0};function qc(a,b){b=void 0===b?1:b;a.g||(b&&!a.m&&(a.m=b),a.m&&(a.m--,pc(a,nc(a,lc(a,oc(a,1)))),a.update(!1),a.m&&setTimeout(function(){qc(a,0)},0)))}
function U(a){return a.g?(a.g=!1,nc(a),a.O&&(a.Kc(a.O),a.O=0),a.update(!0),!0):a.m?(a.m=0,a.update(!0),!0):!1}p.update=function(a){a&&this.u(this.g?"started with %s target\n":"stopped\n",gc(this.K));M(this,cc,this.g?"Halt":"Run");M(this,hc,this.m?"Stop":"Step");this.I||(this.u(B.za,"getSpeedCurrent(%5.3fhz)\n",1E6*this.R),fc(this,this.g&&this.R?gc(this.R):"Stopped"));for(var b=0;b<this.ia.length;b++){var c=this.ia[b];c.md.call(c,void 0!=a)}this.Ka=Date.now();this.ba=!0};
function fc(a,b){M(a,rc,b);M(a,ec,b)}var cc="run",ec="setSpeed",rc="speed",hc="step",jc="throttle";D.Time=$b;
function sc(a,b,c){O.call(this,a,b,c);this.type="static"==this.J.type?tc:uc;this.v=this.J.addrWidth||16;this.j=Math.pow(2,this.v);this.I=this.j-1|0;this.blockSize=this.J.blockSize||(16<this.v?4096:1024);this.blockSize>this.j&&(this.blockSize=this.j);this.K=this.j/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.m=(1<<this.h)-1;this.H=this.J.dataWidth||8;this.g=Array(this.K);this.s=0;a=new V(a,b+"[NONE]",{size:this.blockSize,bus:this.X});for(b=0;b<this.j;b+=this.blockSize)vc(this,b,this.blockSize,
W.NONE,a);a=this.s;this.s+=this.type;a&&this.s||(this.Fa=this.yc,this.Ga=this.Ha)}u(sc,O);
function vc(a,b,c,d,e){for(var f=b>>>a.h;0<c&&f<a.g.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var l=a.g[f];if(b!=g||h!=a.blockSize||l&&l.type!=W.NONE)break;var k=l=void 0,m=b,n=a.v,q=16;n=void 0===n?0:n;l=void 0===l?0:l;var v="",z="",w=-1;q||(q=a.N||10);n&&(w=Math.ceil(n/Math.log2(q)));if(void 0==k)switch(q){case 8:k="0o";break;case 16:k="0x";break;case 10:z=".";default:k=""}isNaN(m)||"number"!=typeof m?(m=void 0,k=z=""):(0>m&&-1<m&&(m=-1),n&&(0>m&&(m+=Math.pow(2,n)),m>=Math.pow(2,
n)&&(w=Math.ceil(Math.log(m)/Math.log(q)))));for(n=l||-1;w--;){n||(v=","+v,n=l);if(void 0==m){if(v="?"+v,0>w)break}else{var A=m%q;m=Math.trunc(m/q);A+=0<=A&&9>=A?48:55;v=String.fromCharCode(A)+v;if(!m&&0>w)break}n--}l=a.X+"["+(k+v+z)+"]";b=e?e.size==a.blockSize?e:new V(a.M,l,{type:d,Ma:b,size:h,bus:a.X}):new V(a.M,l,{type:d,Ma:b,size:h,bus:a.X});a.g[f]=b;b=g+a.blockSize;c-=h;f++}}p=sc.prototype;p.ha=function(){void 0===this.pa&&(this.pa=Q(this,"Debugger",!1))};p.qa=function(){};
p.bb=function(a){return a&&this.oa(a)?!0:!1};p.cb=function(a){this.ra(a)};p.oa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==uc||c.type&W.La)&&c.oa){var d=a.shift();if(!c.oa(d))return!1}}return!0};p.ra=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==uc||c.type&W.La)&&c.ra){var d=[];c.ra(d);a.push(d)}}};p.xa=function(a){return this.g[a>>>this.h].xa(a&this.m)};p.yc=function(a){return this.g[a>>>this.h].Fa(a&this.m)};
p.eb=function(a,b){this.g[a>>>this.h].eb(a&this.m,b)};p.Ha=function(a,b){this.g[a>>>this.h].Ga(a&this.m,b)};var tc=0,uc=1;D.Bus=sc;
function V(a,b,c){O.call(this,a,b,c);this.Ma=this.J.addr;this.size=this.J.size;this.type=this.J.type||W.NONE;this.m=(a=this.J.bus)?P(this,a):Q(this,a="Bus");if(!this.m)throw Error(this.W("unable to find bus '%s'",a));this.v=this.m.H;this.K=Math.pow(2,this.v)-1;this.s=this.I=!1;this.values=this.j=null;a=this.ub;b=this.Ha;if(this.m.type==tc){b=this.qd;if(c=8==this.v)c=P(this,this.M),c=!1!==(c&&c.J&&c.J.ArrayBuffer||this.J.ArrayBuffer);c&&(this.I=!0)}switch(this.type){case W.NONE:this.Fa=this.nd;this.Ga=
this.Xb;break;case W.Hb:this.Fa=a;this.Ga=this.Xb;break;case W.La:this.Fa=a,this.Ga=b}wc(this,this.J.values);xc(this)}u(V,O);function wc(a,b){"string"==typeof b?(gb(a,!1),Na(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);wc(a,g.values)}catch(h){a.u("error (%s) parsing resource: %s\n",h.message,c)}gb(a,!0)}else a.u("error (%d) loading resource: %s\n",f,c)})):a.J.values=b}
function xc(a,b){if(a.type>W.NONE&&(a.I?(a.j=new ArrayBuffer(a.size),new DataView(a.j,0,a.size),a.values=new Uint8Array(a.j,0,a.size),new Uint16Array(a.j,0,a.size>>1),new Int32Array(a.j,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}p=V.prototype;
p.qa=function(){if(this.J.values)a:{var a=this.m,b=this.Ma,c=this.size,d=this.J.values,e=0,f=b&a.m;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var g=a.g[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Ha(f++,d[e++]),c--;f=0}}else this.type&W.La&&this.values&&this.values.fill(0)};p.nd=function(){return this.K};p.xa=function(a){return this.values?this.values[a]:0};p.ub=function(a){return this.values[a]};p.Xb=function(){};p.eb=function(a,b){this.values&&(this.values[a]=b)};
p.Ha=function(a,b){this.values[a]=b};p.qd=function(a,b){this.values[a]=b;this.s=!0;this.Ga=this.Ha};p.oa=function(a){if(a){var b=a.shift();if(this.X==b){this.s=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}xc(this,a)}return!0}}return!1};
p.ra=function(a){a.push(this.X);a.push(this.s);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var W={NONE:1,Hb:2,La:4,Fe:14,Je:12};D.Memory=V;
function yc(a,b,c){c.type=W.Hb;V.call(this,a,b,c);vc(this.m,this.J.addr,this.J.size,this.J.type,this);hb(this,this.qa.bind(this));this.da=this.pa=void 0;if(D.LED&&this.S[zc]){var d=this;this.h=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.H=this.values.length/this.h|0;this.g=new Eb(a,b+"LEDs",{"class":"LED",bindings:{container:Ja(this,zc)},type:Gb,cols:this.h,rows:this.H,color:H(this,"colorROM","green"),backgroundColor:H(this,"backgroundColorROM","black"),persistent:!0}),Pb(this.g);
this.N=new jb(a,b+"Input",{"class":"Input",location:[0,0,this.g.ea,this.g.Z,this.h,this.H],bindings:{surface:Ja(this,zc)}});this.O=Ka(this)||"";mb(this.N,function(e,f){if(d.da){var g=d.O;0<=e&&0<=f&&(e=f*d.h+e,g=Ac(d.da,d.Ma+e,d.values[e]));M(d,La,g)}})}}u(yc,V);
yc.prototype.oa=function(a){var b=!0,c=a.shift();if(c&&this.g){var d=c.length;this.g.g.length==d?(this.g.g=c,Ob(this.g,!0)):(this.u("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.u("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};yc.prototype.ha=function(){void 0===this.da&&(this.da=Q(this,"CPU"));void 0===this.pa&&(this.pa=Q(this,"Debugger",!1))};
yc.prototype.ub=function(a){this.g&&Xb(this.g,a%this.h,a/this.h|0,1,Rb);return this.values[a]};yc.prototype.ra=function(a){this.g&&(a.push(this.g.g),a.push(this.values))};var zc="array",La="cellDesc";D.ROM=yc;function Bc(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.pa=void 0;this.h=this.Ra=0;this.time=Q(this,"Time");this.time.N.push(this);this.time.ia.push(this);this.Z=this.v=0}u(Bc,O);p=Bc.prototype;p.abort=function(a){this.h=this.Ra;this.u("%s\n",a.message);U(this.time)};p.Sb=function(){};
p.pd=function(a){this.Z=this.v=a=void 0===a?0:a;try{this.Sb(a)}catch(b){this.abort(b)}return this.Ub()};p.Wb=function(){this.Z-=this.v;this.v=0};p.Ub=function(){return this.Z-this.v};function X(a,b,c){O.call(this,a.M,b);this.da=a;this.name=b;this.l=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.ma[c]=[this,-1];for(var d=0;d<this.l.length;d++)c=this.W("reg%s-%02d",this.name,d),b.push(c),a.ma[c]=[this,d];Ga(a,b)}}u(X,O);p=X.prototype;
p.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]+b.l[f]+e,e=0,this.l[f]>=d&&(this.l[f]-=d,e=1);e&&(this.da.H=!0);Cc(this,c)};p.get=function(){return this.l};function Dc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.l.length;d++)a.l[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.l[d]=b&15,b>>>=4;return a}p.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.l[e]=a.l[e]+d,d=0,this.l[e]>=c&&(this.l[e]-=c,d=1);Cc(a,b)};
p.set=function(a){if(a&&a.length==this.l.length)for(var b=0;b<this.l.length;b++)this.l[b]=a[b]};p.store=function(a){for(var b=0,c=this.l.length;b<c;b++)this.l[b]=a.l[b]};p.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]-b.l[f]-e,e=0,0>this.l[f]&&(this.l[f]+=d,e=1);e&&(this.da.H=!0);Cc(this,c)};p.toString=function(a){a=void 0===a?!1:a;var b=this.X+"=";a&&3>b.length&&(b+=" ");for(var c=this.l.length-1;0<=c;c--)b=a?b+xa[this.l[c]]:b+(ya[this.l[c]]+(c%4?"":" "));return b};
function Cc(a,b){a.da.s=a.l[b[0]];b[0]<b[1]&&(a.da.s|=a.l[b[0]+1]<<4)}
function Ec(a,b,c){Bc.call(this,a,b,c);this.type=Number.parseInt(H(this,"type","1501").slice(-4),10);this.ma={};this.g=Array(4);for(a=0;4>a;a++)this.g[a]=new X(this,String.fromCharCode(65+a));this.U=this.g[0];this.$=this.g[1];this.sa=this.g[2];this.wa=this.g[3];this.R=Array(8);for(a=0;8>a;a++)this.R[a]=new X(this,"X"+a);this.V=Array(8);for(a=0;8>a;a++)this.V[a]=new X(this,"Y"+a);this.na=new X(this,"Supp",!0);this.ba=new X(this,"Temp",!0);this.O=10;this.H=!1;this.aa=this.s=this.K=0;this.m=[-1,-1,-1];
this.va=P(this,this.J.input);this.va.K=this.zc.bind(this);this.j=P(this,this.J.output,!1);this.N=Q(this,"Bus");this.I=Q(this,"ROM");this.ka=this.la=this.Y=void 0;this.ia=this.ca=-1;this.T={};this.ea=Fc;a=this.ld.bind(this);b=Ta.kb;this.L.Ja[b]||(this.L.Ja[b]=[]);this.L.Ja[b].push(a)}u(Ec,Bc);function Gc(a,b){a.T[b]&&(a.T[b]=!1,a.u("break on %s\n",Hc[b]),U(a.time))}function Ic(a){a.j&&Pb(a.j);if(a.I){var b=a.I;b.g&&Pb(b.g)}Jc(a,!1)}p=Ec.prototype;
p.Sb=function(a){for(;0<this.v;){if(this.ia==this.h){this.ia=-1;this.u("break\n");U(this.time);break}var b=this.N.Fa(this.h);this.h=(this.Ra=this.h)+1&this.N.I;if(void 0==b||!Kc(this,b)){this.h=this.Ra;this.u("unimplemented opcode\n");U(this.time);break}this.v-=Lc}if(0>=a){var c=this;mc(this.time,function(){var d=c.I;d.g&&Ob(d.g);c.ua(c.toString())})}};p.Wb=function(){this.v=0};p.Ub=function(){return this.Z-this.v};
function Kc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.H&&(a.h=a.h&1024|b&1023):(a.push(a.h),a.h=b&2047),a.H=!1,!0;var c;var d=b&Mc;switch(d){case Nc:case Oc:case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:d=Zc[d];var e=(b&$c)>>ad;var f=(b&bd)>>cd;var g=(b&dd)>>ed;var h=(c=b&fd)?gd:hd;b=b>=Uc?16:a.O;switch(f){case 0:case 1:case 2:case 3:var l=a.g[f];break;case 4:l=Dc(a.ba,1,d);break;case 5:h=c?id:jd;break;case 6:l=Dc(a.ba,a.s&15,d);break;case 7:l=Dc(a.ba,a.s&255,d)}switch(g){case 0:var k=
a.g[e];break;case 1:k=4>f?a.g[f]:void 0;break;case 2:k=5>f?a.na:5==f?a.g[e]:void 0;break;case 3:if(c)a.g[e].move(l,d,b);else{a=a.U;e=l;b=d[0];for(l=d[1];b<=l;b++)k=a.l[b],a.l[b]=e.l[b],e.l[b]=k;Cc(e,d)}return!0}if(!k)break;switch(h){case hd:k.add(a.g[e],l,d,b);break;case gd:k.sub(a.g[e],l,d,b);break;case jd:b=k;a=a.g[e];e=d[1];for(l=d[0];e>l;e--)b.l[e]=a.l[e-1];b.l[e]=0;Cc(b,d);break;case id:b=k;a=a.g[e];e=d[0];for(l=d[1];e<l;e++)b.l[e]=a.l[e+1];b.l[e]=0;Cc(b,d)}return!0;case kd:e=(b&ld)>>md;d=(b&
nd)>>od;l=1<<((b&pd)>>qd);if(!d)break;d+=12;switch(b&rd){case sd:a.g[e].l[d]|=l;break;case td:a.g[e].l[d]&=~l;break;case ud:a.g[e].l[d]&l&&(a.H=!0);break;case vd:a.g[e].l[d]^=l}return!0;case wd:switch(b&xd){case yd:a.U.store(a.V[a.K]);break;case zd:a.K=b>>4&7;break;case Ad:a.h=a.s;break;case Bd:a.H=!1;d=a.m[0];e=0;for(b=a.m.length-1;e<b;)a.m[e]=a.m[++e];a.m[e]=-1;a.h=d;break;case Cd:a.R[a.K].store(a.U);break;case Dd:a.U.store(a.R[a.K]);break;case Ed:a.V[a.K].store(a.U);break;case Fd:Gc(a,"o");if(a.j){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.$.l[e]&8?b=" ":a.$.l[e]&1?b="-":b=xa[a.U.l[e]],Xb(a.j,d,0,b,a.$.l[e]&2?Ub:0)&&Gc(a,"om");Jc(a)}a.v-=31*Lc;a.aa&&(a.s=a.aa,a.H=!0,Gc(a,"i"));break;case Gd:a.O=10;break;case Hd:a.O=16;break;case Id:a.K=a.s&7;break;default:return!1}return!0}return!1}
p.oa=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return this.u("invalid saved state\n"),!1;var c=b.shift();if(3!==(c|0))return this.u("saved state version mismatch: %3.2f\n",c),!1;try{this.g.forEach(function(d){return d.set(b.shift())}),this.R.forEach(function(d){return d.set(b.shift())}),this.V.forEach(function(d){return d.set(b.shift())}),this.na.set(b.shift()),this.ba.set(b.shift()),this.O=b.shift(),this.H=b.shift(),this.K=b.shift(),this.s=b.shift(),this.h=b.shift(),this.m=b.shift(),this.aa=
b.shift()}catch(d){return this.u("CPU state error: %s\n",d.message),!1}return(a=a.stateROM||a[1])&&this.I&&!this.I.oa(a)?!1:!0};
p.ld=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,h=3;h<a.length;h++)d.push(Number.parseInt(a[h],16));this.ea=Fc;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Hc)c=Hc[f],b+="break on "+c+" (b"+f+"): "+(this.T[f]||!1)+"\n";break}(c=Hc[f])?(this.T[f]=!this.T[f],b="break on "+c+" (b"+f+"): "+this.T[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.N.xa(f);if(void 0==
a)break;this.N.eb(f,d[g]);b+=this.W("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.W("%d locations updated\n",c);break;case "g":this.time.start()?this.ia=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.ea=Jd);g=Number.parseInt(a[2],10)||1;ic(this.time,g);break;case "r":"c"==e[1]&&(this.ea=Jd);this.Vb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.ca?this.ca:this.h;g--;){c=this.I&&this.N.xa(f);if(void 0==
c)break;b+=Ac(this,f++,c)}this.ca=f;break;case "?":b="additional commands:\n";Kd.forEach(function(l){b+=l+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};p.zc=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.aa=c};p.bb=function(a){return a&&this.oa(a)?!0:!1};p.ha=function(a){a?this.time.start():(U(this.time),Ic(this))};p.qa=function(){this.u("reset\n");this.h=0;Ic(this);this.time.g||this.ua(this.toString())};p.cb=function(a){this.ra(a)};
p.md=function(a){for(var b in this.S){var c=this.ma[b];if(c){var d=c[0];c=c[1];M(this,b,0>c?d.toString():xa[d.l[c]])}}a&&!this.time.g&&(a=this.I,a.g&&Ob(a.g),this.ua(this.toString()))};p.push=function(a){for(var b=this.m.length-1;0<b;)this.m[b]=this.m[--b];this.m[0]=a};
p.ra=function(a){var b=[],c=[];b.push(3);this.g.forEach(function(d){return b.push(d.get())});this.R.forEach(function(d){return b.push(d.get())});this.V.forEach(function(d){return b.push(d.get())});b.push(this.na.get());b.push(this.ba.get());b.push(this.O);b.push(this.H);b.push(this.K);b.push(this.s);b.push(this.h);b.push(this.m);b.push(this.aa);this.I&&this.I.ra(c);a.push(b);a.push(c)};p.Vb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.h=b;break;default:this.u("unrecognized register: %s\n",a)}};
function Ac(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.W("%#06x",f);else if(0<=c){var g=c&Mc;var h;switch(g){case Nc:case Oc:case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:f="";e=Zc[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&$c)>>ad;var l=(c&bd)>>cd;var k=(c&dd)>>ed;var m=c&fd;e="LOAD";var n=h="?";var q=m?5==l?">>":"-":5==l?"<<":"+";switch(k){case 0:h=
Y[g];break;case 1:4>l&&(h=Y[l]);break;case 2:6>l&&(h="NUL");break;case 3:m?(e="MOVE",h=Y[g],n=Y[l]):(e="XCHG",g||(h="A"),4>l&&(n=Y[l])),l=-1}switch(l){case 0:case 1:case 2:case 3:n=Y[g]+q+Y[l];break;case 4:case 5:n=Y[g]+q+"1";break;case 6:n=Y[g]+q+"R5L";break;case 7:n=Y[g]+q+"R5"}f=h+","+n+","+f;break;case kd:switch(c&rd){case sd:e="SET";break;case td:e="CLR";break;case ud:e="TST";break;case vd:e="NOT"}f=a.g[(c&ld)>>md].name;g=(c&nd)>>od;f+="["+(g?g+12:"?")+":"+((c&pd)>>qd)+"]";break;case wd:switch(c&
xd){case yd:e="STORE";f="A,Y[RAB]";break;case zd:e="STORE";f="RAB,"+((c&112)>>4);break;case Ad:e="BR";f="R5";break;case Bd:e="RET";break;case Cd:e="STORE";f="X[RAB],A";break;case Dd:e="STORE";f="A,X[RAB]";break;case Ed:e="STORE";f="Y[RAB],A";break;case Fd:e="DISP";break;case Gd:e="BCDS";break;case Hd:e="BCDR";break;case Id:e="STORE",f="RAB,R5L"}}}return a.W(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
p.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.ea){this.I&&(d+=Ac(this,this.h,this.N.xa(this.h),!0));d+="  ";b=0;for(a=this.g.length;b<a;b++)d+=this.g[b].toString()+" ";d+="\n ";d+=" COND="+(this.H?1:0);d+=" BASE="+this.O;d+=" R5="+this.W("%02X",this.s);d+=" RAB="+this.K+" ST=";this.m.forEach(function(f){d+=c.W("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.g);0<=a.indexOf("a")&&(d+=this.toString(a,this.R),d+=this.toString(a,this.V));d+="COND="+(this.H?1:0);d+=" BASE="+this.O;d+=" R5="+this.W("%#04x",this.s);d+=" RAB="+this.K+" ";this.m.forEach(function(f,g){d+=c.W("ST%d=%#06x ",g,f&65535)});this.I&&(d+="\n"+Ac(this,this.h,this.N.xa(this.h)));this.ca=this.h;return d};
function Jc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Ld?!!(a.sa.l[14]&8):!!(a.$.l[15]&4));if(a.ka!==d){if(c=a.S["2nd"])c.style.opacity=d?"1":"0",void 0===a.ka&&a.j&&(c.style.color=a.j.color);a.ka=d}d=b&&(a.type==Ld?!!(a.$.l[15]&4):!!(a.wa.l[15]&8));if(a.la!==d){if(c=a.S.INV)c.style.opacity=d?"1":"0",void 0===a.la&&a.j&&(c.style.color=a.j.color);a.la=d}c=a.type==Ld?a.R[4].l[15]>>2:a.sa.l[15];b=b?c?1==c?Md:Nd:Od:Pd;if(a.Y!==b){if(c=a.S.Deg)c.style.opacity=b==Od?"1":"0",void 0===a.Y&&a.j&&(c.style.color=
a.j.color);if(c=a.S.Rad)c.style.opacity=b==Md?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);if(c=a.S.Grad)c.style.opacity=b==Nd?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);a.Y=b}}
var Mc=3840,Nc=0,Oc=256,Pc=512,Qc=768,Rc=1024,Sc=1280,Tc=1792,Uc=2048,Vc=2304,Wc=2560,kd=3072,Xc=3328,wd=3584,Yc=3840,$c=192,ad=6,bd=56,cd=3,dd=6,ed=1,fd=1,rd=3,sd=0,td=1,ud=2,vd=3,ld=192,md=6,nd=48,od=4,pd=12,qd=2,xd=15,yd=0,zd=1,Ad=2,Bd=3,Cd=4,Dd=5,Ed=6,Fd=7,Gd=8,Hd=9,Id=10,Z={},Zc=(Z[Nc]=[12,12],Z[Oc]=[0,15],Z[Pc]=[2,12],Z[Qc]=[0,12],Z[Rc]=[2,2],Z[Sc]=[0,1],Z[Tc]=[0,13],Z[Uc]=[14,14],Z[Vc]=[13,15],Z[Wc]=[14,15],Z[Xc]=[13,13],Z[Yc]=[15,15],Z),Lc=128,hd=0,gd=1,jd=2,id=3,Ld=1501,Pd=0,Od=1,Md=2,Nd=
3,Hc={i:"input",o:"output",om:"output modification"},Fc=0,Jd=1,Y="A B C D 1 ? R5L R5".split(" "),Kd="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");D.CPU1500=Ec;
function Qd(a,b,c){O.call(this,a,a);var d=this;this.j=!1;this.H=c;this.h="";this.v=this.s=!1;gb(this,!1);this.fa=B.ic;b=b.trim();"{"==b[0]?Rd(this,b):(this.h=b,Na(this.h,function(e,f,g,h){4==g&&(!h&&f?(Rd(d,f),Sd(d)):d.u("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.v=!0;Sd(d)});window.addEventListener(Pa("iOS")?"pagehide":Pa("Opera")?"unload":"beforeunload",function(){Td(d)});window.addEventListener("pageshow",function(){d.j||d.ha(!0)})}u(Qd,O);
Qd.prototype.Ba=function(a,b){var c=this;switch(a){case Ud:b.onclick=function(){c.ha()};break;case Vd:b.onclick=function(){c.qa()}}O.prototype.Ba.call(this,a,b)};
function Sd(a){var b=!0;if(a.s&&a.v){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],D[d]?"Machine"==d?(a.u("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2023 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.u("Configuration: %s\n",a.h)):new D[d](a.M,c,e):a.u('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.u('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),ib(a,c)}}if(a.m){var f=Qa(a);eb(a,function(g){return g.bb&&!g.bb(f)?(g.u('unable to restore state for device "%s"\n',
g.X),!1):!0})}gb(a,!0);hb(a,a.ha.bind(a,b))||a.u("machine %s not ready to power, waiting for device(s)\n",a.M)}}
function Rd(a,b){try{a.g=JSON.parse(b);var c=a.g[a.M];if(!c){c=a.g[Aa(a.h)];if(!c)throw Error("configuration missing machine ID");a.g[a.M]=c}db(a,c,["autoSave","autoStart"]);a.m=!1!==a.J.autoSave;a.I=!1!==a.J.autoStart;if(a.H){var d=eval("("+a.H+")"),e;for(e in d)a.J[e]=d[e]}a.s=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.u("machine '%s' initialization error: %s\n",a.M,c)}}
Qd.prototype.ha=function(a){a=void 0===a?!this.j:a;if(fb(this)){var b=this;a&&this.u("power on\n");eb(this,function(c){c.ha&&c!=b&&("CPU"!=c.J["class"]||b.I&&fb(b)?c.ha(a):c.time.update(!0));return!0});(this.j=a)||this.u("power off\n")}};Qd.prototype.qa=function(){if(fb(this)){var a=this;eb(this,function(b){b.qa&&b!=a&&b.qa();return!0});this.u("reset\n")}};function Td(a){if(a.m){var b=[];eb(a,function(c){c.cb&&c.cb(b);return!0});Xa(a,b)}a.ha(!1)}var Ud="power",Vd="reset";
window.TMS1500=function(a,b,c){var d=new Qd(a,b,c);window.command=function(e){return Ra(d,e)};return d};D.Machine=Qd;})()

//# sourceMappingURL=ti42.js.map
