(function(){/*
 https://www.pcjs.org/modules/defs.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/numio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/stdio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/webio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/device.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/input.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/led.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/time.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/bus.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/memory.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/rom.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/cpu.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/cpu1500.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/machine.js (C) 2012-2020 Jeff Parsons
*/
var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function q(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={Xa:!0},fa={};try{fa.__proto__=ea;da=fa.Xa;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function r(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var ia="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ja(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var v=ja(this);function y(a,b){if(b){var c=v;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ia(c,a,{configurable:!0,writable:!0,value:b})}}
y("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});y("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});function ka(){ka=function(){};v.Symbol||(v.Symbol=la)}function ma(a,b){this.a=a;ia(this,"description",{configurable:!0,writable:!0,value:b})}ma.prototype.toString=function(){return this.a};
var la=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ma("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function na(){ka();var a=v.Symbol.iterator;a||(a=v.Symbol.iterator=v.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ia(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}});na=function(){}}function oa(a){na();a={next:a};a[v.Symbol.iterator]=function(){return this};return a}
function pa(a,b){na();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}y("Array.prototype.keys",function(a){return a?a:function(){return pa(this,function(b){return b})}});
y("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});y("Number.parseInt",function(a){return a||parseInt});y("Array.prototype.values",function(a){return a?a:function(){return pa(this,function(b,c){return c})}});function qa(){}var ra=new ArrayBuffer(2);(new DataView(ra)).setUint16(0,256,!0);new Uint16Array(ra);
var A={Vb:0xffffffffffff,NONE:0,ec:0,ta:0x800000000000},B={};B.Defs=qa;function sa(){}r(sa,qa);function ta(a,b){var c=a/C|0,d=b/C|0;return(a&b)==(b|0)&&(c&d)==d}function ua(a){for(var b=0,c=0,d=[];b<a.length;){for(var e=a[b],f=b+1;f<a.length&&a[f]===e;)f++;d[c++]=f-b;d[c++]=e;b=f}return d.length>=a.length?a:d}var C=Math.pow(2,32);B.NumIO=sa;function F(){this.Da={};for(var a=0;22>a;a++)this.Da["ACDFHIMNSTWYbdfjcsoXx%"[a]]=null}r(F,sa);p=F.prototype;p.flush=function(){var a=va;va="";this.na(a)};
function wa(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}p.dd=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,q(b)))};
p.na=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),xa||(xa=b),a=((b-xa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(va+a.substr(0,c)),va="",a=a.substr(c+1)),xa=null);va+=a;return a.length};function G(a,b,c){a.na(b+"\n",c)}p.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.na(this.L.apply(this,[a].concat(q(c))))};
p.L=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(!c||!c.length)return a;d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var k=e[g+5];if(void 0===this.Da[k])d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+k;else{if(f<c.length){var h=c[f];"%"!=k&&f++}else h=c[c.length-1];var m=e[g+1],l=0<=m.indexOf("#"),t=0<=m.indexOf("0"),n=e[g+2];"*"==n?(n=h,h=f<c.length?c[f++]:c[c.length-1]):n=+n||0;var u=e[g+3];u=u?+u.substr(1):
-1;var z=e[g+4],x=null,E=0,D="";var w=0<="ACDFHIMNSTWY".indexOf(k)&&"object"!=typeof h?this.dd(h):h;switch(k){case "C":h=l?"#":"";d+=isNaN(w.getTime())?void 0:this.L(this.L("%%%sW, %%%sF %%%sD, %%%sY",h),w);continue;case "D":h=l?w.getUTCDate():w.getDate();k="d";break;case "A":case "H":case "I":h=l?w.getUTCHours():w.getHours();"A"==k?(h=12>h?"am":"pm",k="s"):("I"==k&&(h=h?12<h?h-12:h:12),k="d");break;case "F":case "M":h=l?w.getUTCMonth():w.getMonth();"F"==k?(h=ya[h],k="s"):(h++,k="d");break;case "N":h=
l?w.getUTCMinutes():w.getMinutes();k="d";break;case "S":h=l?w.getUTCSeconds():w.getSeconds();k="d";break;case "T":h=l?"#":"";d+=isNaN(w.getTime())?void 0:this.L(this.L("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),w);continue;case "W":h=za[l?w.getUTCDay():w.getDay()];k="s";break;case "Y":h=l?w.getUTCFullYear():w.getFullYear(),0<u&&(h%=Math.pow(10,u),u=-1),k="d"}switch(k){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=u&&(t=!0,n<u&&(n=u),u=-1);case "f":h=+h;w=h+"";0<=u&&(w=h.toFixed(u));
w.length<n&&(t?(0>h&&(n--,w=w.substr(1)),w=("0000000000"+w).slice(-n),0>h&&(w="-"+w)):w=("          "+w).slice(-n));d+=w;break;case "j":d+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=u&&(h=h.substr(0,u));h.length<n;)h=0<=m.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":E=8,l&&(D="0");case "X":x=Aa;case "x":w="";E||(E=16);!D&&l&&(D="0x");x||(x=Ba);h=Math.trunc(h);0<=u&&(t=!0,n<u&&(n=
u));t&&!n&&("b"==z?n=2:"h"==z||"w"==z?n=4:"l"==z?n=8:(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9),n+=D.length);n-=D.length;do l=h&E-1,h>>>=16==E?4:3,t||!w||l||h?w=x[l]+w:(D&&(w=D+w,D=""),0<n&&(w=" "+w));while(0<--n||h);d+=D+w;break;case "%":d+="%";break;default:this.Da[k]?d+=this.Da[k](k,m,n,u,h):d+="(unimplemented sprintf type: %"+k+")"}}}return d+=e[g]};
var va="",xa=null,Ba="0123456789abcdef",Aa="0123456789ABCDEF",za="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ya="January February March April May June July August September October November December".split(" ");B.StdIO=F;function H(a){F.call(this);this.M={};this.aa=0;this.J=this;a&&(this.J.aa=0,this.J.oa=[],this.J.ea=0,this.J.Ea={},this.J.ze=!1)}var Ca;r(H,F);p=H.prototype;
p.va=function(a,b){var c=this,d=this;switch(a){case Da.$b:b.onclick=function(){var e=c.xa(Da.Ua,!0);e&&(e.value="")};break;case Da.Ua:Ea(b),b.addEventListener("keydown",function(e){Fa(d,e,!0)}),b.addEventListener("keypress",function(e){Fa(d,e)})}};
function Ga(a,b){b=void 0===b?{}:b;if("undefined"!=typeof document){a.s.M||(a.s.M=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.V);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.M[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.M[d].push(e)}while(1);continue}if(f=document.getElementById(e))a.M[d]=f,a.va(d,f)}}}
function Ea(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}p.error=function(a,b){b=this.L.apply(this,[a].concat(q(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.L.apply(this,[c].concat(q(b))))G(this,b),a||alert(b)};p.xa=function(a){return this.M[a]};
function Ha(a){var b=window;if(b){do{for(var c=0;c<Ia.length;c++){var d=Ia[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ja(a,b){return a.s.bindings&&a.s.bindings[b]}function Ka(a){if(a=a.M[La])var b=a.textContent;return b}function Ma(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function I(a,b,c,d){a=a.s[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Na(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Oa(a){if(void 0===J.Sa){var b=!1;if(window)try{window.localStorage.setItem(J.ua,J.ua),b=window.localStorage.getItem(J.ua)==J.ua,window.localStorage.removeItem(J.ua)}catch(c){G(a,c.message),b=!1}J.Sa=b}return!!J.Sa}function K(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.aa;return-1==(b|1)||ta(a.J.aa,b)?!0:!1}
function Pa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Qa(a){var b=null;if(Oa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.I))&&(b=JSON.parse(c))}catch(d){G(a,d.message)}}return b}
function Fa(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.J,f=b.target;if(c){a=!1;var g;c=f.value;var k=c.lastIndexOf("\n");d==L.cb&&f.selectionStart<=k+1&&(a=!0);d==L.Uc?(a=!0,0<e.ea&&(g=e.oa[--e.ea])):d==L.gc&&(a=!0,e.ea<e.oa.length&&(g=e.oa[++e.ea]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,k+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ea&&c+1==g.length&&
(f.value+=e.oa[--e.ea],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ra(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&G(a,b.replace(/\n$/,""),!1))}}
function Sa(a,b){if(void 0!=b){var c=a.J;try{if(b=b.trim())c.ea<c.oa.length&&b==c.oa[c.ea]?c.ea++:(c.oa.push(b),c.ea=c.oa.length);var d=b.split(" "),e=d[0],f=a.J.Ea[Ta.gb];switch(e[0]){case "m":if("?"==e[1]){var g="";Ua.forEach(function(t){g+=t+"\n"});g&&(g="message commands:\n"+g);break}g="";var k=void 0;e=d[d.length-1].toLowerCase();var h="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=h&&d.pop();1>=d.length&&(void 0!=h&&(k=h,h=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(M));for(f=
1;f<d.length;f++){e=d[f];var m=M[e];if(!m){g+="unrecognized message: "+e+"\n";break}void 0!=h&&Va(a,m,h);if(void 0==k||k==K(a,m))g+=a.L("%8s: %b\n",e,K(a,m))}K(a,A.ta)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Wa.forEach(function(t){g+=t+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var l=f[a](d);if(void 0!=l){g=g?g+l:l;break}}}}catch(t){g="error: "+t.message+"\n"}}return g}
function Ra(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Sa(a,b[d])}return c}p.na=function(a,b){void 0==b&&(b=K(this,A.ta));if(!b){var c=this.xa(Da.Ua,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Pa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return F.prototype.na.call(this,a,b)};
p.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return K(this,d)?F.prototype.w.call.apply(F.prototype.w,[this,a].concat(q(c))):0};function Xa(a,b){if(Oa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.I,b)}catch(c){G(a,c.message)}}}function Ya(a,b,c){(a=a.M[b])&&a.textContent!=c&&(a.textContent=c)}
function Va(a,b,c){var d=!1;c?(c=a.J.aa,a.J.aa=(c|b)+(c/C|0|b/C|0)*C):(d=ta(a.J.aa,A.ta)&&ta(b,A.ta),c=a.J.aa,a.J.aa=(c&~b)+((c/C|0)&~(b/C|0))*C);d&&a.flush()}
var Da={$b:"clear",Ua:"print"},Wa=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Ua=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],M={all:A.Vb,buffer:A.ta},Ta={gb:"command"},Za={hb:13,Ra:65,bb:66,eb:67,ib:68,E:69,kb:70,lb:71,mb:72,nb:73,qb:74,rb:75,tb:76,vb:77,xb:78,zb:79,Ab:80,Q:81,Bb:82,Db:83,Eb:84,
Fb:85,Gb:86,Hb:87,Ib:88,Jb:89,Wa:90,Xa:97,Ce:98,De:99,d:100,e:101,He:102,Ie:103,Ke:104,Le:105,Me:106,k:107,Ne:108,Oe:109,n:110,Pe:111,p:112,q:113,r:114,Qe:115,t:116,Re:117,Se:118,Te:119,x:120,y:121,z:122},L={cb:8,Oc:9,tc:10,hb:13,Lc:16,cc:17,Wb:18,pe:19,Ta:20,rd:27,Nc:32,se:33,re:34,qd:35,Md:36,ub:37,Uc:38,Va:39,Jd:39,gc:40,Gd:44,te:44,Nd:45,pd:46,Id:46,Ld:47,ZERO:48,ONE:49,Tc:50,Pc:51,qc:52,pc:53,Mc:54,Kc:55,hc:56,zc:57,nc:59,mc:61,Ra:65,bb:66,eb:67,ib:68,E:69,kb:70,lb:71,mb:72,nb:73,qb:74,rb:75,
tb:76,vb:77,xb:78,zb:79,Ab:80,Q:81,Bb:82,Db:83,Eb:84,Fb:85,Gb:86,Hb:87,Ib:88,Jb:89,Wa:90,fb:91,Hd:91,Fd:92,we:93,Kd:93,Rd:96,he:96,Ed:96,Sd:97,fe:97,Td:98,ee:98,Ud:99,ke:99,Vd:100,ie:100,Wd:101,be:101,Xd:102,me:102,Yd:103,ge:103,Zd:104,oe:104,$d:105,le:105,je:106,ae:107,ne:109,ce:110,de:111,sd:112,wd:113,xd:114,yd:115,zd:116,Ad:117,Bd:118,Cd:119,Dd:120,td:121,ud:122,vd:123,Ac:144,Hc:145,lc:173,Ic:186,ic:187,nd:188,dc:189,qe:190,ye:191,ld:192,Od:219,md:220,ve:221,ue:222,kc:224,Pd:901,Ae:1E3},$a={},
ab=($a[L.nc]=L.Ic,$a[L.mc]=L.ic,$a[L.lc]=L.dc,$a[L.kc]=L.fb,$a),bb={ub:1,Va:2,Qd:3},N={},cb=(N[L.cb]="\b",N[L.Oc]="\t",N[L.tc]="\n",N[L.hb]="\r",N[L.Nc]=" ",N[L.ZERO]="0",N[L.ONE]="1",N[L.Tc]="2",N[L.Pc]="3",N[L.qc]="4",N[L.pc]="5",N[L.Mc]="6",N[L.Kc]="7",N[L.hc]="8",N[L.zc]="9",N[L.Ra]="A",N[L.bb]="B",N[L.eb]="C",N[L.ib]="D",N[L.E]="E",N[L.kb]="F",N[L.lb]="G",N[L.mb]="H",N[L.nb]="I",N[L.qb]="J",N[L.rb]="K",N[L.tb]="L",N[L.vb]="M",N[L.xb]="N",N[L.zb]="O",N[L.Ab]="P",N[L.Q]="Q",N[L.Bb]="R",N[L.Db]=
"S",N[L.Eb]="T",N[L.Fb]="U",N[L.Gb]="V",N[L.Hb]="W",N[L.Ib]="X",N[L.Jb]="Y",N[L.Wa]="Z",N[L.ub]="Left",N[L.Va]="Right",N),Ia=["","moz","ms","webkit"],db={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},J={Sa:void 0,ua:"PCjs.localStorage"};B.WebIO=H;
function O(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?"default":b;c=void 0===c?{}:c;d=void 0===d?[]:d;H.call(this,a==b);this.I=a;this.V=b;P[this.I]||(P[this.I]={});P[this.I][this.V]&&this.w("warning: machine configuration contains multiple '%s' devices\n",this.V);P[this.I][this.V]=this;this.id=this.I+"."+this.V;eb.push(this);this.J=fb(this,this.I);this.ready=!0;gb(this,c,d);this.Ec={};this.pb=[]}r(O,H);
function gb(a,b,c){c=b.overrides||c;if(c.length){var d,e=Ca;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,k=/([^&=]+)=?([^&]*)/g;f=k.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ca=e}d=e;for(var h in d)if(0<=c.indexOf(h)){e=d[h];f=void 0;var m;g=void 0;k=e;var l=10;if(k){l||(l=10);var t=0<k.indexOf(",");t&&(k=k.replace(/,/g,""));var n=m=k.charAt(0);"#"==m?(l=8,m=""):"$"==m&&(l=16,m="");n!=m?k=k.substr(1):
(n=m=k.substr(0,2),"0b"==m&&t||"^B"==m?(l=2,m=""):"0o"==m||"^O"==m?(l=8,m=""):"^D"==m?(l=10,m=""):"0x"==m&&(l=16,m=""),n!=m&&(k=k.substr(2)));n=m=k.slice(-1);"Y"==m||"y"==m?(l=2,m=""):"."==m?(l=10,m=""):"H"==m||"h"==m?(l=16,m=""):"K"==m?m="000":"M"==m?m="000000":"G"==m&&(m="000000000");n!=m&&(k=k.slice(0,-1)+m);n=0;10>=l&&(m=k.match(/(-?[0-9]+)B([0-9]*)$/))&&(k=m[1],n=35-((m[2]||35)&255));(l&&10!=l?16==l?null===k.match(/^-?[0-9a-f]+$/i):8==l?null===k.match(/^-?[0-7]+$/):2!=l||null===k.match(/^-?[01]+$/):
null===k.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(k,l))||(n&&(0>f&&(f+=Math.pow(2,36)),f=0<n?f*Math.pow(2,n):Math.trunc(f/Math.pow(2,-n))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[h]=f;G(a,"overriding "+a.V+" property '"+h+"' with "+e)}}a.s=b;Ga(a,b.bindings);b=void 0===b?{}:b;a.version=2;if(a.version){c="";var u;a.I!=a.V&&(u=fb(a,a.I).version)&&u!=a.version&&(c="Machine");c||(u=b.version)&&u>a.version&&(c="Config");c&&(u=a.L("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.Ee,a.version,c,u),a.error("%s\n\nClearing your browser's cache may resolve the issue.",u))}}function hb(a,b){var c;try{var d=P[a.I];if(d)for(c in d){var e=d[c];if(e.V!=e.I&&!b(e))return!1}return!0}catch(f){a.w("error while enumerating device '%s': %s\n",c,f.message)}return!1}O.prototype.xa=function(a,b){b=void 0===b?!1:b;if(a){var c=H.prototype.xa.call(this,a,b);if(void 0===c&&b){b=P[this.I];for(var d in b)if(c=b[d].M[a])break;c||(c=null);this.M[a]=c}}return c};
function fb(a,b,c){var d=b,e=a.I,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=P[e])&&f[b]||null;if(!b){for(f=0;f<eb.length;f++)if(eb[f].id===d){b=eb[f];break}if(!b&&(void 0===c||c))throw Error(a.L('no "%s" device',d));}return b}function Q(a,b,c){var d=null,e=P[a.I];if(e)for(var f in e)if(e[f].s["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.L("no %s device",b));return d}function ib(a){return a==a.J&&a.ready?hb(a,function(b){return ib(b)}):a.ready}
function jb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(ib(a)){for(;b=a.pb.pop();)b();a!=a.J&&jb(a.J)}}function kb(a,b){if(ib(a))return b(),!0;a.pb.push(b);return!1}
O.prototype.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&K(this,a)&&(void 0===this.ja&&(this.ja=Q(this,"Debugger",!1)),this.J.aa&A.ab&&(void 0===this.Y&&(this.Y=Q(this,"CPU")),this.Y))?(a=c.shift(),H.prototype.w.call(this,"%#06x: %s.%s\n",this.Y.Oa,this.V,this.L.apply(this,[a].concat(q(c))).trim())):H.prototype.w.call.apply(H.prototype.w,[this,a].concat(q(c)))};function lb(a,b){(a=P[a.I])&&delete a[b]}
O.prototype.Qb=function(a,b){(a=this.Ec[a])&&a.set&&a.set(b)};"undefined"!=typeof window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]));var P="undefined"!=typeof window?window.PCjs.Machines:{},eb="undefined"!=typeof window?window.PCjs.Components:[];A.ab=1;A.Xb=2;A.jc=4;A.uc=8;A.Cc=16;A.Zb=32;A.sc=64;A.Jc=128;A.vc=256;A.ac=512;A.wc=1024;A.INT=2048;A.Sc=4096;A.Vc=8192;A.xc=16384;A.Gc=32768;A.fc=65536;A.oc=131072;
A.Ha=262144;A.Qc=524288;A.jb=1048576;A.ob=2097152;A.sb=4194304;A.yc=8388608;A.Rc=16777216;A.Ia=33554432;A.rc=67108864;A.od=4294967296;M.addr=A.ab;M.bus=A.Xb;M.fault=A.jc;M.memory=A.uc;M.ports=A.Cc;M.chips=A.Zb;M.kbd=A.sc;M.serial=A.Jc;M.misc=A.vc;M.cpu=A.ac;M.mmu=A.wc;M["int"]=A.INT;M.trap=A.Sc;M.video=A.Vc;M.monitor=A.xc;M.screen=A.Gc;M.disk=A.fc;M.file=A.oc;M.time=A.Ha;M.timer=A.Qc;M.event=A.jb;M.input=A.ob;M.key=A.sb;M.mouse=A.yc;M.touch=A.Rc;M.warn=A.Ia;M.halt=A.rc;B.Device=O;
function mb(a,b,c){O.call(this,a,b,c);this.aa=A.ob;this.u=this.H=null;this.time=Q(this,"Time");this.J=Q(this,"Machine");this.X=I(this,"drag",!1);this.S=I(this,"scroll",!1);this.W=I(this,"hexagonal",!1);this.h=I(this,"releaseDelay",0,void 0);this.j=!1;a=this.s.map;this.b=this.c=null;if(a)if(a.length)this.b=a;else{this.c={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.c[f]={keys:g,
Je:e,state:0}}}this.K=[];this.N=[];this.g=this.O=null;(a=this.M[nb])&&ob(this,a,this.xa(c.focusBinding,!0),this.s.location);this.ka()}r(mb,O);function pb(a,b){a.H=b}function qb(a,b,c){for(var d=0;d<a.K.length;d++){var e=a.K[d];e.id===b&&e.Ob(b,c)}}
function ob(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.b||a.c){var e={};e.jd=d[0]||0;e.kd=d[1]||0;e.wa=d[2]||b.clientWidth;e.Ka=d[3]||b.clientHeight;e.La=d[4]||1;e.Pa=d[5]||1;e.Zc=d[6]||b.naturalWidth||e.wa;e.ad=d[7]||b.naturalHeight||e.Ka;e.Tb=d[8]||0;e.Ub=d[9]||0;e.Yc=d[10]||0;e.$c=d[11]||0;a.b?(e.Na=a.b.length,e.ya=a.b[0].length):(e.ya=e.La,e.Na=e.Pa,e.La=e.Pa=0);e.Kb=e.wa/(e.ya+e.ya*e.La)|0;e.Lb=e.Ka/(e.Na+e.Na*e.Pa)|0;e.Xc=e.Kb*e.La|0;e.Mb=e.Lb*e.Pa|0;e.Ca=e.Qa=-1;rb(a,b,e);sb(a,b,e);a.time&&
a.h&&(a.U=tb(a.time,"timerInputRelease",function(){0>e.Ca&&0>e.Qa&&ub(a,-1,-1)}))}if(a.b||a.c)a.time&&a.h&&(a.Z=tb(a.time,"timerKeyRelease",function(){vb(a)})),a.l=0,a.v="",a.m=[],d=b,c&&(d=c,a.g||"BUTTON"!=c.nodeName||(d=document,a.g=c,wb(a,b),a.O=b)),wb(a,d),a.g||(a.g=d)}function xb(a){a.h?yb(a.time,a.Z,a.h):vb(a)}
function wb(a,b){function c(e,f,g){var k=document.activeElement;a.w(A.sb+A.jb,"%s.onKey%s(%d): %5.2f (%s)\n",k.id||k.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.g&&e!=a.g&&e!=a.O?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=zb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=zb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=zb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function rb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.j){var e=a.g;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,Ab,d,c)}});b.addEventListener("mousemove",function(d){a.j||R(a,b,Bb,d,c)});b.addEventListener("mouseup",function(d){a.j||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.j||(0>c.Ca?R(a,b,Bb,d,c):R(a,b,S,d,c))})}
function sb(a,b,c){b.addEventListener("touchstart",function(d){a.S&&(a.j=!0);R(a,b,Ab,d,c)});b.addEventListener("touchmove",function(d){R(a,b,Bb,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function zb(a,b,c,d){if(void 0!=c){var e=ab[b]||b;var f=cb[b];var g=Cb[e];d=d&&d.location==bb.Va;g&Db&&d&&(g>>=1);g&&(g&Eb&&(c=!(a.a&g)),a.a=c?a.a|g:a.a&~g,qb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=Za.Ra&&b<=Za.Wa?a.a&(Fb|Gb)||(a.a|=Gb,qb(a,L.Ta,!0)):b>=Za.Xa&&b<=Za.z&&a.a&Gb&&(a.a&=~Gb,qb(a,L.Ta,!1));if(a.b){if(void 0!=c)return!1;for(e=0;e<a.b.length;e++)for(g=a.b[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.l?16>a.m.length&&a.m.push(b):(a.l=1,a.v=f,ub(a,d,e),qb(a,
f,!0),xb(a)),!0}if(a.c){if(void 0==c)return!0;b=Object.keys(a.c);for(e=0;e<b.length;e++)if(g=b[e],0<=a.c[g].keys.indexOf(f))return qb(a,g,c),a.c[g].state=c?1:0,!0}return!1}function vb(a){1==a.l?(a.l++,qb(a,a.v,!1),a.v="",ub(a,-1,-1),xb(a)):(a.l=0,a.m.length&&zb(a,a.m.shift()))}mb.prototype.ka=function(){this.a=0;this.R=this.T=-1};
function R(a,b,c,d,e){var f=-1,g=-1,k=!1,h=-1,m=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(h=d.targetTouches[0].clientX,m=d.targetTouches[0].clientY,k=1<d.targetTouches.length):(h=d.clientX,m=d.clientY);var l=d.target.getBoundingClientRect();h-=l.left;m-=l.top;h=e.Zc/b.offsetWidth*h|0;m=e.ad/b.offsetHeight*m|0;var t=h-e.jd;var n=m-e.kd;var u=l=!1;var z=h>=e.Tb&&h<e.Tb+e.Yc&&m>=e.Ub&&m<e.Ub+e.$c;if(0<=t&&t<e.wa&&0<=n+e.Mb||z)if(k||a.S||d.preventDefault(),0<=t&&t<e.wa&&0<=
n&&n<e.Ka){u=!0;d=e.wa/e.ya|0;var x=e.Ka/e.Na|0,E=t/d|0,D=n/x|0;!a.W||D&1||(t-=d>>1,E=t/d|0,E==e.ya-1&&(t=-1));x=D*x+(e.Mb>>1);t-=E*d+(e.Xc>>1);n-=x;0<=t&&t<e.Kb&&0<=n&&n<e.Lb&&(f=E,g=D,l=!0)}}t=t||0;n=n||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Ab||c==S)for(E=0;E<a.N.length;E++)D=a.N[E],c==S?D.Ob(D.id,!1):(x=n/(b/D.Ge|0)|0,(t/(d/D.Fe|0)|0)==D.Ue&&x==D.Ve&&D.Ob(D.id,!0));if(!k)if(c==Ab)e.Ca=h,e.Qa=m,u?(ub(a,f,g),l&&a.h&&yb(a.time,a.U,a.h,!0)):z&&a.J.ca();else if(c==Bb)0<=e.Ca&&0<=e.Qa&&a.X?ub(a,f,
g):a.H&&a.H(f,g);else if(c==S){if(c=a.h)c=a.time,f=a.U,c=c.a&&0<f&&f<=c.b.length?0<=c.b[f-1].ba:!1;c||ub(a,-1,-1);e.Ca=e.Qa=-1}else G(a,"unrecognized action: "+c)}function ub(a,b,c){if(b!=a.R||c!=a.T)a.R=b,a.T=c,a.u&&a.u(b,c)}var Ab=1,Bb=2,S=3,nb="surface",Fb=3,Db=170,Gb=512,Eb=3584,T={},Cb=(T[L.Lc]=2,T[L.cc]=8,T[L.Wb]=32,T[L.fb]=128,T[L.Ta]=Gb,T[L.Ac]=1024,T[L.Hc]=2048,T);B.Input=mb;
function Hb(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.M[Ib];if(!a)throw Error("LED "+this.s.M[Ib]+" binding for '"+Ib+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.qa=Ja(this,Ib)+".canvas";b.setAttribute("id",this.qa);this.yb=a;this.type=Ma(I(this,"type",Jb,Kb),Lb,Mb);this.g=Nb[this.type][0];this.m=Nb[this.type][1];this.width=I(this,"width",
this.g,void 0);this.height=I(this,"height",this.m,void 0);this.h=I(this,"cols",1,void 0);this.K=this.h+I(this,"colsExtra",0,void 0);this.X=I(this,"rows",1,void 0);this.R=this.X+I(this,"rowsExtra",0,void 0);this.$=this.width*this.h;this.T=this.height*this.X;this.l=Ob("black",0);this.c=Pb(this.s.color)||this.l;this.ha=Ob(this.c,1,.25);this.ga=Ob(this.c,1,2);this.j=Pb(this.s.backgroundColor);this.ma=I(this,"fixed",!1);this.ma||(b.style.width="100%",b.style.height="auto");this.fa=I(this,"hexagonal",!1);
this.pa=I(this,"highlight",!0);this.S=I(this,"persistent",this.type<Mb);b.setAttribute("width",this.$.toString());b.setAttribute("height",this.T.toString());b.style.backgroundColor=this.l;a.appendChild(b);this.da=b.getContext("2d");if(this.u=document.createElement("canvas"))this.u.width=this.Z=this.g*this.h,this.u.height=this.v=this.m*this.X,this.b=this.u.getContext("2d");this.ra=(this.R+1)*this.K*4;this.a=Array(this.ra);this.Fa=this.h<this.K?4*(this.K-this.h):0;this.N=this.O=!1;this.H=this.W=0;this.U=
-1;var d=this;this.time=Q(this,"Time");Qb(this.time,function(e){Rb(d,!1,e)});Sb(d)}r(Hb,O);function Sb(a){for(var b=a.a,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Mb?Tb:" ";e[f+1]=d.c==d.l?null:d.c;e[f+2]=0;e[f+3]=Ub}a.N=a.O=!0;Rb(a,!0)}function Vb(a){a.j?(a.b.fillStyle=a.j,a.b.fillRect(0,0,a.Z,a.v)):a.b.clearRect(0,0,a.Z,a.v)}
function Rb(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.N||b){if(a.type<Mb){var d=0;if(!a.S||b)Vb(a);else if(a.H){d=a.h-a.H;var e=a.g*d;a.b.drawImage(a.u,a.g*a.H,0,e,a.v,0,0,e,a.v)}for(var f=e=0;f<a.R;f++){for(var g=0;g<a.h;g++){var k=a.a[e],h=a.a[e+1]||a.l,m=a.pa&&e==a.U;if(a.a[e+3]&Ub||m||b){if(g>=d)a:{var l=a,t=k;k=h;var n=g;h=f;var u=m;n=void 0===n?0:n;h=void 0===h?0:h;u=void 0===u?!1:u;var z=0;if(l.fa&&!(h&1)&&(z=l.g>>1,n==l.h-1))break a;if(k&&k!=l.c){u=u?Ob(k,1,2):k;var x=Ob(k,1,.25)}else u=
u?l.ga:l.c,x=l.ha;k=!1;t=t?u:x;u==l.l&&(t=l.j,k=!0);u=n*l.g+z;x=h*l.m;l.S&&(n=n*l.g+z,h*=l.m,l.j?(l.b.fillStyle=l.j,l.b.fillRect(n,h,l.g,l.m)):l.b.clearRect(n,h,l.g,l.m));l.b.fillStyle=t;h=Wb[l.type];3==h.length?(l.b.beginPath(),l.b.arc(u+h[0],x+h[1],h[2],0,2*Math.PI),k?(l.b.globalCompositeOperation="destination-out",l.b.fill(),l.b.globalCompositeOperation="source-over"):l.b.fill()):l.b.fillRect(u+h[0],x+h[1],h[2],h[3])}a.a[e+3]=m?a.a[e+3]|Ub:a.a[e+3]&~Ub}e+=4}e+=a.Fa}a.H=0}else{b="";for(d=0;d<a.a.length;d+=
4)b+=a.a[d]||" ",a.a[d+3]&Xb&&(b+=".");Vb(a);for(f=e=d=0;d<b.length;d++){h=b[d];"."==h&&e&&e--;g=a;m=e;l=f;m=void 0===m?0:m;l=void 0===l?0:l;if(h=Yb[h])for(k=0;k<h.length;k++)if(n=g,z=Zb[h[k]]){t=(void 0===m?0:m)*n.g;u=(void 0===l?0:l)*n.m;n.b.fillStyle=n.c;n.b.beginPath();if(3==z.length)n.b.arc(t+z[0],u+z[1],z[2],0,2*Math.PI);else for(x=0;x<z.length;x+=2)x?n.b.lineTo(t+z[x],u+z[x+1]):n.b.moveTo(t+z[x],u+z[x+1]);n.b.closePath();n.b.fill()}if(++e==a.h&&(e=0,++f==a.R))break}}a.da.globalCompositeOperation=
a.j&&a.c!=a.l?"source-over":"copy";a.da.drawImage(a.u,0,0,a.Z,a.v,0,0,a.$,a.T);a.N=!1;a.U=-1}else a.S||a.O||(!c||!a.W||c-a.W>=(1E3/60|0))&&Sb(a);a.O=!1;c&&(a.W=c)}function Pb(a){return(a=a||void 0)&&db[a]||a}
function Ob(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=db[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Hb.prototype.ia=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.c&&c==this.j&&a&&a.length==this.a.length){this.a=a;for(b=0;b<=this.a.length-4;b+=4)this.a[b+1]==this.l&&(this.a[b+1]=null);Rb(this,!0);return!0}return!1};Hb.prototype.la=function(a){this.a&&(a.push(this.c),a.push(this.j),a.push(this.a))};
function $b(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&ac;b=4*(c*a.K+b);if(b<=a.a.length-4){if(a.a[b]!==d||(a.a[b+3]&ac)!==e)a.a[b]=d,a.a[b+3]=a.a[b+3]&~ac|e|Ub,a.N=f=!0;a.U=b;a.O=!0;a.H=0}return f}
var Lb=0,Jb=1,Mb=3,Kb={small:Lb,round:Jb,square:2,digit:Mb},Ib="container",Tb=0,ac=129,Xb=1,Ub=128,bc={},Wb=(bc[Lb]=[4,4,4],bc[Jb]=[16,16,14],bc[2]=[2,2,28,28],bc),Nb=[[8,8],[32,32],[32,32],[96,128]],Zb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Yb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};B.LED=Hb;
function cc(a,b,c){O.call(this,a,b,c);this.ga=I(this,"cyclesMinimum",1E5,void 0);this.ra=I(this,"cyclesMaximum",1E9,void 0);this.ha=Ma(I(this,"cyclesPerSecond",1E6,void 0),this.ga,this.ra);this.R=1E3/60;this.Dc=I(this,"updatesPerSecond",2,void 0)||2;this.Bc=1E3/this.Dc;this.qa=0;this.Fc=I(this,"timeLock",!0);this.da=this.K=0;this.$=this.l=1;this.pa=this.u=this.ha/1E4/100;this.X=[];this.v=[];this.b=[];this.Z=[];this.ma=this.a=this.W=this.m=!1;this.H=this.g=0;a=Ha("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.R}this.Fa=window[a].bind(window,this.fd.bind(this),d);this.yb=window[Ha("cancelAnimationFrame")||"clearTimeout"].bind(window);this.U=this.T=this.h=this.c=this.fa=0;dc(this)||ec(this,this.$)}r(cc,O);function Qb(a,b){a.X.push(b)}p=cc.prototype;
p.va=function(a,b){var c=this;switch(a){case fc:b.onclick=function(){gc(c)&&(c.a?U(c):c.start())};break;case hc:b.onclick=function(){ec(c,c.l<<1);ic(c,jc(c.u))};break;case kc:b.onclick=function(){lc(c)};break;case mc:b.addEventListener("mousedown",function(){c.m=!0}),b.addEventListener("mouseup",function(){dc(c);c.m=!1}),b.addEventListener("mousemove",function(){c.m&&dc(c)}),b.addEventListener("change",function(){c.m=!0;dc(c);c.m=!1})}O.prototype.va.call(this,a,b)};
function tb(a,b,c){var d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,Wc:c,Ma:d,ba:-1});0<=d&&yb(a,e,d);return e}
function nc(a,b,c,d){var e=0,f=a.u,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.w(A.Ha,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.R&&(1<a.l&&(a.l>>=1,a.w(A.Ia,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.R,a.l)),e=d));a.K=f;a.da=f/a.pa;b=a.da/a.l;a.fa=g/b/60+1E-8;a.w(A.Ha,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.fa,g,b,60);return e}
function oc(a,b){a.T=a.h=b;if(!a.v.length)return a.h=0,a.T;for(var c=0;0<a.h;){if(c<a.v.length){var d=a.v[c++];b=d.gd.call(d,b)||1}else c=b=0;a.h-=b}return a.T-a.h}function pc(a,b){var c=Date.now();b()&&(a.S+=Date.now()-c)}function qc(a,b){b=void 0===b?a.T-a.h:b;if(!a.a){if(a.c)for(var c=0;c<a.v.length;c++){var d=a.v[c];d.Rb.call(d)}a.c=b}a.c-=b;1>a.c&&(a.W=!0);a.U+=b;a.T=a.h=0;a.a||(a.U=0);return b}
function rc(a,b){b=void 0===b?0:b;if(b){var c=b;a.c+=b}else for(c=a.c,1>c&&(c=a.c+=a.fa),0>c&&(a.w(A.Ia,"warning: cycle count dropped below zero: %f\n",c),c=a.c=0),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.ba)&&c>d.ba&&(c=d.ba)}return c}function jc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function gc(a){return a.ma?!0:(G(a,"not powered"),!1)}
function sc(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.ba||(d.ba-=b,0>=d.ba&&(d.ba=-1,d.Wc(),0<=d.Ma&&yb(a,c,d.Ma)))}}p.ca=function(a){this.ma=a;void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};function lc(a,b){gc(a)&&(a.a?G(a,"already running"):a.g?U(a):tc(a,b))}
p.fd=function(a){a=void 0===a?Date.now():a;this.H=0;if(this.a){var b=Date.now();if(this.N){var c=b-this.O-this.R;c>this.R&&(this.j+=c,this.w(A.Ia,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.O=b;this.j||(this.j=b);this.S=0;try{this.W=!1;do sc(this,qc(this,oc(this,rc(this))));while(this.a&&!this.W)}catch(d){G(this,d.message),U(this)}this.N=Date.now();this.S&&(this.j+=this.S,this.O+=this.S);this.O+=nc(this,this.U,this.N-this.j,this.N-this.O);this.N-this.qa>=this.Bc&&this.update();
for(b=0;b<this.X.length;b++)this.X[b](a);this.H=this.Fa()}};function ec(a,b){if(void 0!==b){if(1>b||!a.m&&0<a.K&&a.K<.9*a.u)b=a.$;a.l=b;b=a.pa*a.l;a.u!=b&&(a.u=b,ic(a,jc(a.u)))}a.j=a.N=0;a.c=a.U=0;nc(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Ma&&yb(a,b,c.Ma,!0)}}function dc(a){var b=a.M[mc];return b?(ec(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.ra-a.ga)+a.ga)/a.ha|0),!0):!1}
function yb(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.ba)&&(c=Math.ceil(a.ha*(a.Fc?a.$:a.da)/1E3*(void 0===c?1E3:c)),a.a&&(c+=qc(a)),b.ba=c)}p.start=function(){if(this.a||this.g)return!1;this.a=!0;this.j=this.N=0;this.update(!0);this.H=this.Fa();return!0};function tc(a,b){b=void 0===b?1:b;a.a||(b&&!a.g&&(a.g=b),a.g&&(a.g--,sc(a,qc(a,oc(a,rc(a,1)))),a.update(!1),a.g&&setTimeout(function(){tc(a,0)},0)))}
function U(a){return a.a?(a.a=!1,qc(a),a.H&&(a.yb(a.H),a.H=0),a.update(!0),!0):a.g?(a.g=0,a.update(!0),!0):!1}p.update=function(a){a&&G(this,this.a?"started with "+jc(this.u)+" target":"stopped");Ya(this,fc,this.a?"Halt":"Run");Ya(this,kc,this.g?"Stop":"Step");this.m||(this.w(A.Ha,"getSpeedCurrent(%5.3fhz)\n",1E6*this.K),ic(this,this.a&&this.K?jc(this.K):"Stopped"));for(var b=0;b<this.Z.length;b++){var c=this.Z[b];c.cd.call(c,void 0!=a)}this.qa=Date.now();this.W=!0};
function ic(a,b){Ya(a,uc,b);Ya(a,hc,b)}var fc="run",hc="setSpeed",uc="speed",kc="step",mc="throttle";B.Time=cc;
function vc(a,b,c){O.call(this,a,b,c);this.type="static"==this.s.type?wc:xc;this.l=this.s.addrWidth||16;this.g=Math.pow(2,this.l);this.u=this.g-1|0;this.b=this.s.blockSize||(16<this.l?4096:1024);this.b>this.g&&(this.b=this.g);this.v=this.g/this.b|0;this.c=Math.log2(this.b)|0;this.h=(1<<this.c)-1;this.m=this.s.dataWidth||8;this.a=Array(this.v);this.j=0;a=new V(a,b+"[NONE]",{size:this.b,bus:this.V});for(b=0;b<this.g;b+=this.b)yc(this,b,this.b,W.NONE,a);a=this.j;this.j+=this.type;a&&this.j||(this.za=
this.Yb,this.Aa=this.Ba)}r(vc,O);
function yc(a,b,c,d,e){for(var f=b>>>a.c;0<c&&f<a.a.length;){var g=f*a.b,k=a.b-(b-g);k>c&&(k=c);var h=a.a[f];if(b!=g||k!=a.b||h&&h.type!=W.NONE)break;var m=h=void 0,l=b,t=a.l,n=16;t=void 0===t?0:t;h=void 0===h?0:h;var u="",z="",x=-1;n||(n=a.H||10);t&&(x=Math.ceil(t/Math.log2(n)));if(void 0==m)switch(n){case 8:m="0o";break;case 16:m="0x";break;case 10:z=".";default:m=""}isNaN(l)||"number"!=typeof l?(l=void 0,m=z=""):(0>l&&-1<l&&(l=-1),t&&(0>l&&(l+=Math.pow(2,t)),l>=Math.pow(2,t)&&(x=Math.ceil(Math.log(l)/
Math.log(n)))));for(t=h||-1;x--;){t||(u=","+u,t=h);if(void 0==l){if(u="?"+u,0>x)break}else{var E=l%n;l=Math.trunc(l/n);E+=0<=E&&9>=E?48:55;u=String.fromCharCode(E)+u;if(!l&&0>x)break}t--}h=a.V+"["+(m+u+z)+"]";b=e?e.size==a.b?e:new V(a.I,h,{type:d,Ja:b,size:k,bus:a.V}):new V(a.I,h,{type:d,Ja:b,size:k,bus:a.V});a.a[f]=b;b=g+a.b;c-=k;f++}}p=vc.prototype;p.ca=function(){void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};p.ka=function(){};p.Ya=function(a){return a&&this.ia(a)?!0:!1};p.Za=function(a){this.la(a)};
p.ia=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if((this.type==xc||c.type&W.Ga)&&c.ia){var d=a.shift();if(!c.ia(d))return!1}}return!0};p.la=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if((this.type==xc||c.type&W.Ga)&&c.la){var d=[];c.la(d);a.push(d)}}};p.sa=function(a){return this.a[a>>>this.c].sa(a&this.h)};p.Yb=function(a){return this.a[a>>>this.c].za(a&this.h)};p.$a=function(a,b){this.a[a>>>this.c].$a(a&this.h,b)};
p.Ba=function(a,b){this.a[a>>>this.c].Aa(a&this.h,b)};var wc=0,xc=1;B.Bus=vc;
function V(a,b,c){O.call(this,a,b,c);this.Ja=this.s.addr;this.size=this.s.size;this.type=this.s.type||W.NONE;this.g=(a=this.s.bus)?fb(this,a):Q(this,a="Bus");if(!this.g)throw Error(this.L("unable to find bus '%s'",a));this.j=this.g.m;this.u=Math.pow(2,this.j)-1;this.h=this.m=!1;this.values=this.c=null;a=this.wb;b=this.Ba;if(this.g.type==wc){b=this.hd;if(c=8==this.j)c=fb(this,this.I),c=!1!==(c&&c.s&&c.s.ArrayBuffer||this.s.ArrayBuffer);c&&(this.m=!0)}switch(this.type){case W.NONE:this.za=this.ed;this.Aa=
this.Sb;break;case W.Cb:this.za=a;this.Aa=this.Sb;break;case W.Ga:this.za=a,this.Aa=b}zc(this,this.s.values);Ac(this)}r(V,O);function zc(a,b){"string"==typeof b?(jb(a,!1),Na(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);zc(a,g.values)}catch(k){a.w("error (%s) parsing resource: %s\n",k.message,c)}jb(a,!0)}else a.w("error (%d) loading resource: %s\n",f,c)})):a.s.values=b}
function Ac(a,b){if(a.type>W.NONE&&(a.m?(a.c=new ArrayBuffer(a.size),new DataView(a.c,0,a.size),a.values=new Uint8Array(a.c,0,a.size),new Uint16Array(a.c,0,a.size>>1),new Int32Array(a.c,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}p=V.prototype;
p.ka=function(){if(this.s.values)a:{var a=this.g,b=this.Ja,c=this.size,d=this.s.values,e=0,f=b&a.h;b>>>=a.c;c>d.length&&(c=d.length);for(;0<c&&b<a.a.length;){var g=a.a[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Ba(f++,d[e++]),c--;f=0}}else this.type&W.Ga&&this.values&&this.values.fill(0)};p.ed=function(){return this.u};p.sa=function(a){return this.values?this.values[a]:0};p.wb=function(a){return this.values[a]};p.Sb=function(){};p.$a=function(a,b){this.values&&(this.values[a]=b)};
p.Ba=function(a,b){this.values[a]=b};p.hd=function(a,b){this.values[a]=b;this.h=!0;this.Aa=this.Ba};p.ia=function(a){var b=a.shift();if(this.V==b){this.h=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}Ac(this,a)}return!0}return!1};p.la=function(a){a.push(this.V);a.push(this.h);a.push(!1);a.push(this.values?ua(this.values):this.values)};var W={NONE:1,Cb:2,Ga:4,xe:14,Be:12};
B.Memory=V;
function Bc(a,b,c){c.type=W.Cb;V.call(this,a,b,c);yc(this.g,this.s.addr,this.s.size,this.s.type,this);kb(this,this.ka.bind(this));this.Y=this.ja=void 0;if(B.LED&&this.M[Cc]){var d=this;this.b=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.l=this.values.length/this.b|0;this.a=new Hb(a,b+"LEDs",{"class":"LED",bindings:{container:Ja(this,Cc)},type:Jb,cols:this.b,rows:this.l,color:I(this,"colorROM","green"),backgroundColor:I(this,"backgroundColorROM","black"),persistent:!0}),Sb(this.a);this.v=
new mb(a,b+"Input",{"class":"Input",location:[0,0,this.a.$,this.a.T,this.b,this.l],bindings:{surface:Ja(this,Cc)}});this.H=Ka(this)||"";pb(this.v,function(e,f){if(d.Y){var g=d.H;0<=e&&0<=f&&(e=f*d.b+e,g=Dc(d.Y,d.Ja+e,d.values[e]));Ya(d,La,g)}})}}r(Bc,V);
Bc.prototype.ia=function(a){var b=!0,c=a.shift();if(c&&this.a){var d=c.length;this.a.a.length==d?(this.a.a=c,Rb(this.a,!0)):(this.w("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.w("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};Bc.prototype.ca=function(){void 0===this.Y&&(this.Y=Q(this,"CPU"));void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};
Bc.prototype.wb=function(a){this.a&&$b(this.a,a%this.b,a/this.b|0,1,Ub);return this.values[a]};Bc.prototype.la=function(a){this.a&&(a.push(this.a.a),a.push(this.values))};var Cc="array",La="cellDesc";B.ROM=Bc;function Ec(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.ja=void 0;this.b=this.Oa=0;this.time=Q(this,"Time");this.time.v.push(this);this.time.Z.push(this);this.T=this.j=0}r(Ec,O);p=Ec.prototype;p.abort=function(a){this.b=this.Oa;G(this,a.message);U(this.time)};p.Nb=function(){};
p.gd=function(a){this.T=this.j=a=void 0===a?0:a;try{this.Nb(a)}catch(b){this.abort(b)}return this.Pb()};p.Rb=function(){this.T-=this.j;this.j=0};p.Pb=function(){return this.T-this.j};function X(a,b,c){O.call(this,a.I,b);this.Y=a;this.name=b;this.f=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.ha[c]=[this,-1];for(var d=0;d<this.f.length;d++)c=this.L("reg%s-%02d",this.name,d),b.push(c),a.ha[c]=[this,d];Ga(a,b)}}r(X,O);p=X.prototype;
p.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.f[f]=a.f[f]+b.f[f]+e,e=0,this.f[f]>=d&&(this.f[f]-=d,e=1);e&&(this.Y.l=!0);Fc(this,c)};p.get=function(){return this.f};function Gc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.f.length;d++)a.f[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.f[d]=b&15,b>>>=4;return a}p.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.f[e]=a.f[e]+d,d=0,this.f[e]>=c&&(this.f[e]-=c,d=1);Fc(a,b)};
p.set=function(a){if(a&&a.length==this.f.length)for(var b=0;b<this.f.length;b++)this.f[b]=a[b]};p.store=function(a){for(var b=0,c=this.f.length;b<c;b++)this.f[b]=a.f[b]};p.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.f[f]=a.f[f]-b.f[f]-e,e=0,0>this.f[f]&&(this.f[f]+=d,e=1);e&&(this.Y.l=!0);Fc(this,c)};p.toString=function(a){a=void 0===a?!1:a;var b=this.V+"=";a&&3>b.length&&(b+=" ");for(var c=this.f.length-1;0<=c;c--)b=a?b+Aa[this.f[c]]:b+(Ba[this.f[c]]+(c%4?"":" "));return b};
function Fc(a,b){a.Y.h=a.f[b[0]];b[0]<b[1]&&(a.Y.h|=a.f[b[0]+1]<<4)}
function Hc(a,b,c){Ec.call(this,a,b,c);this.type=Number.parseInt(I(this,"type","1501").slice(-4),10);this.ha={};this.a=Array(4);for(a=0;4>a;a++)this.a[a]=new X(this,String.fromCharCode(65+a));this.O=this.a[0];this.U=this.a[1];this.pa=this.a[2];this.ra=this.a[3];this.K=Array(8);for(a=0;8>a;a++)this.K[a]=new X(this,"X"+a);this.R=Array(8);for(a=0;8>a;a++)this.R[a]=new X(this,"Y"+a);this.ma=new X(this,"Supp",!0);this.X=new X(this,"Temp",!0);this.H=10;this.l=!1;this.W=this.h=this.u=0;this.g=[-1,-1,-1];
this.qa=fb(this,this.s.input);this.qa.u=this.bc.bind(this);this.c=fb(this,this.s.output,!1);this.v=Q(this,"Bus");this.m=Q(this,"ROM");this.fa=this.ga=this.S=void 0;this.da=this.Z=-1;this.N={};this.$=Ic;a=this.bd.bind(this);b=Ta.gb;this.J.Ea[b]||(this.J.Ea[b]=[]);this.J.Ea[b].push(a)}r(Hc,Ec);function Jc(a,b){a.N[b]&&(a.N[b]=!1,G(a,"break on "+Kc[b]),U(a.time))}function Lc(a){a.c&&Sb(a.c);if(a.m){var b=a.m;b.a&&Sb(b.a)}Mc(a,!1)}p=Hc.prototype;
p.Nb=function(a){for(;0<this.j;){if(this.da==this.b){this.da=-1;G(this,"break");U(this.time);break}var b=this.v.za(this.b);this.b=(this.Oa=this.b)+1&this.v.u;if(void 0==b||!Nc(this,b)){this.b=this.Oa;G(this,"unimplemented opcode");U(this.time);break}this.j-=Oc}if(0>=a){var c=this;pc(this.time,function(){var d=c.m;d.a&&Rb(d.a);c.na(c.toString())})}};p.Rb=function(){this.j=0};p.Pb=function(){return this.T-this.j};
function Nc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.l&&(a.b=a.b&1024|b&1023):(a.push(a.b),a.b=b&2047),a.l=!1,!0;var c;var d=b&Pc;switch(d){case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:case ad:d=bd[d];var e=(b&cd)>>dd;var f=(b&ed)>>fd;var g=(b&gd)>>hd;var k=(c=b&id)?jd:kd;b=b>=Xc?16:a.H;switch(f){case 0:case 1:case 2:case 3:var h=a.a[f];break;case 4:h=Gc(a.X,1,d);break;case 5:k=c?ld:md;break;case 6:h=Gc(a.X,a.h&15,d);break;case 7:h=Gc(a.X,a.h&255,d)}switch(g){case 0:var m=
a.a[e];break;case 1:m=4>f?a.a[f]:void 0;break;case 2:m=5>f?a.ma:5==f?a.a[e]:void 0;break;case 3:if(c)a.a[e].move(h,d,b);else{a=a.O;e=h;b=d[0];for(h=d[1];b<=h;b++)m=a.f[b],a.f[b]=e.f[b],e.f[b]=m;Fc(e,d)}return!0}if(!m)break;switch(k){case kd:m.add(a.a[e],h,d,b);break;case jd:m.sub(a.a[e],h,d,b);break;case md:b=m;a=a.a[e];e=d[1];for(h=d[0];e>h;e--)b.f[e]=a.f[e-1];b.f[e]=0;Fc(b,d);break;case ld:b=m;a=a.a[e];e=d[0];for(h=d[1];e<h;e++)b.f[e]=a.f[e+1];b.f[e]=0;Fc(b,d)}return!0;case nd:e=(b&od)>>pd;d=(b&
qd)>>rd;h=1<<((b&sd)>>td);if(!d)break;d+=12;switch(b&ud){case vd:a.a[e].f[d]|=h;break;case wd:a.a[e].f[d]&=~h;break;case xd:a.a[e].f[d]&h&&(a.l=!0);break;case yd:a.a[e].f[d]^=h}return!0;case zd:switch(b&Ad){case Bd:a.O.store(a.R[a.u]);break;case Cd:a.u=b>>4&7;break;case Dd:a.b=a.h;break;case Ed:a.l=!1;d=a.g[0];e=0;for(b=a.g.length-1;e<b;)a.g[e]=a.g[++e];a.g[e]=-1;a.b=d;break;case Fd:a.K[a.u].store(a.O);break;case Gd:a.O.store(a.K[a.u]);break;case Hd:a.R[a.u].store(a.O);break;case Id:Jc(a,"o");if(a.c){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.U.f[e]&8?b=" ":a.U.f[e]&1?b="-":b=Aa[a.O.f[e]],$b(a.c,d,0,b,a.U.f[e]&2?Xb:0)&&Jc(a,"om");Mc(a)}a.j-=31*Oc;a.W&&(a.h=a.W,a.l=!0,Jc(a,"i"));break;case Jd:a.H=10;break;case Kd:a.H=16;break;case Ld:a.u=a.h&7;break;default:return!1}return!0}return!1}
p.ia=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return G(this,"invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.w("saved state version mismatch: %3.2f\n",c),!1;try{this.a.forEach(function(d){return d.set(b.shift())}),this.K.forEach(function(d){return d.set(b.shift())}),this.R.forEach(function(d){return d.set(b.shift())}),this.ma.set(b.shift()),this.X.set(b.shift()),this.H=b.shift(),this.l=b.shift(),this.u=b.shift(),this.h=b.shift(),this.b=b.shift(),this.g=b.shift(),this.W=
b.shift()}catch(d){return G(this,"CPU state error: "+d.message),!1}return(a=a.stateROM||a[1])&&this.m&&!this.m.ia(a)?!1:!0};
p.bd=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,k=3;k<a.length;k++)d.push(Number.parseInt(a[k],16));this.$=Ic;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Kc)c=Kc[f],b+="break on "+c+" (b"+f+"): "+(this.N[f]||!1)+"\n";break}(c=Kc[f])?(this.N[f]=!this.N[f],b="break on "+c+" (b"+f+"): "+this.N[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.v.sa(f);if(void 0==
a)break;this.v.$a(f,d[g]);b+=this.L("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.L("%d locations updated\n",c);break;case "g":this.time.start()?this.da=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.$=Md);g=Number.parseInt(a[2],10)||1;lc(this.time,g);break;case "r":"c"==e[1]&&(this.$=Md);this.Qb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.Z?this.Z:this.b;g--;){c=this.m&&this.v.sa(f);if(void 0==
c)break;b+=Dc(this,f++,c)}this.Z=f;break;case "?":b="additional commands:\n";Nd.forEach(function(h){b+=h+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};p.bc=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.W=c};p.Ya=function(a){return a&&this.ia(a)?!0:!1};p.ca=function(a){a?this.time.start():(U(this.time),Lc(this))};p.ka=function(){G(this,"reset");this.b=0;Lc(this);this.time.a||this.na(this.toString())};p.Za=function(a){this.la(a)};
p.cd=function(a){for(var b in this.M){var c=this.ha[b];if(c){var d=c[0];c=c[1];Ya(this,b,0>c?d.toString():Aa[d.f[c]])}}a&&!this.time.a&&(a=this.m,a.a&&Rb(a.a),this.na(this.toString()))};p.push=function(a){for(var b=this.g.length-1;0<b;)this.g[b]=this.g[--b];this.g[0]=a};
p.la=function(a){var b=[],c=[];b.push(2);this.a.forEach(function(d){return b.push(d.get())});this.K.forEach(function(d){return b.push(d.get())});this.R.forEach(function(d){return b.push(d.get())});b.push(this.ma.get());b.push(this.X.get());b.push(this.H);b.push(this.l);b.push(this.u);b.push(this.h);b.push(this.b);b.push(this.g);b.push(this.W);this.m&&this.m.la(c);a.push(b);a.push(c)};p.Qb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.b=b;break;default:G(this,"unrecognized register: "+a)}};
function Dc(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.L("%#06x",f);else if(0<=c){var g=c&Pc;var k;switch(g){case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:case ad:f="";e=bd[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&cd)>>dd;var h=(c&ed)>>fd;var m=(c&gd)>>hd;var l=c&id;e="LOAD";var t=k="?";var n=l?5==h?">>":"-":5==h?"<<":"+";switch(m){case 0:k=
Y[g];break;case 1:4>h&&(k=Y[h]);break;case 2:6>h&&(k="NUL");break;case 3:l?(e="MOVE",k=Y[g],t=Y[h]):(e="XCHG",g||(k="A"),4>h&&(t=Y[h])),h=-1}switch(h){case 0:case 1:case 2:case 3:t=Y[g]+n+Y[h];break;case 4:case 5:t=Y[g]+n+"1";break;case 6:t=Y[g]+n+"R5L";break;case 7:t=Y[g]+n+"R5"}f=k+","+t+","+f;break;case nd:switch(c&ud){case vd:e="SET";break;case wd:e="CLR";break;case xd:e="TST";break;case yd:e="NOT"}f=a.a[(c&od)>>pd].name;g=(c&qd)>>rd;f+="["+(g?g+12:"?")+":"+((c&sd)>>td)+"]";break;case zd:switch(c&
Ad){case Bd:e="STORE";f="A,Y[RAB]";break;case Cd:e="STORE";f="RAB,"+((c&112)>>4);break;case Dd:e="BR";f="R5";break;case Ed:e="RET";break;case Fd:e="STORE";f="X[RAB],A";break;case Gd:e="STORE";f="A,X[RAB]";break;case Hd:e="STORE";f="Y[RAB],A";break;case Id:e="DISP";break;case Jd:e="BCDS";break;case Kd:e="BCDR";break;case Ld:e="STORE",f="RAB,R5L"}}}return a.L(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
p.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.$){this.m&&(d+=Dc(this,this.b,this.v.sa(this.b),!0));d+="  ";b=0;for(a=this.a.length;b<a;b++)d+=this.a[b].toString()+" ";d+="\n ";d+=" COND="+(this.l?1:0);d+=" BASE="+this.H;d+=" R5="+this.L("%02X",this.h);d+=" RAB="+this.u+" ST=";this.g.forEach(function(f){d+=c.L("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.a);0<=a.indexOf("a")&&(d+=this.toString(a,this.K),d+=this.toString(a,this.R));d+="COND="+(this.l?1:0);d+=" BASE="+this.H;d+=" R5="+this.L("%#04x",this.h);d+=" RAB="+this.u+" ";this.g.forEach(function(f,g){d+=c.L("ST%d=%#06x ",g,f&65535)});this.m&&(d+="\n"+Dc(this,this.b,this.v.sa(this.b)));this.Z=this.b;return d};
function Mc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Od?!!(a.pa.f[14]&8):!!(a.U.f[15]&4));if(a.fa!==d){if(c=a.M["2nd"])c.style.opacity=d?"1":"0",void 0===a.fa&&a.c&&(c.style.color=a.c.color);a.fa=d}d=b&&(a.type==Od?!!(a.U.f[15]&4):!!(a.ra.f[15]&8));if(a.ga!==d){if(c=a.M.INV)c.style.opacity=d?"1":"0",void 0===a.ga&&a.c&&(c.style.color=a.c.color);a.ga=d}c=a.type==Od?a.K[4].f[15]>>2:a.pa.f[15];b=b?c?1==c?Pd:Qd:Rd:Sd;if(a.S!==b){if(c=a.M.Deg)c.style.opacity=b==Rd?"1":"0",void 0===a.S&&a.c&&(c.style.color=
a.c.color);if(c=a.M.Rad)c.style.opacity=b==Pd?"1":"0",void 0===a.S&&a.c&&(c.style.color=a.c.color);if(c=a.M.Grad)c.style.opacity=b==Qd?"1":"0",void 0===a.S&&a.c&&(c.style.color=a.c.color);a.S=b}}
var Pc=3840,Qc=0,Rc=256,Sc=512,Tc=768,Uc=1024,Vc=1280,Wc=1792,Xc=2048,Yc=2304,Zc=2560,nd=3072,$c=3328,zd=3584,ad=3840,cd=192,dd=6,ed=56,fd=3,gd=6,hd=1,id=1,ud=3,vd=0,wd=1,xd=2,yd=3,od=192,pd=6,qd=48,rd=4,sd=12,td=2,Ad=15,Bd=0,Cd=1,Dd=2,Ed=3,Fd=4,Gd=5,Hd=6,Id=7,Jd=8,Kd=9,Ld=10,Z={},bd=(Z[Qc]=[12,12],Z[Rc]=[0,15],Z[Sc]=[2,12],Z[Tc]=[0,12],Z[Uc]=[2,2],Z[Vc]=[0,1],Z[Wc]=[0,13],Z[Xc]=[14,14],Z[Yc]=[13,15],Z[Zc]=[14,15],Z[$c]=[13,13],Z[ad]=[15,15],Z),Oc=128,kd=0,jd=1,md=2,ld=3,Od=1501,Sd=0,Rd=1,Pd=2,Qd=
3,Kc={i:"input",o:"output",om:"output modification"},Ic=0,Md=1,Y="A B C D 1 ? R5L R5".split(" "),Nd="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");B.CPU1500=Hc;
function Td(a,b,c){O.call(this,a,a);var d=this;this.c=!1;this.l=c;this.b="";this.j=this.h=!1;jb(this,!1);this.aa=A.ec;b=b.trim();"{"==b[0]?Ud(this,b):(this.b=b,Na(this.b,function(e,f,g,k){4==g&&(!k&&f?(Ud(d,f),Vd(d)):d.w("error (%d) loading configuration: %s\n",k,e))}));window.addEventListener("load",function(){d.j=!0;Vd(d)});window.addEventListener(Pa("iOS")?"pagehide":Pa("Opera")?"unload":"beforeunload",function(){Wd(d)});window.addEventListener("pageshow",function(){d.c||d.ca(!0)})}r(Td,O);
Td.prototype.va=function(a,b){var c=this;switch(a){case Xd:b.onclick=function(){c.ca()};break;case Yd:b.onclick=function(){c.ka()}}O.prototype.va.call(this,a,b)};
function Vd(a){var b=!0;if(a.h&&a.j){for(var c in a.a){var d=void 0,e=a.a[c];try{d=e["class"],B[d]?"Machine"==d?(a.w("PCjs %s v%3.2f\n%s\n",e.name,2,Zd),a.b&&a.w("Configuration: %s\n",a.b)):new B[d](a.I,c,e):a.w('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.w('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),lb(a,c)}}if(a.g){var f=Qa(a);hb(a,function(g){return g.Ya&&!g.Ya(f)?(g.w('unable to restore state for device "%s"\n',g.V),!1):!0})}jb(a,!0);kb(a,a.ca.bind(a,b))||a.w("machine %s not ready to power, waiting for device(s)\n",
a.I)}}function Ud(a,b){try{a.a=JSON.parse(b);var c=a.a[a.I];if(!c){c=a.a[wa(a.b)];if(!c)throw Error("configuration missing machine ID");a.a[a.I]=c}gb(a,c,["autoSave","autoStart"]);a.g=!1!==a.s.autoSave;a.m=!1!==a.s.autoStart;if(a.l){var d=eval("("+a.l+")"),e;for(e in d)a.s[e]=d[e]}a.h=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),G(a,"machine '"+a.I+"' initialization error: "+c)}}
Td.prototype.ca=function(a){a=void 0===a?!this.c:a;if(ib(this)){var b=this;a&&G(this,"power on");hb(this,function(c){c.ca&&c!=b&&("CPU"!=c.s["class"]||b.m||ib(b)?c.ca(a):c.time.update(!0));return!0});(this.c=a)||G(this,"power off")}};Td.prototype.ka=function(){if(ib(this)){var a=this;hb(this,function(b){b.ka&&b!=a&&b.ka();return!0});G(this,"reset")}};function Wd(a){if(a.g){var b=[];hb(a,function(c){c.Za&&c.Za(b);return!0});Xa(a,b)}a.ca(!1)}var Xd="power",Yd="reset",Zd="Copyright \u00a9 2012-2020 Jeff Parsons <Jeff@pcjs.org>";
window.TMS1500=function(a,b,c){var d=new Td(a,b,c);window.command=function(e){return Ra(d,e)};return d};B.Machine=Td;})()

//# sourceMappingURL=ti42.js.map
