(function(){/*
 https://www.pcjs.org/machines/lib/defs.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/numio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/stdio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/webio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/device.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/input.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/led.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/time.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/bus.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/memory.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/rom.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/cpu.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/ti/lib/cpu1500.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/machine.js (C) 2012-2020 Jeff Parsons
*/
var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function q(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={Xa:!0},fa={};try{fa.__proto__=ea;da=fa.Xa;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function r(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var ia="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ja(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var w=ja(this);function y(a,b){if(b){var c=w;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ia(c,a,{configurable:!0,writable:!0,value:b})}}
y("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});y("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});function ka(){ka=function(){};w.Symbol||(w.Symbol=la)}function ma(a,b){this.a=a;ia(this,"description",{configurable:!0,writable:!0,value:b})}ma.prototype.toString=function(){return this.a};
var la=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ma("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function na(){ka();var a=w.Symbol.iterator;a||(a=w.Symbol.iterator=w.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ia(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}});na=function(){}}function oa(a){na();a={next:a};a[w.Symbol.iterator]=function(){return this};return a}
function pa(a,b){na();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}y("Array.prototype.keys",function(a){return a?a:function(){return pa(this,function(b){return b})}});
y("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});y("Number.parseInt",function(a){return a||parseInt});y("Array.prototype.values",function(a){return a?a:function(){return pa(this,function(b,c){return c})}});function qa(){}var ra=new ArrayBuffer(2);(new DataView(ra)).setUint16(0,256,!0);new Uint16Array(ra);
var A={Vb:0xffffffffffff,NONE:0,ec:0,ta:0x800000000000},C={};C.Defs=qa;function sa(){}r(sa,qa);function ta(a,b){var c=a/D|0,d=b/D|0;return(a&b)==(b|0)&&(c&d)==d}function ua(a){for(var b=0,c=0,d=[];b<a.length;){for(var e=a[b],f=b+1;f<a.length&&a[f]===e;)f++;d[c++]=f-b;d[c++]=e;b=f}return d.length>=a.length?a:d}var D=Math.pow(2,32);C.NumIO=sa;function E(){this.Da={};for(var a=0;22>a;a++)this.Da["ACDFHIMNSTWYbdfjcsoXx%"[a]]=null}r(E,sa);p=E.prototype;p.flush=function(){var a=va;va="";this.na(a)};
function wa(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}p.bd=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,q(b)))};
p.na=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),xa||(xa=b),a=((b-xa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(va+a.substr(0,c)),va="",a=a.substr(c+1)),xa=null);va+=a;return a.length};function F(a,b,c){a.na(b+"\n",c)}p.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.na(this.L.apply(this,[a].concat(q(c))))};
p.L=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(!c||!c.length)return a;d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var k=e[g+5];if(void 0===this.Da[k])d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+k;else{if(f<c.length){var h=c[f];"%"!=k&&f++}else h=c[c.length-1];var m=e[g+1],l=0<=m.indexOf("#"),t=0<=m.indexOf("0"),n=e[g+2];"*"==n?(n=h,h=f<c.length?c[f++]:c[c.length-1]):n=+n||0;var u=e[g+3];u=u?+u.substr(1):
-1;var z=null,x=0,B="";var v=0<="ACDFHIMNSTWY".indexOf(k)&&"object"!=typeof h?this.bd(h):h;switch(k){case "C":h=l?"#":"";d+=isNaN(v.getTime())?void 0:this.L(this.L("%%%sW, %%%sF %%%sD, %%%sY",h),v);continue;case "D":h=l?v.getUTCDate():v.getDate();k="d";break;case "A":case "H":case "I":h=l?v.getUTCHours():v.getHours();"A"==k?(h=12>h?"am":"pm",k="s"):("I"==k&&(h=h?12<h?h-12:h:12),k="d");break;case "F":case "M":h=l?v.getUTCMonth():v.getMonth();"F"==k?(h=ya[h],k="s"):(h++,k="d");break;case "N":h=l?v.getUTCMinutes():
v.getMinutes();k="d";break;case "S":h=l?v.getUTCSeconds():v.getSeconds();k="d";break;case "T":h=l?"#":"";d+=isNaN(v.getTime())?void 0:this.L(this.L("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),v);continue;case "W":h=za[l?v.getUTCDay():v.getDay()];k="s";break;case "Y":h=l?v.getUTCFullYear():v.getFullYear(),0<u&&(h%=Math.pow(10,u),u=-1),k="d"}switch(k){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=u&&(t=!0,n<u&&(n=u),u=-1);case "f":h=+h;v=h+"";0<=u&&(v=h.toFixed(u));v.length<
n&&(t?(0>h&&(n--,v=v.substr(1)),v=("0000000000"+v).slice(-n),0>h&&(v="-"+v)):v=("          "+v).slice(-n));d+=v;break;case "j":d+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=u&&(h=h.substr(0,u));h.length<n;)h=0<=m.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":x=8,l&&(B="0");case "X":z=Aa;case "x":v="";x||(x=16);!B&&l&&(B="0x");z||(z=Ba);h=Math.trunc(h);0<=u&&(t=!0,n<u&&(n=u));t&&!n&&
(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9,n+=B.length);n-=B.length;do l=h&x-1,h>>>=16==x?4:3,t||!v||l||h?v=z[l]+v:(B&&(v=B+v,B=""),0<n&&(v=" "+v));while(0<--n||h);d+=B+v;break;case "%":d+="%";break;default:this.Da[k]?d+=this.Da[k](k,m,n,u,h):d+="(unimplemented sprintf type: %"+k+")"}}}return d+=e[g]};var va="",xa=null,Ba="0123456789abcdef",Aa="0123456789ABCDEF",za="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ya="January February March April May June July August September October November December".split(" ");
C.StdIO=E;function G(a){E.call(this);this.M={};this.aa=0;this.J=this;a&&(this.J.aa=0,this.J.oa=[],this.J.ea=0,this.J.Ea={},this.J.xe=!1)}var Ca;r(G,E);p=G.prototype;p.va=function(a,b){var c=this,d=this;switch(a){case Da.$b:b.onclick=function(){var e=c.xa(Da.Ua,!0);e&&(e.value="")};break;case Da.Ua:Ea(b),b.addEventListener("keydown",function(e){Fa(d,e,!0)}),b.addEventListener("keypress",function(e){Fa(d,e)})}};
function Ga(a,b){b=void 0===b?{}:b;a.s.M||(a.s.M=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.V);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.M[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.M[d].push(e)}while(1);continue}if(f=document.getElementById(e))a.M[d]=f,a.va(d,f)}}
function Ea(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}p.error=function(a,b){b=this.L.apply(this,[a].concat(q(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.L.apply(this,[c].concat(q(b))))F(this,b),a||alert(b)};p.xa=function(a){return this.M[a]};
function Ha(a){var b=window;if(b){do{for(var c=0;c<Ia.length;c++){var d=Ia[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ja(a,b){return a.s.bindings&&a.s.bindings[b]}function Ka(a){if(a=a.M[La])var b=a.textContent;return b}function Ma(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function H(a,b,c,d){a=a.s[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Na(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Oa(a){if(void 0===I.Sa){var b=!1;if(window)try{window.localStorage.setItem(I.ua,I.ua),b=window.localStorage.getItem(I.ua)==I.ua,window.localStorage.removeItem(I.ua)}catch(c){F(a,c.message),b=!1}I.Sa=b}return!!I.Sa}function J(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.aa;return-1==(b|1)||ta(a.J.aa,b)?!0:!1}
function Pa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Qa(a){var b=null;if(Oa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.I))&&(b=JSON.parse(c))}catch(d){F(a,d.message)}}return b}
function Fa(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.J,f=b.target;if(c){a=!1;var g;c=f.value;var k=c.lastIndexOf("\n");d==K.cb&&f.selectionStart<=k+1&&(a=!0);d==K.Sc?(a=!0,0<e.ea&&(g=e.oa[--e.ea])):d==K.fc&&(a=!0,e.ea<e.oa.length&&(g=e.oa[++e.ea]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,k+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ea&&c+1==g.length&&
(f.value+=e.oa[--e.ea],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ra(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&F(a,b.replace(/\n$/,""),!1))}}
function Sa(a,b){if(void 0!=b){var c=a.J;try{if(b=b.trim())c.ea<c.oa.length&&b==c.oa[c.ea]?c.ea++:(c.oa.push(b),c.ea=c.oa.length);var d=b.split(" "),e=d[0],f=a.J.Ea[Ta.gb];switch(e[0]){case "m":if("?"==e[1]){var g="";Ua.forEach(function(t){g+=t+"\n"});g&&(g="message commands:\n"+g);break}g="";var k=void 0;e=d[d.length-1].toLowerCase();var h="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=h&&d.pop();1>=d.length&&(void 0!=h&&(k=h,h=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(L));for(f=
1;f<d.length;f++){e=d[f];var m=L[e];if(!m){g+="unrecognized message: "+e+"\n";break}void 0!=h&&Va(a,m,h);if(void 0==k||k==J(a,m))g+=a.L("%8s: %b\n",e,J(a,m))}J(a,A.ta)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Wa.forEach(function(t){g+=t+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var l=f[a](d);if(void 0!=l){g=g?g+l:l;break}}}}catch(t){g="error: "+t.message+"\n"}}return g}
function Ra(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Sa(a,b[d])}return c}p.na=function(a,b){void 0==b&&(b=J(this,A.ta));if(!b){var c=this.xa(Da.Ua,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Pa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return E.prototype.na.call(this,a,b)};
p.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return J(this,d)?E.prototype.w.call.apply(E.prototype.w,[this,a].concat(q(c))):0};function Xa(a,b){if(Oa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.I,b)}catch(c){F(a,c.message)}}}function M(a,b,c){(a=a.M[b])&&a.textContent!=c&&(a.textContent=c)}
function Va(a,b,c){var d=!1;c?(c=a.J.aa,a.J.aa=(c|b)+(c/D|0|b/D|0)*D):(d=ta(a.J.aa,A.ta)&&ta(b,A.ta),c=a.J.aa,a.J.aa=(c&~b)+((c/D|0)&~(b/D|0))*D);d&&a.flush()}
var Da={$b:"clear",Ua:"print"},Wa=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Ua=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],L={all:A.Vb,buffer:A.ta},Ta={gb:"command"},Ya={hb:13,Ra:65,bb:66,eb:67,ib:68,E:69,kb:70,lb:71,mb:72,nb:73,qb:74,rb:75,tb:76,vb:77,xb:78,zb:79,Ab:80,Q:81,Bb:82,Db:83,Eb:84,
Fb:85,Gb:86,Hb:87,Ib:88,Jb:89,Wa:90,Xa:97,Ae:98,Be:99,d:100,e:101,Fe:102,Ge:103,Ie:104,Je:105,Ke:106,k:107,Le:108,Me:109,n:110,Ne:111,p:112,q:113,r:114,Oe:115,t:116,Pe:117,Qe:118,Re:119,x:120,y:121,z:122},K={cb:8,Mc:9,rc:10,hb:13,Jc:16,cc:17,Wb:18,ne:19,Ta:20,pd:27,Lc:32,qe:33,pe:34,od:35,Kd:36,ub:37,Sc:38,Va:39,Hd:39,fc:40,Ed:44,re:44,Ld:45,nd:46,Gd:46,Jd:47,ZERO:48,ONE:49,Rc:50,Nc:51,oc:52,nc:53,Kc:54,Ic:55,gc:56,xc:57,mc:59,lc:61,Ra:65,bb:66,eb:67,ib:68,E:69,kb:70,lb:71,mb:72,nb:73,qb:74,rb:75,
tb:76,vb:77,xb:78,zb:79,Ab:80,Q:81,Bb:82,Db:83,Eb:84,Fb:85,Gb:86,Hb:87,Ib:88,Jb:89,Wa:90,fb:91,Fd:91,Dd:92,ue:93,Id:93,Pd:96,fe:96,Cd:96,Qd:97,de:97,Rd:98,ce:98,Sd:99,ie:99,Td:100,ge:100,Ud:101,$d:101,Vd:102,ke:102,Wd:103,ee:103,Xd:104,me:104,Yd:105,je:105,he:106,Zd:107,le:109,ae:110,be:111,qd:112,ud:113,vd:114,wd:115,xd:116,yd:117,zd:118,Ad:119,Bd:120,rd:121,sd:122,td:123,yc:144,Fc:145,kc:173,Gc:186,hc:187,ld:188,dc:189,oe:190,we:191,jd:192,Md:219,kd:220,te:221,se:222,jc:224,Nd:901,ye:1E3},Za={},
$a=(Za[K.mc]=K.Gc,Za[K.lc]=K.hc,Za[K.kc]=K.dc,Za[K.jc]=K.fb,Za),ab={ub:1,Va:2,Od:3},N={},bb=(N[K.cb]="\b",N[K.Mc]="\t",N[K.rc]="\n",N[K.hb]="\r",N[K.Lc]=" ",N[K.ZERO]="0",N[K.ONE]="1",N[K.Rc]="2",N[K.Nc]="3",N[K.oc]="4",N[K.nc]="5",N[K.Kc]="6",N[K.Ic]="7",N[K.gc]="8",N[K.xc]="9",N[K.Ra]="A",N[K.bb]="B",N[K.eb]="C",N[K.ib]="D",N[K.E]="E",N[K.kb]="F",N[K.lb]="G",N[K.mb]="H",N[K.nb]="I",N[K.qb]="J",N[K.rb]="K",N[K.tb]="L",N[K.vb]="M",N[K.xb]="N",N[K.zb]="O",N[K.Ab]="P",N[K.Q]="Q",N[K.Bb]="R",N[K.Db]=
"S",N[K.Eb]="T",N[K.Fb]="U",N[K.Gb]="V",N[K.Hb]="W",N[K.Ib]="X",N[K.Jb]="Y",N[K.Wa]="Z",N[K.ub]="Left",N[K.Va]="Right",N),Ia=["","moz","ms","webkit"],cb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},I={Sa:void 0,ua:"PCjs.localStorage"};C.WebIO=G;
function O(a,b,c,d){G.call(this,a==b);this.I=a;this.V=b;P[this.I]||(P[this.I]={});P[this.I][this.V]&&this.w("warning: machine configuration contains multiple '%s' devices\n",this.V);P[this.I][this.V]=this;this.id=this.I+"."+this.V;db.push(this);this.J=eb(this,this.I);this.ready=!0;fb(this,c,d);this.Cc={};this.pb=[]}r(O,G);
function fb(a,b,c){b=void 0===b?{}:b;c=void 0===c?[]:c;c=b.overrides||c;if(c.length){var d,e=Ca;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,k=/([^&=]+)=?([^&]*)/g;f=k.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ca=e}d=e;for(var h in d)if(0<=c.indexOf(h)){e=d[h];f=void 0;var m;g=void 0;k=e;var l=10;if(k){l||(l=10);var t=0<k.indexOf(",");t&&(k=k.replace(/,/g,""));var n=m=k.charAt(0);"#"==m?(l=8,m=""):
"$"==m&&(l=16,m="");n!=m?k=k.substr(1):(n=m=k.substr(0,2),"0b"==m&&t||"^B"==m?(l=2,m=""):"0o"==m||"^O"==m?(l=8,m=""):"^D"==m?(l=10,m=""):"0x"==m&&(l=16,m=""),n!=m&&(k=k.substr(2)));n=m=k.slice(-1);"Y"==m||"y"==m?(l=2,m=""):"."==m?(l=10,m=""):"H"==m||"h"==m?(l=16,m=""):"K"==m?m="000":"M"==m?m="000000":"G"==m&&(m="000000000");n!=m&&(k=k.slice(0,-1)+m);n=0;10>=l&&(m=k.match(/(-?[0-9]+)B([0-9]*)$/))&&(k=m[1],n=35-((m[2]||35)&255));(l&&10!=l?16==l?null===k.match(/^-?[0-9a-f]+$/i):8==l?null===k.match(/^-?[0-7]+$/):
2!=l||null===k.match(/^-?[01]+$/):null===k.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(k,l))||(n&&(0>f&&(f+=Math.pow(2,36)),f=0<n?f*Math.pow(2,n):Math.trunc(f/Math.pow(2,-n))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[h]=f;F(a,"overriding "+a.V+" property '"+h+"' with "+e)}}a.s=b;Ga(a,b.bindings);b=void 0===b?{}:b;a.version=2;if(a.version){c="";var u;a.I!=a.V&&(u=eb(a,a.I).version)&&u!=a.version&&(c="Machine");c||(u=b.version)&&u>a.version&&(c="Config");c&&(u=a.L("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.Ce,a.version,c,u),a.error("%s\n\nClearing your browser's cache may resolve the issue.",u))}}function gb(a,b){var c;try{var d=P[a.I];if(d)for(c in d){var e=d[c];if(e.V!=e.I&&!b(e))return!1}return!0}catch(f){a.w("error while enumerating device '%s': %s\n",c,f.message)}return!1}O.prototype.xa=function(a,b){b=void 0===b?!1:b;if(a){var c=G.prototype.xa.call(this,a,b);if(void 0===c&&b){b=P[this.I];for(var d in b)if(c=b[d].M[a])break;c||(c=null);this.M[a]=c}}return c};
function eb(a,b,c){var d=b,e=a.I,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=P[e])&&f[b]||null;if(!b){for(f=0;f<db.length;f++)if(db[f].id===d){b=db[f];break}if(!b&&(void 0===c||c))throw Error(a.L('no "%s" device',d));}return b}function Q(a,b,c){var d=null,e=P[a.I];if(e)for(var f in e)if(e[f].s["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.L("no %s device",b));return d}function hb(a){return a==a.J&&a.ready?gb(a,function(b){return hb(b)}):a.ready}
function ib(a,b){b=void 0===b?a.ready:b;a.ready=b;if(hb(a)){for(;b=a.pb.pop();)b();a!=a.J&&ib(a.J)}}function jb(a,b){if(hb(a))return b(),!0;a.pb.push(b);return!1}
O.prototype.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&J(this,a)&&(void 0===this.ja&&(this.ja=Q(this,"Debugger",!1)),this.J.aa&A.ab&&(void 0===this.Y&&(this.Y=Q(this,"CPU")),this.Y))?(a=c.shift(),G.prototype.w.call(this,"%#06x: %s.%s\n",this.Y.Oa,this.V,this.L.apply(this,[a].concat(q(c))).trim())):G.prototype.w.call.apply(G.prototype.w,[this,a].concat(q(c)))};function kb(a,b){(a=P[a.I])&&delete a[b]}
O.prototype.Qb=function(a,b){(a=this.Cc[a])&&a.set&&a.set(b)};window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]));var P=window?window.PCjs.Machines:{},db=window?window.PCjs.Components:[];A.ab=1;A.Xb=2;A.ic=4;A.sc=8;A.Ac=16;A.Zb=32;A.qc=64;A.Hc=128;A.tc=256;A.ac=512;A.uc=1024;A.INT=2048;A.Qc=4096;A.Tc=8192;A.vc=16384;A.Ec=32768;A.Ha=65536;A.Oc=131072;A.jb=262144;A.ob=524288;A.sb=1048576;A.wc=2097152;A.Pc=4194304;
A.Ia=8388608;A.pc=16777216;A.md=4294967296;L.addr=A.ab;L.bus=A.Xb;L.fault=A.ic;L.memory=A.sc;L.ports=A.Ac;L.chips=A.Zb;L.kbd=A.qc;L.serial=A.Hc;L.misc=A.tc;L.cpu=A.ac;L.mmu=A.uc;L["int"]=A.INT;L.trap=A.Qc;L.video=A.Tc;L.monitor=A.vc;L.screen=A.Ec;L.time=A.Ha;L.timer=A.Oc;L.event=A.jb;L.input=A.ob;L.key=A.sb;L.mouse=A.wc;L.touch=A.Pc;L.warn=A.Ia;L.halt=A.pc;C.Device=O;
function lb(a,b,c){O.call(this,a,b,c);this.aa=A.ob;this.u=this.H=null;this.time=Q(this,"Time");this.J=Q(this,"Machine");this.X=H(this,"drag",!1);this.S=H(this,"scroll",!1);this.W=H(this,"hexagonal",!1);this.h=H(this,"releaseDelay",0,void 0);this.j=!1;a=this.s.map;this.b=this.c=null;if(a)if(a.length)this.b=a;else{this.c={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.c[f]={keys:g,
He:e,state:0}}}this.K=[];this.N=[];this.g=this.O=null;(a=this.M[mb])&&nb(this,a,this.xa(c.focusBinding,!0),this.s.location);this.ka()}r(lb,O);function ob(a,b){a.H=b}function pb(a,b,c){for(var d=0;d<a.K.length;d++){var e=a.K[d];e.id===b&&e.Ob(b,c)}}
function nb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.b||a.c){var e={};e.gd=d[0]||0;e.hd=d[1]||0;e.wa=d[2]||b.clientWidth;e.Ka=d[3]||b.clientHeight;e.La=d[4]||1;e.Pa=d[5]||1;e.Xc=d[6]||b.naturalWidth||e.wa;e.Zc=d[7]||b.naturalHeight||e.Ka;e.Tb=d[8]||0;e.Ub=d[9]||0;e.Wc=d[10]||0;e.Yc=d[11]||0;a.b?(e.Na=a.b.length,e.ya=a.b[0].length):(e.ya=e.La,e.Na=e.Pa,e.La=e.Pa=0);e.Kb=e.wa/(e.ya+e.ya*e.La)|0;e.Lb=e.Ka/(e.Na+e.Na*e.Pa)|0;e.Vc=e.Kb*e.La|0;e.Mb=e.Lb*e.Pa|0;e.Ca=e.Qa=-1;qb(a,b,e);rb(a,b,e);a.time&&
a.h&&(a.U=sb(a.time,"timerInputRelease",function(){0>e.Ca&&0>e.Qa&&tb(a,-1,-1)}))}if(a.b||a.c)a.time&&a.h&&(a.Z=sb(a.time,"timerKeyRelease",function(){ub(a)})),a.l=0,a.v="",a.m=[],d=b,c&&(d=c,a.g||"BUTTON"!=c.nodeName||(d=document,a.g=c,vb(a,b),a.O=b)),vb(a,d),a.g||(a.g=d)}function wb(a){a.h?xb(a.time,a.Z,a.h):ub(a)}
function vb(a,b){function c(e,f,g){var k=document.activeElement;a.w(A.sb+A.jb,"%s.onKey%s(%d): %5.2f (%s)\n",k.id||k.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.g&&e!=a.g&&e!=a.O?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=yb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=yb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=yb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function qb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.j){var e=a.g;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,zb,d,c)}});b.addEventListener("mousemove",function(d){a.j||R(a,b,Ab,d,c)});b.addEventListener("mouseup",function(d){a.j||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.j||(0>c.Ca?R(a,b,Ab,d,c):R(a,b,S,d,c))})}
function rb(a,b,c){b.addEventListener("touchstart",function(d){a.S&&(a.j=!0);R(a,b,zb,d,c)});b.addEventListener("touchmove",function(d){R(a,b,Ab,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function yb(a,b,c,d){if(void 0!=c){var e=$a[b]||b;var f=bb[b];var g=Bb[e];d=d&&d.location==ab.Va;g&Cb&&d&&(g>>=1);g&&(g&Db&&(c=!(a.a&g)),a.a=c?a.a|g:a.a&~g,pb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=Ya.Ra&&b<=Ya.Wa?a.a&(Eb|Fb)||(a.a|=Fb,pb(a,K.Ta,!0)):b>=Ya.Xa&&b<=Ya.z&&a.a&Fb&&(a.a&=~Fb,pb(a,K.Ta,!1));if(a.b){if(void 0!=c)return!1;for(e=0;e<a.b.length;e++)for(g=a.b[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.l?16>a.m.length&&a.m.push(b):(a.l=1,a.v=f,tb(a,d,e),pb(a,
f,!0),wb(a)),!0}if(a.c){if(void 0==c)return!0;b=Object.keys(a.c);for(e=0;e<b.length;e++)if(g=b[e],0<=a.c[g].keys.indexOf(f))return pb(a,g,c),a.c[g].state=c?1:0,!0}return!1}function ub(a){1==a.l?(a.l++,pb(a,a.v,!1),a.v="",tb(a,-1,-1),wb(a)):(a.l=0,a.m.length&&yb(a,a.m.shift()))}lb.prototype.ka=function(){this.a=0;this.R=this.T=-1};
function R(a,b,c,d,e){var f=-1,g=-1,k=!1,h=-1,m=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(h=d.targetTouches[0].clientX,m=d.targetTouches[0].clientY,k=1<d.targetTouches.length):(h=d.clientX,m=d.clientY);var l=d.target.getBoundingClientRect();h-=l.left;m-=l.top;h=e.Xc/b.offsetWidth*h|0;m=e.Zc/b.offsetHeight*m|0;var t=h-e.gd;var n=m-e.hd;var u=l=!1;var z=h>=e.Tb&&h<e.Tb+e.Wc&&m>=e.Ub&&m<e.Ub+e.Yc;if(0<=t&&t<e.wa&&0<=n+e.Mb||z)if(k||a.S||d.preventDefault(),0<=t&&t<e.wa&&0<=
n&&n<e.Ka){u=!0;d=e.wa/e.ya|0;var x=e.Ka/e.Na|0,B=t/d|0,v=n/x|0;!a.W||v&1||(t-=d>>1,B=t/d|0,B==e.ya-1&&(t=-1));x=v*x+(e.Mb>>1);t-=B*d+(e.Vc>>1);n-=x;0<=t&&t<e.Kb&&0<=n&&n<e.Lb&&(f=B,g=v,l=!0)}}t=t||0;n=n||0;d=b.offsetWidth;b=b.offsetHeight;if(c==zb||c==S)for(B=0;B<a.N.length;B++)v=a.N[B],c==S?v.Ob(v.id,!1):(x=n/(b/v.Ee|0)|0,(t/(d/v.De|0)|0)==v.Se&&x==v.Te&&v.Ob(v.id,!0));if(!k)if(c==zb)e.Ca=h,e.Qa=m,u?(tb(a,f,g),l&&a.h&&xb(a.time,a.U,a.h,!0)):z&&a.J.ca();else if(c==Ab)0<=e.Ca&&0<=e.Qa&&a.X?tb(a,f,
g):a.H&&a.H(f,g);else if(c==S){if(c=a.h)c=a.time,f=a.U,c=c.a&&0<f&&f<=c.b.length?0<=c.b[f-1].ba:!1;c||tb(a,-1,-1);e.Ca=e.Qa=-1}else F(a,"unrecognized action: "+c)}function tb(a,b,c){if(b!=a.R||c!=a.T)a.R=b,a.T=c,a.u&&a.u(b,c)}var zb=1,Ab=2,S=3,mb="surface",Eb=3,Cb=170,Fb=512,Db=3584,T={},Bb=(T[K.Jc]=2,T[K.cc]=8,T[K.Wb]=32,T[K.fb]=128,T[K.Ta]=Fb,T[K.yc]=1024,T[K.Fc]=2048,T);C.Input=lb;
function Gb(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.M[Hb];if(!a)throw Error("LED "+this.s.M[Hb]+" binding for '"+Hb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.qa=Ja(this,Hb)+".canvas";b.setAttribute("id",this.qa);this.yb=a;this.type=Ma(H(this,"type",Ib,Jb),Kb,Lb);this.g=Mb[this.type][0];this.m=Mb[this.type][1];this.width=H(this,"width",
this.g,void 0);this.height=H(this,"height",this.m,void 0);this.h=H(this,"cols",1,void 0);this.K=this.h+H(this,"colsExtra",0,void 0);this.X=H(this,"rows",1,void 0);this.R=this.X+H(this,"rowsExtra",0,void 0);this.$=this.width*this.h;this.T=this.height*this.X;this.l=Nb("black",0);this.c=Ob(this.s.color)||this.l;this.ha=Nb(this.c,1,.25);this.ga=Nb(this.c,1,2);this.j=Ob(this.s.backgroundColor);this.ma=H(this,"fixed",!1);this.ma||(b.style.width="100%",b.style.height="auto");this.fa=H(this,"hexagonal",!1);
this.pa=H(this,"highlight",!0);this.S=H(this,"persistent",this.type<Lb);b.setAttribute("width",this.$.toString());b.setAttribute("height",this.T.toString());b.style.backgroundColor=this.l;a.appendChild(b);this.da=b.getContext("2d");if(this.u=document.createElement("canvas"))this.u.width=this.Z=this.g*this.h,this.u.height=this.v=this.m*this.X,this.b=this.u.getContext("2d");this.ra=(this.R+1)*this.K*4;this.a=Array(this.ra);this.Fa=this.h<this.K?4*(this.K-this.h):0;this.N=this.O=!1;this.H=this.W=0;this.U=
-1;var d=this;this.time=Q(this,"Time");Pb(this.time,function(e){Qb(d,!1,e)});Rb(d)}r(Gb,O);function Rb(a){for(var b=a.a,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Lb?Sb:" ";e[f+1]=d.c==d.l?null:d.c;e[f+2]=0;e[f+3]=Tb}a.N=a.O=!0;Qb(a,!0)}function Ub(a){a.j?(a.b.fillStyle=a.j,a.b.fillRect(0,0,a.Z,a.v)):a.b.clearRect(0,0,a.Z,a.v)}
function Qb(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.N||b){if(a.type<Lb){var d=0;if(!a.S||b)Ub(a);else if(a.H){d=a.h-a.H;var e=a.g*d;a.b.drawImage(a.u,a.g*a.H,0,e,a.v,0,0,e,a.v)}for(var f=e=0;f<a.R;f++){for(var g=0;g<a.h;g++){var k=a.a[e],h=a.a[e+1]||a.l,m=a.pa&&e==a.U;if(a.a[e+3]&Tb||m||b){if(g>=d)a:{var l=a,t=k;k=h;var n=g;h=f;var u=m;n=void 0===n?0:n;h=void 0===h?0:h;u=void 0===u?!1:u;var z=0;if(l.fa&&!(h&1)&&(z=l.g>>1,n==l.h-1))break a;if(k&&k!=l.c){u=u?Nb(k,1,2):k;var x=Nb(k,1,.25)}else u=
u?l.ga:l.c,x=l.ha;k=!1;t=t?u:x;u==l.l&&(t=l.j,k=!0);u=n*l.g+z;x=h*l.m;l.S&&(n=n*l.g+z,h*=l.m,l.j?(l.b.fillStyle=l.j,l.b.fillRect(n,h,l.g,l.m)):l.b.clearRect(n,h,l.g,l.m));l.b.fillStyle=t;h=Vb[l.type];3==h.length?(l.b.beginPath(),l.b.arc(u+h[0],x+h[1],h[2],0,2*Math.PI),k?(l.b.globalCompositeOperation="destination-out",l.b.fill(),l.b.globalCompositeOperation="source-over"):l.b.fill()):l.b.fillRect(u+h[0],x+h[1],h[2],h[3])}a.a[e+3]=m?a.a[e+3]|Tb:a.a[e+3]&~Tb}e+=4}e+=a.Fa}a.H=0}else{b="";for(d=0;d<a.a.length;d+=
4)b+=a.a[d]||" ",a.a[d+3]&Wb&&(b+=".");Ub(a);for(f=e=d=0;d<b.length;d++){h=b[d];"."==h&&e&&e--;g=a;m=e;l=f;m=void 0===m?0:m;l=void 0===l?0:l;if(h=Xb[h])for(k=0;k<h.length;k++)if(n=g,z=Yb[h[k]]){t=(void 0===m?0:m)*n.g;u=(void 0===l?0:l)*n.m;n.b.fillStyle=n.c;n.b.beginPath();if(3==z.length)n.b.arc(t+z[0],u+z[1],z[2],0,2*Math.PI);else for(x=0;x<z.length;x+=2)x?n.b.lineTo(t+z[x],u+z[x+1]):n.b.moveTo(t+z[x],u+z[x+1]);n.b.closePath();n.b.fill()}if(++e==a.h&&(e=0,++f==a.R))break}}a.da.globalCompositeOperation=
a.j&&a.c!=a.l?"source-over":"copy";a.da.drawImage(a.u,0,0,a.Z,a.v,0,0,a.$,a.T);a.N=!1;a.U=-1}else a.S||a.O||(!c||!a.W||c-a.W>=(1E3/60|0))&&Rb(a);a.O=!1;c&&(a.W=c)}function Ob(a){return(a=a||void 0)&&cb[a]||a}
function Nb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=cb[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Gb.prototype.ia=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.c&&c==this.j&&a&&a.length==this.a.length){this.a=a;for(b=0;b<=this.a.length-4;b+=4)this.a[b+1]==this.l&&(this.a[b+1]=null);Qb(this,!0);return!0}return!1};Gb.prototype.la=function(a){this.a&&(a.push(this.c),a.push(this.j),a.push(this.a))};
function Zb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&$b;b=4*(c*a.K+b);if(b<=a.a.length-4){if(a.a[b]!==d||(a.a[b+3]&$b)!==e)a.a[b]=d,a.a[b+3]=a.a[b+3]&~$b|e|Tb,a.N=f=!0;a.U=b;a.O=!0;a.H=0}return f}
var Kb=0,Ib=1,Lb=3,Jb={small:Kb,round:Ib,square:2,digit:Lb},Hb="container",Sb=0,$b=129,Wb=1,Tb=128,ac={},Vb=(ac[Kb]=[4,4,4],ac[Ib]=[16,16,14],ac[2]=[2,2,28,28],ac),Mb=[[8,8],[32,32],[32,32],[96,128]],Yb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Xb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};C.LED=Gb;
function bc(a,b,c){O.call(this,a,b,c);this.ga=H(this,"cyclesMinimum",1E5,void 0);this.ra=H(this,"cyclesMaximum",1E9,void 0);this.ha=Ma(H(this,"cyclesPerSecond",1E6,void 0),this.ga,this.ra);this.R=1E3/60;this.Bc=H(this,"updatesPerSecond",2,void 0)||2;this.zc=1E3/this.Bc;this.qa=0;this.Dc=H(this,"timeLock",!0);this.da=this.K=0;this.$=this.l=1;this.pa=this.u=this.ha/1E4/100;this.X=[];this.v=[];this.b=[];this.Z=[];this.ma=this.a=this.W=this.m=!1;this.H=this.g=0;a=Ha("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.R}this.Fa=window[a].bind(window,this.dd.bind(this),d);this.yb=window[Ha("cancelAnimationFrame")||"clearTimeout"].bind(window);this.U=this.T=this.h=this.c=this.fa=0;cc(this)||dc(this,this.$)}r(bc,O);function Pb(a,b){a.X.push(b)}p=bc.prototype;
p.va=function(a,b){var c=this;switch(a){case ec:b.onclick=function(){fc(c)&&(c.a?U(c):c.start())};break;case gc:b.onclick=function(){dc(c,c.l<<1);hc(c,ic(c.u))};break;case jc:b.onclick=function(){kc(c)};break;case lc:b.addEventListener("mousedown",function(){c.m=!0}),b.addEventListener("mouseup",function(){cc(c);c.m=!1}),b.addEventListener("mousemove",function(){c.m&&cc(c)}),b.addEventListener("change",function(){c.m=!0;cc(c);c.m=!1})}O.prototype.va.call(this,a,b)};
function sb(a,b,c){var d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,Uc:c,Ma:d,ba:-1});0<=d&&xb(a,e,d);return e}
function mc(a,b,c,d){var e=0,f=a.u,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.w(A.Ha,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.R&&(1<a.l&&(a.l>>=1,a.w(A.Ia,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.R,a.l)),e=d));a.K=f;a.da=f/a.pa;b=a.da/a.l;a.fa=g/b/60+1E-8;a.w(A.Ha,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.fa,g,b,60);return e}
function nc(a,b){a.T=a.h=b;if(!a.v.length)return a.h=0,a.T;for(var c=0;0<a.h;){if(c<a.v.length){var d=a.v[c++];b=d.ed.call(d,b)||1}else c=b=0;a.h-=b}return a.T-a.h}function oc(a,b){var c=Date.now();b()&&(a.S+=Date.now()-c)}function pc(a,b){b=void 0===b?a.T-a.h:b;if(!a.a){if(a.c)for(var c=0;c<a.v.length;c++){var d=a.v[c];d.Rb.call(d)}a.c=b}a.c-=b;1>a.c&&(a.W=!0);a.U+=b;a.T=a.h=0;a.a||(a.U=0);return b}
function qc(a,b){b=void 0===b?0:b;if(b){var c=b;a.c+=b}else for(c=a.c,1>c&&(c=a.c+=a.fa),0>c&&(a.w(A.Ia,"warning: cycle count dropped below zero: %f\n",c),c=a.c=0),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.ba)&&c>d.ba&&(c=d.ba)}return c}function ic(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function fc(a){return a.ma?!0:(F(a,"not powered"),!1)}
function rc(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.ba||(d.ba-=b,0>=d.ba&&(d.ba=-1,d.Uc(),0<=d.Ma&&xb(a,c,d.Ma)))}}p.ca=function(a){this.ma=a;void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};function kc(a,b){fc(a)&&(a.a?F(a,"already running"):a.g?U(a):sc(a,b))}
p.dd=function(a){a=void 0===a?Date.now():a;this.H=0;if(this.a){var b=Date.now();if(this.N){var c=b-this.O-this.R;c>this.R&&(this.j+=c,this.w(A.Ia,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.O=b;this.j||(this.j=b);this.S=0;try{this.W=!1;do rc(this,pc(this,nc(this,qc(this))));while(this.a&&!this.W)}catch(d){F(this,d.message),U(this)}this.N=Date.now();this.S&&(this.j+=this.S,this.O+=this.S);this.O+=mc(this,this.U,this.N-this.j,this.N-this.O);this.N-this.qa>=this.zc&&this.update();
for(b=0;b<this.X.length;b++)this.X[b](a);this.H=this.Fa()}};function dc(a,b){if(void 0!==b){if(1>b||!a.m&&0<a.K&&a.K<.9*a.u)b=a.$;a.l=b;b=a.pa*a.l;a.u!=b&&(a.u=b,hc(a,ic(a.u)))}a.j=a.N=0;a.c=a.U=0;mc(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.Ma&&xb(a,b,c.Ma,!0)}}function cc(a){var b=a.M[lc];return b?(dc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.ra-a.ga)+a.ga)/a.ha|0),!0):!1}
function xb(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.ba)&&(c=Math.ceil(a.ha*(a.Dc?a.$:a.da)/1E3*(void 0===c?1E3:c)),a.a&&(c+=pc(a)),b.ba=c)}p.start=function(){if(this.a||this.g)return!1;this.a=!0;this.j=this.N=0;this.update(!0);this.H=this.Fa();return!0};function sc(a,b){b=void 0===b?1:b;a.a||(b&&!a.g&&(a.g=b),a.g&&(a.g--,rc(a,pc(a,nc(a,qc(a,1)))),a.update(!1),a.g&&setTimeout(function(){sc(a,0)},0)))}
function U(a){return a.a?(a.a=!1,pc(a),a.H&&(a.yb(a.H),a.H=0),a.update(!0),!0):a.g?(a.g=0,a.update(!0),!0):!1}p.update=function(a){a&&F(this,this.a?"started with "+ic(this.u)+" target":"stopped");M(this,ec,this.a?"Halt":"Run");M(this,jc,this.g?"Stop":"Step");this.m||(this.w(A.Ha,"getSpeedCurrent(%5.3fhz)\n",1E6*this.K),hc(this,this.a&&this.K?ic(this.K):"Stopped"));for(var b=0;b<this.Z.length;b++){var c=this.Z[b];c.ad.call(c,void 0!=a)}this.qa=Date.now();this.W=!0};
function hc(a,b){M(a,tc,b);M(a,gc,b)}var ec="run",gc="setSpeed",tc="speed",jc="step",lc="throttle";C.Time=bc;
function uc(a,b,c){O.call(this,a,b,c);this.type="static"==this.s.type?vc:wc;this.l=this.s.addrWidth||16;this.g=Math.pow(2,this.l);this.u=this.g-1|0;this.b=this.s.blockSize||(16<this.l?4096:1024);this.b>this.g&&(this.b=this.g);this.v=this.g/this.b|0;this.c=Math.log2(this.b)|0;this.h=(1<<this.c)-1;this.m=this.s.dataWidth||8;this.a=Array(this.v);this.j=0;a=new V(a,b+"[NONE]",{size:this.b,bus:this.V});for(b=0;b<this.g;b+=this.b)xc(this,b,this.b,W.NONE,a);a=this.j;this.j+=this.type;a&&this.j||(this.za=
this.Yb,this.Aa=this.Ba)}r(uc,O);
function xc(a,b,c,d,e){for(var f=b>>>a.c;0<c&&f<a.a.length;){var g=f*a.b,k=a.b-(b-g);k>c&&(k=c);var h=a.a[f];if(b!=g||k!=a.b||h&&h.type!=W.NONE)break;var m=h=void 0,l=b,t=a.l,n=16;t=void 0===t?0:t;h=void 0===h?0:h;var u="",z="",x=-1;n||(n=a.H||10);t&&(x=Math.ceil(t/Math.log2(n)));if(void 0==m)switch(n){case 8:m="0o";break;case 16:m="0x";break;case 10:z=".";default:m=""}isNaN(l)||"number"!=typeof l?(l=void 0,m=z=""):(0>l&&-1<l&&(l=-1),t&&(0>l&&(l+=Math.pow(2,t)),l>=Math.pow(2,t)&&(x=Math.ceil(Math.log(l)/
Math.log(n)))));for(t=h||-1;x--;){t||(u=","+u,t=h);if(void 0==l){if(u="?"+u,0>x)break}else{var B=l%n;l=Math.trunc(l/n);B+=0<=B&&9>=B?48:55;u=String.fromCharCode(B)+u;if(!l&&0>x)break}t--}h=a.V+"["+(m+u+z)+"]";b=e?e.size==a.b?e:new V(a.I,h,{type:d,Ja:b,size:k,bus:a.V}):new V(a.I,h,{type:d,Ja:b,size:k,bus:a.V});a.a[f]=b;b=g+a.b;c-=k;f++}}p=uc.prototype;p.ca=function(){void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};p.ka=function(){};p.Ya=function(a){return a&&this.ia(a)?!0:!1};p.Za=function(a){this.la(a)};
p.ia=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if((this.type==wc||c.type&W.Ga)&&c.ia){var d=a.shift();if(!c.ia(d))return!1}}return!0};p.la=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if((this.type==wc||c.type&W.Ga)&&c.la){var d=[];c.la(d);a.push(d)}}};p.sa=function(a){return this.a[a>>>this.c].sa(a&this.h)};p.Yb=function(a){return this.a[a>>>this.c].za(a&this.h)};p.$a=function(a,b){this.a[a>>>this.c].$a(a&this.h,b)};
p.Ba=function(a,b){this.a[a>>>this.c].Aa(a&this.h,b)};var vc=0,wc=1;C.Bus=uc;
function V(a,b,c){O.call(this,a,b,c);this.Ja=this.s.addr;this.size=this.s.size;this.type=this.s.type||W.NONE;this.g=(a=this.s.bus)?eb(this,a):Q(this,a="Bus");if(!this.g)throw Error(this.L("unable to find bus '%s'",a));this.j=this.g.m;this.u=Math.pow(2,this.j)-1;this.h=this.m=!1;this.values=this.c=null;a=this.wb;b=this.Ba;if(this.g.type==vc){b=this.fd;if(c=8==this.j)c=eb(this,this.I),c=!1!==(c&&c.s&&c.s.ArrayBuffer||this.s.ArrayBuffer);c&&(this.m=!0)}switch(this.type){case W.NONE:this.za=this.cd;this.Aa=
this.Sb;break;case W.Cb:this.za=a;this.Aa=this.Sb;break;case W.Ga:this.za=a,this.Aa=b}yc(this,this.s.values);zc(this)}r(V,O);function yc(a,b){"string"==typeof b?(ib(a,!1),Na(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);yc(a,g.values)}catch(k){a.w("error (%s) parsing resource: %s\n",k.message,c)}ib(a,!0)}else a.w("error (%d) loading resource: %s\n",f,c)})):a.s.values=b}
function zc(a,b){if(a.type>W.NONE&&(a.m?(a.c=new ArrayBuffer(a.size),new DataView(a.c,0,a.size),a.values=new Uint8Array(a.c,0,a.size),new Uint16Array(a.c,0,a.size>>1),new Int32Array(a.c,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}p=V.prototype;
p.ka=function(){if(this.s.values)a:{var a=this.g,b=this.Ja,c=this.size,d=this.s.values,e=0,f=b&a.h;b>>>=a.c;c>d.length&&(c=d.length);for(;0<c&&b<a.a.length;){var g=a.a[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Ba(f++,d[e++]),c--;f=0}}else this.type&W.Ga&&this.values&&this.values.fill(0)};p.cd=function(){return this.u};p.sa=function(a){return this.values?this.values[a]:0};p.wb=function(a){return this.values[a]};p.Sb=function(){};p.$a=function(a,b){this.values&&(this.values[a]=b)};
p.Ba=function(a,b){this.values[a]=b};p.fd=function(a,b){this.values[a]=b;this.h=!0;this.Aa=this.Ba};p.ia=function(a){var b=a.shift();if(this.V==b){this.h=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}zc(this,a)}return!0}return!1};p.la=function(a){a.push(this.V);a.push(this.h);a.push(!1);a.push(this.values?ua(this.values):this.values)};var W={NONE:1,Cb:2,Ga:4,ve:14,ze:12};
C.Memory=V;
function Ac(a,b,c){c.type=W.Cb;V.call(this,a,b,c);xc(this.g,this.s.addr,this.s.size,this.s.type,this);jb(this,this.ka.bind(this));this.Y=this.ja=void 0;if(C.LED&&this.M[Bc]){var d=this;this.b=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.l=this.values.length/this.b|0;this.a=new Gb(a,b+"LEDs",{"class":"LED",bindings:{container:Ja(this,Bc)},type:Ib,cols:this.b,rows:this.l,color:H(this,"colorROM","green"),backgroundColor:H(this,"backgroundColorROM","black"),persistent:!0}),Rb(this.a);this.v=
new lb(a,b+"Input",{"class":"Input",location:[0,0,this.a.$,this.a.T,this.b,this.l],bindings:{surface:Ja(this,Bc)}});this.H=Ka(this)||"";ob(this.v,function(e,f){if(d.Y){var g=d.H;0<=e&&0<=f&&(e=f*d.b+e,g=Cc(d.Y,d.Ja+e,d.values[e]));M(d,La,g)}})}}r(Ac,V);
Ac.prototype.ia=function(a){var b=!0,c=a.shift();if(c&&this.a){var d=c.length;this.a.a.length==d?(this.a.a=c,Qb(this.a,!0)):(this.w("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.w("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};Ac.prototype.ca=function(){void 0===this.Y&&(this.Y=Q(this,"CPU"));void 0===this.ja&&(this.ja=Q(this,"Debugger",!1))};
Ac.prototype.wb=function(a){this.a&&Zb(this.a,a%this.b,a/this.b|0,1,Tb);return this.values[a]};Ac.prototype.la=function(a){this.a&&(a.push(this.a.a),a.push(this.values))};var Bc="array",La="cellDesc";C.ROM=Ac;function Dc(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.ja=void 0;this.b=this.Oa=0;this.time=Q(this,"Time");this.time.v.push(this);this.time.Z.push(this);this.T=this.j=0}r(Dc,O);p=Dc.prototype;p.abort=function(a){this.b=this.Oa;F(this,a.message);U(this.time)};p.Nb=function(){};
p.ed=function(a){this.T=this.j=a=void 0===a?0:a;try{this.Nb(a)}catch(b){this.abort(b)}return this.Pb()};p.Rb=function(){this.T-=this.j;this.j=0};p.Pb=function(){return this.T-this.j};function X(a,b,c){O.call(this,a.I,b);this.Y=a;this.name=b;this.f=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.ha[c]=[this,-1];for(var d=0;d<this.f.length;d++)c=this.L("reg%s-%02d",this.name,d),b.push(c),a.ha[c]=[this,d];Ga(a,b)}}r(X,O);p=X.prototype;
p.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.f[f]=a.f[f]+b.f[f]+e,e=0,this.f[f]>=d&&(this.f[f]-=d,e=1);e&&(this.Y.l=!0);Ec(this,c)};p.get=function(){return this.f};function Fc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.f.length;d++)a.f[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.f[d]=b&15,b>>>=4;return a}p.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.f[e]=a.f[e]+d,d=0,this.f[e]>=c&&(this.f[e]-=c,d=1);Ec(a,b)};
p.set=function(a){if(a&&a.length==this.f.length)for(var b=0;b<this.f.length;b++)this.f[b]=a[b]};p.store=function(a){for(var b=0,c=this.f.length;b<c;b++)this.f[b]=a.f[b]};p.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.f[f]=a.f[f]-b.f[f]-e,e=0,0>this.f[f]&&(this.f[f]+=d,e=1);e&&(this.Y.l=!0);Ec(this,c)};p.toString=function(a){a=void 0===a?!1:a;var b=this.V+"=";a&&3>b.length&&(b+=" ");for(var c=this.f.length-1;0<=c;c--)b=a?b+Aa[this.f[c]]:b+(Ba[this.f[c]]+(c%4?"":" "));return b};
function Ec(a,b){a.Y.h=a.f[b[0]];b[0]<b[1]&&(a.Y.h|=a.f[b[0]+1]<<4)}
function Gc(a,b,c){Dc.call(this,a,b,c);this.type=Number.parseInt(H(this,"type","1501").slice(-4),10);this.ha={};this.a=Array(4);for(a=0;4>a;a++)this.a[a]=new X(this,String.fromCharCode(65+a));this.O=this.a[0];this.U=this.a[1];this.pa=this.a[2];this.ra=this.a[3];this.K=Array(8);for(a=0;8>a;a++)this.K[a]=new X(this,"X"+a);this.R=Array(8);for(a=0;8>a;a++)this.R[a]=new X(this,"Y"+a);this.ma=new X(this,"Supp",!0);this.X=new X(this,"Temp",!0);this.H=10;this.l=!1;this.W=this.h=this.u=0;this.g=[-1,-1,-1];
this.qa=eb(this,this.s.input);this.qa.u=this.bc.bind(this);this.c=eb(this,this.s.output,!1);this.v=Q(this,"Bus");this.m=Q(this,"ROM");this.fa=this.ga=this.S=void 0;this.da=this.Z=-1;this.N={};this.$=Hc;a=this.$c.bind(this);b=Ta.gb;this.J.Ea[b]||(this.J.Ea[b]=[]);this.J.Ea[b].push(a)}r(Gc,Dc);function Ic(a,b){a.N[b]&&(a.N[b]=!1,F(a,"break on "+Jc[b]),U(a.time))}function Kc(a){a.c&&Rb(a.c);if(a.m){var b=a.m;b.a&&Rb(b.a)}Lc(a,!1)}p=Gc.prototype;
p.Nb=function(a){for(;0<this.j;){if(this.da==this.b){this.da=-1;F(this,"break");U(this.time);break}var b=this.v.za(this.b);this.b=(this.Oa=this.b)+1&this.v.u;if(void 0==b||!Mc(this,b)){this.b=this.Oa;F(this,"unimplemented opcode");U(this.time);break}this.j-=Nc}if(0>=a){var c=this;oc(this.time,function(){var d=c.m;d.a&&Qb(d.a);c.na(c.toString())})}};p.Rb=function(){this.j=0};p.Pb=function(){return this.T-this.j};
function Mc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.l&&(a.b=a.b&1024|b&1023):(a.push(a.b),a.b=b&2047),a.l=!1,!0;var c;var d=b&Oc;switch(d){case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:d=ad[d];var e=(b&bd)>>cd;var f=(b&dd)>>ed;var g=(b&fd)>>gd;var k=(c=b&hd)?id:jd;b=b>=Wc?16:a.H;switch(f){case 0:case 1:case 2:case 3:var h=a.a[f];break;case 4:h=Fc(a.X,1,d);break;case 5:k=c?kd:ld;break;case 6:h=Fc(a.X,a.h&15,d);break;case 7:h=Fc(a.X,a.h&255,d)}switch(g){case 0:var m=
a.a[e];break;case 1:m=4>f?a.a[f]:void 0;break;case 2:m=5>f?a.ma:5==f?a.a[e]:void 0;break;case 3:if(c)a.a[e].move(h,d,b);else{a=a.O;e=h;b=d[0];for(h=d[1];b<=h;b++)m=a.f[b],a.f[b]=e.f[b],e.f[b]=m;Ec(e,d)}return!0}if(!m)break;switch(k){case jd:m.add(a.a[e],h,d,b);break;case id:m.sub(a.a[e],h,d,b);break;case ld:b=m;a=a.a[e];e=d[1];for(h=d[0];e>h;e--)b.f[e]=a.f[e-1];b.f[e]=0;Ec(b,d);break;case kd:b=m;a=a.a[e];e=d[0];for(h=d[1];e<h;e++)b.f[e]=a.f[e+1];b.f[e]=0;Ec(b,d)}return!0;case md:e=(b&nd)>>od;d=(b&
pd)>>qd;h=1<<((b&rd)>>sd);if(!d)break;d+=12;switch(b&td){case ud:a.a[e].f[d]|=h;break;case vd:a.a[e].f[d]&=~h;break;case wd:a.a[e].f[d]&h&&(a.l=!0);break;case xd:a.a[e].f[d]^=h}return!0;case yd:switch(b&zd){case Ad:a.O.store(a.R[a.u]);break;case Bd:a.u=b>>4&7;break;case Cd:a.b=a.h;break;case Dd:a.l=!1;d=a.g[0];e=0;for(b=a.g.length-1;e<b;)a.g[e]=a.g[++e];a.g[e]=-1;a.b=d;break;case Ed:a.K[a.u].store(a.O);break;case Fd:a.O.store(a.K[a.u]);break;case Gd:a.R[a.u].store(a.O);break;case Hd:Ic(a,"o");if(a.c){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.U.f[e]&8?b=" ":a.U.f[e]&1?b="-":b=Aa[a.O.f[e]],Zb(a.c,d,0,b,a.U.f[e]&2?Wb:0)&&Ic(a,"om");Lc(a)}a.j-=31*Nc;a.W&&(a.h=a.W,a.l=!0,Ic(a,"i"));break;case Id:a.H=10;break;case Jd:a.H=16;break;case Kd:a.u=a.h&7;break;default:return!1}return!0}return!1}
p.ia=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return F(this,"invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.w("saved state version mismatch: %3.2f\n",c),!1;try{this.a.forEach(function(d){return d.set(b.shift())}),this.K.forEach(function(d){return d.set(b.shift())}),this.R.forEach(function(d){return d.set(b.shift())}),this.ma.set(b.shift()),this.X.set(b.shift()),this.H=b.shift(),this.l=b.shift(),this.u=b.shift(),this.h=b.shift(),this.b=b.shift(),this.g=b.shift(),this.W=
b.shift()}catch(d){return F(this,"CPU state error: "+d.message),!1}return(a=a.stateROM||a[1])&&this.m&&!this.m.ia(a)?!1:!0};
p.$c=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,k=3;k<a.length;k++)d.push(Number.parseInt(a[k],16));this.$=Hc;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Jc)c=Jc[f],b+="break on "+c+" (b"+f+"): "+(this.N[f]||!1)+"\n";break}(c=Jc[f])?(this.N[f]=!this.N[f],b="break on "+c+" (b"+f+"): "+this.N[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.v.sa(f);if(void 0==
a)break;this.v.$a(f,d[g]);b+=this.L("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.L("%d locations updated\n",c);break;case "g":this.time.start()?this.da=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.$=Ld);g=Number.parseInt(a[2],10)||1;kc(this.time,g);break;case "r":"c"==e[1]&&(this.$=Ld);this.Qb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.Z?this.Z:this.b;g--;){c=this.m&&this.v.sa(f);if(void 0==
c)break;b+=Cc(this,f++,c)}this.Z=f;break;case "?":b="additional commands:\n";Md.forEach(function(h){b+=h+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};p.bc=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.W=c};p.Ya=function(a){return a&&this.ia(a)?!0:!1};p.ca=function(a){a?this.time.start():(U(this.time),Kc(this))};p.ka=function(){F(this,"reset");this.b=0;Kc(this);this.time.a||this.na(this.toString())};p.Za=function(a){this.la(a)};
p.ad=function(a){for(var b in this.M){var c=this.ha[b];if(c){var d=c[0];c=c[1];M(this,b,0>c?d.toString():Aa[d.f[c]])}}a&&!this.time.a&&(a=this.m,a.a&&Qb(a.a),this.na(this.toString()))};p.push=function(a){for(var b=this.g.length-1;0<b;)this.g[b]=this.g[--b];this.g[0]=a};
p.la=function(a){var b=[],c=[];b.push(2);this.a.forEach(function(d){return b.push(d.get())});this.K.forEach(function(d){return b.push(d.get())});this.R.forEach(function(d){return b.push(d.get())});b.push(this.ma.get());b.push(this.X.get());b.push(this.H);b.push(this.l);b.push(this.u);b.push(this.h);b.push(this.b);b.push(this.g);b.push(this.W);this.m&&this.m.la(c);a.push(b);a.push(c)};p.Qb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.b=b;break;default:F(this,"unrecognized register: "+a)}};
function Cc(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.L("%#06x",f);else if(0<=c){var g=c&Oc;var k;switch(g){case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:f="";e=ad[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&bd)>>cd;var h=(c&dd)>>ed;var m=(c&fd)>>gd;var l=c&hd;e="LOAD";var t=k="?";var n=l?5==h?">>":"-":5==h?"<<":"+";switch(m){case 0:k=
Y[g];break;case 1:4>h&&(k=Y[h]);break;case 2:6>h&&(k="NUL");break;case 3:l?(e="MOVE",k=Y[g],t=Y[h]):(e="XCHG",g||(k="A"),4>h&&(t=Y[h])),h=-1}switch(h){case 0:case 1:case 2:case 3:t=Y[g]+n+Y[h];break;case 4:case 5:t=Y[g]+n+"1";break;case 6:t=Y[g]+n+"R5L";break;case 7:t=Y[g]+n+"R5"}f=k+","+t+","+f;break;case md:switch(c&td){case ud:e="SET";break;case vd:e="CLR";break;case wd:e="TST";break;case xd:e="NOT"}f=a.a[(c&nd)>>od].name;g=(c&pd)>>qd;f+="["+(g?g+12:"?")+":"+((c&rd)>>sd)+"]";break;case yd:switch(c&
zd){case Ad:e="STORE";f="A,Y[RAB]";break;case Bd:e="STORE";f="RAB,"+((c&112)>>4);break;case Cd:e="BR";f="R5";break;case Dd:e="RET";break;case Ed:e="STORE";f="X[RAB],A";break;case Fd:e="STORE";f="A,X[RAB]";break;case Gd:e="STORE";f="Y[RAB],A";break;case Hd:e="DISP";break;case Id:e="BCDS";break;case Jd:e="BCDR";break;case Kd:e="STORE",f="RAB,R5L"}}}return a.L(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
p.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.$){this.m&&(d+=Cc(this,this.b,this.v.sa(this.b),!0));d+="  ";b=0;for(a=this.a.length;b<a;b++)d+=this.a[b].toString()+" ";d+="\n ";d+=" COND="+(this.l?1:0);d+=" BASE="+this.H;d+=" R5="+this.L("%02X",this.h);d+=" RAB="+this.u+" ST=";this.g.forEach(function(f){d+=c.L("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.a);0<=a.indexOf("a")&&(d+=this.toString(a,this.K),d+=this.toString(a,this.R));d+="COND="+(this.l?1:0);d+=" BASE="+this.H;d+=" R5="+this.L("%#04x",this.h);d+=" RAB="+this.u+" ";this.g.forEach(function(f,g){d+=c.L("ST%d=%#06x ",g,f&65535)});this.m&&(d+="\n"+Cc(this,this.b,this.v.sa(this.b)));this.Z=this.b;return d};
function Lc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Nd?!!(a.pa.f[14]&8):!!(a.U.f[15]&4));if(a.fa!==d){if(c=a.M["2nd"])c.style.opacity=d?"1":"0",void 0===a.fa&&a.c&&(c.style.color=a.c.color);a.fa=d}d=b&&(a.type==Nd?!!(a.U.f[15]&4):!!(a.ra.f[15]&8));if(a.ga!==d){if(c=a.M.INV)c.style.opacity=d?"1":"0",void 0===a.ga&&a.c&&(c.style.color=a.c.color);a.ga=d}c=a.type==Nd?a.K[4].f[15]>>2:a.pa.f[15];b=b?c?1==c?Od:Pd:Qd:Rd;if(a.S!==b){if(c=a.M.Deg)c.style.opacity=b==Qd?"1":"0",void 0===a.S&&a.c&&(c.style.color=
a.c.color);if(c=a.M.Rad)c.style.opacity=b==Od?"1":"0",void 0===a.S&&a.c&&(c.style.color=a.c.color);if(c=a.M.Grad)c.style.opacity=b==Pd?"1":"0",void 0===a.S&&a.c&&(c.style.color=a.c.color);a.S=b}}
var Oc=3840,Pc=0,Qc=256,Rc=512,Sc=768,Tc=1024,Uc=1280,Vc=1792,Wc=2048,Xc=2304,Yc=2560,md=3072,Zc=3328,yd=3584,$c=3840,bd=192,cd=6,dd=56,ed=3,fd=6,gd=1,hd=1,td=3,ud=0,vd=1,wd=2,xd=3,nd=192,od=6,pd=48,qd=4,rd=12,sd=2,zd=15,Ad=0,Bd=1,Cd=2,Dd=3,Ed=4,Fd=5,Gd=6,Hd=7,Id=8,Jd=9,Kd=10,Z={},ad=(Z[Pc]=[12,12],Z[Qc]=[0,15],Z[Rc]=[2,12],Z[Sc]=[0,12],Z[Tc]=[2,2],Z[Uc]=[0,1],Z[Vc]=[0,13],Z[Wc]=[14,14],Z[Xc]=[13,15],Z[Yc]=[14,15],Z[Zc]=[13,13],Z[$c]=[15,15],Z),Nc=128,jd=0,id=1,ld=2,kd=3,Nd=1501,Rd=0,Qd=1,Od=2,Pd=
3,Jc={i:"input",o:"output",om:"output modification"},Hc=0,Ld=1,Y="A B C D 1 ? R5L R5".split(" "),Md="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");C.CPU1500=Gc;
function Sd(a,b,c){O.call(this,a,a);var d=this;this.c=!1;this.l=c;this.b="";this.j=this.h=!1;ib(this,!1);this.aa=A.ec;b=b.trim();"{"==b[0]?Td(this,b):(this.b=b,Na(this.b,function(e,f,g,k){4==g&&(!k&&f?(Td(d,f),Ud(d)):d.w("error (%d) loading configuration: %s\n",k,e))}));window.addEventListener("load",function(){d.j=!0;Ud(d)});window.addEventListener(Pa("iOS")?"pagehide":Pa("Opera")?"unload":"beforeunload",function(){Vd(d)});window.addEventListener("pageshow",function(){d.c||d.ca(!0)})}r(Sd,O);
Sd.prototype.va=function(a,b){var c=this;switch(a){case Wd:b.onclick=function(){c.ca()};break;case Xd:b.onclick=function(){c.ka()}}O.prototype.va.call(this,a,b)};
function Ud(a){var b=!0;if(a.h&&a.j){for(var c in a.a){var d=void 0,e=a.a[c];try{d=e["class"],C[d]?"Machine"==d?(a.w("PCjs %s v%3.2f\n%s\n",e.name,2,Yd),a.b&&a.w("Configuration: %s\n",a.b)):new C[d](a.I,c,e):a.w('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.w('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),kb(a,c)}}if(a.g){var f=Qa(a);gb(a,function(g){return g.Ya&&!g.Ya(f)?(g.w('unable to restore state for device "%s"\n',g.V),!1):!0})}ib(a,!0);jb(a,a.ca.bind(a,b))||a.w("machine %s not ready to power, waiting for device(s)\n",
a.I)}}function Td(a,b){try{a.a=JSON.parse(b);var c=a.a[a.I];if(!c){c=a.a[wa(a.b)];if(!c)throw Error("configuration missing machine ID");a.a[a.I]=c}fb(a,c,["autoSave","autoStart"]);a.g=!1!==a.s.autoSave;a.m=!1!==a.s.autoStart;if(a.l){var d=eval("("+a.l+")"),e;for(e in d)a.s[e]=d[e]}a.h=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),F(a,"machine '"+a.I+"' initialization error: "+c)}}
Sd.prototype.ca=function(a){a=void 0===a?!this.c:a;if(hb(this)){var b=this;a&&F(this,"power on");gb(this,function(c){c.ca&&c!=b&&("CPU"!=c.s["class"]||b.m||hb(b)?c.ca(a):c.time.update(!0));return!0});(this.c=a)||F(this,"power off")}};Sd.prototype.ka=function(){if(hb(this)){var a=this;gb(this,function(b){b.ka&&b!=a&&b.ka();return!0});F(this,"reset")}};function Vd(a){if(a.g){var b=[];gb(a,function(c){c.Za&&c.Za(b);return!0});Xa(a,b)}a.ca(!1)}var Wd="power",Xd="reset",Yd="Copyright \u00a9 2012-2020 Jeff Parsons <Jeff@pcjs.org>";
window.TMS1500=function(a,b,c){var d=new Sd(a,b,c);window.command=function(e){return Ra(d,e)};return d};C.Machine=Sd;})()

//# sourceMappingURL=ti42.js.map
