(function(){/*
 https://www.pcjs.org/modules/v3/defines.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/message.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/format.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/numio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/stdio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/webio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/device.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/input.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/led.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/time.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/bus.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/memory.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/rom.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/cpu.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/cpu1500.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/machine.js (C) 2012-2023 Jeff Parsons
*/
var q;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function r(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)a=b.call(a);else if("number"==typeof a.length)a={next:aa(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function t(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function z(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.qe=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
t("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
t("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});t("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
t("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});t("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
t("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}t("Array.prototype.keys",function(a){return a?a:function(){return na(this,function(b){return b})}});
t("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function A(a){return a?a:Array.prototype.fill}t("Int8Array.prototype.fill",A);t("Uint8Array.prototype.fill",A);t("Uint8ClampedArray.prototype.fill",A);t("Int16Array.prototype.fill",A);t("Uint16Array.prototype.fill",A);t("Int32Array.prototype.fill",A);
t("Uint32Array.prototype.fill",A);t("Float32Array.prototype.fill",A);t("Float64Array.prototype.fill",A);t("Number.parseInt",function(a){return a||parseInt});t("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});function oa(){}var pa=new ArrayBuffer(2);(new DataView(pa)).setUint16(0,256,!0);new Uint16Array(pa);"undefined"==typeof window||window.PCjs||(window.PCjs={machines:{},components:[],commands:{}});
var B="undefined"!=typeof window?window.PCjs.machines:{},qa="undefined"!=typeof window?window.PCjs.components:[],C={};C.Defines=oa;
var ra={all:0xffffffffffff,addr:1,bus:2,fault:4,memory:8,ports:16,chips:32,kbd:64,serial:128,misc:256,cpu:512,mmu:2048,"int":1024,trap:4096,video:8192,monitor:16384,screen:32768,disk:131072,file:65536,time:262144,timer:524288,event:1048576,input:2097152,key:4194304,mouse:8388608,touch:16777216,info:274877906944,warn:549755813888,error:1099511627776,halt:70368744177664,buffer:0x800000000000};function sa(){this.g={};for(var a=0;23>a;a++)this.g["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
function ta(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,r(a)));return a}
sa.prototype.L=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(void 0===this.g[g])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];"%"!=g&&e++}else h=b[b.length-1];var l=d[f+1],k=0<=l.indexOf("#"),m=0<=l.indexOf("0"),n=d[f+2];"*"==n?(n=h,h=e<b.length?b[e++]:b[b.length-1]):n=+n||0;var p=d[f+3];p=p?+p.substr(1):-1;var u=d[f+4],x=null,
v=0,y="",w=0<="ACDFGHMNSTWY".indexOf(g)&&"object"!=typeof h?ta(h):h;switch(g){case "C":c+=isNaN(w.getTime())?void 0:this.L("%#W, %#F %#D, %#Y".replaceAll("#",k?"#":""),w);continue;case "D":h=k?w.getUTCDate():w.getDate();g="d";break;case "A":case "G":case "H":h=k?w.getUTCHours():w.getHours();"A"==g?(h=12>h?"am":"pm",g="s"):("G"==g&&(h=h?12<h?h-12:h:12),g="d");break;case "F":case "M":h=k?w.getUTCMonth():w.getMonth();"F"==g?(h=ua[h],g="s"):(h++,g="d");break;case "N":h=k?w.getUTCMinutes():w.getMinutes();
g="d";break;case "S":h=k?w.getUTCSeconds():w.getSeconds();g="d";break;case "T":c+=isNaN(w.getTime())?void 0:this.L("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",k?"#":""),w);continue;case "W":h=va[k?w.getUTCDay():w.getDay()];g="s";break;case "Y":h=k?w.getUTCFullYear():w.getFullYear(),0<p&&(h%=Math.pow(10,p)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=p&&(m=!0,n<p&&(n=p),p=-1);case "f":h=+h;g=h+"";0<=p&&(g=h.toFixed(p));g.length<n&&(m?(0>h&&(n--,g=g.substr(1)),
g=("0".repeat(n)+g).slice(-n),0>h&&(g="-"+g)):g=(" ".repeat(n)+g).slice(-n));c+=g;break;case "j":c+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=p&&(h=h.substr(0,p));h.length<n;)h=0<=l.indexOf("-")?h+" ":" "+h;c+=h;break;case "B":v=2,k&&(y="0b");case "o":v||(v=8),!y&&k&&(y="0o");case "X":x=wa;case "x":g="";v||(v=16);!y&&k&&(y="0x");x||(x=xa);h=Math.trunc(h);0<=p&&(m=!0,n<p&&(n=p));
m&&!n&&("b"==u?n=2:"h"==u||"w"==u?n=4:"l"==u?n=8:(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9),n+=y.length);n-=y.length;do k=16,Number.isNaN(h)||(k=h&v-1,h=Math.trunc(h/v)),m||!g||k||h?g=x[k]+g:(y&&(g=y+g,y=""),0<n&&(g=" "+g));while(0<--n||h);c+=y+g;break;case "%":c+="%";break;default:c=this.g[g]?c+this.g[g](g,l,n,p,h):c+("(unimplemented sprintf type: %"+g+")")}}}return c+=d[f]};
var xa="0123456789abcdef?",wa="0123456789ABCDEF?",va="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ua="January February March April May June July August September October November December".split(" ");function ya(){}z(ya,oa);function za(a,b){var c=a/D|0,d=b/D|0;return(a&b)==(b|0)&&(c&d)==d}var D=Math.pow(2,32);C.NumIO=ya;function E(){this.pb=new sa;this.W=this.pb.L.bind(this.pb)}z(E,ya);E.prototype.flush=function(){var a=Aa;Aa="";this.ua(a)};
function Ba(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}E.prototype.ua=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),Ca||(Ca=b),a=((b-Ca)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(Aa+a.substr(0,c)),Aa="",a=a.substr(c+1)),Ca=null);Aa+=a;return a.length};E.prototype.s=function(a){return this.ua(this.W.apply(this,[a].concat(r(la.apply(1,arguments)))))};var Aa="",Ca=null;
C.StdIO=E;function F(a){E.call(this);this.S={};this.ga=0;this.L=this;a&&(this.L.ga=0,this.L.ta=[],this.L.ka=0,this.L.Ha={},this.L.ce=!1)}var Da;z(F,E);q=F.prototype;q.za=function(a,b){var c=this,d=this;switch(a){case Ea.Ub:b.onclick=function(){var e=c.Ba(Ea.Wa,!0);e&&(e.value="")};break;case Ea.Wa:Fa(b),b.addEventListener("keydown",function(e){Ga(d,e,!0)}),b.addEventListener("keypress",function(e){Ga(d,e)})}};
function Ha(a,b){b=void 0===b?{}:b;if("undefined"!=typeof document){a.J.S||(a.J.S=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.X);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.S[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.S[d].push(e)}while(1);continue}if(f=document.getElementById(e))a.S[d]=f,a.za(d,f)}}}
function Fa(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}q.error=function(a,b){b=this.W.apply(this,[a].concat(r(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.W.apply(this,[c].concat(r(b))))this.s("%s\n",b),a||alert(b)};q.Ba=function(a){return this.S[a]};
function Ia(a){var b=window;if(b){do{for(var c=0;c<Ja.length;c++){var d=Ja[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ka(a,b){return a.J.bindings&&a.J.bindings[b]}function La(a){if(a=a.S[Ma])var b=a.textContent;return b}function Na(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function G(a,b,c,d){a=a.J[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Oa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Pa(a){if(void 0===H.Ta){var b=!1;if(window)try{window.localStorage.setItem(H.ya,H.ya),b=window.localStorage.getItem(H.ya)==H.ya,window.localStorage.removeItem(H.ya)}catch(c){a.s("%s\n",c.message),b=!1}H.Ta=b}return!!H.Ta}function I(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.ga;return-1==(b|1)||za(a.L.ga,b)?!0:!1}
function Qa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ra(a){var b=null;if(Pa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.M))&&(b=JSON.parse(c))}catch(d){a.s("%s\n",d.message)}}return b}
function Ga(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.L,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==J.cb&&f.selectionStart<=h+1&&(a=!0);d==J.yc?(a=!0,0<e.ka&&(g=e.ta[--e.ka])):d==J.Xb&&(a=!0,e.ka<e.ta.length&&(g=e.ta[++e.ka]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ka&&c+1==g.length&&
(f.value+=e.ta[--e.ka],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Sa(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&a.s("%s\n",b.replace(/\n$/,"")))}}
function Ta(a,b){if(void 0!=b){var c=a.L;try{if(b=b.trim())c.ka<c.ta.length&&b==c.ta[c.ka]?c.ka++:(c.ta.push(b),c.ka=c.ta.length);var d=b.split(" "),e=d[0],f=a.L.Ha[Ua.gb];switch(e[0]){case "m":if("?"==e[1]){var g="";Va.forEach(function(n){g+=n+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var l="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=l&&d.pop();1>=d.length&&(void 0!=l&&(h=l,l=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(ra));for(f=
1;f<d.length;f++){e=d[f];var k=ra[e];if(!k){g+="unrecognized message: "+e+"\n";break}void 0!=l&&Wa(a,k,l);if(void 0==h||h==I(a,k))g+=a.W("%8s: %b\n",e,I(a,k))}I(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Xa.forEach(function(n){g+=n+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var m=f[a](d);if(void 0!=m){g=g?g+m:m;break}}}}catch(n){g="error: "+n.message+"\n"}}return g}
function Sa(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Ta(a,b[d])}return c}q.ua=function(a,b){void 0==b&&(b=I(this,0x800000000000));if(!b){var c=this.Ba(Ea.Wa,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Qa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return E.prototype.ua.call(this,a,b)};
q.s=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return I(this,c)?(za(c,1099511627776)&&(a="error: "+a),za(c,549755813888)&&(a="warning: "+a),E.prototype.s.call.apply(E.prototype.s,[this,a].concat(r(b)))):0};function Ya(a,b){if(Pa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.M,b)}catch(c){a.s("%s\n",c.message)}}}function K(a,b,c){(a=a.S[b])&&a.textContent!=c&&(a.textContent=c)}
function Wa(a,b,c){var d=!1;c?(c=a.L.ga,a.L.ga=(c|b)+(c/D|0|b/D|0)*D):(d=za(a.L.ga,0x800000000000)&&za(b,0x800000000000),c=a.L.ga,a.L.ga=(c&~b)+((c/D|0)&~(b/D|0))*D);d&&a.flush()}
var Ea={Ub:"clear",Wa:"print"},Xa=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Va=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],Ua={gb:"command"},Za={hb:13,Sa:65,bb:66,eb:67,ib:68,E:69,jb:70,kb:71,lb:72,mb:73,nb:74,qb:75,rb:76,ub:77,vb:78,wb:79,xb:80,Q:81,zb:82,Bb:83,Cb:84,Db:85,Eb:86,Fb:87,Gb:88,
Hb:89,Ya:90,a:97,b:98,c:99,d:100,e:101,f:102,ie:103,je:104,ke:105,le:106,k:107,me:108,ne:109,n:110,oe:111,p:112,q:113,r:114,pe:115,t:116,re:117,se:118,w:119,x:120,y:121,z:122},J={cb:8,uc:9,ic:10,hb:13,qc:16,Vb:17,Tb:18,Sd:19,Ua:20,Tc:27,sc:32,Vd:33,Ud:34,Sc:35,od:36,sb:37,yc:38,Xa:39,ld:39,Xb:40,hd:44,Wd:44,pd:45,Rc:46,kd:46,nd:47,ZERO:48,ONE:49,wc:50,vc:51,ec:52,dc:53,rc:54,pc:55,Yb:56,jc:57,cc:59,bc:61,Sa:65,bb:66,eb:67,ib:68,E:69,jb:70,kb:71,lb:72,mb:73,nb:74,qb:75,rb:76,ub:77,vb:78,wb:79,xb:80,
Q:81,zb:82,Bb:83,Cb:84,Db:85,Eb:86,Fb:87,Gb:88,Hb:89,Ya:90,fb:91,jd:91,gd:92,Zd:93,md:93,td:96,Kd:96,fd:96,ud:97,Id:97,vd:98,Hd:98,wd:99,Nd:99,xd:100,Ld:100,yd:101,Ed:101,zd:102,Pd:102,Ad:103,Jd:103,Bd:104,Rd:104,Cd:105,Od:105,Md:106,Dd:107,Qd:109,Fd:110,Gd:111,Uc:112,Yc:113,Zc:114,$c:115,ad:116,bd:117,cd:118,dd:119,ed:120,Vc:121,Wc:122,Xc:123,kc:144,nc:145,ac:173,oc:186,Zb:187,Qc:188,Wb:189,Td:190,ae:191,Oc:192,qd:219,Pc:220,Yd:221,Xd:222,$b:224,rd:901,be:1E3},$a={},ab=($a[J.cc]=J.oc,$a[J.bc]=J.Zb,
$a[J.ac]=J.Wb,$a[J.$b]=J.fb,$a),bb={sb:1,Xa:2,sd:3},L={},cb=(L[J.cb]="\b",L[J.uc]="\t",L[J.ic]="\n",L[J.hb]="\r",L[J.sc]=" ",L[J.ZERO]="0",L[J.ONE]="1",L[J.wc]="2",L[J.vc]="3",L[J.ec]="4",L[J.dc]="5",L[J.rc]="6",L[J.pc]="7",L[J.Yb]="8",L[J.jc]="9",L[J.Sa]="A",L[J.bb]="B",L[J.eb]="C",L[J.ib]="D",L[J.E]="E",L[J.jb]="F",L[J.kb]="G",L[J.lb]="H",L[J.mb]="I",L[J.nb]="J",L[J.qb]="K",L[J.rb]="L",L[J.ub]="M",L[J.vb]="N",L[J.wb]="O",L[J.xb]="P",L[J.Q]="Q",L[J.zb]="R",L[J.Bb]="S",L[J.Cb]="T",L[J.Db]="U",L[J.Eb]=
"V",L[J.Fb]="W",L[J.Gb]="X",L[J.Hb]="Y",L[J.Ya]="Z",L[J.sb]="Left",L[J.Xa]="Right",L),Ja=["","moz","ms","webkit"],db={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",
darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",
fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",
navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},H={Ta:void 0,ya:"PCjs.localStorage"};C.WebIO=F;
function M(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;F.call(this,a==b);this.M=a;this.X=b;B[this.M]||(B[this.M]={});B[this.M][this.X]&&this.s("warning: machine configuration contains multiple '%s' devices\n",this.X);B[this.M][this.X]=this;this.id=this.M==this.X?this.M:this.M+"."+this.X;qa.push(this);this.L=N(this,this.M);this.ready=!0;eb(this,c,d);this.xc={};this.tb=[]}z(M,F);
function eb(a,b,c){c=b.overrides||c;if(c.length){var d,e=Da;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,h=/([^&=]+)=?([^&]*)/g;f=h.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Da=e}d=e;for(var l in d)if(0<=c.indexOf(l)){e=d[l];f=void 0;var k;g=void 0;h=e;var m=10;if(h){m||(m=10);var n=0<h.indexOf(",");n&&(h=h.replace(/,/g,""));var p=k=h.charAt(0);"#"==k?(m=8,k=""):"$"==k&&(m=16,k="");p!=k?h=h.substr(1):
(p=k=h.substr(0,2),"0b"==k&&n||"^B"==k?(m=2,k=""):"0o"==k||"^O"==k?(m=8,k=""):"^D"==k?(m=10,k=""):"0x"==k&&(m=16,k=""),p!=k&&(h=h.substr(2)));p=k=h.slice(-1);"Y"==k||"y"==k?(m=2,k=""):"."==k?(m=10,k=""):"H"==k||"h"==k?(m=16,k=""):"K"==k?k="000":"M"==k?k="000000":"G"==k&&(k="000000000");p!=k&&(h=h.slice(0,-1)+k);p=0;10>=m&&(k=h.match(/(-?[0-9]+)B([0-9]*)$/))&&(h=k[1],p=35-((k[2]||35)&255));(m&&10!=m?16==m?null===h.match(/^-?[0-9a-f]+$/i):8==m?null===h.match(/^-?[0-7]+$/):2!=m||null===h.match(/^-?[01]+$/):
null===h.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(h,m))||(p&&(0>f&&(f+=Math.pow(2,36)),f=0<p?f*Math.pow(2,p):Math.trunc(f/Math.pow(2,-p))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[l]=f;a.s("overriding %s property '%s' with %s\n",a.X,l,e)}}a.J=b;Ha(a,b.bindings);b=void 0===b?{}:b;a.version=3;if(a.version){c="";var u;a.M!=a.X&&(u=N(a,a.M).version)&&u!=a.version&&(c="Machine");c||(u=b.version)&&u>a.version&&(c="Config");c&&(u=a.W("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.ee,a.version,c,u),a.error("%s\n\nClearing your browser's cache may resolve the issue.",u))}}function fb(a,b){var c;try{var d=B[a.M];if(d)for(c in d){var e=d[c];if(e.X!=e.M&&!b(e))return!1}return!0}catch(f){a.s("error while enumerating device '%s': %s\n",c,f.message)}return!1}M.prototype.Ba=function(a,b){b=void 0===b?!1:b;if(a){var c=F.prototype.Ba.call(this,a,b);if(void 0===c&&b){b=B[this.M];for(var d in b)if(c=b[d].S[a])break;c||(c=null);this.S[a]=c}}return c};
function N(a,b,c){var d=b,e=a.M,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=B[e])&&f[b]||null;if(!b){for(f=0;f<qa.length;f++)if(qa[f].id===d){b=qa[f];break}if(!b&&(void 0===c||c))throw Error(a.W('no "%s" device',d));}return b}function O(a,b,c){var d=null,e=B[a.M];if(e)for(var f in e)if(e[f].J["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.W("no %s device",b));return d}function P(a){return a==a.L&&a.ready?fb(a,function(b){return P(b)}):a.ready}
function gb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(P(a)){for(;b=a.tb.pop();)b();a!=a.L&&gb(a.L)}}function hb(a,b){if(P(a))return b(),!0;a.tb.push(b);return!1}
M.prototype.s=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&I(this,a)&&(void 0===this.fa&&(this.fa=O(this,"Debugger",!1)),this.L.ga&1&&(void 0===this.da&&(this.da=O(this,"CPU")),this.da))?(a=b.shift(),F.prototype.s.call(this,"%#06x: %s.%s\n",this.da.Pa,this.X,this.W.apply(this,[a].concat(r(b))).trim())):F.prototype.s.call.apply(F.prototype.s,[this,a].concat(r(b)))};function ib(a,b){(a=B[a.M])&&delete a[b]}M.prototype.Ob=function(a,b){(a=this.xc[a])&&a.set&&a.set(b)};C.Device=M;
function jb(a,b,c){M.call(this,a,b,c);this.ga=2097152;this.K=this.O=null;this.time=O(this,"Time");this.L=O(this,"Machine");this.ba=G(this,"drag",!1);this.Y=G(this,"scroll",!1);this.aa=G(this,"hexagonal",!1);this.u=G(this,"releaseDelay",0);this.v=!1;a=this.J.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.j[f]={keys:g,grid:e,
state:0}}}this.R=[];this.T=[];this.m=this.U=null;(a=this.S[kb])&&lb(this,a,this.Ba(c.focusBinding,!0),this.J.location);this.qa()}z(jb,M);function mb(a,b){a.O=b}function Q(a,b,c){for(var d=0;d<a.R.length;d++){var e=a.R[d];e.id===b&&e.Mb(b,c)}}
function lb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.Mc=d[0]||0;e.Nc=d[1]||0;e.Aa=d[2]||b.clientWidth;e.La=d[3]||b.clientHeight;e.Ma=d[4]||1;e.Qa=d[5]||1;e.Dc=d[6]||b.naturalWidth||e.Aa;e.Fc=d[7]||b.naturalHeight||e.La;e.Rb=d[8]||0;e.Sb=d[9]||0;e.Cc=d[10]||0;e.Ec=d[11]||0;a.h?(e.Oa=a.h.length,e.Ca=a.h[0].length):(e.Ca=e.Ma,e.Oa=e.Qa,e.Ma=e.Qa=0);e.Ib=e.Aa/(e.Ca+e.Ca*e.Ma)|0;e.Jb=e.La/(e.Oa+e.Oa*e.Qa)|0;e.Bc=e.Ib*e.Ma|0;e.Kb=e.Jb*e.Qa|0;e.Ga=e.Ra=-1;nb(a,b,e);ob(a,b,e);a.time&&
a.u&&(a.$=pb(a.time,"timerInputRelease",function(){0>e.Ga&&0>e.Ra&&qb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.u&&(a.ca=pb(a.time,"timerKeyRelease",function(){rb(a)})),a.H=0,a.N="",a.I=[],d=b,c&&(d=c,a.m||"BUTTON"!=c.nodeName||(d=document,a.m=c,sb(a,b),a.U=b)),sb(a,d),a.m||(a.m=d)}function tb(a){a.u?ub(a.time,a.ca,a.u):rb(a)}
function sb(a,b){function c(e,f,g){var h=document.activeElement;a.s(5242880,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.m&&e!=a.m&&e!=a.U?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=vb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=vb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=vb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function nb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.v){var e=a.m;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,wb,d,c)}});b.addEventListener("mousemove",function(d){a.v||R(a,b,xb,d,c)});b.addEventListener("mouseup",function(d){a.v||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.v||(0>c.Ga?R(a,b,xb,d,c):R(a,b,S,d,c))})}
function ob(a,b,c){b.addEventListener("touchstart",function(d){a.Y&&(a.v=!0);R(a,b,wb,d,c)});b.addEventListener("touchmove",function(d){R(a,b,xb,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function vb(a,b,c,d){if(void 0!=c){var e=ab[b]||b;var f=cb[b];var g=yb[e];d=d&&d.location==bb.Xa;g&zb&&d&&(g>>=1);g&&(g&Ab&&(c=!(a.g&g)),a.g=c?a.g|g:a.g&~g,Q(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=Za.Sa&&b<=Za.Ya?a.g&(Bb|Cb)||(a.g|=Cb,Q(a,J.Ua,!0)):b>=Za.a&&b<=Za.z&&a.g&Cb&&(a.g&=~Cb,Q(a,J.Ua,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(g=a.h[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.H?16>a.I.length&&a.I.push(b):(a.H=1,a.N=f,qb(a,d,e),Q(a,f,
!0),tb(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(g=b[e],0<=a.j[g].keys.indexOf(f))return Q(a,g,c),a.j[g].state=c?1:0,!0}return!1}function rb(a){1==a.H?(a.H++,Q(a,a.N,!1),a.N="",qb(a,-1,-1),tb(a)):(a.H=0,a.I.length&&vb(a,a.I.shift()))}jb.prototype.qa=function(){this.g=0;this.V=this.Z=-1};
function R(a,b,c,d,e){var f=-1,g=-1,h=!1,l=-1,k=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(l=d.targetTouches[0].clientX,k=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(l=d.clientX,k=d.clientY);var m=d.target.getBoundingClientRect();l-=m.left;k-=m.top;l=e.Dc/b.offsetWidth*l|0;k=e.Fc/b.offsetHeight*k|0;var n=l-e.Mc;var p=k-e.Nc;var u=m=!1;var x=l>=e.Rb&&l<e.Rb+e.Cc&&k>=e.Sb&&k<e.Sb+e.Ec;if(0<=n&&n<e.Aa&&0<=p+e.Kb||x)if(h||a.Y||d.preventDefault(),0<=n&&n<e.Aa&&0<=
p&&p<e.La){u=!0;d=e.Aa/e.Ca|0;var v=e.La/e.Oa|0,y=n/d|0,w=p/v|0;!a.aa||w&1||(n-=d>>1,y=n/d|0,y==e.Ca-1&&(n=-1));v=w*v+(e.Kb>>1);n-=y*d+(e.Bc>>1);p-=v;0<=n&&n<e.Ib&&0<=p&&p<e.Jb&&(f=y,g=w,m=!0)}}n=n||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==wb||c==S)for(y=0;y<a.T.length;y++)w=a.T[y],c==S?w.Mb(w.id,!1):(v=p/(b/w.ge|0)|0,(n/(d/w.fe|0)|0)==w.te&&v==w.ue&&w.Mb(w.id,!0));if(!h)if(c==wb)e.Ga=l,e.Ra=k,u?(qb(a,f,g),m&&a.u&&ub(a.time,a.$,a.u,!0)):x&&a.L.ia();else if(c==xb)0<=e.Ga&&0<=e.Ra&&a.ba?qb(a,
f,g):a.O&&a.O(f,g);else if(c==S){if(c=a.u)c=a.time,f=a.$,c=c.g&&0<f&&f<=c.h.length?0<=c.h[f-1].ha:!1;c||qb(a,-1,-1);e.Ga=e.Ra=-1}else a.s("unrecognized action: %d\n",c)}function qb(a,b,c){if(b!=a.V||c!=a.Z)a.V=b,a.Z=c,a.K&&a.K(b,c)}var wb=1,xb=2,S=3,kb="surface",Bb=3,zb=170,Cb=512,Ab=3584,T={},yb=(T[J.qc]=2,T[J.Vb]=8,T[J.Tb]=32,T[J.fb]=128,T[J.Ua]=Cb,T[J.kc]=1024,T[J.nc]=2048,T);C.Input=jb;
function Db(a,b,c){M.call(this,a,b,c,["color","backgroundColor"]);a=this.S[Eb];if(!a)throw Error("LED "+this.J.S[Eb]+" binding for '"+Eb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.va=Ka(this,Eb)+".canvas";b.setAttribute("id",this.va);this.Va=a;this.type=Na(G(this,"type",Fb,Gb),Hb,Ib);this.m=Jb[this.type][0];this.I=Jb[this.type][1];this.width=G(this,"width",
this.m);this.height=G(this,"height",this.I);this.u=G(this,"cols",1);this.R=this.u+G(this,"colsExtra",0);this.ba=G(this,"rows",1);this.V=this.ba+G(this,"rowsExtra",0);this.ea=this.width*this.u;this.Z=this.height*this.ba;this.H=Kb("black",0);this.j=Lb(this.J.color)||this.H;this.na=Kb(this.j,1,.25);this.ma=Kb(this.j,1,2);this.v=Lb(this.J.backgroundColor);this.oa=G(this,"fixed",!1);this.oa||(b.style.width="100%",b.style.height="auto");this.la=G(this,"hexagonal",!1);this.sa=G(this,"highlight",!0);this.Y=
G(this,"persistent",this.type<Ib);b.setAttribute("width",this.ea.toString());b.setAttribute("height",this.Z.toString());b.style.backgroundColor=this.H;a.appendChild(b);this.ja=b.getContext("2d");if(this.K=document.createElement("canvas"))this.K.width=this.ca=this.m*this.u,this.K.height=this.N=this.I*this.ba,this.h=this.K.getContext("2d");this.wa=(this.V+1)*this.R*4;this.g=Array(this.wa);this.Ia=this.u<this.R?4*(this.R-this.u):0;this.T=this.U=!1;this.O=this.aa=0;this.$=-1;var d=this;this.time=O(this,
"Time");Mb(this.time,function(e,f){Nb(d,!1,e,f)});Ob(d)}z(Db,M);function Ob(a){for(var b=a.g,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Ib?Pb:" ";e[f+1]=d.j==d.H?null:d.j;e[f+2]=0;e[f+3]=Qb}a.T=a.U=!0;Nb(a,!0)}function Rb(a){a.v?(a.h.fillStyle=a.v,a.h.fillRect(0,0,a.ca,a.N)):a.h.clearRect(0,0,a.ca,a.N)}
function Nb(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.T||b){if(a.type<Ib){d=0;if(!a.Y||b)Rb(a);else if(a.O){d=a.u-a.O;var e=a.m*d;a.h.drawImage(a.K,a.m*a.O,0,e,a.N,0,0,e,a.N)}for(var f=e=0;f<a.V;f++){for(var g=0;g<a.u;g++){var h=a.g[e],l=a.g[e+1]||a.H,k=a.sa&&e==a.$;if(a.g[e+3]&Qb||k||b){if(g>=d)a:{var m=a,n=h;h=l;var p=g;l=f;var u=k;p=void 0===p?0:p;l=void 0===l?0:l;u=void 0===u?!1:u;var x=0;if(m.la&&!(l&1)&&(x=m.m>>1,p==m.u-1))break a;if(h&&h!=m.j){u=u?Kb(h,1,2):h;var v=
Kb(h,1,.25)}else u=u?m.ma:m.j,v=m.na;h=!1;n=n?u:v;u==m.H&&(n=m.v,h=!0);u=p*m.m+x;v=l*m.I;m.Y&&(p=p*m.m+x,l*=m.I,m.v?(m.h.fillStyle=m.v,m.h.fillRect(p,l,m.m,m.I)):m.h.clearRect(p,l,m.m,m.I));m.h.fillStyle=n;l=Sb[m.type];3==l.length?(m.h.beginPath(),m.h.arc(u+l[0],v+l[1],l[2],0,2*Math.PI),h?(m.h.globalCompositeOperation="destination-out",m.h.fill(),m.h.globalCompositeOperation="source-over"):m.h.fill()):m.h.fillRect(u+l[0],v+l[1],l[2],l[3])}a.g[e+3]=k?a.g[e+3]|Qb:a.g[e+3]&~Qb}e+=4}e+=a.Ia}a.O=0}else{b=
"";for(d=0;d<a.g.length;d+=4)b+=a.g[d]||" ",a.g[d+3]&Tb&&(b+=".");Rb(a);for(f=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;g=a;k=e;m=f;k=void 0===k?0:k;m=void 0===m?0:m;if(l=Ub[l])for(h=0;h<l.length;h++)if(p=g,x=Vb[l[h]]){n=(void 0===k?0:k)*p.m;u=(void 0===m?0:m)*p.I;p.h.fillStyle=p.j;p.h.beginPath();if(3==x.length)p.h.arc(n+x[0],u+x[1],x[2],0,2*Math.PI);else for(v=0;v<x.length;v+=2)v?p.h.lineTo(n+x[v],u+x[v+1]):p.h.moveTo(n+x[v],u+x[v+1]);p.h.closePath();p.h.fill()}if(++e==a.u&&(e=0,++f==a.V))break}}a.ja.globalCompositeOperation=
a.v&&a.j!=a.H?"source-over":"copy";a.ja.drawImage(a.K,0,0,a.ca,a.N,0,0,a.ea,a.Z);a.T=!1;a.$=-1}else a.Y||a.U||(!c||!a.aa||c-a.aa>=(1E3/d|0))&&Ob(a);a.U=!1;c&&(a.aa=c)}function Lb(a){return(a=a||void 0)&&db[a]||a}
function Kb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=db[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Db.prototype.pa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.j&&c==this.v&&a&&a.length==this.g.length){this.g=a;for(b=0;b<=this.g.length-4;b+=4)this.g[b+1]==this.H&&(this.g[b+1]=null);Nb(this,!0);return!0}return!1};Db.prototype.ra=function(a){this.g&&(a.push(this.j),a.push(this.v),a.push(this.g))};
function Wb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&Xb;b=4*(c*a.R+b);if(b<=a.g.length-4){if(a.g[b]!==d||(a.g[b+3]&Xb)!==e)a.g[b]=d,a.g[b+3]=a.g[b+3]&~Xb|e|Qb,a.T=f=!0;a.$=b;a.U=!0;a.O=0}return f}
var Hb=0,Fb=1,Ib=3,Gb={small:Hb,round:Fb,square:2,digit:Ib},Eb="container",Pb=0,Xb=129,Tb=1,Qb=128,Yb={},Sb=(Yb[Hb]=[4,4,4],Yb[Fb]=[16,16,14],Yb[2]=[2,2,28,28],Yb),Jb=[[8,8],[32,32],[32,32],[96,128]],Vb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Ub={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};C.LED=Db;
function Zb(a,b,c){M.call(this,a,b,c);this.oa=G(this,"cyclesMinimum",1E5);this.Va=G(this,"cyclesMaximum",1E9);this.sa=Na(G(this,"cyclesPerSecond",1E6),this.oa,this.Va);this.ba=60;this.V=0;this.Y=1E3/this.ba;this.tc=G(this,"updatesPerSecond",2)||2;this.mc=1E3/this.tc;this.Ia=0;this.zc=G(this,"timeLock",!0);this.ma=this.R=0;this.la=this.H=1;this.wa=this.K=this.sa/1E4/100;this.ea=[];this.N=[];this.h=[];this.ja=[];this.va=this.g=this.ca=this.I=!1;this.O=this.m=0;a=Ia("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.Y}this.yb=window[a].bind(window,this.Jc.bind(this),d);this.lc=window[Ia("cancelAnimationFrame")||"clearTimeout"].bind(window);this.aa=this.$=this.u=this.j=this.na=0;$b(this)||ac(this,this.la)}z(Zb,M);function Mb(a,b){a.ea.push(b)}q=Zb.prototype;
q.za=function(a,b){var c=this;switch(a){case bc:b.onclick=function(){cc(c)&&(c.g?U(c):c.start())};break;case dc:b.onclick=function(){ac(c,c.H<<1);ec(c,fc(c.K))};break;case gc:b.onclick=function(){hc(c)};break;case ic:b.addEventListener("mousedown",function(){c.I=!0}),b.addEventListener("mouseup",function(){$b(c);c.I=!1}),b.addEventListener("mousemove",function(){c.I&&$b(c)}),b.addEventListener("change",function(){c.I=!0;$b(c);c.I=!1})}M.prototype.za.call(this,a,b)};
function pb(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,Ac:c,Na:d,ha:-1});0<=d&&ub(a,e,d);return e}
function jc(a,b,c,d){var e=0,f=a.K,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.s(262144,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.Y&&(1<a.H&&(a.H>>=1,a.s(549755813888,"frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.Y,a.H)),e=d));a.R=f;a.ma=f/a.wa;b=a.ma/a.H;a.na=g/b/a.ba+1E-8;a.s(262144,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.na,g,b,a.ba);return e}
function kc(a,b){a.$=a.u=b;if(!a.N.length)return a.u=0,a.$;for(var c=0;0<a.u;){if(c<a.N.length){var d=a.N[c++];b=d.Kc.call(d,b)||1}else c=b=0;a.u-=b}return a.$-a.u}function lc(a,b){var c=Date.now();b()&&(a.Z+=Date.now()-c)}function mc(a,b){b=void 0===b?a.$-a.u:b;if(!a.g){if(a.j)for(var c=0;c<a.N.length;c++){var d=a.N[c];d.Pb.call(d)}a.j=b}a.j-=b;1>a.j&&(a.ca=!0);a.aa+=b;a.$=a.u=0;a.g||(a.aa=0);return b}
function nc(a,b){b=void 0===b?0:b;if(b){var c=b;a.j+=b}else for(c=a.j,1>c&&(c=a.j+=a.na),0>c&&(a.s(262144,"warning: cycle count dropped below zero: %f\n",c),c=a.j=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.ha)&&c>d.ha&&(c=d.ha)}return c}function fc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function cc(a){return a.va?!0:(a.s("not powered\n"),!1)}
function oc(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.ha||(d.ha-=b,0>=d.ha&&(d.ha=-1,d.Ac(),0<=d.Na&&ub(a,c,d.Na)))}}q.ia=function(a){this.va=a;void 0===this.fa&&(this.fa=O(this,"Debugger",!1))};function hc(a,b){cc(a)&&(a.g?a.s("already running\n"):a.m?U(a):pc(a,b))}
q.Jc=function(a){a=void 0===a?Date.now():a;this.O=0;if(this.g){if(this.V){var b=a-this.V;1>b&&(b=16.67);this.ba=1E3/b}this.V=a;a=Date.now();this.T&&(b=a-this.U-this.Y,b>this.Y&&(this.v+=b,this.s(549755813888,"browser throttling detected, compensating by %5.3fms\n",b)));this.U=a;this.v||(this.v=a);this.Z=0;try{this.ca=!1;do oc(this,mc(this,kc(this,nc(this))));while(this.g&&!this.ca)}catch(c){this.s("%s\n",c.message),U(this)}this.T=Date.now();this.Z&&(this.v+=this.Z,this.U+=this.Z);this.U+=jc(this,
this.aa,this.T-this.v,this.T-this.U);this.T-this.Ia>=this.mc&&this.update();for(a=0;a<this.ea.length;a++)this.ea[a](this.V,this.ba);this.O=this.yb()}};function ac(a,b){if(void 0!==b){if(1>b||!a.I&&0<a.R&&a.R<.9*a.K)b=a.la;a.H=b;b=a.wa*a.H;a.K!=b&&(a.K=b,ec(a,fc(a.K)))}a.v=a.T=0;a.j=a.aa=0;jc(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.Na&&ub(a,b,c.Na,!0)}}function $b(a){var b=a.S[ic];return b?(ac(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Va-a.oa)+a.oa)/a.sa|0),!0):!1}
function ub(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.ha)&&(c=Math.ceil(a.sa*(a.zc?a.la:a.ma)/1E3*(void 0===c?1E3:c)),a.g&&(c+=mc(a)),b.ha=c)}q.start=function(){if(this.g||this.m)return!1;this.g=!0;this.v=this.T=this.V=0;this.update(!0);this.O=this.yb();return!0};function pc(a,b){b=void 0===b?1:b;a.g||(b&&!a.m&&(a.m=b),a.m&&(a.m--,oc(a,mc(a,kc(a,nc(a,1)))),a.update(!1),a.m&&setTimeout(function(){pc(a,0)},0)))}
function U(a){return a.g?(a.g=!1,mc(a),a.O&&(a.lc(a.O),a.O=0),a.update(!0),!0):a.m?(a.m=0,a.update(!0),!0):!1}q.update=function(a){a&&this.s(this.g?"started with %s target\n":"stopped\n",fc(this.K));K(this,bc,this.g?"Halt":"Run");K(this,gc,this.m?"Stop":"Step");this.I||(this.s(262144,"getSpeedCurrent(%5.3fhz)\n",1E6*this.R),ec(this,this.g&&this.R?fc(this.R):"Stopped"));for(var b=0;b<this.ja.length;b++){var c=this.ja[b];c.Hc.call(c,void 0!=a)}this.Ia=Date.now();this.ca=!0};
function ec(a,b){K(a,qc,b);K(a,dc,b)}var bc="run",dc="setSpeed",qc="speed",gc="step",ic="throttle";C.Time=Zb;
function rc(a,b,c){M.call(this,a,b,c);this.type="static"==this.J.type?sc:tc;this.v=this.J.addrWidth||16;this.j=Math.pow(2,this.v);this.I=this.j-1|0;this.blockSize=this.J.blockSize||(16<this.v?4096:1024);this.blockSize>this.j&&(this.blockSize=this.j);this.K=this.j/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.m=(1<<this.h)-1;this.H=this.J.dataWidth||8;this.g=Array(this.K);this.u=0;a=new V(a,b+"[NONE]",{size:this.blockSize,bus:this.X});for(b=0;b<this.j;b+=this.blockSize)uc(this,b,this.blockSize,
W.NONE,a);a=this.u;this.u+=this.type;a&&this.u||(this.Da=this.fc,this.Ea=this.Fa)}z(rc,M);
function uc(a,b,c,d,e){for(var f=b>>>a.h;0<c&&f<a.g.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var l=a.g[f];if(b!=g||h!=a.blockSize||l&&l.type!=W.NONE)break;var k=l=void 0,m=b,n=a.v,p=16;n=void 0===n?0:n;l=void 0===l?0:l;var u="",x="",v=-1;p||(p=a.N||10);n&&(v=Math.ceil(n/Math.log2(p)));if(void 0==k)switch(p){case 8:k="0o";break;case 16:k="0x";break;case 10:x=".";default:k=""}isNaN(m)||"number"!=typeof m?(m=void 0,k=x=""):(0>m&&-1<m&&(m=-1),n&&(0>m&&(m+=Math.pow(2,n)),m>=Math.pow(2,
n)&&(v=Math.ceil(Math.log(m)/Math.log(p)))));for(n=l||-1;v--;){n||(u=","+u,n=l);if(void 0==m){if(u="?"+u,0>v)break}else{var y=m%p;m=Math.trunc(m/p);y+=0<=y&&9>=y?48:55;u=String.fromCharCode(y)+u;if(!m&&0>v)break}n--}l=a.X+"["+(k+u+x)+"]";b=e?e.size==a.blockSize?e:new V(a.M,l,{type:d,Ka:b,size:h,bus:a.X}):new V(a.M,l,{type:d,Ka:b,size:h,bus:a.X});a.g[f]=b;b=g+a.blockSize;c-=h;f++}}q=rc.prototype;q.he=function(a,b){this.fa&&this.fa.s(4,"bus fault (%d) at %n\n",b,a)};
q.ia=function(){void 0===this.fa&&(this.fa=O(this,"Debugger",!1))};q.qa=function(){};q.Za=function(a){return a&&this.pa(a)?!0:!1};q.$a=function(a){this.ra(a)};q.pa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==tc||c.type&W.Ja)&&c.pa){var d=a.shift();if(!c.pa(d))return!1}}return!0};q.ra=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==tc||c.type&W.Ja)&&c.ra){var d=[];c.ra(d);a.push(d)}}};q.xa=function(a){return this.g[a>>>this.h].xa(a&this.m)};
q.fc=function(a){return this.g[a>>>this.h].Da(a&this.m)};q.ab=function(a,b){this.g[a>>>this.h].ab(a&this.m,b)};q.Fa=function(a,b){this.g[a>>>this.h].Ea(a&this.m,b)};var sc=0,tc=1;C.Bus=rc;
function V(a,b,c){M.call(this,a,b,c);this.Ka=this.J.addr;this.size=this.J.size;this.type=this.J.type||W.NONE;this.m=(a=this.J.bus)?N(this,a):O(this,a="Bus");if(!this.m)throw Error(this.W("unable to find bus '%s'",a));this.v=this.m.H;this.K=Math.pow(2,this.v)-1;this.u=this.I=!1;this.values=this.j=null;a=this.ob;b=this.Fa;if(this.m.type==sc){b=this.Lc;if(c=8==this.v)c=N(this,this.M),c=!1!==(c&&c.J&&c.J.ArrayBuffer||this.J.ArrayBuffer);c&&(this.I=!0)}switch(this.type){case W.NONE:this.Da=this.Ic;this.Ea=
this.Qb;break;case W.Ab:this.Da=a;this.Ea=this.Qb;break;case W.Ja:this.Da=a,this.Ea=b}vc(this,this.J.values);wc(this)}z(V,M);function vc(a,b){"string"==typeof b?(gb(a,!1),Oa(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);vc(a,g.values)}catch(h){a.s("error (%s) parsing resource: %s\n",h.message,c)}gb(a,!0)}else a.s("error (%d) loading resource: %s\n",f,c)})):a.J.values=b}
function wc(a,b){if(a.type>W.NONE&&(a.I?(a.j=new ArrayBuffer(a.size),new DataView(a.j,0,a.size),a.values=new Uint8Array(a.j,0,a.size),new Uint16Array(a.j,0,a.size>>1),new Int32Array(a.j,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}q=V.prototype;
q.qa=function(){if(this.J.values)a:{var a=this.m,b=this.Ka,c=this.size,d=this.J.values,e=0,f=b&a.m;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var g=a.g[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Fa(f++,d[e++]),c--;f=0}}else this.type&W.Ja&&this.values&&this.values.fill(0)};q.Ic=function(){return this.K};q.xa=function(a){return this.values?this.values[a]:0};q.ob=function(a){return this.values[a]};q.Qb=function(){};q.ab=function(a,b){this.values&&(this.values[a]=b)};
q.Fa=function(a,b){this.values[a]=b};q.Lc=function(a,b){this.values[a]=b;this.u=!0;this.Ea=this.Fa};q.pa=function(a){if(a){var b=a.shift();if(this.X==b){this.u=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}wc(this,a)}return!0}}return!1};
q.ra=function(a){a.push(this.X);a.push(this.u);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var W={NONE:1,Ab:2,Ja:4,$d:14,de:12};C.Memory=V;
function xc(a,b,c){c.type=W.Ab;V.call(this,a,b,c);uc(this.m,this.J.addr,this.J.size,this.J.type,this);hb(this,this.qa.bind(this));this.da=this.fa=void 0;if(C.LED&&this.S[yc]){var d=this;this.h=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.H=this.values.length/this.h|0;this.g=new Db(a,b+"LEDs",{"class":"LED",bindings:{container:Ka(this,yc)},type:Fb,cols:this.h,rows:this.H,color:G(this,"colorROM","green"),backgroundColor:G(this,"backgroundColorROM","black"),persistent:!0}),Ob(this.g);
this.N=new jb(a,b+"Input",{"class":"Input",location:[0,0,this.g.ea,this.g.Z,this.h,this.H],bindings:{surface:Ka(this,yc)}});this.O=La(this)||"";mb(this.N,function(e,f){if(d.da){var g=d.O;0<=e&&0<=f&&(e=f*d.h+e,g=zc(d.da,d.Ka+e,d.values[e]));K(d,Ma,g)}})}}z(xc,V);
xc.prototype.pa=function(a){var b=!0,c=a.shift();if(c&&this.g){var d=c.length;this.g.g.length==d?(this.g.g=c,Nb(this.g,!0)):(this.s("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.s("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};xc.prototype.ia=function(){void 0===this.da&&(this.da=O(this,"CPU"));void 0===this.fa&&(this.fa=O(this,"Debugger",!1))};
xc.prototype.ob=function(a){this.g&&Wb(this.g,a%this.h,a/this.h|0,1,Qb);return this.values[a]};xc.prototype.ra=function(a){this.g&&(a.push(this.g.g),a.push(this.values))};var yc="array",Ma="cellDesc";C.ROM=xc;function Ac(a,b,c){c["class"]="CPU";M.call(this,a,b,c);this.fa=void 0;this.h=this.Pa=0;this.time=O(this,"Time");this.time.N.push(this);this.time.ja.push(this);this.Z=this.v=0}z(Ac,M);q=Ac.prototype;q.abort=function(a){this.h=this.Pa;this.s("%s\n",a.message);U(this.time)};q.Lb=function(){};
q.Kc=function(a){this.Z=this.v=a=void 0===a?0:a;try{this.Lb(a)}catch(b){this.abort(b)}return this.Nb()};q.Pb=function(){this.Z-=this.v;this.v=0};q.Nb=function(){return this.Z-this.v};function X(a,b,c){M.call(this,a.M,b);this.da=a;this.name=b;this.l=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.na[c]=[this,-1];for(var d=0;d<this.l.length;d++)c=this.W("reg%s-%02d",this.name,d),b.push(c),a.na[c]=[this,d];Ha(a,b)}}z(X,M);q=X.prototype;
q.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]+b.l[f]+e,e=0,this.l[f]>=d&&(this.l[f]-=d,e=1);e&&(this.da.H=!0);Bc(this,c)};q.get=function(){return this.l};function Cc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.l.length;d++)a.l[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.l[d]=b&15,b>>>=4;return a}q.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.l[e]=a.l[e]+d,d=0,this.l[e]>=c&&(this.l[e]-=c,d=1);Bc(a,b)};
q.set=function(a){if(a&&a.length==this.l.length)for(var b=0;b<this.l.length;b++)this.l[b]=a[b]};q.store=function(a){for(var b=0,c=this.l.length;b<c;b++)this.l[b]=a.l[b]};q.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]-b.l[f]-e,e=0,0>this.l[f]&&(this.l[f]+=d,e=1);e&&(this.da.H=!0);Bc(this,c)};q.toString=function(a){a=void 0===a?!1:a;var b=this.X+"=";a&&3>b.length&&(b+=" ");for(var c=this.l.length-1;0<=c;c--)b=a?b+wa[this.l[c]]:b+(xa[this.l[c]]+(c%4?"":" "));return b};
function Bc(a,b){a.da.u=a.l[b[0]];b[0]<b[1]&&(a.da.u|=a.l[b[0]+1]<<4)}
function Dc(a,b,c){Ac.call(this,a,b,c);this.type=Number.parseInt(G(this,"type","1501").slice(-4),10);this.na={};this.g=Array(4);for(a=0;4>a;a++)this.g[a]=new X(this,String.fromCharCode(65+a));this.U=this.g[0];this.$=this.g[1];this.sa=this.g[2];this.wa=this.g[3];this.R=Array(8);for(a=0;8>a;a++)this.R[a]=new X(this,"X"+a);this.V=Array(8);for(a=0;8>a;a++)this.V[a]=new X(this,"Y"+a);this.oa=new X(this,"Supp",!0);this.ba=new X(this,"Temp",!0);this.O=10;this.H=!1;this.aa=this.u=this.K=0;this.m=[-1,-1,-1];
this.va=N(this,this.J.input);this.va.K=this.hc.bind(this);this.j=N(this,this.J.output,!1);this.N=O(this,"Bus");this.I=O(this,"ROM");this.la=this.ma=this.Y=void 0;this.ja=this.ca=-1;this.T={};this.ea=Ec;a=this.Gc.bind(this);b=Ua.gb;this.L.Ha[b]||(this.L.Ha[b]=[]);this.L.Ha[b].push(a)}z(Dc,Ac);function Fc(a,b){a.T[b]&&(a.T[b]=!1,a.s("break on %s\n",Gc[b]),U(a.time))}function Hc(a){a.j&&Ob(a.j);if(a.I){var b=a.I;b.g&&Ob(b.g)}Ic(a,!1)}q=Dc.prototype;
q.Lb=function(a){for(;0<this.v;){if(this.ja==this.h){this.ja=-1;this.s("break\n");U(this.time);break}var b=this.N.Da(this.h);this.h=(this.Pa=this.h)+1&this.N.I;if(void 0==b||!Jc(this,b)){this.h=this.Pa;this.s("unimplemented opcode\n");U(this.time);break}this.v-=Kc}if(0>=a){var c=this;lc(this.time,function(){var d=c.I;d.g&&Nb(d.g);c.ua(c.toString())})}};q.Pb=function(){this.v=0};q.Nb=function(){return this.Z-this.v};
function Jc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.H&&(a.h=a.h&1024|b&1023):(a.push(a.h),a.h=b&2047),a.H=!1,!0;var c;var d=b&Lc;switch(d){case Mc:case Nc:case Oc:case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:d=Yc[d];var e=(b&Zc)>>$c;var f=(b&ad)>>bd;var g=(b&cd)>>dd;var h=(c=b&ed)?fd:gd;b=b>=Tc?16:a.O;switch(f){case 0:case 1:case 2:case 3:var l=a.g[f];break;case 4:l=Cc(a.ba,1,d);break;case 5:h=c?hd:id;break;case 6:l=Cc(a.ba,a.u&15,d);break;case 7:l=Cc(a.ba,a.u&255,d)}switch(g){case 0:var k=
a.g[e];break;case 1:k=4>f?a.g[f]:void 0;break;case 2:k=5>f?a.oa:5==f?a.g[e]:void 0;break;case 3:if(c)a.g[e].move(l,d,b);else{a=a.U;e=l;b=d[0];for(l=d[1];b<=l;b++)k=a.l[b],a.l[b]=e.l[b],e.l[b]=k;Bc(e,d)}return!0}if(!k)break;switch(h){case gd:k.add(a.g[e],l,d,b);break;case fd:k.sub(a.g[e],l,d,b);break;case id:b=k;a=a.g[e];e=d[1];for(l=d[0];e>l;e--)b.l[e]=a.l[e-1];b.l[e]=0;Bc(b,d);break;case hd:b=k;a=a.g[e];e=d[0];for(l=d[1];e<l;e++)b.l[e]=a.l[e+1];b.l[e]=0;Bc(b,d)}return!0;case jd:e=(b&kd)>>ld;d=(b&
md)>>nd;l=1<<((b&od)>>pd);if(!d)break;d+=12;switch(b&qd){case rd:a.g[e].l[d]|=l;break;case sd:a.g[e].l[d]&=~l;break;case td:a.g[e].l[d]&l&&(a.H=!0);break;case ud:a.g[e].l[d]^=l}return!0;case vd:switch(b&wd){case xd:a.U.store(a.V[a.K]);break;case yd:a.K=b>>4&7;break;case zd:a.h=a.u;break;case Ad:a.H=!1;d=a.m[0];e=0;for(b=a.m.length-1;e<b;)a.m[e]=a.m[++e];a.m[e]=-1;a.h=d;break;case Bd:a.R[a.K].store(a.U);break;case Cd:a.U.store(a.R[a.K]);break;case Dd:a.V[a.K].store(a.U);break;case Ed:Fc(a,"o");if(a.j){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.$.l[e]&8?b=" ":a.$.l[e]&1?b="-":b=wa[a.U.l[e]],Wb(a.j,d,0,b,a.$.l[e]&2?Tb:0)&&Fc(a,"om");Ic(a)}a.v-=31*Kc;a.aa&&(a.u=a.aa,a.H=!0,Fc(a,"i"));break;case Fd:a.O=10;break;case Gd:a.O=16;break;case Hd:a.K=a.u&7;break;default:return!1}return!0}return!1}
q.pa=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return this.s("invalid saved state\n"),!1;var c=b.shift();if(3!==(c|0))return this.s("saved state version mismatch: %3.2f\n",c),!1;try{this.g.forEach(function(d){return d.set(b.shift())}),this.R.forEach(function(d){return d.set(b.shift())}),this.V.forEach(function(d){return d.set(b.shift())}),this.oa.set(b.shift()),this.ba.set(b.shift()),this.O=b.shift(),this.H=b.shift(),this.K=b.shift(),this.u=b.shift(),this.h=b.shift(),this.m=b.shift(),this.aa=
b.shift()}catch(d){return this.s("CPU state error: %s\n",d.message),!1}return(a=a.stateROM||a[1])&&this.I&&!this.I.pa(a)?!1:!0};
q.Gc=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,h=3;h<a.length;h++)d.push(Number.parseInt(a[h],16));this.ea=Ec;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Gc)c=Gc[f],b+="break on "+c+" (b"+f+"): "+(this.T[f]||!1)+"\n";break}(c=Gc[f])?(this.T[f]=!this.T[f],b="break on "+c+" (b"+f+"): "+this.T[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.N.xa(f);if(void 0==
a)break;this.N.ab(f,d[g]);b+=this.W("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.W("%d locations updated\n",c);break;case "g":this.time.start()?this.ja=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.ea=Id);g=Number.parseInt(a[2],10)||1;hc(this.time,g);break;case "r":"c"==e[1]&&(this.ea=Id);this.Ob(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.ca?this.ca:this.h;g--;){c=this.I&&this.N.xa(f);if(void 0==
c)break;b+=zc(this,f++,c)}this.ca=f;break;case "?":b="additional commands:\n";Jd.forEach(function(l){b+=l+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};q.hc=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.aa=c};q.Za=function(a){return a&&this.pa(a)?!0:!1};q.ia=function(a){a?this.time.start():(U(this.time),Hc(this))};q.qa=function(){this.s("reset\n");this.h=0;Hc(this);this.time.g||this.ua(this.toString())};q.$a=function(a){this.ra(a)};
q.Hc=function(a){for(var b in this.S){var c=this.na[b];if(c){var d=c[0];c=c[1];K(this,b,0>c?d.toString():wa[d.l[c]])}}a&&!this.time.g&&(a=this.I,a.g&&Nb(a.g),this.ua(this.toString()))};q.push=function(a){for(var b=this.m.length-1;0<b;)this.m[b]=this.m[--b];this.m[0]=a};
q.ra=function(a){var b=[],c=[];b.push(3);this.g.forEach(function(d){return b.push(d.get())});this.R.forEach(function(d){return b.push(d.get())});this.V.forEach(function(d){return b.push(d.get())});b.push(this.oa.get());b.push(this.ba.get());b.push(this.O);b.push(this.H);b.push(this.K);b.push(this.u);b.push(this.h);b.push(this.m);b.push(this.aa);this.I&&this.I.ra(c);a.push(b);a.push(c)};q.Ob=function(a,b){if(a&&0<=b)switch(a){case "pc":this.h=b;break;default:this.s("unrecognized register: %s\n",a)}};
function zc(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.W("%#06x",f);else if(0<=c){var g=c&Lc;var h;switch(g){case Mc:case Nc:case Oc:case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:f="";e=Yc[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&Zc)>>$c;var l=(c&ad)>>bd;var k=(c&cd)>>dd;var m=c&ed;e="LOAD";var n=h="?";var p=m?5==l?">>":"-":5==l?"<<":"+";switch(k){case 0:h=
Y[g];break;case 1:4>l&&(h=Y[l]);break;case 2:6>l&&(h="NUL");break;case 3:m?(e="MOVE",h=Y[g],n=Y[l]):(e="XCHG",g||(h="A"),4>l&&(n=Y[l])),l=-1}switch(l){case 0:case 1:case 2:case 3:n=Y[g]+p+Y[l];break;case 4:case 5:n=Y[g]+p+"1";break;case 6:n=Y[g]+p+"R5L";break;case 7:n=Y[g]+p+"R5"}f=h+","+n+","+f;break;case jd:switch(c&qd){case rd:e="SET";break;case sd:e="CLR";break;case td:e="TST";break;case ud:e="NOT"}f=a.g[(c&kd)>>ld].name;g=(c&md)>>nd;f+="["+(g?g+12:"?")+":"+((c&od)>>pd)+"]";break;case vd:switch(c&
wd){case xd:e="STORE";f="A,Y[RAB]";break;case yd:e="STORE";f="RAB,"+((c&112)>>4);break;case zd:e="BR";f="R5";break;case Ad:e="RET";break;case Bd:e="STORE";f="X[RAB],A";break;case Cd:e="STORE";f="A,X[RAB]";break;case Dd:e="STORE";f="Y[RAB],A";break;case Ed:e="DISP";break;case Fd:e="BCDS";break;case Gd:e="BCDR";break;case Hd:e="STORE",f="RAB,R5L"}}}return a.W(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
q.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.ea){this.I&&(d+=zc(this,this.h,this.N.xa(this.h),!0));d+="  ";b=0;for(a=this.g.length;b<a;b++)d+=this.g[b].toString()+" ";d+="\n ";d+=" COND="+(this.H?1:0);d+=" BASE="+this.O;d+=" R5="+this.W("%02X",this.u);d+=" RAB="+this.K+" ST=";this.m.forEach(function(f){d+=c.W("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.g);0<=a.indexOf("a")&&(d+=this.toString(a,this.R),d+=this.toString(a,this.V));d+="COND="+(this.H?1:0);d+=" BASE="+this.O;d+=" R5="+this.W("%#04x",this.u);d+=" RAB="+this.K+" ";this.m.forEach(function(f,g){d+=c.W("ST%d=%#06x ",g,f&65535)});this.I&&(d+="\n"+zc(this,this.h,this.N.xa(this.h)));this.ca=this.h;return d};
function Ic(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Kd?!!(a.sa.l[14]&8):!!(a.$.l[15]&4));if(a.la!==d){if(c=a.S["2nd"])c.style.opacity=d?"1":"0",void 0===a.la&&a.j&&(c.style.color=a.j.color);a.la=d}d=b&&(a.type==Kd?!!(a.$.l[15]&4):!!(a.wa.l[15]&8));if(a.ma!==d){if(c=a.S.INV)c.style.opacity=d?"1":"0",void 0===a.ma&&a.j&&(c.style.color=a.j.color);a.ma=d}c=a.type==Kd?a.R[4].l[15]>>2:a.sa.l[15];b=b?c?1==c?Ld:Md:Nd:Od;if(a.Y!==b){if(c=a.S.Deg)c.style.opacity=b==Nd?"1":"0",void 0===a.Y&&a.j&&(c.style.color=
a.j.color);if(c=a.S.Rad)c.style.opacity=b==Ld?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);if(c=a.S.Grad)c.style.opacity=b==Md?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);a.Y=b}}
var Lc=3840,Mc=0,Nc=256,Oc=512,Pc=768,Qc=1024,Rc=1280,Sc=1792,Tc=2048,Uc=2304,Vc=2560,jd=3072,Wc=3328,vd=3584,Xc=3840,Zc=192,$c=6,ad=56,bd=3,cd=6,dd=1,ed=1,qd=3,rd=0,sd=1,td=2,ud=3,kd=192,ld=6,md=48,nd=4,od=12,pd=2,wd=15,xd=0,yd=1,zd=2,Ad=3,Bd=4,Cd=5,Dd=6,Ed=7,Fd=8,Gd=9,Hd=10,Z={},Yc=(Z[Mc]=[12,12],Z[Nc]=[0,15],Z[Oc]=[2,12],Z[Pc]=[0,12],Z[Qc]=[2,2],Z[Rc]=[0,1],Z[Sc]=[0,13],Z[Tc]=[14,14],Z[Uc]=[13,15],Z[Vc]=[14,15],Z[Wc]=[13,13],Z[Xc]=[15,15],Z),Kc=128,gd=0,fd=1,id=2,hd=3,Kd=1501,Od=0,Nd=1,Ld=2,Md=
3,Gc={i:"input",o:"output",om:"output modification"},Ec=0,Id=1,Y="A B C D 1 ? R5L R5".split(" "),Jd="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");C.CPU1500=Dc;
function Pd(a,b,c){M.call(this,a,a);var d=this;this.j=!1;this.H=c;this.h="";this.v=this.u=!1;gb(this,!1);this.ga=0;b=b.trim();"{"==b[0]?Qd(this,b):(this.h=b,Oa(this.h,function(e,f,g,h){4==g&&(!h&&f?(Qd(d,f),Rd(d)):d.s("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.v=!0;Rd(d)});window.addEventListener(Qa("iOS")?"pagehide":Qa("Opera")?"unload":"beforeunload",function(){Sd(d)});window.addEventListener("pageshow",function(){d.j||d.ia(!0)})}z(Pd,M);
Pd.prototype.za=function(a,b){var c=this;switch(a){case Td:b.onclick=function(){c.ia()};break;case Ud:b.onclick=function(){c.qa()}}M.prototype.za.call(this,a,b)};
function Rd(a){var b=!0;if(a.u&&a.v){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],C[d]?"Machine"==d?(a.s("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2023 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.s("Configuration: %s\n",a.h)):new C[d](a.M,c,e):a.s('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.s('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),ib(a,c)}}if(a.m){var f=Ra(a);fb(a,function(g){return g.Za&&!g.Za(f)?(g.s('unable to restore state for device "%s"\n',
g.X),!1):!0})}gb(a,!0);hb(a,a.ia.bind(a,b))||a.s("machine %s not ready to power, waiting for device(s)\n",a.M)}}
function Qd(a,b){try{a.g=JSON.parse(b);var c=a.g[a.M];if(!c){c=a.g[Ba(a.h)];if(!c)throw Error("configuration missing machine ID");a.g[a.M]=c}eb(a,c,["autoSave","autoStart"]);a.m=!1!==a.J.autoSave;a.I=!1!==a.J.autoStart;if(a.H){var d=eval("("+a.H+")"),e;for(e in d)a.J[e]=d[e]}a.u=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.s("machine '%s' initialization error: %s\n",a.M,c)}}
Pd.prototype.ia=function(a){a=void 0===a?!this.j:a;if(P(this)){var b=this;a&&this.s("power on\n");fb(this,function(c){c.ia&&c!=b&&("CPU"!=c.J["class"]||b.I&&P(b)?c.ia(a):c.time.update(!0));return!0});(this.j=a)||this.s("power off\n")}};Pd.prototype.qa=function(){if(P(this)){var a=this;fb(this,function(b){b.qa&&b!=a&&b.qa();return!0});this.s("reset\n")}};function Sd(a){if(a.m){var b=[];fb(a,function(c){c.$a&&c.$a(b);return!0});Ya(a,b)}a.ia(!1)}var Td="power",Ud="reset";
window.TMS1500=function(a,b,c){var d=new Pd(a,b,c);window.command=function(e){return Sa(d,e)};return d};C.Machine=Pd;})()

//# sourceMappingURL=ti57.js.map
