(function(){/*
 https://www.pcjs.org/machines/modules/v3/defines.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/message.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdlib.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdio.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/webio.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/device.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/input.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/led.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/time.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/bus.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/memory.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/rom.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/cpu.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/ti/modules/v3/cpu1500.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/machine.js (C) 2012-2025 Jeff Parsons
*/
var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function q(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)a=b.call(a);else if("number"==typeof a.length)a={next:aa(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function u(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function y(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.se=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
u("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});u("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
u("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});u("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
u("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}u("Array.prototype.keys",function(a){return a?a:function(){return na(this,function(b){return b})}});
u("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function z(a){return a?a:Array.prototype.fill}u("Int8Array.prototype.fill",z);u("Uint8Array.prototype.fill",z);u("Uint8ClampedArray.prototype.fill",z);u("Int16Array.prototype.fill",z);u("Uint16Array.prototype.fill",z);u("Int32Array.prototype.fill",z);
u("Uint32Array.prototype.fill",z);u("Float32Array.prototype.fill",z);u("Float64Array.prototype.fill",z);u("Number.parseInt",function(a){return a||parseInt});u("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});function oa(){this.U=""}var pa=new ArrayBuffer(2);(new DataView(pa)).setUint16(0,256,!0);new Uint16Array(pa);
var B={ee:"undefined"!=typeof window,node:"undefined"!=typeof window?{}:global,process:"undefined"!=typeof process?process:{},window:"undefined"!=typeof window?window:global,document:"undefined"!=typeof document?document:{},Oa:{machines:{},components:[],commands:{},files:null}};B.window.PCjs?B.Oa=B.window.PCjs:B.window.PCjs=B.Oa;var qa=B.process,D=B.Oa.machines,ra=B.Oa.components,E={};E.Defines=oa;
var sa={all:0xffffffffffff,addr:1,bus:2,fault:4,memory:8,ports:16,chips:32,kbd:64,serial:128,misc:256,cpu:512,mmu:2048,"int":1024,trap:4096,video:8192,monitor:16384,screen:32768,disk:131072,file:65536,time:262144,timer:524288,event:1048576,input:2097152,key:4194304,mouse:8388608,touch:16777216,info:274877906944,warn:549755813888,error:1099511627776,halt:70368744177664,buffer:0x800000000000};function ta(){this.g={};for(var a=0;23>a;a++)this.g["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
function ua(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,q(a)));return a}
ta.prototype.K=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(void 0===this.g[g])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];"%"!=g&&e++}else h=b[b.length-1];var k=!1,m=d[f+1],n=0<=m.indexOf("#"),r=0<=m.indexOf("0"),l=d[f+2];"*"==l?(l=h,h=e<b.length?b[e++]:b[b.length-1]):l=+l||0;var t=d[f+3];t=t?+t.substr(1):-1;var v=d[f+4],
w=null,A=0,x="",C=0<="ACDFGHMNSTWY".indexOf(g)&&"object"!=typeof h?ua(h):h;switch(g){case "C":c+=isNaN(C.getTime())?void 0:this.K("%#W, %#F %#D, %#Y".replaceAll("#",n?"#":""),C);continue;case "D":h=n?C.getUTCDate():C.getDate();g="d";break;case "A":case "G":case "H":h=n?C.getUTCHours():C.getHours();"A"==g?(h=12>h?"am":"pm",g="s"):("G"==g&&(h=h?12<h?h-12:h:12),g="d");break;case "F":case "M":h=n?C.getUTCMonth():C.getMonth();"F"==g?(h=va[h],g="s"):(h++,g="d");break;case "N":h=n?C.getUTCMinutes():C.getMinutes();
g="d";break;case "S":h=n?C.getUTCSeconds():C.getSeconds();g="d";break;case "T":c+=isNaN(C.getTime())?void 0:this.K("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",n?"#":""),C);continue;case "W":h=wa[n?C.getUTCDay():C.getDay()];g="s";break;case "Y":h=n?C.getUTCFullYear():C.getFullYear(),0<t&&(h%=Math.pow(10,t)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=t&&(r=!0,l<t&&(l=t),t=-1);case "f":h=+h;g=h+"";0<=t&&(g=h.toFixed(t));g.length<l&&(r?(0>h&&(l--,g=g.substr(1)),
g=("0".repeat(l)+g).slice(-l),0>h&&(g="-"+g)):g=(" ".repeat(l)+g).slice(-l));c+=g;break;case "j":c+=JSON.stringify(h,null,l||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=t&&(h=h.substr(0,t));h.length<l;)h=0<=m.indexOf("-")?h+" ":" "+h;c+=h;break;case "B":A=2,n&&(x="0b");case "o":A||(A=8),!x&&n&&(x="0o");case "X":w=xa;case "x":g="";A||(A=16);!x&&n&&(x="0x");w||(w=ya);"string"==typeof h&&"-"==h[0]&&(k=!0,h=
h.slice(1));h=Math.trunc(h);k&&(h=-h);0>h&&((h|0)==h?h>>>=0:Math.abs(h)<=Math.pow(2,53)&&(h+=Math.pow(2,53)));0<=t&&(r=!0,l<t&&(l=t));r&&!l&&("b"==v?l=2:"h"==v||"w"==v?l=4:"l"==v?l=8:(l=Math.abs(h),l=255>=l?2:65535>=l?4:4294967295>=l?8:9),l+=x.length);l-=x.length;do k=16,Number.isNaN(h)||(k=h&A-1,h=Math.trunc(h/A)),r||!g||k||h?g=w[k]+g:(x&&(g=x+g,x=""),0<l&&(g=" "+g));while(0<--l||h);c+=x+g;break;case "%":c+="%";break;default:c=this.g[g]?c+this.g[g](g,m,l,t,h):c+("(unimplemented sprintf type: %"+
g+")")}}}return c+=d[f]};var wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" "),ya="0123456789abcdef?",xa="0123456789ABCDEF?";function za(){oa.apply(this,arguments)}y(za,oa);function Aa(a,b){var c=a/F|0,d=b/F|0;return(a&b)==(b|0)&&(c&d)==d}var F=Math.pow(2,32);E.StdLib=za;function G(){za.call(this);this.format=new ta;this.W=this.format.K.bind(this.format)}y(G,za);
G.prototype.flush=function(){var a=Ba;Ba="";this.ta(a)};function Ca(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}G.prototype.ta=function(a,b){var c=a.length,d=a.lastIndexOf("\n");b?0<=d&&(b=Date.now(),Da||(Da=b),a=((b-Da)/1E3).toFixed(3)+": "+a,c=a.length):"node"==this.U?(qa.re.write(a),a=""):(0<=d&&(console.log(Ba+a.slice(0,d)),Ba="",a=a.slice(d+1)),Da=null);Ba+=a;return c};
G.prototype.s=function(a){return this.ta(this.W.apply(this,[a].concat(q(la.apply(1,arguments)))))};var Ba="",Da=null;E.StdIO=G;function H(a){G.call(this);this.R={};this.fa=0;this.K=this;a&&(this.K.fa=0,this.K.sa=[],this.K.ja=0,this.K.Ga={},this.K.ae=!1)}var Ea;y(H,G);p=H.prototype;
p.ya=function(a,b){var c=this,d=this;this.R[a]=b;switch(a){case Fa.Tb:b.onclick=function(){var e=c.Aa(Fa.Wa,!0);e&&(e.value="")};break;case Fa.Wa:Ga(b),b.addEventListener("keydown",function(e){Ha(d,e,!0)}),b.addEventListener("keypress",function(e){Ha(d,e)})}};
function Ia(a,b){b=void 0===b?{}:b;if("undefined"!=typeof document){a.config.R||(a.config.R=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.U);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.R[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.R[d].push(e)}while(1);continue}(f=document.getElementById(e))&&a.ya(d,f)}}}
function Ga(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}p.error=function(a,b){b=this.W.apply(this,[a].concat(q(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.W.apply(this,[c].concat(q(b))))this.s("%s\n",b),a||alert(b)};p.Aa=function(a){return this.R[a]};
function Ja(a){var b=window;if(b){do{for(var c=0;c<Ka.length;c++){var d=Ka[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function La(a,b){return a.config.bindings&&a.config.bindings[b]}function Ma(a){if(a=a.R[Na])var b=a.textContent;return b}function Oa(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function I(a,b,c,d){a=a.config[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Pa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Qa(a){if(void 0===J.Ta){var b=!1;if(window)try{window.localStorage.setItem(J.xa,J.xa),b=window.localStorage.getItem(J.xa)==J.xa,window.localStorage.removeItem(J.xa)}catch(c){a.s("%s\n",c.message),b=!1}J.Ta=b}return!!J.Ta}function K(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.fa;return-1==(b|1)||Aa(a.K.fa,b)?!0:!1}
function Ra(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Sa(a){var b=null;if(Qa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.L))&&(b=JSON.parse(c))}catch(d){a.s("%s\n",d.message)}}return b}
function Ha(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.K,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==L.cb&&f.selectionStart<=h+1&&(a=!0);d==L.yc?(a=!0,0<e.ja&&(g=e.sa[--e.ja])):d==L.Wb&&(a=!0,e.ja<e.sa.length&&(g=e.sa[++e.ja]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ja&&c+1==g.length&&
(f.value+=e.sa[--e.ja],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ta(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&a.s("%s\n",b.replace(/\n$/,"")))}}
function Ua(a,b){if(void 0!=b){var c=a.K;try{if(b=b.trim())c.ja<c.sa.length&&b==c.sa[c.ja]?c.ja++:(c.sa.push(b),c.ja=c.sa.length);var d=b.split(" "),e=d[0],f=a.K.Ga[Va.gb];switch(e[0]){case "m":if("?"==e[1]){var g="";Wa.forEach(function(r){g+=r+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var k="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=k&&d.pop();1>=d.length&&(void 0!=k&&(h=k,k=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(sa));for(f=
1;f<d.length;f++){e=d[f];var m=sa[e];if(!m){g+="unrecognized message: "+e+"\n";break}void 0!=k&&Xa(a,m,k);if(void 0==h||h==K(a,m))g+=a.W("%8s: %b\n",e,K(a,m))}K(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ya.forEach(function(r){g+=r+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var n=f[a](d);if(void 0!=n){g=g?g+n:n;break}}}}catch(r){g="error: "+r.message+"\n"}}return g}
function Ta(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Ua(a,b[d])}return c}
p.ta=function(a,b){void 0==b&&(b=K(this,0x800000000000));if(!b){var c=this.Aa(Fa.Wa,!0);if(c){b=c.selectionStart;for(var d=a.split(/([\n\r\b])/),e=0;e<d.length;e++){var f=d[e];if(f)if("\b"==f||"\r"==f)for(;0<b&&"\n"!=c.value.slice(b-1,b)&&(b--,"\b"!=f););else if("\n"==f){for(f="";b<c.value.length&&(f=c.value[b],b++,"\n"!=f););"\n"!=f&&(c.value+="\r\n",b=c.value.length)}else c.value=c.value.slice(0,b)+f+c.value.slice(b+f.length),b+=f.length}c.focus();c.setSelectionRange(b,b);8192<=c.value.length&&
(c.value=c.value.slice(c.value.length-8192+4096));c.scrollTop=c.scrollHeight;return a.length}}return G.prototype.ta.call(this,a,b)};p.s=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return K(this,c)?(Aa(c,1099511627776)&&(a="error: "+a),Aa(c,549755813888)&&(a="warning: "+a),G.prototype.s.call.apply(G.prototype.s,[this,a].concat(q(b)))):0};function Za(a,b){if(Qa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.L,b)}catch(c){a.s("%s\n",c.message)}}}
function M(a,b,c){(a=a.R[b])&&a.textContent!=c&&(a.textContent=c)}function Xa(a,b,c){var d=!1;c?(c=a.K.fa,a.K.fa=(c|b)+(c/F|0|b/F|0)*F):(d=Aa(a.K.fa,0x800000000000)&&Aa(b,0x800000000000),c=a.K.fa,a.K.fa=(c&~b)+((c/F|0)&~(b/F|0))*F);d&&a.flush()}
var Fa={Tb:"clear",Wa:"print"},Ya=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Wa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],Va={gb:"command"},$a={hb:13,Sa:65,bb:66,eb:67,ib:68,E:69,jb:70,kb:71,lb:72,mb:73,nb:74,pb:75,rb:76,tb:77,ub:78,vb:79,xb:80,Q:81,yb:82,Ab:83,Bb:84,Cb:85,Db:86,Eb:87,Fb:88,
Gb:89,Ya:90,a:97,b:98,c:99,d:100,e:101,f:102,je:103,ke:104,le:105,me:106,k:107,ne:108,oe:109,n:110,pe:111,p:112,q:113,r:114,qe:115,t:116,te:117,ue:118,w:119,x:120,y:121,z:122},L={cb:8,uc:9,hc:10,hb:13,qc:16,Ub:17,Sb:18,Rd:19,Ua:20,Sc:27,sc:32,Ud:33,Td:34,Rc:35,nd:36,sb:37,yc:38,Xa:39,kd:39,Wb:40,gd:44,Vd:44,od:45,Qc:46,jd:46,md:47,ZERO:48,ONE:49,wc:50,vc:51,dc:52,cc:53,rc:54,pc:55,Xb:56,ic:57,bc:59,ac:61,Sa:65,bb:66,eb:67,ib:68,E:69,jb:70,kb:71,lb:72,mb:73,nb:74,pb:75,rb:76,tb:77,ub:78,vb:79,xb:80,
Q:81,yb:82,Ab:83,Bb:84,Cb:85,Db:86,Eb:87,Fb:88,Gb:89,Ya:90,fb:91,hd:91,fd:92,Yd:93,ld:93,sd:96,Jd:96,ed:96,td:97,Hd:97,ud:98,Gd:98,vd:99,Md:99,wd:100,Kd:100,xd:101,Dd:101,yd:102,Od:102,zd:103,Id:103,Ad:104,Qd:104,Bd:105,Nd:105,Ld:106,Cd:107,Pd:109,Ed:110,Fd:111,Tc:112,Xc:113,Yc:114,Zc:115,$c:116,ad:117,bd:118,cd:119,dd:120,Uc:121,Vc:122,Wc:123,jc:144,nc:145,$b:173,oc:186,Yb:187,Pc:188,Vb:189,Sd:190,$d:191,Nc:192,pd:219,Oc:220,Xd:221,Wd:222,Zb:224,qd:901,be:1E3},ab={},bb=(ab[L.bc]=L.oc,ab[L.ac]=L.Yb,
ab[L.$b]=L.Vb,ab[L.Zb]=L.fb,ab),cb={sb:1,Xa:2,rd:3},N={},db=(N[L.cb]="\b",N[L.uc]="\t",N[L.hc]="\n",N[L.hb]="\r",N[L.sc]=" ",N[L.ZERO]="0",N[L.ONE]="1",N[L.wc]="2",N[L.vc]="3",N[L.dc]="4",N[L.cc]="5",N[L.rc]="6",N[L.pc]="7",N[L.Xb]="8",N[L.ic]="9",N[L.Sa]="A",N[L.bb]="B",N[L.eb]="C",N[L.ib]="D",N[L.E]="E",N[L.jb]="F",N[L.kb]="G",N[L.lb]="H",N[L.mb]="I",N[L.nb]="J",N[L.pb]="K",N[L.rb]="L",N[L.tb]="M",N[L.ub]="N",N[L.vb]="O",N[L.xb]="P",N[L.Q]="Q",N[L.yb]="R",N[L.Ab]="S",N[L.Bb]="T",N[L.Cb]="U",N[L.Db]=
"V",N[L.Eb]="W",N[L.Fb]="X",N[L.Gb]="Y",N[L.Ya]="Z",N[L.sb]="Left",N[L.Xa]="Right",N),Ka=["","moz","ms","webkit"],eb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",
darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",
fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",
navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},J={Ta:void 0,xa:"PCjs.localStorage"};E.WebIO=H;
function O(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;H.call(this,a==b);this.L=a;this.U=b;D[this.L]||(D[this.L]={});D[this.L][this.U]&&this.s("warning: machine configuration contains multiple '%s' devices\n",this.U);D[this.L][this.U]=this;this.id=this.L==this.U?this.L:this.L+"."+this.U;ra.push(this);this.K=P(this,this.L);this.ready=!0;fb(this,c,d);this.tc={};this.qb=[]}y(O,H);
function fb(a,b,c){c=b.overrides||c;if(c.length){var d,e=Ea;if(!e){e={};if(window){d||(d=window.location.search.slice(1));for(var f,g=/\+/g,h=/([^&=]+)=?([^&]*)/g;f=h.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ea=e}d=e;for(var k in d)if(0<=c.indexOf(k)){e=d[k];f=void 0;var m;g=void 0;h=e;var n=10;if(h){n||(n=10);var r=0<h.indexOf(",");r&&(h=h.replace(/,/g,""));var l=m=h.charAt(0);"#"==m?(n=8,m=""):"$"==m&&(n=16,m="");l!=m?h=h.substr(1):
(l=m=h.substr(0,2),"0b"==m&&r||"^B"==m?(n=2,m=""):"0o"==m||"^O"==m?(n=8,m=""):"^D"==m?(n=10,m=""):"0x"==m&&(n=16,m=""),l!=m&&(h=h.substr(2)));l=m=h.slice(-1);"Y"==m||"y"==m?(n=2,m=""):"."==m?(n=10,m=""):"H"==m||"h"==m?(n=16,m=""):"K"==m?m="000":"M"==m?m="000000":"G"==m&&(m="000000000");l!=m&&(h=h.slice(0,-1)+m);l=0;10>=n&&(m=h.match(/(-?[0-9]+)B([0-9]*)$/))&&(h=m[1],l=35-((m[2]||35)&255));(n&&10!=n?16==n?null===h.match(/^-?[0-9a-f]+$/i):8==n?null===h.match(/^-?[0-7]+$/):2!=n||null===h.match(/^-?[01]+$/):
null===h.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(h,n))||(l&&(0>f&&(f+=Math.pow(2,36)),f=0<l?f*Math.pow(2,l):Math.trunc(f/Math.pow(2,-l))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[k]=f;a.s("overriding %s property '%s' with %s\n",a.U,k,e)}}a.config=b;Ia(a,b.bindings);b=void 0===b?{}:b;a.version=3;if(a.version){c="";var t;a.L!=a.U&&(t=P(a,a.L).version)&&t!=a.version&&(c="Machine");c||(t=b.version)&&t>a.version&&(c="Config");c&&(t=a.W("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.fe,a.version,c,t),a.error("%s\n\nClearing your browser's cache may resolve the issue.",t))}}function gb(a,b){var c;try{var d=D[a.L];if(d)for(c in d){var e=d[c];if(e.U!=e.L&&!b(e))return!1}return!0}catch(f){a.s("error while enumerating device '%s': %s\n",c,f.message)}return!1}O.prototype.Aa=function(a,b){b=void 0===b?!1:b;if(a){var c=H.prototype.Aa.call(this,a,b);if(void 0===c&&b){b=D[this.L];for(var d in b)if(c=b[d].R[a])break;c||(c=null);this.R[a]=c}}return c};
function P(a,b,c){var d=b,e=a.L,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=D[e])&&f[b]||null;if(!b){for(f=0;f<ra.length;f++)if(ra[f].id===d){b=ra[f];break}if(!b&&(void 0===c||c))throw Error(a.W('no "%s" device',d));}return b}function Q(a,b,c){var d=null,e=D[a.L];if(e)for(var f in e)if(e[f].config["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.W("no %s device",b));return d}function hb(a){return a==a.K&&a.ready?gb(a,function(b){return hb(b)}):a.ready}
function ib(a,b){b=void 0===b?a.ready:b;a.ready=b;if(hb(a)){for(;b=a.qb.pop();)b();a!=a.K&&ib(a.K)}}function jb(a,b){if(hb(a))return b(),!0;a.qb.push(b);return!1}
O.prototype.s=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&K(this,a)&&(void 0===this.ea&&(this.ea=Q(this,"Debugger",!1)),this.K.fa&1&&(void 0===this.ca&&(this.ca=Q(this,"CPU")),this.ca))?(a=b.shift(),H.prototype.s.call(this,"%#06x: %s.%s\n",this.ca.Pa,this.U,this.W.apply(this,[a].concat(q(b))).trim())):H.prototype.s.call.apply(H.prototype.s,[this,a].concat(q(b)))};function kb(a,b){(a=D[a.L])&&delete a[b]}O.prototype.Nb=function(a,b){(a=this.tc[a])&&a.set&&a.set(b)};E.Device=O;
function lb(a,b,c){O.call(this,a,b,c);this.fa=2097152;this.J=this.N=null;this.time=Q(this,"Time");this.K=Q(this,"Machine");this.aa=I(this,"drag",!1);this.X=I(this,"scroll",!1);this.$=I(this,"hexagonal",!1);this.u=I(this,"releaseDelay",0);this.v=!1;a=this.config.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.j[f]={keys:g,
grid:e,state:0}}}this.O=[];this.S=[];this.m=this.T=null;(a=this.R[mb])&&nb(this,a,this.Aa(c.focusBinding,!0),this.config.location);this.pa()}y(lb,O);function ob(a,b){a.N=b}function pb(a,b,c){for(var d=0;d<a.O.length;d++){var e=a.O[d];e.id===b&&e.Lb(b,c)}}
function nb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.Lc=d[0]||0;e.Mc=d[1]||0;e.za=d[2]||b.clientWidth;e.Ka=d[3]||b.clientHeight;e.La=d[4]||1;e.Qa=d[5]||1;e.Cc=d[6]||b.naturalWidth||e.za;e.Ec=d[7]||b.naturalHeight||e.Ka;e.Qb=d[8]||0;e.Rb=d[9]||0;e.Bc=d[10]||0;e.Dc=d[11]||0;a.h?(e.Na=a.h.length,e.Ba=a.h[0].length):(e.Ba=e.La,e.Na=e.Qa,e.La=e.Qa=0);e.Hb=e.za/(e.Ba+e.Ba*e.La)|0;e.Ib=e.Ka/(e.Na+e.Na*e.Qa)|0;e.Ac=e.Hb*e.La|0;e.Jb=e.Ib*e.Qa|0;e.Fa=e.Ra=-1;qb(a,b,e);rb(a,b,e);a.time&&
a.u&&(a.Z=sb(a.time,"timerInputRelease",function(){0>e.Fa&&0>e.Ra&&tb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.u&&(a.ba=sb(a.time,"timerKeyRelease",function(){ub(a)})),a.H=0,a.M="",a.I=[],d=b,c&&(d=c,a.m||"BUTTON"!=c.nodeName||(d=document,a.m=c,vb(a,b),a.T=b)),vb(a,d),a.m||(a.m=d)}function wb(a){a.u?xb(a.time,a.ba,a.u):ub(a)}
function vb(a,b){function c(e,f,g){var h=document.activeElement;a.s(5242880,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.m&&e!=a.m&&e!=a.T?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=yb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=yb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=yb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function qb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.v){var e=a.m;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,zb,d,c)}});b.addEventListener("mousemove",function(d){a.v||R(a,b,Ab,d,c)});b.addEventListener("mouseup",function(d){a.v||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.v||(0>c.Fa?R(a,b,Ab,d,c):R(a,b,S,d,c))})}
function rb(a,b,c){b.addEventListener("touchstart",function(d){a.X&&(a.v=!0);R(a,b,zb,d,c)});b.addEventListener("touchmove",function(d){R(a,b,Ab,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function yb(a,b,c,d){if(void 0!=c){var e=bb[b]||b;var f=db[b];var g=Bb[e];d=d&&d.location==cb.Xa;g&Cb&&d&&(g>>=1);g&&(g&Db&&(c=!(a.g&g)),a.g=c?a.g|g:a.g&~g,pb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=$a.Sa&&b<=$a.Ya?a.g&(Eb|Fb)||(a.g|=Fb,pb(a,L.Ua,!0)):b>=$a.a&&b<=$a.z&&a.g&Fb&&(a.g&=~Fb,pb(a,L.Ua,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(g=a.h[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.H?16>a.I.length&&a.I.push(b):(a.H=1,a.M=f,tb(a,d,e),pb(a,
f,!0),wb(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(g=b[e],0<=a.j[g].keys.indexOf(f))return pb(a,g,c),a.j[g].state=c?1:0,!0}return!1}function ub(a){1==a.H?(a.H++,pb(a,a.M,!1),a.M="",tb(a,-1,-1),wb(a)):(a.H=0,a.I.length&&yb(a,a.I.shift()))}lb.prototype.pa=function(){this.g=0;this.V=this.Y=-1};
function R(a,b,c,d,e){var f=-1,g=-1,h=!1,k=-1,m=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,m=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(k=d.clientX,m=d.clientY);var n=d.target.getBoundingClientRect();k-=n.left;m-=n.top;k=e.Cc/b.offsetWidth*k|0;m=e.Ec/b.offsetHeight*m|0;var r=k-e.Lc;var l=m-e.Mc;var t=n=!1;var v=k>=e.Qb&&k<e.Qb+e.Bc&&m>=e.Rb&&m<e.Rb+e.Dc;if(0<=r&&r<e.za&&0<=l+e.Jb||v)if(h||a.X||d.preventDefault(),0<=r&&r<e.za&&0<=
l&&l<e.Ka){t=!0;d=e.za/e.Ba|0;var w=e.Ka/e.Na|0,A=r/d|0,x=l/w|0;!a.$||x&1||(r-=d>>1,A=r/d|0,A==e.Ba-1&&(r=-1));w=x*w+(e.Jb>>1);r-=A*d+(e.Ac>>1);l-=w;0<=r&&r<e.Hb&&0<=l&&l<e.Ib&&(f=A,g=x,n=!0)}}r=r||0;l=l||0;d=b.offsetWidth;b=b.offsetHeight;if(c==zb||c==S)for(A=0;A<a.S.length;A++)x=a.S[A],c==S?x.Lb(x.id,!1):(w=l/(b/x.he|0)|0,(r/(d/x.ge|0)|0)==x.ve&&w==x.we&&x.Lb(x.id,!0));if(!h)if(c==zb)e.Fa=k,e.Ra=m,t?(tb(a,f,g),n&&a.u&&xb(a.time,a.Z,a.u,!0)):v&&a.K.ha();else if(c==Ab)0<=e.Fa&&0<=e.Ra&&a.aa?tb(a,
f,g):a.N&&a.N(f,g);else if(c==S){if(c=a.u)c=a.time,f=a.Z,c=c.g&&0<f&&f<=c.h.length?0<=c.h[f-1].ga:!1;c||tb(a,-1,-1);e.Fa=e.Ra=-1}else a.s("unrecognized action: %d\n",c)}function tb(a,b,c){if(b!=a.V||c!=a.Y)a.V=b,a.Y=c,a.J&&a.J(b,c)}var zb=1,Ab=2,S=3,mb="surface",Eb=3,Cb=170,Fb=512,Db=3584,T={},Bb=(T[L.qc]=2,T[L.Ub]=8,T[L.Sb]=32,T[L.fb]=128,T[L.Ua]=Fb,T[L.jc]=1024,T[L.nc]=2048,T);E.Input=lb;
function Gb(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.R[Hb];if(!a)throw Error("LED "+this.config.R[Hb]+" binding for '"+Hb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.ua=La(this,Hb)+".canvas";b.setAttribute("id",this.ua);this.Va=a;this.type=Oa(I(this,"type",Ib,Jb),Kb,Lb);this.m=Mb[this.type][0];this.I=Mb[this.type][1];this.width=I(this,"width",
this.m);this.height=I(this,"height",this.I);this.u=I(this,"cols",1);this.O=this.u+I(this,"colsExtra",0);this.aa=I(this,"rows",1);this.V=this.aa+I(this,"rowsExtra",0);this.da=this.width*this.u;this.Y=this.height*this.aa;this.H=Nb("black",0);this.j=Ob(this.config.color)||this.H;this.ma=Nb(this.j,1,.25);this.la=Nb(this.j,1,2);this.v=Ob(this.config.backgroundColor);this.na=I(this,"fixed",!1);this.na||(b.style.width="100%",b.style.height="auto");this.ka=I(this,"hexagonal",!1);this.ra=I(this,"highlight",
!0);this.X=I(this,"persistent",this.type<Lb);b.setAttribute("width",this.da.toString());b.setAttribute("height",this.Y.toString());b.style.backgroundColor=this.H;a.appendChild(b);this.ia=b.getContext("2d");if(this.J=document.createElement("canvas"))this.J.width=this.ba=this.m*this.u,this.J.height=this.M=this.I*this.aa,this.h=this.J.getContext("2d");this.va=(this.V+1)*this.O*4;this.g=Array(this.va);this.Ha=this.u<this.O?4*(this.O-this.u):0;this.S=this.T=!1;this.N=this.$=0;this.Z=-1;var d=this;this.time=
Q(this,"Time");Pb(this.time,function(e,f){Qb(d,!1,e,f)});Rb(d)}y(Gb,O);function Rb(a){for(var b=a.g,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Lb?Sb:" ";e[f+1]=d.j==d.H?null:d.j;e[f+2]=0;e[f+3]=Tb}a.S=a.T=!0;Qb(a,!0)}function Ub(a){a.v?(a.h.fillStyle=a.v,a.h.fillRect(0,0,a.ba,a.M)):a.h.clearRect(0,0,a.ba,a.M)}
function Qb(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.S||b){if(a.type<Lb){d=0;if(!a.X||b)Ub(a);else if(a.N){d=a.u-a.N;var e=a.m*d;a.h.drawImage(a.J,a.m*a.N,0,e,a.M,0,0,e,a.M)}for(var f=e=0;f<a.V;f++){for(var g=0;g<a.u;g++){var h=a.g[e],k=a.g[e+1]||a.H,m=a.ra&&e==a.Z;if(a.g[e+3]&Tb||m||b){if(g>=d)a:{var n=a,r=h;h=k;var l=g;k=f;var t=m;l=void 0===l?0:l;k=void 0===k?0:k;t=void 0===t?!1:t;var v=0;if(n.ka&&!(k&1)&&(v=n.m>>1,l==n.u-1))break a;if(h&&h!=n.j){t=t?Nb(h,1,2):h;var w=
Nb(h,1,.25)}else t=t?n.la:n.j,w=n.ma;h=!1;r=r?t:w;t==n.H&&(r=n.v,h=!0);t=l*n.m+v;w=k*n.I;n.X&&(l=l*n.m+v,k*=n.I,n.v?(n.h.fillStyle=n.v,n.h.fillRect(l,k,n.m,n.I)):n.h.clearRect(l,k,n.m,n.I));n.h.fillStyle=r;k=Vb[n.type];3==k.length?(n.h.beginPath(),n.h.arc(t+k[0],w+k[1],k[2],0,2*Math.PI),h?(n.h.globalCompositeOperation="destination-out",n.h.fill(),n.h.globalCompositeOperation="source-over"):n.h.fill()):n.h.fillRect(t+k[0],w+k[1],k[2],k[3])}a.g[e+3]=m?a.g[e+3]|Tb:a.g[e+3]&~Tb}e+=4}e+=a.Ha}a.N=0}else{b=
"";for(d=0;d<a.g.length;d+=4)b+=a.g[d]||" ",a.g[d+3]&Wb&&(b+=".");Ub(a);for(f=e=d=0;d<b.length;d++){m=b[d];"."==m&&e&&e--;g=a;k=m;m=e;n=f;m=void 0===m?0:m;n=void 0===n?0:n;if(k=Xb[k])for(h=0;h<k.length;h++)if(l=g,v=Yb[k[h]]){r=(void 0===m?0:m)*l.m;t=(void 0===n?0:n)*l.I;l.h.fillStyle=l.j;l.h.beginPath();if(3==v.length)l.h.arc(r+v[0],t+v[1],v[2],0,2*Math.PI);else for(w=0;w<v.length;w+=2)w?l.h.lineTo(r+v[w],t+v[w+1]):l.h.moveTo(r+v[w],t+v[w+1]);l.h.closePath();l.h.fill()}if(++e==a.u&&(e=0,++f==a.V))break}}a.ia.globalCompositeOperation=
a.v&&a.j!=a.H?"source-over":"copy";a.ia.drawImage(a.J,0,0,a.ba,a.M,0,0,a.da,a.Y);a.S=!1;a.Z=-1}else a.X||a.T||(!c||!a.$||c-a.$>=(1E3/d|0))&&Rb(a);a.T=!1;c&&(a.$=c)}function Ob(a){return(a=a||void 0)&&eb[a]||a}
function Nb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=eb[a]||a;var e=a;var f=16;var g=e.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);g||(f=10,g=e.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(g){for(e=1;e<g.length;e++)d[e-1]=Number.parseInt(g[e],f);d.length=e-1;f=!0}else f=!1;if(f){a="rgba(";for(f=0;3>f;f++)g=Math.round(d[f]*c),g=0>g?0:255<g?255:g,a+=g+",";a+=(f<d.length?d[f]:b)+")"}}return a}
Gb.prototype.oa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.j&&c==this.v&&a&&a.length==this.g.length){this.g=a;for(b=0;b<=this.g.length-4;b+=4)this.g[b+1]==this.H&&(this.g[b+1]=null);Qb(this,!0);return!0}return!1};Gb.prototype.qa=function(a){this.g&&(a.push(this.j),a.push(this.v),a.push(this.g))};
function Zb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&$b;b=4*(c*a.O+b);if(b<=a.g.length-4){if(a.g[b]!==d||(a.g[b+3]&$b)!==e)a.g[b]=d,a.g[b+3]=a.g[b+3]&~$b|e|Tb,a.S=f=!0;a.Z=b;a.T=!0;a.N=0}return f}
var Kb=0,Ib=1,Lb=3,Jb={small:Kb,round:Ib,square:2,digit:Lb},Hb="container",Sb=0,$b=129,Wb=1,Tb=128,ac={},Vb=(ac[Kb]=[4,4,4],ac[Ib]=[16,16,14],ac[2]=[2,2,28,28],ac),Mb=[[8,8],[32,32],[32,32],[96,128]],Yb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Xb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};E.LED=Gb;
function bc(a,b,c){O.call(this,a,b,c);this.na=I(this,"cyclesMinimum",1E5);this.Va=I(this,"cyclesMaximum",1E9);this.ra=Oa(I(this,"cyclesPerSecond",1E6),this.na,this.Va);this.aa=60;this.V=0;this.X=1E3/this.aa;this.mc=I(this,"updatesPerSecond",2)||2;this.lc=1E3/this.mc;this.Ha=0;this.xc=I(this,"timeLock",!0);this.la=this.O=0;this.ka=this.H=1;this.va=this.J=this.ra/1E4/100;this.da=[];this.M=[];this.h=[];this.ia=[];this.ua=this.g=this.ba=this.I=!1;this.N=this.m=0;a=Ja("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.X}this.wb=window[a].bind(window,this.Ic.bind(this),d);this.kc=window[Ja("cancelAnimationFrame")||"clearTimeout"].bind(window);this.$=this.Z=this.u=this.j=this.ma=0;cc(this)||dc(this,this.ka)}y(bc,O);function Pb(a,b){a.da.push(b)}p=bc.prototype;
p.ya=function(a,b){var c=this;switch(a){case ec:b.onclick=function(){fc(c)&&(c.g?U(c):c.start())};break;case gc:b.onclick=function(){dc(c,c.H<<1);hc(c,ic(c.J))};break;case jc:b.onclick=function(){kc(c)};break;case lc:b.addEventListener("mousedown",function(){c.I=!0}),b.addEventListener("mouseup",function(){cc(c);c.I=!1}),b.addEventListener("mousemove",function(){c.I&&cc(c)}),b.addEventListener("change",function(){c.I=!0;cc(c);c.I=!1})}O.prototype.ya.call(this,a,b)};
function sb(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,zc:c,Ma:d,ga:-1});0<=d&&xb(a,e,d);return e}
function mc(a,b,c,d){var e=0,f=a.J,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.s(262144,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.X&&(1<a.H&&(a.H>>=1,a.s(549755813888,"frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.X,a.H)),e=d));a.O=f;a.la=f/a.va;b=a.la/a.H;a.ma=g/b/a.aa+1E-8;a.s(262144,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.ma,g,b,a.aa);return e}
function nc(a,b){a.Z=a.u=b;if(!a.M.length)return a.u=0,a.Z;for(var c=0;0<a.u;){if(c<a.M.length){var d=a.M[c++];b=d.Jc.call(d,b)||1}else c=b=0;a.u-=b}return a.Z-a.u}function oc(a,b){var c=Date.now();b()&&(a.Y+=Date.now()-c)}function pc(a,b){b=void 0===b?a.Z-a.u:b;if(!a.g){if(a.j)for(var c=0;c<a.M.length;c++){var d=a.M[c];d.Ob.call(d)}a.j=b}a.j-=b;1>a.j&&(a.ba=!0);a.$+=b;a.Z=a.u=0;a.g||(a.$=0);return b}
function qc(a,b){b=void 0===b?0:b;if(b){var c=b;a.j+=b}else for(c=a.j,1>c&&(c=a.j+=a.ma),0>c&&(a.s(262144,"warning: cycle count dropped below zero: %f\n",c),c=a.j=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.ga)&&c>d.ga&&(c=d.ga)}return c}function ic(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function fc(a){return a.ua?!0:(a.s("not powered\n"),!1)}
function rc(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.ga||(d.ga-=b,0>=d.ga&&(d.ga=-1,d.zc(),0<=d.Ma&&xb(a,c,d.Ma)))}}p.ha=function(a){this.ua=a;void 0===this.ea&&(this.ea=Q(this,"Debugger",!1))};function kc(a,b){fc(a)&&(a.g?a.s("already running\n"):a.m?U(a):sc(a,b))}
p.Ic=function(a){a=void 0===a?Date.now():a;this.N=0;if(this.g){if(this.V){var b=a-this.V;1>b&&(b=16.67);this.aa=1E3/b}this.V=a;a=Date.now();this.S&&(b=a-this.T-this.X,b>this.X&&(this.v+=b,this.s(549755813888,"browser throttling detected, compensating by %5.3fms\n",b)));this.T=a;this.v||(this.v=a);this.Y=0;try{this.ba=!1;do rc(this,pc(this,nc(this,qc(this))));while(this.g&&!this.ba)}catch(c){this.s("%s\n",c.message),U(this)}this.S=Date.now();this.Y&&(this.v+=this.Y,this.T+=this.Y);this.T+=mc(this,
this.$,this.S-this.v,this.S-this.T);this.S-this.Ha>=this.lc&&this.update();for(a=0;a<this.da.length;a++)this.da[a](this.V,this.aa);this.N=this.wb()}};function dc(a,b){if(void 0!==b){if(1>b||!a.I&&0<a.O&&a.O<.9*a.J)b=a.ka;a.H=b;b=a.va*a.H;a.J!=b&&(a.J=b,hc(a,ic(a.J)))}a.v=a.S=0;a.j=a.$=0;mc(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.Ma&&xb(a,b,c.Ma,!0)}}function cc(a){var b=a.R[lc];return b?(dc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Va-a.na)+a.na)/a.ra|0),!0):!1}
function xb(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.ga)&&(c=Math.ceil(a.ra*(a.xc?a.ka:a.la)/1E3*(void 0===c?1E3:c)),a.g&&(c+=pc(a)),b.ga=c)}p.start=function(){if(this.g||this.m)return!1;this.g=!0;this.v=this.S=this.V=0;this.update(!0);this.N=this.wb();return!0};function sc(a,b){b=void 0===b?1:b;a.g||(b&&!a.m&&(a.m=b),a.m&&(a.m--,rc(a,pc(a,nc(a,qc(a,1)))),a.update(!1),a.m&&setTimeout(function(){sc(a,0)},0)))}
function U(a){return a.g?(a.g=!1,pc(a),a.N&&(a.kc(a.N),a.N=0),a.update(!0),!0):a.m?(a.m=0,a.update(!0),!0):!1}p.update=function(a){a&&this.s(this.g?"started with %s target\n":"stopped\n",ic(this.J));M(this,ec,this.g?"Halt":"Run");M(this,jc,this.m?"Stop":"Step");this.I||(this.s(262144,"getSpeedCurrent(%5.3fhz)\n",1E6*this.O),hc(this,this.g&&this.O?ic(this.O):"Stopped"));for(var b=0;b<this.ia.length;b++){var c=this.ia[b];c.Gc.call(c,void 0!=a)}this.Ha=Date.now();this.ba=!0};
function hc(a,b){M(a,tc,b);M(a,gc,b)}var ec="run",gc="setSpeed",tc="speed",jc="step",lc="throttle";E.Time=bc;
function uc(a,b,c){O.call(this,a,b,c);this.type="static"==this.config.type?vc:wc;this.v=this.config.addrWidth||16;this.j=Math.pow(2,this.v);this.I=this.j-1|0;this.blockSize=this.config.blockSize||(16<this.v?4096:1024);this.blockSize>this.j&&(this.blockSize=this.j);this.J=this.j/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.m=(1<<this.h)-1;this.H=this.config.dataWidth||8;this.g=Array(this.J);this.u=0;a=new V(a,b+"[NONE]",{size:this.blockSize,bus:this.U});for(b=0;b<this.j;b+=this.blockSize)xc(this,
b,this.blockSize,W.NONE,a);a=this.u;this.u+=this.type;a&&this.u||(this.Ca=this.ec,this.Da=this.Ea)}y(uc,O);
function xc(a,b,c,d,e){for(var f=b>>>a.h;0<c&&f<a.g.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var k=a.g[f];if(b!=g||h!=a.blockSize||k&&k.type!=W.NONE)break;var m=k=void 0,n=a,r=b,l=a.v,t=16;l=void 0===l?0:l;k=void 0===k?0:k;var v="",w="",A=-1;t||(t=n.ce||10);l&&(A=Math.ceil(l/Math.log2(t)));if(void 0==m)switch(t){case 8:m="0o";break;case 16:m="0x";break;case 10:w=".";default:m=""}isNaN(r)||"number"!=typeof r?(r=void 0,m=w=""):(0>r&&-1<r&&(r=-1),l&&(0>r&&(r+=Math.pow(2,l)),r>=Math.pow(2,
l)&&(A=Math.ceil(Math.log(r)/Math.log(t)))));for(n=k||-1;A--;){n||(v=","+v,n=k);if(void 0==r){if(v="?"+v,0>A)break}else if(l=r%t,r=Math.trunc(r/t),l+=0<=l&&9>=l?48:55,v=String.fromCharCode(l)+v,!r&&0>A)break;n--}k=a.U+"["+(m+v+w)+"]";b=e?e.size==a.blockSize?e:new V(a.L,k,{type:d,Ja:b,size:h,bus:a.U}):new V(a.L,k,{type:d,Ja:b,size:h,bus:a.U});a.g[f]=b;b=g+a.blockSize;c-=h;f++}}p=uc.prototype;p.ie=function(a,b){this.ea&&this.ea.s(4,"bus fault (%d) at %n\n",b,a)};
p.ha=function(){void 0===this.ea&&(this.ea=Q(this,"Debugger",!1))};p.pa=function(){};p.Za=function(a){return a&&this.oa(a)?!0:!1};p.$a=function(a){this.qa(a)};p.oa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==wc||c.type&W.Ia)&&c.oa){var d=a.shift();if(!c.oa(d))return!1}}return!0};p.qa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==wc||c.type&W.Ia)&&c.qa){var d=[];c.qa(d);a.push(d)}}};p.wa=function(a){return this.g[a>>>this.h].wa(a&this.m)};
p.ec=function(a){return this.g[a>>>this.h].Ca(a&this.m)};p.ab=function(a,b){this.g[a>>>this.h].ab(a&this.m,b)};p.Ea=function(a,b){this.g[a>>>this.h].Da(a&this.m,b)};var vc=0,wc=1;E.Bus=uc;
function V(a,b,c){O.call(this,a,b,c);this.Ja=this.config.addr;this.size=this.config.size;this.type=this.config.type||W.NONE;this.m=(a=this.config.bus)?P(this,a):Q(this,a="Bus");if(!this.m)throw Error(this.W("unable to find bus '%s'",a));this.v=this.m.H;this.J=Math.pow(2,this.v)-1;this.u=this.I=!1;this.values=this.j=null;a=this.ob;b=this.Ea;if(this.m.type==vc){b=this.Kc;if(c=8==this.v)c=P(this,this.L),c=!1!==(c&&c.config&&c.config.ArrayBuffer||this.config.ArrayBuffer);c&&(this.I=!0)}switch(this.type){case W.NONE:this.Ca=
this.Hc;this.Da=this.Pb;break;case W.zb:this.Ca=a;this.Da=this.Pb;break;case W.Ia:this.Ca=a,this.Da=b}yc(this,this.config.values);zc(this)}y(V,O);function yc(a,b){"string"==typeof b?(ib(a,!1),Pa(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);yc(a,g.values)}catch(h){a.s("error (%s) parsing resource: %s\n",h.message,c)}ib(a,!0)}else a.s("error (%d) loading resource: %s\n",f,c)})):a.config.values=b}
function zc(a,b){if(a.type>W.NONE&&(a.I?(a.j=new ArrayBuffer(a.size),new DataView(a.j,0,a.size),a.values=new Uint8Array(a.j,0,a.size),new Uint16Array(a.j,0,a.size>>1),new Int32Array(a.j,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}p=V.prototype;
p.pa=function(){if(this.config.values)a:{var a=this.m,b=this.Ja,c=this.size,d=this.config.values,e=0,f=b&a.m;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var g=a.g[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Ea(f++,d[e++]),c--;f=0}}else this.type&W.Ia&&this.values&&this.values.fill(0)};p.Hc=function(){return this.J};p.wa=function(a){return this.values?this.values[a]:0};p.ob=function(a){return this.values[a]};p.Pb=function(){};p.ab=function(a,b){this.values&&(this.values[a]=b)};
p.Ea=function(a,b){this.values[a]=b};p.Kc=function(a,b){this.values[a]=b;this.u=!0;this.Da=this.Ea};p.oa=function(a){if(a){var b=a.shift();if(this.U==b){this.u=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}zc(this,a)}return!0}}return!1};
p.qa=function(a){a.push(this.U);a.push(this.u);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var W={NONE:1,zb:2,Ia:4,Zd:14,de:12};E.Memory=V;
function Ac(a,b,c){c.type=W.zb;V.call(this,a,b,c);xc(this.m,this.config.addr,this.config.size,this.config.type,this);jb(this,this.pa.bind(this));this.ca=this.ea=void 0;if(E.LED&&this.R[Bc]){var d=this;this.h=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.H=this.values.length/this.h|0;this.g=new Gb(a,b+"LEDs",{"class":"LED",bindings:{container:La(this,Bc)},type:Ib,cols:this.h,rows:this.H,color:I(this,"colorROM","green"),backgroundColor:I(this,"backgroundColorROM","black"),persistent:!0}),
Rb(this.g);this.M=new lb(a,b+"Input",{"class":"Input",location:[0,0,this.g.da,this.g.Y,this.h,this.H],bindings:{surface:La(this,Bc)}});this.N=Ma(this)||"";ob(this.M,function(e,f){if(d.ca){var g=d.N;0<=e&&0<=f&&(e=f*d.h+e,g=Cc(d.ca,d.Ja+e,d.values[e]));M(d,Na,g)}})}}y(Ac,V);
Ac.prototype.oa=function(a){var b=!0,c=a.shift();if(c&&this.g){var d=c.length;this.g.g.length==d?(this.g.g=c,Qb(this.g,!0)):(this.s("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.s("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};Ac.prototype.ha=function(){void 0===this.ca&&(this.ca=Q(this,"CPU"));void 0===this.ea&&(this.ea=Q(this,"Debugger",!1))};
Ac.prototype.ob=function(a){this.g&&Zb(this.g,a%this.h,a/this.h|0,1,Tb);return this.values[a]};Ac.prototype.qa=function(a){this.g&&(a.push(this.g.g),a.push(this.values))};var Bc="array",Na="cellDesc";E.ROM=Ac;function Dc(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.ea=void 0;this.h=this.Pa=0;this.time=Q(this,"Time");this.time.M.push(this);this.time.ia.push(this);this.Y=this.v=0}y(Dc,O);p=Dc.prototype;p.abort=function(a){this.h=this.Pa;this.s("%s\n",a.message);U(this.time)};p.Kb=function(){};
p.Jc=function(a){this.Y=this.v=a=void 0===a?0:a;try{this.Kb(a)}catch(b){this.abort(b)}return this.Mb()};p.Ob=function(){this.Y-=this.v;this.v=0};p.Mb=function(){return this.Y-this.v};function X(a,b,c){O.call(this,a.L,b);this.ca=a;this.name=b;this.l=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.ma[c]=[this,-1];for(var d=0;d<this.l.length;d++)c=this.W("reg%s-%02d",this.name,d),b.push(c),a.ma[c]=[this,d];Ia(a,b)}}y(X,O);p=X.prototype;
p.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]+b.l[f]+e,e=0,this.l[f]>=d&&(this.l[f]-=d,e=1);e&&(this.ca.H=!0);Ec(this,c)};p.get=function(){return this.l};function Fc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.l.length;d++)a.l[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.l[d]=b&15,b>>>=4;return a}p.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.l[e]=a.l[e]+d,d=0,this.l[e]>=c&&(this.l[e]-=c,d=1);Ec(a,b)};
p.set=function(a){if(a&&a.length==this.l.length)for(var b=0;b<this.l.length;b++)this.l[b]=a[b]};p.store=function(a){for(var b=0,c=this.l.length;b<c;b++)this.l[b]=a.l[b]};p.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]-b.l[f]-e,e=0,0>this.l[f]&&(this.l[f]+=d,e=1);e&&(this.ca.H=!0);Ec(this,c)};p.toString=function(a){a=void 0===a?!1:a;var b=this.U+"=";a&&3>b.length&&(b+=" ");for(var c=this.l.length-1;0<=c;c--)b=a?b+xa[this.l[c]]:b+(ya[this.l[c]]+(c%4?"":" "));return b};
function Ec(a,b){a.ca.u=a.l[b[0]];b[0]<b[1]&&(a.ca.u|=a.l[b[0]+1]<<4)}
function Gc(a,b,c){Dc.call(this,a,b,c);this.type=Number.parseInt(I(this,"type","1501").slice(-4),10);this.ma={};this.g=Array(4);for(a=0;4>a;a++)this.g[a]=new X(this,String.fromCharCode(65+a));this.T=this.g[0];this.Z=this.g[1];this.ra=this.g[2];this.va=this.g[3];this.O=Array(8);for(a=0;8>a;a++)this.O[a]=new X(this,"X"+a);this.V=Array(8);for(a=0;8>a;a++)this.V[a]=new X(this,"Y"+a);this.na=new X(this,"Supp",!0);this.aa=new X(this,"Temp",!0);this.N=10;this.H=!1;this.$=this.u=this.J=0;this.m=[-1,-1,-1];
this.ua=P(this,this.config.input);this.ua.J=this.fc.bind(this);this.j=P(this,this.config.output,!1);this.M=Q(this,"Bus");this.I=Q(this,"ROM");this.ka=this.la=this.X=void 0;this.ia=this.ba=-1;this.S={};this.da=Hc;a=this.Fc.bind(this);b=Va.gb;this.K.Ga[b]||(this.K.Ga[b]=[]);this.K.Ga[b].push(a)}y(Gc,Dc);function Ic(a,b){a.S[b]&&(a.S[b]=!1,a.s("break on %s\n",Jc[b]),U(a.time))}function Kc(a){a.j&&Rb(a.j);if(a.I){var b=a.I;b.g&&Rb(b.g)}Lc(a,!1)}p=Gc.prototype;
p.Kb=function(a){for(;0<this.v;){if(this.ia==this.h){this.ia=-1;this.s("break\n");U(this.time);break}var b=this.M.Ca(this.h);this.h=(this.Pa=this.h)+1&this.M.I;if(void 0==b||!Mc(this,b)){this.h=this.Pa;this.s("unimplemented opcode\n");U(this.time);break}this.v-=Nc}if(0>=a){var c=this;oc(this.time,function(){var d=c.I;d.g&&Qb(d.g);c.ta(c.toString())})}};p.Ob=function(){this.v=0};p.Mb=function(){return this.Y-this.v};
function Mc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.H&&(a.h=a.h&1024|b&1023):(a.push(a.h),a.h=b&2047),a.H=!1,!0;var c;var d=b&Oc;switch(d){case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:d=ad[d];var e=(b&bd)>>cd;var f=(b&dd)>>ed;var g=(b&fd)>>gd;var h=(c=b&hd)?id:jd;b=b>=Wc?16:a.N;switch(f){case 0:case 1:case 2:case 3:var k=a.g[f];break;case 4:k=Fc(a.aa,1,d);break;case 5:h=c?kd:ld;break;case 6:k=Fc(a.aa,a.u&15,d);break;case 7:k=Fc(a.aa,a.u&255,d)}switch(g){case 0:var m=
a.g[e];break;case 1:m=4>f?a.g[f]:void 0;break;case 2:m=5>f?a.na:5==f?a.g[e]:void 0;break;case 3:if(c)a.g[e].move(k,d,b);else{a=a.T;e=k;b=d[0];for(k=d[1];b<=k;b++)m=a.l[b],a.l[b]=e.l[b],e.l[b]=m;Ec(e,d)}return!0}if(!m)break;switch(h){case jd:m.add(a.g[e],k,d,b);break;case id:m.sub(a.g[e],k,d,b);break;case ld:b=m;a=a.g[e];e=d[1];for(k=d[0];e>k;e--)b.l[e]=a.l[e-1];b.l[e]=0;Ec(b,d);break;case kd:b=m;a=a.g[e];e=d[0];for(k=d[1];e<k;e++)b.l[e]=a.l[e+1];b.l[e]=0;Ec(b,d)}return!0;case md:e=(b&nd)>>od;d=(b&
pd)>>qd;k=1<<((b&rd)>>sd);if(!d)break;d+=12;switch(b&td){case ud:a.g[e].l[d]|=k;break;case vd:a.g[e].l[d]&=~k;break;case wd:a.g[e].l[d]&k&&(a.H=!0);break;case xd:a.g[e].l[d]^=k}return!0;case yd:switch(b&zd){case Ad:a.T.store(a.V[a.J]);break;case Bd:a.J=b>>4&7;break;case Cd:a.h=a.u;break;case Dd:a.H=!1;d=a.m[0];e=0;for(b=a.m.length-1;e<b;)a.m[e]=a.m[++e];a.m[e]=-1;a.h=d;break;case Ed:a.O[a.J].store(a.T);break;case Fd:a.T.store(a.O[a.J]);break;case Gd:a.V[a.J].store(a.T);break;case Hd:Ic(a,"o");if(a.j){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.Z.l[e]&8?b=" ":a.Z.l[e]&1?b="-":b=xa[a.T.l[e]],Zb(a.j,d,0,b,a.Z.l[e]&2?Wb:0)&&Ic(a,"om");Lc(a)}a.v-=31*Nc;a.$&&(a.u=a.$,a.H=!0,Ic(a,"i"));break;case Id:a.N=10;break;case Jd:a.N=16;break;case Kd:a.J=a.u&7;break;default:return!1}return!0}return!1}
p.oa=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return this.s("invalid saved state\n"),!1;var c=b.shift();if(3!==(c|0))return this.s("saved state version mismatch: %3.2f\n",c),!1;try{this.g.forEach(function(d){return d.set(b.shift())}),this.O.forEach(function(d){return d.set(b.shift())}),this.V.forEach(function(d){return d.set(b.shift())}),this.na.set(b.shift()),this.aa.set(b.shift()),this.N=b.shift(),this.H=b.shift(),this.J=b.shift(),this.u=b.shift(),this.h=b.shift(),this.m=b.shift(),this.$=
b.shift()}catch(d){return this.s("CPU state error: %s\n",d.message),!1}return(a=a.stateROM||a[1])&&this.I&&!this.I.oa(a)?!1:!0};
p.Fc=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,h=3;h<a.length;h++)d.push(Number.parseInt(a[h],16));this.da=Hc;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Jc)c=Jc[f],b+="break on "+c+" (b"+f+"): "+(this.S[f]||!1)+"\n";break}(c=Jc[f])?(this.S[f]=!this.S[f],b="break on "+c+" (b"+f+"): "+this.S[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.M.wa(f);if(void 0==
a)break;this.M.ab(f,d[g]);b+=this.W("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.W("%d locations updated\n",c);break;case "g":this.time.start()?this.ia=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.da=Ld);g=Number.parseInt(a[2],10)||1;kc(this.time,g);break;case "r":"c"==e[1]&&(this.da=Ld);this.Nb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.ba?this.ba:this.h;g--;){c=this.I&&this.M.wa(f);if(void 0==
c)break;b+=Cc(this,f++,c)}this.ba=f;break;case "?":b="additional commands:\n";Md.forEach(function(k){b+=k+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};p.fc=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.$=c};p.Za=function(a){return a&&this.oa(a)?!0:!1};p.ha=function(a){a?this.time.start():(U(this.time),Kc(this))};p.pa=function(){this.s("reset\n");this.h=0;Kc(this);this.time.g||this.ta(this.toString())};p.$a=function(a){this.qa(a)};
p.Gc=function(a){for(var b in this.R){var c=this.ma[b];if(c){var d=c[0];c=c[1];M(this,b,0>c?d.toString():xa[d.l[c]])}}a&&!this.time.g&&(a=this.I,a.g&&Qb(a.g),this.ta(this.toString()))};p.push=function(a){for(var b=this.m.length-1;0<b;)this.m[b]=this.m[--b];this.m[0]=a};
p.qa=function(a){var b=[],c=[];b.push(3);this.g.forEach(function(d){return b.push(d.get())});this.O.forEach(function(d){return b.push(d.get())});this.V.forEach(function(d){return b.push(d.get())});b.push(this.na.get());b.push(this.aa.get());b.push(this.N);b.push(this.H);b.push(this.J);b.push(this.u);b.push(this.h);b.push(this.m);b.push(this.$);this.I&&this.I.qa(c);a.push(b);a.push(c)};p.Nb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.h=b;break;default:this.s("unrecognized register: %s\n",a)}};
function Cc(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.W("%#06x",f);else if(0<=c){var g=c&Oc;var h;switch(g){case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:f="";e=ad[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&bd)>>cd;var k=(c&dd)>>ed;var m=(c&fd)>>gd;var n=c&hd;e="LOAD";var r=h="?";var l=n?5==k?">>":"-":5==k?"<<":"+";switch(m){case 0:h=
Y[g];break;case 1:4>k&&(h=Y[k]);break;case 2:5>k?h="NUL":5==k&&(h=Y[g]);break;case 3:n?(e="MOVE",h=Y[g],r=Y[k]):(e="XCHG",g||(h="A"),4>k&&(r=Y[k])),k=-1}switch(k){case 0:case 1:case 2:case 3:r=Y[g]+l+Y[k];break;case 4:case 5:r=Y[g]+l+"1";break;case 6:r=Y[g]+l+"R5L";break;case 7:r=Y[g]+l+"R5"}f=h+","+r+","+f;break;case md:switch(c&td){case ud:e="SET";break;case vd:e="CLR";break;case wd:e="TST";break;case xd:e="NOT"}f=a.g[(c&nd)>>od].name;g=(c&pd)>>qd;f+="["+(g?g+12:"?")+":"+((c&rd)>>sd)+"]";break;
case yd:switch(c&zd){case Ad:e="STORE";f="A,Y[RAB]";break;case Bd:e="STORE";f="RAB,"+((c&112)>>4);break;case Cd:e="BR";f="R5";break;case Dd:e="RET";break;case Ed:e="STORE";f="X[RAB],A";break;case Fd:e="STORE";f="A,X[RAB]";break;case Gd:e="STORE";f="Y[RAB],A";break;case Hd:e="DISP";break;case Id:e="BCDS";break;case Jd:e="BCDR";break;case Kd:e="STORE",f="RAB,R5L"}}}return a.W(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
p.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.da){this.I&&(d+=Cc(this,this.h,this.M.wa(this.h),!0));d+="  ";b=0;for(a=this.g.length;b<a;b++)d+=this.g[b].toString()+" ";d+="\n ";d+=" COND="+(this.H?1:0);d+=" BASE="+this.N;d+=" R5="+this.W("%02X",this.u);d+=" RAB="+this.J+" ST=";this.m.forEach(function(f){d+=c.W("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.g);0<=a.indexOf("a")&&(d+=this.toString(a,this.O),d+=this.toString(a,this.V));d+="COND="+(this.H?1:0);d+=" BASE="+this.N;d+=" R5="+this.W("%#04x",this.u);d+=" RAB="+this.J+" ";this.m.forEach(function(f,g){d+=c.W("ST%d=%#06x ",g,f&65535)});this.I&&(d+="\n"+Cc(this,this.h,this.M.wa(this.h)));this.ba=this.h;return d};
function Lc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Nd?!!(a.ra.l[14]&8):!!(a.Z.l[15]&4));if(a.ka!==d){if(c=a.R["2nd"])c.style.opacity=d?"1":"0",void 0===a.ka&&a.j&&(c.style.color=a.j.color);a.ka=d}d=b&&(a.type==Nd?!!(a.Z.l[15]&4):!!(a.va.l[15]&8));if(a.la!==d){if(c=a.R.INV)c.style.opacity=d?"1":"0",void 0===a.la&&a.j&&(c.style.color=a.j.color);a.la=d}c=a.type==Nd?a.O[4].l[15]>>2:a.ra.l[15]&3;b=b?c?1==c?Od:Pd:Qd:Rd;if(a.X!==b){if(c=a.R.Deg)c.style.opacity=b==Qd?"1":"0",void 0===a.X&&a.j&&(c.style.color=
a.j.color);if(c=a.R.Rad)c.style.opacity=b==Od?"1":"0",void 0===a.X&&a.j&&(c.style.color=a.j.color);if(c=a.R.Grad)c.style.opacity=b==Pd?"1":"0",void 0===a.X&&a.j&&(c.style.color=a.j.color);a.X=b}}
var Oc=3840,Pc=0,Qc=256,Rc=512,Sc=768,Tc=1024,Uc=1280,Vc=1792,Wc=2048,Xc=2304,Yc=2560,md=3072,Zc=3328,yd=3584,$c=3840,bd=192,cd=6,dd=56,ed=3,fd=6,gd=1,hd=1,td=3,ud=0,vd=1,wd=2,xd=3,nd=192,od=6,pd=48,qd=4,rd=12,sd=2,zd=15,Ad=0,Bd=1,Cd=2,Dd=3,Ed=4,Fd=5,Gd=6,Hd=7,Id=8,Jd=9,Kd=10,Z={},ad=(Z[Pc]=[12,12],Z[Qc]=[0,15],Z[Rc]=[2,12],Z[Sc]=[0,12],Z[Tc]=[2,2],Z[Uc]=[0,1],Z[Vc]=[0,13],Z[Wc]=[14,14],Z[Xc]=[13,15],Z[Yc]=[14,15],Z[Zc]=[13,13],Z[$c]=[15,15],Z),Nc=128,jd=0,id=1,ld=2,kd=3,Nd=1501,Rd=0,Qd=1,Od=2,Pd=
3,Jc={i:"input",o:"output",om:"output modification"},Hc=0,Ld=1,Y="A B C D 1 ? R5L R5".split(" "),Md="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");E.CPU1500=Gc;
function Sd(a,b,c){O.call(this,a,a);var d=this;this.j=!1;this.H=c;this.h="";this.v=this.u=!1;ib(this,!1);this.fa=0;b=b.trim();"{"==b[0]?Td(this,b):(this.h=b,Pa(this.h,function(e,f,g,h){4==g&&(!h&&f?(Td(d,f),Ud(d)):d.s("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.v=!0;Ud(d)});window.addEventListener(Ra("iOS")?"pagehide":Ra("Opera")?"unload":"beforeunload",function(){Vd(d)});window.addEventListener("pageshow",function(){d.j||d.ha(!0)})}y(Sd,O);
Sd.prototype.ya=function(a,b){var c=this;switch(a){case Wd:b.onclick=function(){c.ha()};break;case Xd:b.onclick=function(){c.pa()}}O.prototype.ya.call(this,a,b)};
function Ud(a){var b=!0;if(a.u&&a.v){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],E[d]?"Machine"==d?(a.s("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2025 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.s("Configuration: %s\n",a.h)):new E[d](a.L,c,e):a.s('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.s('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),kb(a,c)}}if(a.m){var f=Sa(a);gb(a,function(g){return g.Za&&!g.Za(f)?(g.s('unable to restore state for device "%s"\n',
g.U),!1):!0})}ib(a,!0);jb(a,a.ha.bind(a,b))||a.s("machine %s not ready to power, waiting for device(s)\n",a.L)}}
function Td(a,b){try{a.g=JSON.parse(b);var c=a.g[a.L];if(!c){c=a.g[Ca(a.h)];if(!c)throw Error("configuration missing machine ID");a.g[a.L]=c}fb(a,c,["autoSave","autoStart"]);a.m=!1!==a.config.autoSave;a.I=!1!==a.config.autoStart;if(a.H){var d=eval("("+a.H+")"),e;for(e in d)a.config[e]=d[e]}a.u=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.s("machine '%s' initialization error: %s\n",a.L,c)}}
Sd.prototype.ha=function(a){a=void 0===a?!this.j:a;if(hb(this)){var b=this;a&&this.s("power on\n");gb(this,function(c){c.ha&&c!=b&&("CPU"!=c.config["class"]||b.I&&hb(b)?c.ha(a):c.time.update(!0));return!0});(this.j=a)||this.s("power off\n")}};Sd.prototype.pa=function(){if(hb(this)){var a=this;gb(this,function(b){b.pa&&b!=a&&b.pa();return!0});this.s("reset\n")}};function Vd(a){if(a.m){var b=[];gb(a,function(c){c.$a&&c.$a(b);return!0});Za(a,b)}a.ha(!1)}var Wd="power",Xd="reset";
window.TMS1500=function(a,b,c){var d=new Sd(a,b,c);window.command=function(e){return Ta(d,e)};return d};E.Machine=Sd;})()

//# sourceMappingURL=ti57.js.map
