(function(){/*
 https://www.pcjs.org/modules/v2/dumpapi.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/reportapi.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/strlib.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/weblib.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/embed.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/defines.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/usrlib.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/component.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/panel.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/cpu.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/rom.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/ram.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/keyboard.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/video.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/serial.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/disk.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/debugger.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v2/computer.js (C) 2012-2023 Jeff Parsons
*/
var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){if(!(a instanceof Array)){a=ba(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ea="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function fa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ha=fa(this);function ja(a,b){if(b)a:{var c=ha;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ea(c,a,{configurable:!0,writable:!0,value:b})}}var ka;
if("function"==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var la;a:{var ma={a:!0},na={};try{na.__proto__=ma;la=na.a;break a}catch(a){}la=!1}ka=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var oa=ka;
function t(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(oa)oa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.af=b.prototype}function pa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
ja("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ja("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});
ja("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,k){this.g=f;ea(this,"description",{configurable:!0,writable:!0,value:k})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
ja("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ha[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ea(d.prototype,a,{configurable:!0,writable:!0,value:function(){return qa(aa(this))}})}return a});function qa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function ra(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}ja("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}});var u={},v=[],sa={},ta="undefined"==typeof window?global:{},w="undefined"==typeof window?global:window,ua="undefined"==typeof document?{}:document;function va(){}
function y(a,b,c){b?9<b&&(b=9):(b=Math.abs(a),b=65535>=b?4:4294967295>=b?8:9);c=c?"0x":"";var d=void 0===d?0:d;var e="";isNaN(a)||"number"!=typeof a?a=null:(0>a&&-1<a&&(a=-1),0>a&&(a+=Math.pow(16,b)),a>=Math.pow(16,b)&&(b=Math.ceil(Math.log(a)/Math.log(16))));for(var f=d||-1;0<b--;){f||(e=","+e,f=d);if(null==a)e="?"+e;else{var k=a%16;k+=0<=k&&9>=k?48:55;e=String.fromCharCode(k)+e;a=Math.trunc(a/16)}f--}return(void 0===c?"":c)+e}function z(a){return y(a,2,!0)}function A(a){return y(a,4,!0)}
function wa(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));return b}function xa(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase(),"json5"==b&&(b="json"));return b}function ya(a){return a.replace(/[&<>"'$]/g,function(b){return za[b]})}
function Aa(){var a=pa.apply(0,arguments);return void 0===a[0]?new Date(Date.now()):"string"===typeof a[0]?new Date(a[0]+" "+(a[1]||"00:00:00 GMT")):void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,ca(a)))}
function Ca(a){var b=pa.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var k=d[f+5],l="ACDFHIMNSTWYbdfjcsoXx%".indexOf(k);if(0>l)c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+k;else{if(e<b.length){var h=b[e];"%"!=k&&e++}else h=b[b.length-1];var p=d[f+1],n=0<=p.indexOf("#"),q=0<=p.indexOf("0"),m=d[f+2];"*"==m?(m=h,h=e<b.length?b[e++]:b[b.length-1]):m=+m||0;var r=d[f+3];r=r?+r.substr(1):-1;var J=null,
R=0,x="";l=12>l&&"object"!=typeof h?Aa(h):h;switch(k){case "C":h=n?"#":"";c+=isNaN(l.getTime())?void 0:Ca(Ca("%%%sW, %%%sF %%%sD, %%%sY",h),l);continue;case "D":h=n?l.getUTCDate():l.getDate();k="d";break;case "A":case "G":case "H":h=n?l.getUTCHours():l.getHours();"A"==k?(h=12>h?"am":"pm",k="s"):("G"==k&&(h=h?12<h?h-12:h:12),k="d");break;case "F":case "M":h=n?l.getUTCMonth():l.getMonth();"F"==k?(h=Da[h],k="s"):(h++,k="d");break;case "N":h=n?l.getUTCMinutes():l.getMinutes();k="d";break;case "S":h=n?
l.getUTCSeconds():l.getSeconds();k="d";break;case "T":h=n?"#":"";c+=isNaN(l.getTime())?void 0:Ca(Ca("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),l);continue;case "W":h=Ea[n?l.getUTCDay():l.getDay()];k="s";break;case "Y":h=n?l.getUTCFullYear():l.getFullYear(),0<r&&(h%=Math.pow(10,r),r=-1),k="d"}switch(k){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=r&&(q=!0,m<r&&(m=r),r=-1);case "f":k=h+"";0<=r&&(k=h.toFixed(r));k.length<m&&(q?(0>h&&(m--,k=k.substr(1)),k=("0000000000"+k).slice(-m),
0>h&&(k="-"+k)):k=("          "+k).slice(-m));c+=k;break;case "j":c+=JSON.stringify(h,null,m||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=r&&(h=h.substr(0,r));h.length<m;)h=0<=p.indexOf("-")?h+" ":" "+h;c+=h;break;case "o":R=8,n&&(x="0");case "X":J=Fa;case "x":k="";R||(R=16);!x&&n&&(x="0x");J||(J=Ga);h=Math.trunc(h);0<=r&&(q=!0,m<r&&(m=r));q&&!m&&(m=Math.abs(h),m=255>=m?2:65535>=m?4:4294967295>=m?8:9,m+=
x.length);m-=x.length;do n=16,Number.isNaN(h)||(n=h&R-1,h=Math.trunc(h/R)),q||!k||n||h?k=J[n]+k:(x&&(k=x+k,x=""),0<m&&(k=" "+k));while(0<--m||h);c+=x+k;break;case "%":c+="%";break;default:c+="(unimplemented printf type %"+k+")"}}}return c+=d[f]}var za={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;",$:"&dollar;"},Ga="0123456789abcdef?",Fa="0123456789ABCDEF?",Ea="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Da="January February March April May June July August September October November December".split(" ");
function B(a,b){var c=null,d=!0;c=void 0===c?"text":c;d=void 0===d?!1:d;var e=0,f=null,k=w.resources;if("object"==typeof k&&(f=k[a]))b&&b(a,f,e);else if(d&&"function"==typeof k)k(a,function(q,m){b&&b(a,q,m)});else if(a=a.replace(/^\/(disks\/|)(diskettes|gamedisks|miscdisks|harddisks|decdisks|pcsigdisks|pcsig[0-9a-z]*-disks|private)\//,"https://$2.pcjs.org/").replace(/^\/(disks\/cdroms|discs)\/([^/]*)\//,"https://$2.pcjs.org/"),ta.Ve)f=ta.Ve(a),b&&b(a,f,e);else{var l=w.XMLHttpRequest?new w.XMLHttpRequest:
new w.ActiveXObject("Microsoft.XMLHTTP"),h=!1,p="string"===typeof l.responseType;k=function(){if(4!==l.readyState)return null;try{f=h?l.response:l.responseText}catch(m){}if(null==f||200!=l.status&&(l.status||!f.length||"file:"!=(w.location?w.location.protocol:"file:")))if(e=l.status||-1,!l.status&&!Ha){var q=a.match(/(^https?:\/\/[^/]+)(.*)/);q&&(Ha=!0,C("PCjs was unable to perform a cross-origin resource request to '"+q[1]+"'.\n\nIf you're running an ad blocker, try adding '"+Ia()+"' to your whitelist (or find a smarter ad blocker)."))}b&&
b(a,f,e);return[f,e]};d&&(l.onreadystatechange=k);if(c&&"object"==typeof c){p="";for(var n in c)c.hasOwnProperty(n)&&(p&&(p+="&"),p+=n+"="+encodeURIComponent(c[n]));p=p.replace(/%20/g,"+");l.open("POST",a,d);l.setRequestHeader("Content-type","application/x-www-form-urlencoded");l.send(p)}else l.open("GET",a,d),"arraybuffer"==c&&(p?(h=!0,l.responseType=c):l.overrideMimeType("text/plain; charset=x-user-defined")),l.send();d||(l.readyState=4,k())}}
function Ia(){return w.location?w.location.protocol+"//"+w.location.host:"https://www.pcjs.org"}function D(a){if(w.navigator){var b=w.navigator?w.navigator.userAgent:"";return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===w.navigator.platform&&1<w.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ja(){var a,b=Ka("mobile");if(b)return"true"==b;if(D("Mobi")){if(!a)return!0;(b="!"==a[0])&&(a=a.substr(1));return D(a)!=b}return!1}
function Ka(a){if(!La){var b,c={};if(w.location){b||(b=w.location.search.substr(1));for(var d,e=/\+/g,f=/([^&=]+)=?([^&]*)/g;d=f.exec(b);)c[decodeURIComponent(d[1].replace(e," "))]=decodeURIComponent(d[2].replace(e," "))}La=c}return La[a]||La[a.toLowerCase()]}function Ma(a,b,c){function d(){--a;0<=a&&(b()||(a=0));0<a?setTimeout(d,0):c()}d()}
function Na(a,b){function c(){b(100===d)&&(e=setTimeout(c,d),d=100)}var d=0,e=null,f=!1;a.onmousedown=function(){f||e||(d=500,c())};a.ontouchstart=function(){e||(d=500,c())};a.onmouseup=a.onmouseout=function(){e&&(clearTimeout(e),e=null)};a.ontouchend=a.ontouchcancel=function(){e&&(clearTimeout(e),e=null);f=!0}}function Oa(a,b){var c=w[a];w[a]="function"!==typeof c?b:function(){c&&c();b()}}function E(a){Pa.init.push(a)}
function Qa(a){if(Ra)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){C("An unexpected error occurred: "+c.message+"\n\nIf it happens again, please send the URL to support@pcjs.org. Thanks.")}}function F(a){!Ra&&a?(Ra=!0,Sa&&Ta("init"),Ua&&Ta("show")):Ra=a}function Ta(a){Pa[a]&&Qa(Pa[a])}var La=null,Pa={init:[],show:[],exit:[]},Sa=!1,Ua=!1,Ra=!0,Ha=!1;Oa("onload",function(){Sa=!0;Qa(Pa.init)});Oa("onpageshow",function(){Ua=!0;Qa(Pa.show)});
Oa(D("iOS")?"onpagehide":D("Opera")?"onunload":"onbeforeunload",function(){Qa(Pa.exit)});function G(a,b,c){this.type=a;b||(b={id:"",name:""});this.name=b.name;this.id=this.id=b.id||"";this.exports={};this.M=this.bindings={};a=this.id.indexOf(".");0>a?this.jb="PCjs":this.jb=this.id.substr(0,a);this.J={ready:!1,Pa:!1,eb:!1,$e:!1,U:!1,Xe:!1,error:!1};this.ib=null;this.J.error=!1;this.qa=c||0;this.D=this.C=this.aa=null;v.push(this)}
function Va(a,b,c){u[a]&&b&&(u[a][b]=c,"parms"==b&&"string"==typeof c&&(u[a].config=eval("("+c+")")))}function Wa(){return Date.now()||+new Date}function C(a){window&&window.alert(a)}function Xa(a,b){a.value+=b;b=a.value;8192<b.length&&(a.value=b.substr(b.length-4096));a.scrollTop=a.scrollHeight}
function H(a,b){b=K("c1p-control","",b.parentNode);for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,e=0;e<d.length;e++){var f=d[e];if(1===f.nodeType){var k=f.getAttribute("class");if(k)for(var l=k.split(" "),h=0;h<l.length;h++)switch(k=l[h],k){case "c1p-binding":(k=M(f))&&void 0!==k.binding&&a.Y(k.type,k.binding,f,k.value),h=l.length}}}}function Ya(a,b){if(void 0!==a){var c;b&&0<(c=b.indexOf("."))&&(a=b.substr(0,c+1)+a);for(c=0;c<v.length;c++)if(v[c].id===a)return v[c]}return null}
function Za(a,b){var c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");for(d=0;d<v.length;d++)if(c)c==v[d]&&(c=null);else if(!(a!=v[d].type||b&&v[d].id.indexOf(b)))return v[d]}return null}function M(a){var b=null;if(a.getAttribute){if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(d){C(d.message+" ("+a+")")}}else if(b=a.config||null){a=a.id;var c=b.id;a&&c&&0>c.indexOf(".")&&(b.id=a+"."+c)}return b}
function K(a,b,c){b=void 0===b?"":b;c=void 0===c?ua:c;var d=[];b&&(a+="-"+b,"machine"!=b&&(a+="-object"));if(c.getElementsByClassName)d=c.getElementsByClassName(a);else if(c.getElementsByTagName){b=c.getElementsByTagName("*");var e=new RegExp("(^| )"+a+"( |$)");a=0;for(c=b.length;a<c;a++)e.test(b[a].className)&&d.push(b[a])}else for(a=Object.keys(u),c=0;c<a.length;c++){e=a[c];var f=u[e].config;if(f&&(f=f[b])){Array.isArray(f)||(f=[f]);f=ba(f);for(var k=f.next();!k.done;k=f.next())d.push({id:e,config:k.value})}}return d}
function $a(a){for(var b=!0,c=sa[a];c&&c.length;){var d=c.splice(0,1)[0],e=d[0],f=null;0<=ab.indexOf(e)&&(f=function(){return function(){$a(a)}}());var k=bb[e];if(k)if(!f)b=k(d[1],d[2],d[3]);else{if(!k(f,d[1],d[2],d[3]))break}else{b=!1;var l=Za(d[1],a);if(l)if(k=db[e])b=k(l,d[2],d[3]);else{var h=l.exports;if(h&&(k=h[e]))if(b=!0,!f)b=k.call(l,d[2],d[3]);else if(!k.call(l,f,d[2],d[3]))break}}if(!b){C("Script error: '"+e+"' command "+(k?" failed":" not recognized"));break}}c&&!c.length&&delete c[a];
return b}g=G.prototype;g.toString=function(){return this.name?this.name:this.id||this.type};function eb(a){var b=1;a.jb&&(a=a.jb.match(/\d+/),null!==a&&(b=parseInt(a[0],10)));return b}
g.Y=function(a,b,c){switch(b){case "clear":return this.M[b]||(this.M[b]=c,c.onclick=function(d){return function(){d.M.print&&(d.M.print.value="")}}(this)),!0;case "print":return this.M[b]||(this.M[b]=c,this.Za=function(d){this.u(d,this.type);return!0},c.value="",this.print=function(d){return function(e){Xa(d,e)}}(c),this.u=function(d,e){return function(f,k){f||(f="");if(k!=fb||"..."!=f.slice(-3))k&&(f=k+": "+f),Xa(e,f+"\n");else{k=e.value;var l=k.lastIndexOf(f);k=0>l?k+(f+"\n"):k.substr(0,l)+(f+".")+
k.substr(l+f.length);8192<k.length&&(k=k.substr(k.length-4096));e.value=k;e.scrollTop=e.scrollHeight}}}(this,c)),!0;default:return!1}};g.log=function(){};g.print=function(){};g.u=function(){};g.status=function(a){this.u(this.type+": "+Ca.apply(va,[a].concat(ca(pa.apply(1,arguments)))))};g.Za=function(a,b,c){if(!b){var d=Za("Computer",this.id);if(d&&d.J.Xe)return console.log("ignoring notice during unload: "+a),!1}c=c||this.type;b||C((c?c+": ":"")+a);return!0};
function gb(a,b){a.J.error=!0;a.Za(b)}function hb(a,b){b&&(a.J.ready?b():a.ib=b);return a.J.ready}g.Z=function(){if(!this.J.error&&(this.J.ready=!0,this.J.ready)){var a=this.ib;this.ib=null;a&&a()}};function ib(a,b){a.J.Pa&&(b?a.J.eb=!0:void 0===b&&a.u(a.toString()+" busy"));return a.J.Pa}function jb(a,b){if(a.J.eb)return a.J.Pa=!1,a.J.eb=!1;if(a.J.error)return a.u(a.toString()+" error"),!1;a.J.Pa=b;return a.J.Pa}
function N(a,b){b=void 0===b?0:b;if(a.D){b%2&&b--;b=b||a.qa;var c;if(!(c=-1==(b|1))){a=a.D.qa;c=Math.pow(2,32);var d=b/c|0;c=(a&b)==(b|0)&&((a/c|0)&d)==d}if(c)return!0}return!1}var fb="progress",ab=["hold","sleep","wait"],bb={alert:function(a){C(a);return!0},sleep:function(a,b){setTimeout(a,+b);return!1}},db={select:function(a,b,c){var d=!1;if(a=a.bindings[b])for(b=0;b<a.options.length;b++)if(a.options[b].textContent==c){a.selectedIndex!=b&&(a.selectedIndex=b);d=!0;break}return d}};
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});
Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return e.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),e=this;c.prototype=this.prototype;b.prototype=new c;return b});function kb(a){G.call(this,"C1PPanel",a);this.J.U=!1}t(kb,G);
kb.prototype.Y=function(a,b,c,d){return this.aa&&this.aa.Y(a,b,c,d)||this.C&&this.C.Y(a,b,c,d)||this.h&&this.h.Y(a,b,c,d)||this.D&&this.D.Y(a,b,c,d)?!0:G.prototype.Y.call(this,a,b,c,d)};kb.prototype.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.aa=b,this.C=O(b,"cpu"),this.h=O(b,"keyboard"),this.D=O(b,"debugger"),lb())};function lb(){for(var a=!1,b=K("c1p","panel"),c=0;c<b.length;c++){var d=b[c],e=M(d),f=Ya(e.id);f||(a=!0,f=new kb(e));H(f,d);a&&f.Z()}}E(lb);
function mb(a){G.call(this,"C1PCPU",a);nb(this);this.J.U=!1;this.J.ta=!1;var b=Ka("autoStart");this.$a="true"==b||"false"==b?JSON.parse(b):a.autoStart;this.Xa=0;this.Nb=1;this.Ob=2;this.speed=this.Xa;this.Ka=30;this.Ja=5;this.Na=8;this.Ra=["Slow","Fast","Max"];this.nb=["(1Mhz)","(up to "+this.Na+"Mhz)","(unlimited)"];this.T=[];this.N=[];this.va=65536;this.wa=0;this.ma=65536;this.na=0;this.Ua=32;this.hb=2;this.Mb=1;this.v=[this.Dc,this.Xd,this.Oe,this.A,this.A,this.Zd,this.tc,this.A,this.be,this.Wd,
this.sc,this.A,this.A,this.Td,this.qc,this.A,this.Cc,this.Yd,this.A,this.A,this.A,this.$d,this.uc,this.A,this.Gc,this.Vd,this.A,this.A,this.A,this.Ud,this.rc,this.A,this.ud,this.mc,this.A,this.A,this.zc,this.oc,this.he,this.A,this.de,this.lc,this.ge,this.A,this.yc,this.ic,this.ee,this.A,this.Ac,this.nc,this.A,this.A,this.A,this.pc,this.ie,this.A,this.ye,this.kc,this.A,this.A,this.A,this.jc,this.fe,this.A,this.oe,this.hd,this.A,this.A,this.A,this.kd,this.Qd,this.A,this.ae,this.gd,this.Pd,this.A,this.td,
this.dd,this.Nd,this.A,this.Ec,this.jd,this.A,this.A,this.A,this.ld,this.Rd,this.A,this.Ic,this.fd,this.A,this.A,this.A,this.ed,this.Od,this.A,this.pe,this.wb,this.A,this.A,this.A,this.yb,this.me,this.A,this.ce,this.vb,this.le,this.A,this.sd,this.sb,this.je,this.A,this.Fc,this.xb,this.A,this.A,this.A,this.zb,this.ne,this.A,this.Ae,this.ub,this.A,this.A,this.A,this.tb,this.ke,this.A,this.A,this.Ee,this.A,this.A,this.Me,this.Ge,this.Je,this.A,this.cd,this.A,this.Se,this.A,this.Le,this.Be,this.Ie,this.A,
this.vc,this.Fe,this.A,this.A,this.Ne,this.He,this.Ke,this.A,this.Ue,this.De,this.Te,this.A,this.A,this.Ce,this.A,this.A,this.Kd,this.zd,this.Fd,this.A,this.Ld,this.Bd,this.Gd,this.A,this.Qe,this.yd,this.Pe,this.A,this.Id,this.vd,this.Dd,this.A,this.wc,this.Ad,this.A,this.A,this.Md,this.Cd,this.Hd,this.A,this.Jc,this.xd,this.Re,this.A,this.Jd,this.wd,this.Ed,this.A,this.Wc,this.Oc,this.A,this.A,this.Xc,this.Qc,this.$c,this.A,this.rd,this.Nc,this.bd,this.A,this.Vc,this.Kc,this.Yc,this.A,this.Bc,this.Pc,
this.A,this.A,this.A,this.Rc,this.ad,this.A,this.Hc,this.Mc,this.A,this.A,this.A,this.Lc,this.Zc,this.A,this.Tc,this.Eb,this.A,this.A,this.Uc,this.Gb,this.od,this.A,this.qd,this.Db,this.Sd,this.A,this.Sc,this.Ab,this.md,this.A,this.xc,this.Fb,this.A,this.A,this.A,this.Hb,this.pd,this.A,this.ze,this.Cb,this.A,this.A,this.A,this.Bb,this.nd,this.A];this.mb=[7,6,0,0,0,3,5,0,3,2,2,0,0,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,3,6,0,0,3,3,5,0,4,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,
3,2,2,0,3,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,4,2,2,0,5,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,0,6,0,0,3,3,3,0,2,0,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,0,4,0,0,2,6,2,0,3,3,3,0,2,2,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,4,4,4,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0]}t(mb,G);g=mb.prototype;
g.reset=function(a){this.J.ta&&this.ga();nb(this);this.j=this.g[65532]|this.g[65533]<<8;this.J.error=!1;this.D?this.D.reset():a&&(!0===this.$a||null===this.$a&&!this.D&&void 0===this.M.run)&&this.Aa()};
g.Y=function(a,b,c){a=!1;switch(b){case "run":this.M[b]=c;c.onclick=function(d){return function(){d.J.ta?d.ga():d.Aa()}}(this);a=!0;break;case "A":case "X":case "Y":case "S":case "PC":case "C":case "Z":case "I":case "D":case "B":case "V":case "N":case "speed":this.M[b]=c;a=!0;break;case "setSpeed":this.M[b]=c,c.onclick=function(d){return function(){ob(d,2<=d.speed?d.Xa:d.speed+1,!0)}}(this),a=!0}return a};
g.ha=function(a,b,c){this.g=a;this.P=b;this.xa=c-b+1;this.La=this.P+this.xa;this.P?C("unsupported CPU address buffer offset ("+this.P+")"):this.Z()};g.oa=function(a,b){if(a&&!this.J.U){this.aa=b;(this.D=O(b,"debugger"))&&this.D.u("Type ? for list of debugger commands\n");if(a=O(b,"video"))this.fb=function(c){return function(){pb(c)}}(a),this.ia=function(c){return function(){c.ia()}}(a);this.J.U=!0;this.reset(!0);this.update()}};
function qb(a,b,c,d,e){0>rb(a.T,b,c,d,e)&&(a.va>b&&(a.va=b),a.wa<c&&(a.wa=c),a.T.push([b,c,d,e]))}function sb(a,b,c){for(var d=0;d<a.T.length;d++)b>=a.T[d][0]&&b<=a.T[d][1]&&a.T[d][3].call(a.T[d][2],b,c)}function tb(a,b,c,d,e){0>rb(a.N,b,c,d,e)&&(a.ma>b&&(a.ma=b),a.na<c&&(a.na=c),a.N.push([b,c,d,e]))}function ub(a,b,c){for(var d=0;d<a.N.length;d++)b>=a.N[d][0]&&b<=a.N[d][1]&&a.N[d][3].call(a.N[d][2],b,c)}
function rb(a,b,c,d,e){for(var f=0;f<a.length;f++)if(a[f][0]==b&&a[f][1]==c&&a[f][2]==d&&a[f][3]==e)return f;return-1}function ob(a,b,c){void 0!==b&&(a.speed=b,a.M.setSpeed&&(a.M.setSpeed.innerHTML=a.Ra[2<=b?0:b+1]),a.u("running at "+a.Ra[b].toLowerCase()+" speed "+a.nb[b]),c&&a.ia());a.ba=0;a.ab=Wa();vb(a)}g.fb=function(){};g.ia=function(){};function S(a,b,c,d){void 0!==a.M[b]&&(void 0===d&&(d=1),c="0000"+c.toString(16),a.M[b].innerHTML=c.slice(c.length-d).toUpperCase())}
function wb(a){S(a,"A",a.m,2);S(a,"X",a.G,2);S(a,"Y",a.K,2);var b=xb(a);S(a,"C",b&1?1:0);S(a,"Z",b&2?1:0);S(a,"I",b&4?1:0);S(a,"D",b&8?1:0);S(a,"B",b&16?1:0);S(a,"V",b&64?1:0);S(a,"N",b&128?1:0);S(a,"S",a.L,4);S(a,"PC",a.j,4);a.M.speed&&a.S&&(a.M.speed.innerHTML=a.S.toFixed(1)+"Mhz")}
function vb(a,b){var c=30;c<a.Ka&&(c=a.Ka);c<a.Ja&&(c=a.Ja);var d=1;b&&a.speed>a.Xa&&a.S&&(d=a.S);d>a.Na&&2>a.speed&&(d=a.Na);a.ob=Math.round(1E3/30);a.ra=Math.floor(1E6/c*d);a.ya=Math.floor(1E6/30*d);a.cb=Math.floor(1E6/a.Ka*d);a.bb=Math.floor(1E6/a.Ja*d);b||(a.W=a.ya,a.da=a.cb,a.ca=a.bb);a.Ha=0}
function yb(a){var b=Wa(),c=a.ob;a.ea&&(c=Math.round(c*a.ea/a.ya));c-=b-a.pb;if(b-=a.ab)a.S=Math.round(a.ba/(100*b))/10,864E5<=b&&ob(a);0>c?c=0:1==a.speed?a.S<=a.Na&&(c=0):2==a.speed&&(c=0);a.Ha+=a.ea;return c}
g.Aa=function(){if(jb(this,!0)){this.J.ta||(ob(this),this.aa&&this.aa.start(),this.J.ta=!0,this.M.run&&(this.M.run.innerHTML="Halt"),this.ia());1E6<=this.Ha&&vb(this,!0);this.ea=0;this.pb=Wa();try{do{this.step(this.ra);var a=this.R-this.I;this.ba+=a;this.ea+=a;this.R=this.I=0;this.da-=this.ra;0>=this.da&&(this.da+=this.cb,this.fb());this.ca-=this.ra;0>=this.ca&&(this.ca+=this.bb,wb(this));this.W-=this.ra;if(0>=this.W){this.W+=this.ya;break}}while(this.J.ta)}catch(b){this.ga();this.update();jb(this,
!1);gb(this,b.stack||b.message);return}setTimeout(function(b){return function(){b.Aa()}}(this),yb(this))}else this.update(),this.aa&&this.aa.stop(this.ab,this.ba)};
g.step=function(a){var b=!0;this.h=this.l=-1;var c;if(c=a&&this.D)c=this.D,c=0<c.ua.length||0<c.Ba.length||0<c.Da.length;this.R=this.I=a;do{a=this.g[this.j];var d;if(d=c){d=this.D;var e=a,f=!1;zb(d,this.j,d.ua,"exec")?f=!0:(d.R++,d.H[e][1]++,d.Ca[d.Qa++]=d.C.j,d.Qa>=d.Ca.length&&(d.Qa=0));d=!!f}if(d){b=void 0;this.ga();break}this.j++;this.v[a].call(this);if(0<=this.h){this.h>=this.va&&this.h<=this.wa&&sb(this,this.h,this.j);if(d=c)d=this.D,e=!1,zb(d,this.h,d.Ba,"read")&&(e=!0),d=!!e;if(d){b=!1;this.ga();
break}this.h=-1}else if(0<=this.l){this.l>=this.ma&&this.l<=this.na&&ub(this,this.l,this.j);if(d=c){d=this.D;e=this.l;f=this.g[this.l];var k=!1;(f&255)!=f&&(d.u("invalid value at "+A(e)+": "+f),k=!0);zb(d,e,d.Da,"write")&&(k=!0);d=!!k}if(d){b=!1;this.ga();break}this.l=-1}this.I-=this.mb[a]}while(0<this.I);return b};function Ab(a){a.W=0;a.R-=a.I;a.I=0}g.ga=function(){ib(this,!0);this.R-=this.I;this.I=0;this.J.ta&&(this.J.ta=!1,this.M.run&&(this.M.run.innerHTML="Run"))};
g.update=function(){this.fb();wb(this)};function Bb(a){return a.J.ta?a.ba+a.R-a.I:0}g.X=function(a){return this.g[a]};function xb(a){var b=a.i&256?1:0;b|=a.s&255?0:2;b|=(a.B&255^a.F^a.B>>1)&128?64:0;b|=a.o&128?128:0;return a.H&60|b}function Cb(a){a.H|=8;a.v[97]=a.dc;a.v[101]=a.fc;a.v[105]=a.cc;a.v[109]=a.$b;a.v[113]=a.ec;a.v[117]=a.hc;a.v[121]=a.bc;a.v[125]=a.ac;a.v[225]=a.ue;a.v[229]=a.we;a.v[233]=a.te;a.v[237]=a.qe;a.v[241]=a.ve;a.v[245]=a.xe;a.v[249]=a.se;a.v[253]=a.re}
function Db(a){a.H&=-9;a.v[97]=a.wb;a.v[101]=a.yb;a.v[105]=a.vb;a.v[109]=a.sb;a.v[113]=a.xb;a.v[117]=a.zb;a.v[121]=a.ub;a.v[125]=a.tb;a.v[225]=a.Eb;a.v[229]=a.Gb;a.v[233]=a.Db;a.v[237]=a.Ab;a.v[241]=a.Fb;a.v[245]=a.Hb;a.v[249]=a.Cb;a.v[253]=a.Bb}function T(a,b,c){var d=a.i&256?1:0,e=(b&15)+(c&15)+d;10<=e&&(e=e+6&15|16);e+=(b&240)+(c&240);a.F=b^c;a.B=e;a.o=e&255;160<=e&&(e+=96);512<=e&&(e-=256);a.i=e;a.s=b+c+d&255;a.I--;return e&255}
function U(a,b,c){var d=a.i&256?0:1,e=(b&15)-(c&15)-d;0>e&&(e=(e-6&15)-16);e+=(b&240)-(c&240);0>e&&(e-=96);a.o=a.s=(a.i=b-c-d)&255;a.F=b^c;a.B=a.i;a.i^=256;a.I--;return e&255}function nb(a){a.m=0;a.G=0;a.K=0;a.L=256;a.H=0;a.o=0;a.s=0;a.F=0;a.B=0;a.i=0;a.j=0;a.h=-1;a.l=-1;a.S=0;a.ba=a.R=a.I=0}
g.Dc=function(){this.j++;this.g[this.L--]=this.j>>8;this.L|=256;this.g[this.L--]=this.j&255;this.L|=256;this.H|=16;this.H=xb(this);this.g[this.L--]=this.H;this.L|=256;this.H&=239;this.h=65534;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.Xd=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m|=this.g[this.h]};g.Zd=function(){this.h=this.g[this.j++];this.o=this.s=this.m|=this.g[this.h]};
g.tc=function(){this.l=this.g[this.j++];this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.be=function(){this.H=xb(this);this.g[this.L--]=this.H;this.L|=256};g.Wd=function(){this.h=this.j++;this.o=this.s=this.m|=this.g[this.h]};g.sc=function(){this.i=this.m<<1;this.o=this.s=this.m=this.i&255};g.Td=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m|=this.g[this.h]};
g.qc=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.Cc=function(){this.j+=(this.o&128?0:(this.I--,this.g[this.j]<<24>>24))+1};g.Yd=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m|=this.g[this.h]};g.$d=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m|=this.g[this.h]};
g.uc=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.Gc=function(){this.i=0};g.Vd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m|=this.g[this.h]};g.Ud=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m|=this.g[this.h]};g.rc=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};
g.ud=function(){this.h=this.j++;this.g[this.L--]=this.j>>8;this.L|=256;this.g[this.L--]=this.j&255;this.L|=256;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.mc=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m&=this.g[this.h]};g.zc=function(){this.h=this.g[this.j++];this.s=this.m&this.g[this.h];this.o=this.o&127|this.g[this.h]&128;this.B=0;this.F=this.g[this.h]&64?128:0};g.oc=function(){this.h=this.g[this.j++];this.o=this.s=this.m&=this.g[this.h]};
g.he=function(){this.l=this.g[this.j++];this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.de=function(){this.L=this.L+1&255|256;this.H=this.g[this.L];this.i=this.H&1?256:0;this.s=this.H&2?0:1;this.o=this.H&128;this.B=0;this.F=this.H&64?128:0};g.lc=function(){this.h=this.j++;this.o=this.s=this.m&=this.g[this.h]};
g.ge=function(){this.i=this.i&65280|this.m;this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.m=this.i&255};g.yc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.s=this.m&this.g[this.h];this.o=this.o&127|this.g[this.h]&128;this.B=0;this.F=this.g[this.h]&64?128:0};g.ic=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m&=this.g[this.h]};
g.ee=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.Ac=function(){this.j+=(this.o&128?(this.I--,this.g[this.j]<<24>>24):0)+1};g.nc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m&=this.g[this.h]};g.pc=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m&=this.g[this.h]};
g.ie=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.ye=function(){this.i=256};g.kc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m&=this.g[this.h]};g.jc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m&=this.g[this.h]};
g.fe=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.oe=function(){this.L=this.L+1&255|256;this.H=this.g[this.L];this.i=this.H&1?256:0;this.s=this.H&2?0:1;this.o=this.H&128;this.B=0;this.F=this.H&64?128:0;this.L=this.L+2&255|256;this.j=this.g[this.L-1|256]|this.g[this.L]<<8};
g.hd=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m^=this.g[this.h]};g.kd=function(){this.h=this.g[this.j++];this.o=this.s=this.m^=this.g[this.h]};g.Qd=function(){this.l=this.g[this.j++];this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};g.ae=function(){this.g[this.L--]=this.m;this.L|=256};g.gd=function(){this.h=this.j++;this.o=this.s=this.m^=this.g[this.h]};
g.Pd=function(){this.i=this.i&65279|(this.m&1?256:0);this.m=(this.i=this.i&65280|this.m>>1)&255;this.o=this.s=this.i&255};g.td=function(){this.h=this.j;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.dd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m^=this.g[this.h]};g.Nd=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.Ec=function(){this.j+=((this.B&255^this.F^this.B>>1)&128?0:(this.I--,this.g[this.j]<<24>>24))+1};g.jd=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m^=this.g[this.h]};g.ld=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m^=this.g[this.h]};g.Rd=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.Ic=function(){this.H&=251};g.fd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m^=this.g[this.h]};g.ed=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m^=this.g[this.h]};g.Od=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.pe=function(){this.L=this.L+2&255|256;this.j=(this.g[this.L-1|256]|this.g[this.L]<<8)+1};g.wb=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.dc=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.m=T(this,this.m,this.g[this.h])};
g.yb=function(){this.h=this.g[this.j++];this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.fc=function(){this.h=this.g[this.j++];this.m=T(this,this.m,this.g[this.h])};g.me=function(){this.l=this.g[this.j++];this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.ce=function(){this.L=this.L+1&255|256;this.o=this.s=this.m=this.g[this.L]};
g.vb=function(){this.h=this.j++;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.cc=function(){this.h=this.j++;this.m=T(this,this.m,this.g[this.h])};g.le=function(){this.i=this.i&65280|this.m;this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.m=this.i&255};g.sd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.j=this.g[this.h]|this.g[this.h+1]<<8};
g.sb=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.$b=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.m=T(this,this.m,this.g[this.h])};g.je=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};
g.Fc=function(){this.j+=((this.B&255^this.F^this.B>>1)&128?(this.I--,this.g[this.j]<<24>>24):0)+1};g.xb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.ec=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.m=T(this,this.m,this.g[this.h])};
g.zb=function(){this.h=this.g[this.j++]+this.G&255;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.hc=function(){this.h=this.g[this.j++]+this.G&255;this.m=T(this,this.m,this.g[this.h])};g.ne=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.Ae=function(){this.H|=4};
g.ub=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.bc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.m=T(this,this.m,this.g[this.h])};g.tb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};
g.ac=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.m=T(this,this.m,this.g[this.h])};g.ke=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.Ee=function(){this.l=this.g[this.j++]+this.G&255;this.l=this.g[this.l]|this.g[this.l+1]<<8;this.g[this.l]=this.m};g.Me=function(){this.l=this.g[this.j++];this.g[this.l]=this.K};
g.Ge=function(){this.l=this.g[this.j++];this.g[this.l]=this.m};g.Je=function(){this.l=this.g[this.j++];this.g[this.l]=this.G};g.cd=function(){this.o=this.s=this.K=this.K-1&255};g.Se=function(){this.o=this.s=this.m=this.G};g.Le=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.K};g.Be=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.m};g.Ie=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.G};
g.vc=function(){this.j+=(this.i&256?0:(this.I--,this.g[this.j]<<24>>24))+1};g.Fe=function(){this.l=this.g[this.j++];this.l=(this.g[this.l]|this.g[this.l+1]<<8)+this.K;this.g[this.l]=this.m};g.Ne=function(){this.l=this.g[this.j++]+this.G&255;this.g[this.l]=this.K};g.He=function(){this.l=this.g[this.j++]+this.G&255;this.g[this.l]=this.m};g.Ke=function(){this.l=this.g[this.j++]+this.K&255;this.g[this.l]=this.G};g.Ue=function(){this.o=this.s=this.m=this.K};
g.De=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.g[this.l]=this.m};g.Te=function(){this.L=this.G|256};g.Ce=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.g[this.l]=this.m};g.Kd=function(){this.h=this.j++;this.o=this.s=this.K=this.g[this.h]};g.zd=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m=this.g[this.h]};g.Fd=function(){this.h=this.j++;this.o=this.s=this.G=this.g[this.h]};
g.Ld=function(){this.h=this.g[this.j++];this.o=this.s=this.K=this.g[this.h]};g.Bd=function(){this.h=this.g[this.j++];this.o=this.s=this.m=this.g[this.h]};g.Gd=function(){this.h=this.g[this.j++];this.o=this.s=this.G=this.g[this.h]};g.Qe=function(){this.o=this.s=this.K=this.m};g.yd=function(){this.h=this.j++;this.o=this.s=this.m=this.g[this.h]};g.Pe=function(){this.o=this.s=this.G=this.m};g.Id=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.K=this.g[this.h]};
g.vd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m=this.g[this.h]};g.Dd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.G=this.g[this.h]};g.wc=function(){this.j+=(this.i&256?(this.I--,this.g[this.j]<<24>>24):0)+1};g.Ad=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m=this.g[this.h]};g.Md=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.K=this.g[this.h]};
g.Cd=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m=this.g[this.h]};g.Hd=function(){this.h=this.g[this.j++]+this.K&255;this.o=this.s=this.G=this.g[this.h]};g.Jc=function(){this.F=this.B=0};g.xd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m=this.g[this.h]};g.Re=function(){this.o=this.s=this.G=this.L&255};g.Jd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.K=this.g[this.h]};
g.wd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m=this.g[this.h]};g.Ed=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.G=this.g[this.h]};g.Wc=function(){this.h=this.j++;this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.Oc=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};
g.Xc=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.Qc=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.$c=function(){this.l=this.g[this.j++];this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.rd=function(){this.o=this.s=this.K=this.K+1&255};g.Nc=function(){this.h=this.j++;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.bd=function(){this.o=this.s=this.G=this.G-1&255};
g.Vc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.Kc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Yc=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.Bc=function(){this.j+=(this.s&255?(this.I--,this.g[this.j]<<24>>24):0)+1};
g.Pc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Rc=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.ad=function(){this.l=this.g[this.j++]+this.G&255;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.Hc=function(){Db(this)};
g.Mc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Lc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Zc=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.Tc=function(){this.h=this.j++;this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.Eb=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.ue=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.m=U(this,this.m,this.g[this.h])};g.Uc=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.Gb=function(){this.h=this.g[this.j++];this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.we=function(){this.h=this.g[this.j++];this.m=U(this,this.m,this.g[this.h])};g.od=function(){this.l=this.g[this.j++];this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.qd=function(){this.o=this.s=this.G=this.G+1&255};
g.Db=function(){this.h=this.j++;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.te=function(){this.h=this.j++;this.m=U(this,this.m,this.g[this.h])};g.Sd=function(){};g.Sc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.Ab=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.qe=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.m=U(this,this.m,this.g[this.h])};g.md=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.xc=function(){this.j+=(this.s&255?0:(this.I--,this.g[this.j]<<24>>24))+1};
g.Fb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.ve=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.m=U(this,this.m,this.g[this.h])};
g.Hb=function(){this.h=this.g[this.j++]+this.G&255;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.xe=function(){this.h=this.g[this.j++]+this.G&255;this.m=U(this,this.m,this.g[this.h])};g.pd=function(){this.l=this.g[this.j++]+this.G&255;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.ze=function(){Cb(this)};
g.Cb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.se=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.m=U(this,this.m,this.g[this.h])};
g.Bb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.re=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.m=U(this,this.m,this.g[this.h])};g.nd=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};
g.Oe=function(){var a=this.g[this.j++];switch(a){case 0:this.u("HALT");this.ga();break;case 1:a=this.j;for(var b="";a<this.g.length;){var c=this.g[a++];if(!c)break;b+=String.fromCharCode(c)}this.j=a;b=b.replace(/%A/g,y(this.m,2)).replace(/%X/g,y(this.G,2)).replace(/%Y/g,y(this.K,2));this.u(b);Ab(this);break;default:this.j-=2,this.u("undefined opSim: "+z(a)+" at "+A(this.j)),this.ga()}};g.A=function(){var a=this.g[--this.j];this.u("undefined opcode: "+z(a)+" at "+A(this.j));this.ga()};
E(function(){for(var a=K("c1p","cpu"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new mb(d);H(d,c)}});function Eb(a){G.call(this,"C1PROM",a);this.h=this.g=null;this.l=+a.size;if(this.v=a.file||a.image){a=this.v;var b=xa(this.v);"json"!=b&&"hex"!=b&&(a=Ia()+"/api/v1/dump?file="+this.v+"&format=bytes");var c=this;B(a,function(d,e,f){Fb(c,d,e,f)})}else this.Z()}t(Eb,G);
Eb.prototype.ha=function(a,b,c,d){this.g=a;this.B=b;a=c-b+1;this.l||(this.l=a);a!=this.l?gb(this,"computer-specified ROM size ("+A(a)+") does not match component-specified size ("+A(this.l)+")"):(d&&(this.C=d,tb(d,b,c,this,this.F)),Gb(this))};Eb.prototype.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.D=O(b,"debugger"))};Eb.prototype.F=function(a,b){void 0!==b&&(this.D&&V(this.D,this,a,b,this.D.Ib,!0),a-=this.B,this.g[this.B+a]=this.h?this.h[a]:0)};
function Fb(a,b,c,d){if(d)a.u('Error loading ROM "'+b+'" ('+d+")");else{if("["==c.charAt(0)||"{"==c.charAt(0))try{var e=eval("("+c+")"),f=e.bytes;a.h=f?f:e}catch(k){a.u('Error processing ROM "'+b+'": '+k.message);return}else for(b=c.replace(/\n/gm," ").replace(/ +$/,"").split(" "),a.h=Array(b.length),c=0;c<b.length;c++)a.h[c]=parseInt(b[c],16);Gb(a)}}
function Gb(a){if(!hb(a))if(!a.v)a.Z();else if(a.h&&a.g){var b=a.h.length;if(b!=a.l)gb(a,"ROM image size ("+A(b)+") does not match component-specified size ("+A(a.l)+")");else{for(var c=0;c<b;c++)a.g[a.B+c]=a.h[c];a.Z()}}}E(function(){for(var a=K("c1p","rom"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Eb(d);H(d,c)}});function Hb(a){G.call(this,"C1PRAM",a)}t(Hb,G);Hb.prototype.ha=function(a){this.g=a;this.Z()};
E(function(){for(var a=K("c1p","ram"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Hb(d);H(d,c)}});
function Ib(a){G.call(this,"C1PKeyboard",a);this.J.U=!1;this.nb=a.model;this.va=8;this.pb=10;this.ob=13;this.wa=27;this.cb=this.va;this.mb=this.pb;this.$a=this.ob;this.na=this.wa;this.F=224;this.l=16+this.F;this.T=17+this.F;this.W=18+this.F;this.ra=20+this.F;this.ma=this.F;this.ab=3;this.bb=15;this.R=1;this.N={};this.N["break"]=this.ma;this.N.esc=this.na;this.N["ctrl-c"]=this.ab;this.N["ctrl-o"]=this.bb;this.h=[];this.h[49]=30464;this.h[33]=30464+this.l;this.h[50]=30208;this.h[34]=30208+this.l;this.h[51]=
29952;this.h[35]=29952+this.l;this.h[52]=29696;this.h[36]=29696+this.l;this.h[53]=29440;this.h[37]=29440+this.l;this.h[54]=29184;this.h[38]=29184+this.l;this.h[55]=28928;this.h[39]=28928+this.l;this.h[56]=26368;this.h[40]=26368+this.l;this.h[57]=26112;this.h[41]=26112+this.l;this.h[48]=25856;this.h[58]=25600;this.h[42]=25600+this.l;this.h[45]=25344;this.h[61]=25344+this.l;this.h[46]=22272;this.h[62]=22272+this.l;this.h[108]=22016;this.h[76]=22016+this.l;this.h[92]=22016+this.l;this.h[111]=21760;this.h[79]=
21760+this.l;this.h[this.cb]=21760+this.l;this.h[this.mb]=21504;this.h[this.$a]=21248;this.h[119]=18176;this.h[87]=18176+this.l;this.h[101]=17920;this.h[69]=17920+this.l;this.h[114]=17664;this.h[82]=17664+this.l;this.h[116]=17408;this.h[84]=17408+this.l;this.h[121]=17152;this.h[89]=17152+this.l;this.h[117]=16896;this.h[85]=16896+this.l;this.h[105]=16640;this.h[73]=16640+this.l;this.h[115]=14080;this.h[83]=14080+this.l;this.h[100]=13824;this.h[68]=13824+this.l;this.h[102]=13568;this.h[70]=13568+this.l;
this.h[103]=13312;this.h[71]=13312+this.l;this.h[104]=13056;this.h[72]=13056+this.l;this.h[106]=12800;this.h[74]=12800+this.l;this.h[107]=12544;this.h[75]=12544+this.l;this.h[91]=12544+this.l;this.h[120]=9984;this.h[88]=9984+this.l;this.h[99]=9728;this.h[67]=9728+this.l;this.h[118]=9472;this.h[86]=9472+this.l;this.h[98]=9216;this.h[66]=9216+this.l;this.h[110]=8960;this.h[78]=8960+this.l;this.h[94]=8960+this.l;this.h[109]=8704;this.h[77]=8704+this.l;this.h[93]=8704+this.l;this.h[44]=8448;this.h[60]=
8448+this.l;this.h[113]=5888;this.h[81]=5888+this.l;this.h[97]=5632;this.h[65]=5632+this.l;this.h[122]=5376;this.h[90]=5376+this.l;this.h[32]=5120;this.h[47]=4864;this.h[63]=4864+this.l;this.h[59]=4608;this.h[43]=4608+this.l;this.h[112]=4352;this.h[80]=4352+this.l;this.h[64]=4352+this.l;this.h[this.T]=1536;this.h[this.na]=1280;this.h[this.l]=512;this.h[this.W]=256;this.h[this.ra]=0;this.reset()}t(Ib,G);g=Ib.prototype;
g.reset=function(){this.Sa(this.nb);this.v=this.R;this.ya=0;this.B=[this.R,0,0,0,0,0,0,0];this.ba=[];if(this.H)for(var a in this.H)isNaN(+a)||this.H[a]&&clearTimeout(this.H[a]);this.H=[];this.Ra=this.I=0;this.Ha=-1;this.xa=this.B;this.Ja=this.ea=0;this.P=""};
g.Y=function(a,b,c){if(void 0===this.M[b])switch(b){case "keyDown":return this.M[b]=c,c.onkeydown=function(d){return function(e){return Jb(d,e,!0)}}(this),!0;case "keyPress":return this.M[b]=c,c.onkeypress=function(d){return function(e){var f=!0;e=e||window.event;e=e.which||e.keyCode;d.P="";d.v&8?d.v&=-9:f=!Kb(d,e);d.D&&N(d.D,d.D.Ea)&&d.D.message("keyPress("+z(e)+"): "+(f?"pass":"consume"));return f}}(this),!0;case "keyUp":return this.M[b]=c,c.onkeyup=function(d){return function(e){return Jb(d,e,
!1)}}(this),!0;case "break":return this.M[b]=c,c.onclick=function(d){return function(){d.aa&&d.aa.reset(!0)}}(this),!0;default:if(void 0!==this.N[b])return this.M[b]=c,c.onclick=function(d,e,f){return function(){d.C&&d.C.ia();return!Kb(d,f)}}(this,b,this.N[b]),!0}return!1};g.ha=function(a,b,c,d){this.g=a;this.Ka=b;this.Pb=c-b+1;this.Rb=this.Ka+this.Pb;d&&(this.C=d,tb(d,b,c,this,this.Sb));this.Z()};g.Sa=function(a){this.S=a;this.ca=255;600!=this.S&&(this.ca=0,this.u("updated keyboard model: "+this.S))};
g.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.aa=b,this.D=O(b,"debugger"))};g.Z=function(){this.da=(this.Qb=D("iOS"))||D("Android");this.D&&N(this.D,this.D.Ea)&&this.D.message("mobile keyboard support: "+(this.da?"true":"false")+" ("+window.navigator.userAgent+")");G.prototype.Z.call(this)};function Lb(a,b){b=b?100:250;a.C&&a.C.S&&(b/=a.C.S);return b}function Mb(a,b){!a.I||void 0!==b&&b==a.I||(a.D&&N(a.D,a.D.Ea)&&a.D.message("autoClear("+z(a.I)+")"),clearTimeout(a.H[a.I]),Nb(a,a.I,!1,4))}
function Ob(a,b,c){a.P=b;Pb(a,c||300)}function Pb(a,b){if(0<a.P.length){var c=a.P.charCodeAt(0);10==c&&(c=13);65<=c&&90>=c&&(c+=32);a.P=a.P.substr(1);Kb(a,c)}0<a.P.length&&setTimeout(function(d){return function(){Pb(d,b)}}(a),b)}
function Jb(a,b,c){var d=!c;b=b.keyCode;c&&(a.Ra=b);if(b==a.l-a.F)a.v&=-5,c&&(a.v|=4),b+=a.F,d=!1;else if(b==a.W-a.F)a.v&=-3,c&&(a.v|=2),b+=a.F,d=!1;else if(b==a.T-a.F)a.v&=-65,c&&(a.v|=64),b+=a.F,d=!1;else if(b==a.ra-a.F)c=!c,a.v&=~a.R,c&&(a.v|=a.R),b+=a.F,d=!1;else if(91==b){a.v&=-9;c&&(a.v|=8);d=!1;var e=!0}else e=9==b?d=!1:b==a.wa||b==a.va?c?!Kb(a,b):!1:!0;d&&(a.v&=-9,a.da||b!=a.Ra||Mb(a));void 0===e&&(e=!Nb(a,b,c,2));a.D&&N(a.D,a.D.Ea)&&a.D.message("key"+(c?"Down":"Up")+"("+z(b)+"): "+(e?"pass":
"consume"));return e}function Kb(a,b){var c=!1;b==a.ma?a.aa&&(a.aa.reset(!0),c=!0):(a.da&&65<=b&&90>=b&&(b+=32),Mb(a,b),Nb(a,b,!0,0)&&(2==a.C.speed?Nb(a,b,!1,1):(c=!1,a.H[b]&&(clearTimeout(a.H[b]),c=!0),c=Lb(a,c),a.H[a.I=b]=setTimeout(function(d){return function(){Nb(d,b,!1,3)}}(a),c),a.D&&N(a.D,a.D.Ea)&&a.D.message("keyPressSimulate("+z(b)+"): setTimeout()")),c=!0));a.D&&N(a.D,a.D.Ea)&&a.D.message("keyPressSimulate("+z(b)+"): "+(c?"true":"false"));return c}
function Nb(a,b,c,d){var e=!1;c||(a.H[b]=null,a.I==b&&(a.I=0));var f=0,k=a.h[b];void 0===k&&(1<=b&&26>=b&&(b+=64,f=a.T),k=a.h[b]);void 0!==k&&(b=k>>12,e=k>>8&15,f||(f=k&255),c?(a.B[b]|=1<<e,a.B[0]=f==a.T?a.B[0]|64:f==a.l?a.B[0]|4:f==a.W?a.B[0]|2:a.B[0]&-71):(a.B[b]&=~(1<<e),a.B[0]&=-71,a.B[0]|=a.v&70),c=0==d&&!a.ba.length,a.ba.push(a.B.slice()),Qb(a,c),e=!0);return e}g.X=function(){};g.Sb=function(a){this.ya=this.C.X(a)^this.ca;this.ea++;Qb(this,!1,a)};
function Qb(a,b,c){var d=Bb(a.C);b||(2==a.C.speed?b=void 0!==c&&32<=a.ea:(b=d-a.Ja,b=0>b||8192<=b));b&&(b=a.ba.shift(),void 0!==b&&(a.xa=b),a.ea=0,a.Ja=d);for(b=d=0;8>b;b++)a.ya&1<<b&&(d|=a.xa[b]);d^=a.ca;if(void 0!==c)a.g[c]=d;else if(c=a.Ka,d!=a.Ha)for(;c<a.Rb;c++)a.g[c]=d;a.Ha=d}E(function(){for(var a=K("c1p","keyboard"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Ib(d);H(d,c)}});
function Rb(a,b,c,d){G.call(this,"C1PVideo",a);this.ra=a.model;this.ea=a.charCols;this.ma=a.charRows;this.wa=a.screenWidth;this.xa=a.screenHeight;this.H=a.charWidth;this.I=a.charHeight;Sb(this);this.F=b;this.T=c;this.v=d;b=["","moz","ms","webkit"];a=a.smoothing;(c=Ka("smoothing"))&&(a="true"==c);if(null!=a)for(c=0;c<b.length;c++)if(d=(d=b[c])?d+"ImageSmoothingEnabled":"imageSmoothingEnabled",void 0!==this.T[d]){this.T[d]=a;break}}t(Rb,G);g=Rb.prototype;
g.reset=function(a){this.Sa(this.ra);if(this.g)for(var b=this.N;b<this.W;b++)this.g[b]=a?Math.floor(256*Math.random()):32};g.Y=function(a,b,c){switch(b){case "refresh":return this.M[b]=c,c.onclick=function(d){return function(){Tb(d);pb(d)}}(this),!0}return!1};g.ha=function(a,b,c,d){this.g=a;this.N=b;this.va=c-b+1;this.W=this.N+this.va;d&&(this.C=d,qb(d,56832,56832,this,this.X),tb(d,56832,56832,this,this.Tb));this.reset(!0)};
function Sb(a,b,c,d,e){a.P=void 0!==b?b:a.ea;a.ya=void 0!==c?c:a.ma;a.l=a.P*a.ya;a.W=a.N+a.l;a.da=void 0!==d?d:0;a.na=void 0!==e?e:c;a.ba=Math.floor(a.wa/a.P);a.ca=Math.floor(a.xa/a.na)}g.ia=function(){this.F.focus()};g.Sa=function(a){this.S=a;600==this.S?(Sb(this,this.ea,this.ma,3,25),1024==this.l&&this.C&&(this.B=this.W+this.l-1,tb(this.C,this.B,this.B,this,this.Lb))):(this.u("updated video model: "+this.S),Sb(this,64,32));Tb(this);pb(this)};
g.oa=function(a,b){if(a&&!this.J.U&&hb(this)){if(this.J.U=!0,this.D=O(b,"debugger"),this.h=O(b,"keyboard"))this.h.Y("canvas","keyDown",this.F),this.h.Y("canvas","keyPress",this.F),this.h.Y("canvas","keyUp",this.F)}else!a&&this.J.U&&(this.J.U=!1)};g.Z=function(){this.H||(this.H=Math.floor(this.v.width/16));this.I||(this.I=Math.floor(this.v.height/16));G.prototype.Z.call(this)};
g.X=function(a,b){var c=this.C.X(a);void 0!==b&&this.D&&V(this.D,this,a,b,this.D.gb);this.C.g[a]=c&127|(Math.floor(Bb(this.C)/8333)&1?128:0)};g.Tb=function(a,b){void 0!==b&&this.D&&V(this.D,this,a,b,this.D.gb)};
g.Lb=function(a,b){if(void 0!==b){this.D&&V(this.D,this,a,b,this.D.gb,!0);this.Sa(540);this.h&&this.h.Sa(542);a=this.C;b=a.N;var c=[],d=rb(b,this.B,this.B,this,this.Lb);if(0<=d){c.push(b[d][0]);c.push(b[d][1]);b.splice(d,1);var e=65536,f=0;for(d=0;d<b.length;d++)e>b[d][0]&&(e=b[d][0]),f<b[d][1]&&(f=b[d][1]);c.push(e);c.push(f)}4==c.length&&(a.ma=c[2],a.na=c[3])}};function Tb(a){a.R=Array(a.l);for(var b=0;b<=a.l;b++)a.R[b]=-1}
function pb(a){var b=0;if(a.J.U)for(;b<a.l;){var c=a.g[a.N+b];if(a.R[b]!=c){var d=Math.floor(b/a.P);if(d>=a.da&&(d-=a.da,d<a.na)){var e=c*a.H;a.T.drawImage(a.v,e%a.v.width,Math.floor(e/a.v.width)*a.I,a.H,a.I,b%a.P*a.ba,d*a.ca,a.ba,a.ca)}a.R[b]=c}b++}}
E(function(){for(var a=K("c1p","video"),b=0;b<a.length;b++){var c=a[b],d=M(c),e=K("pcjs-canvas","",c);if(e&&e.length)var f=e[0];else if(f=document.createElement("canvas"))f.setAttribute("class","pcjs-canvas"),f.setAttribute("width",d.screenWidth),f.setAttribute("height",d.screenHeight),f.style.backgroundColor=d.screenColor,f.style.height="auto",c.appendChild(f);if(!f||!f.getContext){c.innerHTML="<br>Missing &lt;canvas&gt; support. Please try a newer web browser.";break}f.setAttribute("contenteditable",
"true");f.setAttribute("autocapitalize","off");f.setAttribute("autocorrect","off");0<=(w.navigator?w.navigator.userAgent:"").indexOf("MSIE")&&(f.style.height=(c.clientWidth*d.screenHeight/d.screenWidth|0)+"px",c.onresize=function(l,h,p,n){return function(){h.style.height=(l.clientWidth*n/p|0)+"px"}}(c,f,d.screenWidth,d.screenHeight));e=new Image;var k=f.getContext("2d");f=new Rb(d,f,k,e);d=d.fontROM||d.charSet;e.onload=function(l){return function(){l.Z()}}(f,d);e.src=d;H(f,c)}});
function Ub(a){G.call(this,"C1PSerialPort",a);this.J.U=!1;this.F=a.demo;this.R='10 PRINT "HELLO OSI #'+eb(this)+'"\n';this.B=Vb;this.v=Ka("autoMount")||a.autoMount;if("string"==typeof this.v)try{this.v=eval("("+this.v+")")}catch(c){C(this.type+" auto-mount error: "+c.message+" ("+this.v+")"),this.v=null}if(a=this.v&&this.v.path){var b=this;this.F=!0;B(a,function(c,d,e){Wb(b,c,d,e);b.R=d;b.v=null;b.g&&b.Z()})}this.reset(!0)}t(Ub,G);
function Wb(a,b,c,d){if(c){a.I=0;a.l=c;a.P=!0;if(0<b.indexOf(".json"))try{d="";var e=eval("("+c+")").bytes;for(c=0;c<e.length;c++)d+=String.fromCharCode(e[c]);a.l=d;a.P=!1}catch(f){a.u('Error processing file "'+b+'": '+f.message);return}a.aa&&a.h&&a.C.J.ta?(a.u("auto-loading "+b),a.F||Xb(a,!0)):a.u(b+" ready to load")}else a.u('Error loading file "'+b+'" ('+d+")")}g=Ub.prototype;g.reset=function(a){if(a||this.B!=Yb)this.H=-1,this.I=0,this.l="",this.F&&(this.l=this.R),this.P=!0,this.B=Vb};
g.start=function(){this.h&&this.F&&("."==this.l[0]?(this.F=!1,Xb(this)):(Ob(this.h," C\n\n",1E3),setTimeout(function(a){return function(){a.F=!1;Xb(a)}}(this),5E3)))};
g.Y=function(a,b,c){var d=this;switch(b){case "listSerial":return this.M[b]=c,!0;case "loadSerial":return this.M[b]=c,c.onclick=function(){d.M.listSerial&&B(d.M.listSerial.value,function(e,f,k){Wb(d,e,f,k)})},!0;case "mountSerial":return!Ja()&&window&&"FileReader"in window?(this.M[b]=c,c.onchange=function(){var e=c.children[0];e.children[1].disabled=!e.children[0].files.length},c.onsubmit=function(e){var f=e.currentTarget[1].files[0],k=new FileReader;k.onload=function(){Wb(d,f.name,k.result.toString(),
0)};k.readAsText(f);return!1}):c.parentNode.removeChild(c),!0}return!1};g.ha=function(a,b,c,d){this.g=a;this.N=b;this.T=c-b+1;this.S=this.N+this.T;if(this.C=d)qb(d,b,c,this,this.X),tb(d,b,c,this,this.Ub);this.v||this.Z()};g.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.aa=b,this.h=O(b,"keyboard"),this.D=O(b,"debugger"))};function Xb(a,b){a.l&&(a.C.ia(),"."!=a.l.charAt(0)?(a.B=Zb,Ob(a.h,"NEW\nLOAD\n")):(a.B=Yb,b&&a.aa.reset(!0),Ob(a.h,"ML")))}
g.X=function(a,b){void 0!==b&&(a&1?$b(this):this.l&&!this.I&&$b(this))};g.Ub=function(a,b){void 0!==b&&this.D&&V(this.D,this,a,b,this.D.Ye,!0)};function $b(a){if(void 0!==a.l){a.H=-1;if(a.I<a.l.length){var b=a.l.charCodeAt(a.I++)&255;a.P&&10==b&&(b=13);a.H=b}else a.l="",a.I=0,a.B==Zb&&a.h&&Ob(a.h," \nRUN\n"),a.B=Vb;for(b=a.N+0;b<a.S;b+=2)a.g[b]=0<=a.H?ac:bc;for(b=a.N+1;b<a.S;b+=2)a.g[b]=0<=a.H?a.H:0}}var bc=0,ac=1,Vb=0,Zb=1,Yb=2;
E(function(){for(var a=K("c1p","serial"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new Ub(d);H(d,c)}});function cc(a){G.call(this,"C1PDiskController",a);this.J.U=!1;this.reset(!0)}t(cc,G);g=cc.prototype;g.reset=function(a){dc(this);this.h=-1;a&&(this.l=[],this.l[0]={Ze:0,rb:40,Yb:!0,Ia:20,sa:0,Ga:-1,Wa:[]})};
function dc(a){a.S={O:64,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c);b.H.O&4||X(b,0,this)}}(a)};a.v={O:255,read:function(){this.update()},update:function(b){return function(c){void 0===c?c=b.v.O:ec(b,c,b.F.O);c=(c|190)&-2;if(0<=b.h&&b.l[b.h].Wa.length){var d=b.l[b.h];d.Yb&&(c&=-33);d.sa||(c&=-3);10>=--d.Ia&&(0<d.Ia?(c&=-129,fc(b)):(d.Ia=100,0<=b.h&&(b.l[b.h].Ga=0,gc(b))))}this.O=c;b.H.O&4&&X(b,0,this)}}(a)};a.H={O:0,read:function(){},update:function(b){return function(c){void 0!==
c&&(this.O=c&-193);X(b,1,this);b.v.update();b.S.update()}}(a)};a.R={O:255,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c);b.I.O&4||X(b,2,this)}}(a)};a.F={O:255,read:function(){},update:function(b){return function(c){void 0===c?c=b.F.O:ec(b,b.v.O,c);if(0<=b.h&&b.h<b.l.length){var d=b.l[b.h];d.Wa.length&&b.F.O&8&&!(c&8)&&(c&4?d.sa--:d.sa++,b.D&&N(b.D,b.D.Ma)&&b.D.message("stepping "+(c&4?"down":"up")+" to track "+d.sa),d.sa>=d.rb&&(d.sa=d.rb),0>d.sa&&(d.sa=0),d.Ia=20,
b.v.update(b.v.O|128),fc(b))}this.O=c;b.I.O&4&&X(b,2,this)}}(a)};a.I={O:0,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c&-193);X(b,3,this);b.F.update();b.R.update()}}(a)};a.T={O:0,read:function(){},update:function(b){return function(c){void 0!==c&&(3==(c&3)&&(b.B.O=14),this.O=c);b.B.update()}}(a)};a.B={O:14,read:function(){},update:function(b){return function(c){void 0===c&&(c=b.B.O);c&=-2;0<=b.h&&0<=b.l[b.h].Ga&&(c|=1);this.O=c;X(b,16,this)}}(a)};a.N={O:0,read:function(b){return function(){gc(b)}}(a),
update:function(b){return function(c){void 0!==c&&(this.O=c);X(b,17,this)}}(a)};a.W={O:0,read:function(){},update:function(){return function(){}}(a)}}g.Y=function(a,b,c){switch(b){case "listDisk":return this.M[b]=c,!0;case "loadDisk":return this.M[b]=c,c.onclick=function(d){return function(){if(d.M.listDisk){var e=d.M.listDisk.value,f=e;".json"!=e.substr(e.length-5)&&(f="http://"+window.location.host+"/api/v1/dump?disk="+e);d.u("loading  "+wa(e)+"...");B(f,function(k,l,h){hc(d,k,l,h)})}}}(this),!0}return!1};
g.ha=function(a,b,c,d){this.g=a;this.P=b;if(this.C=d)qb(d,b,c,this,this.X),tb(d,b,c,this,this.Vb);this.Z()};g.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.D=O(b,"debugger"))};
function hc(a,b,c,d){if(d)a.u("disk load error ("+d+")");else{d=[];a.u("mounting "+b+"...");try{if(d=eval("("+c+")"),d.length)if(d[0].length){var e=d[0];if(void 0===e[0].trackNum)a.u("data error: "+e[0]);else if(a.l[0]){for(c=0;c<e.length;c++){var f,k=e[c],l=k.sectors;if(void 0===(f=k.trackNum)||void 0===l)throw Error("track "+c+" missing data");f!=c&&C("track "+f+" out of order (expected "+c+")");d=[];var h;if(f){ic(d,k,"trackSig");jc(d,k);kc(d,k,"trackType");for(var p=0;p<l.length;p++){var n=l[p];
var q=n.sectorData;kc(d,n,"sectorSig");kc(d,n,"sectorNum");kc(d,n,"sectorPages");for(h=0;h<q.length;h++)d.push(q[h]);ic(d,n,"sectorEndSig")}}else for(n=l[0],q=n.sectorData,kc(d,k,"trackLoad",2),kc(d,n,"sectorPages"),h=0;h<q.length;h++)d.push(q[h]);e[f].Kb=d;a.D&&N(a.D,a.D.Ma)&&a.D.message("track "+f+": "+d.length+" bytes")}a.l[0].Wa=e;a.u("mount of "+b+" complete")}else a.u("no available drives")}else a.u("no tracks: "+b);else a.u("no data: "+b)}catch(m){a.u("disk data error: "+m.message)}}}
function jc(a,b){b=b.trackNum;if(void 0===b)throw Error("missing bcd value: trackNum");a.push(Math.floor(b/10)<<4|b%10)}function kc(a,b,c,d){b=b[c];if(void 0===b)throw Error("missing binary value: "+c);2==d&&a.push(b>>8&255);a.push(b&255)}function ic(a,b,c){b=b[c];if(void 0===b)throw Error("missing signature: "+c);for(c=0;c<b.length;c++)a.push(b.charCodeAt(c))}
function lc(a,b,c){b&=63;16>b?b&=3:32>b&&(b&=17);switch(b){case 0:a=a.H.O&4?a.v:a.S;break;case 1:a=a.H;break;case 2:a=a.I.O&4?a.F:a.R;break;case 3:a=a.I;break;case 16:a=c?a.T:a.B;break;case 17:a=a.N;break;default:a=a.W}return a}g.X=function(a,b){if(void 0!==b){var c=lc(this,a-this.P,!1);this.D&&V(this.D,this,a,b,this.D.Ma,!1,c.Jb);c.read()}};
g.Vb=function(a,b){if(void 0!==b){var c=this.C.X(a),d=lc(this,a-this.P,!0);if(this.D&&N(this.D,this.D.Ma|this.D.Ib)&&(V(this.D,this,a,b,this.D.Ma,!0,d.Jb),d.Wb))for(a=128,b=d.O^c;b&&a;)b&a&&this.D.message("  changed "+d.Jb+"."+d.Wb[a]+" to "+(c&a?"1":"0")),a>>=1;d.update(c)}};function ec(a,b,c){var d=-1;void 0!==b&&void 0!==c&&(d=0,c&32||(d|=2),a.v.O&64||(d|=1));a.h!=d&&(a.h=d,a.B.update())}function fc(a){0<=a.h&&(a.l[a.h].Ga=-1,a.N.update(255),a.B.update())}
function gc(a){if(0<=a.h){var b=a.l[a.h];var c=b.Wa[b.sa];void 0!==c&&(0<=b.Ga&&b.Ga<c.Kb.length?(b.Ia=100,b=c.Kb[b.Ga++],a.N.update(b),a.B.update()):(b.Ia=10,fc(a)))}}function X(a,b,c){a.C.g[b+a.P]=c.O}E(function(){for(var a=K("c1p","disk"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new cc(d);H(d,c)}});
function mc(a){G.call(this,"C1PDebugger",a);this.D=this;this.R=-1;this.za=0;this.lb=null;this.Ya=!1;this.la=0;this.ua=[];this.Ba=[];this.Da=[];this.Qa=0;this.Ca=[];this.H=[];this.Ib=1;this.Ea=16;this.gb=32;this.Ma=64;this.Ye=128;this.qa=this.da=0;this.Va={port:1,kbd:16,video:32,disk:64,serial:128};this.Ua=28;this.hb=56;this.Oa="ADC AND ASL BCC BCS BEQ BIT BMI BNE BPL BRK BVC BVS CLC CLD CLI CLV CMP CPX CPY DEC DEX DEY EOR INC INX INY JMP JSR LDA LDX LDY LSR NOP ORA PHA PHP PLA PLP ROL ROR RTI RTS SBC SEC SED SEI STA STX STY TAX TAY TSX TXA TXS TYA SIM .DB".split(" ");
this.ca=["HLT","MSG"];nc(this,!0);this.ka=[[10],[34,1,this.I],[this.hb,1],[],[],[34,1,this.h],[2,1,this.h],[],[36],[34,1,this.B],[2,0,this.T],[],[],[34,2,this.V],[2,2,this.V],[],[9,1,this.ja],[34,1,this.N],[],[],[],[34,1,this.l],[2,1,this.l],[],[13],[34,2,this.F],[],[],[],[34,2,this.v],[2,2,this.v],[],[this.Ua,2,this.Ta],[1,1,this.I],[],[],[6,1,this.h],[1,1,this.h],[39,1,this.h],[],[38],[1,1,this.B],[39,0,this.T],[],[6,2,this.V],[1,2,this.V],[39,2,this.V],[],[7,1,this.ja],[1,1,this.N],[],[],[],[1,
1,this.l],[39,1,this.l],[],[44],[1,2,this.F],[],[],[],[1,2,this.v],[39,2,this.v],[],[41],[23,1,this.I],[],[],[],[23,1,this.h],[32,1,this.h],[],[35],[23,1,this.B],[32,0,this.T],[],[27,2,this.Ta],[23,2,this.V],[32,2,this.V],[],[11,1,this.ja],[23,1,this.N],[],[],[],[23,1,this.l],[32,1,this.l],[],[15],[23,2,this.F],[],[],[],[23,2,this.v],[32,2,this.v],[],[42],[0,1,this.I],[],[],[],[0,1,this.h],[40,1,this.h],[],[37],[0,1,this.B],[40,0,this.T],[],[27,2,this.qb],[0,2,this.V],[40,2,this.V],[],[12,1,this.ja],
[0,1,this.N],[],[],[],[0,1,this.l],[40,1,this.l],[],[46],[0,2,this.F],[],[],[],[0,2,this.v],[40,2,this.v],[],[],[47,1,this.I],[],[],[49,1,this.h],[47,1,this.h],[48,1,this.h],[],[22],[],[53],[],[49,2,this.V],[47,2,this.V],[48,2,this.V],[],[3,1,this.ja],[47,1,this.N],[],[],[49,1,this.l],[47,1,this.l],[48,1,this.ba],[],[55],[47,2,this.F],[54],[],[],[47,2,this.v],[],[],[31,1,this.B],[29,1,this.I],[30,1,this.B],[],[31,1,this.h],[29,1,this.h],[30,1,this.h],[],[51],[29,1,this.B],[50],[],[31,2,this.V],[29,
2,this.V],[30,2,this.V],[],[4,1,this.ja],[29,1,this.N],[],[],[31,1,this.l],[29,1,this.l],[30,1,this.ba],[],[16],[29,2,this.F],[52],[],[31,2,this.v],[29,2,this.v],[30,2,this.F],[],[19,1,this.B],[17,1,this.I],[],[],[19,1,this.h],[17,1,this.h],[20,1,this.h],[],[26],[17,1,this.B],[21],[],[19,2,this.V],[17,2,this.V],[20,2,this.V],[],[8,1,this.ja],[17,1,this.N],[],[],[],[17,1,this.l],[20,1,this.l],[],[14],[17,2,this.F],[],[],[],[17,2,this.v],[20,2,this.v],[],[18,1,this.B],[43,1,this.I],[],[],[18,1,this.h],
[43,1,this.h],[24,1,this.h],[],[25],[43,1,this.B],[33],[],[18,2,this.V],[43,2,this.V],[24,2,this.V],[],[5,1,this.ja],[43,1,this.N],[],[],[],[43,1,this.l],[24,1,this.l],[],[45],[43,2,this.F],[],[],[],[43,2,this.v],[24,2,this.v],[]]}t(mc,G);g=mc.prototype;
g.Y=function(a,b,c){var d=this;switch(b){case "debugInput":return this.W=this.M[b]=c,this.W.focus(),c.onkeypress=function(e,f){return function(k){13==k.keyCode&&(b=f.value,f.value="",oc(e,b))}}(this,c),!0;case "debugEnter":return this.M[b]=c,Na(c,function(){return d.W?(b=d.W.value,oc(d,b),!0):!1}),!0;case "step":return this.M[b]=c,Na(c,function(e){var f=!1;ib(d,!0)||(jb(d,!0),f=d.step(e?1:0),jb(d,!1));return f}),!0}return!1};
g.ha=function(a,b,c){this.g=a;this.P=b;this.xa=c-b+1;this.La=this.P+this.xa;this.Z()};g.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.C=O(b,"cpu"))};g.ia=function(){this.W.focus()};
function nc(a,b){a.T=0;a.B=1;a.v=2;a.F=3;a.Ta=4;a.qb=5;a.l=6;a.ba=7;a.I=8;a.N=9;a.V=10;a.h=11;a.ja=a.Ta;var c="";if(b)for(a.pa="A #$nn $nnnn,X $nnnn,Y $nnnn ($nnnn) $nn,X $nn,Y ($nn,X) ($nn),Y $nnnn $nn".split(" "),b=0;b<a.pa.length;b++){var d=a.pa[b];c+="("+d.replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\$/g,"\\$")+"|)"}else for(a.pa="A nn [nnnn+X] [nnnn+Y] nnnn [nnnn] [nn+X] [nn+Y] [[nn+X]] [[nn]+Y] [nnnn] [nn]".split(" "),
b=0;b<a.pa.length;b++)d=a.pa[b],c+="("+d.replace(/\[/g,"\\[").replace(/]/g,"\\]").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\+/g,"\\+")+"|)";a.We=new RegExp(c);a.Xb=[27,a.Ua,9,7,11,12,3,4,8,5]}g.ga=function(){this.C.ga()};g.info=function(){};function V(a,b,c,d,e,f,k){(a.qa&e)==e&&(e=a.C.X(c),a.message(b.id+"."+(f?"setByte":"getByte")+"("+A(c)+")"+(void 0!==d?" @"+A(d):"")+": "+(k?k+"=":"")+z(e)))}g.message=function(a){this.u(a);Ab(this.C)};
g.Aa=function(){if(!pc(this))return!1;this.C.Aa();return!0};g.step=function(a){if(!pc(this))return!1;try{var b=this.C.step(a)}catch(c){b=void 0,gb(this.C,c.stack||c.message)}void 0!==b&&this.R++;this.C.update(!0);this.update(!0);return b};g.update=function(a){this.za=this.C.j;a||this.Fa?qc(this):rc(this)};function pc(a){a.C&&hb(a.C)&&!ib(a.C)?(a=a.C,a.J.error?(a.u(a.toString()+" error"),a=!0):a=!1,a=!a):a=!1;return a}
g.reset=function(){var a;this.Ca.length||(this.Ca=Array(1E3));for(a=0;a<this.Ca.length;a++)this.Ca[a]=-1;this.H.length||(this.H=Array(256));for(a=0;a<this.H.length;a++)this.H[a]=[a,0];this.R&&this.update();this.R=0};g.start=function(){this.Fa||this.u("running")};g.stop=function(a,b){this.Fa||(this.u("stopped"),b&&this.u(Wa()-a+"ms ("+b+" cycles)"));this.update();this.ia();this.Fa||(this.R=0);sc(this,this.C.j)};g.X=function(a){if(a>=this.P&&a<this.La){sb(this.C,a);var b=this.g[this.P+a];b&=255}return b};
function tc(a,b,c){b<a.P||b>=a.La?a.u("invalid address: "+A(b)):(a.g[a.P+b]=c&255,ub(a.C,b),a.C.update())}function uc(a,b){Y(a.ua,b)||a.ua.push(b);return!0}function Y(a,b,c){for(var d=!1,e=0;e<a.length;e++)if(a[e]==b){c&&a.splice(e,1);d=!0;break}return d}function vc(a,b){void 0!==b&&(sc(a,a.S),uc(a,b)&&(a.S=b))}function sc(a,b){void 0!==a.S&&b==a.S&&Y(a.ua,a.S,!0)&&(a.S=void 0);a.Fa=!1}
function zb(a,b,c,d){for(var e=!1,f=0;f<c.length;f++)if(c[f]==b){b!=a.S&&a.u("breakpoint hit: "+A(b)+" ("+d+")");e=!0;break}return e}
function wc(a,b,c){var d=y(b,4),e=a.X(b++),f=void 0===e?0:e,k=a.ka[f],l=[],h=void 0===k[1]?0:k[1];do{d+=" "+y(f,2);if(!h--)break;f=a.X(b++);if(void 0===f)break;l.push(f)}while(1);void 0===k[0]&&(k=[57,1,a.B],l.push(e));d=(d+"        ").substr(0,15);d+=a.Oa[k[0]];var p=null;if(void 0!==k[2]){h=k[2];p=a.pa[h];if(1==k[1]&&h==a.ja){var n=p.replace;l=f=l.pop();p=n.call(p,/nnnn/,y(b+(l<<24>>24),4))}else for(;l.length;)p=p.replace(/nn/,y(f=l.pop(),2));h==a.B&&1==k[1]&&32<=f&&128>f&&(p+=" ;'"+String.fromCharCode(f)+
"'")}if(e==a.C.hb&&(f<a.ca.length&&(p=a.ca[f]),f==a.C.Mb)){h=0;for(p='"';f=a.X(b++);)16>h?p+=String.fromCharCode(f):16==h&&(p+="\u2026"),h++;p+='"'}p&&(d+=" "+p);c&&(d=(d+"               ").substr(0,30),d+=";"+c.toString());a.ea=b;return d}
function Z(a,b){var c=a.za;if(void 0!==b){var d=16;"$"==b.charAt(0)?b=b.substr(1):"0x"==b.substr(0,2)?b=b.substr(2):"."==b.charAt(b.length-1)&&(d=10,b=b.substr(0,b.length-1));c=parseInt(b,d);isNaN(c)&&(a.u("invalid base-"+d+" address: "+b),c=void 0)}void 0!==c&&(c<a.P||c>=a.La)&&(a.u("address out of range: "+y(c)),c=void 0);return c}
function xc(a,b){if("?"==b)a.u("\nfrequency commands:"),a.u("clear\tclear all frequency counts");else{var c=0;if(a.H)if("clear"==b){for(b=0;b<a.H.length;b++)a.H[b]=[b,0];a.u("frequency data cleared");c++}else if(void 0!==b)a.u("unknown frequency command: "+b),c++;else{var d=a.H.slice();d.sort(function(k,l){return l[1]-k[1]});for(b=0;b<d.length;b++){var e=d[b][0],f=d[b][1];f&&(a.u(a.Oa[a.ka[e][0]]+" ("+z(e)+"): "+f+" times"),c++)}}c||a.u("no frequency data available")}}
function qc(a,b,c,d){var e=Z(a,b);if(void 0!==e){void 0===d&&(d=1);b=a.La;if(void 0!==c){b=Z(a,c);if(void 0===b||b<e)return;if(256<b-e){a.u("range too large");return}b++;d=-1}for(e!=a.za&&a.u();d--&&e<b;)c=wc(a,e,ib(a,!1)||a.Fa?a.R:0),a.u(c),a.za=e=a.ea}}
function rc(a,b){if(b&&"?"==b[1])a.u("\nregister commands:"),a.u("r to display all"),a.u("r [target=value] to modify"),a.u("supported targets:"),a.u("A,X,Y,S,PC and flags C,Z,D,V,N");else{var c=!0;if(void 0!==b&&1<b.length){c=!1;var d=b[1],e=d.indexOf("=");if(0<e)b=d.substr(e+1),d=d.substr(0,e);else if(2<b.length)b=b[2];else{a.u("missing value for "+b[1]);return}e=parseInt(b,16);if(isNaN(e)){a.u("invalid value: "+b);return}switch(d.toUpperCase()){case "A":a.C.m=e&255;break;case "X":a.C.G=e&255;break;
case "Y":a.C.K=e&255;break;case "C":a.C.i=e?256:0;break;case "Z":a.C.s=e?0:1;break;case "D":e?Cb(a.C):Db(a.C);break;case "V":e?(d=a.C,d.B=0,d.F=128):(d=a.C,d.B=0,d.F=0);break;case "N":a.C.o=e?128:0;break;case "S":if(256!=(e&-256)){a.u("invalid stack pointer: "+b);return}a.C.L=e;break;case "PC":c=!0;a.C.j=e&65535;a.za=a.C.j;break;default:a.u("unknown register: "+d);return}a.C.update()}a.u("A="+y(a.C.m,2)+" X="+y(a.C.G,2)+" Y="+y(a.C.K,2)+" P="+y(xb(a.C),2)+" S="+y(a.C.L,4)+" PC="+y(a.C.j,4));c&&qc(a,
y(a.za=a.C.j,4))}}function yc(a,b){b=void 0===b?1:parseInt(b,10);var c=1==b?0:1;Ma(b,function(d){return function(){return jb(d,!0)&&d.step(c)}}(a),function(d){return function(){jb(d,!1)}}(a))}
function oc(a,b){b.length||(a.Ya?(a.u("ended assemble @"+y(a.la,4)),a.za=a.la,a.Ya=!1):a.lb&&(b=a.lb));if(hb(a)&&!ib(a,!0)&&0<b.length){a.Ya?b="a "+y(a.la,4)+" "+b:1<b.length&&1!=b.indexOf(" ")&&(b=b.charAt(0).toLowerCase()+" "+b.substr(1));var c=b.split(" ");a.lb=c[0];switch(c[0].toLowerCase()){case "a":var d=Z(a,c[1]);if(void 0!==d)if(a.la=d,void 0===c[2])a.u("begin assemble @"+A(a.la)),a.Ya=!0,a.C.update();else{b=c[2];var e=c[3];c=a.la;d=[];if(void 0!==b){var f;b=b.toUpperCase();"?"==b.charAt(b.length-
1)&&(e="?",b=b.substr(0,b.length-1));for(f=0;f<a.Oa.length&&b!=a.Oa[f];f++);f==a.Oa.length&&(a.u("unknown operation: "+b),f=-1);var k="",l;if(0<=f&&void 0!==e)if(k=e.toUpperCase(),"?"==k){for(e=l=0;e<a.ka.length;e++)a.ka[e][0]===f&&(l||a.u("supported opcodes:"),a.u("     "+y(e,2)+": "+b+(void 0!==a.ka[e][2]?" "+a.pa[a.ka[e][2]]:"")),l++);f=-1}else if(l=k.match(a.We),null!==l&&l[0]==k){for(e=1;e<l.length;e++)if(l[e]==k)if(void 0===h)var h=e-1;else{a.u("too many operand matches (both "+a.pa[h]+" and "+
a.pa[e-1]+")");f=-1;break}h==a.Ta&&0>a.Xb.indexOf(f)&&(h=a.V);h==a.qb&&27!=f&&(h=a.V)}else a.u("unknown operand: "+k),f=-1;if(0<=f){l=-1;for(e=0;e<a.ka.length;e++)if(a.ka[e][0]===f&&a.ka[e][2]===h)if(0>l)l=e;else{a.u("too many instruction matches (both "+z(l)+" and "+z(e)+")");l=-2;break}if(0<=l){if(d.push(l),void 0!==h)if(b=a.ka[l][1],k=k.match(/[0-9A-F]+/),null!==k)for(k=parseInt(k[0],16),1==b&&h==a.ja&&(k-=c+2,-128>k||127<k)&&(a.u("branch out of range ("+k+")"),d=[],b=0),e=0;e<b;e++)d.push(k&255),
k>>>=8;else b&&a.u("instruction missing "+b+" bytes")}else a.u("unknown instruction: "+b+" "+k)}}h=d;if(h.length){for(c=0;c<h.length;c++)tc(a,a.la+c,h[c]);a.u(wc(a,a.la));a.la+=h.length}}break;case "b":h=c[1];c=c[2];if(void 0===h||"?"==h)a.u("\nbreakpoint commands:"),a.u("bp [a]\tset exec breakpoint at [a]"),a.u("br [a]\tset read breakpoint at [a]"),a.u("bw [a]\tset write breakpoint at [a]"),a.u("bc [a]\tclear breakpoint at [a]"),a.u("bl\tlist all breakpoints");else if(void 0===c&&1<h.length&&(c=
h.substr(1),h=h.charAt(0)),"l"==h){h=0;d=a.ua;for(c=0;c<d.length;c++)a.u("breakpoint enabled: "+A(d[c])+" (exec)"),h++;d=a.Ba;for(c=0;c<d.length;c++)a.u("breakpoint enabled: "+A(d[c])+" (read)"),h++;d=a.Da;for(c=0;c<d.length;c++)a.u("breakpoint enabled: "+A(d[c])+" (write)"),h++;h||a.u("no breakpoints")}else void 0===c?a.u("missing breakpoint address"):"c"==h&&"*"==c?(a.ua=[],a.Ba=[],a.Da=[],a.u("all breakpoints cleared")):(c=Z(a,c),void 0!==c&&("p"==h?uc(a,c)?a.u("breakpoint enabled: "+A(c)+" (exec)"):
a.u("breakpoint not set: "+A(c)):"c"==h?Y(a.ua,c,!0)?a.u("breakpoint cleared: "+A(c)+" (exec)"):Y(a.Ba,c,!0)?a.u("breakpoint cleared: "+A(c)+" (read)"):Y(a.Da,c,!0)?a.u("breakpoint cleared: "+A(c)+" (write)"):a.u("breakpoint missing: "+A(c)):"r"==h?(Y(a.Ba,c)||a.Ba.push(c),a.u("breakpoint enabled: "+A(c)+" (read)")):"w"==h?(Y(a.Da,c)||a.Da.push(c),a.u("breakpoint enabled: "+A(c)+" (write)")):a.u("unknown breakpoint command: "+h)));break;case "d":h=c[1];d=c[2];if("?"==h)a.u("\ndump commands:"),a.u("d [a] [#]    dump # lines of memory");
else if(h=Z(a,h),void 0!==h){c=0;void 0!==d&&("l"==d.charAt(0)&&(d=d.substr(1)),c=parseInt(d,10));c||(c=1);for(d=0;d<c;d++){k=b="";e=h;for(f=0;8>f&&h<a.La;f++)l=a.X(h),void 0===l&&(l=0),b+=y(l,2)+" ",k+=32<=l&&127>l?String.fromCharCode(l):".",h++;a.u(y(e,4)+" "+b+k)}a.za=h}break;case "e":h=c[1];if(void 0===h)a.u("missing address");else if(h=Z(a,h),void 0!==h)for(d=2;d<c.length;d++)b=parseInt(c[d],16),tc(a,h++,b);break;case "f":xc(a,c[1]);break;case "g":h=c[1];void 0!==h&&vc(a,Z(a,h));a.Aa()||a.C.ia();
break;case "h":a.ga();break;case "o":if(void 0===c[1]||"?"==c[1])a.u("\noption commands:"),a.u("max\trun at maximum speed"),a.u("fast\trun faster (up to "+a.C.Na+"Mhz)"),a.u("slow\trun at normal speed (1Mhz)"),a.u("classic\tuse classic operand syntax"),a.u("modern\tuse modern operand syntax"),a.u("msg\tenable message categories");else switch(h=c[1],h){case "slow":ob(a.C,a.C.Xa);break;case "fast":ob(a.C,a.C.Nb);break;case "max":ob(a.C,a.C.Ob);break;case "classic":nc(a,!0);a.u("classic syntax enabled");
break;case "modern":nc(a,!1);a.u("modern syntax enabled");break;case "msg":h=0;void 0!==c[2]&&("all"==c[2]?h=255:void 0!==a.Va[c[2]]&&(h=a.Va[c[2]]),h&&("on"==c[3]?a.qa|=h:"off"==c[3]&&(a.qa&=~h)));for(d in a.Va)if(void 0===c[2]||"all"==c[2]||c[2]==d)h=a.Va[d],a.u(d+" messages: "+(a.qa&h?"on":"off"));break;default:a.u("unknown option: "+h)}break;case "p":k=c[1];h=10;c=a.Qa;d=a.Ca;if(void 0!==d){b=void 0===k?a.Zb:parseInt(k,10);void 0===b&&(b=10);b>d.length&&(a.u("note: only "+d.length+" available"),
b=d.length);void 0!==k&&(a.kb=0,a.u(b+" instructions earlier:"));k=a.kb?a.kb:1;c-=b;for(0>c&&(c=d.length-1);h&&c!=a.Qa;){e=d[c];if(0>e)break;a.u(wc(a,e,k++));++c==d.length&&(c=0);h--;b--}a.Zb=b;a.kb=k}10==h&&a.u("no history available");break;case "r":rc(a,c);break;case "s":a.X(a.C.j)==a.C.Ua?(vc(a,a.C.j+3),a.Fa=!0,a.Aa()||a.C.ia()):yc(a);break;case "t":yc(a,c[1]);break;case "u":qc(a,c[1],c[2],8);break;case "?":case "help":a.u("\ncommands:\n?\thelp\na [#]\tassemble\nb [#]\tbreakpoint\nd [#]\tdump memory\ne [#]\tedit memory\nf\tdump frequencies\ng [#]\trun to [#]\nh\thalt\no\toptions\np [#]\tdump history\nr\tdump/edit registers\ns\tstep over instruction\nt [#]\tstep instruction(s)\nu [#]\tunassemble");
a.u("note: frequency and history commands operate only when breakpoints are set");break;default:a.u("unknown command: "+b)}}}E(function(){for(var a=K("c1p","debugger"),b=0;b<a.length;b++){var c=a[b],d=M(c);d=new mc(d);H(d,c)}});function zc(a,b){G.call(this,"C1PComputer",a);this.fa=b}t(zc,G);zc.prototype.reset=function(a){var b=null,c;for(c in this.fa)for(var d=0;d<this.fa[c].length;d++){var e=this.fa[c][d];e&&e.reset&&(e.reset(),"cpu"==c&&(b=e))}b&&(b.update(),a&&b.Aa())};
zc.prototype.start=function(){for(var a in this.fa)if("cpu"!=a)for(var b=0;b<this.fa[a].length;b++){var c=this.fa[a][b];c&&c.start&&c.start()}};zc.prototype.stop=function(a,b){for(var c in this.fa)if("cpu"!=c)for(var d=0;d<this.fa[c].length;d++){var e=this.fa[c][d];e&&e.stop&&e.stop(a,b)}};zc.prototype.Y=function(a,b,c){switch(b){case "reset":return this.M[b]=c,c.onclick=function(d){return function(){d.reset()}}(this),!0}return!1};function O(a,b){return a.fa[b]?a.fa[b][0]:null}
function Ac(a){var b=null,c;for(c in a.fa)for(var d=0;d<a.fa[c].length;d++){var e=a.fa[c][d];if(e){if(!hb(e)){hb(e,function(f){return function(){Ac(f)}}(a));return}"cpu"==c?b=e:e.oa&&e.oa(!0,a)}}a.Z();a.u("C1Pjs v2.20\nCopyright \u00a9 2012-2023 Jeff Parsons <Jeff@pcjs.org>");b&&b.oa(!0,a)}
E(function(){for(var a=K("c1p","computer"),b=0;b<a.length;b++){for(var c=a[b],d=M(c),e,f={},k,l=0,h=0,p=0;p<d.modules.length;p++){var n=d.modules[p];if(!p){if("cpu"!=n.type)break;l=+n.start;h=+n.end;k=Array(h+1-l);for(e=l;e<k.length;e++)k[e]=0}if(e=Ya(n.refID,d.id)){var q=n.type;void 0===f[q]&&(f[q]=[]);f[q].push(e);e.ha&&void 0!==n.start&&e.ha(k,+n.start,+n.end,f.cpu[0])}else{C('no component for <module refid="'+n.refID+'">');return}}if(void 0===k){C('<module type="cpu"> definition must appear first in the <computer> specification');
break}if(e=Ya("debugger",d.id))f["debugger"]=[e],e.ha&&e.ha(k,l,h,f.cpu[0]);l=new zc(d,f);if(h=Ya("panel",d.id))if(f.panel=[h],h.M.print){e=void 0;d=d.id;f=[];d&&(d=0<(e=d.indexOf("."))?d.substr(0,e+1):"");for(e=0;e<v.length;e++)p=v[e],d&&p.id.indexOf(d)||f.push(p);d=f;for(f=0;f<d.length;f++)e=d[f],e!=h&&(e.Za=h.Za,e.print=h.print,e.u=h.u)}H(l,c);Ac(l)}});var Bc=0;
function Cc(a,b,c,d,e,f,k,l,h){l("Loading "+a+"...");B(a,function(p,n,q){q?(n||(n="unable to load "+a+" ("+q+")"),h(p,n,null)):Dc(n,a,b,c,d,e,f,k,l,h)})}
function Dc(a,b,c,d,e,f,k,l,h,p){function n(q,m,r){if(r)p(q,r,null);else{c&&(Va(c,b,m),(r=b)&&0>r.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(r=window.location.pathname+r),f?"}"==f.slice(-1)?(f=f.slice(0,-1),1<f.length&&(f+=",")):f='{state:"'+f+'",':f="{",f+='url:"'+r+'"}',"object"==typeof resources&&(r=null),f=f.replace(/\$/g,"$$$$").replace(/'/g,"&apos;"),k&&(q=m.match(/(<machine[^>]*\sclass=)(['"])(.*?)(\2[^>]*>)/))&&(m=m.replace(q[0],q[1]+q[2]+k+q[4]),k=""),(q=m.match(/(<machine[^>]*\sdebugger=)(['"])(available)(\2[^>]*>)/))&&
(m=m.replace(q[0],q[1]+q[2]+"optional"+q[4])),m=m.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(k?' class="'+k+'"':"")+(f?" parms='"+f+"'":"")+(r?' url="'+r+'"':"")));l||(m=m.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1"+d+"$2"),m=m.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1"+e+"$2"),m=m.replace(/<xsl:variable name="APPVERSION"(\/>|>[^<]*<\/xsl:variable>)/,'<xsl:variable name="APPVERSION">2.20</xsl:variable>'));q=null;if("<"==m.charAt(0))try{l||
(m=m.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(q=new window.ActiveXObject("Microsoft.XMLDOM"),q.async=!1,q.loadXML(m)):q=(new window.DOMParser).parseFromString(m,"text/xml")}catch(J){q=null,m=J.message}else m="unrecognized XML: "+(255<m.length?m.substr(0,255)+"...":m);p(b,m,q)}}a?l?Ec(b,a,h,n):n(b,a,""):p(b,"no data",null)}
function Ec(a,b,c,d){var e;if(e=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(b)){var f=e[2];c("Loading "+f+"...");B(f,function(k,l,h){if(h||!l)d(k,b,"unable to resolve XML reference: "+e[0]+" ("+h+")");else{if(h=e[3]){var p=l.match(new RegExp("<"+e[1]+"[^>]*>"));if(p){for(var n=p[0],q,m=/( [a-z]+=)(['"])(.*?)\2/gi;q=m.exec(h);)n=0>n.toLowerCase().indexOf(q[1].toLowerCase())?n.replace(">",q[0]+">"):n.replace(new RegExp(q[1]+"(['\"])(.*?)\\1"),q[0]);p[0]!=n&&(l=l.replace(p[0],n))}else{d(k,b,"missing <"+
e[1]+"> in "+f);return}}l=l.replace(/<\?xml[^>]*>[\r\n]*/,"");b=b.replace(e[0],l);Ec(k,b,c,d)}})}else d(a,b,"")}
function Fc(a,b,c,d,e,f,k){function l(P){if(void 0===q){var I=n&&K("machine-warning","",n);q=I&&I[0]||n}q&&(q.innerHTML=ya(P))}function h(P,I){if("string"==typeof I&&0<=I.indexOf("<!DOCTYPE html>")){var ia=I.match(/<title>(?:PCjs: |)(.*?)<\/title>/);ia&&(I=ia[1])}l("Error: "+I+(P?" ("+P+")":""));m&&p();m=!1}function p(){--Bc||F(!0)}var n,q,m=!0;Bc++;u[c]={};if(!d)return f&&Va(c,"parms",f),p(),m;"true"==Ka("debugger")&&0>d.indexOf("/debugger")&&(d=d.replace("/machine.xml","/debugger/machine.xml"));
try{if(n=document.getElementById(c)){var r,J=w.resources;if("object"==typeof J&&(r=J.css)){var R=document.head||document.getElementsByTagName("head")[0],x=document.createElement("style");x.type="text/css";x.styleSheet?x.styleSheet.cssText=r:x.appendChild(document.createTextNode(r));R.appendChild(x)}e||(e="/machines/"+b+"/xsl/components.xsl");b=b.split("/").pop();r=function(P,I,ia){ia?Cc(e||"","",a,b,"","",!1,l,function(Q,W,L){if(L)if(Va(c,e||"",W),l("Processing "+d+"..."),window.ActiveXObject||"ActiveXObject"in
window)(L=ia.transformNode(L))?(n.outerHTML=L,p()):h(Q,"transformNodeToObject failed");else if(document.implementation&&document.implementation.createDocument)if(W=new XSLTProcessor,W.importStylesheet(L),L=W.transformToFragment(ia,document))if(W=n.parentNode){var Ba=Q=0,cb=n.getBoundingClientRect();0>cb.bottom&&(Q=window.scrollX,Ba=window.scrollY);W.replaceChild(L,n);(n=document.getElementById(c))&&0>cb.bottom&&(L=n.getBoundingClientRect(),Ba=window.performance&&window.performance.navigation.type==
window.performance.navigation.TYPE_RELOAD?0:Ba+Math.ceil(L.height-cb.height),window.scrollTo(Q,Ba));p()}else h(Q,"invalid machine element: "+c);else h(Q,"transformToFragment failed");else h(Q,"unable to transform XML: unsupported browser");else h(Q,W)}):h(P,I)};"<"!=d.charAt(0)?Cc(d,c,a,b,f||"",k||"",!0,l,r):Dc(d,"",c,a,b,f||"",k||"",!1,l,r)}else h(d,"missing machine element: "+c)}catch(P){h(d,P.message)}return m}function Gc(a,b,c,d,e){F(!1);return Fc("PCx86","pcx86",a,b,c,d,e)}
w.embedC1P=function(a,b,c,d,e){F(!1);return Fc("C1Pjs","osi/c1p",a,b,c,void 0,e)};w.embedPC=Gc;w.embedPCx86=Gc;w.embedPCx80=function(a,b,c,d,e){F(!1);return Fc("PCx80","pcx80",a,b,c,d,e)};w.embedPDP10=function(a,b,c,d,e){F(!1);return Fc("PDPjs","dec/pdp10",a,b,c,d,e)};w.embedPDP11=function(a,b,c,d,e){F(!1);return Fc("PDPjs","dec/pdp11",a,b,c,d,e)};
w.commandMachine=function(a,b,c,d,e,f){if("script"==e){d=!1;c+=".machine";if(!f)delete sa[c],d=!0;else if("string"==typeof f&&!sa[c]){d=!0;e=c;for(var k=f.length,l=[],h=[],p="",n=null,q=0;q<k;q++){var m=f[q];if('"'==m||"'"==m)n&&m!=n?p+=m:(n?n=null:n=m,p&&(h.push(p),p=""));else{if(!n){if("\r"==m||"\n"==m)m=";";if(" "==m||"\t"==m||";"==m){p&&(h.push(p),p="");";"==m&&h.length&&(l.push(h),h=[]);continue}}p+=m}}p&&h.push(p);h.length&&l.push(h);sa[e]=l;$a(c)||(d=!1)}return d?(b&&(a.disabled=!0),!0):!1}if(d&&
(k=Za(d,c+".machine"))&&(l=k.exports)&&(l=l[e]))return l.call(k,f)?(b&&(a.disabled=!0),!0):!1;console.log("unimplemented: commandMachine('"+c+"','"+d+"','"+e+"','"+f+"')");return!1};w.enableEvents=F;w.sendEvent=Ta;})()

//# sourceMappingURL=c1p.js.map
