(function(){/*
 https://www.pcjs.org/modules/v2/messages.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/dumpapi.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/reportapi.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/strlib.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/weblib.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/embed.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/defines.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/format.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/usrlib.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/component.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/panel.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/cpu.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/rom.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/ram.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/keyboard.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/video.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/serial.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/disk.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/debugger.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v2/computer.js (C) 2012-2025 Jeff Parsons
*/
var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){if(!(a instanceof Array)){a=ba(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ea="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ha(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ia=ha(this);function r(a,b){if(b)a:{var c=ia;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ea(c,a,{configurable:!0,writable:!0,value:b})}}var ja;
if("function"==typeof Object.setPrototypeOf)ja=Object.setPrototypeOf;else{var ka;a:{var la={a:!0},ma={};try{ma.__proto__=la;ka=ma.a;break a}catch(a){}ka=!1}ja=ka?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var na=ja;
function v(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(na)na(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ze=b.prototype}function oa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
r("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
r("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});r("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
r("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});r("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,h){this.g=f;ea(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ia[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ea(d.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(aa(this))}})}return a});function pa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function qa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});var ra="undefined"!=typeof window?{}:global,w="undefined"!=typeof window?window:global,sa="undefined"!=typeof document?document:{},y={machines:{},components:[],commands:{}};
w.PCjs?y=w.PCjs:w.PCjs=y;w.LOCALDISKS=!1;function ta(){this.g={};for(var a=0;23>a;a++)this.g["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
function ua(){var a=oa.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,ca(a)));return a}
ta.prototype.h=function(a){var b=oa.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var h=d[f+5];if(void 0===this.g[h])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+h;else{if(e<b.length){var k=b[e];"%"!=h&&e++}else k=b[b.length-1];var l=d[f+1],n=0<=l.indexOf("#"),p=0<=l.indexOf("0"),m=d[f+2];"*"==m?(m=k,k=e<b.length?b[e++]:b[b.length-1]):m=+m||0;var q=d[f+3];q=q?+q.substr(1):-1;var t=d[f+4],J=null,
K=0,x="",u=0<="ACDFGHMNSTWY".indexOf(h)&&"object"!=typeof k?ua(k):k;switch(h){case "C":c+=isNaN(u.getTime())?void 0:this.h("%#W, %#F %#D, %#Y".replaceAll("#",n?"#":""),u);continue;case "D":k=n?u.getUTCDate():u.getDate();h="d";break;case "A":case "G":case "H":k=n?u.getUTCHours():u.getHours();"A"==h?(k=12>k?"am":"pm",h="s"):("G"==h&&(k=k?12<k?k-12:k:12),h="d");break;case "F":case "M":k=n?u.getUTCMonth():u.getMonth();"F"==h?(k=va[k],h="s"):(k++,h="d");break;case "N":k=n?u.getUTCMinutes():u.getMinutes();
h="d";break;case "S":k=n?u.getUTCSeconds():u.getSeconds();h="d";break;case "T":c+=isNaN(u.getTime())?void 0:this.h("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",n?"#":""),u);continue;case "W":k=wa[n?u.getUTCDay():u.getDay()];h="s";break;case "Y":k=n?u.getUTCFullYear():u.getFullYear(),0<q&&(k%=Math.pow(10,q)),h="d"}switch(h){case "b":c+=k?"true":"false";break;case "d":k=Math.trunc(k),0<=q&&(p=!0,m<q&&(m=q),q=-1);case "f":k=+k;h=k+"";0<=q&&(h=k.toFixed(q));h.length<m&&(p?(0>k&&(m--,h=h.substr(1)),
h=("0".repeat(m)+h).slice(-m),0>k&&(h="-"+h)):h=(" ".repeat(m)+h).slice(-m));c+=h;break;case "j":c+=JSON.stringify(k,null,m||void 0);break;case "c":k="string"==typeof k?k[0]:String.fromCharCode(k);case "s":if(void 0!=k)for("string"!=typeof k&&(k=k.toString()),0<=q&&(k=k.substr(0,q));k.length<m;)k=0<=l.indexOf("-")?k+" ":" "+k;c+=k;break;case "B":K=2,n&&(x="0b");case "o":K||(K=8),!x&&n&&(x="0o");case "X":J=xa;case "x":h="";K||(K=16);!x&&n&&(x="0x");J||(J=za);k=Math.trunc(k);0<=q&&(p=!0,m<q&&(m=q));
p&&!m&&("b"==t?m=2:"h"==t||"w"==t?m=4:"l"==t?m=8:(m=Math.abs(k),m=255>=m?2:65535>=m?4:4294967295>=m?8:9),m+=x.length);m-=x.length;do n=16,Number.isNaN(k)||(n=k&K-1,k=Math.trunc(k/K)),p||!h||n||k?h=J[n]+h:(x&&(h=x+h,x=""),0<m&&(h=" "+h));while(0<--m||k);c+=x+h;break;case "%":c+="%";break;default:c=this.g[h]?c+this.g[h](h,l,m,q,k):c+("(unimplemented sprintf type: %"+h+")")}}}return c+=d[f]};
var za="0123456789abcdef?",xa="0123456789ABCDEF?",wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" ");function Aa(){}
function z(a,b,c){b?9<b&&(b=9):(b=Math.abs(a),b=65535>=b?4:4294967295>=b?8:9);c=c?"0x":"";var d=void 0===d?0:d;var e="";isNaN(a)||"number"!=typeof a?a=null:(0>a&&-1<a&&(a=-1),0>a&&(a+=Math.pow(16,b)),a>=Math.pow(16,b)&&(b=Math.ceil(Math.log(a)/Math.log(16))));for(var f=d||-1;0<b--;){f||(e=","+e,f=d);if(null==a)e="?"+e;else{var h=a%16;h+=0<=h&&9>=h?48:55;e=String.fromCharCode(h)+e;a=Math.trunc(a/16)}f--}return(void 0===c?"":c)+e}
function Ba(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));return b}function Ca(a){var b="",c=a.lastIndexOf(".");0<=c&&(b=a.substr(c+1).toLowerCase(),"json5"==b&&(b="json"));return b}function Da(a){return a.replace(/[&<>"'$]/g,function(b){return Ea[b]})}var Ea={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;",$:"&dollar;"},Fa=new ta,Ga=Fa.h.bind(Fa);
function A(a,b){var c=null,d=!0;c=void 0===c?"text":c;d=void 0===d?!1:d;var e=0,f=null,h=w.resources;if("object"==typeof h&&(f=h[a]))b&&b(a,f,e);else if(d&&"function"==typeof h)h(a,function(m,q){b&&b(a,m,q)});else{a=w.LOCALDISKS&&(w.location?w.location.hostname:"localhost").match(/^(.+\.local|localhost|0\.0\.0\.0|pcjs)$/)?a.replace(/^\/(diskettes|gamedisks|miscdisks|harddisks|decdisks|pcsigdisks|pcsig[0-9a-z]*-disks|private)\//,"/disks/$1/").replace(/^\/discs\/([^/]*)\//,"/disks/cdroms/$1/"):a.replace(/^\/(disks\/|)(diskettes|gamedisks|miscdisks|harddisks|decdisks|pcsigdisks|pcsig[0-9a-z]*-disks|private)\//,
"https://$2.pcjs.org/").replace(/^\/(disks\/cdroms|discs)\/([^/]*)\//,"https://$2.pcjs.org/");if(ra.Ue&&0!=a.indexOf("http")){try{h="arraybuffer"==c?null:"utf8",f=ra.Ue(a,h),h||(f=f.buffer,f.buffer&&(f=f.buffer))}catch(m){e=m.errno}if(void 0!==f){b&&b(a,f,e);return}}if(w.XMLHttpRequest)var k=new w.XMLHttpRequest;else if(w.ActiveXObject)k=new w.ActiveXObject("Microsoft.XMLHTTP");else if(w.fetch){fetch(a).then(function(m){switch(c){case "json":case "text":return m.text();case "arraybuffer":return m.arrayBuffer();
default:throw Error("unsupported response type: "+c);}}).then(function(m){b&&b(a,m,e)}).catch(function(){B(68719476736,"fetch %s error: %d\n",a,e);b&&b(a,f,e)});return}var l=!1,n="string"===typeof k.responseType;h=function(){if(4!==k.readyState)return null;try{f=l?k.response:k.responseText}catch(q){B(68719476736,"xmlHTTPRequest(%s) exception: %s\n",a,q.message)}if(null==f||200!=k.status&&(k.status||!f.length||"file:"!=(w.location?w.location.protocol:"file:")))if(e=k.status||-1,B(68719476736,"xmlHTTPRequest(%s) returned error %d\n",
a,e),!k.status&&!Ha){var m=a.match(/(^https?:\/\/[^/]+)(.*)/);m&&(Ha=!0,Ia("PCjs was unable to perform a cross-origin resource request to '"+m[1]+"'.\n\nIf you're running an ad blocker, try adding '"+Ja()+"' to your whitelist (or find a smarter ad blocker)."))}b&&b(a,f,e);return[f,e]};d&&(k.onreadystatechange=h);if(c&&"object"==typeof c){n="";for(var p in c)c.hasOwnProperty(p)&&(n&&(n+="&"),n+=p+"="+encodeURIComponent(c[p]));n=n.replace(/%20/g,"+");k.open("POST",a,d);k.setRequestHeader("Content-type",
"application/x-www-form-urlencoded");k.send(n)}else k.open("GET",a,d),"arraybuffer"==c&&(n?(l=!0,k.responseType=c):k.overrideMimeType("text/plain; charset=x-user-defined")),k.send();d||(k.readyState=4,h())}}function Ja(){return w.location?w.location.protocol+"//"+w.location.host:"https://www.pcjs.org"}
function C(a){if(w.navigator){var b=w.navigator?w.navigator.userAgent:"";return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===w.navigator.platform&&1<w.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ka(){var a,b=La("mobile");if(b)return"true"==b;if(C("Mobi")){if(!a)return!0;(b="!"==a[0])&&(a=a.substr(1));return C(a)!=b}return!1}
function La(a){if(!Ma){var b,c={};if(w.location){b||(b=w.location.search.substr(1));for(var d,e=/\+/g,f=/([^&=]+)=?([^&]*)/g;d=f.exec(b);)c[decodeURIComponent(d[1].replace(e," "))]=decodeURIComponent(d[2].replace(e," "))}Ma=c}return Ma[a]||Ma[a.toLowerCase()]}function Na(a,b,c){function d(){--a;0<=a&&(b()||(a=0));0<a?setTimeout(d,0):c()}d()}
function Oa(a,b){function c(){b(100===d)&&(e=setTimeout(c,d),d=100)}var d=0,e=null,f=!1;a.onmousedown=function(){f||e||(d=500,c())};a.ontouchstart=function(){e||(d=500,c())};a.onmouseup=a.onmouseout=function(){e&&(clearTimeout(e),e=null)};a.ontouchend=a.ontouchcancel=function(){e&&(clearTimeout(e),e=null);f=!0}}function D(a){Pa.init.push(a)}
function F(a){if((a=Pa[a])&&Qa)try{for(var b=0;b<a.length;b++)a[b]()}catch(c){B(274877906944,"%s\n\nIf it happens again, please send the URL to support@pcjs.org. Thanks.\n","An unexpected error occurred: "+c.message)}}function G(a){!Qa&&a?(Qa=!0,Ra&&F("init"),Sa&&F("show")):Qa=a}var Ma=null,Pa={init:[],show:[],exit:[]},Ra=!1,Sa=!1,Qa=!0,Ha=!1;function Ta(){Ra=!0;F("init",!0)}w.addEventListener&&w.addEventListener("load",Ta);function Ua(){Sa=!0;F("show",!0)}
w.addEventListener&&w.addEventListener("pageshow",Ua);function Va(){F("exit",!0)}w.addEventListener&&w.addEventListener(C("iOS")?"pagehide":C("Opera")?"unload":"beforeunload",Va);
function H(a,b,c){this.type=a;b||(b={id:"",name:""});this.name=b.name;this.id=this.id=b.id||"";this.exports={};this.M=this.bindings={};a=this.id.indexOf(".");0>a?this.ib="PCjs":this.ib=this.id.substr(0,a);this.J={ready:!1,Pa:!1,cb:!1,Ye:!1,U:!1,$e:!1,error:!1};this.hb=null;this.J.error=!1;this.qa=c||0;this.C=this.D=this.aa=null;y.components.push(this)}function Wa(a,b,c){y.machines[a]&&b&&(y.machines[a][b]=c,"parms"==b&&"string"==typeof c&&(y.machines[a].config=eval("("+c+")")))}
function Ya(){return Date.now()||+new Date}function B(a){var b=oa.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());if(68719476736<=c&&1099511627776>=c){var d=!1;1099511627776==c?(d=!0,a="Error: "+a):549755813888==c?(d=!0,a="Warning: "+a):274877906944==c&&(d=!0);b=Ga.apply(Aa,[a].concat(ca(b))).trim();d?Ia(b):console.log(b)}}function Ia(a){w.alert&&w.alert(a);console.log(a)}
function I(a,b){b=M("c1p-control","",b.parentNode);for(var c=0;c<b.length;c++)for(var d=b[c].childNodes,e=0;e<d.length;e++){var f=d[e];if(1===f.nodeType){var h=f.getAttribute("class");if(h)for(var k=h.split(" "),l=0;l<k.length;l++)switch(h=k[l],h){case "c1p-binding":(h=N(f))&&void 0!==h.binding?a.Y(h.type,h.binding,f,h.value):h&&"description"==h.type||B(549755813888,'Component "%s" missing binding%s\n',a.toString(),h?" for "+h.type:""),l=k.length}}}}
function Za(a,b){if(void 0!==a){var c;b&&0<(c=b.indexOf("."))&&(a=b.substr(0,c+1)+a);var d=y.components;for(c=0;c<d.length;c++)if(d[c].id===a)return d[c];d.length&&!1!==b&&B(549755813888,'Component ID "%s" not found\n',a)}return null}function $a(a,b,c){c=void 0===c?null:c;if(void 0!==a){var d;b&&(b=0<(d=b.indexOf("."))?b.substr(0,d+1):"");var e=y.components;for(d=0;d<e.length;d++)if(c)c==e[d]&&(c=null);else if(!(a!=e[d].type||b&&e[d].id.indexOf(b)))return e[d]}return null}
function N(a){var b=null;if(a.getAttribute){if(a=a.getAttribute("data-value"))try{b=eval("("+a+")")}catch(d){B(1099511627776,d.message+" ("+a+")")}}else if(b=a.config||null){a=a.id;var c=b.id;a&&c&&0>c.indexOf(".")&&(b.id=a+"."+c)}return b}
function M(a,b,c){b=void 0===b?"":b;c=void 0===c?sa:c;var d=[];b&&(a+="-"+b,"machine"!=b&&(a+="-object"));if(c.getElementsByClassName)d=c.getElementsByClassName(a);else if(c.getElementsByTagName){b=c.getElementsByTagName("*");var e=new RegExp("(^| )"+a+"( |$)");a=0;for(c=b.length;a<c;a++)e.test(b[a].className)&&d.push(b[a])}else for(a=Object.keys(y.machines),c=0;c<a.length;c++){e=a[c];var f=y.machines[e].config;if(f&&(f=f[b])){Array.isArray(f)||(f=[f]);f=ba(f);for(var h=f.next();!h.done;h=f.next())d.push({id:e,
config:h.value})}}return d}
function ab(a){for(var b=!0,c=y.commands[a];c&&c.length;){var d=c.splice(0,1)[0],e=d[0];B(8796093022208,d.join(" "));var f=null;0<=bb.indexOf(e)&&(f=function(){return function(){ab(a)}}());var h=cb[e];if(h)if(!f)b=h(d[1],d[2],d[3]);else{if(!h(f,d[1],d[2],d[3]))break}else{b=!1;var k=$a(d[1],a);if(k)if(h=db[e])b=h(k,d[2],d[3]);else{var l=k.exports;if(l&&(h=l[e]))if(b=!0,!f)b=h.call(k,d[2],d[3]);else if(!h.call(k,f,d[2],d[3]))break}}if(!b){Ia("Script error: '"+e+"' command "+(h?" failed":" not recognized"));
break}}c&&!c.length&&delete c[a];return b}g=H.prototype;g.toString=function(){return this.name?this.name:this.id||this.type};function eb(a){var b=1;a.ib&&(a=a.ib.match(/\d+/),null!==a&&(b=parseInt(a[0],10)));return b}
g.Y=function(a,b,c){switch(b){case "clear":return this.M[b]||(this.M[b]=c,c.onclick=function(d){return function(){d.M.print&&(d.M.print.value="")}}(this)),!0;case "print":return this.M[b]||(this.M[b]=c,c.value="",this.print=function(d,e){return function(f,h){f||(f="");if(4398046511104==(void 0===h?0:h)&&"...\n"==f.slice(-4)){h=f.slice(0,-1);var k=e.value,l=k.lastIndexOf(h);k=0>l?k+(h+"\n"):k.substr(0,l)+(f.slice(0,-1)+".")+k.substr(l+h.length);8192<k.length&&(k=k.substr(k.length-4096));e.value=k}else e.value+=
f,f=e.value,8192<f.length&&(e.value=f.substr(f.length-4096));e.scrollTop=e.scrollHeight}}(this,c)),!0;default:return!1}};g.print=function(a,b){B(void 0===b?0:b,a)};function fb(a,b){a.J.error=!0;a.u(274877906944,"%s\n",b)}function O(a,b){b&&(a.J.ready?b():a.hb=b);return a.J.ready}g.Z=function(){if(!this.J.error&&(this.J.ready=!0,this.J.ready)){var a=this.hb;this.hb=null;a&&a()}};function gb(a,b){a.J.Pa&&(b?a.J.cb=!0:void 0===b&&a.print(a.toString()+" busy\n"));return a.J.Pa}
function hb(a,b){if(a.J.cb)return a.J.Pa=!1,a.J.cb=!1;if(a.J.error)return a.print(a.toString()+" error\n"),!1;a.J.Pa=b;return a.J.Pa}function ib(a,b){var c=Math.pow(2,32),d=b/c|0;return(a&b)==(b|0)&&((a/c|0)&d)==d}function Q(a,b){b=void 0===b?0:b;b&1&&--b;b=b||a.qa;return!ib(b,2199023255552)&&(ib(0xff000000000-(a.C?618475290624:0),b)||a.C&&ib(a.C.qa,b))?!0:!1}
g.u=function(a){var b=oa.apply(1,arguments),c=0;"number"==typeof a&&(c=a||4398046511104,a=b.shift(),ib(c,68719476736)?a=(this.id||this.type||"log")+": "+a:ib(c,137438953472)&&(a=this.type+": "+a));Q(this,c)&&(b=Ga.apply(Aa,[a].concat(ca(b))),this.C&&this.C.message?this.C.message(b,c):this.print(b,c))};
var bb=["hold","sleep","wait"],cb={alert:function(a){Ia(a);return!0},sleep:function(a,b){setTimeout(a,+b);return!1}},db={select:function(a,b,c){var d=!1;if(a=a.bindings[b])for(b=0;b<a.options.length;b++)if(a.options[b].textContent==c){a.selectedIndex!=b&&(a.selectedIndex=b);d=!0;break}return d}};Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){b=b||0;for(var c=this.length;b<c;b++)if(this[b]===a)return b;return-1});Array.isArray||(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});
Function.prototype.bind||(Function.prototype.bind=function(a){function b(){return e.apply(this instanceof c&&a?this:a,d.concat(Array.prototype.slice.call(arguments)))}function c(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind: non-callable object");var d=Array.prototype.slice.call(arguments,1),e=this;c.prototype=this.prototype;b.prototype=new c;return b});function jb(a){H.call(this,"C1PPanel",a);this.J.U=!1}v(jb,H);
jb.prototype.Y=function(a,b,c,d){return this.aa&&this.aa.Y(a,b,c,d)||this.D&&this.D.Y(a,b,c,d)||this.h&&this.h.Y(a,b,c,d)||this.C&&this.C.Y(a,b,c,d)?!0:H.prototype.Y.call(this,a,b,c,d)};jb.prototype.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.aa=b,this.D=R(b,"cpu"),this.h=R(b,"keyboard"),this.C=R(b,"debugger"),kb())};function kb(){for(var a=!1,b=M("c1p","panel"),c=0;c<b.length;c++){var d=b[c],e=N(d),f=Za(e.id,!1);f||(a=!0,f=new jb(e));I(f,d);a&&f.Z()}}D(kb);
function lb(a){H.call(this,"C1PCPU",a);mb(this);this.J.U=!1;this.J.ta=!1;var b=La("autoStart");this.Za="true"==b||"false"==b?JSON.parse(b):a.autoStart;this.Xa=0;this.Mb=1;this.Nb=2;this.speed=this.Xa;this.Ka=30;this.Ja=5;this.Na=8;this.Ra=["Slow","Fast","Max"];this.mb=["(1Mhz)","(up to "+this.Na+"Mhz)","(unlimited)"];this.T=[];this.N=[];this.va=65536;this.wa=0;this.ma=65536;this.na=0;this.Ua=32;this.gb=2;this.Lb=1;this.v=[this.Cc,this.Wd,this.Ne,this.A,this.A,this.Yd,this.sc,this.A,this.ae,this.Vd,
this.rc,this.A,this.A,this.Sd,this.pc,this.A,this.Bc,this.Xd,this.A,this.A,this.A,this.Zd,this.tc,this.A,this.Fc,this.Ud,this.A,this.A,this.A,this.Td,this.qc,this.A,this.td,this.lc,this.A,this.A,this.yc,this.nc,this.ge,this.A,this.ce,this.kc,this.fe,this.A,this.xc,this.hc,this.de,this.A,this.zc,this.mc,this.A,this.A,this.A,this.oc,this.he,this.A,this.xe,this.jc,this.A,this.A,this.A,this.ic,this.ee,this.A,this.ne,this.gd,this.A,this.A,this.A,this.jd,this.Pd,this.A,this.$d,this.fd,this.Od,this.A,this.sd,
this.cd,this.Md,this.A,this.Dc,this.hd,this.A,this.A,this.A,this.kd,this.Qd,this.A,this.Hc,this.ed,this.A,this.A,this.A,this.dd,this.Nd,this.A,this.oe,this.vb,this.A,this.A,this.A,this.xb,this.le,this.A,this.be,this.ub,this.ke,this.A,this.rd,this.rb,this.ie,this.A,this.Ec,this.wb,this.A,this.A,this.A,this.yb,this.me,this.A,this.ze,this.tb,this.A,this.A,this.A,this.sb,this.je,this.A,this.A,this.De,this.A,this.A,this.Le,this.Fe,this.Ie,this.A,this.bd,this.A,this.Re,this.A,this.Ke,this.Ae,this.He,this.A,
this.uc,this.Ee,this.A,this.A,this.Me,this.Ge,this.Je,this.A,this.Te,this.Ce,this.Se,this.A,this.A,this.Be,this.A,this.A,this.Jd,this.yd,this.Ed,this.A,this.Kd,this.Ad,this.Fd,this.A,this.Pe,this.xd,this.Oe,this.A,this.Hd,this.ud,this.Cd,this.A,this.vc,this.zd,this.A,this.A,this.Ld,this.Bd,this.Gd,this.A,this.Ic,this.wd,this.Qe,this.A,this.Id,this.vd,this.Dd,this.A,this.Vc,this.Nc,this.A,this.A,this.Wc,this.Pc,this.Zc,this.A,this.qd,this.Mc,this.ad,this.A,this.Uc,this.Jc,this.Xc,this.A,this.Ac,this.Oc,
this.A,this.A,this.A,this.Qc,this.$c,this.A,this.Gc,this.Lc,this.A,this.A,this.A,this.Kc,this.Yc,this.A,this.Sc,this.Db,this.A,this.A,this.Tc,this.Fb,this.nd,this.A,this.pd,this.Cb,this.Rd,this.A,this.Rc,this.zb,this.ld,this.A,this.wc,this.Eb,this.A,this.A,this.A,this.Gb,this.od,this.A,this.ye,this.Bb,this.A,this.A,this.A,this.Ab,this.md,this.A];this.lb=[7,6,0,0,0,3,5,0,3,2,2,0,0,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,3,6,0,0,3,3,5,0,4,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,
3,2,2,0,3,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,6,6,0,0,0,3,5,0,4,2,2,0,5,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,0,6,0,0,3,3,3,0,2,0,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,0,4,0,0,2,6,2,0,3,3,3,0,2,2,2,0,4,4,4,0,2,5,0,0,4,4,4,0,2,4,2,0,4,4,4,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0,2,6,0,0,3,3,5,0,2,2,2,0,4,4,6,0,2,5,0,0,0,4,6,0,2,4,0,0,0,4,7,0]}v(lb,H);g=lb.prototype;
g.reset=function(a){this.J.ta&&this.ga();mb(this);this.j=this.g[65532]|this.g[65533]<<8;this.J.error=!1;this.C?this.C.reset():a&&(!0===this.Za||null===this.Za&&!this.C&&void 0===this.M.run)&&this.Aa()};
g.Y=function(a,b,c){a=!1;switch(b){case "run":this.M[b]=c;c.onclick=function(d){return function(){d.J.ta?d.ga():d.Aa()}}(this);a=!0;break;case "A":case "X":case "Y":case "S":case "PC":case "C":case "Z":case "I":case "D":case "B":case "V":case "N":case "speed":this.M[b]=c;a=!0;break;case "setSpeed":this.M[b]=c,c.onclick=function(d){return function(){nb(d,2<=d.speed?d.Xa:d.speed+1,!0)}}(this),a=!0}return a};
g.ha=function(a,b,c){this.g=a;this.P=b;this.xa=c-b+1;this.La=this.P+this.xa;this.P?B(1099511627776,"unsupported CPU address buffer offset ("+this.P+")"):this.Z()};g.oa=function(a,b){if(a&&!this.J.U){this.aa=b;(this.C=R(b,"debugger"))&&this.C.u("Type ? for list of debugger commands\n\n");if(a=R(b,"video"))this.eb=function(c){return function(){ob(c)}}(a),this.ia=function(c){return function(){c.ia()}}(a);this.J.U=!0;this.reset(!0);this.update()}};
function pb(a,b,c,d,e){0>qb(a.T,b,c,d,e)&&(a.va>b&&(a.va=b),a.wa<c&&(a.wa=c),a.T.push([b,c,d,e]))}function rb(a,b,c){for(var d=0;d<a.T.length;d++)b>=a.T[d][0]&&b<=a.T[d][1]&&a.T[d][3].call(a.T[d][2],b,c)}function sb(a,b,c,d,e){0>qb(a.N,b,c,d,e)&&(a.ma>b&&(a.ma=b),a.na<c&&(a.na=c),a.N.push([b,c,d,e]))}function tb(a,b,c){for(var d=0;d<a.N.length;d++)b>=a.N[d][0]&&b<=a.N[d][1]&&a.N[d][3].call(a.N[d][2],b,c)}
function qb(a,b,c,d,e){for(var f=0;f<a.length;f++)if(a[f][0]==b&&a[f][1]==c&&a[f][2]==d&&a[f][3]==e)return f;return-1}function nb(a,b,c){void 0!==b&&(a.speed=b,a.M.setSpeed&&(a.M.setSpeed.innerHTML=a.Ra[2<=b?0:b+1]),a.u("running at %s speed %s\n",a.Ra[b].toLowerCase(),a.mb[b]),c&&a.ia());a.ba=0;a.$a=Ya();ub(a)}g.eb=function(){};g.ia=function(){};function S(a,b,c,d){void 0!==a.M[b]&&(void 0===d&&(d=1),c="0000"+c.toString(16),a.M[b].innerHTML=c.slice(c.length-d).toUpperCase())}
function vb(a){S(a,"A",a.m,2);S(a,"X",a.G,2);S(a,"Y",a.K,2);var b=wb(a);S(a,"C",b&1?1:0);S(a,"Z",b&2?1:0);S(a,"I",b&4?1:0);S(a,"D",b&8?1:0);S(a,"B",b&16?1:0);S(a,"V",b&64?1:0);S(a,"N",b&128?1:0);S(a,"S",a.L,4);S(a,"PC",a.j,4);a.M.speed&&a.S&&(a.M.speed.innerHTML=a.S.toFixed(1)+"Mhz")}
function ub(a,b){var c=30;c<a.Ka&&(c=a.Ka);c<a.Ja&&(c=a.Ja);var d=1;b&&a.speed>a.Xa&&a.S&&(d=a.S);d>a.Na&&2>a.speed&&(d=a.Na);a.nb=Math.round(1E3/30);a.ra=Math.floor(1E6/c*d);a.ya=Math.floor(1E6/30*d);a.bb=Math.floor(1E6/a.Ka*d);a.ab=Math.floor(1E6/a.Ja*d);b||(a.W=a.ya,a.da=a.bb,a.ca=a.ab);a.Ha=0}
function xb(a){var b=Ya(),c=a.nb;a.ea&&(c=Math.round(c*a.ea/a.ya));c-=b-a.ob;if(b-=a.$a)a.S=Math.round(a.ba/(100*b))/10,864E5<=b&&nb(a);0>c?c=0:1==a.speed?a.S<=a.Na&&(c=0):2==a.speed&&(c=0);a.Ha+=a.ea;return c}
g.Aa=function(){if(hb(this,!0)){this.J.ta||(nb(this),this.aa&&this.aa.start(),this.J.ta=!0,this.M.run&&(this.M.run.innerHTML="Halt"),this.ia());1E6<=this.Ha&&ub(this,!0);this.ea=0;this.ob=Ya();try{do{this.step(this.ra);var a=this.R-this.I;this.ba+=a;this.ea+=a;this.R=this.I=0;this.da-=this.ra;0>=this.da&&(this.da+=this.bb,this.eb());this.ca-=this.ra;0>=this.ca&&(this.ca+=this.ab,vb(this));this.W-=this.ra;if(0>=this.W){this.W+=this.ya;break}}while(this.J.ta)}catch(b){this.ga();this.update();hb(this,
!1);fb(this,b.stack||b.message);return}setTimeout(function(b){return function(){b.Aa()}}(this),xb(this))}else this.update(),this.aa&&this.aa.stop(this.$a,this.ba)};
g.step=function(a){var b=!0;this.h=this.l=-1;var c;if(c=a&&this.C)c=this.C,c=0<c.ua.length||0<c.Ba.length||0<c.Da.length;this.R=this.I=a;do{a=this.g[this.j];var d;if(d=c){d=this.C;var e=a,f=!1;yb(d,this.j,d.ua,"exec")?f=!0:(d.R++,d.H[e][1]++,d.Ca[d.Qa++]=d.D.j,d.Qa>=d.Ca.length&&(d.Qa=0));d=!!f}if(d){b=void 0;this.ga();break}this.j++;this.v[a].call(this);if(0<=this.h){this.h>=this.va&&this.h<=this.wa&&rb(this,this.h,this.j);if(d=c)d=this.C,e=!1,yb(d,this.h,d.Ba,"read")&&(e=!0),d=!!e;if(d){b=!1;this.ga();
break}this.h=-1}else if(0<=this.l){this.l>=this.ma&&this.l<=this.na&&tb(this,this.l,this.j);if(d=c){d=this.C;e=this.l;f=this.g[this.l];var h=!1;(f&255)!=f&&(d.u("invalid value at %#06x: %s\n",e,f),h=!0);yb(d,e,d.Da,"write")&&(h=!0);d=!!h}if(d){b=!1;this.ga();break}this.l=-1}this.I-=this.lb[a]}while(0<this.I);return b};function zb(a){a.W=0;a.R-=a.I;a.I=0}g.ga=function(){gb(this,!0);this.R-=this.I;this.I=0;this.J.ta&&(this.J.ta=!1,this.M.run&&(this.M.run.innerHTML="Run"))};
g.update=function(){this.eb();vb(this)};function Ab(a){return a.J.ta?a.ba+a.R-a.I:0}g.X=function(a){return this.g[a]};function wb(a){var b=a.i&256?1:0;b|=a.s&255?0:2;b|=(a.B&255^a.F^a.B>>1)&128?64:0;b|=a.o&128?128:0;return a.H&60|b}function Bb(a){a.H|=8;a.v[97]=a.cc;a.v[101]=a.ec;a.v[105]=a.bc;a.v[109]=a.Zb;a.v[113]=a.dc;a.v[117]=a.fc;a.v[121]=a.ac;a.v[125]=a.$b;a.v[225]=a.te;a.v[229]=a.ve;a.v[233]=a.se;a.v[237]=a.pe;a.v[241]=a.ue;a.v[245]=a.we;a.v[249]=a.re;a.v[253]=a.qe}
function Cb(a){a.H&=-9;a.v[97]=a.vb;a.v[101]=a.xb;a.v[105]=a.ub;a.v[109]=a.rb;a.v[113]=a.wb;a.v[117]=a.yb;a.v[121]=a.tb;a.v[125]=a.sb;a.v[225]=a.Db;a.v[229]=a.Fb;a.v[233]=a.Cb;a.v[237]=a.zb;a.v[241]=a.Eb;a.v[245]=a.Gb;a.v[249]=a.Bb;a.v[253]=a.Ab}function T(a,b,c){var d=a.i&256?1:0,e=(b&15)+(c&15)+d;10<=e&&(e=e+6&15|16);e+=(b&240)+(c&240);a.F=b^c;a.B=e;a.o=e&255;160<=e&&(e+=96);512<=e&&(e-=256);a.i=e;a.s=b+c+d&255;a.I--;return e&255}
function U(a,b,c){var d=a.i&256?0:1,e=(b&15)-(c&15)-d;0>e&&(e=(e-6&15)-16);e+=(b&240)-(c&240);0>e&&(e-=96);a.o=a.s=(a.i=b-c-d)&255;a.F=b^c;a.B=a.i;a.i^=256;a.I--;return e&255}function mb(a){a.m=0;a.G=0;a.K=0;a.L=256;a.H=0;a.o=0;a.s=0;a.F=0;a.B=0;a.i=0;a.j=0;a.h=-1;a.l=-1;a.S=0;a.ba=a.R=a.I=0}
g.Cc=function(){this.j++;this.g[this.L--]=this.j>>8;this.L|=256;this.g[this.L--]=this.j&255;this.L|=256;this.H|=16;this.H=wb(this);this.g[this.L--]=this.H;this.L|=256;this.H&=239;this.h=65534;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.Wd=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m|=this.g[this.h]};g.Yd=function(){this.h=this.g[this.j++];this.o=this.s=this.m|=this.g[this.h]};
g.sc=function(){this.l=this.g[this.j++];this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.ae=function(){this.H=wb(this);this.g[this.L--]=this.H;this.L|=256};g.Vd=function(){this.h=this.j++;this.o=this.s=this.m|=this.g[this.h]};g.rc=function(){this.i=this.m<<1;this.o=this.s=this.m=this.i&255};g.Sd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m|=this.g[this.h]};
g.pc=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.Bc=function(){this.j+=(this.o&128?0:(this.I--,this.g[this.j]<<24>>24))+1};g.Xd=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m|=this.g[this.h]};g.Zd=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m|=this.g[this.h]};
g.tc=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};g.Fc=function(){this.i=0};g.Ud=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m|=this.g[this.h]};g.Td=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m|=this.g[this.h]};g.qc=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.g[this.l]<<1;this.o=this.s=this.g[this.l]=this.i&255};
g.td=function(){this.h=this.j++;this.g[this.L--]=this.j>>8;this.L|=256;this.g[this.L--]=this.j&255;this.L|=256;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.lc=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m&=this.g[this.h]};g.yc=function(){this.h=this.g[this.j++];this.s=this.m&this.g[this.h];this.o=this.o&127|this.g[this.h]&128;this.B=0;this.F=this.g[this.h]&64?128:0};g.nc=function(){this.h=this.g[this.j++];this.o=this.s=this.m&=this.g[this.h]};
g.ge=function(){this.l=this.g[this.j++];this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.ce=function(){this.L=this.L+1&255|256;this.H=this.g[this.L];this.i=this.H&1?256:0;this.s=this.H&2?0:1;this.o=this.H&128;this.B=0;this.F=this.H&64?128:0};g.kc=function(){this.h=this.j++;this.o=this.s=this.m&=this.g[this.h]};
g.fe=function(){this.i=this.i&65280|this.m;this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.m=this.i&255};g.xc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.s=this.m&this.g[this.h];this.o=this.o&127|this.g[this.h]&128;this.B=0;this.F=this.g[this.h]&64?128:0};g.hc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m&=this.g[this.h]};
g.de=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.zc=function(){this.j+=(this.o&128?(this.I--,this.g[this.j]<<24>>24):0)+1};g.mc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m&=this.g[this.h]};g.oc=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m&=this.g[this.h]};
g.he=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.xe=function(){this.i=256};g.jc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m&=this.g[this.h]};g.ic=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m&=this.g[this.h]};
g.ee=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65280|this.g[this.l];this.i<<=1;this.i=this.i&65534|(this.i&512?1:0);this.o=this.s=this.g[this.l]=this.i&255};g.ne=function(){this.L=this.L+1&255|256;this.H=this.g[this.L];this.i=this.H&1?256:0;this.s=this.H&2?0:1;this.o=this.H&128;this.B=0;this.F=this.H&64?128:0;this.L=this.L+2&255|256;this.j=this.g[this.L-1|256]|this.g[this.L]<<8};
g.gd=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m^=this.g[this.h]};g.jd=function(){this.h=this.g[this.j++];this.o=this.s=this.m^=this.g[this.h]};g.Pd=function(){this.l=this.g[this.j++];this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};g.$d=function(){this.g[this.L--]=this.m;this.L|=256};g.fd=function(){this.h=this.j++;this.o=this.s=this.m^=this.g[this.h]};
g.Od=function(){this.i=this.i&65279|(this.m&1?256:0);this.m=(this.i=this.i&65280|this.m>>1)&255;this.o=this.s=this.i&255};g.sd=function(){this.h=this.j;this.j=this.g[this.h]|this.g[this.h+1]<<8};g.cd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m^=this.g[this.h]};g.Md=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.Dc=function(){this.j+=((this.B&255^this.F^this.B>>1)&128?0:(this.I--,this.g[this.j]<<24>>24))+1};g.hd=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m^=this.g[this.h]};g.kd=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m^=this.g[this.h]};g.Qd=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.Hc=function(){this.H&=251};g.ed=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m^=this.g[this.h]};g.dd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m^=this.g[this.h]};g.Nd=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65279|(this.g[this.l]&1?256:0);this.g[this.l]=(this.i=this.i&65280|this.g[this.l]>>1)&255;this.o=this.s=this.i&255};
g.oe=function(){this.L=this.L+2&255|256;this.j=(this.g[this.L-1|256]|this.g[this.L]<<8)+1};g.vb=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.cc=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.m=T(this,this.m,this.g[this.h])};
g.xb=function(){this.h=this.g[this.j++];this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.ec=function(){this.h=this.g[this.j++];this.m=T(this,this.m,this.g[this.h])};g.le=function(){this.l=this.g[this.j++];this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.be=function(){this.L=this.L+1&255|256;this.o=this.s=this.m=this.g[this.L]};
g.ub=function(){this.h=this.j++;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.bc=function(){this.h=this.j++;this.m=T(this,this.m,this.g[this.h])};g.ke=function(){this.i=this.i&65280|this.m;this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.m=this.i&255};g.rd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.j=this.g[this.h]|this.g[this.h+1]<<8};
g.rb=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.Zb=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.m=T(this,this.m,this.g[this.h])};g.ie=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};
g.Ec=function(){this.j+=((this.B&255^this.F^this.B>>1)&128?(this.I--,this.g[this.j]<<24>>24):0)+1};g.wb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.dc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.m=T(this,this.m,this.g[this.h])};
g.yb=function(){this.h=this.g[this.j++]+this.G&255;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.fc=function(){this.h=this.g[this.j++]+this.G&255;this.m=T(this,this.m,this.g[this.h])};g.me=function(){this.l=this.g[this.j++]+this.G&255;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.ze=function(){this.H|=4};
g.tb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};g.ac=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.m=T(this,this.m,this.g[this.h])};g.sb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.m+this.g[this.h]+(this.i&256?1:0);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255};
g.$b=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.m=T(this,this.m,this.g[this.h])};g.je=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.i&65280|this.g[this.l];this.i=this.i&65023|(this.i&1?512:0);this.i>>=1;this.o=this.s=this.g[this.l]=this.i&255};g.De=function(){this.l=this.g[this.j++]+this.G&255;this.l=this.g[this.l]|this.g[this.l+1]<<8;this.g[this.l]=this.m};g.Le=function(){this.l=this.g[this.j++];this.g[this.l]=this.K};
g.Fe=function(){this.l=this.g[this.j++];this.g[this.l]=this.m};g.Ie=function(){this.l=this.g[this.j++];this.g[this.l]=this.G};g.bd=function(){this.o=this.s=this.K=this.K-1&255};g.Re=function(){this.o=this.s=this.m=this.G};g.Ke=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.K};g.Ae=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.m};g.He=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.g[this.l]=this.G};
g.uc=function(){this.j+=(this.i&256?0:(this.I--,this.g[this.j]<<24>>24))+1};g.Ee=function(){this.l=this.g[this.j++];this.l=(this.g[this.l]|this.g[this.l+1]<<8)+this.K;this.g[this.l]=this.m};g.Me=function(){this.l=this.g[this.j++]+this.G&255;this.g[this.l]=this.K};g.Ge=function(){this.l=this.g[this.j++]+this.G&255;this.g[this.l]=this.m};g.Je=function(){this.l=this.g[this.j++]+this.K&255;this.g[this.l]=this.G};g.Te=function(){this.o=this.s=this.m=this.K};
g.Ce=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.g[this.l]=this.m};g.Se=function(){this.L=this.G|256};g.Be=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.g[this.l]=this.m};g.Jd=function(){this.h=this.j++;this.o=this.s=this.K=this.g[this.h]};g.yd=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.m=this.g[this.h]};g.Ed=function(){this.h=this.j++;this.o=this.s=this.G=this.g[this.h]};
g.Kd=function(){this.h=this.g[this.j++];this.o=this.s=this.K=this.g[this.h]};g.Ad=function(){this.h=this.g[this.j++];this.o=this.s=this.m=this.g[this.h]};g.Fd=function(){this.h=this.g[this.j++];this.o=this.s=this.G=this.g[this.h]};g.Pe=function(){this.o=this.s=this.K=this.m};g.xd=function(){this.h=this.j++;this.o=this.s=this.m=this.g[this.h]};g.Oe=function(){this.o=this.s=this.G=this.m};g.Hd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.K=this.g[this.h]};
g.ud=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.m=this.g[this.h]};g.Cd=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.G=this.g[this.h]};g.vc=function(){this.j+=(this.i&256?(this.I--,this.g[this.j]<<24>>24):0)+1};g.zd=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.m=this.g[this.h]};g.Ld=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.K=this.g[this.h]};
g.Bd=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.m=this.g[this.h]};g.Gd=function(){this.h=this.g[this.j++]+this.K&255;this.o=this.s=this.G=this.g[this.h]};g.Ic=function(){this.F=this.B=0};g.wd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.m=this.g[this.h]};g.Qe=function(){this.o=this.s=this.G=this.L&255};g.Id=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.K=this.g[this.h]};
g.vd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.m=this.g[this.h]};g.Dd=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.G=this.g[this.h]};g.Vc=function(){this.h=this.j++;this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.Nc=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};
g.Wc=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.Pc=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Zc=function(){this.l=this.g[this.j++];this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.qd=function(){this.o=this.s=this.K=this.K+1&255};g.Mc=function(){this.h=this.j++;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.ad=function(){this.o=this.s=this.G=this.G-1&255};
g.Uc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.K-this.g[this.h];this.i^=256};g.Jc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Xc=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.Ac=function(){this.j+=(this.s&255?(this.I--,this.g[this.j]<<24>>24):0)+1};
g.Oc=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Qc=function(){this.h=this.g[this.j++]+this.G&255;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.$c=function(){this.l=this.g[this.j++]+this.G&255;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.Gc=function(){Cb(this)};
g.Lc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Kc=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.i=this.m-this.g[this.h];this.i^=256};g.Yc=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.g[this.l]=this.g[this.l]-1&255};g.Sc=function(){this.h=this.j++;this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.Db=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.te=function(){this.h=this.g[this.j++]+this.G&255;this.h=this.g[this.h]|this.g[this.h+1]<<8;this.m=U(this,this.m,this.g[this.h])};g.Tc=function(){this.h=this.g[this.j++];this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.Fb=function(){this.h=this.g[this.j++];this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.ve=function(){this.h=this.g[this.j++];this.m=U(this,this.m,this.g[this.h])};g.nd=function(){this.l=this.g[this.j++];this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.pd=function(){this.o=this.s=this.G=this.G+1&255};
g.Cb=function(){this.h=this.j++;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.se=function(){this.h=this.j++;this.m=U(this,this.m,this.g[this.h])};g.Rd=function(){};g.Rc=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.i=this.G-this.g[this.h];this.i^=256};
g.zb=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.pe=function(){this.h=this.g[this.j++]|this.g[this.j++]<<8;this.m=U(this,this.m,this.g[this.h])};g.ld=function(){this.l=this.g[this.j++]|this.g[this.j++]<<8;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.wc=function(){this.j+=(this.s&255?0:(this.I--,this.g[this.j]<<24>>24))+1};
g.Eb=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.ue=function(){this.h=this.g[this.j++];this.h=(this.g[this.h]|this.g[this.h+1]<<8)+this.K;this.m=U(this,this.m,this.g[this.h])};
g.Gb=function(){this.h=this.g[this.j++]+this.G&255;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.we=function(){this.h=this.g[this.j++]+this.G&255;this.m=U(this,this.m,this.g[this.h])};g.od=function(){this.l=this.g[this.j++]+this.G&255;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};g.ye=function(){Bb(this)};
g.Bb=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.re=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.K;this.m=U(this,this.m,this.g[this.h])};
g.Ab=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.i=this.m-this.g[this.h]-(this.i&256?0:1);this.F=this.m^this.g[this.h];this.B=this.i;this.o=this.s=this.m=this.i&255;this.i^=256};g.qe=function(){this.h=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.m=U(this,this.m,this.g[this.h])};g.md=function(){this.l=(this.g[this.j++]|this.g[this.j++]<<8)+this.G;this.o=this.s=this.g[this.l]=this.g[this.l]+1&255};
g.Ne=function(){var a=this.g[this.j++];switch(a){case 0:this.u("HALT\n");this.ga();break;case 1:a=this.j;for(var b="";a<this.g.length;){var c=this.g[a++];if(!c)break;b+=String.fromCharCode(c)}this.j=a;b=b.replace(/%A/g,z(this.m,2)).replace(/%X/g,z(this.G,2)).replace(/%Y/g,z(this.K,2));this.u("%s\n",b);zb(this);break;default:this.j-=2,this.u("undefined opSim: %#04x at %#06x\n",a,this.j),this.ga()}};g.A=function(){var a=this.g[--this.j];this.u("undefined opcode: %#04x at %#06x\n",a,this.j);this.ga()};
D(function(){for(var a=M("c1p","cpu"),b=0;b<a.length;b++){var c=a[b],d=N(c);d=new lb(d);I(d,c)}});function Db(a){H.call(this,"C1PROM",a);this.h=this.g=null;this.l=+a.size;if(this.v=a.file||a.image){a=this.v;var b=Ca(this.v);"json"!=b&&"hex"!=b&&(a=Ja()+"/api/v1/dump?file="+this.v+"&format=bytes");var c=this;A(a,function(d,e,f){Eb(c,d,e,f)})}else this.Z()}v(Db,H);
Db.prototype.ha=function(a,b,c,d){this.g=a;this.B=b;a=c-b+1;this.l||(this.l=a);a!=this.l?fb(this,"computer-specified ROM size ("+z(a,4,!0)+") does not match component-specified size ("+z(this.l,4,!0)+")"):(d&&(this.D=d,sb(d,b,c,this,this.F)),Fb(this))};Db.prototype.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.C=R(b,"debugger"))};Db.prototype.F=function(a,b){void 0!==b&&(this.C&&W(this.C,this,a,b,this.C.Hb,!0),a-=this.B,this.g[this.B+a]=this.h?this.h[a]:0)};
function Eb(a,b,c,d){if(d)a.u('Error loading ROM "%s" (%d)\n',b,d);else{if("["==c.charAt(0)||"{"==c.charAt(0))try{var e=eval("("+c+")"),f=e.bytes;a.h=f?f:e}catch(h){a.u('Error processing ROM "%s": %s\n',b,h.message);return}else for(b=c.replace(/\n/gm," ").replace(/ +$/,"").split(" "),a.h=Array(b.length),c=0;c<b.length;c++)a.h[c]=parseInt(b[c],16);Fb(a)}}
function Fb(a){if(!O(a))if(!a.v)a.Z();else if(a.h&&a.g){var b=a.h.length;if(b!=a.l)fb(a,"ROM image size ("+z(b,4,!0)+") does not match component-specified size ("+z(a.l,4,!0)+")");else{for(var c=0;c<b;c++)a.g[a.B+c]=a.h[c];a.Z()}}}D(function(){for(var a=M("c1p","rom"),b=0;b<a.length;b++){var c=a[b],d=N(c);d=new Db(d);I(d,c)}});function Gb(a){H.call(this,"C1PRAM",a)}v(Gb,H);Gb.prototype.ha=function(a){this.g=a;this.Z()};
D(function(){for(var a=M("c1p","ram"),b=0;b<a.length;b++){var c=a[b],d=N(c);d=new Gb(d);I(d,c)}});
function Hb(a){H.call(this,"C1PKeyboard",a);this.J.U=!1;this.mb=a.model;this.va=8;this.ob=10;this.nb=13;this.wa=27;this.bb=this.va;this.lb=this.ob;this.Za=this.nb;this.na=this.wa;this.F=224;this.l=16+this.F;this.T=17+this.F;this.W=18+this.F;this.ra=20+this.F;this.ma=this.F;this.$a=3;this.ab=15;this.R=1;this.N={};this.N["break"]=this.ma;this.N.esc=this.na;this.N["ctrl-c"]=this.$a;this.N["ctrl-o"]=this.ab;this.h=[];this.h[49]=30464;this.h[33]=30464+this.l;this.h[50]=30208;this.h[34]=30208+this.l;this.h[51]=
29952;this.h[35]=29952+this.l;this.h[52]=29696;this.h[36]=29696+this.l;this.h[53]=29440;this.h[37]=29440+this.l;this.h[54]=29184;this.h[38]=29184+this.l;this.h[55]=28928;this.h[39]=28928+this.l;this.h[56]=26368;this.h[40]=26368+this.l;this.h[57]=26112;this.h[41]=26112+this.l;this.h[48]=25856;this.h[58]=25600;this.h[42]=25600+this.l;this.h[45]=25344;this.h[61]=25344+this.l;this.h[46]=22272;this.h[62]=22272+this.l;this.h[108]=22016;this.h[76]=22016+this.l;this.h[92]=22016+this.l;this.h[111]=21760;this.h[79]=
21760+this.l;this.h[this.bb]=21760+this.l;this.h[this.lb]=21504;this.h[this.Za]=21248;this.h[119]=18176;this.h[87]=18176+this.l;this.h[101]=17920;this.h[69]=17920+this.l;this.h[114]=17664;this.h[82]=17664+this.l;this.h[116]=17408;this.h[84]=17408+this.l;this.h[121]=17152;this.h[89]=17152+this.l;this.h[117]=16896;this.h[85]=16896+this.l;this.h[105]=16640;this.h[73]=16640+this.l;this.h[115]=14080;this.h[83]=14080+this.l;this.h[100]=13824;this.h[68]=13824+this.l;this.h[102]=13568;this.h[70]=13568+this.l;
this.h[103]=13312;this.h[71]=13312+this.l;this.h[104]=13056;this.h[72]=13056+this.l;this.h[106]=12800;this.h[74]=12800+this.l;this.h[107]=12544;this.h[75]=12544+this.l;this.h[91]=12544+this.l;this.h[120]=9984;this.h[88]=9984+this.l;this.h[99]=9728;this.h[67]=9728+this.l;this.h[118]=9472;this.h[86]=9472+this.l;this.h[98]=9216;this.h[66]=9216+this.l;this.h[110]=8960;this.h[78]=8960+this.l;this.h[94]=8960+this.l;this.h[109]=8704;this.h[77]=8704+this.l;this.h[93]=8704+this.l;this.h[44]=8448;this.h[60]=
8448+this.l;this.h[113]=5888;this.h[81]=5888+this.l;this.h[97]=5632;this.h[65]=5632+this.l;this.h[122]=5376;this.h[90]=5376+this.l;this.h[32]=5120;this.h[47]=4864;this.h[63]=4864+this.l;this.h[59]=4608;this.h[43]=4608+this.l;this.h[112]=4352;this.h[80]=4352+this.l;this.h[64]=4352+this.l;this.h[this.T]=1536;this.h[this.na]=1280;this.h[this.l]=512;this.h[this.W]=256;this.h[this.ra]=0;this.reset()}v(Hb,H);g=Hb.prototype;
g.reset=function(){this.Sa(this.mb);this.v=this.R;this.ya=0;this.B=[this.R,0,0,0,0,0,0,0];this.ba=[];if(this.H)for(var a in this.H)isNaN(+a)||this.H[a]&&clearTimeout(this.H[a]);this.H=[];this.Ra=this.I=0;this.Ha=-1;this.xa=this.B;this.Ja=this.ea=0;this.P=""};
g.Y=function(a,b,c){if(void 0===this.M[b])switch(b){case "keyDown":return this.M[b]=c,c.onkeydown=function(d){return function(e){return Ib(d,e,!0)}}(this),!0;case "keyPress":return this.M[b]=c,c.onkeypress=function(d){return function(e){var f=!0;e=e||window.event;e=e.which||e.keyCode;d.P="";d.v&8?d.v&=-9:f=!Jb(d,e);d.C&&Q(d.C,d.C.Ea)&&d.C.u("keyPress(%#04x): %s\n",e,f?"pass":"consume");return f}}(this),!0;case "keyUp":return this.M[b]=c,c.onkeyup=function(d){return function(e){return Ib(d,e,!1)}}(this),
!0;case "break":return this.M[b]=c,c.onclick=function(d){return function(){d.aa&&d.aa.reset(!0)}}(this),!0;default:if(void 0!==this.N[b])return this.M[b]=c,c.onclick=function(d,e,f){return function(){d.D&&d.D.ia();return!Jb(d,f)}}(this,b,this.N[b]),!0}return!1};g.ha=function(a,b,c,d){this.g=a;this.Ka=b;this.Ob=c-b+1;this.Qb=this.Ka+this.Ob;d&&(this.D=d,sb(d,b,c,this,this.Rb));this.Z()};g.Sa=function(a){this.S=a;this.ca=255;600!=this.S&&(this.ca=0,this.u("updated keyboard model: %d\n",this.S))};
g.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.aa=b,this.C=R(b,"debugger"))};g.Z=function(){this.da=(this.Pb=C("iOS"))||C("Android");this.C&&Q(this.C,this.C.Ea)&&this.C.u("mobile keyboard support: %b (%s)\n",this.da,window.navigator.userAgent);H.prototype.Z.call(this)};function Kb(a,b){b=b?100:250;a.D&&a.D.S&&(b/=a.D.S);return b}function Lb(a,b){!a.I||void 0!==b&&b==a.I||(a.C&&Q(a.C,a.C.Ea)&&a.C.u("autoClear(%#04x)\n",a.I),clearTimeout(a.H[a.I]),Mb(a,a.I,!1,4))}
function Nb(a,b,c){a.P=b;Ob(a,c||300)}function Ob(a,b){if(0<a.P.length){var c=a.P.charCodeAt(0);10==c&&(c=13);65<=c&&90>=c&&(c+=32);a.P=a.P.substr(1);Jb(a,c)}0<a.P.length&&setTimeout(function(d){return function(){Ob(d,b)}}(a),b)}
function Ib(a,b,c){var d=!c;b=b.keyCode;c&&(a.Ra=b);if(b==a.l-a.F)a.v&=-5,c&&(a.v|=4),b+=a.F,d=!1;else if(b==a.W-a.F)a.v&=-3,c&&(a.v|=2),b+=a.F,d=!1;else if(b==a.T-a.F)a.v&=-65,c&&(a.v|=64),b+=a.F,d=!1;else if(b==a.ra-a.F)c=!c,a.v&=~a.R,c&&(a.v|=a.R),b+=a.F,d=!1;else if(91==b){a.v&=-9;c&&(a.v|=8);d=!1;var e=!0}else e=9==b?d=!1:b==a.wa||b==a.va?c?!Jb(a,b):!1:!0;d&&(a.v&=-9,a.da||b!=a.Ra||Lb(a));void 0===e&&(e=!Mb(a,b,c,2));a.C&&Q(a.C,a.C.Ea)&&a.C.u("key%s(%#04x): %s\n",c?"Down":"Up",b,e?"pass":"consume");
return e}function Jb(a,b){var c=!1;b==a.ma?a.aa&&(a.aa.reset(!0),c=!0):(a.da&&65<=b&&90>=b&&(b+=32),Lb(a,b),Mb(a,b,!0,0)&&(2==a.D.speed?Mb(a,b,!1,1):(c=!1,a.H[b]&&(clearTimeout(a.H[b]),c=!0),c=Kb(a,c),a.H[a.I=b]=setTimeout(function(d){return function(){Mb(d,b,!1,3)}}(a),c),a.C&&Q(a.C,a.C.Ea)&&a.C.u("keyPressSimulate(%#04x): setTimeout()\n",b)),c=!0));a.C&&Q(a.C,a.C.Ea)&&a.C.u("keyPressSimulate(%#04x): %b\n",b,c);return c}
function Mb(a,b,c,d){var e=!1;c||(a.H[b]=null,a.I==b&&(a.I=0));var f=0,h=a.h[b];void 0===h&&(1<=b&&26>=b&&(b+=64,f=a.T),h=a.h[b]);void 0!==h&&(b=h>>12,e=h>>8&15,f||(f=h&255),c?(a.B[b]|=1<<e,a.B[0]=f==a.T?a.B[0]|64:f==a.l?a.B[0]|4:f==a.W?a.B[0]|2:a.B[0]&-71):(a.B[b]&=~(1<<e),a.B[0]&=-71,a.B[0]|=a.v&70),c=0==d&&!a.ba.length,a.ba.push(a.B.slice()),Pb(a,c),e=!0);return e}g.X=function(){};g.Rb=function(a){this.ya=this.D.X(a)^this.ca;this.ea++;Pb(this,!1,a)};
function Pb(a,b,c){var d=Ab(a.D);b||(2==a.D.speed?b=void 0!==c&&32<=a.ea:(b=d-a.Ja,b=0>b||8192<=b));b&&(b=a.ba.shift(),void 0!==b&&(a.xa=b),a.ea=0,a.Ja=d);for(b=d=0;8>b;b++)a.ya&1<<b&&(d|=a.xa[b]);d^=a.ca;if(void 0!==c)a.g[c]=d;else if(c=a.Ka,d!=a.Ha)for(;c<a.Qb;c++)a.g[c]=d;a.Ha=d}D(function(){for(var a=M("c1p","keyboard"),b=0;b<a.length;b++){var c=a[b],d=N(c);d=new Hb(d);I(d,c)}});
function Qb(a,b,c,d){H.call(this,"C1PVideo",a);this.ra=a.model;this.ea=a.charCols;this.ma=a.charRows;this.wa=a.screenWidth;this.xa=a.screenHeight;this.H=a.charWidth;this.I=a.charHeight;Rb(this);this.F=b;this.T=c;this.v=d;b=["","moz","ms","webkit"];a=a.smoothing;(c=La("smoothing"))&&(a="true"==c);if(null!=a)for(c=0;c<b.length;c++)if(d=(d=b[c])?d+"ImageSmoothingEnabled":"imageSmoothingEnabled",void 0!==this.T[d]){this.T[d]=a;break}}v(Qb,H);g=Qb.prototype;
g.reset=function(a){this.Sa(this.ra);if(this.g)for(var b=this.N;b<this.W;b++)this.g[b]=a?Math.floor(256*Math.random()):32};g.Y=function(a,b,c){switch(b){case "refresh":return this.M[b]=c,c.onclick=function(d){return function(){Sb(d);ob(d)}}(this),!0}return!1};g.ha=function(a,b,c,d){this.g=a;this.N=b;this.va=c-b+1;this.W=this.N+this.va;d&&(this.D=d,pb(d,56832,56832,this,this.X),sb(d,56832,56832,this,this.Sb));this.reset(!0)};
function Rb(a,b,c,d,e){a.P=void 0!==b?b:a.ea;a.ya=void 0!==c?c:a.ma;a.l=a.P*a.ya;a.W=a.N+a.l;a.da=void 0!==d?d:0;a.na=void 0!==e?e:c;a.ba=Math.floor(a.wa/a.P);a.ca=Math.floor(a.xa/a.na)}g.ia=function(){this.F.focus()};g.Sa=function(a){this.S=a;600==this.S?(Rb(this,this.ea,this.ma,3,25),1024==this.l&&this.D&&(this.B=this.W+this.l-1,sb(this.D,this.B,this.B,this,this.Kb))):(this.u("updated video model: %d\n",this.S),Rb(this,64,32));Sb(this);ob(this)};
g.oa=function(a,b){if(a&&!this.J.U&&O(this)){if(this.J.U=!0,this.C=R(b,"debugger"),this.h=R(b,"keyboard"))this.h.Y("canvas","keyDown",this.F),this.h.Y("canvas","keyPress",this.F),this.h.Y("canvas","keyUp",this.F)}else!a&&this.J.U&&(this.J.U=!1)};g.Z=function(){this.H||(this.H=Math.floor(this.v.width/16));this.I||(this.I=Math.floor(this.v.height/16));H.prototype.Z.call(this)};
g.X=function(a,b){var c=this.D.X(a);void 0!==b&&this.C&&W(this.C,this,a,b,this.C.fb);this.D.g[a]=c&127|(Math.floor(Ab(this.D)/8333)&1?128:0)};g.Sb=function(a,b){void 0!==b&&this.C&&W(this.C,this,a,b,this.C.fb)};
g.Kb=function(a,b){if(void 0!==b){this.C&&W(this.C,this,a,b,this.C.fb,!0);this.Sa(540);this.h&&this.h.Sa(542);a=this.D;b=a.N;var c=[],d=qb(b,this.B,this.B,this,this.Kb);if(0<=d){c.push(b[d][0]);c.push(b[d][1]);b.splice(d,1);var e=65536,f=0;for(d=0;d<b.length;d++)e>b[d][0]&&(e=b[d][0]),f<b[d][1]&&(f=b[d][1]);c.push(e);c.push(f)}4==c.length&&(a.ma=c[2],a.na=c[3])}};function Sb(a){a.R=Array(a.l);for(var b=0;b<=a.l;b++)a.R[b]=-1}
function ob(a){var b=0;if(a.J.U)for(;b<a.l;){var c=a.g[a.N+b];if(a.R[b]!=c){var d=Math.floor(b/a.P);if(d>=a.da&&(d-=a.da,d<a.na)){var e=c*a.H;a.T.drawImage(a.v,e%a.v.width,Math.floor(e/a.v.width)*a.I,a.H,a.I,b%a.P*a.ba,d*a.ca,a.ba,a.ca)}a.R[b]=c}b++}}
D(function(){for(var a=M("c1p","video"),b=0;b<a.length;b++){var c=a[b],d=N(c),e=M("pcjs-canvas","",c);if(e&&e.length)var f=e[0];else if(f=document.createElement("canvas"))f.setAttribute("class","pcjs-canvas"),f.setAttribute("width",d.screenWidth),f.setAttribute("height",d.screenHeight),f.style.backgroundColor=d.screenColor,f.style.height="auto",c.appendChild(f);if(!f||!f.getContext){c.innerHTML="<br>Missing &lt;canvas&gt; support. Please try a newer web browser.";break}f.setAttribute("contenteditable",
"true");f.setAttribute("autocapitalize","off");f.setAttribute("autocorrect","off");0<=(w.navigator?w.navigator.userAgent:"").indexOf("MSIE")&&(f.style.height=(c.clientWidth*d.screenHeight/d.screenWidth|0)+"px",c.onresize=function(k,l,n,p){return function(){l.style.height=(k.clientWidth*p/n|0)+"px"}}(c,f,d.screenWidth,d.screenHeight));e=new Image;var h=f.getContext("2d");f=new Qb(d,f,h,e);d=d.fontROM||d.charSet;e.onload=function(k){return function(){k.Z()}}(f,d);e.src=d;I(f,c)}});
function Tb(a){H.call(this,"C1PSerialPort",a);this.J.U=!1;this.F=a.demo;this.R='10 PRINT "HELLO OSI #'+eb(this)+'"\n';this.B=Ub;this.v=La("autoMount")||a.autoMount;if("string"==typeof this.v)try{this.v=eval("("+this.v+")")}catch(c){B(1099511627776,this.type+" auto-mount error: "+c.message+" ("+this.v+")"),this.v=null}if(a=this.v&&this.v.path){var b=this;this.F=!0;A(a,function(c,d,e){Vb(b,c,d,e);b.R=d;b.v=null;b.g&&b.Z()})}this.reset(!0)}v(Tb,H);
function Vb(a,b,c,d){if(c){a.I=0;a.l=c;a.P=!0;if(0<b.indexOf(".json"))try{d="";var e=eval("("+c+")").bytes;for(c=0;c<e.length;c++)d+=String.fromCharCode(e[c]);a.l=d;a.P=!1}catch(f){a.u('Error processing file "%s": %s\n',b,f.message);return}a.aa&&a.h&&a.D.J.ta?(a.u("auto-loading %s\n",b),a.F||Wb(a,!0)):a.u("%s ready to load\n",b)}else a.u('Error loading file "%s" (%d)\n',b,d)}g=Tb.prototype;g.reset=function(a){if(a||this.B!=Xb)this.H=-1,this.I=0,this.l="",this.F&&(this.l=this.R),this.P=!0,this.B=Ub};
g.start=function(){this.h&&this.F&&("."==this.l[0]?(this.F=!1,Wb(this)):(Nb(this.h," C\n\n",1E3),setTimeout(function(a){return function(){a.F=!1;Wb(a)}}(this),5E3)))};
g.Y=function(a,b,c){var d=this;switch(b){case "listSerial":return this.M[b]=c,!0;case "loadSerial":return this.M[b]=c,c.onclick=function(){d.M.listSerial&&A(d.M.listSerial.value,function(e,f,h){Vb(d,e,f,h)})},!0;case "mountSerial":return!Ka()&&window&&"FileReader"in window?(this.M[b]=c,c.onchange=function(){var e=c.children[0];e.children[1].disabled=!e.children[0].files.length},c.onsubmit=function(e){var f=e.currentTarget[1].files[0],h=new FileReader;h.onload=function(){Vb(d,f.name,h.result.toString(),
0)};h.readAsText(f);return!1}):c.parentNode.removeChild(c),!0}return!1};g.ha=function(a,b,c,d){this.g=a;this.N=b;this.T=c-b+1;this.S=this.N+this.T;if(this.D=d)pb(d,b,c,this,this.X),sb(d,b,c,this,this.Tb);this.v||this.Z()};g.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.aa=b,this.h=R(b,"keyboard"),this.C=R(b,"debugger"))};function Wb(a,b){a.l&&(a.D.ia(),"."!=a.l.charAt(0)?(a.B=Yb,Nb(a.h,"NEW\nLOAD\n")):(a.B=Xb,b&&a.aa.reset(!0),Nb(a.h,"ML")))}
g.X=function(a,b){void 0!==b&&(a&1?Zb(this):this.l&&!this.I&&Zb(this))};g.Tb=function(a,b){void 0!==b&&this.C&&W(this.C,this,a,b,this.C.We,!0)};function Zb(a){if(void 0!==a.l){a.H=-1;if(a.I<a.l.length){var b=a.l.charCodeAt(a.I++)&255;a.P&&10==b&&(b=13);a.H=b}else a.l="",a.I=0,a.B==Yb&&a.h&&Nb(a.h," \nRUN\n"),a.B=Ub;for(b=a.N+0;b<a.S;b+=2)a.g[b]=0<=a.H?$b:ac;for(b=a.N+1;b<a.S;b+=2)a.g[b]=0<=a.H?a.H:0}}var ac=0,$b=1,Ub=0,Yb=1,Xb=2;
D(function(){for(var a=M("c1p","serial"),b=0;b<a.length;b++){var c=a[b],d=N(c);d=new Tb(d);I(d,c)}});function bc(a){H.call(this,"C1PDiskController",a);this.J.U=!1;this.reset(!0)}v(bc,H);g=bc.prototype;g.reset=function(a){cc(this);this.h=-1;a&&(this.l=[],this.l[0]={Xe:0,qb:40,Xb:!0,Ia:20,sa:0,Ga:-1,Wa:[]})};
function cc(a){a.S={O:64,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c);b.H.O&4||X(b,0,this)}}(a)};a.v={O:255,read:function(){this.update()},update:function(b){return function(c){void 0===c?c=b.v.O:dc(b,c,b.F.O);c=(c|190)&-2;if(0<=b.h&&b.l[b.h].Wa.length){var d=b.l[b.h];d.Xb&&(c&=-33);d.sa||(c&=-3);10>=--d.Ia&&(0<d.Ia?(c&=-129,ec(b)):(d.Ia=100,0<=b.h&&(b.l[b.h].Ga=0,fc(b))))}this.O=c;b.H.O&4&&X(b,0,this)}}(a)};a.H={O:0,read:function(){},update:function(b){return function(c){void 0!==
c&&(this.O=c&-193);X(b,1,this);b.v.update();b.S.update()}}(a)};a.R={O:255,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c);b.I.O&4||X(b,2,this)}}(a)};a.F={O:255,read:function(){},update:function(b){return function(c){void 0===c?c=b.F.O:dc(b,b.v.O,c);if(0<=b.h&&b.h<b.l.length){var d=b.l[b.h];d.Wa.length&&b.F.O&8&&!(c&8)&&(c&4?d.sa--:d.sa++,b.C&&Q(b.C,b.C.Ma)&&b.C.u("stepping %s to track %d\n",c&4?"down":"up",d.sa),d.sa>=d.qb&&(d.sa=d.qb),0>d.sa&&(d.sa=0),d.Ia=20,b.v.update(b.v.O|
128),ec(b))}this.O=c;b.I.O&4&&X(b,2,this)}}(a)};a.I={O:0,read:function(){},update:function(b){return function(c){void 0!==c&&(this.O=c&-193);X(b,3,this);b.F.update();b.R.update()}}(a)};a.T={O:0,read:function(){},update:function(b){return function(c){void 0!==c&&(3==(c&3)&&(b.B.O=14),this.O=c);b.B.update()}}(a)};a.B={O:14,read:function(){},update:function(b){return function(c){void 0===c&&(c=b.B.O);c&=-2;0<=b.h&&0<=b.l[b.h].Ga&&(c|=1);this.O=c;X(b,16,this)}}(a)};a.N={O:0,read:function(b){return function(){fc(b)}}(a),
update:function(b){return function(c){void 0!==c&&(this.O=c);X(b,17,this)}}(a)};a.W={O:0,read:function(){},update:function(){return function(){}}(a)}}
g.Y=function(a,b,c){switch(b){case "listDisk":return this.M[b]=c,!0;case "loadDisk":return this.M[b]=c,c.onclick=function(d){return function(){if(d.M.listDisk){var e=d.M.listDisk.value,f=e;".json"!=e.substr(e.length-5)&&(f="http://"+window.location.host+"/api/v1/dump?disk="+e);d.u("loading  %s...\n",Ba(e));A(f,function(h,k,l){gc(d,h,k,l)})}}}(this),!0}return!1};g.ha=function(a,b,c,d){this.g=a;this.P=b;if(this.D=d)pb(d,b,c,this,this.X),sb(d,b,c,this,this.Ub);this.Z()};
g.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.C=R(b,"debugger"))};
function gc(a,b,c,d){if(d)a.u("disk load error (%d)\n",d);else{d=[];a.u("mounting %s...\n",b);try{if(d=eval("("+c+")"),d.length)if(d[0].length){var e=d[0];if(void 0===e[0].trackNum)a.u("data error: %d\n",e[0]);else if(a.l[0]){for(c=0;c<e.length;c++){var f,h=e[c],k=h.sectors;if(void 0===(f=h.trackNum)||void 0===k)throw Error("track "+c+" missing data");f!=c&&B(549755813888,"track "+f+" out of order (expected "+c+")");d=[];var l;if(f){hc(d,h,"trackSig");ic(d,h);jc(d,h,"trackType");for(var n=0;n<k.length;n++){var p=
k[n];var m=p.sectorData;jc(d,p,"sectorSig");jc(d,p,"sectorNum");jc(d,p,"sectorPages");for(l=0;l<m.length;l++)d.push(m[l]);hc(d,p,"sectorEndSig")}}else for(p=k[0],m=p.sectorData,jc(d,h,"trackLoad",2),jc(d,p,"sectorPages"),l=0;l<m.length;l++)d.push(m[l]);e[f].Jb=d;a.C&&Q(a.C,a.C.Ma)&&a.C.u("track %d: %d bytes\n",f,d.length)}a.l[0].Wa=e;a.u("mount of %s complete\n",b)}else a.u("no available drives\n")}else a.u("no tracks: %s\n",b);else a.u("no data: %s\n",b)}catch(q){a.u("disk data error: %s\n",q.message)}}}
function ic(a,b){b=b.trackNum;if(void 0===b)throw Error("missing bcd value: trackNum");a.push(Math.floor(b/10)<<4|b%10)}function jc(a,b,c,d){b=b[c];if(void 0===b)throw Error("missing binary value: "+c);2==d&&a.push(b>>8&255);a.push(b&255)}function hc(a,b,c){b=b[c];if(void 0===b)throw Error("missing signature: "+c);for(c=0;c<b.length;c++)a.push(b.charCodeAt(c))}
function kc(a,b,c){b&=63;16>b?b&=3:32>b&&(b&=17);switch(b){case 0:a=a.H.O&4?a.v:a.S;break;case 1:a=a.H;break;case 2:a=a.I.O&4?a.F:a.R;break;case 3:a=a.I;break;case 16:a=c?a.T:a.B;break;case 17:a=a.N;break;default:a=a.W}return a}g.X=function(a,b){if(void 0!==b){var c=kc(this,a-this.P,!1);this.C&&W(this.C,this,a,b,this.C.Ma,!1,c.Ib);c.read()}};
g.Ub=function(a,b){if(void 0!==b){var c=this.D.X(a),d=kc(this,a-this.P,!0);if(this.C&&Q(this.C,this.C.Ma|this.C.Hb)&&(W(this.C,this,a,b,this.C.Ma,!0,d.Ib),d.Vb))for(a=128,b=d.O^c;b&&a;)b&a&&this.C.u("  changed %s.%s to %s\n",d.Ib,d.Vb[a],c&a?"1":"0"),a>>=1;d.update(c)}};function dc(a,b,c){var d=-1;void 0!==b&&void 0!==c&&(d=0,c&32||(d|=2),a.v.O&64||(d|=1));a.h!=d&&(a.h=d,a.B.update())}function ec(a){0<=a.h&&(a.l[a.h].Ga=-1,a.N.update(255),a.B.update())}
function fc(a){if(0<=a.h){var b=a.l[a.h];var c=b.Wa[b.sa];void 0!==c&&(0<=b.Ga&&b.Ga<c.Jb.length?(b.Ia=100,b=c.Jb[b.Ga++],a.N.update(b),a.B.update()):(b.Ia=10,ec(a)))}}function X(a,b,c){a.D.g[b+a.P]=c.O}D(function(){for(var a=M("c1p","disk"),b=0;b<a.length;b++){var c=a[b],d=N(c);d=new bc(d);I(d,c)}});
function lc(a){H.call(this,"C1PDebugger",a);this.C=this;this.R=-1;this.za=0;this.kb=null;this.Ya=!1;this.la=0;this.ua=[];this.Ba=[];this.Da=[];this.Qa=0;this.Ca=[];this.H=[];this.Hb=1;this.Ea=16;this.fb=32;this.Ma=64;this.We=128;this.qa=this.da=0;this.Va={port:1,kbd:16,video:32,disk:64,serial:128};this.Ua=28;this.gb=56;this.Oa="ADC AND ASL BCC BCS BEQ BIT BMI BNE BPL BRK BVC BVS CLC CLD CLI CLV CMP CPX CPY DEC DEX DEY EOR INC INX INY JMP JSR LDA LDX LDY LSR NOP ORA PHA PHP PLA PLP ROL ROR RTI RTS SBC SEC SED SEI STA STX STY TAX TAY TSX TXA TXS TYA SIM .DB".split(" ");
this.ca=["HLT","MSG"];mc(this,!0);this.ka=[[10],[34,1,this.I],[this.gb,1],[],[],[34,1,this.h],[2,1,this.h],[],[36],[34,1,this.B],[2,0,this.T],[],[],[34,2,this.V],[2,2,this.V],[],[9,1,this.ja],[34,1,this.N],[],[],[],[34,1,this.l],[2,1,this.l],[],[13],[34,2,this.F],[],[],[],[34,2,this.v],[2,2,this.v],[],[this.Ua,2,this.Ta],[1,1,this.I],[],[],[6,1,this.h],[1,1,this.h],[39,1,this.h],[],[38],[1,1,this.B],[39,0,this.T],[],[6,2,this.V],[1,2,this.V],[39,2,this.V],[],[7,1,this.ja],[1,1,this.N],[],[],[],[1,
1,this.l],[39,1,this.l],[],[44],[1,2,this.F],[],[],[],[1,2,this.v],[39,2,this.v],[],[41],[23,1,this.I],[],[],[],[23,1,this.h],[32,1,this.h],[],[35],[23,1,this.B],[32,0,this.T],[],[27,2,this.Ta],[23,2,this.V],[32,2,this.V],[],[11,1,this.ja],[23,1,this.N],[],[],[],[23,1,this.l],[32,1,this.l],[],[15],[23,2,this.F],[],[],[],[23,2,this.v],[32,2,this.v],[],[42],[0,1,this.I],[],[],[],[0,1,this.h],[40,1,this.h],[],[37],[0,1,this.B],[40,0,this.T],[],[27,2,this.pb],[0,2,this.V],[40,2,this.V],[],[12,1,this.ja],
[0,1,this.N],[],[],[],[0,1,this.l],[40,1,this.l],[],[46],[0,2,this.F],[],[],[],[0,2,this.v],[40,2,this.v],[],[],[47,1,this.I],[],[],[49,1,this.h],[47,1,this.h],[48,1,this.h],[],[22],[],[53],[],[49,2,this.V],[47,2,this.V],[48,2,this.V],[],[3,1,this.ja],[47,1,this.N],[],[],[49,1,this.l],[47,1,this.l],[48,1,this.ba],[],[55],[47,2,this.F],[54],[],[],[47,2,this.v],[],[],[31,1,this.B],[29,1,this.I],[30,1,this.B],[],[31,1,this.h],[29,1,this.h],[30,1,this.h],[],[51],[29,1,this.B],[50],[],[31,2,this.V],[29,
2,this.V],[30,2,this.V],[],[4,1,this.ja],[29,1,this.N],[],[],[31,1,this.l],[29,1,this.l],[30,1,this.ba],[],[16],[29,2,this.F],[52],[],[31,2,this.v],[29,2,this.v],[30,2,this.F],[],[19,1,this.B],[17,1,this.I],[],[],[19,1,this.h],[17,1,this.h],[20,1,this.h],[],[26],[17,1,this.B],[21],[],[19,2,this.V],[17,2,this.V],[20,2,this.V],[],[8,1,this.ja],[17,1,this.N],[],[],[],[17,1,this.l],[20,1,this.l],[],[14],[17,2,this.F],[],[],[],[17,2,this.v],[20,2,this.v],[],[18,1,this.B],[43,1,this.I],[],[],[18,1,this.h],
[43,1,this.h],[24,1,this.h],[],[25],[43,1,this.B],[33],[],[18,2,this.V],[43,2,this.V],[24,2,this.V],[],[5,1,this.ja],[43,1,this.N],[],[],[],[43,1,this.l],[24,1,this.l],[],[45],[43,2,this.F],[],[],[],[43,2,this.v],[24,2,this.v],[]]}v(lc,H);g=lc.prototype;
g.Y=function(a,b,c){var d=this;switch(b){case "debugInput":return this.W=this.M[b]=c,this.W.focus(),c.onkeypress=function(e,f){return function(h){13==h.keyCode&&(b=f.value,f.value="",nc(e,b))}}(this,c),!0;case "debugEnter":return this.M[b]=c,Oa(c,function(){return d.W?(b=d.W.value,nc(d,b),!0):!1}),!0;case "step":return this.M[b]=c,Oa(c,function(e){var f=!1;gb(d,!0)||(hb(d,!0),f=d.step(e?1:0),hb(d,!1));return f}),!0}return!1};
g.ha=function(a,b,c){this.g=a;this.P=b;this.xa=c-b+1;this.La=this.P+this.xa;this.Z()};g.oa=function(a,b){a&&!this.J.U&&(this.J.U=!0,this.D=R(b,"cpu"))};g.ia=function(){this.W.focus()};
function mc(a,b){a.T=0;a.B=1;a.v=2;a.F=3;a.Ta=4;a.pb=5;a.l=6;a.ba=7;a.I=8;a.N=9;a.V=10;a.h=11;a.ja=a.Ta;var c="";if(b)for(a.pa="A #$nn $nnnn,X $nnnn,Y $nnnn ($nnnn) $nn,X $nn,Y ($nn,X) ($nn),Y $nnnn $nn".split(" "),b=0;b<a.pa.length;b++){var d=a.pa[b];c+="("+d.replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\$/g,"\\$")+"|)"}else for(a.pa="A nn [nnnn+X] [nnnn+Y] nnnn [nnnn] [nn+X] [nn+Y] [[nn+X]] [[nn]+Y] [nnnn] [nn]".split(" "),
b=0;b<a.pa.length;b++)d=a.pa[b],c+="("+d.replace(/\[/g,"\\[").replace(/]/g,"\\]").replace(/nnnn/g,"[0-9A-F][0-9A-F][0-9A-F][0-9A-F]?").replace(/nn/g,"[0-9A-F][0-9A-F]?").replace(/\+/g,"\\+")+"|)";a.Ve=new RegExp(c);a.Wb=[27,a.Ua,9,7,11,12,3,4,8,5]}g.ga=function(){this.D.ga()};g.info=function(){};g.message=function(a){this.print(a);zb(this.D)};function W(a,b,c,d,e,f,h){(a.qa&e)==e&&(e=a.D.X(c),a.u("%s.%s(%#06x) @%#06x %s=%#04x\n",b.id,f?"setByte":"getByte",c,d,h||"unknown",e))}
g.Aa=function(){if(!oc(this))return!1;this.D.Aa();return!0};g.step=function(a){if(!oc(this))return!1;try{var b=this.D.step(a)}catch(c){b=void 0,fb(this.D,c.stack||c.message)}void 0!==b&&this.R++;this.D.update(!0);this.update(!0);return b};g.update=function(a){this.za=this.D.j;a||this.Fa?pc(this):qc(this)};function oc(a){a.D&&O(a.D)&&!gb(a.D)?(a=a.D,a.J.error?(a.print(a.toString()+" error\n"),a=!0):a=!1,a=!a):a=!1;return a}
g.reset=function(){var a;this.Ca.length||(this.Ca=Array(1E3));for(a=0;a<this.Ca.length;a++)this.Ca[a]=-1;this.H.length||(this.H=Array(256));for(a=0;a<this.H.length;a++)this.H[a]=[a,0];this.R&&this.update();this.R=0};g.start=function(){this.Fa||this.u("running\n")};g.stop=function(a,b){this.Fa||(this.u("stopped\n"),b&&this.u("%dms (%d cycles)\n",Ya()-a,b));this.update();this.ia();this.Fa||(this.R=0);rc(this,this.D.j)};
g.X=function(a){if(a>=this.P&&a<this.La){rb(this.D,a);var b=this.g[this.P+a];b&=255}return b};function sc(a,b,c){b<a.P||b>=a.La?a.u("invalid address: %#06x\n",b):(a.g[a.P+b]=c&255,tb(a.D,b),a.D.update())}function tc(a,b){Y(a.ua,b)||a.ua.push(b);return!0}function Y(a,b,c){for(var d=!1,e=0;e<a.length;e++)if(a[e]==b){c&&a.splice(e,1);d=!0;break}return d}function uc(a,b){void 0!==b&&(rc(a,a.S),tc(a,b)&&(a.S=b))}function rc(a,b){void 0!==a.S&&b==a.S&&Y(a.ua,a.S,!0)&&(a.S=void 0);a.Fa=!1}
function yb(a,b,c,d){for(var e=!1,f=0;f<c.length;f++)if(c[f]==b){b!=a.S&&a.u("breakpoint hit: %#06x (%s)\n",b,d);e=!0;break}return e}
function vc(a,b,c){var d=z(b,4),e=a.X(b++),f=void 0===e?0:e,h=a.ka[f],k=[],l=void 0===h[1]?0:h[1];do{d+=" "+z(f,2);if(!l--)break;f=a.X(b++);if(void 0===f)break;k.push(f)}while(1);void 0===h[0]&&(h=[57,1,a.B],k.push(e));d=(d+"        ").substr(0,15);d+=a.Oa[h[0]];var n=null;if(void 0!==h[2]){l=h[2];n=a.pa[l];if(1==h[1]&&l==a.ja){var p=n.replace;k=f=k.pop();n=p.call(n,/nnnn/,z(b+(k<<24>>24),4))}else for(;k.length;)n=n.replace(/nn/,z(f=k.pop(),2));l==a.B&&1==h[1]&&32<=f&&128>f&&(n+=" ;'"+String.fromCharCode(f)+
"'")}if(e==a.D.gb&&(f<a.ca.length&&(n=a.ca[f]),f==a.D.Lb)){l=0;for(n='"';f=a.X(b++);)16>l?n+=String.fromCharCode(f):16==l&&(n+="\u2026"),l++;n+='"'}n&&(d+=" "+n);c&&(d=(d+"               ").substr(0,30),d+=";"+c.toString());a.ea=b;return d}
function Z(a,b){var c=a.za;if(void 0!==b){var d=16;"$"==b.charAt(0)?b=b.substr(1):"0x"==b.substr(0,2)?b=b.substr(2):"."==b.charAt(b.length-1)&&(d=10,b=b.substr(0,b.length-1));c=parseInt(b,d);isNaN(c)&&(a.u("invalid base-%d address: %s\n",d,b),c=void 0)}void 0!==c&&(c<a.P||c>=a.La)&&(a.u("address out of range: %x\n",c),c=void 0);return c}
function wc(a,b){if("?"==b)a.u("\nfrequency commands:\n"),a.u("clear\tclear all frequency counts\n");else{var c=0;if(a.H)if("clear"==b){for(b=0;b<a.H.length;b++)a.H[b]=[b,0];a.u("frequency data cleared\n");c++}else if(void 0!==b)a.u("unknown frequency command: %s\n",b),c++;else{var d=a.H.slice();d.sort(function(h,k){return k[1]-h[1]});for(b=0;b<d.length;b++){var e=d[b][0],f=d[b][1];f&&(a.u("%s (%#04x): %d times\n",a.Oa[a.ka[e][0]],e,f),c++)}}c||a.u("no frequency data available\n")}}
function pc(a,b,c,d){var e=Z(a,b);if(void 0!==e){void 0===d&&(d=1);b=a.La;if(void 0!==c){b=Z(a,c);if(void 0===b||b<e)return;if(256<b-e){a.u("range too large\n");return}b++;d=-1}for(e!=a.za&&a.u("\n");d--&&e<b;)c=vc(a,e,gb(a,!1)||a.Fa?a.R:0),a.u("%s\n",c),a.za=e=a.ea}}
function qc(a,b){if(b&&"?"==b[1])a.u("\nregister commands:\n"),a.u("r to display all\n"),a.u("r [target=value] to modify\n"),a.u("supported targets:\n"),a.u("A,X,Y,S,PC and flags C,Z,D,V,N\n");else{var c=!0;if(void 0!==b&&1<b.length){c=!1;var d=b[1],e=d.indexOf("=");if(0<e)b=d.substr(e+1),d=d.substr(0,e);else if(2<b.length)b=b[2];else{a.u("missing value for %s\n",b[1]);return}e=parseInt(b,16);if(isNaN(e)){a.u("invalid value: %s\n",b);return}switch(d.toUpperCase()){case "A":a.D.m=e&255;break;case "X":a.D.G=
e&255;break;case "Y":a.D.K=e&255;break;case "C":a.D.i=e?256:0;break;case "Z":a.D.s=e?0:1;break;case "D":e?Bb(a.D):Cb(a.D);break;case "V":e?(d=a.D,d.B=0,d.F=128):(d=a.D,d.B=0,d.F=0);break;case "N":a.D.o=e?128:0;break;case "S":if(256!=(e&-256)){a.u("invalid stack pointer: %s\n",b);return}a.D.L=e;break;case "PC":c=!0;a.D.j=e&65535;a.za=a.D.j;break;default:a.u("unknown register: %s\n",d);return}a.D.update()}a.u("%s\n","A="+z(a.D.m,2)+" X="+z(a.D.G,2)+" Y="+z(a.D.K,2)+" P="+z(wb(a.D),2)+" S="+z(a.D.L,
4)+" PC="+z(a.D.j,4));c&&pc(a,z(a.za=a.D.j,4))}}function xc(a,b){b=void 0===b?1:parseInt(b,10);var c=1==b?0:1;Na(b,function(d){return function(){return hb(d,!0)&&d.step(c)}}(a),function(d){return function(){hb(d,!1)}}(a))}
function nc(a,b){b.length||(a.Ya?(a.u("ended assemble @%04x\n",a.la),a.za=a.la,a.Ya=!1):a.kb&&(b=a.kb));if(O(a)&&!gb(a,!0)&&0<b.length){a.Ya?b="a "+z(a.la,4)+" "+b:1<b.length&&1!=b.indexOf(" ")&&(b=b.charAt(0).toLowerCase()+" "+b.substr(1));var c=b.split(" ");a.kb=c[0];switch(c[0].toLowerCase()){case "a":var d=Z(a,c[1]);if(void 0!==d)if(a.la=d,void 0===c[2])a.u("begin assemble @%#06x\n",a.la),a.Ya=!0,a.D.update();else{b=c[2];var e=c[3];c=a.la;d=[];if(void 0!==b){var f;b=b.toUpperCase();"?"==b.charAt(b.length-
1)&&(e="?",b=b.substr(0,b.length-1));for(f=0;f<a.Oa.length&&b!=a.Oa[f];f++);f==a.Oa.length&&(a.u("unknown operation: %s\n",b),f=-1);var h="",k;if(0<=f&&void 0!==e)if(h=e.toUpperCase(),"?"==h){for(e=k=0;e<a.ka.length;e++)a.ka[e][0]===f&&(k||a.u("supported opcodes:\n"),a.u("     %02x: %s%s\n",e,b,void 0!==a.ka[e][2]?" "+a.pa[a.ka[e][2]]:""),k++);f=-1}else if(k=h.match(a.Ve),null!==k&&k[0]==h){for(e=1;e<k.length;e++)if(k[e]==h)if(void 0===l)var l=e-1;else{a.u("too many operand matches (both %s and %s)\n",
a.pa[l],a.pa[e-1]);f=-1;break}l==a.Ta&&0>a.Wb.indexOf(f)&&(l=a.V);l==a.pb&&27!=f&&(l=a.V)}else a.u("unknown operand: %s\n",h),f=-1;if(0<=f){k=-1;for(e=0;e<a.ka.length;e++)if(a.ka[e][0]===f&&a.ka[e][2]===l)if(0>k)k=e;else{a.u("too many instruction matches (both %#04x and %#04x)\n",k,e);k=-2;break}if(0<=k){if(d.push(k),void 0!==l)if(b=a.ka[k][1],h=h.match(/[0-9A-F]+/),null!==h)for(h=parseInt(h[0],16),1==b&&l==a.ja&&(h-=c+2,-128>h||127<h)&&(a.u("branch out of range (%d)\n",h),d=[],b=0),e=0;e<b;e++)d.push(h&
255),h>>>=8;else b&&a.u("instruction missing %d bytes\n",b)}else a.u("unknown instruction: %s %s%s\n",b,h,"")}}l=d;if(l.length){for(c=0;c<l.length;c++)sc(a,a.la+c,l[c]);a.u("%s\n",vc(a,a.la));a.la+=l.length}}break;case "b":l=c[1];c=c[2];if(void 0===l||"?"==l)a.u("\nbreakpoint commands:\n"),a.u("bp [a]\tset exec breakpoint at [a]\n"),a.u("br [a]\tset read breakpoint at [a]\n"),a.u("bw [a]\tset write breakpoint at [a]\n"),a.u("bc [a]\tclear breakpoint at [a]\n"),a.u("bl\tlist all breakpoints\n");else if(void 0===
c&&1<l.length&&(c=l.substr(1),l=l.charAt(0)),"l"==l){l=0;d=a.ua;for(c=0;c<d.length;c++)a.u("breakpoint enabled: %#06x (exec)\n",d[c]),l++;d=a.Ba;for(c=0;c<d.length;c++)a.u("breakpoint enabled: %#06x (read)\n",d[c]),l++;d=a.Da;for(c=0;c<d.length;c++)a.u("breakpoint enabled: %#06x (write)\n",d[c]),l++;l||a.u("no breakpoints\n")}else void 0===c?a.u("missing breakpoint address\n"):"c"==l&&"*"==c?(a.ua=[],a.Ba=[],a.Da=[],a.u("all breakpoints cleared\n")):(c=Z(a,c),void 0!==c&&("p"==l?tc(a,c)?a.u("breakpoint enabled: %#06x (exec)\n",
c):a.u("breakpoint not set: %#06x\n",c):"c"==l?Y(a.ua,c,!0)?a.u("breakpoint cleared: %#06x (exec)\n",c):Y(a.Ba,c,!0)?a.u("breakpoint cleared: %#06x (read)\n",c):Y(a.Da,c,!0)?a.u("breakpoint cleared: %#06x (write)\n",c):a.u("breakpoint missing: %#06x\n",c):"r"==l?(Y(a.Ba,c)||a.Ba.push(c),a.u("breakpoint enabled: %#06x (read)\n",c)):"w"==l?(Y(a.Da,c)||a.Da.push(c),a.u("breakpoint enabled: %#06x (write)\n",c)):a.u("unknown breakpoint command: %s\n",l)));break;case "d":l=c[1];d=c[2];if("?"==l)a.u("\ndump commands:\n"),
a.u("d [a] [#]    dump # lines of memory\n");else if(l=Z(a,l),void 0!==l){c=0;void 0!==d&&("l"==d.charAt(0)&&(d=d.substr(1)),c=parseInt(d,10));c||(c=1);for(d=0;d<c;d++){h=b="";e=l;for(f=0;8>f&&l<a.La;f++)k=a.X(l),void 0===k&&(k=0),b+=z(k,2)+" ",h+=32<=k&&127>k?String.fromCharCode(k):".",l++;a.u("%04x %s%s\n",e,b,h)}a.za=l}break;case "e":l=c[1];if(void 0===l)a.u("missing address\n");else if(l=Z(a,l),void 0!==l)for(d=2;d<c.length;d++)b=parseInt(c[d],16),sc(a,l++,b);break;case "f":wc(a,c[1]);break;case "g":l=
c[1];void 0!==l&&uc(a,Z(a,l));a.Aa()||a.D.ia();break;case "h":a.ga();break;case "o":if(void 0===c[1]||"?"==c[1])a.u("\noption commands:\n"),a.u("max\trun at maximum speed\n"),a.u("fast\trun faster (up to %dMhz)\n",a.D.Na),a.u("slow\trun at normal speed (1Mhz)\n"),a.u("classic\tuse classic operand syntax\n"),a.u("modern\tuse modern operand syntax\n"),a.u("msg\tenable message categories\n");else switch(l=c[1],l){case "slow":nb(a.D,a.D.Xa);break;case "fast":nb(a.D,a.D.Mb);break;case "max":nb(a.D,a.D.Nb);
break;case "classic":mc(a,!0);a.u("classic syntax enabled\n");break;case "modern":mc(a,!1);a.u("modern syntax enabled\n");break;case "msg":l=0;void 0!==c[2]&&("all"==c[2]?l=255:void 0!==a.Va[c[2]]&&(l=a.Va[c[2]]),l&&("on"==c[3]?a.qa|=l:"off"==c[3]&&(a.qa&=~l)));for(d in a.Va)if(void 0===c[2]||"all"==c[2]||c[2]==d)l=a.Va[d],a.u("%s messages: %s\n",d,a.qa&l?"on":"off");break;default:a.u("unknown option: %s\n",l)}break;case "p":h=c[1];l=10;c=a.Qa;d=a.Ca;if(void 0!==d){b=void 0===h?a.Yb:parseInt(h,10);
void 0===b&&(b=10);b>d.length&&(a.u("note: only %d available\n",d.length),b=d.length);void 0!==h&&(a.jb=0,a.u("%d instructions earlier:\n",b));h=a.jb?a.jb:1;c-=b;for(0>c&&(c=d.length-1);l&&c!=a.Qa;){e=d[c];if(0>e)break;a.u("%s\n",vc(a,e,h++));++c==d.length&&(c=0);l--;b--}a.Yb=b;a.jb=h}10==l&&a.u("no history available\n");break;case "r":qc(a,c);break;case "s":a.X(a.D.j)==a.D.Ua?(uc(a,a.D.j+3),a.Fa=!0,a.Aa()||a.D.ia()):xc(a);break;case "t":xc(a,c[1]);break;case "u":pc(a,c[1],c[2],8);break;case "?":case "help":a.u("\ncommands:\n?\thelp\na [#]\tassemble\nb [#]\tbreakpoint\nd [#]\tdump memory\ne [#]\tedit memory\nf\tdump frequencies\ng [#]\trun to [#]\nh\thalt\no\toptions\np [#]\tdump history\nr\tdump/edit registers\ns\tstep over instruction\nt [#]\tstep instruction(s)\nu [#]\tunassemble\n");
a.u("note: frequency and history commands operate only when breakpoints are set\n");break;default:a.u("unknown command: %s\n",b)}}}D(function(){for(var a=M("c1p","debugger"),b=0;b<a.length;b++){var c=a[b],d=N(c);d=new lc(d);I(d,c)}});function yc(a,b){H.call(this,"C1PComputer",a);this.fa=b}v(yc,H);yc.prototype.reset=function(a){var b=null,c;for(c in this.fa)for(var d=0;d<this.fa[c].length;d++){var e=this.fa[c][d];e&&e.reset&&(e.reset(),"cpu"==c&&(b=e))}b&&(b.update(),a&&b.Aa())};
yc.prototype.start=function(){for(var a in this.fa)if("cpu"!=a)for(var b=0;b<this.fa[a].length;b++){var c=this.fa[a][b];c&&c.start&&c.start()}};yc.prototype.stop=function(a,b){for(var c in this.fa)if("cpu"!=c)for(var d=0;d<this.fa[c].length;d++){var e=this.fa[c][d];e&&e.stop&&e.stop(a,b)}};yc.prototype.Y=function(a,b,c){switch(b){case "reset":return this.M[b]=c,c.onclick=function(d){return function(){d.reset()}}(this),!0}return!1};function R(a,b){return a.fa[b]?a.fa[b][0]:null}
function zc(a){var b=null,c;for(c in a.fa)for(var d=0;d<a.fa[c].length;d++){var e=a.fa[c][d];if(e){if(!O(e)){O(e,function(f){return function(){zc(f)}}(a));return}"cpu"==c?b=e:e.oa&&e.oa(!0,a)}}a.Z();a.u(0,"%s v%s\n%s\n","C1Pjs","2.20","Copyright \u00a9 2012-2023 Jeff Parsons <Jeff@pcjs.org>");b&&b.oa(!0,a)}
D(function(){for(var a=M("c1p","computer"),b=0;b<a.length;b++){for(var c=a[b],d=N(c),e,f={},h,k=0,l=0,n=0;n<d.modules.length;n++){var p=d.modules[n];if(!n){if("cpu"!=p.type)break;k=+p.start;l=+p.end;h=Array(l+1-k);for(e=k;e<h.length;e++)h[e]=0}if(e=Za(p.refID,d.id)){var m=p.type;void 0===f[m]&&(f[m]=[]);f[m].push(e);e.ha&&void 0!==p.start&&e.ha(h,+p.start,+p.end,f.cpu[0])}else{B(1099511627776,'no component for <module refid="'+p.refID+'">');return}}if(void 0===h){B(1099511627776,'<module type="cpu"> definition must appear first in the <computer> specification');
break}if(e=$a("C1PDebugger",d.id,!1))f["debugger"]=[e],e.ha&&e.ha(h,k,l,f.cpu[0]);k=new yc(d,f);if(l=$a("C1PPanel",d.id,!1))if(f.panel=[l],l.M.print){e=void 0;d=d.id;f=[];d&&0<(e=d.indexOf("."))&&(d=d.substr(0,e+1));n=y.components;for(e=0;e<n.length;e++)p=n[e],d&&0!=p.id.indexOf(d)||f.push(p);d=f;for(f=0;f<d.length;f++)e=d[f],e!=l&&(e.print=l.print)}I(k,c);zc(k)}});var Ac=0;
function Bc(a,b,c,d,e,f,h,k,l){k("Loading "+a+"...");A(a,function(n,p,m){m?(p||(p="unable to load "+a+" ("+m+")"),l(n,p,null)):Cc(p,a,b,c,d,e,f,h,k,l)})}
function Cc(a,b,c,d,e,f,h,k,l,n){function p(m,q,t){if(t)n(m,t,null);else{c&&(Wa(c,b,q),(t=b)&&0>t.indexOf("/")&&"/"==window.location.pathname.slice(-1)&&(t=window.location.pathname+t),f?"}"==f.slice(-1)?(f=f.slice(0,-1),1<f.length&&(f+=",")):f='{state:"'+f+'",':f="{",f+='url:"'+t+'"}',"object"==typeof resources&&(t=null),f=f.replace(/\$/g,"$$$$").replace(/'/g,"&apos;"),h&&(m=q.match(/(<machine[^>]*\sclass=)(['"])(.*?)(\2[^>]*>)/))&&(q=q.replace(m[0],m[1]+m[2]+h+m[4]),h=""),(m=q.match(/(<machine[^>]*\sdebugger=)(['"])(available)(\2[^>]*>)/))&&
(q=q.replace(m[0],m[1]+m[2]+"optional"+m[4])),q=q.replace(/(<machine[^>]*\sid=)(['"]).*?\2/,"$1$2"+c+"$2"+(h?' class="'+h+'"':"")+(f?" parms='"+f+"'":"")+(t?' url="'+t+'"':"")));k||(q=q.replace(/(<xsl:variable name="APPNAME">).*?(<\/xsl:variable>)/,"$1"+d+"$2"),q=q.replace(/(<xsl:variable name="APPCLASS">).*?(<\/xsl:variable>)/,"$1"+e+"$2"),q=q.replace(/<xsl:variable name="APPVERSION"(\/>|>[^<]*<\/xsl:variable>)/,'<xsl:variable name="APPVERSION">2.20</xsl:variable>'));m=null;if("<"==q.charAt(0))try{k||
(q=q.replace(/<!DOCTYPE(.|[\r\n])*]>\s*/g,"")),window.ActiveXObject||"ActiveXObject"in window?(m=new window.ActiveXObject("Microsoft.XMLDOM"),m.async=!1,m.loadXML(q)):m=(new window.DOMParser).parseFromString(q,"text/xml")}catch(J){m=null,q=J.message}else q="unrecognized XML: "+(255<q.length?q.substr(0,255)+"...":q);n(b,q,m)}}a?k?Dc(b,a,l,p):p(b,a,""):n(b,"no data",null)}
function Dc(a,b,c,d){var e;if(e=/<([a-z]+)\s+ref="(.*?)"(.*?)\/>/g.exec(b)){var f=e[2];c("Loading "+f+"...");A(f,function(h,k,l){if(l||!k)d(h,b,"unable to resolve XML reference: "+e[0]+" ("+l+")");else{if(l=e[3]){var n=k.match(new RegExp("<"+e[1]+"[^>]*>"));if(n){for(var p=n[0],m,q=/( [a-z]+=)(['"])(.*?)\2/gi;m=q.exec(l);)p=0>p.toLowerCase().indexOf(m[1].toLowerCase())?p.replace(">",m[0]+">"):p.replace(new RegExp(m[1]+"(['\"])(.*?)\\1"),m[0]);n[0]!=p&&(k=k.replace(n[0],p))}else{d(h,b,"missing <"+
e[1]+"> in "+f);return}}k=k.replace(/<\?xml[^>]*>[\r\n]*/,"");b=b.replace(e[0],k);Dc(h,b,c,d)}})}else d(a,b,"")}
function Ec(a,b,c,d,e,f,h){function k(u){if(void 0===m){var E=p&&M("machine-warning","",p);m=E&&E[0]||p}m&&(m.innerHTML=Da(u))}function l(u,E){if("string"==typeof E&&0<=E.indexOf("<!DOCTYPE html>")){var fa=E.match(/<title>(?:PCjs: |)(.*?)<\/title>/);fa&&(E=fa[1])}B(1099511627776,"%s\n",E);k("Error: "+E+(u?" ("+u+")":""));q&&n();q=!1}function n(){--Ac||G(!0)}var p,m,q=!0;Ac++;y.machines[c]={};if(!d)return f&&Wa(c,"parms",f),n(),q;"true"==La("debugger")&&0>d.indexOf("/debugger")&&(d=d.replace("/machine.xml",
"/debugger/machine.xml"));try{if(p=document.getElementById(c)){var t,J=w.resources;if("object"==typeof J&&(t=J.css)){var K=document.head||document.getElementsByTagName("head")[0],x=document.createElement("style");x.type="text/css";x.styleSheet?x.styleSheet.cssText=t:x.appendChild(document.createTextNode(t));K.appendChild(x)}e||(e="/machines/"+b+"/xsl/components.xsl");b=b.split("/").pop();t=function(u,E,fa){fa?Bc(e||"","",a,b,"","",!1,k,function(P,V,L){if(L)if(Wa(c,e||"",V),k("Processing "+d+"..."),
window.ActiveXObject||"ActiveXObject"in window)(L=fa.transformNode(L))?(p.outerHTML=L,n()):l(P,"transformNodeToObject failed");else if(document.implementation&&document.implementation.createDocument)if(V=new XSLTProcessor,V.importStylesheet(L),L=V.transformToFragment(fa,document))if(V=p.parentNode){var ya=P=0,Xa=p.getBoundingClientRect();0>Xa.bottom&&(P=window.scrollX,ya=window.scrollY);V.replaceChild(L,p);(p=document.getElementById(c))&&0>Xa.bottom&&(L=p.getBoundingClientRect(),ya=window.performance&&
window.performance.navigation.type==window.performance.navigation.TYPE_RELOAD?0:ya+Math.ceil(L.height-Xa.height),window.scrollTo(P,ya));n()}else l(P,"invalid machine element: "+c);else l(P,"transformToFragment failed");else l(P,"unable to transform XML: unsupported browser");else l(P,V)}):l(u,E)};"<"!=d.charAt(0)?Bc(d,c,a,b,f||"",h||"",!0,k,t):Cc(d,"",c,a,b,f||"",h||"",!1,k,t)}else l(d,"missing machine element: "+c)}catch(u){l(d,u.message)}return q}
function Fc(a,b,c,d,e){G(!1);return Ec("PCx86","pcx86",a,b,c,d,e)}w.embedC1P=function(a,b,c,d,e){G(!1);return Ec("C1Pjs","osi/c1p",a,b,c,void 0,e)};w.embedPC=Fc;w.embedPCx86=Fc;w.embedPCx80=function(a,b,c,d,e){G(!1);return Ec("PCx80","pcx80",a,b,c,d,e)};w.embedPDP10=function(a,b,c,d,e){G(!1);return Ec("PDPjs","dec/pdp10",a,b,c,d,e)};w.embedPDP11=function(a,b,c,d,e){G(!1);return Ec("PDPjs","dec/pdp11",a,b,c,d,e)};
w.commandMachine=function(a,b,c,d,e,f){if("script"==e){d=!1;e=y.commands;c+=".machine";if(!f)delete e[c],d=!0;else if("string"==typeof f&&!e[c]){d=!0;for(var h=c,k=f.length,l=[],n=[],p="",m=null,q=0;q<k;q++){var t=f[q];if('"'==t||"'"==t)m&&t!=m?p+=t:(m?m=null:m=t,p&&(n.push(p),p=""));else{if(!m){if("\r"==t||"\n"==t)t=";";if(" "==t||"\t"==t||";"==t){p&&(n.push(p),p="");";"==t&&n.length&&(l.push(n),n=[]);continue}}p+=t}}p&&n.push(p);n.length&&l.push(n);e[h]=l;ab(c)||(d=!1)}return d?(b&&(a.disabled=
!0),!0):!1}if(d&&(h=$a(d,c+".machine"))&&(k=h.exports)&&(k=k[e]))return k.call(h,f)?(b&&(a.disabled=!0),!0):!1;console.log("unimplemented: commandMachine('"+c+"','"+d+"','"+e+"','"+f+"')");return!1};w.enableEvents=G;w.sendEvent=F;})()

//# sourceMappingURL=c1p.js.map
