(function(){/*
 https://www.pcjs.org/modules/v3/defines.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/numio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/stdio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/webio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/device.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/bus.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/memory.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/rom.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/input.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/led.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/time.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/cpu.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/ledctrl.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/modules/v3/machine.js (C) 2012-2023 Jeff Parsons
*/
var t;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function v(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function y(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function z(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.lf=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
y("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});y("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
y("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
function ma(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}y("String.prototype.repeat",function(a){return a?a:function(b){var c=ma(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
y("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});y("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,f){this.aa=g;ca(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.aa};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
y("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return na(aa(this))}})}return a});function na(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function oa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}y("Array.prototype.keys",function(a){return a?a:function(){return oa(this,function(b){return b})}});y("Array.prototype.values",function(a){return a?a:function(){return oa(this,function(b,c){return c})}});
y("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function A(a){return a?a:Array.prototype.fill}y("Int8Array.prototype.fill",A);y("Uint8Array.prototype.fill",A);y("Uint8ClampedArray.prototype.fill",A);y("Int16Array.prototype.fill",A);y("Uint16Array.prototype.fill",A);y("Int32Array.prototype.fill",A);
y("Uint32Array.prototype.fill",A);y("Float32Array.prototype.fill",A);y("Float64Array.prototype.fill",A);y("Number.parseInt",function(a){return a||parseInt});y("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ma(this,b,"startsWith"),e=d.length,g=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<g&&c<e;)if(d[c++]!=b[f++])return!1;return f>=g}});function pa(){}var qa=new ArrayBuffer(2);(new DataView(qa)).setUint16(0,256,!0);new Uint16Array(qa);
var B={uc:0xffffffffffff,NONE:0,Cc:0,Ua:0x800000000000};"undefined"!=typeof window&&(window.PCjs||(window.PCjs={}),window.PCjs.machines||(window.PCjs.machines={}),window.PCjs.components||(window.PCjs.components=[]));var D="undefined"!=typeof window?window.PCjs.machines:{},ra="undefined"!=typeof window?window.PCjs.components:[],E={};E.Defines=pa;function sa(){}z(sa,pa);function ta(a,b){var c=a/F|0,d=b/F|0;return(a&b)==(b|0)&&(c&d)==d}var F=Math.pow(2,32);E.NumIO=sa;
function H(){this.sb={};for(var a=0;22>a;a++)this.sb["ACDFGHMNSTWYbdfjcsoXx%"[a]]=null}z(H,sa);t=H.prototype;t.flush=function(){var a=ua;ua="";this.fb(a)};function va(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}
t.Dd=function(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,v(a)));return a};
t.fb=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),wa||(wa=b),a=((b-wa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(ua+a.substr(0,c)),ua="",a=a.substr(c+1)),wa=null);ua+=a;return a.length};t.da=function(a){return this.fb(this.Aa.apply(this,[a].concat(v(la.apply(1,arguments)))))};
t.Aa=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,g;for(g=0;g<d.length-6;g+=6){c+=d[g];var f=d[g+5];if(void 0===this.sb[f])c+="%"+d[g+1]+d[g+2]+d[g+3]+d[g+4]+f;else{if(e<b.length){var h=b[e];"%"!=f&&e++}else h=b[b.length-1];var m=d[g+1],n=0<=m.indexOf("#"),l=0<=m.indexOf("0"),k=d[g+2];"*"==k?(k=h,h=e<b.length?b[e++]:b[b.length-1]):k=+k||0;var p=d[g+3];p=p?+p.substr(1):-1;var q=d[g+4],r=null,x=0,w=
"",u=0<="ACDFGHMNSTWY".indexOf(f)&&"object"!=typeof h?this.Dd(h):h;switch(f){case "C":c+=isNaN(u.getTime())?void 0:this.Aa("%#W, %#F %#D, %#Y".replaceAll("#",n?"#":""),u);continue;case "D":h=n?u.getUTCDate():u.getDate();f="d";break;case "A":case "G":case "H":h=n?u.getUTCHours():u.getHours();"A"==f?(h=12>h?"am":"pm",f="s"):("G"==f&&(h=h?12<h?h-12:h:12),f="d");break;case "F":case "M":h=n?u.getUTCMonth():u.getMonth();"F"==f?(h=xa[h],f="s"):(h++,f="d");break;case "N":h=n?u.getUTCMinutes():u.getMinutes();
f="d";break;case "S":h=n?u.getUTCSeconds():u.getSeconds();f="d";break;case "T":c+=isNaN(u.getTime())?void 0:this.Aa("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",n?"#":""),u);continue;case "W":h=ya[n?u.getUTCDay():u.getDay()];f="s";break;case "Y":h=n?u.getUTCFullYear():u.getFullYear(),0<p&&(h%=Math.pow(10,p),p=-1),f="d"}switch(f){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=p&&(l=!0,k<p&&(k=p),p=-1);case "f":h=+h;f=h+"";0<=p&&(f=h.toFixed(p));f.length<k&&(l?(0>h&&(k--,f=f.substr(1)),
f=("0".repeat(k)+f).slice(-k),0>h&&(f="-"+f)):f=(" ".repeat(k)+f).slice(-k));c+=f;break;case "j":c+=JSON.stringify(h,null,k||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=p&&(h=h.substr(0,p));h.length<k;)h=0<=m.indexOf("-")?h+" ":" "+h;c+=h;break;case "o":x=8,n&&(w="0o");case "X":r=za;case "x":f="";x||(x=16);!w&&n&&(w="0x");r||(r=Aa);h=Math.trunc(h);0<=p&&(l=!0,k<p&&(k=p));l&&!k&&("b"==q?k=2:"h"==q||"w"==q?
k=4:"l"==q?k=8:(k=Math.abs(h),k=255>=k?2:65535>=k?4:4294967295>=k?8:9),k+=w.length);k-=w.length;do n=16,Number.isNaN(h)||(n=h&x-1,h=Math.trunc(h/x)),l||!f||n||h?f=r[n]+f:(w&&(f=w+f,w=""),0<k&&(f=" "+f));while(0<--k||h);c+=w+f;break;case "%":c+="%";break;default:c=this.sb[f]?c+this.sb[f](f,m,k,p,h):c+("(unimplemented sprintf type: %"+f+")")}}}return c+=d[g]};var ua="",wa=null,Aa="0123456789abcdef?",za="0123456789ABCDEF?",ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),xa="January February March April May June July August September October November December".split(" ");
E.StdIO=H;function I(a){H.call(this);this.la={};this.Ca=0;this.oa=this;a&&(this.oa.Ca=0,this.oa.Ma=[],this.oa.Fa=0,this.oa.eb={},this.oa.Xe=!1)}var Ba;z(I,H);t=I.prototype;t.Oa=function(a,b){var c=this,d=this;switch(a){case Ca.yc:b.onclick=function(){var e=c.Za(Ca.wb,!0);e&&(e.value="")};break;case Ca.wb:Da(b),b.addEventListener("keydown",function(e){Ea(d,e,!0)}),b.addEventListener("keypress",function(e){Ea(d,e)})}};
function Fa(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value="string"==typeof b[e]?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}function Ga(a,b){var c=Ha.Ib;a.oa.eb[c]||(a.oa.eb[c]=[]);a.oa.eb[c].push(b)}function Da(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}
t.error=function(a,b){b=this.Aa.apply(this,[a].concat(v(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.Aa.apply(this,[c].concat(v(b))))this.da("%s\n",b),a||alert(b)};t.Za=function(a){return this.la[a]};function Ia(a){var b=window;if(b){do{for(var c=0;c<Ja.length;c++){var d=Ja[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}
function Ka(a,b){return a.ha.bindings&&a.ha.bindings[b]}function La(a){if(a=a.la[Ma])var b=a.textContent;return b}function Na(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}function K(a,b,c,d){a=a.ha[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Oa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Pa(){var a,b=Ba;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ba=b}return b}function Qa(a){if(void 0===L.ub){var b=!1;if(window)try{window.localStorage.setItem(L.Xa,L.Xa),b=window.localStorage.getItem(L.Xa)==L.Xa,window.localStorage.removeItem(L.Xa)}catch(c){a.da("%s\n",c.message),b=!1}L.ub=b}return!!L.ub}
function Ra(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.Ca;return-1==(b|1)||ta(a.oa.Ca,b)?!0:!1}function Sa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ta(a){var b=null;if(Qa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.na))&&(b=JSON.parse(c))}catch(d){a.da("%s\n",d.message)}}return b}
function Ea(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.oa,g=b.target;if(c){a=!1;var f;c=g.value;var h=c.lastIndexOf("\n");d==M.Fb&&g.selectionStart<=h+1&&(a=!0);d==M.td?(a=!0,0<e.Fa&&(f=e.Ma[--e.Fa])):d==M.Ec&&(a=!0,e.Fa<e.Ma.length&&(f=e.Ma[++e.Fa]||""));a&&b.preventDefault();void 0!=f&&(g.value=c.substr(0,h+1)+f)}else d=String.fromCharCode(d),f=g.value,c=f.lastIndexOf("\n"),g.selectionStart<=c&&g.setSelectionRange(f.length,f.length),b.stopPropagation(),"@"==d&&0<e.Fa&&c+1==
f.length&&(g.value+=e.Ma[--e.Fa],d="\r"),"\r"==d&&(b.preventDefault(),f=g.value+="\n",g.blur(),g.focus(),(b=Ua(a,f.slice(f.lastIndexOf("\n",f.length-2)+1,-1)||""))&&a.da("%s\n",b.replace(/\n$/,"")))}}
function Va(a,b){if(void 0!=b){var c=a.oa;try{if(b=b.trim())c.Fa<c.Ma.length&&b==c.Ma[c.Fa]?c.Fa++:(c.Ma.push(b),c.Fa=c.Ma.length);var d=b.split(" "),e=d[0],g=a.oa.eb[Ha.Ib];switch(e[0]){case "m":if("?"==e[1]){var f="";Wa.forEach(function(k){f+=k+"\n"});f&&(f="message commands:\n"+f);break}f="";var h=void 0;e=d[d.length-1].toLowerCase();var m="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=m&&d.pop();1>=d.length&&(void 0!=m&&(h=m,m=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(N));
for(g=1;g<d.length;g++){e=d[g];var n=N[e];if(!n){f+="unrecognized message: "+e+"\n";break}void 0!=m&&Xa(a,n,m);if(void 0==h||h==Ra(a,n))f+=a.Aa("%8s: %b\n",e,Ra(a,n))}Ra(a,B.Ua)&&(f+="all messages will be buffered until buffer is turned off\n");f||(f="no messages\n");break;case "?":f="",Ya.forEach(function(k){f+=k+"\n"}),f&&(f="default commands:\n"+f);default:if(d.unshift(b),g)for(a=0;a<g.length;a++){var l=g[a](d);if(void 0!=l){f=f?f+l:l;break}}}}catch(k){f="error: "+k.message+"\n"}}return f}
function Ua(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Va(a,b[d])}return c}t.fb=function(a,b){void 0==b&&(b=Ra(this,B.Ua));if(!b){var c=this.Za(Ca.wb,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Sa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return H.prototype.fb.call(this,a,b)};
t.da=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return Ra(this,c)?H.prototype.da.call.apply(H.prototype.da,[this,a].concat(v(b))):0};function Za(a,b){if(Qa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.na,b)}catch(c){a.da("%s\n",c.message)}}}function $a(a,b,c){(a=a.la[b])&&a.textContent!=c&&(a.textContent=c)}
function Xa(a,b,c){var d=!1;c?(c=a.oa.Ca,a.oa.Ca=(c|b)+(c/F|0|b/F|0)*F):(d=ta(a.oa.Ca,B.Ua)&&ta(b,B.Ua),c=a.oa.Ca,a.oa.Ca=(c&~b)+((c/F|0)&~(b/F|0))*F);d&&a.flush()}
var Ca={yc:"clear",wb:"print"},Ya=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Wa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],N={all:B.uc,buffer:B.Ua},Ha={Ib:"command"},ab={Jb:13,tb:65,Eb:66,Gb:67,Kb:68,E:69,Mb:70,Nb:71,Ob:72,Pb:73,Rb:74,Sb:75,Ub:76,Xb:77,Yb:78,Zb:79,$b:80,Q:81,ac:82,cc:83,dc:84,
ec:85,fc:86,hc:87,ic:88,jc:89,zb:90,a:97,b:98,c:99,d:100,e:101,f:102,cf:103,df:104,ef:105,ff:106,k:107,gf:108,hf:109,n:110,jf:111,p:112,q:113,r:114,kf:115,t:116,mf:117,nf:118,w:119,x:120,y:121,z:122},M={Fb:8,md:9,Tc:10,Jb:13,hd:16,Ac:17,vc:18,Ne:19,vb:20,Pd:27,kd:32,Qe:33,Pe:34,Od:35,je:36,Vb:37,td:38,yb:39,ge:39,Ec:40,de:44,Re:44,ke:45,Nd:46,fe:46,ie:47,ZERO:48,ONE:49,rd:50,nd:51,Pc:52,Oc:53,jd:54,gd:55,Fc:56,Zc:57,Mc:59,Lc:61,tb:65,Eb:66,Gb:67,Kb:68,E:69,Mb:70,Nb:71,Ob:72,Pb:73,Rb:74,Sb:75,Ub:76,
Xb:77,Yb:78,Zb:79,$b:80,Q:81,ac:82,cc:83,dc:84,ec:85,fc:86,hc:87,ic:88,jc:89,zb:90,Hb:91,ee:91,ce:92,Ue:93,he:93,oe:96,Fe:96,be:96,pe:97,De:97,qe:98,Ce:98,re:99,Ie:99,se:100,Ge:100,te:101,ze:101,ue:102,Ke:102,ve:103,Ee:103,we:104,Me:104,xe:105,Je:105,He:106,ye:107,Le:109,Ae:110,Be:111,Qd:112,Ud:113,Vd:114,Wd:115,Xd:116,Yd:117,Zd:118,$d:119,ae:120,Rd:121,Sd:122,Td:123,$c:144,dd:145,Kc:173,ed:186,Gc:187,Ld:188,Bc:189,Oe:190,We:191,Jd:192,le:219,Kd:220,Te:221,Se:222,Jc:224,me:901,Ye:1E3},bb={},cb=(bb[M.Mc]=
M.ed,bb[M.Lc]=M.Gc,bb[M.Kc]=M.Bc,bb[M.Jc]=M.Hb,bb),db={Vb:1,yb:2,ne:3},O={},eb=(O[M.Fb]="\b",O[M.md]="\t",O[M.Tc]="\n",O[M.Jb]="\r",O[M.kd]=" ",O[M.ZERO]="0",O[M.ONE]="1",O[M.rd]="2",O[M.nd]="3",O[M.Pc]="4",O[M.Oc]="5",O[M.jd]="6",O[M.gd]="7",O[M.Fc]="8",O[M.Zc]="9",O[M.tb]="A",O[M.Eb]="B",O[M.Gb]="C",O[M.Kb]="D",O[M.E]="E",O[M.Mb]="F",O[M.Nb]="G",O[M.Ob]="H",O[M.Pb]="I",O[M.Rb]="J",O[M.Sb]="K",O[M.Ub]="L",O[M.Xb]="M",O[M.Yb]="N",O[M.Zb]="O",O[M.$b]="P",O[M.Q]="Q",O[M.ac]="R",O[M.cc]="S",O[M.dc]=
"T",O[M.ec]="U",O[M.fc]="V",O[M.hc]="W",O[M.ic]="X",O[M.jc]="Y",O[M.zb]="Z",O[M.Vb]="Left",O[M.yb]="Right",O),Ja=["","moz","ms","webkit"],fb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},L={ub:void 0,Xa:"PCjs.localStorage"};E.WebIO=I;
function Q(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;I.call(this,a==b);this.na=a;this.va=b;D[this.na]||(D[this.na]={});D[this.na][this.va]&&this.da("warning: machine configuration contains multiple '%s' devices\n",this.va);D[this.na][this.va]=this;this.id=this.na==this.va?this.na:this.na+"."+this.va;ra.push(this);this.oa=gb(this,this.na);this.ready=!0;hb(this,c,d);this.Wb=[]}z(Q,I);
function hb(a,b,c){c=b.overrides||c;if(c.length){var d=Pa();for(q in d)if(0<=c.indexOf(q)){var e=d[q];var g=void 0;var f,h=void 0,m=e,n=10;if(m){n||(n=10);var l=0<m.indexOf(",");l&&(m=m.replace(/,/g,""));var k=f=m.charAt(0);"#"==f?(n=8,f=""):"$"==f&&(n=16,f="");k!=f?m=m.substr(1):(k=f=m.substr(0,2),"0b"==f&&l||"^B"==f?(n=2,f=""):"0o"==f||"^O"==f?(n=8,f=""):"^D"==f?(n=10,f=""):"0x"==f&&(n=16,f=""),k!=f&&(m=m.substr(2)));k=f=m.slice(-1);"Y"==f||"y"==f?(n=2,f=""):"."==f?(n=10,f=""):"H"==f||"h"==f?(n=
16,f=""):"K"==f?f="000":"M"==f?f="000000":"G"==f&&(f="000000000");k!=f&&(m=m.slice(0,-1)+f);k=0;10>=n&&(f=m.match(/(-?[0-9]+)B([0-9]*)$/))&&(m=f[1],k=35-((f[2]||35)&255));(n&&10!=n?16==n?null===m.match(/^-?[0-9a-f]+$/i):8==n?null===m.match(/^-?[0-7]+$/):2!=n||null===m.match(/^-?[01]+$/):null===m.match(/^[+-]?[0-9]+$/))||isNaN(g=parseInt(m,n))||(k&&(0>g&&(g+=Math.pow(2,36)),g=0<k?g*Math.pow(2,k):Math.trunc(g/Math.pow(2,-k))),h=g)}g=h;void 0==g&&("true"==e?g=!0:"false"==e?g=!1:(g=e,e='"'+e+'"'));b[q]=
g;a.da("overriding %s property '%s' with %s\n",a.va,q,e)}}a.ha=b;c=b.bindings;c=void 0===c?{}:c;if("undefined"!=typeof document){a.ha.la||(a.ha.la=c);(d=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.va);for(var p in c){e=c[p];if(d)p=e;else if(e.match(/^[0-9]+$/)){var q=+e;a.la[p]=[];do{e=p+q++;e=document.getElementById(e);if(!e)break;a.la[p].push(e)}while(1);continue}if(q=document.getElementById(e))a.la[p]=q,a.Oa(p,q)}}b=void 0===b?{}:b;a.version=3;if(a.version){p=
"";var r;a.na!=a.va&&(r=gb(a,a.na).version)&&r!=a.version&&(p="Machine");p||(r=b.version)&&r>a.version&&(p="Config");p&&(r=a.Aa("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.$e,a.version,p,r),a.error("%s\n\nClearing your browser's cache may resolve the issue.",r))}}function ib(a,b){var c;try{var d=D[a.na];if(d)for(c in d){var e=d[c];if(e.va!=e.na&&!b(e))return!1}return!0}catch(g){a.da("error while enumerating device '%s': %s\n",c,g.message)}return!1}
Q.prototype.Za=function(a,b){b=void 0===b?!1:b;if(a){var c=I.prototype.Za.call(this,a,b);if(void 0===c&&b){b=D[this.na];for(var d in b)if(c=b[d].la[a])break;c||(c=null);this.la[a]=c}}return c};function gb(a,b){var c=b,d=a.na,e=d.indexOf(".");0<e&&(d=d.substr(0,e),b=b.substr(e+1));b=(e=D[d])&&e[b]||null;if(!b){for(e=0;e<ra.length;e++)if(ra[e].id===c){b=ra[e];break}if(!b)throw Error(a.Aa('no "%s" device',c));}return b}
function R(a,b,c){var d=null,e=D[a.na];if(e)for(var g in e)if(e[g].ha["class"]==b){if(d){d=null;break}d=e[g]}if(!d&&(void 0===c||c))throw Error(a.Aa("no %s device",b));return d}function jb(a){return a==a.oa&&a.ready?ib(a,function(b){return jb(b)}):a.ready}function kb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(jb(a)){for(;b=a.Wb.pop();)b();a!=a.oa&&kb(a.oa)}}function lb(a,b){if(jb(a))return b(),!0;a.Wb.push(b);return!1}
Q.prototype.da=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&Ra(this,a)&&(void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1)),this.oa.Ca&B.Db&&(void 0===this.Pa&&(this.Pa=R(this,"CPU")),this.Pa))?(a=b.shift(),I.prototype.da.call(this,"%#06x: %s.%s\n",this.Pa.Ed,this.va,this.Aa.apply(this,[a].concat(v(b))).trim())):I.prototype.da.call.apply(I.prototype.da,[this,a].concat(v(b)))};function mb(a,b){(a=D[a.na])&&delete a[b]}B.Db=1;B.wc=2;B.Ic=4;B.Uc=8;B.ad=16;B.xc=32;B.Sc=64;B.fd=128;
B.Vc=256;B.zc=512;B.Wc=1024;B.INT=2048;B.qd=4096;B.ud=8192;B.Xc=16384;B.cd=32768;B.Dc=65536;B.Nc=131072;B.kb=262144;B.od=524288;B.Lb=1048576;B.Qb=2097152;B.Tb=4194304;B.Yc=8388608;B.pd=16777216;B.Rc=33554432;B.lb=67108864;B.Hc=134217728;B.Qc=268435456;B.Md=4294967296;N.addr=B.Db;N.bus=B.wc;N.fault=B.Ic;N.memory=B.Uc;N.ports=B.ad;N.chips=B.xc;N.kbd=B.Sc;N.serial=B.fd;N.misc=B.Vc;N.cpu=B.zc;N.mmu=B.Wc;N["int"]=B.INT;N.trap=B.qd;N.video=B.ud;N.monitor=B.Xc;N.screen=B.cd;N.disk=B.Dc;N.file=B.Nc;
N.time=B.kb;N.timer=B.od;N.event=B.Lb;N.input=B.Qb;N.key=B.Tb;N.mouse=B.Yc;N.touch=B.pd;N.info=B.Rc;N.warn=B.lb;N.error=B.Hc;N.halt=B.Qc;E.Device=Q;
function nb(a,b,c){Q.call(this,a,b,c);this.type="static"==this.ha.type?ob:pb;this.fa=this.ha.addrWidth||16;this.ba=Math.pow(2,this.fa);this.blockSize=this.ha.blockSize||(16<this.fa?4096:1024);this.blockSize>this.ba&&(this.blockSize=this.ba);this.ja=this.ba/this.blockSize|0;this.ca=Math.log2(this.blockSize)|0;this.ga=(1<<this.ca)-1;this.ia=this.ha.dataWidth||8;this.aa=Array(this.ja);this.ea=0;a=new S(a,b+"[NONE]",{size:this.blockSize,bus:this.va});for(b=0;b<this.ba;b+=this.blockSize)qb(this,b,this.blockSize,
T.NONE,a);a=this.ea;this.ea+=this.type;a&&this.ea||(this.ab=this.bb)}z(nb,Q);
function qb(a,b,c,d,e){for(var g=b>>>a.ca;0<c&&g<a.aa.length;){var f=g*a.blockSize,h=a.blockSize-(b-f);h>c&&(h=c);var m=a.aa[g];if(b!=f||h!=a.blockSize||m&&m.type!=T.NONE)break;var n=m=void 0,l=b,k=a.fa,p=16;k=void 0===k?0:k;m=void 0===m?0:m;var q="",r="",x=-1;p||(p=a.ka||10);k&&(x=Math.ceil(k/Math.log2(p)));if(void 0==n)switch(p){case 8:n="0o";break;case 16:n="0x";break;case 10:r=".";default:n=""}isNaN(l)||"number"!=typeof l?(l=void 0,n=r=""):(0>l&&-1<l&&(l=-1),k&&(0>l&&(l+=Math.pow(2,k)),l>=Math.pow(2,
k)&&(x=Math.ceil(Math.log(l)/Math.log(p)))));for(k=m||-1;x--;){k||(q=","+q,k=m);if(void 0==l){if(q="?"+q,0>x)break}else{var w=l%p;l=Math.trunc(l/p);w+=0<=w&&9>=w?48:55;q=String.fromCharCode(w)+q;if(!l&&0>x)break}k--}m=a.va+"["+(n+q+r)+"]";b=e?e.size==a.blockSize?e:new S(a.na,m,{type:d,Ab:b,size:h,bus:a.va}):new S(a.na,m,{type:d,Ab:b,size:h,bus:a.va});a.aa[g]=b;b=f+a.blockSize;c-=h;g++}}t=nb.prototype;t.Ea=function(){void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};t.Ga=function(){};
t.Bb=function(a){return a&&this.Ka(a)?!0:!1};t.Cb=function(a){this.La(a)};t.Ka=function(a){for(var b=0;b<this.aa.length;b++){var c=this.aa[b];if((this.type==pb||c.type&T.jb)&&c.Ka){var d=a.shift();if(!c.Ka(d))return!1}}return!0};t.La=function(a){for(var b=0;b<this.aa.length;b++){var c=this.aa[b];if((this.type==pb||c.type&T.jb)&&c.La){var d=[];c.La(d);a.push(d)}}};t.bb=function(a,b){this.aa[a>>>this.ca].ab(a&this.ga,b)};var ob=0,pb=1;E.Bus=nb;
function S(a,b,c){Q.call(this,a,b,c);this.Ab=this.ha.addr;this.size=this.ha.size;this.type=this.ha.type||T.NONE;this.ca=(a=this.ha.bus)?gb(this,a):R(this,a="Bus");if(!this.ca)throw Error(this.Aa("unable to find bus '%s'",a));this.ja=this.ca.ia;this.fa=this.ia=!1;this.values=this.ba=null;a=this.bb;if(this.ca.type==ob){a=this.Gd;if(b=8==this.ja)b=gb(this,this.na),b=!1!==(b&&b.ha&&b.ha.ArrayBuffer||this.ha.ArrayBuffer);b&&(this.ia=!0)}switch(this.type){case T.NONE:this.ab=this.rc;break;case T.bc:this.ab=
this.rc;break;case T.jb:this.ab=a}rb(this,this.ha.values);sb(this)}z(S,Q);function rb(a,b){"string"==typeof b?(kb(a,!1),Oa(b,function(c,d,e,g){if(4==e)if(!g&&d){try{var f=JSON.parse(d);rb(a,f.values)}catch(h){a.da("error (%s) parsing resource: %s\n",h.message,c)}kb(a,!0)}else a.da("error (%d) loading resource: %s\n",g,c)})):a.ha.values=b}
function sb(a,b){if(a.type>T.NONE&&(a.ia?(a.ba=new ArrayBuffer(a.size),new DataView(a.ba,0,a.size),a.values=new Uint8Array(a.ba,0,a.size),new Uint16Array(a.ba,0,a.size>>1),new Int32Array(a.ba,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}t=S.prototype;
t.Ga=function(){if(this.ha.values)a:{var a=this.ca,b=this.Ab,c=this.size,d=this.ha.values,e=0,g=b&a.ga;b>>>=a.ca;c>d.length&&(c=d.length);for(;0<c&&b<a.aa.length;){var f=a.aa[b++];if(!f)break a;for(;0<c&&g<f.size;)f.bb(g++,d[e++]),c--;g=0}}else this.type&T.jb&&this.values&&this.values.fill(0)};t.rc=function(){};t.bb=function(a,b){this.values[a]=b};t.Gd=function(a,b){this.values[a]=b;this.fa=!0;this.ab=this.bb};
t.Ka=function(a){if(a){var b=a.shift();if(this.va==b){this.fa=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],g=a[d++];e--;)c[b++]=g;a=c}sb(this,a)}return!0}}return!1};
t.La=function(a){a.push(this.va);a.push(this.fa);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var g=b[c],f=c+1;f<b.length&&b[f]===g;)f++;e[d++]=f-c;e[d++]=g;c=f}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var T={NONE:1,bc:2,jb:4,Ve:14,Ze:12};E.Memory=S;
function tb(a,b,c){c.type=T.bc;S.call(this,a,b,c);qb(this.ca,this.ha.addr,this.ha.size,this.ha.type,this);lb(this,this.Ga.bind(this));this.Pa=this.Ja=void 0;if(E.LED&&this.la[ub]){var d=this;this.ea=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.ga=this.values.length/this.ea|0;this.aa=new vb(a,b+"LEDs",{"class":"LED",bindings:{container:Ka(this,ub)},type:wb,cols:this.ea,rows:this.ga,color:K(this,"colorROM","green"),backgroundColor:K(this,"backgroundColorROM","black"),persistent:!0}),
xb(this.aa,!0);this.ka=new yb(a,b+"Input",{"class":"Input",location:[0,0,this.aa.za,this.aa.ya,this.ea,this.ga],bindings:{surface:Ka(this,ub)}});this.ma=La(this)||"";zb(this.ka,function(e,g){if(d.Pa){var f=d.ma;0<=e&&0<=g&&(f="");$a(d,Ma,f)}})}}z(tb,S);
tb.prototype.Ka=function(a){var b=!0,c=a.shift();if(c&&this.aa){var d=c.length;this.aa.aa.length==d?(this.aa.aa=c,Ab(this.aa,!0)):(this.da("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.da("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};tb.prototype.Ea=function(){void 0===this.Pa&&(this.Pa=R(this,"CPU"));void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};
tb.prototype.La=function(a){this.aa&&(a.push(this.aa.aa),a.push(this.values))};var ub="array",Ma="cellDesc";E.ROM=tb;
function yb(a,b,c){Q.call(this,a,b,c);this.Ca=B.Qb;this.ka=this.qa=null;this.time=R(this,"Time");this.oa=R(this,"Machine");this.wa=K(this,"drag",!1);this.ma=K(this,"scroll",!1);this.za=K(this,"hexagonal",!1);this.fa=K(this,"releaseDelay",0);this.ga=!1;a=this.ha.map;this.ba=this.ca=null;if(a)if(a.length)this.ba=a;else{this.ca={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],g=b[d],f=a[g];"string"==typeof f?f=[f]:void 0==f.length&&(e=f.grid,f=f.keys,"string"==typeof f&&(f=[f]));this.ca[g]={keys:f,
grid:e,state:0}}}this.ra=[];this.sa=[];this.ea=this.ta=null;(a=this.la[Bb])&&Cb(this,a,this.Za(c.focusBinding,!0),this.ha.location);this.Ga()}z(yb,Q);function zb(a,b){a.qa=b}function Db(a,b){a.ka=b}function Eb(a,b,c){for(var d=0;d<a.ra.length;d++){var e=a.ra[d];e.id===b&&e.nc(b,c)}}
function Cb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.ba||a.ca){var e={};e.Hd=d[0]||0;e.Id=d[1]||0;e.Ya=d[2]||b.clientWidth;e.mb=d[3]||b.clientHeight;e.nb=d[4]||1;e.qb=d[5]||1;e.yd=d[6]||b.naturalWidth||e.Ya;e.Ad=d[7]||b.naturalHeight||e.mb;e.sc=d[8]||0;e.tc=d[9]||0;e.xd=d[10]||0;e.zd=d[11]||0;a.ba?(e.pb=a.ba.length,e.$a=a.ba[0].length):(e.$a=e.nb,e.pb=e.qb,e.nb=e.qb=0);e.kc=e.Ya/(e.$a+e.$a*e.nb)|0;e.lc=e.mb/(e.pb+e.pb*e.qb)|0;e.wd=e.kc*e.nb|0;e.mc=e.lc*e.qb|0;e.cb=e.rb=-1;Fb(a,b,e);Gb(a,b,e);a.time&&
a.fa&&(a.ya=Hb(a.time,"timerInputRelease",function(){0>e.cb&&0>e.rb&&Ib(a,-1,-1)}))}if(a.ba||a.ca)a.time&&a.fa&&(a.Ba=Hb(a.time,"timerKeyRelease",function(){Jb(a)})),a.ia=0,a.pa="",a.ja=[],d=b,c&&(d=c,a.ea||"BUTTON"!=c.nodeName||(d=document,a.ea=c,Kb(a,b),a.ta=b)),Kb(a,d),a.ea||(a.ea=d)}function Lb(a){a.fa?Mb(a.time,a.Ba,a.fa):Jb(a)}
function Kb(a,b){function c(e,g,f){var h=document.activeElement;a.da(B.Tb+B.Lb,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,g,Date.now()/1E3%60,void 0!=f?f?"used":"unused":"ignored")}function d(e,g){e=document.activeElement;return a.ea&&e!=a.ea&&e!=a.ta?null:g||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var g=e.which||e.keyCode,f=Nb(a,g,!0,e);c("Down",g,f);f&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var g=e.which||e.charCode,f=
Nb(a,g);c("Press",g,f);f&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var g=e.which||e.keyCode,f=Nb(a,g,!1,e);c("Up",g);f&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function Fb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.ga){var e=a.ea;if(e){var g=window.scrollX,f=window.scrollY;e.focus();window.scrollTo(g,f)}d.button||U(a,b,Ob,d,c)}});b.addEventListener("mousemove",function(d){a.ga||U(a,b,Pb,d,c)});b.addEventListener("mouseup",function(d){a.ga||d.button||U(a,b,Qb,d,c)});b.addEventListener("mouseout",function(d){a.ga||(0>c.cb?U(a,b,Pb,d,c):U(a,b,Qb,d,c))})}
function Gb(a,b,c){b.addEventListener("touchstart",function(d){a.ma&&(a.ga=!0);U(a,b,Ob,d,c)});b.addEventListener("touchmove",function(d){U(a,b,Pb,d,c)});b.addEventListener("touchend",function(d){U(a,b,Qb,d,c)})}
function Nb(a,b,c,d){if(void 0!=c){var e=cb[b]||b;var g=eb[b];var f=Rb[e];d=d&&d.location==db.yb;f&Sb&&d&&(f>>=1);f&&(f&Tb&&(c=!(a.aa&f)),a.aa=c?a.aa|f:a.aa&~f,Eb(a,e,c))}else g=String.fromCharCode(b).toUpperCase(),b>=ab.tb&&b<=ab.zb?a.aa&(Ub|Vb)||(a.aa|=Vb,Eb(a,M.vb,!0)):b>=ab.a&&b<=ab.z&&a.aa&Vb&&(a.aa&=~Vb,Eb(a,M.vb,!1));if(a.ba){if(void 0!=c)return!1;for(e=0;e<a.ba.length;e++)for(f=a.ba[e],d=0;d<f.length;d++)if(0<=f[d].split("|").indexOf(g))return a.ia?16>a.ja.length&&a.ja.push(b):(a.ia=1,a.pa=
g,Ib(a,d,e),Eb(a,g,!0),Lb(a)),!0}if(a.ca){if(void 0==c)return!0;b=Object.keys(a.ca);for(e=0;e<b.length;e++)if(f=b[e],0<=a.ca[f].keys.indexOf(g))return Eb(a,f,c),a.ca[f].state=c?1:0,!0}return!1}function Jb(a){1==a.ia?(a.ia++,Eb(a,a.pa,!1),a.pa="",Ib(a,-1,-1),Lb(a)):(a.ia=0,a.ja.length&&Nb(a,a.ja.shift()))}yb.prototype.Ga=function(){this.aa=0;this.ua=this.xa=-1};
function U(a,b,c,d,e){var g=-1,f=-1,h=!1,m=-1,n=-1;if(c<Qb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(m=d.targetTouches[0].clientX,n=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(m=d.clientX,n=d.clientY);var l=d.target.getBoundingClientRect();m-=l.left;n-=l.top;m=e.yd/b.offsetWidth*m|0;n=e.Ad/b.offsetHeight*n|0;var k=m-e.Hd;var p=n-e.Id;var q=l=!1;var r=m>=e.sc&&m<e.sc+e.xd&&n>=e.tc&&n<e.tc+e.zd;if(0<=k&&k<e.Ya&&0<=p+e.mc||r)if(h||a.ma||d.preventDefault(),0<=k&&k<e.Ya&&
0<=p&&p<e.mb){q=!0;d=e.Ya/e.$a|0;var x=e.mb/e.pb|0,w=k/d|0,u=p/x|0;!a.za||u&1||(k-=d>>1,w=k/d|0,w==e.$a-1&&(k=-1));x=u*x+(e.mc>>1);k-=w*d+(e.wd>>1);p-=x;0<=k&&k<e.kc&&0<=p&&p<e.lc&&(g=w,f=u,l=!0)}}k=k||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Ob||c==Qb)for(w=0;w<a.sa.length;w++)u=a.sa[w],c==Qb?u.nc(u.id,!1):(x=p/(b/u.bf|0)|0,(k/(d/u.af|0)|0)==u.pf&&x==u.qf&&u.nc(u.id,!0));if(!h)if(c==Ob)e.cb=m,e.rb=n,q?(Ib(a,g,f),l&&a.fa&&Mb(a.time,a.ya,a.fa,!0)):r&&a.oa.Ea();else if(c==Pb)0<=e.cb&&0<=e.rb&&
a.wa?Ib(a,g,f):a.qa&&a.qa(g,f);else if(c==Qb){if(c=a.fa)c=a.time,g=a.ya,c=c.aa&&0<g&&g<=c.ba.length?0<=c.ba[g-1].Da:!1;c||Ib(a,-1,-1);e.cb=e.rb=-1}else a.da("unrecognized action: %d\n",c)}function Ib(a,b,c){if(b!=a.ua||c!=a.xa)a.ua=b,a.xa=c,a.ka&&a.ka(b,c)}var Ob=1,Pb=2,Qb=3,Bb="surface",Ub=3,Sb=170,Vb=512,Tb=3584,V={},Rb=(V[M.hd]=2,V[M.Ac]=8,V[M.vc]=32,V[M.Hb]=128,V[M.vb]=Vb,V[M.$c]=1024,V[M.dd]=2048,V);E.Input=yb;
function vb(a,b,c){Q.call(this,a,b,c,["color","backgroundColor"]);a=this.la[Wb];if(!a)throw Error("LED "+this.ha.la[Wb]+" binding for '"+Wb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Ta=Ka(this,Wb)+".canvas";b.setAttribute("id",this.Ta);this.Ra=a;this.type=Na(K(this,"type",wb,Xb),Yb,Zb);this.ja=$b[this.type][0];this.pa=$b[this.type][1];this.width=K(this,"width",
this.ja);this.height=K(this,"height",this.pa);this.ea=K(this,"cols",1);this.ca=this.ea+K(this,"colsExtra",0);this.xa=K(this,"rows",1);this.fa=this.xa+K(this,"rowsExtra",0);this.za=this.width*this.ea;this.ya=this.height*this.xa;this.ia=ac("black",0);this.ga=bc(this.ha.color)||this.ia;this.hb=ac(this.ga,1,.25);this.gb=ac(this.ga,1,2);this.ma=bc(this.ha.backgroundColor);this.ib=K(this,"fixed",!1);this.ib||(b.style.width="100%",b.style.height="auto");this.Qa=K(this,"hexagonal",!1);this.xb=K(this,"highlight",
!0);this.Ha=K(this,"persistent",this.type<Zb);b.setAttribute("width",this.za.toString());b.setAttribute("height",this.ya.toString());b.style.backgroundColor=this.ia;a.appendChild(b);this.Sa=b.getContext("2d");if(this.sa=document.createElement("canvas"))this.sa.width=this.Na=this.ja*this.ea,this.sa.height=this.ua=this.pa*this.xa,this.ba=this.sa.getContext("2d");this.Va=(this.fa+1)*this.ca*4;this.aa=Array(this.Va);this.ra=null;this.Wa=this.ea<this.ca?4*(this.ca-this.ea):0;this.ka=this.ta=!1;this.Ia=
0;this.Ba=!0;this.qa=0;this.wa=-1;var d=this;this.time=R(this,"Time");cc(this.time,function(e,g){Ab(d,!1,e,g)});xb(d,!0)}z(vb,Q);function xb(a,b){dc(a,a.aa);a.ka=a.ta=!0;b&&Ab(a,!0)}function ec(a){a.ma?(a.ba.fillStyle=a.ma,a.ba.fillRect(0,0,a.Na,a.ua)):a.ba.clearRect(0,0,a.Na,a.ua)}
function Ab(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.ka||b){if(a.type<Zb){d=0;if(!a.Ha||b)ec(a);else if(a.qa){d=a.ea-a.qa;var e=a.ja*d;a.ba.drawImage(a.sa,a.ja*a.qa,0,e,a.ua,0,0,e,a.ua)}for(var g=e=0;g<a.fa;g++){for(var f=0;f<a.ea;f++){var h=a.aa[e],m=a.aa[e+1]||a.ia,n=!1,l=!!(a.aa[e+3]&W),k=a.xb&&e==a.wa;!a.Ba&&h&&(h=fc,l=n=!0);if(l||k||b){if(f>=d)a:{l=a;var p=h;h=m;var q=f;m=g;var r=k;q=void 0===q?0:q;m=void 0===m?0:m;r=void 0===r?!1:r;var x=0;if(l.Qa&&!(m&1)&&(x=l.ja>>
1,q==l.ea-1))break a;if(h&&h!=l.ga){r=r?ac(h,1,2):h;var w=ac(h,1,.25)}else r=r?l.gb:l.ga,w=l.hb;h=!1;p=p?r:w;r==l.ia&&(p=l.ma,h=!0);r=q*l.ja+x;w=m*l.pa;l.Ha&&(q=q*l.ja+x,m*=l.pa,l.ma?(l.ba.fillStyle=l.ma,l.ba.fillRect(q,m,l.ja,l.pa)):l.ba.clearRect(q,m,l.ja,l.pa));l.ba.fillStyle=p;m=gc[l.type];3==m.length?(l.ba.beginPath(),l.ba.arc(r+m[0],w+m[1],m[2],0,2*Math.PI),h?(l.ba.globalCompositeOperation="destination-out",l.ba.fill(),l.ba.globalCompositeOperation="source-over"):l.ba.fill()):l.ba.fillRect(r+
m[0],w+m[1],m[2],m[3])}a.aa[e+3]=k||n?a.aa[e+3]|W:a.aa[e+3]&~W}e+=4}e+=a.Wa}a.qa=0}else{b="";for(d=0;d<a.aa.length;d+=4)b+=a.aa[d]||" ",a.aa[d+3]&hc&&(b+=".");ec(a);for(g=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;f=a;n=e;k=g;n=void 0===n?0:n;k=void 0===k?0:k;if(l=ic[l])for(m=0;m<l.length;m++)if(h=f,q=jc[l[m]]){x=(void 0===n?0:n)*h.ja;p=(void 0===k?0:k)*h.pa;h.ba.fillStyle=h.ga;h.ba.beginPath();if(3==q.length)h.ba.arc(x+q[0],p+q[1],q[2],0,2*Math.PI);else for(r=0;r<q.length;r+=2)r?h.ba.lineTo(x+q[r],
p+q[r+1]):h.ba.moveTo(x+q[r],p+q[r+1]);h.ba.closePath();h.ba.fill()}if(++e==a.ea&&(e=0,++g==a.fa))break}}a.Sa.globalCompositeOperation=a.ma&&a.ga!=a.ia?"source-over":"copy";a.Sa.drawImage(a.sa,0,0,a.Na,a.ua,0,0,a.za,a.ya);a.ka=!1;a.wa=-1}else a.Ha||a.ta||(!c||!a.Ia||c-a.Ia>=(1E3/d|0))&&xb(a,!0);a.ta=!1;c&&(a.Ia=c)}function kc(a,b){b=void 0===b?!0:b;a.Ba!=b&&(a.Ba=b,a.ka=!0)}function lc(a,b,c){b=4*(c*a.ca+b);return b<=a.aa.length-4?a.aa[b+2]:0}
function mc(a,b,c){var d;b=4*(c*a.ca+b);b<=a.aa.length-4&&(d=a.aa[b]);return d}function bc(a){return(a=a||void 0)&&fb[a]||a}function ac(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=fb[a]||a;if(nc(a,d)){a="rgba(";var e;for(e=0;3>e;e++){var g=Math.round(d[e]*c);g=0>g?0:255<g?255:g;a+=g+","}a+=(e<d.length?d[e]:b)+")"}}return a}function dc(a,b){for(var c=0;c<b.length;c+=4)oc(a,b,c)}function oc(a,b,c){b[c]=a.type<Zb?fc:" ";b[c+1]=a.ga==a.ia?null:a.ga;b[c+2]=0;b[c+3]=W}
vb.prototype.Ka=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.ga&&c==this.ma&&a&&a.length==this.aa.length){this.aa=a;for(b=0;b<=this.aa.length-4;b+=4)this.aa[b+1]==this.ia&&(this.aa[b+1]=null);Ab(this,!0);return!0}return!1};function nc(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}
vb.prototype.La=function(a){this.aa&&(a.push(this.ga),a.push(this.ma),a.push(this.aa))};function pc(a,b,c,d){var e=null;0<=c&&c<a.fa&&0<=b&&b<a.ca&&(e=!1,d=d||a.ga,d==a.ia&&(d=null),b=4*(c*a.ca+b),a.aa[b+1]!==d&&((a.aa[b+1]=d)||(a.aa[b]=fc),a.aa[b+3]|=W,a.ka=e=!0),a.wa=b,a.ta=!0);return e}function qc(a,b,c,d){if(0<=c&&c<a.fa&&0<=b&&b<a.ca){b=4*(c*a.ca+b);c=0;if(a.aa[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.aa[b+2]!==c&&(a.aa[b+2]=c,a.aa[b+3]|=W,a.ka=!0);a.wa=b;a.ta=!0}}
function rc(a,b,c,d){var e=!1,g=0&sc;b=4*(c*a.ca+b);if(b<=a.aa.length-4){if(a.aa[b]!==d||(a.aa[b+3]&sc)!==g)a.aa[b]=d,a.aa[b+3]=a.aa[b+3]&~sc|g|W,a.ka=e=!0;a.wa=b;a.ta=!0;a.qa=0}return e}
var Yb=0,wb=1,Zb=3,Xb={small:Yb,round:wb,square:2,digit:Zb},Wb="container",fc=0,sc=129,hc=1,W=128,tc={},gc=(tc[Yb]=[4,4,4],tc[wb]=[16,16,14],tc[2]=[2,2,28,28],tc),$b=[[8,8],[32,32],[32,32],[96,128]],jc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},ic={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};E.LED=vb;
function uc(a,b,c){Q.call(this,a,b,c);this.Sa=K(this,"cyclesMinimum",1E5);this.hb=K(this,"cyclesMaximum",1E9);this.Ta=Na(K(this,"cyclesPerSecond",1E6),this.Sa,this.hb);this.xa=60;this.za=0;this.ta=1E3/this.xa;this.ld=K(this,"updatesPerSecond",2)||2;this.bd=1E3/this.ld;this.gb=0;this.sd=K(this,"timeLock",!0);this.Qa=this.qa=0;this.Na=this.ia=1;this.Wa=this.ka=this.Ta/1E4/100;this.Ba=[];this.ma=[];this.ba=[];this.Ha=[];this.Va=this.aa=this.ya=this.ja=!1;this.pa=this.ea=0;a=Ia("requestAnimationFrame");
if(!a){a="setTimeout";var d=this.ta}this.ib=window[a].bind(window,this.Fd.bind(this),d);this.xb=window[Ia("cancelAnimationFrame")||"clearTimeout"].bind(window);this.wa=this.ua=this.fa=this.ca=this.Ra=0;vc(this)||wc(this,this.Na)}z(uc,Q);function cc(a,b){a.Ba.push(b)}t=uc.prototype;
t.Oa=function(a,b){var c=this;switch(a){case xc:b.onclick=function(){yc(c)&&(c.aa?zc(c):c.start())};break;case Ac:b.onclick=function(){wc(c,c.ia<<1);Bc(c,Cc(c.ka))};break;case Dc:b.onclick=function(){yc(c)&&(c.aa?c.da("already running\n"):c.ea?zc(c):Ec(c))};break;case Fc:b.addEventListener("mousedown",function(){c.ja=!0}),b.addEventListener("mouseup",function(){vc(c);c.ja=!1}),b.addEventListener("mousemove",function(){c.ja&&vc(c)}),b.addEventListener("change",function(){c.ja=!0;vc(c);c.ja=!1})}Q.prototype.Oa.call(this,
a,b)};function Hb(a,b,c){var d=void 0===d?-1:d;var e=a.ba.length+1;a.ba.push({id:b,vd:c,ob:d,Da:-1});0<=d&&Mb(a,e,d);return e}
function Gc(a,b,c,d){var e=0,g=a.ka,f=1E6*g;b&&c&&(g=b/(10*c)/100,a.da(B.kb,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,g),d>a.ta&&(1<a.ia&&(a.ia>>=1,a.da(B.lb,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.ta,a.ia)),e=d));a.qa=g;a.Qa=g/a.Wa;b=a.Qa/a.ia;a.Ra=f/b/a.xa+1E-8;a.da(B.kb,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.Ra,f,b,a.xa);return e}
function Hc(a,b){a.ua=a.fa=b;if(!a.ma.length)return a.fa=0,a.ua;for(var c=0;0<a.fa;){if(c<a.ma.length){var d=a.ma[c++];b=d.pc.call(d,b)||1}else c=b=0;a.fa-=b}return a.ua-a.fa}function Ic(a,b){b=void 0===b?a.ua-a.fa:b;if(!a.aa){if(a.ca)for(var c=0;c<a.ma.length;c++){var d=a.ma[c];d.qc.call(d)}a.ca=b}a.ca-=b;1>a.ca&&(a.ya=!0);a.wa+=b;a.ua=a.fa=0;a.aa||(a.wa=0);return b}
function Jc(a,b){b=void 0===b?0:b;if(b){var c=b;a.ca+=b}else for(c=a.ca,1>c&&(c=a.ca+=a.Ra),0>c&&(a.da(B.lb,"warning: cycle count dropped below zero: %f\n",c),c=a.ca=0),c|=0,b=a.ba.length;0<b;b--){var d=a.ba[b-1];!(0>d.Da)&&c>d.Da&&(c=d.Da)}return c}function Cc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function yc(a){return a.Va?!0:(a.da("not powered\n"),!1)}
function Kc(a,b){if(1<=b)for(var c=a.ba.length;0<c;c--){var d=a.ba[c-1];0>d.Da||(d.Da-=b,0>=d.Da&&(d.Da=-1,d.vd(),0<=d.ob&&Mb(a,c,d.ob)))}}t.Ea=function(a){this.Va=a;void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};
t.Fd=function(a){a=void 0===a?Date.now():a;this.pa=0;if(this.aa){if(this.za){var b=a-this.za;1>b&&(b=16.67);this.xa=1E3/b}this.za=a;a=Date.now();this.ra&&(b=a-this.sa-this.ta,b>this.ta&&(this.ga+=b,this.da(B.lb,"warning: browser throttling detected, compensating by %5.3fms\n",b)));this.sa=a;this.ga||(this.ga=a);this.Ia=0;try{this.ya=!1;do Kc(this,Ic(this,Hc(this,Jc(this))));while(this.aa&&!this.ya)}catch(c){this.da("%s\n",c.message),zc(this)}this.ra=Date.now();this.Ia&&(this.ga+=this.Ia,this.sa+=
this.Ia);this.sa+=Gc(this,this.wa,this.ra-this.ga,this.ra-this.sa);this.ra-this.gb>=this.bd&&this.update();for(a=0;a<this.Ba.length;a++)this.Ba[a](this.za,this.xa);this.pa=this.ib()}};function wc(a,b){if(void 0!==b){if(1>b||!a.ja&&0<a.qa&&a.qa<.9*a.ka)b=a.Na;a.ia=b;b=a.Wa*a.ia;a.ka!=b&&(a.ka=b,Bc(a,Cc(a.ka)))}a.ga=a.ra=0;a.ca=a.wa=0;Gc(a);for(b=a.ba.length;0<b;b--){var c=a.ba[b-1];0<=c.ob&&Mb(a,b,c.ob,!0)}}
function vc(a){var b=a.la[Fc];return b?(wc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.hb-a.Sa)+a.Sa)/a.Ta|0),!0):!1}function Mb(a,b,c,d){0<b&&b<=a.ba.length&&(b=a.ba[b-1],d||0>b.Da)&&(c=Math.ceil(a.Ta*(a.sd?a.Na:a.Qa)/1E3*(void 0===c?1E3:c)),a.aa&&(c+=Ic(a)),b.Da=c)}t.start=function(){if(this.aa||this.ea)return!1;this.aa=!0;this.ga=this.ra=0;this.update(!0);this.pa=this.ib();return!0};
function Ec(a,b){b=void 0===b?1:b;a.aa||(b&&!a.ea&&(a.ea=b),a.ea&&(a.ea--,Kc(a,Ic(a,Hc(a,Jc(a,1)))),a.update(!1),a.ea&&setTimeout(function(){Ec(a,0)},0)))}function zc(a){a.aa?(a.aa=!1,Ic(a),a.pa&&(a.xb(a.pa),a.pa=0),a.update(!0)):a.ea&&(a.ea=0,a.update(!0))}
t.update=function(a){a&&this.da(this.aa?"started with %s target\n":"stopped\n",Cc(this.ka));$a(this,xc,this.aa?"Halt":"Run");$a(this,Dc,this.ea?"Stop":"Step");this.ja||(this.da(B.kb,"getSpeedCurrent(%5.3fhz)\n",1E6*this.qa),Bc(this,this.aa&&this.qa?Cc(this.qa):"Stopped"));for(a=0;a<this.Ha.length;a++){var b=this.Ha[a];b.Cd.call(b)}this.gb=Date.now();this.ya=!0};function Bc(a,b){$a(a,Lc,b);$a(a,Ac,b)}var xc="run",Ac="setSpeed",Lc="speed",Dc="step",Fc="throttle";E.Time=uc;
function Z(a,b,c){c["class"]="CPU";Q.call(this,a,b,c);this.Ja=void 0;this.Ed=0;this.time=R(this,"Time");this.time.ma.push(this);this.time.Ha.push(this);this.sa=this.qa=0}z(Z,Q);Z.prototype.abort=function(a){this.da("%s\n",a.message);zc(this.time)};Z.prototype.pc=function(a){this.sa=this.qa=void 0===a?0:a;return this.oc()};Z.prototype.qc=function(){this.sa-=this.qa;this.qa=0};Z.prototype.oc=function(){return this.sa-this.qa};
function Mc(a,b,c){Z.call(this,a,b,c);this.ka=K(this,"wrap",!1);this.ta=(this.xa=K(this,"font",""))&&Nc[this.xa]||Nc.Helvetica;this.ua=K(this,"rule","");this.pa=K(this,"pattern","");Oc(this,this.ya=K(this,"message",""));this.Ia=K(this,"toggleColor",!1);this.Ha=Array(Pc(this).length);if(c=R(this,"LED",!1)){this.aa=c;Qc(this)||xb(c,!0);this.ra=R(this,"Input",!1);var d=this;this.za=new yb(a,b+"Input",{"class":"Input",location:[0,0,c.za,c.ya,c.ea,c.xa],drag:!(!this.ra||!this.ra.wa),scroll:!(!this.ra||
!this.ra.ma),hexagonal:c.Qa,bindings:{surface:c.Ta}});Db(this.za,function(e,g){var f=d.aa;0<=e&&0<=g&&(d.ja?pc(f,e,g,d.ja)?rc(f,e,g,1):d.Ia?pc(f,e,g):rc(f,e,g,1-mc(f,e,g)):rc(f,e,g,1-mc(f,e,g)),qc(f,e,g,Pc(d,!!mc(f,e,g))),Ab(f))});this.ia=[];this.Ba=c.ga;Rc(this,this.Ba);Sc(this);Tc(this,this.ha[Uc]);Ga(this,this.Bd.bind(this))}}z(Mc,Z);t=Mc.prototype;
t.Oa=function(a,b){var c=this,d;switch(a){case Vc:case Wc:b.onchange=function(){Xc(c,a)};Xc(this);break;case Uc:b.onchange=function(){Tc(c)};break;case Yc:Fa(b,Zc(this.ha[Yc]),!1,this.ha.pattern);b.onchange=function(){var e=c.la[Yc];e&&e.options.length&&((e=e.options[e.selectedIndex].value)?Qc(c,e):c.Ga())};break;case $c:b.onclick=function(){var e=ad(c,!0),g=c.la[bd];g&&(e='"'+g.value+'":"'+e.replace(/^([0-9]+\/)*/,"")+'",');c.da("%s\n",e)};break;case cd:b.onclick=function(){var e=ad(c);c.da("%s\n",
e);var g=window.location.href;g=0<=g.indexOf("pattern=")?g.replace(/(pattern=)[^&]*/,"$1"+e.replace(/\$/g,"$$$$")):g+((0>g.indexOf("?")?"?":"&")+"pattern="+e);window.location=g};break;case bd:b.onkeypress=function(e){b.value=String.fromCharCode(e.charCode);var g=c.la[dd];g&&(g.textContent=b.value);e.preventDefault()};break;default:a.startsWith(ed)?b.onclick=function(){Sc(c,a)}:(d=this.ha[Yc])&&d[a]&&(b.onclick=function(){Qc(c,a)})}Z.prototype.Oa.call(this,a,b)};
function Zc(a){var b={},c;for(c in a){for(var d=c,e=a[c],g=0;g<e.length;g++)if(0==e[g].indexOf("#N")){d=e[g].substr(2).trim();break}b[d]=c}return b}
t.pc=function(a){a=void 0===a?0:a;var b=0;if(0<=a){var c=1;do{switch(this.ua){case fd:var d=0;for(var e=this.aa,g=e.ea,f=e.fa,h=this.Ha,m=0;m<f;m++)for(var n=0;n<g;n++){var l=h,k=!1,p=4*(m*e.ca+n);if(p<=e.aa.length-4&&e.aa[p+1]){k=!0;p=e.aa[p+2];for(var q=l.length-1;0<=q;q--)l[q]=p&15,p>>>=4}if(k){d++;if(h[0])h[0]--;else{k=(l=mc(e,n,m))||0;switch(l){case 1:if(k=fc,h[0]=h[2],h[0]){h[0]--;break}case fc:if(h[3]&&(k=this.ia.indexOf(e.aa[4*(m*e.ca+n)+1]||e.ia),0<=k)){for(k+=h[3];k>=this.ia.length;)k-=
this.ia.length;pc(e,n,m,this.ia[k])}k=1;h[0]=h[1];h[0]&&h[0]--}k!==l&&rc(e,n,m,k)}qc(e,n,m,h)}}break;case gd:c=a||c;d=c;d=void 0===d?1:d;e=0;g=this.aa;f=g.ca;h=g.fa;if(g.qa||!hd(this,d))d=0;else{m=g.aa;p=4*d;n=4*f;k=q=l=0;for(this.ma=this.wa=-1;l<f-d;){for(var r=1,x=k,w=0;w<h;w++){var u=m[k],C=m[k]=m[k+p];u=C!==u?W:0;m[k+1]=m[k+p+1];m[k+2]=m[k+p+2];m[k+3]=m[k+p+3]|u;C&&(e++,r=0);k+=n}k=x+4;l++<g.ea&&(r?q++:(0>this.ma&&(this.ma=q),q=0))}0>this.ma&&(this.ma=q);for(this.wa=q;l<f;){p=k;for(q=0;q<h;q++)oc(g,
m,k),k+=n;k=p+4;l++}g.ka=!0;g.qa=d;d=e}break;case id:d=0;e=this.aa;g=e.aa;f=e;f.ra||(f.ra=Array(f.Va),dc(f,f.ra));f=f.ra;h=e.ea;m=e.fa;n=4*h+e.Wa;l=m*n;k=0;p=k-n;q=p-4;r=p+4;x=k-4;w=k+4;C=k+n;u=C-4;for(var G=C+4,J=0;J<m;J++){J?J==m-1&&(this.ka?(C-=l,u-=l,G-=l):C=u=G=l):this.ka?(p+=l,q+=l,r+=l):p=q=r=l;for(var X=0;X<h;X++){X?1==X?this.ka?(x-=n,q-=n,u-=n):(x=k-4,q=p-4,u=C-4):X==h-1&&(this.ka?(w-=n,r-=n,G-=n):w=r=G=l):this.ka?(x+=n,q+=n,u+=n):x=q=u=l;var Y=g[k],P=g[q]+g[p]+g[r]+g[w]+g[G]+g[C]+g[u]+g[x];
3==P?Y=1:2!=P&&(Y=fc);f[k]=Y;f[k+1]=g[k+1];f[k+2]=g[k+2];f[k+3]=g[k+3]|(g[k]!==Y?W:0);k+=4;q+=4;p+=4;r+=4;w+=4;G+=4;C+=4;u+=4;x+=4;1==Y&&d++}this.ka?(J||(p-=l,q-=l,r-=l),w+=n,r+=n,G+=n):(J||(p=k-n,q=p-4),w=k+4,r=p+4,G=C+4)}g=e.aa;e.aa=e.ra;e.ra=g;e.ka=!0}a||this.da("active cells: %d\n",d);b+=c}while(b<a)}return b};t.qc=function(){};t.oc=function(){return 0};function jd(a,b){var c=0;(a=a.la[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}
function Pc(a,b){var c=0;if(b&&(b=a.la[kd])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=jd(a,ld)+jd(a,md),!(d&1)&&c==d-1||0>b.selectedIndex||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<nd.length;b++)c.push(jd(a,nd[b]));return c}
function Qc(a,b){var c=a.aa,d=-1,e=-1,g="";b||a.pa.match(/^[0-9]/)||(b=a.pa);if(b){var f=a.ha[Yc];f=f&&f[b];if(!f)return a.da("unknown pattern: %s\n",b),!1;a.da('loading pattern "%s"\n',b);for(var h=b=0;b<f.length;b++){var m=f[b];if("#"==m[0])a.da("%s\n",m);else if(h++){var n=m.indexOf("!");if(0<=n){g+=m.substr(0,n);break}g+=m}else{var l=m.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!l)return a.da("unrecognized header line\n"),!1;var k=+l[1];var p=+l[2];l=l[3]}}}else{if(!a.pa)return!1;
g=0;l=a.pa.split("/");5==l.length&&(d=+l[g++],e=+l[g++]);if(3==l.length||5==l.length)k=+l[g++],p=+l[g++],g=l[g];else return a.da("unrecognized pattern: %s\n",a.pa),!1;l=a.ua}if(l!=a.ua)return a.da("unsupported rule: %s\n",l),!1;0>d&&(d=c.ca-k>>1);0>e&&(e=c.fa-p>>1);return 0>d||d+k>c.ca||0>e||e+p>c.fa?(a.da("pattern too large (%d,%d)\n",k,p),!1):0<od(a,d,e,g)}
function od(a,b,c,d,e){e=void 0===e?!1:e;var g=a.aa,f=[0,0,0,1],h=0,m=!1,n=!1;d=d.split(/([a-z$])/i);e||xb(g);for(var l=0,k=b,p=0;l<d.length-1;){var q=d[l++],r=d[l++],x=+q;for(q=""===q?1:x;q--;){var w=0,u=!1;switch(r){case "$":m=n=!1;b=k;c++;break;case "C":h=x;n=!0;break;case "R":f[0]=x;m=!0;break;case "G":f[1]=x;m=!0;break;case "B":f[2]=x;m=!0;break;case "A":f[3]=x;m=!0;break;case "b":u=rc(g,b,c,fc);w++;break;case "o":u=rc(g,b,c,1);w++;break;default:a.da("unrecognized pattern token: %s\n",r)}if(null==
u)a.da("invalid pattern position (%d,%d)\n",b,c);else{if(m){u=g;var C=f;u=4>C.length||1==C[3]?u.Aa("#%02x%02x%02x",C[0],C[1],C[2]):u.Aa("rgba(%d,%d,%d,%d)",C[0],C[1],C[2],C[3]);pc(g,b,c,u)}n&&(u=4*(c*g.ca+b),u<=g.aa.length-4&&g.aa[u+2]!=h&&(g.aa[u+2]=h));p<b&&(p=b);b+=w}}}e||Ab(g,!0);return 0>(p-=k-1)?0:p}
t.Ka=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return this.da("Invalid saved state\n"),!1;var c=b.shift();if(3!==(c|0))return this.da("Saved state version mismatch: %3.2f\n",c),!1;try{this.ca=b.shift(),this.ea=b.shift(),this.fa=b.shift(),this.ba=b.shift()}catch(d){return this.da("Controller state error: %s\n",d.message),!1}return Pa().message||Pa().pattern||Pa()[Uc]||!(a=a.stateLEDs||a[1])||!this.aa||this.aa.Ka(a)?!0:!1};
t.Bd=function(a){var b="",c=a.shift();switch(a.shift()[0]){case "s":Oc(this,a.join(" "));break;case "?":b="";pd.forEach(function(d){b+=d+"\n"});b&&(b="additional commands:\n"+b);break;default:c&&(b="unrecognized command '"+c+"' (try '?')\n")}return b};t.Bb=function(a){return a&&this.Ka(a)?!0:!1};t.Ea=function(a){a?this.time.start():zc(this.time)};t.Ga=function(){this.da("reset\n");xb(this.aa,!0);kc(this.aa,!0);this.ya&&Oc(this,this.ya)};t.Cb=function(a){this.La(a)};t.Cd=function(){this.time.aa||Ab(this.aa)};
function hd(a,b,c,d){b=void 0===b?1:b;c&&(a.fa=c,a.ba=d);switch(a.fa){case qd:return!1;case rd:case sd:if(0<a.ba)return a.ba-=b,!0;break;case td:if(0<a.ba)return a.ba-=b,!1;break;case ud:if(a.ma>a.wa)return!0;break;case vd:kc(a.aa,!1);a.fa=td;break;case wd:kc(a.aa,!0);a.fa=td;break;default:return!1}if(c)a=!1;else a:if(b=void 0===b?1:b,a.ca){a.ea>=a.ca.length&&(a.ea=0);c=a.ca[a.ea++];if("$"==c){d=0;for(var e=a.ea;e<a.ca.length;){var g=a.ca.charCodeAt(e)-48;if(0>g||9<g)break;d=10*d+g;e++}if(e<a.ca.length)if(g=
a.ca[e++],"$"==g)a.ea=e;else{var f=xd[g];if(f){a.ea=e;a=hd(a,b,f,d);break a}a.da("unrecognized message code: $%s\n",g)}}" "==c?a.ba+=2:(d=a.aa.ea+1,e=0>a.ba?a.ba:0,c=a.ta[c]||a.ta[c.toUpperCase()],g=Math.round((a.aa.xa-a.ta.height)/2),c&&(a.ba+=od(a,d+e,0>g?0:g,c,!0)),a.ba+=2-b);a.fa=sd;a=!0}else a.fa=qd,a=!1;return a}
function ad(a,b){function c(Y){var P=!1;null==l[3]&&(l[3]=1);if(w){if(m){if(l[0]!==r[0]||l[1]!==r[1]||l[2]!==r[2]||l[3]!==r[3])P=!0;X!==x&&(P=!0)}n!==q&&(P=!0);if(P||Y&&q)m&&(k[0]!==r[0]&&(k[0]=r[0],e+=(r[0]||"")+"R"),k[1]!==r[1]&&(k[1]=r[1],e+=(r[1]||"")+"G"),k[2]!==r[2]&&(k[2]=r[2],e+=(r[2]||"")+"B"),k[3]!==r[3]&&(k[3]=r[3],e+=(r[3]||"")+"A"),p!==x&&(p=x,e+=(x||"")+"C")),1<w&&(e+=w),e+=1===q?"o":"b",P=!0}Y?(e+="$",w=0):(P?w=1:w++,q=n,r[0]=l[0],r[1]=l[1],r[2]=l[2],r[3]=l[3],x=X)}var d=a.aa,e="",
g=0,f=a.aa.ca,h=a.aa.fa,m=!!a.ia.length,n,l=[0,0,0],k=[0,0,0,1],p=0,q=0,r=[0,0,0,1],x=0,w=0;a=0;var u=d.ca-1,C=d.fa-1;if(b){b&&(a=u,u=0);for(f=0;f<d.fa;f++)for(h=0;h<d.ca;h++)(n=mc(d,h,f))&&b&&(a>h&&(a=h),u<h&&(u=h));f=u-a+1;h=C+1;0>f&&(f=0);0>h&&(h=0)}for(var G=0;G<=C;G++){for(var J=a;J<=u;J++){n=mc(d,J,G);nc(d.aa[4*(G*d.ca+J)+1]||d.ia,l);var X=lc(d,J,G);c()}c(!0)}if(!b)for(;"$"==e[0];)g++,h--,e=e.slice(1);for(;"$$"==e.slice(-2);)h--,e=e.slice(0,-1);"$"==e&&(h=0);e=(b?"":"0/"+g+"/")+f+"/"+h+"/"+
e.slice(0,-1);return e=e.replace(/\$+$/,"")}t.La=function(a){var b=[],c=[];b.push(3);b.push(this.ca);b.push(this.ea);b.push(this.fa);b.push(this.ba);this.aa&&this.aa.La(c);a.push(b);a.push(c)};function Oc(a,b){a.ca!=b&&(b&&a.da('new message: "%s"\n',b),a.ca=b);a.fa=rd;a.ea=a.ba=0}t.toString=function(){return""};
function Tc(a,b){var c=a.la[Uc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.aa;a.Ra&&(a.Ra.style.backgroundImage=b?"url('"+b+"')":"none")}}
function Xc(a,b){var c=a.la[Vc],d=a.la[Wc];b=b===Vc;c&&!c.options.length&&(Fa(c,a.ha.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.ga=a.ha.colors[c.options[c.selectedIndex].value];for(var e in a.ga)if(b=a.ha[e.toLowerCase()])"#"!=b[0]&&(b="#"+b),a.da('overriding color "%s" with %s (formerly %s)\n',e,b,a.ga[e]),a.ga[e]=b;Fa(d,a.ga,!0)}c&&d&&d.options.length&&(a.ja=d.options[d.selectedIndex].value,Sc(a))}
function Rc(a,b){var c=a.la[Wc];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.ja=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function Sc(a,b){var c=1,d;!b&&a.ja&&(d=a.la[yd])&&(d.style.backgroundColor=a.ja);if(a.ga)for(var e in a.ga){var g=a.ga[e];a.ia&&(a.ia[c-1]=g);var f=ed+c++;d=a.la[f];if(!d)break;d.style.display="inline-block";f==b&&Rc(a,g);if(b&&b!=f||g!=a.ja)g=ac(g,1,.5);d.style.backgroundColor=g}for(;;){b=ed+c++;b=a.la[b];if(!b)break;b.style.display="none"}}
var Vc="colorPalette",Wc="colorSelection",ed="colorSwatch",yd="colorSwatchSelected",kd="countInit",ld="countOn",md="countOff",Uc="backgroundImage",Yc="patterns",bd="symbolInput",dd="symbolPreview",$c="save",cd="saveToURL",nd=[null,ld,md,"countCycle"],pd=["s\t\tset string"],rd="load",sd="scroll",td="pause",qd="halt",ud="center",vd="off",wd="on",xd={b:vd,c:ud,h:qd,o:wd,p:td,s:sd},fd="A4",gd="L1",id="B3/S23",Nc={Helvetica:{width:16,height:16,0:"$2b2o$bo2bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$bo2bo$2b2o",
1:"$3bo$2b2o$4o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo",2:"$2b3o$bo3bo$o5bo$o5bo$6bo$5bo$3b2o$2bo$bo$o$7o",3:"$b4o$o4bo$o4bo$5bo$4bo$2b2o$4bo$5bo$o4bo$o4bo$b4o",4:"$5bo$4b2o$3bobo$2bo2bo$bo3bo$o4bo$o4bo$8o$5bo$5bo$5bo",5:"$6o$o$o$o$4o$4bo$5bo$5bo$5bo$o3bo$b3o",6:"$2b4o$bo4bo$o$o$o$ob4o$2o4bo$o5bo$o5bo$bo4bo$2b4o",7:"$8o$7bo$6bo$5bo$4bo$4bo$3bo$3bo$2bo$2bo$2bo",8:"$b4o$o4bo$o4bo$o4bo$bo2bo$2b2o$bo2bo$o4bo$o4bo$o4bo$b4o",9:"$b4o$o4bo$o5bo$o5bo$o4b2o$b4obo$6bo$6bo$6bo$o4bo$b4o",A:"$3b2o$2bo2bo$bo4bo$bo4bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo",
B:"$6o$o5bo$o5bo$o5bo$o4bo$7o$o6bo$o6bo$o6bo$o6bo$7o",C:"$2b4o$bo4bo$o6bo$o$o$o$o$o$o6bo$bo4bo$2b4o",D:"$6o$o5bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o5bo$6o",E:"$7o$o$o$o$o$6o$o$o$o$o$7o",F:"$7o$o$o$o$o$6o$o$o$o$o$o",G:"$2b4o$bo4bo$o$o$o$o3b4o$o6bo$o6bo$o6bo$bo4bo$2b4o",H:"$o6bo$o6bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo$o6bo$o6bo",I:"$o$o$o$o$o$o$o$o$o$o$o",J:"$5bo$5bo$5bo$5bo$5bo$5bo$5bo$o4bo$o4bo$o4bo$b4o",K:"$o6bo$o5bo$o4bo$o3bo$o2bo$ob2o$2o2bo$o4bo$o5bo$o6bo$o7bo",L:"$o$o$o$o$o$o$o$o$o$o$7o",M:"$o8bo$2o6b2o$obo4bobo$obo4bobo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o8bo$o8bo$o8bo$o8bo",
N:"$2o5bo$obo4bo$obo4bo$o2bo3bo$o2bo3bo$o3bo2bo$o3bo2bo$o4bobo$o4bobo$o4bobo$o5b2o",O:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo6bo$2bo4bo$3b4o",P:"$6o$o5bo$o6bo$o6bo$o6bo$o5bo$6o$o$o$o$o",Q:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo4bobo$2bo4bo$3b4obo$9bo",R:"$6o$o5bo$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo$o6bo",S:"$2b4o$bo4bo$o6bo$o$bo$2b4o$6bo$7bo$o6bo$bo4bo$2b4o",T:"$9o$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo",U:"$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",V:"$o8bo$o8bo$bo6bo$bo6bo$bo6bo$2bo4bo$2bo4bo$2bo4bo$3bo2bo$3bo2bo$4b2o",
W:"$o4b2o4bo$o4b2o4bo$o4b2o4bo$o3bo2bo3bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$2b2o4b2o$2b2o4b2o$2b2o4b2o",X:"$o8bo$bo6bo$2bo4bo$3bo2bo$4b2o$4b2o$4b2o$3bo2bo$2bo4bo$bo6bo$o8bo",Y:"$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$9o$8bo$7bo$6bo$5bo$4bo$3bo$2bo$bo$o$9o",a:"$$$$b4o$o4bo$5bo$b5o$o4bo$o4bo$o3b2o$b3obo",b:"$o$o$o$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o",c:"$$$$2b4o$bo4bo$o$o$o$o$bo4bo$2b4o",d:"$6bo$6bo$6bo$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo",e:"$$$$2b3o$bo3bo$o5bo$7o$o$o$bo4bo$2b4o",
f:"$2b2o$bo2bo$bo$bo$4o$bo$bo$bo$bo$bo$bo",g:"$$$$2b2obo$bo2b2o$o4bo$o4bo$o4bo$bo2b2o$2b2obo$5bo$5bo$o4bo$b4o",h:"$o$o$o$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",i:"$$o$$o$o$o$o$o$o$o$o",j:"$$3bo$$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$o2bo$b2o",k:"$o$o$o$o4bo$o3bo$o2bo$obo$2obo$o3bo$o4bo$o5bo",l:"$o$o$o$o$o$o$o$o$o$o$o",m:"$$$$ob2o3b2o$2o2bobo2bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo",n:"$$$$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",o:"$$$$2b4o$bo4bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",p:"$$$$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o$o$o$o",
q:"$$$$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo$6bo$6bo$6bo",r:"$$$$ob2o$2o2bo$o$o$o$o$o$o",s:"$$$$b4o$o4bo$o$b4o$5bo$5bo$o4bo$b4o",t:"$$bo$bo$4o$bo$bo$bo$bo$bo$bo2bo$2b2o",u:"$$$$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o3b2o$b3obo",v:"$$$$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo",w:"$$$$o3b2o3bo$o3b2o3bo$o3b2o3bo$o3b2o3bo$bobo2bobo$bobo2bobo$bobo2bobo$2bo4bo",x:"$$$$$o5bo$bo3bo$2bobo$3bo$2bobo$bo3bo$o5bo",y:"$$$$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$2bo$2o",z:"$$$$6o$5bo$4bo$3bo$2bo$bo$o$6o",
"!":"$o$o$o$o$o$o$o$o$$o$o",'"':"$obo$obo$obo$obo","#":"$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo",$:"3bo$2b4o$bobo2bo$o2bo$o2bo$bobo$2b3o$3bobo$3bo2bo$3bo2bo$o2bobo$b4o$3bo","%":"$b2o7bo$o2bo5bo$o2bo4bo$o2bo3bo$o2bo2bo$b2o2bo2b2o$4bo2bo2bo$3bo3bo2bo$2bo4bo2bo$bo5bo2bo$o7b2o","&":"$b3o$o3bo$o3bo$o3bo$bobo$2bo$bobo$o3bobo$o4bo$o3bobo$b3o3bo","'":"$o$o$o$o","(":"$3bo$2bo$bo$bo$o$o$o$o$o$o$bo$bo$2bo$3bo",")":"$o$bo$2bo$2bo$3bo$3bo$3bo$3bo$3bo$3bo$2bo$2bo$bo$o","*":"2bo$obobo$b3o$b3o$o3bo",
"+":"$$$$3bo$3bo$3bo$7o$3bo$3bo$3bo",",":"$$$$$$$$$$2o$2o$bo$o",".":"$$$$$$$$$$2o$2o","/":"$3bo$3bo$2bo$2bo$2bo$bo$bo$bo$o$o$o",":":"$$$$2o$2o$$$$$2o$2o",";":"$$$$2o$2o$$$$$2o$2o$bo$o","<":"$$$$6b2o$4b2o$2b2o$2o$2o$2b2o$4b2o$6b2o",">":"$$$$2o$2b2o$4b2o$6b2o$6b2o$4b2o$2b2o$2o","=":"$$$$$$8o$$$8o","?":"$b4o$o4bo$o4bo$5bo$4bo$3bo$2bo$2bo$$2bo$2bo","@":"$3b4o$2bo4bo$bo6bo$o3b2o3bo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o5b3o$bo$2bo5bo$3b5o","[":"$3o$o$o$o$o$o$o$o$o$o$o$o$o$3o","]":"$3o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$3o",
"\\":"$o$o$bo$bo$bo$2bo$2bo$2bo$3bo$3bo$3bo","^":"$2b2o$2b2o$bo2bo$bo2bo$o4bo$o4bo",_:"$$$$$$$$$$$$$8o","`":"o$bo$2bo","{":"$2b2o$bo$bo$bo$bo$bo$bo$o$bo$bo$bo$bo$bo$2b2o","}":"$2o$2bo$2bo$2bo$2bo$2bo$2bo$3bo$2bo$2bo$2bo$2bo$2bo$2o","|":"o$o$o$o$o$o$o$o$o$o$o$o$o$o$o","~":"$$$$$$b3o3bo$o3b3o"},ATT4425:{width:9,height:13,A:"$3bo$3bo$2bobo$2bobo$bo3bo$bo3bo$7o$o5bo$o5bo",B:"$6o$bo4bo$bo4bo$bo3bo$b4o$bo3bo$bo4bo$bo4bo$6o",C:"$2b5o$bo$o$o$o$o$o$bo$2b5o",D:"$5o$bo3bo$bo4bo$bo4bo$bo4bo$bo4bo$bo4bo$bo3bo$5o",
E:"$6o$o$o$o$5o$o$o$o$6o",F:"$6o$o$o$o$5o$o$o$o$o",G:"$2b3o$bo3bo$o$o$o$o3b3o$o4bo$bo3bo$2b3o",H:"$o5bo$o5bo$o5bo$o5bo$7o$o5bo$o5bo$o5bo$o5bo",I:"$3o$bo$bo$bo$bo$bo$bo$bo$3o",J:"$4bo$4bo$4bo$4bo$4bo$4bo$o3bo$o3bo$b3o",K:"$o5bo$o4bo$o3bo$o2bo$3o$o2bo$o3bo$o4bo$o5bo",L:"$o$o$o$o$o$o$o$o$7o",M:"$o5bo$2o3b2o$obobobo$o2bo2bo$o5bo$o5bo$o5bo$o5bo$o5bo",N:"$o5bo$2o4bo$obo3bo$obo3bo$o2bo2bo$o3bobo$o3bobo$o4b2o$o5bo",O:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",P:"$6o$o5bo$o5bo$o5bo$6o$o$o$o$o",Q:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o$3bo2bo$4b3o",
R:"$6o$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo",S:"$2b3o$bo3bo$bo$2bo$3bo$4bo$o4bo$bo3bo$2b3o",T:"$5o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo",U:"$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",V:"$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo",W:"$o5bo$o5bo$o2bo2bo$o2bo2bo$obobobo$obobobo$2o3b2o$2o3b2o$o5bo",X:"$o5bo$bo3bo$bo3bo$2bobo$3bo$2bobo$bo3bo$bo3bo$o5bo",Y:"$o5bo$o5bo$bo3bo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$7o$6bo$5bo$4bo$3bo$2bo$bo$o$7o"}};E.LEDCtrl=Mc;
function zd(a,b,c){Q.call(this,a,a);var d=this;this.ca=!1;this.ia=c;this.ba="";this.ga=this.fa=!1;kb(this,!1);this.Ca=B.Cc;b=b.trim();"{"==b[0]?Ad(this,b):(this.ba=b,Oa(this.ba,function(e,g,f,h){4==f&&(!h&&g?(Ad(d,g),Bd(d)):d.da("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.ga=!0;Bd(d)});window.addEventListener(Sa("iOS")?"pagehide":Sa("Opera")?"unload":"beforeunload",function(){Cd(d)});window.addEventListener("pageshow",function(){d.ca||d.Ea(!0)})}
z(zd,Q);zd.prototype.Oa=function(a,b){var c=this;switch(a){case Dd:b.onclick=function(){c.Ea()};break;case Ed:b.onclick=function(){c.Ga()}}Q.prototype.Oa.call(this,a,b)};
function Bd(a){var b=!0;if(a.fa&&a.ga){for(var c in a.aa){var d=void 0,e=a.aa[c];try{d=e["class"],E[d]?"Machine"==d?(a.da("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2023 Jeff Parsons <Jeff@pcjs.org>"),a.ba&&a.da("Configuration: %s\n",a.ba)):new E[d](a.na,c,e):a.da('unrecognized %s device "%s"\n',d,c)}catch(f){e.optional||(a.da('error initializing %s device "%s": %s\n',d,c,f.message),b=!1),mb(a,c)}}if(a.ea){var g=Ta(a);ib(a,function(f){return f.Bb&&!f.Bb(g)?(f.da('unable to restore state for device "%s"\n',
f.va),!1):!0})}kb(a,!0);lb(a,a.Ea.bind(a,b))||a.da("machine %s not ready to power, waiting for device(s)\n",a.na)}}
function Ad(a,b){try{a.aa=JSON.parse(b);var c=a.aa[a.na];if(!c){c=a.aa[va(a.ba)];if(!c)throw Error("configuration missing machine ID");a.aa[a.na]=c}hb(a,c,["autoSave","autoStart"]);a.ea=!1!==a.ha.autoSave;a.ja=!1!==a.ha.autoStart;if(a.ia){var d=eval("("+a.ia+")"),e;for(e in d)a.ha[e]=d[e]}a.fa=!0}catch(g){c=g.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.da("machine '%s' initialization error: %s\n",a.na,c)}}
zd.prototype.Ea=function(a){a=void 0===a?!this.ca:a;if(jb(this)){var b=this;a&&this.da("power on\n");ib(this,function(c){c.Ea&&c!=b&&("CPU"!=c.ha["class"]||b.ja&&jb(b)?c.Ea(a):c.time.update(!0));return!0});(this.ca=a)||this.da("power off\n")}};zd.prototype.Ga=function(){if(jb(this)){var a=this;ib(this,function(b){b.Ga&&b!=a&&b.Ga();return!0});this.da("reset\n")}};function Cd(a){if(a.ea){var b=[];ib(a,function(c){c.Cb&&c.Cb(b);return!0});Za(a,b)}a.Ea(!1)}var Dd="power",Ed="reset";
window.LEDs=function(a,b,c){var d=new zd(a,b,c);window.command=function(e){return Ua(d,e)};return d};E.Machine=zd;})()

//# sourceMappingURL=led.js.map
