(function(){/*
 https://www.pcjs.org/machines/modules/v3/defines.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/message.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdlib.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdio.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/webio.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/device.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/bus.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/memory.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/rom.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/input.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/led.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/time.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/cpu.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/ledctrl.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/machine.js (C) 2012-2026 Jeff Parsons
*/
var t,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this),ea="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");da.BigInt64Array&&(ea.push("BigInt64"),ea.push("BigUint64"));
function fa(a,b){if(b)for(var c=0;c<ea.length;c++)ha(ea[c]+"Array.prototype."+a,b)}function w(a,b){b&&ha(a,b)}function ha(a,b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}var ia;
if(typeof Object.setPrototypeOf=="function")ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ma=ia;
function x(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ma)ma(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Je=b.prototype}function na(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function A(a){if(!(a instanceof Array)){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)a=b.call(a);else if(typeof a.length=="number")a={next:na(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function oa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
w("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
w("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});function pa(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
w("String.prototype.repeat",function(a){return a?a:function(b){var c=pa(this,null,"repeat");if(b<0||b>1342177279)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});w("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});w("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
w("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
w("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.ja=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.ja};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
w("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return qa(na(this))}});return a});function qa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}function ra(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}
w("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}});w("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}});w("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;c<0&&(c=Math.max(0,e+c));if(d==null||d>e)d=e;d=Number(d);d<0&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});fa("fill",function(a){return a?a:Array.prototype.fill});
w("Number.parseInt",function(a){return a||parseInt});w("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=pa(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});function sa(){this.sa=""}var ta=new ArrayBuffer(2);(new DataView(ta)).setUint16(0,256,!0);new Uint16Array(ta);
var B={we:typeof window!="undefined",node:typeof window!="undefined"?{}:global,process:typeof process!="undefined"?process:{},window:typeof window!="undefined"?window:global,document:typeof document!="undefined"?document:{},mb:{machines:{},components:[],commands:{},files:null}};B.window.PCjs?B.mb=B.window.PCjs:B.window.PCjs=B.mb;var ua=B.process,C=B.mb.machines,va=B.mb.components,E={};E.Defines=sa;
var wa={all:0xffffffffffff,addr:1,bus:2,fault:4,memory:8,ports:16,chips:32,kbd:64,serial:128,misc:256,cpu:512,mmu:2048,"int":1024,trap:4096,video:8192,monitor:16384,screen:32768,disk:131072,file:65536,time:262144,timer:524288,event:1048576,input:2097152,key:4194304,mouse:8388608,touch:16777216,info:274877906944,warn:549755813888,error:1099511627776,halt:70368744177664,buffer:0x800000000000};function xa(){this.ja={};for(var a=0;a<23;a++)this.ja["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
function ya(){var a=oa.apply(0,arguments);if(a[0]===void 0)a=new Date(Date.now());else if(typeof a[0]==="string"){var b=a[0];b.indexOf(":")<0?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=a[1]===void 0?new Date(a[0]):new Date(Date.UTC.apply(Date,A(a)));return a}
xa.prototype.aa=function(a){var b=oa.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(this.ja[g]===void 0)c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];g!="%"&&e++}else h=b[b.length-1];var m=!1,p=d[f+1],l=p.indexOf("#")>=0,n=p.indexOf("0")>=0,k=d[f+2];k=="*"?(k=h,h=e<b.length?b[e++]:b[b.length-1]):k=+k||0;var q=d[f+3];q=q?+q.substr(1):-1;var r=d[f+
4],y=null,v=0,u="",z="ACDFGHMNSTWY".indexOf(g)>=0&&typeof h!="object"?ya(h):h;switch(g){case "C":c+=isNaN(z.getTime())?void 0:this.aa("%#W, %#F %#D, %#Y".replaceAll("#",l?"#":""),z);continue;case "D":h=l?z.getUTCDate():z.getDate();g="d";break;case "A":case "G":case "H":h=l?z.getUTCHours():z.getHours();g=="A"?(h=h<12?"am":"pm",g="s"):(g=="G"&&(h=h?h>12?h-12:h:12),g="d");break;case "F":case "M":h=l?z.getUTCMonth():z.getMonth();g=="F"?(h=za[h],g="s"):(h++,g="d");break;case "N":h=l?z.getUTCMinutes():
z.getMinutes();g="d";break;case "S":h=l?z.getUTCSeconds():z.getSeconds();g="d";break;case "T":c+=isNaN(z.getTime())?void 0:this.aa("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",l?"#":""),z);continue;case "W":h=Aa[l?z.getUTCDay():z.getDay()];g="s";break;case "Y":h=l?z.getUTCFullYear():z.getFullYear(),q>0&&(h%=Math.pow(10,q)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),q>=0&&(n=!0,k<q&&(k=q),q=-1);case "f":h=+h;g=h+"";q>=0&&(g=h.toFixed(q));g.length<k&&(n?(h<0&&
(k--,g=g.substr(1)),g=("0".repeat(k)+g).slice(-k),h<0&&(g="-"+g)):g=(" ".repeat(k)+g).slice(-k));c+=g;break;case "j":c+=JSON.stringify(h,null,k||void 0);break;case "c":h=typeof h=="string"?h[0]:String.fromCharCode(h);case "s":if(h!=void 0)for(typeof h!="string"&&(h=h.toString()),q>=0&&(h=h.substr(0,q));h.length<k;)h=p.indexOf("-")>=0?h+" ":" "+h;c+=h;break;case "B":v=2,l&&(u="0b");case "o":v||(v=8),!u&&l&&(u="0o");case "X":y=Ba;case "x":g="";v||(v=16);!u&&l&&(u="0x");y||(y=Ca);typeof h=="string"&&
h[0]=="-"&&(m=!0,h=h.slice(1));h=Math.trunc(h);m&&(h=-h);h<0&&((h|0)==h?h>>>=0:Math.abs(h)<=9007199254740992&&(h+=9007199254740992));q>=0&&(n=!0,k<q&&(k=q));n&&!k&&(r=="b"?k=2:r=="h"||r=="w"?k=4:r=="l"?k=8:(k=Math.abs(h),k=k<=255?2:k<=65535?4:k<=4294967295?8:9),k+=u.length);k-=u.length;do m=16,Number.isNaN(h)||(m=h&v-1,h=Math.trunc(h/v)),n||!g||m||h?g=y[m]+g:(u&&(g=u+g,u=""),k>0&&(g=" "+g));while(--k>0||h);c+=u+g;break;case "%":c+="%";break;default:c=this.ja[g]?c+this.ja[g](g,p,k,q,h):c+("(unimplemented sprintf type: %"+
g+")")}}}return c+=d[f]};var Aa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),za="January February March April May June July August September October November December".split(" "),Ca="0123456789abcdef?",Ba="0123456789ABCDEF?";function Da(){sa.apply(this,arguments)}x(Da,sa);function Ea(a,b){var c=a/F|0,d=b/F|0;return(a&b)==(b|0)&&(c&d)==d}var F=4294967296;E.StdLib=Da;function G(){Da.call(this);this.format=new xa;this.Ba=this.format.aa.bind(this.format)}x(G,Da);
G.prototype.flush=function(){var a=Fa;Fa="";this.bb(a)};function Ga(a){var b=a,c=a.lastIndexOf("/");c>=0&&(b=a.substr(c+1));c=b.indexOf("&");c>0&&(b=b.substr(0,c));c=b.lastIndexOf(".");c>0&&(b=b.substring(0,c));return b}G.prototype.bb=function(a,b){var c=a.length,d=a.lastIndexOf("\n");b?d>=0&&(b=Date.now(),Ha||(Ha=b),a=((b-Ha)/1E3).toFixed(3)+": "+a,c=a.length):this.sa=="node"?(ua.Ie.write(a),a=""):(d>=0&&(console.log(Fa+a.slice(0,d)),Fa="",a=a.slice(d+1)),Ha=null);Fa+=a;return c};
G.prototype.ca=function(a){return this.bb(this.Ba.apply(this,[a].concat(A(oa.apply(1,arguments)))))};var Fa="",Ha=null;E.StdIO=G;function I(a){G.call(this);this.la={};this.Da=0;this.ja=this;a&&(this.ja.Da=0,this.ja.Ka=[],this.ja.Ha=0,this.ja.ab={},this.ja.se=!1)}var Ia;x(I,G);t=I.prototype;
t.Ma=function(a,b){var c=this,d=this;this.la[a]=b;switch(a){case Ja.rc:b.onclick=function(){var e=c.Wa(Ja.sb,!0);e&&(e.value="")};break;case Ja.sb:Ka(b),b.addEventListener("keydown",function(e){La(d,e,!0)}),b.addEventListener("keypress",function(e){La(d,e)})}};function Ma(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value=typeof b[e]=="string"?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}
function Na(a,b){var c=Oa.Db;a.ja.ab[c]||(a.ja.ab[c]=[]);a.ja.ab[c].push(b)}function Ka(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}t.error=function(a,b){b=this.Ba.apply(this,[a].concat(A(b)));var c="%s";a=!1;typeof c=="boolean"&&(a=c,c=b.shift());if(b=this.Ba.apply(this,[c].concat(A(b))))this.ca("%s\n",b),a||alert(b)};t.Wa=function(a){return this.la[a]};
function Pa(a){var b=window;if(b){do{for(var c=0;c<Qa.length;c++){var d=Qa[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(a.indexOf("screen")<0)break;a=a.replace("screen","Screen")}while(1)}return null}function Ra(a,b){return a.config.bindings&&a.config.bindings[b]}function Sa(a){if(a=a.la[Ta])var b=a.textContent;return b}function Ua(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function J(a,b,c,d){a=a.config[b];a===void 0?a=c:(d&&d[a]!==void 0&&(a=d[a]),d=typeof c,typeof a!=d&&(d=="boolean"?a=!!a:typeof c=="number"&&(a=+a)));return a}
function Va(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){e.readyState!==4?b(a,d,e.readyState,c):(d=e.responseText,e.status==200||!e.status&&d.length&&(window?window.location.protocol:"file:")=="file:"||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Wa(){var a,b=Ia;if(!b){b={};if(window){a||(a=window.location.search.slice(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ia=b}return b}function Xa(a){if(K.qb===void 0){var b=!1;if(window)try{window.localStorage.setItem(K.Ua,K.Ua),b=window.localStorage.getItem(K.Ua)==K.Ua,window.localStorage.removeItem(K.Ua)}catch(c){a.ca("%s\n",c.message),b=!1}K.qb=b}return!!K.qb}
function Ya(a,b){b=b===void 0?0:b;b>1&&b%2&&b--;b=b||a.Da;return(b|1)==-1||Ea(a.ja.Da,b)?!0:!1}function Za(a){if(window){var b=window.navigator.userAgent;return a=="iOS"&&(!!b.match(/(iPod|iPhone|iPad)/)||window.navigator.platform==="MacIntel"&&window.navigator.maxTouchPoints>1)||a=="MSIE"&&!!b.match(/(MSIE|Trident)/)||b.indexOf(a)>=0}return!1}
function $a(a){var b=null;if(Xa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.ma))&&(b=JSON.parse(c))}catch(d){a.ca("%s\n",d.message)}}return b}
function La(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.ja,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==L.Ab&&f.selectionStart<=h+1&&(a=!0);d==L.Zb?(a=!0,e.Ha>0&&(g=e.Ka[--e.Ha])):d==L.Gb&&(a=!0,e.Ha<e.Ka.length&&(g=e.Ka[++e.Ha]||""));a&&b.preventDefault();g!=void 0&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),d=="@"&&e.Ha>0&&c+1==
g.length&&(f.value+=e.Ka[--e.Ha],d="\r"),d=="\r"&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=ab(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&a.ca("%s\n",b.replace(/\n$/,"")))}}
function bb(a,b){if(b!=void 0){var c=a.ja;try{if(b=b.trim())c.Ha<c.Ka.length&&b==c.Ka[c.Ha]?c.Ha++:(c.Ka.push(b),c.Ha=c.Ka.length);var d=b.split(" "),e=d[0],f=a.ja.ab[Oa.Db];switch(e[0]){case "m":if(e[1]=="?"){var g="";cb.forEach(function(n){g+=n+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var m=e=="true"||e=="on"?!0:e=="false"||e=="off"?!1:void 0;m!=void 0&&d.pop();d.length<=1&&(m!=void 0&&(h=m,m=void 0),d[1]="all");d[1]=="all"&&(d=Object.keys(wa));
for(f=1;f<d.length;f++){e=d[f];var p=wa[e];if(!p){g+="unrecognized message: "+e+"\n";break}m!=void 0&&db(a,p,m);if(h==void 0||h==Ya(a,p))g+=a.Ba("%8s: %b\n",e,Ya(a,p))}Ya(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",eb.forEach(function(n){g+=n+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var l=f[a](d);if(l!=void 0){g=g?g+l:l;break}}}}catch(n){g="error: "+n.message+"\n"}}return g}
function ab(a,b){b=b===void 0?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=bb(a,b[d])}return c}
t.bb=function(a,b){b==void 0&&(b=Ya(this,0x800000000000));if(!b){var c=this.Wa(Ja.sb,!0);if(c){b=c.selectionStart;for(var d=a.split(/([\n\r\b])/),e=0;e<d.length;e++){var f=d[e];if(f)if(f=="\b"||f=="\r")for(;b>0&&c.value.slice(b-1,b)!="\n"&&(b--,f!="\b"););else if(f=="\n"){for(f="";b<c.value.length&&(f=c.value[b],b++,f!="\n"););f!="\n"&&(c.value+="\r\n",b=c.value.length)}else c.value=c.value.slice(0,b)+f+c.value.slice(b+f.length),b+=f.length}c.focus();c.setSelectionRange(b,b);c.value.length>=8192&&
(c.value=c.value.slice(c.value.length-8192+4096));c.scrollTop=c.scrollHeight;return a.length}}return G.prototype.bb.call(this,a,b)};t.ca=function(a){var b=oa.apply(1,arguments),c=0;typeof a=="number"&&(c=a,a=b.shift());return Ya(this,c)?(Ea(c,1099511627776)&&(a="error: "+a),Ea(c,549755813888)&&(a="warning: "+a),G.prototype.ca.call.apply(G.prototype.ca,[this,a].concat(A(b)))):0};function fb(a,b,c){(a=a.la[b])&&a.textContent!=c&&(a.textContent=c)}
function db(a,b,c){var d=!1;c?(c=a.ja.Da,a.ja.Da=(c|b)+(c/F|0|b/F|0)*F):(d=Ea(a.ja.Da,0x800000000000)&&Ea(b,0x800000000000),c=a.ja.Da,a.ja.Da=(c&~b)+((c/F|0)&~(b/F|0))*F);d&&a.flush()}
var Ja={rc:"clear",sb:"print"},eb=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],cb=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],Oa={Db:"command"},gb={Eb:13,pb:65,zb:66,Bb:67,Fb:68,E:69,Hb:70,Ib:71,Jb:72,Kb:73,Lb:74,Mb:75,Nb:76,Qb:77,Rb:78,Sb:79,Tb:80,Q:81,Ub:82,Wb:83,Xb:84,Yb:85,$b:86,ac:87,bc:88,
cc:89,ub:90,a:97,b:98,c:99,d:100,e:101,f:102,Be:103,Ce:104,De:105,Ee:106,k:107,Fe:108,Ge:109,n:110,He:111,p:112,q:113,r:114,s:115,t:116,Ke:117,Le:118,w:119,x:120,y:121,z:122},L={Ab:8,Oc:9,Cc:10,Eb:13,Kc:16,sc:17,qc:18,ie:19,rb:20,kd:27,Mc:32,le:33,ke:34,jd:35,Fd:36,Ob:37,Zb:38,tb:39,Cd:39,Gb:40,zd:44,me:44,Gd:45,hd:46,Bd:46,Ed:47,ZERO:48,ONE:49,Qc:50,Pc:51,Bc:52,Ac:53,Lc:54,Jc:55,uc:56,Dc:57,zc:59,yc:61,pb:65,zb:66,Bb:67,Fb:68,E:69,Hb:70,Ib:71,Jb:72,Kb:73,Lb:74,Mb:75,Nb:76,Qb:77,Rb:78,Sb:79,Tb:80,
Q:81,Ub:82,Wb:83,Xb:84,Yb:85,$b:86,ac:87,bc:88,cc:89,ub:90,Cb:91,Ad:91,yd:92,pe:93,Dd:93,Kd:96,ae:96,xd:96,Ld:97,Zd:97,Md:98,Yd:98,Nd:99,de:99,Od:100,be:100,Pd:101,Vd:101,Qd:102,fe:102,Rd:103,$d:103,Sd:104,he:104,Td:105,ee:105,ce:106,Ud:107,ge:109,Wd:110,Xd:111,ld:112,pd:113,qd:114,rd:115,sd:116,td:117,ud:118,vd:119,wd:120,md:121,nd:122,od:123,Ec:144,Hc:145,xc:173,Ic:186,vc:187,gd:188,tc:189,je:190,re:191,ed:192,Hd:219,fd:220,oe:221,ne:222,wc:224,Id:901,te:1E3},hb={},ib=(hb[L.zc]=L.Ic,hb[L.yc]=L.vc,
hb[L.xc]=L.tc,hb[L.wc]=L.Cb,hb),jb={Ob:1,tb:2,Jd:3},M={},kb=(M[L.Ab]="\b",M[L.Oc]="\t",M[L.Cc]="\n",M[L.Eb]="\r",M[L.Mc]=" ",M[L.ZERO]="0",M[L.ONE]="1",M[L.Qc]="2",M[L.Pc]="3",M[L.Bc]="4",M[L.Ac]="5",M[L.Lc]="6",M[L.Jc]="7",M[L.uc]="8",M[L.Dc]="9",M[L.pb]="A",M[L.zb]="B",M[L.Bb]="C",M[L.Fb]="D",M[L.E]="E",M[L.Hb]="F",M[L.Ib]="G",M[L.Jb]="H",M[L.Kb]="I",M[L.Lb]="J",M[L.Mb]="K",M[L.Nb]="L",M[L.Qb]="M",M[L.Rb]="N",M[L.Sb]="O",M[L.Tb]="P",M[L.Q]="Q",M[L.Ub]="R",M[L.Wb]="S",M[L.Xb]="T",M[L.Yb]="U",M[L.$b]=
"V",M[L.ac]="W",M[L.bc]="X",M[L.cc]="Y",M[L.ub]="Z",M[L.Ob]="Left",M[L.tb]="Right",M[L.Zb]="Up",M[L.Gb]="Down",M),Qa=["","moz","ms","webkit"],lb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},K={qb:void 0,Ua:"PCjs.localStorage"};E.WebIO=I;
function O(a,b,c,d){a=a===void 0?"default":a;b=b===void 0?a:b;c=c===void 0?{}:c;d=d===void 0?[]:d;I.call(this,a==b);this.ma=a;this.sa=b;C[this.ma]||(C[this.ma]={});C[this.ma][this.sa]&&this.ca("warning: machine configuration contains multiple '%s' devices\n",this.sa);C[this.ma][this.sa]=this;this.id=this.ma==this.sa?this.ma:this.ma+"."+this.sa;va.push(this);this.ja=mb(this,this.ma);this.ready=!0;nb(this,c,d);this.Pb=[]}x(O,I);
function nb(a,b,c){c=b.overrides||c;if(c.length){var d=Wa();for(q in d)if(c.indexOf(q)>=0){var e=d[q];var f=void 0;var g,h=void 0,m=e,p=10;if(m){p||(p=10);var l=m.indexOf(",")>0;l&&(m=m.replace(/,/g,""));var n=g=m.charAt(0);g=="#"?(p=8,g=""):g=="$"&&(p=16,g="");n!=g?m=m.substr(1):(n=g=m.substr(0,2),g=="0b"&&l||g=="^B"?(p=2,g=""):g=="0o"||g=="^O"?(p=8,g=""):g=="^D"?(p=10,g=""):g=="0x"&&(p=16,g=""),n!=g&&(m=m.substr(2)));n=g=m.slice(-1);g=="Y"||g=="y"?(p=2,g=""):g=="."?(p=10,g=""):g=="H"||g=="h"?(p=
16,g=""):g=="K"?g="000":g=="M"?g="000000":g=="G"&&(g="000000000");n!=g&&(m=m.slice(0,-1)+g);n=0;p<=10&&(g=m.match(/(-?[0-9]+)B([0-9]*)$/))&&(m=g[1],n=35-((g[2]||35)&255));(p&&p!=10?p==16?m.match(/^-?[0-9a-f]+$/i)===null:p==8?m.match(/^-?[0-7]+$/)===null:p!=2||m.match(/^-?[01]+$/)===null:m.match(/^[+-]?[0-9]+$/)===null)||isNaN(f=parseInt(m,p))||(n&&(f<0&&(f+=68719476736),f=n>0?f*Math.pow(2,n):Math.trunc(f/Math.pow(2,-n))),h=f)}f=h;f==void 0&&(e=="true"?f=!0:e=="false"?f=!1:(f=e,e='"'+e+'"'));b[q]=
f;a.ca("overriding %s property '%s' with %s\n",a.sa,q,e)}}a.config=b;c=b.bindings;c=c===void 0?{}:c;if(typeof document!="undefined"){a.config.la||(a.config.la=c);(d=Array.isArray(c))?c.indexOf("container")<0&&c.push("container"):c.container||(c.container=a.sa);for(var k in c){e=c[k];if(d)k=e;else if(e.match(/^[0-9]+$/)){var q=+e;a.la[k]=[];do{e=k+q++;e=document.getElementById(e);if(!e)break;a.la[k].push(e)}while(1);continue}(q=document.getElementById(e))&&a.Ma(k,q)}}b=b===void 0?{}:b;a.version=3;
if(a.version){k="";var r;a.ma!=a.sa&&(r=mb(a,a.ma).version)&&r!=a.version&&(k="Machine");k||(r=b.version)&&r>a.version&&(k="Config");k&&(r=a.Ba("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.xe,a.version,k,r),a.error("%s\n\nClearing your browser's cache may resolve the issue.",r))}}function ob(a,b){var c;try{var d=C[a.ma];if(d)for(c in d){var e=d[c];if(e.sa!=e.ma&&!b(e))return!1}return!0}catch(f){a.ca("error while enumerating device '%s': %s\n",c,f.message)}return!1}
O.prototype.Wa=function(a,b){b=b===void 0?!1:b;if(a){var c=I.prototype.Wa.call(this,a,b);if(c===void 0&&b){b=C[this.ma];for(var d in b)if(c=b[d].la[a])break;c||(c=null);this.la[a]=c}}return c};function mb(a,b){var c=b,d=a.ma,e=d.indexOf(".");e>0&&(d=d.substr(0,e),b=b.substr(e+1));b=(e=C[d])&&e[b]||null;if(!b){for(e=0;e<va.length;e++)if(va[e].id===c){b=va[e];break}if(!b)throw Error(a.Ba('no "%s" device',c));}return b}
function P(a,b,c){var d=null,e=C[a.ma];if(e)for(var f in e)if(e[f].config["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(c===void 0||c))throw Error(a.Ba("no %s device",b));return d}function pb(a){return a==a.ja&&a.ready?ob(a,function(b){return pb(b)}):a.ready}function qb(a,b){b=b===void 0?a.ready:b;a.ready=b;if(pb(a)){for(;b=a.Pb.pop();)b();a!=a.ja&&qb(a.ja)}}function rb(a,b){if(pb(a))return b(),!0;a.Pb.push(b);return!1}
O.prototype.ca=function(a){var b=oa.apply(1,arguments);return typeof a=="number"&&Ya(this,a)&&(this.Ca===void 0&&(this.Ca=P(this,"Debugger",!1)),this.ja.Da&1&&(this.Na===void 0&&(this.Na=P(this,"CPU")),this.Na))?(a=b.shift(),I.prototype.ca.call(this,"%#06x: %s.%s\n",this.Na.$c,this.sa,this.Ba.apply(this,[a].concat(A(b))).trim())):I.prototype.ca.call.apply(I.prototype.ca,[this,a].concat(A(b)))};function sb(a,b){(a=C[a.ma])&&delete a[b]}E.Device=O;
function tb(a,b,c){O.call(this,a,b,c);this.type=this.config.type=="static"?ub:vb;this.fa=this.config.addrWidth||16;this.ba=Math.pow(2,this.fa);this.blockSize=this.config.blockSize||(this.fa>16?4096:1024);this.blockSize>this.ba&&(this.blockSize=this.ba);this.ia=this.ba/this.blockSize|0;this.da=Math.log2(this.blockSize)|0;this.ga=(1<<this.da)-1;this.ha=this.config.dataWidth||8;this.aa=Array(this.ia);this.ea=0;a=new Q(a,b+"[NONE]",{size:this.blockSize,bus:this.sa});for(b=0;b<this.ba;b+=this.blockSize)wb(this,
b,this.blockSize,R.NONE,a);a=this.ea;this.ea+=this.type;a&&this.ea||(this.Ya=this.Za)}x(tb,O);
function wb(a,b,c,d,e){for(var f=b>>>a.da;c>0&&f<a.aa.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var m=a.aa[f];if(b!=g||h!=a.blockSize||m&&m.type!=R.NONE)break;var p=m=void 0,l=a,n=b,k=a.fa,q=16;k=k===void 0?0:k;m=m===void 0?0:m;var r="",y="",v=-1;q||(q=l.ue||10);k&&(v=Math.ceil(k/Math.log2(q)));if(p==void 0)switch(q){case 8:p="0o";break;case 16:p="0x";break;case 10:y=".";default:p=""}isNaN(n)||typeof n!="number"?(n=void 0,p=y=""):(n<0&&n>-1&&(n=-1),k&&(n<0&&(n+=Math.pow(2,k)),n>=
Math.pow(2,k)&&(v=Math.ceil(Math.log(n)/Math.log(q)))));for(l=m||-1;v--;){l||(r=","+r,l=m);if(n==void 0){if(r="?"+r,v<0)break}else if(k=n%q,n=Math.trunc(n/q),k+=k>=0&&k<=9?48:55,r=String.fromCharCode(k)+r,!n&&v<0)break;l--}m=a.sa+"["+(p+r+y)+"]";b=e?e.size==a.blockSize?e:new Q(a.ma,m,{type:d,wb:b,size:h,bus:a.sa}):new Q(a.ma,m,{type:d,wb:b,size:h,bus:a.sa});a.aa[f]=b;b=g+a.blockSize;c-=h;f++}}t=tb.prototype;t.Ae=function(a,b){this.Ca&&this.Ca.ca(4,"bus fault (%d) at %n\n",b,a)};
t.Fa=function(){this.Ca===void 0&&(this.Ca=P(this,"Debugger",!1))};t.Ia=function(){};t.xb=function(a){return a&&this.za(a)?!0:!1};t.yb=function(a){this.Ga(a)};t.za=function(a){for(var b=0;b<this.aa.length;b++){var c=this.aa[b];if((this.type==vb||c.type&R.hb)&&c.za){var d=a.shift();if(!c.za(d))return!1}}return!0};t.Ga=function(a){for(var b=0;b<this.aa.length;b++){var c=this.aa[b];if((this.type==vb||c.type&R.hb)&&c.Ga){var d=[];c.Ga(d);a.push(d)}}};
t.Za=function(a,b){this.aa[a>>>this.da].Ya(a&this.ga,b)};var ub=0,vb=1;E.Bus=tb;
function Q(a,b,c){O.call(this,a,b,c);this.wb=this.config.addr;this.size=this.config.size;this.type=this.config.type||R.NONE;this.ba=(a=this.config.bus)?mb(this,a):P(this,a="Bus");if(!this.ba)throw Error(this.Ba("unable to find bus '%s'",a));this.ha=this.ba.ha;this.ea=this.ga=!1;this.values=this.buffer=null;a=this.Za;if(this.ba.type==ub){a=this.bd;if(b=this.ha==8)b=mb(this,this.ma),b=(b&&b.config&&b.config.ArrayBuffer||this.config.ArrayBuffer)!==!1;b&&(this.ga=!0)}switch(this.type){case R.NONE:this.Ya=
this.mc;break;case R.Vb:this.Ya=this.mc;break;case R.hb:this.Ya=a}xb(this,this.config.values);yb(this)}x(Q,O);function xb(a,b){typeof b=="string"?(qb(a,!1),Va(b,function(c,d,e,f){if(e==4)if(!f&&d){try{var g=JSON.parse(d);xb(a,g.values)}catch(h){a.ca("error (%s) parsing resource: %s\n",h.message,c)}qb(a,!0)}else a.ca("error (%d) loading resource: %s\n",f,c)})):a.config.values=b}
function yb(a,b){if(a.type>R.NONE&&(a.ga?(a.buffer=new ArrayBuffer(a.size),new DataView(a.buffer,0,a.size),a.values=new Uint8Array(a.buffer,0,a.size),new Uint16Array(a.buffer,0,a.size>>1),new Int32Array(a.buffer,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}t=Q.prototype;
t.Ia=function(){if(this.config.values)a:{var a=this.ba,b=this.wb,c=this.size,d=this.config.values,e=0,f=b&a.ga;b>>>=a.da;c>d.length&&(c=d.length);for(;c>0&&b<a.aa.length;){var g=a.aa[b++];if(!g)break a;for(;c>0&&f<g.size;)g.Za(f++,d[e++]),c--;f=0}}else this.type&R.hb&&this.values&&this.values.fill(0)};t.mc=function(){};t.Za=function(a,b){this.values[a]=b};t.bd=function(a,b){this.values[a]=b;this.ea=!0;this.Ya=this.Za};
t.za=function(a){if(a){var b=a.shift();if(this.sa==b){this.ea=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=c===void 0?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}yb(this,a)}return!0}}return!1};
t.Ga=function(a){a.push(this.sa);a.push(this.ea);a.push(!1);var b=a.push;if(this.values){var c=this.values;for(var d=0,e=0,f=[];d<c.length;){for(var g=c[d],h=d+1;h<c.length&&c[h]===g;)h++;f[e++]=h-d;f[e++]=g;d=h}c=f.length>=c.length?Array.isArray(c)?c:Array.from(c):f}else c=this.values;b.call(a,c)};var R={NONE:1,Vb:2,hb:4,qe:14,ve:12};E.Memory=Q;
function zb(a,b,c){c.type=R.Vb;Q.call(this,a,b,c);wb(this.ba,this.config.addr,this.config.size,this.config.type,this);rb(this,this.Ia.bind(this));this.Na=this.Ca=void 0;if(E.LED&&this.la[Ab]){var d=this;this.da=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.fa=this.values.length/this.da|0;this.aa=new Bb(a,b+"LEDs",{"class":"LED",bindings:{container:Ra(this,Ab)},type:Cb,cols:this.da,rows:this.fa,color:J(this,"colorROM","green"),backgroundColor:J(this,"backgroundColorROM","black"),persistent:!0}),
Db(this.aa,!0);this.ia=new Eb(a,b+"Input",{"class":"Input",location:[0,0,this.aa.xa,this.aa.wa,this.da,this.fa],bindings:{surface:Ra(this,Ab)}});this.ka=Sa(this)||"";Fb(this.ia,function(e,f){if(d.Na){var g=d.ka;e>=0&&f>=0&&(g="");fb(d,Ta,g)}})}}x(zb,Q);
zb.prototype.za=function(a){var b=!0,c=a.shift();if(c&&this.aa){var d=c.length;this.aa.buffer.length==d?(this.aa.buffer=c,S(this.aa,!0)):(this.ca("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.ca("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};zb.prototype.Fa=function(){this.Na===void 0&&(this.Na=P(this,"CPU"));this.Ca===void 0&&(this.Ca=P(this,"Debugger",!1))};
zb.prototype.Ga=function(a){this.aa&&(a.push(this.aa.buffer),a.push(this.values))};var Ab="array",Ta="cellDesc";E.ROM=zb;
function Eb(a,b,c){O.call(this,a,b,c);this.Da=2097152;this.ka=this.pa=null;this.time=P(this,"Time");this.ja=P(this,"Machine");this.va=J(this,"drag",!1);this.na=J(this,"scroll",!1);this.ya=J(this,"hexagonal",!1);this.fa=J(this,"releaseDelay",0);this.ga=!1;a=this.config.map;this.ba=this.da=null;if(a)if(a.length)this.ba=a;else{this.da={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];typeof g=="string"?g=[g]:g.length==void 0&&(e=g.grid,g=g.keys,typeof g=="string"&&(g=[g]));this.da[f]=
{keys:g,grid:e,state:0}}}this.qa=[];this.ra=[];this.ea=this.ta=null;(a=this.la[Gb])&&Hb(this,a,this.Wa(c.focusBinding,!0),this.config.location);this.Ia()}x(Eb,O);function Fb(a,b){a.pa=b}function Ib(a,b){a.ka=b}function Jb(a,b,c){for(var d=0;d<a.qa.length;d++){var e=a.qa[d];e.id===b&&e.hc(b,c)}}
function Hb(a,b,c,d){d=d===void 0?[]:d;if(d.length||a.ba||a.da){var e={};e.cd=d[0]||0;e.dd=d[1]||0;e.Va=d[2]||b.clientWidth;e.ib=d[3]||b.clientHeight;e.jb=d[4]||1;e.nb=d[5]||1;e.Vc=d[6]||b.naturalWidth||e.Va;e.Xc=d[7]||b.naturalHeight||e.ib;e.nc=d[8]||0;e.oc=d[9]||0;e.Uc=d[10]||0;e.Wc=d[11]||0;a.ba?(e.lb=a.ba.length,e.Xa=a.ba[0].length):(e.Xa=e.jb,e.lb=e.nb,e.jb=e.nb=0);e.dc=e.Va/(e.Xa+e.Xa*e.jb)|0;e.ec=e.ib/(e.lb+e.lb*e.nb)|0;e.Tc=e.dc*e.jb|0;e.fc=e.ec*e.nb|0;e.$a=e.ob=-1;Kb(a,b,e);Lb(a,b,e);a.time&&
a.fa&&(a.xa=Mb(a.time,"timerInputRelease",function(){e.$a<0&&e.ob<0&&Nb(a,-1,-1)}))}if(a.ba||a.da)a.time&&a.fa&&(a.Aa=Mb(a.time,"timerKeyRelease",function(){Ob(a)})),a.ha=0,a.oa="",a.ia=[],d=b,c&&(d=c,a.ea||c.nodeName!="BUTTON"||(d=document,a.ea=c,Pb(a,b),a.ta=b)),Pb(a,d),a.ea||(a.ea=d)}function Qb(a){a.fa?Rb(a.time,a.Aa,a.fa):Ob(a)}
function Pb(a,b){function c(e,f,g){var h=document.activeElement;a.ca(5242880,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,g!=void 0?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.ea&&e!=a.ea&&e!=a.ta?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Sb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=Sb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Sb(a,f,!1,e);c("Up",f);g&&e.preventDefault();b.nodeName=="TEXTAREA"&&(b.value="")}})}
function Kb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.ga){var e=a.ea;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||T(a,b,Tb,d,c)}});b.addEventListener("mousemove",function(d){a.ga||T(a,b,Ub,d,c)});b.addEventListener("mouseup",function(d){a.ga||d.button||T(a,b,U,d,c)});b.addEventListener("mouseout",function(d){a.ga||(c.$a<0?T(a,b,Ub,d,c):T(a,b,U,d,c))})}
function Lb(a,b,c){b.addEventListener("touchstart",function(d){a.na&&(a.ga=!0);T(a,b,Tb,d,c)});b.addEventListener("touchmove",function(d){T(a,b,Ub,d,c)});b.addEventListener("touchend",function(d){T(a,b,U,d,c)})}
function Sb(a,b,c,d){if(c!=void 0){var e=ib[b]||b;var f=kb[b];var g=Vb[e];d=d&&d.location==jb.tb;g&Wb&&d&&(g>>=1);g&&(g&Xb&&(c=!(a.aa&g)),a.aa=c?a.aa|g:a.aa&~g,Jb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=gb.pb&&b<=gb.ub?a.aa&(Yb|Zb)||(a.aa|=Zb,Jb(a,L.rb,!0)):b>=gb.a&&b<=gb.z&&a.aa&Zb&&(a.aa&=~Zb,Jb(a,L.rb,!1));if(a.ba){if(c!=void 0)return!1;for(e=0;e<a.ba.length;e++)for(g=a.ba[e],d=0;d<g.length;d++)if(g[d].split("|").indexOf(f)>=0)return a.ha?a.ia.length<16&&a.ia.push(b):(a.ha=1,a.oa=
f,Nb(a,d,e),Jb(a,f,!0),Qb(a)),!0}if(a.da){if(c==void 0)return!0;b=Object.keys(a.da);for(e=0;e<b.length;e++)if(g=b[e],a.da[g].keys.indexOf(f)>=0)return Jb(a,g,c),a.da[g].state=c?1:0,!0}return!1}function Ob(a){a.ha==1?(a.ha++,Jb(a,a.oa,!1),a.oa="",Nb(a,-1,-1),Qb(a)):(a.ha=0,a.ia.length&&Sb(a,a.ia.shift()))}Eb.prototype.Ia=function(){this.aa=0;this.ua=this.wa=-1};
function T(a,b,c,d,e){var f=-1,g=-1,h=!1,m=-1,p=-1;if(c<U){d=d||window.event;d.targetTouches&&d.targetTouches.length?(m=d.targetTouches[0].clientX,p=d.targetTouches[0].clientY,h=d.targetTouches.length>1):(m=d.clientX,p=d.clientY);var l=d.target.getBoundingClientRect();m-=l.left;p-=l.top;m=e.Vc/b.offsetWidth*m|0;p=e.Xc/b.offsetHeight*p|0;var n=m-e.cd;var k=p-e.dd;var q=l=!1;var r=m>=e.nc&&m<e.nc+e.Uc&&p>=e.oc&&p<e.oc+e.Wc;if(n>=0&&n<e.Va&&k+e.fc>=0||r)if(h||a.na||d.preventDefault(),n>=0&&n<e.Va&&k>=
0&&k<e.ib){q=!0;d=e.Va/e.Xa|0;var y=e.ib/e.lb|0,v=n/d|0,u=k/y|0;!a.ya||u&1||(n-=d>>1,v=n/d|0,v==e.Xa-1&&(n=-1));y=u*y+(e.fc>>1);n-=v*d+(e.Tc>>1);k-=y;n>=0&&n<e.dc&&k>=0&&k<e.ec&&(f=v,g=u,l=!0)}}n=n||0;k=k||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Tb||c==U)for(v=0;v<a.ra.length;v++)u=a.ra[v],c==U?u.hc(u.id,!1):(y=k/(b/u.ze|0)|0,(n/(d/u.ye|0)|0)==u.Me&&y==u.Ne&&u.hc(u.id,!0));if(!h)if(c==Tb)e.$a=m,e.ob=p,q?(Nb(a,f,g),l&&a.fa&&Rb(a.time,a.xa,a.fa,!0)):r&&a.ja.Fa();else if(c==Ub)e.$a>=0&&e.ob>=0&&a.va?
Nb(a,f,g):a.pa&&a.pa(f,g);else if(c==U){if(c=a.fa)c=a.time,f=a.xa,c=c.aa&&f>0&&f<=c.ba.length?c.ba[f-1].Ea>=0:!1;c||Nb(a,-1,-1);e.$a=e.ob=-1}else a.ca("unrecognized action: %d\n",c)}function Nb(a,b,c){if(b!=a.ua||c!=a.wa)a.ua=b,a.wa=c,a.ka&&a.ka(b,c)}var Tb=1,Ub=2,U=3,Gb="surface",Yb=3,Wb=170,Zb=512,Xb=3584,X={},Vb=(X[L.Kc]=2,X[L.sc]=8,X[L.qc]=32,X[L.Cb]=128,X[L.rb]=Zb,X[L.Ec]=1024,X[L.Hc]=2048,X);E.Input=Eb;
function Bb(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.la[$b];if(!a)throw Error("LED "+this.config.la[$b]+" binding for '"+$b+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Ra=Ra(this,$b)+".canvas";b.setAttribute("id",this.Ra);this.Oa=a;this.type=Ua(J(this,"type",Cb,ac),bc,cc);this.ha=dc[this.type][0];this.na=dc[this.type][1];this.width=J(this,
"width",this.ha);this.height=J(this,"height",this.na);this.da=J(this,"cols",1);this.ba=this.da+J(this,"colsExtra",0);this.va=J(this,"rows",1);this.ea=this.va+J(this,"rowsExtra",0);this.xa=this.width*this.da;this.wa=this.height*this.va;this.ga=ec("black",0);this.fa=fc(this.config.color)||this.ga;this.eb=ec(this.fa,1,.25);this.cb=ec(this.fa,1,2);this.ka=fc(this.config.backgroundColor);this.fb=J(this,"fixed",!1);this.fb||(b.style.width="100%",b.style.height="auto");this.Pa=J(this,"hexagonal",!1);this.gb=
J(this,"highlight",!0);this.Aa=J(this,"persistent",this.type<cc);b.setAttribute("width",this.xa.toString());b.setAttribute("height",this.wa.toString());b.style.backgroundColor=this.ga;a.appendChild(b);this.Qa=b.getContext("2d");if(this.qa=document.createElement("canvas"))this.qa.width=this.La=this.ha*this.da,this.qa.height=this.ta=this.na*this.va,this.aa=this.qa.getContext("2d");this.Sa=(this.ea+1)*this.ba*4;this.buffer=Array(this.Sa);this.pa=null;this.Ta=this.da<this.ba?(this.ba-this.da)*4:0;this.ia=
this.ra=!1;this.Ja=0;this.ya=!0;this.oa=0;this.ua=-1;var d=this;this.time=P(this,"Time");hc(this.time,function(e,f){S(d,!1,e,f)});Db(d,!0)}x(Bb,O);function Db(a,b){ic(a,a.buffer);a.ia=a.ra=!0;b&&S(a,!0)}function jc(a){a.ka?(a.aa.fillStyle=a.ka,a.aa.fillRect(0,0,a.La,a.ta)):a.aa.clearRect(0,0,a.La,a.ta)}
function S(a,b,c,d){b=b===void 0?!1:b;c=c===void 0?0:c;d=d===void 0?60:d;if(a.ia||b){if(a.type<cc){d=0;if(!a.Aa||b)jc(a);else if(a.oa){d=a.da-a.oa;var e=a.ha*d;a.aa.drawImage(a.qa,a.ha*a.oa,0,e,a.ta,0,0,e,a.ta)}for(var f=e=0;f<a.ea;f++){for(var g=0;g<a.da;g++){var h=a.buffer[e],m=a.buffer[e+1]||a.ga,p=!1,l=!!(a.buffer[e+3]&Y),n=a.gb&&e==a.ua;!a.ya&&h&&(h=kc,l=p=!0);if(l||n||b){if(g>=d)a:{l=a;var k=h;h=m;var q=g;m=f;var r=n;q=q===void 0?0:q;m=m===void 0?0:m;r=r===void 0?!1:r;var y=0;if(l.Pa&&!(m&1)&&
(y=l.ha>>1,q==l.da-1))break a;if(h&&h!=l.fa){r=r?ec(h,1,2):h;var v=ec(h,1,.25)}else r=r?l.cb:l.fa,v=l.eb;h=!1;k=k?r:v;r==l.ga&&(k=l.ka,h=!0);r=q*l.ha+y;v=m*l.na;l.Aa&&(q=q*l.ha+y,m*=l.na,l.ka?(l.aa.fillStyle=l.ka,l.aa.fillRect(q,m,l.ha,l.na)):l.aa.clearRect(q,m,l.ha,l.na));l.aa.fillStyle=k;m=lc[l.type];m.length==3?(l.aa.beginPath(),l.aa.arc(r+m[0],v+m[1],m[2],0,Math.PI*2),h?(l.aa.globalCompositeOperation="destination-out",l.aa.fill(),l.aa.globalCompositeOperation="source-over"):l.aa.fill()):l.aa.fillRect(r+
m[0],v+m[1],m[2],m[3])}a.buffer[e+3]=n||p?a.buffer[e+3]|Y:a.buffer[e+3]&~Y}e+=4}e+=a.Ta}a.oa=0}else{b="";for(d=0;d<a.buffer.length;d+=4)b+=a.buffer[d]||" ",a.buffer[d+3]&mc&&(b+=".");jc(a);for(f=e=d=0;d<b.length;d++){p=b[d];p=="."&&e&&e--;g=a;l=p;p=e;n=f;p=p===void 0?0:p;n=n===void 0?0:n;if(l=nc[l])for(m=0;m<l.length;m++)if(h=g,q=oc[l[m]]){y=(p===void 0?0:p)*h.ha;k=(n===void 0?0:n)*h.na;h.aa.fillStyle=h.fa;h.aa.beginPath();if(q.length==3)h.aa.arc(y+q[0],k+q[1],q[2],0,Math.PI*2);else for(r=0;r<q.length;r+=
2)r?h.aa.lineTo(y+q[r],k+q[r+1]):h.aa.moveTo(y+q[r],k+q[r+1]);h.aa.closePath();h.aa.fill()}if(++e==a.da&&(e=0,++f==a.ea))break}}a.Qa.globalCompositeOperation=a.ka&&a.fa!=a.ga?"source-over":"copy";a.Qa.drawImage(a.qa,0,0,a.La,a.ta,0,0,a.xa,a.wa);a.ia=!1;a.ua=-1}else a.Aa||a.ra||(!c||!a.Ja||c-a.Ja>=(1E3/d|0))&&Db(a,!0);a.ra=!1;c&&(a.Ja=c)}function pc(a,b){b=b===void 0?!0:b;a.ya!=b&&(a.ya=b,a.ia=!0)}function qc(a,b,c){b=(c*a.ba+b)*4;return b<=a.buffer.length-4?a.buffer[b+2]:0}
function rc(a,b,c){var d;b=(c*a.ba+b)*4;b<=a.buffer.length-4&&(d=a.buffer[b]);return d}function fc(a){return(a=a||void 0)&&lb[a]||a}function ec(a,b,c){b=b===void 0?1:b;c=c===void 0?1:c;if(a){var d=[];a=lb[a]||a;if(sc(a,d)){a="rgba(";var e;for(e=0;e<3;e++){var f=Math.round(d[e]*c);f=f<0?0:f>255?255:f;a+=f+","}a+=(e<d.length?d[e]:b)+")"}}return a}function ic(a,b){for(var c=0;c<b.length;c+=4)tc(a,b,c)}function tc(a,b,c){b[c]=a.type<cc?kc:" ";b[c+1]=a.fa==a.ga?null:a.fa;b[c+2]=0;b[c+3]=Y}
Bb.prototype.za=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.fa&&c==this.ka&&a&&a.length==this.buffer.length){this.buffer=a;for(b=0;b<=this.buffer.length-4;b+=4)this.buffer[b+1]==this.ga&&(this.buffer[b+1]=null);S(this,!0);return!0}return!1};
function sc(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}Bb.prototype.Ga=function(a){this.buffer&&(a.push(this.fa),a.push(this.ka),a.push(this.buffer))};
function uc(a,b,c,d){var e=null;c>=0&&c<a.ea&&b>=0&&b<a.ba&&(e=!1,d=d||a.fa,d==a.ga&&(d=null),b=(c*a.ba+b)*4,a.buffer[b+1]!==d&&((a.buffer[b+1]=d)||(a.buffer[b]=kc),a.buffer[b+3]|=Y,a.ia=e=!0),a.ua=b,a.ra=!0);return e}function vc(a,b,c,d){if(c>=0&&c<a.ea&&b>=0&&b<a.ba){b=(c*a.ba+b)*4;c=0;if(a.buffer[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.buffer[b+2]!==c&&(a.buffer[b+2]=c,a.buffer[b+3]|=Y,a.ia=!0);a.ua=b;a.ra=!0}}
function wc(a,b,c,d){var e=!1,f=0&xc;b=(c*a.ba+b)*4;if(b<=a.buffer.length-4){if(a.buffer[b]!==d||(a.buffer[b+3]&xc)!==f)a.buffer[b]=d,a.buffer[b+3]=a.buffer[b+3]&~xc|f|Y,a.ia=e=!0;a.ua=b;a.ra=!0;a.oa=0}return e}
var bc=0,Cb=1,cc=3,ac={small:bc,round:Cb,square:2,digit:cc},$b="container",kc=0,xc=129,mc=1,Y=128,yc={},lc=(yc[bc]=[4,4,4],yc[Cb]=[16,16,14],yc[2]=[2,2,28,28],yc),dc=[[8,8],[32,32],[32,32],[96,128]],oc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},nc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};E.LED=Bb;
function zc(a,b,c){O.call(this,a,b,c);this.Ra=J(this,"cyclesMinimum",1E5);this.fb=J(this,"cyclesMaximum",1E9);this.Sa=Ua(J(this,"cyclesPerSecond",1E6),this.Ra,this.fb);this.xa=60;this.ta=0;this.ua=1E3/this.xa;this.Nc=J(this,"updatesPerSecond",2)||2;this.Gc=1E3/this.Nc;this.eb=0;this.Rc=J(this,"timeLock",!0);this.Pa=this.pa=0;this.Oa=this.ha=1;this.cb=this.ka=this.Sa/1E4/100;this.Aa=[];this.na=[];this.ba=[];this.Ja=[];this.Ta=this.aa=this.ya=this.ia=!1;this.oa=this.ea=0;a=Pa("requestAnimationFrame");
if(!a){a="setTimeout";var d=this.ua}this.gb=window[a].bind(window,this.ad.bind(this),d);this.Fc=window[Pa("cancelAnimationFrame")||"clearTimeout"].bind(window);this.wa=this.va=this.fa=this.da=this.Qa=0;Ac(this)||Bc(this,this.Oa)}x(zc,O);function hc(a,b){a.Aa.push(b)}t=zc.prototype;
t.Ma=function(a,b){var c=this;switch(a){case Cc:b.onclick=function(){Dc(c)&&(c.aa?Ec(c):c.start())};break;case Fc:b.onclick=function(){Bc(c,c.ha<<1);Gc(c,Hc(c.ka))};break;case Ic:b.onclick=function(){Dc(c)&&(c.aa?c.ca("already running\n"):c.ea?Ec(c):Jc(c))};break;case Kc:b.addEventListener("mousedown",function(){c.ia=!0}),b.addEventListener("mouseup",function(){Ac(c);c.ia=!1}),b.addEventListener("mousemove",function(){c.ia&&Ac(c)}),b.addEventListener("change",function(){c.ia=!0;Ac(c);c.ia=!1})}O.prototype.Ma.call(this,
a,b)};function Mb(a,b,c){var d=d===void 0?-1:d;var e=a.ba.length+1;a.ba.push({id:b,Sc:c,kb:d,Ea:-1});d>=0&&Rb(a,e,d);return e}
function Lc(a,b,c,d){var e=0,f=a.ka,g=f*1E6;b&&c&&(f=b/(c*10)/100,a.ca(262144,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.ua&&(a.ha>1&&(a.ha>>=1,a.ca(549755813888,"frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.ua,a.ha)),e=d));a.pa=f;a.Pa=f/a.cb;b=a.Pa/a.ha;a.Qa=g/b/a.xa+1E-8;a.ca(262144,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.Qa,g,b,a.xa);return e}
function Mc(a,b){a.va=a.fa=b;if(!a.na.length)return a.fa=0,a.va;for(var c=0;a.fa>0;){if(c<a.na.length){var d=a.na[c++];b=d.kc.call(d,b)||1}else c=b=0;a.fa-=b}return a.va-a.fa}function Nc(a,b){b=b===void 0?a.va-a.fa:b;if(!a.aa){if(a.da)for(var c=0;c<a.na.length;c++){var d=a.na[c];d.lc.call(d)}a.da=b}a.da-=b;a.da<1&&(a.ya=!0);a.wa+=b;a.va=a.fa=0;a.aa||(a.wa=0);return b}
function Oc(a,b){b=b===void 0?0:b;if(b){var c=b;a.da+=b}else for(c=a.da,c<1&&(c=a.da+=a.Qa),c<0&&(a.ca(262144,"warning: cycle count dropped below zero: %f\n",c),c=a.da=0),c|=0,b=a.ba.length;b>0;b--){var d=a.ba[b-1];!(d.Ea<0)&&c>d.Ea&&(c=d.Ea)}return c}function Hc(a){a>=1?a=a.toFixed(2)+"Mhz":(a=Math.round(a*1E6),a=a<=999?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Dc(a){return a.Ta?!0:(a.ca("not powered\n"),!1)}
function Pc(a,b){if(b>=1)for(var c=a.ba.length;c>0;c--){var d=a.ba[c-1];d.Ea<0||(d.Ea-=b,d.Ea<=0&&(d.Ea=-1,d.Sc(),d.kb>=0&&Rb(a,c,d.kb)))}}t.Fa=function(a){this.Ta=a;this.Ca===void 0&&(this.Ca=P(this,"Debugger",!1))};
t.ad=function(a){a=a===void 0?Date.now():a;this.oa=0;if(this.aa){if(this.ta){var b=a-this.ta;b<1&&(b=16.67);this.xa=1E3/b}this.ta=a;a=Date.now();this.qa&&(b=a-this.ra-this.ua,b>this.ua&&(this.ga+=b,this.ca(549755813888,"browser throttling detected, compensating by %5.3fms\n",b)));this.ra=a;this.ga||(this.ga=a);this.La=0;try{this.ya=!1;do Pc(this,Nc(this,Mc(this,Oc(this))));while(this.aa&&!this.ya)}catch(c){this.ca("%s\n",c.message),Ec(this)}this.qa=Date.now();this.La&&(this.ga+=this.La,this.ra+=this.La);
this.ra+=Lc(this,this.wa,this.qa-this.ga,this.qa-this.ra);this.qa-this.eb>=this.Gc&&this.update();for(a=0;a<this.Aa.length;a++)this.Aa[a](this.ta,this.xa);this.oa=this.gb()}};function Bc(a,b){if(b!==void 0){if(b<1||!a.ia&&a.pa>0&&a.pa<a.ka*.9)b=a.Oa;a.ha=b;b=a.cb*a.ha;a.ka!=b&&(a.ka=b,Gc(a,Hc(a.ka)))}a.ga=a.qa=0;a.da=a.wa=0;Lc(a);for(b=a.ba.length;b>0;b--){var c=a.ba[b-1];c.kb>=0&&Rb(a,b,c.kb,!0)}}
function Ac(a){var b=a.la[Kc];return b?(Bc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.fb-a.Ra)+a.Ra)/a.Sa|0),!0):!1}function Rb(a,b,c,d){b>0&&b<=a.ba.length&&(b=a.ba[b-1],d||b.Ea<0)&&(c=Math.ceil(a.Sa*(a.Rc?a.Oa:a.Pa)/1E3*(c===void 0?1E3:c)),a.aa&&(c+=Nc(a)),b.Ea=c)}t.start=function(){if(this.aa||this.ea)return!1;this.aa=!0;this.ga=this.qa=this.ta=0;this.update(!0);this.oa=this.gb();return!0};
function Jc(a,b){b=b===void 0?1:b;a.aa||(b&&!a.ea&&(a.ea=b),a.ea&&(a.ea--,Pc(a,Nc(a,Mc(a,Oc(a,1)))),a.update(!1),a.ea&&setTimeout(function(){Jc(a,0)},0)))}function Ec(a){a.aa?(a.aa=!1,Nc(a),a.oa&&(a.Fc(a.oa),a.oa=0),a.update(!0)):a.ea&&(a.ea=0,a.update(!0))}
t.update=function(a){a&&this.ca(this.aa?"started with %s target\n":"stopped\n",Hc(this.ka));fb(this,Cc,this.aa?"Halt":"Run");fb(this,Ic,this.ea?"Stop":"Step");this.ia||(this.ca(262144,"getSpeedCurrent(%5.3fhz)\n",this.pa*1E6),Gc(this,this.aa&&this.pa?Hc(this.pa):"Stopped"));for(a=0;a<this.Ja.length;a++){var b=this.Ja[a];b.Zc.call(b)}this.eb=Date.now();this.ya=!0};function Gc(a,b){fb(a,Qc,b);fb(a,Fc,b)}var Cc="run",Fc="setSpeed",Qc="speed",Ic="step",Kc="throttle";E.Time=zc;
function Z(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.Ca=void 0;this.$c=0;this.time=P(this,"Time");this.time.na.push(this);this.time.Ja.push(this);this.qa=this.pa=0}x(Z,O);Z.prototype.abort=function(a){this.ca("%s\n",a.message);Ec(this.time)};Z.prototype.kc=function(a){this.qa=this.pa=a===void 0?0:a;return this.jc()};Z.prototype.lc=function(){this.qa-=this.pa;this.pa=0};Z.prototype.jc=function(){return this.qa-this.pa};
function Rc(a,b,c){Z.call(this,a,b,c);this.ka=J(this,"wrap",!1);this.ra=(this.va=J(this,"font",""))&&Sc[this.va]||Sc.Helvetica;this.ta=J(this,"rule","");this.oa=J(this,"pattern","");Tc(this,this.wa=J(this,"message",""));this.Ja=J(this,"toggleColor",!1);this.Aa=Array(Uc(this).length);if(c=P(this,"LED",!1)){this.aa=c;Vc(this)||Db(c,!0);this.input=P(this,"Input",!1);var d=this;this.xa=new Eb(a,b+"Input",{"class":"Input",location:[0,0,c.xa,c.wa,c.da,c.va],drag:!(!this.input||!this.input.va),scroll:!(!this.input||
!this.input.na),hexagonal:c.Pa,bindings:{surface:c.Ra}});Ib(this.xa,function(e,f){var g=d.aa;e>=0&&f>=0&&(d.ia?uc(g,e,f,d.ia)?wc(g,e,f,1):d.Ja?uc(g,e,f):wc(g,e,f,1-rc(g,e,f)):wc(g,e,f,1-rc(g,e,f)),vc(g,e,f,Uc(d,!!rc(g,e,f))),S(g))});this.ha=[];this.ya=c.fa;Wc(this,this.ya);Xc(this);Yc(this,this.config[Zc]);Na(this,this.Yc.bind(this))}}x(Rc,Z);t=Rc.prototype;
t.Ma=function(a,b){var c=this,d;Z.prototype.Ma.call(this,a,b);switch(a){case $c:case ad:b.onchange=function(){bd(c,a)};bd(this);break;case Zc:b.onchange=function(){Yc(c)};break;case cd:Ma(b,dd(this.config[cd]),!1,this.config.pattern);b.onchange=function(){var e=c.la[cd];e&&e.options.length&&((e=e.options[e.selectedIndex].value)?Vc(c,e):c.Ia())};break;case ed:b.onclick=function(){var e=fd(c,!0),f=c.la[gd];f&&(e='"'+f.value+'":"'+e.replace(/^([0-9]+\/)*/,"")+'",');c.ca("%s\n",e)};break;case hd:b.onclick=
function(){var e=fd(c);c.ca("%s\n",e);var f=window.location.href;f=f.indexOf("pattern=")>=0?f.replace(/(pattern=)[^&]*/,"$1"+e.replace(/\$/g,"$$$$")):f+((f.indexOf("?")<0?"?":"&")+"pattern="+e);window.location=f};break;case gd:b.onkeypress=function(e){b.value=String.fromCharCode(e.charCode);var f=c.la[id];f&&(f.textContent=b.value);e.preventDefault()};break;default:a.startsWith(jd)?b.onclick=function(){Xc(c,a)}:(d=this.config[cd])&&d[a]&&(b.onclick=function(){Vc(c,a)})}};
function dd(a){var b={},c;for(c in a){for(var d=c,e=a[c],f=0;f<e.length;f++)if(e[f].indexOf("#N")==0){d=e[f].substr(2).trim();break}b[d]=c}return b}
t.kc=function(a){a=a===void 0?0:a;var b=0;if(a>=0){var c=1;do{switch(this.ta){case kd:var d=0;for(var e=this.aa,f=e.da,g=e.ea,h=this.Aa,m=0;m<g;m++)for(var p=0;p<f;p++){var l=e,n=h,k=!1,q=(m*l.ba+p)*4;if(q<=l.buffer.length-4&&l.buffer[q+1])for(k=!0,l=l.buffer[q+2],q=n.length-1;q>=0;q--)n[q]=l&15,l>>>=4;if(k){d++;if(h[0])h[0]--;else{k=(n=rc(e,p,m))||0;switch(n){case 1:if(k=kc,h[0]=h[2],h[0]){h[0]--;break}case kc:if(h[3]&&(k=this.ha.indexOf(e.buffer[(m*e.ba+p)*4+1]||e.ga),k>=0)){for(k+=h[3];k>=this.ha.length;)k-=
this.ha.length;uc(e,p,m,this.ha[k])}k=1;h[0]=h[1];h[0]&&h[0]--}k!==n&&wc(e,p,m,k)}vc(e,p,m,h)}}break;case ld:c=a||c;d=c;d=d===void 0?1:d;e=0;f=this.aa;g=f.ba;h=f.ea;if(f.oa||!md(this,d))d=0;else{m=f.buffer;l=4*d;p=4*g;k=q=n=0;for(this.na=this.ua=-1;n<g-d;){for(var r=1,y=k,v=0;v<h;v++){var u=m[k],z=m[k]=m[k+l];u=z!==u?Y:0;m[k+1]=m[k+l+1];m[k+2]=m[k+l+2];m[k+3]=m[k+l+3]|u;z&&(e++,r=0);k+=p}k=y+4;n++<f.da&&(r?q++:(this.na<0&&(this.na=q),q=0))}this.na<0&&(this.na=q);for(this.ua=q;n<g;){l=k;for(q=0;q<
h;q++)tc(f,m,k),k+=p;k=l+4;n++}f.ia=!0;f.oa=d;d=e}break;case nd:d=0;e=this.aa;f=e.buffer;g=e;g.pa||(g.pa=Array(g.Sa),ic(g,g.pa));g=g.pa;h=e.da;m=e.ea;p=h*4+e.Ta;n=m*p;k=0;l=k-p;q=l-4;r=l+4;y=k-4;v=k+4;z=k+p;u=z-4;for(var D=z+4,H=0;H<m;H++){H?H==m-1&&(this.ka?(z-=n,u-=n,D-=n):z=u=D=n):this.ka?(l+=n,q+=n,r+=n):l=q=r=n;for(var V=0;V<h;V++){V?V==1?this.ka?(y-=p,q-=p,u-=p):(y=k-4,q=l-4,u=z-4):V==h-1&&(this.ka?(v-=p,r-=p,D-=p):v=r=D=n):this.ka?(y+=p,q+=p,u+=p):y=q=u=n;var W=f[k],N=f[q]+f[l]+f[r]+f[v]+f[D]+
f[z]+f[u]+f[y];N==3?W=1:N!=2&&(W=kc);g[k]=W;g[k+1]=f[k+1];g[k+2]=f[k+2];g[k+3]=f[k+3]|(f[k]!==W?Y:0);k+=4;q+=4;l+=4;r+=4;v+=4;D+=4;z+=4;u+=4;y+=4;W==1&&d++}this.ka?(H||(l-=n,q-=n,r-=n),v+=p,r+=p,D+=p):(H||(l=k-p,q=l-4),v=k+4,r=l+4,D=z+4)}f=e.buffer;e.buffer=e.pa;e.pa=f;e.ia=!0}a||this.ca("active cells: %d\n",d);b+=c}while(b<a)}return b};t.lc=function(){};t.jc=function(){return 0};function od(a,b){var c=0;(a=a.la[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}
function Uc(a,b){var c=0;if(b&&(b=a.la[pd])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=od(a,qd)+od(a,rd),!(d&1)&&c==d-1||b.selectedIndex<0||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<sd.length;b++)c.push(od(a,sd[b]));return c}
function Vc(a,b){var c=a.aa,d=-1,e=-1,f="";b||a.oa.match(/^[0-9]/)||(b=a.oa);if(b){var g=a.config[cd];g=g&&g[b];if(!g)return a.ca("unknown pattern: %s\n",b),!1;a.ca('loading pattern "%s"\n',b);for(var h=b=0;b<g.length;b++){var m=g[b];if(m[0]=="#")a.ca("%s\n",m);else if(h++){var p=m.indexOf("!");if(p>=0){f+=m.substr(0,p);break}f+=m}else{var l=m.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!l)return a.ca("unrecognized header line\n"),!1;var n=+l[1];var k=+l[2];l=
l[3]}}}else{if(!a.oa)return!1;f=0;l=a.oa.split("/");l.length==5&&(d=+l[f++],e=+l[f++]);if(l.length==3||l.length==5)n=+l[f++],k=+l[f++],f=l[f];else return a.ca("unrecognized pattern: %s\n",a.oa),!1;l=a.ta}if(l!=a.ta)return a.ca("unsupported rule: %s\n",l),!1;d<0&&(d=c.ba-n>>1);e<0&&(e=c.ea-k>>1);return d<0||d+n>c.ba||e<0||e+k>c.ea?(a.ca("pattern too large (%d,%d)\n",n,k),!1):td(a,d,e,f)>0}
function td(a,b,c,d,e){e=e===void 0?!1:e;var f=a.aa,g=[0,0,0,1],h=0,m=!1,p=!1;d=d.split(/([a-z$])/i);e||Db(f);for(var l=0,n=b,k=0;l<d.length-1;){var q=d[l++],r=d[l++],y=+q;for(q=q===""?1:y;q--;){var v=0,u=!1;switch(r){case "$":m=p=!1;b=n;c++;break;case "C":h=y;p=!0;break;case "R":g[0]=y;m=!0;break;case "G":g[1]=y;m=!0;break;case "B":g[2]=y;m=!0;break;case "A":g[3]=y;m=!0;break;case "b":u=wc(f,b,c,kc);v++;break;case "o":u=wc(f,b,c,1);v++;break;default:a.ca("unrecognized pattern token: %s\n",r)}if(u==
null)a.ca("invalid pattern position (%d,%d)\n",b,c);else{if(m){u=f;var z=g;u=z.length<4||z[3]==1?u.Ba("#%02x%02x%02x",z[0],z[1],z[2]):u.Ba("rgba(%d,%d,%d,%d)",z[0],z[1],z[2],z[3]);uc(f,b,c,u)}p&&(u=(c*f.ba+b)*4,u<=f.buffer.length-4&&f.buffer[u+2]!=h&&(f.buffer[u+2]=h));k<b&&(k=b);b+=v}}}e||S(f,!0);return(k-=n-1)<0?0:k}
t.za=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return this.ca("Invalid saved state\n"),!1;var c=b.shift();if((c|0)!==3)return this.ca("Saved state version mismatch: %3.2f\n",c),!1;try{this.da=b.shift(),this.ea=b.shift(),this.fa=b.shift(),this.ba=b.shift()}catch(d){return this.ca("Controller state error: %s\n",d.message),!1}return Wa().message||Wa().pattern||Wa()[Zc]||!(a=a.stateLEDs||a[1])||!this.aa||this.aa.za(a)?!0:!1};
t.Yc=function(a){var b="",c=a.shift();switch(a.shift()[0]){case "s":Tc(this,a.join(" "));break;case "?":b="";ud.forEach(function(d){b+=d+"\n"});b&&(b="additional commands:\n"+b);break;default:c&&(b="unrecognized command '"+c+"' (try '?')\n")}return b};t.xb=function(a){return a&&this.za(a)?!0:!1};t.Fa=function(a){a?this.time.start():Ec(this.time)};t.Ia=function(){this.ca("reset\n");Db(this.aa,!0);pc(this.aa,!0);this.wa&&Tc(this,this.wa)};t.yb=function(a){this.Ga(a)};t.Zc=function(){this.time.aa||S(this.aa)};
function md(a,b,c,d){b=b===void 0?1:b;c&&(a.fa=c,a.ba=d);switch(a.fa){case vd:return!1;case wd:case xd:if(a.ba>0)return a.ba-=b,!0;break;case yd:if(a.ba>0)return a.ba-=b,!1;break;case zd:if(a.na>a.ua)return!0;break;case Ad:pc(a.aa,!1);a.fa=yd;break;case Bd:pc(a.aa,!0);a.fa=yd;break;default:return!1}if(c)a=!1;else a:if(b=b===void 0?1:b,a.da){a.ea>=a.da.length&&(a.ea=0);c=a.da[a.ea++];if(c=="$"){d=0;for(var e=a.ea;e<a.da.length;){var f=a.da.charCodeAt(e)-48;if(f<0||f>9)break;d=d*10+f;e++}if(e<a.da.length)if(f=
a.da[e++],f=="$")a.ea=e;else{var g=Cd[f];if(g){a.ea=e;a=md(a,b,g,d);break a}a.ca("unrecognized message code: $%s\n",f)}}c==" "?a.ba+=2:(d=a.aa.da+1,e=a.ba<0?a.ba:0,c=a.ra[c]||a.ra[c.toUpperCase()],f=Math.round((a.aa.va-a.ra.height)/2),c&&(a.ba+=td(a,d+e,f<0?0:f,c,!0)),a.ba+=2-b);a.fa=xd;a=!0}else a.fa=vd,a=!1;return a}
function fd(a,b){function c(W){var N=!1;l[3]==null&&(l[3]=1);if(v){if(m){if(l[0]!==r[0]||l[1]!==r[1]||l[2]!==r[2]||l[3]!==r[3])N=!0;V!==y&&(N=!0)}p!==q&&(N=!0);if(N||W&&q)m&&(n[0]!==r[0]&&(n[0]=r[0],e+=(r[0]||"")+"R"),n[1]!==r[1]&&(n[1]=r[1],e+=(r[1]||"")+"G"),n[2]!==r[2]&&(n[2]=r[2],e+=(r[2]||"")+"B"),n[3]!==r[3]&&(n[3]=r[3],e+=(r[3]||"")+"A"),k!==y&&(k=y,e+=(y||"")+"C")),v>1&&(e+=v),e+=q===1?"o":"b",N=!0}W?(e+="$",v=0):(N?v=1:v++,q=p,r[0]=l[0],r[1]=l[1],r[2]=l[2],r[3]=l[3],y=V)}var d=a.aa,e="",
f=0,g=a.aa.ba,h=a.aa.ea,m=!!a.ha.length,p,l=[0,0,0],n=[0,0,0,1],k=0,q=0,r=[0,0,0,1],y=0,v=0;a=0;var u=d.ba-1,z=d.ea-1;if(b){b&&(a=u,u=0);for(g=0;g<d.ea;g++)for(h=0;h<d.ba;h++)(p=rc(d,h,g))&&b&&(a>h&&(a=h),u<h&&(u=h));g=u-a+1;h=z+1;g<0&&(g=0);h<0&&(h=0)}for(var D=0;D<=z;D++){for(var H=a;H<=u;H++){p=rc(d,H,D);sc(d.buffer[(D*d.ba+H)*4+1]||d.ga,l);var V=qc(d,H,D);c()}c(!0)}if(!b)for(;e[0]=="$";)f++,h--,e=e.slice(1);for(;e.slice(-2)=="$$";)h--,e=e.slice(0,-1);e=="$"&&(h=0);e=(b?"":"0/"+f+"/")+g+"/"+h+
"/"+e.slice(0,-1);return e=e.replace(/\$+$/,"")}t.Ga=function(a){var b=[],c=[];b.push(3);b.push(this.da);b.push(this.ea);b.push(this.fa);b.push(this.ba);this.aa&&this.aa.Ga(c);a.push(b);a.push(c)};function Tc(a,b){a.da!=b&&(b&&a.ca('new message: "%s"\n',b),a.da=b);a.fa=wd;a.ea=a.ba=0}t.toString=function(){return""};
function Yc(a,b){var c=a.la[Zc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.aa;a.Oa&&(a.Oa.style.backgroundImage=b?"url('"+b+"')":"none")}}
function bd(a,b){var c=a.la[$c],d=a.la[ad];b=b===$c;c&&!c.options.length&&(Ma(c,a.config.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.ga=a.config.colors[c.options[c.selectedIndex].value];for(var e in a.ga)if(b=a.config[e.toLowerCase()])b[0]!="#"&&(b="#"+b),a.ca('overriding color "%s" with %s (formerly %s)\n',e,b,a.ga[e]),a.ga[e]=b;Ma(d,a.ga,!0)}c&&d&&d.options.length&&(a.ia=d.options[d.selectedIndex].value,Xc(a))}
function Wc(a,b){var c=a.la[ad];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.ia=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function Xc(a,b){var c=1,d;!b&&a.ia&&(d=a.la[Dd])&&(d.style.backgroundColor=a.ia);if(a.ga)for(var e in a.ga){var f=a.ga[e];a.ha&&(a.ha[c-1]=f);var g=jd+c++;d=a.la[g];if(!d)break;d.style.display="inline-block";g==b&&Wc(a,f);if(b&&b!=g||f!=a.ia)f=ec(f,1,.5);d.style.backgroundColor=f}for(;;){b=jd+c++;b=a.la[b];if(!b)break;b.style.display="none"}}
var $c="colorPalette",ad="colorSelection",jd="colorSwatch",Dd="colorSwatchSelected",pd="countInit",qd="countOn",rd="countOff",Zc="backgroundImage",cd="patterns",gd="symbolInput",id="symbolPreview",ed="save",hd="saveToURL",sd=[null,qd,rd,"countCycle"],ud=["s\t\tset string"],wd="load",xd="scroll",yd="pause",vd="halt",zd="center",Ad="off",Bd="on",Cd={b:Ad,c:zd,h:vd,o:Bd,p:yd,s:xd},kd="A4",ld="L1",nd="B3/S23",Sc={Helvetica:{width:16,height:16,0:"$2b2o$bo2bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$bo2bo$2b2o",
1:"$3bo$2b2o$4o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo",2:"$2b3o$bo3bo$o5bo$o5bo$6bo$5bo$3b2o$2bo$bo$o$7o",3:"$b4o$o4bo$o4bo$5bo$4bo$2b2o$4bo$5bo$o4bo$o4bo$b4o",4:"$5bo$4b2o$3bobo$2bo2bo$bo3bo$o4bo$o4bo$8o$5bo$5bo$5bo",5:"$6o$o$o$o$4o$4bo$5bo$5bo$5bo$o3bo$b3o",6:"$2b4o$bo4bo$o$o$o$ob4o$2o4bo$o5bo$o5bo$bo4bo$2b4o",7:"$8o$7bo$6bo$5bo$4bo$4bo$3bo$3bo$2bo$2bo$2bo",8:"$b4o$o4bo$o4bo$o4bo$bo2bo$2b2o$bo2bo$o4bo$o4bo$o4bo$b4o",9:"$b4o$o4bo$o5bo$o5bo$o4b2o$b4obo$6bo$6bo$6bo$o4bo$b4o",A:"$3b2o$2bo2bo$bo4bo$bo4bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo",
B:"$6o$o5bo$o5bo$o5bo$o4bo$7o$o6bo$o6bo$o6bo$o6bo$7o",C:"$2b4o$bo4bo$o6bo$o$o$o$o$o$o6bo$bo4bo$2b4o",D:"$6o$o5bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o5bo$6o",E:"$7o$o$o$o$o$6o$o$o$o$o$7o",F:"$7o$o$o$o$o$6o$o$o$o$o$o",G:"$2b4o$bo4bo$o$o$o$o3b4o$o6bo$o6bo$o6bo$bo4bo$2b4o",H:"$o6bo$o6bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo$o6bo$o6bo",I:"$o$o$o$o$o$o$o$o$o$o$o",J:"$5bo$5bo$5bo$5bo$5bo$5bo$5bo$o4bo$o4bo$o4bo$b4o",K:"$o6bo$o5bo$o4bo$o3bo$o2bo$ob2o$2o2bo$o4bo$o5bo$o6bo$o7bo",L:"$o$o$o$o$o$o$o$o$o$o$7o",M:"$o8bo$2o6b2o$obo4bobo$obo4bobo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o8bo$o8bo$o8bo$o8bo",
N:"$2o5bo$obo4bo$obo4bo$o2bo3bo$o2bo3bo$o3bo2bo$o3bo2bo$o4bobo$o4bobo$o4bobo$o5b2o",O:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo6bo$2bo4bo$3b4o",P:"$6o$o5bo$o6bo$o6bo$o6bo$o5bo$6o$o$o$o$o",Q:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo4bobo$2bo4bo$3b4obo$9bo",R:"$6o$o5bo$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo$o6bo",S:"$2b4o$bo4bo$o6bo$o$bo$2b4o$6bo$7bo$o6bo$bo4bo$2b4o",T:"$9o$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo",U:"$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",V:"$o8bo$o8bo$bo6bo$bo6bo$bo6bo$2bo4bo$2bo4bo$2bo4bo$3bo2bo$3bo2bo$4b2o",
W:"$o4b2o4bo$o4b2o4bo$o4b2o4bo$o3bo2bo3bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$2b2o4b2o$2b2o4b2o$2b2o4b2o",X:"$o8bo$bo6bo$2bo4bo$3bo2bo$4b2o$4b2o$4b2o$3bo2bo$2bo4bo$bo6bo$o8bo",Y:"$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$9o$8bo$7bo$6bo$5bo$4bo$3bo$2bo$bo$o$9o",a:"$$$$b4o$o4bo$5bo$b5o$o4bo$o4bo$o3b2o$b3obo",b:"$o$o$o$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o",c:"$$$$2b4o$bo4bo$o$o$o$o$bo4bo$2b4o",d:"$6bo$6bo$6bo$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo",e:"$$$$2b3o$bo3bo$o5bo$7o$o$o$bo4bo$2b4o",
f:"$2b2o$bo2bo$bo$bo$4o$bo$bo$bo$bo$bo$bo",g:"$$$$2b2obo$bo2b2o$o4bo$o4bo$o4bo$bo2b2o$2b2obo$5bo$5bo$o4bo$b4o",h:"$o$o$o$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",i:"$$o$$o$o$o$o$o$o$o$o",j:"$$3bo$$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$o2bo$b2o",k:"$o$o$o$o4bo$o3bo$o2bo$obo$2obo$o3bo$o4bo$o5bo",l:"$o$o$o$o$o$o$o$o$o$o$o",m:"$$$$ob2o3b2o$2o2bobo2bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo",n:"$$$$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",o:"$$$$2b4o$bo4bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",p:"$$$$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o$o$o$o",
q:"$$$$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo$6bo$6bo$6bo",r:"$$$$ob2o$2o2bo$o$o$o$o$o$o",s:"$$$$b4o$o4bo$o$b4o$5bo$5bo$o4bo$b4o",t:"$$bo$bo$4o$bo$bo$bo$bo$bo$bo2bo$2b2o",u:"$$$$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o3b2o$b3obo",v:"$$$$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo",w:"$$$$o3b2o3bo$o3b2o3bo$o3b2o3bo$o3b2o3bo$bobo2bobo$bobo2bobo$bobo2bobo$2bo4bo",x:"$$$$$o5bo$bo3bo$2bobo$3bo$2bobo$bo3bo$o5bo",y:"$$$$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$2bo$2o",z:"$$$$6o$5bo$4bo$3bo$2bo$bo$o$6o",
"!":"$o$o$o$o$o$o$o$o$$o$o",'"':"$obo$obo$obo$obo","#":"$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo",$:"3bo$2b4o$bobo2bo$o2bo$o2bo$bobo$2b3o$3bobo$3bo2bo$3bo2bo$o2bobo$b4o$3bo","%":"$b2o7bo$o2bo5bo$o2bo4bo$o2bo3bo$o2bo2bo$b2o2bo2b2o$4bo2bo2bo$3bo3bo2bo$2bo4bo2bo$bo5bo2bo$o7b2o","&":"$b3o$o3bo$o3bo$o3bo$bobo$2bo$bobo$o3bobo$o4bo$o3bobo$b3o3bo","'":"$o$o$o$o","(":"$3bo$2bo$bo$bo$o$o$o$o$o$o$bo$bo$2bo$3bo",")":"$o$bo$2bo$2bo$3bo$3bo$3bo$3bo$3bo$3bo$2bo$2bo$bo$o","*":"2bo$obobo$b3o$b3o$o3bo",
"+":"$$$$3bo$3bo$3bo$7o$3bo$3bo$3bo",",":"$$$$$$$$$$2o$2o$bo$o",".":"$$$$$$$$$$2o$2o","/":"$3bo$3bo$2bo$2bo$2bo$bo$bo$bo$o$o$o",":":"$$$$2o$2o$$$$$2o$2o",";":"$$$$2o$2o$$$$$2o$2o$bo$o","<":"$$$$6b2o$4b2o$2b2o$2o$2o$2b2o$4b2o$6b2o",">":"$$$$2o$2b2o$4b2o$6b2o$6b2o$4b2o$2b2o$2o","=":"$$$$$$8o$$$8o","?":"$b4o$o4bo$o4bo$5bo$4bo$3bo$2bo$2bo$$2bo$2bo","@":"$3b4o$2bo4bo$bo6bo$o3b2o3bo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o5b3o$bo$2bo5bo$3b5o","[":"$3o$o$o$o$o$o$o$o$o$o$o$o$o$3o","]":"$3o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$3o",
"\\":"$o$o$bo$bo$bo$2bo$2bo$2bo$3bo$3bo$3bo","^":"$2b2o$2b2o$bo2bo$bo2bo$o4bo$o4bo",_:"$$$$$$$$$$$$$8o","`":"o$bo$2bo","{":"$2b2o$bo$bo$bo$bo$bo$bo$o$bo$bo$bo$bo$bo$2b2o","}":"$2o$2bo$2bo$2bo$2bo$2bo$2bo$3bo$2bo$2bo$2bo$2bo$2bo$2o","|":"o$o$o$o$o$o$o$o$o$o$o$o$o$o$o","~":"$$$$$$b3o3bo$o3b3o"},ATT4425:{width:9,height:13,A:"$3bo$3bo$2bobo$2bobo$bo3bo$bo3bo$7o$o5bo$o5bo",B:"$6o$bo4bo$bo4bo$bo3bo$b4o$bo3bo$bo4bo$bo4bo$6o",C:"$2b5o$bo$o$o$o$o$o$bo$2b5o",D:"$5o$bo3bo$bo4bo$bo4bo$bo4bo$bo4bo$bo4bo$bo3bo$5o",
E:"$6o$o$o$o$5o$o$o$o$6o",F:"$6o$o$o$o$5o$o$o$o$o",G:"$2b3o$bo3bo$o$o$o$o3b3o$o4bo$bo3bo$2b3o",H:"$o5bo$o5bo$o5bo$o5bo$7o$o5bo$o5bo$o5bo$o5bo",I:"$3o$bo$bo$bo$bo$bo$bo$bo$3o",J:"$4bo$4bo$4bo$4bo$4bo$4bo$o3bo$o3bo$b3o",K:"$o5bo$o4bo$o3bo$o2bo$3o$o2bo$o3bo$o4bo$o5bo",L:"$o$o$o$o$o$o$o$o$7o",M:"$o5bo$2o3b2o$obobobo$o2bo2bo$o5bo$o5bo$o5bo$o5bo$o5bo",N:"$o5bo$2o4bo$obo3bo$obo3bo$o2bo2bo$o3bobo$o3bobo$o4b2o$o5bo",O:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",P:"$6o$o5bo$o5bo$o5bo$6o$o$o$o$o",Q:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o$3bo2bo$4b3o",
R:"$6o$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo",S:"$2b3o$bo3bo$bo$2bo$3bo$4bo$o4bo$bo3bo$2b3o",T:"$5o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo",U:"$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",V:"$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo",W:"$o5bo$o5bo$o2bo2bo$o2bo2bo$obobobo$obobobo$2o3b2o$2o3b2o$o5bo",X:"$o5bo$bo3bo$bo3bo$2bobo$3bo$2bobo$bo3bo$bo3bo$o5bo",Y:"$o5bo$o5bo$bo3bo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$7o$6bo$5bo$4bo$3bo$2bo$bo$o$7o"}};E.LEDCtrl=Rc;
function Ed(a,b,c){O.call(this,a,a);var d=this;this.ea=!1;this.ia=c;this.da="";this.ha=this.ga=!1;this.ba=void 0;qb(this,!1);this.Da=0;b=b.trim();b[0]=="{"?Fd(this,b):(this.da=b,Va(this.da,function(e,f,g,h){g==4&&(!h&&f?(Fd(d,f),Gd(d)):d.ca("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.ha=!0;Gd(d)});window.addEventListener(Za("iOS")?"pagehide":Za("Opera")?"unload":"beforeunload",function(){if(d.fa){var e=d.Ga();if(Xa(d)){e=JSON.stringify(e);try{window.localStorage.setItem(d.ma,
e)}catch(f){d.ca("%s\n",f.message)}}}d.Fa(!1)});window.addEventListener("pageshow",function(){d.ea||d.Fa(!0)})}x(Ed,O);t=Ed.prototype;t.Ma=function(a,b){var c=this;switch(a){case Hd:b.onclick=function(){c.Fa()};break;case Id:b.onclick=function(){c.Ia()}}O.prototype.Ma.call(this,a,b)};
function Gd(a){var b=!0;if(a.ga&&a.ha){var c=a.config.state;if(c&&typeof a.ba!="string")a.ba===void 0&&(a.ba=null,Va(c,function(f,g,h,m){if(h==4){a.ba="";if(!m&&g)try{JSON.parse(g),a.ba=g}catch(p){a.ca("error parsing state file %s: %s\n",f,p.message)}else a.ca("error (%d) loading state file: %s\n",m,f);Gd(a)}}));else{for(var d in a.aa){c=void 0;var e=a.aa[d];try{c=e["class"],E[c]?c=="Machine"?(a.ca("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2026 Jeff Parsons <Jeff@pcjs.org>"),a.da&&a.ca("Configuration: %s\n",
a.da)):new E[c](a.ma,d,e):a.ca('unrecognized %s device "%s"\n',c,d)}catch(f){e.optional||(a.ca('error initializing %s device "%s": %s\n',c,d,f.message),b=!1),sb(a,d)}}d=a.fa?$a(a):null;!d&&a.ba&&(d=JSON.parse(a.ba),a.ca("Initial state: %s\n",a.config.state));d&&a.za(d);qb(a,!0);rb(a,a.Fa.bind(a,b))||a.ca("machine %s not ready to power, waiting for device(s)\n",a.ma)}}}
function Fd(a,b){try{a.aa=JSON.parse(b);var c=a.aa[a.ma];if(!c){var d=Ga(a.da);c=a.aa[d];if(!c){var e=Object.keys(a.aa).filter(function(m){return a.aa[m]["class"]=="Machine"});e.length==1&&(d=e[0],c=a.aa[d])}if(!c)throw Error("configuration missing machine ID");e={};for(var f in a.aa)e[f==d?a.ma:f]=a.aa[f];a.aa=e}nb(a,c,["autoSave","autoStart"]);a.fa=a.config.autoSave!==!1;a.ka=a.config.autoStart!==!1;if(a.ia){var g=eval("("+a.ia+")"),h;for(h in g)a.config[h]=g[h]}a.ga=!0}catch(m){c=m.message,(d=
c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.ca("machine '%s' initialization error: %s\n",a.ma,c)}}t.za=function(a){var b=!0;ob(this,function(c){return c.xb&&!c.xb(a)?(c.ca('unable to restore state for device "%s"\n',c.sa),b=!1):!0});return b};t.Ga=function(){var a=[];ob(this,function(b){b.yb&&b.yb(a);return!0});return a};
t.Fa=function(a){a=a===void 0?!this.ea:a;if(pb(this)){var b=this;a&&this.ca("power on\n");ob(this,function(c){c.Fa&&c!=b&&(c.config["class"]!="CPU"||b.ka&&pb(b)?c.Fa(a):c.time.update(!0));return!0});(this.ea=a)||this.ca("power off\n")}};t.Ia=function(){if(pb(this)){var a=this;ob(this,function(b){b.Ia&&b!=a&&b.Ia();return!0});this.ca("reset\n");this.ba&&this.za(JSON.parse(this.ba))&&this.ca("Initial state restored: %s\n",this.config.state)}};var Hd="power",Id="reset";
window.LEDs=function(a,b,c){var d=new Ed(a,b,c);window.command=function(e){return ab(d,e)};return d};E.Machine=Ed;})()

//# sourceMappingURL=led.js.map
