(function(){/*
 https://www.pcjs.org/modules/dl11.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/pc11.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/defs.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/numio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/stdio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/webio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/device.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/input.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/led.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/time.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/bus.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/memory.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/ports.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/ram.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/rom.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/cpu.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/debugger.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/pdp11ops.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/pdp11.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/pdp11dbg.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/iopage.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/machine.js (C) 2012-2020 Jeff Parsons
*/
var l;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={Gb:!0},ha={};try{ha.__proto__=fa;ea=ha.Gb;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=da;
function n(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ka(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var la=ka(this);function ma(a,b){if(b){var c=la;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}
ma("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});ma("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});function na(){na=function(){};la.Symbol||(la.Symbol=oa)}function pa(a,b){this.o=a;ja(this,"description",{configurable:!0,writable:!0,value:b})}pa.prototype.toString=function(){return this.o};
var oa=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new pa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function qa(){na();var a=la.Symbol.iterator;a||(a=la.Symbol.iterator=la.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ja(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ra(aa(this))}});qa=function(){}}
function ra(a){qa();a={next:a};a[la.Symbol.iterator]=function(){return this};return a}function sa(a,b){qa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}ma("Array.prototype.keys",function(a){return a?a:function(){return sa(this,function(b){return b})}});
ma("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});ma("Number.parseInt",function(a){return a||parseInt});ma("Array.prototype.values",function(a){return a?a:function(){return sa(this,function(b,c){return c})}});function ta(){}var ua,va=new ArrayBuffer(2);(new DataView(va)).setUint16(0,256,!0);ua=256===(new Uint16Array(va))[0];
var w={Xb:0xffffffffffff,NONE:0,ld:0,Ra:0x800000000000},wa={Qd:{Ta:4,pa:16},jc:{Ta:5,pa:32},od:{Ta:6,pa:64},ec:{Ta:8,pa:256},pd:{Ta:20,pa:1048576},Hg:{Ta:22,pa:4194304}},y={};y.Defs=ta;function xa(){}n(xa,ta);
function ya(a,b){if(a){b||(b=10);var c,d=0<a.indexOf(",");d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);"#"==c?(b=8,c=""):"$"==c&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),"0b"==c&&d||"^B"==c?(b=2,c=""):"0o"==c||"^O"==c?(b=8,c=""):"^D"==c?(b=10,c=""):"0x"==c&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);"Y"==c||"y"==c?(b=2,c=""):"."==c?(b=10,c=""):"H"==c||"h"==c?(b=16,c=""):"K"==c?c="000":"M"==c?c="000000":"G"==c&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var f;e=0;10>=b&&(c=a.match(/(-?[0-9]+)B([0-9]*)$/))&&
(a=c[1],e=35-((c[2]||35)&255));if((b&&10!=b?16==b?null!==a.match(/^-?[0-9a-f]+$/i):8==b?null!==a.match(/^-?[0-7]+$/):2==b&&null!==a.match(/^-?[01]+$/):null!==a.match(/^[+-]?[0-9]+$/))&&!isNaN(f=parseInt(a,b))){e&&(0>f&&(f+=Math.pow(2,36)),f=0<e?f*Math.pow(2,e):Math.trunc(f/Math.pow(2,-e)));var g=f}}return g}
function z(a,b,c,d,e){d=void 0===d?0:d;var f=void 0===f?0:f;var g="",k="",h=-1;c||(c=a.aa||10);d&&(h=Math.ceil(d/Math.log2(c)));if(void 0==e)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:k=".";default:e=""}isNaN(b)||"number"!=typeof b?(b=void 0,e=k=""):(0>b&&-1<b&&(b=-1),d&&(0>b&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(h=Math.ceil(Math.log(b)/Math.log(c)))));for(a=f||-1;h--;){a||(g=","+g,a=f);if(void 0==b){if(g="?"+g,0>h)break}else if(d=b%c,b=Math.trunc(b/c),d+=0<=d&&9>=d?48:55,g=String.fromCharCode(d)+
g,!b&&0>h)break;a--}return e+g+k}function za(a,b){var c=a/E|0,d=b/E|0;return(a&b)==(b|0)&&(c&d)==d}function Aa(a){for(var b=0,c=0,d=[];b<a.length;){for(var e=a[b],f=b+1;f<a.length&&a[f]===e;)f++;d[c++]=f-b;d[c++]=e;b=f}return d.length>=a.length?a:d}var E=Math.pow(2,32);y.NumIO=xa;function Ba(){this.Qa={};for(var a=0;22>a;a++)this.Qa["ACDFHIMNSTWYbdfjcsoXx%"[a]]=null}n(Ba,xa);function Ca(a,b,c){a.Qa[b]||(a.Qa[b]=c)}l=Ba.prototype;l.flush=function(){var a=Da;Da="";this.Ha(a)};
function Fa(a,b){var c=a,d=a.lastIndexOf("/");0<=d&&(c=a.substr(d+1));d=c.indexOf("&");0<d&&(c=c.substr(0,d));b&&(d=c.lastIndexOf("."),0<d&&(c=c.substring(0,d)));return c}l.Be=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,ba(b)))};
l.Ha=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),Ga||(Ga=b),a=((b-Ga)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(Da+a.substr(0,c)),Da="",a=a.substr(c+1)),Ga=null);Da+=a;return a.length};function F(a,b,c){a.Ha(b+"\n",c)}l.l=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.Ha(this.w.apply(this,[a].concat(ba(c))))};
l.w=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(!c||!c.length)return a;d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var k=e[g+5];if(void 0===this.Qa[k])d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+k;else{if(f<c.length){var h=c[f];"%"!=k&&f++}else h=c[c.length-1];var p=e[g+1],m=0<=p.indexOf("#"),u=0<=p.indexOf("0"),q=e[g+2];"*"==q?(q=h,h=f<c.length?c[f++]:c[c.length-1]):q=+q||0;var r=e[g+3];r=r?+r.substr(1):
-1;var x=null,v=0,A="";var t=0<="ACDFHIMNSTWY".indexOf(k)&&"object"!=typeof h?this.Be(h):h;switch(k){case "C":h=m?"#":"";d+=isNaN(t.getTime())?void 0:this.w(this.w("%%%sW, %%%sF %%%sD, %%%sY",h),t);continue;case "D":h=m?t.getUTCDate():t.getDate();k="d";break;case "A":case "H":case "I":h=m?t.getUTCHours():t.getHours();"A"==k?(h=12>h?"am":"pm",k="s"):("I"==k&&(h=h?12<h?h-12:h:12),k="d");break;case "F":case "M":h=m?t.getUTCMonth():t.getMonth();"F"==k?(h=Ha[h],k="s"):(h++,k="d");break;case "N":h=m?t.getUTCMinutes():
t.getMinutes();k="d";break;case "S":h=m?t.getUTCSeconds():t.getSeconds();k="d";break;case "T":h=m?"#":"";d+=isNaN(t.getTime())?void 0:this.w(this.w("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),t);continue;case "W":h=Ia[m?t.getUTCDay():t.getDay()];k="s";break;case "Y":h=m?t.getUTCFullYear():t.getFullYear(),0<r&&(h%=Math.pow(10,r),r=-1),k="d"}switch(k){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=r&&(u=!0,q<r&&(q=r),r=-1);case "f":h=+h;t=h+"";0<=r&&(t=h.toFixed(r));t.length<
q&&(u?(0>h&&(q--,t=t.substr(1)),t=("0000000000"+t).slice(-q),0>h&&(t="-"+t)):t=("          "+t).slice(-q));d+=t;break;case "j":d+=JSON.stringify(h,null,q||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=r&&(h=h.substr(0,r));h.length<q;)h=0<=p.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":v=8,m&&(A="0");case "X":x=Ja;case "x":t="";v||(v=16);!A&&m&&(A="0x");x||(x=Ka);h=Math.trunc(h);0<=r&&(u=!0,q<r&&(q=r));u&&!q&&
(q=Math.abs(h),q=255>=q?2:65535>=q?4:4294967295>=q?8:9,q+=A.length);q-=A.length;do m=h&v-1,h>>>=16==v?4:3,u||!t||m||h?t=x[m]+t:(A&&(t=A+t,A=""),0<q&&(t=" "+t));while(0<--q||h);d+=A+t;break;case "%":d+="%";break;default:this.Qa[k]?d+=this.Qa[k](k,p,q,r,h):d+="(unimplemented sprintf type: %"+k+")"}}}return d+=e[g]};var Da="",Ga=null,Ka="0123456789abcdef",Ja="0123456789ABCDEF",Ia="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ha="January February March April May June July August September October November December".split(" ");
y.StdIO=Ba;function La(a){Ba.call(this);this.Y={};this.ja=0;this.S=this;a&&(this.S.ja=0,this.S.Ea=[],this.S.Aa=0,this.S.eb={},this.S.Tg=!1)}var Ma;n(La,Ba);l=La.prototype;l.Ia=function(a,b){var c=this,d=this;switch(a){case Na.gd:b.onclick=function(){var e=c.Pa(Na.fb,!0);e&&(e.value="")};break;case Na.fb:Oa(b),b.addEventListener("keydown",function(e){Pa(d,e,!0)}),b.addEventListener("keypress",function(e){Pa(d,e)})}};function Qa(a,b){var c=Ra.gc;a.S.eb[c]||(a.S.eb[c]=[]);a.S.eb[c].push(b)}
function Sa(a,b,c){var d=!1;"boolean"==typeof b&&(d=b,b=c.shift());if(b=a.w.apply(a,[b].concat(ba(c))))F(a,b),d||alert(b)}function Oa(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}l.error=function(a,b){Sa(this,"%s",this.w.apply(this,[a].concat(ba(b))))};l.Pa=function(a){return this.Y[a]};
function Ta(a){var b=window;if(b){do{for(var c=0;c<Ua.length;c++){var d=Ua[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Va(a,b){return a.s.bindings&&a.s.bindings[b]}function Wa(a){if(a=a.Y[Xa])var b=a.textContent;return b}function Ya(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function G(a,b,c,d){a=a.s[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}function Za(a,b,c){if("string"==typeof b)return $a(b,function(d,e,f,g){var k=!1;if(g){k=0>g;var h=d}else{if(4!=f)return;try{var p=JSON.parse(e)}catch(m){h=m.message||"unknown error"}}h&&Sa(a,k,"Unable to load %s media (error %d: %s)");c(p)}),!1;c(b);return!0}
function $a(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function ab(a){if(void 0===bb.tb){var b=!1;if(window)try{window.localStorage.setItem(bb.Xa,bb.Xa),b=window.localStorage.getItem(bb.Xa)==bb.Xa,window.localStorage.removeItem(bb.Xa)}catch(c){F(a,c.message),b=!1}bb.tb=b}return!!bb.tb}function cb(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.ja;return-1==(b|1)||za(a.S.ja,b)?!0:!1}
function db(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function eb(a){var b=null;if(ab(a)){var c;if(window)try{(c=window.localStorage.getItem(a.U))&&(b=JSON.parse(c))}catch(d){F(a,d.message)}}return b}
function Pa(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.S,f=b.target;if(c){a=!1;var g;c=f.value;var k=c.lastIndexOf("\n");d==H.Zb&&f.selectionStart<=k+1&&(a=!0);d==H.ce?(a=!0,0<e.Aa&&(g=e.Ea[--e.Aa])):d==H.nd&&(a=!0,e.Aa<e.Ea.length&&(g=e.Ea[++e.Aa]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,k+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.Aa&&c+1==g.length&&
(f.value+=e.Ea[--e.Aa],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=fb(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&F(a,b.replace(/\n$/,""),!1))}}function gb(a){return"true"==a||"on"==a?!0:"false"==a||"off"==a?!1:void 0}
function hb(a,b){if(void 0!=b){var c=a.S;try{if(b=b.trim())c.Aa<c.Ea.length&&b==c.Ea[c.Aa]?c.Aa++:(c.Ea.push(b),c.Aa=c.Ea.length);var d=b.split(" "),e=d[0],f=a.S.eb[Ra.gc];switch(e[0]){case "m":if("?"==e[1]){var g="";ib.forEach(function(u){g+=u+"\n"});g&&(g="message commands:\n"+g);break}g="";var k=void 0;e=d[d.length-1].toLowerCase();var h=gb(e);void 0!=h&&d.pop();1>=d.length&&(void 0!=h&&(k=h,h=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(I));for(f=1;f<d.length;f++){e=d[f];var p=I[e];if(!p){g+=
"unrecognized message: "+e+"\n";break}void 0!=h&&jb(a,p,h);if(void 0==k||k==cb(a,p))g+=a.w("%8s: %b\n",e,cb(a,p))}cb(a,w.Ra)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",kb.forEach(function(u){g+=u+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var m=f[a](d);if(void 0!=m){g=g?g+m:m;break}}}}catch(u){g="error: "+u.message+"\n"}}return g}
function fb(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=hb(a,b[d])}return c}l.Ha=function(a,b){void 0==b&&(b=cb(this,w.Ra));if(!b){var c=this.Pa(Na.fb,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,db("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return Ba.prototype.Ha.call(this,a,b)};
l.l=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return cb(this,d)?Ba.prototype.l.call.apply(Ba.prototype.l,[this,a].concat(ba(c))):0};function lb(a,b){if(ab(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.U,b)}catch(c){F(a,c.message)}}}function mb(a,b,c){(a=a.Y[b])&&a.textContent!=c&&(a.textContent=c)}
function jb(a,b,c){var d=!1;c?(c=a.S.ja,a.S.ja=(c|b)+(c/E|0|b/E|0)*E):(d=za(a.S.ja,w.Ra)&&za(b,w.Ra),c=a.S.ja,a.S.ja=(c&~b)+((c/E|0)&~(b/E|0))*E);d&&a.flush()}
var Na={gd:"clear",fb:"print"},kb=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],ib=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],I={all:w.Xb,buffer:w.Ra},Ra={gc:"command"},nb={ic:13,sb:65,Yb:66,dc:67,kc:68,E:69,mc:70,oc:71,pc:72,qc:73,rc:74,sc:75,uc:76,xc:77,yc:78,zc:79,Ac:80,Q:81,Bc:82,Dc:83,Ec:84,
Gc:85,Hc:86,Jc:87,Kc:88,Mc:89,Fb:90,Gb:97,Kg:98,Lg:99,d:100,e:101,Pg:102,Qg:103,Sg:104,Ug:105,Vg:106,k:107,Wg:108,Xg:109,n:110,Yg:111,p:112,q:113,r:114,Zg:115,t:116,ah:117,bh:118,dh:119,x:120,y:121,z:122},H={Zb:8,Yd:9,Ad:10,ic:13,Vd:16,jd:17,cd:18,yg:19,ub:20,Af:27,Xd:32,Bg:33,Ag:34,zf:35,Vf:36,wc:37,ce:38,zb:39,Sf:39,nd:40,Pf:44,Cg:44,Wf:45,yf:46,Rf:46,Uf:47,ZERO:48,ONE:49,be:50,Zd:51,xd:52,wd:53,Wd:54,Ud:55,qd:56,Hd:57,vd:59,ud:61,sb:65,Yb:66,dc:67,kc:68,E:69,mc:70,oc:71,pc:72,qc:73,rc:74,sc:75,
uc:76,xc:77,yc:78,zc:79,Ac:80,Q:81,Bc:82,Dc:83,Ec:84,Gc:85,Hc:86,Jc:87,Kc:88,Mc:89,Fb:90,fc:91,Qf:91,Of:92,Fg:93,Tf:93,$f:96,qg:96,Nf:96,ag:97,og:97,bg:98,ng:98,cg:99,tg:99,dg:100,rg:100,eg:101,kg:101,fg:102,vg:102,gg:103,pg:103,hg:104,xg:104,ig:105,ug:105,sg:106,jg:107,wg:109,lg:110,mg:111,Bf:112,Ff:113,Gf:114,Hf:115,If:116,Jf:117,Kf:118,Lf:119,Mf:120,Cf:121,Df:122,Ef:123,Id:144,Sd:145,td:173,Td:186,rd:187,wf:188,kd:189,zg:190,Ig:191,uf:192,Xf:219,vf:220,Eg:221,Dg:222,sd:224,Yf:901,Ic:1E3},ob={},
pb=(ob[H.vd]=H.Td,ob[H.ud]=H.rd,ob[H.td]=H.kd,ob[H.sd]=H.fc,ob),qb={wc:1,zb:2,Zf:3},J={},rb=(J[H.Zb]="\b",J[H.Yd]="\t",J[H.Ad]="\n",J[H.ic]="\r",J[H.Xd]=" ",J[H.ZERO]="0",J[H.ONE]="1",J[H.be]="2",J[H.Zd]="3",J[H.xd]="4",J[H.wd]="5",J[H.Wd]="6",J[H.Ud]="7",J[H.qd]="8",J[H.Hd]="9",J[H.sb]="A",J[H.Yb]="B",J[H.dc]="C",J[H.kc]="D",J[H.E]="E",J[H.mc]="F",J[H.oc]="G",J[H.pc]="H",J[H.qc]="I",J[H.rc]="J",J[H.sc]="K",J[H.uc]="L",J[H.xc]="M",J[H.yc]="N",J[H.zc]="O",J[H.Ac]="P",J[H.Q]="Q",J[H.Bc]="R",J[H.Dc]=
"S",J[H.Ec]="T",J[H.Gc]="U",J[H.Hc]="V",J[H.Jc]="W",J[H.Kc]="X",J[H.Mc]="Y",J[H.Fb]="Z",J[H.wc]="Left",J[H.zb]="Right",J),Ua=["","moz","ms","webkit"],sb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},bb={tb:void 0,Xa:"PCjs.localStorage"};y.WebIO=La;
function K(a,b,c,d){La.call(this,a==b);this.U=a;this.M=b;tb[this.U]||(tb[this.U]={});tb[this.U][this.M]&&this.l("warning: machine configuration contains multiple '%s' devices\n",this.M);tb[this.U][this.M]=this;this.id=this.U+"."+this.M;ub.push(this);this.S=vb(this,this.U);this.ready=!0;wb(this,c,d);this.Fa={};this.Lc=[]}n(K,La);l=K.prototype;l.Hb=function(){};l.Ib=function(){};
function wb(a,b,c){b=void 0===b?{}:b;c=void 0===c?[]:c;c=b.overrides||c;if(c.length){var d,e=Ma;if(!e){e={};if(window){d||(d=window.location.search.substr(1));for(var f,g=/\+/g,k=/([^&=]+)=?([^&]*)/g;f=k.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ma=e}d=e;for(var h in d)0<=c.indexOf(h)&&(e=d[h],f=ya(e,10),void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"')),b[h]=f,F(a,"overriding "+a.M+" property '"+h+"' with "+e))}a.s=b;c=b.bindings;
c=void 0===c?{}:c;a.s.Y||(a.s.Y=c);(h=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.M);for(var p in c){e=c[p];if(h)p=e;else if(e.match(/^[0-9]+$/)){d=+e;a.Y[p]=[];do{e=p+d++;e=document.getElementById(e);if(!e)break;a.Y[p].push(e)}while(1);continue}if(d=document.getElementById(e))a.Y[p]=d,a.Ia(p,d)}b=void 0===b?{}:b;a.version=3;if(a.version){p="";var m;a.U!=a.M&&(m=vb(a,a.U).version)&&m!=a.version&&(p="Machine");p||(m=b.version)&&m>a.version&&(p="Config");
p&&(m=a.w("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.Mg,a.version,p,m),a.error("%s\n\nClearing your browser's cache may resolve the issue.",m))}}function L(a,b,c,d){a.Fa[b]={get:c.bind(a),set:d?d.bind(a):null}}function xb(a,b,c){a.Fa[b]&&(a.Fa[c]=a.Fa[b])}function yb(a,b){var c;try{var d=tb[a.U];if(d)for(c in d){var e=d[c];if(e.M!=e.U&&!b(e))return!1}return!0}catch(f){a.l("error while enumerating device '%s': %s\n",c,f.message)}return!1}
l.Pa=function(a,b){b=void 0===b?!1:b;if(a){var c=La.prototype.Pa.call(this,a,b);if(void 0===c&&b){b=tb[this.U];for(var d in b)if(c=b[d].Y[a])break;c||(c=null);this.Y[a]=c}}return c};function vb(a,b,c){var d=b,e=a.U,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=tb[e])&&f[b]||null;if(!b){for(f=0;f<ub.length;f++)if(ub[f].id===d){b=ub[f];break}if(!b&&(void 0===c||c))throw Error(a.w('no "%s" device',d));}return b}
function N(a,b,c){var d=null,e=tb[a.U];if(e)for(var f in e)if(e[f].s["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.w("no %s device",b));return d}function zb(a,b){var c=vb(a,a.U);return c&&c.s&&c.s[b]||a.s[b]}function Ab(a,b){return(a=a.Fa[b])&&a.get()}function Bb(a){return a==a.S&&a.ready?yb(a,function(b){return Bb(b)}):a.ready}function Cb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(Bb(a)){for(;b=a.Lc.pop();)b();a!=a.S&&Cb(a.S)}}
function Db(a,b){if(Bb(a))return b(),!0;a.Lc.push(b);return!1}l.Yc=function(){};l.l=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&cb(this,a)&&(void 0===this.W&&(this.W=N(this,"Debugger",!1)),this.W&&this.W.Yc(a),this.S.ja&w.Wb&&(void 0===this.o&&(this.o=N(this,"CPU")),this.o))?(a=c.shift(),La.prototype.l.call(this,"%#06x: %s.%s\n",this.o.Ob,this.M,this.w.apply(this,[a].concat(ba(c))).trim())):La.prototype.l.call.apply(La.prototype.l,[this,a].concat(ba(c)))};
function Eb(a,b){(a=tb[a.U])&&delete a[b]}function Fb(a,b,c){(a=a.Fa[b])&&a.set&&a.set(c)}window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]));var tb=window?window.PCjs.Machines:{},ub=window?window.PCjs.Components:[];w.Wb=1;w.dd=2;w.nc=4;w.Bd=8;w.yb=16;w.fd=32;w.zd=64;w.Wa=128;w.vb=256;w.hd=512;w.Cd=1024;w.INT=2048;w.Fc=4096;w.ee=8192;w.Dd=16384;w.Rd=32768;w.gb=65536;w.$d=131072;w.lc=262144;w.Ca=524288;w.tc=1048576;
w.Ed=2097152;w.ae=4194304;w.hb=8388608;w.yd=16777216;w.xf=4294967296;I.addr=w.Wb;I.bus=w.dd;I.fault=w.nc;I.memory=w.Bd;I.ports=w.yb;I.chips=w.fd;I.kbd=w.zd;I.serial=w.Wa;I.misc=w.vb;I.cpu=w.hd;I.mmu=w.Cd;I["int"]=w.INT;I.trap=w.Fc;I.video=w.ee;I.monitor=w.Dd;I.screen=w.Rd;I.time=w.gb;I.timer=w.$d;I.event=w.lc;I.input=w.Ca;I.key=w.tc;I.mouse=w.Ed;I.touch=w.ae;I.warn=w.hb;I.halt=w.yd;y.Device=K;
function Gb(a,b,c){K.call(this,a,b,c);this.ja=w.Ca;this.L=this.v=null;this.time=N(this,"Time");this.S=N(this,"Machine");this.V=G(this,"drag",!1);this.K=G(this,"scroll",!1);this.T=G(this,"hexagonal",!1);this.g=G(this,"releaseDelay",0,void 0);this.h=!1;a=this.s.map;this.b=this.f=null;if(a)if(a.length)this.b=a;else{this.f={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.f[f]={keys:g,
Rg:e,state:0}}}this.u=[];this.H=[];this.c=this.J=null;(a=this.Y[Hb])&&Ib(this,a,this.Pa(c.focusBinding,!0),this.s.location);this.la()}n(Gb,K);function Jb(a,b){a.v=b}function Kb(a,b,c){for(var d=0;d<a.u.length;d++){var e=a.u[d];e.id===b&&e.jb(b,c)}}
function Ib(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.b||a.f){var e={};e.sf=d[0]||0;e.tf=d[1]||0;e.Za=d[2]||b.clientWidth;e.ib=d[3]||b.clientHeight;e.kb=d[4]||1;e.pb=d[5]||1;e.pe=d[6]||b.naturalWidth||e.Za;e.re=d[7]||b.naturalHeight||e.ib;e.ad=d[8]||0;e.bd=d[9]||0;e.oe=d[10]||0;e.qe=d[11]||0;a.b?(e.mb=a.b.length,e.$a=a.b[0].length):(e.$a=e.kb,e.mb=e.pb,e.kb=e.pb=0);e.Uc=e.Za/(e.$a+e.$a*e.kb)|0;e.Vc=e.ib/(e.mb+e.mb*e.pb)|0;e.ne=e.Uc*e.kb|0;e.Wc=e.Vc*e.pb|0;e.cb=e.rb=-1;Lb(a,b,e);Mb(a,b,e);a.time&&
a.g&&(a.R=Nb(a.time,"timerInputRelease",function(){0>e.cb&&0>e.rb&&Ob(a,-1,-1)}))}if(a.b||a.f)a.time&&a.g&&(a.X=Nb(a.time,"timerKeyRelease",function(){Pb(a)})),a.i=0,a.m="",a.j=[],d=b,c&&(d=c,a.c||"BUTTON"!=c.nodeName||(d=document,a.c=c,Qb(a,b),a.J=b)),Qb(a,d),a.c||(a.c=d)}function Rb(a){a.g?Sb(a.time,a.X,a.g):Pb(a)}
function Tb(a,b,c,d,e){if(a=a.Y[b]){for(b=0;b<a.options.length&&a.options[b].text!=c;b++);void 0==a.options.length&&(b=document.createElement("option"),b.text=c,b.value=d,(void 0===e?0:e)&&a.childNodes[0]?a.insertBefore(b,a.childNodes[0]):a.appendChild(b))}}
function Qb(a,b){function c(e,f,g){var k=document.activeElement;a.l(w.tc+w.lc,"%s.onKey%s(%d): %5.2f (%s)\n",k.id||k.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.c&&e!=a.c&&e!=a.J?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Ub(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=Ub(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Ub(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function Lb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.h){var e=a.c;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||Vb(a,b,Wb,d,c)}});b.addEventListener("mousemove",function(d){a.h||Vb(a,b,Xb,d,c)});b.addEventListener("mouseup",function(d){a.h||d.button||Vb(a,b,Yb,d,c)});b.addEventListener("mouseout",function(d){a.h||(0>c.cb?Vb(a,b,Xb,d,c):Vb(a,b,Yb,d,c))})}
function Mb(a,b,c){b.addEventListener("touchstart",function(d){a.K&&(a.h=!0);Vb(a,b,Wb,d,c)});b.addEventListener("touchmove",function(d){Vb(a,b,Xb,d,c)});b.addEventListener("touchend",function(d){Vb(a,b,Yb,d,c)})}
function Ub(a,b,c,d){if(void 0!=c){var e=pb[b]||b;var f=rb[b];var g=Zb[e];d=d&&d.location==qb.zb;g&$b&&d&&(g>>=1);g&&(g&ac&&(c=!(a.a&g)),a.a=c?a.a|g:a.a&~g,Kb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=nb.sb&&b<=nb.Fb?a.a&(bc|cc)||(a.a|=cc,Kb(a,H.ub,!0)):b>=nb.Gb&&b<=nb.z&&a.a&cc&&(a.a&=~cc,Kb(a,H.ub,!1));if(a.b){if(void 0!=c)return!1;for(e=0;e<a.b.length;e++)for(g=a.b[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.i?16>a.j.length&&a.j.push(b):(a.i=1,a.m=f,Ob(a,d,e),Kb(a,
f,!0),Rb(a)),!0}if(a.f){if(void 0==c)return!0;b=Object.keys(a.f);for(e=0;e<b.length;e++)if(g=b[e],0<=a.f[g].keys.indexOf(f))return Kb(a,g,c),a.f[g].state=c?1:0,!0}return!1}function Pb(a){1==a.i?(a.i++,Kb(a,a.m,!1),a.m="",Ob(a,-1,-1),Rb(a)):(a.i=0,a.j.length&&Ub(a,a.j.shift()))}Gb.prototype.la=function(){this.a=0;this.I=this.N=-1};
function Vb(a,b,c,d,e){var f=-1,g=-1,k=!1,h=-1,p=-1;if(c<Yb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(h=d.targetTouches[0].clientX,p=d.targetTouches[0].clientY,k=1<d.targetTouches.length):(h=d.clientX,p=d.clientY);var m=d.target.getBoundingClientRect();h-=m.left;p-=m.top;h=e.pe/b.offsetWidth*h|0;p=e.re/b.offsetHeight*p|0;var u=h-e.sf;var q=p-e.tf;var r=m=!1;var x=h>=e.ad&&h<e.ad+e.oe&&p>=e.bd&&p<e.bd+e.qe;if(0<=u&&u<e.Za&&0<=q+e.Wc||x)if(k||a.K||d.preventDefault(),0<=u&&u<e.Za&&
0<=q&&q<e.ib){r=!0;d=e.Za/e.$a|0;var v=e.ib/e.mb|0,A=u/d|0,t=q/v|0;!a.T||t&1||(u-=d>>1,A=u/d|0,A==e.$a-1&&(u=-1));v=t*v+(e.Wc>>1);u-=A*d+(e.ne>>1);q-=v;0<=u&&u<e.Uc&&0<=q&&q<e.Vc&&(f=A,g=t,m=!0)}}u=u||0;q=q||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Wb||c==Yb)for(A=0;A<a.H.length;A++)t=a.H[A],c==Yb?t.jb(t.id,!1):(v=q/(b/t.Og|0)|0,(u/(d/t.Ng|0)|0)==t.eh&&v==t.fh&&t.jb(t.id,!0));if(!k)if(c==Wb)e.cb=h,e.rb=p,r?(Ob(a,f,g),m&&a.g&&Sb(a.time,a.R,a.g,!0)):x&&a.S.ka();else if(c==Xb)0<=e.cb&&0<=e.rb&&a.V?Ob(a,
f,g):a.v&&a.v(f,g);else if(c==Yb){if(c=a.g)c=a.time,f=a.R,c=c.a&&0<f&&f<=c.b.length?0<=c.b[f-1].va:!1;c||Ob(a,-1,-1);e.cb=e.rb=-1}else F(a,"unrecognized action: "+c)}function Ob(a,b,c){if(b!=a.I||c!=a.N)a.I=b,a.N=c,a.L&&a.L(b,c)}var Wb=1,Xb=2,Yb=3,Hb="surface",bc=3,$b=170,cc=512,ac=3584,dc={},Zb=(dc[H.Vd]=2,dc[H.jd]=8,dc[H.cd]=32,dc[H.fc]=128,dc[H.ub]=cc,dc[H.Id]=1024,dc[H.Sd]=2048,dc);y.Input=Gb;
function ec(a,b,c){K.call(this,a,b,c,["color","backgroundColor"]);a=this.Y[fc];if(!a)throw Error("LED "+this.s.Y[fc]+" binding for '"+fc+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.oa=Va(this,fc)+".canvas";b.setAttribute("id",this.oa);this.xa=a;this.type=Ya(G(this,"type",gc,hc),ic,jc);this.f=kc[this.type][0];this.j=kc[this.type][1];this.width=G(this,"width",
this.f,void 0);this.height=G(this,"height",this.j,void 0);this.g=G(this,"cols",1,void 0);this.H=this.g+G(this,"colsExtra",0,void 0);this.V=G(this,"rows",1,void 0);this.K=this.V+G(this,"rowsExtra",0,void 0);this.Z=this.width*this.g;this.N=this.height*this.V;this.i=lc("black",0);this.c=mc(this.s.color)||this.i;this.ga=lc(this.c,1,.25);this.fa=lc(this.c,1,2);this.h=mc(this.s.backgroundColor);this.ia=G(this,"fixed",!1);this.ia||(b.style.width="100%",b.style.height="auto");this.ea=G(this,"hexagonal",!1);
this.na=G(this,"highlight",!0);this.L=G(this,"persistent",this.type<jc);b.setAttribute("width",this.Z.toString());b.setAttribute("height",this.N.toString());b.style.backgroundColor=this.i;a.appendChild(b);this.ca=b.getContext("2d");if(this.m=document.createElement("canvas"))this.m.width=this.X=this.f*this.g,this.m.height=this.v=this.j*this.V,this.b=this.m.getContext("2d");this.qa=(this.K+1)*this.H*4;this.a=Array(this.qa);this.ra=this.g<this.H?4*(this.H-this.g):0;this.J=this.I=!1;this.u=this.T=0;this.R=
-1;var d=this;this.time=N(this,"Time");nc(this.time,function(e){oc(d,!1,e)});pc(d)}n(ec,K);function pc(a){for(var b=a.a,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<jc?qc:" ";e[f+1]=d.c==d.i?null:d.c;e[f+2]=0;e[f+3]=rc}a.J=a.I=!0;oc(a,!0)}function sc(a){a.h?(a.b.fillStyle=a.h,a.b.fillRect(0,0,a.X,a.v)):a.b.clearRect(0,0,a.X,a.v)}
function oc(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.J||b){if(a.type<jc){var d=0;if(!a.L||b)sc(a);else if(a.u){d=a.g-a.u;var e=a.f*d;a.b.drawImage(a.m,a.f*a.u,0,e,a.v,0,0,e,a.v)}for(var f=e=0;f<a.K;f++){for(var g=0;g<a.g;g++){var k=a.a[e],h=a.a[e+1]||a.i,p=a.na&&e==a.R;if(a.a[e+3]&rc||p||b){if(g>=d)a:{var m=a,u=k;k=h;var q=g;h=f;var r=p;q=void 0===q?0:q;h=void 0===h?0:h;r=void 0===r?!1:r;var x=0;if(m.ea&&!(h&1)&&(x=m.f>>1,q==m.g-1))break a;if(k&&k!=m.c){r=r?lc(k,1,2):k;var v=lc(k,1,.25)}else r=
r?m.fa:m.c,v=m.ga;k=!1;u=u?r:v;r==m.i&&(u=m.h,k=!0);r=q*m.f+x;v=h*m.j;m.L&&(q=q*m.f+x,h*=m.j,m.h?(m.b.fillStyle=m.h,m.b.fillRect(q,h,m.f,m.j)):m.b.clearRect(q,h,m.f,m.j));m.b.fillStyle=u;h=tc[m.type];3==h.length?(m.b.beginPath(),m.b.arc(r+h[0],v+h[1],h[2],0,2*Math.PI),k?(m.b.globalCompositeOperation="destination-out",m.b.fill(),m.b.globalCompositeOperation="source-over"):m.b.fill()):m.b.fillRect(r+h[0],v+h[1],h[2],h[3])}a.a[e+3]=p?a.a[e+3]|rc:a.a[e+3]&~rc}e+=4}e+=a.ra}a.u=0}else{b="";for(d=0;d<a.a.length;d+=
4)b+=a.a[d]||" ",a.a[d+3]&uc&&(b+=".");sc(a);for(f=e=d=0;d<b.length;d++){h=b[d];"."==h&&e&&e--;g=a;p=e;m=f;p=void 0===p?0:p;m=void 0===m?0:m;if(h=vc[h])for(k=0;k<h.length;k++)if(q=g,x=wc[h[k]]){u=(void 0===p?0:p)*q.f;r=(void 0===m?0:m)*q.j;q.b.fillStyle=q.c;q.b.beginPath();if(3==x.length)q.b.arc(u+x[0],r+x[1],x[2],0,2*Math.PI);else for(v=0;v<x.length;v+=2)v?q.b.lineTo(u+x[v],r+x[v+1]):q.b.moveTo(u+x[v],r+x[v+1]);q.b.closePath();q.b.fill()}if(++e==a.g&&(e=0,++f==a.K))break}}a.ca.globalCompositeOperation=
a.h&&a.c!=a.i?"source-over":"copy";a.ca.drawImage(a.m,0,0,a.X,a.v,0,0,a.Z,a.N);a.J=!1;a.R=-1}else a.L||a.I||(!c||!a.T||c-a.T>=(1E3/60|0))&&pc(a);a.I=!1;c&&(a.T=c)}function mc(a){return(a=a||void 0)&&sb[a]||a}
function lc(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=sb[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
ec.prototype.sa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.c&&c==this.h&&a&&a.length==this.a.length){this.a=a;for(b=0;b<=this.a.length-4;b+=4)this.a[b+1]==this.i&&(this.a[b+1]=null);oc(this,!0);return!0}return!1};ec.prototype.ta=function(a){this.a&&(a.push(this.c),a.push(this.h),a.push(this.a))};
var ic=0,gc=1,jc=3,hc={small:ic,round:gc,square:2,digit:jc},fc="container",qc=0,uc=1,rc=128,xc={},tc=(xc[ic]=[4,4,4],xc[gc]=[16,16,14],xc[2]=[2,2,28,28],xc),kc=[[8,8],[32,32],[32,32],[96,128]],wc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},vc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C",
"D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};y.LED=ec;
function yc(a,b,c){K.call(this,a,b,c);this.ga=G(this,"cyclesMinimum",1E5,void 0);this.qa=G(this,"cyclesMaximum",1E9,void 0);this.X=Ya(G(this,"cyclesPerSecond",1E6,void 0),this.ga,this.qa);this.L=1E3/60;this.ra=G(this,"updatesPerSecond",2,void 0)||2;this.Ua=1E3/this.ra;this.oa=0;this.Va=G(this,"timeLock",!0);this.fa=this.H=0;this.ea=this.g=1;this.na=this.i=this.X/1E4/100;this.Z=[];this.v=[];this.b=[];this.T=[];this.ia=this.a=this.K=this.m=!1;this.u=this.f=0;a=Ta("requestAnimationFrame");if(!a){a="setTimeout";
var d=this.L}this.xa=window[a].bind(window,this.Ve.bind(this),d);this.Na=window[Ta("cancelAnimationFrame")||"clearTimeout"].bind(window);this.R=this.N=this.h=this.c=this.V=0;zc(this)||Ac(this,this.ea)}n(yc,K);function nc(a,b){a.Z.push(b)}l=yc.prototype;
l.Ia=function(a,b){var c=this;switch(a){case Bc:b.onclick=function(){Cc(c)&&(c.a?Dc(c):c.start())};break;case Ec:b.onclick=function(){Ac(c,c.g<<1);Fc(c,Gc(c.i))};break;case Hc:b.onclick=function(){Ic(c)};break;case Jc:b.addEventListener("mousedown",function(){c.m=!0}),b.addEventListener("mouseup",function(){zc(c);c.m=!1}),b.addEventListener("mousemove",function(){c.m&&zc(c)}),b.addEventListener("change",function(){c.m=!0;zc(c);c.m=!1})}K.prototype.Ia.call(this,a,b)};
function Nb(a,b,c){var d=void 0===d?-1:d;var e=a.b.length+1;a.b.push({id:b,ge:c,lb:d,va:-1});0<=d&&Sb(a,e,d);return e}
function Kc(a,b,c,d){var e=0,f=a.i,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.l(w.gb,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.L&&(1<a.g&&(a.g>>=1,a.l(w.hb,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.L,a.g)),e=d));a.H=f;a.fa=f/a.na;b=a.fa/a.g;a.V=g/b/60+1E-8;a.l(w.gb,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.V,g,b,60);return e}
function Lc(a,b){a.N=a.h=b;if(!a.v.length)return a.h=0,a.N;for(var c=0;0<a.h;){if(c<a.v.length){var d=a.v[c++];b=d.Xe.call(d,b)||1}else c=b=0;a.h-=b}return a.N-a.h}function Mc(a,b){b=void 0===b?a.N-a.h:b;if(!a.a){if(a.c)for(var c=0;c<a.v.length;c++){var d=a.v[c];d.Ye.call(d)}a.c=b}a.c-=b;1>a.c&&(a.K=!0);a.R+=b;a.N=a.h=0;a.a||(a.R=0);return b}
function Nc(a,b){b=void 0===b?0:b;if(b){var c=b;a.c+=b}else for(c=a.c,1>c&&(c=a.c+=a.V),0>c&&(a.l(w.hb,"warning: cycle count dropped below zero: %f\n",c),c=a.c=0),c|=0,b=a.b.length;0<b;b--){var d=a.b[b-1];!(0>d.va)&&c>d.va&&(c=d.va)}return c}function Gc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Oc(a){a.l(w.gb,"getSpeedCurrent(%5.3fhz)\n",1E6*a.H);return a.a&&a.H?Gc(a.H):"Stopped"}
function Cc(a){return a.ia?!0:(F(a,"not powered"),!1)}function Pc(a,b){if(1<=b)for(var c=a.b.length;0<c;c--){var d=a.b[c-1];0>d.va||(d.va-=b,0>=d.va&&(d.va=-1,d.ge(),0<=d.lb&&Sb(a,c,d.lb)))}}l.ka=function(a){this.ia=a;void 0===this.W&&(this.W=N(this,"Debugger",!1))&&this.W.Hb(this,"time","dump time state",this.ve)};function Ic(a,b){Cc(a)&&(a.a?F(a,"already running"):a.f?Dc(a):Qc(a,b))}
l.Ve=function(a){a=void 0===a?Date.now():a;this.u=0;if(this.a){var b=Date.now();if(this.J){var c=b-this.I-this.L;c>this.L&&(this.j+=c,this.l(w.hb,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.I=b;this.j||(this.j=b);this.ca=0;try{this.K=!1;do Pc(this,Mc(this,Lc(this,Nc(this))));while(this.a&&!this.K)}catch(d){F(this,d.message),Dc(this)}this.J=Date.now();this.ca&&(this.j+=this.ca,this.I+=this.ca);this.I+=Kc(this,this.R,this.J-this.j,this.J-this.I);this.J-this.oa>=this.Ua&&
this.update();for(b=0;b<this.Z.length;b++)this.Z[b](a);this.u=this.xa()}};function Ac(a,b){if(void 0!==b){if(1>b||!a.m&&0<a.H&&a.H<.9*a.i)b=a.ea;a.g=b;b=a.na*a.g;a.i!=b&&(a.i=b,Fc(a,Gc(a.i)))}a.j=a.J=0;a.c=a.R=0;Kc(a);for(b=a.b.length;0<b;b--){var c=a.b[b-1];0<=c.lb&&Sb(a,b,c.lb,!0)}}function zc(a){var b=a.Y[Jc];return b?(Ac(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.qa-a.ga)+a.ga)/a.X|0),!0):!1}
function Sb(a,b,c,d){0<b&&b<=a.b.length&&(b=a.b[b-1],d||0>b.va)&&(c=Math.ceil(a.X*(a.Va?a.ea:a.fa)/1E3*(void 0===c?1E3:c)),a.a&&(c+=Mc(a)),b.va=c)}l.start=function(){if(this.a||this.f)return!1;this.a=!0;this.j=this.J=0;this.update(!0);this.u=this.xa();return!0};function Qc(a,b){b=void 0===b?1:b;a.a||(b&&!a.f&&(a.f=b),a.f&&(a.f--,Pc(a,Mc(a,Lc(a,Nc(a,1)))),a.update(!1),a.f&&setTimeout(function(){Qc(a,0)},0)))}
function Dc(a){return a.a?(a.a=!1,Mc(a),a.u&&(a.Na(a.u),a.u=0),a.update(!0),!0):a.f?(a.f=0,a.update(!0),!0):!1}l.update=function(a){a&&F(this,this.a?"started with "+Gc(this.i)+" target":"stopped");mb(this,Bc,this.a?"Halt":"Run");mb(this,Hc,this.f?"Stop":"Step");this.m||Fc(this,Oc(this));for(var b=0;b<this.T.length;b++){var c=this.T[b];c.Zc.call(c,void 0!=a)}this.oa=Date.now();this.K=!0};function Fc(a,b){mb(a,Rc,b);mb(a,Ec,b)}
l.ve=function(){var a=this.w("nCyclesPerSecond: %f\n",this.X);a+=this.w("nUpdatesPerSecond: %f\n",this.ra);a+=this.w("nTargetMultiplier: %f\n",this.g);return a+=this.w("nCyclesDepositPerFrame: %f\n",this.V)};var Bc="run",Ec="setSpeed",Rc="speed",Hc="step",Jc="throttle";y.Time=yc;
function Sc(a,b,c){K.call(this,a,b,c);this.type="static"==this.s.type?Tc:Uc;this.$=this.s.addrWidth||16;this.i=Math.pow(2,this.$);this.h=this.i-1|0;this.f=this.s.blockSize||(16<this.$?4096:1024);this.f>this.i&&(this.f=this.i);this.H=this.i/this.f|0;this.b=Math.log2(this.f)|0;this.c=(1<<this.b)-1;this.g=this.s.dataWidth||8;this.u=Math.pow(2,this.g)-1;this.j=!1!==this.s.littleEndian;this.a=Array(this.H);this.m=0;this.v=null;a=new O(a,b+"[NONE]",{size:this.f,bus:this.M});for(b=0;b<this.i;b+=this.f)Vc(this,
b,this.f,P.NONE,a);Wc(this,this.type)}n(Sc,K);function Vc(a,b,c,d,e){for(var f=b>>>a.b;0<c&&f<a.a.length;){var g=f*a.f,k=a.f-(b-g);k>c&&(k=c);var h=a.a[f];if(b!=g||k!=a.f||h&&h.type!=P.NONE)break;h=a.M+"["+z(a,b,16,a.$)+"]";b=e?e.size==a.f?e:new O(a.U,h,{type:d,da:b,size:k,bus:a.M}):new O(a.U,h,{type:d,da:b,size:k,bus:a.M});a.a[f]=b;b=g+a.f;c-=k;f++}}function Xc(a,b){for(var c=P.Pd,d=0,e=0;e<a.a.length;e++){var f=a.a[e];f&&f.type&c&&(b(f),d++)}return d}
function Yc(a,b,c){if(!(b&a.c)){b>>>=a.b;var d=a.a[b];a.a[b]=c}return d}function Zc(a,b,c){a.W&&a.W.l(w.nc,"bus fault (%d) at %n\n",c,b);a.v&&a.v(b,c)}l=Sc.prototype;l.ka=function(){void 0===this.W&&(this.W=N(this,"Debugger",!1))};l.la=function(){};l.Lb=function(a){return a&&this.sa(a)?!0:!1};l.ab=function(a){this.ta(a)};l.sa=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if((this.type==Uc||c.type&P.Oa)&&c.sa){var d=a.shift();if(!c.sa(d))return!1}}return!0};
l.ta=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if((this.type==Uc||c.type&P.Oa)&&c.ta){var d=[];c.ta(d);a.push(d)}}};l.Nb=function(a){return this.a[a>>>this.b].Nb(a&this.c)};l.ed=function(a){return this.a[a>>>this.b].wa(a&this.c)};l.bb=function(a,b){this.a[a>>>this.b].bb(a&this.c,b)};l.Ba=function(a,b){this.a[a>>>this.b].ua(a&this.c,b)};l.$b=function(a){return a&1?this.wa(a+1&this.h)|this.wa(a)<<this.g:this.a[a>>>this.b].ha(a&this.c)};
l.ac=function(a){return a&1?this.wa(a)|this.wa(a+1&this.h)<<this.g:this.a[a>>>this.b].ha(a&this.c)};l.De=function(a){return(a&this.c)==this.c?this.j?this.ac(a):this.$b(a):this.a[a>>>this.b].ha(a&this.c)};l.bc=function(a,b){a&1?(this.ua(a,b>>this.g),this.ua(a+1&this.h,b&this.u)):this.a[a>>>this.b].ba(a&this.c,b)};l.cc=function(a,b){a&1?(this.ua(a,b&this.u),this.ua(a+1&this.h,b>>this.g)):this.a[a>>>this.b].ba(a&this.c,b)};
l.$e=function(a,b){(a&this.c)==this.c?this.j?this.cc(a,b):this.bc(a,b):this.a[a>>>this.b].ba(a&this.c,b)};function Wc(a,b){var c=a.m;a.m+=b;c&&a.m||(a.wa=a.ed,a.ua=a.Ba,a.type==Uc?(a.ha=a.De,a.ba=a.$e):a.j?(a.ha=a.ac,a.ba=a.cc):(a.ha=a.$b,a.ba=a.bc))}l.nb=function(a,b){return this.a[a>>>this.b].nb(b)?(Wc(this,1),!0):!1};l.Qb=function(a,b){return this.a[a>>>this.b].Qb(b)?(Wc(this,1),!0):!1};l.ob=function(a,b){return this.a[a>>>this.b].ob(b)?(Wc(this,-1),!0):!1};
l.Sb=function(a,b){return this.a[a>>>this.b].Sb(b)?(Wc(this,-1),!0):!1};var Tc=0,Uc=1;y.Bus=Sc;
function O(a,b,c){K.call(this,a,b,c);this.da=this.s.addr;this.size=this.s.size;this.type=this.s.type||P.NONE;this.f=(a=this.s.bus)?vb(this,a):N(this,a="Bus");if(!this.f)throw Error(this.w("unable to find bus '%s'",a));this.a=this.f.g;this.c=Math.pow(2,this.a)-1;this.T=this.X=!1;this.g=!1!==this.f.j;this.values=this.V=this.v=this.R=null;a=this.Ma;b=this.Ba;c=this.g?this.Fe:this.Ee;var d=this.g?this.bf:this.af;this.f.type==Tc&&(b=this.lf,c=this.g?this.Gd:this.Fd,d=this.mf,8==this.a&&!1!==zb(this,"ArrayBuffer")&&
(this.X=!0,c=this.g==ua?this.Oe:this.Pe));switch(this.type){case P.NONE:this.wa=this.Ka;this.ua=this.Da;this.ha=this.Ge;this.ba=this.cf;break;case P.Cc:this.wa=a;this.ua=this.Da;this.ha=c;this.ba=this.Da;break;case P.Oa:this.wa=a,this.ua=b,this.ha=c,this.ba=d}this.H=this.h=0;this.N=this.i=this.L=this.J=this.j=this.m=null;$c(this,this.s.values);ad(this)}n(O,K);
function $c(a,b){"string"==typeof b?(Cb(a,!1),$a(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);$c(a,g.values)}catch(k){a.l("error (%s) parsing resource: %s\n",k.message,c)}Cb(a,!0)}else a.l("error (%d) loading resource: %s\n",f,c)})):a.s.values=b}
function ad(a,b){if(a.type>P.NONE&&(a.X?(a.v=new ArrayBuffer(a.size),a.R=new DataView(a.v,0,a.size),a.values=new Uint8Array(a.v,0,a.size),a.V=new Uint16Array(a.v,0,a.size>>1),new Int32Array(a.v,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}l=O.prototype;
l.la=function(){if(this.s.values)a:{var a=this.f,b=this.da,c=this.size,d=this.s.values,e=0,f=b&a.c;b>>>=a.b;c>d.length&&(c=d.length);for(;0<c&&b<a.a.length;){var g=a.a[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Ba(f++,d[e++]),c--;f=0}}else this.type&P.Oa&&this.values&&this.values.fill(0)};l.Ka=function(){return this.c};l.Ge=function(a){return this.g?this.Ka(a)|this.Ka(a+1)<<this.a:this.Ka(a+1)|this.Ka(a)<<this.a};l.Nb=function(a){return this.values?this.values[a]:0};l.Ma=function(a){return this.values[a]};
l.Fd=function(a){return this.values[a+1]|this.values[a]<<this.a};l.Gd=function(a){return this.values[a]|this.values[a+1]<<this.a};l.Oe=function(a){return this.V[a>>>1]};l.Pe=function(a){return this.R.getUint16(a,this.g)};l.Ee=function(a){return this.Ma(a+1)|this.Ma(a)<<this.a};l.Fe=function(a){return this.Ma(a)|this.Ma(a+1)<<this.a};l.Da=function(){};l.cf=function(a,b){this.g?(this.Da(a,b&this.c),this.Da(a+1,b>>this.a)):(this.Da(a,b>>this.a),this.Da(a+1,b&this.c))};
l.bb=function(a,b){this.values&&(this.values[a]=b)};l.Ba=function(a,b){this.values[a]=b};l.lf=function(a,b){this.values[a]=b;this.T=!0;this.h?this.J=this.Ba:this.ua=this.Ba};l.wb=function(a,b){this.values[a]=b>>this.a;this.values[a+1]=b&this.c};l.xb=function(a,b){this.values[a]=b&this.c;this.values[a+1]=b>>this.a};l.Tb=function(a,b){this.V[a>>>1]=b};l.Ub=function(a,b){this.R.setUint16(a,b,this.g)};l.af=function(a,b){this.Ba(a,b>>this.a);this.Ba(a+1,b&this.c)};
l.bf=function(a,b){this.Ba(a,b&this.c);this.Ba(a+1,b>>this.a)};l.mf=function(a,b){this.v?this.g==ua?(this.Tb(a,b),this.h?this.i=this.Tb:this.ba=this.Tb):(this.Ub(a,b),this.h?this.i=this.Ub:this.ba=this.Ub):this.g?(this.xb(a,b),this.h?this.i=this.xb:this.ba=this.xb):(this.wb(a,b),this.h?this.i=this.wb:this.ba=this.wb)};
l.nb=function(a){if(!this.H){var b=this;this.H++;this.j=a;this.L=this.wa;this.N=this.ha;this.wa=function(c){var d=b.L(c);b.j(b.da,c,d);return d};this.ha=function(c){var d=b.N(c);b.j(b.da,c,d);b.j(b.da,c+1,d);return d};return!0}return this.j==a?(this.H++,!0):!1};l.Qb=function(a){if(!this.h){var b=this;this.h++;this.m=a;this.J=this.ua;this.i=this.ba;this.ua=function(c,d){b.m(b.da,c,d);b.J(c,d)};this.ba=function(c,d){b.m(b.da,c,d);b.m(b.da,c+1,d);b.i(c,d)};return!0}return this.m==a?(this.h++,!0):!1};
l.ob=function(a){return this.H&&this.j==a?(--this.H||(this.wa=this.L,this.ha=this.N,this.L=this.N=this.j=null),!0):!1};l.Sb=function(a){return this.h&&this.m==a?(--this.h||(this.ua=this.J,this.ba=this.i,this.J=this.i=this.m=null),!0):!1};l.sa=function(a){var b=a.shift();if(this.M==b){this.T=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}ad(this,a)}return!0}return!1};
l.ta=function(a){a.push(this.M);a.push(this.T);a.push(!1);a.push(this.values?Aa(this.values):this.values)};var P={NONE:1,Cc:2,Oa:4,Pd:14,Jg:12};y.Memory=O;function bd(a,b,c){O.call(this,a,b,c);this.u=[];this.I=[];this.b=[];this.K=[];void 0!=this.s.addr&&Vc(this.f,this.s.addr,this.s.size,P.NONE,this)}n(bd,O);
function cd(a,b,c,d,e,f,g,k){for(var h;c<=d;c++){h=!1;if(e){if(a.u[c])break;a.u[c]=e.bind(b)}if(f){if(a.I[c])break;a.I[c]=f.bind(b)}if(g){if(a.b[c])break;a.b[c]=g.bind(b)}if(k){if(a.K[c])break;a.K[c]=k.bind(b)}h=!0}if(!h)throw Error(a.w("handler for port %#0x already exists",c));}function dd(a,b,c){var d=void 0===d?0:d;for(var e in c){var f=c[e];cd(a,b,+e+d,+e+d,f[0],f[1],f[2],f[3])}}
bd.prototype.Ka=function(a){var b,c=this.da+a;if(b=this.u[c]){var d=b(c);var e=!0}else if(b=this.b[c])d=c&1?b(c&-2)>>this.a:b(c)&this.c,e=!0;else if(c&1)if(c&=-2,b=this.b[c])d=b(c)>>this.a,e=!0;else if(b=this.u[c])d=b(c),e=!0;e||(Zc(this.f,c,0),this.l(w.yb+w.vb,"readNone(%#04x): unknown port\n",c),d=O.prototype.Ka.call(this,a));return d};
bd.prototype.Da=function(a,b){var c,d=this.da+a;if(c=this.I[d]){c(d,b);var e=!0}else if(c=this.K[d])e=this.b[d]?this.b[d](d,!0):0,d&1?c(d,e&this.c|b<<this.a):c(d,e&~this.c|b),e=!0;else if(d&1)if(d&=-2,c=this.K[d])e=this.b[d]?this.b[d](d,!0):0,c(d,e&this.c|b<<this.a),e=!0;else if(c=this.I[d])c(d,b),e=!0;e||(Zc(this.f,d,1),this.l(w.yb+w.vb,"writeNone(%#04x,%#04x): unknown port\n",d,b),O.prototype.Da.call(this,a,b))};y.Ports=bd;
function ed(a,b,c){c.type=P.NONE;O.call(this,a,b,c);Vc(this.f,this.s.addr,this.s.size,P.Oa);Db(this,this.la.bind(this))}n(ed,O);y.RAM=ed;
function fd(a,b,c){c.type=P.Cc;O.call(this,a,b,c);Vc(this.f,this.s.addr,this.s.size,this.s.type,this);Db(this,this.la.bind(this));this.o=this.W=void 0;if(y.LED&&this.Y[gd]){var d=this;this.u=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.I=this.values.length/this.u|0;this.b=new ec(a,b+"LEDs",{"class":"LED",bindings:{container:Va(this,gd)},type:gc,cols:this.u,rows:this.I,color:G(this,"colorROM","green"),backgroundColor:G(this,"backgroundColorROM","black"),persistent:!0}),pc(this.b);this.K=
new Gb(a,b+"Input",{"class":"Input",location:[0,0,this.b.Z,this.b.N,this.u,this.I],bindings:{surface:Va(this,gd)}});this.Z=Wa(this)||"";Jb(this.K,function(e,f){if(d.o){var g=d.Z;0<=e&&0<=f&&(e=f*d.u+e,f=d.o,g=f.W&&hd(f.W,d.da+e,1)||"");mb(d,Xa,g)}})}}n(fd,O);
fd.prototype.sa=function(a){var b=!0,c=a.shift();if(c&&this.b){var d=c.length;this.b.a.length==d?(this.b.a=c,oc(this.b,!0)):(this.l("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.l("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};fd.prototype.ka=function(){void 0===this.o&&(this.o=N(this,"CPU"));void 0===this.W&&(this.W=N(this,"Debugger",!1))&&this.W.Ib&&this.W.Ib(this.s.symbols)};
fd.prototype.Ma=function(a){if(this.b){var b=this.b,c=rc;c=(void 0===c?0:c)&129;var d=4*((a/this.u|0)*b.H+a%this.u);if(d<=b.a.length-4){if(1!==b.a[d]||(b.a[d+3]&129)!==c)b.a[d]=1,b.a[d+3]=b.a[d+3]&-130|c|rc,b.J=!0;b.R=d;b.I=!0;b.u=0}}return this.values[a]};fd.prototype.ta=function(a){this.b&&(a.push(this.b.a),a.push(this.values))};var gd="array",Xa="cellDesc";y.ROM=fd;
function id(a,b,c){c["class"]="CPU";K.call(this,a,b,c);this.W=void 0;this.Cb=this.Ob=0;this.time=N(this,"Time");this.time.v.push(this);this.time.T.push(this);this.ga=this.V=0}n(id,K);id.prototype.abort=function(a){this.Cb=this.Ob;F(this,a.message);Dc(this.time)};function jd(a,b){a.W=b;return a.Fa}id.prototype.Xe=function(a){this.ga=this.V=void 0===a?0:a;return this.ga-this.V};id.prototype.Ye=function(){this.ga-=this.V;this.V=0};
function kd(a,b,c){c["class"]="Debugger";K.call(this,a,b,c);var d=this;this.aa=this.s.defaultRadix||16;this.ea=1;this.R=["(",")"];Ca(this,"a",function(f,g,k,h,p){return z(d,p.O,d.aa,k)});Ca(this,"n",function(f,g,k,h,p){return z(d,p,d.aa,k,0>g.indexOf("#")?"":void 0)});this.v=0;this.fa=w.NONE;this.H={};this.ga=[];this.ia=[];this.o=N(this,"CPU");this.Fa=jd(this.o,this);this.na=N(this,"Input",!1);if(a=this.o.s.busMemory||this.s.busMemory){this.a=vb(this,a);if(a=this.o.s.busIO||this.s.busIO)this.f=vb(this,
a,!1);this.f||(this.f=this.a)}else this.a=this.f=N(this,"Bus");this.u=this.a.$;this.xa=Math.pow(2,this.u)-1|0;this.j=this.Z=0;this.i=[];for(var e in R)this.i[R[e]]=[];this.h=[];this.h[R.za]=this.a;this.h[R.Ya]=this.a;this.h[R.Ca]=this.f;this.h[R.Sa]=this.f;this.g=[];this.g[R.za]=this.je.bind(this);this.g[R.Ya]=this.me.bind(this);this.g[R.Ca]=this.he.bind(this);this.g[R.Sa]=this.ie.bind(this);this.c=[];this.I=void 0;this.N=null;this.T=0;this.time=N(this,"Time");this.time.T.push(this);this.V=0;this.m=
[];this.L="";this.Hb(this,"state","dump machine state",this.ue);this.X=ld();this.oa=ld();this.ca=!1;this.K=0;this.b=[];Qa(this,this.ze.bind(this));(e=zb(this,"commands"))&&fb(this,e)}n(kd,K);l=kd.prototype;l.Hb=function(a,b,c,d){this.m.push({te:a,name:b,se:c,jb:d})};function md(a,b,c){for(var d,e=0;e<a.m.length;e++){var f=a.m[e];if(f.name==b){d=f.jb.call(f.te,c);break}}return d}
l.Ib=function(a){if(a&&a.length)for(var b=0;b<a.length-2;b+=3){var c=nd(this,a[b]);if(c){var d=od[a[b+1]];if(d){c={Ja:c,type:d,name:a[b+2]};d=this.ga;var e=c,f=pd(d,e,this.Sc);0>f&&d.splice(-(f+1),0,e);d=this.ia;e=pd(d,c,this.Tc);0>e&&d.splice(-(e+1),0,c)}}}};function pd(a,b,c){var d=0,e=a.length,f=0;for(void 0===c&&(c=function(h,p){return h>p?1:h<p?-1:0});d<e;){var g=d+e>>1,k=void 0;k=c(b,a[g]);0<k?d=g+1:(e=g,f=!k)}return f?d:~d}l.Sc=function(a,b){return a.name>b.name?1:a.name<b.name?-1:0};
l.Tc=function(a,b){return a.Ja.O>b.Ja.O?1:a.Ja.O<b.Ja.O?-1:0};function qd(a,b,c){b=pd(a.ia,{Ja:b,type:0,name:void 0},a.Tc);if(0<=b&&(a=a.ia[b],!c||a.type==c))var d=a.name;return d}function rd(a,b,c,d){d=void 0===d?a.a:d;b.O=b.O+c&d.h}function ld(a){a=void 0===a?0:a;var b=sd.Md;return"number"==typeof a?{O:a,Pb:-1,type:b}:{O:a.O,Pb:a.Pb,type:a.type}}
function nd(a,b,c){if(b){var d=ld();var e=0,f=b.charAt(e);switch(f){case "&":e++;break;case "#":e++;d.type=sd.Nd;break;case "%":e++,f=b.charAt(e),"%"==f?e++:d.type=sd.Ic}f=b.indexOf(":",e);if(0<=f){var g=td(a,b.substring(e,f),c);void 0==g?d=null:(d.Pb=g,e=f+1)}d&&(b=td(a,b.substring(e),c),void 0==b?d=null:d.O=b&a.xa)}return d}function ud(a,b,c,d){d=void 0===d?a.a:d;a.j++;var e=d.Nb(b.O);c&&rd(a,b,c,d);a.j--;return e}
function vd(a,b,c){if(32>=a.u)return b&c;b=S(a,b,0,!0);c=S(a,c,0,!0);return((b/E|0)&(c/E|0))*E+((b&c)>>>0)}function wd(a,b,c){if(32>=a.u)return b^c;b=S(a,b,0,!0);c=S(a,c,0,!0);return((b/E|0)^(c/E|0))*E+((b^c)>>>0)}
function xd(a,b,c,d){for(d=void 0===d?-1:d;d--&&c.length;){var e=c.pop();if(2>b.length)return!1;var f=b.pop();var g=b.pop();switch(e){case "*":g*=f;break;case "/":if(!f)return!1;g=Math.trunc(g/f);break;case "^/":if(!f)return!1;g%=f;break;case "+":g+=f;break;case "-":g-=f;break;case "<<":g<<=f;break;case ">>":g>>=f;break;case ">>>":g>>>=f;break;case "<":g=g<f?1:0;break;case "<=":g=g<=f?1:0;break;case ">":g=g>f?1:0;break;case ">=":g=g>=f?1:0;break;case "==":g=g==f?1:0;break;case "!=":g=g!=f?1:0;break;
case "&":g=vd(a,g,f);break;case "!":case "|":e=g;32>=a.u?g=e|f:(e=S(a,e,0,!0),f=S(a,f,0,!0),g=(e/E|0|f/E|0)*E+((e|f)>>>0));break;case "^!":g=wd(a,g,f);break;case "&&":g=g&&f?1:0;break;case "||":g=g||f?1:0;break;case ",,":g=S(a,g,18,!0)*Math.pow(2,18)+S(a,f,18,!0);break;case "_":case "^_":"^_"==e&&(f=35-(f&255));f&&(g=S(a,g,0,!0),g=0<f?g*Math.pow(2,f):Math.trunc(g/Math.pow(2,-f)));break;default:return!1}b.push(S(a,g))}return!0}
function yd(a,b,c,d,e,f){var g,k=!1,h=0,p=[],m=[],u=a.aa;for(a.aa=e;c<d;){var q=b[c++].trim();var r=c<d?b[c++]:"";if(q){var x=void 0;var v=a;var A=q,t=f;h=void 0===h?0:h;if(void 0!=A){x=Ab(v,A.toUpperCase());if(void 0==x){x=void 0;var Ea=v,W=pd(Ea.ga,{Ja:null,type:0,name:A},Ea.Sc);0<=W&&(x=Ea.ga[W].Ja.O);if(void 0==x)if(x=A,v.H[x]?x=v.H[x].value:(x=x.substr(0,6),x=v.H[x]&&v.H[x].value),void 0==x)x=ya(A,1<A.length||10<v.aa?v.aa:10);else if(A=v.H[A]&&v.H[A].$g)t?t.push(A):(t=td(v,A,t),void 0!==t?x+=
t:x=void 0)}void 0!=x&&(x=S(v,zd(v,x,h)))}v=x}else if("{"==r){q=1;for(v=c;c<d;)if(c++,r=c<b.length?b[c++]:"","{"==r)q++;else if("}"==r&&!--q)break;v=yd(a,b,v,c-1,a.aa,f);null!=v&&h&&(v=zd(a,v,h));q=c<d?b[c++].trim():"";r=c<d?b[c++]:""}else{if(" "==r)continue;if("^B"==r){a.aa=2;continue}if("^O"==r){a.aa=8;continue}if("^D"==r){a.aa=10;continue}if(!(h&-1073741824)){if("+"==r)continue;if("-"==r){h=h<<2|1;continue}if("~"==r||"^-"==r){h=h<<2|2;continue}if("^L"==r){h=h<<2|3;continue}}k=!0;break}if(void 0===
v)if(f)f.push(q),v=0;else{k=!0;break}p.push(S(a,v));if(" "==r)if(c<b.length-1&&!b[c])c++,r=b[c++];else{k=!0;break}if(!r)break;v="<"==a.R[0]?Ad:Bd;if(!v[r]){k=!0;break}m.length&&v[r]<=v[m[m.length-1]]&&xd(a,p,m,1);m.push(r);a.aa="^_"==r?10:e;h=0}if(k||!xd(a,p,m)||1!=p.length)k=!0;k?f||a.l("parse error (%s)\n",q||r):g=p.pop();a.aa=u;return g}
function Cd(a,b,c,d){for(var e,f=a.u/d|0;0<=(e=b.indexOf(c));){for(var g=0,k=e+1,h=f;k<b.length;){var p=b[k++];if(p==c){h=-1;break}if(!h)break;h--;p=p.charCodeAt(0);6==d&&(p-=32);p&=(1<<d)-1;g=S(a,g*Math.pow(2,d)+p,d*f,!0)}if(0<=h){a.l("parse error (%c%s%c)\n",c,b,c);return}b=b.substr(0,e)+z(a,g)+b.substr(k)}return b}
function td(a,b,c){if(b){"{"!=a.R[0]&&(b=b.split(a.R[0]).join("{").split(a.R[1]).join("}"));b=Cd(a,b,'"',8);if(!b)return d;b=Cd(a,b,"'",6);if(!b)return d;16!=a.aa&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);var d=yd(a,b,0,b.length,a.aa,c)}return d}
function zd(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-S(a,b);break;case 2:b=wd(a,b,-1);break;case 3:for(d=35;0<=d&&!vd(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function S(a,b,c,d){var e=b;c=c||a.u;if(d)if(32==c)e=b>>>0;else if(32>c)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),0>b||b>=a)e=b%a,0>e&&(e+=a)}else 32>=c?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}
l.Jb=function(a){function b(k){for(var h=0;h<k.length;h++)if(void 0!=k[h])return!1;return!0}if(-1>a)return Dd(this,this.Jb);var c="";if(0<=a){var d=this.c[a];if(void 0!=d){c=d>>8;d&=255;var e=this.h[c];if(e){var f=this.i[c],g=f[d];(c&1?e.Sb(g.O,this.g[c]):e.ob(g.O,this.g[c]))?(f[d]=void 0,this.c[a]=void 0,b(f)&&(f.length=0,b(this.c)&&(this.c.length=0)),c=this.w("%2d: %s %*a cleared\n",a,Ed[c],e.$,g),--this.Z||this.ca||(c+=Fd(this,!1))):c=this.w("invalid break address: %*a\n",e.$,g)}else c="invalid bus"}else c=
this.w("invalid break index: %d\n",a)}else c="missing break index\n";return c};function Gd(a,b){if(a.N&&(void 0==b||a.N.O==b)){var c=void 0===c?R.za:c;b=-1;var d=Hd(a.N,a.i[c]);if(0<=d)for(var e=0;e<a.c.length;e++){var f=a.c[e];if(void 0!=f&&c==f>>8&&d==(f&255)){b=e;break}}c=b;0<=c&&a.Jb(c);a.N=null}}
l.Kb=function(a,b){b=void 0===b?!1:b;if(-1>a)return Dd(this,this.Kb,b);if(0<=a){var c=this.c[a];if(void 0!=c){var d=c>>8;c=this.i[d][c&255];if(void 0!=c){var e=b?"enabled":"disabled",f=this.h[d];!c.disabled==!b?(c.disabled=!b,a=this.w("%2d: %s %*a %s\n",a,Ed[d],f.$,c,e)):a=this.w("%2d: %s %*a already %s\n",a,Ed[d],f.$,c,e)}else a=this.w("no break address at index: %d\n",a)}else a=this.w("invalid break index: %d\n",a)}else a="missing break index\n";return a};
function Dd(a,b,c){for(var d="",e=0;e<a.c.length;e++)void 0!=a.c[e]&&(d+=b.call(a,e,c));d||(d="no break addresses found");return d}function Id(a,b,c){c=void 0===c?R.za:c;a=a.i[c];for(c=0;c<a.length;c++){var d=a[c];if(d.O==b)return d}}function Hd(a,b){for(var c=0;c<b.length;c++)if(b[c].O==a.O)return c;return-1}
function Jd(a,b){b=void 0===b?!1:b;for(var c="",d=0;d<a.c.length;d++){var e=a.c[d];if(void 0!=e){var f=e>>8;e=a.i[f][e&255];f=a.w("%s %*a",Ed[f],a.h[f].$,e);b?(c&&(c+=";"),c+=f,e.disabled&&(c+=";bd "+d)):c+=a.w("%2d: %s %s\n",d,f,e.disabled?"disabled":"enabled")}}c||b||(c="no break addresses found\n");return c}
function Kd(a,b,c){c=void 0===c?R.za:c;if(b){var d=a.h[c];if(d){var e=a.i[c];var f=Hd(b,e);if(0<=f)f=-(f+1);else{for(f=0;f<e.length&&void 0!=e[f];f++);e[f]=b}e=f;if(0<=e)if(f=c&1?d.Qb(b.O,a.g[c]):d.nb(b.O,a.g[c])){for(f=0;f<a.c.length&&void 0!=a.c[f];f++);a.c[f]=c<<8|e;b=a.w("%2d: %s %*a set\n",f,Ed[c],d.$,b);a.Z++||a.b.length||(b+=Fd(a,!0))}else b=a.w("invalid break address: %*a\n",d.$,b),a.i[c][e]=void 0;else b=a.w("%s %*a already set\n",Ed[c],d.$,b)}else b="invalid bus"}else b="missing break address\n";
return b}function Ld(a,b){0<=b&&(a.v=b);var c="instruction break count: "+(0<a.v?a.v:"disabled")+"\n";0<b&&(a.b.length||(c+=Fd(a,!0)),a.ca=!0);return c}function Md(a,b){var c;if(b){var d=gb(b);void 0!=d?a.fa=d?w.Xb:w.NONE:c=a.w("unrecognized message option: %s\n",b)}c||(c=a.w("break on message: %b\n",!!a.fa));return c}l.he=function(a,b){this.j||(void 0==a?T(this,"break on unknown input %#0x: %#0x",b):(a=Id(this,a+b,R.Ca))&&!a.disabled&&T(this,"break on input %*a: %#0x",this.f.$))};
l.ie=function(a,b){this.j||(void 0==a?T(this,"break on unknown output %#0x: %#0x",b):(a=Id(this,a+b,R.Sa))&&!a.disabled&&T(this,"break on output %*a: %#0x",this.f.$))};l.je=function(a,b){this.j||(void 0==a?T(this,"break on unknown read %#0x: %#0x",b):(a+=b,this.b.length&&a==this.o.Ob&&(this.T++,0<this.v&&(--this.v||T(this,"break on instruction count")),this.b[this.K++]=a,this.K==this.b.length&&(this.K=0)),(b=Id(this,a,R.za))&&!b.disabled&&(T(this,"break on read %*a: %#0x",this.a.$),Gd(this,a))))};
l.me=function(a,b){this.j||(void 0==a?T(this,"break on unknown write %#0x: %#0x",b):(a=Id(this,a+b,R.Ya))&&!a.disabled&&T(this,"break on write %*a: %#0x",this.a.$))};function T(a,b,c){b=a.w.apply(a,[b].concat(ba(c)));F(a,b);Dc(a.time)}function Nd(a,b,c){c=void 0===c?a.a:c;return z(a,b.O,a.aa,c.$,"")}
function Od(a,b,c){c=void 0===c?10:c;var d="";if(a.b.length){var e,f=[];c>a.b.length&&(c=a.b.length);0>b&&(b=c);var g=a.K-b;for(0>g&&(g+=a.b.length);0<=g&&g<a.b.length&&0<c;){var k=a.b[g++];if(void 0==k)break;g==a.b.length&&(g=0);e?e.O=k:e=ld(k);for(k=0;k<a.ea;k++)f[k]=ud(a,e,1);rd(a,e,-f.length);d+=a.Rb(e,f,a.w("[%6d]",b--));c--}}return d||"no history"}
function hd(a,b,c){var d=[],e="";for(b="number"==typeof b?ld(b):b;c--;){for(rd(a,b,d.length);d.length<a.ea;)d.push(ud(a,b,1));rd(a,b,-d.length);e+=a.Rb(b,d)}return e}
function Pd(a,b,c,d,e,f){var g="";f=f?a.f:a.a;c||(c=f.g);var k=c>>3;d||(d=128);var h=0,p=d+15>>4||1,m=4==k?16:a.aa;"y"==e&&(m=k,p=d,h=8*k);b||(b=a.oa);for(;p--&&0<d;){var u=e=0,q,r="",x="",v=Nd(a,b,f);for(q=m;0<q&&0<d;q--){var A=ud(a,b,1,f);e|=A<<(u++<<3);u==k&&(r+=z(a,e,0,c,""),r+=1==k?9==q?"-":" ":" ",h&&(x+=z(a,e,2,c,"")),e=u=0);h||(x+=32<=A&&127>A?String.fromCharCode(A):".");d--}g&&(g+="\n");g+=v+"  "+r+" "+x}a.oa=b;return g}
l.ue=function(){var a=[];yb(this,function(b){b.ab&&b.ab(a);return!0});return JSON.stringify(a,null,2)};function Qd(a,b,c,d){var e=0,f="";d=d?a.f:a.a;for(var g=0;void 0!=b&&g<c.length;g++){var k=ud(a,b,0,d);if(void 0==k)break;var h=a,p=b,m=c[g],u=d;u=void 0===u?h.a:u;h.j++;u.bb(p.O,m);h.j--;f+=a.w("%*a: %#*n changed to %#*n\n",a.a.$,b,a.a.g,k,a.a.g,c[g]);rd(a,b,1,d);e++}e||(f+=a.w("%d locations updated\n",e));a.time.update();return f}
function Fd(a,b){var c="";void 0!=b&&b==!a.b.length&&Xc(a.a,function(d){b?a.a.nb(d.da,a.g[R.za]):a.a.ob(d.da,a.g[R.za])})&&(b?(a.K=0,a.b=Array(Rd)):a.b=[]);return c+=a.w("instruction history %s\n",a.b.length?"enabled":"disabled")}l.sa=function(a){var b=a.shift();return this.M==b?(fb(this,a.shift()),this.S.ja=a.shift(),!0):!1};l.Yc=function(a){za(this.fa,a)?T(this,"break on message"):this.time.K=!0};
l.ze=function(a){var b=a[1],c=a[2],d=[],e=[],f=!1,g="";this.I=void 0;if("*"==c)var k=-2;else{k=ya(c);void 0==k&&(k=-1);var h=nd(this,c,e);if(null===h)return}var p=0;a[3]&&(p=ya(a[3].substr("l"==a[3][0]?1:0))||8);for(var m=3;m<a.length;m++)d.push(ya(a[m],16));if("d"==b){m=md(this,c,d);if(void 0!=m)return m;b=this.L||b}if("s"!=b[0]&&e.length)return"unrecognized symbol(s): "+e;switch(b[0]){case "b":"c"==b[1]?g=this.Jb(k):"d"==b[1]?g=this.Kb(k):"e"==b[1]?g=this.Kb(k,!0):"i"==b[1]?g=Kd(this,h,R.Ca):"l"==
b[1]?g=Jd(this):"m"==b[1]?g=Md(this,c):"n"==b[1]?g=Ld(this,k):"o"==b[1]?g=Kd(this,h,R.Sa):"r"==b[1]?g=Kd(this,h,R.za):"w"==b[1]?g=Kd(this,h,R.Ya):"?"==b[1]?(g="break commands:\n",Sd.forEach(function(u){g+=u+"\n"})):b[1]&&(g=void 0);break;case "d":this.L=b;if("b"!=b[1]&&b[1])if("w"==b[1])c=16;else if("d"==b[1])c=32;else if("i"==b[1]){if(!this.f){g="invalid bus";break}c=this.f.g;p=p||1;f=!0}else{if("h"==b[1])this.L="",g=Od(this,k,p);else if("?"==b[1]){if(this.L="",g="dump commands:\n",Td.forEach(function(u){g+=
u+"\n"}),this.m.length)for(g+="dump extensions:\n",b=0;b<this.m.length;b++)h=this.m[b],g+=this.w("d   %-12s%s\n",h.name,h.se)}else this.L="",g=void 0;break}else c=8;g=Pd(this,h,c,p,b[2],f);break;case "e":if("o"==b[1]){if(!this.f){g="invalid bus";break}f=!0}else if(b[1]){g=void 0;break}g=Qd(this,h,d,f);break;case "g":if(this.time.start()){if(void 0!=h){Gd(this);g=Kd(this,h);if(2!=g.indexOf(":"))break;this.N=h;g=""}break}g="already started\n";break;case "h":Dc(this.time)||(g="already stopped\n");break;
case "p":a.shift();a.shift();b=a.join(" ");g+=this.w("%s = %s\n",b,z(this,td(this,b)));break;case "r":if(b=b.substr(1).toUpperCase()){if(void 0==Ab(this.o,b)){g+=this.w("unrecognized register: %s\n",b);break}void 0!=h&&Fb(this.o,b,h.O)}this.X.O=this.o.Cb;g+=this.o.toString();break;case "s":h=gb(c);if("h"==b[1]){if(this.Z||0<this.v)h=void 0;g=Fd(this,h);void 0!=h&&(this.ca=h)}else"p"==b[1]?0<k?(Ac(this.time,k),g="target speed:  "+Gc(this.time.i)):g="current speed: "+Oc(this.time):"s"==b[1]&&this.ra?
(k=this.ra.indexOf(c),0<=k&&(this.style=this.ra[k]),g="style: "+this.style):"?"==b[1]?(g="set commands:\n",Ud.forEach(function(u){g+=u+"\n"})):g=void 0;break;case "t":p=ya(c,10)||1;this.I=!0;if(b[1]){if("r"!=b[1]){g=void 0;break}this.I=!1}Ic(this.time,p);break;case "u":if(b[1]){g=void 0;break}p||(p=8);h||(h=this.X);g+=hd(this,h,p);this.X=h;break;case "?":g="debugger commands:\n";Vd.forEach(function(u){g+=u+"\n"});break;default:g=void 0}void 0==g&&a[0]&&(g="unrecognized command '"+a[0]+"' (try '?')\n");
return g};l.Lb=function(a){return a&&this.sa(a[0])?(a.shift(),!0):!1};l.ab=function(a){var b=[];this.ta(b);a.push(b);this.V=0};l.Zc=function(a){if(a){if(this.time.a){if(this.V&&this.na){a=this.na;var b=a.c;b&&Bb(a.S)&&(a.l(w.Ca,'setFocus("%s")\n',b.id||b.nodeName),b.focus(),b.scrollIntoView())}}else this.I?this.Ha(hd(this,this.o.Cb,1)):(this.T&&(F(this.o,this.T+" instructions executed"),this.T=0),this.o.Ha(this.o.toString()),void 0==this.I&&this.V&&(a=this.Pa(Na.fb,!0))&&a.focus());this.V++}};
l.ta=function(a){a.push(this.M);a.push(Jd(this,!0));a.push(this.S.ja)};l.Rb=function(a,b,c){var d=this;return this.w("%s %02x       unsupported       ; %s\n",Nd(this,a),function(){var e=b.shift();rd(d,a,1);return e}(),c||"")};
var Vd="b?\t\tbreak commands;d?\t\tdump commands;e[o] [addr] ...\tedit memory/ports;g    [addr]\trun (to addr);h\t\thalt;p    [expr]\tparse expression;r?   [value]\tdisplay/set registers;s?\t\tset commands;t[r] [n]\tstep (n instructions);u    [addr] [n]\tunassemble (at addr)".split(";"),Sd="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write;bm [on|off]\tbreak on message;bn [count]\tbreak on instruction count".split(";"),
Td="db  [addr]\tdump bytes (8 bits);dw  [addr]\tdump words (16 bits);dd  [addr]\tdump dwords (32 bits);di  [addr]\tdump input ports;d*y [addr]\tdump values in binary;dh  [n] [l]\tdump instruction history buffer;ds\t\tdump machine state".split(";"),Ud=["sh [on|off]\tset instruction history","sp [n]\t\tset speed multiplier","ss\t\tset debugger style"],sd={Ic:1,Md:0,Nd:2,Gg:0},R={za:0,Ya:1,Ca:2,Sa:3},Wd={},Ed=(Wd[R.za]="br",Wd[R.Ya]="bw",Wd[R.Ca]="bi",Wd[R.Sa]="bo",Wd),Xd={Kd:"PC"},Yd={BYTE:1,Jd:2,Od:4,
vc:5,hc:6,de:7},od={"=":Yd.de,1:Yd.BYTE,2:Yd.Jd,4:Yd.Od,"@":Yd.vc,";":Yd.hc},Rd=1E5,Bd={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},Ad={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};function Zd(a,b,c){id.call(this,a,b,c)}n(Zd,id);
function $d(a,b,c){id.call(this,a,b,c);this.L=+this.s.model||ae;this.X=+this.s.addrReset||0;this.i=N(this,"Bus");this.i.v=this.Ld.bind(this);this.xe=N(this,"IOPage");N(this,"Panel",!1);this.v=0;this.Ab=null;N(this,"Input",!1);this.L<=be?(this.Nc=this.ke,this.Pc=~(ce|de|ee|fe)&65535,this.Vb=0):(this.Nc=this.le,this.Pc=~(ce|(this.L<=ge?de:0))&65535,this.Vb=this.L>ge?de:0);this.Eb=this.Db=this.ia=0;this.g=null;this.Ua=[];he(this)}n($d,Zd);
function he(a){a.Z=65536;a.ea=32768;a.fa=65535;a.ca=32768;a.R=15;a.b=[0,0,0,0,0,0,0,a.X,-1,-2,-3,-4,-5,-6,-7,-8];a.T=[0,0,0,0,0,0];a.ra=[0,0,0,0];a.xa=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];a.Na=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];a.La=
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];a.Rc=[0,0,0,0,0,0,0,0];a.c=0;a.j=-1;a.Qc=0;a.a=0;ie(a);for(var b={Ga:0};7>=b.Ga;b={Ga:b.Ga},b.Ga++)L(a,"R"+b.Ga,function(c){return function(){return a.b[c.Ga]}}(b),function(c){return function(d){return a.b[c.Ga]=d&65535}}(b));xb(a,"R6","SP");xb(a,"R7",Xd.Kd);L(a,"CF",function(){return a.Z&65536&&je?1:0},function(c){a.Z=c?65536:0});L(a,"NF",function(){return a.ca&32768&&me?1:0},function(c){a.ca=c?32768:0});L(a,"VF",function(){return a.ea&
32768&&ne?1:0},function(c){a.ea=c?32768:0});L(a,"ZF",function(){return(a.fa&65535?0:oe)?1:0},function(c){a.fa=c?0:1});L(a,"PS",function(){return pe(a)},function(c){return qe(a,c)});L(a,"PI",function(){return a.qa},function(c){if(c&=re){var d=c>>se;do c+=te;while(d>>=1);a.a|=ue}a.qa=c});L(a,"ER",function(){return a.ma});L(a,"SL",function(){return a.H&65280},function(c){a.H=c|255});L(a,"M0",function(){return ve(a)},function(c){return we(a,c)});L(a,"M1",function(){return xe(a)});L(a,"M2",function(){return ye(a)});
L(a,"M3",function(){return a.m},function(c){return ze(a,c)})}function ie(a){a.f=0;a.na=0;a.oa=0;a.m=0;a.ma=0;a.qa=0;a.H=255;a.N=0;a.I=0;a.K=0;a.u=262143;a.Oc=[4,2,0,1];a.J=a.b[7];a.h=0;a.g=null;Ae(a);for(var b=a.i,c=P.Oa,d=0,e=0;e<b.a.length;e++){var f=b.a[e];f.type&c&&(d=f.da+f.size)}a.we=d}l=$d.prototype;l.Zc=function(){};function ve(a){var b=a.f;b&Be||(b=b&~(Ce|De|Ee)|a.I<<5|a.K<<1);return b}
function we(a,b){b&=~Ce;if(a.f!=b){b&Be&&!(a.f&Be)&&(a.na=a.h>>16&65535,a.oa=a.h&65535);a.f=b;a.I=(b&Ee)>>Fe;a.K=(b&De)>>Ge;var c=0;b&(He|Ie)&&(c=Je,b&He&&(c|=Ke));a.N!=c&&(a.N=c,Ae(a))}}function xe(a){a.f&Be||(a.na=a.h>>16&65535);a=a.na;a&65280&&(a=(a<<8|a>>8)&65535);return a}function ye(a){a.f&Be||(a.oa=a.h&65535);return a.oa}function ze(a,b){a.L<ae&&(b&=~(Le|Me));a.m!=b&&(a.m=b,a.u=b&Le?Ne:Oe,Ae(a))}
function Ae(a){a.Ab&&Yc(a.i,a.v,a.Ab);a.N?(a.Va=Pe,a.v=a.m&Le?Qe:Re,a.Bb=a.Re,a.Xc=a.pf):(a.Va=0,a.v=Se,a.Bb=a.Qe,a.Xc=a.nf);a.Ab=Yc(a.i,a.v,a.xe)}
l.sa=function(a){if(!a||!a.length)return F(this,"invalid saved state"),!1;var b=a.shift(),c=a.shift();if(b!=this.M||3!==(c|0))return this.l("CPU state mismatch (%s %3.2f)\n",b,c),!1;try{this.b=a.shift();this.T=a.shift();this.ra=a.shift();this.xa=a.shift();this.Na=a.shift();this.La=a.shift();this.Rc=a.shift();this.ma=a.shift();this.Qc=a.shift();this.qa=a.shift();this.H=a.shift();this.I=a.shift();this.K=a.shift();this.J=a.shift();this.a=a.shift();this.h=a.shift();this.j=a.shift();this.Db=a.shift();
this.Eb=a.shift();this.X=a.shift();qe(this,a.shift());we(this,a.shift());this.na=a.shift();this.oa=a.shift();ze(this,a.shift());for(var d=a.shift(),e=d.length-1;0<=e;e--){a:{for(a=0;a<this.Ua.length;a++){var f=this.Ua[a];if(f.qb===d[e]){var g=f;break a}}g=null}g&&(g.next=this.g,this.g=g)}}catch(k){return F(this,"CPU state error: "+k.message),!1}return!0};
l.ta=function(a){a.push(this.M);a.push(3);a.push(this.b);a.push(this.T);a.push(this.ra);a.push(this.xa);a.push(this.Na);a.push(this.La);a.push(this.Rc);a.push(this.ma);a.push(this.Qc);a.push(this.qa);a.push(this.H);a.push(this.I);a.push(this.K);a.push(this.J);a.push(this.a);a.push(this.h);a.push(this.j);a.push(this.Db);a.push(this.Eb);a.push(this.X);a.push(pe(this));a.push(ve(this));a.push(xe(this));a.push(ye(this));a.push(this.m);a.push(Te(this))};
function Ue(a,b,c){b={qb:b,priority:4,message:c||0,name:Ve[b],next:null};a.Ua.push(b);return b}function We(a,b){if(b){if(b!=a.g){var c=a.g;if(!c||c.priority<=b.priority)b.next=c,a.g=b;else{do{var d=c.next;if(!d||d.priority<=b.priority){b.next=d;c.next=b;break}c=d}while(c)}}a.a|=ue;a.l(w.INT+b.message,"setIRQ(vector=%o,priority=%d)\n",b.qb,b.priority+")")}}function Te(a){var b=[];for(a=a.g;a;)b.push(a.qb),a=a.next;return b}
function pe(a){return a.R=a.R&(fe|ee|de|Xe|Ye)|(a.ca&32768?me:0)|(a.fa&65535?0:oe)|(a.ea&32768?ne:0)|(a.Z&65536?je:0)}function qe(a,b){b&=a.Pc;a.ca=b<<12;a.fa=~b&4;a.ea=b<<14;a.Z=b<<16;if((b^a.R)&a.Vb)for(var c=a.T.length;0<=--c;){var d=a.b[c];a.b[c]=a.T[c];a.T[c]=d}a.c=b>>Ze&$e;c=a.R>>Ze&$e;a.c!=c&&(a.ra[c]=a.b[6],a.b[6]=a.ra[a.c]);a.R=b;a.a&=~af;a.a|=a.g?af:ue}l.Ld=function(a,b){3>=b&&(this.o.ma|=bf);cf(this,df,0,a)};
function cf(a,b,c,d){a.l(w.Fc,"trap to vector %o (%o: %s)\n",b,d,0>d?ef[-d]:"BUS ERROR");if(!a.ia){0>a.j?a.j=pe(a):a.c||(d=ff);d==ff&&(a.a&gf&&(d=hf),a.a|=gf,a.ma|=jf,a.b[6]=b=4);if(d!=hf){a.h=b|4143316992;a.c=0;var e=a.Bb(b|a.Va),f=a.Bb(b+2&65535|a.Va);qe(a,f&~ee|a.j>>2&ee);kf(a,a.j);kf(a,a.b[7]);a.b[lf]=e&65535}a.a&=~(c|mf|nf);a.a=a.a|ue|of;a.j=-1;a.Db=d;a.Eb=b;d==hf&&Dc(a.time);if(d>=ff)throw b;}}function pf(a,b){var c=b>>13&31;31>c&&(b=a.m&Me?a.La[c]+(b&8191)&Ne:b&~qf);return b}
function rf(a,b,c){if(!(c&a.N)){var d=b&65535;d>=Se&&(d|=a.v);return d}var e=b>>13;a.m&a.Oc[a.c]||(e&=7);var f=a.Na[a.c][e];d=(a.xa[a.c][e]<<6)+(b&8191)&a.u;d>=qf&&(d=pf(a,d));if(a.ia)return d;d>=a.we&&d<a.v?(a.ma|=sf,cf(a,df,0,d)):d&1&&!(c&tf)&&(a.ma|=uf,cf(a,df,0,d));var g=0;switch(f&vf){case wf:g=xf;case yf:f|=zf;c&Je&&(g=Af);break;case Bf:g=xf;case Cf:c&Je&&(g=xf);case Df:f|=c&Je?zf|Ef:zf;break;default:g=Ff}(f&(Gf|Hf))!=Gf&&(f&Hf?f&Gf&&(b&8128)<(f>>2&8128)&&(g|=If):(b&8128)>(f>>2&8128)&&(g|=If));
a.Na[a.c][e]=f;if(d!=((Qe|Jf)&a.u)||a.c)a.I=a.c,a.K=e;g&&(g&Be&&(0<=a.j&&(g|=Kf),a.f&Be||(g|=a.f&xf|a.I<<5|a.K<<1,we(a,a.f&~Lf|g&Lf)),cf(a,Mf,Nf,Of)),a.f&(Be|xf)||!(d<((Qe|Pf)&a.u)||d>((Qe|Qf|1)&a.u))||(a.f|=xf,a.f&Rf&&(a.a|=Nf)));return d}function kf(a,b){var c=a.b[6]-2&65535;a.b[6]=c;a.h=a.h&65535|(a.h&-65536)<<8|16121856;a.a&gf||a.Nc(Sf,-2,c);a.Xc(c,b)}l.ke=function(a,b,c){!this.c&&0>=b&&c<=this.H&&(this.a|=Tf)};
l.le=function(a,b,c){this.c||(65534<=c&&(c|=-65536),a&Je&&c<=this.H&&(c<=this.H-32?cf(this,df,0,ff):(this.ma|=Uf,this.a|=Tf)))};l.Qe=function(a){return this.i.ha(this.J=a)};l.Re=function(a){return this.i.ha(this.J=rf(this,a,Vf))};l.nf=function(a,b){this.i.ba(this.J=a,b)};l.pf=function(a,b){this.i.ba(this.J=rf(this,a,Sf),b)};
l.toString=function(){var a="";if(this.W)for(var b="R0 R1 R2 R3 R4 R5  SP PC PS PI SL NF ZF VF CF  M0 M1 M2 M3 ER  SR AR DR".split(" "),c=0;c<b.length;c++){var d=b[c];if(d){var e=16;"F"==d[1]&&(e=1);var f=Ab(this,d);void 0!=f&&(a+=this.W.w("%s=%*n ",d,e,f))}else a+="\n"}return a};
var be=1120,ge=1140,ae=1170,$e=3,je=1,ne=2,oe=4,me=8,Ye=16,Xe=224,ce=1792,de=2048,ee=12288,fe=49152,Ze=14,re=65024,te=34,se=9,df=4,Mf=168,hf=-1,Of=-2,ff=-4,ef="UNKNOWN PANIC ABORT ILLEGAL RED YELLOW FAULT TRACE HALT OPCODE INTERRUPT".split(" "),ue=1,af=2,nf=3,mf=16,Tf=32,Nf=64,of=128,gf=256,lf=7,tf=1,Ke=2,Je=4,Pe=65536,jf=4,Uf=8,bf=16,sf=32,uf=64,He=1,De=30,Ee=96,Kf=128,Ie=256,Rf=512,Ce=3072,xf=4096,Af=8192,If=16384,Ff=32768,Be=57344,Lf=61694,Ge=1,Fe=5,Le=16,Me=32,wf=1,yf=2,Bf=4,Cf=5,Df=6,vf=7,Hf=
8,Ef=64,zf=128,Gf=32512,Pf=62592,Jf=65402,Qf=65470,Ve={48:"DL11R",52:"DL11X",56:"PC11R",60:"PC11X",64:"KW11",112:"RL11",144:"RK11",180:"RX11"},Vf=0|Ke,Sf=0|Je,Se=57344,Re=253952,Qe=4186112,Oe=262143,qf=3932160,Ne=4194303;y.PDP11=$d;function Wf(a,b,c){kd.call(this,a,b,c);this.qa=Xf;this.J=[];this.o.L<ge&&(this.J=this.J.concat(Yf));1145>this.o.L&&(this.J=this.J.concat(Zf));this.ea=6}n(Wf,kd);
Wf.prototype.Rb=function(a,b,c){function d(C){var B=h.o,D=[];if(B.N){var Q=B.c<<1,M=C>>13;7<M&&(Q|=1);B.m&B.Oc[B.c]||(M&=7);var ke=C&8191,le=B.xa[B.c][M]<<6;C=le+ke&B.u;C>=qf&&(C=pf(B,C));D.push(C);D.push(ke);D.push(Q);D.push(M&7);D.push(le);D.push(B.u)}else C&=65535,C>=Se&&(C|=B.v),D.push(C);return null}function e(C){return $f[C]||"?"}function f(C,B){var D="",Q=B&ag;if(Q==U)D=a.O+((C&255)<<24>>23)&65535,D=k(D);else if(Q==bg)D=a.O-((C&63)<<1)&65535,D=k(D);else if(Q==cg)D=z(h,C&7,0,3,"");else if(Q==
dg)D=z(h,C&63,0,6,"");else if(Q==eg)D=z(h,C&255,0,8,"");else if(C&=B,B&V&&(C>>=6,B>>=6),B&X){Q=null;var M=C&7;switch(C&56){case 0:D=e(M);break;case 8:D="@"+e(M);Q=d(h.o.b[M]);break;case 16:7>M?D="("+e(M)+")+":(B=g(),D="#"+k(B));break;case 24:7>M?D="@("+e(M)+")+":(B=g(),D="@#"+k(B),Q=d(B));break;case 32:D="-("+e(M)+")";break;case 40:D="@-("+e(M)+")";break;case 48:B=g();D=k(B)+"("+e(M)+")";7==M&&(D=k(B=B+a.O&65535),Q=d(B));break;case 56:B=g(),D="@"+k(B)+"("+e(M)+")",7==M&&(D="@"+k(B=B+a.O&65535),C=
h.o,C.ia++,B=C.i.ha(rf(C,B,Vf)),C.ia--,Q=d(B))}Q&&(D=[D,Q])}return D}function g(){var C=b.shift()|b.shift()<<8;m+=k(C)+" ";rd(h,a,2);return C}function k(C){return z(h,C,0,16,"")}var h=this,p=Nd(this,a),m="",u=qd(this,a,Yd.vc),q=qd(this,a,Yd.hc),r=g(),x;for(A in this.qa)if(x=this.qa[A][r&A])break;x||(x=fg);var v=x[0];0<=this.J.indexOf(v)&&(x=fg,v=x[0]);var A=gg[v];var t="",Ea=x.length-1;v||Ea||(t=k(r));for(v=1;v<=Ea;v++){var W=x[v];if(void 0!=W){W=f(r,W);if(!W||!W.length){t="INVALID";break}"string"!=
typeof W&&(W=W[0]);0<t.length&&(t+=",");t+=W||"???"}}p=this.w("%s %-21s %-7s %s",p,m,A,t);c?q&&(c+=" "+q):q&&(c=q);c&&(p=this.w("%-32s; %s",p,c));u&&(p=u+":\n"+p);return p+"\n"};
var gg=".WORD ADC ADCB ADD ASL ASLB ASR ASRB BCC BCS BEQ BGE BGT BHI BIC BICB BIS BISB BIT BITB BLE BLOS BLT BMI BNE BPL BPT BR BVC BVS CCC CLC CLCN CLCV CLCVN CLCVZ CLCZ CLCZN CLN CLR CLRB CLV CLVN CLVZ CLVZN CLZ CLZN CMP CMPB COM COMB DEC DECB INC INCB HALT JMP JSR MARK MFPD MFPI MFPS MOV MOVB MTPD MTPI MTPS NEG NEGB NOP RESET ROL ROLB ROR RORB RTI RTS SBC SBCB SCC SEC SECN SECV SECVN SECVZ SECZ SECZN SEN SEV SEVN SEVZ SEVZN SEZ SEZN SUB SWAB SXT TST TSTB WAIT MUL DIV ASH ASHC XOR SOB EMT TRAP SPL IOT RTT MFPT".split(" "),$f=
"R0 R1 R2 R3 R4 R5 SP PC A0 A1 A2 A3 A4 A5 A6 A7 S0 S1 S2 S3 PS PI ER SL M0 M1 M2 M3 AR DR SR".split(" "),X=63,V=4032,U=4096,bg=8192,cg=12288,dg=24576,eg=32768,ag=61440,Xf={61440:{4096:[62,V,X],8192:[47,V,X],12288:[18,V,X],16384:[14,V,X],20480:[16,V,X],24576:[3,V,X],36864:[63,V,X],40960:[48,V,X],45056:[19,V,X],49152:[15,V,X],53248:[17,V,X],57344:[94,V,X]},65024:{2048:[57,448,X],28672:[100,X,448],29184:[101,X,448],29696:[102,X,448],30208:[103,X,448],30720:[104,448,X],32256:[105,448,bg]},65280:{256:[27,
U],512:[24,U],768:[10,U],1024:[11,U],1280:[22,U],1536:[12,U],1792:[20,U],32768:[25,U],33024:[23,U],33280:[13,U],33536:[21,U],33792:[28,U],34048:[29,U],34304:[8,U],34560:[9,U],34816:[106,eg],35072:[107,eg]},65472:{64:[56,X],192:[95,X],2560:[39,X],2624:[49,X],2688:[53,X],2752:[51,X],2816:[67,X],2880:[1,X],2944:[77,X],3008:[97,X],3072:[73,X],3136:[71,X],3200:[6,X],3264:[4,X],3328:[58,dg],3392:[60,X],3456:[65,X],3520:[96,X],35328:[40,X],35392:[50,X],35456:[54,X],35520:[52,X],35584:[68,X],35648:[2,X],
35712:[78,X],35776:[98,X],35840:[74,X],35904:[72,X],35968:[7,X],36032:[5,X],36096:[66,X],36160:[59,X],36224:[64,X],36288:[61,X]},65528:{128:[76,7],152:[108,cg]},65535:{0:[55],1:[99],2:[75],3:[26],4:[109],5:[70],6:[110],7:[111],160:[69],161:[31],162:[41],163:[33],164:[45],165:[36],166:[43],167:[35],168:[38],169:[32],170:[42],171:[34],172:[46],173:[37],174:[44],175:[30],176:[69],177:[80],178:[88],179:[82],180:[92],181:[85],182:[90],183:[84],184:[87],185:[81],186:[89],187:[83],188:[93],189:[86],190:[91],
191:[79]}},fg=[0],Yf=[58,60,65,96,110,100,101,102,103,104,105],Zf=[108,59,64];y.PDP11Dbg=Wf;function hg(a,b,c){bd.call(this,a,b,c);for(var d in ig){var e=ig[d];d=+d;a=e[0];b=e[1];c=e[2];e=e[3];65472<=d&&65487>=d&&(!a&&c&&(a=function(f){return function(g){return f(g)&255}}(c)),!b&&e&&(b=function(f){return function(g,k){return f(g,k)}}(e)));cd(this,this,d,d,a,b,c,e)}this.la()}n(hg,bd);l=hg.prototype;l.ka=function(){void 0===this.o&&(this.o=N(this,"Debugger"))};
l.sa=function(a){return a&&(a=a.shift(),this.M==a)?!0:!1};l.ta=function(a){a.push(this.M)};l.Ne=function(a){a=a>>1&63;var b=this.o.La[a>>1];return a&1?b>>16:b&65535};l.kf=function(a,b){a=a>>1&63;var c=a>>1;this.o.La[c]=a&1?this.o.La[c]&65535|(b&63)<<16:this.o.La[c]&-65536|b&65534};var jg={},ig=(jg[61568]=[null,null,hg.prototype.Ne,hg.prototype.kf,"UNIMAP",64,ae],jg);y.IOPage=hg;w.md=4294967296;I.dl11=w.md;
function Y(a,b,c){K.call(this,a,b,c);this.I=+this.s.baudReceive||9600;this.K=+this.s.baudTransmit||9600;this.time=N(this,"Time");this.L=Nb(this.time,this.M+".receive",this.$c.bind(this));this.N=Nb(this.time,this.M+".transmit",this.Ze.bind(this));this.ports=N(this,"IOPage");dd(this.ports,this,kg);this.f="";this.c=this.g=this.j=null;this.exports={connect:this.ye,receiveData:this.$c,receiveStatus:this.Ue,setConnection:this.We};this.la()}n(Y,K);l=Y.prototype;
l.ye=function(a){if(!this.c){var b=zb(this,"connection");if(b){var c=b.split("->");if(2==c.length){var d=c[0].trim();if(d!=this.M)return;c=c[1].trim();if(this.c=vb(this,c)){var e=this.c.exports;if(e){var f=e.connect;f&&f.call(this.c,this.u);if(this.g=e.receiveData){this.u=a;this.j=e.receiveStatus;this.l("Connected %s.%s to %s\n",this.U,d,c);return}}}}this.l("Unable to establish connection: %s\n",b)}}};
l.sa=function(a){var b=a.shift();return this.M==b?(this.h=a.shift(),this.a=a.shift(),this.b=a.shift(),this.m=a.shift(),!0):!1};l.ta=function(a){a.push(this.M);a.push(this.h);a.push(this.a);a.push(this.b);a.push(this.m)};l.ka=function(){this.o||(this.o=N(this,"CPU"),this.H=Ue(this.o,this.J?-1:48,w.Wa),this.i=Ue(this.o,this.J?-1:52,w.Wa))};l.la=function(){this.h=0;this.a=8192;this.b=128;this.m=[]};
l.$c=function(a){null!=a&&(this.f="number"!=typeof a?a:this.f+String.fromCharCode(a));this.f&&(a=this.f.charCodeAt(0),this.l(w.Wa,"receiveByte(%#04x)\n",a),this.v?a=!1:(this.h=a,this.a&128?this.h|=49152:this.a|=128,this.a&64&&We(this.o,this.H),a=!0),a&&(this.f=this.f.substr(1)),this.f&&Sb(this.time,this.L,1E3/Math.round(this.I/10)));return!0};l.Ue=function(a){var b=this.a;this.a&=-12289;a&wa.jc.pa&&(this.a|=8192);a&wa.ec.pa&&(this.a|=4096);b!=this.a&&(this.a|=32768,this.a&32&&We(this.o,this.H))};
l.We=function(a,b){return this.c?!1:(this.c=a,this.g=b,!0)};l.Ze=function(a){var b=!0;this.b|=128;this.b&64&&We(this.o,this.i);a&&(b=this.g?this.g.call(this.c,a):!1);return b};l.Me=function(){var a=this.a&65534;this.a&=-32769;return a};l.jf=function(a){var b=a^this.a;this.a=this.a&-112|a&111;this.j&&b&6&&(b=0,this.u?(b|=a&4?wa.jc.pa:0,b|=a&2?wa.od.pa|wa.ec.pa:0):(b|=a&4?wa.Qd.pa:0,b|=a&2?wa.pd.pa:0),this.j.call(this.c,b))};l.Le=function(){this.a&=-129;return this.h};l.hf=function(){};l.Te=function(){return this.b};
l.rf=function(a){if(this.b&128)if(a&64)We(this.o,this.i);else{var b=this.o,c=this.i;if(c){var d=b.g;if(d==c)b.g=c.next;else for(;d;){var e=d.next;if(e==c){d.next=e.next;break}d=e}b.g&&(b.a|=ue);b.l(w.INT+c.message,"clearIRQ(vector=%o,priority=%d)\n",c.qb,c.priority+")")}}this.b=this.b&-70|a&69};l.Se=function(){return 0};
l.qf=function(a){a:{a&=255;this.l(w.Wa,"transmitByte(%#04x)\n",a);if(this.R){if(19==a){this.v=!0;break a}if(17==a){this.v=!1;break a}}this.g&&this.g.call(this.c,a);Sb(this.o,this.N,1E3/Math.round(this.K/10))}this.b&=-129};var lg={},kg=(lg[65392]=[null,null,Y.prototype.Me,Y.prototype.jf,"RCSR"],lg[65394]=[null,null,Y.prototype.Le,Y.prototype.hf,"RBUF"],lg[65396]=[null,null,Y.prototype.Te,Y.prototype.rf,"XCSR"],lg[65398]=[null,null,Y.prototype.Se,Y.prototype.qf,"XBUF"],lg);y.DL11=Y;w.ya=8589934592;
I.pc11=w.ya;
function Z(a,b,c){K.call(this,a,b,c);this.name=this.s.name||"PTR";this.b=zb(this,"autoLoad")||"";this.K=+this.s.baudReceive||3600;this.c=this.s.library||[];this.j=null;this.H=window&&"FileReader"in window;this.u=N(this,"Bus");this.time=N(this,"Time");this.L=Nb(this.time,this.M+".reader",this.fe.bind(this));N(this,"Input");this.m=null;this.h=this.a=0;this.v=32768;this.f=this.I=0;this.i=[];this.g=mg;this.J=-1;this.ports=N(this,"IOPage");dd(this.ports,this,ng);Za(this,this.c,this.Ce.bind(this))||Cb(this,
!1)}n(Z,K);l=Z.prototype;
l.Ia=function(a,b){var c=this,d=mg;switch(a){case "readTape":d=og;case "loadTape":d||(d=pg);b.onclick=function(){var e=c.Y[qg];e&&(e=c.c[e.selectedIndex])&&rg(c,e,d)};break;case "mountTape":if(!this.H){this.l("Local tape support not available\n");b.parentNode.removeChild(b);break}b.addEventListener("change",function(){var e=b.children[0];e.children[1].disabled=!e.children[0].files.length});b.onsubmit=function(e){(e=e.currentTarget[1].files[0])&&rg(c,{name:Fa(e.name,!0),path:e.name},pg,e);return!1};
break;default:K.prototype.Ia.call(this,a,b)}};l.Ae=function(){var a=this.Y[sg],b=this.Y[qg],c=b.options[b.selectedIndex];if(a&&c){b={};if(c=c.getAttribute("data-value"))try{b=eval("("+c+")")}catch(d){this.l("PC11 option error: %s",d.message)}c=b.desc;void 0===c&&(c="");b=b.href;void 0!==b&&(c='<a href="'+b+'" target="_blank">'+c+"</a>");a.innerHTML=c}};l.sa=function(a){a=a.shift();return this.M==a?!0:!1};l.ta=function(a){a.push(this.M)};
l.ka=function(){this.o||(this.o=N(this,"CPU"),this.m=Ue(this.o,56,w.ya))};l.la=function(){this.a&=-2241;this.h=0};
function rg(a,b,c,d){var e=b.name,f=b.path;a.l(w.ya,'load("%s","%s")\n',e,f);if(!f)return tg(a),!0;if(f==ug)return Sa(a,'Use "Choose File" and "Mount" to select and load a local tape.'),!0;if(f==vg){f=window.prompt("Enter the URL of a remote tape image.","")||"";if(!f)return!1;e=Fa(f);a.l('Attempting to load %s as "%s"',f,e)}a.g=c;if(d){var g=new FileReader;g.onload=function(){var k=g.result;k&&(b.values=new Uint8Array(k,0,k.byteLength),a.Mb(b));wg(a)};g.readAsArrayBuffer(d);return!1}if(!b.values&&
!Za(a,b.path,a.Mb.bind(a)))return!1;a.Mb(b);return!0}function wg(a){if(a.j){var b=a.Y[qg];if(b&&b.options){var c;for(c=0;c<b.options.length;c++)if(b.options[c].value==a.j.path){b.selectedIndex!=c&&(b.selectedIndex=c);break}c==b.options.length&&(b.selectedIndex=0)}}}function xg(a,b){b|=0;if(b!==a.J){var c=a.Y[yg];c&&(c=(c=c.getElementsByClassName(zg))&&c[0])&&c.style&&(c.style.width=b+"%");a.J=b}}
l.Ce=function(a){a=this.c=a||[];var b=this.Ae.bind(this),c=qg,d=this.Y[c];if(d){for(var e=0;e<a.length;e++)Tb(this,c,a[e].name,a[e].path);b&&(d.onchange=b)}Tb(this,qg,"None",Ag,!0);this.H&&Tb(this,qg,"Local Tape",ug);Tb(this,qg,"Remote Tape",vg);Cb(this,!0);if(this.b&&"string"==typeof this.b){for(a=0;a<this.c.length;a++)if(b=this.c[a],"object"==typeof b&&b.name==this.b){this.b=b;break}a==this.c.length&&(Sa(this,"Unable to find %s media: %s",this.M),this.b="")}this.b?rg(this,this.b,pg)||Cb(this,!1):
wg(this)};
l.Mb=function(a){var b=a.name,c=a.values,d=a.addrLoad,e=a.addrExec;this.j=a;Cb(this,!0);if(this.g==og){var f=e,g=a=!1;e=!1;if(null==d)for(var k=0;k<c.length-1;){var h=c[k]&255|(c[k+1]&255)<<8;if(h)if(h&255){var p=k;if(1!=h){this.l(w.ya,"invalid signature (%#06x) at offset %#06x\n",h,p);break}if(k+6>=c.length){this.l(w.ya,"invalid block at offset %#06x\n",p);break}k+=2;var m=c[k++]&255|(c[k++]&255)<<8,u=c[k++]&255|(c[k++]&255)<<8;h+=(m&255)+(m>>8)+(u&255)+(u>>8);for(var q=k,r=m-=6;0<m&&k<c.length;)h+=
c[k++]&255,m--;if(0!=m||k>=c.length){this.l(w.ya,"insufficient data for block at offset %#06x\n",p);break}h+=c[k++]&255;if(h&255){this.l(w.ya,"invalid checksum (%#04x) for block at offset %#06x\n",h,p);break}if(r)for(this.l(w.ya,"loading %#06x bytes at %#06x-%#06x\n",r,u,u+r);r--;)this.u.bb(u++,c[q++]&255);else u&1?g=!0:null==f&&(f=u),null!=f&&this.l(w.ya,"starting address: %#06x\n",f);e=!0}else k++;else k+=2}if(!e&&(null==d&&(d=null),null!=d)){for(e=0;e<c.length;e++)this.u.bb(d+e,c[e]);e=!0}if(e){if(null==
f||g)Dc(this.time),a=!1;if(null!=f&&(c=this.o,d=f,c.X=d,c.b[lf]=d&65535,qe(c,0),ie(c),a)){c.b[0]=0;for(a=1;5>=a;a++)c.b[a]=0;c.b[6]=1024}}e?this.l('Read tape "%s"',b):Sa(this,'No valid memory address for tape "%s"',b)}else this.f=0,this.i=c,this.a&=-32769,this.l('Loaded tape "%s" (%d bytes)',b,c.length),xg(this,0)};function tg(a){a.j=null;a.g&&a.l(a.g==pg?"tape detached":"tape unloaded");a.g=mg;wg(a)}
l.fe=function(){1!=(this.a&32769)||this.a&128||(this.f<this.i.length?(this.h=this.i[this.f]&255,this.l(w.ya,"%s.advanceReader(%d): %#02x\n",this.M,this.f,this.h),this.f++,xg(this,this.f/this.i.length*100)):this.a|=32768,this.a|=128,this.a&=-2049,this.a&64&&We(this.o,this.m))};l.Ke=function(){return this.a&65534};l.gf=function(a){a&1&&(this.a&32768?(a&=-2,this.a&64&&We(this.o,this.m)):(this.a&=-129,this.a|=2048,this.h=0,Sb(this.time,this.L,1E3/Math.round(this.K/10))));this.a=this.a&-66|a&65};
l.Je=function(){this.a&=-129;this.a|=2048;return this.h};l.ff=function(){};l.Ie=function(){return this.v};l.ef=function(a){this.v=this.v&-65|a&64};l.He=function(){return this.I};l.df=function(a){this.I=a&255};
var Ag="",ug="?",vg="??",mg=0,pg=1,og=2,qg="listTapes",sg="descTape",yg="readProgress",zg="progressBar",Bg={},ng=(Bg[65384]=[null,null,Z.prototype.Ke,Z.prototype.gf,"PRS"],Bg[65386]=[null,null,Z.prototype.Je,Z.prototype.ff,"PRB"],Bg[65388]=[null,null,Z.prototype.Ie,Z.prototype.ef,"PPS"],Bg[65390]=[null,null,Z.prototype.He,Z.prototype.df,"PPB"],Bg);y.PC11=Z;
function Cg(a,b,c){K.call(this,a,a);var d=this;this.c=!1;this.i=c;this.b="";this.h=this.g=!1;Cb(this,!1);this.ja=w.ld;b=b.trim();"{"==b[0]?Dg(this,b):(this.b=b,$a(this.b,function(e,f,g,k){4==g&&(!k&&f?(Dg(d,f),Eg(d)):d.l("error (%d) loading configuration: %s\n",k,e))}));window.addEventListener("load",function(){d.h=!0;Eg(d)});window.addEventListener(db("iOS")?"pagehide":db("Opera")?"unload":"beforeunload",function(){Fg(d)});window.addEventListener("pageshow",function(){d.c||d.ka(!0)})}n(Cg,K);
Cg.prototype.Ia=function(a,b){var c=this;switch(a){case Gg:b.onclick=function(){c.ka()};break;case Hg:b.onclick=function(){c.la()}}K.prototype.Ia.call(this,a,b)};
function Eg(a){var b=!0;if(a.g&&a.h){for(var c in a.a){var d=void 0,e=a.a[c];try{d=e["class"],y[d]?"Machine"==d?(a.l("PCjs %s v%3.2f\n%s\n",e.name,3,Ig),a.b&&a.l("Configuration: %s\n",a.b)):new y[d](a.U,c,e):a.l('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.l('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),Eb(a,c)}}if(a.f){var f=eb(a);yb(a,function(g){return g.Lb&&!g.Lb(f)?(g.l('unable to restore state for device "%s"\n',g.M),!1):!0})}Cb(a,!0);Db(a,a.ka.bind(a,b))||a.l("machine %s not ready to power, waiting for device(s)\n",
a.U)}}function Dg(a,b){try{a.a=JSON.parse(b);var c=a.a[a.U];if(!c){c=a.a[Fa(a.b,!0)];if(!c)throw Error("configuration missing machine ID");a.a[a.U]=c}wb(a,c,["autoSave","autoStart"]);a.f=!1!==a.s.autoSave;a.j=!1!==a.s.autoStart;if(a.i){var d=eval("("+a.i+")"),e;for(e in d)a.s[e]=d[e]}a.g=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),F(a,"machine '"+a.U+"' initialization error: "+c)}}
Cg.prototype.ka=function(a){a=void 0===a?!this.c:a;if(Bb(this)){var b=this;a&&F(this,"power on");yb(this,function(c){c.ka&&c!=b&&("CPU"!=c.s["class"]||b.j||Bb(b)?c.ka(a):c.time.update(!0));return!0});(this.c=a)||F(this,"power off")}};Cg.prototype.la=function(){if(Bb(this)){var a=this;yb(this,function(b){b.la&&b!=a&&b.la();return!0});F(this,"reset")}};function Fg(a){if(a.f){var b=[];yb(a,function(c){c.ab&&c.ab(b);return!0});lb(a,b)}a.ka(!1)}var Gg="power",Hg="reset",Ig="Copyright \u00a9 2012-2020 Jeff Parsons <Jeff@pcjs.org>";
window.PDP11v3=function(a,b,c){var d=new Cg(a,b,c);window.command=function(e){return fb(d,e)};return d};y.Machine=Cg;})()

//# sourceMappingURL=pdp11v3.js.map
