(function(){/*
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/dl11.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/pc11.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/defines.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/message.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdlib.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdio.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/webio.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/device.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/input.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/led.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/time.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/bus.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/memory.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/ports.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/ram.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/rom.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/cpu.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/debugger.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/pdp11ops.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/pdp11.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/pdp11dbg.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/iopage.js (C) 2012-2026 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/machine.js (C) 2012-2026 Jeff Parsons
*/
var l,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this),ea="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");da.BigInt64Array&&(ea.push("BigInt64"),ea.push("BigUint64"));
function fa(a,b){if(b)for(var c=0;c<ea.length;c++)ha(ea[c]+"Array.prototype."+a,b)}function t(a,b){b&&ha(a,b)}function ha(a,b){var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}var ia;
if(typeof Object.setPrototypeOf=="function")ia=Object.setPrototypeOf;else{var ja;a:{var ka={a:!0},la={};try{la.__proto__=ka;ja=la.a;break a}catch(a){}ja=!1}ia=ja?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ma=ia;
function w(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ma)ma(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Cg=b.prototype}function na(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function oa(a){if(!(a instanceof Array)){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)a=b.call(a);else if(typeof a.length=="number")a={next:na(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function pa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
t("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
t("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});t("String.prototype.repeat",function(a){return a?a:function(b){if(this==null)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(b<0||b>1342177279)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
t("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});t("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});t("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
t("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.H=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.H};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return qa(na(this))}});return a});function qa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}function ra(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}
t("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}});t("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;c<0&&(c=Math.max(0,e+c));if(d==null||d>e)d=e;d=Number(d);d<0&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});fa("fill",function(a){return a?a:Array.prototype.fill});t("Number.parseInt",function(a){return a||parseInt});
t("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}});function sa(){this.R=""}var ta,ua=new ArrayBuffer(2);(new DataView(ua)).setUint16(0,256,!0);ta=(new Uint16Array(ua))[0]===256;
var va={Bd:{Wa:4,wa:16},ac:{Wa:5,wa:32},dd:{Wa:6,wa:64},Wb:{Wa:8,wa:256},ed:{Wa:20,wa:1048576},lg:{Wa:22,wa:4194304}},wa={og:typeof window!="undefined",node:typeof window!="undefined"?{}:global,process:typeof process!="undefined"?process:{},window:typeof window!="undefined"?window:global,document:typeof document!="undefined"?document:{},ob:{machines:{},components:[],commands:{},files:null}};wa.window.PCjs?wa.ob=wa.window.PCjs:wa.window.PCjs=wa.ob;
var xa=wa.process,x=wa.ob.machines,ya=wa.ob.components,E={};E.Defines=sa;var za={all:0xffffffffffff,addr:1,bus:2,fault:4,memory:8,ports:16,chips:32,kbd:64,serial:128,misc:256,cpu:512,mmu:2048,"int":1024,trap:4096,video:8192,monitor:16384,screen:32768,disk:131072,file:65536,time:262144,timer:524288,event:1048576,input:2097152,key:4194304,mouse:8388608,touch:16777216,info:274877906944,warn:549755813888,error:1099511627776,halt:70368744177664,buffer:0x800000000000};
function Aa(){this.H={};for(var a=0;a<23;a++)this.H["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}Aa.prototype.g=function(a,b){return this.H[a]?!1:(this.H[a]=b,!0)};
function Ba(){var a=pa.apply(0,arguments);if(a[0]===void 0)a=new Date(Date.now());else if(typeof a[0]==="string"){var b=a[0];b.indexOf(":")<0?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=a[1]===void 0?new Date(a[0]):new Date(Date.UTC.apply(Date,oa(a)));return a}
Aa.prototype.K=function(a){var b=pa.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(this.H[g]===void 0)c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];g!="%"&&e++}else h=b[b.length-1];var k=!1,n=d[f+1],m=n.indexOf("#")>=0,r=n.indexOf("0")>=0,p=d[f+2];p=="*"?(p=h,h=e<b.length?b[e++]:b[b.length-1]):p=+p||0;var q=d[f+3];q=q?+q.substr(1):-1;var v=d[f+4],
u=null,y=0,z="",C="ACDFGHMNSTWY".indexOf(g)>=0&&typeof h!="object"?Ba(h):h;switch(g){case "C":c+=isNaN(C.getTime())?void 0:this.K("%#W, %#F %#D, %#Y".replaceAll("#",m?"#":""),C);continue;case "D":h=m?C.getUTCDate():C.getDate();g="d";break;case "A":case "G":case "H":h=m?C.getUTCHours():C.getHours();g=="A"?(h=h<12?"am":"pm",g="s"):(g=="G"&&(h=h?h>12?h-12:h:12),g="d");break;case "F":case "M":h=m?C.getUTCMonth():C.getMonth();g=="F"?(h=Ca[h],g="s"):(h++,g="d");break;case "N":h=m?C.getUTCMinutes():C.getMinutes();
g="d";break;case "S":h=m?C.getUTCSeconds():C.getSeconds();g="d";break;case "T":c+=isNaN(C.getTime())?void 0:this.K("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",m?"#":""),C);continue;case "W":h=Da[m?C.getUTCDay():C.getDay()];g="s";break;case "Y":h=m?C.getUTCFullYear():C.getFullYear(),q>0&&(h%=Math.pow(10,q)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),q>=0&&(r=!0,p<q&&(p=q),q=-1);case "f":h=+h;g=h+"";q>=0&&(g=h.toFixed(q));g.length<p&&(r?(h<0&&(p--,g=g.substr(1)),
g=("0".repeat(p)+g).slice(-p),h<0&&(g="-"+g)):g=(" ".repeat(p)+g).slice(-p));c+=g;break;case "j":c+=JSON.stringify(h,null,p||void 0);break;case "c":h=typeof h=="string"?h[0]:String.fromCharCode(h);case "s":if(h!=void 0)for(typeof h!="string"&&(h=h.toString()),q>=0&&(h=h.substr(0,q));h.length<p;)h=n.indexOf("-")>=0?h+" ":" "+h;c+=h;break;case "B":y=2,m&&(z="0b");case "o":y||(y=8),!z&&m&&(z="0o");case "X":u=Ea;case "x":g="";y||(y=16);!z&&m&&(z="0x");u||(u=Fa);typeof h=="string"&&h[0]=="-"&&(k=!0,h=
h.slice(1));h=Math.trunc(h);k&&(h=-h);h<0&&((h|0)==h?h>>>=0:Math.abs(h)<=9007199254740992&&(h+=9007199254740992));q>=0&&(r=!0,p<q&&(p=q));r&&!p&&(v=="b"?p=2:v=="h"||v=="w"?p=4:v=="l"?p=8:(p=Math.abs(h),p=p<=255?2:p<=65535?4:p<=4294967295?8:9),p+=z.length);p-=z.length;do k=16,Number.isNaN(h)||(k=h&y-1,h=Math.trunc(h/y)),r||!g||k||h?g=u[k]+g:(z&&(g=z+g,z=""),p>0&&(g=" "+g));while(--p>0||h);c+=z+g;break;case "%":c+="%";break;default:c=this.H[g]?c+this.H[g](g,n,p,q,h):c+("(unimplemented sprintf type: %"+
g+")")}}}return c+=d[f]};var Da="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ca="January February March April May June July August September October November December".split(" "),Fa="0123456789abcdef?",Ea="0123456789ABCDEF?";function Ga(){sa.apply(this,arguments)}w(Ga,sa);
function Ha(a,b){if(a){b||(b=10);var c,d=a.indexOf(",")>0;d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);c=="#"?(b=8,c=""):c=="$"&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),c=="0b"&&d||c=="^B"?(b=2,c=""):c=="0o"||c=="^O"?(b=8,c=""):c=="^D"?(b=10,c=""):c=="0x"&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);c=="Y"||c=="y"?(b=2,c=""):c=="."?(b=10,c=""):c=="H"||c=="h"?(b=16,c=""):c=="K"?c="000":c=="M"?c="000000":c=="G"&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var f;e=0;b<=10&&(c=a.match(/(-?[0-9]+)B([0-9]*)$/))&&
(a=c[1],e=35-((c[2]||35)&255));if((b&&b!=10?b==16?a.match(/^-?[0-9a-f]+$/i)!==null:b==8?a.match(/^-?[0-7]+$/)!==null:b==2&&a.match(/^-?[01]+$/)!==null:a.match(/^[+-]?[0-9]+$/)!==null)&&!isNaN(f=parseInt(a,b))){e&&(f<0&&(f+=68719476736),f=e>0?f*Math.pow(2,e):Math.trunc(f/Math.pow(2,-e)));var g=f}}return g}
function F(a,b,c,d,e){d=d===void 0?0:d;var f=f===void 0?0:f;var g="",h="",k=-1;c||(c=a.ea||10);d&&(k=Math.ceil(d/Math.log2(c)));if(e==void 0)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:h=".";default:e=""}isNaN(b)||typeof b!="number"?(b=void 0,e=h=""):(b<0&&b>-1&&(b=-1),d&&(b<0&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(k=Math.ceil(Math.log(b)/Math.log(c)))));for(a=f||-1;k--;){a||(g=","+g,a=f);if(b==void 0){if(g="?"+g,k<0)break}else if(d=b%c,b=Math.trunc(b/c),d+=d>=0&&d<=9?48:55,g=String.fromCharCode(d)+
g,!b&&k<0)break;a--}return e+g+h}function Ia(a,b){var c=a/G|0,d=b/G|0;return(a&b)==(b|0)&&(c&d)==d}var G=4294967296;E.StdLib=Ga;function H(){Ga.call(this);this.format=new Aa;this.Gc=this.format.g.bind(this.format);this.K=this.format.K.bind(this.format)}w(H,Ga);H.prototype.flush=function(){var a=Ja;Ja="";this.Oa(a)};function Ka(a,b){var c=a,d=a.lastIndexOf("/");d>=0&&(c=a.substr(d+1));d=c.indexOf("&");d>0&&(c=c.substr(0,d));b&&(d=c.lastIndexOf("."),d>0&&(c=c.substring(0,d)));return c}
H.prototype.Oa=function(a,b){var c=a.length,d=a.lastIndexOf("\n");b?d>=0&&(b=Date.now(),La||(La=b),a=((b-La)/1E3).toFixed(3)+": "+a,c=a.length):this.R=="node"?(xa.Bg.write(a),a=""):(d>=0&&(console.log(Ja+a.slice(0,d)),Ja="",a=a.slice(d+1)),La=null);Ja+=a;return c};H.prototype.m=function(a){return this.Oa(this.K.apply(this,[a].concat(oa(pa.apply(1,arguments)))))};var Ja="",La=null;E.StdIO=H;
function Ma(a){H.call(this);this.ba={};this.ra=0;this.X=this;a&&(this.X.ra=0,this.X.Ha=[],this.X.Ca=0,this.X.hb={},this.X.ug=!1)}var Na;w(Ma,H);l=Ma.prototype;l.Ka=function(a,b){var c=this,d=this;this.ba[a]=b;switch(a){case Oa.ad:b.onclick=function(){var e=c.Ta(Oa.ib,!0);e&&(e.value="")};break;case Oa.ib:Pa(b),b.addEventListener("keydown",function(e){Qa(d,e,!0)}),b.addEventListener("keypress",function(e){Qa(d,e)})}};function Ra(a,b){var c=Sa.Yb;a.X.hb[c]||(a.X.hb[c]=[]);a.X.hb[c].push(b)}
function Ta(a,b,c){var d=!1;typeof b=="boolean"&&(d=b,b=c.shift());if(b=a.K.apply(a,[b].concat(oa(c))))a.m("%s\n",b),d||alert(b)}function Pa(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}
function Ua(a,b){if(window&&window.document&&typeof Blob=="function"&&typeof URL!="undefined"&&URL.createObjectURL){var c=window.document.createElement("a");if(typeof c.download=="string"){var d=URL.createObjectURL(new Blob([a],{type:"application/json"}));c.href=d;c.download=b;window.document.body.appendChild(c);c.click();window.document.body.removeChild(c);setTimeout(function(){URL.revokeObjectURL(d)},1E3);return!0}}return!1}l.error=function(a,b){Ta(this,"%s",this.K.apply(this,[a].concat(oa(b))))};
l.Ta=function(a){return this.ba[a]};function Va(a){var b=window;if(b){do{for(var c=0;c<Wa.length;c++){var d=Wa[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(a.indexOf("screen")<0)break;a=a.replace("screen","Screen")}while(1)}return null}function Xa(a,b){return a.config.bindings&&a.config.bindings[b]}function Ya(a){if(a=a.ba[Za])var b=a.textContent;return b}function $a(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function I(a,b,c,d){a=a.config[b];a===void 0?a=c:(d&&d[a]!==void 0&&(a=d[a]),d=typeof c,typeof a!=d&&(d=="boolean"?a=!!a:typeof c=="number"&&(a=+a)));return a}function ab(a,b,c){if(typeof b=="string")return bb(b,function(d,e,f,g){var h=!1;if(g){h=g<0;var k=d}else{if(f!=4)return;try{var n=JSON.parse(e)}catch(m){k=m.message||"unknown error"}}k&&Ta(a,h,"Unable to load %s media (error %d: %s)");c(n)}),!1;c(b);return!0}
function bb(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){e.readyState!==4?b(a,d,e.readyState,c):(d=e.responseText,e.status==200||!e.status&&d.length&&(window?window.location.protocol:"file:")=="file:"||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function cb(a){if(db.wb===void 0){var b=!1;if(window)try{window.localStorage.setItem(db.$a,db.$a),b=window.localStorage.getItem(db.$a)==db.$a,window.localStorage.removeItem(db.$a)}catch(c){a.m("%s\n",c.message),b=!1}db.wb=b}return!!db.wb}function eb(a,b){b=b===void 0?0:b;b>1&&b%2&&b--;b=b||a.ra;return(b|1)==-1||Ia(a.X.ra,b)?!0:!1}
function fb(a){if(window){var b=window.navigator.userAgent;return a=="iOS"&&(!!b.match(/(iPod|iPhone|iPad)/)||window.navigator.platform==="MacIntel"&&window.navigator.maxTouchPoints>1)||a=="MSIE"&&!!b.match(/(MSIE|Trident)/)||b.indexOf(a)>=0}return!1}function gb(a){var b=null;if(cb(a)){var c;if(window)try{(c=window.localStorage.getItem(a.Y))&&(b=JSON.parse(c))}catch(d){a.m("%s\n",d.message)}}return b}
function Qa(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.X,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==J.Ub&&f.selectionStart<=h+1&&(a=!0);d==J.Cc?(a=!0,e.Ca>0&&(g=e.Ha[--e.Ca])):d==J.cc&&(a=!0,e.Ca<e.Ha.length&&(g=e.Ha[++e.Ca]||""));a&&b.preventDefault();g!=void 0&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),d=="@"&&e.Ca>0&&c+1==g.length&&
(f.value+=e.Ha[--e.Ca],d="\r"),d=="\r"&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=hb(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&a.m("%s\n",b.replace(/\n$/,"")))}}function ib(a){return a=="true"||a=="on"?!0:a=="false"||a=="off"?!1:void 0}
function jb(a,b){if(b!=void 0){var c=a.X;try{if(b=b.trim())c.Ca<c.Ha.length&&b==c.Ha[c.Ca]?c.Ca++:(c.Ha.push(b),c.Ca=c.Ha.length);var d=b.split(" "),e=d[0],f=a.X.hb[Sa.Yb];switch(e[0]){case "m":if(e[1]=="?"){var g="";kb.forEach(function(r){g+=r+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var k=ib(e);k!=void 0&&d.pop();d.length<=1&&(k!=void 0&&(h=k,k=void 0),d[1]="all");d[1]=="all"&&(d=Object.keys(za));for(f=1;f<d.length;f++){e=d[f];var n=za[e];if(!n){g+=
"unrecognized message: "+e+"\n";break}k!=void 0&&lb(a,n,k);if(h==void 0||h==eb(a,n))g+=a.K("%8s: %b\n",e,eb(a,n))}eb(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",mb.forEach(function(r){g+=r+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var m=f[a](d);if(m!=void 0){g=g?g+m:m;break}}}}catch(r){g="error: "+r.message+"\n"}}return g}
function hb(a,b){b=b===void 0?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=jb(a,b[d])}return c}
l.Oa=function(a,b){b==void 0&&(b=eb(this,0x800000000000));if(!b){var c=this.Ta(Oa.ib,!0);if(c){b=c.selectionStart;for(var d=a.split(/([\n\r\b])/),e=0;e<d.length;e++){var f=d[e];if(f)if(f=="\b"||f=="\r")for(;b>0&&c.value.slice(b-1,b)!="\n"&&(b--,f!="\b"););else if(f=="\n"){for(f="";b<c.value.length&&(f=c.value[b],b++,f!="\n"););f!="\n"&&(c.value+="\r\n",b=c.value.length)}else c.value=c.value.slice(0,b)+f+c.value.slice(b+f.length),b+=f.length}c.focus();c.setSelectionRange(b,b);c.value.length>=8192&&
(c.value=c.value.slice(c.value.length-8192+4096));c.scrollTop=c.scrollHeight;return a.length}}return H.prototype.Oa.call(this,a,b)};l.m=function(a){var b=pa.apply(1,arguments),c=0;typeof a=="number"&&(c=a,a=b.shift());return eb(this,c)?(Ia(c,1099511627776)&&(a="error: "+a),Ia(c,549755813888)&&(a="warning: "+a),H.prototype.m.call.apply(H.prototype.m,[this,a].concat(oa(b)))):0};function nb(a,b,c){(a=a.ba[b])&&a.textContent!=c&&(a.textContent=c)}
function lb(a,b,c){var d=!1;c?(c=a.X.ra,a.X.ra=(c|b)+(c/G|0|b/G|0)*G):(d=Ia(a.X.ra,0x800000000000)&&Ia(b,0x800000000000),c=a.X.ra,a.X.ra=(c&~b)+((c/G|0)&~(b/G|0))*G);d&&a.flush()}
var Oa={ad:"clear",ib:"print"},mb=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],kb=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],Sa={Yb:"command"},ob={$b:13,ub:65,Tb:66,Vb:67,bc:68,E:69,dc:70,ec:71,fc:72,hc:73,jc:74,oc:75,qc:76,tc:77,uc:78,vc:79,wc:80,Q:81,xc:82,zc:83,Ac:84,Bc:85,Dc:86,Fc:87,Hc:88,
Jc:89,Db:90,a:97,b:98,c:99,d:100,e:101,f:102,sg:103,tg:104,vg:105,wg:106,k:107,xg:108,yg:109,n:110,zg:111,p:112,q:113,r:114,s:115,t:116,Dg:117,Eg:118,w:119,x:120,y:121,z:122},J={Ub:8,Id:9,sd:10,$b:13,Fd:16,bd:17,$c:18,cg:19,xb:20,cf:27,Hd:32,fg:33,eg:34,bf:35,zf:36,sc:37,Cc:38,Ab:39,wf:39,cc:40,tf:44,gg:44,Af:45,af:46,vf:46,yf:47,ZERO:48,ONE:49,Kd:50,Jd:51,nd:52,md:53,Gd:54,Ed:55,fd:56,td:57,ld:59,kd:61,ub:65,Tb:66,Vb:67,bc:68,E:69,dc:70,ec:71,fc:72,hc:73,jc:74,oc:75,qc:76,tc:77,uc:78,vc:79,wc:80,
Q:81,xc:82,zc:83,Ac:84,Bc:85,Dc:86,Fc:87,Hc:88,Jc:89,Db:90,Xb:91,uf:91,sf:92,jg:93,xf:93,Ef:96,Vf:96,rf:96,Ff:97,Tf:97,Gf:98,Sf:98,Hf:99,Yf:99,If:100,Wf:100,Jf:101,Pf:101,Kf:102,$f:102,Lf:103,Uf:103,Mf:104,bg:104,Nf:105,Zf:105,Xf:106,Of:107,ag:109,Qf:110,Rf:111,df:112,hf:113,jf:114,kf:115,lf:116,mf:117,nf:118,pf:119,qf:120,ef:121,ff:122,gf:123,ud:144,Cd:145,jd:173,Dd:186,gd:187,$e:188,cd:189,dg:190,mg:191,Ye:192,Bf:219,Ze:220,ig:221,hg:222,hd:224,Cf:901,Ec:1E3},pb={},qb=(pb[J.ld]=J.Dd,pb[J.kd]=J.gd,
pb[J.jd]=J.cd,pb[J.hd]=J.Xb,pb),rb={sc:1,Ab:2,Df:3},L={},sb=(L[J.Ub]="\b",L[J.Id]="\t",L[J.sd]="\n",L[J.$b]="\r",L[J.Hd]=" ",L[J.ZERO]="0",L[J.ONE]="1",L[J.Kd]="2",L[J.Jd]="3",L[J.nd]="4",L[J.md]="5",L[J.Gd]="6",L[J.Ed]="7",L[J.fd]="8",L[J.td]="9",L[J.ub]="A",L[J.Tb]="B",L[J.Vb]="C",L[J.bc]="D",L[J.E]="E",L[J.dc]="F",L[J.ec]="G",L[J.fc]="H",L[J.hc]="I",L[J.jc]="J",L[J.oc]="K",L[J.qc]="L",L[J.tc]="M",L[J.uc]="N",L[J.vc]="O",L[J.wc]="P",L[J.Q]="Q",L[J.xc]="R",L[J.zc]="S",L[J.Ac]="T",L[J.Bc]="U",L[J.Dc]=
"V",L[J.Fc]="W",L[J.Hc]="X",L[J.Jc]="Y",L[J.Db]="Z",L[J.sc]="Left",L[J.Ab]="Right",L[J.Cc]="Up",L[J.cc]="Down",L),Wa=["","moz","ms","webkit"],tb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},db={wb:void 0,$a:"PCjs.localStorage"};E.WebIO=Ma;
function M(a,b,c,d){a=a===void 0?"default":a;b=b===void 0?a:b;c=c===void 0?{}:c;d=d===void 0?[]:d;Ma.call(this,a==b);this.Y=a;this.R=b;x[this.Y]||(x[this.Y]={});x[this.Y][this.R]&&this.m("warning: machine configuration contains multiple '%s' devices\n",this.R);x[this.Y][this.R]=this;this.id=this.Y==this.R?this.Y:this.Y+"."+this.R;ya.push(this);this.X=ub(this,this.Y);this.ready=!0;vb(this,c,d);this.Ia={};this.Ic=[]}w(M,Ma);l=M.prototype;l.Eb=function(){};l.Fb=function(){};
function vb(a,b,c){c=b.overrides||c;if(c.length){var d,e=Na;if(!e){e={};if(window){d||(d=window.location.search.slice(1));for(var f,g=/\+/g,h=/([^&=]+)=?([^&]*)/g;f=h.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Na=e}d=e;for(var k in d)c.indexOf(k)>=0&&(e=d[k],f=Ha(e,10),f==void 0&&(e=="true"?f=!0:e=="false"?f=!1:(f=e,e='"'+e+'"')),b[k]=f,a.m("overriding %s property '%s' with %s\n",a.R,k,e))}a.config=b;c=b.bindings;c=c===void 0?{}:c;if(typeof document!=
"undefined"){a.config.ba||(a.config.ba=c);(k=Array.isArray(c))?c.indexOf("container")<0&&c.push("container"):c.container||(c.container=a.R);for(var n in c){e=c[n];if(k)n=e;else if(e.match(/^[0-9]+$/)){d=+e;a.ba[n]=[];do{e=n+d++;e=document.getElementById(e);if(!e)break;a.ba[n].push(e)}while(1);continue}(d=document.getElementById(e))&&a.Ka(n,d)}}b=b===void 0?{}:b;a.version=3;if(a.version){n="";var m;a.Y!=a.R&&(m=ub(a,a.Y).version)&&m!=a.version&&(n="Machine");n||(m=b.version)&&m>a.version&&(n="Config");
n&&(m=a.K("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.pg,a.version,n,m),a.error("%s\n\nClearing your browser's cache may resolve the issue.",m))}}function N(a,b,c,d){a.Ia[b]={get:c.bind(a),set:d?d.bind(a):null}}function wb(a,b,c){a.Ia[b]&&(a.Ia[c]=a.Ia[b])}function xb(a,b){var c;try{var d=x[a.Y];if(d)for(c in d){var e=d[c];if(e.R!=e.Y&&!b(e))return!1}return!0}catch(f){a.m("error while enumerating device '%s': %s\n",c,f.message)}return!1}
l.Ta=function(a,b){b=b===void 0?!1:b;if(a){var c=Ma.prototype.Ta.call(this,a,b);if(c===void 0&&b){b=x[this.Y];for(var d in b)if(c=b[d].ba[a])break;c||(c=null);this.ba[a]=c}}return c};function ub(a,b,c){var d=b,e=a.Y,f=e.indexOf(".");f>0&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=x[e])&&f[b]||null;if(!b){for(f=0;f<ya.length;f++)if(ya[f].id===d){b=ya[f];break}if(!b&&(c===void 0||c))throw Error(a.K('no "%s" device',d));}return b}
function P(a,b,c){var d=null,e=x[a.Y];if(e)for(var f in e)if(e[f].config["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(c===void 0||c))throw Error(a.K("no %s device",b));return d}function yb(a,b){var c=ub(a,a.Y);return c&&c.config&&c.config[b]||a.config[b]}function zb(a,b){return(a=a.Ia[b])&&a.get()}function Ab(a){return a==a.X&&a.ready?xb(a,function(b){return Ab(b)}):a.ready}function Bb(a,b){b=b===void 0?a.ready:b;a.ready=b;if(Ab(a)){for(;b=a.Ic.pop();)b();a!=a.X&&Bb(a.X)}}
function Cb(a,b){if(Ab(a))return b(),!0;a.Ic.push(b);return!1}l.Vc=function(){};l.m=function(a){var b=pa.apply(1,arguments);return typeof a=="number"&&eb(this,a)&&(this.aa===void 0&&(this.aa=P(this,"Debugger",!1)),this.aa&&this.aa.Vc(a),this.X.ra&1&&(this.H===void 0&&(this.H=P(this,"CPU")),this.H))?(a=b.shift(),Ma.prototype.m.call(this,"%#06x: %s.%s\n",this.H.Lb,this.R,this.K.apply(this,[a].concat(oa(b))).trim())):Ma.prototype.m.call.apply(Ma.prototype.m,[this,a].concat(oa(b)))};
function Db(a,b){(a=x[a.Y])&&delete a[b]}function Eb(a,b,c){(a=a.Ia[b])&&a.set&&a.set(c)}E.Device=M;
function Fb(a,b,c){M.call(this,a,b,c);this.ra=2097152;this.T=this.J=null;this.time=P(this,"Time");this.X=P(this,"Machine");this.$=I(this,"drag",!1);this.S=I(this,"scroll",!1);this.Z=I(this,"hexagonal",!1);this.l=I(this,"releaseDelay",0);this.o=!1;a=this.config.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];typeof g=="string"?g=[g]:g.length==void 0&&(e=g.grid,g=g.keys,typeof g=="string"&&(g=[g]));this.j[f]={keys:g,
grid:e,state:0}}}this.L=[];this.M=[];this.i=this.N=null;(a=this.ba[Gb])&&Hb(this,a,this.Ta(c.focusBinding,!0),this.config.location);this.ta()}w(Fb,M);function Ib(a,b){a.J=b}function Jb(a,b,c){for(var d=0;d<a.L.length;d++){var e=a.L[d];e.id===b&&e.kb(b,c)}}
function Hb(a,b,c,d){d=d===void 0?[]:d;if(d.length||a.h||a.j){var e={};e.We=d[0]||0;e.Xe=d[1]||0;e.bb=d[2]||b.clientWidth;e.jb=d[3]||b.clientHeight;e.lb=d[4]||1;e.rb=d[5]||1;e.Wd=d[6]||b.naturalWidth||e.bb;e.Yd=d[7]||b.naturalHeight||e.jb;e.Yc=d[8]||0;e.Zc=d[9]||0;e.Vd=d[10]||0;e.Xd=d[11]||0;a.h?(e.nb=a.h.length,e.cb=a.h[0].length):(e.cb=e.lb,e.nb=e.rb,e.lb=e.rb=0);e.Rc=e.bb/(e.cb+e.cb*e.lb)|0;e.Sc=e.jb/(e.nb+e.nb*e.rb)|0;e.Ud=e.Rc*e.lb|0;e.Tc=e.Sc*e.rb|0;e.gb=e.tb=-1;Kb(a,b,e);Lb(a,b,e);a.time&&
a.l&&(a.W=Mb(a.time,"timerInputRelease",function(){e.gb<0&&e.tb<0&&Nb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.l&&(a.ca=Mb(a.time,"timerKeyRelease",function(){Ob(a)})),a.u=0,a.I="",a.v=[],d=b,c&&(d=c,a.i||c.nodeName!="BUTTON"||(d=document,a.i=c,Pb(a,b),a.N=b)),Pb(a,d),a.i||(a.i=d)}function Qb(a){a.l?Rb(a.time,a.ca,a.l):Ob(a)}
function Sb(a,b,c,d,e){if(a=a.ba[b]){for(b=0;b<a.options.length&&a.options[b].text!=c;b++);void 0==a.options.length&&(b=document.createElement("option"),b.text=c,b.value=d,(e===void 0?0:e)&&a.childNodes[0]?a.insertBefore(b,a.childNodes[0]):a.appendChild(b))}}
function Pb(a,b){function c(e,f,g){var h=document.activeElement;a.m(5242880,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,g!=void 0?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.i&&e!=a.i&&e!=a.N?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Tb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=Tb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Tb(a,f,!1,e);c("Up",f);g&&e.preventDefault();b.nodeName=="TEXTAREA"&&(b.value="")}})}
function Kb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.o){var e=a.i;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||Ub(a,b,Vb,d,c)}});b.addEventListener("mousemove",function(d){a.o||Ub(a,b,Wb,d,c)});b.addEventListener("mouseup",function(d){a.o||d.button||Ub(a,b,Xb,d,c)});b.addEventListener("mouseout",function(d){a.o||(c.gb<0?Ub(a,b,Wb,d,c):Ub(a,b,Xb,d,c))})}
function Lb(a,b,c){b.addEventListener("touchstart",function(d){a.S&&(a.o=!0);Ub(a,b,Vb,d,c)});b.addEventListener("touchmove",function(d){Ub(a,b,Wb,d,c)});b.addEventListener("touchend",function(d){Ub(a,b,Xb,d,c)})}
function Tb(a,b,c,d){if(c!=void 0){var e=qb[b]||b;var f=sb[b];var g=Yb[e];d=d&&d.location==rb.Ab;g&Zb&&d&&(g>>=1);g&&(g&$b&&(c=!(a.g&g)),a.g=c?a.g|g:a.g&~g,Jb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=ob.ub&&b<=ob.Db?a.g&(ac|bc)||(a.g|=bc,Jb(a,J.xb,!0)):b>=ob.a&&b<=ob.z&&a.g&bc&&(a.g&=~bc,Jb(a,J.xb,!1));if(a.h){if(c!=void 0)return!1;for(e=0;e<a.h.length;e++)for(g=a.h[e],d=0;d<g.length;d++)if(g[d].split("|").indexOf(f)>=0)return a.u?a.v.length<16&&a.v.push(b):(a.u=1,a.I=f,Nb(a,d,e),Jb(a,
f,!0),Qb(a)),!0}if(a.j){if(c==void 0)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(g=b[e],a.j[g].keys.indexOf(f)>=0)return Jb(a,g,c),a.j[g].state=c?1:0,!0}return!1}function Ob(a){a.u==1?(a.u++,Jb(a,a.I,!1),a.I="",Nb(a,-1,-1),Qb(a)):(a.u=0,a.v.length&&Tb(a,a.v.shift()))}Fb.prototype.ta=function(){this.g=0;this.O=this.U=-1};
function Ub(a,b,c,d,e){var f=-1,g=-1,h=!1,k=-1,n=-1;if(c<Xb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,n=d.targetTouches[0].clientY,h=d.targetTouches.length>1):(k=d.clientX,n=d.clientY);var m=d.target.getBoundingClientRect();k-=m.left;n-=m.top;k=e.Wd/b.offsetWidth*k|0;n=e.Yd/b.offsetHeight*n|0;var r=k-e.We;var p=n-e.Xe;var q=m=!1;var v=k>=e.Yc&&k<e.Yc+e.Vd&&n>=e.Zc&&n<e.Zc+e.Xd;if(r>=0&&r<e.bb&&p+e.Tc>=0||v)if(h||a.S||d.preventDefault(),r>=0&&r<e.bb&&
p>=0&&p<e.jb){q=!0;d=e.bb/e.cb|0;var u=e.jb/e.nb|0,y=r/d|0,z=p/u|0;!a.Z||z&1||(r-=d>>1,y=r/d|0,y==e.cb-1&&(r=-1));u=z*u+(e.Tc>>1);r-=y*d+(e.Ud>>1);p-=u;r>=0&&r<e.Rc&&p>=0&&p<e.Sc&&(f=y,g=z,m=!0)}}r=r||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Vb||c==Xb)for(y=0;y<a.M.length;y++)z=a.M[y],c==Xb?z.kb(z.id,!1):(u=p/(b/z.rg|0)|0,(r/(d/z.qg|0)|0)==z.Fg&&u==z.Gg&&z.kb(z.id,!0));if(!h)if(c==Vb)e.gb=k,e.tb=n,q?(Nb(a,f,g),m&&a.l&&Rb(a.time,a.W,a.l,!0)):v&&a.X.sa();else if(c==Wb)e.gb>=0&&e.tb>=0&&a.$?Nb(a,
f,g):a.J&&a.J(f,g);else if(c==Xb){if(c=a.l)c=a.time,f=a.W,c=c.g&&f>0&&f<=c.h.length?c.h[f-1].za>=0:!1;c||Nb(a,-1,-1);e.gb=e.tb=-1}else a.m("unrecognized action: %d\n",c)}function Nb(a,b,c){if(b!=a.O||c!=a.U)a.O=b,a.U=c,a.T&&a.T(b,c)}var Vb=1,Wb=2,Xb=3,Gb="surface",ac=3,Zb=170,bc=512,$b=3584,cc={},Yb=(cc[J.Fd]=2,cc[J.bd]=8,cc[J.$c]=32,cc[J.Xb]=128,cc[J.xb]=bc,cc[J.ud]=1024,cc[J.Cd]=2048,cc);E.Input=Fb;
function dc(a,b,c){M.call(this,a,b,c,["color","backgroundColor"]);a=this.ba[ec];if(!a)throw Error("LED "+this.config.ba[ec]+" binding for '"+ec+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.qa=Xa(this,ec)+".canvas";b.setAttribute("id",this.qa);this.type=$a(I(this,"type",fc,hc),ic,jc);this.i=kc[this.type][0];this.u=kc[this.type][1];this.width=I(this,"width",this.i);
this.height=I(this,"height",this.u);this.j=I(this,"cols",1);this.L=this.j+I(this,"colsExtra",0);this.Z=I(this,"rows",1);this.O=this.Z+I(this,"rowsExtra",0);this.ca=this.width*this.j;this.T=this.height*this.Z;this.o=lc("black",0);this.h=mc(this.config.color)||this.o;this.ma=lc(this.h,1,.25);this.la=lc(this.h,1,2);this.l=mc(this.config.backgroundColor);this.na=I(this,"fixed",!1);this.na||(b.style.width="100%",b.style.height="auto");this.ha=I(this,"hexagonal",!1);this.oa=I(this,"highlight",!0);this.S=
I(this,"persistent",this.type<jc);b.setAttribute("width",this.ca.toString());b.setAttribute("height",this.T.toString());b.style.backgroundColor=this.o;a.appendChild(b);this.ga=b.getContext("2d");if(this.v=document.createElement("canvas"))this.v.width=this.$=this.i*this.j,this.v.height=this.I=this.u*this.Z,this.g=this.v.getContext("2d");this.va=(this.O+1)*this.L*4;this.buffer=Array(this.va);this.xa=this.j<this.L?(this.L-this.j)*4:0;this.M=this.N=!1;this.J=this.W=0;this.U=-1;var d=this;this.time=P(this,
"Time");nc(this.time,function(e,f){oc(d,!1,e,f)});pc(d)}w(dc,M);function pc(a){for(var b=a.buffer,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<jc?qc:" ";e[f+1]=d.h==d.o?null:d.h;e[f+2]=0;e[f+3]=rc}a.M=a.N=!0;oc(a,!0)}function sc(a){a.l?(a.g.fillStyle=a.l,a.g.fillRect(0,0,a.$,a.I)):a.g.clearRect(0,0,a.$,a.I)}
function oc(a,b,c,d){b=b===void 0?!1:b;c=c===void 0?0:c;d=d===void 0?60:d;if(a.M||b){if(a.type<jc){d=0;if(!a.S||b)sc(a);else if(a.J){d=a.j-a.J;var e=a.i*d;a.g.drawImage(a.v,a.i*a.J,0,e,a.I,0,0,e,a.I)}for(var f=e=0;f<a.O;f++){for(var g=0;g<a.j;g++){var h=a.buffer[e],k=a.buffer[e+1]||a.o,n=a.oa&&e==a.U;if(a.buffer[e+3]&rc||n||b){if(g>=d)a:{var m=a,r=h;h=k;var p=g;k=f;var q=n;p=p===void 0?0:p;k=k===void 0?0:k;q=q===void 0?!1:q;var v=0;if(m.ha&&!(k&1)&&(v=m.i>>1,p==m.j-1))break a;if(h&&h!=m.h){q=q?lc(h,
1,2):h;var u=lc(h,1,.25)}else q=q?m.la:m.h,u=m.ma;h=!1;r=r?q:u;q==m.o&&(r=m.l,h=!0);q=p*m.i+v;u=k*m.u;m.S&&(p=p*m.i+v,k*=m.u,m.l?(m.g.fillStyle=m.l,m.g.fillRect(p,k,m.i,m.u)):m.g.clearRect(p,k,m.i,m.u));m.g.fillStyle=r;k=tc[m.type];k.length==3?(m.g.beginPath(),m.g.arc(q+k[0],u+k[1],k[2],0,Math.PI*2),h?(m.g.globalCompositeOperation="destination-out",m.g.fill(),m.g.globalCompositeOperation="source-over"):m.g.fill()):m.g.fillRect(q+k[0],u+k[1],k[2],k[3])}a.buffer[e+3]=n?a.buffer[e+3]|rc:a.buffer[e+3]&
~rc}e+=4}e+=a.xa}a.J=0}else{b="";for(d=0;d<a.buffer.length;d+=4)b+=a.buffer[d]||" ",a.buffer[d+3]&uc&&(b+=".");sc(a);for(f=e=d=0;d<b.length;d++){n=b[d];n=="."&&e&&e--;g=a;k=n;n=e;m=f;n=n===void 0?0:n;m=m===void 0?0:m;if(k=vc[k])for(h=0;h<k.length;h++)if(p=g,v=wc[k[h]]){r=(n===void 0?0:n)*p.i;q=(m===void 0?0:m)*p.u;p.g.fillStyle=p.h;p.g.beginPath();if(v.length==3)p.g.arc(r+v[0],q+v[1],v[2],0,Math.PI*2);else for(u=0;u<v.length;u+=2)u?p.g.lineTo(r+v[u],q+v[u+1]):p.g.moveTo(r+v[u],q+v[u+1]);p.g.closePath();
p.g.fill()}if(++e==a.j&&(e=0,++f==a.O))break}}a.ga.globalCompositeOperation=a.l&&a.h!=a.o?"source-over":"copy";a.ga.drawImage(a.v,0,0,a.$,a.I,0,0,a.ca,a.T);a.M=!1;a.U=-1}else a.S||a.N||(!c||!a.W||c-a.W>=(1E3/d|0))&&pc(a);a.N=!1;c&&(a.W=c)}function mc(a){return(a=a||void 0)&&tb[a]||a}
function lc(a,b,c){b=b===void 0?1:b;c=c===void 0?1:c;if(a){var d=[];a=tb[a]||a;var e=a;var f=16;var g=e.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);g||(f=10,g=e.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(g){for(e=1;e<g.length;e++)d[e-1]=Number.parseInt(g[e],f);d.length=e-1;f=!0}else f=!1;if(f){a="rgba(";for(f=0;f<3;f++)g=Math.round(d[f]*c),g=g<0?0:g>255?255:g,a+=g+",";a+=(f<d.length?d[f]:b)+")"}}return a}
dc.prototype.ja=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.h&&c==this.l&&a&&a.length==this.buffer.length){this.buffer=a;for(b=0;b<=this.buffer.length-4;b+=4)this.buffer[b+1]==this.o&&(this.buffer[b+1]=null);oc(this,!0);return!0}return!1};dc.prototype.ka=function(a){this.buffer&&(a.push(this.h),a.push(this.l),a.push(this.buffer))};
var ic=0,fc=1,jc=3,hc={small:ic,round:fc,square:2,digit:jc},ec="container",qc=0,uc=1,rc=128,xc={},tc=(xc[ic]=[4,4,4],xc[fc]=[16,16,14],xc[2]=[2,2,28,28],xc),kc=[[8,8],[32,32],[32,32],[96,128]],wc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},vc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C",
"D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};E.LED=dc;
function yc(a,b,c){M.call(this,a,b,c);this.qa=I(this,"cyclesMinimum",1E5);this.Ja=I(this,"cyclesMaximum",1E9);this.ha=$a(I(this,"cyclesPerSecond",1E6),this.qa,this.Ja);this.$=60;this.T=0;this.U=1E3/this.$;this.Qa=I(this,"updatesPerSecond",2)||2;this.Ya=1E3/this.Qa;this.Fa=0;this.Za=I(this,"timeLock",!0);this.oa=this.M=0;this.na=this.l=1;this.xa=this.u=this.ha/1E4/100;this.la=[];this.J=[];this.h=[];this.ca=[];this.va=this.g=this.S=this.I=!1;this.L=this.j=0;a=Va("requestAnimationFrame");if(!a){a="setTimeout";
var d=this.U}this.Ra=window[a].bind(window,this.Ae.bind(this),d);this.Xa=window[Va("cancelAnimationFrame")||"clearTimeout"].bind(window);this.Z=this.W=this.o=this.i=this.ga=0;zc(this)||Ac(this,this.na)}w(yc,M);function nc(a,b){a.la.push(b)}l=yc.prototype;
l.Ka=function(a,b){var c=this;switch(a){case Bc:b.onclick=function(){Cc(c)&&(c.g?Dc(c):c.start())};break;case Ec:b.onclick=function(){Ac(c,c.l<<1);Fc(c,Gc(c.u))};break;case Hc:b.onclick=function(){Ic(c)};break;case Jc:b.addEventListener("mousedown",function(){c.I=!0}),b.addEventListener("mouseup",function(){zc(c);c.I=!1}),b.addEventListener("mousemove",function(){c.I&&zc(c)}),b.addEventListener("change",function(){c.I=!0;zc(c);c.I=!1})}M.prototype.Ka.call(this,a,b)};
function Mb(a,b,c){var d=d===void 0?-1:d;var e=a.h.length+1;a.h.push({id:b,Nd:c,mb:d,za:-1});d>=0&&Rb(a,e,d);return e}
function Kc(a,b,c,d){var e=0,f=a.u,g=f*1E6;b&&c&&(f=b/(c*10)/100,a.m(262144,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.U&&(a.l>1&&(a.l>>=1,a.m(549755813888,"frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.U,a.l)),e=d));a.M=f;a.oa=f/a.xa;b=a.oa/a.l;a.ga=g/b/a.$+1E-8;a.m(262144,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.ga,g,b,a.$);return e}
function Lc(a,b){a.W=a.o=b;if(!a.J.length)return a.o=0,a.W;for(var c=0;a.o>0;){if(c<a.J.length){var d=a.J[c++];b=d.Ce.call(d,b)||1}else c=b=0;a.o-=b}return a.W-a.o}function Mc(a,b){b=b===void 0?a.W-a.o:b;if(!a.g){if(a.i)for(var c=0;c<a.J.length;c++){var d=a.J[c];d.De.call(d)}a.i=b}a.i-=b;a.i<1&&(a.S=!0);a.Z+=b;a.W=a.o=0;a.g||(a.Z=0);return b}
function Nc(a,b){b=b===void 0?0:b;if(b){var c=b;a.i+=b}else for(c=a.i,c<1&&(c=a.i+=a.ga),c<0&&(a.m(262144,"warning: cycle count dropped below zero: %f\n",c),c=a.i=0),c|=0,b=a.h.length;b>0;b--){var d=a.h[b-1];!(d.za<0)&&c>d.za&&(c=d.za)}return c}function Gc(a){a>=1?a=a.toFixed(2)+"Mhz":(a=Math.round(a*1E6),a=a<=999?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Oc(a){a.m(262144,"getSpeedCurrent(%5.3fhz)\n",a.M*1E6);return a.g&&a.M?Gc(a.M):"Stopped"}
function Cc(a){return a.va?!0:(a.m("not powered\n"),!1)}function Pc(a,b){if(b>=1)for(var c=a.h.length;c>0;c--){var d=a.h[c-1];d.za<0||(d.za-=b,d.za<=0&&(d.za=-1,d.Nd(),d.mb>=0&&Rb(a,c,d.mb)))}}l.sa=function(a){this.va=a;this.aa===void 0&&(this.aa=P(this,"Debugger",!1))&&this.aa.Eb(this,"time","dump time state",this.be)};function Ic(a,b){Cc(a)&&(a.g?a.m("already running\n"):a.j?Dc(a):Qc(a,b))}
l.Ae=function(a){a=a===void 0?Date.now():a;this.L=0;if(this.g){if(this.T){var b=a-this.T;b<1&&(b=16.67);this.$=1E3/b}this.T=a;a=Date.now();this.N&&(b=a-this.O-this.U,b>this.U&&(this.v+=b,this.m(549755813888,"browser throttling detected, compensating by %5.3fms\n",b)));this.O=a;this.v||(this.v=a);this.ma=0;try{this.S=!1;do Pc(this,Mc(this,Lc(this,Nc(this))));while(this.g&&!this.S)}catch(c){this.m("%s\n",c.message),Dc(this)}this.N=Date.now();this.ma&&(this.v+=this.ma,this.O+=this.ma);this.O+=Kc(this,
this.Z,this.N-this.v,this.N-this.O);this.N-this.Fa>=this.Ya&&this.update();for(a=0;a<this.la.length;a++)this.la[a](this.T,this.$);this.L=this.Ra()}};function Ac(a,b){if(b!==void 0){if(b<1||!a.I&&a.M>0&&a.M<a.u*.9)b=a.na;a.l=b;b=a.xa*a.l;a.u!=b&&(a.u=b,Fc(a,Gc(a.u)))}a.v=a.N=0;a.i=a.Z=0;Kc(a);for(b=a.h.length;b>0;b--){var c=a.h[b-1];c.mb>=0&&Rb(a,b,c.mb,!0)}}function zc(a){var b=a.ba[Jc];return b?(Ac(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Ja-a.qa)+a.qa)/a.ha|0),!0):!1}
function Rb(a,b,c,d){b>0&&b<=a.h.length&&(b=a.h[b-1],d||b.za<0)&&(c=Math.ceil(a.ha*(a.Za?a.na:a.oa)/1E3*(c===void 0?1E3:c)),a.g&&(c+=Mc(a)),b.za=c)}l.start=function(){if(this.g||this.j)return!1;this.g=!0;this.v=this.N=this.T=0;this.update(!0);this.L=this.Ra();return!0};function Qc(a,b){b=b===void 0?1:b;a.g||(b&&!a.j&&(a.j=b),a.j&&(a.j--,Pc(a,Mc(a,Lc(a,Nc(a,1)))),a.update(!1),a.j&&setTimeout(function(){Qc(a,0)},0)))}
function Dc(a){return a.g?(a.g=!1,Mc(a),a.L&&(a.Xa(a.L),a.L=0),a.update(!0),!0):a.j?(a.j=0,a.update(!0),!0):!1}l.update=function(a){a&&this.m(this.g?"started with %s target\n":"stopped\n",Gc(this.u));nb(this,Bc,this.g?"Halt":"Run");nb(this,Hc,this.j?"Stop":"Step");this.I||Fc(this,Oc(this));for(var b=0;b<this.ca.length;b++){var c=this.ca[b];c.Wc.call(c,a!=void 0)}this.Fa=Date.now();this.S=!0};function Fc(a,b){nb(a,Rc,b);nb(a,Ec,b)}
l.be=function(){var a=this.K("nCyclesPerSecond: %f\n",this.ha);a+=this.K("nUpdatesPerSecond: %f\n",this.Qa);a+=this.K("nTargetMultiplier: %f\n",this.l);return a+=this.K("nCyclesDepositPerFrame: %f\n",this.ga)};var Bc="run",Ec="setSpeed",Rc="speed",Hc="step",Jc="throttle";E.Time=yc;
function Sc(a,b,c){M.call(this,a,b,c);this.type=this.config.type=="static"?Tc:Uc;this.da=this.config.addrWidth||16;this.u=Math.pow(2,this.da);this.o=this.u-1|0;this.blockSize=this.config.blockSize||(this.da>16?4096:1024);this.blockSize>this.u&&(this.blockSize=this.u);this.L=this.u/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.i=(1<<this.h)-1;this.j=this.config.dataWidth||8;this.J=Math.pow(2,this.j)-1;this.l=this.config.littleEndian!==!1;this.g=Array(this.L);this.v=0;this.I=null;a=new Q(a,
b+"[NONE]",{size:this.blockSize,bus:this.R});for(b=0;b<this.u;b+=this.blockSize)Vc(this,b,this.blockSize,R.NONE,a);Wc(this,this.type)}w(Sc,M);function Vc(a,b,c,d,e){for(var f=b>>>a.h;c>0&&f<a.g.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var k=a.g[f];if(b!=g||h!=a.blockSize||k&&k.type!=R.NONE)break;k=a.R+"["+F(a,b,16,a.da)+"]";b=e?e.size==a.blockSize?e:new Q(a.Y,k,{type:d,ia:b,size:h,bus:a.R}):new Q(a.Y,k,{type:d,ia:b,size:h,bus:a.R});a.g[f]=b;b=g+a.blockSize;c-=h;f++}}
function Xc(a,b){for(var c=R.Ad,d=0,e=0;e<a.g.length;e++){var f=a.g[e];f&&f.type&c&&(b(f),d++)}return d}function Yc(a,b,c){if(!(b&a.i)){b>>>=a.h;var d=a.g[b];a.g[b]=c}return d}function Zc(a,b,c){a.aa&&a.aa.m(4,"bus fault (%d) at %n\n",c,b);a.I&&a.I(b,c)}l=Sc.prototype;l.sa=function(){this.aa===void 0&&(this.aa=P(this,"Debugger",!1))};l.ta=function(){};l.Ib=function(a){return a&&this.ja(a)?!0:!1};l.eb=function(a){this.ka(a)};
l.ja=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==Uc||c.type&R.Sa)&&c.ja){var d=a.shift();if(!c.ja(d))return!1}}return!0};l.ka=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==Uc||c.type&R.Sa)&&c.ka){var d=[];c.ka(d);a.push(d)}}};l.Kb=function(a){return this.g[a>>>this.h].Kb(a&this.i)};l.od=function(a){return this.g[a>>>this.h].Aa(a&this.i)};l.fb=function(a,b){this.g[a>>>this.h].fb(a&this.i,b)};
l.Ea=function(a,b){this.g[a>>>this.h].ya(a&this.i,b)};l.kc=function(a){return a&1?this.Aa(a+1&this.o)|this.Aa(a)<<this.j:this.g[a>>>this.h].pa(a&this.i)};l.lc=function(a){return a&1?this.Aa(a)|this.Aa(a+1&this.o)<<this.j:this.g[a>>>this.h].pa(a&this.i)};l.ie=function(a){return(a&this.i)==this.i?this.l?this.lc(a):this.kc(a):this.g[a>>>this.h].pa(a&this.i)};l.mc=function(a,b){a&1?(this.ya(a,b>>this.j),this.ya(a+1&this.o,b&this.J)):this.g[a>>>this.h].fa(a&this.i,b)};
l.nc=function(a,b){a&1?(this.ya(a,b&this.J),this.ya(a+1&this.o,b>>this.j)):this.g[a>>>this.h].fa(a&this.i,b)};l.Fe=function(a,b){(a&this.i)==this.i?this.l?this.nc(a,b):this.mc(a,b):this.g[a>>>this.h].fa(a&this.i,b)};function Wc(a,b){var c=a.v;a.v+=b;c&&a.v||(a.Aa=a.od,a.ya=a.Ea,a.type==Uc?(a.pa=a.ie,a.fa=a.Fe):a.l?(a.pa=a.lc,a.fa=a.nc):(a.pa=a.kc,a.fa=a.mc))}l.pb=function(a,b){return this.g[a>>>this.h].pb(b)?(Wc(this,1),!0):!1};l.Nb=function(a,b){return this.g[a>>>this.h].Nb(b)?(Wc(this,1),!0):!1};
l.qb=function(a,b){return this.g[a>>>this.h].qb(b)?(Wc(this,-1),!0):!1};l.Pb=function(a,b){return this.g[a>>>this.h].Pb(b)?(Wc(this,-1),!0):!1};var Tc=0,Uc=1;E.Bus=Sc;
function Q(a,b,c){M.call(this,a,b,c);this.ia=this.config.addr;this.size=this.config.size;this.type=this.config.type||R.NONE;this.j=(a=this.config.bus)?ub(this,a):P(this,a="Bus");if(!this.j)throw Error(this.K("unable to find bus '%s'",a));this.g=this.j.j;this.i=Math.pow(2,this.g)-1;this.W=this.$=!1;this.l=this.j.l!==!1;this.values=this.Z=this.buffer=this.U=null;a=this.Pa;b=this.Ea;c=this.l?this.ke:this.je;var d=this.l?this.He:this.Ge;this.j.type==Tc&&(b=this.Qe,c=this.l?this.qd:this.pd,d=this.Re,this.g==
8&&yb(this,"ArrayBuffer")!==!1&&(this.$=!0,c=this.l==ta?this.te:this.ue));switch(this.type){case R.NONE:this.Aa=this.Ma;this.ya=this.Ga;this.pa=this.le;this.fa=this.Ie;break;case R.yc:this.Aa=a;this.ya=this.Ga;this.pa=c;this.fa=this.Ga;break;case R.Sa:this.Aa=a,this.ya=b,this.pa=c,this.fa=d}this.L=this.o=0;this.T=this.u=this.S=this.M=this.v=this.I=null;$c(this,this.config.values);ad(this)}w(Q,M);
function $c(a,b){typeof b=="string"?(Bb(a,!1),bb(b,function(c,d,e,f){if(e==4)if(!f&&d){try{var g=JSON.parse(d);$c(a,g.values)}catch(h){a.m("error (%s) parsing resource: %s\n",h.message,c)}Bb(a,!0)}else a.m("error (%d) loading resource: %s\n",f,c)})):a.config.values=b}
function ad(a,b){if(a.type>R.NONE&&(a.$?(a.buffer=new ArrayBuffer(a.size),a.U=new DataView(a.buffer,0,a.size),a.values=new Uint8Array(a.buffer,0,a.size),a.Z=new Uint16Array(a.buffer,0,a.size>>1),new Int32Array(a.buffer,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}l=Q.prototype;
l.ta=function(){if(this.config.values)a:{var a=this.j,b=this.ia,c=this.size,d=this.config.values,e=0,f=b&a.i;b>>>=a.h;c>d.length&&(c=d.length);for(;c>0&&b<a.g.length;){var g=a.g[b++];if(!g)break a;for(;c>0&&f<g.size;)g.Ea(f++,d[e++]),c--;f=0}}else this.type&R.Sa&&this.values&&this.values.fill(0)};l.Ma=function(){return this.i};l.le=function(a){return this.l?this.Ma(a)|this.Ma(a+1)<<this.g:this.Ma(a+1)|this.Ma(a)<<this.g};l.Kb=function(a){return this.values?this.values[a]:0};l.Pa=function(a){return this.values[a]};
l.pd=function(a){return this.values[a+1]|this.values[a]<<this.g};l.qd=function(a){return this.values[a]|this.values[a+1]<<this.g};l.te=function(a){return this.Z[a>>>1]};l.ue=function(a){return this.U.getUint16(a,this.l)};l.je=function(a){return this.Pa(a+1)|this.Pa(a)<<this.g};l.ke=function(a){return this.Pa(a)|this.Pa(a+1)<<this.g};l.Ga=function(){};l.Ie=function(a,b){this.l?(this.Ga(a,b&this.i),this.Ga(a+1,b>>this.g)):(this.Ga(a,b>>this.g),this.Ga(a+1,b&this.i))};
l.fb=function(a,b){this.values&&(this.values[a]=b)};l.Ea=function(a,b){this.values[a]=b};l.Qe=function(a,b){this.values[a]=b;this.W=!0;this.o?this.M=this.Ea:this.ya=this.Ea};l.yb=function(a,b){this.values[a]=b>>this.g;this.values[a+1]=b&this.i};l.zb=function(a,b){this.values[a]=b&this.i;this.values[a+1]=b>>this.g};l.Qb=function(a,b){this.Z[a>>>1]=b};l.Rb=function(a,b){this.U.setUint16(a,b,this.l)};l.Ge=function(a,b){this.Ea(a,b>>this.g);this.Ea(a+1,b&this.i)};
l.He=function(a,b){this.Ea(a,b&this.i);this.Ea(a+1,b>>this.g)};l.Re=function(a,b){this.buffer?this.l==ta?(this.Qb(a,b),this.o?this.u=this.Qb:this.fa=this.Qb):(this.Rb(a,b),this.o?this.u=this.Rb:this.fa=this.Rb):this.l?(this.zb(a,b),this.o?this.u=this.zb:this.fa=this.zb):(this.yb(a,b),this.o?this.u=this.yb:this.fa=this.yb)};
l.pb=function(a){if(!this.L){var b=this;this.L++;this.v=a;this.S=this.Aa;this.T=this.pa;this.Aa=function(c){var d=b.S(c);b.v(b.ia,c,d);return d};this.pa=function(c){var d=b.T(c);b.v(b.ia,c,d);b.v(b.ia,c+1,d);return d};return!0}return this.v==a?(this.L++,!0):!1};l.Nb=function(a){if(!this.o){var b=this;this.o++;this.I=a;this.M=this.ya;this.u=this.fa;this.ya=function(c,d){b.I(b.ia,c,d);b.M(c,d)};this.fa=function(c,d){b.I(b.ia,c,d);b.I(b.ia,c+1,d);b.u(c,d)};return!0}return this.I==a?(this.o++,!0):!1};
l.qb=function(a){return this.L&&this.v==a?(--this.L||(this.Aa=this.S,this.pa=this.T,this.S=this.T=this.v=null),!0):!1};l.Pb=function(a){return this.o&&this.I==a?(--this.o||(this.ya=this.M,this.fa=this.u,this.M=this.u=this.I=null),!0):!1};l.ja=function(a){if(a){var b=a.shift();if(this.R==b){this.W=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=c===void 0?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}ad(this,a)}return!0}}return!1};
l.ka=function(a){a.push(this.R);a.push(this.W);a.push(!1);var b=a.push;if(this.values){var c=this.values;for(var d=0,e=0,f=[];d<c.length;){for(var g=c[d],h=d+1;h<c.length&&c[h]===g;)h++;f[e++]=h-d;f[e++]=g;d=h}c=f.length>=c.length?Array.isArray(c)?c:Array.from(c):f}else c=this.values;b.call(a,c)};var R={NONE:1,yc:2,Sa:4,Ad:14,ng:12};E.Memory=Q;
function bd(a,b,c){Q.call(this,a,b,c);this.J=[];this.N=[];this.h=[];this.O=[];this.config.addr!=void 0&&Vc(this.j,this.config.addr,this.config.size,R.NONE,this)}w(bd,Q);function cd(a,b,c,d,e,f,g,h){for(var k;c<=d;c++){k=!1;if(e){if(a.J[c])break;a.J[c]=e.bind(b)}if(f){if(a.N[c])break;a.N[c]=f.bind(b)}if(g){if(a.h[c])break;a.h[c]=g.bind(b)}if(h){if(a.O[c])break;a.O[c]=h.bind(b)}k=!0}if(!k)throw Error(a.K("handler for port %#0x already exists",c));}
function dd(a,b,c){var d=d===void 0?0:d;for(var e in c){var f=c[e];cd(a,b,+e+d,+e+d,f[0],f[1],f[2],f[3])}}bd.prototype.Ma=function(a){var b,c=this.ia+a;if(b=this.J[c]){var d=b(c);var e=!0}else if(b=this.h[c])d=c&1?b(c&-2)>>this.g:b(c)&this.i,e=!0;else if(c&1)if(c&=-2,b=this.h[c])d=b(c)>>this.g,e=!0;else if(b=this.J[c])d=b(c),e=!0;e||(Zc(this.j,c,0),this.m(272,"readNone(%#04x): unknown port\n",c),d=Q.prototype.Ma.call(this,a));return d};
bd.prototype.Ga=function(a,b){var c,d=this.ia+a;if(c=this.N[d]){c(d,b);var e=!0}else if(c=this.O[d])e=this.h[d]?this.h[d](d,!0):0,d&1?c(d,e&this.i|b<<this.g):c(d,e&~this.i|b),e=!0;else if(d&1)if(d&=-2,c=this.O[d])e=this.h[d]?this.h[d](d,!0):0,c(d,e&this.i|b<<this.g),e=!0;else if(c=this.N[d])c(d,b),e=!0;e||(Zc(this.j,d,1),this.m(272,"writeNone(%#04x,%#04x): unknown port\n",d,b),Q.prototype.Ga.call(this,a,b))};E.Ports=bd;
function ed(a,b,c){c.type=R.NONE;Q.call(this,a,b,c);Vc(this.j,this.config.addr,this.config.size,R.Sa);Cb(this,this.ta.bind(this))}w(ed,Q);E.RAM=ed;
function fd(a,b,c){c.type=R.yc;Q.call(this,a,b,c);Vc(this.j,this.config.addr,this.config.size,this.config.type,this);Cb(this,this.ta.bind(this));this.H=this.aa=void 0;if(E.LED&&this.ba[gd]){var d=this;this.J=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.N=this.values.length/this.J|0;this.h=new dc(a,b+"LEDs",{"class":"LED",bindings:{container:Xa(this,gd)},type:fc,cols:this.J,rows:this.N,color:I(this,"colorROM","green"),backgroundColor:I(this,"backgroundColorROM","black"),persistent:!0}),
pc(this.h);this.O=new Fb(a,b+"Input",{"class":"Input",location:[0,0,this.h.ca,this.h.T,this.J,this.N],bindings:{surface:Xa(this,gd)}});this.ca=Ya(this)||"";Ib(this.O,function(e,f){if(d.H){var g=d.ca;e>=0&&f>=0&&(e=f*d.J+e,f=d.H,g=f.aa&&hd(f.aa,d.ia+e,1)||"");nb(d,Za,g)}})}}w(fd,Q);
fd.prototype.ja=function(a){var b=!0,c=a.shift();if(c&&this.h){var d=c.length;this.h.buffer.length==d?(this.h.buffer=c,oc(this.h,!0)):(this.m("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.m("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};fd.prototype.sa=function(){this.H===void 0&&(this.H=P(this,"CPU"));this.aa===void 0&&(this.aa=P(this,"Debugger",!1))&&this.aa.Fb&&this.aa.Fb(this.config.symbols)};
fd.prototype.Pa=function(a){if(this.h){var b=this.h,c=rc;c=(c===void 0?0:c)&129;var d=((a/this.J|0)*b.L+a%this.J)*4;if(d<=b.buffer.length-4){if(b.buffer[d]!==1||(b.buffer[d+3]&129)!==c)b.buffer[d]=1,b.buffer[d+3]=b.buffer[d+3]&-130|c|rc,b.M=!0;b.U=d;b.N=!0;b.J=0}}return this.values[a]};fd.prototype.ka=function(a){this.h&&(a.push(this.h.buffer),a.push(this.values))};var gd="array",Za="cellDesc";E.ROM=fd;
function id(a,b,c){c["class"]="CPU";M.call(this,a,b,c);this.aa=void 0;this.Za=this.Lb=0;this.T=this.config.addrReset||0;this.time=P(this,"Time");this.time.J.push(this);this.time.ca.push(this);this.ma=this.$=0}w(id,M);id.prototype.abort=function(a){this.Za=this.Lb;this.m("%s\n",a.message);Dc(this.time)};function jd(a,b){a.aa=b;return a.Ia}id.prototype.Ce=function(a){this.ma=this.$=a===void 0?0:a;return this.ma-this.$};id.prototype.De=function(){this.ma-=this.$;this.$=0};
function kd(a,b,c){c["class"]="Debugger";M.call(this,a,b,c);var d=this;this.ea=this.config.defaultRadix||16;this.la=1;this.Z=["(",")"];this.Gc("a",function(f,g,h,k,n){return F(d,n.V,d.ea,h)});this.Gc("n",function(f,g,h,k,n){return F(d,n,d.ea,h,g.indexOf("#")<0?"":void 0)});this.ma=this.L=0;this.N={};this.na=[];this.oa=[];this.H=P(this,"CPU");this.Ia=jd(this.H,this);this.input=P(this,"Input",!1);if(a=this.H.config.busMemory||this.config.busMemory){this.g=ub(this,a);if(a=this.H.config.busIO||this.config.busIO)this.j=
ub(this,a,!1);this.j||(this.j=this.g)}else this.g=this.j=P(this,"Bus");this.M=this.g.da;this.Fa=Math.pow(2,this.M)-1|0;this.v=this.ga=0;this.u=[];for(var e in S)this.u[S[e]]=[];this.o=[];this.o[S.Ba]=this.g;this.o[S.ab]=this.g;this.o[S.Ua]=this.j;this.o[S.Va]=this.j;this.l=[];this.l[S.Ba]=this.Qd.bind(this);this.l[S.ab]=this.Td.bind(this);this.l[S.Ua]=this.Od.bind(this);this.l[S.Va]=this.Pd.bind(this);this.i=[];this.S=void 0;this.W=null;this.$=0;this.time=P(this,"Time");this.time.ca.push(this);this.J=
0;this.I=[];this.U="";this.Eb(this,"state","dump machine state",this.ae);this.ca=ld();this.qa=ld();this.ha=!1;this.T=0;this.h=[];Ra(this,this.fe.bind(this));(e=yb(this,"commands"))&&hb(this,e)}w(kd,M);l=kd.prototype;l.Eb=function(a,b,c,d){this.I.push({$d:a,name:b,Zd:c,kb:d})};function md(a,b,c){for(var d,e=0;e<a.I.length;e++){var f=a.I[e];if(f.name==b){d=f.kb.call(f.$d,c);break}}return d}
l.Fb=function(a){if(a&&a.length)for(var b=0;b<a.length-2;b+=3){var c=nd(this,a[b]);if(c){var d=od[a[b+1]];if(d){c={address:c,type:d,name:a[b+2]};d=this.na;var e=c,f=pd(d,e,this.Pc);f<0&&d.splice(-(f+1),0,e);d=this.oa;e=pd(d,c,this.Qc);e<0&&d.splice(-(e+1),0,c)}}}};function pd(a,b,c){var d=0,e=a.length,f=0;for(c===void 0&&(c=function(k,n){return k>n?1:k<n?-1:0});d<e;){var g=d+e>>1,h=void 0;h=c(b,a[g]);h>0?d=g+1:(e=g,f=!h)}return f?d:~d}l.Pc=function(a,b){return a.name>b.name?1:a.name<b.name?-1:0};
l.Qc=function(a,b){return a.address.V>b.address.V?1:a.address.V<b.address.V?-1:0};function qd(a,b,c){b=pd(a.oa,{address:b,type:0,name:void 0},a.Qc);if(b>=0&&(a=a.oa[b],!c||a.type==c))var d=a.name;return d}function rd(a,b,c,d){d=d===void 0?a.g:d;b.V=b.V+c&d.o}function ld(a){a=a===void 0?0:a;var b=sd.xd;return typeof a=="number"?{V:a,Mb:-1,type:b}:{V:a.V,Mb:a.Mb,type:a.type}}
function nd(a,b,c){if(b){var d=ld();var e=0,f=b.charAt(e);switch(f){case "&":e++;break;case "#":e++;d.type=sd.yd;break;case "%":e++,f=b.charAt(e),f=="%"?e++:d.type=sd.Ec}f=b.indexOf(":",e);if(f>=0){var g=td(a,b.substring(e,f),c);g==void 0?d=null:(d.Mb=g,e=f+1)}d&&(b=td(a,b.substring(e),c),b==void 0?d=null:d.V=b&a.Fa)}return d}function ud(a,b,c,d){d=d===void 0?a.g:d;a.v++;var e=d.Kb(b.V);c&&rd(a,b,c,d);a.v--;return e}
function vd(a,b,c){if(a.M<=32)return b&c;b=T(a,b,0,!0);c=T(a,c,0,!0);return((b/G|0)&(c/G|0))*G+((b&c)>>>0)}function wd(a,b,c){if(a.M<=32)return b^c;b=T(a,b,0,!0);c=T(a,c,0,!0);return((b/G|0)^(c/G|0))*G+((b^c)>>>0)}
function xd(a,b,c,d){for(d=d===void 0?-1:d;d--&&c.length;){var e=c.pop();if(b.length<2)return!1;var f=b.pop();var g=b.pop();switch(e){case "*":g*=f;break;case "/":if(!f)return!1;g=Math.trunc(g/f);break;case "^/":if(!f)return!1;g%=f;break;case "+":g+=f;break;case "-":g-=f;break;case "<<":g<<=f;break;case ">>":g>>=f;break;case ">>>":g>>>=f;break;case "<":g=g<f?1:0;break;case "<=":g=g<=f?1:0;break;case ">":g=g>f?1:0;break;case ">=":g=g>=f?1:0;break;case "==":g=g==f?1:0;break;case "!=":g=g!=f?1:0;break;
case "&":g=vd(a,g,f);break;case "!":case "|":e=a;e.M<=32?g|=f:(g=T(e,g,0,!0),f=T(e,f,0,!0),g=(g/G|0|f/G|0)*G+((g|f)>>>0));break;case "^!":g=wd(a,g,f);break;case "&&":g=g&&f?1:0;break;case "||":g=g||f?1:0;break;case ",,":g=T(a,g,18,!0)*262144+T(a,f,18,!0);break;case "_":case "^_":e=="^_"&&(f=35-(f&255));f&&(g=T(a,g,0,!0),g=f>0?g*Math.pow(2,f):Math.trunc(g/Math.pow(2,-f)));break;default:return!1}b.push(T(a,g))}return!0}
function yd(a,b,c,d,e,f){var g,h=!1,k=0,n=[],m=[],r=a.ea;for(a.ea=e;c<d;){var p=b[c++].trim();var q=c<d?b[c++]:"";if(p){var v=void 0;var u=a;var y=p,z=f;k=k===void 0?0:k;if(y!=void 0){v=zb(u,y.toUpperCase());if(v==void 0){v=void 0;var C=u,V=pd(C.na,{address:null,type:0,name:y},C.Pc);V>=0&&(v=C.na[V].address.V);if(v==void 0)if(v=u,C=y,v.N[C]?v=v.N[C].value:(C=C.substr(0,6),v=v.N[C]&&v.N[C].value),v==void 0)v=Ha(y,y.length>1||u.ea>10?u.ea:10);else if(y=u.N[y]&&u.N[y].Ag)z?z.push(y):(z=td(u,y,z),z!==
void 0?v+=z:v=void 0)}v!=void 0&&(v=T(u,zd(u,v,k)))}u=v}else if(q=="{"){p=1;for(u=c;c<d;)if(c++,q=c<b.length?b[c++]:"",q=="{")p++;else if(q=="}"&&!--p)break;u=yd(a,b,u,c-1,a.ea,f);u!=null&&k&&(u=zd(a,u,k));p=c<d?b[c++].trim():"";q=c<d?b[c++]:""}else{if(q==" ")continue;if(q=="^B"){a.ea=2;continue}if(q=="^O"){a.ea=8;continue}if(q=="^D"){a.ea=10;continue}if(!(k&-1073741824)){if(q=="+")continue;if(q=="-"){k=k<<2|1;continue}if(q=="~"||q=="^-"){k=k<<2|2;continue}if(q=="^L"){k=k<<2|3;continue}}h=!0;break}if(u===
void 0)if(f)f.push(p),u=0;else{h=!0;break}n.push(T(a,u));if(q==" ")if(c<b.length-1&&!b[c])c++,q=b[c++];else{h=!0;break}if(!q)break;u=a.Z[0]=="<"?Ad:Bd;if(!u[q]){h=!0;break}m.length&&u[q]<=u[m[m.length-1]]&&xd(a,n,m,1);m.push(q);a.ea=q=="^_"?10:e;k=0}if(h||!xd(a,n,m)||n.length!=1)h=!0;h?f||a.m("parse error (%s)\n",p||q):g=n.pop();a.ea=r;return g}
function Cd(a,b,c,d){for(var e,f=a.M/d|0;(e=b.indexOf(c))>=0;){for(var g=0,h=e+1,k=f;h<b.length;){var n=b[h++];if(n==c){k=-1;break}if(!k)break;k--;n=n.charCodeAt(0);d==6&&(n-=32);n&=(1<<d)-1;g=T(a,g*Math.pow(2,d)+n,d*f,!0)}if(k>=0){a.m("parse error (%c%s%c)\n",c,b,c);return}b=b.substr(0,e)+F(a,g)+b.substr(h)}return b}
function td(a,b,c){if(b){a.Z[0]!="{"&&(b=b.split(a.Z[0]).join("{").split(a.Z[1]).join("}"));b=Cd(a,b,'"',8);if(!b)return d;b=Cd(a,b,"'",6);if(!b)return d;a.ea!=16&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);var d=yd(a,b,0,b.length,a.ea,c)}return d}
function zd(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-T(a,b);break;case 2:b=wd(a,b,-1);break;case 3:for(d=35;d>=0&&!vd(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function T(a,b,c,d){var e=b;c=c||a.M;if(d)if(c==32)e=b>>>0;else if(c<32)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),b<0||b>=a)e=b%a,e<0&&(e+=a)}else c<=32?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}
l.Gb=function(a){function b(h){for(var k=0;k<h.length;k++)if(h[k]!=void 0)return!1;return!0}if(a<-1)return Dd(this,this.Gb);var c="";if(a>=0){var d=this.i[a];if(d!=void 0){c=d>>8;d&=255;var e=this.o[c];if(e){var f=this.u[c],g=f[d];(c&1?e.Pb(g.V,this.l[c]):e.qb(g.V,this.l[c]))?(f[d]=void 0,this.i[a]=void 0,b(f)&&(f.length=0,b(this.i)&&(this.i.length=0)),c=this.K("%2d: %s %*a cleared\n",a,Ed[c],e.da,g),--this.ga||this.ha||(c+=Fd(this,!1))):c=this.K("invalid break address: %*a\n",e.da,g)}else c="invalid bus"}else c=
this.K("invalid break index: %d\n",a)}else c="missing break index\n";return c};function Gd(a,b){if(a.W&&(b==void 0||a.W.V==b)){var c=c===void 0?S.Ba:c;b=-1;var d=Hd(a.W,a.u[c]);if(d>=0)for(var e=0;e<a.i.length;e++){var f=a.i[e];if(f!=void 0&&c==f>>8&&d==(f&255)){b=e;break}}c=b;c>=0&&a.Gb(c);a.W=null}}
l.Hb=function(a,b){b=b===void 0?!1:b;if(a<-1)return Dd(this,this.Hb,b);if(a>=0){var c=this.i[a];if(c!=void 0){var d=c>>8;c=this.u[d][c&255];if(c!=void 0){var e=b?"enabled":"disabled",f=this.o[d];!c.disabled==!b?(c.disabled=!b,a=this.K("%2d: %s %*a %s\n",a,Ed[d],f.da,c,e)):a=this.K("%2d: %s %*a already %s\n",a,Ed[d],f.da,c,e)}else a=this.K("no break address at index: %d\n",a)}else a=this.K("invalid break index: %d\n",a)}else a="missing break index\n";return a};
function Dd(a,b,c){for(var d="",e=0;e<a.i.length;e++)a.i[e]!=void 0&&(d+=b.call(a,e,c));d||(d="no break addresses found");return d}function Id(a,b,c){c=c===void 0?S.Ba:c;a=a.u[c];for(c=0;c<a.length;c++){var d=a[c];if(d.V==b)return d}}function Hd(a,b){for(var c=0;c<b.length;c++)if(b[c].V==a.V)return c;return-1}
function Jd(a,b){b=b===void 0?!1:b;for(var c="",d=0;d<a.i.length;d++){var e=a.i[d];if(e!=void 0){var f=e>>8;e=a.u[f][e&255];f=a.K("%s %*a",Ed[f],a.o[f].da,e);b?(c&&(c+=";"),c+=f,e.disabled&&(c+=";bd "+d)):c+=a.K("%2d: %s %s\n",d,f,e.disabled?"disabled":"enabled")}}c||b||(c="no break addresses found\n");return c}
function Kd(a,b,c){c=c===void 0?S.Ba:c;if(b){var d=a.o[c];if(d){var e=a.u[c];var f=Hd(b,e);if(f>=0)f=-(f+1);else{for(f=0;f<e.length&&e[f]!=void 0;f++);e[f]=b}e=f;if(e>=0)if(f=c&1?d.Nb(b.V,a.l[c]):d.pb(b.V,a.l[c])){for(f=0;f<a.i.length&&a.i[f]!=void 0;f++);a.i[f]=c<<8|e;b=a.K("%2d: %s %*a set\n",f,Ed[c],d.da,b);a.ga++||a.h.length||(b+=Fd(a,!0))}else b=a.K("invalid break address: %*a\n",d.da,b),a.u[c][e]=void 0;else b=a.K("%s %*a already set\n",Ed[c],d.da,b)}else b="invalid bus"}else b="missing break address\n";
return b}function Ld(a,b){b>=0&&(a.L=b);var c="instruction break count: "+(a.L>0?a.L:"disabled")+"\n";b>0&&(a.h.length||(c+=Fd(a,!0)),a.ha=!0);return c}function Md(a,b){var c;if(b){var d=ib(b);d!=void 0?a.ma=d?0xffffffffffff:0:c=a.K("unrecognized message option: %s\n",b)}c||(c=a.K("break on message: %b\n",!!a.ma));return c}l.Od=function(a,b,c){this.v||(a==void 0?this.Da("break on unknown input %#0x: %#0x",b,c):(a=Id(this,a+b,S.Ua))&&!a.disabled&&this.Da("break on input %*a: %#0x",this.j.da,a,c))};
l.Pd=function(a,b,c){this.v||(a==void 0?this.Da("break on unknown output %#0x: %#0x",b,c):(a=Id(this,a+b,S.Va))&&!a.disabled&&this.Da("break on output %*a: %#0x",this.j.da,a,c))};
l.Qd=function(a,b,c){this.v||(a==void 0?this.Da("break on unknown read %#0x: %#0x",b,c):(a+=b,this.h.length&&a==this.H.Lb&&(this.$++,this.L>0&&(--this.L||this.Da("break on instruction count")),this.h[this.T++]=a,this.T==this.h.length&&(this.T=0)),(b=Id(this,a,S.Ba))&&!b.disabled&&(this.Da("break on read %*a: %#0x",this.g.da,b,c),Gd(this,a))))};
l.Td=function(a,b,c){this.v||(a==void 0?this.Da("break on unknown write %#0x: %#0x",b,c):(a=Id(this,a+b,S.ab))&&!a.disabled&&this.Da("break on write %*a: %#0x",this.g.da,a,c))};l.Da=function(a){a=this.K.apply(this,[a].concat(oa(pa.apply(1,arguments))));this.m("%s\n",a);Dc(this.time)};function Nd(a,b,c){c=c===void 0?a.g:c;return F(a,b.V,a.ea,c.da,"")}
function Od(a,b,c){c=c===void 0?10:c;var d="";if(a.h.length){var e,f=[];c>a.h.length&&(c=a.h.length);b<0&&(b=c);var g=a.T-b;for(g<0&&(g+=a.h.length);g>=0&&g<a.h.length&&c>0;){var h=a.h[g++];if(h==void 0)break;g==a.h.length&&(g=0);e?e.V=h:e=ld(h);for(h=0;h<a.la;h++)f[h]=ud(a,e,1);rd(a,e,-f.length);d+=a.Ob(e,f,a.K("[%6d]",b--));c--}}return d||"no history"}
function hd(a,b,c){var d=[],e="";for(b=typeof b=="number"?ld(b):b;c--;){for(rd(a,b,d.length);d.length<a.la;)d.push(ud(a,b,1));rd(a,b,-d.length);e+=a.Ob(b,d)}return e}
function Pd(a,b,c,d,e,f){var g="";f=f?a.j:a.g;c||(c=f.j);var h=c>>3;d||(d=128);var k=0,n=d+15>>4||1,m=h==4?16:a.ea;e=="y"&&(m=h,n=d,k=h*8);b||(b=a.qa);for(;n--&&d>0;){var r=e=0,p,q="",v="",u=Nd(a,b,f);for(p=m;p>0&&d>0;p--){var y=ud(a,b,1,f);f.l===!1?(e=(e<<8|y)>>>0,r++):e|=y<<(r++<<3);r==h&&(q+=F(a,e,0,c,""),q+=h==1?p==9?"-":" ":" ",k&&(v+=F(a,e,2,c,"")),e=r=0);k||(v+=y>=32&&y<127?String.fromCharCode(y):".");d--}g&&(g+="\n");g+=u+"  "+q+" "+v}a.qa=b;return g}
l.ae=function(){var a=[];xb(this,function(b){b.eb&&b.eb(a);return!0});return JSON.stringify(a,null,2)};function Qd(a,b,c,d){var e=0,f="";d=d?a.j:a.g;for(var g=0;b!=void 0&&g<c.length;g++){var h=ud(a,b,0,d);if(h==void 0)break;var k=a,n=b,m=c[g],r=d;r=r===void 0?k.g:r;k.v++;r.fb(n.V,m);k.v--;f+=a.K("%*a: %#*n changed to %#*n\n",a.g.da,b,a.g.j,h,a.g.j,c[g]);rd(a,b,1,d);e++}e||(f+=a.K("%d locations updated\n",e));a.time.update();return f}
function Fd(a,b){var c="";b!=void 0&&b==!a.h.length&&Xc(a.g,function(d){b?a.g.pb(d.ia,a.l[S.Ba]):a.g.qb(d.ia,a.l[S.Ba])})&&(b?(a.T=0,a.h=Array(Rd)):a.h=[]);return c+=a.K("instruction history %s\n",a.h.length?"enabled":"disabled")}l.ja=function(a){var b=a.shift();return this.R==b?(hb(this,a.shift()),this.X.ra=a.shift(),!0):!1};l.Vc=function(a){Ia(this.ma,a)?this.Da("break on message"):this.time.S=!0};
l.fe=function(a){var b=a[1],c=a[2],d=[],e=[],f=!1,g="";this.S=void 0;if(b=="save")return Sd(this,c);if(c=="*")var h=-2;else{h=Ha(c);h==void 0&&(h=-1);var k=nd(this,c,e);if(k===null)return}var n=0;a[3]&&(n=Ha(a[3].substr(a[3][0]=="l"?1:0))||8);for(var m=3;m<a.length;m++)d.push(Ha(a[m],16));if(b=="d"){m=md(this,c,d);if(m!=void 0)return m;b=this.U||b}if(b[0]!="s"&&e.length)return"unrecognized symbol(s): "+e;switch(b[0]){case "b":b[1]=="c"?g=this.Gb(h):b[1]=="d"?g=this.Hb(h):b[1]=="e"?g=this.Hb(h,!0):
b[1]=="i"?g=Kd(this,k,S.Ua):b[1]=="l"?g=Jd(this):b[1]=="m"?g=Md(this,c):b[1]=="n"?g=Ld(this,h):b[1]=="o"?g=Kd(this,k,S.Va):b[1]=="r"?g=Kd(this,k,S.Ba):b[1]=="w"?g=Kd(this,k,S.ab):b[1]=="?"?(g="break commands:\n",Td.forEach(function(r){g+=r+"\n"})):b[1]&&(g=void 0);break;case "d":this.U=b;if(b[1]!="b"&&b[1])if(b[1]=="w")c=16;else if(b[1]=="d")c=32;else if(b[1]=="i"){if(!this.j){g="invalid bus";break}c=this.j.j;n=n||1;f=!0}else{if(b[1]=="h")this.U="",g=Od(this,h,n);else if(b[1]=="?"){if(this.U="",g=
"dump commands:\n",Ud.forEach(function(r){g+=r+"\n"}),this.I.length)for(g+="dump extensions:\n",b=0;b<this.I.length;b++)k=this.I[b],g+=this.K("d   %-12s%s\n",k.name,k.Zd)}else this.U="",g=void 0;break}else c=8;g=Pd(this,k,c,n,b[2],f);break;case "e":if(b[1]=="o"){if(!this.j){g="invalid bus";break}f=!0}else if(b[1]){g=void 0;break}g=Qd(this,k,d,f);break;case "g":if(this.time.start()){if(k!=void 0){Gd(this);g=Kd(this,k);if(g.indexOf(":")!=2)break;this.W=k;g=""}break}g="already started\n";break;case "h":Dc(this.time)||
(g="already stopped\n");break;case "p":a.shift();a.shift();b=a.join(" ");g+=this.K("%s = %s\n",b,F(this,td(this,b)));break;case "r":if(b=b.substr(1).toUpperCase()){if(zb(this.H,b)==void 0){g+=this.K("unrecognized register: %s\n",b);break}k!=void 0&&Eb(this.H,b,k.V)}this.ca.V=this.H.Za;g+=this.H.toString();break;case "s":k=ib(c);if(b[1]=="h"){if(this.ga||this.L>0)k=void 0;g=Fd(this,k);k!=void 0&&(this.ha=k)}else b[1]=="p"?h>0?(Ac(this.time,h),g="target speed:  "+Gc(this.time.u)):g="current speed: "+
Oc(this.time):b[1]=="s"&&this.xa?(h=this.xa.indexOf(c),h>=0&&(this.style=this.xa[h]),g="style: "+this.style):b[1]=="?"?(g="set commands:\n",Vd.forEach(function(r){g+=r+"\n"})):g=void 0;break;case "t":n=Ha(c,10)||1;this.S=!0;if(b[1]){if(b[1]!="r"){g=void 0;break}this.S=!1}Ic(this.time,n);break;case "u":if(b[1]){g=void 0;break}n||(n=8);k||(k=this.ca);g+=hd(this,k,n);this.ca=k;break;case "?":g="debugger commands:\n";Wd.forEach(function(r){g+=r+"\n"});break;default:g=void 0}g==void 0&&a[0]&&(g="unrecognized command '"+
a[0]+"' (try '?')\n");return g};l.Ib=function(a){return a&&this.ja(a[0])?(a.shift(),!0):!1};l.eb=function(a){var b=[];this.ka(b);a.push(b);this.J=0};
l.Wc=function(a){if(a){if(this.time.g){if(this.J&&this.input){a=this.input;var b=a.i;b&&Ab(a.X)&&(a.m(2097152,'setFocus("%s")\n',b.id||b.nodeName),b.focus(),b.scrollIntoView())}}else this.S?this.Oa(hd(this,this.H.Za,1)):(this.$&&(this.H.m("%d instructions executed\n",this.$),this.$=0),this.H.Oa(this.H.toString()),this.S==void 0&&this.J&&(a=this.Ta(Oa.ib,!0))&&a.focus());this.J++}};
function Sd(a,b){var c=a.J,d=JSON.stringify(a.X.ka());a.J=c;b||(b=a.Y);b.indexOf(".")<0&&(b+=".json");return Ua(d,b)?a.K("saved %d bytes to %s\n",d.length,b):d+"\n"}l.ka=function(a){a.push(this.R);a.push(Jd(this,!0));a.push(this.X.ra)};l.Ob=function(a,b,c){var d=this.K,e=Nd(this,a);b=b.shift();rd(this,a,1);return d.call(this,"%s %02x       unsupported       ; %s\n",e,b,c||"")};
var Wd="b?\t\tbreak commands;d?\t\tdump commands;e[o] [addr] ...\tedit memory/ports;g    [addr]\trun (to addr);h\t\thalt;p    [expr]\tparse expression;r?   [value]\tdisplay/set registers;s?\t\tset commands;save [file]\tsave machine state;t[r] [n]\tstep (n instructions);u    [addr] [n]\tunassemble (at addr)".split(";"),Td="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write;bm [on|off]\tbreak on message;bn [count]\tbreak on instruction count".split(";"),
Ud="db  [addr]\tdump bytes (8 bits);dw  [addr]\tdump words (16 bits);dd  [addr]\tdump dwords (32 bits);di  [addr]\tdump input ports;d*y [addr]\tdump values in binary;dh  [n] [l]\tdump instruction history buffer;ds\t\tdump machine state".split(";"),Vd=["sh [on|off]\tset instruction history","sp [n]\t\tset speed multiplier","ss\t\tset debugger style"],sd={Ec:1,xd:0,yd:2,kg:0},S={Ba:0,ab:1,Ua:2,Va:3},Xd={},Ed=(Xd[S.Ba]="br",Xd[S.ab]="bw",Xd[S.Ua]="bi",Xd[S.Va]="bo",Xd),Yd={wd:"PC"},Zd={BYTE:1,vd:2,zd:4,
rc:5,Zb:6,Ld:7},od={"=":Zd.Ld,1:Zd.BYTE,2:Zd.vd,4:Zd.zd,"@":Zd.rc,";":Zd.Zb},Rd=1E5,Bd={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},Ad={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};function $d(a,b,c){id.call(this,a,b,c)}w($d,id);
function ae(a,b,c){id.call(this,a,b,c);this.model=+this.config.model||be;this.T=+this.config.addrReset||0;this.u=P(this,"Bus");this.u.I=this.rd.bind(this);this.de=P(this,"IOPage");P(this,"Panel",!1);this.J=0;this.Xa=null;this.input=P(this,"Input",!1);this.model<=ce?(this.Kc=this.Rd,this.Mc=~(de|ee|fe|ge)&65535,this.Sb=0):(this.Kc=this.Sd,this.Mc=~(de|(this.model<=he?ee:0))&65535,this.Sb=this.model>he?ee:0);this.Cb=this.Bb=this.na=0;this.l=null;this.Qa=[];ie(this)}w(ae,$d);
function ie(a){a.ca=65536;a.ha=32768;a.la=65535;a.ga=32768;a.W=15;a.h=[0,0,0,0,0,0,0,a.T,-1,-2,-3,-4,-5,-6,-7,-8];a.Z=[0,0,0,0,0,0];a.xa=[0,0,0,0];a.Fa=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];a.Ja=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];a.Na=
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];a.Oc=[0,0,0,0,0,0,0,0];a.i=0;a.v=-1;a.Nc=0;a.g=0;je(a);for(var b={La:0};b.La<=7;b={La:b.La},b.La++)N(a,"R"+b.La,function(c){return function(){return a.h[c.La]}}(b),function(c){return function(d){return a.h[c.La]=d&65535}}(b));wb(a,"R6","SP");wb(a,"R7",Yd.wd);N(a,"CF",function(){return a.ca&65536&&me?1:0},function(c){a.ca=c?65536:0});N(a,"NF",function(){return a.ga&32768&&ne?1:0},function(c){a.ga=c?32768:0});N(a,"VF",function(){return a.ha&
32768&&oe?1:0},function(c){a.ha=c?32768:0});N(a,"ZF",function(){return(a.la&65535?0:pe)?1:0},function(c){a.la=c?0:1});N(a,"PS",function(){return qe(a)},function(c){return re(a,c)});N(a,"PI",function(){return a.va},function(c){if(c&=se){var d=c>>te;do c+=ue;while(d>>=1);a.g|=ve}a.va=c});N(a,"ER",function(){return a.ua});N(a,"SL",function(){return a.M&65280},function(c){a.M=c|255});N(a,"M0",function(){return we(a)},function(c){return xe(a,c)});N(a,"M1",function(){return ye(a)});N(a,"M2",function(){return ze(a)});
N(a,"M3",function(){return a.I},function(c){return Ae(a,c)})}function je(a){a.j=0;a.oa=0;a.qa=0;a.I=0;a.ua=0;a.va=0;a.M=255;a.U=0;a.O=0;a.S=0;a.L=262143;a.Lc=[4,2,0,1];a.N=a.h[7];a.o=0;a.l=null;Be(a);for(var b=a.u,c=R.Sa,d=0,e=0;e<b.g.length;e++){var f=b.g[e];f.type&c&&(d=f.ia+f.size)}a.ce=d}l=ae.prototype;l.Wc=function(){};function we(a){var b=a.j;b&Ce||(b=b&~(De|Ee|Fe)|a.O<<5|a.S<<1);return b}
function xe(a,b){b&=~De;if(a.j!=b){b&Ce&&!(a.j&Ce)&&(a.oa=a.o>>16&65535,a.qa=a.o&65535);a.j=b;a.O=(b&Fe)>>Ge;a.S=(b&Ee)>>He;var c=0;b&(Ie|Je)&&(c=Ke,b&Ie&&(c|=Le));a.U!=c&&(a.U=c,Be(a))}}function ye(a){a.j&Ce||(a.oa=a.o>>16&65535);a=a.oa;a&65280&&(a=(a<<8|a>>8)&65535);return a}function ze(a){a.j&Ce||(a.qa=a.o&65535);return a.qa}function Ae(a,b){a.model<be&&(b&=~(Me|Ne));a.I!=b&&(a.I=b,a.L=b&Me?Oe:Pe,Be(a))}
function Be(a){a.Xa&&Yc(a.u,a.J,a.Xa);a.U?(a.Ra=Qe,a.J=a.I&Me?Re:Se,a.Ya=a.we,a.Uc=a.Te):(a.Ra=0,a.J=Te,a.Ya=a.ve,a.Uc=a.Se);a.Xa=Yc(a.u,a.J,a.de)}
l.ja=function(a){if(!a||!a.length)return this.m("invalid saved state\n"),!1;var b=a.shift(),c=a.shift();if(b!=this.R||(c|0)!==3)return this.m("CPU state mismatch (%s %3.2f)\n",b,c),!1;try{this.h=a.shift();this.Z=a.shift();this.xa=a.shift();this.Fa=a.shift();this.Ja=a.shift();this.Na=a.shift();this.Oc=a.shift();this.ua=a.shift();this.Nc=a.shift();this.va=a.shift();this.M=a.shift();this.O=a.shift();this.S=a.shift();this.N=a.shift();this.g=a.shift();this.o=a.shift();this.v=a.shift();this.Bb=a.shift();
this.Cb=a.shift();this.T=a.shift();re(this,a.shift());xe(this,a.shift());this.oa=a.shift();this.qa=a.shift();Ae(this,a.shift());for(var d=a.shift(),e=d.length-1;e>=0;e--){a:{for(a=0;a<this.Qa.length;a++){var f=this.Qa[a];if(f.sb===d[e]){var g=f;break a}}g=null}g&&(g.next=this.l,this.l=g)}}catch(h){return this.m("CPU state error: %s\n",h.message),!1}return!0};
l.ka=function(a){a.push(this.R);a.push(3);a.push(this.h);a.push(this.Z);a.push(this.xa);a.push(this.Fa);a.push(this.Ja);a.push(this.Na);a.push(this.Oc);a.push(this.ua);a.push(this.Nc);a.push(this.va);a.push(this.M);a.push(this.O);a.push(this.S);a.push(this.N);a.push(this.g);a.push(this.o);a.push(this.v);a.push(this.Bb);a.push(this.Cb);a.push(this.T);a.push(qe(this));a.push(we(this));a.push(ye(this));a.push(ze(this));a.push(this.I);for(var b=a.push,c=[],d=this.l;d;)c.push(d.sb),d=d.next;b.call(a,c)};
function Ue(a,b,c){b={sb:b,priority:4,message:c||0,name:Ve[b],next:null};a.Qa.push(b);return b}function We(a,b){if(b){if(b!=a.l){var c=a.l;if(!c||c.priority<=b.priority)b.next=c,a.l=b;else{do{var d=c.next;if(!d||d.priority<=b.priority){b.next=d;c.next=b;break}c=d}while(c)}}a.g|=ve;a.m(1024+b.message,"setIRQ(vector=%o,priority=%d)\n",b.sb,b.priority+")")}}function qe(a){return a.W=a.W&(ge|fe|ee|Xe|Ye)|(a.ga&32768?ne:0)|(a.la&65535?0:pe)|(a.ha&32768?oe:0)|(a.ca&65536?me:0)}
function re(a,b){b&=a.Mc;a.ga=b<<12;a.la=~b&4;a.ha=b<<14;a.ca=b<<16;if((b^a.W)&a.Sb)for(var c=a.Z.length;--c>=0;){var d=a.h[c];a.h[c]=a.Z[c];a.Z[c]=d}a.i=b>>Ze&$e;c=a.W>>Ze&$e;a.i!=c&&(a.xa[c]=a.h[6],a.h[6]=a.xa[a.i]);a.W=b;a.g&=~af;a.g|=a.l?af:ve}l.rd=function(a,b){b<=3&&(this.H.ua|=bf);cf(this,df,0,a)};
function cf(a,b,c,d){a.m(4096,"trap to vector %o (%o: %s)\n",b,d,d<0?ef[-d]:"BUS ERROR");if(!a.na){a.v<0?a.v=qe(a):a.i||(d=ff);d==ff&&(a.g&gf&&(d=hf),a.g|=gf,a.ua|=jf,a.h[6]=b=4);if(d!=hf){a.o=b|4143316992;a.i=0;var e=a.Ya(b|a.Ra),f=a.Ya(b+2&65535|a.Ra);re(a,f&~fe|a.v>>2&fe);kf(a,a.v);kf(a,a.h[7]);a.h[lf]=e&65535}a.g&=~(c|mf|nf);a.g|=ve|of;a.v=-1;a.Bb=d;a.Cb=b;d==hf&&Dc(a.time);if(d>=ff)throw b;}}function pf(a,b){var c=b>>13&31;c<31&&(b=a.I&Ne?a.Na[c]+(b&8191)&Oe:b&~qf);return b}
function rf(a,b,c){if(!(c&a.U)){var d=b&65535;d>=Te&&(d|=a.J);return d}var e=b>>13;a.I&a.Lc[a.i]||(e&=7);var f=a.Ja[a.i][e];d=(a.Fa[a.i][e]<<6)+(b&8191)&a.L;d>=qf&&(d=pf(a,d));if(a.na)return d;d>=a.ce&&d<a.J?(a.ua|=sf,cf(a,df,0,d)):d&1&&!(c&tf)&&(a.ua|=uf,cf(a,df,0,d));var g=0;switch(f&vf){case wf:g=xf;case yf:f|=zf;c&Ke&&(g=Af);break;case Bf:g=xf;case Cf:c&Ke&&(g=xf);case Df:f|=c&Ke?zf|Ef:zf;break;default:g=Ff}(f&(Gf|Hf))!=Gf&&(f&Hf?f&Gf&&(b&8128)<(f>>2&8128)&&(g|=If):(b&8128)>(f>>2&8128)&&(g|=If));
a.Ja[a.i][e]=f;if(d!=((Re|Jf)&a.L)||a.i)a.O=a.i,a.S=e;g&&(g&Ce&&(a.v>=0&&(g|=Kf),a.j&Ce||(g|=a.j&xf|a.O<<5|a.S<<1,xe(a,a.j&~Lf|g&Lf)),cf(a,Mf,Nf,Of)),a.j&(Ce|xf)||!(d<((Re|Pf)&a.L)||d>((Re|Qf|1)&a.L))||(a.j|=xf,a.j&Rf&&(a.g|=Nf)));return d}function kf(a,b){var c=a.h[6]-2&65535;a.h[6]=c;a.o=a.o&65535|(a.o&-65536)<<8|16121856;a.g&gf||a.Kc(Sf,-2,c);a.Uc(c,b)}l.Rd=function(a,b,c){!this.i&&b<=0&&c<=this.M&&(this.g|=Tf)};
l.Sd=function(a,b,c){this.i||(c>=65534&&(c|=-65536),a&Ke&&c<=this.M&&(c<=this.M-32?cf(this,df,0,ff):(this.ua|=Uf,this.g|=Tf)))};l.ve=function(a){return this.u.pa(this.N=a)};l.we=function(a){return this.u.pa(this.N=rf(this,a,Vf))};l.Se=function(a,b){this.u.fa(this.N=a,b)};l.Te=function(a,b){this.u.fa(this.N=rf(this,a,Sf),b)};
l.toString=function(){var a="";if(this.aa)for(var b="R0 R1 R2 R3 R4 R5  SP PC PS PI SL NF ZF VF CF  M0 M1 M2 M3 ER  SR AR DR".split(" "),c=0;c<b.length;c++){var d=b[c];if(d){var e=16;d[1]=="F"&&(e=1);var f=zb(this,d);f!=void 0&&(a+=this.aa.K("%s=%*n ",d,e,f))}else a+="\n"}return a};
var ce=1120,he=1140,be=1170,$e=3,me=1,oe=2,pe=4,ne=8,Ye=16,Xe=224,de=1792,ee=2048,fe=12288,ge=49152,Ze=14,se=65024,ue=34,te=9,df=4,Mf=168,hf=-1,Of=-2,ff=-4,ef="UNKNOWN PANIC ABORT ILLEGAL RED YELLOW FAULT TRACE HALT OPCODE INTERRUPT".split(" "),ve=1,af=2,nf=3,mf=16,Tf=32,Nf=64,of=128,gf=256,lf=7,tf=1,Le=2,Ke=4,Qe=65536,jf=4,Uf=8,bf=16,sf=32,uf=64,Ie=1,Ee=30,Fe=96,Kf=128,Je=256,Rf=512,De=3072,xf=4096,Af=8192,If=16384,Ff=32768,Ce=57344,Lf=61694,He=1,Ge=5,Me=16,Ne=32,wf=1,yf=2,Bf=4,Cf=5,Df=6,vf=7,Hf=
8,Ef=64,zf=128,Gf=32512,Pf=62592,Jf=65402,Qf=65470,Ve={48:"DL11R",52:"DL11X",56:"PC11R",60:"PC11X",64:"KW11",112:"RL11",144:"RK11",180:"RX11"},Vf=0|Le,Sf=0|Ke,Te=57344,Se=253952,Re=4186112,Pe=262143,qf=3932160,Oe=4194303;E.PDP11=ae;function Wf(a,b,c){kd.call(this,a,b,c);this.va=Xf;this.O=[];this.H.model<he&&(this.O=this.O.concat(Yf));this.H.model<1145&&(this.O=this.O.concat(Zf));this.la=6}w(Wf,kd);
Wf.prototype.Ob=function(a,b,c){function d(B){var A=k.H,D=[];if(A.U){var O=A.i<<1,K=B>>13;K>7&&(O|=1);A.I&A.Lc[A.i]||(K&=7);var ke=B&8191,le=A.Fa[A.i][K]<<6;B=le+ke&A.L;B>=qf&&(B=pf(A,B));D.push(B);D.push(ke);D.push(O);D.push(K&7);D.push(le);D.push(A.L)}else B&=65535,B>=Te&&(B|=A.J),D.push(B);return null}function e(B){return $f[B]||"?"}function f(B,A){var D="",O=A&ag;if(O==U)D=a.V+((B&255)<<24>>23)&65535,D=h(D);else if(O==bg)D=a.V-((B&63)<<1)&65535,D=h(D);else if(O==cg)D=F(k,B&7,0,3,"");else if(O==
dg)D=F(k,B&63,0,6,"");else if(O==eg)D=F(k,B&255,0,8,"");else if(B&=A,A&W&&(B>>=6,A>>=6),A&X){O=null;var K=B&7;switch(B&56){case 0:D=e(K);break;case 8:D="@"+e(K);O=d(k.H.h[K]);break;case 16:K<7?D="("+e(K)+")+":(A=g(),D="#"+h(A));break;case 24:K<7?D="@("+e(K)+")+":(A=g(),D="@#"+h(A),O=d(A));break;case 32:D="-("+e(K)+")";break;case 40:D="@-("+e(K)+")";break;case 48:A=g();D=h(A)+"("+e(K)+")";K==7&&(D=h(A=A+a.V&65535),O=d(A));break;case 56:A=g(),D="@"+h(A)+"("+e(K)+")",K==7&&(D="@"+h(A=A+a.V&65535),B=
k.H,B.na++,A=B.u.pa(rf(B,A,Vf)),B.na--,O=d(A))}O&&(D=[D,O])}return D}function g(){var B=b.shift()|b.shift()<<8;m+=h(B)+" ";rd(k,a,2);return B}function h(B){return F(k,B,0,16,"")}var k=this,n=Nd(this,a),m="",r=qd(this,a,Zd.rc),p=qd(this,a,Zd.Zb),q=g(),v;for(y in this.va)if(v=this.va[y][q&y])break;v||(v=fg);var u=v[0];this.O.indexOf(u)>=0&&(v=fg,u=v[0]);var y=gg[u];var z="",C=v.length-1;u||C||(z=h(q));for(u=1;u<=C;u++){var V=v[u];if(V!=void 0){V=f(q,V);if(!V||!V.length){z="INVALID";break}typeof V!=
"string"&&(V=V[0]);z.length>0&&(z+=",");z+=V||"???"}}n=this.K("%s %-21s %-7s %s",n,m,y,z);c?p&&(c+=" "+p):p&&(c=p);c&&(n=this.K("%-32s; %s",n,c));r&&(n=r+":\n"+n);return n+"\n"};
var gg=".WORD ADC ADCB ADD ASL ASLB ASR ASRB BCC BCS BEQ BGE BGT BHI BIC BICB BIS BISB BIT BITB BLE BLOS BLT BMI BNE BPL BPT BR BVC BVS CCC CLC CLCN CLCV CLCVN CLCVZ CLCZ CLCZN CLN CLR CLRB CLV CLVN CLVZ CLVZN CLZ CLZN CMP CMPB COM COMB DEC DECB INC INCB HALT JMP JSR MARK MFPD MFPI MFPS MOV MOVB MTPD MTPI MTPS NEG NEGB NOP RESET ROL ROLB ROR RORB RTI RTS SBC SBCB SCC SEC SECN SECV SECVN SECVZ SECZ SECZN SEN SEV SEVN SEVZ SEVZN SEZ SEZN SUB SWAB SXT TST TSTB WAIT MUL DIV ASH ASHC XOR SOB EMT TRAP SPL IOT RTT MFPT".split(" "),$f=
"R0 R1 R2 R3 R4 R5 SP PC A0 A1 A2 A3 A4 A5 A6 A7 S0 S1 S2 S3 PS PI ER SL M0 M1 M2 M3 AR DR SR".split(" "),X=63,W=4032,U=4096,bg=8192,cg=12288,dg=24576,eg=32768,ag=61440,Xf={61440:{4096:[62,W,X],8192:[47,W,X],12288:[18,W,X],16384:[14,W,X],20480:[16,W,X],24576:[3,W,X],36864:[63,W,X],40960:[48,W,X],45056:[19,W,X],49152:[15,W,X],53248:[17,W,X],57344:[94,W,X]},65024:{2048:[57,448,X],28672:[100,X,448],29184:[101,X,448],29696:[102,X,448],30208:[103,X,448],30720:[104,448,X],32256:[105,448,bg]},65280:{256:[27,
U],512:[24,U],768:[10,U],1024:[11,U],1280:[22,U],1536:[12,U],1792:[20,U],32768:[25,U],33024:[23,U],33280:[13,U],33536:[21,U],33792:[28,U],34048:[29,U],34304:[8,U],34560:[9,U],34816:[106,eg],35072:[107,eg]},65472:{64:[56,X],192:[95,X],2560:[39,X],2624:[49,X],2688:[53,X],2752:[51,X],2816:[67,X],2880:[1,X],2944:[77,X],3008:[97,X],3072:[73,X],3136:[71,X],3200:[6,X],3264:[4,X],3328:[58,dg],3392:[60,X],3456:[65,X],3520:[96,X],35328:[40,X],35392:[50,X],35456:[54,X],35520:[52,X],35584:[68,X],35648:[2,X],
35712:[78,X],35776:[98,X],35840:[74,X],35904:[72,X],35968:[7,X],36032:[5,X],36096:[66,X],36160:[59,X],36224:[64,X],36288:[61,X]},65528:{128:[76,7],152:[108,cg]},65535:{0:[55],1:[99],2:[75],3:[26],4:[109],5:[70],6:[110],7:[111],160:[69],161:[31],162:[41],163:[33],164:[45],165:[36],166:[43],167:[35],168:[38],169:[32],170:[42],171:[34],172:[46],173:[37],174:[44],175:[30],176:[69],177:[80],178:[88],179:[82],180:[92],181:[85],182:[90],183:[84],184:[87],185:[81],186:[89],187:[83],188:[93],189:[86],190:[91],
191:[79]}},fg=[0],Yf=[58,60,65,96,110,100,101,102,103,104,105],Zf=[108,59,64];E.PDP11Dbg=Wf;function hg(a,b,c){bd.call(this,a,b,c);for(var d in ig){var e=ig[d];d=+d;a=e[0];b=e[1];c=e[2];e=e[3];d>=65472&&d<=65487&&(!a&&c&&(a=function(f){return function(g){return f(g)&255}}(c)),!b&&e&&(b=function(f){return function(g,h){return f(g,h)}}(e)));cd(this,this,d,d,a,b,c,e)}this.ta()}w(hg,bd);l=hg.prototype;l.sa=function(){this.H===void 0&&(this.H=P(this,"Debugger"))};
l.ja=function(a){return a&&(a=a.shift(),this.R==a)?!0:!1};l.ka=function(a){a.push(this.R)};l.se=function(a){a=a>>1&63;var b=this.H.Na[a>>1];return a&1?b>>16:b&65535};l.Pe=function(a,b){a=a>>1&63;var c=a>>1;this.H.Na[c]=a&1?this.H.Na[c]&65535|(b&63)<<16:this.H.Na[c]&-65536|b&65534};var jg={},ig=(jg[61568]=[null,null,hg.prototype.se,hg.prototype.Pe,"UNIMAP",64,be],jg);E.IOPage=hg;za.dl11=268435456;
function Y(a,b,c){M.call(this,a,b,c);this.O=+this.config.baudReceive||9600;this.S=+this.config.baudTransmit||9600;this.time=P(this,"Time");this.T=Mb(this.time,this.R+".receive",this.Xc.bind(this));this.U=Mb(this.time,this.R+".transmit",this.Ee.bind(this));this.ports=P(this,"IOPage");dd(this.ports,this,kg);this.j="";this.i=this.l=this.v=null;this.exports={connect:this.ee,receiveData:this.Xc,receiveStatus:this.ze,setConnection:this.Be};this.ta()}w(Y,M);l=Y.prototype;
l.ee=function(a){if(!this.i){var b=yb(this,"connection");if(b){var c=b.split("->");if(c.length==2){var d=c[0].trim();if(d!=this.R)return;c=c[1].trim();if(this.i=ub(this,c)){var e=this.i.exports;if(e){var f=e.connect;f&&f.call(this.i,this.L);if(this.l=e.receiveData){this.L=a;this.v=e.receiveStatus;this.m("Connected %s.%s to %s\n",this.Y,d,c);return}}}}this.m("Unable to establish connection: %s\n",b)}}};
l.ja=function(a){var b=a.shift();return this.R==b?(this.o=a.shift(),this.g=a.shift(),this.h=a.shift(),this.I=a.shift(),!0):!1};l.ka=function(a){a.push(this.R);a.push(this.o);a.push(this.g);a.push(this.h);a.push(this.I)};l.sa=function(){this.H||(this.H=P(this,"CPU"),this.M=Ue(this.H,this.N?-1:48,128),this.u=Ue(this.H,this.N?-1:52,128))};l.ta=function(){this.o=0;this.g=8192;this.h=128;this.I=[]};
l.Xc=function(a){a!=null&&(this.j=typeof a!="number"?a:this.j+String.fromCharCode(a));this.j&&(a=this.j.charCodeAt(0),this.m(128,"receiveByte(%#04x)\n",a),this.J?a=!1:(this.o=a,this.g&128?this.o|=49152:this.g|=128,this.g&64&&We(this.H,this.M),a=!0),a&&(this.j=this.j.substr(1)),this.j&&Rb(this.time,this.T,1E3/Math.round(this.O/10)));return!0};l.ze=function(a){var b=this.g;this.g&=-12289;a&va.ac.wa&&(this.g|=8192);a&va.Wb.wa&&(this.g|=4096);b!=this.g&&(this.g|=32768,this.g&32&&We(this.H,this.M))};
l.Be=function(a,b){return this.i?!1:(this.i=a,this.l=b,!0)};l.Ee=function(a){var b=!0;this.h|=128;this.h&64&&We(this.H,this.u);a&&(b=this.l?this.l.call(this.i,a):!1);return b};l.re=function(){var a=this.g&65534;this.g&=-32769;return a};l.Oe=function(a){var b=a^this.g;this.g=this.g&-112|a&111;this.v&&b&6&&(b=0,this.L?(b|=a&4?va.ac.wa:0,b|=a&2?va.dd.wa|va.Wb.wa:0):(b|=a&4?va.Bd.wa:0,b|=a&2?va.ed.wa:0),this.v.call(this.i,b))};l.qe=function(){this.g&=-129;return this.o};l.Ne=function(){};l.ye=function(){return this.h};
l.Ve=function(a){if(this.h&128)if(a&64)We(this.H,this.u);else{var b=this.H,c=this.u;if(c){var d=b.l;if(d==c)b.l=c.next;else for(;d;){var e=d.next;if(e==c){d.next=e.next;break}d=e}b.l&&(b.g|=ve);b.m(1024+c.message,"clearIRQ(vector=%o,priority=%d)\n",c.sb,c.priority+")")}}this.h=this.h&-70|a&69};l.xe=function(){return 0};
l.Ue=function(a){a:{a&=255;this.m(128,"transmitByte(%#04x)\n",a);if(this.W){if(a==19){this.J=!0;break a}if(a==17){this.J=!1;break a}}this.l&&this.l.call(this.i,a);Rb(this.H,this.U,1E3/Math.round(this.S/10))}this.h&=-129};var lg={},kg=(lg[65392]=[null,null,Y.prototype.re,Y.prototype.Oe,"RCSR"],lg[65394]=[null,null,Y.prototype.qe,Y.prototype.Ne,"RBUF"],lg[65396]=[null,null,Y.prototype.ye,Y.prototype.Ve,"XCSR"],lg[65398]=[null,null,Y.prototype.xe,Y.prototype.Ue,"XBUF"],lg);E.DL11=Y;za.pc11=536870912;
function Z(a,b,c){M.call(this,a,b,c);this.name=this.config.name||"PTR";this.h=yb(this,"autoLoad")||"";this.S=+this.config.baudReceive||3600;this.i=this.config.library||[];this.v=null;this.M=window&&"FileReader"in window;this.L=P(this,"Bus");this.time=P(this,"Time");this.T=Mb(this.time,this.R+".reader",this.Md.bind(this));this.input=P(this,"Input");this.I=null;this.o=this.g=0;this.J=32768;this.j=this.O=0;this.u=[];this.l=mg;this.N=-1;this.ports=P(this,"IOPage");dd(this.ports,this,ng);ab(this,this.i,
this.he.bind(this))||Bb(this,!1)}w(Z,M);l=Z.prototype;
l.Ka=function(a,b){var c=this,d=mg;switch(a){case "readTape":d=og;case "loadTape":d||(d=pg);b.onclick=function(){var e=c.ba[qg];e&&(e=c.i[e.selectedIndex])&&rg(c,e,d)};break;case "mountTape":this.M?(b.addEventListener("change",function(){var e=b.children[0];e.children[1].disabled=!e.children[0].files.length}),b.onsubmit=function(e){(e=e.currentTarget[1].files[0])&&rg(c,{name:Ka(e.name,!0),path:e.name},pg,e);return!1}):(this.m("Local tape support not available\n"),b.parentNode.removeChild(b))}M.prototype.Ka.call(this,
a,b)};l.ge=function(){var a=this.ba[sg],b=this.ba[qg],c=b.options[b.selectedIndex];if(a&&c){b={};if(c=c.getAttribute("data-value"))try{b=eval("("+c+")")}catch(d){this.m("PC11 option error: %s",d.message)}c=b.desc;c===void 0&&(c="");b=b.href;b!==void 0&&(c='<a href="'+b+'" target="_blank">'+c+"</a>");a.innerHTML=c}};l.ja=function(a){a=a.shift();return this.R==a?!0:!1};l.ka=function(a){a.push(this.R)};l.sa=function(){this.H||(this.H=P(this,"CPU"),this.I=Ue(this.H,56,536870912))};
l.ta=function(){this.g&=-2241;this.o=0};
function rg(a,b,c,d){var e=b.name,f=b.path;a.m(536870912,'load("%s","%s")\n',e,f);if(!f)return tg(a),!0;if(f==ug)return Ta(a,'Use "Choose File" and "Mount" to select and load a local tape.'),!0;if(f==vg){f=window.prompt("Enter the URL of a remote tape image.","")||"";if(!f)return!1;e=Ka(f);a.m('Attempting to load %s as "%s"',f,e)}a.l=c;if(d){var g=new FileReader;g.onload=function(){var h=g.result;h&&(b.values=new Uint8Array(h,0,h.byteLength),a.Jb(b));wg(a)};g.readAsArrayBuffer(d);return!1}if(!b.values&&
!ab(a,b.path,a.Jb.bind(a)))return!1;a.Jb(b);return!0}function wg(a){if(a.v){var b=a.ba[qg];if(b&&b.options){var c;for(c=0;c<b.options.length;c++)if(b.options[c].value==a.v.path){b.selectedIndex!=c&&(b.selectedIndex=c);break}c==b.options.length&&(b.selectedIndex=0)}}}function xg(a,b){b|=0;if(b!==a.N){var c=a.ba[yg];c&&(c=(c=c.getElementsByClassName(zg))&&c[0])&&c.style&&(c.style.width=b+"%");a.N=b}}
l.he=function(a){a=this.i=a||[];var b=this.ge.bind(this),c=qg,d=this.ba[c];if(d){for(var e=0;e<a.length;e++)Sb(this,c,a[e].name,a[e].path);b&&(d.onchange=b)}Sb(this,qg,"None",Ag,!0);this.M&&Sb(this,qg,"Local Tape",ug);Sb(this,qg,"Remote Tape",vg);Bb(this,!0);if(this.h&&typeof this.h=="string"){for(a=0;a<this.i.length;a++)if(b=this.i[a],typeof b=="object"&&b.name==this.h){this.h=b;break}a==this.i.length&&(Ta(this,"Unable to find %s media: %s",this.R),this.h="")}this.h?rg(this,this.h,pg)||Bb(this,!1):
wg(this)};
l.Jb=function(a){var b=a.name,c=a.values,d=a.addrLoad,e=a.addrExec;this.v=a;Bb(this,!0);if(this.l==og){var f=e,g=a=!1;e=!1;if(d==null)for(var h=0;h<c.length-1;){var k=c[h]&255|(c[h+1]&255)<<8;if(k)if(k&255){var n=h;if(k!=1){this.m(536870912,"invalid signature (%#06x) at offset %#06x\n",k,n);break}if(h+6>=c.length){this.m(536870912,"invalid block at offset %#06x\n",n);break}h+=2;var m=c[h++]&255|(c[h++]&255)<<8,r=c[h++]&255|(c[h++]&255)<<8;k+=(m&255)+(m>>8)+(r&255)+(r>>8);for(var p=h,q=m-=6;m>0&&h<
c.length;)k+=c[h++]&255,m--;if(m!=0||h>=c.length){this.m(536870912,"insufficient data for block at offset %#06x\n",n);break}k+=c[h++]&255;if(k&255){this.m(536870912,"invalid checksum (%#04x) for block at offset %#06x\n",k,n);break}if(q)for(this.m(536870912,"loading %#06x bytes at %#06x-%#06x\n",q,r,r+q);q--;)this.L.fb(r++,c[p++]&255);else r&1?g=!0:f==null&&(f=r),f!=null&&this.m(536870912,"starting address: %#06x\n",f);e=!0}else h++;else h+=2}if(!e&&(d==null&&(d=null),d!=null)){for(e=0;e<c.length;e++)this.L.fb(d+
e,c[e]);e=!0}if(e){if(f==null||g)Dc(this.time),a=!1;if(f!=null&&(c=this.H,d=f,c.T=d,c.h[lf]=d&65535,re(c,0),je(c),a)){c.h[0]=0;for(a=1;a<=5;a++)c.h[a]=0;c.h[6]=1024}}e?this.m('Read tape "%s"',b):Ta(this,'No valid memory address for tape "%s"',b)}else this.j=0,this.u=c,this.g&=-32769,this.m('Loaded tape "%s" (%d bytes)',b,c.length),xg(this,0)};function tg(a){a.v=null;a.l&&a.m(a.l==pg?"tape detached":"tape unloaded");a.l=mg;wg(a)}
l.Md=function(){(this.g&32769)!=1||this.g&128||(this.j<this.u.length?(this.o=this.u[this.j]&255,this.m(536870912,"%s.advanceReader(%d): %#02x\n",this.R,this.j,this.o),this.j++,xg(this,this.j/this.u.length*100)):this.g|=32768,this.g|=128,this.g&=-2049,this.g&64&&We(this.H,this.I))};l.pe=function(){return this.g&65534};l.Me=function(a){a&1&&(this.g&32768?(a&=-2,this.g&64&&We(this.H,this.I)):(this.g&=-129,this.g|=2048,this.o=0,Rb(this.time,this.T,1E3/Math.round(this.S/10))));this.g=this.g&-66|a&65};
l.oe=function(){this.g&=-129;this.g|=2048;return this.o};l.Le=function(){};l.ne=function(){return this.J};l.Ke=function(a){this.J=this.J&-65|a&64};l.me=function(){return this.O};l.Je=function(a){this.O=a&255};
var Ag="",ug="?",vg="??",mg=0,pg=1,og=2,qg="listTapes",sg="descTape",yg="readProgress",zg="progressBar",Bg={},ng=(Bg[65384]=[null,null,Z.prototype.pe,Z.prototype.Me,"PRS"],Bg[65386]=[null,null,Z.prototype.oe,Z.prototype.Le,"PRB"],Bg[65388]=[null,null,Z.prototype.ne,Z.prototype.Ke,"PPS"],Bg[65390]=[null,null,Z.prototype.me,Z.prototype.Je,"PPB"],Bg);E.PC11=Z;
function Cg(a,b,c){M.call(this,a,a);var d=this;this.j=!1;this.v=c;this.i="";this.u=this.o=!1;this.h=void 0;Bb(this,!1);this.ra=0;b=b.trim();b[0]=="{"?Dg(this,b):(this.i=b,bb(this.i,function(e,f,g,h){g==4&&(!h&&f?(Dg(d,f),Eg(d)):d.m("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.u=!0;Eg(d)});window.addEventListener(fb("iOS")?"pagehide":fb("Opera")?"unload":"beforeunload",function(){if(d.l){var e=d.ka();if(cb(d)){e=JSON.stringify(e);try{window.localStorage.setItem(d.Y,
e)}catch(f){d.m("%s\n",f.message)}}}d.sa(!1)});window.addEventListener("pageshow",function(){d.j||d.sa(!0)})}w(Cg,M);l=Cg.prototype;l.Ka=function(a,b){var c=this;switch(a){case Fg:b.onclick=function(){c.sa()};break;case Gg:b.onclick=function(){c.ta()}}M.prototype.Ka.call(this,a,b)};
function Eg(a){var b=!0;if(a.o&&a.u){var c=a.config.state;if(c&&typeof a.h!="string")a.h===void 0&&(a.h=null,bb(c,function(f,g,h,k){if(h==4){a.h="";if(!k&&g)try{JSON.parse(g),a.h=g}catch(n){a.m("error parsing state file %s: %s\n",f,n.message)}else a.m("error (%d) loading state file: %s\n",k,f);Eg(a)}}));else{for(var d in a.g){c=void 0;var e=a.g[d];try{c=e["class"],E[c]?c=="Machine"?(a.m("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2026 Jeff Parsons <Jeff@pcjs.org>"),a.i&&a.m("Configuration: %s\n",
a.i)):new E[c](a.Y,d,e):a.m('unrecognized %s device "%s"\n',c,d)}catch(f){e.optional||(a.m('error initializing %s device "%s": %s\n',c,d,f.message),b=!1),Db(a,d)}}d=a.l?gb(a):null;!d&&a.h&&(d=JSON.parse(a.h),a.m("Initial state: %s\n",a.config.state));d&&a.ja(d);Bb(a,!0);Cb(a,a.sa.bind(a,b))||a.m("machine %s not ready to power, waiting for device(s)\n",a.Y)}}}
function Dg(a,b){try{a.g=JSON.parse(b);var c=a.g[a.Y];if(!c){var d=Ka(a.i,!0);c=a.g[d];if(!c){var e=Object.keys(a.g).filter(function(k){return a.g[k]["class"]=="Machine"});e.length==1&&(d=e[0],c=a.g[d])}if(!c)throw Error("configuration missing machine ID");e={};for(var f in a.g)e[f==d?a.Y:f]=a.g[f];a.g=e}vb(a,c,["autoSave","autoStart"]);a.l=a.config.autoSave!==!1;a.I=a.config.autoStart!==!1;if(a.v){var g=eval("("+a.v+")"),h;for(h in g)a.config[h]=g[h]}a.o=!0}catch(k){c=k.message,(d=c.match(/position ([0-9]+)/))&&
(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.m("machine '%s' initialization error: %s\n",a.Y,c)}}l.ja=function(a){var b=!0;xb(this,function(c){return c.Ib&&!c.Ib(a)?(c.m('unable to restore state for device "%s"\n',c.R),b=!1):!0});return b};l.ka=function(){var a=[];xb(this,function(b){b.eb&&b.eb(a);return!0});return a};
l.sa=function(a){a=a===void 0?!this.j:a;if(Ab(this)){var b=this;a&&this.m("power on\n");xb(this,function(c){c.sa&&c!=b&&(c.config["class"]!="CPU"||b.I&&Ab(b)?c.sa(a):c.time.update(!0));return!0});(this.j=a)||this.m("power off\n")}};l.ta=function(){if(Ab(this)){var a=this;xb(this,function(b){b.ta&&b!=a&&b.ta();return!0});this.m("reset\n");this.h&&this.ja(JSON.parse(this.h))&&this.m("Initial state restored: %s\n",this.config.state)}};var Fg="power",Gg="reset";
window.PDP11v3=function(a,b,c){var d=new Cg(a,b,c);window.command=function(e){return hb(d,e)};return d};E.Machine=Cg;})()

//# sourceMappingURL=pdp11v3.js.map
