(function(){/*
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/dl11.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/pc11.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/defines.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/message.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdlib.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdio.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/webio.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/device.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/input.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/led.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/time.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/bus.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/memory.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/ports.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/ram.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/rom.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/cpu.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/debugger.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/pdp11ops.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/pdp11.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/pdp11dbg.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/dec/pdp11/modules/v3/iopage.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/machine.js (C) 2012-2024 Jeff Parsons
*/
var l;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)a=b.call(a);else if("number"==typeof a.length)a={next:aa(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ea(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var fa=ea(this);function u(a,b){if(b)a:{var c=fa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&da(c,a,{configurable:!0,writable:!0,value:b})}}var ha;
if("function"==typeof Object.setPrototypeOf)ha=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},ka={};try{ka.__proto__=ja;ia=ka.a;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var la=ha;
function w(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ag=b.prototype}function ma(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
u("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});u("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
u("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});u("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
u("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.v=f;da(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.v};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=fa[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&da(d.prototype,a,{configurable:!0,writable:!0,value:function(){return na(aa(this))}})}return a});function na(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function oa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}u("Array.prototype.keys",function(a){return a?a:function(){return oa(this,function(b){return b})}});
u("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function pa(a){return a?a:Array.prototype.fill}u("Int8Array.prototype.fill",pa);u("Uint8Array.prototype.fill",pa);u("Uint8ClampedArray.prototype.fill",pa);u("Int16Array.prototype.fill",pa);u("Uint16Array.prototype.fill",pa);u("Int32Array.prototype.fill",pa);
u("Uint32Array.prototype.fill",pa);u("Float32Array.prototype.fill",pa);u("Float64Array.prototype.fill",pa);u("Number.parseInt",function(a){return a||parseInt});u("Array.prototype.values",function(a){return a?a:function(){return oa(this,function(b,c){return c})}});function qa(){this.S=""}var ra,sa=new ArrayBuffer(2);(new DataView(sa)).setUint16(0,256,!0);ra=256===(new Uint16Array(sa))[0];
var ta={xd:{Va:4,ta:16},$b:{Va:5,ta:32},$c:{Va:6,ta:64},Vb:{Va:8,ta:256},ad:{Va:20,ta:1048576},ig:{Va:22,ta:4194304}},ua={lg:"undefined"!=typeof window,node:"undefined"!=typeof window?{}:global,process:"undefined"!=typeof process?process:{},window:"undefined"!=typeof window?window:global,document:"undefined"!=typeof document?document:{},ob:{machines:{},components:[],commands:{},files:null}};ua.window.PCjs?ua.ob=ua.window.PCjs:ua.window.PCjs=ua.ob;
var va=ua.process,wa=ua.ob.machines,xa=ua.ob.components,x={};x.Defines=qa;var ya={all:0xffffffffffff,addr:1,bus:2,fault:4,memory:8,ports:16,chips:32,kbd:64,serial:128,misc:256,cpu:512,mmu:2048,"int":1024,trap:4096,video:8192,monitor:16384,screen:32768,disk:131072,file:65536,time:262144,timer:524288,event:1048576,input:2097152,key:4194304,mouse:8388608,touch:16777216,info:274877906944,warn:549755813888,error:1099511627776,halt:70368744177664,buffer:0x800000000000};
function za(){this.v={};for(var a=0;23>a;a++)this.v["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}za.prototype.g=function(a,b){return this.v[a]?!1:(this.v[a]=b,!0)};
function Aa(){var a=ma.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,ba(a)));return a}
za.prototype.L=function(a){var b=ma.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(void 0===this.v[g])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];"%"!=g&&e++}else h=b[b.length-1];var k=!1,n=d[f+1],m=0<=n.indexOf("#"),r=0<=n.indexOf("0"),p=d[f+2];"*"==p?(p=h,h=e<b.length?b[e++]:b[b.length-1]):p=+p||0;var q=d[f+3];q=q?+q.substr(1):-1;var v=d[f+4],
t=null,y=0,z="",G=0<="ACDFGHMNSTWY".indexOf(g)&&"object"!=typeof h?Aa(h):h;switch(g){case "C":c+=isNaN(G.getTime())?void 0:this.L("%#W, %#F %#D, %#Y".replaceAll("#",m?"#":""),G);continue;case "D":h=m?G.getUTCDate():G.getDate();g="d";break;case "A":case "G":case "H":h=m?G.getUTCHours():G.getHours();"A"==g?(h=12>h?"am":"pm",g="s"):("G"==g&&(h=h?12<h?h-12:h:12),g="d");break;case "F":case "M":h=m?G.getUTCMonth():G.getMonth();"F"==g?(h=Ba[h],g="s"):(h++,g="d");break;case "N":h=m?G.getUTCMinutes():G.getMinutes();
g="d";break;case "S":h=m?G.getUTCSeconds():G.getSeconds();g="d";break;case "T":c+=isNaN(G.getTime())?void 0:this.L("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",m?"#":""),G);continue;case "W":h=Ca[m?G.getUTCDay():G.getDay()];g="s";break;case "Y":h=m?G.getUTCFullYear():G.getFullYear(),0<q&&(h%=Math.pow(10,q)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=q&&(r=!0,p<q&&(p=q),q=-1);case "f":h=+h;g=h+"";0<=q&&(g=h.toFixed(q));g.length<p&&(r?(0>h&&(p--,g=g.substr(1)),
g=("0".repeat(p)+g).slice(-p),0>h&&(g="-"+g)):g=(" ".repeat(p)+g).slice(-p));c+=g;break;case "j":c+=JSON.stringify(h,null,p||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=q&&(h=h.substr(0,q));h.length<p;)h=0<=n.indexOf("-")?h+" ":" "+h;c+=h;break;case "B":y=2,m&&(z="0b");case "o":y||(y=8),!z&&m&&(z="0o");case "X":t=Da;case "x":g="";y||(y=16);!z&&m&&(z="0x");t||(t=Ea);"string"==typeof h&&"-"==h[0]&&(k=!0,h=
h.slice(1));h=Math.trunc(h);k&&(h=-h);0>h&&((h|0)==h?h>>>=0:Math.abs(h)<=Math.pow(2,53)&&(h+=Math.pow(2,53)));0<=q&&(r=!0,p<q&&(p=q));r&&!p&&("b"==v?p=2:"h"==v||"w"==v?p=4:"l"==v?p=8:(p=Math.abs(h),p=255>=p?2:65535>=p?4:4294967295>=p?8:9),p+=z.length);p-=z.length;do k=16,Number.isNaN(h)||(k=h&y-1,h=Math.trunc(h/y)),r||!g||k||h?g=t[k]+g:(z&&(g=z+g,z=""),0<p&&(g=" "+g));while(0<--p||h);c+=z+g;break;case "%":c+="%";break;default:c=this.v[g]?c+this.v[g](g,n,p,q,h):c+("(unimplemented sprintf type: %"+
g+")")}}}return c+=d[f]};var Ca="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Ba="January February March April May June July August September October November December".split(" "),Ea="0123456789abcdef?",Da="0123456789ABCDEF?";function Fa(){qa.apply(this,arguments)}w(Fa,qa);
function Ga(a,b){if(a){b||(b=10);var c,d=0<a.indexOf(",");d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);"#"==c?(b=8,c=""):"$"==c&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),"0b"==c&&d||"^B"==c?(b=2,c=""):"0o"==c||"^O"==c?(b=8,c=""):"^D"==c?(b=10,c=""):"0x"==c&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);"Y"==c||"y"==c?(b=2,c=""):"."==c?(b=10,c=""):"H"==c||"h"==c?(b=16,c=""):"K"==c?c="000":"M"==c?c="000000":"G"==c&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var f;e=0;10>=b&&(c=a.match(/(-?[0-9]+)B([0-9]*)$/))&&
(a=c[1],e=35-((c[2]||35)&255));if((b&&10!=b?16==b?null!==a.match(/^-?[0-9a-f]+$/i):8==b?null!==a.match(/^-?[0-7]+$/):2==b&&null!==a.match(/^-?[01]+$/):null!==a.match(/^[+-]?[0-9]+$/))&&!isNaN(f=parseInt(a,b))){e&&(0>f&&(f+=Math.pow(2,36)),f=0<e?f*Math.pow(2,e):Math.trunc(f/Math.pow(2,-e)));var g=f}}return g}
function D(a,b,c,d,e){d=void 0===d?0:d;var f=void 0===f?0:f;var g="",h="",k=-1;c||(c=a.fa||10);d&&(k=Math.ceil(d/Math.log2(c)));if(void 0==e)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:h=".";default:e=""}isNaN(b)||"number"!=typeof b?(b=void 0,e=h=""):(0>b&&-1<b&&(b=-1),d&&(0>b&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(k=Math.ceil(Math.log(b)/Math.log(c)))));for(a=f||-1;k--;){a||(g=","+g,a=f);if(void 0==b){if(g="?"+g,0>k)break}else if(d=b%c,b=Math.trunc(b/c),d+=0<=d&&9>=d?48:55,g=String.fromCharCode(d)+
g,!b&&0>k)break;a--}return e+g+h}function Ha(a,b){var c=a/E|0,d=b/E|0;return(a&b)==(b|0)&&(c&d)==d}var E=Math.pow(2,32);x.StdLib=Fa;function F(){Fa.call(this);this.gb=new za;this.Cc=this.gb.g.bind(this.gb);this.L=this.gb.L.bind(this.gb)}w(F,Fa);F.prototype.flush=function(){var a=Ia;Ia="";this.Na(a)};function Ja(a,b){var c=a,d=a.lastIndexOf("/");0<=d&&(c=a.substr(d+1));d=c.indexOf("&");0<d&&(c=c.substr(0,d));b&&(d=c.lastIndexOf("."),0<d&&(c=c.substring(0,d)));return c}
F.prototype.Na=function(a,b){var c=a.length,d=a.lastIndexOf("\n");b?0<=d&&(b=Date.now(),Ka||(Ka=b),a=((b-Ka)/1E3).toFixed(3)+": "+a,c=a.length):"node"==this.S?(va.zg.write(a),a=""):(0<=d&&(console.log(Ia+a.slice(0,d)),Ia="",a=a.slice(d+1)),Ka=null);Ia+=a;return c};F.prototype.o=function(a){return this.Na(this.L.apply(this,[a].concat(ba(ma.apply(1,arguments)))))};var Ia="",Ka=null;x.StdIO=F;
function La(a){F.call(this);this.ca={};this.pa=0;this.X=this;a&&(this.X.pa=0,this.X.Ha=[],this.X.Ea=0,this.X.hb={},this.X.sg=!1)}var Ma;w(La,F);l=La.prototype;l.Ja=function(a,b){var c=this,d=this;this.ca[a]=b;switch(a){case Na.Wc:b.onclick=function(){var e=c.Sa(Na.ib,!0);e&&(e.value="")};break;case Na.ib:Oa(b),b.addEventListener("keydown",function(e){Pa(d,e,!0)}),b.addEventListener("keypress",function(e){Pa(d,e)})}};function Qa(a,b){var c=Ra.Xb;a.X.hb[c]||(a.X.hb[c]=[]);a.X.hb[c].push(b)}
function Sa(a,b,c){var d=!1;"boolean"==typeof b&&(d=b,b=c.shift());if(b=a.L.apply(a,[b].concat(ba(c))))a.o("%s\n",b),d||alert(b)}function Oa(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}l.error=function(a,b){Sa(this,"%s",this.L.apply(this,[a].concat(ba(b))))};l.Sa=function(a){return this.ca[a]};
function Ta(a){var b=window;if(b){do{for(var c=0;c<Ua.length;c++){var d=Ua[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Va(a,b){return a.H.bindings&&a.H.bindings[b]}function Wa(a){if(a=a.ca[Xa])var b=a.textContent;return b}function Ya(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function H(a,b,c,d){a=a.H[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}function Za(a,b,c){if("string"==typeof b)return $a(b,function(d,e,f,g){var h=!1;if(g){h=0>g;var k=d}else{if(4!=f)return;try{var n=JSON.parse(e)}catch(m){k=m.message||"unknown error"}}k&&Sa(a,h,"Unable to load %s media (error %d: %s)");c(n)}),!1;c(b);return!0}
function $a(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function ab(a){if(void 0===bb.vb){var b=!1;if(window)try{window.localStorage.setItem(bb.Ya,bb.Ya),b=window.localStorage.getItem(bb.Ya)==bb.Ya,window.localStorage.removeItem(bb.Ya)}catch(c){a.o("%s\n",c.message),b=!1}bb.vb=b}return!!bb.vb}function cb(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.pa;return-1==(b|1)||Ha(a.X.pa,b)?!0:!1}
function db(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function eb(a){var b=null;if(ab(a)){var c;if(window)try{(c=window.localStorage.getItem(a.Y))&&(b=JSON.parse(c))}catch(d){a.o("%s\n",d.message)}}return b}
function Pa(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.X,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==I.Tb&&f.selectionStart<=h+1&&(a=!0);d==I.Hd?(a=!0,0<e.Ea&&(g=e.Ha[--e.Ea])):d==I.Zc&&(a=!0,e.Ea<e.Ha.length&&(g=e.Ha[++e.Ea]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.Ea&&c+1==g.length&&
(f.value+=e.Ha[--e.Ea],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=fb(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&a.o("%s\n",b.replace(/\n$/,"")))}}function gb(a){return"true"==a||"on"==a?!0:"false"==a||"off"==a?!1:void 0}
function hb(a,b){if(void 0!=b){var c=a.X;try{if(b=b.trim())c.Ea<c.Ha.length&&b==c.Ha[c.Ea]?c.Ea++:(c.Ha.push(b),c.Ea=c.Ha.length);var d=b.split(" "),e=d[0],f=a.X.hb[Ra.Xb];switch(e[0]){case "m":if("?"==e[1]){var g="";ib.forEach(function(r){g+=r+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var k=gb(e);void 0!=k&&d.pop();1>=d.length&&(void 0!=k&&(h=k,k=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(ya));for(f=1;f<d.length;f++){e=d[f];var n=ya[e];if(!n){g+=
"unrecognized message: "+e+"\n";break}void 0!=k&&jb(a,n,k);if(void 0==h||h==cb(a,n))g+=a.L("%8s: %b\n",e,cb(a,n))}cb(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",kb.forEach(function(r){g+=r+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var m=f[a](d);if(void 0!=m){g=g?g+m:m;break}}}}catch(r){g="error: "+r.message+"\n"}}return g}
function fb(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=hb(a,b[d])}return c}
l.Na=function(a,b){void 0==b&&(b=cb(this,0x800000000000));if(!b){var c=this.Sa(Na.ib,!0);if(c){b=c.selectionStart;for(var d=a.split(/([\n\r\b])/),e=0;e<d.length;e++){var f=d[e];if(f)if("\b"==f||"\r"==f)for(;0<b&&"\n"!=c.value.slice(b-1,b)&&(b--,"\b"!=f););else if("\n"==f){for(f="";b<c.value.length&&(f=c.value[b],b++,"\n"!=f););"\n"!=f&&(c.value+="\r\n",b=c.value.length)}else c.value=c.value.slice(0,b)+f+c.value.slice(b+f.length),b+=f.length}c.focus();c.setSelectionRange(b,b);8192<=c.value.length&&
(c.value=c.value.slice(c.value.length-8192+4096));c.scrollTop=c.scrollHeight;return a.length}}return F.prototype.Na.call(this,a,b)};l.o=function(a){var b=ma.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return cb(this,c)?(Ha(c,1099511627776)&&(a="error: "+a),Ha(c,549755813888)&&(a="warning: "+a),F.prototype.o.call.apply(F.prototype.o,[this,a].concat(ba(b)))):0};function lb(a,b){if(ab(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.Y,b)}catch(c){a.o("%s\n",c.message)}}}
function mb(a,b,c){(a=a.ca[b])&&a.textContent!=c&&(a.textContent=c)}function jb(a,b,c){var d=!1;c?(c=a.X.pa,a.X.pa=(c|b)+(c/E|0|b/E|0)*E):(d=Ha(a.X.pa,0x800000000000)&&Ha(b,0x800000000000),c=a.X.pa,a.X.pa=(c&~b)+((c/E|0)&~(b/E|0))*E);d&&a.flush()}
var Na={Wc:"clear",ib:"print"},kb=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],ib=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],Ra={Xb:"command"},nb={Zb:13,ub:65,Sb:66,Ub:67,ac:68,E:69,bc:70,cc:71,dc:72,ec:73,fc:74,lc:75,mc:76,pc:77,qc:78,rc:79,sc:80,Q:81,tc:82,vc:83,wc:84,xc:85,yc:86,Ac:87,Bc:88,
Dc:89,Cb:90,a:97,b:98,c:99,d:100,e:101,f:102,pg:103,qg:104,rg:105,tg:106,k:107,ug:108,vg:109,n:110,wg:111,p:112,q:113,r:114,xg:115,t:116,Bg:117,Cg:118,w:119,x:120,y:121,z:122},I={Tb:8,Ed:9,od:10,Zb:13,Bd:16,Xc:17,Vc:18,$f:19,wb:20,$e:27,Dd:32,cg:33,bg:34,Ze:35,wf:36,oc:37,Hd:38,zb:39,tf:39,Zc:40,qf:44,dg:44,xf:45,Ye:46,sf:46,vf:47,ZERO:48,ONE:49,Gd:50,Fd:51,jd:52,hd:53,Cd:54,Ad:55,bd:56,pd:57,gd:59,fd:61,ub:65,Sb:66,Ub:67,ac:68,E:69,bc:70,cc:71,dc:72,ec:73,fc:74,lc:75,mc:76,pc:77,qc:78,rc:79,sc:80,
Q:81,tc:82,vc:83,wc:84,xc:85,yc:86,Ac:87,Bc:88,Dc:89,Cb:90,Wb:91,rf:91,pf:92,gg:93,uf:93,Bf:96,Sf:96,nf:96,Cf:97,Qf:97,Df:98,Pf:98,Ef:99,Vf:99,Ff:100,Tf:100,Gf:101,Mf:101,Hf:102,Xf:102,If:103,Rf:103,Jf:104,Zf:104,Kf:105,Wf:105,Uf:106,Lf:107,Yf:109,Nf:110,Of:111,af:112,ef:113,ff:114,gf:115,hf:116,jf:117,kf:118,lf:119,mf:120,bf:121,cf:122,df:123,qd:144,yd:145,ed:173,zd:186,cd:187,Xe:188,Yc:189,ag:190,jg:191,Ve:192,yf:219,We:220,fg:221,eg:222,dd:224,zf:901,zc:1E3},ob={},pb=(ob[I.gd]=I.zd,ob[I.fd]=I.cd,
ob[I.ed]=I.Yc,ob[I.dd]=I.Wb,ob),qb={oc:1,zb:2,Af:3},J={},rb=(J[I.Tb]="\b",J[I.Ed]="\t",J[I.od]="\n",J[I.Zb]="\r",J[I.Dd]=" ",J[I.ZERO]="0",J[I.ONE]="1",J[I.Gd]="2",J[I.Fd]="3",J[I.jd]="4",J[I.hd]="5",J[I.Cd]="6",J[I.Ad]="7",J[I.bd]="8",J[I.pd]="9",J[I.ub]="A",J[I.Sb]="B",J[I.Ub]="C",J[I.ac]="D",J[I.E]="E",J[I.bc]="F",J[I.cc]="G",J[I.dc]="H",J[I.ec]="I",J[I.fc]="J",J[I.lc]="K",J[I.mc]="L",J[I.pc]="M",J[I.qc]="N",J[I.rc]="O",J[I.sc]="P",J[I.Q]="Q",J[I.tc]="R",J[I.vc]="S",J[I.wc]="T",J[I.xc]="U",J[I.yc]=
"V",J[I.Ac]="W",J[I.Bc]="X",J[I.Dc]="Y",J[I.Cb]="Z",J[I.oc]="Left",J[I.zb]="Right",J),Ua=["","moz","ms","webkit"],sb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",
darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",
fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",
navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},bb={vb:void 0,Ya:"PCjs.localStorage"};x.WebIO=La;
function K(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;La.call(this,a==b);this.Y=a;this.S=b;wa[this.Y]||(wa[this.Y]={});wa[this.Y][this.S]&&this.o("warning: machine configuration contains multiple '%s' devices\n",this.S);wa[this.Y][this.S]=this;this.id=this.Y==this.S?this.Y:this.Y+"."+this.S;xa.push(this);this.X=tb(this,this.Y);this.ready=!0;ub(this,c,d);this.Ia={};this.Ec=[]}w(K,La);l=K.prototype;l.Db=function(){};l.Eb=function(){};
function ub(a,b,c){c=b.overrides||c;if(c.length){var d,e=Ma;if(!e){e={};if(window){d||(d=window.location.search.slice(1));for(var f,g=/\+/g,h=/([^&=]+)=?([^&]*)/g;f=h.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ma=e}d=e;for(var k in d)0<=c.indexOf(k)&&(e=d[k],f=Ga(e,10),void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"')),b[k]=f,a.o("overriding %s property '%s' with %s\n",a.S,k,e))}a.H=b;c=b.bindings;c=void 0===c?{}:c;if("undefined"!=
typeof document){a.H.ca||(a.H.ca=c);(k=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.S);for(var n in c){e=c[n];if(k)n=e;else if(e.match(/^[0-9]+$/)){d=+e;a.ca[n]=[];do{e=n+d++;e=document.getElementById(e);if(!e)break;a.ca[n].push(e)}while(1);continue}(d=document.getElementById(e))&&a.Ja(n,d)}}b=void 0===b?{}:b;a.version=3;if(a.version){n="";var m;a.Y!=a.S&&(m=tb(a,a.Y).version)&&m!=a.version&&(n="Machine");n||(m=b.version)&&m>a.version&&(n="Config");n&&
(m=a.L("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.mg,a.version,n,m),a.error("%s\n\nClearing your browser's cache may resolve the issue.",m))}}function M(a,b,c,d){a.Ia[b]={get:c.bind(a),set:d?d.bind(a):null}}function vb(a,b,c){a.Ia[b]&&(a.Ia[c]=a.Ia[b])}function wb(a,b){var c;try{var d=wa[a.Y];if(d)for(c in d){var e=d[c];if(e.S!=e.Y&&!b(e))return!1}return!0}catch(f){a.o("error while enumerating device '%s': %s\n",c,f.message)}return!1}
l.Sa=function(a,b){b=void 0===b?!1:b;if(a){var c=La.prototype.Sa.call(this,a,b);if(void 0===c&&b){b=wa[this.Y];for(var d in b)if(c=b[d].ca[a])break;c||(c=null);this.ca[a]=c}}return c};function tb(a,b,c){var d=b,e=a.Y,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=wa[e])&&f[b]||null;if(!b){for(f=0;f<xa.length;f++)if(xa[f].id===d){b=xa[f];break}if(!b&&(void 0===c||c))throw Error(a.L('no "%s" device',d));}return b}
function N(a,b,c){var d=null,e=wa[a.Y];if(e)for(var f in e)if(e[f].H["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.L("no %s device",b));return d}function xb(a,b){var c=tb(a,a.Y);return c&&c.H&&c.H[b]||a.H[b]}function yb(a,b){return(a=a.Ia[b])&&a.get()}function zb(a){return a==a.X&&a.ready?wb(a,function(b){return zb(b)}):a.ready}function Ab(a,b){b=void 0===b?a.ready:b;a.ready=b;if(zb(a)){for(;b=a.Ec.pop();)b();a!=a.X&&Ab(a.X)}}
function Bb(a,b){if(zb(a))return b(),!0;a.Ec.push(b);return!1}l.Qc=function(){};l.o=function(a){var b=ma.apply(1,arguments);return"number"==typeof a&&cb(this,a)&&(void 0===this.aa&&(this.aa=N(this,"Debugger",!1)),this.aa&&this.aa.Qc(a),this.X.pa&1&&(void 0===this.v&&(this.v=N(this,"CPU")),this.v))?(a=b.shift(),La.prototype.o.call(this,"%#06x: %s.%s\n",this.v.Kb,this.S,this.L.apply(this,[a].concat(ba(b))).trim())):La.prototype.o.call.apply(La.prototype.o,[this,a].concat(ba(b)))};
function Cb(a,b){(a=wa[a.Y])&&delete a[b]}function Db(a,b,c){(a=a.Ia[b])&&a.set&&a.set(c)}x.Device=K;
function Eb(a,b,c){K.call(this,a,b,c);this.pa=2097152;this.T=this.K=null;this.time=N(this,"Time");this.X=N(this,"Machine");this.$=H(this,"drag",!1);this.R=H(this,"scroll",!1);this.Z=H(this,"hexagonal",!1);this.l=H(this,"releaseDelay",0);this.m=!1;a=this.H.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.j[f]={keys:g,grid:e,
state:0}}}this.J=[];this.M=[];this.i=this.O=null;(a=this.ca[Fb])&&Gb(this,a,this.Sa(c.focusBinding,!0),this.H.location);this.ra()}w(Eb,K);function Hb(a,b){a.K=b}function Ib(a,b,c){for(var d=0;d<a.J.length;d++){var e=a.J[d];e.id===b&&e.kb(b,c)}}
function Gb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.Te=d[0]||0;e.Ue=d[1]||0;e.ab=d[2]||b.clientWidth;e.jb=d[3]||b.clientHeight;e.lb=d[4]||1;e.rb=d[5]||1;e.Td=d[6]||b.naturalWidth||e.ab;e.Vd=d[7]||b.naturalHeight||e.jb;e.Tc=d[8]||0;e.Uc=d[9]||0;e.Sd=d[10]||0;e.Ud=d[11]||0;a.h?(e.nb=a.h.length,e.bb=a.h[0].length):(e.bb=e.lb,e.nb=e.rb,e.lb=e.rb=0);e.Lc=e.ab/(e.bb+e.bb*e.lb)|0;e.Mc=e.jb/(e.nb+e.nb*e.rb)|0;e.Rd=e.Lc*e.lb|0;e.Nc=e.Mc*e.rb|0;e.fb=e.tb=-1;Jb(a,b,e);Kb(a,b,e);a.time&&
a.l&&(a.W=Lb(a.time,"timerInputRelease",function(){0>e.fb&&0>e.tb&&Mb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.l&&(a.ba=Lb(a.time,"timerKeyRelease",function(){Nb(a)})),a.s=0,a.I="",a.u=[],d=b,c&&(d=c,a.i||"BUTTON"!=c.nodeName||(d=document,a.i=c,Ob(a,b),a.O=b)),Ob(a,d),a.i||(a.i=d)}function Pb(a){a.l?Qb(a.time,a.ba,a.l):Nb(a)}
function Rb(a,b,c,d,e){if(a=a.ca[b]){for(b=0;b<a.options.length&&a.options[b].text!=c;b++);void 0==a.options.length&&(b=document.createElement("option"),b.text=c,b.value=d,(void 0===e?0:e)&&a.childNodes[0]?a.insertBefore(b,a.childNodes[0]):a.appendChild(b))}}
function Ob(a,b){function c(e,f,g){var h=document.activeElement;a.o(5242880,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.i&&e!=a.i&&e!=a.O?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Sb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=Sb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Sb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function Jb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.m){var e=a.i;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||Tb(a,b,Ub,d,c)}});b.addEventListener("mousemove",function(d){a.m||Tb(a,b,Vb,d,c)});b.addEventListener("mouseup",function(d){a.m||d.button||Tb(a,b,Wb,d,c)});b.addEventListener("mouseout",function(d){a.m||(0>c.fb?Tb(a,b,Vb,d,c):Tb(a,b,Wb,d,c))})}
function Kb(a,b,c){b.addEventListener("touchstart",function(d){a.R&&(a.m=!0);Tb(a,b,Ub,d,c)});b.addEventListener("touchmove",function(d){Tb(a,b,Vb,d,c)});b.addEventListener("touchend",function(d){Tb(a,b,Wb,d,c)})}
function Sb(a,b,c,d){if(void 0!=c){var e=pb[b]||b;var f=rb[b];var g=Xb[e];d=d&&d.location==qb.zb;g&Yb&&d&&(g>>=1);g&&(g&Zb&&(c=!(a.g&g)),a.g=c?a.g|g:a.g&~g,Ib(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=nb.ub&&b<=nb.Cb?a.g&($b|ac)||(a.g|=ac,Ib(a,I.wb,!0)):b>=nb.a&&b<=nb.z&&a.g&ac&&(a.g&=~ac,Ib(a,I.wb,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(g=a.h[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.s?16>a.u.length&&a.u.push(b):(a.s=1,a.I=f,Mb(a,d,e),Ib(a,
f,!0),Pb(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(g=b[e],0<=a.j[g].keys.indexOf(f))return Ib(a,g,c),a.j[g].state=c?1:0,!0}return!1}function Nb(a){1==a.s?(a.s++,Ib(a,a.I,!1),a.I="",Mb(a,-1,-1),Pb(a)):(a.s=0,a.u.length&&Sb(a,a.u.shift()))}Eb.prototype.ra=function(){this.g=0;this.N=this.U=-1};
function Tb(a,b,c,d,e){var f=-1,g=-1,h=!1,k=-1,n=-1;if(c<Wb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,n=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(k=d.clientX,n=d.clientY);var m=d.target.getBoundingClientRect();k-=m.left;n-=m.top;k=e.Td/b.offsetWidth*k|0;n=e.Vd/b.offsetHeight*n|0;var r=k-e.Te;var p=n-e.Ue;var q=m=!1;var v=k>=e.Tc&&k<e.Tc+e.Sd&&n>=e.Uc&&n<e.Uc+e.Ud;if(0<=r&&r<e.ab&&0<=p+e.Nc||v)if(h||a.R||d.preventDefault(),0<=r&&r<e.ab&&
0<=p&&p<e.jb){q=!0;d=e.ab/e.bb|0;var t=e.jb/e.nb|0,y=r/d|0,z=p/t|0;!a.Z||z&1||(r-=d>>1,y=r/d|0,y==e.bb-1&&(r=-1));t=z*t+(e.Nc>>1);r-=y*d+(e.Rd>>1);p-=t;0<=r&&r<e.Lc&&0<=p&&p<e.Mc&&(f=y,g=z,m=!0)}}r=r||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Ub||c==Wb)for(y=0;y<a.M.length;y++)z=a.M[y],c==Wb?z.kb(z.id,!1):(t=p/(b/z.og|0)|0,(r/(d/z.ng|0)|0)==z.Dg&&t==z.Eg&&z.kb(z.id,!0));if(!h)if(c==Ub)e.fb=k,e.tb=n,q?(Mb(a,f,g),m&&a.l&&Qb(a.time,a.W,a.l,!0)):v&&a.X.qa();else if(c==Vb)0<=e.fb&&0<=e.tb&&a.$?Mb(a,
f,g):a.K&&a.K(f,g);else if(c==Wb){if(c=a.l)c=a.time,f=a.W,c=c.g&&0<f&&f<=c.h.length?0<=c.h[f-1].Aa:!1;c||Mb(a,-1,-1);e.fb=e.tb=-1}else a.o("unrecognized action: %d\n",c)}function Mb(a,b,c){if(b!=a.N||c!=a.U)a.N=b,a.U=c,a.T&&a.T(b,c)}var Ub=1,Vb=2,Wb=3,Fb="surface",$b=3,Yb=170,ac=512,Zb=3584,bc={},Xb=(bc[I.Bd]=2,bc[I.Xc]=8,bc[I.Vc]=32,bc[I.Wb]=128,bc[I.wb]=ac,bc[I.qd]=1024,bc[I.yd]=2048,bc);x.Input=Eb;
function cc(a,b,c){K.call(this,a,b,c,["color","backgroundColor"]);a=this.ca[dc];if(!a)throw Error("LED "+this.H.ca[dc]+" binding for '"+dc+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.ua=Va(this,dc)+".canvas";b.setAttribute("id",this.ua);this.Ca=a;this.type=Ya(H(this,"type",ec,fc),gc,hc);this.j=ic[this.type][0];this.u=ic[this.type][1];this.width=H(this,"width",
this.j);this.height=H(this,"height",this.u);this.l=H(this,"cols",1);this.M=this.l+H(this,"colsExtra",0);this.$=H(this,"rows",1);this.R=this.$+H(this,"rowsExtra",0);this.da=this.width*this.l;this.U=this.height*this.$;this.s=jc("black",0);this.i=kc(this.H.color)||this.s;this.la=jc(this.i,1,.25);this.ka=jc(this.i,1,2);this.m=kc(this.H.backgroundColor);this.ma=H(this,"fixed",!1);this.ma||(b.style.width="100%",b.style.height="auto");this.ja=H(this,"hexagonal",!1);this.oa=H(this,"highlight",!0);this.T=
H(this,"persistent",this.type<hc);b.setAttribute("width",this.da.toString());b.setAttribute("height",this.U.toString());b.style.backgroundColor=this.s;a.appendChild(b);this.ha=b.getContext("2d");if(this.I=document.createElement("canvas"))this.I.width=this.ba=this.j*this.l,this.I.height=this.K=this.u*this.$,this.h=this.I.getContext("2d");this.va=(this.R+1)*this.M*4;this.g=Array(this.va);this.wa=this.l<this.M?4*(this.M-this.l):0;this.O=this.N=!1;this.J=this.Z=0;this.W=-1;var d=this;this.time=N(this,
"Time");lc(this.time,function(e,f){mc(d,!1,e,f)});nc(d)}w(cc,K);function nc(a){for(var b=a.g,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<hc?oc:" ";e[f+1]=d.i==d.s?null:d.i;e[f+2]=0;e[f+3]=pc}a.O=a.N=!0;mc(a,!0)}function qc(a){a.m?(a.h.fillStyle=a.m,a.h.fillRect(0,0,a.ba,a.K)):a.h.clearRect(0,0,a.ba,a.K)}
function mc(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.O||b){if(a.type<hc){d=0;if(!a.T||b)qc(a);else if(a.J){d=a.l-a.J;var e=a.j*d;a.h.drawImage(a.I,a.j*a.J,0,e,a.K,0,0,e,a.K)}for(var f=e=0;f<a.R;f++){for(var g=0;g<a.l;g++){var h=a.g[e],k=a.g[e+1]||a.s,n=a.oa&&e==a.W;if(a.g[e+3]&pc||n||b){if(g>=d)a:{var m=a,r=h;h=k;var p=g;k=f;var q=n;p=void 0===p?0:p;k=void 0===k?0:k;q=void 0===q?!1:q;var v=0;if(m.ja&&!(k&1)&&(v=m.j>>1,p==m.l-1))break a;if(h&&h!=m.i){q=q?jc(h,1,2):h;var t=
jc(h,1,.25)}else q=q?m.ka:m.i,t=m.la;h=!1;r=r?q:t;q==m.s&&(r=m.m,h=!0);q=p*m.j+v;t=k*m.u;m.T&&(p=p*m.j+v,k*=m.u,m.m?(m.h.fillStyle=m.m,m.h.fillRect(p,k,m.j,m.u)):m.h.clearRect(p,k,m.j,m.u));m.h.fillStyle=r;k=rc[m.type];3==k.length?(m.h.beginPath(),m.h.arc(q+k[0],t+k[1],k[2],0,2*Math.PI),h?(m.h.globalCompositeOperation="destination-out",m.h.fill(),m.h.globalCompositeOperation="source-over"):m.h.fill()):m.h.fillRect(q+k[0],t+k[1],k[2],k[3])}a.g[e+3]=n?a.g[e+3]|pc:a.g[e+3]&~pc}e+=4}e+=a.wa}a.J=0}else{b=
"";for(d=0;d<a.g.length;d+=4)b+=a.g[d]||" ",a.g[d+3]&sc&&(b+=".");qc(a);for(f=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;g=a;n=e;m=f;n=void 0===n?0:n;m=void 0===m?0:m;if(k=tc[k])for(h=0;h<k.length;h++)if(p=g,v=uc[k[h]]){r=(void 0===n?0:n)*p.j;q=(void 0===m?0:m)*p.u;p.h.fillStyle=p.i;p.h.beginPath();if(3==v.length)p.h.arc(r+v[0],q+v[1],v[2],0,2*Math.PI);else for(t=0;t<v.length;t+=2)t?p.h.lineTo(r+v[t],q+v[t+1]):p.h.moveTo(r+v[t],q+v[t+1]);p.h.closePath();p.h.fill()}if(++e==a.l&&(e=0,++f==a.R))break}}a.ha.globalCompositeOperation=
a.m&&a.i!=a.s?"source-over":"copy";a.ha.drawImage(a.I,0,0,a.ba,a.K,0,0,a.da,a.U);a.O=!1;a.W=-1}else a.T||a.N||(!c||!a.Z||c-a.Z>=(1E3/d|0))&&nc(a);a.N=!1;c&&(a.Z=c)}function kc(a){return(a=a||void 0)&&sb[a]||a}
function jc(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=sb[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
cc.prototype.xa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.i&&c==this.m&&a&&a.length==this.g.length){this.g=a;for(b=0;b<=this.g.length-4;b+=4)this.g[b+1]==this.s&&(this.g[b+1]=null);mc(this,!0);return!0}return!1};cc.prototype.ya=function(a){this.g&&(a.push(this.i),a.push(this.m),a.push(this.g))};
var gc=0,ec=1,hc=3,fc={small:gc,round:ec,square:2,digit:hc},dc="container",oc=0,sc=1,pc=128,vc={},rc=(vc[gc]=[4,4,4],vc[ec]=[16,16,14],vc[2]=[2,2,28,28],vc),ic=[[8,8],[32,32],[32,32],[96,128]],uc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},tc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C",
"D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};x.LED=cc;
function wc(a,b,c){K.call(this,a,b,c);this.oa=H(this,"cyclesMinimum",1E5);this.Ca=H(this,"cyclesMaximum",1E9);this.ha=Ya(H(this,"cyclesPerSecond",1E6),this.oa,this.Ca);this.$=60;this.T=0;this.U=1E3/this.$;this.Pa=H(this,"updatesPerSecond",2)||2;this.Xa=1E3/this.Pa;this.wa=0;this.Za=H(this,"timeLock",!0);this.ma=this.M=0;this.la=this.l=1;this.va=this.s=this.ha/1E4/100;this.ja=[];this.K=[];this.h=[];this.ba=[];this.ua=this.g=this.R=this.I=!1;this.J=this.j=0;a=Ta("requestAnimationFrame");if(!a){a="setTimeout";
var d=this.U}this.Ra=window[a].bind(window,this.xe.bind(this),d);this.Wa=window[Ta("cancelAnimationFrame")||"clearTimeout"].bind(window);this.Z=this.W=this.m=this.i=this.da=0;xc(this)||yc(this,this.la)}w(wc,K);function lc(a,b){a.ja.push(b)}l=wc.prototype;
l.Ja=function(a,b){var c=this;switch(a){case zc:b.onclick=function(){Ac(c)&&(c.g?Bc(c):c.start())};break;case Cc:b.onclick=function(){yc(c,c.l<<1);Dc(c,Ec(c.s))};break;case Fc:b.onclick=function(){Gc(c)};break;case Hc:b.addEventListener("mousedown",function(){c.I=!0}),b.addEventListener("mouseup",function(){xc(c);c.I=!1}),b.addEventListener("mousemove",function(){c.I&&xc(c)}),b.addEventListener("change",function(){c.I=!0;xc(c);c.I=!1})}K.prototype.Ja.call(this,a,b)};
function Lb(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,Kd:c,mb:d,Aa:-1});0<=d&&Qb(a,e,d);return e}
function Ic(a,b,c,d){var e=0,f=a.s,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.o(262144,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.U&&(1<a.l&&(a.l>>=1,a.o(549755813888,"frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.U,a.l)),e=d));a.M=f;a.ma=f/a.va;b=a.ma/a.l;a.da=g/b/a.$+1E-8;a.o(262144,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.da,g,b,a.$);return e}
function Jc(a,b){a.W=a.m=b;if(!a.K.length)return a.m=0,a.W;for(var c=0;0<a.m;){if(c<a.K.length){var d=a.K[c++];b=d.ze.call(d,b)||1}else c=b=0;a.m-=b}return a.W-a.m}function Kc(a,b){b=void 0===b?a.W-a.m:b;if(!a.g){if(a.i)for(var c=0;c<a.K.length;c++){var d=a.K[c];d.Ae.call(d)}a.i=b}a.i-=b;1>a.i&&(a.R=!0);a.Z+=b;a.W=a.m=0;a.g||(a.Z=0);return b}
function Lc(a,b){b=void 0===b?0:b;if(b){var c=b;a.i+=b}else for(c=a.i,1>c&&(c=a.i+=a.da),0>c&&(a.o(262144,"warning: cycle count dropped below zero: %f\n",c),c=a.i=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.Aa)&&c>d.Aa&&(c=d.Aa)}return c}function Ec(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Mc(a){a.o(262144,"getSpeedCurrent(%5.3fhz)\n",1E6*a.M);return a.g&&a.M?Ec(a.M):"Stopped"}
function Ac(a){return a.ua?!0:(a.o("not powered\n"),!1)}function Nc(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.Aa||(d.Aa-=b,0>=d.Aa&&(d.Aa=-1,d.Kd(),0<=d.mb&&Qb(a,c,d.mb)))}}l.qa=function(a){this.ua=a;void 0===this.aa&&(this.aa=N(this,"Debugger",!1))&&this.aa.Db(this,"time","dump time state",this.Zd)};function Gc(a,b){Ac(a)&&(a.g?a.o("already running\n"):a.j?Bc(a):Oc(a,b))}
l.xe=function(a){a=void 0===a?Date.now():a;this.J=0;if(this.g){if(this.T){var b=a-this.T;1>b&&(b=16.67);this.$=1E3/b}this.T=a;a=Date.now();this.O&&(b=a-this.N-this.U,b>this.U&&(this.u+=b,this.o(549755813888,"browser throttling detected, compensating by %5.3fms\n",b)));this.N=a;this.u||(this.u=a);this.ka=0;try{this.R=!1;do Nc(this,Kc(this,Jc(this,Lc(this))));while(this.g&&!this.R)}catch(c){this.o("%s\n",c.message),Bc(this)}this.O=Date.now();this.ka&&(this.u+=this.ka,this.N+=this.ka);this.N+=Ic(this,
this.Z,this.O-this.u,this.O-this.N);this.O-this.wa>=this.Xa&&this.update();for(a=0;a<this.ja.length;a++)this.ja[a](this.T,this.$);this.J=this.Ra()}};function yc(a,b){if(void 0!==b){if(1>b||!a.I&&0<a.M&&a.M<.9*a.s)b=a.la;a.l=b;b=a.va*a.l;a.s!=b&&(a.s=b,Dc(a,Ec(a.s)))}a.u=a.O=0;a.i=a.Z=0;Ic(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.mb&&Qb(a,b,c.mb,!0)}}function xc(a){var b=a.ca[Hc];return b?(yc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Ca-a.oa)+a.oa)/a.ha|0),!0):!1}
function Qb(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.Aa)&&(c=Math.ceil(a.ha*(a.Za?a.la:a.ma)/1E3*(void 0===c?1E3:c)),a.g&&(c+=Kc(a)),b.Aa=c)}l.start=function(){if(this.g||this.j)return!1;this.g=!0;this.u=this.O=this.T=0;this.update(!0);this.J=this.Ra();return!0};function Oc(a,b){b=void 0===b?1:b;a.g||(b&&!a.j&&(a.j=b),a.j&&(a.j--,Nc(a,Kc(a,Jc(a,Lc(a,1)))),a.update(!1),a.j&&setTimeout(function(){Oc(a,0)},0)))}
function Bc(a){return a.g?(a.g=!1,Kc(a),a.J&&(a.Wa(a.J),a.J=0),a.update(!0),!0):a.j?(a.j=0,a.update(!0),!0):!1}l.update=function(a){a&&this.o(this.g?"started with %s target\n":"stopped\n",Ec(this.s));mb(this,zc,this.g?"Halt":"Run");mb(this,Fc,this.j?"Stop":"Step");this.I||Dc(this,Mc(this));for(var b=0;b<this.ba.length;b++){var c=this.ba[b];c.Rc.call(c,void 0!=a)}this.wa=Date.now();this.R=!0};function Dc(a,b){mb(a,Pc,b);mb(a,Cc,b)}
l.Zd=function(){var a=this.L("nCyclesPerSecond: %f\n",this.ha);a+=this.L("nUpdatesPerSecond: %f\n",this.Pa);a+=this.L("nTargetMultiplier: %f\n",this.l);return a+=this.L("nCyclesDepositPerFrame: %f\n",this.da)};var zc="run",Cc="setSpeed",Pc="speed",Fc="step",Hc="throttle";x.Time=wc;
function Qc(a,b,c){K.call(this,a,b,c);this.type="static"==this.H.type?Rc:Sc;this.ea=this.H.addrWidth||16;this.m=Math.pow(2,this.ea);this.l=this.m-1|0;this.blockSize=this.H.blockSize||(16<this.ea?4096:1024);this.blockSize>this.m&&(this.blockSize=this.m);this.J=this.m/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.i=(1<<this.h)-1;this.j=this.H.dataWidth||8;this.K=Math.pow(2,this.j)-1;this.s=!1!==this.H.littleEndian;this.g=Array(this.J);this.u=0;this.I=null;a=new O(a,b+"[NONE]",{size:this.blockSize,
bus:this.S});for(b=0;b<this.m;b+=this.blockSize)Tc(this,b,this.blockSize,Q.NONE,a);Uc(this,this.type)}w(Qc,K);function Tc(a,b,c,d,e){for(var f=b>>>a.h;0<c&&f<a.g.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var k=a.g[f];if(b!=g||h!=a.blockSize||k&&k.type!=Q.NONE)break;k=a.S+"["+D(a,b,16,a.ea)+"]";b=e?e.size==a.blockSize?e:new O(a.Y,k,{type:d,ia:b,size:h,bus:a.S}):new O(a.Y,k,{type:d,ia:b,size:h,bus:a.S});a.g[f]=b;b=g+a.blockSize;c-=h;f++}}
function Vc(a,b){for(var c=Q.wd,d=0,e=0;e<a.g.length;e++){var f=a.g[e];f&&f.type&c&&(b(f),d++)}return d}function Wc(a,b,c){if(!(b&a.i)){b>>>=a.h;var d=a.g[b];a.g[b]=c}return d}function Xc(a,b,c){a.aa&&a.aa.o(4,"bus fault (%d) at %n\n",c,b);a.I&&a.I(b,c)}l=Qc.prototype;l.qa=function(){void 0===this.aa&&(this.aa=N(this,"Debugger",!1))};l.ra=function(){};l.Hb=function(a){return a&&this.xa(a)?!0:!1};l.cb=function(a){this.ya(a)};
l.xa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==Sc||c.type&Q.Qa)&&c.xa){var d=a.shift();if(!c.xa(d))return!1}}return!0};l.ya=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==Sc||c.type&Q.Qa)&&c.ya){var d=[];c.ya(d);a.push(d)}}};l.Jb=function(a){return this.g[a>>>this.h].Jb(a&this.i)};l.kd=function(a){return this.g[a>>>this.h].Ba(a&this.i)};l.eb=function(a,b){this.g[a>>>this.h].eb(a&this.i,b)};
l.Fa=function(a,b){this.g[a>>>this.h].za(a&this.i,b)};l.hc=function(a){return a&1?this.Ba(a+1&this.l)|this.Ba(a)<<this.j:this.g[a>>>this.h].na(a&this.i)};l.ic=function(a){return a&1?this.Ba(a)|this.Ba(a+1&this.l)<<this.j:this.g[a>>>this.h].na(a&this.i)};l.fe=function(a){return(a&this.i)==this.i?this.s?this.ic(a):this.hc(a):this.g[a>>>this.h].na(a&this.i)};l.jc=function(a,b){a&1?(this.za(a,b>>this.j),this.za(a+1&this.l,b&this.K)):this.g[a>>>this.h].ga(a&this.i,b)};
l.kc=function(a,b){a&1?(this.za(a,b&this.K),this.za(a+1&this.l,b>>this.j)):this.g[a>>>this.h].ga(a&this.i,b)};l.Ce=function(a,b){(a&this.i)==this.i?this.s?this.kc(a,b):this.jc(a,b):this.g[a>>>this.h].ga(a&this.i,b)};function Uc(a,b){var c=a.u;a.u+=b;c&&a.u||(a.Ba=a.kd,a.za=a.Fa,a.type==Sc?(a.na=a.fe,a.ga=a.Ce):a.s?(a.na=a.ic,a.ga=a.kc):(a.na=a.hc,a.ga=a.jc))}l.pb=function(a,b){return this.g[a>>>this.h].pb(b)?(Uc(this,1),!0):!1};l.Mb=function(a,b){return this.g[a>>>this.h].Mb(b)?(Uc(this,1),!0):!1};
l.qb=function(a,b){return this.g[a>>>this.h].qb(b)?(Uc(this,-1),!0):!1};l.Ob=function(a,b){return this.g[a>>>this.h].Ob(b)?(Uc(this,-1),!0):!1};var Rc=0,Sc=1;x.Bus=Qc;
function O(a,b,c){K.call(this,a,b,c);this.ia=this.H.addr;this.size=this.H.size;this.type=this.H.type||Q.NONE;this.j=(a=this.H.bus)?tb(this,a):N(this,a="Bus");if(!this.j)throw Error(this.L("unable to find bus '%s'",a));this.g=this.j.j;this.i=Math.pow(2,this.g)-1;this.Z=this.ba=!1;this.l=!1!==this.j.s;this.values=this.$=this.K=this.W=null;a=this.Oa;b=this.Fa;c=this.l?this.he:this.ge;var d=this.l?this.Ee:this.De;this.j.type==Rc&&(b=this.Ne,c=this.l?this.md:this.ld,d=this.Oe,8==this.g&&!1!==xb(this,"ArrayBuffer")&&
(this.ba=!0,c=this.l==ra?this.qe:this.re));switch(this.type){case Q.NONE:this.Ba=this.La;this.za=this.Ga;this.na=this.ie;this.ga=this.Fe;break;case Q.uc:this.Ba=a;this.za=this.Ga;this.na=c;this.ga=this.Ga;break;case Q.Qa:this.Ba=a,this.za=b,this.na=c,this.ga=d}this.M=this.m=0;this.U=this.s=this.T=this.O=this.u=this.I=null;Yc(this,this.H.values);Zc(this)}w(O,K);
function Yc(a,b){"string"==typeof b?(Ab(a,!1),$a(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);Yc(a,g.values)}catch(h){a.o("error (%s) parsing resource: %s\n",h.message,c)}Ab(a,!0)}else a.o("error (%d) loading resource: %s\n",f,c)})):a.H.values=b}
function Zc(a,b){if(a.type>Q.NONE&&(a.ba?(a.K=new ArrayBuffer(a.size),a.W=new DataView(a.K,0,a.size),a.values=new Uint8Array(a.K,0,a.size),a.$=new Uint16Array(a.K,0,a.size>>1),new Int32Array(a.K,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}l=O.prototype;
l.ra=function(){if(this.H.values)a:{var a=this.j,b=this.ia,c=this.size,d=this.H.values,e=0,f=b&a.i;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var g=a.g[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Fa(f++,d[e++]),c--;f=0}}else this.type&Q.Qa&&this.values&&this.values.fill(0)};l.La=function(){return this.i};l.ie=function(a){return this.l?this.La(a)|this.La(a+1)<<this.g:this.La(a+1)|this.La(a)<<this.g};l.Jb=function(a){return this.values?this.values[a]:0};l.Oa=function(a){return this.values[a]};
l.ld=function(a){return this.values[a+1]|this.values[a]<<this.g};l.md=function(a){return this.values[a]|this.values[a+1]<<this.g};l.qe=function(a){return this.$[a>>>1]};l.re=function(a){return this.W.getUint16(a,this.l)};l.ge=function(a){return this.Oa(a+1)|this.Oa(a)<<this.g};l.he=function(a){return this.Oa(a)|this.Oa(a+1)<<this.g};l.Ga=function(){};l.Fe=function(a,b){this.l?(this.Ga(a,b&this.i),this.Ga(a+1,b>>this.g)):(this.Ga(a,b>>this.g),this.Ga(a+1,b&this.i))};
l.eb=function(a,b){this.values&&(this.values[a]=b)};l.Fa=function(a,b){this.values[a]=b};l.Ne=function(a,b){this.values[a]=b;this.Z=!0;this.m?this.O=this.Fa:this.za=this.Fa};l.xb=function(a,b){this.values[a]=b>>this.g;this.values[a+1]=b&this.i};l.yb=function(a,b){this.values[a]=b&this.i;this.values[a+1]=b>>this.g};l.Pb=function(a,b){this.$[a>>>1]=b};l.Qb=function(a,b){this.W.setUint16(a,b,this.l)};l.De=function(a,b){this.Fa(a,b>>this.g);this.Fa(a+1,b&this.i)};
l.Ee=function(a,b){this.Fa(a,b&this.i);this.Fa(a+1,b>>this.g)};l.Oe=function(a,b){this.K?this.l==ra?(this.Pb(a,b),this.m?this.s=this.Pb:this.ga=this.Pb):(this.Qb(a,b),this.m?this.s=this.Qb:this.ga=this.Qb):this.l?(this.yb(a,b),this.m?this.s=this.yb:this.ga=this.yb):(this.xb(a,b),this.m?this.s=this.xb:this.ga=this.xb)};
l.pb=function(a){if(!this.M){var b=this;this.M++;this.u=a;this.T=this.Ba;this.U=this.na;this.Ba=function(c){var d=b.T(c);b.u(b.ia,c,d);return d};this.na=function(c){var d=b.U(c);b.u(b.ia,c,d);b.u(b.ia,c+1,d);return d};return!0}return this.u==a?(this.M++,!0):!1};l.Mb=function(a){if(!this.m){var b=this;this.m++;this.I=a;this.O=this.za;this.s=this.ga;this.za=function(c,d){b.I(b.ia,c,d);b.O(c,d)};this.ga=function(c,d){b.I(b.ia,c,d);b.I(b.ia,c+1,d);b.s(c,d)};return!0}return this.I==a?(this.m++,!0):!1};
l.qb=function(a){return this.M&&this.u==a?(--this.M||(this.Ba=this.T,this.na=this.U,this.T=this.U=this.u=null),!0):!1};l.Ob=function(a){return this.m&&this.I==a?(--this.m||(this.za=this.O,this.ga=this.s,this.O=this.s=this.I=null),!0):!1};l.xa=function(a){if(a){var b=a.shift();if(this.S==b){this.Z=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}Zc(this,a)}return!0}}return!1};
l.ya=function(a){a.push(this.S);a.push(this.Z);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var Q={NONE:1,uc:2,Qa:4,wd:14,kg:12};x.Memory=O;function $c(a,b,c){O.call(this,a,b,c);this.J=[];this.N=[];this.h=[];this.R=[];void 0!=this.H.addr&&Tc(this.j,this.H.addr,this.H.size,Q.NONE,this)}w($c,O);
function ad(a,b,c,d,e,f,g,h){for(var k;c<=d;c++){k=!1;if(e){if(a.J[c])break;a.J[c]=e.bind(b)}if(f){if(a.N[c])break;a.N[c]=f.bind(b)}if(g){if(a.h[c])break;a.h[c]=g.bind(b)}if(h){if(a.R[c])break;a.R[c]=h.bind(b)}k=!0}if(!k)throw Error(a.L("handler for port %#0x already exists",c));}function bd(a,b,c){var d=void 0===d?0:d;for(var e in c){var f=c[e];ad(a,b,+e+d,+e+d,f[0],f[1],f[2],f[3])}}
$c.prototype.La=function(a){var b,c=this.ia+a;if(b=this.J[c]){var d=b(c);var e=!0}else if(b=this.h[c])d=c&1?b(c&-2)>>this.g:b(c)&this.i,e=!0;else if(c&1)if(c&=-2,b=this.h[c])d=b(c)>>this.g,e=!0;else if(b=this.J[c])d=b(c),e=!0;e||(Xc(this.j,c,0),this.o(272,"readNone(%#04x): unknown port\n",c),d=O.prototype.La.call(this,a));return d};
$c.prototype.Ga=function(a,b){var c,d=this.ia+a;if(c=this.N[d]){c(d,b);var e=!0}else if(c=this.R[d])e=this.h[d]?this.h[d](d,!0):0,d&1?c(d,e&this.i|b<<this.g):c(d,e&~this.i|b),e=!0;else if(d&1)if(d&=-2,c=this.R[d])e=this.h[d]?this.h[d](d,!0):0,c(d,e&this.i|b<<this.g),e=!0;else if(c=this.N[d])c(d,b),e=!0;e||(Xc(this.j,d,1),this.o(272,"writeNone(%#04x,%#04x): unknown port\n",d,b),O.prototype.Ga.call(this,a,b))};x.Ports=$c;
function cd(a,b,c){c.type=Q.NONE;O.call(this,a,b,c);Tc(this.j,this.H.addr,this.H.size,Q.Qa);Bb(this,this.ra.bind(this))}w(cd,O);x.RAM=cd;
function dd(a,b,c){c.type=Q.uc;O.call(this,a,b,c);Tc(this.j,this.H.addr,this.H.size,this.H.type,this);Bb(this,this.ra.bind(this));this.v=this.aa=void 0;if(x.LED&&this.ca[ed]){var d=this;this.J=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.N=this.values.length/this.J|0;this.h=new cc(a,b+"LEDs",{"class":"LED",bindings:{container:Va(this,ed)},type:ec,cols:this.J,rows:this.N,color:H(this,"colorROM","green"),backgroundColor:H(this,"backgroundColorROM","black"),persistent:!0}),nc(this.h);
this.R=new Eb(a,b+"Input",{"class":"Input",location:[0,0,this.h.da,this.h.U,this.J,this.N],bindings:{surface:Va(this,ed)}});this.da=Wa(this)||"";Hb(this.R,function(e,f){if(d.v){var g=d.da;0<=e&&0<=f&&(e=f*d.J+e,f=d.v,g=f.aa&&fd(f.aa,d.ia+e,1)||"");mb(d,Xa,g)}})}}w(dd,O);
dd.prototype.xa=function(a){var b=!0,c=a.shift();if(c&&this.h){var d=c.length;this.h.g.length==d?(this.h.g=c,mc(this.h,!0)):(this.o("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.o("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};dd.prototype.qa=function(){void 0===this.v&&(this.v=N(this,"CPU"));void 0===this.aa&&(this.aa=N(this,"Debugger",!1))&&this.aa.Eb&&this.aa.Eb(this.H.symbols)};
dd.prototype.Oa=function(a){if(this.h){var b=this.h,c=pc;c=(void 0===c?0:c)&129;var d=4*((a/this.J|0)*b.M+a%this.J);if(d<=b.g.length-4){if(1!==b.g[d]||(b.g[d+3]&129)!==c)b.g[d]=1,b.g[d+3]=b.g[d+3]&-130|c|pc,b.O=!0;b.W=d;b.N=!0;b.J=0}}return this.values[a]};dd.prototype.ya=function(a){this.h&&(a.push(this.h.g),a.push(this.values))};var ed="array",Xa="cellDesc";x.ROM=dd;
function gd(a,b,c){c["class"]="CPU";K.call(this,a,b,c);this.aa=void 0;this.Za=this.Kb=0;this.T=this.H.addrReset||0;this.time=N(this,"Time");this.time.K.push(this);this.time.ba.push(this);this.ka=this.$=0}w(gd,K);gd.prototype.abort=function(a){this.Za=this.Kb;this.o("%s\n",a.message);Bc(this.time)};function hd(a,b){a.aa=b;return a.Ia}gd.prototype.ze=function(a){this.ka=this.$=void 0===a?0:a;return this.ka-this.$};gd.prototype.Ae=function(){this.ka-=this.$;this.$=0};
function id(a,b,c){c["class"]="Debugger";K.call(this,a,b,c);var d=this;this.fa=this.H.defaultRadix||16;this.ja=1;this.W=["(",")"];this.Cc("a",function(f,g,h,k,n){return D(d,n.V,d.fa,h)});this.Cc("n",function(f,g,h,k,n){return D(d,n,d.fa,h,0>g.indexOf("#")?"":void 0)});this.ka=this.K=0;this.M={};this.la=[];this.ma=[];this.v=N(this,"CPU");this.Ia=hd(this.v,this);this.oa=N(this,"Input",!1);if(a=this.v.H.busMemory||this.H.busMemory){this.g=tb(this,a);if(a=this.v.H.busIO||this.H.busIO)this.j=tb(this,a,
!1);this.j||(this.j=this.g)}else this.g=this.j=N(this,"Bus");this.J=this.g.ea;this.Ca=Math.pow(2,this.J)-1|0;this.u=this.da=0;this.s=[];for(var e in R)this.s[R[e]]=[];this.m=[];this.m[R.Da]=this.g;this.m[R.$a]=this.g;this.m[R.Ta]=this.j;this.m[R.Ua]=this.j;this.l=[];this.l[R.Da]=this.Nd.bind(this);this.l[R.$a]=this.Qd.bind(this);this.l[R.Ta]=this.Ld.bind(this);this.l[R.Ua]=this.Md.bind(this);this.i=[];this.N=void 0;this.U=null;this.Z=0;this.time=N(this,"Time");this.time.ba.push(this);this.$=0;this.I=
[];this.T="";this.Db(this,"state","dump machine state",this.Yd);this.ba=jd();this.ua=jd();this.ha=!1;this.R=0;this.h=[];Qa(this,this.ce.bind(this));(e=xb(this,"commands"))&&fb(this,e)}w(id,K);l=id.prototype;l.Db=function(a,b,c,d){this.I.push({Xd:a,name:b,Wd:c,kb:d})};function kd(a,b,c){for(var d,e=0;e<a.I.length;e++){var f=a.I[e];if(f.name==b){d=f.kb.call(f.Xd,c);break}}return d}
l.Eb=function(a){if(a&&a.length)for(var b=0;b<a.length-2;b+=3){var c=ld(this,a[b]);if(c){var d=md[a[b+1]];if(d){c={address:c,type:d,name:a[b+2]};d=this.la;var e=c,f=nd(d,e,this.Jc);0>f&&d.splice(-(f+1),0,e);d=this.ma;e=nd(d,c,this.Kc);0>e&&d.splice(-(e+1),0,c)}}}};function nd(a,b,c){var d=0,e=a.length,f=0;for(void 0===c&&(c=function(k,n){return k>n?1:k<n?-1:0});d<e;){var g=d+e>>1,h=void 0;h=c(b,a[g]);0<h?d=g+1:(e=g,f=!h)}return f?d:~d}l.Jc=function(a,b){return a.name>b.name?1:a.name<b.name?-1:0};
l.Kc=function(a,b){return a.address.V>b.address.V?1:a.address.V<b.address.V?-1:0};function od(a,b,c){b=nd(a.ma,{address:b,type:0,name:void 0},a.Kc);if(0<=b&&(a=a.ma[b],!c||a.type==c))var d=a.name;return d}function pd(a,b,c,d){d=void 0===d?a.g:d;b.V=b.V+c&d.l}function jd(a){a=void 0===a?0:a;var b=qd.td;return"number"==typeof a?{V:a,Lb:-1,type:b}:{V:a.V,Lb:a.Lb,type:a.type}}
function ld(a,b,c){if(b){var d=jd();var e=0,f=b.charAt(e);switch(f){case "&":e++;break;case "#":e++;d.type=qd.ud;break;case "%":e++,f=b.charAt(e),"%"==f?e++:d.type=qd.zc}f=b.indexOf(":",e);if(0<=f){var g=rd(a,b.substring(e,f),c);void 0==g?d=null:(d.Lb=g,e=f+1)}d&&(b=rd(a,b.substring(e),c),void 0==b?d=null:d.V=b&a.Ca)}return d}function sd(a,b,c,d){d=void 0===d?a.g:d;a.u++;var e=d.Jb(b.V);c&&pd(a,b,c,d);a.u--;return e}
function td(a,b,c){if(32>=a.J)return b&c;b=S(a,b,0,!0);c=S(a,c,0,!0);return((b/E|0)&(c/E|0))*E+((b&c)>>>0)}function ud(a,b,c){if(32>=a.J)return b^c;b=S(a,b,0,!0);c=S(a,c,0,!0);return((b/E|0)^(c/E|0))*E+((b^c)>>>0)}
function vd(a,b,c,d){for(d=void 0===d?-1:d;d--&&c.length;){var e=c.pop();if(2>b.length)return!1;var f=b.pop();var g=b.pop();switch(e){case "*":g*=f;break;case "/":if(!f)return!1;g=Math.trunc(g/f);break;case "^/":if(!f)return!1;g%=f;break;case "+":g+=f;break;case "-":g-=f;break;case "<<":g<<=f;break;case ">>":g>>=f;break;case ">>>":g>>>=f;break;case "<":g=g<f?1:0;break;case "<=":g=g<=f?1:0;break;case ">":g=g>f?1:0;break;case ">=":g=g>=f?1:0;break;case "==":g=g==f?1:0;break;case "!=":g=g!=f?1:0;break;
case "&":g=td(a,g,f);break;case "!":case "|":e=g;32>=a.J?g=e|f:(e=S(a,e,0,!0),f=S(a,f,0,!0),g=(e/E|0|f/E|0)*E+((e|f)>>>0));break;case "^!":g=ud(a,g,f);break;case "&&":g=g&&f?1:0;break;case "||":g=g||f?1:0;break;case ",,":g=S(a,g,18,!0)*Math.pow(2,18)+S(a,f,18,!0);break;case "_":case "^_":"^_"==e&&(f=35-(f&255));f&&(g=S(a,g,0,!0),g=0<f?g*Math.pow(2,f):Math.trunc(g/Math.pow(2,-f)));break;default:return!1}b.push(S(a,g))}return!0}
function wd(a,b,c,d,e,f){var g,h=!1,k=0,n=[],m=[],r=a.fa;for(a.fa=e;c<d;){var p=b[c++].trim();var q=c<d?b[c++]:"";if(p){var v=void 0;var t=a;var y=p,z=f;k=void 0===k?0:k;if(void 0!=y){v=yb(t,y.toUpperCase());if(void 0==v){v=void 0;var G=t,V=nd(G.la,{address:null,type:0,name:y},G.Jc);0<=V&&(v=G.la[V].address.V);if(void 0==v)if(v=y,t.M[v]?v=t.M[v].value:(v=v.substr(0,6),v=t.M[v]&&t.M[v].value),void 0==v)v=Ga(y,1<y.length||10<t.fa?t.fa:10);else if(y=t.M[y]&&t.M[y].yg)z?z.push(y):(z=rd(t,y,z),void 0!==
z?v+=z:v=void 0)}void 0!=v&&(v=S(t,xd(t,v,k)))}t=v}else if("{"==q){p=1;for(t=c;c<d;)if(c++,q=c<b.length?b[c++]:"","{"==q)p++;else if("}"==q&&!--p)break;t=wd(a,b,t,c-1,a.fa,f);null!=t&&k&&(t=xd(a,t,k));p=c<d?b[c++].trim():"";q=c<d?b[c++]:""}else{if(" "==q)continue;if("^B"==q){a.fa=2;continue}if("^O"==q){a.fa=8;continue}if("^D"==q){a.fa=10;continue}if(!(k&-1073741824)){if("+"==q)continue;if("-"==q){k=k<<2|1;continue}if("~"==q||"^-"==q){k=k<<2|2;continue}if("^L"==q){k=k<<2|3;continue}}h=!0;break}if(void 0===
t)if(f)f.push(p),t=0;else{h=!0;break}n.push(S(a,t));if(" "==q)if(c<b.length-1&&!b[c])c++,q=b[c++];else{h=!0;break}if(!q)break;t="<"==a.W[0]?yd:zd;if(!t[q]){h=!0;break}m.length&&t[q]<=t[m[m.length-1]]&&vd(a,n,m,1);m.push(q);a.fa="^_"==q?10:e;k=0}if(h||!vd(a,n,m)||1!=n.length)h=!0;h?f||a.o("parse error (%s)\n",p||q):g=n.pop();a.fa=r;return g}
function Ad(a,b,c,d){for(var e,f=a.J/d|0;0<=(e=b.indexOf(c));){for(var g=0,h=e+1,k=f;h<b.length;){var n=b[h++];if(n==c){k=-1;break}if(!k)break;k--;n=n.charCodeAt(0);6==d&&(n-=32);n&=(1<<d)-1;g=S(a,g*Math.pow(2,d)+n,d*f,!0)}if(0<=k){a.o("parse error (%c%s%c)\n",c,b,c);return}b=b.substr(0,e)+D(a,g)+b.substr(h)}return b}
function rd(a,b,c){if(b){"{"!=a.W[0]&&(b=b.split(a.W[0]).join("{").split(a.W[1]).join("}"));b=Ad(a,b,'"',8);if(!b)return d;b=Ad(a,b,"'",6);if(!b)return d;16!=a.fa&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);var d=wd(a,b,0,b.length,a.fa,c)}return d}
function xd(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-S(a,b);break;case 2:b=ud(a,b,-1);break;case 3:for(d=35;0<=d&&!td(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function S(a,b,c,d){var e=b;c=c||a.J;if(d)if(32==c)e=b>>>0;else if(32>c)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),0>b||b>=a)e=b%a,0>e&&(e+=a)}else 32>=c?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}
l.Fb=function(a){function b(h){for(var k=0;k<h.length;k++)if(void 0!=h[k])return!1;return!0}if(-1>a)return Bd(this,this.Fb);var c="";if(0<=a){var d=this.i[a];if(void 0!=d){c=d>>8;d&=255;var e=this.m[c];if(e){var f=this.s[c],g=f[d];(c&1?e.Ob(g.V,this.l[c]):e.qb(g.V,this.l[c]))?(f[d]=void 0,this.i[a]=void 0,b(f)&&(f.length=0,b(this.i)&&(this.i.length=0)),c=this.L("%2d: %s %*a cleared\n",a,Cd[c],e.ea,g),--this.da||this.ha||(c+=Dd(this,!1))):c=this.L("invalid break address: %*a\n",e.ea,g)}else c="invalid bus"}else c=
this.L("invalid break index: %d\n",a)}else c="missing break index\n";return c};function Ed(a,b){if(a.U&&(void 0==b||a.U.V==b)){var c=void 0===c?R.Da:c;b=-1;var d=Fd(a.U,a.s[c]);if(0<=d)for(var e=0;e<a.i.length;e++){var f=a.i[e];if(void 0!=f&&c==f>>8&&d==(f&255)){b=e;break}}c=b;0<=c&&a.Fb(c);a.U=null}}
l.Gb=function(a,b){b=void 0===b?!1:b;if(-1>a)return Bd(this,this.Gb,b);if(0<=a){var c=this.i[a];if(void 0!=c){var d=c>>8;c=this.s[d][c&255];if(void 0!=c){var e=b?"enabled":"disabled",f=this.m[d];!c.disabled==!b?(c.disabled=!b,a=this.L("%2d: %s %*a %s\n",a,Cd[d],f.ea,c,e)):a=this.L("%2d: %s %*a already %s\n",a,Cd[d],f.ea,c,e)}else a=this.L("no break address at index: %d\n",a)}else a=this.L("invalid break index: %d\n",a)}else a="missing break index\n";return a};
function Bd(a,b,c){for(var d="",e=0;e<a.i.length;e++)void 0!=a.i[e]&&(d+=b.call(a,e,c));d||(d="no break addresses found");return d}function Gd(a,b,c){c=void 0===c?R.Da:c;a=a.s[c];for(c=0;c<a.length;c++){var d=a[c];if(d.V==b)return d}}function Fd(a,b){for(var c=0;c<b.length;c++)if(b[c].V==a.V)return c;return-1}
function Hd(a,b){b=void 0===b?!1:b;for(var c="",d=0;d<a.i.length;d++){var e=a.i[d];if(void 0!=e){var f=e>>8;e=a.s[f][e&255];f=a.L("%s %*a",Cd[f],a.m[f].ea,e);b?(c&&(c+=";"),c+=f,e.disabled&&(c+=";bd "+d)):c+=a.L("%2d: %s %s\n",d,f,e.disabled?"disabled":"enabled")}}c||b||(c="no break addresses found\n");return c}
function Id(a,b,c){c=void 0===c?R.Da:c;if(b){var d=a.m[c];if(d){var e=a.s[c];var f=Fd(b,e);if(0<=f)f=-(f+1);else{for(f=0;f<e.length&&void 0!=e[f];f++);e[f]=b}e=f;if(0<=e)if(f=c&1?d.Mb(b.V,a.l[c]):d.pb(b.V,a.l[c])){for(f=0;f<a.i.length&&void 0!=a.i[f];f++);a.i[f]=c<<8|e;b=a.L("%2d: %s %*a set\n",f,Cd[c],d.ea,b);a.da++||a.h.length||(b+=Dd(a,!0))}else b=a.L("invalid break address: %*a\n",d.ea,b),a.s[c][e]=void 0;else b=a.L("%s %*a already set\n",Cd[c],d.ea,b)}else b="invalid bus"}else b="missing break address\n";
return b}function Jd(a,b){0<=b&&(a.K=b);var c="instruction break count: "+(0<a.K?a.K:"disabled")+"\n";0<b&&(a.h.length||(c+=Dd(a,!0)),a.ha=!0);return c}function Kd(a,b){var c;if(b){var d=gb(b);void 0!=d?a.ka=d?0xffffffffffff:0:c=a.L("unrecognized message option: %s\n",b)}c||(c=a.L("break on message: %b\n",!!a.ka));return c}l.Ld=function(a,b){this.u||(void 0==a?T(this,"break on unknown input %#0x: %#0x",b):(a=Gd(this,a+b,R.Ta))&&!a.disabled&&T(this,"break on input %*a: %#0x",this.j.ea))};
l.Md=function(a,b){this.u||(void 0==a?T(this,"break on unknown output %#0x: %#0x",b):(a=Gd(this,a+b,R.Ua))&&!a.disabled&&T(this,"break on output %*a: %#0x",this.j.ea))};l.Nd=function(a,b){this.u||(void 0==a?T(this,"break on unknown read %#0x: %#0x",b):(a+=b,this.h.length&&a==this.v.Kb&&(this.Z++,0<this.K&&(--this.K||T(this,"break on instruction count")),this.h[this.R++]=a,this.R==this.h.length&&(this.R=0)),(b=Gd(this,a,R.Da))&&!b.disabled&&(T(this,"break on read %*a: %#0x",this.g.ea),Ed(this,a))))};
l.Qd=function(a,b){this.u||(void 0==a?T(this,"break on unknown write %#0x: %#0x",b):(a=Gd(this,a+b,R.$a))&&!a.disabled&&T(this,"break on write %*a: %#0x",this.g.ea))};function T(a,b,c){b=a.L.apply(a,[b].concat(ba(c)));a.o("%s\n",b);Bc(a.time)}function Ld(a,b,c){c=void 0===c?a.g:c;return D(a,b.V,a.fa,c.ea,"")}
function Md(a,b,c){c=void 0===c?10:c;var d="";if(a.h.length){var e,f=[];c>a.h.length&&(c=a.h.length);0>b&&(b=c);var g=a.R-b;for(0>g&&(g+=a.h.length);0<=g&&g<a.h.length&&0<c;){var h=a.h[g++];if(void 0==h)break;g==a.h.length&&(g=0);e?e.V=h:e=jd(h);for(h=0;h<a.ja;h++)f[h]=sd(a,e,1);pd(a,e,-f.length);d+=a.Nb(e,f,a.L("[%6d]",b--));c--}}return d||"no history"}
function fd(a,b,c){var d=[],e="";for(b="number"==typeof b?jd(b):b;c--;){for(pd(a,b,d.length);d.length<a.ja;)d.push(sd(a,b,1));pd(a,b,-d.length);e+=a.Nb(b,d)}return e}
function Nd(a,b,c,d,e,f){var g="";f=f?a.j:a.g;c||(c=f.j);var h=c>>3;d||(d=128);var k=0,n=d+15>>4||1,m=4==h?16:a.fa;"y"==e&&(m=h,n=d,k=8*h);b||(b=a.ua);for(;n--&&0<d;){var r=e=0,p,q="",v="",t=Ld(a,b,f);for(p=m;0<p&&0<d;p--){var y=sd(a,b,1,f);e|=y<<(r++<<3);r==h&&(q+=D(a,e,0,c,""),q+=1==h?9==p?"-":" ":" ",k&&(v+=D(a,e,2,c,"")),e=r=0);k||(v+=32<=y&&127>y?String.fromCharCode(y):".");d--}g&&(g+="\n");g+=t+"  "+q+" "+v}a.ua=b;return g}
l.Yd=function(){var a=[];wb(this,function(b){b.cb&&b.cb(a);return!0});return JSON.stringify(a,null,2)};function Od(a,b,c,d){var e=0,f="";d=d?a.j:a.g;for(var g=0;void 0!=b&&g<c.length;g++){var h=sd(a,b,0,d);if(void 0==h)break;var k=a,n=b,m=c[g],r=d;r=void 0===r?k.g:r;k.u++;r.eb(n.V,m);k.u--;f+=a.L("%*a: %#*n changed to %#*n\n",a.g.ea,b,a.g.j,h,a.g.j,c[g]);pd(a,b,1,d);e++}e||(f+=a.L("%d locations updated\n",e));a.time.update();return f}
function Dd(a,b){var c="";void 0!=b&&b==!a.h.length&&Vc(a.g,function(d){b?a.g.pb(d.ia,a.l[R.Da]):a.g.qb(d.ia,a.l[R.Da])})&&(b?(a.R=0,a.h=Array(Pd)):a.h=[]);return c+=a.L("instruction history %s\n",a.h.length?"enabled":"disabled")}l.xa=function(a){var b=a.shift();return this.S==b?(fb(this,a.shift()),this.X.pa=a.shift(),!0):!1};l.Qc=function(a){Ha(this.ka,a)?T(this,"break on message"):this.time.R=!0};
l.ce=function(a){var b=a[1],c=a[2],d=[],e=[],f=!1,g="";this.N=void 0;if("*"==c)var h=-2;else{h=Ga(c);void 0==h&&(h=-1);var k=ld(this,c,e);if(null===k)return}var n=0;a[3]&&(n=Ga(a[3].substr("l"==a[3][0]?1:0))||8);for(var m=3;m<a.length;m++)d.push(Ga(a[m],16));if("d"==b){m=kd(this,c,d);if(void 0!=m)return m;b=this.T||b}if("s"!=b[0]&&e.length)return"unrecognized symbol(s): "+e;switch(b[0]){case "b":"c"==b[1]?g=this.Fb(h):"d"==b[1]?g=this.Gb(h):"e"==b[1]?g=this.Gb(h,!0):"i"==b[1]?g=Id(this,k,R.Ta):"l"==
b[1]?g=Hd(this):"m"==b[1]?g=Kd(this,c):"n"==b[1]?g=Jd(this,h):"o"==b[1]?g=Id(this,k,R.Ua):"r"==b[1]?g=Id(this,k,R.Da):"w"==b[1]?g=Id(this,k,R.$a):"?"==b[1]?(g="break commands:\n",Qd.forEach(function(r){g+=r+"\n"})):b[1]&&(g=void 0);break;case "d":this.T=b;if("b"!=b[1]&&b[1])if("w"==b[1])c=16;else if("d"==b[1])c=32;else if("i"==b[1]){if(!this.j){g="invalid bus";break}c=this.j.j;n=n||1;f=!0}else{if("h"==b[1])this.T="",g=Md(this,h,n);else if("?"==b[1]){if(this.T="",g="dump commands:\n",Rd.forEach(function(r){g+=
r+"\n"}),this.I.length)for(g+="dump extensions:\n",b=0;b<this.I.length;b++)k=this.I[b],g+=this.L("d   %-12s%s\n",k.name,k.Wd)}else this.T="",g=void 0;break}else c=8;g=Nd(this,k,c,n,b[2],f);break;case "e":if("o"==b[1]){if(!this.j){g="invalid bus";break}f=!0}else if(b[1]){g=void 0;break}g=Od(this,k,d,f);break;case "g":if(this.time.start()){if(void 0!=k){Ed(this);g=Id(this,k);if(2!=g.indexOf(":"))break;this.U=k;g=""}break}g="already started\n";break;case "h":Bc(this.time)||(g="already stopped\n");break;
case "p":a.shift();a.shift();b=a.join(" ");g+=this.L("%s = %s\n",b,D(this,rd(this,b)));break;case "r":if(b=b.substr(1).toUpperCase()){if(void 0==yb(this.v,b)){g+=this.L("unrecognized register: %s\n",b);break}void 0!=k&&Db(this.v,b,k.V)}this.ba.V=this.v.Za;g+=this.v.toString();break;case "s":k=gb(c);if("h"==b[1]){if(this.da||0<this.K)k=void 0;g=Dd(this,k);void 0!=k&&(this.ha=k)}else"p"==b[1]?0<h?(yc(this.time,h),g="target speed:  "+Ec(this.time.s)):g="current speed: "+Mc(this.time):"s"==b[1]&&this.wa?
(h=this.wa.indexOf(c),0<=h&&(this.style=this.wa[h]),g="style: "+this.style):"?"==b[1]?(g="set commands:\n",Sd.forEach(function(r){g+=r+"\n"})):g=void 0;break;case "t":n=Ga(c,10)||1;this.N=!0;if(b[1]){if("r"!=b[1]){g=void 0;break}this.N=!1}Gc(this.time,n);break;case "u":if(b[1]){g=void 0;break}n||(n=8);k||(k=this.ba);g+=fd(this,k,n);this.ba=k;break;case "?":g="debugger commands:\n";Td.forEach(function(r){g+=r+"\n"});break;default:g=void 0}void 0==g&&a[0]&&(g="unrecognized command '"+a[0]+"' (try '?')\n");
return g};l.Hb=function(a){return a&&this.xa(a[0])?(a.shift(),!0):!1};l.cb=function(a){var b=[];this.ya(b);a.push(b);this.$=0};l.Rc=function(a){if(a){if(this.time.g){if(this.$&&this.oa){a=this.oa;var b=a.i;b&&zb(a.X)&&(a.o(2097152,'setFocus("%s")\n',b.id||b.nodeName),b.focus(),b.scrollIntoView())}}else this.N?this.Na(fd(this,this.v.Za,1)):(this.Z&&(this.v.o("%d instructions executed\n",this.Z),this.Z=0),this.v.Na(this.v.toString()),void 0==this.N&&this.$&&(a=this.Sa(Na.ib,!0))&&a.focus());this.$++}};
l.ya=function(a){a.push(this.S);a.push(Hd(this,!0));a.push(this.X.pa)};l.Nb=function(a,b,c){var d=this.L,e=Ld(this,a);b=b.shift();pd(this,a,1);return d.call(this,"%s %02x       unsupported       ; %s\n",e,b,c||"")};
var Td="b?\t\tbreak commands;d?\t\tdump commands;e[o] [addr] ...\tedit memory/ports;g    [addr]\trun (to addr);h\t\thalt;p    [expr]\tparse expression;r?   [value]\tdisplay/set registers;s?\t\tset commands;t[r] [n]\tstep (n instructions);u    [addr] [n]\tunassemble (at addr)".split(";"),Qd="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write;bm [on|off]\tbreak on message;bn [count]\tbreak on instruction count".split(";"),
Rd="db  [addr]\tdump bytes (8 bits);dw  [addr]\tdump words (16 bits);dd  [addr]\tdump dwords (32 bits);di  [addr]\tdump input ports;d*y [addr]\tdump values in binary;dh  [n] [l]\tdump instruction history buffer;ds\t\tdump machine state".split(";"),Sd=["sh [on|off]\tset instruction history","sp [n]\t\tset speed multiplier","ss\t\tset debugger style"],qd={zc:1,td:0,ud:2,hg:0},R={Da:0,$a:1,Ta:2,Ua:3},Ud={},Cd=(Ud[R.Da]="br",Ud[R.$a]="bw",Ud[R.Ta]="bi",Ud[R.Ua]="bo",Ud),Vd={sd:"PC"},Wd={BYTE:1,rd:2,vd:4,
nc:5,Yb:6,Id:7},md={"=":Wd.Id,1:Wd.BYTE,2:Wd.rd,4:Wd.vd,"@":Wd.nc,";":Wd.Yb},Pd=1E5,zd={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},yd={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};function Xd(a,b,c){gd.call(this,a,b,c)}w(Xd,gd);
function Yd(a,b,c){gd.call(this,a,b,c);this.model=+this.H.model||Zd;this.T=+this.H.addrReset||0;this.s=N(this,"Bus");this.s.I=this.nd.bind(this);this.ae=N(this,"IOPage");N(this,"Panel",!1);this.K=0;this.Wa=null;N(this,"Input",!1);this.model<=$d?(this.Fc=this.Od,this.Hc=~(ae|be|ce|de)&65535,this.Gc=0):(this.Fc=this.Pd,this.Hc=~(ae|(this.model<=ee?be:0))&65535,this.Gc=this.model>ee?be:0);this.Bb=this.Ab=this.la=0;this.l=null;this.Pa=[];fe(this)}w(Yd,Xd);
function fe(a){a.ba=65536;a.ha=32768;a.ja=65535;a.da=32768;a.W=15;a.h=[0,0,0,0,0,0,0,a.T,-1,-2,-3,-4,-5,-6,-7,-8];a.Z=[0,0,0,0,0,0];a.va=[0,0,0,0];a.wa=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];a.Ca=[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535,65535],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]];a.Ma=
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];a.Oc=[0,0,0,0,0,0,0,0];a.i=0;a.u=-1;a.Ic=0;a.g=0;ge(a);for(var b={Ka:0};7>=b.Ka;b={Ka:b.Ka},b.Ka++)M(a,"R"+b.Ka,function(c){return function(){return a.h[c.Ka]}}(b),function(c){return function(d){return a.h[c.Ka]=d&65535}}(b));vb(a,"R6","SP");vb(a,"R7",Vd.sd);M(a,"CF",function(){return a.ba&65536&&he?1:0},function(c){a.ba=c?65536:0});M(a,"NF",function(){return a.da&32768&&ke?1:0},function(c){a.da=c?32768:0});M(a,"VF",function(){return a.ha&
32768&&le?1:0},function(c){a.ha=c?32768:0});M(a,"ZF",function(){return(a.ja&65535?0:me)?1:0},function(c){a.ja=c?0:1});M(a,"PS",function(){return ne(a)},function(c){return oe(a,c)});M(a,"PI",function(){return a.ua},function(c){if(c&=pe){var d=c>>qe;do c+=re;while(d>>=1);a.g|=se}a.ua=c});M(a,"ER",function(){return a.sa});M(a,"SL",function(){return a.M&65280},function(c){a.M=c|255});M(a,"M0",function(){return te(a)},function(c){return ue(a,c)});M(a,"M1",function(){return ve(a)});M(a,"M2",function(){return we(a)});
M(a,"M3",function(){return a.I},function(c){return xe(a,c)})}function ge(a){a.j=0;a.ma=0;a.oa=0;a.I=0;a.sa=0;a.ua=0;a.M=255;a.U=0;a.N=0;a.R=0;a.J=262143;a.Rb=[4,2,0,1];a.O=a.h[7];a.m=0;a.l=null;ye(a);for(var b=a.s,c=Q.Qa,d=0,e=0;e<b.g.length;e++){var f=b.g[e];f.type&c&&(d=f.ia+f.size)}a.$d=d}l=Yd.prototype;l.Rc=function(){};function te(a){var b=a.j;b&ze||(b=b&~(Ae|Be|Ce)|a.N<<5|a.R<<1);return b}
function ue(a,b){b&=~Ae;if(a.j!=b){b&ze&&!(a.j&ze)&&(a.ma=a.m>>16&65535,a.oa=a.m&65535);a.j=b;a.N=(b&Ce)>>De;a.R=(b&Be)>>Ee;var c=0;b&(Fe|Ge)&&(c=He,b&Fe&&(c|=Ie));a.U!=c&&(a.U=c,ye(a))}}function ve(a){a.j&ze||(a.ma=a.m>>16&65535);a=a.ma;a&65280&&(a=(a<<8|a>>8)&65535);return a}function we(a){a.j&ze||(a.oa=a.m&65535);return a.oa}function xe(a,b){a.model<Zd&&(b&=~(Je|Ke));a.I!=b&&(a.I=b,a.J=b&Je?Le:Me,ye(a))}
function ye(a){a.Wa&&Wc(a.s,a.K,a.Wa);a.U?(a.Ra=Ne,a.K=a.I&Je?Oe:Pe,a.Xa=a.te,a.Pc=a.Qe):(a.Ra=0,a.K=Qe,a.Xa=a.se,a.Pc=a.Pe);a.Wa=Wc(a.s,a.K,a.ae)}
l.xa=function(a){if(!a||!a.length)return this.o("invalid saved state\n"),!1;var b=a.shift(),c=a.shift();if(b!=this.S||3!==(c|0))return this.o("CPU state mismatch (%s %3.2f)\n",b,c),!1;try{this.h=a.shift();this.Z=a.shift();this.va=a.shift();this.wa=a.shift();this.Ca=a.shift();this.Ma=a.shift();this.Oc=a.shift();this.sa=a.shift();this.Ic=a.shift();this.ua=a.shift();this.M=a.shift();this.N=a.shift();this.R=a.shift();this.O=a.shift();this.g=a.shift();this.m=a.shift();this.u=a.shift();this.Ab=a.shift();
this.Bb=a.shift();this.T=a.shift();oe(this,a.shift());ue(this,a.shift());this.ma=a.shift();this.oa=a.shift();xe(this,a.shift());for(var d=a.shift(),e=d.length-1;0<=e;e--){a:{for(a=0;a<this.Pa.length;a++){var f=this.Pa[a];if(f.sb===d[e]){var g=f;break a}}g=null}g&&(g.next=this.l,this.l=g)}}catch(h){return this.o("CPU state error: %s\n",h.message),!1}return!0};
l.ya=function(a){a.push(this.S);a.push(3);a.push(this.h);a.push(this.Z);a.push(this.va);a.push(this.wa);a.push(this.Ca);a.push(this.Ma);a.push(this.Oc);a.push(this.sa);a.push(this.Ic);a.push(this.ua);a.push(this.M);a.push(this.N);a.push(this.R);a.push(this.O);a.push(this.g);a.push(this.m);a.push(this.u);a.push(this.Ab);a.push(this.Bb);a.push(this.T);a.push(ne(this));a.push(te(this));a.push(ve(this));a.push(we(this));a.push(this.I);for(var b=a.push,c=[],d=this.l;d;)c.push(d.sb),d=d.next;b.call(a,c)};
function Re(a,b,c){b={sb:b,priority:4,message:c||0,name:Se[b],next:null};a.Pa.push(b);return b}function Te(a,b){if(b){if(b!=a.l){var c=a.l;if(!c||c.priority<=b.priority)b.next=c,a.l=b;else{do{var d=c.next;if(!d||d.priority<=b.priority){b.next=d;c.next=b;break}c=d}while(c)}}a.g|=se;a.o(1024+b.message,"setIRQ(vector=%o,priority=%d)\n",b.sb,b.priority+")")}}function ne(a){return a.W=a.W&(de|ce|be|Ue|Ve)|(a.da&32768?ke:0)|(a.ja&65535?0:me)|(a.ha&32768?le:0)|(a.ba&65536?he:0)}
function oe(a,b){b&=a.Hc;a.da=b<<12;a.ja=~b&4;a.ha=b<<14;a.ba=b<<16;if((b^a.W)&a.Gc)for(var c=a.Z.length;0<=--c;){var d=a.h[c];a.h[c]=a.Z[c];a.Z[c]=d}a.i=b>>We&Xe;c=a.W>>We&Xe;a.i!=c&&(a.va[c]=a.h[6],a.h[6]=a.va[a.i]);a.W=b;a.g&=~Ye;a.g|=a.l?Ye:se}l.nd=function(a,b){3>=b&&(this.v.sa|=Ze);$e(this,af,0,a)};
function $e(a,b,c,d){a.o(4096,"trap to vector %o (%o: %s)\n",b,d,0>d?bf[-d]:"BUS ERROR");if(!a.la){0>a.u?a.u=ne(a):a.i||(d=cf);d==cf&&(a.g&df&&(d=ef),a.g|=df,a.sa|=ff,a.h[6]=b=4);if(d!=ef){a.m=b|4143316992;a.i=0;var e=a.Xa(b|a.Ra),f=a.Xa(b+2&65535|a.Ra);oe(a,f&~ce|a.u>>2&ce);gf(a,a.u);gf(a,a.h[7]);a.h[hf]=e&65535}a.g&=~(c|jf|kf);a.g=a.g|se|lf;a.u=-1;a.Ab=d;a.Bb=b;d==ef&&Bc(a.time);if(d>=cf)throw b;}}function mf(a,b){var c=b>>13&31;31>c&&(b=a.I&Ke?a.Ma[c]+(b&8191)&Le:b&~nf);return b}
function of(a,b,c){if(!(c&a.U)){var d=b&65535;d>=Qe&&(d|=a.K);return d}var e=b>>13;a.I&a.Rb[a.i]||(e&=7);var f=a.Ca[a.i][e];d=(a.wa[a.i][e]<<6)+(b&8191)&a.J;d>=nf&&(d=mf(a,d));if(a.la)return d;d>=a.$d&&d<a.K?(a.sa|=pf,$e(a,af,0,d)):d&1&&!(c&qf)&&(a.sa|=rf,$e(a,af,0,d));var g=0;switch(f&sf){case tf:g=uf;case vf:f|=wf;c&He&&(g=xf);break;case yf:g=uf;case zf:c&He&&(g=uf);case Af:f|=c&He?wf|Bf:wf;break;default:g=Cf}(f&(Df|Ef))!=Df&&(f&Ef?f&Df&&(b&8128)<(f>>2&8128)&&(g|=Ff):(b&8128)>(f>>2&8128)&&(g|=Ff));
a.Ca[a.i][e]=f;if(d!=((Oe|Gf)&a.J)||a.i)a.N=a.i,a.R=e;g&&(g&ze&&(0<=a.u&&(g|=Hf),a.j&ze||(g|=a.j&uf|a.N<<5|a.R<<1,ue(a,a.j&~If|g&If)),$e(a,Jf,Kf,Lf)),a.j&(ze|uf)||!(d<((Oe|Mf)&a.J)||d>((Oe|Nf|1)&a.J))||(a.j|=uf,a.j&Of&&(a.g|=Kf)));return d}function gf(a,b){var c=a.h[6]-2&65535;a.h[6]=c;a.m=a.m&65535|(a.m&-65536)<<8|16121856;a.g&df||a.Fc(Pf,-2,c);a.Pc(c,b)}l.Od=function(a,b,c){!this.i&&0>=b&&c<=this.M&&(this.g|=Qf)};
l.Pd=function(a,b,c){this.i||(65534<=c&&(c|=-65536),a&He&&c<=this.M&&(c<=this.M-32?$e(this,af,0,cf):(this.sa|=Rf,this.g|=Qf)))};l.se=function(a){return this.s.na(this.O=a)};l.te=function(a){return this.s.na(this.O=of(this,a,Sf))};l.Pe=function(a,b){this.s.ga(this.O=a,b)};l.Qe=function(a,b){this.s.ga(this.O=of(this,a,Pf),b)};
l.toString=function(){var a="";if(this.aa)for(var b="R0 R1 R2 R3 R4 R5  SP PC PS PI SL NF ZF VF CF  M0 M1 M2 M3 ER  SR AR DR".split(" "),c=0;c<b.length;c++){var d=b[c];if(d){var e=16;"F"==d[1]&&(e=1);var f=yb(this,d);void 0!=f&&(a+=this.aa.L("%s=%*n ",d,e,f))}else a+="\n"}return a};
var $d=1120,ee=1140,Zd=1170,Xe=3,he=1,le=2,me=4,ke=8,Ve=16,Ue=224,ae=1792,be=2048,ce=12288,de=49152,We=14,pe=65024,re=34,qe=9,af=4,Jf=168,ef=-1,Lf=-2,cf=-4,bf="UNKNOWN PANIC ABORT ILLEGAL RED YELLOW FAULT TRACE HALT OPCODE INTERRUPT".split(" "),se=1,Ye=2,kf=3,jf=16,Qf=32,Kf=64,lf=128,df=256,hf=7,qf=1,Ie=2,He=4,Ne=65536,ff=4,Rf=8,Ze=16,pf=32,rf=64,Fe=1,Be=30,Ce=96,Hf=128,Ge=256,Of=512,Ae=3072,uf=4096,xf=8192,Ff=16384,Cf=32768,ze=57344,If=61694,Ee=1,De=5,Je=16,Ke=32,tf=1,vf=2,yf=4,zf=5,Af=6,sf=7,Ef=
8,Bf=64,wf=128,Df=32512,Mf=62592,Gf=65402,Nf=65470,Se={48:"DL11R",52:"DL11X",56:"PC11R",60:"PC11X",64:"KW11",112:"RL11",144:"RK11",180:"RX11"},Sf=0|Ie,Pf=0|He,Qe=57344,Pe=253952,Oe=4186112,Me=262143,nf=3932160,Le=4194303;x.PDP11=Yd;function Tf(a,b,c){id.call(this,a,b,c);this.va=Uf;this.O=[];this.v.model<ee&&(this.O=this.O.concat(Vf));1145>this.v.model&&(this.O=this.O.concat(Wf));this.ja=6}w(Tf,id);
Tf.prototype.Nb=function(a,b,c){function d(B){var A=k.v,C=[];if(A.U){var P=A.i<<1,L=B>>13;7<L&&(P|=1);A.I&A.Rb[A.i]||(L&=7);var ie=B&8191,je=A.wa[A.i][L]<<6;B=je+ie&A.J;B>=nf&&(B=mf(A,B));C.push(B);C.push(ie);C.push(P);C.push(L&7);C.push(je);C.push(A.J)}else B&=65535,B>=Qe&&(B|=A.K),C.push(B);return null}function e(B){return Xf[B]||"?"}function f(B,A){var C="",P=A&Yf;if(P==U)C=a.V+((B&255)<<24>>23)&65535,C=h(C);else if(P==Zf)C=a.V-((B&63)<<1)&65535,C=h(C);else if(P==$f)C=D(k,B&7,0,3,"");else if(P==
ag)C=D(k,B&63,0,6,"");else if(P==bg)C=D(k,B&255,0,8,"");else if(B&=A,A&W&&(B>>=6,A>>=6),A&X){P=null;var L=B&7;switch(B&56){case 0:C=e(L);break;case 8:C="@"+e(L);P=d(k.v.h[L]);break;case 16:7>L?C="("+e(L)+")+":(A=g(),C="#"+h(A));break;case 24:7>L?C="@("+e(L)+")+":(A=g(),C="@#"+h(A),P=d(A));break;case 32:C="-("+e(L)+")";break;case 40:C="@-("+e(L)+")";break;case 48:A=g();C=h(A)+"("+e(L)+")";7==L&&(C=h(A=A+a.V&65535),P=d(A));break;case 56:A=g(),C="@"+h(A)+"("+e(L)+")",7==L&&(C="@"+h(A=A+a.V&65535),B=
k.v,B.la++,A=B.s.na(of(B,A,Sf)),B.la--,P=d(A))}P&&(C=[C,P])}return C}function g(){var B=b.shift()|b.shift()<<8;m+=h(B)+" ";pd(k,a,2);return B}function h(B){return D(k,B,0,16,"")}var k=this,n=Ld(this,a),m="",r=od(this,a,Wd.nc),p=od(this,a,Wd.Yb),q=g(),v;for(y in this.va)if(v=this.va[y][q&y])break;v||(v=cg);var t=v[0];0<=this.O.indexOf(t)&&(v=cg,t=v[0]);var y=dg[t];var z="",G=v.length-1;t||G||(z=h(q));for(t=1;t<=G;t++){var V=v[t];if(void 0!=V){V=f(q,V);if(!V||!V.length){z="INVALID";break}"string"!=
typeof V&&(V=V[0]);0<z.length&&(z+=",");z+=V||"???"}}n=this.L("%s %-21s %-7s %s",n,m,y,z);c?p&&(c+=" "+p):p&&(c=p);c&&(n=this.L("%-32s; %s",n,c));r&&(n=r+":\n"+n);return n+"\n"};
var dg=".WORD ADC ADCB ADD ASL ASLB ASR ASRB BCC BCS BEQ BGE BGT BHI BIC BICB BIS BISB BIT BITB BLE BLOS BLT BMI BNE BPL BPT BR BVC BVS CCC CLC CLCN CLCV CLCVN CLCVZ CLCZ CLCZN CLN CLR CLRB CLV CLVN CLVZ CLVZN CLZ CLZN CMP CMPB COM COMB DEC DECB INC INCB HALT JMP JSR MARK MFPD MFPI MFPS MOV MOVB MTPD MTPI MTPS NEG NEGB NOP RESET ROL ROLB ROR RORB RTI RTS SBC SBCB SCC SEC SECN SECV SECVN SECVZ SECZ SECZN SEN SEV SEVN SEVZ SEVZN SEZ SEZN SUB SWAB SXT TST TSTB WAIT MUL DIV ASH ASHC XOR SOB EMT TRAP SPL IOT RTT MFPT".split(" "),Xf=
"R0 R1 R2 R3 R4 R5 SP PC A0 A1 A2 A3 A4 A5 A6 A7 S0 S1 S2 S3 PS PI ER SL M0 M1 M2 M3 AR DR SR".split(" "),X=63,W=4032,U=4096,Zf=8192,$f=12288,ag=24576,bg=32768,Yf=61440,Uf={61440:{4096:[62,W,X],8192:[47,W,X],12288:[18,W,X],16384:[14,W,X],20480:[16,W,X],24576:[3,W,X],36864:[63,W,X],40960:[48,W,X],45056:[19,W,X],49152:[15,W,X],53248:[17,W,X],57344:[94,W,X]},65024:{2048:[57,448,X],28672:[100,X,448],29184:[101,X,448],29696:[102,X,448],30208:[103,X,448],30720:[104,448,X],32256:[105,448,Zf]},65280:{256:[27,
U],512:[24,U],768:[10,U],1024:[11,U],1280:[22,U],1536:[12,U],1792:[20,U],32768:[25,U],33024:[23,U],33280:[13,U],33536:[21,U],33792:[28,U],34048:[29,U],34304:[8,U],34560:[9,U],34816:[106,bg],35072:[107,bg]},65472:{64:[56,X],192:[95,X],2560:[39,X],2624:[49,X],2688:[53,X],2752:[51,X],2816:[67,X],2880:[1,X],2944:[77,X],3008:[97,X],3072:[73,X],3136:[71,X],3200:[6,X],3264:[4,X],3328:[58,ag],3392:[60,X],3456:[65,X],3520:[96,X],35328:[40,X],35392:[50,X],35456:[54,X],35520:[52,X],35584:[68,X],35648:[2,X],
35712:[78,X],35776:[98,X],35840:[74,X],35904:[72,X],35968:[7,X],36032:[5,X],36096:[66,X],36160:[59,X],36224:[64,X],36288:[61,X]},65528:{128:[76,7],152:[108,$f]},65535:{0:[55],1:[99],2:[75],3:[26],4:[109],5:[70],6:[110],7:[111],160:[69],161:[31],162:[41],163:[33],164:[45],165:[36],166:[43],167:[35],168:[38],169:[32],170:[42],171:[34],172:[46],173:[37],174:[44],175:[30],176:[69],177:[80],178:[88],179:[82],180:[92],181:[85],182:[90],183:[84],184:[87],185:[81],186:[89],187:[83],188:[93],189:[86],190:[91],
191:[79]}},cg=[0],Vf=[58,60,65,96,110,100,101,102,103,104,105],Wf=[108,59,64];x.PDP11Dbg=Tf;function eg(a,b,c){$c.call(this,a,b,c);for(var d in fg){var e=fg[d];d=+d;a=e[0];b=e[1];c=e[2];e=e[3];65472<=d&&65487>=d&&(!a&&c&&(a=function(f){return function(g){return f(g)&255}}(c)),!b&&e&&(b=function(f){return function(g,h){return f(g,h)}}(e)));ad(this,this,d,d,a,b,c,e)}this.ra()}w(eg,$c);l=eg.prototype;l.qa=function(){void 0===this.v&&(this.v=N(this,"Debugger"))};
l.xa=function(a){return a&&(a=a.shift(),this.S==a)?!0:!1};l.ya=function(a){a.push(this.S)};l.pe=function(a){a=a>>1&63;var b=this.v.Ma[a>>1];return a&1?b>>16:b&65535};l.Me=function(a,b){a=a>>1&63;var c=a>>1;this.v.Ma[c]=a&1?this.v.Ma[c]&65535|(b&63)<<16:this.v.Ma[c]&-65536|b&65534};var gg={},fg=(gg[61568]=[null,null,eg.prototype.pe,eg.prototype.Me,"UNIMAP",64,Zd],gg);x.IOPage=eg;ya.dl11=268435456;
function Y(a,b,c){K.call(this,a,b,c);this.N=+this.H.baudReceive||9600;this.R=+this.H.baudTransmit||9600;this.time=N(this,"Time");this.T=Lb(this.time,this.S+".receive",this.Sc.bind(this));this.U=Lb(this.time,this.S+".transmit",this.Be.bind(this));this.ports=N(this,"IOPage");bd(this.ports,this,hg);this.j="";this.i=this.l=this.u=null;this.exports={connect:this.be,receiveData:this.Sc,receiveStatus:this.we,setConnection:this.ye};this.ra()}w(Y,K);l=Y.prototype;
l.be=function(a){if(!this.i){var b=xb(this,"connection");if(b){var c=b.split("->");if(2==c.length){var d=c[0].trim();if(d!=this.S)return;c=c[1].trim();if(this.i=tb(this,c)){var e=this.i.exports;if(e){var f=e.connect;f&&f.call(this.i,this.J);if(this.l=e.receiveData){this.J=a;this.u=e.receiveStatus;this.o("Connected %s.%s to %s\n",this.Y,d,c);return}}}}this.o("Unable to establish connection: %s\n",b)}}};
l.xa=function(a){var b=a.shift();return this.S==b?(this.m=a.shift(),this.g=a.shift(),this.h=a.shift(),this.I=a.shift(),!0):!1};l.ya=function(a){a.push(this.S);a.push(this.m);a.push(this.g);a.push(this.h);a.push(this.I)};l.qa=function(){this.v||(this.v=N(this,"CPU"),this.M=Re(this.v,this.O?-1:48,128),this.s=Re(this.v,this.O?-1:52,128))};l.ra=function(){this.m=0;this.g=8192;this.h=128;this.I=[]};
l.Sc=function(a){null!=a&&(this.j="number"!=typeof a?a:this.j+String.fromCharCode(a));this.j&&(a=this.j.charCodeAt(0),this.o(128,"receiveByte(%#04x)\n",a),this.K?a=!1:(this.m=a,this.g&128?this.m|=49152:this.g|=128,this.g&64&&Te(this.v,this.M),a=!0),a&&(this.j=this.j.substr(1)),this.j&&Qb(this.time,this.T,1E3/Math.round(this.N/10)));return!0};l.we=function(a){var b=this.g;this.g&=-12289;a&ta.$b.ta&&(this.g|=8192);a&ta.Vb.ta&&(this.g|=4096);b!=this.g&&(this.g|=32768,this.g&32&&Te(this.v,this.M))};
l.ye=function(a,b){return this.i?!1:(this.i=a,this.l=b,!0)};l.Be=function(a){var b=!0;this.h|=128;this.h&64&&Te(this.v,this.s);a&&(b=this.l?this.l.call(this.i,a):!1);return b};l.oe=function(){var a=this.g&65534;this.g&=-32769;return a};l.Le=function(a){var b=a^this.g;this.g=this.g&-112|a&111;this.u&&b&6&&(b=0,this.J?(b|=a&4?ta.$b.ta:0,b|=a&2?ta.$c.ta|ta.Vb.ta:0):(b|=a&4?ta.xd.ta:0,b|=a&2?ta.ad.ta:0),this.u.call(this.i,b))};l.ne=function(){this.g&=-129;return this.m};l.Ke=function(){};l.ve=function(){return this.h};
l.Se=function(a){if(this.h&128)if(a&64)Te(this.v,this.s);else{var b=this.v,c=this.s;if(c){var d=b.l;if(d==c)b.l=c.next;else for(;d;){var e=d.next;if(e==c){d.next=e.next;break}d=e}b.l&&(b.g|=se);b.o(1024+c.message,"clearIRQ(vector=%o,priority=%d)\n",c.sb,c.priority+")")}}this.h=this.h&-70|a&69};l.ue=function(){return 0};
l.Re=function(a){a:{a&=255;this.o(128,"transmitByte(%#04x)\n",a);if(this.W){if(19==a){this.K=!0;break a}if(17==a){this.K=!1;break a}}this.l&&this.l.call(this.i,a);Qb(this.v,this.U,1E3/Math.round(this.R/10))}this.h&=-129};var ig={},hg=(ig[65392]=[null,null,Y.prototype.oe,Y.prototype.Le,"RCSR"],ig[65394]=[null,null,Y.prototype.ne,Y.prototype.Ke,"RBUF"],ig[65396]=[null,null,Y.prototype.ve,Y.prototype.Se,"XCSR"],ig[65398]=[null,null,Y.prototype.ue,Y.prototype.Re,"XBUF"],ig);x.DL11=Y;ya.pc11=536870912;
function Z(a,b,c){K.call(this,a,b,c);this.name=this.H.name||"PTR";this.h=xb(this,"autoLoad")||"";this.R=+this.H.baudReceive||3600;this.i=this.H.library||[];this.u=null;this.M=window&&"FileReader"in window;this.J=N(this,"Bus");this.time=N(this,"Time");this.T=Lb(this.time,this.S+".reader",this.Jd.bind(this));N(this,"Input");this.I=null;this.m=this.g=0;this.K=32768;this.j=this.N=0;this.s=[];this.l=jg;this.O=-1;this.ports=N(this,"IOPage");bd(this.ports,this,kg);Za(this,this.i,this.ee.bind(this))||Ab(this,
!1)}w(Z,K);l=Z.prototype;
l.Ja=function(a,b){var c=this,d=jg;switch(a){case "readTape":d=lg;case "loadTape":d||(d=mg);b.onclick=function(){var e=c.ca[ng];e&&(e=c.i[e.selectedIndex])&&og(c,e,d)};break;case "mountTape":this.M?(b.addEventListener("change",function(){var e=b.children[0];e.children[1].disabled=!e.children[0].files.length}),b.onsubmit=function(e){(e=e.currentTarget[1].files[0])&&og(c,{name:Ja(e.name,!0),path:e.name},mg,e);return!1}):(this.o("Local tape support not available\n"),b.parentNode.removeChild(b))}K.prototype.Ja.call(this,a,
b)};l.de=function(){var a=this.ca[pg],b=this.ca[ng],c=b.options[b.selectedIndex];if(a&&c){b={};if(c=c.getAttribute("data-value"))try{b=eval("("+c+")")}catch(d){this.o("PC11 option error: %s",d.message)}c=b.desc;void 0===c&&(c="");b=b.href;void 0!==b&&(c='<a href="'+b+'" target="_blank">'+c+"</a>");a.innerHTML=c}};l.xa=function(a){a=a.shift();return this.S==a?!0:!1};l.ya=function(a){a.push(this.S)};l.qa=function(){this.v||(this.v=N(this,"CPU"),this.I=Re(this.v,56,536870912))};
l.ra=function(){this.g&=-2241;this.m=0};
function og(a,b,c,d){var e=b.name,f=b.path;a.o(536870912,'load("%s","%s")\n',e,f);if(!f)return qg(a),!0;if(f==rg)return Sa(a,'Use "Choose File" and "Mount" to select and load a local tape.'),!0;if(f==sg){f=window.prompt("Enter the URL of a remote tape image.","")||"";if(!f)return!1;e=Ja(f);a.o('Attempting to load %s as "%s"',f,e)}a.l=c;if(d){var g=new FileReader;g.onload=function(){var h=g.result;h&&(b.values=new Uint8Array(h,0,h.byteLength),a.Ib(b));tg(a)};g.readAsArrayBuffer(d);return!1}if(!b.values&&
!Za(a,b.path,a.Ib.bind(a)))return!1;a.Ib(b);return!0}function tg(a){if(a.u){var b=a.ca[ng];if(b&&b.options){var c;for(c=0;c<b.options.length;c++)if(b.options[c].value==a.u.path){b.selectedIndex!=c&&(b.selectedIndex=c);break}c==b.options.length&&(b.selectedIndex=0)}}}function ug(a,b){b|=0;if(b!==a.O){var c=a.ca[vg];c&&(c=(c=c.getElementsByClassName(wg))&&c[0])&&c.style&&(c.style.width=b+"%");a.O=b}}
l.ee=function(a){a=this.i=a||[];var b=this.de.bind(this),c=ng,d=this.ca[c];if(d){for(var e=0;e<a.length;e++)Rb(this,c,a[e].name,a[e].path);b&&(d.onchange=b)}Rb(this,ng,"None",xg,!0);this.M&&Rb(this,ng,"Local Tape",rg);Rb(this,ng,"Remote Tape",sg);Ab(this,!0);if(this.h&&"string"==typeof this.h){for(a=0;a<this.i.length;a++)if(b=this.i[a],"object"==typeof b&&b.name==this.h){this.h=b;break}a==this.i.length&&(Sa(this,"Unable to find %s media: %s",this.S),this.h="")}this.h?og(this,this.h,mg)||Ab(this,!1):
tg(this)};
l.Ib=function(a){var b=a.name,c=a.values,d=a.addrLoad,e=a.addrExec;this.u=a;Ab(this,!0);if(this.l==lg){var f=e,g=a=!1;e=!1;if(null==d)for(var h=0;h<c.length-1;){var k=c[h]&255|(c[h+1]&255)<<8;if(k)if(k&255){var n=h;if(1!=k){this.o(536870912,"invalid signature (%#06x) at offset %#06x\n",k,n);break}if(h+6>=c.length){this.o(536870912,"invalid block at offset %#06x\n",n);break}h+=2;var m=c[h++]&255|(c[h++]&255)<<8,r=c[h++]&255|(c[h++]&255)<<8;k+=(m&255)+(m>>8)+(r&255)+(r>>8);for(var p=h,q=m-=6;0<m&&h<
c.length;)k+=c[h++]&255,m--;if(0!=m||h>=c.length){this.o(536870912,"insufficient data for block at offset %#06x\n",n);break}k+=c[h++]&255;if(k&255){this.o(536870912,"invalid checksum (%#04x) for block at offset %#06x\n",k,n);break}if(q)for(this.o(536870912,"loading %#06x bytes at %#06x-%#06x\n",q,r,r+q);q--;)this.J.eb(r++,c[p++]&255);else r&1?g=!0:null==f&&(f=r),null!=f&&this.o(536870912,"starting address: %#06x\n",f);e=!0}else h++;else h+=2}if(!e&&(null==d&&(d=null),null!=d)){for(e=0;e<c.length;e++)this.J.eb(d+
e,c[e]);e=!0}if(e){if(null==f||g)Bc(this.time),a=!1;if(null!=f&&(c=this.v,d=f,c.T=d,c.h[hf]=d&65535,oe(c,0),ge(c),a)){c.h[0]=0;for(a=1;5>=a;a++)c.h[a]=0;c.h[6]=1024}}e?this.o('Read tape "%s"',b):Sa(this,'No valid memory address for tape "%s"',b)}else this.j=0,this.s=c,this.g&=-32769,this.o('Loaded tape "%s" (%d bytes)',b,c.length),ug(this,0)};function qg(a){a.u=null;a.l&&a.o(a.l==mg?"tape detached":"tape unloaded");a.l=jg;tg(a)}
l.Jd=function(){1!=(this.g&32769)||this.g&128||(this.j<this.s.length?(this.m=this.s[this.j]&255,this.o(536870912,"%s.advanceReader(%d): %#02x\n",this.S,this.j,this.m),this.j++,ug(this,this.j/this.s.length*100)):this.g|=32768,this.g|=128,this.g&=-2049,this.g&64&&Te(this.v,this.I))};l.me=function(){return this.g&65534};l.Je=function(a){a&1&&(this.g&32768?(a&=-2,this.g&64&&Te(this.v,this.I)):(this.g&=-129,this.g|=2048,this.m=0,Qb(this.time,this.T,1E3/Math.round(this.R/10))));this.g=this.g&-66|a&65};
l.le=function(){this.g&=-129;this.g|=2048;return this.m};l.Ie=function(){};l.ke=function(){return this.K};l.He=function(a){this.K=this.K&-65|a&64};l.je=function(){return this.N};l.Ge=function(a){this.N=a&255};
var xg="",rg="?",sg="??",jg=0,mg=1,lg=2,ng="listTapes",pg="descTape",vg="readProgress",wg="progressBar",yg={},kg=(yg[65384]=[null,null,Z.prototype.me,Z.prototype.Je,"PRS"],yg[65386]=[null,null,Z.prototype.le,Z.prototype.Ie,"PRB"],yg[65388]=[null,null,Z.prototype.ke,Z.prototype.He,"PPS"],yg[65390]=[null,null,Z.prototype.je,Z.prototype.Ge,"PPB"],yg);x.PC11=Z;
function zg(a,b,c){K.call(this,a,a);var d=this;this.i=!1;this.s=c;this.h="";this.m=this.l=!1;Ab(this,!1);this.pa=0;b=b.trim();"{"==b[0]?Ag(this,b):(this.h=b,$a(this.h,function(e,f,g,h){4==g&&(!h&&f?(Ag(d,f),Bg(d)):d.o("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.m=!0;Bg(d)});window.addEventListener(db("iOS")?"pagehide":db("Opera")?"unload":"beforeunload",function(){Cg(d)});window.addEventListener("pageshow",function(){d.i||d.qa(!0)})}w(zg,K);
zg.prototype.Ja=function(a,b){var c=this;switch(a){case Dg:b.onclick=function(){c.qa()};break;case Eg:b.onclick=function(){c.ra()}}K.prototype.Ja.call(this,a,b)};
function Bg(a){var b=!0;if(a.l&&a.m){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],x[d]?"Machine"==d?(a.o("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2024 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.o("Configuration: %s\n",a.h)):new x[d](a.Y,c,e):a.o('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.o('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),Cb(a,c)}}if(a.j){var f=eb(a);wb(a,function(g){return g.Hb&&!g.Hb(f)?(g.o('unable to restore state for device "%s"\n',
g.S),!1):!0})}Ab(a,!0);Bb(a,a.qa.bind(a,b))||a.o("machine %s not ready to power, waiting for device(s)\n",a.Y)}}
function Ag(a,b){try{a.g=JSON.parse(b);var c=a.g[a.Y];if(!c){c=a.g[Ja(a.h,!0)];if(!c)throw Error("configuration missing machine ID");a.g[a.Y]=c}ub(a,c,["autoSave","autoStart"]);a.j=!1!==a.H.autoSave;a.u=!1!==a.H.autoStart;if(a.s){var d=eval("("+a.s+")"),e;for(e in d)a.H[e]=d[e]}a.l=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.o("machine '%s' initialization error: %s\n",a.Y,c)}}
zg.prototype.qa=function(a){a=void 0===a?!this.i:a;if(zb(this)){var b=this;a&&this.o("power on\n");wb(this,function(c){c.qa&&c!=b&&("CPU"!=c.H["class"]||b.u&&zb(b)?c.qa(a):c.time.update(!0));return!0});(this.i=a)||this.o("power off\n")}};zg.prototype.ra=function(){if(zb(this)){var a=this;wb(this,function(b){b.ra&&b!=a&&b.ra();return!0});this.o("reset\n")}};function Cg(a){if(a.j){var b=[];wb(a,function(c){c.cb&&c.cb(b);return!0});lb(a,b)}a.qa(!1)}var Dg="power",Eg="reset";
window.PDP11v3=function(a,b,c){var d=new zg(a,b,c);window.command=function(e){return fb(d,e)};return d};x.Machine=zg;})()

//# sourceMappingURL=pdp11v3.js.map
