(function(){/*
 https://www.pcjs.org/machines/modules/v3/defines.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/message.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdlib.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/webio.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/device.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/input.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/led.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/time.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/bus.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/memory.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/rom.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/cpu.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/ti/modules/v3/cpu1500.js (C) 2012-2023 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/machine.js (C) 2012-2023 Jeff Parsons
*/
var q;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function r(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)a=b.call(a);else if("number"==typeof a.length)a={next:aa(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function t(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function z(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.te=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
t("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
t("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});t("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
t("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});t("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
t("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}t("Array.prototype.keys",function(a){return a?a:function(){return na(this,function(b){return b})}});
t("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function A(a){return a?a:Array.prototype.fill}t("Int8Array.prototype.fill",A);t("Uint8Array.prototype.fill",A);t("Uint8ClampedArray.prototype.fill",A);t("Int16Array.prototype.fill",A);t("Uint16Array.prototype.fill",A);t("Int32Array.prototype.fill",A);
t("Uint32Array.prototype.fill",A);t("Float32Array.prototype.fill",A);t("Float64Array.prototype.fill",A);t("Number.parseInt",function(a){return a||parseInt});t("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});function oa(){this.V=""}var pa=new ArrayBuffer(2);(new DataView(pa)).setUint16(0,256,!0);new Uint16Array(pa);
var B={fe:"undefined"!=typeof window?{}:null,node:"undefined"!=typeof window?{}:global,process:"undefined"!=typeof process?process:{},window:"undefined"!=typeof window?window:global,document:"undefined"!=typeof document?document:{},Pa:{machines:{},components:[],commands:{}}};B.window.PCjs?B.Pa=B.window.PCjs:B.window.PCjs=B.Pa;var qa=B.process,C=B.Pa.machines,ra=B.Pa.components,D={};D.Defines=oa;
var sa={all:0xffffffffffff,addr:1,bus:2,fault:4,memory:8,ports:16,chips:32,kbd:64,serial:128,misc:256,cpu:512,mmu:2048,"int":1024,trap:4096,video:8192,monitor:16384,screen:32768,disk:131072,file:65536,time:262144,timer:524288,event:1048576,input:2097152,key:4194304,mouse:8388608,touch:16777216,info:274877906944,warn:549755813888,error:1099511627776,halt:70368744177664,buffer:0x800000000000};function ta(){this.g={};for(var a=0;23>a;a++)this.g["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
function ua(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,r(a)));return a}
ta.prototype.L=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(void 0===this.g[g])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];"%"!=g&&e++}else h=b[b.length-1];var l=d[f+1],k=0<=l.indexOf("#"),m=0<=l.indexOf("0"),n=d[f+2];"*"==n?(n=h,h=e<b.length?b[e++]:b[b.length-1]):n=+n||0;var p=d[f+3];p=p?+p.substr(1):-1;var u=d[f+4],x=null,
v=0,y="",w=0<="ACDFGHMNSTWY".indexOf(g)&&"object"!=typeof h?ua(h):h;switch(g){case "C":c+=isNaN(w.getTime())?void 0:this.L("%#W, %#F %#D, %#Y".replaceAll("#",k?"#":""),w);continue;case "D":h=k?w.getUTCDate():w.getDate();g="d";break;case "A":case "G":case "H":h=k?w.getUTCHours():w.getHours();"A"==g?(h=12>h?"am":"pm",g="s"):("G"==g&&(h=h?12<h?h-12:h:12),g="d");break;case "F":case "M":h=k?w.getUTCMonth():w.getMonth();"F"==g?(h=va[h],g="s"):(h++,g="d");break;case "N":h=k?w.getUTCMinutes():w.getMinutes();
g="d";break;case "S":h=k?w.getUTCSeconds():w.getSeconds();g="d";break;case "T":c+=isNaN(w.getTime())?void 0:this.L("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",k?"#":""),w);continue;case "W":h=wa[k?w.getUTCDay():w.getDay()];g="s";break;case "Y":h=k?w.getUTCFullYear():w.getFullYear(),0<p&&(h%=Math.pow(10,p)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=p&&(m=!0,n<p&&(n=p),p=-1);case "f":h=+h;g=h+"";0<=p&&(g=h.toFixed(p));g.length<n&&(m?(0>h&&(n--,g=g.substr(1)),
g=("0".repeat(n)+g).slice(-n),0>h&&(g="-"+g)):g=(" ".repeat(n)+g).slice(-n));c+=g;break;case "j":c+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=p&&(h=h.substr(0,p));h.length<n;)h=0<=l.indexOf("-")?h+" ":" "+h;c+=h;break;case "B":v=2,k&&(y="0b");case "o":v||(v=8),!y&&k&&(y="0o");case "X":x=xa;case "x":g="";v||(v=16);!y&&k&&(y="0x");x||(x=ya);h=Math.trunc(h);0<=p&&(m=!0,n<p&&(n=p));
m&&!n&&("b"==u?n=2:"h"==u||"w"==u?n=4:"l"==u?n=8:(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9),n+=y.length);n-=y.length;do k=16,Number.isNaN(h)||(k=h&v-1,h=Math.trunc(h/v)),m||!g||k||h?g=x[k]+g:(y&&(g=y+g,y=""),0<n&&(g=" "+g));while(0<--n||h);c+=y+g;break;case "%":c+="%";break;default:c=this.g[g]?c+this.g[g](g,l,n,p,h):c+("(unimplemented sprintf type: %"+g+")")}}}return c+=d[f]};
var wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" "),ya="0123456789abcdef?",xa="0123456789ABCDEF?";function za(){oa.apply(this,arguments)}z(za,oa);function Aa(a,b){var c=a/E|0,d=b/E|0;return(a&b)==(b|0)&&(c&d)==d}var E=Math.pow(2,32);D.StdLib=za;function F(){za.call(this);this.qb=new ta;this.X=this.qb.L.bind(this.qb)}z(F,za);F.prototype.flush=function(){var a=Ba;Ba="";this.ua(a)};
function Ca(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}F.prototype.ua=function(a,b){var c=a.length,d=a.lastIndexOf("\n");b?0<=d&&(b=Date.now(),Da||(Da=b),a=((b-Da)/1E3).toFixed(3)+": "+a,c=a.length):"node"==this.V?(qa.se.write(a),a=""):(0<=d&&(console.log(Ba+a.slice(0,d)),Ba="",a=a.slice(d+1)),Da=null);Ba+=a;return c};
F.prototype.s=function(a){return this.ua(this.X.apply(this,[a].concat(r(la.apply(1,arguments)))))};var Ba="",Da=null;D.StdIO=F;function G(a){F.call(this);this.S={};this.ga=0;this.L=this;a&&(this.L.ga=0,this.L.ta=[],this.L.ka=0,this.L.Ha={},this.L.de=!1)}var Ea;z(G,F);q=G.prototype;
q.za=function(a,b){var c=this,d=this;this.S[a]=b;switch(a){case Fa.Vb:b.onclick=function(){var e=c.Ba(Fa.Xa,!0);e&&(e.value="")};break;case Fa.Xa:Ga(b),b.addEventListener("keydown",function(e){Ha(d,e,!0)}),b.addEventListener("keypress",function(e){Ha(d,e)})}};
function Ia(a,b){b=void 0===b?{}:b;if("undefined"!=typeof document){a.J.S||(a.J.S=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.V);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.S[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.S[d].push(e)}while(1);continue}(f=document.getElementById(e))&&a.za(d,f)}}}
function Ga(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}q.error=function(a,b){b=this.X.apply(this,[a].concat(r(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.X.apply(this,[c].concat(r(b))))this.s("%s\n",b),a||alert(b)};q.Ba=function(a){return this.S[a]};
function Ja(a){var b=window;if(b){do{for(var c=0;c<Ka.length;c++){var d=Ka[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function La(a,b){return a.J.bindings&&a.J.bindings[b]}function Ma(a){if(a=a.S[Na])var b=a.textContent;return b}function Oa(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function H(a,b,c,d){a=a.J[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Pa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Qa(a){if(void 0===I.Ua){var b=!1;if(window)try{window.localStorage.setItem(I.ya,I.ya),b=window.localStorage.getItem(I.ya)==I.ya,window.localStorage.removeItem(I.ya)}catch(c){a.s("%s\n",c.message),b=!1}I.Ua=b}return!!I.Ua}function J(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.ga;return-1==(b|1)||Aa(a.L.ga,b)?!0:!1}
function Ra(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Sa(a){var b=null;if(Qa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.M))&&(b=JSON.parse(c))}catch(d){a.s("%s\n",d.message)}}return b}
function Ha(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.L,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==K.eb&&f.selectionStart<=h+1&&(a=!0);d==K.zc?(a=!0,0<e.ka&&(g=e.ta[--e.ka])):d==K.Yb&&(a=!0,e.ka<e.ta.length&&(g=e.ta[++e.ka]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ka&&c+1==g.length&&
(f.value+=e.ta[--e.ka],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ta(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&a.s("%s\n",b.replace(/\n$/,"")))}}
function Ua(a,b){if(void 0!=b){var c=a.L;try{if(b=b.trim())c.ka<c.ta.length&&b==c.ta[c.ka]?c.ka++:(c.ta.push(b),c.ka=c.ta.length);var d=b.split(" "),e=d[0],f=a.L.Ha[Va.hb];switch(e[0]){case "m":if("?"==e[1]){var g="";Wa.forEach(function(n){g+=n+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var l="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=l&&d.pop();1>=d.length&&(void 0!=l&&(h=l,l=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(sa));for(f=
1;f<d.length;f++){e=d[f];var k=sa[e];if(!k){g+="unrecognized message: "+e+"\n";break}void 0!=l&&Xa(a,k,l);if(void 0==h||h==J(a,k))g+=a.X("%8s: %b\n",e,J(a,k))}J(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ya.forEach(function(n){g+=n+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var m=f[a](d);if(void 0!=m){g=g?g+m:m;break}}}}catch(n){g="error: "+n.message+"\n"}}return g}
function Ta(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Ua(a,b[d])}return c}
q.ua=function(a,b){void 0==b&&(b=J(this,0x800000000000));if(!b){var c=a.length,d=this.Ba(Fa.Xa,!0);if(d){if("\n"!=a.slice(-1)||d.value.slice(-a.length)!=a){if(0<=a.indexOf("\b"))for(b=c=0;b<a.length;b++)"\b"==a[b]?(d.value=d.value.slice(0,-1),c--):(d.value+=a[b],c++);else d.value+=a;8192<d.value.length&&(d.value=d.value.substr(d.value.length-4096));d.scrollTop=d.scrollHeight;Ra("iOS")||d.setSelectionRange(d.value.length,d.value.length)}return c}}return F.prototype.ua.call(this,a,b)};
q.s=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return J(this,c)?(Aa(c,1099511627776)&&(a="error: "+a),Aa(c,549755813888)&&(a="warning: "+a),F.prototype.s.call.apply(F.prototype.s,[this,a].concat(r(b)))):0};function Za(a,b){if(Qa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.M,b)}catch(c){a.s("%s\n",c.message)}}}function L(a,b,c){(a=a.S[b])&&a.textContent!=c&&(a.textContent=c)}
function Xa(a,b,c){var d=!1;c?(c=a.L.ga,a.L.ga=(c|b)+(c/E|0|b/E|0)*E):(d=Aa(a.L.ga,0x800000000000)&&Aa(b,0x800000000000),c=a.L.ga,a.L.ga=(c&~b)+((c/E|0)&~(b/E|0))*E);d&&a.flush()}
var Fa={Vb:"clear",Xa:"print"},Ya=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Wa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],Va={hb:"command"},$a={ib:13,Ta:65,cb:66,fb:67,jb:68,E:69,kb:70,lb:71,mb:72,nb:73,ob:74,rb:75,sb:76,vb:77,wb:78,xb:79,yb:80,Q:81,Ab:82,Cb:83,Db:84,Eb:85,Fb:86,Gb:87,Hb:88,
Ib:89,Za:90,a:97,b:98,c:99,d:100,e:101,f:102,ke:103,le:104,me:105,ne:106,k:107,oe:108,pe:109,n:110,qe:111,p:112,q:113,r:114,re:115,t:116,ue:117,ve:118,w:119,x:120,y:121,z:122},K={eb:8,vc:9,jc:10,ib:13,rc:16,Wb:17,Ub:18,Td:19,Va:20,Uc:27,tc:32,Wd:33,Vd:34,Tc:35,pd:36,tb:37,zc:38,Ya:39,md:39,Yb:40,jd:44,Xd:44,qd:45,Sc:46,ld:46,od:47,ZERO:48,ONE:49,xc:50,wc:51,fc:52,ec:53,sc:54,qc:55,Zb:56,kc:57,dc:59,cc:61,Ta:65,cb:66,fb:67,jb:68,E:69,kb:70,lb:71,mb:72,nb:73,ob:74,rb:75,sb:76,vb:77,wb:78,xb:79,yb:80,
Q:81,Ab:82,Cb:83,Db:84,Eb:85,Fb:86,Gb:87,Hb:88,Ib:89,Za:90,gb:91,kd:91,hd:92,$d:93,nd:93,ud:96,Ld:96,gd:96,vd:97,Jd:97,wd:98,Id:98,xd:99,Od:99,yd:100,Md:100,zd:101,Fd:101,Ad:102,Qd:102,Bd:103,Kd:103,Cd:104,Sd:104,Dd:105,Pd:105,Nd:106,Ed:107,Rd:109,Gd:110,Hd:111,Vc:112,Zc:113,$c:114,ad:115,bd:116,cd:117,dd:118,ed:119,fd:120,Wc:121,Xc:122,Yc:123,lc:144,oc:145,bc:173,pc:186,$b:187,Rc:188,Xb:189,Ud:190,be:191,Pc:192,rd:219,Qc:220,Zd:221,Yd:222,ac:224,sd:901,ce:1E3},ab={},bb=(ab[K.dc]=K.pc,ab[K.cc]=K.$b,
ab[K.bc]=K.Xb,ab[K.ac]=K.gb,ab),cb={tb:1,Ya:2,td:3},M={},db=(M[K.eb]="\b",M[K.vc]="\t",M[K.jc]="\n",M[K.ib]="\r",M[K.tc]=" ",M[K.ZERO]="0",M[K.ONE]="1",M[K.xc]="2",M[K.wc]="3",M[K.fc]="4",M[K.ec]="5",M[K.sc]="6",M[K.qc]="7",M[K.Zb]="8",M[K.kc]="9",M[K.Ta]="A",M[K.cb]="B",M[K.fb]="C",M[K.jb]="D",M[K.E]="E",M[K.kb]="F",M[K.lb]="G",M[K.mb]="H",M[K.nb]="I",M[K.ob]="J",M[K.rb]="K",M[K.sb]="L",M[K.vb]="M",M[K.wb]="N",M[K.xb]="O",M[K.yb]="P",M[K.Q]="Q",M[K.Ab]="R",M[K.Cb]="S",M[K.Db]="T",M[K.Eb]="U",M[K.Fb]=
"V",M[K.Gb]="W",M[K.Hb]="X",M[K.Ib]="Y",M[K.Za]="Z",M[K.tb]="Left",M[K.Ya]="Right",M),Ka=["","moz","ms","webkit"],eb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",
darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",
fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",
navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},I={Ua:void 0,ya:"PCjs.localStorage"};D.WebIO=G;
function N(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;G.call(this,a==b);this.M=a;this.V=b;C[this.M]||(C[this.M]={});C[this.M][this.V]&&this.s("warning: machine configuration contains multiple '%s' devices\n",this.V);C[this.M][this.V]=this;this.id=this.M==this.V?this.M:this.M+"."+this.V;ra.push(this);this.L=O(this,this.M);this.ready=!0;fb(this,c,d);this.yc={};this.ub=[]}z(N,G);
function fb(a,b,c){c=b.overrides||c;if(c.length){var d,e=Ea;if(!e){e={};if(window){d||(d=window.location.search.slice(1));for(var f,g=/\+/g,h=/([^&=]+)=?([^&]*)/g;f=h.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ea=e}d=e;for(var l in d)if(0<=c.indexOf(l)){e=d[l];f=void 0;var k;g=void 0;h=e;var m=10;if(h){m||(m=10);var n=0<h.indexOf(",");n&&(h=h.replace(/,/g,""));var p=k=h.charAt(0);"#"==k?(m=8,k=""):"$"==k&&(m=16,k="");p!=k?h=h.substr(1):
(p=k=h.substr(0,2),"0b"==k&&n||"^B"==k?(m=2,k=""):"0o"==k||"^O"==k?(m=8,k=""):"^D"==k?(m=10,k=""):"0x"==k&&(m=16,k=""),p!=k&&(h=h.substr(2)));p=k=h.slice(-1);"Y"==k||"y"==k?(m=2,k=""):"."==k?(m=10,k=""):"H"==k||"h"==k?(m=16,k=""):"K"==k?k="000":"M"==k?k="000000":"G"==k&&(k="000000000");p!=k&&(h=h.slice(0,-1)+k);p=0;10>=m&&(k=h.match(/(-?[0-9]+)B([0-9]*)$/))&&(h=k[1],p=35-((k[2]||35)&255));(m&&10!=m?16==m?null===h.match(/^-?[0-9a-f]+$/i):8==m?null===h.match(/^-?[0-7]+$/):2!=m||null===h.match(/^-?[01]+$/):
null===h.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(h,m))||(p&&(0>f&&(f+=Math.pow(2,36)),f=0<p?f*Math.pow(2,p):Math.trunc(f/Math.pow(2,-p))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[l]=f;a.s("overriding %s property '%s' with %s\n",a.V,l,e)}}a.J=b;Ia(a,b.bindings);b=void 0===b?{}:b;a.version=3;if(a.version){c="";var u;a.M!=a.V&&(u=O(a,a.M).version)&&u!=a.version&&(c="Machine");c||(u=b.version)&&u>a.version&&(c="Config");c&&(u=a.X("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.ge,a.version,c,u),a.error("%s\n\nClearing your browser's cache may resolve the issue.",u))}}function gb(a,b){var c;try{var d=C[a.M];if(d)for(c in d){var e=d[c];if(e.V!=e.M&&!b(e))return!1}return!0}catch(f){a.s("error while enumerating device '%s': %s\n",c,f.message)}return!1}N.prototype.Ba=function(a,b){b=void 0===b?!1:b;if(a){var c=G.prototype.Ba.call(this,a,b);if(void 0===c&&b){b=C[this.M];for(var d in b)if(c=b[d].S[a])break;c||(c=null);this.S[a]=c}}return c};
function O(a,b,c){var d=b,e=a.M,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=C[e])&&f[b]||null;if(!b){for(f=0;f<ra.length;f++)if(ra[f].id===d){b=ra[f];break}if(!b&&(void 0===c||c))throw Error(a.X('no "%s" device',d));}return b}function P(a,b,c){var d=null,e=C[a.M];if(e)for(var f in e)if(e[f].J["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.X("no %s device",b));return d}function Q(a){return a==a.L&&a.ready?gb(a,function(b){return Q(b)}):a.ready}
function hb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(Q(a)){for(;b=a.ub.pop();)b();a!=a.L&&hb(a.L)}}function ib(a,b){if(Q(a))return b(),!0;a.ub.push(b);return!1}
N.prototype.s=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&J(this,a)&&(void 0===this.fa&&(this.fa=P(this,"Debugger",!1)),this.L.ga&1&&(void 0===this.da&&(this.da=P(this,"CPU")),this.da))?(a=b.shift(),G.prototype.s.call(this,"%#06x: %s.%s\n",this.da.Qa,this.V,this.X.apply(this,[a].concat(r(b))).trim())):G.prototype.s.call.apply(G.prototype.s,[this,a].concat(r(b)))};function jb(a,b){(a=C[a.M])&&delete a[b]}N.prototype.Pb=function(a,b){(a=this.yc[a])&&a.set&&a.set(b)};D.Device=N;
function kb(a,b,c){N.call(this,a,b,c);this.ga=2097152;this.K=this.O=null;this.time=P(this,"Time");this.L=P(this,"Machine");this.ba=H(this,"drag",!1);this.Y=H(this,"scroll",!1);this.aa=H(this,"hexagonal",!1);this.u=H(this,"releaseDelay",0);this.v=!1;a=this.J.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.j[f]={keys:g,grid:e,
state:0}}}this.R=[];this.T=[];this.m=this.U=null;(a=this.S[lb])&&mb(this,a,this.Ba(c.focusBinding,!0),this.J.location);this.qa()}z(kb,N);function nb(a,b){a.O=b}function ob(a,b,c){for(var d=0;d<a.R.length;d++){var e=a.R[d];e.id===b&&e.Nb(b,c)}}
function mb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.Nc=d[0]||0;e.Oc=d[1]||0;e.Aa=d[2]||b.clientWidth;e.La=d[3]||b.clientHeight;e.Ma=d[4]||1;e.Ra=d[5]||1;e.Ec=d[6]||b.naturalWidth||e.Aa;e.Gc=d[7]||b.naturalHeight||e.La;e.Sb=d[8]||0;e.Tb=d[9]||0;e.Dc=d[10]||0;e.Fc=d[11]||0;a.h?(e.Oa=a.h.length,e.Ca=a.h[0].length):(e.Ca=e.Ma,e.Oa=e.Ra,e.Ma=e.Ra=0);e.Jb=e.Aa/(e.Ca+e.Ca*e.Ma)|0;e.Kb=e.La/(e.Oa+e.Oa*e.Ra)|0;e.Cc=e.Jb*e.Ma|0;e.Lb=e.Kb*e.Ra|0;e.Ga=e.Sa=-1;pb(a,b,e);qb(a,b,e);a.time&&
a.u&&(a.$=rb(a.time,"timerInputRelease",function(){0>e.Ga&&0>e.Sa&&sb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.u&&(a.ca=rb(a.time,"timerKeyRelease",function(){tb(a)})),a.H=0,a.N="",a.I=[],d=b,c&&(d=c,a.m||"BUTTON"!=c.nodeName||(d=document,a.m=c,ub(a,b),a.U=b)),ub(a,d),a.m||(a.m=d)}function vb(a){a.u?wb(a.time,a.ca,a.u):tb(a)}
function ub(a,b){function c(e,f,g){var h=document.activeElement;a.s(5242880,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.m&&e!=a.m&&e!=a.U?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=xb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=xb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=xb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function pb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.v){var e=a.m;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,yb,d,c)}});b.addEventListener("mousemove",function(d){a.v||R(a,b,zb,d,c)});b.addEventListener("mouseup",function(d){a.v||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.v||(0>c.Ga?R(a,b,zb,d,c):R(a,b,S,d,c))})}
function qb(a,b,c){b.addEventListener("touchstart",function(d){a.Y&&(a.v=!0);R(a,b,yb,d,c)});b.addEventListener("touchmove",function(d){R(a,b,zb,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function xb(a,b,c,d){if(void 0!=c){var e=bb[b]||b;var f=db[b];var g=Ab[e];d=d&&d.location==cb.Ya;g&Bb&&d&&(g>>=1);g&&(g&Cb&&(c=!(a.g&g)),a.g=c?a.g|g:a.g&~g,ob(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=$a.Ta&&b<=$a.Za?a.g&(Db|Eb)||(a.g|=Eb,ob(a,K.Va,!0)):b>=$a.a&&b<=$a.z&&a.g&Eb&&(a.g&=~Eb,ob(a,K.Va,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(g=a.h[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.H?16>a.I.length&&a.I.push(b):(a.H=1,a.N=f,sb(a,d,e),ob(a,
f,!0),vb(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(g=b[e],0<=a.j[g].keys.indexOf(f))return ob(a,g,c),a.j[g].state=c?1:0,!0}return!1}function tb(a){1==a.H?(a.H++,ob(a,a.N,!1),a.N="",sb(a,-1,-1),vb(a)):(a.H=0,a.I.length&&xb(a,a.I.shift()))}kb.prototype.qa=function(){this.g=0;this.W=this.Z=-1};
function R(a,b,c,d,e){var f=-1,g=-1,h=!1,l=-1,k=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(l=d.targetTouches[0].clientX,k=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(l=d.clientX,k=d.clientY);var m=d.target.getBoundingClientRect();l-=m.left;k-=m.top;l=e.Ec/b.offsetWidth*l|0;k=e.Gc/b.offsetHeight*k|0;var n=l-e.Nc;var p=k-e.Oc;var u=m=!1;var x=l>=e.Sb&&l<e.Sb+e.Dc&&k>=e.Tb&&k<e.Tb+e.Fc;if(0<=n&&n<e.Aa&&0<=p+e.Lb||x)if(h||a.Y||d.preventDefault(),0<=n&&n<e.Aa&&0<=
p&&p<e.La){u=!0;d=e.Aa/e.Ca|0;var v=e.La/e.Oa|0,y=n/d|0,w=p/v|0;!a.aa||w&1||(n-=d>>1,y=n/d|0,y==e.Ca-1&&(n=-1));v=w*v+(e.Lb>>1);n-=y*d+(e.Cc>>1);p-=v;0<=n&&n<e.Jb&&0<=p&&p<e.Kb&&(f=y,g=w,m=!0)}}n=n||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==yb||c==S)for(y=0;y<a.T.length;y++)w=a.T[y],c==S?w.Nb(w.id,!1):(v=p/(b/w.ie|0)|0,(n/(d/w.he|0)|0)==w.we&&v==w.xe&&w.Nb(w.id,!0));if(!h)if(c==yb)e.Ga=l,e.Sa=k,u?(sb(a,f,g),m&&a.u&&wb(a.time,a.$,a.u,!0)):x&&a.L.ia();else if(c==zb)0<=e.Ga&&0<=e.Sa&&a.ba?sb(a,
f,g):a.O&&a.O(f,g);else if(c==S){if(c=a.u)c=a.time,f=a.$,c=c.g&&0<f&&f<=c.h.length?0<=c.h[f-1].ha:!1;c||sb(a,-1,-1);e.Ga=e.Sa=-1}else a.s("unrecognized action: %d\n",c)}function sb(a,b,c){if(b!=a.W||c!=a.Z)a.W=b,a.Z=c,a.K&&a.K(b,c)}var yb=1,zb=2,S=3,lb="surface",Db=3,Bb=170,Eb=512,Cb=3584,T={},Ab=(T[K.rc]=2,T[K.Wb]=8,T[K.Ub]=32,T[K.gb]=128,T[K.Va]=Eb,T[K.lc]=1024,T[K.oc]=2048,T);D.Input=kb;
function Fb(a,b,c){N.call(this,a,b,c,["color","backgroundColor"]);a=this.S[Gb];if(!a)throw Error("LED "+this.J.S[Gb]+" binding for '"+Gb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.va=La(this,Gb)+".canvas";b.setAttribute("id",this.va);this.Wa=a;this.type=Oa(H(this,"type",Hb,Ib),Jb,Kb);this.m=Lb[this.type][0];this.I=Lb[this.type][1];this.width=H(this,"width",
this.m);this.height=H(this,"height",this.I);this.u=H(this,"cols",1);this.R=this.u+H(this,"colsExtra",0);this.ba=H(this,"rows",1);this.W=this.ba+H(this,"rowsExtra",0);this.ea=this.width*this.u;this.Z=this.height*this.ba;this.H=Mb("black",0);this.j=Nb(this.J.color)||this.H;this.na=Mb(this.j,1,.25);this.ma=Mb(this.j,1,2);this.v=Nb(this.J.backgroundColor);this.oa=H(this,"fixed",!1);this.oa||(b.style.width="100%",b.style.height="auto");this.la=H(this,"hexagonal",!1);this.sa=H(this,"highlight",!0);this.Y=
H(this,"persistent",this.type<Kb);b.setAttribute("width",this.ea.toString());b.setAttribute("height",this.Z.toString());b.style.backgroundColor=this.H;a.appendChild(b);this.ja=b.getContext("2d");if(this.K=document.createElement("canvas"))this.K.width=this.ca=this.m*this.u,this.K.height=this.N=this.I*this.ba,this.h=this.K.getContext("2d");this.wa=(this.W+1)*this.R*4;this.g=Array(this.wa);this.Ia=this.u<this.R?4*(this.R-this.u):0;this.T=this.U=!1;this.O=this.aa=0;this.$=-1;var d=this;this.time=P(this,
"Time");Ob(this.time,function(e,f){Pb(d,!1,e,f)});Qb(d)}z(Fb,N);function Qb(a){for(var b=a.g,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Kb?Rb:" ";e[f+1]=d.j==d.H?null:d.j;e[f+2]=0;e[f+3]=Sb}a.T=a.U=!0;Pb(a,!0)}function Tb(a){a.v?(a.h.fillStyle=a.v,a.h.fillRect(0,0,a.ca,a.N)):a.h.clearRect(0,0,a.ca,a.N)}
function Pb(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.T||b){if(a.type<Kb){d=0;if(!a.Y||b)Tb(a);else if(a.O){d=a.u-a.O;var e=a.m*d;a.h.drawImage(a.K,a.m*a.O,0,e,a.N,0,0,e,a.N)}for(var f=e=0;f<a.W;f++){for(var g=0;g<a.u;g++){var h=a.g[e],l=a.g[e+1]||a.H,k=a.sa&&e==a.$;if(a.g[e+3]&Sb||k||b){if(g>=d)a:{var m=a,n=h;h=l;var p=g;l=f;var u=k;p=void 0===p?0:p;l=void 0===l?0:l;u=void 0===u?!1:u;var x=0;if(m.la&&!(l&1)&&(x=m.m>>1,p==m.u-1))break a;if(h&&h!=m.j){u=u?Mb(h,1,2):h;var v=
Mb(h,1,.25)}else u=u?m.ma:m.j,v=m.na;h=!1;n=n?u:v;u==m.H&&(n=m.v,h=!0);u=p*m.m+x;v=l*m.I;m.Y&&(p=p*m.m+x,l*=m.I,m.v?(m.h.fillStyle=m.v,m.h.fillRect(p,l,m.m,m.I)):m.h.clearRect(p,l,m.m,m.I));m.h.fillStyle=n;l=Ub[m.type];3==l.length?(m.h.beginPath(),m.h.arc(u+l[0],v+l[1],l[2],0,2*Math.PI),h?(m.h.globalCompositeOperation="destination-out",m.h.fill(),m.h.globalCompositeOperation="source-over"):m.h.fill()):m.h.fillRect(u+l[0],v+l[1],l[2],l[3])}a.g[e+3]=k?a.g[e+3]|Sb:a.g[e+3]&~Sb}e+=4}e+=a.Ia}a.O=0}else{b=
"";for(d=0;d<a.g.length;d+=4)b+=a.g[d]||" ",a.g[d+3]&Vb&&(b+=".");Tb(a);for(f=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;g=a;k=e;m=f;k=void 0===k?0:k;m=void 0===m?0:m;if(l=Wb[l])for(h=0;h<l.length;h++)if(p=g,x=Xb[l[h]]){n=(void 0===k?0:k)*p.m;u=(void 0===m?0:m)*p.I;p.h.fillStyle=p.j;p.h.beginPath();if(3==x.length)p.h.arc(n+x[0],u+x[1],x[2],0,2*Math.PI);else for(v=0;v<x.length;v+=2)v?p.h.lineTo(n+x[v],u+x[v+1]):p.h.moveTo(n+x[v],u+x[v+1]);p.h.closePath();p.h.fill()}if(++e==a.u&&(e=0,++f==a.W))break}}a.ja.globalCompositeOperation=
a.v&&a.j!=a.H?"source-over":"copy";a.ja.drawImage(a.K,0,0,a.ca,a.N,0,0,a.ea,a.Z);a.T=!1;a.$=-1}else a.Y||a.U||(!c||!a.aa||c-a.aa>=(1E3/d|0))&&Qb(a);a.U=!1;c&&(a.aa=c)}function Nb(a){return(a=a||void 0)&&eb[a]||a}
function Mb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=eb[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Fb.prototype.pa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.j&&c==this.v&&a&&a.length==this.g.length){this.g=a;for(b=0;b<=this.g.length-4;b+=4)this.g[b+1]==this.H&&(this.g[b+1]=null);Pb(this,!0);return!0}return!1};Fb.prototype.ra=function(a){this.g&&(a.push(this.j),a.push(this.v),a.push(this.g))};
function Yb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&Zb;b=4*(c*a.R+b);if(b<=a.g.length-4){if(a.g[b]!==d||(a.g[b+3]&Zb)!==e)a.g[b]=d,a.g[b+3]=a.g[b+3]&~Zb|e|Sb,a.T=f=!0;a.$=b;a.U=!0;a.O=0}return f}
var Jb=0,Hb=1,Kb=3,Ib={small:Jb,round:Hb,square:2,digit:Kb},Gb="container",Rb=0,Zb=129,Vb=1,Sb=128,$b={},Ub=($b[Jb]=[4,4,4],$b[Hb]=[16,16,14],$b[2]=[2,2,28,28],$b),Lb=[[8,8],[32,32],[32,32],[96,128]],Xb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Wb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};D.LED=Fb;
function ac(a,b,c){N.call(this,a,b,c);this.oa=H(this,"cyclesMinimum",1E5);this.Wa=H(this,"cyclesMaximum",1E9);this.sa=Oa(H(this,"cyclesPerSecond",1E6),this.oa,this.Wa);this.ba=60;this.W=0;this.Y=1E3/this.ba;this.uc=H(this,"updatesPerSecond",2)||2;this.nc=1E3/this.uc;this.Ia=0;this.Ac=H(this,"timeLock",!0);this.ma=this.R=0;this.la=this.H=1;this.wa=this.K=this.sa/1E4/100;this.ea=[];this.N=[];this.h=[];this.ja=[];this.va=this.g=this.ca=this.I=!1;this.O=this.m=0;a=Ja("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.Y}this.zb=window[a].bind(window,this.Kc.bind(this),d);this.mc=window[Ja("cancelAnimationFrame")||"clearTimeout"].bind(window);this.aa=this.$=this.u=this.j=this.na=0;bc(this)||cc(this,this.la)}z(ac,N);function Ob(a,b){a.ea.push(b)}q=ac.prototype;
q.za=function(a,b){var c=this;switch(a){case dc:b.onclick=function(){ec(c)&&(c.g?U(c):c.start())};break;case fc:b.onclick=function(){cc(c,c.H<<1);gc(c,hc(c.K))};break;case ic:b.onclick=function(){jc(c)};break;case kc:b.addEventListener("mousedown",function(){c.I=!0}),b.addEventListener("mouseup",function(){bc(c);c.I=!1}),b.addEventListener("mousemove",function(){c.I&&bc(c)}),b.addEventListener("change",function(){c.I=!0;bc(c);c.I=!1})}N.prototype.za.call(this,a,b)};
function rb(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,Bc:c,Na:d,ha:-1});0<=d&&wb(a,e,d);return e}
function lc(a,b,c,d){var e=0,f=a.K,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.s(262144,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.Y&&(1<a.H&&(a.H>>=1,a.s(549755813888,"frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.Y,a.H)),e=d));a.R=f;a.ma=f/a.wa;b=a.ma/a.H;a.na=g/b/a.ba+1E-8;a.s(262144,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.na,g,b,a.ba);return e}
function mc(a,b){a.$=a.u=b;if(!a.N.length)return a.u=0,a.$;for(var c=0;0<a.u;){if(c<a.N.length){var d=a.N[c++];b=d.Lc.call(d,b)||1}else c=b=0;a.u-=b}return a.$-a.u}function nc(a,b){var c=Date.now();b()&&(a.Z+=Date.now()-c)}function oc(a,b){b=void 0===b?a.$-a.u:b;if(!a.g){if(a.j)for(var c=0;c<a.N.length;c++){var d=a.N[c];d.Qb.call(d)}a.j=b}a.j-=b;1>a.j&&(a.ca=!0);a.aa+=b;a.$=a.u=0;a.g||(a.aa=0);return b}
function pc(a,b){b=void 0===b?0:b;if(b){var c=b;a.j+=b}else for(c=a.j,1>c&&(c=a.j+=a.na),0>c&&(a.s(262144,"warning: cycle count dropped below zero: %f\n",c),c=a.j=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.ha)&&c>d.ha&&(c=d.ha)}return c}function hc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function ec(a){return a.va?!0:(a.s("not powered\n"),!1)}
function qc(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.ha||(d.ha-=b,0>=d.ha&&(d.ha=-1,d.Bc(),0<=d.Na&&wb(a,c,d.Na)))}}q.ia=function(a){this.va=a;void 0===this.fa&&(this.fa=P(this,"Debugger",!1))};function jc(a,b){ec(a)&&(a.g?a.s("already running\n"):a.m?U(a):rc(a,b))}
q.Kc=function(a){a=void 0===a?Date.now():a;this.O=0;if(this.g){if(this.W){var b=a-this.W;1>b&&(b=16.67);this.ba=1E3/b}this.W=a;a=Date.now();this.T&&(b=a-this.U-this.Y,b>this.Y&&(this.v+=b,this.s(549755813888,"browser throttling detected, compensating by %5.3fms\n",b)));this.U=a;this.v||(this.v=a);this.Z=0;try{this.ca=!1;do qc(this,oc(this,mc(this,pc(this))));while(this.g&&!this.ca)}catch(c){this.s("%s\n",c.message),U(this)}this.T=Date.now();this.Z&&(this.v+=this.Z,this.U+=this.Z);this.U+=lc(this,
this.aa,this.T-this.v,this.T-this.U);this.T-this.Ia>=this.nc&&this.update();for(a=0;a<this.ea.length;a++)this.ea[a](this.W,this.ba);this.O=this.zb()}};function cc(a,b){if(void 0!==b){if(1>b||!a.I&&0<a.R&&a.R<.9*a.K)b=a.la;a.H=b;b=a.wa*a.H;a.K!=b&&(a.K=b,gc(a,hc(a.K)))}a.v=a.T=0;a.j=a.aa=0;lc(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.Na&&wb(a,b,c.Na,!0)}}function bc(a){var b=a.S[kc];return b?(cc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Wa-a.oa)+a.oa)/a.sa|0),!0):!1}
function wb(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.ha)&&(c=Math.ceil(a.sa*(a.Ac?a.la:a.ma)/1E3*(void 0===c?1E3:c)),a.g&&(c+=oc(a)),b.ha=c)}q.start=function(){if(this.g||this.m)return!1;this.g=!0;this.v=this.T=this.W=0;this.update(!0);this.O=this.zb();return!0};function rc(a,b){b=void 0===b?1:b;a.g||(b&&!a.m&&(a.m=b),a.m&&(a.m--,qc(a,oc(a,mc(a,pc(a,1)))),a.update(!1),a.m&&setTimeout(function(){rc(a,0)},0)))}
function U(a){return a.g?(a.g=!1,oc(a),a.O&&(a.mc(a.O),a.O=0),a.update(!0),!0):a.m?(a.m=0,a.update(!0),!0):!1}q.update=function(a){a&&this.s(this.g?"started with %s target\n":"stopped\n",hc(this.K));L(this,dc,this.g?"Halt":"Run");L(this,ic,this.m?"Stop":"Step");this.I||(this.s(262144,"getSpeedCurrent(%5.3fhz)\n",1E6*this.R),gc(this,this.g&&this.R?hc(this.R):"Stopped"));for(var b=0;b<this.ja.length;b++){var c=this.ja[b];c.Ic.call(c,void 0!=a)}this.Ia=Date.now();this.ca=!0};
function gc(a,b){L(a,sc,b);L(a,fc,b)}var dc="run",fc="setSpeed",sc="speed",ic="step",kc="throttle";D.Time=ac;
function tc(a,b,c){N.call(this,a,b,c);this.type="static"==this.J.type?uc:vc;this.v=this.J.addrWidth||16;this.j=Math.pow(2,this.v);this.I=this.j-1|0;this.blockSize=this.J.blockSize||(16<this.v?4096:1024);this.blockSize>this.j&&(this.blockSize=this.j);this.K=this.j/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.m=(1<<this.h)-1;this.H=this.J.dataWidth||8;this.g=Array(this.K);this.u=0;a=new V(a,b+"[NONE]",{size:this.blockSize,bus:this.V});for(b=0;b<this.j;b+=this.blockSize)wc(this,b,this.blockSize,
W.NONE,a);a=this.u;this.u+=this.type;a&&this.u||(this.Da=this.hc,this.Ea=this.Fa)}z(tc,N);
function wc(a,b,c,d,e){for(var f=b>>>a.h;0<c&&f<a.g.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var l=a.g[f];if(b!=g||h!=a.blockSize||l&&l.type!=W.NONE)break;var k=l=void 0,m=b,n=a.v,p=16;n=void 0===n?0:n;l=void 0===l?0:l;var u="",x="",v=-1;p||(p=a.N||10);n&&(v=Math.ceil(n/Math.log2(p)));if(void 0==k)switch(p){case 8:k="0o";break;case 16:k="0x";break;case 10:x=".";default:k=""}isNaN(m)||"number"!=typeof m?(m=void 0,k=x=""):(0>m&&-1<m&&(m=-1),n&&(0>m&&(m+=Math.pow(2,n)),m>=Math.pow(2,
n)&&(v=Math.ceil(Math.log(m)/Math.log(p)))));for(n=l||-1;v--;){n||(u=","+u,n=l);if(void 0==m){if(u="?"+u,0>v)break}else{var y=m%p;m=Math.trunc(m/p);y+=0<=y&&9>=y?48:55;u=String.fromCharCode(y)+u;if(!m&&0>v)break}n--}l=a.V+"["+(k+u+x)+"]";b=e?e.size==a.blockSize?e:new V(a.M,l,{type:d,Ka:b,size:h,bus:a.V}):new V(a.M,l,{type:d,Ka:b,size:h,bus:a.V});a.g[f]=b;b=g+a.blockSize;c-=h;f++}}q=tc.prototype;q.je=function(a,b){this.fa&&this.fa.s(4,"bus fault (%d) at %n\n",b,a)};
q.ia=function(){void 0===this.fa&&(this.fa=P(this,"Debugger",!1))};q.qa=function(){};q.$a=function(a){return a&&this.pa(a)?!0:!1};q.ab=function(a){this.ra(a)};q.pa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==vc||c.type&W.Ja)&&c.pa){var d=a.shift();if(!c.pa(d))return!1}}return!0};q.ra=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==vc||c.type&W.Ja)&&c.ra){var d=[];c.ra(d);a.push(d)}}};q.xa=function(a){return this.g[a>>>this.h].xa(a&this.m)};
q.hc=function(a){return this.g[a>>>this.h].Da(a&this.m)};q.bb=function(a,b){this.g[a>>>this.h].bb(a&this.m,b)};q.Fa=function(a,b){this.g[a>>>this.h].Ea(a&this.m,b)};var uc=0,vc=1;D.Bus=tc;
function V(a,b,c){N.call(this,a,b,c);this.Ka=this.J.addr;this.size=this.J.size;this.type=this.J.type||W.NONE;this.m=(a=this.J.bus)?O(this,a):P(this,a="Bus");if(!this.m)throw Error(this.X("unable to find bus '%s'",a));this.v=this.m.H;this.K=Math.pow(2,this.v)-1;this.u=this.I=!1;this.values=this.j=null;a=this.pb;b=this.Fa;if(this.m.type==uc){b=this.Mc;if(c=8==this.v)c=O(this,this.M),c=!1!==(c&&c.J&&c.J.ArrayBuffer||this.J.ArrayBuffer);c&&(this.I=!0)}switch(this.type){case W.NONE:this.Da=this.Jc;this.Ea=
this.Rb;break;case W.Bb:this.Da=a;this.Ea=this.Rb;break;case W.Ja:this.Da=a,this.Ea=b}xc(this,this.J.values);yc(this)}z(V,N);function xc(a,b){"string"==typeof b?(hb(a,!1),Pa(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);xc(a,g.values)}catch(h){a.s("error (%s) parsing resource: %s\n",h.message,c)}hb(a,!0)}else a.s("error (%d) loading resource: %s\n",f,c)})):a.J.values=b}
function yc(a,b){if(a.type>W.NONE&&(a.I?(a.j=new ArrayBuffer(a.size),new DataView(a.j,0,a.size),a.values=new Uint8Array(a.j,0,a.size),new Uint16Array(a.j,0,a.size>>1),new Int32Array(a.j,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}q=V.prototype;
q.qa=function(){if(this.J.values)a:{var a=this.m,b=this.Ka,c=this.size,d=this.J.values,e=0,f=b&a.m;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var g=a.g[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Fa(f++,d[e++]),c--;f=0}}else this.type&W.Ja&&this.values&&this.values.fill(0)};q.Jc=function(){return this.K};q.xa=function(a){return this.values?this.values[a]:0};q.pb=function(a){return this.values[a]};q.Rb=function(){};q.bb=function(a,b){this.values&&(this.values[a]=b)};
q.Fa=function(a,b){this.values[a]=b};q.Mc=function(a,b){this.values[a]=b;this.u=!0;this.Ea=this.Fa};q.pa=function(a){if(a){var b=a.shift();if(this.V==b){this.u=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}yc(this,a)}return!0}}return!1};
q.ra=function(a){a.push(this.V);a.push(this.u);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var W={NONE:1,Bb:2,Ja:4,ae:14,ee:12};D.Memory=V;
function zc(a,b,c){c.type=W.Bb;V.call(this,a,b,c);wc(this.m,this.J.addr,this.J.size,this.J.type,this);ib(this,this.qa.bind(this));this.da=this.fa=void 0;if(D.LED&&this.S[Ac]){var d=this;this.h=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.H=this.values.length/this.h|0;this.g=new Fb(a,b+"LEDs",{"class":"LED",bindings:{container:La(this,Ac)},type:Hb,cols:this.h,rows:this.H,color:H(this,"colorROM","green"),backgroundColor:H(this,"backgroundColorROM","black"),persistent:!0}),Qb(this.g);
this.N=new kb(a,b+"Input",{"class":"Input",location:[0,0,this.g.ea,this.g.Z,this.h,this.H],bindings:{surface:La(this,Ac)}});this.O=Ma(this)||"";nb(this.N,function(e,f){if(d.da){var g=d.O;0<=e&&0<=f&&(e=f*d.h+e,g=Bc(d.da,d.Ka+e,d.values[e]));L(d,Na,g)}})}}z(zc,V);
zc.prototype.pa=function(a){var b=!0,c=a.shift();if(c&&this.g){var d=c.length;this.g.g.length==d?(this.g.g=c,Pb(this.g,!0)):(this.s("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.s("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};zc.prototype.ia=function(){void 0===this.da&&(this.da=P(this,"CPU"));void 0===this.fa&&(this.fa=P(this,"Debugger",!1))};
zc.prototype.pb=function(a){this.g&&Yb(this.g,a%this.h,a/this.h|0,1,Sb);return this.values[a]};zc.prototype.ra=function(a){this.g&&(a.push(this.g.g),a.push(this.values))};var Ac="array",Na="cellDesc";D.ROM=zc;function Cc(a,b,c){c["class"]="CPU";N.call(this,a,b,c);this.fa=void 0;this.h=this.Qa=0;this.time=P(this,"Time");this.time.N.push(this);this.time.ja.push(this);this.Z=this.v=0}z(Cc,N);q=Cc.prototype;q.abort=function(a){this.h=this.Qa;this.s("%s\n",a.message);U(this.time)};q.Mb=function(){};
q.Lc=function(a){this.Z=this.v=a=void 0===a?0:a;try{this.Mb(a)}catch(b){this.abort(b)}return this.Ob()};q.Qb=function(){this.Z-=this.v;this.v=0};q.Ob=function(){return this.Z-this.v};function X(a,b,c){N.call(this,a.M,b);this.da=a;this.name=b;this.l=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.na[c]=[this,-1];for(var d=0;d<this.l.length;d++)c=this.X("reg%s-%02d",this.name,d),b.push(c),a.na[c]=[this,d];Ia(a,b)}}z(X,N);q=X.prototype;
q.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]+b.l[f]+e,e=0,this.l[f]>=d&&(this.l[f]-=d,e=1);e&&(this.da.H=!0);Dc(this,c)};q.get=function(){return this.l};function Ec(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.l.length;d++)a.l[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.l[d]=b&15,b>>>=4;return a}q.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.l[e]=a.l[e]+d,d=0,this.l[e]>=c&&(this.l[e]-=c,d=1);Dc(a,b)};
q.set=function(a){if(a&&a.length==this.l.length)for(var b=0;b<this.l.length;b++)this.l[b]=a[b]};q.store=function(a){for(var b=0,c=this.l.length;b<c;b++)this.l[b]=a.l[b]};q.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]-b.l[f]-e,e=0,0>this.l[f]&&(this.l[f]+=d,e=1);e&&(this.da.H=!0);Dc(this,c)};q.toString=function(a){a=void 0===a?!1:a;var b=this.V+"=";a&&3>b.length&&(b+=" ");for(var c=this.l.length-1;0<=c;c--)b=a?b+xa[this.l[c]]:b+(ya[this.l[c]]+(c%4?"":" "));return b};
function Dc(a,b){a.da.u=a.l[b[0]];b[0]<b[1]&&(a.da.u|=a.l[b[0]+1]<<4)}
function Fc(a,b,c){Cc.call(this,a,b,c);this.type=Number.parseInt(H(this,"type","1501").slice(-4),10);this.na={};this.g=Array(4);for(a=0;4>a;a++)this.g[a]=new X(this,String.fromCharCode(65+a));this.U=this.g[0];this.$=this.g[1];this.sa=this.g[2];this.wa=this.g[3];this.R=Array(8);for(a=0;8>a;a++)this.R[a]=new X(this,"X"+a);this.W=Array(8);for(a=0;8>a;a++)this.W[a]=new X(this,"Y"+a);this.oa=new X(this,"Supp",!0);this.ba=new X(this,"Temp",!0);this.O=10;this.H=!1;this.aa=this.u=this.K=0;this.m=[-1,-1,-1];
this.va=O(this,this.J.input);this.va.K=this.ic.bind(this);this.j=O(this,this.J.output,!1);this.N=P(this,"Bus");this.I=P(this,"ROM");this.la=this.ma=this.Y=void 0;this.ja=this.ca=-1;this.T={};this.ea=Gc;a=this.Hc.bind(this);b=Va.hb;this.L.Ha[b]||(this.L.Ha[b]=[]);this.L.Ha[b].push(a)}z(Fc,Cc);function Hc(a,b){a.T[b]&&(a.T[b]=!1,a.s("break on %s\n",Ic[b]),U(a.time))}function Jc(a){a.j&&Qb(a.j);if(a.I){var b=a.I;b.g&&Qb(b.g)}Kc(a,!1)}q=Fc.prototype;
q.Mb=function(a){for(;0<this.v;){if(this.ja==this.h){this.ja=-1;this.s("break\n");U(this.time);break}var b=this.N.Da(this.h);this.h=(this.Qa=this.h)+1&this.N.I;if(void 0==b||!Lc(this,b)){this.h=this.Qa;this.s("unimplemented opcode\n");U(this.time);break}this.v-=Mc}if(0>=a){var c=this;nc(this.time,function(){var d=c.I;d.g&&Pb(d.g);c.ua(c.toString())})}};q.Qb=function(){this.v=0};q.Ob=function(){return this.Z-this.v};
function Lc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.H&&(a.h=a.h&1024|b&1023):(a.push(a.h),a.h=b&2047),a.H=!1,!0;var c;var d=b&Nc;switch(d){case Oc:case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:d=$c[d];var e=(b&ad)>>bd;var f=(b&cd)>>dd;var g=(b&ed)>>fd;var h=(c=b&gd)?hd:id;b=b>=Vc?16:a.O;switch(f){case 0:case 1:case 2:case 3:var l=a.g[f];break;case 4:l=Ec(a.ba,1,d);break;case 5:h=c?jd:kd;break;case 6:l=Ec(a.ba,a.u&15,d);break;case 7:l=Ec(a.ba,a.u&255,d)}switch(g){case 0:var k=
a.g[e];break;case 1:k=4>f?a.g[f]:void 0;break;case 2:k=5>f?a.oa:5==f?a.g[e]:void 0;break;case 3:if(c)a.g[e].move(l,d,b);else{a=a.U;e=l;b=d[0];for(l=d[1];b<=l;b++)k=a.l[b],a.l[b]=e.l[b],e.l[b]=k;Dc(e,d)}return!0}if(!k)break;switch(h){case id:k.add(a.g[e],l,d,b);break;case hd:k.sub(a.g[e],l,d,b);break;case kd:b=k;a=a.g[e];e=d[1];for(l=d[0];e>l;e--)b.l[e]=a.l[e-1];b.l[e]=0;Dc(b,d);break;case jd:b=k;a=a.g[e];e=d[0];for(l=d[1];e<l;e++)b.l[e]=a.l[e+1];b.l[e]=0;Dc(b,d)}return!0;case ld:e=(b&md)>>nd;d=(b&
od)>>pd;l=1<<((b&qd)>>rd);if(!d)break;d+=12;switch(b&sd){case td:a.g[e].l[d]|=l;break;case ud:a.g[e].l[d]&=~l;break;case vd:a.g[e].l[d]&l&&(a.H=!0);break;case wd:a.g[e].l[d]^=l}return!0;case xd:switch(b&yd){case zd:a.U.store(a.W[a.K]);break;case Ad:a.K=b>>4&7;break;case Bd:a.h=a.u;break;case Cd:a.H=!1;d=a.m[0];e=0;for(b=a.m.length-1;e<b;)a.m[e]=a.m[++e];a.m[e]=-1;a.h=d;break;case Dd:a.R[a.K].store(a.U);break;case Ed:a.U.store(a.R[a.K]);break;case Fd:a.W[a.K].store(a.U);break;case Gd:Hc(a,"o");if(a.j){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.$.l[e]&8?b=" ":a.$.l[e]&1?b="-":b=xa[a.U.l[e]],Yb(a.j,d,0,b,a.$.l[e]&2?Vb:0)&&Hc(a,"om");Kc(a)}a.v-=31*Mc;a.aa&&(a.u=a.aa,a.H=!0,Hc(a,"i"));break;case Hd:a.O=10;break;case Id:a.O=16;break;case Jd:a.K=a.u&7;break;default:return!1}return!0}return!1}
q.pa=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return this.s("invalid saved state\n"),!1;var c=b.shift();if(3!==(c|0))return this.s("saved state version mismatch: %3.2f\n",c),!1;try{this.g.forEach(function(d){return d.set(b.shift())}),this.R.forEach(function(d){return d.set(b.shift())}),this.W.forEach(function(d){return d.set(b.shift())}),this.oa.set(b.shift()),this.ba.set(b.shift()),this.O=b.shift(),this.H=b.shift(),this.K=b.shift(),this.u=b.shift(),this.h=b.shift(),this.m=b.shift(),this.aa=
b.shift()}catch(d){return this.s("CPU state error: %s\n",d.message),!1}return(a=a.stateROM||a[1])&&this.I&&!this.I.pa(a)?!1:!0};
q.Hc=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,h=3;h<a.length;h++)d.push(Number.parseInt(a[h],16));this.ea=Gc;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Ic)c=Ic[f],b+="break on "+c+" (b"+f+"): "+(this.T[f]||!1)+"\n";break}(c=Ic[f])?(this.T[f]=!this.T[f],b="break on "+c+" (b"+f+"): "+this.T[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.N.xa(f);if(void 0==
a)break;this.N.bb(f,d[g]);b+=this.X("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.X("%d locations updated\n",c);break;case "g":this.time.start()?this.ja=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.ea=Kd);g=Number.parseInt(a[2],10)||1;jc(this.time,g);break;case "r":"c"==e[1]&&(this.ea=Kd);this.Pb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.ca?this.ca:this.h;g--;){c=this.I&&this.N.xa(f);if(void 0==
c)break;b+=Bc(this,f++,c)}this.ca=f;break;case "?":b="additional commands:\n";Ld.forEach(function(l){b+=l+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};q.ic=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.aa=c};q.$a=function(a){return a&&this.pa(a)?!0:!1};q.ia=function(a){a?this.time.start():(U(this.time),Jc(this))};q.qa=function(){this.s("reset\n");this.h=0;Jc(this);this.time.g||this.ua(this.toString())};q.ab=function(a){this.ra(a)};
q.Ic=function(a){for(var b in this.S){var c=this.na[b];if(c){var d=c[0];c=c[1];L(this,b,0>c?d.toString():xa[d.l[c]])}}a&&!this.time.g&&(a=this.I,a.g&&Pb(a.g),this.ua(this.toString()))};q.push=function(a){for(var b=this.m.length-1;0<b;)this.m[b]=this.m[--b];this.m[0]=a};
q.ra=function(a){var b=[],c=[];b.push(3);this.g.forEach(function(d){return b.push(d.get())});this.R.forEach(function(d){return b.push(d.get())});this.W.forEach(function(d){return b.push(d.get())});b.push(this.oa.get());b.push(this.ba.get());b.push(this.O);b.push(this.H);b.push(this.K);b.push(this.u);b.push(this.h);b.push(this.m);b.push(this.aa);this.I&&this.I.ra(c);a.push(b);a.push(c)};q.Pb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.h=b;break;default:this.s("unrecognized register: %s\n",a)}};
function Bc(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.X("%#06x",f);else if(0<=c){var g=c&Nc;var h;switch(g){case Oc:case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:f="";e=$c[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&ad)>>bd;var l=(c&cd)>>dd;var k=(c&ed)>>fd;var m=c&gd;e="LOAD";var n=h="?";var p=m?5==l?">>":"-":5==l?"<<":"+";switch(k){case 0:h=
Y[g];break;case 1:4>l&&(h=Y[l]);break;case 2:6>l&&(h="NUL");break;case 3:m?(e="MOVE",h=Y[g],n=Y[l]):(e="XCHG",g||(h="A"),4>l&&(n=Y[l])),l=-1}switch(l){case 0:case 1:case 2:case 3:n=Y[g]+p+Y[l];break;case 4:case 5:n=Y[g]+p+"1";break;case 6:n=Y[g]+p+"R5L";break;case 7:n=Y[g]+p+"R5"}f=h+","+n+","+f;break;case ld:switch(c&sd){case td:e="SET";break;case ud:e="CLR";break;case vd:e="TST";break;case wd:e="NOT"}f=a.g[(c&md)>>nd].name;g=(c&od)>>pd;f+="["+(g?g+12:"?")+":"+((c&qd)>>rd)+"]";break;case xd:switch(c&
yd){case zd:e="STORE";f="A,Y[RAB]";break;case Ad:e="STORE";f="RAB,"+((c&112)>>4);break;case Bd:e="BR";f="R5";break;case Cd:e="RET";break;case Dd:e="STORE";f="X[RAB],A";break;case Ed:e="STORE";f="A,X[RAB]";break;case Fd:e="STORE";f="Y[RAB],A";break;case Gd:e="DISP";break;case Hd:e="BCDS";break;case Id:e="BCDR";break;case Jd:e="STORE",f="RAB,R5L"}}}return a.X(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
q.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.ea){this.I&&(d+=Bc(this,this.h,this.N.xa(this.h),!0));d+="  ";b=0;for(a=this.g.length;b<a;b++)d+=this.g[b].toString()+" ";d+="\n ";d+=" COND="+(this.H?1:0);d+=" BASE="+this.O;d+=" R5="+this.X("%02X",this.u);d+=" RAB="+this.K+" ST=";this.m.forEach(function(f){d+=c.X("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.g);0<=a.indexOf("a")&&(d+=this.toString(a,this.R),d+=this.toString(a,this.W));d+="COND="+(this.H?1:0);d+=" BASE="+this.O;d+=" R5="+this.X("%#04x",this.u);d+=" RAB="+this.K+" ";this.m.forEach(function(f,g){d+=c.X("ST%d=%#06x ",g,f&65535)});this.I&&(d+="\n"+Bc(this,this.h,this.N.xa(this.h)));this.ca=this.h;return d};
function Kc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Md?!!(a.sa.l[14]&8):!!(a.$.l[15]&4));if(a.la!==d){if(c=a.S["2nd"])c.style.opacity=d?"1":"0",void 0===a.la&&a.j&&(c.style.color=a.j.color);a.la=d}d=b&&(a.type==Md?!!(a.$.l[15]&4):!!(a.wa.l[15]&8));if(a.ma!==d){if(c=a.S.INV)c.style.opacity=d?"1":"0",void 0===a.ma&&a.j&&(c.style.color=a.j.color);a.ma=d}c=a.type==Md?a.R[4].l[15]>>2:a.sa.l[15];b=b?c?1==c?Nd:Od:Pd:Qd;if(a.Y!==b){if(c=a.S.Deg)c.style.opacity=b==Pd?"1":"0",void 0===a.Y&&a.j&&(c.style.color=
a.j.color);if(c=a.S.Rad)c.style.opacity=b==Nd?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);if(c=a.S.Grad)c.style.opacity=b==Od?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);a.Y=b}}
var Nc=3840,Oc=0,Pc=256,Qc=512,Rc=768,Sc=1024,Tc=1280,Uc=1792,Vc=2048,Wc=2304,Xc=2560,ld=3072,Yc=3328,xd=3584,Zc=3840,ad=192,bd=6,cd=56,dd=3,ed=6,fd=1,gd=1,sd=3,td=0,ud=1,vd=2,wd=3,md=192,nd=6,od=48,pd=4,qd=12,rd=2,yd=15,zd=0,Ad=1,Bd=2,Cd=3,Dd=4,Ed=5,Fd=6,Gd=7,Hd=8,Id=9,Jd=10,Z={},$c=(Z[Oc]=[12,12],Z[Pc]=[0,15],Z[Qc]=[2,12],Z[Rc]=[0,12],Z[Sc]=[2,2],Z[Tc]=[0,1],Z[Uc]=[0,13],Z[Vc]=[14,14],Z[Wc]=[13,15],Z[Xc]=[14,15],Z[Yc]=[13,13],Z[Zc]=[15,15],Z),Mc=128,id=0,hd=1,kd=2,jd=3,Md=1501,Qd=0,Pd=1,Nd=2,Od=
3,Ic={i:"input",o:"output",om:"output modification"},Gc=0,Kd=1,Y="A B C D 1 ? R5L R5".split(" "),Ld="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");D.CPU1500=Fc;
function Rd(a,b,c){N.call(this,a,a);var d=this;this.j=!1;this.H=c;this.h="";this.v=this.u=!1;hb(this,!1);this.ga=0;b=b.trim();"{"==b[0]?Sd(this,b):(this.h=b,Pa(this.h,function(e,f,g,h){4==g&&(!h&&f?(Sd(d,f),Td(d)):d.s("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.v=!0;Td(d)});window.addEventListener(Ra("iOS")?"pagehide":Ra("Opera")?"unload":"beforeunload",function(){Ud(d)});window.addEventListener("pageshow",function(){d.j||d.ia(!0)})}z(Rd,N);
Rd.prototype.za=function(a,b){var c=this;switch(a){case Vd:b.onclick=function(){c.ia()};break;case Wd:b.onclick=function(){c.qa()}}N.prototype.za.call(this,a,b)};
function Td(a){var b=!0;if(a.u&&a.v){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],D[d]?"Machine"==d?(a.s("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2023 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.s("Configuration: %s\n",a.h)):new D[d](a.M,c,e):a.s('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.s('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),jb(a,c)}}if(a.m){var f=Sa(a);gb(a,function(g){return g.$a&&!g.$a(f)?(g.s('unable to restore state for device "%s"\n',
g.V),!1):!0})}hb(a,!0);ib(a,a.ia.bind(a,b))||a.s("machine %s not ready to power, waiting for device(s)\n",a.M)}}
function Sd(a,b){try{a.g=JSON.parse(b);var c=a.g[a.M];if(!c){c=a.g[Ca(a.h)];if(!c)throw Error("configuration missing machine ID");a.g[a.M]=c}fb(a,c,["autoSave","autoStart"]);a.m=!1!==a.J.autoSave;a.I=!1!==a.J.autoStart;if(a.H){var d=eval("("+a.H+")"),e;for(e in d)a.J[e]=d[e]}a.u=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.s("machine '%s' initialization error: %s\n",a.M,c)}}
Rd.prototype.ia=function(a){a=void 0===a?!this.j:a;if(Q(this)){var b=this;a&&this.s("power on\n");gb(this,function(c){c.ia&&c!=b&&("CPU"!=c.J["class"]||b.I&&Q(b)?c.ia(a):c.time.update(!0));return!0});(this.j=a)||this.s("power off\n")}};Rd.prototype.qa=function(){if(Q(this)){var a=this;gb(this,function(b){b.qa&&b!=a&&b.qa();return!0});this.s("reset\n")}};function Ud(a){if(a.m){var b=[];gb(a,function(c){c.ab&&c.ab(b);return!0});Za(a,b)}a.ia(!1)}var Vd="power",Wd="reset";
window.TMS1500=function(a,b,c){var d=new Rd(a,b,c);window.command=function(e){return Ta(d,e)};return d};D.Machine=Rd;})()

//# sourceMappingURL=ti55.js.map
