(function(){/*
 https://www.pcjs.org/machines/modules/v3/defines.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/message.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdlib.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdio.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/webio.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/device.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/input.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/led.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/time.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/bus.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/memory.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/rom.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/cpu.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/ti/modules/v3/cpu1500.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/machine.js (C) 2012-2024 Jeff Parsons
*/
var p;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function q(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)a=b.call(a);else if("number"==typeof a.length)a={next:aa(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function u(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function y(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.te=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
u("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});u("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
u("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});u("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
u("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}u("Array.prototype.keys",function(a){return a?a:function(){return na(this,function(b){return b})}});
u("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function z(a){return a?a:Array.prototype.fill}u("Int8Array.prototype.fill",z);u("Uint8Array.prototype.fill",z);u("Uint8ClampedArray.prototype.fill",z);u("Int16Array.prototype.fill",z);u("Uint16Array.prototype.fill",z);u("Int32Array.prototype.fill",z);
u("Uint32Array.prototype.fill",z);u("Float32Array.prototype.fill",z);u("Float64Array.prototype.fill",z);u("Number.parseInt",function(a){return a||parseInt});u("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});function oa(){this.V=""}var pa=new ArrayBuffer(2);(new DataView(pa)).setUint16(0,256,!0);new Uint16Array(pa);
var B={fe:"undefined"!=typeof window,node:"undefined"!=typeof window?{}:global,process:"undefined"!=typeof process?process:{},window:"undefined"!=typeof window?window:global,document:"undefined"!=typeof document?document:{},Pa:{machines:{},components:[],commands:{},files:null}};B.window.PCjs?B.Pa=B.window.PCjs:B.window.PCjs=B.Pa;var qa=B.process,D=B.Pa.machines,ra=B.Pa.components,E={};E.Defines=oa;
var sa={all:0xffffffffffff,addr:1,bus:2,fault:4,memory:8,ports:16,chips:32,kbd:64,serial:128,misc:256,cpu:512,mmu:2048,"int":1024,trap:4096,video:8192,monitor:16384,screen:32768,disk:131072,file:65536,time:262144,timer:524288,event:1048576,input:2097152,key:4194304,mouse:8388608,touch:16777216,info:274877906944,warn:549755813888,error:1099511627776,halt:70368744177664,buffer:0x800000000000};function ta(){this.g={};for(var a=0;23>a;a++)this.g["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
function ua(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,q(a)));return a}
ta.prototype.L=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(void 0===this.g[g])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];"%"!=g&&e++}else h=b[b.length-1];var k=!1,m=d[f+1],l=0<=m.indexOf("#"),r=0<=m.indexOf("0"),n=d[f+2];"*"==n?(n=h,h=e<b.length?b[e++]:b[b.length-1]):n=+n||0;var t=d[f+3];t=t?+t.substr(1):-1;var w=d[f+4],
v=null,A=0,x="",C=0<="ACDFGHMNSTWY".indexOf(g)&&"object"!=typeof h?ua(h):h;switch(g){case "C":c+=isNaN(C.getTime())?void 0:this.L("%#W, %#F %#D, %#Y".replaceAll("#",l?"#":""),C);continue;case "D":h=l?C.getUTCDate():C.getDate();g="d";break;case "A":case "G":case "H":h=l?C.getUTCHours():C.getHours();"A"==g?(h=12>h?"am":"pm",g="s"):("G"==g&&(h=h?12<h?h-12:h:12),g="d");break;case "F":case "M":h=l?C.getUTCMonth():C.getMonth();"F"==g?(h=va[h],g="s"):(h++,g="d");break;case "N":h=l?C.getUTCMinutes():C.getMinutes();
g="d";break;case "S":h=l?C.getUTCSeconds():C.getSeconds();g="d";break;case "T":c+=isNaN(C.getTime())?void 0:this.L("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",l?"#":""),C);continue;case "W":h=wa[l?C.getUTCDay():C.getDay()];g="s";break;case "Y":h=l?C.getUTCFullYear():C.getFullYear(),0<t&&(h%=Math.pow(10,t)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=t&&(r=!0,n<t&&(n=t),t=-1);case "f":h=+h;g=h+"";0<=t&&(g=h.toFixed(t));g.length<n&&(r?(0>h&&(n--,g=g.substr(1)),
g=("0".repeat(n)+g).slice(-n),0>h&&(g="-"+g)):g=(" ".repeat(n)+g).slice(-n));c+=g;break;case "j":c+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=t&&(h=h.substr(0,t));h.length<n;)h=0<=m.indexOf("-")?h+" ":" "+h;c+=h;break;case "B":A=2,l&&(x="0b");case "o":A||(A=8),!x&&l&&(x="0o");case "X":v=xa;case "x":g="";A||(A=16);!x&&l&&(x="0x");v||(v=ya);"string"==typeof h&&"-"==h[0]&&(k=!0,h=
h.slice(1));h=Math.trunc(h);k&&(h=-h);0>h&&((h|0)==h?h>>>=0:Math.abs(h)<=Math.pow(2,53)&&(h+=Math.pow(2,53)));0<=t&&(r=!0,n<t&&(n=t));r&&!n&&("b"==w?n=2:"h"==w||"w"==w?n=4:"l"==w?n=8:(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9),n+=x.length);n-=x.length;do k=16,Number.isNaN(h)||(k=h&A-1,h=Math.trunc(h/A)),r||!g||k||h?g=v[k]+g:(x&&(g=x+g,x=""),0<n&&(g=" "+g));while(0<--n||h);c+=x+g;break;case "%":c+="%";break;default:c=this.g[g]?c+this.g[g](g,m,n,t,h):c+("(unimplemented sprintf type: %"+
g+")")}}}return c+=d[f]};var wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" "),ya="0123456789abcdef?",xa="0123456789ABCDEF?";function za(){oa.apply(this,arguments)}y(za,oa);function Aa(a,b){var c=a/F|0,d=b/F|0;return(a&b)==(b|0)&&(c&d)==d}var F=Math.pow(2,32);E.StdLib=za;function G(){za.call(this);this.qb=new ta;this.X=this.qb.L.bind(this.qb)}y(G,za);
G.prototype.flush=function(){var a=Ba;Ba="";this.ua(a)};function Ca(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}G.prototype.ua=function(a,b){var c=a.length,d=a.lastIndexOf("\n");b?0<=d&&(b=Date.now(),Da||(Da=b),a=((b-Da)/1E3).toFixed(3)+": "+a,c=a.length):"node"==this.V?(qa.se.write(a),a=""):(0<=d&&(console.log(Ba+a.slice(0,d)),Ba="",a=a.slice(d+1)),Da=null);Ba+=a;return c};
G.prototype.s=function(a){return this.ua(this.X.apply(this,[a].concat(q(la.apply(1,arguments)))))};var Ba="",Da=null;E.StdIO=G;function H(a){G.call(this);this.S={};this.ga=0;this.L=this;a&&(this.L.ga=0,this.L.ta=[],this.L.ka=0,this.L.Ha={},this.L.de=!1)}var Ea;y(H,G);p=H.prototype;
p.za=function(a,b){var c=this,d=this;this.S[a]=b;switch(a){case Fa.Vb:b.onclick=function(){var e=c.Ba(Fa.Xa,!0);e&&(e.value="")};break;case Fa.Xa:Ga(b),b.addEventListener("keydown",function(e){Ha(d,e,!0)}),b.addEventListener("keypress",function(e){Ha(d,e)})}};
function Ia(a,b){b=void 0===b?{}:b;if("undefined"!=typeof document){a.J.S||(a.J.S=b);var c=Array.isArray(b);c?0>b.indexOf("container")&&b.push("container"):b.container||(b.container=a.V);for(var d in b){var e=b[d];if(c)d=e;else if(e.match(/^[0-9]+$/)){var f=+e;a.S[d]=[];do{e=d+f++;e=document.getElementById(e);if(!e)break;a.S[d].push(e)}while(1);continue}(f=document.getElementById(e))&&a.za(d,f)}}}
function Ga(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}p.error=function(a,b){b=this.X.apply(this,[a].concat(q(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.X.apply(this,[c].concat(q(b))))this.s("%s\n",b),a||alert(b)};p.Ba=function(a){return this.S[a]};
function Ja(a){var b=window;if(b){do{for(var c=0;c<Ka.length;c++){var d=Ka[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function La(a,b){return a.J.bindings&&a.J.bindings[b]}function Ma(a){if(a=a.S[Na])var b=a.textContent;return b}function Oa(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function I(a,b,c,d){a=a.J[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Pa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Qa(a){if(void 0===J.Ua){var b=!1;if(window)try{window.localStorage.setItem(J.ya,J.ya),b=window.localStorage.getItem(J.ya)==J.ya,window.localStorage.removeItem(J.ya)}catch(c){a.s("%s\n",c.message),b=!1}J.Ua=b}return!!J.Ua}function K(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.ga;return-1==(b|1)||Aa(a.L.ga,b)?!0:!1}
function Ra(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Sa(a){var b=null;if(Qa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.M))&&(b=JSON.parse(c))}catch(d){a.s("%s\n",d.message)}}return b}
function Ha(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.L,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==L.eb&&f.selectionStart<=h+1&&(a=!0);d==L.zc?(a=!0,0<e.ka&&(g=e.ta[--e.ka])):d==L.Yb&&(a=!0,e.ka<e.ta.length&&(g=e.ta[++e.ka]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.ka&&c+1==g.length&&
(f.value+=e.ta[--e.ka],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ta(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&a.s("%s\n",b.replace(/\n$/,"")))}}
function Ua(a,b){if(void 0!=b){var c=a.L;try{if(b=b.trim())c.ka<c.ta.length&&b==c.ta[c.ka]?c.ka++:(c.ta.push(b),c.ka=c.ta.length);var d=b.split(" "),e=d[0],f=a.L.Ha[Va.hb];switch(e[0]){case "m":if("?"==e[1]){var g="";Wa.forEach(function(r){g+=r+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var k="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=k&&d.pop();1>=d.length&&(void 0!=k&&(h=k,k=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(sa));for(f=
1;f<d.length;f++){e=d[f];var m=sa[e];if(!m){g+="unrecognized message: "+e+"\n";break}void 0!=k&&Xa(a,m,k);if(void 0==h||h==K(a,m))g+=a.X("%8s: %b\n",e,K(a,m))}K(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ya.forEach(function(r){g+=r+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var l=f[a](d);if(void 0!=l){g=g?g+l:l;break}}}}catch(r){g="error: "+r.message+"\n"}}return g}
function Ta(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Ua(a,b[d])}return c}
p.ua=function(a,b){void 0==b&&(b=K(this,0x800000000000));if(!b){var c=this.Ba(Fa.Xa,!0);if(c){b=c.selectionStart;for(var d=a.split(/([\n\r\b])/),e=0;e<d.length;e++){var f=d[e];if(f)if("\b"==f||"\r"==f)for(;0<b&&"\n"!=c.value.slice(b-1,b)&&(b--,"\b"!=f););else if("\n"==f){for(f="";b<c.value.length&&(f=c.value[b],b++,"\n"!=f););"\n"!=f&&(c.value+="\r\n",b=c.value.length)}else c.value=c.value.slice(0,b)+f+c.value.slice(b+f.length),b+=f.length}c.focus();c.setSelectionRange(b,b);8192<=c.value.length&&
(c.value=c.value.slice(c.value.length-8192+4096));c.scrollTop=c.scrollHeight;return a.length}}return G.prototype.ua.call(this,a,b)};p.s=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return K(this,c)?(Aa(c,1099511627776)&&(a="error: "+a),Aa(c,549755813888)&&(a="warning: "+a),G.prototype.s.call.apply(G.prototype.s,[this,a].concat(q(b)))):0};function Za(a,b){if(Qa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.M,b)}catch(c){a.s("%s\n",c.message)}}}
function M(a,b,c){(a=a.S[b])&&a.textContent!=c&&(a.textContent=c)}function Xa(a,b,c){var d=!1;c?(c=a.L.ga,a.L.ga=(c|b)+(c/F|0|b/F|0)*F):(d=Aa(a.L.ga,0x800000000000)&&Aa(b,0x800000000000),c=a.L.ga,a.L.ga=(c&~b)+((c/F|0)&~(b/F|0))*F);d&&a.flush()}
var Fa={Vb:"clear",Xa:"print"},Ya=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Wa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],Va={hb:"command"},$a={ib:13,Ta:65,cb:66,fb:67,jb:68,E:69,kb:70,lb:71,mb:72,nb:73,ob:74,rb:75,sb:76,vb:77,wb:78,xb:79,yb:80,Q:81,Ab:82,Cb:83,Db:84,Eb:85,Fb:86,Gb:87,Hb:88,
Ib:89,Za:90,a:97,b:98,c:99,d:100,e:101,f:102,ke:103,le:104,me:105,ne:106,k:107,oe:108,pe:109,n:110,qe:111,p:112,q:113,r:114,re:115,t:116,ue:117,ve:118,w:119,x:120,y:121,z:122},L={eb:8,vc:9,jc:10,ib:13,rc:16,Wb:17,Ub:18,Td:19,Va:20,Uc:27,tc:32,Wd:33,Vd:34,Tc:35,pd:36,tb:37,zc:38,Ya:39,md:39,Yb:40,jd:44,Xd:44,qd:45,Sc:46,ld:46,od:47,ZERO:48,ONE:49,xc:50,wc:51,fc:52,ec:53,sc:54,qc:55,Zb:56,kc:57,dc:59,cc:61,Ta:65,cb:66,fb:67,jb:68,E:69,kb:70,lb:71,mb:72,nb:73,ob:74,rb:75,sb:76,vb:77,wb:78,xb:79,yb:80,
Q:81,Ab:82,Cb:83,Db:84,Eb:85,Fb:86,Gb:87,Hb:88,Ib:89,Za:90,gb:91,kd:91,hd:92,$d:93,nd:93,ud:96,Ld:96,gd:96,vd:97,Jd:97,wd:98,Id:98,xd:99,Od:99,yd:100,Md:100,zd:101,Fd:101,Ad:102,Qd:102,Bd:103,Kd:103,Cd:104,Sd:104,Dd:105,Pd:105,Nd:106,Ed:107,Rd:109,Gd:110,Hd:111,Vc:112,Zc:113,$c:114,ad:115,bd:116,cd:117,dd:118,ed:119,fd:120,Wc:121,Xc:122,Yc:123,lc:144,oc:145,bc:173,pc:186,$b:187,Rc:188,Xb:189,Ud:190,be:191,Pc:192,rd:219,Qc:220,Zd:221,Yd:222,ac:224,sd:901,ce:1E3},ab={},bb=(ab[L.dc]=L.pc,ab[L.cc]=L.$b,
ab[L.bc]=L.Xb,ab[L.ac]=L.gb,ab),cb={tb:1,Ya:2,td:3},N={},db=(N[L.eb]="\b",N[L.vc]="\t",N[L.jc]="\n",N[L.ib]="\r",N[L.tc]=" ",N[L.ZERO]="0",N[L.ONE]="1",N[L.xc]="2",N[L.wc]="3",N[L.fc]="4",N[L.ec]="5",N[L.sc]="6",N[L.qc]="7",N[L.Zb]="8",N[L.kc]="9",N[L.Ta]="A",N[L.cb]="B",N[L.fb]="C",N[L.jb]="D",N[L.E]="E",N[L.kb]="F",N[L.lb]="G",N[L.mb]="H",N[L.nb]="I",N[L.ob]="J",N[L.rb]="K",N[L.sb]="L",N[L.vb]="M",N[L.wb]="N",N[L.xb]="O",N[L.yb]="P",N[L.Q]="Q",N[L.Ab]="R",N[L.Cb]="S",N[L.Db]="T",N[L.Eb]="U",N[L.Fb]=
"V",N[L.Gb]="W",N[L.Hb]="X",N[L.Ib]="Y",N[L.Za]="Z",N[L.tb]="Left",N[L.Ya]="Right",N),Ka=["","moz","ms","webkit"],eb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",
darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",
fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",
navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},J={Ua:void 0,ya:"PCjs.localStorage"};E.WebIO=H;
function O(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;H.call(this,a==b);this.M=a;this.V=b;D[this.M]||(D[this.M]={});D[this.M][this.V]&&this.s("warning: machine configuration contains multiple '%s' devices\n",this.V);D[this.M][this.V]=this;this.id=this.M==this.V?this.M:this.M+"."+this.V;ra.push(this);this.L=P(this,this.M);this.ready=!0;fb(this,c,d);this.yc={};this.ub=[]}y(O,H);
function fb(a,b,c){c=b.overrides||c;if(c.length){var d,e=Ea;if(!e){e={};if(window){d||(d=window.location.search.slice(1));for(var f,g=/\+/g,h=/([^&=]+)=?([^&]*)/g;f=h.exec(d);)e[decodeURIComponent(f[1].replace(g," ")).trim()]=decodeURIComponent(f[2].replace(g," ")).trim()}Ea=e}d=e;for(var k in d)if(0<=c.indexOf(k)){e=d[k];f=void 0;var m;g=void 0;h=e;var l=10;if(h){l||(l=10);var r=0<h.indexOf(",");r&&(h=h.replace(/,/g,""));var n=m=h.charAt(0);"#"==m?(l=8,m=""):"$"==m&&(l=16,m="");n!=m?h=h.substr(1):
(n=m=h.substr(0,2),"0b"==m&&r||"^B"==m?(l=2,m=""):"0o"==m||"^O"==m?(l=8,m=""):"^D"==m?(l=10,m=""):"0x"==m&&(l=16,m=""),n!=m&&(h=h.substr(2)));n=m=h.slice(-1);"Y"==m||"y"==m?(l=2,m=""):"."==m?(l=10,m=""):"H"==m||"h"==m?(l=16,m=""):"K"==m?m="000":"M"==m?m="000000":"G"==m&&(m="000000000");n!=m&&(h=h.slice(0,-1)+m);n=0;10>=l&&(m=h.match(/(-?[0-9]+)B([0-9]*)$/))&&(h=m[1],n=35-((m[2]||35)&255));(l&&10!=l?16==l?null===h.match(/^-?[0-9a-f]+$/i):8==l?null===h.match(/^-?[0-7]+$/):2!=l||null===h.match(/^-?[01]+$/):
null===h.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(h,l))||(n&&(0>f&&(f+=Math.pow(2,36)),f=0<n?f*Math.pow(2,n):Math.trunc(f/Math.pow(2,-n))),g=f)}f=g;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[k]=f;a.s("overriding %s property '%s' with %s\n",a.V,k,e)}}a.J=b;Ia(a,b.bindings);b=void 0===b?{}:b;a.version=3;if(a.version){c="";var t;a.M!=a.V&&(t=P(a,a.M).version)&&t!=a.version&&(c="Machine");c||(t=b.version)&&t>a.version&&(c="Config");c&&(t=a.X("%s Device version (%3.2f) incompatible with %s version (%3.2f)",
b.ge,a.version,c,t),a.error("%s\n\nClearing your browser's cache may resolve the issue.",t))}}function gb(a,b){var c;try{var d=D[a.M];if(d)for(c in d){var e=d[c];if(e.V!=e.M&&!b(e))return!1}return!0}catch(f){a.s("error while enumerating device '%s': %s\n",c,f.message)}return!1}O.prototype.Ba=function(a,b){b=void 0===b?!1:b;if(a){var c=H.prototype.Ba.call(this,a,b);if(void 0===c&&b){b=D[this.M];for(var d in b)if(c=b[d].S[a])break;c||(c=null);this.S[a]=c}}return c};
function P(a,b,c){var d=b,e=a.M,f=e.indexOf(".");0<f&&(e=e.substr(0,f),b=b.substr(f+1));b=(f=D[e])&&f[b]||null;if(!b){for(f=0;f<ra.length;f++)if(ra[f].id===d){b=ra[f];break}if(!b&&(void 0===c||c))throw Error(a.X('no "%s" device',d));}return b}function Q(a,b,c){var d=null,e=D[a.M];if(e)for(var f in e)if(e[f].J["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.X("no %s device",b));return d}function hb(a){return a==a.L&&a.ready?gb(a,function(b){return hb(b)}):a.ready}
function ib(a,b){b=void 0===b?a.ready:b;a.ready=b;if(hb(a)){for(;b=a.ub.pop();)b();a!=a.L&&ib(a.L)}}function jb(a,b){if(hb(a))return b(),!0;a.ub.push(b);return!1}
O.prototype.s=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&K(this,a)&&(void 0===this.fa&&(this.fa=Q(this,"Debugger",!1)),this.L.ga&1&&(void 0===this.da&&(this.da=Q(this,"CPU")),this.da))?(a=b.shift(),H.prototype.s.call(this,"%#06x: %s.%s\n",this.da.Qa,this.V,this.X.apply(this,[a].concat(q(b))).trim())):H.prototype.s.call.apply(H.prototype.s,[this,a].concat(q(b)))};function kb(a,b){(a=D[a.M])&&delete a[b]}O.prototype.Pb=function(a,b){(a=this.yc[a])&&a.set&&a.set(b)};E.Device=O;
function lb(a,b,c){O.call(this,a,b,c);this.ga=2097152;this.K=this.O=null;this.time=Q(this,"Time");this.L=Q(this,"Machine");this.ba=I(this,"drag",!1);this.Y=I(this,"scroll",!1);this.aa=I(this,"hexagonal",!1);this.u=I(this,"releaseDelay",0);this.v=!1;a=this.J.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.j[f]={keys:g,grid:e,
state:0}}}this.R=[];this.T=[];this.m=this.U=null;(a=this.S[mb])&&nb(this,a,this.Ba(c.focusBinding,!0),this.J.location);this.qa()}y(lb,O);function ob(a,b){a.O=b}function pb(a,b,c){for(var d=0;d<a.R.length;d++){var e=a.R[d];e.id===b&&e.Nb(b,c)}}
function nb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.Nc=d[0]||0;e.Oc=d[1]||0;e.Aa=d[2]||b.clientWidth;e.La=d[3]||b.clientHeight;e.Ma=d[4]||1;e.Ra=d[5]||1;e.Ec=d[6]||b.naturalWidth||e.Aa;e.Gc=d[7]||b.naturalHeight||e.La;e.Sb=d[8]||0;e.Tb=d[9]||0;e.Dc=d[10]||0;e.Fc=d[11]||0;a.h?(e.Oa=a.h.length,e.Ca=a.h[0].length):(e.Ca=e.Ma,e.Oa=e.Ra,e.Ma=e.Ra=0);e.Jb=e.Aa/(e.Ca+e.Ca*e.Ma)|0;e.Kb=e.La/(e.Oa+e.Oa*e.Ra)|0;e.Cc=e.Jb*e.Ma|0;e.Lb=e.Kb*e.Ra|0;e.Ga=e.Sa=-1;qb(a,b,e);rb(a,b,e);a.time&&
a.u&&(a.$=sb(a.time,"timerInputRelease",function(){0>e.Ga&&0>e.Sa&&tb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.u&&(a.ca=sb(a.time,"timerKeyRelease",function(){ub(a)})),a.H=0,a.N="",a.I=[],d=b,c&&(d=c,a.m||"BUTTON"!=c.nodeName||(d=document,a.m=c,vb(a,b),a.U=b)),vb(a,d),a.m||(a.m=d)}function wb(a){a.u?xb(a.time,a.ca,a.u):ub(a)}
function vb(a,b){function c(e,f,g){var h=document.activeElement;a.s(5242880,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.m&&e!=a.m&&e!=a.U?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=yb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=yb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=yb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function qb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.v){var e=a.m;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||R(a,b,zb,d,c)}});b.addEventListener("mousemove",function(d){a.v||R(a,b,Ab,d,c)});b.addEventListener("mouseup",function(d){a.v||d.button||R(a,b,S,d,c)});b.addEventListener("mouseout",function(d){a.v||(0>c.Ga?R(a,b,Ab,d,c):R(a,b,S,d,c))})}
function rb(a,b,c){b.addEventListener("touchstart",function(d){a.Y&&(a.v=!0);R(a,b,zb,d,c)});b.addEventListener("touchmove",function(d){R(a,b,Ab,d,c)});b.addEventListener("touchend",function(d){R(a,b,S,d,c)})}
function yb(a,b,c,d){if(void 0!=c){var e=bb[b]||b;var f=db[b];var g=Bb[e];d=d&&d.location==cb.Ya;g&Cb&&d&&(g>>=1);g&&(g&Db&&(c=!(a.g&g)),a.g=c?a.g|g:a.g&~g,pb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=$a.Ta&&b<=$a.Za?a.g&(Eb|Fb)||(a.g|=Fb,pb(a,L.Va,!0)):b>=$a.a&&b<=$a.z&&a.g&Fb&&(a.g&=~Fb,pb(a,L.Va,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(g=a.h[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.H?16>a.I.length&&a.I.push(b):(a.H=1,a.N=f,tb(a,d,e),pb(a,
f,!0),wb(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(g=b[e],0<=a.j[g].keys.indexOf(f))return pb(a,g,c),a.j[g].state=c?1:0,!0}return!1}function ub(a){1==a.H?(a.H++,pb(a,a.N,!1),a.N="",tb(a,-1,-1),wb(a)):(a.H=0,a.I.length&&yb(a,a.I.shift()))}lb.prototype.qa=function(){this.g=0;this.W=this.Z=-1};
function R(a,b,c,d,e){var f=-1,g=-1,h=!1,k=-1,m=-1;if(c<S){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,m=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(k=d.clientX,m=d.clientY);var l=d.target.getBoundingClientRect();k-=l.left;m-=l.top;k=e.Ec/b.offsetWidth*k|0;m=e.Gc/b.offsetHeight*m|0;var r=k-e.Nc;var n=m-e.Oc;var t=l=!1;var w=k>=e.Sb&&k<e.Sb+e.Dc&&m>=e.Tb&&m<e.Tb+e.Fc;if(0<=r&&r<e.Aa&&0<=n+e.Lb||w)if(h||a.Y||d.preventDefault(),0<=r&&r<e.Aa&&0<=
n&&n<e.La){t=!0;d=e.Aa/e.Ca|0;var v=e.La/e.Oa|0,A=r/d|0,x=n/v|0;!a.aa||x&1||(r-=d>>1,A=r/d|0,A==e.Ca-1&&(r=-1));v=x*v+(e.Lb>>1);r-=A*d+(e.Cc>>1);n-=v;0<=r&&r<e.Jb&&0<=n&&n<e.Kb&&(f=A,g=x,l=!0)}}r=r||0;n=n||0;d=b.offsetWidth;b=b.offsetHeight;if(c==zb||c==S)for(A=0;A<a.T.length;A++)x=a.T[A],c==S?x.Nb(x.id,!1):(v=n/(b/x.ie|0)|0,(r/(d/x.he|0)|0)==x.we&&v==x.xe&&x.Nb(x.id,!0));if(!h)if(c==zb)e.Ga=k,e.Sa=m,t?(tb(a,f,g),l&&a.u&&xb(a.time,a.$,a.u,!0)):w&&a.L.ia();else if(c==Ab)0<=e.Ga&&0<=e.Sa&&a.ba?tb(a,
f,g):a.O&&a.O(f,g);else if(c==S){if(c=a.u)c=a.time,f=a.$,c=c.g&&0<f&&f<=c.h.length?0<=c.h[f-1].ha:!1;c||tb(a,-1,-1);e.Ga=e.Sa=-1}else a.s("unrecognized action: %d\n",c)}function tb(a,b,c){if(b!=a.W||c!=a.Z)a.W=b,a.Z=c,a.K&&a.K(b,c)}var zb=1,Ab=2,S=3,mb="surface",Eb=3,Cb=170,Fb=512,Db=3584,T={},Bb=(T[L.rc]=2,T[L.Wb]=8,T[L.Ub]=32,T[L.gb]=128,T[L.Va]=Fb,T[L.lc]=1024,T[L.oc]=2048,T);E.Input=lb;
function Gb(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.S[Hb];if(!a)throw Error("LED "+this.J.S[Hb]+" binding for '"+Hb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.va=La(this,Hb)+".canvas";b.setAttribute("id",this.va);this.Wa=a;this.type=Oa(I(this,"type",Ib,Jb),Kb,Lb);this.m=Mb[this.type][0];this.I=Mb[this.type][1];this.width=I(this,"width",
this.m);this.height=I(this,"height",this.I);this.u=I(this,"cols",1);this.R=this.u+I(this,"colsExtra",0);this.ba=I(this,"rows",1);this.W=this.ba+I(this,"rowsExtra",0);this.ea=this.width*this.u;this.Z=this.height*this.ba;this.H=Nb("black",0);this.j=Ob(this.J.color)||this.H;this.na=Nb(this.j,1,.25);this.ma=Nb(this.j,1,2);this.v=Ob(this.J.backgroundColor);this.oa=I(this,"fixed",!1);this.oa||(b.style.width="100%",b.style.height="auto");this.la=I(this,"hexagonal",!1);this.sa=I(this,"highlight",!0);this.Y=
I(this,"persistent",this.type<Lb);b.setAttribute("width",this.ea.toString());b.setAttribute("height",this.Z.toString());b.style.backgroundColor=this.H;a.appendChild(b);this.ja=b.getContext("2d");if(this.K=document.createElement("canvas"))this.K.width=this.ca=this.m*this.u,this.K.height=this.N=this.I*this.ba,this.h=this.K.getContext("2d");this.wa=(this.W+1)*this.R*4;this.g=Array(this.wa);this.Ia=this.u<this.R?4*(this.R-this.u):0;this.T=this.U=!1;this.O=this.aa=0;this.$=-1;var d=this;this.time=Q(this,
"Time");Pb(this.time,function(e,f){Qb(d,!1,e,f)});Rb(d)}y(Gb,O);function Rb(a){for(var b=a.g,c=0;c<b.length;c+=4){var d=a,e=b,f=c;e[f]=d.type<Lb?Sb:" ";e[f+1]=d.j==d.H?null:d.j;e[f+2]=0;e[f+3]=Tb}a.T=a.U=!0;Qb(a,!0)}function Ub(a){a.v?(a.h.fillStyle=a.v,a.h.fillRect(0,0,a.ca,a.N)):a.h.clearRect(0,0,a.ca,a.N)}
function Qb(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.T||b){if(a.type<Lb){d=0;if(!a.Y||b)Ub(a);else if(a.O){d=a.u-a.O;var e=a.m*d;a.h.drawImage(a.K,a.m*a.O,0,e,a.N,0,0,e,a.N)}for(var f=e=0;f<a.W;f++){for(var g=0;g<a.u;g++){var h=a.g[e],k=a.g[e+1]||a.H,m=a.sa&&e==a.$;if(a.g[e+3]&Tb||m||b){if(g>=d)a:{var l=a,r=h;h=k;var n=g;k=f;var t=m;n=void 0===n?0:n;k=void 0===k?0:k;t=void 0===t?!1:t;var w=0;if(l.la&&!(k&1)&&(w=l.m>>1,n==l.u-1))break a;if(h&&h!=l.j){t=t?Nb(h,1,2):h;var v=
Nb(h,1,.25)}else t=t?l.ma:l.j,v=l.na;h=!1;r=r?t:v;t==l.H&&(r=l.v,h=!0);t=n*l.m+w;v=k*l.I;l.Y&&(n=n*l.m+w,k*=l.I,l.v?(l.h.fillStyle=l.v,l.h.fillRect(n,k,l.m,l.I)):l.h.clearRect(n,k,l.m,l.I));l.h.fillStyle=r;k=Vb[l.type];3==k.length?(l.h.beginPath(),l.h.arc(t+k[0],v+k[1],k[2],0,2*Math.PI),h?(l.h.globalCompositeOperation="destination-out",l.h.fill(),l.h.globalCompositeOperation="source-over"):l.h.fill()):l.h.fillRect(t+k[0],v+k[1],k[2],k[3])}a.g[e+3]=m?a.g[e+3]|Tb:a.g[e+3]&~Tb}e+=4}e+=a.Ia}a.O=0}else{b=
"";for(d=0;d<a.g.length;d+=4)b+=a.g[d]||" ",a.g[d+3]&Wb&&(b+=".");Ub(a);for(f=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;g=a;m=e;l=f;m=void 0===m?0:m;l=void 0===l?0:l;if(k=Xb[k])for(h=0;h<k.length;h++)if(n=g,w=Yb[k[h]]){r=(void 0===m?0:m)*n.m;t=(void 0===l?0:l)*n.I;n.h.fillStyle=n.j;n.h.beginPath();if(3==w.length)n.h.arc(r+w[0],t+w[1],w[2],0,2*Math.PI);else for(v=0;v<w.length;v+=2)v?n.h.lineTo(r+w[v],t+w[v+1]):n.h.moveTo(r+w[v],t+w[v+1]);n.h.closePath();n.h.fill()}if(++e==a.u&&(e=0,++f==a.W))break}}a.ja.globalCompositeOperation=
a.v&&a.j!=a.H?"source-over":"copy";a.ja.drawImage(a.K,0,0,a.ca,a.N,0,0,a.ea,a.Z);a.T=!1;a.$=-1}else a.Y||a.U||(!c||!a.aa||c-a.aa>=(1E3/d|0))&&Rb(a);a.U=!1;c&&(a.aa=c)}function Ob(a){return(a=a||void 0)&&eb[a]||a}
function Nb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=eb[a]||a;var e=16;var f=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);f||(e=10,f=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(f){var g;for(g=1;g<f.length;g++)d[g-1]=Number.parseInt(f[g],e);d.length=g-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)f=Math.round(d[e]*c),f=0>f?0:255<f?255:f,a+=f+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Gb.prototype.pa=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.j&&c==this.v&&a&&a.length==this.g.length){this.g=a;for(b=0;b<=this.g.length-4;b+=4)this.g[b+1]==this.H&&(this.g[b+1]=null);Qb(this,!0);return!0}return!1};Gb.prototype.ra=function(a){this.g&&(a.push(this.j),a.push(this.v),a.push(this.g))};
function Zb(a,b,c,d,e){var f=!1;e=(void 0===e?0:e)&$b;b=4*(c*a.R+b);if(b<=a.g.length-4){if(a.g[b]!==d||(a.g[b+3]&$b)!==e)a.g[b]=d,a.g[b+3]=a.g[b+3]&~$b|e|Tb,a.T=f=!0;a.$=b;a.U=!0;a.O=0}return f}
var Kb=0,Ib=1,Lb=3,Jb={small:Kb,round:Ib,square:2,digit:Lb},Hb="container",Sb=0,$b=129,Wb=1,Tb=128,ac={},Vb=(ac[Kb]=[4,4,4],ac[Ib]=[16,16,14],ac[2]=[2,2,28,28],ac),Mb=[[8,8],[32,32],[32,32],[96,128]],Yb={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},Xb={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};E.LED=Gb;
function bc(a,b,c){O.call(this,a,b,c);this.oa=I(this,"cyclesMinimum",1E5);this.Wa=I(this,"cyclesMaximum",1E9);this.sa=Oa(I(this,"cyclesPerSecond",1E6),this.oa,this.Wa);this.ba=60;this.W=0;this.Y=1E3/this.ba;this.uc=I(this,"updatesPerSecond",2)||2;this.nc=1E3/this.uc;this.Ia=0;this.Ac=I(this,"timeLock",!0);this.ma=this.R=0;this.la=this.H=1;this.wa=this.K=this.sa/1E4/100;this.ea=[];this.N=[];this.h=[];this.ja=[];this.va=this.g=this.ca=this.I=!1;this.O=this.m=0;a=Ja("requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.Y}this.zb=window[a].bind(window,this.Kc.bind(this),d);this.mc=window[Ja("cancelAnimationFrame")||"clearTimeout"].bind(window);this.aa=this.$=this.u=this.j=this.na=0;cc(this)||dc(this,this.la)}y(bc,O);function Pb(a,b){a.ea.push(b)}p=bc.prototype;
p.za=function(a,b){var c=this;switch(a){case ec:b.onclick=function(){fc(c)&&(c.g?U(c):c.start())};break;case gc:b.onclick=function(){dc(c,c.H<<1);hc(c,ic(c.K))};break;case jc:b.onclick=function(){kc(c)};break;case lc:b.addEventListener("mousedown",function(){c.I=!0}),b.addEventListener("mouseup",function(){cc(c);c.I=!1}),b.addEventListener("mousemove",function(){c.I&&cc(c)}),b.addEventListener("change",function(){c.I=!0;cc(c);c.I=!1})}O.prototype.za.call(this,a,b)};
function sb(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,Bc:c,Na:d,ha:-1});0<=d&&xb(a,e,d);return e}
function mc(a,b,c,d){var e=0,f=a.K,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.s(262144,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.Y&&(1<a.H&&(a.H>>=1,a.s(549755813888,"frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.Y,a.H)),e=d));a.R=f;a.ma=f/a.wa;b=a.ma/a.H;a.na=g/b/a.ba+1E-8;a.s(262144,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.na,g,b,a.ba);return e}
function nc(a,b){a.$=a.u=b;if(!a.N.length)return a.u=0,a.$;for(var c=0;0<a.u;){if(c<a.N.length){var d=a.N[c++];b=d.Lc.call(d,b)||1}else c=b=0;a.u-=b}return a.$-a.u}function oc(a,b){var c=Date.now();b()&&(a.Z+=Date.now()-c)}function pc(a,b){b=void 0===b?a.$-a.u:b;if(!a.g){if(a.j)for(var c=0;c<a.N.length;c++){var d=a.N[c];d.Qb.call(d)}a.j=b}a.j-=b;1>a.j&&(a.ca=!0);a.aa+=b;a.$=a.u=0;a.g||(a.aa=0);return b}
function qc(a,b){b=void 0===b?0:b;if(b){var c=b;a.j+=b}else for(c=a.j,1>c&&(c=a.j+=a.na),0>c&&(a.s(262144,"warning: cycle count dropped below zero: %f\n",c),c=a.j=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.ha)&&c>d.ha&&(c=d.ha)}return c}function ic(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function fc(a){return a.va?!0:(a.s("not powered\n"),!1)}
function rc(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.ha||(d.ha-=b,0>=d.ha&&(d.ha=-1,d.Bc(),0<=d.Na&&xb(a,c,d.Na)))}}p.ia=function(a){this.va=a;void 0===this.fa&&(this.fa=Q(this,"Debugger",!1))};function kc(a,b){fc(a)&&(a.g?a.s("already running\n"):a.m?U(a):sc(a,b))}
p.Kc=function(a){a=void 0===a?Date.now():a;this.O=0;if(this.g){if(this.W){var b=a-this.W;1>b&&(b=16.67);this.ba=1E3/b}this.W=a;a=Date.now();this.T&&(b=a-this.U-this.Y,b>this.Y&&(this.v+=b,this.s(549755813888,"browser throttling detected, compensating by %5.3fms\n",b)));this.U=a;this.v||(this.v=a);this.Z=0;try{this.ca=!1;do rc(this,pc(this,nc(this,qc(this))));while(this.g&&!this.ca)}catch(c){this.s("%s\n",c.message),U(this)}this.T=Date.now();this.Z&&(this.v+=this.Z,this.U+=this.Z);this.U+=mc(this,
this.aa,this.T-this.v,this.T-this.U);this.T-this.Ia>=this.nc&&this.update();for(a=0;a<this.ea.length;a++)this.ea[a](this.W,this.ba);this.O=this.zb()}};function dc(a,b){if(void 0!==b){if(1>b||!a.I&&0<a.R&&a.R<.9*a.K)b=a.la;a.H=b;b=a.wa*a.H;a.K!=b&&(a.K=b,hc(a,ic(a.K)))}a.v=a.T=0;a.j=a.aa=0;mc(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.Na&&xb(a,b,c.Na,!0)}}function cc(a){var b=a.S[lc];return b?(dc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Wa-a.oa)+a.oa)/a.sa|0),!0):!1}
function xb(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.ha)&&(c=Math.ceil(a.sa*(a.Ac?a.la:a.ma)/1E3*(void 0===c?1E3:c)),a.g&&(c+=pc(a)),b.ha=c)}p.start=function(){if(this.g||this.m)return!1;this.g=!0;this.v=this.T=this.W=0;this.update(!0);this.O=this.zb();return!0};function sc(a,b){b=void 0===b?1:b;a.g||(b&&!a.m&&(a.m=b),a.m&&(a.m--,rc(a,pc(a,nc(a,qc(a,1)))),a.update(!1),a.m&&setTimeout(function(){sc(a,0)},0)))}
function U(a){return a.g?(a.g=!1,pc(a),a.O&&(a.mc(a.O),a.O=0),a.update(!0),!0):a.m?(a.m=0,a.update(!0),!0):!1}p.update=function(a){a&&this.s(this.g?"started with %s target\n":"stopped\n",ic(this.K));M(this,ec,this.g?"Halt":"Run");M(this,jc,this.m?"Stop":"Step");this.I||(this.s(262144,"getSpeedCurrent(%5.3fhz)\n",1E6*this.R),hc(this,this.g&&this.R?ic(this.R):"Stopped"));for(var b=0;b<this.ja.length;b++){var c=this.ja[b];c.Ic.call(c,void 0!=a)}this.Ia=Date.now();this.ca=!0};
function hc(a,b){M(a,tc,b);M(a,gc,b)}var ec="run",gc="setSpeed",tc="speed",jc="step",lc="throttle";E.Time=bc;
function uc(a,b,c){O.call(this,a,b,c);this.type="static"==this.J.type?vc:wc;this.v=this.J.addrWidth||16;this.j=Math.pow(2,this.v);this.I=this.j-1|0;this.blockSize=this.J.blockSize||(16<this.v?4096:1024);this.blockSize>this.j&&(this.blockSize=this.j);this.K=this.j/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.m=(1<<this.h)-1;this.H=this.J.dataWidth||8;this.g=Array(this.K);this.u=0;a=new V(a,b+"[NONE]",{size:this.blockSize,bus:this.V});for(b=0;b<this.j;b+=this.blockSize)xc(this,b,this.blockSize,
W.NONE,a);a=this.u;this.u+=this.type;a&&this.u||(this.Da=this.hc,this.Ea=this.Fa)}y(uc,O);
function xc(a,b,c,d,e){for(var f=b>>>a.h;0<c&&f<a.g.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var k=a.g[f];if(b!=g||h!=a.blockSize||k&&k.type!=W.NONE)break;var m=k=void 0,l=b,r=a.v,n=16;r=void 0===r?0:r;k=void 0===k?0:k;var t="",w="",v=-1;n||(n=a.N||10);r&&(v=Math.ceil(r/Math.log2(n)));if(void 0==m)switch(n){case 8:m="0o";break;case 16:m="0x";break;case 10:w=".";default:m=""}isNaN(l)||"number"!=typeof l?(l=void 0,m=w=""):(0>l&&-1<l&&(l=-1),r&&(0>l&&(l+=Math.pow(2,r)),l>=Math.pow(2,
r)&&(v=Math.ceil(Math.log(l)/Math.log(n)))));for(r=k||-1;v--;){r||(t=","+t,r=k);if(void 0==l){if(t="?"+t,0>v)break}else{var A=l%n;l=Math.trunc(l/n);A+=0<=A&&9>=A?48:55;t=String.fromCharCode(A)+t;if(!l&&0>v)break}r--}k=a.V+"["+(m+t+w)+"]";b=e?e.size==a.blockSize?e:new V(a.M,k,{type:d,Ka:b,size:h,bus:a.V}):new V(a.M,k,{type:d,Ka:b,size:h,bus:a.V});a.g[f]=b;b=g+a.blockSize;c-=h;f++}}p=uc.prototype;p.je=function(a,b){this.fa&&this.fa.s(4,"bus fault (%d) at %n\n",b,a)};
p.ia=function(){void 0===this.fa&&(this.fa=Q(this,"Debugger",!1))};p.qa=function(){};p.$a=function(a){return a&&this.pa(a)?!0:!1};p.ab=function(a){this.ra(a)};p.pa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==wc||c.type&W.Ja)&&c.pa){var d=a.shift();if(!c.pa(d))return!1}}return!0};p.ra=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==wc||c.type&W.Ja)&&c.ra){var d=[];c.ra(d);a.push(d)}}};p.xa=function(a){return this.g[a>>>this.h].xa(a&this.m)};
p.hc=function(a){return this.g[a>>>this.h].Da(a&this.m)};p.bb=function(a,b){this.g[a>>>this.h].bb(a&this.m,b)};p.Fa=function(a,b){this.g[a>>>this.h].Ea(a&this.m,b)};var vc=0,wc=1;E.Bus=uc;
function V(a,b,c){O.call(this,a,b,c);this.Ka=this.J.addr;this.size=this.J.size;this.type=this.J.type||W.NONE;this.m=(a=this.J.bus)?P(this,a):Q(this,a="Bus");if(!this.m)throw Error(this.X("unable to find bus '%s'",a));this.v=this.m.H;this.K=Math.pow(2,this.v)-1;this.u=this.I=!1;this.values=this.j=null;a=this.pb;b=this.Fa;if(this.m.type==vc){b=this.Mc;if(c=8==this.v)c=P(this,this.M),c=!1!==(c&&c.J&&c.J.ArrayBuffer||this.J.ArrayBuffer);c&&(this.I=!0)}switch(this.type){case W.NONE:this.Da=this.Jc;this.Ea=
this.Rb;break;case W.Bb:this.Da=a;this.Ea=this.Rb;break;case W.Ja:this.Da=a,this.Ea=b}yc(this,this.J.values);zc(this)}y(V,O);function yc(a,b){"string"==typeof b?(ib(a,!1),Pa(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);yc(a,g.values)}catch(h){a.s("error (%s) parsing resource: %s\n",h.message,c)}ib(a,!0)}else a.s("error (%d) loading resource: %s\n",f,c)})):a.J.values=b}
function zc(a,b){if(a.type>W.NONE&&(a.I?(a.j=new ArrayBuffer(a.size),new DataView(a.j,0,a.size),a.values=new Uint8Array(a.j,0,a.size),new Uint16Array(a.j,0,a.size>>1),new Int32Array(a.j,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}p=V.prototype;
p.qa=function(){if(this.J.values)a:{var a=this.m,b=this.Ka,c=this.size,d=this.J.values,e=0,f=b&a.m;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var g=a.g[b++];if(!g)break a;for(;0<c&&f<g.size;)g.Fa(f++,d[e++]),c--;f=0}}else this.type&W.Ja&&this.values&&this.values.fill(0)};p.Jc=function(){return this.K};p.xa=function(a){return this.values?this.values[a]:0};p.pb=function(a){return this.values[a]};p.Rb=function(){};p.bb=function(a,b){this.values&&(this.values[a]=b)};
p.Fa=function(a,b){this.values[a]=b};p.Mc=function(a,b){this.values[a]=b;this.u=!0;this.Ea=this.Fa};p.pa=function(a){if(a){var b=a.shift();if(this.V==b){this.u=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}zc(this,a)}return!0}}return!1};
p.ra=function(a){a.push(this.V);a.push(this.u);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var W={NONE:1,Bb:2,Ja:4,ae:14,ee:12};E.Memory=V;
function Ac(a,b,c){c.type=W.Bb;V.call(this,a,b,c);xc(this.m,this.J.addr,this.J.size,this.J.type,this);jb(this,this.qa.bind(this));this.da=this.fa=void 0;if(E.LED&&this.S[Bc]){var d=this;this.h=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.H=this.values.length/this.h|0;this.g=new Gb(a,b+"LEDs",{"class":"LED",bindings:{container:La(this,Bc)},type:Ib,cols:this.h,rows:this.H,color:I(this,"colorROM","green"),backgroundColor:I(this,"backgroundColorROM","black"),persistent:!0}),Rb(this.g);
this.N=new lb(a,b+"Input",{"class":"Input",location:[0,0,this.g.ea,this.g.Z,this.h,this.H],bindings:{surface:La(this,Bc)}});this.O=Ma(this)||"";ob(this.N,function(e,f){if(d.da){var g=d.O;0<=e&&0<=f&&(e=f*d.h+e,g=Cc(d.da,d.Ka+e,d.values[e]));M(d,Na,g)}})}}y(Ac,V);
Ac.prototype.pa=function(a){var b=!0,c=a.shift();if(c&&this.g){var d=c.length;this.g.g.length==d?(this.g.g=c,Qb(this.g,!0)):(this.s("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.s("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};Ac.prototype.ia=function(){void 0===this.da&&(this.da=Q(this,"CPU"));void 0===this.fa&&(this.fa=Q(this,"Debugger",!1))};
Ac.prototype.pb=function(a){this.g&&Zb(this.g,a%this.h,a/this.h|0,1,Tb);return this.values[a]};Ac.prototype.ra=function(a){this.g&&(a.push(this.g.g),a.push(this.values))};var Bc="array",Na="cellDesc";E.ROM=Ac;function Dc(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.fa=void 0;this.h=this.Qa=0;this.time=Q(this,"Time");this.time.N.push(this);this.time.ja.push(this);this.Z=this.v=0}y(Dc,O);p=Dc.prototype;p.abort=function(a){this.h=this.Qa;this.s("%s\n",a.message);U(this.time)};p.Mb=function(){};
p.Lc=function(a){this.Z=this.v=a=void 0===a?0:a;try{this.Mb(a)}catch(b){this.abort(b)}return this.Ob()};p.Qb=function(){this.Z-=this.v;this.v=0};p.Ob=function(){return this.Z-this.v};function X(a,b,c){O.call(this,a.M,b);this.da=a;this.name=b;this.l=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];if(!c){b=[];c="reg"+this.name;b.push(c);a.na[c]=[this,-1];for(var d=0;d<this.l.length;d++)c=this.X("reg%s-%02d",this.name,d),b.push(c),a.na[c]=[this,d];Ia(a,b)}}y(X,O);p=X.prototype;
p.add=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]+b.l[f]+e,e=0,this.l[f]>=d&&(this.l[f]-=d,e=1);e&&(this.da.H=!0);Ec(this,c)};p.get=function(){return this.l};function Fc(a,b,c){c=void 0===c?[0,15]:c;for(var d=0;d<a.l.length;d++)a.l[d]=0;d=c[0];for(c=c[1];d<=c;d++)a.l[d]=b&15,b>>>=4;return a}p.move=function(a,b,c){for(var d=0,e=b[0],f=b[1];e<=f;e++)this.l[e]=a.l[e]+d,d=0,this.l[e]>=c&&(this.l[e]-=c,d=1);Ec(a,b)};
p.set=function(a){if(a&&a.length==this.l.length)for(var b=0;b<this.l.length;b++)this.l[b]=a[b]};p.store=function(a){for(var b=0,c=this.l.length;b<c;b++)this.l[b]=a.l[b]};p.sub=function(a,b,c,d){for(var e=0,f=c[0],g=c[1];f<=g;f++)this.l[f]=a.l[f]-b.l[f]-e,e=0,0>this.l[f]&&(this.l[f]+=d,e=1);e&&(this.da.H=!0);Ec(this,c)};p.toString=function(a){a=void 0===a?!1:a;var b=this.V+"=";a&&3>b.length&&(b+=" ");for(var c=this.l.length-1;0<=c;c--)b=a?b+xa[this.l[c]]:b+(ya[this.l[c]]+(c%4?"":" "));return b};
function Ec(a,b){a.da.u=a.l[b[0]];b[0]<b[1]&&(a.da.u|=a.l[b[0]+1]<<4)}
function Gc(a,b,c){Dc.call(this,a,b,c);this.type=Number.parseInt(I(this,"type","1501").slice(-4),10);this.na={};this.g=Array(4);for(a=0;4>a;a++)this.g[a]=new X(this,String.fromCharCode(65+a));this.U=this.g[0];this.$=this.g[1];this.sa=this.g[2];this.wa=this.g[3];this.R=Array(8);for(a=0;8>a;a++)this.R[a]=new X(this,"X"+a);this.W=Array(8);for(a=0;8>a;a++)this.W[a]=new X(this,"Y"+a);this.oa=new X(this,"Supp",!0);this.ba=new X(this,"Temp",!0);this.O=10;this.H=!1;this.aa=this.u=this.K=0;this.m=[-1,-1,-1];
this.va=P(this,this.J.input);this.va.K=this.ic.bind(this);this.j=P(this,this.J.output,!1);this.N=Q(this,"Bus");this.I=Q(this,"ROM");this.la=this.ma=this.Y=void 0;this.ja=this.ca=-1;this.T={};this.ea=Hc;a=this.Hc.bind(this);b=Va.hb;this.L.Ha[b]||(this.L.Ha[b]=[]);this.L.Ha[b].push(a)}y(Gc,Dc);function Ic(a,b){a.T[b]&&(a.T[b]=!1,a.s("break on %s\n",Jc[b]),U(a.time))}function Kc(a){a.j&&Rb(a.j);if(a.I){var b=a.I;b.g&&Rb(b.g)}Lc(a,!1)}p=Gc.prototype;
p.Mb=function(a){for(;0<this.v;){if(this.ja==this.h){this.ja=-1;this.s("break\n");U(this.time);break}var b=this.N.Da(this.h);this.h=(this.Qa=this.h)+1&this.N.I;if(void 0==b||!Mc(this,b)){this.h=this.Qa;this.s("unimplemented opcode\n");U(this.time);break}this.v-=Nc}if(0>=a){var c=this;oc(this.time,function(){var d=c.I;d.g&&Qb(d.g);c.ua(c.toString())})}};p.Qb=function(){this.v=0};p.Ob=function(){return this.Z-this.v};
function Mc(a,b){if(b&4096)return b&2048?!!(b&1024)==a.H&&(a.h=a.h&1024|b&1023):(a.push(a.h),a.h=b&2047),a.H=!1,!0;var c;var d=b&Oc;switch(d){case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:d=ad[d];var e=(b&bd)>>cd;var f=(b&dd)>>ed;var g=(b&fd)>>gd;var h=(c=b&hd)?id:jd;b=b>=Wc?16:a.O;switch(f){case 0:case 1:case 2:case 3:var k=a.g[f];break;case 4:k=Fc(a.ba,1,d);break;case 5:h=c?kd:ld;break;case 6:k=Fc(a.ba,a.u&15,d);break;case 7:k=Fc(a.ba,a.u&255,d)}switch(g){case 0:var m=
a.g[e];break;case 1:m=4>f?a.g[f]:void 0;break;case 2:m=5>f?a.oa:5==f?a.g[e]:void 0;break;case 3:if(c)a.g[e].move(k,d,b);else{a=a.U;e=k;b=d[0];for(k=d[1];b<=k;b++)m=a.l[b],a.l[b]=e.l[b],e.l[b]=m;Ec(e,d)}return!0}if(!m)break;switch(h){case jd:m.add(a.g[e],k,d,b);break;case id:m.sub(a.g[e],k,d,b);break;case ld:b=m;a=a.g[e];e=d[1];for(k=d[0];e>k;e--)b.l[e]=a.l[e-1];b.l[e]=0;Ec(b,d);break;case kd:b=m;a=a.g[e];e=d[0];for(k=d[1];e<k;e++)b.l[e]=a.l[e+1];b.l[e]=0;Ec(b,d)}return!0;case md:e=(b&nd)>>od;d=(b&
pd)>>qd;k=1<<((b&rd)>>sd);if(!d)break;d+=12;switch(b&td){case ud:a.g[e].l[d]|=k;break;case vd:a.g[e].l[d]&=~k;break;case wd:a.g[e].l[d]&k&&(a.H=!0);break;case xd:a.g[e].l[d]^=k}return!0;case yd:switch(b&zd){case Ad:a.U.store(a.W[a.K]);break;case Bd:a.K=b>>4&7;break;case Cd:a.h=a.u;break;case Dd:a.H=!1;d=a.m[0];e=0;for(b=a.m.length-1;e<b;)a.m[e]=a.m[++e];a.m[e]=-1;a.h=d;break;case Ed:a.R[a.K].store(a.U);break;case Fd:a.U.store(a.R[a.K]);break;case Gd:a.W[a.K].store(a.U);break;case Hd:Ic(a,"o");if(a.j){d=
0;for(e=11;0<=e;d++,e--)b=void 0,a.$.l[e]&8?b=" ":a.$.l[e]&1?b="-":b=xa[a.U.l[e]],Zb(a.j,d,0,b,a.$.l[e]&2?Wb:0)&&Ic(a,"om");Lc(a)}a.v-=31*Nc;a.aa&&(a.u=a.aa,a.H=!0,Ic(a,"i"));break;case Id:a.O=10;break;case Jd:a.O=16;break;case Kd:a.K=a.u&7;break;default:return!1}return!0}return!1}
p.pa=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return this.s("invalid saved state\n"),!1;var c=b.shift();if(3!==(c|0))return this.s("saved state version mismatch: %3.2f\n",c),!1;try{this.g.forEach(function(d){return d.set(b.shift())}),this.R.forEach(function(d){return d.set(b.shift())}),this.W.forEach(function(d){return d.set(b.shift())}),this.oa.set(b.shift()),this.ba.set(b.shift()),this.O=b.shift(),this.H=b.shift(),this.K=b.shift(),this.u=b.shift(),this.h=b.shift(),this.m=b.shift(),this.aa=
b.shift()}catch(d){return this.s("CPU state error: %s\n",d.message),!1}return(a=a.stateROM||a[1])&&this.I&&!this.I.pa(a)?!1:!0};
p.Hc=function(a){var b="";var c=0;var d=[],e=a[1];var f=Number.parseInt(a[2],16);isNaN(f)&&(f=-1);for(var g=Number.parseInt(a[3],10)||8,h=3;h<a.length;h++)d.push(Number.parseInt(a[h],16));this.ea=Hc;switch(e[0]){case "b":f=e.substr(1);if("l"==f){for(f in Jc)c=Jc[f],b+="break on "+c+" (b"+f+"): "+(this.T[f]||!1)+"\n";break}(c=Jc[f])?(this.T[f]=!this.T[f],b="break on "+c+" (b"+f+"): "+this.T[f]):f&&(b="unrecognized break option '"+f+"'");break;case "e":for(g=0;g<d.length;g++){a=this.N.xa(f);if(void 0==
a)break;this.N.bb(f,d[g]);b+=this.X("%#06x: %#06x changed to %#06x\n",f,a,d[g]);c++;f++}b+=this.X("%d locations updated\n",c);break;case "g":this.time.start()?this.ja=f:b="already started\n";break;case "h":U(this.time)||(b="already stopped\n");break;case "t":"c"==e[1]&&(this.ea=Ld);g=Number.parseInt(a[2],10)||1;kc(this.time,g);break;case "r":"c"==e[1]&&(this.ea=Ld);this.Pb(e.substr(1),f);b+=this.toString(e[1]);break;case "u":for(f=0<=f?f:0<=this.ca?this.ca:this.h;g--;){c=this.I&&this.N.xa(f);if(void 0==
c)break;b+=Cc(this,f++,c)}this.ca=f;break;case "?":b="additional commands:\n";Md.forEach(function(k){b+=k+"\n"});break;default:a[0]&&(b="unrecognized command '"+a[0]+"' (try '?')\n")}return b};p.ic=function(a,b){var c=0;0<=a&&0<=b&&(c=b|a+1<<4);this.aa=c};p.$a=function(a){return a&&this.pa(a)?!0:!1};p.ia=function(a){a?this.time.start():(U(this.time),Kc(this))};p.qa=function(){this.s("reset\n");this.h=0;Kc(this);this.time.g||this.ua(this.toString())};p.ab=function(a){this.ra(a)};
p.Ic=function(a){for(var b in this.S){var c=this.na[b];if(c){var d=c[0];c=c[1];M(this,b,0>c?d.toString():xa[d.l[c]])}}a&&!this.time.g&&(a=this.I,a.g&&Qb(a.g),this.ua(this.toString()))};p.push=function(a){for(var b=this.m.length-1;0<b;)this.m[b]=this.m[--b];this.m[0]=a};
p.ra=function(a){var b=[],c=[];b.push(3);this.g.forEach(function(d){return b.push(d.get())});this.R.forEach(function(d){return b.push(d.get())});this.W.forEach(function(d){return b.push(d.get())});b.push(this.oa.get());b.push(this.ba.get());b.push(this.O);b.push(this.H);b.push(this.K);b.push(this.u);b.push(this.h);b.push(this.m);b.push(this.aa);this.I&&this.I.ra(c);a.push(b);a.push(c)};p.Pb=function(a,b){if(a&&0<=b)switch(a){case "pc":this.h=b;break;default:this.s("unrecognized register: %s\n",a)}};
function Cc(a,b,c,d){d=void 0===d?!1:d;var e="???",f="";if(c&4096)c&2048?(e="BR",e=c&1024?e+"C":e+"NC",f=b&1024|c&1023):(e="CALL",f=c&2047),f=a.X("%#06x",f);else if(0<=c){var g=c&Oc;var h;switch(g){case Pc:case Qc:case Rc:case Sc:case Tc:case Uc:case Vc:case Wc:case Xc:case Yc:case Zc:case $c:f="";e=ad[g];for(g=0;16>g;g++)g%4||(f=" "+f),f=(e?g>=e[0]&&g<=e[1]?"F":"0":"?")+f;g=(c&bd)>>cd;var k=(c&dd)>>ed;var m=(c&fd)>>gd;var l=c&hd;e="LOAD";var r=h="?";var n=l?5==k?">>":"-":5==k?"<<":"+";switch(m){case 0:h=
Y[g];break;case 1:4>k&&(h=Y[k]);break;case 2:6>k&&(h="NUL");break;case 3:l?(e="MOVE",h=Y[g],r=Y[k]):(e="XCHG",g||(h="A"),4>k&&(r=Y[k])),k=-1}switch(k){case 0:case 1:case 2:case 3:r=Y[g]+n+Y[k];break;case 4:case 5:r=Y[g]+n+"1";break;case 6:r=Y[g]+n+"R5L";break;case 7:r=Y[g]+n+"R5"}f=h+","+r+","+f;break;case md:switch(c&td){case ud:e="SET";break;case vd:e="CLR";break;case wd:e="TST";break;case xd:e="NOT"}f=a.g[(c&nd)>>od].name;g=(c&pd)>>qd;f+="["+(g?g+12:"?")+":"+((c&rd)>>sd)+"]";break;case yd:switch(c&
zd){case Ad:e="STORE";f="A,Y[RAB]";break;case Bd:e="STORE";f="RAB,"+((c&112)>>4);break;case Cd:e="BR";f="R5";break;case Dd:e="RET";break;case Ed:e="STORE";f="X[RAB],A";break;case Fd:e="STORE";f="A,X[RAB]";break;case Gd:e="STORE";f="Y[RAB],A";break;case Hd:e="DISP";break;case Id:e="BCDS";break;case Jd:e="BCDR";break;case Kd:e="STORE",f="RAB,R5L"}}}return a.X(d?"%03X %04X\n":"%#06x: %#06x  %-8s%s\n",b,c,e,f)}
p.toString=function(a,b){var c=this;a=void 0===a?"":a;b=void 0===b?null:b;var d="";if(this.ea){this.I&&(d+=Cc(this,this.h,this.N.xa(this.h),!0));d+="  ";b=0;for(a=this.g.length;b<a;b++)d+=this.g[b].toString()+" ";d+="\n ";d+=" COND="+(this.H?1:0);d+=" BASE="+this.O;d+=" R5="+this.X("%02X",this.u);d+=" RAB="+this.K+" ST=";this.m.forEach(function(f){d+=c.X("%03X ",0>f?0:f&4095)});return d.trim()}if(b){a=0;for(var e=b.length>>1;a<e;a++)d+=b[a].toString(!0)+"  "+b[a+e].toString(!0)+"\n";return d}d+=this.toString(a,
this.g);0<=a.indexOf("a")&&(d+=this.toString(a,this.R),d+=this.toString(a,this.W));d+="COND="+(this.H?1:0);d+=" BASE="+this.O;d+=" R5="+this.X("%#04x",this.u);d+=" RAB="+this.K+" ";this.m.forEach(function(f,g){d+=c.X("ST%d=%#06x ",g,f&65535)});this.I&&(d+="\n"+Cc(this,this.h,this.N.xa(this.h)));this.ca=this.h;return d};
function Lc(a,b){b=void 0===b?!0:b;var c,d=b&&(a.type==Nd?!!(a.sa.l[14]&8):!!(a.$.l[15]&4));if(a.la!==d){if(c=a.S["2nd"])c.style.opacity=d?"1":"0",void 0===a.la&&a.j&&(c.style.color=a.j.color);a.la=d}d=b&&(a.type==Nd?!!(a.$.l[15]&4):!!(a.wa.l[15]&8));if(a.ma!==d){if(c=a.S.INV)c.style.opacity=d?"1":"0",void 0===a.ma&&a.j&&(c.style.color=a.j.color);a.ma=d}c=a.type==Nd?a.R[4].l[15]>>2:a.sa.l[15];b=b?c?1==c?Od:Pd:Qd:Rd;if(a.Y!==b){if(c=a.S.Deg)c.style.opacity=b==Qd?"1":"0",void 0===a.Y&&a.j&&(c.style.color=
a.j.color);if(c=a.S.Rad)c.style.opacity=b==Od?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);if(c=a.S.Grad)c.style.opacity=b==Pd?"1":"0",void 0===a.Y&&a.j&&(c.style.color=a.j.color);a.Y=b}}
var Oc=3840,Pc=0,Qc=256,Rc=512,Sc=768,Tc=1024,Uc=1280,Vc=1792,Wc=2048,Xc=2304,Yc=2560,md=3072,Zc=3328,yd=3584,$c=3840,bd=192,cd=6,dd=56,ed=3,fd=6,gd=1,hd=1,td=3,ud=0,vd=1,wd=2,xd=3,nd=192,od=6,pd=48,qd=4,rd=12,sd=2,zd=15,Ad=0,Bd=1,Cd=2,Dd=3,Ed=4,Fd=5,Gd=6,Hd=7,Id=8,Jd=9,Kd=10,Z={},ad=(Z[Pc]=[12,12],Z[Qc]=[0,15],Z[Rc]=[2,12],Z[Sc]=[0,12],Z[Tc]=[2,2],Z[Uc]=[0,1],Z[Vc]=[0,13],Z[Wc]=[14,14],Z[Xc]=[13,15],Z[Yc]=[14,15],Z[Zc]=[13,13],Z[$c]=[15,15],Z),Nc=128,jd=0,id=1,ld=2,kd=3,Nd=1501,Rd=0,Qd=1,Od=2,Pd=
3,Jc={i:"input",o:"output",om:"output modification"},Hc=0,Ld=1,Y="A B C D 1 ? R5L R5".split(" "),Md="b[c]\t\tbreak on condition c;bl\t\tlist break conditions;e [addr] ...\tedit ROM locations;g [addr]\trun (to addr);h\t\thalt;r[a]\t\tdump (all) registers;t [n]\t\tstep (n instructions);u [addr] [n]\tunassemble (at addr)".split(";");E.CPU1500=Gc;
function Sd(a,b,c){O.call(this,a,a);var d=this;this.j=!1;this.H=c;this.h="";this.v=this.u=!1;ib(this,!1);this.ga=0;b=b.trim();"{"==b[0]?Td(this,b):(this.h=b,Pa(this.h,function(e,f,g,h){4==g&&(!h&&f?(Td(d,f),Ud(d)):d.s("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.v=!0;Ud(d)});window.addEventListener(Ra("iOS")?"pagehide":Ra("Opera")?"unload":"beforeunload",function(){Vd(d)});window.addEventListener("pageshow",function(){d.j||d.ia(!0)})}y(Sd,O);
Sd.prototype.za=function(a,b){var c=this;switch(a){case Wd:b.onclick=function(){c.ia()};break;case Xd:b.onclick=function(){c.qa()}}O.prototype.za.call(this,a,b)};
function Ud(a){var b=!0;if(a.u&&a.v){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],E[d]?"Machine"==d?(a.s("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2024 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.s("Configuration: %s\n",a.h)):new E[d](a.M,c,e):a.s('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.s('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),kb(a,c)}}if(a.m){var f=Sa(a);gb(a,function(g){return g.$a&&!g.$a(f)?(g.s('unable to restore state for device "%s"\n',
g.V),!1):!0})}ib(a,!0);jb(a,a.ia.bind(a,b))||a.s("machine %s not ready to power, waiting for device(s)\n",a.M)}}
function Td(a,b){try{a.g=JSON.parse(b);var c=a.g[a.M];if(!c){c=a.g[Ca(a.h)];if(!c)throw Error("configuration missing machine ID");a.g[a.M]=c}fb(a,c,["autoSave","autoStart"]);a.m=!1!==a.J.autoSave;a.I=!1!==a.J.autoStart;if(a.H){var d=eval("("+a.H+")"),e;for(e in d)a.J[e]=d[e]}a.u=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.s("machine '%s' initialization error: %s\n",a.M,c)}}
Sd.prototype.ia=function(a){a=void 0===a?!this.j:a;if(hb(this)){var b=this;a&&this.s("power on\n");gb(this,function(c){c.ia&&c!=b&&("CPU"!=c.J["class"]||b.I&&hb(b)?c.ia(a):c.time.update(!0));return!0});(this.j=a)||this.s("power off\n")}};Sd.prototype.qa=function(){if(hb(this)){var a=this;gb(this,function(b){b.qa&&b!=a&&b.qa();return!0});this.s("reset\n")}};function Vd(a){if(a.m){var b=[];gb(a,function(c){c.ab&&c.ab(b);return!0});Za(a,b)}a.ia(!1)}var Wd="power",Xd="reset";
window.TMS1500=function(a,b,c){var d=new Sd(a,b,c);window.command=function(e){return Ta(d,e)};return d};E.Machine=Sd;})()

//# sourceMappingURL=ti55.js.map
