(function(){/*
 https://www.pcjs.org/modules/v3/defs.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/numio.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/stdio.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/webio.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/device.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/bus.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/memory.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/rom.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/input.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/led.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/time.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/cpu.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/ledctrl.js (C) 2012-2025 Jeff Parsons
 https://www.pcjs.org/modules/v3/machine.js (C) 2012-2025 Jeff Parsons
*/
var u;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ca="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},da="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ea(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var fa=ea(this);function v(a,b){if(b)a:{var c=fa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&da(c,a,{configurable:!0,writable:!0,value:b})}}var ha;
if("function"==typeof Object.setPrototypeOf)ha=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},ka={};try{ka.__proto__=ja;ia=ka.a;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var la=ha;
function y(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.lf=b.prototype}function ma(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
v("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});v("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
function na(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}v("String.prototype.repeat",function(a){return a?a:function(b){var c=na(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
v("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.aa=f;da(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.aa};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
v("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=fa[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&da(d.prototype,a,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}})}return a});function oa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function pa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}v("Array.prototype.keys",function(a){return a?a:function(){return pa(this,function(b){return b})}});v("Array.prototype.values",function(a){return a?a:function(){return pa(this,function(b,c){return c})}});
v("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function z(a){return a?a:Array.prototype.fill}v("Int8Array.prototype.fill",z);v("Uint8Array.prototype.fill",z);v("Uint8ClampedArray.prototype.fill",z);v("Int16Array.prototype.fill",z);v("Uint16Array.prototype.fill",z);v("Int32Array.prototype.fill",z);
v("Uint32Array.prototype.fill",z);v("Float32Array.prototype.fill",z);v("Float64Array.prototype.fill",z);v("Number.parseInt",function(a){return a||parseInt});v("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=na(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});function qa(){}var ra=new ArrayBuffer(2);(new DataView(ra)).setUint16(0,256,!0);new Uint16Array(ra);
var A={uc:0xffffffffffff,NONE:0,Cc:0,Ua:0x800000000000},B={};B.Defs=qa;function sa(){}y(sa,qa);function ta(a,b){var c=a/C|0,d=b/C|0;return(a&b)==(b|0)&&(c&d)==d}var C=Math.pow(2,32);B.NumIO=sa;function E(){this.sb={};for(var a=0;22>a;a++)this.sb["ACDFHGMNSTWYbdfjcsoXx%"[a]]=null}y(E,sa);u=E.prototype;u.flush=function(){var a=ua;ua="";this.Va(a)};
function va(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}
u.Dd=function(){var a=ma.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,ba(a)));return a};
u.Va=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),wa||(wa=b),a=((b-wa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(ua+a.substr(0,c)),ua="",a=a.substr(c+1)),wa=null);ua+=a;return a.length};function F(a,b,c){a.Va(b+"\n",c)}u.ka=function(a){return this.Va(this.ya.apply(this,[a].concat(ba(ma.apply(1,arguments)))))};
u.ya=function(a){var b=ma.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,f;for(f=0;f<d.length-6;f+=6){c+=d[f];var g=d[f+5];if(void 0===this.sb[g])c+="%"+d[f+1]+d[f+2]+d[f+3]+d[f+4]+g;else{if(e<b.length){var h=b[e];"%"!=g&&e++}else h=b[b.length-1];var m=d[f+1],n=0<=m.indexOf("#"),l=0<=m.indexOf("0"),k=d[f+2];"*"==k?(k=h,h=e<b.length?b[e++]:b[b.length-1]):k=+k||0;var p=d[f+3];p=p?+p.substr(1):-1;var r=d[f+4],t=null,x=0,w=
"";var q=0<="ACDFHGMNSTWY".indexOf(g)&&"object"!=typeof h?this.Dd(h):h;switch(g){case "C":h=n?"#":"";c+=isNaN(q.getTime())?void 0:this.ya(this.ya("%%%sW, %%%sF %%%sD, %%%sY",h),q);continue;case "D":h=n?q.getUTCDate():q.getDate();g="d";break;case "A":case "G":case "H":h=n?q.getUTCHours():q.getHours();"A"==g?(h=12>h?"am":"pm",g="s"):("G"==g&&(h=h?12<h?h-12:h:12),g="d");break;case "F":case "M":h=n?q.getUTCMonth():q.getMonth();"F"==g?(h=xa[h],g="s"):(h++,g="d");break;case "N":h=n?q.getUTCMinutes():q.getMinutes();
g="d";break;case "S":h=n?q.getUTCSeconds():q.getSeconds();g="d";break;case "T":h=n?"#":"";c+=isNaN(q.getTime())?void 0:this.ya(this.ya("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),q);continue;case "W":h=ya[n?q.getUTCDay():q.getDay()];g="s";break;case "Y":h=n?q.getUTCFullYear():q.getFullYear(),0<p&&(h%=Math.pow(10,p)),g="d"}switch(g){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=p&&(l=!0,k<p&&(k=p),p=-1);case "f":h=+h;q=h+"";0<=p&&(q=h.toFixed(p));q.length<k&&(l?(0>h&&(k--,q=
q.substr(1)),q=("0".repeat(k)+q).slice(-k),0>h&&(q="-"+q)):q=(" ".repeat(k)+q).slice(-k));c+=q;break;case "j":c+=JSON.stringify(h,null,k||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=p&&(h=h.substr(0,p));h.length<k;)h=0<=m.indexOf("-")?h+" ":" "+h;c+=h;break;case "o":x=8,n&&(w="0");case "X":t=za;case "x":q="";x||(x=16);!w&&n&&(w="0x");t||(t=Aa);h=Math.trunc(h);0<=p&&(l=!0,k<p&&(k=p));l&&!k&&("b"==r?k=2:"h"==
r||"w"==r?k=4:"l"==r?k=8:(k=Math.abs(h),k=255>=k?2:65535>=k?4:4294967295>=k?8:9),k+=w.length);k-=w.length;do n=h&x-1,h>>>=16==x?4:3,l||!q||n||h?q=t[n]+q:(w&&(q=w+q,w=""),0<k&&(q=" "+q));while(0<--k||h);c+=w+q;break;case "%":c+="%";break;default:c=this.sb[g]?c+this.sb[g](g,m,k,p,h):c+("(unimplemented sprintf type: %"+g+")")}}}return c+=d[f]};var ua="",wa=null,Aa="0123456789abcdef",za="0123456789ABCDEF",ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),xa="January February March April May June July August September October November December".split(" ");
B.StdIO=E;function G(a){E.call(this);this.la={};this.Ca=0;this.oa=this;a&&(this.oa.Ca=0,this.oa.Ma=[],this.oa.Fa=0,this.oa.fb={},this.oa.Xe=!1)}var Ba;y(G,E);u=G.prototype;u.Oa=function(a,b){var c=this,d=this;switch(a){case Ca.yc:b.onclick=function(){var e=c.$a(Ca.wb,!0);e&&(e.value="")};break;case Ca.wb:Da(b),b.addEventListener("keydown",function(e){Ea(d,e,!0)}),b.addEventListener("keypress",function(e){Ea(d,e)})}};
function Fa(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value="string"==typeof b[e]?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}function Ga(a,b){var c=Ha.Ib;a.oa.fb[c]||(a.oa.fb[c]=[]);a.oa.fb[c].push(b)}function Da(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}
u.error=function(a,b){b=this.ya.apply(this,[a].concat(ba(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.ya.apply(this,[c].concat(ba(b))))F(this,b),a||alert(b)};u.$a=function(a){return this.la[a]};function Ia(a){var b=window;if(b){do{for(var c=0;c<Ja.length;c++){var d=Ja[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ka(a,b){return a.ga.bindings&&a.ga.bindings[b]}
function La(a){if(a=a.la[Ma])var b=a.textContent;return b}function Na(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}function I(a,b,c,d){a=a.ga[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Oa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Pa(){var a,b=Ba;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ba=b}return b}function Qa(a){if(void 0===J.ub){var b=!1;if(window)try{window.localStorage.setItem(J.Ya,J.Ya),b=window.localStorage.getItem(J.Ya)==J.Ya,window.localStorage.removeItem(J.Ya)}catch(c){F(a,c.message),b=!1}J.ub=b}return!!J.ub}
function Ra(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.Ca;return-1==(b|1)||ta(a.oa.Ca,b)?!0:!1}function Sa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ta(a){var b=null;if(Qa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.na))&&(b=JSON.parse(c))}catch(d){F(a,d.message)}}return b}
function Ea(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.oa,f=b.target;if(c){a=!1;var g;c=f.value;var h=c.lastIndexOf("\n");d==L.Fb&&f.selectionStart<=h+1&&(a=!0);d==L.td?(a=!0,0<e.Fa&&(g=e.Ma[--e.Fa])):d==L.Ec&&(a=!0,e.Fa<e.Ma.length&&(g=e.Ma[++e.Fa]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,h+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.Fa&&c+1==
g.length&&(f.value+=e.Ma[--e.Fa],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ua(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&F(a,b.replace(/\n$/,""),!1))}}
function Va(a,b){if(void 0!=b){var c=a.oa;try{if(b=b.trim())c.Fa<c.Ma.length&&b==c.Ma[c.Fa]?c.Fa++:(c.Ma.push(b),c.Fa=c.Ma.length);var d=b.split(" "),e=d[0],f=a.oa.fb[Ha.Ib];switch(e[0]){case "m":if("?"==e[1]){var g="";Wa.forEach(function(k){g+=k+"\n"});g&&(g="message commands:\n"+g);break}g="";var h=void 0;e=d[d.length-1].toLowerCase();var m="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=m&&d.pop();1>=d.length&&(void 0!=m&&(h=m,m=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(M));
for(f=1;f<d.length;f++){e=d[f];var n=M[e];if(!n){g+="unrecognized message: "+e+"\n";break}void 0!=m&&Xa(a,n,m);if(void 0==h||h==Ra(a,n))g+=a.ya("%8s: %b\n",e,Ra(a,n))}Ra(a,A.Ua)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ya.forEach(function(k){g+=k+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var l=f[a](d);if(void 0!=l){g=g?g+l:l;break}}}}catch(k){g="error: "+k.message+"\n"}}return g}
function Ua(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Va(a,b[d])}return c}u.Va=function(a,b){void 0==b&&(b=Ra(this,A.Ua));if(!b){var c=this.$a(Ca.wb,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Sa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return E.prototype.Va.call(this,a,b)};
u.ka=function(a){var b=ma.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return Ra(this,c)?E.prototype.ka.call.apply(E.prototype.ka,[this,a].concat(ba(b))):0};function Za(a,b){if(Qa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.na,b)}catch(c){F(a,c.message)}}}function $a(a,b,c){(a=a.la[b])&&a.textContent!=c&&(a.textContent=c)}
function Xa(a,b,c){var d=!1;c?(c=a.oa.Ca,a.oa.Ca=(c|b)+(c/C|0|b/C|0)*C):(d=ta(a.oa.Ca,A.Ua)&&ta(b,A.Ua),c=a.oa.Ca,a.oa.Ca=(c&~b)+((c/C|0)&~(b/C|0))*C);d&&a.flush()}
var Ca={yc:"clear",wb:"print"},Ya=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Wa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],M={all:A.uc,buffer:A.Ua},Ha={Ib:"command"},ab={Jb:13,tb:65,Eb:66,Gb:67,Kb:68,E:69,Mb:70,Nb:71,Ob:72,Pb:73,Rb:74,Sb:75,Ub:76,Xb:77,Yb:78,Zb:79,$b:80,Q:81,ac:82,cc:83,dc:84,
ec:85,fc:86,hc:87,ic:88,jc:89,zb:90,a:97,b:98,c:99,d:100,e:101,f:102,cf:103,df:104,ef:105,ff:106,k:107,gf:108,hf:109,n:110,jf:111,p:112,q:113,r:114,kf:115,t:116,mf:117,nf:118,w:119,x:120,y:121,z:122},L={Fb:8,md:9,Tc:10,Jb:13,hd:16,Ac:17,vc:18,Ne:19,vb:20,Pd:27,kd:32,Qe:33,Pe:34,Od:35,je:36,Vb:37,td:38,yb:39,ge:39,Ec:40,de:44,Re:44,ke:45,Nd:46,fe:46,ie:47,ZERO:48,ONE:49,rd:50,nd:51,Pc:52,Oc:53,jd:54,gd:55,Fc:56,Zc:57,Mc:59,Lc:61,tb:65,Eb:66,Gb:67,Kb:68,E:69,Mb:70,Nb:71,Ob:72,Pb:73,Rb:74,Sb:75,Ub:76,
Xb:77,Yb:78,Zb:79,$b:80,Q:81,ac:82,cc:83,dc:84,ec:85,fc:86,hc:87,ic:88,jc:89,zb:90,Hb:91,ee:91,ce:92,Ue:93,he:93,oe:96,Fe:96,be:96,pe:97,De:97,qe:98,Ce:98,re:99,Ie:99,se:100,Ge:100,te:101,ze:101,ue:102,Ke:102,ve:103,Ee:103,we:104,Me:104,xe:105,Je:105,He:106,ye:107,Le:109,Ae:110,Be:111,Qd:112,Ud:113,Vd:114,Wd:115,Xd:116,Yd:117,Zd:118,$d:119,ae:120,Rd:121,Sd:122,Td:123,$c:144,dd:145,Kc:173,ed:186,Gc:187,Ld:188,Bc:189,Oe:190,We:191,Jd:192,le:219,Kd:220,Te:221,Se:222,Jc:224,me:901,Ye:1E3},bb={},cb=(bb[L.Mc]=
L.ed,bb[L.Lc]=L.Gc,bb[L.Kc]=L.Bc,bb[L.Jc]=L.Hb,bb),db={Vb:1,yb:2,ne:3},N={},eb=(N[L.Fb]="\b",N[L.md]="\t",N[L.Tc]="\n",N[L.Jb]="\r",N[L.kd]=" ",N[L.ZERO]="0",N[L.ONE]="1",N[L.rd]="2",N[L.nd]="3",N[L.Pc]="4",N[L.Oc]="5",N[L.jd]="6",N[L.gd]="7",N[L.Fc]="8",N[L.Zc]="9",N[L.tb]="A",N[L.Eb]="B",N[L.Gb]="C",N[L.Kb]="D",N[L.E]="E",N[L.Mb]="F",N[L.Nb]="G",N[L.Ob]="H",N[L.Pb]="I",N[L.Rb]="J",N[L.Sb]="K",N[L.Ub]="L",N[L.Xb]="M",N[L.Yb]="N",N[L.Zb]="O",N[L.$b]="P",N[L.Q]="Q",N[L.ac]="R",N[L.cc]="S",N[L.dc]=
"T",N[L.ec]="U",N[L.fc]="V",N[L.hc]="W",N[L.ic]="X",N[L.jc]="Y",N[L.zb]="Z",N[L.Vb]="Left",N[L.yb]="Right",N),Ja=["","moz","ms","webkit"],fb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},J={ub:void 0,Ya:"PCjs.localStorage"};B.WebIO=G;
function O(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;G.call(this,a==b);this.na=a;this.va=b;P[this.na]||(P[this.na]={});P[this.na][this.va]&&this.ka("warning: machine configuration contains multiple '%s' devices\n",this.va);P[this.na][this.va]=this;this.id=this.na==this.va?this.na:this.na+"."+this.va;gb.push(this);this.oa=hb(this,this.na);this.ready=!0;ib(this,c,d);this.Wb=[]}y(O,G);
function ib(a,b,c){c=b.overrides||c;if(c.length){var d=Pa();for(r in d)if(0<=c.indexOf(r)){var e=d[r];var f=void 0;var g,h=void 0,m=e,n=10;if(m){n||(n=10);var l=0<m.indexOf(",");l&&(m=m.replace(/,/g,""));var k=g=m.charAt(0);"#"==g?(n=8,g=""):"$"==g&&(n=16,g="");k!=g?m=m.substr(1):(k=g=m.substr(0,2),"0b"==g&&l||"^B"==g?(n=2,g=""):"0o"==g||"^O"==g?(n=8,g=""):"^D"==g?(n=10,g=""):"0x"==g&&(n=16,g=""),k!=g&&(m=m.substr(2)));k=g=m.slice(-1);"Y"==g||"y"==g?(n=2,g=""):"."==g?(n=10,g=""):"H"==g||"h"==g?(n=
16,g=""):"K"==g?g="000":"M"==g?g="000000":"G"==g&&(g="000000000");k!=g&&(m=m.slice(0,-1)+g);k=0;10>=n&&(g=m.match(/(-?[0-9]+)B([0-9]*)$/))&&(m=g[1],k=35-((g[2]||35)&255));(n&&10!=n?16==n?null===m.match(/^-?[0-9a-f]+$/i):8==n?null===m.match(/^-?[0-7]+$/):2!=n||null===m.match(/^-?[01]+$/):null===m.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(m,n))||(k&&(0>f&&(f+=Math.pow(2,36)),f=0<k?f*Math.pow(2,k):Math.trunc(f/Math.pow(2,-k))),h=f)}f=h;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[r]=
f;F(a,"overriding "+a.va+" property '"+r+"' with "+e)}}a.ga=b;c=b.bindings;c=void 0===c?{}:c;if("undefined"!=typeof document){a.ga.la||(a.ga.la=c);(d=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.va);for(var p in c){e=c[p];if(d)p=e;else if(e.match(/^[0-9]+$/)){var r=+e;a.la[p]=[];do{e=p+r++;e=document.getElementById(e);if(!e)break;a.la[p].push(e)}while(1);continue}if(r=document.getElementById(e))a.la[p]=r,a.Oa(p,r)}}b=void 0===b?{}:b;a.version=2;if(a.version){p=
"";var t;a.na!=a.va&&(t=hb(a,a.na).version)&&t!=a.version&&(p="Machine");p||(t=b.version)&&t>a.version&&(p="Config");p&&(t=a.ya("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.$e,a.version,p,t),a.error("%s\n\nClearing your browser's cache may resolve the issue.",t))}}function jb(a,b){var c;try{var d=P[a.na];if(d)for(c in d){var e=d[c];if(e.va!=e.na&&!b(e))return!1}return!0}catch(f){a.ka("error while enumerating device '%s': %s\n",c,f.message)}return!1}
O.prototype.$a=function(a,b){b=void 0===b?!1:b;if(a){var c=G.prototype.$a.call(this,a,b);if(void 0===c&&b){b=P[this.na];for(var d in b)if(c=b[d].la[a])break;c||(c=null);this.la[a]=c}}return c};function hb(a,b){var c=b,d=a.na,e=d.indexOf(".");0<e&&(d=d.substr(0,e),b=b.substr(e+1));b=(e=P[d])&&e[b]||null;if(!b){for(e=0;e<gb.length;e++)if(gb[e].id===c){b=gb[e];break}if(!b)throw Error(a.ya('no "%s" device',c));}return b}
function R(a,b,c){var d=null,e=P[a.na];if(e)for(var f in e)if(e[f].ga["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.ya("no %s device",b));return d}function kb(a){return a==a.oa&&a.ready?jb(a,function(b){return kb(b)}):a.ready}function lb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(kb(a)){for(;b=a.Wb.pop();)b();a!=a.oa&&lb(a.oa)}}function mb(a,b){if(kb(a))return b(),!0;a.Wb.push(b);return!1}
O.prototype.ka=function(a){var b=ma.apply(1,arguments);return"number"==typeof a&&Ra(this,a)&&(void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1)),this.oa.Ca&A.Db&&(void 0===this.Pa&&(this.Pa=R(this,"CPU")),this.Pa))?(a=b.shift(),G.prototype.ka.call(this,"%#06x: %s.%s\n",this.Pa.Ed,this.va,this.ya.apply(this,[a].concat(ba(b))).trim())):G.prototype.ka.call.apply(G.prototype.ka,[this,a].concat(ba(b)))};function nb(a,b){(a=P[a.na])&&delete a[b]}
"undefined"!=typeof window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]));var P="undefined"!=typeof window?window.PCjs.Machines:{},gb="undefined"!=typeof window?window.PCjs.Components:[];A.Db=1;A.wc=2;A.Ic=4;A.Uc=8;A.ad=16;A.xc=32;A.Sc=64;A.fd=128;A.Vc=256;A.zc=512;A.Wc=1024;A.INT=2048;A.qd=4096;A.ud=8192;A.Xc=16384;A.cd=32768;A.Dc=65536;A.Nc=131072;A.kb=262144;A.od=524288;A.Lb=1048576;A.Qb=2097152;A.Tb=4194304;
A.Yc=8388608;A.pd=16777216;A.Rc=33554432;A.lb=67108864;A.Hc=134217728;A.Qc=268435456;A.Md=4294967296;M.addr=A.Db;M.bus=A.wc;M.fault=A.Ic;M.memory=A.Uc;M.ports=A.ad;M.chips=A.xc;M.kbd=A.Sc;M.serial=A.fd;M.misc=A.Vc;M.cpu=A.zc;M.mmu=A.Wc;M["int"]=A.INT;M.trap=A.qd;M.video=A.ud;M.monitor=A.Xc;M.screen=A.cd;M.disk=A.Dc;M.file=A.Nc;M.time=A.kb;M.timer=A.od;M.event=A.Lb;M.input=A.Qb;M.key=A.Tb;M.mouse=A.Yc;M.touch=A.pd;M.info=A.Rc;M.warn=A.lb;M.error=A.Hc;M.halt=A.Qc;B.Device=O;
function ob(a,b,c){O.call(this,a,b,c);this.type="static"==this.ga.type?pb:qb;this.ea=this.ga.addrWidth||16;this.ba=Math.pow(2,this.ea);this.blockSize=this.ga.blockSize||(16<this.ea?4096:1024);this.blockSize>this.ba&&(this.blockSize=this.ba);this.ia=this.ba/this.blockSize|0;this.ca=Math.log2(this.blockSize)|0;this.fa=(1<<this.ca)-1;this.ha=this.ga.dataWidth||8;this.aa=Array(this.ia);this.da=0;a=new S(a,b+"[NONE]",{size:this.blockSize,bus:this.va});for(b=0;b<this.ba;b+=this.blockSize)rb(this,b,this.blockSize,
T.NONE,a);a=this.da;this.da+=this.type;a&&this.da||(this.bb=this.cb)}y(ob,O);
function rb(a,b,c,d,e){for(var f=b>>>a.ca;0<c&&f<a.aa.length;){var g=f*a.blockSize,h=a.blockSize-(b-g);h>c&&(h=c);var m=a.aa[f];if(b!=g||h!=a.blockSize||m&&m.type!=T.NONE)break;var n=m=void 0,l=b,k=a.ea,p=16;k=void 0===k?0:k;m=void 0===m?0:m;var r="",t="",x=-1;p||(p=a.ja||10);k&&(x=Math.ceil(k/Math.log2(p)));if(void 0==n)switch(p){case 8:n="0o";break;case 16:n="0x";break;case 10:t=".";default:n=""}isNaN(l)||"number"!=typeof l?(l=void 0,n=t=""):(0>l&&-1<l&&(l=-1),k&&(0>l&&(l+=Math.pow(2,k)),l>=Math.pow(2,
k)&&(x=Math.ceil(Math.log(l)/Math.log(p)))));for(k=m||-1;x--;){k||(r=","+r,k=m);if(void 0==l){if(r="?"+r,0>x)break}else{var w=l%p;l=Math.trunc(l/p);w+=0<=w&&9>=w?48:55;r=String.fromCharCode(w)+r;if(!l&&0>x)break}k--}m=a.va+"["+(n+r+t)+"]";b=e?e.size==a.blockSize?e:new S(a.na,m,{type:d,Ab:b,size:h,bus:a.va}):new S(a.na,m,{type:d,Ab:b,size:h,bus:a.va});a.aa[f]=b;b=g+a.blockSize;c-=h;f++}}u=ob.prototype;u.Ea=function(){void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};u.Ga=function(){};
u.Bb=function(a){return a&&this.Ka(a)?!0:!1};u.Cb=function(a){this.La(a)};u.Ka=function(a){for(var b=0;b<this.aa.length;b++){var c=this.aa[b];if((this.type==qb||c.type&T.jb)&&c.Ka){var d=a.shift();if(!c.Ka(d))return!1}}return!0};u.La=function(a){for(var b=0;b<this.aa.length;b++){var c=this.aa[b];if((this.type==qb||c.type&T.jb)&&c.La){var d=[];c.La(d);a.push(d)}}};u.cb=function(a,b){this.aa[a>>>this.ca].bb(a&this.fa,b)};var pb=0,qb=1;B.Bus=ob;
function S(a,b,c){O.call(this,a,b,c);this.Ab=this.ga.addr;this.size=this.ga.size;this.type=this.ga.type||T.NONE;this.ca=(a=this.ga.bus)?hb(this,a):R(this,a="Bus");if(!this.ca)throw Error(this.ya("unable to find bus '%s'",a));this.ia=this.ca.ha;this.ea=this.ha=!1;this.values=this.ba=null;a=this.cb;if(this.ca.type==pb){a=this.Gd;if(b=8==this.ia)b=hb(this,this.na),b=!1!==(b&&b.ga&&b.ga.ArrayBuffer||this.ga.ArrayBuffer);b&&(this.ha=!0)}switch(this.type){case T.NONE:this.bb=this.rc;break;case T.bc:this.bb=
this.rc;break;case T.jb:this.bb=a}sb(this,this.ga.values);tb(this)}y(S,O);function sb(a,b){"string"==typeof b?(lb(a,!1),Oa(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);sb(a,g.values)}catch(h){a.ka("error (%s) parsing resource: %s\n",h.message,c)}lb(a,!0)}else a.ka("error (%d) loading resource: %s\n",f,c)})):a.ga.values=b}
function tb(a,b){if(a.type>T.NONE&&(a.ha?(a.ba=new ArrayBuffer(a.size),new DataView(a.ba,0,a.size),a.values=new Uint8Array(a.ba,0,a.size),new Uint16Array(a.ba,0,a.size>>1),new Int32Array(a.ba,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}u=S.prototype;
u.Ga=function(){if(this.ga.values)a:{var a=this.ca,b=this.Ab,c=this.size,d=this.ga.values,e=0,f=b&a.fa;b>>>=a.ca;c>d.length&&(c=d.length);for(;0<c&&b<a.aa.length;){var g=a.aa[b++];if(!g)break a;for(;0<c&&f<g.size;)g.cb(f++,d[e++]),c--;f=0}}else this.type&T.jb&&this.values&&this.values.fill(0)};u.rc=function(){};u.cb=function(a,b){this.values[a]=b};u.Gd=function(a,b){this.values[a]=b;this.ea=!0;this.bb=this.cb};
u.Ka=function(a){if(a){var b=a.shift();if(this.va==b){this.ea=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}tb(this,a)}return!0}}return!1};
u.La=function(a){a.push(this.va);a.push(this.ea);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var f=b[c],g=c+1;g<b.length&&b[g]===f;)g++;e[d++]=g-c;e[d++]=f;c=g}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var T={NONE:1,bc:2,jb:4,Ve:14,Ze:12};B.Memory=S;
function ub(a,b,c){c.type=T.bc;S.call(this,a,b,c);rb(this.ca,this.ga.addr,this.ga.size,this.ga.type,this);mb(this,this.Ga.bind(this));this.Pa=this.Ja=void 0;if(B.LED&&this.la[vb]){var d=this;this.da=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.fa=this.values.length/this.da|0;this.aa=new wb(a,b+"LEDs",{"class":"LED",bindings:{container:Ka(this,vb)},type:xb,cols:this.da,rows:this.fa,color:I(this,"colorROM","green"),backgroundColor:I(this,"backgroundColorROM","black"),persistent:!0}),
yb(this.aa,!0);this.ja=new zb(a,b+"Input",{"class":"Input",location:[0,0,this.aa.Aa,this.aa.za,this.da,this.fa],bindings:{surface:Ka(this,vb)}});this.ma=La(this)||"";Ab(this.ja,function(e,f){if(d.Pa){var g=d.ma;0<=e&&0<=f&&(g="");$a(d,Ma,g)}})}}y(ub,S);
ub.prototype.Ka=function(a){var b=!0,c=a.shift();if(c&&this.aa){var d=c.length;this.aa.aa.length==d?(this.aa.aa=c,Bb(this.aa,!0)):(this.ka("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.ka("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};ub.prototype.Ea=function(){void 0===this.Pa&&(this.Pa=R(this,"CPU"));void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};
ub.prototype.La=function(a){this.aa&&(a.push(this.aa.aa),a.push(this.values))};var vb="array",Ma="cellDesc";B.ROM=ub;
function zb(a,b,c){O.call(this,a,b,c);this.Ca=A.Qb;this.ja=this.qa=null;this.time=R(this,"Time");this.oa=R(this,"Machine");this.wa=I(this,"drag",!1);this.ma=I(this,"scroll",!1);this.Aa=I(this,"hexagonal",!1);this.ea=I(this,"releaseDelay",0);this.fa=!1;a=this.ga.map;this.ba=this.ca=null;if(a)if(a.length)this.ba=a;else{this.ca={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.ca[f]={keys:g,
grid:e,state:0}}}this.ra=[];this.sa=[];this.da=this.ta=null;(a=this.la[Cb])&&Db(this,a,this.$a(c.focusBinding,!0),this.ga.location);this.Ga()}y(zb,O);function Ab(a,b){a.qa=b}function Eb(a,b){a.ja=b}function Fb(a,b,c){for(var d=0;d<a.ra.length;d++){var e=a.ra[d];e.id===b&&e.nc(b,c)}}
function Db(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.ba||a.ca){var e={};e.Hd=d[0]||0;e.Id=d[1]||0;e.Za=d[2]||b.clientWidth;e.mb=d[3]||b.clientHeight;e.nb=d[4]||1;e.qb=d[5]||1;e.yd=d[6]||b.naturalWidth||e.Za;e.Ad=d[7]||b.naturalHeight||e.mb;e.sc=d[8]||0;e.tc=d[9]||0;e.xd=d[10]||0;e.zd=d[11]||0;a.ba?(e.pb=a.ba.length,e.ab=a.ba[0].length):(e.ab=e.nb,e.pb=e.qb,e.nb=e.qb=0);e.kc=e.Za/(e.ab+e.ab*e.nb)|0;e.lc=e.mb/(e.pb+e.pb*e.qb)|0;e.wd=e.kc*e.nb|0;e.mc=e.lc*e.qb|0;e.eb=e.rb=-1;Gb(a,b,e);Hb(a,b,e);a.time&&
a.ea&&(a.za=Ib(a.time,"timerInputRelease",function(){0>e.eb&&0>e.rb&&Jb(a,-1,-1)}))}if(a.ba||a.ca)a.time&&a.ea&&(a.Ba=Ib(a.time,"timerKeyRelease",function(){Kb(a)})),a.ha=0,a.pa="",a.ia=[],d=b,c&&(d=c,a.da||"BUTTON"!=c.nodeName||(d=document,a.da=c,Lb(a,b),a.ta=b)),Lb(a,d),a.da||(a.da=d)}function Mb(a){a.ea?Nb(a.time,a.Ba,a.ea):Kb(a)}
function Lb(a,b){function c(e,f,g){var h=document.activeElement;a.ka(A.Tb+A.Lb,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.da&&e!=a.da&&e!=a.ta?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Ob(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=
Ob(a,f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Ob(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function Gb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.fa){var e=a.da;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||U(a,b,Pb,d,c)}});b.addEventListener("mousemove",function(d){a.fa||U(a,b,Qb,d,c)});b.addEventListener("mouseup",function(d){a.fa||d.button||U(a,b,Rb,d,c)});b.addEventListener("mouseout",function(d){a.fa||(0>c.eb?U(a,b,Qb,d,c):U(a,b,Rb,d,c))})}
function Hb(a,b,c){b.addEventListener("touchstart",function(d){a.ma&&(a.fa=!0);U(a,b,Pb,d,c)});b.addEventListener("touchmove",function(d){U(a,b,Qb,d,c)});b.addEventListener("touchend",function(d){U(a,b,Rb,d,c)})}
function Ob(a,b,c,d){if(void 0!=c){var e=cb[b]||b;var f=eb[b];var g=Sb[e];d=d&&d.location==db.yb;g&Tb&&d&&(g>>=1);g&&(g&Ub&&(c=!(a.aa&g)),a.aa=c?a.aa|g:a.aa&~g,Fb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=ab.tb&&b<=ab.zb?a.aa&(Vb|Wb)||(a.aa|=Wb,Fb(a,L.vb,!0)):b>=ab.a&&b<=ab.z&&a.aa&Wb&&(a.aa&=~Wb,Fb(a,L.vb,!1));if(a.ba){if(void 0!=c)return!1;for(e=0;e<a.ba.length;e++)for(g=a.ba[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.ha?16>a.ia.length&&a.ia.push(b):(a.ha=1,a.pa=
f,Jb(a,d,e),Fb(a,f,!0),Mb(a)),!0}if(a.ca){if(void 0==c)return!0;b=Object.keys(a.ca);for(e=0;e<b.length;e++)if(g=b[e],0<=a.ca[g].keys.indexOf(f))return Fb(a,g,c),a.ca[g].state=c?1:0,!0}return!1}function Kb(a){1==a.ha?(a.ha++,Fb(a,a.pa,!1),a.pa="",Jb(a,-1,-1),Mb(a)):(a.ha=0,a.ia.length&&Ob(a,a.ia.shift()))}zb.prototype.Ga=function(){this.aa=0;this.ua=this.xa=-1};
function U(a,b,c,d,e){var f=-1,g=-1,h=!1,m=-1,n=-1;if(c<Rb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(m=d.targetTouches[0].clientX,n=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(m=d.clientX,n=d.clientY);var l=d.target.getBoundingClientRect();m-=l.left;n-=l.top;m=e.yd/b.offsetWidth*m|0;n=e.Ad/b.offsetHeight*n|0;var k=m-e.Hd;var p=n-e.Id;var r=l=!1;var t=m>=e.sc&&m<e.sc+e.xd&&n>=e.tc&&n<e.tc+e.zd;if(0<=k&&k<e.Za&&0<=p+e.mc||t)if(h||a.ma||d.preventDefault(),0<=k&&k<e.Za&&
0<=p&&p<e.mb){r=!0;d=e.Za/e.ab|0;var x=e.mb/e.pb|0,w=k/d|0,q=p/x|0;!a.Aa||q&1||(k-=d>>1,w=k/d|0,w==e.ab-1&&(k=-1));x=q*x+(e.mc>>1);k-=w*d+(e.wd>>1);p-=x;0<=k&&k<e.kc&&0<=p&&p<e.lc&&(f=w,g=q,l=!0)}}k=k||0;p=p||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Pb||c==Rb)for(w=0;w<a.sa.length;w++)q=a.sa[w],c==Rb?q.nc(q.id,!1):(x=p/(b/q.bf|0)|0,(k/(d/q.af|0)|0)==q.pf&&x==q.qf&&q.nc(q.id,!0));if(!h)if(c==Pb)e.eb=m,e.rb=n,r?(Jb(a,f,g),l&&a.ea&&Nb(a.time,a.za,a.ea,!0)):t&&a.oa.Ea();else if(c==Qb)0<=e.eb&&0<=e.rb&&
a.wa?Jb(a,f,g):a.qa&&a.qa(f,g);else if(c==Rb){if(c=a.ea)c=a.time,f=a.za,c=c.aa&&0<f&&f<=c.ba.length?0<=c.ba[f-1].Da:!1;c||Jb(a,-1,-1);e.eb=e.rb=-1}else F(a,"unrecognized action: "+c)}function Jb(a,b,c){if(b!=a.ua||c!=a.xa)a.ua=b,a.xa=c,a.ja&&a.ja(b,c)}var Pb=1,Qb=2,Rb=3,Cb="surface",Vb=3,Tb=170,Wb=512,Ub=3584,V={},Sb=(V[L.hd]=2,V[L.Ac]=8,V[L.vc]=32,V[L.Hb]=128,V[L.vb]=Wb,V[L.$c]=1024,V[L.dd]=2048,V);B.Input=zb;
function wb(a,b,c){O.call(this,a,b,c,["color","backgroundColor"]);a=this.la[Xb];if(!a)throw Error("LED "+this.ga.la[Xb]+" binding for '"+Xb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Ta=Ka(this,Xb)+".canvas";b.setAttribute("id",this.Ta);this.Ra=a;this.type=Na(I(this,"type",xb,Yb),Zb,$b);this.ia=ac[this.type][0];this.pa=ac[this.type][1];this.width=I(this,"width",
this.ia);this.height=I(this,"height",this.pa);this.da=I(this,"cols",1);this.ca=this.da+I(this,"colsExtra",0);this.xa=I(this,"rows",1);this.ea=this.xa+I(this,"rowsExtra",0);this.Aa=this.width*this.da;this.za=this.height*this.xa;this.ha=bc("black",0);this.fa=cc(this.ga.color)||this.ha;this.hb=bc(this.fa,1,.25);this.gb=bc(this.fa,1,2);this.ma=cc(this.ga.backgroundColor);this.ib=I(this,"fixed",!1);this.ib||(b.style.width="100%",b.style.height="auto");this.Qa=I(this,"hexagonal",!1);this.xb=I(this,"highlight",
!0);this.Ha=I(this,"persistent",this.type<$b);b.setAttribute("width",this.Aa.toString());b.setAttribute("height",this.za.toString());b.style.backgroundColor=this.ha;a.appendChild(b);this.Sa=b.getContext("2d");if(this.sa=document.createElement("canvas"))this.sa.width=this.Na=this.ia*this.da,this.sa.height=this.ua=this.pa*this.xa,this.ba=this.sa.getContext("2d");this.Wa=(this.ea+1)*this.ca*4;this.aa=Array(this.Wa);this.ra=null;this.Xa=this.da<this.ca?4*(this.ca-this.da):0;this.ja=this.ta=!1;this.Ia=
0;this.Ba=!0;this.qa=0;this.wa=-1;var d=this;this.time=R(this,"Time");dc(this.time,function(e,f){Bb(d,!1,e,f)});yb(d,!0)}y(wb,O);function yb(a,b){ec(a,a.aa);a.ja=a.ta=!0;b&&Bb(a,!0)}function fc(a){a.ma?(a.ba.fillStyle=a.ma,a.ba.fillRect(0,0,a.Na,a.ua)):a.ba.clearRect(0,0,a.Na,a.ua)}
function Bb(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.ja||b){if(a.type<$b){d=0;if(!a.Ha||b)fc(a);else if(a.qa){d=a.da-a.qa;var e=a.ia*d;a.ba.drawImage(a.sa,a.ia*a.qa,0,e,a.ua,0,0,e,a.ua)}for(var f=e=0;f<a.ea;f++){for(var g=0;g<a.da;g++){var h=a.aa[e],m=a.aa[e+1]||a.ha,n=!1,l=!!(a.aa[e+3]&W),k=a.xb&&e==a.wa;!a.Ba&&h&&(h=gc,l=n=!0);if(l||k||b){if(g>=d)a:{l=a;var p=h;h=m;var r=g;m=f;var t=k;r=void 0===r?0:r;m=void 0===m?0:m;t=void 0===t?!1:t;var x=0;if(l.Qa&&!(m&1)&&(x=l.ia>>
1,r==l.da-1))break a;if(h&&h!=l.fa){t=t?bc(h,1,2):h;var w=bc(h,1,.25)}else t=t?l.gb:l.fa,w=l.hb;h=!1;p=p?t:w;t==l.ha&&(p=l.ma,h=!0);t=r*l.ia+x;w=m*l.pa;l.Ha&&(r=r*l.ia+x,m*=l.pa,l.ma?(l.ba.fillStyle=l.ma,l.ba.fillRect(r,m,l.ia,l.pa)):l.ba.clearRect(r,m,l.ia,l.pa));l.ba.fillStyle=p;m=hc[l.type];3==m.length?(l.ba.beginPath(),l.ba.arc(t+m[0],w+m[1],m[2],0,2*Math.PI),h?(l.ba.globalCompositeOperation="destination-out",l.ba.fill(),l.ba.globalCompositeOperation="source-over"):l.ba.fill()):l.ba.fillRect(t+
m[0],w+m[1],m[2],m[3])}a.aa[e+3]=k||n?a.aa[e+3]|W:a.aa[e+3]&~W}e+=4}e+=a.Xa}a.qa=0}else{b="";for(d=0;d<a.aa.length;d+=4)b+=a.aa[d]||" ",a.aa[d+3]&ic&&(b+=".");fc(a);for(f=e=d=0;d<b.length;d++){l=b[d];"."==l&&e&&e--;g=a;n=e;k=f;n=void 0===n?0:n;k=void 0===k?0:k;if(l=jc[l])for(m=0;m<l.length;m++)if(h=g,r=kc[l[m]]){x=(void 0===n?0:n)*h.ia;p=(void 0===k?0:k)*h.pa;h.ba.fillStyle=h.fa;h.ba.beginPath();if(3==r.length)h.ba.arc(x+r[0],p+r[1],r[2],0,2*Math.PI);else for(t=0;t<r.length;t+=2)t?h.ba.lineTo(x+r[t],
p+r[t+1]):h.ba.moveTo(x+r[t],p+r[t+1]);h.ba.closePath();h.ba.fill()}if(++e==a.da&&(e=0,++f==a.ea))break}}a.Sa.globalCompositeOperation=a.ma&&a.fa!=a.ha?"source-over":"copy";a.Sa.drawImage(a.sa,0,0,a.Na,a.ua,0,0,a.Aa,a.za);a.ja=!1;a.wa=-1}else a.Ha||a.ta||(!c||!a.Ia||c-a.Ia>=(1E3/d|0))&&yb(a,!0);a.ta=!1;c&&(a.Ia=c)}function lc(a,b){b=void 0===b?!0:b;a.Ba!=b&&(a.Ba=b,a.ja=!0)}function mc(a,b,c){b=4*(c*a.ca+b);return b<=a.aa.length-4?a.aa[b+2]:0}
function nc(a,b,c){var d;b=4*(c*a.ca+b);b<=a.aa.length-4&&(d=a.aa[b]);return d}function cc(a){return(a=a||void 0)&&fb[a]||a}function bc(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=fb[a]||a;if(oc(a,d)){a="rgba(";var e;for(e=0;3>e;e++){var f=Math.round(d[e]*c);f=0>f?0:255<f?255:f;a+=f+","}a+=(e<d.length?d[e]:b)+")"}}return a}function ec(a,b){for(var c=0;c<b.length;c+=4)pc(a,b,c)}function pc(a,b,c){b[c]=a.type<$b?gc:" ";b[c+1]=a.fa==a.ha?null:a.fa;b[c+2]=0;b[c+3]=W}
wb.prototype.Ka=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.fa&&c==this.ma&&a&&a.length==this.aa.length){this.aa=a;for(b=0;b<=this.aa.length-4;b+=4)this.aa[b+1]==this.ha&&(this.aa[b+1]=null);Bb(this,!0);return!0}return!1};function oc(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}
wb.prototype.La=function(a){this.aa&&(a.push(this.fa),a.push(this.ma),a.push(this.aa))};function qc(a,b,c,d){var e=null;0<=c&&c<a.ea&&0<=b&&b<a.ca&&(e=!1,d=d||a.fa,d==a.ha&&(d=null),b=4*(c*a.ca+b),a.aa[b+1]!==d&&((a.aa[b+1]=d)||(a.aa[b]=gc),a.aa[b+3]|=W,a.ja=e=!0),a.wa=b,a.ta=!0);return e}function rc(a,b,c,d){if(0<=c&&c<a.ea&&0<=b&&b<a.ca){b=4*(c*a.ca+b);c=0;if(a.aa[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.aa[b+2]!==c&&(a.aa[b+2]=c,a.aa[b+3]|=W,a.ja=!0);a.wa=b;a.ta=!0}}
function sc(a,b,c,d){var e=!1,f=0&tc;b=4*(c*a.ca+b);if(b<=a.aa.length-4){if(a.aa[b]!==d||(a.aa[b+3]&tc)!==f)a.aa[b]=d,a.aa[b+3]=a.aa[b+3]&~tc|f|W,a.ja=e=!0;a.wa=b;a.ta=!0;a.qa=0}return e}
var Zb=0,xb=1,$b=3,Yb={small:Zb,round:xb,square:2,digit:$b},Xb="container",gc=0,tc=129,ic=1,W=128,uc={},hc=(uc[Zb]=[4,4,4],uc[xb]=[16,16,14],uc[2]=[2,2,28,28],uc),ac=[[8,8],[32,32],[32,32],[96,128]],kc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},jc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};B.LED=wb;
function vc(a,b,c){O.call(this,a,b,c);this.Sa=I(this,"cyclesMinimum",1E5);this.hb=I(this,"cyclesMaximum",1E9);this.Ta=Na(I(this,"cyclesPerSecond",1E6),this.Sa,this.hb);this.xa=60;this.Aa=0;this.ta=1E3/this.xa;this.ld=I(this,"updatesPerSecond",2)||2;this.bd=1E3/this.ld;this.gb=0;this.sd=I(this,"timeLock",!0);this.Qa=this.qa=0;this.Na=this.ha=1;this.Xa=this.ja=this.Ta/1E4/100;this.Ba=[];this.ma=[];this.ba=[];this.Ha=[];this.Wa=this.aa=this.za=this.ia=!1;this.pa=this.da=0;a=Ia("requestAnimationFrame");
if(!a){a="setTimeout";var d=this.ta}this.ib=window[a].bind(window,this.Fd.bind(this),d);this.xb=window[Ia("cancelAnimationFrame")||"clearTimeout"].bind(window);this.wa=this.ua=this.ea=this.ca=this.Ra=0;wc(this)||xc(this,this.Na)}y(vc,O);function dc(a,b){a.Ba.push(b)}u=vc.prototype;
u.Oa=function(a,b){var c=this;switch(a){case yc:b.onclick=function(){zc(c)&&(c.aa?Ac(c):c.start())};break;case Bc:b.onclick=function(){xc(c,c.ha<<1);Cc(c,Dc(c.ja))};break;case Ec:b.onclick=function(){zc(c)&&(c.aa?F(c,"already running"):c.da?Ac(c):Fc(c))};break;case Gc:b.addEventListener("mousedown",function(){c.ia=!0}),b.addEventListener("mouseup",function(){wc(c);c.ia=!1}),b.addEventListener("mousemove",function(){c.ia&&wc(c)}),b.addEventListener("change",function(){c.ia=!0;wc(c);c.ia=!1})}O.prototype.Oa.call(this,
a,b)};function Ib(a,b,c){var d=void 0===d?-1:d;var e=a.ba.length+1;a.ba.push({id:b,vd:c,ob:d,Da:-1});0<=d&&Nb(a,e,d);return e}
function Hc(a,b,c,d){var e=0,f=a.ja,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.ka(A.kb,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.ta&&(1<a.ha&&(a.ha>>=1,a.ka(A.lb,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.ta,a.ha)),e=d));a.qa=f;a.Qa=f/a.Xa;b=a.Qa/a.ha;a.Ra=g/b/a.xa+1E-8;a.ka(A.kb,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.Ra,g,b,a.xa);return e}
function Ic(a,b){a.ua=a.ea=b;if(!a.ma.length)return a.ea=0,a.ua;for(var c=0;0<a.ea;){if(c<a.ma.length){var d=a.ma[c++];b=d.pc.call(d,b)||1}else c=b=0;a.ea-=b}return a.ua-a.ea}function Jc(a,b){b=void 0===b?a.ua-a.ea:b;if(!a.aa){if(a.ca)for(var c=0;c<a.ma.length;c++){var d=a.ma[c];d.qc.call(d)}a.ca=b}a.ca-=b;1>a.ca&&(a.za=!0);a.wa+=b;a.ua=a.ea=0;a.aa||(a.wa=0);return b}
function Kc(a,b){b=void 0===b?0:b;if(b){var c=b;a.ca+=b}else for(c=a.ca,1>c&&(c=a.ca+=a.Ra),0>c&&(a.ka(A.lb,"warning: cycle count dropped below zero: %f\n",c),c=a.ca=0),c|=0,b=a.ba.length;0<b;b--){var d=a.ba[b-1];!(0>d.Da)&&c>d.Da&&(c=d.Da)}return c}function Dc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function zc(a){return a.Wa?!0:(F(a,"not powered"),!1)}
function Lc(a,b){if(1<=b)for(var c=a.ba.length;0<c;c--){var d=a.ba[c-1];0>d.Da||(d.Da-=b,0>=d.Da&&(d.Da=-1,d.vd(),0<=d.ob&&Nb(a,c,d.ob)))}}u.Ea=function(a){this.Wa=a;void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};
u.Fd=function(a){a=void 0===a?Date.now():a;this.pa=0;if(this.aa){if(this.Aa){var b=a-this.Aa;1>b&&(b=16.67);this.xa=1E3/b}this.Aa=a;a=Date.now();this.ra&&(b=a-this.sa-this.ta,b>this.ta&&(this.fa+=b,this.ka(A.lb,"warning: browser throttling detected, compensating by %5.3fms\n",b)));this.sa=a;this.fa||(this.fa=a);this.Ia=0;try{this.za=!1;do Lc(this,Jc(this,Ic(this,Kc(this))));while(this.aa&&!this.za)}catch(c){F(this,c.message),Ac(this)}this.ra=Date.now();this.Ia&&(this.fa+=this.Ia,this.sa+=this.Ia);
this.sa+=Hc(this,this.wa,this.ra-this.fa,this.ra-this.sa);this.ra-this.gb>=this.bd&&this.update();for(a=0;a<this.Ba.length;a++)this.Ba[a](this.Aa,this.xa);this.pa=this.ib()}};function xc(a,b){if(void 0!==b){if(1>b||!a.ia&&0<a.qa&&a.qa<.9*a.ja)b=a.Na;a.ha=b;b=a.Xa*a.ha;a.ja!=b&&(a.ja=b,Cc(a,Dc(a.ja)))}a.fa=a.ra=0;a.ca=a.wa=0;Hc(a);for(b=a.ba.length;0<b;b--){var c=a.ba[b-1];0<=c.ob&&Nb(a,b,c.ob,!0)}}
function wc(a){var b=a.la[Gc];return b?(xc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.hb-a.Sa)+a.Sa)/a.Ta|0),!0):!1}function Nb(a,b,c,d){0<b&&b<=a.ba.length&&(b=a.ba[b-1],d||0>b.Da)&&(c=Math.ceil(a.Ta*(a.sd?a.Na:a.Qa)/1E3*(void 0===c?1E3:c)),a.aa&&(c+=Jc(a)),b.Da=c)}u.start=function(){if(this.aa||this.da)return!1;this.aa=!0;this.fa=this.ra=0;this.update(!0);this.pa=this.ib();return!0};
function Fc(a,b){b=void 0===b?1:b;a.aa||(b&&!a.da&&(a.da=b),a.da&&(a.da--,Lc(a,Jc(a,Ic(a,Kc(a,1)))),a.update(!1),a.da&&setTimeout(function(){Fc(a,0)},0)))}function Ac(a){a.aa?(a.aa=!1,Jc(a),a.pa&&(a.xb(a.pa),a.pa=0),a.update(!0)):a.da&&(a.da=0,a.update(!0))}
u.update=function(a){a&&F(this,this.aa?"started with "+Dc(this.ja)+" target":"stopped");$a(this,yc,this.aa?"Halt":"Run");$a(this,Ec,this.da?"Stop":"Step");this.ia||(this.ka(A.kb,"getSpeedCurrent(%5.3fhz)\n",1E6*this.qa),Cc(this,this.aa&&this.qa?Dc(this.qa):"Stopped"));for(a=0;a<this.Ha.length;a++){var b=this.Ha[a];b.Cd.call(b)}this.gb=Date.now();this.za=!0};function Cc(a,b){$a(a,Mc,b);$a(a,Bc,b)}var yc="run",Bc="setSpeed",Mc="speed",Ec="step",Gc="throttle";B.Time=vc;
function X(a,b,c){c["class"]="CPU";O.call(this,a,b,c);this.Ja=void 0;this.Ed=0;this.time=R(this,"Time");this.time.ma.push(this);this.time.Ha.push(this);this.sa=this.qa=0}y(X,O);X.prototype.abort=function(a){F(this,a.message);Ac(this.time)};X.prototype.pc=function(a){this.sa=this.qa=void 0===a?0:a;return this.oc()};X.prototype.qc=function(){this.sa-=this.qa;this.qa=0};X.prototype.oc=function(){return this.sa-this.qa};
function Nc(a,b,c){X.call(this,a,b,c);this.ja=I(this,"wrap",!1);this.ta=(this.xa=I(this,"font",""))&&Oc[this.xa]||Oc.Helvetica;this.ua=I(this,"rule","");this.pa=I(this,"pattern","");Pc(this,this.za=I(this,"message",""));this.Ia=I(this,"toggleColor",!1);this.Ha=Array(Qc(this).length);if(c=R(this,"LED",!1)){this.aa=c;Rc(this)||yb(c,!0);this.ra=R(this,"Input",!1);var d=this;this.Aa=new zb(a,b+"Input",{"class":"Input",location:[0,0,c.Aa,c.za,c.da,c.xa],drag:!(!this.ra||!this.ra.wa),scroll:!(!this.ra||
!this.ra.ma),hexagonal:c.Qa,bindings:{surface:c.Ta}});Eb(this.Aa,function(e,f){var g=d.aa;0<=e&&0<=f&&(d.ia?qc(g,e,f,d.ia)?sc(g,e,f,1):d.Ia?qc(g,e,f):sc(g,e,f,1-nc(g,e,f)):sc(g,e,f,1-nc(g,e,f)),rc(g,e,f,Qc(d,!!nc(g,e,f))),Bb(g))});this.ha=[];this.Ba=c.fa;Sc(this,this.Ba);Tc(this);Uc(this,this.ga[Vc]);Ga(this,this.Bd.bind(this))}}y(Nc,X);u=Nc.prototype;
u.Oa=function(a,b){var c=this,d;switch(a){case Wc:case Xc:b.onchange=function(){Yc(c,a)};Yc(this);break;case Vc:b.onchange=function(){Uc(c)};break;case Zc:Fa(b,$c(this.ga[Zc]),!1,this.ga.pattern);b.onchange=function(){var e=c.la[Zc];e&&e.options.length&&((e=e.options[e.selectedIndex].value)?Rc(c,e):c.Ga())};break;case ad:b.onclick=function(){var e=bd(c,!0),f=c.la[cd];f&&(e='"'+f.value+'":"'+e.replace(/^([0-9]+\/)*/,"")+'",');F(c,e)};break;case dd:b.onclick=function(){var e=bd(c);F(c,e);var f=window.location.href;
f=0<=f.indexOf("pattern=")?f.replace(/(pattern=)[^&]*/,"$1"+e.replace(/\$/g,"$$$$")):f+((0>f.indexOf("?")?"?":"&")+"pattern="+e);window.location=f};break;case cd:b.onkeypress=function(e){b.value=String.fromCharCode(e.charCode);var f=c.la[ed];f&&(f.textContent=b.value);e.preventDefault()};break;default:a.startsWith(fd)?b.onclick=function(){Tc(c,a)}:(d=this.ga[Zc])&&d[a]&&(b.onclick=function(){Rc(c,a)})}X.prototype.Oa.call(this,a,b)};
function $c(a){var b={},c;for(c in a){for(var d=c,e=a[c],f=0;f<e.length;f++)if(0==e[f].indexOf("#N")){d=e[f].substr(2).trim();break}b[d]=c}return b}
u.pc=function(a){a=void 0===a?0:a;var b=0;if(0<=a){var c=1;do{switch(this.ua){case gd:var d=0;for(var e=this.aa,f=e.da,g=e.ea,h=this.Ha,m=0;m<g;m++)for(var n=0;n<f;n++){var l=h,k=!1,p=4*(m*e.ca+n);if(p<=e.aa.length-4&&e.aa[p+1]){k=!0;p=e.aa[p+2];for(var r=l.length-1;0<=r;r--)l[r]=p&15,p>>>=4}if(k){d++;if(h[0])h[0]--;else{k=(l=nc(e,n,m))||0;switch(l){case 1:if(k=gc,h[0]=h[2],h[0]){h[0]--;break}case gc:if(h[3]&&(k=this.ha.indexOf(e.aa[4*(m*e.ca+n)+1]||e.ha),0<=k)){for(k+=h[3];k>=this.ha.length;)k-=
this.ha.length;qc(e,n,m,this.ha[k])}k=1;h[0]=h[1];h[0]&&h[0]--}k!==l&&sc(e,n,m,k)}rc(e,n,m,h)}}break;case hd:c=a||c;d=c;d=void 0===d?1:d;e=0;f=this.aa;g=f.ca;h=f.ea;if(f.qa||!id(this,d))d=0;else{m=f.aa;p=4*d;n=4*g;k=r=l=0;for(this.ma=this.wa=-1;l<g-d;){for(var t=1,x=k,w=0;w<h;w++){var q=m[k],D=m[k]=m[k+p];q=D!==q?W:0;m[k+1]=m[k+p+1];m[k+2]=m[k+p+2];m[k+3]=m[k+p+3]|q;D&&(e++,t=0);k+=n}k=x+4;l++<f.da&&(t?r++:(0>this.ma&&(this.ma=r),r=0))}0>this.ma&&(this.ma=r);for(this.wa=r;l<g;){p=k;for(r=0;r<h;r++)pc(f,
m,k),k+=n;k=p+4;l++}f.ja=!0;f.qa=d;d=e}break;case jd:d=0;e=this.aa;f=e.aa;g=e;g.ra||(g.ra=Array(g.Wa),ec(g,g.ra));g=g.ra;h=e.da;m=e.ea;n=4*h+e.Xa;l=m*n;k=0;p=k-n;r=p-4;t=p+4;x=k-4;w=k+4;D=k+n;q=D-4;for(var H=D+4,K=0;K<m;K++){K?K==m-1&&(this.ja?(D-=l,q-=l,H-=l):D=q=H=l):this.ja?(p+=l,r+=l,t+=l):p=r=t=l;for(var Y=0;Y<h;Y++){Y?1==Y?this.ja?(x-=n,r-=n,q-=n):(x=k-4,r=p-4,q=D-4):Y==h-1&&(this.ja?(w-=n,t-=n,H-=n):w=t=H=l):this.ja?(x+=n,r+=n,q+=n):x=r=q=l;var Z=f[k],Q=f[r]+f[p]+f[t]+f[w]+f[H]+f[D]+f[q]+f[x];
3==Q?Z=1:2!=Q&&(Z=gc);g[k]=Z;g[k+1]=f[k+1];g[k+2]=f[k+2];g[k+3]=f[k+3]|(f[k]!==Z?W:0);k+=4;r+=4;p+=4;t+=4;w+=4;H+=4;D+=4;q+=4;x+=4;1==Z&&d++}this.ja?(K||(p-=l,r-=l,t-=l),w+=n,t+=n,H+=n):(K||(p=k-n,r=p-4),w=k+4,t=p+4,H=D+4)}f=e.aa;e.aa=e.ra;e.ra=f;e.ja=!0}a||F(this,"active cells: "+d);b+=c}while(b<a)}return b};u.qc=function(){};u.oc=function(){return 0};function kd(a,b){var c=0;(a=a.la[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}
function Qc(a,b){var c=0;if(b&&(b=a.la[ld])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=kd(a,md)+kd(a,nd),!(d&1)&&c==d-1||0>b.selectedIndex||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<od.length;b++)c.push(kd(a,od[b]));return c}
function Rc(a,b){var c=a.aa,d=-1,e=-1,f="";b||a.pa.match(/^[0-9]/)||(b=a.pa);if(b){var g=a.ga[Zc];g=g&&g[b];if(!g)return F(a,"unknown pattern: "+b),!1;F(a,"loading pattern '"+b+"'");for(var h=b=0;b<g.length;b++){var m=g[b];if("#"==m[0])F(a,m);else if(h++){var n=m.indexOf("!");if(0<=n){f+=m.substr(0,n);break}f+=m}else{var l=m.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!l)return F(a,"unrecognized header line"),!1;var k=+l[1];var p=+l[2];l=l[3]}}}else{if(!a.pa)return!1;
f=0;l=a.pa.split("/");5==l.length&&(d=+l[f++],e=+l[f++]);if(3==l.length||5==l.length)k=+l[f++],p=+l[f++],f=l[f];else return F(a,"unrecognized pattern: "+a.pa),!1;l=a.ua}if(l!=a.ua)return F(a,"unsupported rule: "+l),!1;0>d&&(d=c.ca-k>>1);0>e&&(e=c.ea-p>>1);return 0>d||d+k>c.ca||0>e||e+p>c.ea?(a.ka("pattern too large (%d,%d)\n",k,p),!1):0<pd(a,d,e,f)}
function pd(a,b,c,d,e){e=void 0===e?!1:e;var f=a.aa,g=[0,0,0,1],h=0,m=!1,n=!1;d=d.split(/([a-z$])/i);e||yb(f);for(var l=0,k=b,p=0;l<d.length-1;){var r=d[l++],t=d[l++],x=+r;for(r=""===r?1:x;r--;){var w=0,q=!1;switch(t){case "$":m=n=!1;b=k;c++;break;case "C":h=x;n=!0;break;case "R":g[0]=x;m=!0;break;case "G":g[1]=x;m=!0;break;case "B":g[2]=x;m=!0;break;case "A":g[3]=x;m=!0;break;case "b":q=sc(f,b,c,gc);w++;break;case "o":q=sc(f,b,c,1);w++;break;default:a.ka("unrecognized pattern token: %s\n",t)}if(null==
q)a.ka("invalid pattern position (%d,%d)\n",b,c);else{if(m){q=f;var D=g;q=4>D.length||1==D[3]?q.ya("#%02x%02x%02x",D[0],D[1],D[2]):q.ya("rgba(%d,%d,%d,%d)",D[0],D[1],D[2],D[3]);qc(f,b,c,q)}n&&(q=4*(c*f.ca+b),q<=f.aa.length-4&&f.aa[q+2]!=h&&(f.aa[q+2]=h));p<b&&(p=b);b+=w}}}e||Bb(f,!0);return 0>(p-=k-1)?0:p}
u.Ka=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return F(this,"Invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.ka("Saved state version mismatch: %3.2f\n",c),!1;try{this.ca=b.shift(),this.da=b.shift(),this.ea=b.shift(),this.ba=b.shift()}catch(d){return F(this,"Controller state error: "+d.message),!1}return Pa().message||Pa().pattern||Pa()[Vc]||!(a=a.stateLEDs||a[1])||!this.aa||this.aa.Ka(a)?!0:!1};
u.Bd=function(a){var b="",c=a.shift();switch(a.shift()[0]){case "s":Pc(this,a.join(" "));break;case "?":b="";qd.forEach(function(d){b+=d+"\n"});b&&(b="additional commands:\n"+b);break;default:c&&(b="unrecognized command '"+c+"' (try '?')\n")}return b};u.Bb=function(a){return a&&this.Ka(a)?!0:!1};u.Ea=function(a){a?this.time.start():Ac(this.time)};u.Ga=function(){F(this,"reset");yb(this.aa,!0);lc(this.aa,!0);this.za&&Pc(this,this.za)};u.Cb=function(a){this.La(a)};u.Cd=function(){this.time.aa||Bb(this.aa)};
function id(a,b,c,d){b=void 0===b?1:b;c&&(a.ea=c,a.ba=d);switch(a.ea){case rd:return!1;case sd:case td:if(0<a.ba)return a.ba-=b,!0;break;case ud:if(0<a.ba)return a.ba-=b,!1;break;case vd:if(a.ma>a.wa)return!0;break;case wd:lc(a.aa,!1);a.ea=ud;break;case xd:lc(a.aa,!0);a.ea=ud;break;default:return!1}if(c)a=!1;else a:if(b=void 0===b?1:b,a.ca){a.da>=a.ca.length&&(a.da=0);c=a.ca[a.da++];if("$"==c){d=0;for(var e=a.da;e<a.ca.length;){var f=a.ca.charCodeAt(e)-48;if(0>f||9<f)break;d=10*d+f;e++}if(e<a.ca.length)if(f=
a.ca[e++],"$"==f)a.da=e;else{var g=yd[f];if(g){a.da=e;a=id(a,b,g,d);break a}F(a,"unrecognized message code: $"+f)}}" "==c?a.ba+=2:(d=a.aa.da+1,e=0>a.ba?a.ba:0,c=a.ta[c]||a.ta[c.toUpperCase()],f=Math.round((a.aa.xa-a.ta.height)/2),c&&(a.ba+=pd(a,d+e,0>f?0:f,c,!0)),a.ba+=2-b);a.ea=td;a=!0}else a.ea=rd,a=!1;return a}
function bd(a,b){function c(Z){var Q=!1;null==l[3]&&(l[3]=1);if(w){if(m){if(l[0]!==t[0]||l[1]!==t[1]||l[2]!==t[2]||l[3]!==t[3])Q=!0;Y!==x&&(Q=!0)}n!==r&&(Q=!0);if(Q||Z&&r)m&&(k[0]!==t[0]&&(k[0]=t[0],e+=(t[0]||"")+"R"),k[1]!==t[1]&&(k[1]=t[1],e+=(t[1]||"")+"G"),k[2]!==t[2]&&(k[2]=t[2],e+=(t[2]||"")+"B"),k[3]!==t[3]&&(k[3]=t[3],e+=(t[3]||"")+"A"),p!==x&&(p=x,e+=(x||"")+"C")),1<w&&(e+=w),e+=1===r?"o":"b",Q=!0}Z?(e+="$",w=0):(Q?w=1:w++,r=n,t[0]=l[0],t[1]=l[1],t[2]=l[2],t[3]=l[3],x=Y)}var d=a.aa,e="",
f=0,g=a.aa.ca,h=a.aa.ea,m=!!a.ha.length,n,l=[0,0,0],k=[0,0,0,1],p=0,r=0,t=[0,0,0,1],x=0,w=0;a=0;var q=d.ca-1,D=d.ea-1;if(b){b&&(a=q,q=0);for(g=0;g<d.ea;g++)for(h=0;h<d.ca;h++)(n=nc(d,h,g))&&b&&(a>h&&(a=h),q<h&&(q=h));g=q-a+1;h=D+1;0>g&&(g=0);0>h&&(h=0)}for(var H=0;H<=D;H++){for(var K=a;K<=q;K++){n=nc(d,K,H);oc(d.aa[4*(H*d.ca+K)+1]||d.ha,l);var Y=mc(d,K,H);c()}c(!0)}if(!b)for(;"$"==e[0];)f++,h--,e=e.slice(1);for(;"$$"==e.slice(-2);)h--,e=e.slice(0,-1);"$"==e&&(h=0);e=(b?"":"0/"+f+"/")+g+"/"+h+"/"+
e.slice(0,-1);return e=e.replace(/\$+$/,"")}u.La=function(a){var b=[],c=[];b.push(2);b.push(this.ca);b.push(this.da);b.push(this.ea);b.push(this.ba);this.aa&&this.aa.La(c);a.push(b);a.push(c)};function Pc(a,b){a.ca!=b&&(b&&F(a,"new message: '"+b+"'"),a.ca=b);a.ea=sd;a.da=a.ba=0}u.toString=function(){return""};
function Uc(a,b){var c=a.la[Vc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.aa;a.Ra&&(a.Ra.style.backgroundImage=b?"url('"+b+"')":"none")}}
function Yc(a,b){var c=a.la[Wc],d=a.la[Xc];b=b===Wc;c&&!c.options.length&&(Fa(c,a.ga.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.fa=a.ga.colors[c.options[c.selectedIndex].value];for(var e in a.fa)if(b=a.ga[e.toLowerCase()])"#"!=b[0]&&(b="#"+b),F(a,"overriding color '"+e+"' with "+b+" (formerly "+a.fa[e]+")"),a.fa[e]=b;Fa(d,a.fa,!0)}c&&d&&d.options.length&&(a.ia=d.options[d.selectedIndex].value,Tc(a))}
function Sc(a,b){var c=a.la[Xc];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.ia=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function Tc(a,b){var c=1,d;!b&&a.ia&&(d=a.la[zd])&&(d.style.backgroundColor=a.ia);if(a.fa)for(var e in a.fa){var f=a.fa[e];a.ha&&(a.ha[c-1]=f);var g=fd+c++;d=a.la[g];if(!d)break;d.style.display="inline-block";g==b&&Sc(a,f);if(b&&b!=g||f!=a.ia)f=bc(f,1,.5);d.style.backgroundColor=f}for(;;){b=fd+c++;b=a.la[b];if(!b)break;b.style.display="none"}}
var Wc="colorPalette",Xc="colorSelection",fd="colorSwatch",zd="colorSwatchSelected",ld="countInit",md="countOn",nd="countOff",Vc="backgroundImage",Zc="patterns",cd="symbolInput",ed="symbolPreview",ad="save",dd="saveToURL",od=[null,md,nd,"countCycle"],qd=["s\t\tset string"],sd="load",td="scroll",ud="pause",rd="halt",vd="center",wd="off",xd="on",yd={b:wd,c:vd,h:rd,o:xd,p:ud,s:td},gd="A4",hd="L1",jd="B3/S23",Oc={Helvetica:{width:16,height:16,0:"$2b2o$bo2bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$bo2bo$2b2o",
1:"$3bo$2b2o$4o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo",2:"$2b3o$bo3bo$o5bo$o5bo$6bo$5bo$3b2o$2bo$bo$o$7o",3:"$b4o$o4bo$o4bo$5bo$4bo$2b2o$4bo$5bo$o4bo$o4bo$b4o",4:"$5bo$4b2o$3bobo$2bo2bo$bo3bo$o4bo$o4bo$8o$5bo$5bo$5bo",5:"$6o$o$o$o$4o$4bo$5bo$5bo$5bo$o3bo$b3o",6:"$2b4o$bo4bo$o$o$o$ob4o$2o4bo$o5bo$o5bo$bo4bo$2b4o",7:"$8o$7bo$6bo$5bo$4bo$4bo$3bo$3bo$2bo$2bo$2bo",8:"$b4o$o4bo$o4bo$o4bo$bo2bo$2b2o$bo2bo$o4bo$o4bo$o4bo$b4o",9:"$b4o$o4bo$o5bo$o5bo$o4b2o$b4obo$6bo$6bo$6bo$o4bo$b4o",A:"$3b2o$2bo2bo$bo4bo$bo4bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo",
B:"$6o$o5bo$o5bo$o5bo$o4bo$7o$o6bo$o6bo$o6bo$o6bo$7o",C:"$2b4o$bo4bo$o6bo$o$o$o$o$o$o6bo$bo4bo$2b4o",D:"$6o$o5bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o5bo$6o",E:"$7o$o$o$o$o$6o$o$o$o$o$7o",F:"$7o$o$o$o$o$6o$o$o$o$o$o",G:"$2b4o$bo4bo$o$o$o$o3b4o$o6bo$o6bo$o6bo$bo4bo$2b4o",H:"$o6bo$o6bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo$o6bo$o6bo",I:"$o$o$o$o$o$o$o$o$o$o$o",J:"$5bo$5bo$5bo$5bo$5bo$5bo$5bo$o4bo$o4bo$o4bo$b4o",K:"$o6bo$o5bo$o4bo$o3bo$o2bo$ob2o$2o2bo$o4bo$o5bo$o6bo$o7bo",L:"$o$o$o$o$o$o$o$o$o$o$7o",M:"$o8bo$2o6b2o$obo4bobo$obo4bobo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o8bo$o8bo$o8bo$o8bo",
N:"$2o5bo$obo4bo$obo4bo$o2bo3bo$o2bo3bo$o3bo2bo$o3bo2bo$o4bobo$o4bobo$o4bobo$o5b2o",O:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo6bo$2bo4bo$3b4o",P:"$6o$o5bo$o6bo$o6bo$o6bo$o5bo$6o$o$o$o$o",Q:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo4bobo$2bo4bo$3b4obo$9bo",R:"$6o$o5bo$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo$o6bo",S:"$2b4o$bo4bo$o6bo$o$bo$2b4o$6bo$7bo$o6bo$bo4bo$2b4o",T:"$9o$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo",U:"$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",V:"$o8bo$o8bo$bo6bo$bo6bo$bo6bo$2bo4bo$2bo4bo$2bo4bo$3bo2bo$3bo2bo$4b2o",
W:"$o4b2o4bo$o4b2o4bo$o4b2o4bo$o3bo2bo3bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$2b2o4b2o$2b2o4b2o$2b2o4b2o",X:"$o8bo$bo6bo$2bo4bo$3bo2bo$4b2o$4b2o$4b2o$3bo2bo$2bo4bo$bo6bo$o8bo",Y:"$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$9o$8bo$7bo$6bo$5bo$4bo$3bo$2bo$bo$o$9o",a:"$$$$b4o$o4bo$5bo$b5o$o4bo$o4bo$o3b2o$b3obo",b:"$o$o$o$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o",c:"$$$$2b4o$bo4bo$o$o$o$o$bo4bo$2b4o",d:"$6bo$6bo$6bo$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo",e:"$$$$2b3o$bo3bo$o5bo$7o$o$o$bo4bo$2b4o",
f:"$2b2o$bo2bo$bo$bo$4o$bo$bo$bo$bo$bo$bo",g:"$$$$2b2obo$bo2b2o$o4bo$o4bo$o4bo$bo2b2o$2b2obo$5bo$5bo$o4bo$b4o",h:"$o$o$o$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",i:"$$o$$o$o$o$o$o$o$o$o",j:"$$3bo$$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$o2bo$b2o",k:"$o$o$o$o4bo$o3bo$o2bo$obo$2obo$o3bo$o4bo$o5bo",l:"$o$o$o$o$o$o$o$o$o$o$o",m:"$$$$ob2o3b2o$2o2bobo2bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo",n:"$$$$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",o:"$$$$2b4o$bo4bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",p:"$$$$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o$o$o$o",
q:"$$$$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo$6bo$6bo$6bo",r:"$$$$ob2o$2o2bo$o$o$o$o$o$o",s:"$$$$b4o$o4bo$o$b4o$5bo$5bo$o4bo$b4o",t:"$$bo$bo$4o$bo$bo$bo$bo$bo$bo2bo$2b2o",u:"$$$$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o3b2o$b3obo",v:"$$$$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo",w:"$$$$o3b2o3bo$o3b2o3bo$o3b2o3bo$o3b2o3bo$bobo2bobo$bobo2bobo$bobo2bobo$2bo4bo",x:"$$$$$o5bo$bo3bo$2bobo$3bo$2bobo$bo3bo$o5bo",y:"$$$$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$2bo$2o",z:"$$$$6o$5bo$4bo$3bo$2bo$bo$o$6o",
"!":"$o$o$o$o$o$o$o$o$$o$o",'"':"$obo$obo$obo$obo","#":"$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo",$:"3bo$2b4o$bobo2bo$o2bo$o2bo$bobo$2b3o$3bobo$3bo2bo$3bo2bo$o2bobo$b4o$3bo","%":"$b2o7bo$o2bo5bo$o2bo4bo$o2bo3bo$o2bo2bo$b2o2bo2b2o$4bo2bo2bo$3bo3bo2bo$2bo4bo2bo$bo5bo2bo$o7b2o","&":"$b3o$o3bo$o3bo$o3bo$bobo$2bo$bobo$o3bobo$o4bo$o3bobo$b3o3bo","'":"$o$o$o$o","(":"$3bo$2bo$bo$bo$o$o$o$o$o$o$bo$bo$2bo$3bo",")":"$o$bo$2bo$2bo$3bo$3bo$3bo$3bo$3bo$3bo$2bo$2bo$bo$o","*":"2bo$obobo$b3o$b3o$o3bo",
"+":"$$$$3bo$3bo$3bo$7o$3bo$3bo$3bo",",":"$$$$$$$$$$2o$2o$bo$o",".":"$$$$$$$$$$2o$2o","/":"$3bo$3bo$2bo$2bo$2bo$bo$bo$bo$o$o$o",":":"$$$$2o$2o$$$$$2o$2o",";":"$$$$2o$2o$$$$$2o$2o$bo$o","<":"$$$$6b2o$4b2o$2b2o$2o$2o$2b2o$4b2o$6b2o",">":"$$$$2o$2b2o$4b2o$6b2o$6b2o$4b2o$2b2o$2o","=":"$$$$$$8o$$$8o","?":"$b4o$o4bo$o4bo$5bo$4bo$3bo$2bo$2bo$$2bo$2bo","@":"$3b4o$2bo4bo$bo6bo$o3b2o3bo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o5b3o$bo$2bo5bo$3b5o","[":"$3o$o$o$o$o$o$o$o$o$o$o$o$o$3o","]":"$3o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$3o",
"\\":"$o$o$bo$bo$bo$2bo$2bo$2bo$3bo$3bo$3bo","^":"$2b2o$2b2o$bo2bo$bo2bo$o4bo$o4bo",_:"$$$$$$$$$$$$$8o","`":"o$bo$2bo","{":"$2b2o$bo$bo$bo$bo$bo$bo$o$bo$bo$bo$bo$bo$2b2o","}":"$2o$2bo$2bo$2bo$2bo$2bo$2bo$3bo$2bo$2bo$2bo$2bo$2bo$2o","|":"o$o$o$o$o$o$o$o$o$o$o$o$o$o$o","~":"$$$$$$b3o3bo$o3b3o"},ATT4425:{width:9,height:13,A:"$3bo$3bo$2bobo$2bobo$bo3bo$bo3bo$7o$o5bo$o5bo",B:"$6o$bo4bo$bo4bo$bo3bo$b4o$bo3bo$bo4bo$bo4bo$6o",C:"$2b5o$bo$o$o$o$o$o$bo$2b5o",D:"$5o$bo3bo$bo4bo$bo4bo$bo4bo$bo4bo$bo4bo$bo3bo$5o",
E:"$6o$o$o$o$5o$o$o$o$6o",F:"$6o$o$o$o$5o$o$o$o$o",G:"$2b3o$bo3bo$o$o$o$o3b3o$o4bo$bo3bo$2b3o",H:"$o5bo$o5bo$o5bo$o5bo$7o$o5bo$o5bo$o5bo$o5bo",I:"$3o$bo$bo$bo$bo$bo$bo$bo$3o",J:"$4bo$4bo$4bo$4bo$4bo$4bo$o3bo$o3bo$b3o",K:"$o5bo$o4bo$o3bo$o2bo$3o$o2bo$o3bo$o4bo$o5bo",L:"$o$o$o$o$o$o$o$o$7o",M:"$o5bo$2o3b2o$obobobo$o2bo2bo$o5bo$o5bo$o5bo$o5bo$o5bo",N:"$o5bo$2o4bo$obo3bo$obo3bo$o2bo2bo$o3bobo$o3bobo$o4b2o$o5bo",O:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",P:"$6o$o5bo$o5bo$o5bo$6o$o$o$o$o",Q:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o$3bo2bo$4b3o",
R:"$6o$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo",S:"$2b3o$bo3bo$bo$2bo$3bo$4bo$o4bo$bo3bo$2b3o",T:"$5o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo",U:"$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",V:"$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo",W:"$o5bo$o5bo$o2bo2bo$o2bo2bo$obobobo$obobobo$2o3b2o$2o3b2o$o5bo",X:"$o5bo$bo3bo$bo3bo$2bobo$3bo$2bobo$bo3bo$bo3bo$o5bo",Y:"$o5bo$o5bo$bo3bo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$7o$6bo$5bo$4bo$3bo$2bo$bo$o$7o"}};B.LEDCtrl=Nc;
function Ad(a,b,c){O.call(this,a,a);var d=this;this.ca=!1;this.ha=c;this.ba="";this.fa=this.ea=!1;lb(this,!1);this.Ca=A.Cc;b=b.trim();"{"==b[0]?Bd(this,b):(this.ba=b,Oa(this.ba,function(e,f,g,h){4==g&&(!h&&f?(Bd(d,f),Cd(d)):d.ka("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.fa=!0;Cd(d)});window.addEventListener(Sa("iOS")?"pagehide":Sa("Opera")?"unload":"beforeunload",function(){Dd(d)});window.addEventListener("pageshow",function(){d.ca||d.Ea(!0)})}
y(Ad,O);Ad.prototype.Oa=function(a,b){var c=this;switch(a){case Ed:b.onclick=function(){c.Ea()};break;case Fd:b.onclick=function(){c.Ga()}}O.prototype.Oa.call(this,a,b)};
function Cd(a){var b=!0;if(a.ea&&a.fa){for(var c in a.aa){var d=void 0,e=a.aa[c];try{d=e["class"],B[d]?"Machine"==d?(a.ka("PCjs %s v%3.2f\n%s\n",e.name,2,"Copyright \u00a9 2012-2023 Jeff Parsons <Jeff@pcjs.org>"),a.ba&&a.ka("Configuration: %s\n",a.ba)):new B[d](a.na,c,e):a.ka('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.ka('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),nb(a,c)}}if(a.da){var f=Ta(a);jb(a,function(g){return g.Bb&&!g.Bb(f)?(g.ka('unable to restore state for device "%s"\n',
g.va),!1):!0})}lb(a,!0);mb(a,a.Ea.bind(a,b))||a.ka("machine %s not ready to power, waiting for device(s)\n",a.na)}}
function Bd(a,b){try{a.aa=JSON.parse(b);var c=a.aa[a.na];if(!c){c=a.aa[va(a.ba)];if(!c)throw Error("configuration missing machine ID");a.aa[a.na]=c}ib(a,c,["autoSave","autoStart"]);a.da=!1!==a.ga.autoSave;a.ia=!1!==a.ga.autoStart;if(a.ha){var d=eval("("+a.ha+")"),e;for(e in d)a.ga[e]=d[e]}a.ea=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),F(a,"machine '"+a.na+"' initialization error: "+c)}}
Ad.prototype.Ea=function(a){a=void 0===a?!this.ca:a;if(kb(this)){var b=this;a&&F(this,"power on");jb(this,function(c){c.Ea&&c!=b&&("CPU"!=c.ga["class"]||b.ia&&kb(b)?c.Ea(a):c.time.update(!0));return!0});(this.ca=a)||F(this,"power off")}};Ad.prototype.Ga=function(){if(kb(this)){var a=this;jb(this,function(b){b.Ga&&b!=a&&b.Ga();return!0});F(this,"reset")}};function Dd(a){if(a.da){var b=[];jb(a,function(c){c.Cb&&c.Cb(b);return!0});Za(a,b)}a.Ea(!1)}var Ed="power",Fd="reset";
window.LEDs=function(a,b,c){var d=new Ad(a,b,c);window.command=function(e){return Ua(d,e)};return d};B.Machine=Ad;})()

//# sourceMappingURL=led.js.map
