(function(){/*
 https://www.pcjs.org/machines/lib/defs.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/numio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/stdio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/webio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/device.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/bus/bus.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/bus/memory.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/bus/rom.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/input.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/led/led.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/time.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/cpu/cpu.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/led/ledctrl.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/machines/lib/machine.js (C) 2012-2020 Jeff Parsons
*/
var u;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function x(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={wb:!0},fa={};try{fa.__proto__=ea;da=fa.wb;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function y(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var ia="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ja(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var z=ja(this);function A(a,b){if(b){var c=z;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ia(c,a,{configurable:!0,writable:!0,value:b})}}
A("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});A("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});function ka(){ka=function(){};z.Symbol||(z.Symbol=la)}function ma(a,b){this.aa=a;ia(this,"description",{configurable:!0,writable:!0,value:b})}ma.prototype.toString=function(){return this.aa};
var la=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ma("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function na(){ka();var a=z.Symbol.iterator;a||(a=z.Symbol.iterator=z.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ia(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return oa(aa(this))}});na=function(){}}function oa(a){na();a={next:a};a[z.Symbol.iterator]=function(){return this};return a}
function pa(a,b){na();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}A("Array.prototype.keys",function(a){return a?a:function(){return pa(this,function(b){return b})}});A("Array.prototype.values",function(a){return a?a:function(){return pa(this,function(b,c){return c})}});
A("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});A("Number.parseInt",function(a){return a||parseInt});
A("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var f=0;f<e&&c<d;)if(this[c++]!=b[f++])return!1;return f>=e}});var qa=new ArrayBuffer(2);
(new DataView(qa)).setUint16(0,256,!0);new Uint16Array(qa);function ra(){}var B={};B.Defs=ra;function sa(){}y(sa,ra);function ta(a,b){var c=a/D|0,d=b/D|0;return(a&b)==(b|0)&&(c&d)==d}function ua(a){for(var b=0,c=0,d=[];b<a.length;){for(var e=a[b],f=b+1;f<a.length&&a[f]===e;)f++;d[c++]=f-b;d[c++]=e;b=f}return d.length>=a.length?a:d}var D=Math.pow(2,32);B.NumIO=sa;function E(){this.mb={};for(var a=0;22>a;a++)this.mb["ACDFHIMNSTWYbdfjcsoXx%"[a]]=null}y(E,sa);u=E.prototype;
u.flush=function(){var a=va;va="";this.Va(a)};u.Wc=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,x(b)))};u.Va=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),wa||(wa=b),a=((b-wa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(va+a.substr(0,c)),va="",a=a.substr(c+1)),wa=null);va+=a;return a.length};
function G(a,b,c){a.Va(b+"\n",c)}u.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.Va(this.ya.apply(this,[a].concat(x(c))))};
u.ya=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(!c||!c.length)return a;d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([hlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var m=e[g+5];if(void 0===this.mb[m])d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+m;else{if(f<c.length){var h=c[f];"%"!=m&&f++}else h=c[c.length-1];var p=e[g+1],k=0<=p.indexOf("#"),l=0<=p.indexOf("0"),n=e[g+2];"*"==n?(n=h,h=f<c.length?c[f++]:c[c.length-1]):n=+n||0;var q=e[g+3];q=q?+q.substr(1):
-1;var t=null,w=0,v="";var r=0<="ACDFHIMNSTWY".indexOf(m)&&"object"!=typeof h?this.Wc(h):h;switch(m){case "C":h=k?"#":"";d+=isNaN(r.getTime())?void 0:this.ya(this.ya("%%%sW, %%%sF %%%sD, %%%sY",h),r);continue;case "D":h=k?r.getUTCDate():r.getDate();m="d";break;case "A":case "H":case "I":h=k?r.getUTCHours():r.getHours();"A"==m?(h=12>h?"am":"pm",m="s"):("I"==m&&(h=h?12<h?h-12:h:12),m="d");break;case "F":case "M":h=k?r.getUTCMonth():r.getMonth();"F"==m?(h=xa[h],m="s"):(h++,m="d");break;case "N":h=k?
r.getUTCMinutes():r.getMinutes();m="d";break;case "S":h=k?r.getUTCSeconds():r.getSeconds();m="d";break;case "T":h=k?"#":"";d+=isNaN(r.getTime())?void 0:this.ya(this.ya("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),r);continue;case "W":h=ya[k?r.getUTCDay():r.getDay()];m="s";break;case "Y":h=k?r.getUTCFullYear():r.getFullYear(),0<q&&(h%=Math.pow(10,q),q=-1),m="d"}switch(m){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=q&&(l=!0,n<q&&(n=q),q=-1);case "f":h=+h;r=h+"";0<=q&&(r=h.toFixed(q));
r.length<n&&(l?(0>h&&(n--,r=r.substr(1)),r=("0000000000"+r).slice(-n),0>h&&(r="-"+r)):r=("          "+r).slice(-n));d+=r;break;case "j":d+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=q&&(h=h.substr(0,q));h.length<n;)h=0<=p.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":w=8,k&&(v="0");case "X":t=za;case "x":r="";w||(w=16);!v&&k&&(v="0x");t||(t=Aa);h=Math.trunc(h);0<=q&&(l=!0,n<q&&(n=
q));l&&!n&&(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9,n+=v.length);n-=v.length;do k=h&w-1,h>>>=16==w?4:3,l||!r||k||h?r=t[k]+r:(v&&(r=v+r,v=""),0<n&&(r=" "+r));while(0<--n||h);d+=v+r;break;case "%":d+="%";break;default:this.mb[m]?d+=this.mb[m](m,p,n,q,h):d+="(unimplemented sprintf type: %"+m+")"}}}return d+=e[g]};var va="",wa=null,Aa="0123456789abcdef",za="0123456789ABCDEF",ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),xa="January February March April May June July August September October November December".split(" ");
B.StdIO=E;function H(a){E.call(this);this.ma={};this.Ca=0;this.na=this;a&&(this.na.Ca=0,this.na.Ma=[],this.na.Fa=0,this.na.nb={},this.na.pe=!1)}var Ba;y(H,E);u=H.prototype;u.Oa=function(a,b){var c=this,d=this;switch(a){case Ca.nc:b.onclick=function(){var e=c.Ya(Ca.sb,!0);e&&(e.value="")};break;case Ca.sb:Da(b),b.addEventListener("keydown",function(e){Ea(d,e,!0)}),b.addEventListener("keypress",function(e){Ea(d,e)})}};
function Fa(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value="string"==typeof b[e]?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}function Ga(a,b){var c=Ha.Eb;a.na.nb[c]||(a.na.nb[c]=[]);a.na.nb[c].push(b)}function Da(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}
u.error=function(a,b){b=this.ya.apply(this,[a].concat(x(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.ya.apply(this,[c].concat(x(b))))G(this,b),a||alert(b)};u.Ya=function(a){return this.ma[a]};function Ia(a){var b=window;if(b){do{for(var c=0;c<Ja.length;c++){var d=Ja[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Ka(a,b){return a.ha.bindings&&a.ha.bindings[b]}
function La(a){if(a=a.ma[Ma])var b=a.textContent;return b}function Na(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}function J(a,b,c,d){a=a.ha[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Oa(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Pa(){var a,b=Ba;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ba=b}return b}function Qa(a){if(void 0===K.pb){var b=!1;if(window)try{window.localStorage.setItem(K.Wa,K.Wa),b=window.localStorage.getItem(K.Wa)==K.Wa,window.localStorage.removeItem(K.Wa)}catch(c){G(a,c.message),b=!1}K.pb=b}return!!K.pb}
function Ra(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.Ca;return-1==(b|1)||ta(a.na.Ca,b)?!0:!1}function Sa(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Ta(a){var b=null;if(Qa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.pa))&&(b=JSON.parse(c))}catch(d){G(a,d.message)}}return b}
function Ea(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.na,f=b.target;if(c){a=!1;var g;c=f.value;var m=c.lastIndexOf("\n");d==L.Bb&&f.selectionStart<=m+1&&(a=!0);d==L.Nc?(a=!0,0<e.Fa&&(g=e.Ma[--e.Fa])):d==L.qc&&(a=!0,e.Fa<e.Ma.length&&(g=e.Ma[++e.Fa]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,m+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.Fa&&c+1==
g.length&&(f.value+=e.Ma[--e.Fa],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Ua(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&G(a,b.replace(/\n$/,""),!1))}}
function Va(a,b){if(void 0!=b){var c=a.na;try{if(b=b.trim())c.Fa<c.Ma.length&&b==c.Ma[c.Fa]?c.Fa++:(c.Ma.push(b),c.Fa=c.Ma.length);var d=b.split(" "),e=d[0],f=a.na.nb[Ha.Eb];switch(e[0]){case "m":if("?"==e[1]){var g="";Wa.forEach(function(l){g+=l+"\n"});g&&(g="message commands:\n"+g);break}g="";var m=void 0;e=d[d.length-1].toLowerCase();var h="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=h&&d.pop();1>=d.length&&(void 0!=h&&(m=h,h=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(M));
for(f=1;f<d.length;f++){e=d[f];var p=M[e];if(!p){g+="unrecognized message: "+e+"\n";break}void 0!=h&&Xa(a,p,h);if(void 0==m||m==Ra(a,p))g+=a.ya("%8s: %b\n",e,Ra(a,p))}Ra(a,0x800000000000)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",Ya.forEach(function(l){g+=l+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var k=f[a](d);if(void 0!=k){g=g?g+k:k;break}}}}catch(l){g="error: "+l.message+"\n"}}return g}
function Ua(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Va(a,b[d])}return c}u.Va=function(a,b){void 0==b&&(b=Ra(this,0x800000000000));if(!b){var c=this.Ya(Ca.sb,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Sa("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return E.prototype.Va.call(this,a,b)};
u.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return Ra(this,d)?E.prototype.ka.call.apply(E.prototype.ka,[this,a].concat(x(c))):0};function Za(a,b){if(Qa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.pa,b)}catch(c){G(a,c.message)}}}function $a(a,b,c){(a=a.ma[b])&&a.textContent!=c&&(a.textContent=c)}
function Xa(a,b,c){var d=!1;c?(c=a.na.Ca,a.na.Ca=(c|b)+(c/D|0|b/D|0)*D):(d=ta(a.na.Ca,0x800000000000)&&ta(b,0x800000000000),c=a.na.Ca,a.na.Ca=(c&~b)+((c/D|0)&~(b/D|0))*D);d&&a.flush()}
var Ca={nc:"clear",sb:"print"},Ya=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Wa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],M={all:0xffffffffffff,buffer:0x800000000000},Ha={Eb:"command"},ab={Fb:13,ob:65,Ab:66,Cb:67,Gb:68,E:69,Hb:70,Ib:71,Jb:72,Kb:73,Lb:74,Nb:75,Ob:76,Qb:77,Rb:78,Sb:79,Tb:80,Q:81,
Ub:82,Wb:83,Xb:84,Yb:85,Zb:86,$b:87,ac:88,bc:89,vb:90,wb:97,se:98,te:99,d:100,e:101,xe:102,ye:103,Ae:104,Be:105,Ce:106,k:107,De:108,Ee:109,n:110,Fe:111,p:112,q:113,r:114,Ge:115,t:116,He:117,Ie:118,Je:119,x:120,y:121,z:122},L={Bb:8,Kc:9,zc:10,Fb:13,Hc:16,oc:17,mc:18,fe:19,qb:20,gd:27,Jc:32,ie:33,he:34,fd:35,Cd:36,Pb:37,Nc:38,ub:39,zd:39,qc:40,wd:44,je:44,Dd:45,ed:46,yd:46,Bd:47,ZERO:48,ONE:49,Mc:50,Lc:51,yc:52,xc:53,Ic:54,Gc:55,rc:56,Ac:57,wc:59,vc:61,ob:65,Ab:66,Cb:67,Gb:68,E:69,Hb:70,Ib:71,Jb:72,
Kb:73,Lb:74,Nb:75,Ob:76,Qb:77,Rb:78,Sb:79,Tb:80,Q:81,Ub:82,Wb:83,Xb:84,Yb:85,Zb:86,$b:87,ac:88,bc:89,vb:90,Db:91,xd:91,vd:92,me:93,Ad:93,Hd:96,Yd:96,ud:96,Id:97,Wd:97,Jd:98,Vd:98,Kd:99,ae:99,Ld:100,Zd:100,Md:101,Sd:101,Nd:102,ce:102,Od:103,Xd:103,Pd:104,ee:104,Qd:105,be:105,$d:106,Rd:107,de:109,Td:110,Ud:111,hd:112,md:113,nd:114,od:115,pd:116,qd:117,rd:118,sd:119,td:120,jd:121,kd:122,ld:123,Bc:144,Ec:145,uc:173,Fc:186,sc:187,dd:188,pc:189,ge:190,oe:191,bd:192,Ed:219,cd:220,le:221,ke:222,tc:224,Fd:901,
qe:1E3},bb={},cb=(bb[L.wc]=L.Fc,bb[L.vc]=L.sc,bb[L.uc]=L.pc,bb[L.tc]=L.Db,bb),db={Pb:1,ub:2,Gd:3},O={},eb=(O[L.Bb]="\b",O[L.Kc]="\t",O[L.zc]="\n",O[L.Fb]="\r",O[L.Jc]=" ",O[L.ZERO]="0",O[L.ONE]="1",O[L.Mc]="2",O[L.Lc]="3",O[L.yc]="4",O[L.xc]="5",O[L.Ic]="6",O[L.Gc]="7",O[L.rc]="8",O[L.Ac]="9",O[L.ob]="A",O[L.Ab]="B",O[L.Cb]="C",O[L.Gb]="D",O[L.E]="E",O[L.Hb]="F",O[L.Ib]="G",O[L.Jb]="H",O[L.Kb]="I",O[L.Lb]="J",O[L.Nb]="K",O[L.Ob]="L",O[L.Qb]="M",O[L.Rb]="N",O[L.Sb]="O",O[L.Tb]="P",O[L.Q]="Q",O[L.Ub]=
"R",O[L.Wb]="S",O[L.Xb]="T",O[L.Yb]="U",O[L.Zb]="V",O[L.$b]="W",O[L.ac]="X",O[L.bc]="Y",O[L.vb]="Z",O[L.Pb]="Left",O[L.ub]="Right",O),Ja=["","moz","ms","webkit"],fb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",
cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",
floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",
lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",
mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",
sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},K={pb:void 0,Wa:"PCjs.localStorage"};B.WebIO=H;
function P(a,b,c,d){H.call(this,a==b);this.pa=a;this.wa=b;Q[this.pa]||(Q[this.pa]={});Q[this.pa][this.wa]&&this.ka("warning: machine configuration contains multiple '%s' devices\n",this.wa);Q[this.pa][this.wa]=this;this.id=this.pa+"."+this.wa;gb.push(this);this.na=hb(this,this.pa);this.ready=!0;ib(this,c,d);this.Mb=[]}y(P,H);
function ib(a,b,c){b=void 0===b?{}:b;c=void 0===c?[]:c;c=b.overrides||c;if(c.length){var d=Pa();for(q in d)if(0<=c.indexOf(q)){var e=d[q];var f=void 0;var g,m=void 0,h=e,p=10;if(h){p||(p=10);var k=0<h.indexOf(",");k&&(h=h.replace(/,/g,""));var l=g=h.charAt(0);"#"==g?(p=8,g=""):"$"==g&&(p=16,g="");l!=g?h=h.substr(1):(l=g=h.substr(0,2),"0b"==g&&k||"^B"==g?(p=2,g=""):"0o"==g||"^O"==g?(p=8,g=""):"^D"==g?(p=10,g=""):"0x"==g&&(p=16,g=""),l!=g&&(h=h.substr(2)));l=g=h.slice(-1);"Y"==g||"y"==g?(p=2,g=""):
"."==g?(p=10,g=""):"H"==g||"h"==g?(p=16,g=""):"K"==g?g="000":"M"==g?g="000000":"G"==g&&(g="000000000");l!=g&&(h=h.slice(0,-1)+g);l=0;10>=p&&(g=h.match(/(-?[0-9]+)B([0-9]*)$/))&&(h=g[1],l=35-((g[2]||35)&255));(p&&10!=p?16==p?null===h.match(/^-?[0-9a-f]+$/i):8==p?null===h.match(/^-?[0-7]+$/):2!=p||null===h.match(/^-?[01]+$/):null===h.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(h,p))||(l&&(0>f&&(f+=Math.pow(2,36)),f=0<l?f*Math.pow(2,l):Math.trunc(f/Math.pow(2,-l))),m=f)}f=m;void 0==f&&("true"==e?f=!0:
"false"==e?f=!1:(f=e,e='"'+e+'"'));b[q]=f;G(a,"overriding "+a.wa+" property '"+q+"' with "+e)}}a.ha=b;c=b.bindings;c=void 0===c?{}:c;a.ha.ma||(a.ha.ma=c);(d=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.wa);for(var n in c){e=c[n];if(d)n=e;else if(e.match(/^[0-9]+$/)){var q=+e;a.ma[n]=[];do{e=n+q++;e=document.getElementById(e);if(!e)break;a.ma[n].push(e)}while(1);continue}if(q=document.getElementById(e))a.ma[n]=q,a.Oa(n,q)}b=void 0===b?{}:b;a.version=2;
if(a.version){n="";var t;a.pa!=a.wa&&(t=hb(a,a.pa).version)&&t!=a.version&&(n="Machine");n||(t=b.version)&&t>a.version&&(n="Config");n&&(t=a.ya("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.ue,a.version,n,t),a.error("%s\n\nClearing your browser's cache may resolve the issue.",t))}}function jb(a,b){var c;try{var d=Q[a.pa];if(d)for(c in d){var e=d[c];if(e.wa!=e.pa&&!b(e))return!1}return!0}catch(f){a.ka("error while enumerating device '%s': %s\n",c,f.message)}return!1}
P.prototype.Ya=function(a,b){b=void 0===b?!1:b;if(a){var c=H.prototype.Ya.call(this,a,b);if(void 0===c&&b){b=Q[this.pa];for(var d in b)if(c=b[d].ma[a])break;c||(c=null);this.ma[a]=c}}return c};function hb(a,b){var c=b,d=a.pa,e=d.indexOf(".");0<e&&(d=d.substr(0,e),b=b.substr(e+1));b=(e=Q[d])&&e[b]||null;if(!b){for(e=0;e<gb.length;e++)if(gb[e].id===c){b=gb[e];break}if(!b)throw Error(a.ya('no "%s" device',c));}return b}
function R(a,b,c){var d=null,e=Q[a.pa];if(e)for(var f in e)if(e[f].ha["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.ya("no %s device",b));return d}function kb(a){return a==a.na&&a.ready?jb(a,function(b){return kb(b)}):a.ready}function lb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(kb(a)){for(;b=a.Mb.pop();)b();a!=a.na&&lb(a.na)}}function mb(a,b){if(kb(a))return b(),!0;a.Mb.push(b);return!1}
P.prototype.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&Ra(this,a)&&(void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1)),this.na.Ca&nb&&(void 0===this.Pa&&(this.Pa=R(this,"CPU")),this.Pa))?(a=c.shift(),H.prototype.ka.call(this,"%#06x: %s.%s\n",this.Pa.Xc,this.wa,this.ya.apply(this,[a].concat(x(c))).trim())):H.prototype.ka.call.apply(H.prototype.ka,[this,a].concat(x(c)))};function ob(a,b){(a=Q[a.pa])&&delete a[b]}var Q={},gb=[],nb=1;M.addr=nb;
M.bus=2;M.fault=4;M.memory=8;M.ports=16;M.chips=32;M.kbd=64;M.serial=128;M.misc=256;M.cpu=512;M.mmu=1024;M["int"]=2048;M.trap=4096;M.video=8192;M.monitor=16384;M.screen=32768;M.time=65536;M.timer=131072;M.event=262144;M.input=524288;M.key=1048576;M.mouse=2097152;M.touch=4194304;M.warn=8388608;M.halt=16777216;window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines=Q),window.PCjs.Components||(window.PCjs.Components=gb));B.Device=P;
function pb(a,b,c){P.call(this,a,b,c);this.type="static"==this.ha.type?qb:rb;this.fa=this.ha.addrWidth||16;this.ca=Math.pow(2,this.fa);this.aa=this.ha.blockSize||(16<this.fa?4096:1024);this.aa>this.ca&&(this.aa=this.ca);this.ja=this.ca/this.aa|0;this.da=Math.log2(this.aa)|0;this.ga=(1<<this.da)-1;this.ia=this.ha.dataWidth||8;this.ba=Array(this.ja);this.ea=0;a=new S(a,b+"[NONE]",{size:this.aa,bus:this.wa});for(b=0;b<this.ca;b+=this.aa)sb(this,b,this.aa,T.NONE,a);a=this.ea;this.ea+=this.type;a&&this.ea||
(this.$a=this.ab)}y(pb,P);
function sb(a,b,c,d,e){for(var f=b>>>a.da;0<c&&f<a.ba.length;){var g=f*a.aa,m=a.aa-(b-g);m>c&&(m=c);var h=a.ba[f];if(b!=g||m!=a.aa||h&&h.type!=T.NONE)break;var p=h=void 0,k=b,l=a.fa,n=16;l=void 0===l?0:l;h=void 0===h?0:h;var q="",t="",w=-1;n||(n=a.la||10);l&&(w=Math.ceil(l/Math.log2(n)));if(void 0==p)switch(n){case 8:p="0o";break;case 16:p="0x";break;case 10:t=".";default:p=""}isNaN(k)||"number"!=typeof k?(k=void 0,p=t=""):(0>k&&-1<k&&(k=-1),l&&(0>k&&(k+=Math.pow(2,l)),k>=Math.pow(2,l)&&(w=Math.ceil(Math.log(k)/
Math.log(n)))));for(l=h||-1;w--;){l||(q=","+q,l=h);if(void 0==k){if(q="?"+q,0>w)break}else{var v=k%n;k=Math.trunc(k/n);v+=0<=v&&9>=v?48:55;q=String.fromCharCode(v)+q;if(!k&&0>w)break}l--}h=a.wa+"["+(p+q+t)+"]";b=e?e.size==a.aa?e:new S(a.pa,h,{type:d,xb:b,size:m,bus:a.wa}):new S(a.pa,h,{type:d,xb:b,size:m,bus:a.wa});a.ba[f]=b;b=g+a.aa;c-=m;f++}}u=pb.prototype;u.Ea=function(){void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};u.Ga=function(){};u.yb=function(a){return a&&this.Ka(a)?!0:!1};u.zb=function(a){this.La(a)};
u.Ka=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if((this.type==rb||c.type&T.fb)&&c.Ka){var d=a.shift();if(!c.Ka(d))return!1}}return!0};u.La=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if((this.type==rb||c.type&T.fb)&&c.La){var d=[];c.La(d);a.push(d)}}};u.ab=function(a,b){this.ba[a>>>this.da].$a(a&this.ga,b)};var qb=0,rb=1;B.Bus=pb;
function S(a,b,c){P.call(this,a,b,c);this.xb=this.ha.addr;this.size=this.ha.size;this.type=this.ha.type||T.NONE;this.ca=(a=this.ha.bus)?hb(this,a):R(this,a="Bus");if(!this.ca)throw Error(this.ya("unable to find bus '%s'",a));this.ia=this.ca.ia;this.ea=this.ga=!1;this.values=this.ba=null;a=this.ab;if(this.ca.type==qb){a=this.Zc;if(b=8==this.ia)b=hb(this,this.pa),b=!1!==(b&&b.ha&&b.ha.ArrayBuffer||this.ha.ArrayBuffer);b&&(this.ga=!0)}switch(this.type){case T.NONE:this.$a=this.jc;break;case T.Vb:this.$a=
this.jc;break;case T.fb:this.$a=a}tb(this,this.ha.values);ub(this)}y(S,P);function tb(a,b){"string"==typeof b?(lb(a,!1),Oa(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);tb(a,g.values)}catch(m){a.ka("error (%s) parsing resource: %s\n",m.message,c)}lb(a,!0)}else a.ka("error (%d) loading resource: %s\n",f,c)})):a.ha.values=b}
function ub(a,b){if(a.type>T.NONE&&(a.ga?(a.ba=new ArrayBuffer(a.size),new DataView(a.ba,0,a.size),a.values=new Uint8Array(a.ba,0,a.size),new Uint16Array(a.ba,0,a.size>>1),new Int32Array(a.ba,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}u=S.prototype;
u.Ga=function(){if(this.ha.values)a:{var a=this.ca,b=this.xb,c=this.size,d=this.ha.values,e=0,f=b&a.ga;b>>>=a.da;c>d.length&&(c=d.length);for(;0<c&&b<a.ba.length;){var g=a.ba[b++];if(!g)break a;for(;0<c&&f<g.size;)g.ab(f++,d[e++]),c--;f=0}}else this.type&T.fb&&this.values&&this.values.fill(0)};u.jc=function(){};u.ab=function(a,b){this.values[a]=b};u.Zc=function(a,b){this.values[a]=b;this.ea=!0;this.$a=this.ab};
u.Ka=function(a){var b=a.shift();if(this.wa==b){this.ea=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}ub(this,a)}return!0}return!1};u.La=function(a){a.push(this.wa);a.push(this.ea);a.push(!1);a.push(this.values?ua(this.values):this.values)};var T={NONE:1,Vb:2,fb:4,ne:14,re:12};B.Memory=S;
function vb(a,b,c){c.type=T.Vb;S.call(this,a,b,c);sb(this.ca,this.ha.addr,this.ha.size,this.ha.type,this);mb(this,this.Ga.bind(this));this.Pa=this.Ja=void 0;if(B.LED&&this.ma[wb]){var d=this;this.da=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.fa=this.values.length/this.da|0;this.aa=new xb(a,b+"LEDs",{"class":"LED",bindings:{container:Ka(this,wb)},type:yb,cols:this.da,rows:this.fa,color:J(this,"colorROM","green"),backgroundColor:J(this,"backgroundColorROM","black"),persistent:!0}),
zb(this.aa,!0);this.ja=new Ab(a,b+"Input",{"class":"Input",location:[0,0,this.aa.Aa,this.aa.za,this.da,this.fa],bindings:{surface:Ka(this,wb)}});this.la=La(this)||"";Bb(this.ja,function(e,f){if(d.Pa){var g=d.la;0<=e&&0<=f&&(g="");$a(d,Ma,g)}})}}y(vb,S);
vb.prototype.Ka=function(a){var b=!0,c=a.shift();if(c&&this.aa){var d=c.length;this.aa.aa.length==d?(this.aa.aa=c,Cb(this.aa,!0)):(this.ka("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.ka("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};vb.prototype.Ea=function(){void 0===this.Pa&&(this.Pa=R(this,"CPU"));void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};
vb.prototype.La=function(a){this.aa&&(a.push(this.aa.aa),a.push(this.values))};var wb="array",Ma="cellDesc";B.ROM=vb;
function Ab(a,b,c){P.call(this,a,b,c);this.Ca=524288;this.ja=this.qa=null;this.time=R(this,"Time");this.na=R(this,"Machine");this.va=J(this,"drag",!1);this.la=J(this,"scroll",!1);this.Aa=J(this,"hexagonal",!1);this.ea=J(this,"releaseDelay",0,void 0);this.fa=!1;a=this.ha.map;this.ba=this.ca=null;if(a)if(a.length)this.ba=a;else{this.ca={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.ca[f]=
{keys:g,ze:e,state:0}}}this.ra=[];this.sa=[];this.da=this.ta=null;(a=this.ma[Db])&&Eb(this,a,this.Ya(c.focusBinding,!0),this.ha.location);this.Ga()}y(Ab,P);function Bb(a,b){a.qa=b}function Fb(a,b){a.ja=b}function Gb(a,b,c){for(var d=0;d<a.ra.length;d++){var e=a.ra[d];e.id===b&&e.fc(b,c)}}
function Eb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.ba||a.ca){var e={};e.$c=d[0]||0;e.ad=d[1]||0;e.Xa=d[2]||b.clientWidth;e.gb=d[3]||b.clientHeight;e.hb=d[4]||1;e.kb=d[5]||1;e.Rc=d[6]||b.naturalWidth||e.Xa;e.Tc=d[7]||b.naturalHeight||e.gb;e.kc=d[8]||0;e.lc=d[9]||0;e.Qc=d[10]||0;e.Sc=d[11]||0;a.ba?(e.jb=a.ba.length,e.Za=a.ba[0].length):(e.Za=e.hb,e.jb=e.kb,e.hb=e.kb=0);e.cc=e.Xa/(e.Za+e.Za*e.hb)|0;e.dc=e.gb/(e.jb+e.jb*e.kb)|0;e.Pc=e.cc*e.hb|0;e.ec=e.dc*e.kb|0;e.bb=e.lb=-1;Hb(a,b,e);Ib(a,b,e);a.time&&
a.ea&&(a.za=Jb(a.time,"timerInputRelease",function(){0>e.bb&&0>e.lb&&Kb(a,-1,-1)}))}if(a.ba||a.ca)a.time&&a.ea&&(a.Ba=Jb(a.time,"timerKeyRelease",function(){Lb(a)})),a.ga=0,a.oa="",a.ia=[],d=b,c&&(d=c,a.da||"BUTTON"!=c.nodeName||(d=document,a.da=c,Mb(a,b),a.ta=b)),Mb(a,d),a.da||(a.da=d)}function Nb(a){a.ea?Ob(a.time,a.Ba,a.ea):Lb(a)}
function Mb(a,b){function c(e,f,g){var m=document.activeElement;a.ka(1310720,"%s.onKey%s(%d): %5.2f (%s)\n",m.id||m.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.da&&e!=a.da&&e!=a.ta?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Pb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=Pb(a,
f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Pb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function Hb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.fa){var e=a.da;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||U(a,b,Qb,d,c)}});b.addEventListener("mousemove",function(d){a.fa||U(a,b,Rb,d,c)});b.addEventListener("mouseup",function(d){a.fa||d.button||U(a,b,Sb,d,c)});b.addEventListener("mouseout",function(d){a.fa||(0>c.bb?U(a,b,Rb,d,c):U(a,b,Sb,d,c))})}
function Ib(a,b,c){b.addEventListener("touchstart",function(d){a.la&&(a.fa=!0);U(a,b,Qb,d,c)});b.addEventListener("touchmove",function(d){U(a,b,Rb,d,c)});b.addEventListener("touchend",function(d){U(a,b,Sb,d,c)})}
function Pb(a,b,c,d){if(void 0!=c){var e=cb[b]||b;var f=eb[b];var g=Tb[e];d=d&&d.location==db.ub;g&Ub&&d&&(g>>=1);g&&(g&Vb&&(c=!(a.aa&g)),a.aa=c?a.aa|g:a.aa&~g,Gb(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=ab.ob&&b<=ab.vb?a.aa&(Wb|Xb)||(a.aa|=Xb,Gb(a,L.qb,!0)):b>=ab.wb&&b<=ab.z&&a.aa&Xb&&(a.aa&=~Xb,Gb(a,L.qb,!1));if(a.ba){if(void 0!=c)return!1;for(e=0;e<a.ba.length;e++)for(g=a.ba[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.ga?16>a.ia.length&&a.ia.push(b):(a.ga=1,a.oa=
f,Kb(a,d,e),Gb(a,f,!0),Nb(a)),!0}if(a.ca){if(void 0==c)return!0;b=Object.keys(a.ca);for(e=0;e<b.length;e++)if(g=b[e],0<=a.ca[g].keys.indexOf(f))return Gb(a,g,c),a.ca[g].state=c?1:0,!0}return!1}function Lb(a){1==a.ga?(a.ga++,Gb(a,a.oa,!1),a.oa="",Kb(a,-1,-1),Nb(a)):(a.ga=0,a.ia.length&&Pb(a,a.ia.shift()))}Ab.prototype.Ga=function(){this.aa=0;this.ua=this.xa=-1};
function U(a,b,c,d,e){var f=-1,g=-1,m=!1,h=-1,p=-1;if(c<Sb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(h=d.targetTouches[0].clientX,p=d.targetTouches[0].clientY,m=1<d.targetTouches.length):(h=d.clientX,p=d.clientY);var k=d.target.getBoundingClientRect();h-=k.left;p-=k.top;h=e.Rc/b.offsetWidth*h|0;p=e.Tc/b.offsetHeight*p|0;var l=h-e.$c;var n=p-e.ad;var q=k=!1;var t=h>=e.kc&&h<e.kc+e.Qc&&p>=e.lc&&p<e.lc+e.Sc;if(0<=l&&l<e.Xa&&0<=n+e.ec||t)if(m||a.la||d.preventDefault(),0<=l&&l<e.Xa&&
0<=n&&n<e.gb){q=!0;d=e.Xa/e.Za|0;var w=e.gb/e.jb|0,v=l/d|0,r=n/w|0;!a.Aa||r&1||(l-=d>>1,v=l/d|0,v==e.Za-1&&(l=-1));w=r*w+(e.ec>>1);l-=v*d+(e.Pc>>1);n-=w;0<=l&&l<e.cc&&0<=n&&n<e.dc&&(f=v,g=r,k=!0)}}l=l||0;n=n||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Qb||c==Sb)for(v=0;v<a.sa.length;v++)r=a.sa[v],c==Sb?r.fc(r.id,!1):(w=n/(b/r.we|0)|0,(l/(d/r.ve|0)|0)==r.Ke&&w==r.Le&&r.fc(r.id,!0));if(!m)if(c==Qb)e.bb=h,e.lb=p,q?(Kb(a,f,g),k&&a.ea&&Ob(a.time,a.za,a.ea,!0)):t&&a.na.Ea();else if(c==Rb)0<=e.bb&&0<=e.lb&&
a.va?Kb(a,f,g):a.qa&&a.qa(f,g);else if(c==Sb){if(c=a.ea)c=a.time,f=a.za,c=c.aa&&0<f&&f<=c.ba.length?0<=c.ba[f-1].Da:!1;c||Kb(a,-1,-1);e.bb=e.lb=-1}else G(a,"unrecognized action: "+c)}function Kb(a,b,c){if(b!=a.ua||c!=a.xa)a.ua=b,a.xa=c,a.ja&&a.ja(b,c)}var Qb=1,Rb=2,Sb=3,Db="surface",Wb=3,Ub=170,Xb=512,Vb=3584,X={},Tb=(X[L.Hc]=2,X[L.oc]=8,X[L.mc]=32,X[L.Db]=128,X[L.qb]=Xb,X[L.Bc]=1024,X[L.Ec]=2048,X);B.Input=Ab;
function xb(a,b,c){P.call(this,a,b,c,["color","backgroundColor"]);a=this.ma[Yb];if(!a)throw Error("LED "+this.ha.ma[Yb]+" binding for '"+Yb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Ra=a;this.type=Na(J(this,"type",yb,Zb),$b,ac);this.ia=bc[this.type][0];this.oa=bc[this.type][1];this.width=J(this,"width",this.ia,void 0);this.height=J(this,"height",this.oa,void 0);
this.da=J(this,"cols",1,void 0);this.ca=this.da+J(this,"colsExtra",0,void 0);this.xa=J(this,"rows",1,void 0);this.ea=this.xa+J(this,"rowsExtra",0,void 0);this.Aa=this.width*this.da;this.za=this.height*this.xa;this.ga=cc("black",0);this.fa=dc(this.ha.color)||this.ga;this.eb=cc(this.fa,1,.25);this.cb=cc(this.fa,1,2);this.la=dc(this.ha.backgroundColor);this.rb=J(this,"fixed",!1);this.rb||(b.style.width="100%",b.style.height="auto");this.Qa=J(this,"hexagonal",!1);this.tb=J(this,"highlight",!0);this.Ha=
J(this,"persistent",this.type<ac);b.setAttribute("width",this.Aa.toString());b.setAttribute("height",this.za.toString());b.style.backgroundColor=this.ga;a.appendChild(b);this.Sa=b.getContext("2d");if(this.sa=document.createElement("canvas"))this.sa.width=this.Na=this.ia*this.da,this.sa.height=this.ua=this.oa*this.xa,this.ba=this.sa.getContext("2d");this.Ta=(this.ea+1)*this.ca*4;this.aa=Array(this.Ta);this.ra=null;this.Ua=this.da<this.ca?4*(this.ca-this.da):0;this.ja=this.ta=!1;this.Ia=0;this.Ba=!0;
this.qa=0;this.va=-1;var d=this;this.time=R(this,"Time");ec(this.time,function(e){Cb(d,!1,e)});zb(d,!0)}y(xb,P);function zb(a,b){fc(a,a.aa);a.ja=a.ta=!0;b&&Cb(a,!0)}function gc(a){a.la?(a.ba.fillStyle=a.la,a.ba.fillRect(0,0,a.Na,a.ua)):a.ba.clearRect(0,0,a.Na,a.ua)}
function Cb(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.ja||b){if(a.type<ac){var d=0;if(!a.Ha||b)gc(a);else if(a.qa){d=a.da-a.qa;var e=a.ia*d;a.ba.drawImage(a.sa,a.ia*a.qa,0,e,a.ua,0,0,e,a.ua)}for(var f=e=0;f<a.ea;f++){for(var g=0;g<a.da;g++){var m=a.aa[e],h=a.aa[e+1]||a.ga,p=!1,k=!!(a.aa[e+3]&Y),l=a.tb&&e==a.va;!a.Ba&&m&&(m=hc,k=p=!0);if(k||l||b){if(g>=d)a:{k=a;var n=m;m=h;var q=g;h=f;var t=l;q=void 0===q?0:q;h=void 0===h?0:h;t=void 0===t?!1:t;var w=0;if(k.Qa&&!(h&1)&&(w=k.ia>>1,q==k.da-1))break a;
if(m&&m!=k.fa){t=t?cc(m,1,2):m;var v=cc(m,1,.25)}else t=t?k.cb:k.fa,v=k.eb;m=!1;n=n?t:v;t==k.ga&&(n=k.la,m=!0);t=q*k.ia+w;v=h*k.oa;k.Ha&&(q=q*k.ia+w,h*=k.oa,k.la?(k.ba.fillStyle=k.la,k.ba.fillRect(q,h,k.ia,k.oa)):k.ba.clearRect(q,h,k.ia,k.oa));k.ba.fillStyle=n;h=ic[k.type];3==h.length?(k.ba.beginPath(),k.ba.arc(t+h[0],v+h[1],h[2],0,2*Math.PI),m?(k.ba.globalCompositeOperation="destination-out",k.ba.fill(),k.ba.globalCompositeOperation="source-over"):k.ba.fill()):k.ba.fillRect(t+h[0],v+h[1],h[2],h[3])}a.aa[e+
3]=l||p?a.aa[e+3]|Y:a.aa[e+3]&~Y}e+=4}e+=a.Ua}a.qa=0}else{b="";for(d=0;d<a.aa.length;d+=4)b+=a.aa[d]||" ",a.aa[d+3]&jc&&(b+=".");gc(a);for(f=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;g=a;p=e;l=f;p=void 0===p?0:p;l=void 0===l?0:l;if(k=kc[k])for(h=0;h<k.length;h++)if(m=g,q=lc[k[h]]){w=(void 0===p?0:p)*m.ia;n=(void 0===l?0:l)*m.oa;m.ba.fillStyle=m.fa;m.ba.beginPath();if(3==q.length)m.ba.arc(w+q[0],n+q[1],q[2],0,2*Math.PI);else for(t=0;t<q.length;t+=2)t?m.ba.lineTo(w+q[t],n+q[t+1]):m.ba.moveTo(w+q[t],
n+q[t+1]);m.ba.closePath();m.ba.fill()}if(++e==a.da&&(e=0,++f==a.ea))break}}a.Sa.globalCompositeOperation=a.la&&a.fa!=a.ga?"source-over":"copy";a.Sa.drawImage(a.sa,0,0,a.Na,a.ua,0,0,a.Aa,a.za);a.ja=!1;a.va=-1}else a.Ha||a.ta||(!c||!a.Ia||c-a.Ia>=(1E3/60|0))&&zb(a,!0);a.ta=!1;c&&(a.Ia=c)}function mc(a,b){b=void 0===b?!0:b;a.Ba!=b&&(a.Ba=b,a.ja=!0)}function nc(a,b,c){b=4*(c*a.ca+b);return b<=a.aa.length-4?a.aa[b+2]:0}function oc(a,b,c){var d;b=4*(c*a.ca+b);b<=a.aa.length-4&&(d=a.aa[b]);return d}
function dc(a){return(a=a||void 0)&&fb[a]||a}function cc(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=fb[a]||a;if(pc(a,d)){a="rgba(";var e;for(e=0;3>e;e++){var f=Math.round(d[e]*c);f=0>f?0:255<f?255:f;a+=f+","}a+=(e<d.length?d[e]:b)+")"}}return a}function fc(a,b){for(var c=0;c<b.length;c+=4)qc(a,b,c)}function qc(a,b,c){b[c]=a.type<ac?hc:" ";b[c+1]=a.fa==a.ga?null:a.fa;b[c+2]=0;b[c+3]=Y}
xb.prototype.Ka=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.fa&&c==this.la&&a&&a.length==this.aa.length){this.aa=a;for(b=0;b<=this.aa.length-4;b+=4)this.aa[b+1]==this.ga&&(this.aa[b+1]=null);Cb(this,!0);return!0}return!1};function pc(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}
xb.prototype.La=function(a){this.aa&&(a.push(this.fa),a.push(this.la),a.push(this.aa))};function rc(a,b,c,d){var e=null;0<=c&&c<a.ea&&0<=b&&b<a.ca&&(e=!1,d=d||a.fa,d==a.ga&&(d=null),b=4*(c*a.ca+b),a.aa[b+1]!==d&&((a.aa[b+1]=d)||(a.aa[b]=hc),a.aa[b+3]|=Y,a.ja=e=!0),a.va=b,a.ta=!0);return e}function sc(a,b,c,d){if(0<=c&&c<a.ea&&0<=b&&b<a.ca){b=4*(c*a.ca+b);c=0;if(a.aa[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.aa[b+2]!==c&&(a.aa[b+2]=c,a.aa[b+3]|=Y,a.ja=!0);a.va=b;a.ta=!0}}
function tc(a,b,c,d){var e=!1,f=0&uc;b=4*(c*a.ca+b);if(b<=a.aa.length-4){if(a.aa[b]!==d||(a.aa[b+3]&uc)!==f)a.aa[b]=d,a.aa[b+3]=a.aa[b+3]&~uc|f|Y,a.ja=e=!0;a.va=b;a.ta=!0;a.qa=0}return e}
var $b=0,yb=1,ac=3,Zb={small:$b,round:yb,square:2,digit:ac},Yb="container",hc=0,uc=129,jc=1,Y=128,vc={},ic=(vc[$b]=[4,4,4],vc[yb]=[16,16,14],vc[2]=[2,2,28,28],vc),bc=[[8,8],[32,32],[32,32],[96,128]],lc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},kc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};B.LED=xb;
function wc(a,b,c){P.call(this,a,b,c);this.Qa=J(this,"cyclesMinimum",1E5,void 0);this.cb=J(this,"cyclesMaximum",1E9,void 0);this.Ra=Na(J(this,"cyclesPerSecond",1E6,void 0),this.Qa,this.cb);this.ta=1E3/60;this.Cc=J(this,"updatesPerSecond",2,void 0)||2;this.tb=1E3/this.Cc;this.Ua=0;this.Dc=J(this,"timeLock",!0);this.Ia=this.qa=0;this.Ha=this.ga=1;this.Ta=this.ja=this.Ra/1E4/100;this.za=[];this.la=[];this.ba=[];this.Aa=[];this.Sa=this.aa=this.xa=this.ia=!1;this.oa=this.da=0;a=Ia("requestAnimationFrame");
if(!a){a="setTimeout";var d=this.ta}this.eb=window[a].bind(window,this.Yc.bind(this),d);this.rb=window[Ia("cancelAnimationFrame")||"clearTimeout"].bind(window);this.va=this.ua=this.ea=this.ca=this.Na=0;xc(this)||yc(this,this.Ha)}y(wc,P);function ec(a,b){a.za.push(b)}u=wc.prototype;
u.Oa=function(a,b){var c=this;switch(a){case zc:b.onclick=function(){Ac(c)&&(c.aa?Bc(c):c.start())};break;case Cc:b.onclick=function(){yc(c,c.ga<<1);Dc(c,Ec(c.ja))};break;case Fc:b.onclick=function(){Ac(c)&&(c.aa?G(c,"already running"):c.da?Bc(c):Gc(c,void 0))};break;case Hc:b.addEventListener("mousedown",function(){c.ia=!0}),b.addEventListener("mouseup",function(){xc(c);c.ia=!1}),b.addEventListener("mousemove",function(){c.ia&&xc(c)}),b.addEventListener("change",function(){c.ia=!0;xc(c);c.ia=!1})}P.prototype.Oa.call(this,
a,b)};function Jb(a,b,c){var d=void 0===d?-1:d;var e=a.ba.length+1;a.ba.push({id:b,Oc:c,ib:d,Da:-1});0<=d&&Ob(a,e,d);return e}
function Ic(a,b,c,d){var e=0,f=a.ja,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.ka(65536,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.ta&&(1<a.ga&&(a.ga>>=1,a.ka(8388608,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.ta,a.ga)),e=d));a.qa=f;a.Ia=f/a.Ta;b=a.Ia/a.ga;a.Na=g/b/60+1E-8;a.ka(65536,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.Na,g,b,60);return e}
function Jc(a,b){a.ua=a.ea=b;if(!a.la.length)return a.ea=0,a.ua;for(var c=0;0<a.ea;){if(c<a.la.length){var d=a.la[c++];b=d.hc.call(d,b)||1}else c=b=0;a.ea-=b}return a.ua-a.ea}function Kc(a,b){b=void 0===b?a.ua-a.ea:b;if(!a.aa){if(a.ca)for(var c=0;c<a.la.length;c++){var d=a.la[c];d.ic.call(d)}a.ca=b}a.ca-=b;1>a.ca&&(a.xa=!0);a.va+=b;a.ua=a.ea=0;a.aa||(a.va=0);return b}
function Lc(a,b){b=void 0===b?0:b;if(b){var c=b;a.ca+=b}else for(c=a.ca,1>c&&(c=a.ca+=a.Na),0>c&&(a.ka(8388608,"warning: cycle count dropped below zero: %f\n",c),c=a.ca=0),c|=0,b=a.ba.length;0<b;b--){var d=a.ba[b-1];!(0>d.Da)&&c>d.Da&&(c=d.Da)}return c}function Ec(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Ac(a){return a.Sa?!0:(G(a,"not powered"),!1)}
function Mc(a,b){if(1<=b)for(var c=a.ba.length;0<c;c--){var d=a.ba[c-1];0>d.Da||(d.Da-=b,0>=d.Da&&(d.Da=-1,d.Oc(),0<=d.ib&&Ob(a,c,d.ib)))}}u.Ea=function(a){this.Sa=a;void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};
u.Yc=function(a){a=void 0===a?Date.now():a;this.oa=0;if(this.aa){var b=Date.now();if(this.ra){var c=b-this.sa-this.ta;c>this.ta&&(this.fa+=c,this.ka(8388608,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.sa=b;this.fa||(this.fa=b);this.Ba=0;try{this.xa=!1;do Mc(this,Kc(this,Jc(this,Lc(this))));while(this.aa&&!this.xa)}catch(d){G(this,d.message),Bc(this)}this.ra=Date.now();this.Ba&&(this.fa+=this.Ba,this.sa+=this.Ba);this.sa+=Ic(this,this.va,this.ra-this.fa,this.ra-this.sa);
this.ra-this.Ua>=this.tb&&this.update();for(b=0;b<this.za.length;b++)this.za[b](a);this.oa=this.eb()}};function yc(a,b){if(void 0!==b){if(1>b||!a.ia&&0<a.qa&&a.qa<.9*a.ja)b=a.Ha;a.ga=b;b=a.Ta*a.ga;a.ja!=b&&(a.ja=b,Dc(a,Ec(a.ja)))}a.fa=a.ra=0;a.ca=a.va=0;Ic(a);for(b=a.ba.length;0<b;b--){var c=a.ba[b-1];0<=c.ib&&Ob(a,b,c.ib,!0)}}function xc(a){var b=a.ma[Hc];return b?(yc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.cb-a.Qa)+a.Qa)/a.Ra|0),!0):!1}
function Ob(a,b,c,d){0<b&&b<=a.ba.length&&(b=a.ba[b-1],d||0>b.Da)&&(c=Math.ceil(a.Ra*(a.Dc?a.Ha:a.Ia)/1E3*(void 0===c?1E3:c)),a.aa&&(c+=Kc(a)),b.Da=c)}u.start=function(){if(this.aa||this.da)return!1;this.aa=!0;this.fa=this.ra=0;this.update(!0);this.oa=this.eb();return!0};function Gc(a,b){b=void 0===b?1:b;a.aa||(b&&!a.da&&(a.da=b),a.da&&(a.da--,Mc(a,Kc(a,Jc(a,Lc(a,1)))),a.update(!1),a.da&&setTimeout(function(){Gc(a,0)},0)))}
function Bc(a){a.aa?(a.aa=!1,Kc(a),a.oa&&(a.rb(a.oa),a.oa=0),a.update(!0)):a.da&&(a.da=0,a.update(!0))}u.update=function(a){a&&G(this,this.aa?"started with "+Ec(this.ja)+" target":"stopped");$a(this,zc,this.aa?"Halt":"Run");$a(this,Fc,this.da?"Stop":"Step");this.ia||(this.ka(65536,"getSpeedCurrent(%5.3fhz)\n",1E6*this.qa),Dc(this,this.aa&&this.qa?Ec(this.qa):"Stopped"));for(a=0;a<this.Aa.length;a++){var b=this.Aa[a];b.Vc.call(b)}this.Ua=Date.now();this.xa=!0};
function Dc(a,b){$a(a,Nc,b);$a(a,Cc,b)}var zc="run",Cc="setSpeed",Nc="speed",Fc="step",Hc="throttle";B.Time=wc;function Z(a,b,c){c["class"]="CPU";P.call(this,a,b,c);this.Ja=void 0;this.Xc=0;this.time=R(this,"Time");this.time.la.push(this);this.time.Aa.push(this);this.sa=this.qa=0}y(Z,P);Z.prototype.abort=function(a){G(this,a.message);Bc(this.time)};Z.prototype.hc=function(a){this.sa=this.qa=void 0===a?0:a;return this.gc()};Z.prototype.ic=function(){this.sa-=this.qa;this.qa=0};
Z.prototype.gc=function(){return this.sa-this.qa};
function Oc(a,b,c){Z.call(this,a,b,c);this.ja=J(this,"wrap",!1);this.ta=(this.xa=J(this,"font",""))&&Pc[this.xa]||Pc.Helvetica;this.ua=J(this,"rule","");this.oa=J(this,"pattern","");Qc(this,this.za=J(this,"message",""));this.Ia=J(this,"toggleColor",!1);this.Ha=Array(Rc(this).length);if(c=R(this,"LED",!1)){this.aa=c;Sc(this)||zb(c,!0);this.ra=R(this,"Input",!1);var d=this;this.Aa=new Ab(a,b+"Input",{"class":"Input",location:[0,0,c.Aa,c.za,c.da,c.xa],drag:!(!this.ra||!this.ra.va),scroll:!(!this.ra||
!this.ra.la),hexagonal:c.Qa,bindings:{surface:Ka(c,Yb)}});Fb(this.Aa,function(e,f){var g=d.aa;0<=e&&0<=f&&(d.ia?rc(g,e,f,d.ia)?tc(g,e,f,1):d.Ia?rc(g,e,f):tc(g,e,f,1-oc(g,e,f)):tc(g,e,f,1-oc(g,e,f)),sc(g,e,f,Rc(d,!!oc(g,e,f))),Cb(g))});this.ga=[];this.Ba=c.fa;Tc(this,this.Ba);Uc(this);Vc(this,this.ha[Wc]);Ga(this,this.Uc.bind(this))}}y(Oc,Z);u=Oc.prototype;
u.Oa=function(a,b){var c=this,d;switch(a){case Xc:case Yc:b.onchange=function(){Zc(c,a)};Zc(this);break;case Wc:b.onchange=function(){Vc(c)};break;case $c:Fa(b,ad(this.ha[$c]),!1,this.ha.pattern);b.onchange=function(){var e=c.ma[$c];e&&e.options.length&&((e=e.options[e.selectedIndex].value)?Sc(c,e):c.Ga())};break;case bd:b.onclick=function(){var e=cd(c,!0),f=c.ma[dd];f&&(e='"'+f.value+'":"'+e.replace(/^([0-9]+\/)*/,"")+'",');G(c,e)};break;case ed:b.onclick=function(){var e=cd(c);G(c,e);var f=window.location.href;
f=0<=f.indexOf("pattern=")?f.replace(/(pattern=)[^&]*/,"$1"+e.replace(/\$/g,"$$$$")):f+((0>f.indexOf("?")?"?":"&")+"pattern="+e);window.location=f};break;case dd:b.onkeypress=function(e){b.value=String.fromCharCode(e.charCode);var f=c.ma[fd];f&&(f.textContent=b.value);e.preventDefault()};break;default:a.startsWith(gd)?b.onclick=function(){Uc(c,a)}:(d=this.ha[$c])&&d[a]&&(b.onclick=function(){Sc(c,a)})}Z.prototype.Oa.call(this,a,b)};
function ad(a){var b={},c;for(c in a){for(var d=c,e=a[c],f=0;f<e.length;f++)if(0==e[f].indexOf("#N")){d=e[f].substr(2).trim();break}b[d]=c}return b}
u.hc=function(a){a=void 0===a?0:a;var b=0;if(0<=a){var c=1;do{switch(this.ua){case hd:var d=0;for(var e=this.aa,f=e.da,g=e.ea,m=this.Ha,h=0;h<g;h++)for(var p=0;p<f;p++){var k=m,l=!1,n=4*(h*e.ca+p);if(n<=e.aa.length-4&&e.aa[n+1]){l=!0;n=e.aa[n+2];for(var q=k.length-1;0<=q;q--)k[q]=n&15,n>>>=4}if(l){d++;if(m[0])m[0]--;else{l=(k=oc(e,p,h))||0;switch(k){case 1:if(l=hc,m[0]=m[2],m[0]){m[0]--;break}case hc:if(m[3]&&(l=this.ga.indexOf(e.aa[4*(h*e.ca+p)+1]||e.ga),0<=l)){for(l+=m[3];l>=this.ga.length;)l-=
this.ga.length;rc(e,p,h,this.ga[l])}l=1;m[0]=m[1];m[0]&&m[0]--}l!==k&&tc(e,p,h,l)}sc(e,p,h,m)}}break;case id:c=a||c;d=c;d=void 0===d?1:d;e=0;f=this.aa;g=f.ca;m=f.ea;if(f.qa||!jd(this,d))d=0;else{h=f.aa;n=4*d;p=4*g;l=q=k=0;for(this.la=this.va=-1;k<g-d;){for(var t=1,w=l,v=0;v<m;v++){var r=h[l],C=h[l]=h[l+n];r=C!==r?Y:0;h[l+1]=h[l+n+1];h[l+2]=h[l+n+2];h[l+3]=h[l+n+3]|r;C&&(e++,t=0);l+=p}l=w+4;k++<f.da&&(t?q++:(0>this.la&&(this.la=q),q=0))}0>this.la&&(this.la=q);for(this.va=q;k<g;){n=l;for(q=0;q<m;q++)qc(f,
h,l),l+=p;l=n+4;k++}f.ja=!0;f.qa=d;d=e}break;case kd:d=0;e=this.aa;f=e.aa;g=e;g.ra||(g.ra=Array(g.Ta),fc(g,g.ra));g=g.ra;m=e.da;h=e.ea;p=4*m+e.Ua;k=h*p;l=0;n=l-p;q=n-4;t=n+4;w=l-4;v=l+4;C=l+p;r=C-4;for(var F=C+4,I=0;I<h;I++){I?I==h-1&&(this.ja?(C-=k,r-=k,F-=k):C=r=F=k):this.ja?(n+=k,q+=k,t+=k):n=q=t=k;for(var V=0;V<m;V++){V?1==V?this.ja?(w-=p,q-=p,r-=p):(w=l-4,q=n-4,r=C-4):V==m-1&&(this.ja?(v-=p,t-=p,F-=p):v=t=F=k):this.ja?(w+=p,q+=p,r+=p):w=q=r=k;var W=f[l],N=f[q]+f[n]+f[t]+f[v]+f[F]+f[C]+f[r]+f[w];
3==N?W=1:2!=N&&(W=hc);g[l]=W;g[l+1]=f[l+1];g[l+2]=f[l+2];g[l+3]=f[l+3]|(f[l]!==W?Y:0);l+=4;q+=4;n+=4;t+=4;v+=4;F+=4;C+=4;r+=4;w+=4;1==W&&d++}this.ja?(I||(n-=k,q-=k,t-=k),v+=p,t+=p,F+=p):(I||(n=l-p,q=n-4),v=l+4,t=n+4,F=C+4)}f=e.aa;e.aa=e.ra;e.ra=f;e.ja=!0}a||G(this,"active cells: "+d);b+=c}while(b<a)}return b};u.ic=function(){};u.gc=function(){return 0};function ld(a,b){var c=0;(a=a.ma[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}
function Rc(a,b){var c=0;if(b&&(b=a.ma[md])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=ld(a,nd)+ld(a,od),!(d&1)&&c==d-1||0>b.selectedIndex||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<pd.length;b++)c.push(ld(a,pd[b]));return c}
function Sc(a,b){var c=a.aa,d=-1,e=-1,f="";b||a.oa.match(/^[0-9]/)||(b=a.oa);if(b){var g=a.ha[$c];g=g&&g[b];if(!g)return G(a,"unknown pattern: "+b),!1;G(a,"loading pattern '"+b+"'");for(var m=b=0;b<g.length;b++){var h=g[b];if("#"==h[0])G(a,h);else if(m++){var p=h.indexOf("!");if(0<=p){f+=h.substr(0,p);break}f+=h}else{var k=h.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!k)return G(a,"unrecognized header line"),!1;var l=+k[1];var n=+k[2];k=k[3]}}}else{if(!a.oa)return!1;
f=0;k=a.oa.split("/");5==k.length&&(d=+k[f++],e=+k[f++]);if(3==k.length||5==k.length)l=+k[f++],n=+k[f++],f=k[f];else return G(a,"unrecognized pattern: "+a.oa),!1;k=a.ua}if(k!=a.ua)return G(a,"unsupported rule: "+k),!1;0>d&&(d=c.ca-l>>1);0>e&&(e=c.ea-n>>1);return 0>d||d+l>c.ca||0>e||e+n>c.ea?(a.ka("pattern too large (%d,%d)\n",l,n),!1):0<qd(a,d,e,f)}
function qd(a,b,c,d,e){e=void 0===e?!1:e;var f=a.aa,g=[0,0,0,1],m=0,h=!1,p=!1;d=d.split(/([a-z$])/i);e||zb(f);for(var k=0,l=b,n=0;k<d.length-1;){var q=d[k++],t=d[k++],w=+q;for(q=""===q?1:w;q--;){var v=0,r=!1;switch(t){case "$":h=p=!1;b=l;c++;break;case "C":m=w;p=!0;break;case "R":g[0]=w;h=!0;break;case "G":g[1]=w;h=!0;break;case "B":g[2]=w;h=!0;break;case "A":g[3]=w;h=!0;break;case "b":r=tc(f,b,c,hc);v++;break;case "o":r=tc(f,b,c,1);v++;break;default:a.ka("unrecognized pattern token: %s\n",t)}if(null==
r)a.ka("invalid pattern position (%d,%d)\n",b,c);else{if(h){r=f;var C=g;r=4>C.length||1==C[3]?r.ya("#%02x%02x%02x",C[0],C[1],C[2]):r.ya("rgba(%d,%d,%d,%d)",C[0],C[1],C[2],C[3]);rc(f,b,c,r)}p&&(r=4*(c*f.ca+b),r<=f.aa.length-4&&f.aa[r+2]!=m&&(f.aa[r+2]=m));n<b&&(n=b);b+=v}}}e||Cb(f,!0);return 0>(n-=l-1)?0:n}
u.Ka=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return G(this,"Invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.ka("Saved state version mismatch: %3.2f\n",c),!1;try{this.ca=b.shift(),this.da=b.shift(),this.ea=b.shift(),this.ba=b.shift()}catch(d){return G(this,"Controller state error: "+d.message),!1}return Pa().message||Pa().pattern||Pa()[Wc]||!(a=a.stateLEDs||a[1])||!this.aa||this.aa.Ka(a)?!0:!1};
u.Uc=function(a){var b="",c=a.shift();switch(a.shift()[0]){case "s":Qc(this,a.join(" "));break;case "?":b="";rd.forEach(function(d){b+=d+"\n"});b&&(b="additional commands:\n"+b);break;default:c&&(b="unrecognized command '"+c+"' (try '?')\n")}return b};u.yb=function(a){return a&&this.Ka(a)?!0:!1};u.Ea=function(a){a?this.time.start():Bc(this.time)};u.Ga=function(){G(this,"reset");zb(this.aa,!0);mc(this.aa,!0);this.za&&Qc(this,this.za)};u.zb=function(a){this.La(a)};u.Vc=function(){this.time.aa||Cb(this.aa)};
function jd(a,b,c,d){b=void 0===b?1:b;c&&(a.ea=c,a.ba=d);switch(a.ea){case sd:return!1;case td:case ud:if(0<a.ba)return a.ba-=b,!0;break;case vd:if(0<a.ba)return a.ba-=b,!1;break;case wd:if(a.la>a.va)return!0;break;case xd:mc(a.aa,!1);a.ea=vd;break;case yd:mc(a.aa,!0);a.ea=vd;break;default:return!1}if(c)a=!1;else a:if(b=void 0===b?1:b,a.ca){a.da>=a.ca.length&&(a.da=0);c=a.ca[a.da++];if("$"==c){d=0;for(var e=a.da;e<a.ca.length;){var f=a.ca.charCodeAt(e)-48;if(0>f||9<f)break;d=10*d+f;e++}if(e<a.ca.length)if(f=
a.ca[e++],"$"==f)a.da=e;else{var g=zd[f];if(g){a.da=e;a=jd(a,b,g,d);break a}G(a,"unrecognized message code: $"+f)}}" "==c?a.ba+=2:(d=a.aa.da+1,e=0>a.ba?a.ba:0,c=a.ta[c]||a.ta[c.toUpperCase()],f=Math.round((a.aa.xa-a.ta.height)/2),c&&(a.ba+=qd(a,d+e,0>f?0:f,c,!0)),a.ba+=2-b);a.ea=ud;a=!0}else a.ea=sd,a=!1;return a}
function cd(a,b){function c(W){var N=!1;null==k[3]&&(k[3]=1);if(v){if(h){if(k[0]!==t[0]||k[1]!==t[1]||k[2]!==t[2]||k[3]!==t[3])N=!0;V!==w&&(N=!0)}p!==q&&(N=!0);if(N||W&&q)h&&(l[0]!==t[0]&&(l[0]=t[0],e+=(t[0]||"")+"R"),l[1]!==t[1]&&(l[1]=t[1],e+=(t[1]||"")+"G"),l[2]!==t[2]&&(l[2]=t[2],e+=(t[2]||"")+"B"),l[3]!==t[3]&&(l[3]=t[3],e+=(t[3]||"")+"A"),n!==w&&(n=w,e+=(w||"")+"C")),1<v&&(e+=v),e+=1===q?"o":"b",N=!0}W?(e+="$",v=0):(N?v=1:v++,q=p,t[0]=k[0],t[1]=k[1],t[2]=k[2],t[3]=k[3],w=V)}var d=a.aa,e="",
f=0,g=a.aa.ca,m=a.aa.ea,h=!!a.ga.length,p,k=[0,0,0],l=[0,0,0,1],n=0,q=0,t=[0,0,0,1],w=0,v=0;a=0;var r=d.ca-1,C=d.ea-1;if(b){b&&(a=r,r=0);for(g=0;g<d.ea;g++)for(m=0;m<d.ca;m++)(p=oc(d,m,g))&&b&&(a>m&&(a=m),r<m&&(r=m));g=r-a+1;m=C+1;0>g&&(g=0);0>m&&(m=0)}for(var F=0;F<=C;F++){for(var I=a;I<=r;I++){p=oc(d,I,F);pc(d.aa[4*(F*d.ca+I)+1]||d.ga,k);var V=nc(d,I,F);c()}c(!0)}if(!b)for(;"$"==e[0];)f++,m--,e=e.slice(1);for(;"$$"==e.slice(-2);)m--,e=e.slice(0,-1);"$"==e&&(m=0);e=(b?"":"0/"+f+"/")+g+"/"+m+"/"+
e.slice(0,-1);return e=e.replace(/\$+$/,"")}u.La=function(a){var b=[],c=[];b.push(2);b.push(this.ca);b.push(this.da);b.push(this.ea);b.push(this.ba);this.aa&&this.aa.La(c);a.push(b);a.push(c)};function Qc(a,b){a.ca!=b&&(b&&G(a,"new message: '"+b+"'"),a.ca=b);a.ea=td;a.da=a.ba=0}u.toString=function(){return""};
function Vc(a,b){var c=a.ma[Wc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.aa;a.Ra&&(a.Ra.style.backgroundImage=b?"url('"+b+"')":"none")}}
function Zc(a,b){var c=a.ma[Xc],d=a.ma[Yc];b=b===Xc;c&&!c.options.length&&(Fa(c,a.ha.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.fa=a.ha.colors[c.options[c.selectedIndex].value];for(var e in a.fa)if(b=a.ha[e.toLowerCase()])"#"!=b[0]&&(b="#"+b),G(a,"overriding color '"+e+"' with "+b+" (formerly "+a.fa[e]+")"),a.fa[e]=b;Fa(d,a.fa,!0)}c&&d&&d.options.length&&(a.ia=d.options[d.selectedIndex].value,Uc(a))}
function Tc(a,b){var c=a.ma[Yc];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.ia=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function Uc(a,b){var c=1,d;!b&&a.ia&&(d=a.ma[Ad])&&(d.style.backgroundColor=a.ia);if(a.fa)for(var e in a.fa){var f=a.fa[e];a.ga&&(a.ga[c-1]=f);var g=gd+c++;d=a.ma[g];if(!d)break;d.style.display="inline-block";g==b&&Tc(a,f);if(b&&b!=g||f!=a.ia)f=cc(f,1,.5);d.style.backgroundColor=f}for(;;){b=gd+c++;b=a.ma[b];if(!b)break;b.style.display="none"}}
var Xc="colorPalette",Yc="colorSelection",gd="colorSwatch",Ad="colorSwatchSelected",md="countInit",nd="countOn",od="countOff",Wc="backgroundImage",$c="patterns",dd="symbolInput",fd="symbolPreview",bd="save",ed="saveToURL",pd=[null,nd,od,"countCycle"],rd=["s\t\tset string"],td="load",ud="scroll",vd="pause",sd="halt",wd="center",xd="off",yd="on",zd={b:xd,c:wd,h:sd,o:yd,p:vd,s:ud},hd="A4",id="L1",kd="B3/S23",Pc={Helvetica:{width:16,height:16,0:"$2b2o$bo2bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$bo2bo$2b2o",
1:"$3bo$2b2o$4o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo",2:"$2b3o$bo3bo$o5bo$o5bo$6bo$5bo$3b2o$2bo$bo$o$7o",3:"$b4o$o4bo$o4bo$5bo$4bo$2b2o$4bo$5bo$o4bo$o4bo$b4o",4:"$5bo$4b2o$3bobo$2bo2bo$bo3bo$o4bo$o4bo$8o$5bo$5bo$5bo",5:"$6o$o$o$o$4o$4bo$5bo$5bo$5bo$o3bo$b3o",6:"$2b4o$bo4bo$o$o$o$ob4o$2o4bo$o5bo$o5bo$bo4bo$2b4o",7:"$8o$7bo$6bo$5bo$4bo$4bo$3bo$3bo$2bo$2bo$2bo",8:"$b4o$o4bo$o4bo$o4bo$bo2bo$2b2o$bo2bo$o4bo$o4bo$o4bo$b4o",9:"$b4o$o4bo$o5bo$o5bo$o4b2o$b4obo$6bo$6bo$6bo$o4bo$b4o",A:"$3b2o$2bo2bo$bo4bo$bo4bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo",
B:"$6o$o5bo$o5bo$o5bo$o4bo$7o$o6bo$o6bo$o6bo$o6bo$7o",C:"$2b4o$bo4bo$o6bo$o$o$o$o$o$o6bo$bo4bo$2b4o",D:"$6o$o5bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o5bo$6o",E:"$7o$o$o$o$o$6o$o$o$o$o$7o",F:"$7o$o$o$o$o$6o$o$o$o$o$o",G:"$2b4o$bo4bo$o$o$o$o3b4o$o6bo$o6bo$o6bo$bo4bo$2b4o",H:"$o6bo$o6bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo$o6bo$o6bo",I:"$o$o$o$o$o$o$o$o$o$o$o",J:"$5bo$5bo$5bo$5bo$5bo$5bo$5bo$o4bo$o4bo$o4bo$b4o",K:"$o6bo$o5bo$o4bo$o3bo$o2bo$ob2o$2o2bo$o4bo$o5bo$o6bo$o7bo",L:"$o$o$o$o$o$o$o$o$o$o$7o",M:"$o8bo$2o6b2o$obo4bobo$obo4bobo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o8bo$o8bo$o8bo$o8bo",
N:"$2o5bo$obo4bo$obo4bo$o2bo3bo$o2bo3bo$o3bo2bo$o3bo2bo$o4bobo$o4bobo$o4bobo$o5b2o",O:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo6bo$2bo4bo$3b4o",P:"$6o$o5bo$o6bo$o6bo$o6bo$o5bo$6o$o$o$o$o",Q:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo4bobo$2bo4bo$3b4obo$9bo",R:"$6o$o5bo$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo$o6bo",S:"$2b4o$bo4bo$o6bo$o$bo$2b4o$6bo$7bo$o6bo$bo4bo$2b4o",T:"$9o$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo",U:"$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",V:"$o8bo$o8bo$bo6bo$bo6bo$bo6bo$2bo4bo$2bo4bo$2bo4bo$3bo2bo$3bo2bo$4b2o",
W:"$o4b2o4bo$o4b2o4bo$o4b2o4bo$o3bo2bo3bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$2b2o4b2o$2b2o4b2o$2b2o4b2o",X:"$o8bo$bo6bo$2bo4bo$3bo2bo$4b2o$4b2o$4b2o$3bo2bo$2bo4bo$bo6bo$o8bo",Y:"$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$9o$8bo$7bo$6bo$5bo$4bo$3bo$2bo$bo$o$9o",a:"$$$$b4o$o4bo$5bo$b5o$o4bo$o4bo$o3b2o$b3obo",b:"$o$o$o$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o",c:"$$$$2b4o$bo4bo$o$o$o$o$bo4bo$2b4o",d:"$6bo$6bo$6bo$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo",e:"$$$$2b3o$bo3bo$o5bo$7o$o$o$bo4bo$2b4o",
f:"$2b2o$bo2bo$bo$bo$4o$bo$bo$bo$bo$bo$bo",g:"$$$$2b2obo$bo2b2o$o4bo$o4bo$o4bo$bo2b2o$2b2obo$5bo$5bo$o4bo$b4o",h:"$o$o$o$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",i:"$$o$$o$o$o$o$o$o$o$o",j:"$$3bo$$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$o2bo$b2o",k:"$o$o$o$o4bo$o3bo$o2bo$obo$2obo$o3bo$o4bo$o5bo",l:"$o$o$o$o$o$o$o$o$o$o$o",m:"$$$$ob2o3b2o$2o2bobo2bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo",n:"$$$$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",o:"$$$$2b4o$bo4bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",p:"$$$$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o$o$o$o",
q:"$$$$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo$6bo$6bo$6bo",r:"$$$$ob2o$2o2bo$o$o$o$o$o$o",s:"$$$$b4o$o4bo$o$b4o$5bo$5bo$o4bo$b4o",t:"$$bo$bo$4o$bo$bo$bo$bo$bo$bo2bo$2b2o",u:"$$$$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o3b2o$b3obo",v:"$$$$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo",w:"$$$$o3b2o3bo$o3b2o3bo$o3b2o3bo$o3b2o3bo$bobo2bobo$bobo2bobo$bobo2bobo$2bo4bo",x:"$$$$$o5bo$bo3bo$2bobo$3bo$2bobo$bo3bo$o5bo",y:"$$$$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$2bo$2o",z:"$$$$6o$5bo$4bo$3bo$2bo$bo$o$6o",
"!":"$o$o$o$o$o$o$o$o$$o$o",'"':"$obo$obo$obo$obo","#":"$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo",$:"3bo$2b4o$bobo2bo$o2bo$o2bo$bobo$2b3o$3bobo$3bo2bo$3bo2bo$o2bobo$b4o$3bo","%":"$b2o7bo$o2bo5bo$o2bo4bo$o2bo3bo$o2bo2bo$b2o2bo2b2o$4bo2bo2bo$3bo3bo2bo$2bo4bo2bo$bo5bo2bo$o7b2o","&":"$b3o$o3bo$o3bo$o3bo$bobo$2bo$bobo$o3bobo$o4bo$o3bobo$b3o3bo","'":"$o$o$o$o","(":"$3bo$2bo$bo$bo$o$o$o$o$o$o$bo$bo$2bo$3bo",")":"$o$bo$2bo$2bo$3bo$3bo$3bo$3bo$3bo$3bo$2bo$2bo$bo$o","*":"2bo$obobo$b3o$b3o$o3bo",
"+":"$$$$3bo$3bo$3bo$7o$3bo$3bo$3bo",",":"$$$$$$$$$$2o$2o$bo$o",".":"$$$$$$$$$$2o$2o","/":"$3bo$3bo$2bo$2bo$2bo$bo$bo$bo$o$o$o",":":"$$$$2o$2o$$$$$2o$2o",";":"$$$$2o$2o$$$$$2o$2o$bo$o","<":"$$$$6b2o$4b2o$2b2o$2o$2o$2b2o$4b2o$6b2o",">":"$$$$2o$2b2o$4b2o$6b2o$6b2o$4b2o$2b2o$2o","=":"$$$$$$8o$$$8o","?":"$b4o$o4bo$o4bo$5bo$4bo$3bo$2bo$2bo$$2bo$2bo","@":"$3b4o$2bo4bo$bo6bo$o3b2o3bo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o5b3o$bo$2bo5bo$3b5o","[":"$3o$o$o$o$o$o$o$o$o$o$o$o$o$3o","]":"$3o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$3o",
"\\":"$o$o$bo$bo$bo$2bo$2bo$2bo$3bo$3bo$3bo","^":"$2b2o$2b2o$bo2bo$bo2bo$o4bo$o4bo",_:"$$$$$$$$$$$$$8o","`":"o$bo$2bo","{":"$2b2o$bo$bo$bo$bo$bo$bo$o$bo$bo$bo$bo$bo$2b2o","}":"$2o$2bo$2bo$2bo$2bo$2bo$2bo$3bo$2bo$2bo$2bo$2bo$2bo$2o","|":"o$o$o$o$o$o$o$o$o$o$o$o$o$o$o","~":"$$$$$$b3o3bo$o3b3o"},ATT4425:{width:9,height:13,A:"$3bo$3bo$2bobo$2bobo$bo3bo$bo3bo$7o$o5bo$o5bo",B:"$6o$bo4bo$bo4bo$bo3bo$b4o$bo3bo$bo4bo$bo4bo$6o",C:"$2b5o$bo$o$o$o$o$o$bo$2b5o",D:"$5o$bo3bo$bo4bo$bo4bo$bo4bo$bo4bo$bo4bo$bo3bo$5o",
E:"$6o$o$o$o$5o$o$o$o$6o",F:"$6o$o$o$o$5o$o$o$o$o",G:"$2b3o$bo3bo$o$o$o$o3b3o$o4bo$bo3bo$2b3o",H:"$o5bo$o5bo$o5bo$o5bo$7o$o5bo$o5bo$o5bo$o5bo",I:"$3o$bo$bo$bo$bo$bo$bo$bo$3o",J:"$4bo$4bo$4bo$4bo$4bo$4bo$o3bo$o3bo$b3o",K:"$o5bo$o4bo$o3bo$o2bo$3o$o2bo$o3bo$o4bo$o5bo",L:"$o$o$o$o$o$o$o$o$7o",M:"$o5bo$2o3b2o$obobobo$o2bo2bo$o5bo$o5bo$o5bo$o5bo$o5bo",N:"$o5bo$2o4bo$obo3bo$obo3bo$o2bo2bo$o3bobo$o3bobo$o4b2o$o5bo",O:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",P:"$6o$o5bo$o5bo$o5bo$6o$o$o$o$o",Q:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o$3bo2bo$4b3o",
R:"$6o$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo",S:"$2b3o$bo3bo$bo$2bo$3bo$4bo$o4bo$bo3bo$2b3o",T:"$5o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo",U:"$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",V:"$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo",W:"$o5bo$o5bo$o2bo2bo$o2bo2bo$obobobo$obobobo$2o3b2o$2o3b2o$o5bo",X:"$o5bo$bo3bo$bo3bo$2bobo$3bo$2bobo$bo3bo$bo3bo$o5bo",Y:"$o5bo$o5bo$bo3bo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$7o$6bo$5bo$4bo$3bo$2bo$bo$o$7o"}};B.LEDCtrl=Oc;
function Bd(a,b,c){P.call(this,a,a);var d=this;this.ba=!1;this.ga=c;this.aa="";this.fa=this.ea=!1;lb(this,!1);this.Ca=0;b=b.trim();"{"==b[0]?Cd(this,b):(this.aa=b,Oa(this.aa,function(e,f,g,m){4==g&&(!m&&f?(Cd(d,f),Dd(d)):d.ka("error (%d) loading configuration: %s\n",m,e))}));window.addEventListener("load",function(){d.fa=!0;Dd(d)});window.addEventListener(Sa("iOS")?"pagehide":Sa("Opera")?"unload":"beforeunload",function(){Ed(d)});window.addEventListener("pageshow",function(){d.ba||d.Ea(!0)})}
y(Bd,P);Bd.prototype.Oa=function(a,b){var c=this;switch(a){case Fd:b.onclick=function(){c.Ea()};break;case Gd:b.onclick=function(){c.Ga()}}P.prototype.Oa.call(this,a,b)};
function Dd(a){var b=!0;if(a.ea&&a.fa){for(var c in a.ca){var d=void 0,e=a.ca[c];try{d=e["class"],B[d]?"Machine"==d?(a.ka("PCjs %s v%3.2f\n%s\n",e.name,2,Hd),a.aa&&a.ka("Configuration: %s\n",a.aa)):new B[d](a.pa,c,e):a.ka('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.ka('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),ob(a,c)}}if(a.da){var f=Ta(a);jb(a,function(g){return g.yb&&!g.yb(f)?(g.ka('unable to restore state for device "%s"\n',g.wa),!1):!0})}lb(a,!0);mb(a,a.Ea.bind(a,
b))||a.ka("machine %s not ready to power, waiting for device(s)\n",a.pa)}}function Cd(a,b){try{a.ca=JSON.parse(b);var c=a.ca[a.pa];if(!c)throw Error("configuration missing machine ID");ib(a,c,["autoSave","autoStart"]);a.da=!1!==a.ha.autoSave;a.ia=!1!==a.ha.autoStart;if(a.ga){var d=eval("("+a.ga+")"),e;for(e in d)a.ha[e]=d[e]}a.ea=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),G(a,"machine '"+a.pa+"' initialization error: "+c)}}
Bd.prototype.Ea=function(a){a=void 0===a?!this.ba:a;if(kb(this)){var b=this;a&&G(this,"power on");jb(this,function(c){c.Ea&&c!=b&&("CPU"!=c.ha["class"]||b.ia||kb(b)?c.Ea(a):c.time.update(!0));return!0});(this.ba=a)||G(this,"power off")}};Bd.prototype.Ga=function(){if(kb(this)){var a=this;jb(this,function(b){b.Ga&&b!=a&&b.Ga();return!0});G(this,"reset")}};function Ed(a){if(a.da){var b=[];jb(a,function(c){c.zb&&c.zb(b);return!0});Za(a,b)}a.Ea(!1)}var Fd="power",Gd="reset",Hd="Copyright \u00a9 2012-2020 Jeff Parsons <Jeff@pcjs.org>";
window.LEDs=function(a,b,c){var d=new Bd(a,b,c);window.command=function(e){return Ua(d,e)};return d};B.Machine=Bd;})()

//# sourceMappingURL=led.js.map
