(function(){/*
 https://www.pcjs.org/modules/defs.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/numio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/stdio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/webio.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/device.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/bus.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/memory.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/rom.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/input.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/led.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/time.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/cpu.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/ledctrl.js (C) 2012-2020 Jeff Parsons
 https://www.pcjs.org/modules/machine.js (C) 2012-2020 Jeff Parsons
*/
var t;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function v(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca;
if("function"==typeof Object.setPrototypeOf)ca=Object.setPrototypeOf;else{var da;a:{var ea={Ab:!0},fa={};try{fa.__proto__=ea;da=fa.Ab;break a}catch(a){}da=!1}ca=da?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ca;
function x(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c]}var ia="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ja(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}return globalThis}var ka=ja(this);function A(a,b){if(b){var c=ka;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ia(c,a,{configurable:!0,writable:!0,value:b})}}
A("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});A("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
function la(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}A("String.prototype.repeat",function(a){return a?a:function(b){var c=la(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
function ma(){ma=function(){};ka.Symbol||(ka.Symbol=na)}function oa(a,b){this.aa=a;ia(this,"description",{configurable:!0,writable:!0,value:b})}oa.prototype.toString=function(){return this.aa};var na=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new oa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function pa(){ma();var a=ka.Symbol.iterator;a||(a=ka.Symbol.iterator=ka.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ia(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return qa(aa(this))}});pa=function(){}}function qa(a){pa();a={next:a};a[ka.Symbol.iterator]=function(){return this};return a}
function ra(a,b){pa();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}A("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}});A("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}});
A("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});A("Number.parseInt",function(a){return a||parseInt});A("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=la(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});
function sa(){}var ta=new ArrayBuffer(2);(new DataView(ta)).setUint16(0,256,!0);new Uint16Array(ta);var B={uc:0xffffffffffff,NONE:0,Cc:0,Sa:0x800000000000},C={};C.Defs=sa;function ua(){}x(ua,sa);function va(a,b){var c=a/D|0,d=b/D|0;return(a&b)==(b|0)&&(c&d)==d}function wa(a){for(var b=0,c=0,d=[];b<a.length;){for(var e=a[b],f=b+1;f<a.length&&a[f]===e;)f++;d[c++]=f-b;d[c++]=e;b=f}return d.length>=a.length?a:d}var D=Math.pow(2,32);C.NumIO=ua;
function E(){this.pb={};for(var a=0;22>a;a++)this.pb["ACDFHIMNSTWYbdfjcsoXx%"[a]]=null}x(E,ua);t=E.prototype;t.flush=function(){var a=xa;xa="";this.Xa(a)};function ya(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}
t.Bd=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c]=arguments[c];return void 0===b[0]?new Date(Date.now()):"string"===typeof b[0]?new Date(b[0]+" "+(b[1]||"00:00:00 GMT")):void 0===b[1]?new Date(b[0]):new Date(Date.UTC.apply(Date,v(b)))};t.Xa=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),za||(za=b),a=((b-za)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(xa+a.substr(0,c)),xa="",a=a.substr(c+1)),za=null);xa+=a;return a.length};function F(a,b,c){a.Xa(b+"\n",c)}
t.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return this.Xa(this.ya.apply(this,[a].concat(v(c))))};
t.ya=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(!c||!c.length)return a;d="";var e=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),f=0,g;for(g=0;g<e.length-6;g+=6){d+=e[g];var m=e[g+5];if(void 0===this.pb[m])d+="%"+e[g+1]+e[g+2]+e[g+3]+e[g+4]+m;else{if(f<c.length){var h=c[f];"%"!=m&&f++}else h=c[c.length-1];var p=e[g+1],k=0<=p.indexOf("#"),l=0<=p.indexOf("0"),n=e[g+2];"*"==n?(n=h,h=f<c.length?c[f++]:c[c.length-1]):n=+n||0;var q=e[g+3];q=q?+q.substr(1):
-1;var r=e[g+4],y=null,z=0,w="";var u=0<="ACDFHIMNSTWY".indexOf(m)&&"object"!=typeof h?this.Bd(h):h;switch(m){case "C":h=k?"#":"";d+=isNaN(u.getTime())?void 0:this.ya(this.ya("%%%sW, %%%sF %%%sD, %%%sY",h),u);continue;case "D":h=k?u.getUTCDate():u.getDate();m="d";break;case "A":case "H":case "I":h=k?u.getUTCHours():u.getHours();"A"==m?(h=12>h?"am":"pm",m="s"):("I"==m&&(h=h?12<h?h-12:h:12),m="d");break;case "F":case "M":h=k?u.getUTCMonth():u.getMonth();"F"==m?(h=Aa[h],m="s"):(h++,m="d");break;case "N":h=
k?u.getUTCMinutes():u.getMinutes();m="d";break;case "S":h=k?u.getUTCSeconds():u.getSeconds();m="d";break;case "T":h=k?"#":"";d+=isNaN(u.getTime())?void 0:this.ya(this.ya("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),u);continue;case "W":h=Ba[k?u.getUTCDay():u.getDay()];m="s";break;case "Y":h=k?u.getUTCFullYear():u.getFullYear(),0<q&&(h%=Math.pow(10,q),q=-1),m="d"}switch(m){case "b":d+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=q&&(l=!0,n<q&&(n=q),q=-1);case "f":h=+h;u=h+"";0<=q&&(u=h.toFixed(q));
u.length<n&&(l?(0>h&&(n--,u=u.substr(1)),u=("0".repeat(n)+u).slice(-n),0>h&&(u="-"+u)):u=(" ".repeat(n)+u).slice(-n));d+=u;break;case "j":d+=JSON.stringify(h,null,n||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=q&&(h=h.substr(0,q));h.length<n;)h=0<=p.indexOf("-")?h+" ":" "+h;d+=h;break;case "o":z=8,k&&(w="0");case "X":y=Ca;case "x":u="";z||(z=16);!w&&k&&(w="0x");y||(y=Da);h=Math.trunc(h);0<=q&&(l=!0,n<q&&
(n=q));l&&!n&&("b"==r?n=2:"h"==r||"w"==r?n=4:"l"==r?n=8:(n=Math.abs(h),n=255>=n?2:65535>=n?4:4294967295>=n?8:9),n+=w.length);n-=w.length;do k=h&z-1,h>>>=16==z?4:3,l||!u||k||h?u=y[k]+u:(w&&(u=w+u,w=""),0<n&&(u=" "+u));while(0<--n||h);d+=w+u;break;case "%":d+="%";break;default:this.pb[m]?d+=this.pb[m](m,p,n,q,h):d+="(unimplemented sprintf type: %"+m+")"}}}return d+=e[g]};
var xa="",za=null,Da="0123456789abcdef",Ca="0123456789ABCDEF",Ba="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Aa="January February March April May June July August September October November December".split(" ");C.StdIO=E;function H(a){E.call(this);this.ma={};this.Ca=0;this.oa=this;a&&(this.oa.Ca=0,this.oa.Ma=[],this.oa.Fa=0,this.oa.qb={},this.oa.Ve=!1)}var Ea;x(H,E);t=H.prototype;
t.Oa=function(a,b){var c=this,d=this;switch(a){case Fa.yc:b.onclick=function(){var e=c.$a(Fa.vb,!0);e&&(e.value="")};break;case Fa.vb:Ga(b),b.addEventListener("keydown",function(e){Ha(d,e,!0)}),b.addEventListener("keypress",function(e){Ha(d,e)})}};function Ia(a,b,c,d){c&&(a.options.length=0);if(b)for(var e in b)c=document.createElement("option"),c.text=e,c.value="string"==typeof b[e]?b[e]:e,a.appendChild(c),c.value==d&&(a.selectedIndex=a.options.length-1)}
function Ja(a,b){var c=Ka.Jb;a.oa.qb[c]||(a.oa.qb[c]=[]);a.oa.qb[c].push(b)}function Ga(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}t.error=function(a,b){b=this.ya.apply(this,[a].concat(v(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.ya.apply(this,[c].concat(v(b))))F(this,b),a||alert(b)};t.$a=function(a){return this.ma[a]};
function La(a){var b=window;if(b){do{for(var c=0;c<Ma.length;c++){var d=Ma[c];d=d?d+a[0].toUpperCase():a[0];d+=a.substr(1);if(d in b)return d}if(0>a.indexOf("screen"))break;a=a.replace("screen","Screen")}while(1)}return null}function Na(a,b){return a.ha.bindings&&a.ha.bindings[b]}function Oa(a){if(a=a.ma[Pa])var b=a.textContent;return b}function Qa(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function I(a,b,c,d){a=a.ha[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Ra(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4===e.readyState&&(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1));b(a,d,e.readyState,c)};e.open("GET",a,!0);e.send()}
function Sa(){var a,b=Ea;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ea=b}return b}function Ta(a){if(void 0===K.sb){var b=!1;if(window)try{window.localStorage.setItem(K.Ya,K.Ya),b=window.localStorage.getItem(K.Ya)==K.Ya,window.localStorage.removeItem(K.Ya)}catch(c){F(a,c.message),b=!1}K.sb=b}return!!K.sb}
function Ua(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.Ca;return-1==(b|1)||va(a.oa.Ca,b)?!0:!1}function Va(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Wa(a){var b=null;if(Ta(a)){var c;if(window)try{(c=window.localStorage.getItem(a.na))&&(b=JSON.parse(c))}catch(d){F(a,d.message)}}return b}
function Ha(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.oa,f=b.target;if(c){a=!1;var g;c=f.value;var m=c.lastIndexOf("\n");d==L.Gb&&f.selectionStart<=m+1&&(a=!0);d==L.rd?(a=!0,0<e.Fa&&(g=e.Ma[--e.Fa])):d==L.Ec&&(a=!0,e.Fa<e.Ma.length&&(g=e.Ma[++e.Fa]||""));a&&b.preventDefault();void 0!=g&&(f.value=c.substr(0,m+1)+g)}else d=String.fromCharCode(d),g=f.value,c=g.lastIndexOf("\n"),f.selectionStart<=c&&f.setSelectionRange(g.length,g.length),b.stopPropagation(),"@"==d&&0<e.Fa&&c+1==
g.length&&(f.value+=e.Ma[--e.Fa],d="\r"),"\r"==d&&(b.preventDefault(),g=f.value+="\n",f.blur(),f.focus(),(b=Xa(a,g.slice(g.lastIndexOf("\n",g.length-2)+1,-1)||""))&&F(a,b.replace(/\n$/,""),!1))}}
function Ya(a,b){if(void 0!=b){var c=a.oa;try{if(b=b.trim())c.Fa<c.Ma.length&&b==c.Ma[c.Fa]?c.Fa++:(c.Ma.push(b),c.Fa=c.Ma.length);var d=b.split(" "),e=d[0],f=a.oa.qb[Ka.Jb];switch(e[0]){case "m":if("?"==e[1]){var g="";Za.forEach(function(l){g+=l+"\n"});g&&(g="message commands:\n"+g);break}g="";var m=void 0;e=d[d.length-1].toLowerCase();var h="true"==e||"on"==e?!0:"false"==e||"off"==e?!1:void 0;void 0!=h&&d.pop();1>=d.length&&(void 0!=h&&(m=h,h=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(M));
for(f=1;f<d.length;f++){e=d[f];var p=M[e];if(!p){g+="unrecognized message: "+e+"\n";break}void 0!=h&&$a(a,p,h);if(void 0==m||m==Ua(a,p))g+=a.ya("%8s: %b\n",e,Ua(a,p))}Ua(a,B.Sa)&&(g+="all messages will be buffered until buffer is turned off\n");g||(g="no messages\n");break;case "?":g="",ab.forEach(function(l){g+=l+"\n"}),g&&(g="default commands:\n"+g);default:if(d.unshift(b),f)for(a=0;a<f.length;a++){var k=f[a](d);if(void 0!=k){g=g?g+k:k;break}}}}catch(l){g="error: "+l.message+"\n"}}return g}
function Xa(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Ya(a,b[d])}return c}t.Xa=function(a,b){void 0==b&&(b=Ua(this,B.Sa));if(!b){var c=this.$a(Fa.vb,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Va("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return E.prototype.Xa.call(this,a,b)};
t.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];d=0;"number"==typeof a&&(d=a,a=c.shift());return Ua(this,d)?E.prototype.ka.call.apply(E.prototype.ka,[this,a].concat(v(c))):0};function bb(a,b){if(Ta(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.na,b)}catch(c){F(a,c.message)}}}function cb(a,b,c){(a=a.ma[b])&&a.textContent!=c&&(a.textContent=c)}
function $a(a,b,c){var d=!1;c?(c=a.oa.Ca,a.oa.Ca=(c|b)+(c/D|0|b/D|0)*D):(d=va(a.oa.Ca,B.Sa)&&va(b,B.Sa),c=a.oa.Ca,a.oa.Ca=(c&~b)+((c/D|0)&~(b/D|0))*D);d&&a.flush()}
var Fa={yc:"clear",vb:"print"},ab=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Za=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],M={all:B.uc,buffer:B.Sa},Ka={Jb:"command"},db={Kb:13,rb:65,Fb:66,Hb:67,Lb:68,E:69,Nb:70,Ob:71,Pb:72,Qb:73,Sb:74,Ub:75,Wb:76,Yb:77,Zb:78,$b:79,ac:80,Q:81,bc:82,dc:83,ec:84,
fc:85,gc:86,hc:87,ic:88,jc:89,zb:90,Ab:97,Ye:98,Ze:99,d:100,e:101,cf:102,df:103,ff:104,gf:105,hf:106,k:107,jf:108,kf:109,n:110,lf:111,p:112,q:113,r:114,mf:115,t:116,nf:117,pf:118,qf:119,x:120,y:121,z:122},L={Gb:8,ld:9,Tc:10,Kb:13,hd:16,Ac:17,vc:18,Le:19,tb:20,Nd:27,kd:32,Oe:33,Ne:34,Md:35,he:36,Xb:37,rd:38,yb:39,ee:39,Ec:40,be:44,Pe:44,ie:45,Ld:46,de:46,ge:47,ZERO:48,ONE:49,qd:50,md:51,Pc:52,Oc:53,jd:54,gd:55,Fc:56,Zc:57,Mc:59,Lc:61,rb:65,Fb:66,Hb:67,Lb:68,E:69,Nb:70,Ob:71,Pb:72,Qb:73,Sb:74,Ub:75,
Wb:76,Yb:77,Zb:78,$b:79,ac:80,Q:81,bc:82,dc:83,ec:84,fc:85,gc:86,hc:87,ic:88,jc:89,zb:90,Ib:91,ce:91,ae:92,Se:93,fe:93,me:96,De:96,$d:96,ne:97,Be:97,oe:98,Ae:98,pe:99,Ge:99,qe:100,Ee:100,re:101,xe:101,se:102,Ie:102,te:103,Ce:103,ue:104,Ke:104,ve:105,He:105,Fe:106,we:107,Je:109,ye:110,ze:111,Od:112,Sd:113,Td:114,Ud:115,Vd:116,Wd:117,Xd:118,Yd:119,Zd:120,Pd:121,Qd:122,Rd:123,$c:144,dd:145,Kc:173,ed:186,Gc:187,Jd:188,Bc:189,Me:190,Ue:191,Hd:192,je:219,Id:220,Re:221,Qe:222,Jc:224,ke:901,We:1E3},eb={},
fb=(eb[L.Mc]=L.ed,eb[L.Lc]=L.Gc,eb[L.Kc]=L.Bc,eb[L.Jc]=L.Ib,eb),gb={Xb:1,yb:2,le:3},N={},hb=(N[L.Gb]="\b",N[L.ld]="\t",N[L.Tc]="\n",N[L.Kb]="\r",N[L.kd]=" ",N[L.ZERO]="0",N[L.ONE]="1",N[L.qd]="2",N[L.md]="3",N[L.Pc]="4",N[L.Oc]="5",N[L.jd]="6",N[L.gd]="7",N[L.Fc]="8",N[L.Zc]="9",N[L.rb]="A",N[L.Fb]="B",N[L.Hb]="C",N[L.Lb]="D",N[L.E]="E",N[L.Nb]="F",N[L.Ob]="G",N[L.Pb]="H",N[L.Qb]="I",N[L.Sb]="J",N[L.Ub]="K",N[L.Wb]="L",N[L.Yb]="M",N[L.Zb]="N",N[L.$b]="O",N[L.ac]="P",N[L.Q]="Q",N[L.bc]="R",N[L.dc]=
"S",N[L.ec]="T",N[L.fc]="U",N[L.gc]="V",N[L.hc]="W",N[L.ic]="X",N[L.jc]="Y",N[L.zb]="Z",N[L.Xb]="Left",N[L.yb]="Right",N),Ma=["","moz","ms","webkit"],ib={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},K={sb:void 0,Ya:"PCjs.localStorage"};C.WebIO=H;
function P(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;H.call(this,a==b);this.na=a;this.va=b;Q[this.na]||(Q[this.na]={});Q[this.na][this.va]&&this.ka("warning: machine configuration contains multiple '%s' devices\n",this.va);Q[this.na][this.va]=this;this.id=this.na==this.va?this.na:this.na+"."+this.va;jb.push(this);this.oa=kb(this,this.na);this.ready=!0;lb(this,c,d);this.Tb=[]}x(P,H);
function lb(a,b,c){c=b.overrides||c;if(c.length){var d=Sa();for(q in d)if(0<=c.indexOf(q)){var e=d[q];var f=void 0;var g,m=void 0,h=e,p=10;if(h){p||(p=10);var k=0<h.indexOf(",");k&&(h=h.replace(/,/g,""));var l=g=h.charAt(0);"#"==g?(p=8,g=""):"$"==g&&(p=16,g="");l!=g?h=h.substr(1):(l=g=h.substr(0,2),"0b"==g&&k||"^B"==g?(p=2,g=""):"0o"==g||"^O"==g?(p=8,g=""):"^D"==g?(p=10,g=""):"0x"==g&&(p=16,g=""),l!=g&&(h=h.substr(2)));l=g=h.slice(-1);"Y"==g||"y"==g?(p=2,g=""):"."==g?(p=10,g=""):"H"==g||"h"==g?(p=
16,g=""):"K"==g?g="000":"M"==g?g="000000":"G"==g&&(g="000000000");l!=g&&(h=h.slice(0,-1)+g);l=0;10>=p&&(g=h.match(/(-?[0-9]+)B([0-9]*)$/))&&(h=g[1],l=35-((g[2]||35)&255));(p&&10!=p?16==p?null===h.match(/^-?[0-9a-f]+$/i):8==p?null===h.match(/^-?[0-7]+$/):2!=p||null===h.match(/^-?[01]+$/):null===h.match(/^[+-]?[0-9]+$/))||isNaN(f=parseInt(h,p))||(l&&(0>f&&(f+=Math.pow(2,36)),f=0<l?f*Math.pow(2,l):Math.trunc(f/Math.pow(2,-l))),m=f)}f=m;void 0==f&&("true"==e?f=!0:"false"==e?f=!1:(f=e,e='"'+e+'"'));b[q]=
f;F(a,"overriding "+a.va+" property '"+q+"' with "+e)}}a.ha=b;c=b.bindings;c=void 0===c?{}:c;if("undefined"!=typeof document){a.ha.ma||(a.ha.ma=c);(d=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.va);for(var n in c){e=c[n];if(d)n=e;else if(e.match(/^[0-9]+$/)){var q=+e;a.ma[n]=[];do{e=n+q++;e=document.getElementById(e);if(!e)break;a.ma[n].push(e)}while(1);continue}if(q=document.getElementById(e))a.ma[n]=q,a.Oa(n,q)}}b=void 0===b?{}:b;a.version=2;if(a.version){n=
"";var r;a.na!=a.va&&(r=kb(a,a.na).version)&&r!=a.version&&(n="Machine");n||(r=b.version)&&r>a.version&&(n="Config");n&&(r=a.ya("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.$e,a.version,n,r),a.error("%s\n\nClearing your browser's cache may resolve the issue.",r))}}function mb(a,b){var c;try{var d=Q[a.na];if(d)for(c in d){var e=d[c];if(e.va!=e.na&&!b(e))return!1}return!0}catch(f){a.ka("error while enumerating device '%s': %s\n",c,f.message)}return!1}
P.prototype.$a=function(a,b){b=void 0===b?!1:b;if(a){var c=H.prototype.$a.call(this,a,b);if(void 0===c&&b){b=Q[this.na];for(var d in b)if(c=b[d].ma[a])break;c||(c=null);this.ma[a]=c}}return c};function kb(a,b){var c=b,d=a.na,e=d.indexOf(".");0<e&&(d=d.substr(0,e),b=b.substr(e+1));b=(e=Q[d])&&e[b]||null;if(!b){for(e=0;e<jb.length;e++)if(jb[e].id===c){b=jb[e];break}if(!b)throw Error(a.ya('no "%s" device',c));}return b}
function R(a,b,c){var d=null,e=Q[a.na];if(e)for(var f in e)if(e[f].ha["class"]==b){if(d){d=null;break}d=e[f]}if(!d&&(void 0===c||c))throw Error(a.ya("no %s device",b));return d}function nb(a){return a==a.oa&&a.ready?mb(a,function(b){return nb(b)}):a.ready}function ob(a,b){b=void 0===b?a.ready:b;a.ready=b;if(nb(a)){for(;b=a.Tb.pop();)b();a!=a.oa&&ob(a.oa)}}function pb(a,b){if(nb(a))return b(),!0;a.Tb.push(b);return!1}
P.prototype.ka=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];return"number"==typeof a&&Ua(this,a)&&(void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1)),this.oa.Ca&B.Eb&&(void 0===this.Pa&&(this.Pa=R(this,"CPU")),this.Pa))?(a=c.shift(),H.prototype.ka.call(this,"%#06x: %s.%s\n",this.Pa.Cd,this.va,this.ya.apply(this,[a].concat(v(c))).trim())):H.prototype.ka.call.apply(H.prototype.ka,[this,a].concat(v(c)))};function qb(a,b){(a=Q[a.na])&&delete a[b]}
"undefined"!=typeof window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]));var Q="undefined"!=typeof window?window.PCjs.Machines:{},jb="undefined"!=typeof window?window.PCjs.Components:[];B.Eb=1;B.wc=2;B.Ic=4;B.Uc=8;B.ad=16;B.xc=32;B.Sc=64;B.fd=128;B.Vc=256;B.zc=512;B.Wc=1024;B.INT=2048;B.pd=4096;B.sd=8192;B.Xc=16384;B.cd=32768;B.Dc=65536;B.Nc=131072;B.hb=262144;B.nd=524288;B.Mb=1048576;B.Rb=2097152;B.Vb=4194304;
B.Yc=8388608;B.od=16777216;B.Rc=33554432;B.ib=67108864;B.Hc=134217728;B.Qc=268435456;B.Kd=4294967296;M.addr=B.Eb;M.bus=B.wc;M.fault=B.Ic;M.memory=B.Uc;M.ports=B.ad;M.chips=B.xc;M.kbd=B.Sc;M.serial=B.fd;M.misc=B.Vc;M.cpu=B.zc;M.mmu=B.Wc;M["int"]=B.INT;M.trap=B.pd;M.video=B.sd;M.monitor=B.Xc;M.screen=B.cd;M.disk=B.Dc;M.file=B.Nc;M.time=B.hb;M.timer=B.nd;M.event=B.Mb;M.input=B.Rb;M.key=B.Vb;M.mouse=B.Yc;M.touch=B.od;M.info=B.Rc;M.warn=B.ib;M.error=B.Hc;M.halt=B.Qc;C.Device=P;
function rb(a,b,c){P.call(this,a,b,c);this.type="static"==this.ha.type?sb:tb;this.fa=this.ha.addrWidth||16;this.ca=Math.pow(2,this.fa);this.aa=this.ha.blockSize||(16<this.fa?4096:1024);this.aa>this.ca&&(this.aa=this.ca);this.ja=this.ca/this.aa|0;this.da=Math.log2(this.aa)|0;this.ga=(1<<this.da)-1;this.ia=this.ha.dataWidth||8;this.ba=Array(this.ja);this.ea=0;a=new S(a,b+"[NONE]",{size:this.aa,bus:this.va});for(b=0;b<this.ca;b+=this.aa)ub(this,b,this.aa,T.NONE,a);a=this.ea;this.ea+=this.type;a&&this.ea||
(this.bb=this.cb)}x(rb,P);
function ub(a,b,c,d,e){for(var f=b>>>a.da;0<c&&f<a.ba.length;){var g=f*a.aa,m=a.aa-(b-g);m>c&&(m=c);var h=a.ba[f];if(b!=g||m!=a.aa||h&&h.type!=T.NONE)break;var p=h=void 0,k=b,l=a.fa,n=16;l=void 0===l?0:l;h=void 0===h?0:h;var q="",r="",y=-1;n||(n=a.la||10);l&&(y=Math.ceil(l/Math.log2(n)));if(void 0==p)switch(n){case 8:p="0o";break;case 16:p="0x";break;case 10:r=".";default:p=""}isNaN(k)||"number"!=typeof k?(k=void 0,p=r=""):(0>k&&-1<k&&(k=-1),l&&(0>k&&(k+=Math.pow(2,l)),k>=Math.pow(2,l)&&(y=Math.ceil(Math.log(k)/
Math.log(n)))));for(l=h||-1;y--;){l||(q=","+q,l=h);if(void 0==k){if(q="?"+q,0>y)break}else{var z=k%n;k=Math.trunc(k/n);z+=0<=z&&9>=z?48:55;q=String.fromCharCode(z)+q;if(!k&&0>y)break}l--}h=a.va+"["+(p+q+r)+"]";b=e?e.size==a.aa?e:new S(a.na,h,{type:d,Bb:b,size:m,bus:a.va}):new S(a.na,h,{type:d,Bb:b,size:m,bus:a.va});a.ba[f]=b;b=g+a.aa;c-=m;f++}}t=rb.prototype;t.Ea=function(){void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};t.Ga=function(){};t.Cb=function(a){return a&&this.Ka(a)?!0:!1};t.Db=function(a){this.La(a)};
t.Ka=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if((this.type==tb||c.type&T.gb)&&c.Ka){var d=a.shift();if(!c.Ka(d))return!1}}return!0};t.La=function(a){for(var b=0;b<this.ba.length;b++){var c=this.ba[b];if((this.type==tb||c.type&T.gb)&&c.La){var d=[];c.La(d);a.push(d)}}};t.cb=function(a,b){this.ba[a>>>this.da].bb(a&this.ga,b)};var sb=0,tb=1;C.Bus=rb;
function S(a,b,c){P.call(this,a,b,c);this.Bb=this.ha.addr;this.size=this.ha.size;this.type=this.ha.type||T.NONE;this.ca=(a=this.ha.bus)?kb(this,a):R(this,a="Bus");if(!this.ca)throw Error(this.ya("unable to find bus '%s'",a));this.ia=this.ca.ia;this.ea=this.ga=!1;this.values=this.ba=null;a=this.cb;if(this.ca.type==sb){a=this.Ed;if(b=8==this.ia)b=kb(this,this.na),b=!1!==(b&&b.ha&&b.ha.ArrayBuffer||this.ha.ArrayBuffer);b&&(this.ga=!0)}switch(this.type){case T.NONE:this.bb=this.rc;break;case T.cc:this.bb=
this.rc;break;case T.gb:this.bb=a}vb(this,this.ha.values);wb(this)}x(S,P);function vb(a,b){"string"==typeof b?(ob(a,!1),Ra(b,function(c,d,e,f){if(4==e)if(!f&&d){try{var g=JSON.parse(d);vb(a,g.values)}catch(m){a.ka("error (%s) parsing resource: %s\n",m.message,c)}ob(a,!0)}else a.ka("error (%d) loading resource: %s\n",f,c)})):a.ha.values=b}
function wb(a,b){if(a.type>T.NONE&&(a.ga?(a.ba=new ArrayBuffer(a.size),new DataView(a.ba,0,a.size),a.values=new Uint8Array(a.ba,0,a.size),new Uint16Array(a.ba,0,a.size>>1),new Int32Array(a.ba,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}t=S.prototype;
t.Ga=function(){if(this.ha.values)a:{var a=this.ca,b=this.Bb,c=this.size,d=this.ha.values,e=0,f=b&a.ga;b>>>=a.da;c>d.length&&(c=d.length);for(;0<c&&b<a.ba.length;){var g=a.ba[b++];if(!g)break a;for(;0<c&&f<g.size;)g.cb(f++,d[e++]),c--;f=0}}else this.type&T.gb&&this.values&&this.values.fill(0)};t.rc=function(){};t.cb=function(a,b){this.values[a]=b};t.Ed=function(a,b){this.values[a]=b;this.ea=!0;this.bb=this.cb};
t.Ka=function(a){var b=a.shift();if(this.va==b){this.ea=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],f=a[d++];e--;)c[b++]=f;a=c}wb(this,a)}return!0}return!1};t.La=function(a){a.push(this.va);a.push(this.ea);a.push(!1);a.push(this.values?wa(this.values):this.values)};var T={NONE:1,cc:2,gb:4,Te:14,Xe:12};C.Memory=S;
function xb(a,b,c){c.type=T.cc;S.call(this,a,b,c);ub(this.ca,this.ha.addr,this.ha.size,this.ha.type,this);pb(this,this.Ga.bind(this));this.Pa=this.Ja=void 0;if(C.LED&&this.ma[yb]){var d=this;this.da=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.fa=this.values.length/this.da|0;this.aa=new zb(a,b+"LEDs",{"class":"LED",bindings:{container:Na(this,yb)},type:Ab,cols:this.da,rows:this.fa,color:I(this,"colorROM","green"),backgroundColor:I(this,"backgroundColorROM","black"),persistent:!0}),
Bb(this.aa,!0);this.ja=new Cb(a,b+"Input",{"class":"Input",location:[0,0,this.aa.Aa,this.aa.za,this.da,this.fa],bindings:{surface:Na(this,yb)}});this.la=Oa(this)||"";Db(this.ja,function(e,f){if(d.Pa){var g=d.la;0<=e&&0<=f&&(g="");cb(d,Pa,g)}})}}x(xb,S);
xb.prototype.Ka=function(a){var b=!0,c=a.shift();if(c&&this.aa){var d=c.length;this.aa.aa.length==d?(this.aa.aa=c,Eb(this.aa,!0)):(this.ka("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.ka("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};xb.prototype.Ea=function(){void 0===this.Pa&&(this.Pa=R(this,"CPU"));void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};
xb.prototype.La=function(a){this.aa&&(a.push(this.aa.aa),a.push(this.values))};var yb="array",Pa="cellDesc";C.ROM=xb;
function Cb(a,b,c){P.call(this,a,b,c);this.Ca=B.Rb;this.ja=this.qa=null;this.time=R(this,"Time");this.oa=R(this,"Machine");this.wa=I(this,"drag",!1);this.la=I(this,"scroll",!1);this.Aa=I(this,"hexagonal",!1);this.ea=I(this,"releaseDelay",0,void 0);this.fa=!1;a=this.ha.map;this.ba=this.ca=null;if(a)if(a.length)this.ba=a;else{this.ca={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],f=b[d],g=a[f];"string"==typeof g?g=[g]:void 0==g.length&&(e=g.grid,g=g.keys,"string"==typeof g&&(g=[g]));this.ca[f]=
{keys:g,ef:e,state:0}}}this.ra=[];this.sa=[];this.da=this.ta=null;(a=this.ma[Fb])&&Gb(this,a,this.$a(c.focusBinding,!0),this.ha.location);this.Ga()}x(Cb,P);function Db(a,b){a.qa=b}function Hb(a,b){a.ja=b}function Ib(a,b,c){for(var d=0;d<a.ra.length;d++){var e=a.ra[d];e.id===b&&e.nc(b,c)}}
function Gb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.ba||a.ca){var e={};e.Fd=d[0]||0;e.Gd=d[1]||0;e.Za=d[2]||b.clientWidth;e.jb=d[3]||b.clientHeight;e.kb=d[4]||1;e.nb=d[5]||1;e.wd=d[6]||b.naturalWidth||e.Za;e.yd=d[7]||b.naturalHeight||e.jb;e.sc=d[8]||0;e.tc=d[9]||0;e.vd=d[10]||0;e.xd=d[11]||0;a.ba?(e.mb=a.ba.length,e.ab=a.ba[0].length):(e.ab=e.kb,e.mb=e.nb,e.kb=e.nb=0);e.kc=e.Za/(e.ab+e.ab*e.kb)|0;e.lc=e.jb/(e.mb+e.mb*e.nb)|0;e.ud=e.kc*e.kb|0;e.mc=e.lc*e.nb|0;e.eb=e.ob=-1;Jb(a,b,e);Kb(a,b,e);a.time&&
a.ea&&(a.za=Lb(a.time,"timerInputRelease",function(){0>e.eb&&0>e.ob&&Mb(a,-1,-1)}))}if(a.ba||a.ca)a.time&&a.ea&&(a.Ba=Lb(a.time,"timerKeyRelease",function(){Nb(a)})),a.ga=0,a.pa="",a.ia=[],d=b,c&&(d=c,a.da||"BUTTON"!=c.nodeName||(d=document,a.da=c,Ob(a,b),a.ta=b)),Ob(a,d),a.da||(a.da=d)}function Pb(a){a.ea?Qb(a.time,a.Ba,a.ea):Nb(a)}
function Ob(a,b){function c(e,f,g){var m=document.activeElement;a.ka(B.Vb+B.Mb,"%s.onKey%s(%d): %5.2f (%s)\n",m.id||m.nodeName,e,f,Date.now()/1E3%60,void 0!=g?g?"used":"unused":"ignored")}function d(e,f){e=document.activeElement;return a.da&&e!=a.da&&e!=a.ta?null:f||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Rb(a,f,!0,e);c("Down",f,g);g&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var f=e.which||e.charCode,g=
Rb(a,f);c("Press",f,g);g&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var f=e.which||e.keyCode,g=Rb(a,f,!1,e);c("Up",f);g&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function Jb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.fa){var e=a.da;if(e){var f=window.scrollX,g=window.scrollY;e.focus();window.scrollTo(f,g)}d.button||U(a,b,Sb,d,c)}});b.addEventListener("mousemove",function(d){a.fa||U(a,b,Tb,d,c)});b.addEventListener("mouseup",function(d){a.fa||d.button||U(a,b,Ub,d,c)});b.addEventListener("mouseout",function(d){a.fa||(0>c.eb?U(a,b,Tb,d,c):U(a,b,Ub,d,c))})}
function Kb(a,b,c){b.addEventListener("touchstart",function(d){a.la&&(a.fa=!0);U(a,b,Sb,d,c)});b.addEventListener("touchmove",function(d){U(a,b,Tb,d,c)});b.addEventListener("touchend",function(d){U(a,b,Ub,d,c)})}
function Rb(a,b,c,d){if(void 0!=c){var e=fb[b]||b;var f=hb[b];var g=Vb[e];d=d&&d.location==gb.yb;g&Wb&&d&&(g>>=1);g&&(g&Xb&&(c=!(a.aa&g)),a.aa=c?a.aa|g:a.aa&~g,Ib(a,e,c))}else f=String.fromCharCode(b).toUpperCase(),b>=db.rb&&b<=db.zb?a.aa&(Yb|Zb)||(a.aa|=Zb,Ib(a,L.tb,!0)):b>=db.Ab&&b<=db.z&&a.aa&Zb&&(a.aa&=~Zb,Ib(a,L.tb,!1));if(a.ba){if(void 0!=c)return!1;for(e=0;e<a.ba.length;e++)for(g=a.ba[e],d=0;d<g.length;d++)if(0<=g[d].split("|").indexOf(f))return a.ga?16>a.ia.length&&a.ia.push(b):(a.ga=1,a.pa=
f,Mb(a,d,e),Ib(a,f,!0),Pb(a)),!0}if(a.ca){if(void 0==c)return!0;b=Object.keys(a.ca);for(e=0;e<b.length;e++)if(g=b[e],0<=a.ca[g].keys.indexOf(f))return Ib(a,g,c),a.ca[g].state=c?1:0,!0}return!1}function Nb(a){1==a.ga?(a.ga++,Ib(a,a.pa,!1),a.pa="",Mb(a,-1,-1),Pb(a)):(a.ga=0,a.ia.length&&Rb(a,a.ia.shift()))}Cb.prototype.Ga=function(){this.aa=0;this.ua=this.xa=-1};
function U(a,b,c,d,e){var f=-1,g=-1,m=!1,h=-1,p=-1;if(c<Ub){d=d||window.event;d.targetTouches&&d.targetTouches.length?(h=d.targetTouches[0].clientX,p=d.targetTouches[0].clientY,m=1<d.targetTouches.length):(h=d.clientX,p=d.clientY);var k=d.target.getBoundingClientRect();h-=k.left;p-=k.top;h=e.wd/b.offsetWidth*h|0;p=e.yd/b.offsetHeight*p|0;var l=h-e.Fd;var n=p-e.Gd;var q=k=!1;var r=h>=e.sc&&h<e.sc+e.vd&&p>=e.tc&&p<e.tc+e.xd;if(0<=l&&l<e.Za&&0<=n+e.mc||r)if(m||a.la||d.preventDefault(),0<=l&&l<e.Za&&
0<=n&&n<e.jb){q=!0;d=e.Za/e.ab|0;var y=e.jb/e.mb|0,z=l/d|0,w=n/y|0;!a.Aa||w&1||(l-=d>>1,z=l/d|0,z==e.ab-1&&(l=-1));y=w*y+(e.mc>>1);l-=z*d+(e.ud>>1);n-=y;0<=l&&l<e.kc&&0<=n&&n<e.lc&&(f=z,g=w,k=!0)}}l=l||0;n=n||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Sb||c==Ub)for(z=0;z<a.sa.length;z++)w=a.sa[z],c==Ub?w.nc(w.id,!1):(y=n/(b/w.bf|0)|0,(l/(d/w.af|0)|0)==w.rf&&y==w.sf&&w.nc(w.id,!0));if(!m)if(c==Sb)e.eb=h,e.ob=p,q?(Mb(a,f,g),k&&a.ea&&Qb(a.time,a.za,a.ea,!0)):r&&a.oa.Ea();else if(c==Tb)0<=e.eb&&0<=e.ob&&
a.wa?Mb(a,f,g):a.qa&&a.qa(f,g);else if(c==Ub){if(c=a.ea)c=a.time,f=a.za,c=c.aa&&0<f&&f<=c.ba.length?0<=c.ba[f-1].Da:!1;c||Mb(a,-1,-1);e.eb=e.ob=-1}else F(a,"unrecognized action: "+c)}function Mb(a,b,c){if(b!=a.ua||c!=a.xa)a.ua=b,a.xa=c,a.ja&&a.ja(b,c)}var Sb=1,Tb=2,Ub=3,Fb="surface",Yb=3,Wb=170,Zb=512,Xb=3584,V={},Vb=(V[L.hd]=2,V[L.Ac]=8,V[L.vc]=32,V[L.Ib]=128,V[L.tb]=Zb,V[L.$c]=1024,V[L.dd]=2048,V);C.Input=Cb;
function zb(a,b,c){P.call(this,a,b,c,["color","backgroundColor"]);a=this.ma[$b];if(!a)throw Error("LED "+this.ha.ma[$b]+" binding for '"+$b+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Ua=Na(this,$b)+".canvas";b.setAttribute("id",this.Ua);this.Ra=a;this.type=Qa(I(this,"type",Ab,ac),bc,cc);this.ia=dc[this.type][0];this.pa=dc[this.type][1];this.width=I(this,"width",
this.ia,void 0);this.height=I(this,"height",this.pa,void 0);this.da=I(this,"cols",1,void 0);this.ca=this.da+I(this,"colsExtra",0,void 0);this.xa=I(this,"rows",1,void 0);this.ea=this.xa+I(this,"rowsExtra",0,void 0);this.Aa=this.width*this.da;this.za=this.height*this.xa;this.ga=ec("black",0);this.fa=fc(this.ha.color)||this.ga;this.ub=ec(this.fa,1,.25);this.fb=ec(this.fa,1,2);this.la=fc(this.ha.backgroundColor);this.wb=I(this,"fixed",!1);this.wb||(b.style.width="100%",b.style.height="auto");this.Qa=
I(this,"hexagonal",!1);this.xb=I(this,"highlight",!0);this.Ha=I(this,"persistent",this.type<cc);b.setAttribute("width",this.Aa.toString());b.setAttribute("height",this.za.toString());b.style.backgroundColor=this.ga;a.appendChild(b);this.Ta=b.getContext("2d");if(this.sa=document.createElement("canvas"))this.sa.width=this.Na=this.ia*this.da,this.sa.height=this.ua=this.pa*this.xa,this.ba=this.sa.getContext("2d");this.Va=(this.ea+1)*this.ca*4;this.aa=Array(this.Va);this.ra=null;this.Wa=this.da<this.ca?
4*(this.ca-this.da):0;this.ja=this.ta=!1;this.Ia=0;this.Ba=!0;this.qa=0;this.wa=-1;var d=this;this.time=R(this,"Time");gc(this.time,function(e){Eb(d,!1,e)});Bb(d,!0)}x(zb,P);function Bb(a,b){hc(a,a.aa);a.ja=a.ta=!0;b&&Eb(a,!0)}function ic(a){a.la?(a.ba.fillStyle=a.la,a.ba.fillRect(0,0,a.Na,a.ua)):a.ba.clearRect(0,0,a.Na,a.ua)}
function Eb(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.ja||b){if(a.type<cc){var d=0;if(!a.Ha||b)ic(a);else if(a.qa){d=a.da-a.qa;var e=a.ia*d;a.ba.drawImage(a.sa,a.ia*a.qa,0,e,a.ua,0,0,e,a.ua)}for(var f=e=0;f<a.ea;f++){for(var g=0;g<a.da;g++){var m=a.aa[e],h=a.aa[e+1]||a.ga,p=!1,k=!!(a.aa[e+3]&W),l=a.xb&&e==a.wa;!a.Ba&&m&&(m=jc,k=p=!0);if(k||l||b){if(g>=d)a:{k=a;var n=m;m=h;var q=g;h=f;var r=l;q=void 0===q?0:q;h=void 0===h?0:h;r=void 0===r?!1:r;var y=0;if(k.Qa&&!(h&1)&&(y=k.ia>>1,q==k.da-1))break a;
if(m&&m!=k.fa){r=r?ec(m,1,2):m;var z=ec(m,1,.25)}else r=r?k.fb:k.fa,z=k.ub;m=!1;n=n?r:z;r==k.ga&&(n=k.la,m=!0);r=q*k.ia+y;z=h*k.pa;k.Ha&&(q=q*k.ia+y,h*=k.pa,k.la?(k.ba.fillStyle=k.la,k.ba.fillRect(q,h,k.ia,k.pa)):k.ba.clearRect(q,h,k.ia,k.pa));k.ba.fillStyle=n;h=kc[k.type];3==h.length?(k.ba.beginPath(),k.ba.arc(r+h[0],z+h[1],h[2],0,2*Math.PI),m?(k.ba.globalCompositeOperation="destination-out",k.ba.fill(),k.ba.globalCompositeOperation="source-over"):k.ba.fill()):k.ba.fillRect(r+h[0],z+h[1],h[2],h[3])}a.aa[e+
3]=l||p?a.aa[e+3]|W:a.aa[e+3]&~W}e+=4}e+=a.Wa}a.qa=0}else{b="";for(d=0;d<a.aa.length;d+=4)b+=a.aa[d]||" ",a.aa[d+3]&lc&&(b+=".");ic(a);for(f=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;g=a;p=e;l=f;p=void 0===p?0:p;l=void 0===l?0:l;if(k=mc[k])for(h=0;h<k.length;h++)if(m=g,q=nc[k[h]]){y=(void 0===p?0:p)*m.ia;n=(void 0===l?0:l)*m.pa;m.ba.fillStyle=m.fa;m.ba.beginPath();if(3==q.length)m.ba.arc(y+q[0],n+q[1],q[2],0,2*Math.PI);else for(r=0;r<q.length;r+=2)r?m.ba.lineTo(y+q[r],n+q[r+1]):m.ba.moveTo(y+q[r],
n+q[r+1]);m.ba.closePath();m.ba.fill()}if(++e==a.da&&(e=0,++f==a.ea))break}}a.Ta.globalCompositeOperation=a.la&&a.fa!=a.ga?"source-over":"copy";a.Ta.drawImage(a.sa,0,0,a.Na,a.ua,0,0,a.Aa,a.za);a.ja=!1;a.wa=-1}else a.Ha||a.ta||(!c||!a.Ia||c-a.Ia>=(1E3/60|0))&&Bb(a,!0);a.ta=!1;c&&(a.Ia=c)}function oc(a,b){b=void 0===b?!0:b;a.Ba!=b&&(a.Ba=b,a.ja=!0)}function pc(a,b,c){b=4*(c*a.ca+b);return b<=a.aa.length-4?a.aa[b+2]:0}function qc(a,b,c){var d;b=4*(c*a.ca+b);b<=a.aa.length-4&&(d=a.aa[b]);return d}
function fc(a){return(a=a||void 0)&&ib[a]||a}function ec(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=ib[a]||a;if(rc(a,d)){a="rgba(";var e;for(e=0;3>e;e++){var f=Math.round(d[e]*c);f=0>f?0:255<f?255:f;a+=f+","}a+=(e<d.length?d[e]:b)+")"}}return a}function hc(a,b){for(var c=0;c<b.length;c+=4)sc(a,b,c)}function sc(a,b,c){b[c]=a.type<cc?jc:" ";b[c+1]=a.fa==a.ga?null:a.fa;b[c+2]=0;b[c+3]=W}
zb.prototype.Ka=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.fa&&c==this.la&&a&&a.length==this.aa.length){this.aa=a;for(b=0;b<=this.aa.length-4;b+=4)this.aa[b+1]==this.ga&&(this.aa[b+1]=null);Eb(this,!0);return!0}return!1};function rc(a,b){var c=16,d=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);d||(c=10,d=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(d){for(a=1;a<d.length;a++)b[a-1]=Number.parseInt(d[a],c);b.length=a-1;return!0}return!1}
zb.prototype.La=function(a){this.aa&&(a.push(this.fa),a.push(this.la),a.push(this.aa))};function tc(a,b,c,d){var e=null;0<=c&&c<a.ea&&0<=b&&b<a.ca&&(e=!1,d=d||a.fa,d==a.ga&&(d=null),b=4*(c*a.ca+b),a.aa[b+1]!==d&&((a.aa[b+1]=d)||(a.aa[b]=jc),a.aa[b+3]|=W,a.ja=e=!0),a.wa=b,a.ta=!0);return e}function uc(a,b,c,d){if(0<=c&&c<a.ea&&0<=b&&b<a.ca){b=4*(c*a.ca+b);c=0;if(a.aa[b+1])for(var e=0;e<d.length;e++)c=c<<4|d[e]&15;a.aa[b+2]!==c&&(a.aa[b+2]=c,a.aa[b+3]|=W,a.ja=!0);a.wa=b;a.ta=!0}}
function vc(a,b,c,d){var e=!1,f=0&wc;b=4*(c*a.ca+b);if(b<=a.aa.length-4){if(a.aa[b]!==d||(a.aa[b+3]&wc)!==f)a.aa[b]=d,a.aa[b+3]=a.aa[b+3]&~wc|f|W,a.ja=e=!0;a.wa=b;a.ta=!0;a.qa=0}return e}
var bc=0,Ab=1,cc=3,ac={small:bc,round:Ab,square:2,digit:cc},$b="container",jc=0,wc=129,lc=1,W=128,xc={},kc=(xc[bc]=[4,4,4],xc[Ab]=[16,16,14],xc[2]=[2,2,28,28],xc),dc=[[8,8],[32,32],[32,32],[96,128]],nc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},mc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A",
"B","C","D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};C.LED=zb;
function yc(a,b,c){P.call(this,a,b,c);this.Qa=I(this,"cyclesMinimum",1E5,void 0);this.Wa=I(this,"cyclesMaximum",1E9,void 0);this.Ra=Qa(I(this,"cyclesPerSecond",1E6,void 0),this.Qa,this.Wa);this.ta=1E3/60;this.xb=I(this,"updatesPerSecond",2,void 0)||2;this.wb=1E3/this.xb;this.Va=0;this.bd=I(this,"timeLock",!0);this.Ia=this.qa=0;this.Ha=this.ga=1;this.Ua=this.ja=this.Ra/1E4/100;this.za=[];this.la=[];this.ba=[];this.Aa=[];this.Ta=this.aa=this.xa=this.ia=!1;this.pa=this.da=0;a=La("requestAnimationFrame");
if(!a){a="setTimeout";var d=this.ta}this.fb=window[a].bind(window,this.Dd.bind(this),d);this.ub=window[La("cancelAnimationFrame")||"clearTimeout"].bind(window);this.wa=this.ua=this.ea=this.ca=this.Na=0;zc(this)||Ac(this,this.Ha)}x(yc,P);function gc(a,b){a.za.push(b)}t=yc.prototype;
t.Oa=function(a,b){var c=this;switch(a){case Bc:b.onclick=function(){Cc(c)&&(c.aa?Dc(c):c.start())};break;case Ec:b.onclick=function(){Ac(c,c.ga<<1);Fc(c,Gc(c.ja))};break;case Hc:b.onclick=function(){Cc(c)&&(c.aa?F(c,"already running"):c.da?Dc(c):Ic(c,void 0))};break;case Jc:b.addEventListener("mousedown",function(){c.ia=!0}),b.addEventListener("mouseup",function(){zc(c);c.ia=!1}),b.addEventListener("mousemove",function(){c.ia&&zc(c)}),b.addEventListener("change",function(){c.ia=!0;zc(c);c.ia=!1})}P.prototype.Oa.call(this,
a,b)};function Lb(a,b,c){var d=void 0===d?-1:d;var e=a.ba.length+1;a.ba.push({id:b,td:c,lb:d,Da:-1});0<=d&&Qb(a,e,d);return e}
function Kc(a,b,c,d){var e=0,f=a.ja,g=1E6*f;b&&c&&(f=b/(10*c)/100,a.ka(B.hb,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,f),d>a.ta&&(1<a.ga&&(a.ga>>=1,a.ka(B.ib,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.ta,a.ga)),e=d));a.qa=f;a.Ia=f/a.Ua;b=a.Ia/a.ga;a.Na=g/b/60+1E-8;a.ka(B.hb,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.Na,g,b,60);return e}
function Lc(a,b){a.ua=a.ea=b;if(!a.la.length)return a.ea=0,a.ua;for(var c=0;0<a.ea;){if(c<a.la.length){var d=a.la[c++];b=d.pc.call(d,b)||1}else c=b=0;a.ea-=b}return a.ua-a.ea}function Mc(a,b){b=void 0===b?a.ua-a.ea:b;if(!a.aa){if(a.ca)for(var c=0;c<a.la.length;c++){var d=a.la[c];d.qc.call(d)}a.ca=b}a.ca-=b;1>a.ca&&(a.xa=!0);a.wa+=b;a.ua=a.ea=0;a.aa||(a.wa=0);return b}
function Nc(a,b){b=void 0===b?0:b;if(b){var c=b;a.ca+=b}else for(c=a.ca,1>c&&(c=a.ca+=a.Na),0>c&&(a.ka(B.ib,"warning: cycle count dropped below zero: %f\n",c),c=a.ca=0),c|=0,b=a.ba.length;0<b;b--){var d=a.ba[b-1];!(0>d.Da)&&c>d.Da&&(c=d.Da)}return c}function Gc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Cc(a){return a.Ta?!0:(F(a,"not powered"),!1)}
function Oc(a,b){if(1<=b)for(var c=a.ba.length;0<c;c--){var d=a.ba[c-1];0>d.Da||(d.Da-=b,0>=d.Da&&(d.Da=-1,d.td(),0<=d.lb&&Qb(a,c,d.lb)))}}t.Ea=function(a){this.Ta=a;void 0===this.Ja&&(this.Ja=R(this,"Debugger",!1))};
t.Dd=function(a){a=void 0===a?Date.now():a;this.pa=0;if(this.aa){var b=Date.now();if(this.ra){var c=b-this.sa-this.ta;c>this.ta&&(this.fa+=c,this.ka(B.ib,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.sa=b;this.fa||(this.fa=b);this.Ba=0;try{this.xa=!1;do Oc(this,Mc(this,Lc(this,Nc(this))));while(this.aa&&!this.xa)}catch(d){F(this,d.message),Dc(this)}this.ra=Date.now();this.Ba&&(this.fa+=this.Ba,this.sa+=this.Ba);this.sa+=Kc(this,this.wa,this.ra-this.fa,this.ra-this.sa);
this.ra-this.Va>=this.wb&&this.update();for(b=0;b<this.za.length;b++)this.za[b](a);this.pa=this.fb()}};function Ac(a,b){if(void 0!==b){if(1>b||!a.ia&&0<a.qa&&a.qa<.9*a.ja)b=a.Ha;a.ga=b;b=a.Ua*a.ga;a.ja!=b&&(a.ja=b,Fc(a,Gc(a.ja)))}a.fa=a.ra=0;a.ca=a.wa=0;Kc(a);for(b=a.ba.length;0<b;b--){var c=a.ba[b-1];0<=c.lb&&Qb(a,b,c.lb,!0)}}function zc(a){var b=a.ma[Jc];return b?(Ac(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Wa-a.Qa)+a.Qa)/a.Ra|0),!0):!1}
function Qb(a,b,c,d){0<b&&b<=a.ba.length&&(b=a.ba[b-1],d||0>b.Da)&&(c=Math.ceil(a.Ra*(a.bd?a.Ha:a.Ia)/1E3*(void 0===c?1E3:c)),a.aa&&(c+=Mc(a)),b.Da=c)}t.start=function(){if(this.aa||this.da)return!1;this.aa=!0;this.fa=this.ra=0;this.update(!0);this.pa=this.fb();return!0};function Ic(a,b){b=void 0===b?1:b;a.aa||(b&&!a.da&&(a.da=b),a.da&&(a.da--,Oc(a,Mc(a,Lc(a,Nc(a,1)))),a.update(!1),a.da&&setTimeout(function(){Ic(a,0)},0)))}
function Dc(a){a.aa?(a.aa=!1,Mc(a),a.pa&&(a.ub(a.pa),a.pa=0),a.update(!0)):a.da&&(a.da=0,a.update(!0))}t.update=function(a){a&&F(this,this.aa?"started with "+Gc(this.ja)+" target":"stopped");cb(this,Bc,this.aa?"Halt":"Run");cb(this,Hc,this.da?"Stop":"Step");this.ia||(this.ka(B.hb,"getSpeedCurrent(%5.3fhz)\n",1E6*this.qa),Fc(this,this.aa&&this.qa?Gc(this.qa):"Stopped"));for(a=0;a<this.Aa.length;a++){var b=this.Aa[a];b.Ad.call(b)}this.Va=Date.now();this.xa=!0};
function Fc(a,b){cb(a,Pc,b);cb(a,Ec,b)}var Bc="run",Ec="setSpeed",Pc="speed",Hc="step",Jc="throttle";C.Time=yc;function Z(a,b,c){c["class"]="CPU";P.call(this,a,b,c);this.Ja=void 0;this.Cd=0;this.time=R(this,"Time");this.time.la.push(this);this.time.Aa.push(this);this.sa=this.qa=0}x(Z,P);Z.prototype.abort=function(a){F(this,a.message);Dc(this.time)};Z.prototype.pc=function(a){this.sa=this.qa=void 0===a?0:a;return this.oc()};Z.prototype.qc=function(){this.sa-=this.qa;this.qa=0};
Z.prototype.oc=function(){return this.sa-this.qa};
function Qc(a,b,c){Z.call(this,a,b,c);this.ja=I(this,"wrap",!1);this.ta=(this.xa=I(this,"font",""))&&Rc[this.xa]||Rc.Helvetica;this.ua=I(this,"rule","");this.pa=I(this,"pattern","");Sc(this,this.za=I(this,"message",""));this.Ia=I(this,"toggleColor",!1);this.Ha=Array(Tc(this).length);if(c=R(this,"LED",!1)){this.aa=c;Uc(this)||Bb(c,!0);this.ra=R(this,"Input",!1);var d=this;this.Aa=new Cb(a,b+"Input",{"class":"Input",location:[0,0,c.Aa,c.za,c.da,c.xa],drag:!(!this.ra||!this.ra.wa),scroll:!(!this.ra||
!this.ra.la),hexagonal:c.Qa,bindings:{surface:c.Ua}});Hb(this.Aa,function(e,f){var g=d.aa;0<=e&&0<=f&&(d.ia?tc(g,e,f,d.ia)?vc(g,e,f,1):d.Ia?tc(g,e,f):vc(g,e,f,1-qc(g,e,f)):vc(g,e,f,1-qc(g,e,f)),uc(g,e,f,Tc(d,!!qc(g,e,f))),Eb(g))});this.ga=[];this.Ba=c.fa;Vc(this,this.Ba);Wc(this);Xc(this,this.ha[Yc]);Ja(this,this.zd.bind(this))}}x(Qc,Z);t=Qc.prototype;
t.Oa=function(a,b){var c=this,d;switch(a){case Zc:case $c:b.onchange=function(){ad(c,a)};ad(this);break;case Yc:b.onchange=function(){Xc(c)};break;case bd:Ia(b,cd(this.ha[bd]),!1,this.ha.pattern);b.onchange=function(){var e=c.ma[bd];e&&e.options.length&&((e=e.options[e.selectedIndex].value)?Uc(c,e):c.Ga())};break;case dd:b.onclick=function(){var e=ed(c,!0),f=c.ma[fd];f&&(e='"'+f.value+'":"'+e.replace(/^([0-9]+\/)*/,"")+'",');F(c,e)};break;case gd:b.onclick=function(){var e=ed(c);F(c,e);var f=window.location.href;
f=0<=f.indexOf("pattern=")?f.replace(/(pattern=)[^&]*/,"$1"+e.replace(/\$/g,"$$$$")):f+((0>f.indexOf("?")?"?":"&")+"pattern="+e);window.location=f};break;case fd:b.onkeypress=function(e){b.value=String.fromCharCode(e.charCode);var f=c.ma[hd];f&&(f.textContent=b.value);e.preventDefault()};break;default:a.startsWith(id)?b.onclick=function(){Wc(c,a)}:(d=this.ha[bd])&&d[a]&&(b.onclick=function(){Uc(c,a)})}Z.prototype.Oa.call(this,a,b)};
function cd(a){var b={},c;for(c in a){for(var d=c,e=a[c],f=0;f<e.length;f++)if(0==e[f].indexOf("#N")){d=e[f].substr(2).trim();break}b[d]=c}return b}
t.pc=function(a){a=void 0===a?0:a;var b=0;if(0<=a){var c=1;do{switch(this.ua){case jd:var d=0;for(var e=this.aa,f=e.da,g=e.ea,m=this.Ha,h=0;h<g;h++)for(var p=0;p<f;p++){var k=m,l=!1,n=4*(h*e.ca+p);if(n<=e.aa.length-4&&e.aa[n+1]){l=!0;n=e.aa[n+2];for(var q=k.length-1;0<=q;q--)k[q]=n&15,n>>>=4}if(l){d++;if(m[0])m[0]--;else{l=(k=qc(e,p,h))||0;switch(k){case 1:if(l=jc,m[0]=m[2],m[0]){m[0]--;break}case jc:if(m[3]&&(l=this.ga.indexOf(e.aa[4*(h*e.ca+p)+1]||e.ga),0<=l)){for(l+=m[3];l>=this.ga.length;)l-=
this.ga.length;tc(e,p,h,this.ga[l])}l=1;m[0]=m[1];m[0]&&m[0]--}l!==k&&vc(e,p,h,l)}uc(e,p,h,m)}}break;case kd:c=a||c;d=c;d=void 0===d?1:d;e=0;f=this.aa;g=f.ca;m=f.ea;if(f.qa||!ld(this,d))d=0;else{h=f.aa;n=4*d;p=4*g;l=q=k=0;for(this.la=this.wa=-1;k<g-d;){for(var r=1,y=l,z=0;z<m;z++){var w=h[l],u=h[l]=h[l+n];w=u!==w?W:0;h[l+1]=h[l+n+1];h[l+2]=h[l+n+2];h[l+3]=h[l+n+3]|w;u&&(e++,r=0);l+=p}l=y+4;k++<f.da&&(r?q++:(0>this.la&&(this.la=q),q=0))}0>this.la&&(this.la=q);for(this.wa=q;k<g;){n=l;for(q=0;q<m;q++)sc(f,
h,l),l+=p;l=n+4;k++}f.ja=!0;f.qa=d;d=e}break;case md:d=0;e=this.aa;f=e.aa;g=e;g.ra||(g.ra=Array(g.Va),hc(g,g.ra));g=g.ra;m=e.da;h=e.ea;p=4*m+e.Wa;k=h*p;l=0;n=l-p;q=n-4;r=n+4;y=l-4;z=l+4;u=l+p;w=u-4;for(var G=u+4,J=0;J<h;J++){J?J==h-1&&(this.ja?(u-=k,w-=k,G-=k):u=w=G=k):this.ja?(n+=k,q+=k,r+=k):n=q=r=k;for(var X=0;X<m;X++){X?1==X?this.ja?(y-=p,q-=p,w-=p):(y=l-4,q=n-4,w=u-4):X==m-1&&(this.ja?(z-=p,r-=p,G-=p):z=r=G=k):this.ja?(y+=p,q+=p,w+=p):y=q=w=k;var Y=f[l],O=f[q]+f[n]+f[r]+f[z]+f[G]+f[u]+f[w]+f[y];
3==O?Y=1:2!=O&&(Y=jc);g[l]=Y;g[l+1]=f[l+1];g[l+2]=f[l+2];g[l+3]=f[l+3]|(f[l]!==Y?W:0);l+=4;q+=4;n+=4;r+=4;z+=4;G+=4;u+=4;w+=4;y+=4;1==Y&&d++}this.ja?(J||(n-=k,q-=k,r-=k),z+=p,r+=p,G+=p):(J||(n=l-p,q=n-4),z=l+4,r=n+4,G=u+4)}f=e.aa;e.aa=e.ra;e.ra=f;e.ja=!0}a||F(this,"active cells: "+d);b+=c}while(b<a)}return b};t.qc=function(){};t.oc=function(){return 0};function nd(a,b){var c=0;(a=a.ma[b])&&a.options&&(c=(c=a.options[a.selectedIndex])&&+c.value||0);return c}
function Tc(a,b){var c=0;if(b&&(b=a.ma[od])&&b.options){var d=b.options[b.selectedIndex];d&&(c=+d.value||0,b.selectedIndex++,d=nd(a,pd)+nd(a,qd),!(d&1)&&c==d-1||0>b.selectedIndex||b.selectedIndex>=b.options.length)&&(b.selectedIndex=0)}c=[c];for(b=1;b<rd.length;b++)c.push(nd(a,rd[b]));return c}
function Uc(a,b){var c=a.aa,d=-1,e=-1,f="";b||a.pa.match(/^[0-9]/)||(b=a.pa);if(b){var g=a.ha[bd];g=g&&g[b];if(!g)return F(a,"unknown pattern: "+b),!1;F(a,"loading pattern '"+b+"'");for(var m=b=0;b<g.length;b++){var h=g[b];if("#"==h[0])F(a,h);else if(m++){var p=h.indexOf("!");if(0<=p){f+=h.substr(0,p);break}f+=h}else{var k=h.match(/x\s*=\s*([0-9]+)\s*,\s*y\s*=\s*([0-9]+)\s*(?:,\s*rule\s*=\s*(\S+)|)/i);if(!k)return F(a,"unrecognized header line"),!1;var l=+k[1];var n=+k[2];k=k[3]}}}else{if(!a.pa)return!1;
f=0;k=a.pa.split("/");5==k.length&&(d=+k[f++],e=+k[f++]);if(3==k.length||5==k.length)l=+k[f++],n=+k[f++],f=k[f];else return F(a,"unrecognized pattern: "+a.pa),!1;k=a.ua}if(k!=a.ua)return F(a,"unsupported rule: "+k),!1;0>d&&(d=c.ca-l>>1);0>e&&(e=c.ea-n>>1);return 0>d||d+l>c.ca||0>e||e+n>c.ea?(a.ka("pattern too large (%d,%d)\n",l,n),!1):0<sd(a,d,e,f)}
function sd(a,b,c,d,e){e=void 0===e?!1:e;var f=a.aa,g=[0,0,0,1],m=0,h=!1,p=!1;d=d.split(/([a-z$])/i);e||Bb(f);for(var k=0,l=b,n=0;k<d.length-1;){var q=d[k++],r=d[k++],y=+q;for(q=""===q?1:y;q--;){var z=0,w=!1;switch(r){case "$":h=p=!1;b=l;c++;break;case "C":m=y;p=!0;break;case "R":g[0]=y;h=!0;break;case "G":g[1]=y;h=!0;break;case "B":g[2]=y;h=!0;break;case "A":g[3]=y;h=!0;break;case "b":w=vc(f,b,c,jc);z++;break;case "o":w=vc(f,b,c,1);z++;break;default:a.ka("unrecognized pattern token: %s\n",r)}if(null==
w)a.ka("invalid pattern position (%d,%d)\n",b,c);else{if(h){w=f;var u=g;w=4>u.length||1==u[3]?w.ya("#%02x%02x%02x",u[0],u[1],u[2]):w.ya("rgba(%d,%d,%d,%d)",u[0],u[1],u[2],u[3]);tc(f,b,c,w)}p&&(w=4*(c*f.ca+b),w<=f.aa.length-4&&f.aa[w+2]!=m&&(f.aa[w+2]=m));n<b&&(n=b);b+=z}}}e||Eb(f,!0);return 0>(n-=l-1)?0:n}
t.Ka=function(a){var b=a.stateCPU||a[0];if(!b||!b.length)return F(this,"Invalid saved state"),!1;var c=b.shift();if(2!==(c|0))return this.ka("Saved state version mismatch: %3.2f\n",c),!1;try{this.ca=b.shift(),this.da=b.shift(),this.ea=b.shift(),this.ba=b.shift()}catch(d){return F(this,"Controller state error: "+d.message),!1}return Sa().message||Sa().pattern||Sa()[Yc]||!(a=a.stateLEDs||a[1])||!this.aa||this.aa.Ka(a)?!0:!1};
t.zd=function(a){var b="",c=a.shift();switch(a.shift()[0]){case "s":Sc(this,a.join(" "));break;case "?":b="";td.forEach(function(d){b+=d+"\n"});b&&(b="additional commands:\n"+b);break;default:c&&(b="unrecognized command '"+c+"' (try '?')\n")}return b};t.Cb=function(a){return a&&this.Ka(a)?!0:!1};t.Ea=function(a){a?this.time.start():Dc(this.time)};t.Ga=function(){F(this,"reset");Bb(this.aa,!0);oc(this.aa,!0);this.za&&Sc(this,this.za)};t.Db=function(a){this.La(a)};t.Ad=function(){this.time.aa||Eb(this.aa)};
function ld(a,b,c,d){b=void 0===b?1:b;c&&(a.ea=c,a.ba=d);switch(a.ea){case ud:return!1;case vd:case wd:if(0<a.ba)return a.ba-=b,!0;break;case xd:if(0<a.ba)return a.ba-=b,!1;break;case yd:if(a.la>a.wa)return!0;break;case zd:oc(a.aa,!1);a.ea=xd;break;case Ad:oc(a.aa,!0);a.ea=xd;break;default:return!1}if(c)a=!1;else a:if(b=void 0===b?1:b,a.ca){a.da>=a.ca.length&&(a.da=0);c=a.ca[a.da++];if("$"==c){d=0;for(var e=a.da;e<a.ca.length;){var f=a.ca.charCodeAt(e)-48;if(0>f||9<f)break;d=10*d+f;e++}if(e<a.ca.length)if(f=
a.ca[e++],"$"==f)a.da=e;else{var g=Bd[f];if(g){a.da=e;a=ld(a,b,g,d);break a}F(a,"unrecognized message code: $"+f)}}" "==c?a.ba+=2:(d=a.aa.da+1,e=0>a.ba?a.ba:0,c=a.ta[c]||a.ta[c.toUpperCase()],f=Math.round((a.aa.xa-a.ta.height)/2),c&&(a.ba+=sd(a,d+e,0>f?0:f,c,!0)),a.ba+=2-b);a.ea=wd;a=!0}else a.ea=ud,a=!1;return a}
function ed(a,b){function c(Y){var O=!1;null==k[3]&&(k[3]=1);if(z){if(h){if(k[0]!==r[0]||k[1]!==r[1]||k[2]!==r[2]||k[3]!==r[3])O=!0;X!==y&&(O=!0)}p!==q&&(O=!0);if(O||Y&&q)h&&(l[0]!==r[0]&&(l[0]=r[0],e+=(r[0]||"")+"R"),l[1]!==r[1]&&(l[1]=r[1],e+=(r[1]||"")+"G"),l[2]!==r[2]&&(l[2]=r[2],e+=(r[2]||"")+"B"),l[3]!==r[3]&&(l[3]=r[3],e+=(r[3]||"")+"A"),n!==y&&(n=y,e+=(y||"")+"C")),1<z&&(e+=z),e+=1===q?"o":"b",O=!0}Y?(e+="$",z=0):(O?z=1:z++,q=p,r[0]=k[0],r[1]=k[1],r[2]=k[2],r[3]=k[3],y=X)}var d=a.aa,e="",
f=0,g=a.aa.ca,m=a.aa.ea,h=!!a.ga.length,p,k=[0,0,0],l=[0,0,0,1],n=0,q=0,r=[0,0,0,1],y=0,z=0;a=0;var w=d.ca-1,u=d.ea-1;if(b){b&&(a=w,w=0);for(g=0;g<d.ea;g++)for(m=0;m<d.ca;m++)(p=qc(d,m,g))&&b&&(a>m&&(a=m),w<m&&(w=m));g=w-a+1;m=u+1;0>g&&(g=0);0>m&&(m=0)}for(var G=0;G<=u;G++){for(var J=a;J<=w;J++){p=qc(d,J,G);rc(d.aa[4*(G*d.ca+J)+1]||d.ga,k);var X=pc(d,J,G);c()}c(!0)}if(!b)for(;"$"==e[0];)f++,m--,e=e.slice(1);for(;"$$"==e.slice(-2);)m--,e=e.slice(0,-1);"$"==e&&(m=0);e=(b?"":"0/"+f+"/")+g+"/"+m+"/"+
e.slice(0,-1);return e=e.replace(/\$+$/,"")}t.La=function(a){var b=[],c=[];b.push(2);b.push(this.ca);b.push(this.da);b.push(this.ea);b.push(this.ba);this.aa&&this.aa.La(c);a.push(b);a.push(c)};function Sc(a,b){a.ca!=b&&(b&&F(a,"new message: '"+b+"'"),a.ca=b);a.ea=vd;a.da=a.ba=0}t.toString=function(){return""};
function Xc(a,b){var c=a.ma[Yc];if(c&&c.options.length){if(b)for(var d=0;d<c.options.length;d++)if(c.options[d].value==b){c.selectedIndex=d;break}b=c.options[c.selectedIndex].value;a=a.aa;a.Ra&&(a.Ra.style.backgroundImage=b?"url('"+b+"')":"none")}}
function ad(a,b){var c=a.ma[Zc],d=a.ma[$c];b=b===Zc;c&&!c.options.length&&(Ia(c,a.ha.colors,!0),b=!0);if(c&&d&&(!d.options.length||b)){a.fa=a.ha.colors[c.options[c.selectedIndex].value];for(var e in a.fa)if(b=a.ha[e.toLowerCase()])"#"!=b[0]&&(b="#"+b),F(a,"overriding color '"+e+"' with "+b+" (formerly "+a.fa[e]+")"),a.fa[e]=b;Ia(d,a.fa,!0)}c&&d&&d.options.length&&(a.ia=d.options[d.selectedIndex].value,Wc(a))}
function Vc(a,b){var c=a.ma[$c];if(c){var d;for(d=0;d<c.options.length;d++)if(c.options[d].value==b){a.ia=b;c.selectedIndex!=d&&(c.selectedIndex=d);break}d==c.options.length&&(c.selectedIndex=0)}}
function Wc(a,b){var c=1,d;!b&&a.ia&&(d=a.ma[Cd])&&(d.style.backgroundColor=a.ia);if(a.fa)for(var e in a.fa){var f=a.fa[e];a.ga&&(a.ga[c-1]=f);var g=id+c++;d=a.ma[g];if(!d)break;d.style.display="inline-block";g==b&&Vc(a,f);if(b&&b!=g||f!=a.ia)f=ec(f,1,.5);d.style.backgroundColor=f}for(;;){b=id+c++;b=a.ma[b];if(!b)break;b.style.display="none"}}
var Zc="colorPalette",$c="colorSelection",id="colorSwatch",Cd="colorSwatchSelected",od="countInit",pd="countOn",qd="countOff",Yc="backgroundImage",bd="patterns",fd="symbolInput",hd="symbolPreview",dd="save",gd="saveToURL",rd=[null,pd,qd,"countCycle"],td=["s\t\tset string"],vd="load",wd="scroll",xd="pause",ud="halt",yd="center",zd="off",Ad="on",Bd={b:zd,c:yd,h:ud,o:Ad,p:xd,s:wd},jd="A4",kd="L1",md="B3/S23",Rc={Helvetica:{width:16,height:16,0:"$2b2o$bo2bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$bo2bo$2b2o",
1:"$3bo$2b2o$4o$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo",2:"$2b3o$bo3bo$o5bo$o5bo$6bo$5bo$3b2o$2bo$bo$o$7o",3:"$b4o$o4bo$o4bo$5bo$4bo$2b2o$4bo$5bo$o4bo$o4bo$b4o",4:"$5bo$4b2o$3bobo$2bo2bo$bo3bo$o4bo$o4bo$8o$5bo$5bo$5bo",5:"$6o$o$o$o$4o$4bo$5bo$5bo$5bo$o3bo$b3o",6:"$2b4o$bo4bo$o$o$o$ob4o$2o4bo$o5bo$o5bo$bo4bo$2b4o",7:"$8o$7bo$6bo$5bo$4bo$4bo$3bo$3bo$2bo$2bo$2bo",8:"$b4o$o4bo$o4bo$o4bo$bo2bo$2b2o$bo2bo$o4bo$o4bo$o4bo$b4o",9:"$b4o$o4bo$o5bo$o5bo$o4b2o$b4obo$6bo$6bo$6bo$o4bo$b4o",A:"$3b2o$2bo2bo$bo4bo$bo4bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo",
B:"$6o$o5bo$o5bo$o5bo$o4bo$7o$o6bo$o6bo$o6bo$o6bo$7o",C:"$2b4o$bo4bo$o6bo$o$o$o$o$o$o6bo$bo4bo$2b4o",D:"$6o$o5bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o5bo$6o",E:"$7o$o$o$o$o$6o$o$o$o$o$7o",F:"$7o$o$o$o$o$6o$o$o$o$o$o",G:"$2b4o$bo4bo$o$o$o$o3b4o$o6bo$o6bo$o6bo$bo4bo$2b4o",H:"$o6bo$o6bo$o6bo$o6bo$o6bo$8o$o6bo$o6bo$o6bo$o6bo$o6bo",I:"$o$o$o$o$o$o$o$o$o$o$o",J:"$5bo$5bo$5bo$5bo$5bo$5bo$5bo$o4bo$o4bo$o4bo$b4o",K:"$o6bo$o5bo$o4bo$o3bo$o2bo$ob2o$2o2bo$o4bo$o5bo$o6bo$o7bo",L:"$o$o$o$o$o$o$o$o$o$o$7o",M:"$o8bo$2o6b2o$obo4bobo$obo4bobo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o8bo$o8bo$o8bo$o8bo",
N:"$2o5bo$obo4bo$obo4bo$o2bo3bo$o2bo3bo$o3bo2bo$o3bo2bo$o4bobo$o4bobo$o4bobo$o5b2o",O:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo6bo$2bo4bo$3b4o",P:"$6o$o5bo$o6bo$o6bo$o6bo$o5bo$6o$o$o$o$o",Q:"$3b4o$2bo4bo$bo6bo$o8bo$o8bo$o8bo$o8bo$o8bo$bo4bobo$2bo4bo$3b4obo$9bo",R:"$6o$o5bo$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo$o6bo",S:"$2b4o$bo4bo$o6bo$o$bo$2b4o$6bo$7bo$o6bo$bo4bo$2b4o",T:"$9o$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo$4bo",U:"$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",V:"$o8bo$o8bo$bo6bo$bo6bo$bo6bo$2bo4bo$2bo4bo$2bo4bo$3bo2bo$3bo2bo$4b2o",
W:"$o4b2o4bo$o4b2o4bo$o4b2o4bo$o3bo2bo3bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$bo2bo2bo2bo$2b2o4b2o$2b2o4b2o$2b2o4b2o",X:"$o8bo$bo6bo$2bo4bo$3bo2bo$4b2o$4b2o$4b2o$3bo2bo$2bo4bo$bo6bo$o8bo",Y:"$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$9o$8bo$7bo$6bo$5bo$4bo$3bo$2bo$bo$o$9o",a:"$$$$b4o$o4bo$5bo$b5o$o4bo$o4bo$o3b2o$b3obo",b:"$o$o$o$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o",c:"$$$$2b4o$bo4bo$o$o$o$o$bo4bo$2b4o",d:"$6bo$6bo$6bo$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo",e:"$$$$2b3o$bo3bo$o5bo$7o$o$o$bo4bo$2b4o",
f:"$2b2o$bo2bo$bo$bo$4o$bo$bo$bo$bo$bo$bo",g:"$$$$2b2obo$bo2b2o$o4bo$o4bo$o4bo$bo2b2o$2b2obo$5bo$5bo$o4bo$b4o",h:"$o$o$o$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",i:"$$o$$o$o$o$o$o$o$o$o",j:"$$3bo$$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$3bo$o2bo$b2o",k:"$o$o$o$o4bo$o3bo$o2bo$obo$2obo$o3bo$o4bo$o5bo",l:"$o$o$o$o$o$o$o$o$o$o$o",m:"$$$$ob2o3b2o$2o2bobo2bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo$o4bo4bo",n:"$$$$ob3o$2o3bo$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo",o:"$$$$2b4o$bo4bo$o6bo$o6bo$o6bo$o6bo$bo4bo$2b4o",p:"$$$$ob3o$2o3bo$o5bo$o5bo$o5bo$o5bo$2o3bo$ob3o$o$o$o",
q:"$$$$2b3obo$bo3b2o$o5bo$o5bo$o5bo$o5bo$bo3b2o$2b3obo$6bo$6bo$6bo",r:"$$$$ob2o$2o2bo$o$o$o$o$o$o",s:"$$$$b4o$o4bo$o$b4o$5bo$5bo$o4bo$b4o",t:"$$bo$bo$4o$bo$bo$bo$bo$bo$bo2bo$2b2o",u:"$$$$o4bo$o4bo$o4bo$o4bo$o4bo$o4bo$o3b2o$b3obo",v:"$$$$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo",w:"$$$$o3b2o3bo$o3b2o3bo$o3b2o3bo$o3b2o3bo$bobo2bobo$bobo2bobo$bobo2bobo$2bo4bo",x:"$$$$$o5bo$bo3bo$2bobo$3bo$2bobo$bo3bo$o5bo",y:"$$$$o5bo$o5bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo$3bo$2bo$2o",z:"$$$$6o$5bo$4bo$3bo$2bo$bo$o$6o",
"!":"$o$o$o$o$o$o$o$o$$o$o",'"':"$obo$obo$obo$obo","#":"$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo$8o$2bo2bo$2bo2bo$2bo2bo",$:"3bo$2b4o$bobo2bo$o2bo$o2bo$bobo$2b3o$3bobo$3bo2bo$3bo2bo$o2bobo$b4o$3bo","%":"$b2o7bo$o2bo5bo$o2bo4bo$o2bo3bo$o2bo2bo$b2o2bo2b2o$4bo2bo2bo$3bo3bo2bo$2bo4bo2bo$bo5bo2bo$o7b2o","&":"$b3o$o3bo$o3bo$o3bo$bobo$2bo$bobo$o3bobo$o4bo$o3bobo$b3o3bo","'":"$o$o$o$o","(":"$3bo$2bo$bo$bo$o$o$o$o$o$o$bo$bo$2bo$3bo",")":"$o$bo$2bo$2bo$3bo$3bo$3bo$3bo$3bo$3bo$2bo$2bo$bo$o","*":"2bo$obobo$b3o$b3o$o3bo",
"+":"$$$$3bo$3bo$3bo$7o$3bo$3bo$3bo",",":"$$$$$$$$$$2o$2o$bo$o",".":"$$$$$$$$$$2o$2o","/":"$3bo$3bo$2bo$2bo$2bo$bo$bo$bo$o$o$o",":":"$$$$2o$2o$$$$$2o$2o",";":"$$$$2o$2o$$$$$2o$2o$bo$o","<":"$$$$6b2o$4b2o$2b2o$2o$2o$2b2o$4b2o$6b2o",">":"$$$$2o$2b2o$4b2o$6b2o$6b2o$4b2o$2b2o$2o","=":"$$$$$$8o$$$8o","?":"$b4o$o4bo$o4bo$5bo$4bo$3bo$2bo$2bo$$2bo$2bo","@":"$3b4o$2bo4bo$bo6bo$o3b2o3bo$o2bo2bo2bo$o2bo2bo2bo$o3b2o3bo$o5b3o$bo$2bo5bo$3b5o","[":"$3o$o$o$o$o$o$o$o$o$o$o$o$o$3o","]":"$3o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo$3o",
"\\":"$o$o$bo$bo$bo$2bo$2bo$2bo$3bo$3bo$3bo","^":"$2b2o$2b2o$bo2bo$bo2bo$o4bo$o4bo",_:"$$$$$$$$$$$$$8o","`":"o$bo$2bo","{":"$2b2o$bo$bo$bo$bo$bo$bo$o$bo$bo$bo$bo$bo$2b2o","}":"$2o$2bo$2bo$2bo$2bo$2bo$2bo$3bo$2bo$2bo$2bo$2bo$2bo$2o","|":"o$o$o$o$o$o$o$o$o$o$o$o$o$o$o","~":"$$$$$$b3o3bo$o3b3o"},ATT4425:{width:9,height:13,A:"$3bo$3bo$2bobo$2bobo$bo3bo$bo3bo$7o$o5bo$o5bo",B:"$6o$bo4bo$bo4bo$bo3bo$b4o$bo3bo$bo4bo$bo4bo$6o",C:"$2b5o$bo$o$o$o$o$o$bo$2b5o",D:"$5o$bo3bo$bo4bo$bo4bo$bo4bo$bo4bo$bo4bo$bo3bo$5o",
E:"$6o$o$o$o$5o$o$o$o$6o",F:"$6o$o$o$o$5o$o$o$o$o",G:"$2b3o$bo3bo$o$o$o$o3b3o$o4bo$bo3bo$2b3o",H:"$o5bo$o5bo$o5bo$o5bo$7o$o5bo$o5bo$o5bo$o5bo",I:"$3o$bo$bo$bo$bo$bo$bo$bo$3o",J:"$4bo$4bo$4bo$4bo$4bo$4bo$o3bo$o3bo$b3o",K:"$o5bo$o4bo$o3bo$o2bo$3o$o2bo$o3bo$o4bo$o5bo",L:"$o$o$o$o$o$o$o$o$7o",M:"$o5bo$2o3b2o$obobobo$o2bo2bo$o5bo$o5bo$o5bo$o5bo$o5bo",N:"$o5bo$2o4bo$obo3bo$obo3bo$o2bo2bo$o3bobo$o3bobo$o4b2o$o5bo",O:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",P:"$6o$o5bo$o5bo$o5bo$6o$o$o$o$o",Q:"$2b3o$bo3bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o$3bo2bo$4b3o",
R:"$6o$o5bo$o5bo$o5bo$6o$o2bo$o3bo$o4bo$o5bo",S:"$2b3o$bo3bo$bo$2bo$3bo$4bo$o4bo$bo3bo$2b3o",T:"$5o$2bo$2bo$2bo$2bo$2bo$2bo$2bo$2bo",U:"$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$o5bo$bo3bo$2b3o",V:"$o5bo$o5bo$bo3bo$bo3bo$bo3bo$2bobo$2bobo$3bo$3bo",W:"$o5bo$o5bo$o2bo2bo$o2bo2bo$obobobo$obobobo$2o3b2o$2o3b2o$o5bo",X:"$o5bo$bo3bo$bo3bo$2bobo$3bo$2bobo$bo3bo$bo3bo$o5bo",Y:"$o5bo$o5bo$bo3bo$2bobo$3bo$3bo$3bo$3bo$3bo",Z:"$7o$6bo$5bo$4bo$3bo$2bo$bo$o$7o"}};C.LEDCtrl=Qc;
function Dd(a,b,c){P.call(this,a,a);var d=this;this.ca=!1;this.ga=c;this.ba="";this.fa=this.ea=!1;ob(this,!1);this.Ca=B.Cc;b=b.trim();"{"==b[0]?Ed(this,b):(this.ba=b,Ra(this.ba,function(e,f,g,m){4==g&&(!m&&f?(Ed(d,f),Fd(d)):d.ka("error (%d) loading configuration: %s\n",m,e))}));window.addEventListener("load",function(){d.fa=!0;Fd(d)});window.addEventListener(Va("iOS")?"pagehide":Va("Opera")?"unload":"beforeunload",function(){Gd(d)});window.addEventListener("pageshow",function(){d.ca||d.Ea(!0)})}
x(Dd,P);Dd.prototype.Oa=function(a,b){var c=this;switch(a){case Hd:b.onclick=function(){c.Ea()};break;case Id:b.onclick=function(){c.Ga()}}P.prototype.Oa.call(this,a,b)};
function Fd(a){var b=!0;if(a.ea&&a.fa){for(var c in a.aa){var d=void 0,e=a.aa[c];try{d=e["class"],C[d]?"Machine"==d?(a.ka("PCjs %s v%3.2f\n%s\n",e.name,2,Jd),a.ba&&a.ka("Configuration: %s\n",a.ba)):new C[d](a.na,c,e):a.ka('unrecognized %s device "%s"\n',d,c)}catch(g){e.optional||(a.ka('error initializing %s device "%s": %s\n',d,c,g.message),b=!1),qb(a,c)}}if(a.da){var f=Wa(a);mb(a,function(g){return g.Cb&&!g.Cb(f)?(g.ka('unable to restore state for device "%s"\n',g.va),!1):!0})}ob(a,!0);pb(a,a.Ea.bind(a,
b))||a.ka("machine %s not ready to power, waiting for device(s)\n",a.na)}}
function Ed(a,b){try{a.aa=JSON.parse(b);var c=a.aa[a.na];if(!c){c=a.aa[ya(a.ba)];if(!c)throw Error("configuration missing machine ID");a.aa[a.na]=c}lb(a,c,["autoSave","autoStart"]);a.da=!1!==a.ha.autoSave;a.ia=!1!==a.ha.autoStart;if(a.ga){var d=eval("("+a.ga+")"),e;for(e in d)a.ha[e]=d[e]}a.ea=!0}catch(f){c=f.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),F(a,"machine '"+a.na+"' initialization error: "+c)}}
Dd.prototype.Ea=function(a){a=void 0===a?!this.ca:a;if(nb(this)){var b=this;a&&F(this,"power on");mb(this,function(c){c.Ea&&c!=b&&("CPU"!=c.ha["class"]||b.ia||nb(b)?c.Ea(a):c.time.update(!0));return!0});(this.ca=a)||F(this,"power off")}};Dd.prototype.Ga=function(){if(nb(this)){var a=this;mb(this,function(b){b.Ga&&b!=a&&b.Ga();return!0});F(this,"reset")}};function Gd(a){if(a.da){var b=[];mb(a,function(c){c.Db&&c.Db(b);return!0});bb(a,b)}a.Ea(!1)}var Hd="power",Id="reset",Jd="Copyright \u00a9 2012-2020 Jeff Parsons <Jeff@pcjs.org>";
window.LEDs=function(a,b,c){var d=new Dd(a,b,c);window.command=function(e){return Xa(d,e)};return d};C.Machine=Dd;})()

//# sourceMappingURL=led.js.map
