(function(){/*
 https://www.pcjs.org/modules/defs.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/numio.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/stdio.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/webio.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/device.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/input.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/led.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/monitor.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/time.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/bus.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/memory.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/ram.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/rom.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/cpu.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/debugger.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/cpux86.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/dbgx86.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/video.js (C) 2012-2021 Jeff Parsons
 https://www.pcjs.org/modules/machine.js (C) 2012-2021 Jeff Parsons
*/
var l;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function q(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function t(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function y(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Af=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
t("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});t("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
t("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
t("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,f){this.I=g;ca(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.I};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}t("Array.prototype.keys",function(a){return a?a:function(){return na(this,function(b){return b})}});
t("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function A(a){return a?a:Array.prototype.fill}t("Int8Array.prototype.fill",A);t("Uint8Array.prototype.fill",A);t("Uint8ClampedArray.prototype.fill",A);t("Int16Array.prototype.fill",A);t("Uint16Array.prototype.fill",A);t("Int32Array.prototype.fill",A);
t("Uint32Array.prototype.fill",A);t("Float32Array.prototype.fill",A);t("Float64Array.prototype.fill",A);t("Number.parseInt",function(a){return a||parseInt});t("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});function oa(){}var pa=new ArrayBuffer(2);(new DataView(pa)).setUint16(0,256,!0);new Uint16Array(pa);var B={Ab:0xffffffffffff,NONE:0,Ec:0,Fa:0x800000000000},C={};C.Defs=oa;function qa(){}y(qa,oa);
function ra(a,b){if(a){b||(b=10);var c,d=0<a.indexOf(",");d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);"#"==c?(b=8,c=""):"$"==c&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),"0b"==c&&d||"^B"==c?(b=2,c=""):"0o"==c||"^O"==c?(b=8,c=""):"^D"==c?(b=10,c=""):"0x"==c&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);"Y"==c||"y"==c?(b=2,c=""):"."==c?(b=10,c=""):"H"==c||"h"==c?(b=16,c=""):"K"==c?c="000":"M"==c?c="000000":"G"==c&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var g;e=0;10>=b&&(c=a.match(/(-?[0-9]+)B([0-9]*)$/))&&
(a=c[1],e=35-((c[2]||35)&255));if((b&&10!=b?16==b?null!==a.match(/^-?[0-9a-f]+$/i):8==b?null!==a.match(/^-?[0-7]+$/):2==b&&null!==a.match(/^-?[01]+$/):null!==a.match(/^[+-]?[0-9]+$/))&&!isNaN(g=parseInt(a,b))){e&&(0>g&&(g+=Math.pow(2,36)),g=0<e?g*Math.pow(2,e):Math.trunc(g/Math.pow(2,-e)));var f=g}}return f}
function D(a,b,c,d,e){d=void 0===d?0:d;var g=void 0===g?0:g;var f="",h="",k=-1;c||(c=a.ca||10);d&&(k=Math.ceil(d/Math.log2(c)));if(void 0==e)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:h=".";default:e=""}isNaN(b)||"number"!=typeof b?(b=void 0,e=h=""):(0>b&&-1<b&&(b=-1),d&&(0>b&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(k=Math.ceil(Math.log(b)/Math.log(c)))));for(a=g||-1;k--;){a||(f=","+f,a=g);if(void 0==b){if(f="?"+f,0>k)break}else if(d=b%c,b=Math.trunc(b/c),d+=0<=d&&9>=d?48:55,f=String.fromCharCode(d)+
f,!b&&0>k)break;a--}return e+f+h}function sa(a,b){var c=a/E|0,d=b/E|0;return(a&b)==(b|0)&&(c&d)==d}var E=Math.pow(2,32);C.NumIO=qa;function F(){this.Da={};for(var a=0;22>a;a++)this.Da["ACDFHGMNSTWYbdfjcsoXx%"[a]]=null}y(F,qa);function ta(a,b,c){a.Da[b]||(a.Da[b]=c)}l=F.prototype;l.flush=function(){var a=ua;ua="";this.wa(a)};function va(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}
l.Sd=function(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,q(a)));return a};
l.wa=function(a,b){var c=a.lastIndexOf("\n");b?0<=c&&(b=Date.now(),wa||(wa=b),a=((b-wa)/1E3).toFixed(3)+": "+a):(0<=c&&(console.log(ua+a.substr(0,c)),ua="",a=a.substr(c+1)),wa=null);ua+=a;return a.length};function G(a,b,c){a.wa(b+"\n",c)}l.K=function(a){return this.wa(this.v.apply(this,[a].concat(q(la.apply(1,arguments)))))};
l.v=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,g;for(g=0;g<d.length-6;g+=6){c+=d[g];var f=d[g+5];if(void 0===this.Da[f])c+="%"+d[g+1]+d[g+2]+d[g+3]+d[g+4]+f;else{if(e<b.length){var h=b[e];"%"!=f&&e++}else h=b[b.length-1];var k=d[g+1],n=0<=k.indexOf("#"),p=0<=k.indexOf("0"),m=d[g+2];"*"==m?(m=h,h=e<b.length?b[e++]:b[b.length-1]):m=+m||0;var r=d[g+3];r=r?+r.substr(1):-1;var w=d[g+4],x=null,v=0,z=
"";var u=0<="ACDFHGMNSTWY".indexOf(f)&&"object"!=typeof h?this.Sd(h):h;switch(f){case "C":h=n?"#":"";c+=isNaN(u.getTime())?void 0:this.v(this.v("%%%sW, %%%sF %%%sD, %%%sY",h),u);continue;case "D":h=n?u.getUTCDate():u.getDate();f="d";break;case "A":case "G":case "H":h=n?u.getUTCHours():u.getHours();"A"==f?(h=12>h?"am":"pm",f="s"):("G"==f&&(h=h?12<h?h-12:h:12),f="d");break;case "F":case "M":h=n?u.getUTCMonth():u.getMonth();"F"==f?(h=xa[h],f="s"):(h++,f="d");break;case "N":h=n?u.getUTCMinutes():u.getMinutes();
f="d";break;case "S":h=n?u.getUTCSeconds():u.getSeconds();f="d";break;case "T":h=n?"#":"";c+=isNaN(u.getTime())?void 0:this.v(this.v("%%%sY-%%%s02M-%%%s02D %%%s02H:%%%s02N:%%%s02S",h),u);continue;case "W":h=ya[n?u.getUTCDay():u.getDay()];f="s";break;case "Y":h=n?u.getUTCFullYear():u.getFullYear(),0<r&&(h%=Math.pow(10,r),r=-1),f="d"}switch(f){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=r&&(p=!0,m<r&&(m=r),r=-1);case "f":h=+h;u=h+"";0<=r&&(u=h.toFixed(r));u.length<m&&(p?(0>h&&(m--,
u=u.substr(1)),u=("0".repeat(m)+u).slice(-m),0>h&&(u="-"+u)):u=(" ".repeat(m)+u).slice(-m));c+=u;break;case "j":c+=JSON.stringify(h,null,m||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=r&&(h=h.substr(0,r));h.length<m;)h=0<=k.indexOf("-")?h+" ":" "+h;c+=h;break;case "o":v=8,n&&(z="0");case "X":x=za;case "x":u="";v||(v=16);!z&&n&&(z="0x");x||(x=Aa);h=Math.trunc(h);0<=r&&(p=!0,m<r&&(m=r));p&&!m&&("b"==w?m=2:
"h"==w||"w"==w?m=4:"l"==w?m=8:(m=Math.abs(h),m=255>=m?2:65535>=m?4:4294967295>=m?8:9),m+=z.length);m-=z.length;do n=h&v-1,h>>>=16==v?4:3,p||!u||n||h?u=x[n]+u:(z&&(u=z+u,z=""),0<m&&(u=" "+u));while(0<--m||h);c+=z+u;break;case "%":c+="%";break;default:c=this.Da[f]?c+this.Da[f](f,k,m,r,h):c+("(unimplemented sprintf type: %"+f+")")}}}return c+=d[g]};var ua="",wa=null,Aa="0123456789abcdef",za="0123456789ABCDEF",ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),xa="January February March April May June July August September October November December".split(" ");
C.StdIO=F;function H(a){F.call(this);this.V={};this.fa=0;this.I=this;a&&(this.I.fa=0,this.I.ta=[],this.I.la=0,this.I.Pa={},this.I.Oa=!1)}var Ba;y(H,F);l=H.prototype;l.za=function(a,b){var c=this,d=this;switch(a){case Ca.zc:b.onclick=function(){var e=c.sa(Ca.Ta,!0);e&&(e.value="")};break;case Ca.Ta:Da(b),b.addEventListener("keydown",function(e){Ea(d,e,!0)}),b.addEventListener("keypress",function(e){Ea(d,e)})}};function Fa(a,b){var c=Ga.Fb;a.I.Pa[c]||(a.I.Pa[c]=[]);a.I.Pa[c].push(b)}
function Da(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}l.error=function(a,b){b=this.v.apply(this,[a].concat(q(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.v.apply(this,[c].concat(q(b))))G(this,b),a||alert(b)};l.sa=function(a){return this.V[a]};
function Ha(a,b,c){if(a){do{for(var d=0;d<Ia.length;d++){var e=Ia[d];if(c){if(e+=c,b+e in a)return e}else if(e=e?e+b[0].toUpperCase():b[0],e+=b.substr(1),e in a)return e}if(0>b.indexOf("screen"))break;b=b.replace("screen","Screen")}while(1)}return null}function Ja(a,b){return a.m.bindings&&a.m.bindings[b]}function Ka(a){if(a=a.V[La])var b=a.textContent;return b}function Ma(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function I(a,b,c,d){a=a.m[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Na(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Oa(){var a,b=Ba;if(!b){b={};if(window){a||(a=window.location.search.substr(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Ba=b}return b}function Pa(a){if(void 0===J.ib){var b=!1;if(window)try{window.localStorage.setItem(J.Ia,J.Ia),b=window.localStorage.getItem(J.Ia)==J.Ia,window.localStorage.removeItem(J.Ia)}catch(c){G(a,c.message),b=!1}J.ib=b}return!!J.ib}
function Qa(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.fa;return-1==(b|1)||sa(a.I.fa,b)?!0:!1}function Ra(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Sa(a){var b=null;if(Pa(a)){var c;if(window)try{(c=window.localStorage.getItem(a.N))&&(b=JSON.parse(c))}catch(d){G(a,d.message)}}return b}
function Ea(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.I,g=b.target;if(c){a=!1;var f;c=g.value;var h=c.lastIndexOf("\n");d==K.Cb&&g.selectionStart<=h+1&&(a=!0);d==K.Ad?(a=!0,0<e.la&&(f=e.ta[--e.la])):d==K.Gc&&(a=!0,e.la<e.ta.length&&(f=e.ta[++e.la]||""));a&&b.preventDefault();void 0!=f&&(g.value=c.substr(0,h+1)+f)}else d=String.fromCharCode(d),f=g.value,c=f.lastIndexOf("\n"),g.selectionStart<=c&&g.setSelectionRange(f.length,f.length),b.stopPropagation(),"@"==d&&0<e.la&&c+1==f.length&&
(g.value+=e.ta[--e.la],d="\r"),"\r"==d&&(b.preventDefault(),f=g.value+="\n",g.blur(),g.focus(),(b=Ta(a,f.slice(f.lastIndexOf("\n",f.length-2)+1,-1)||""))&&G(a,b.replace(/\n$/,""),!1))}}function Ua(a){if(window){var b=window.onresize;window.onresize="function"!==typeof b?a:function(){b&&b();a()}}}function Va(a){return"true"==a||"on"==a?!0:"false"==a||"off"==a?!1:void 0}
function Wa(a,b){if(void 0!=b){var c=a.I;try{if(b=b.trim())c.la<c.ta.length&&b==c.ta[c.la]?c.la++:(c.ta.push(b),c.la=c.ta.length);var d=b.split(" "),e=d[0],g=a.I.Pa[Ga.Fb];switch(e[0]){case "m":if("?"==e[1]){var f="";Xa.forEach(function(m){f+=m+"\n"});f&&(f="message commands:\n"+f);break}f="";var h=void 0;e=d[d.length-1].toLowerCase();var k=Va(e);void 0!=k&&d.pop();1>=d.length&&(void 0!=k&&(h=k,k=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(L));for(g=1;g<d.length;g++){e=d[g];var n=L[e];if(!n){f+=
"unrecognized message: "+e+"\n";break}void 0!=k&&Ya(a,n,k);if(void 0==h||h==Qa(a,n))f+=a.v("%8s: %b\n",e,Qa(a,n))}Qa(a,B.Fa)&&(f+="all messages will be buffered until buffer is turned off\n");f||(f="no messages\n");break;case "?":f="",Za.forEach(function(m){f+=m+"\n"}),f&&(f="default commands:\n"+f);default:if(d.unshift(b),g)for(a=0;a<g.length;a++){var p=g[a](d);if(void 0!=p){f=f?f+p:p;break}}}}catch(m){f="error: "+m.message+"\n"}}return f}
function Ta(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=Wa(a,b[d])}return c}l.wa=function(a,b){void 0==b&&(b=Qa(this,B.Fa));if(!b){var c=this.sa(Ca.Ta,!0);if(c)return c.value.substr(-a.length)!=a&&(c.value+=a,8192<c.value.length&&(c.value=c.value.substr(c.value.length-4096)),c.scrollTop=c.scrollHeight,Ra("iOS")||c.setSelectionRange(c.value.length,c.value.length)),a.length}return F.prototype.wa.call(this,a,b)};
l.K=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return Qa(this,c)?F.prototype.K.call.apply(F.prototype.K,[this,a].concat(q(b))):0};function $a(a,b){if(Pa(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.N,b)}catch(c){G(a,c.message)}}}function ab(a,b,c){(a=a.V[b])&&a.textContent!=c&&(a.textContent=c)}
function Ya(a,b,c){var d=!1;c?(c=a.I.fa,a.I.fa=(c|b)+(c/E|0|b/E|0)*E):(d=sa(a.I.fa,B.Fa)&&sa(b,B.Fa),c=a.I.fa,a.I.fa=(c&~b)+((c/E|0)&~(b/E|0))*E);d&&a.flush()}
var Ca={zc:"clear",Ta:"print"},Za=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],Xa=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],L={all:B.Ab,buffer:B.Fa},Ga={Fb:"command"},bb={Hb:13,hb:65,Bb:66,Db:67,Ib:68,E:69,Kb:70,Mb:71,Nb:72,Ob:73,Pb:74,Qb:75,Sb:76,Wb:77,Xb:78,Yb:79,Zb:80,Q:81,ac:82,cc:83,ec:84,
fc:85,hc:86,jc:87,kc:88,lc:89,lb:90,a:97,b:98,c:99,d:100,e:101,f:102,rf:103,sf:104,tf:105,uf:106,k:107,vf:108,wf:109,n:110,xf:111,p:112,q:113,r:114,yf:115,t:116,Cf:117,Df:118,w:119,x:120,y:121,z:122},K={Cb:8,td:9,Vc:10,Hb:13,pd:16,Cc:17,wc:18,bf:19,jb:20,de:27,rd:32,ef:33,df:34,ce:35,ye:36,Ub:37,Ad:38,kb:39,ve:39,Gc:40,se:44,ff:44,ze:45,be:46,ue:46,xe:47,ZERO:48,ONE:49,yd:50,ud:51,Rc:52,Qc:53,qd:54,od:55,Hc:56,$c:57,Oc:59,Nc:61,hb:65,Bb:66,Db:67,Ib:68,E:69,Kb:70,Mb:71,Nb:72,Ob:73,Pb:74,Qb:75,Sb:76,
Wb:77,Xb:78,Yb:79,Zb:80,Q:81,ac:82,cc:83,ec:84,fc:85,hc:86,jc:87,kc:88,lc:89,lb:90,Eb:91,te:91,re:92,jf:93,we:93,De:96,Ue:96,qe:96,Ee:97,Se:97,Fe:98,Re:98,Ge:99,Xe:99,He:100,Ve:100,Ie:101,Oe:101,Je:102,Ze:102,Ke:103,Te:103,Le:104,af:104,Me:105,Ye:105,We:106,Ne:107,$e:109,Pe:110,Qe:111,ee:112,ie:113,je:114,ke:115,le:116,me:117,ne:118,oe:119,pe:120,fe:121,ge:122,he:123,ad:144,ld:145,Mc:173,md:186,Ic:187,$d:188,Dc:189,cf:190,lf:191,Yd:192,Ae:219,Zd:220,hf:221,gf:222,Lc:224,Be:901,ic:1E3},cb={},db=(cb[K.Oc]=
K.md,cb[K.Nc]=K.Ic,cb[K.Mc]=K.Dc,cb[K.Lc]=K.Eb,cb),eb={Ub:1,kb:2,Ce:3},M={},fb=(M[K.Cb]="\b",M[K.td]="\t",M[K.Vc]="\n",M[K.Hb]="\r",M[K.rd]=" ",M[K.ZERO]="0",M[K.ONE]="1",M[K.yd]="2",M[K.ud]="3",M[K.Rc]="4",M[K.Qc]="5",M[K.qd]="6",M[K.od]="7",M[K.Hc]="8",M[K.$c]="9",M[K.hb]="A",M[K.Bb]="B",M[K.Db]="C",M[K.Ib]="D",M[K.E]="E",M[K.Kb]="F",M[K.Mb]="G",M[K.Nb]="H",M[K.Ob]="I",M[K.Pb]="J",M[K.Qb]="K",M[K.Sb]="L",M[K.Wb]="M",M[K.Xb]="N",M[K.Yb]="O",M[K.Zb]="P",M[K.Q]="Q",M[K.ac]="R",M[K.cc]="S",M[K.ec]=
"T",M[K.fc]="U",M[K.hc]="V",M[K.jc]="W",M[K.kc]="X",M[K.lc]="Y",M[K.lb]="Z",M[K.Ub]="Left",M[K.kb]="Right",M),Ia=["","moz","ms","webkit"],gb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",
seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},J={ib:void 0,Ia:"PCjs.localStorage"};C.WebIO=H;
function N(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;H.call(this,a==b);this.N=a;this.W=b;O[this.N]||(O[this.N]={});O[this.N][this.W]&&this.K("warning: machine configuration contains multiple '%s' devices\n",this.W);O[this.N][this.W]=this;this.id=this.N==this.W?this.N:this.N+"."+this.W;hb.push(this);this.I=ib(this,this.N);this.ready=!0;jb(this,c,d);this.Qa={};this.Vb=[]}y(N,H);l=N.prototype;l.mb=function(){};l.nb=function(){};
function jb(a,b,c){c=b.overrides||c;if(c.length){var d=Oa();for(h in d)if(0<=c.indexOf(h)){var e=d[h],g=ra(e,10);void 0==g&&("true"==e?g=!0:"false"==e?g=!1:(g=e,e='"'+e+'"'));b[h]=g;G(a,"overriding "+a.W+" property '"+h+"' with "+e)}}a.m=b;c=b.bindings;c=void 0===c?{}:c;if("undefined"!=typeof document){a.m.V||(a.m.V=c);(d=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.W);for(var f in c){e=c[f];if(d)f=e;else if(e.match(/^[0-9]+$/)){var h=+e;a.V[f]=[];do{e=
f+h++;e=document.getElementById(e);if(!e)break;a.V[f].push(e)}while(1);continue}if(h=document.getElementById(e))a.V[f]=h,a.za(f,h)}}b=void 0===b?{}:b;a.version=3;if(a.version){f="";var k;a.N!=a.W&&(k=ib(a,a.N).version)&&k!=a.version&&(f="Machine");f||(k=b.version)&&k>a.version&&(f="Config");f&&(k=a.v("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.nf,a.version,f,k),a.error("%s\n\nClearing your browser's cache may resolve the issue.",k))}}
function kb(a,b){var c;try{var d=O[a.N];if(d)for(c in d){var e=d[c];if(e.W!=e.N&&!b(e))return!1}return!0}catch(g){a.K("error while enumerating device '%s': %s\n",c,g.message)}return!1}l.sa=function(a,b){b=void 0===b?!1:b;if(a){var c=H.prototype.sa.call(this,a,b);if(void 0===c&&b){b=O[this.N];for(var d in b)if(c=b[d].V[a])break;c||(c=null);this.V[a]=c}}return c};
function ib(a,b,c){var d=b,e=a.N,g=e.indexOf(".");0<g&&(e=e.substr(0,g),b=b.substr(g+1));b=(g=O[e])&&g[b]||null;if(!b){for(g=0;g<hb.length;g++)if(hb[g].id===d){b=hb[g];break}if(!b&&(void 0===c||c))throw Error(a.v('no "%s" device',d));}return b}function P(a,b,c){var d=null,e=O[a.N];if(e)for(var g in e)if(e[g].m["class"]==b){if(d){d=null;break}d=e[g]}if(!d&&(void 0===c||c))throw Error(a.v("no %s device",b));return d}function lb(a,b){var c=ib(a,a.N);return c&&c.m&&c.m[b]||a.m[b]}
function mb(a,b){return(a=a.Qa[b])&&a.get()}function nb(a){return a==a.I&&a.ready?kb(a,function(b){return nb(b)}):a.ready}function ob(a,b){b=void 0===b?a.ready:b;a.ready=b;if(nb(a)){for(;b=a.Vb.pop();)b();a!=a.I&&ob(a.I)}}function pb(a,b){if(nb(a))return b(),!0;a.Vb.push(b);return!1}l.rc=function(){};
l.K=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&Qa(this,a)&&(void 0===this.ba&&(this.ba=P(this,"Debugger",!1)),this.ba&&this.ba.rc(a),this.I.fa&B.zb&&(void 0===this.T&&(this.T=P(this,"CPU")),this.T))?(a=b.shift(),H.prototype.K.call(this,"%#06x: %s.%s\n",this.T.sb,this.W,this.v.apply(this,[a].concat(q(b))).trim())):H.prototype.K.call.apply(H.prototype.K,[this,a].concat(q(b)))};function qb(a,b){(a=O[a.N])&&delete a[b]}function rb(a,b,c){(a=a.Qa[b])&&a.set&&a.set(c)}
"undefined"!=typeof window&&(window.PCjs||(window.PCjs={}),window.PCjs.Machines||(window.PCjs.Machines={}),window.PCjs.Components||(window.PCjs.Components=[]));var O="undefined"!=typeof window?window.PCjs.Machines:{},hb="undefined"!=typeof window?window.PCjs.Components:[];B.zb=1;B.xc=2;B.Kc=4;B.Wc=8;B.ed=16;B.yc=32;B.Uc=64;B.nd=128;B.Xc=256;B.Bc=512;B.Yc=1024;B.INT=2048;B.xd=4096;B.Cd=8192;B.Ra=16384;B.kd=32768;B.Fc=65536;B.Pc=131072;B.Va=262144;B.vd=524288;B.Jb=1048576;B.oa=2097152;B.Rb=4194304;
B.Zc=8388608;B.wd=16777216;B.Tc=33554432;B.Wa=67108864;B.Jc=134217728;B.Sc=268435456;B.ae=4294967296;L.addr=B.zb;L.bus=B.xc;L.fault=B.Kc;L.memory=B.Wc;L.ports=B.ed;L.chips=B.yc;L.kbd=B.Uc;L.serial=B.nd;L.misc=B.Xc;L.cpu=B.Bc;L.mmu=B.Yc;L["int"]=B.INT;L.trap=B.xd;L.video=B.Cd;L.monitor=B.Ra;L.screen=B.kd;L.disk=B.Fc;L.file=B.Pc;L.time=B.Va;L.timer=B.vd;L.event=B.Jb;L.input=B.oa;L.key=B.Rb;L.mouse=B.Zc;L.touch=B.wd;L.info=B.Tc;L.warn=B.Wa;L.error=B.Jc;L.halt=B.Sc;C.Device=N;
function sb(a,b,c){N.call(this,a,b,c);this.fa=B.oa;this.Z=this.M=null;this.time=P(this,"Time");this.I=P(this,"Machine");this.ea=I(this,"drag",!1);this.X=I(this,"scroll",!1);this.da=I(this,"hexagonal",!1);this.l=I(this,"releaseDelay",0,void 0);this.o=!1;a=this.m.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],g=b[d],f=a[g];"string"==typeof f?f=[f]:void 0==f.length&&(e=f.grid,f=f.keys,"string"==typeof f&&(f=[f]));this.j[g]={keys:f,
grid:e,state:0}}}this.R=[];this.S=[];this.u=!1;this.i=this.H=null;(a=this.V[tb])&&ub(this,a,this.sa(c.focusBinding,!0),this.m.location);this.ma()}y(sb,N);function vb(a,b){a.M=b}function wb(a,b,c){for(var d=0;d<a.R.length;d++){var e=a.R[d];e.id===b&&e.Za(b,c)}}
function ub(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.Wd=d[0]||0;e.Xd=d[1]||0;e.Ka=d[2]||b.clientWidth;e.Xa=d[3]||b.clientHeight;e.$a=d[4]||1;e.fb=d[5]||1;e.Kd=d[6]||b.naturalWidth||e.Ka;e.Md=d[7]||b.naturalHeight||e.Xa;e.uc=d[8]||0;e.vc=d[9]||0;e.Jd=d[10]||0;e.Ld=d[11]||0;a.h?(e.bb=a.h.length,e.La=a.h[0].length):(e.La=e.$a,e.bb=e.fb,e.$a=e.fb=0);e.oc=e.Ka/(e.La+e.La*e.$a)|0;e.pc=e.Xa/(e.bb+e.bb*e.fb)|0;e.Id=e.oc*e.$a|0;e.qc=e.pc*e.fb|0;e.Na=e.gb=-1;xb(a,b,e);zb(a,b,e);a.time&&
a.l&&(a.Y=Ab(a.time,"timerInputRelease",function(){0>e.Na&&0>e.gb&&Bb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.l&&(a.ga=Ab(a.time,"timerKeyRelease",function(){Cb(a)})),a.s=0,a.L="",a.J=[],d=b,c&&(d=c,a.i||"BUTTON"!=c.nodeName||(d=document,a.i=c,Db(a,b),a.H=b)),Db(a,d),a.i||(a.i=d)}function Eb(a){a.l?Fb(a.time,a.ga,a.l):Cb(a)}
function Db(a,b){function c(e,g,f){var h=document.activeElement;a.K(B.Rb+B.Jb,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,g,Date.now()/1E3%60,void 0!=f?f?"used":"unused":"ignored")}function d(e,g){e=document.activeElement;return a.i&&e!=a.i&&e!=a.H?null:g||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var g=e.which||e.keyCode,f=Gb(a,g,!0,e);c("Down",g,f);f&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var g=e.which||e.charCode,f=Gb(a,
g);c("Press",g,f);f&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var g=e.which||e.keyCode,f=Gb(a,g,!1,e);c("Up",g);f&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function xb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.o){var e=a.u?a.H:a.i;if(e){var g=window.scrollX,f=window.scrollY;e.focus();window.scrollTo(g,f)}d.button||Q(a,b,Hb,d,c)}});b.addEventListener("mousemove",function(d){a.o||Q(a,b,Ib,d,c)});b.addEventListener("mouseup",function(d){a.o||d.button||Q(a,b,Jb,d,c)});b.addEventListener("mouseout",function(d){a.o||(0>c.Na?Q(a,b,Ib,d,c):Q(a,b,Jb,d,c))})}
function zb(a,b,c){b.addEventListener("touchstart",function(d){a.X&&(a.o=!0);Q(a,b,Hb,d,c)});b.addEventListener("touchmove",function(d){Q(a,b,Ib,d,c)});b.addEventListener("touchend",function(d){Q(a,b,Jb,d,c)})}
function Gb(a,b,c,d){if(void 0!=c){var e=db[b]||b;var g=fb[b];var f=Kb[e];d=d&&d.location==eb.kb;f&Lb&&d&&(f>>=1);f&&(f&Mb&&(c=!(a.g&f)),a.g=c?a.g|f:a.g&~f,wb(a,e,c))}else g=String.fromCharCode(b).toUpperCase(),b>=bb.hb&&b<=bb.lb?a.g&(Nb|Ob)||(a.g|=Ob,wb(a,K.jb,!0)):b>=bb.a&&b<=bb.z&&a.g&Ob&&(a.g&=~Ob,wb(a,K.jb,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(f=a.h[e],d=0;d<f.length;d++)if(0<=f[d].split("|").indexOf(g))return a.s?16>a.J.length&&a.J.push(b):(a.s=1,a.L=g,Bb(a,d,e),wb(a,
g,!0),Eb(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(f=b[e],0<=a.j[f].keys.indexOf(g))return wb(a,f,c),a.j[f].state=c?1:0,!0}return!1}function Cb(a){1==a.s?(a.s++,wb(a,a.L,!1),a.L="",Bb(a,-1,-1),Eb(a)):(a.s=0,a.J.length&&Gb(a,a.J.shift()))}sb.prototype.ma=function(){this.g=0;this.U=this.$=-1};
function Q(a,b,c,d,e){var g=-1,f=-1,h=!1,k=-1,n=-1;if(c<Jb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,n=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(k=d.clientX,n=d.clientY);var p=d.target.getBoundingClientRect();k-=p.left;n-=p.top;k=e.Kd/b.offsetWidth*k|0;n=e.Md/b.offsetHeight*n|0;var m=k-e.Wd;var r=n-e.Xd;var w=p=!1;var x=k>=e.uc&&k<e.uc+e.Jd&&n>=e.vc&&n<e.vc+e.Ld;if(0<=m&&m<e.Ka&&0<=r+e.qc||x)if(h||a.X||d.preventDefault(),0<=m&&m<e.Ka&&0<=
r&&r<e.Xa){w=!0;d=e.Ka/e.La|0;var v=e.Xa/e.bb|0,z=m/d|0,u=r/v|0;!a.da||u&1||(m-=d>>1,z=m/d|0,z==e.La-1&&(m=-1));v=u*v+(e.qc>>1);m-=z*d+(e.Id>>1);r-=v;0<=m&&m<e.oc&&0<=r&&r<e.pc&&(g=z,f=u,p=!0)}}m=m||0;r=r||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Hb||c==Jb)for(z=0;z<a.S.length;z++)u=a.S[z],c==Jb?u.Za(u.id,!1):(v=r/(b/u.qf|0)|0,(m/(d/u.pf|0)|0)==u.Ef&&v==u.Ff&&u.Za(u.id,!0));if(!h)if(c==Hb)e.Na=k,e.gb=n,w?(Bb(a,g,f),p&&a.l&&Fb(a.time,a.Y,a.l,!0)):x&&a.I.ia();else if(c==Ib)0<=e.Na&&0<=e.gb&&a.ea?Bb(a,
g,f):a.M&&a.M(g,f);else if(c==Jb){if(c=a.l)c=a.time,g=a.Y,c=c.g&&0<g&&g<=c.h.length?0<=c.h[g-1].ha:!1;c||Bb(a,-1,-1);e.Na=e.gb=-1}else G(a,"unrecognized action: "+c)}function Pb(a){var b=a.u?a.H:a.i;b&&nb(a.I)&&(a.K(B.oa,'setFocus("%s")\n',b.id||b.nodeName),b.focus(),b.scrollIntoView())}function Bb(a,b,c){if(b!=a.U||c!=a.$)a.U=b,a.$=c,a.Z&&a.Z(b,c)}var Hb=1,Ib=2,Jb=3,tb="surface",Nb=3,Lb=170,Ob=512,Mb=3584,R={},Kb=(R[K.pd]=2,R[K.Cc]=8,R[K.wc]=32,R[K.Eb]=128,R[K.jb]=Ob,R[K.ad]=1024,R[K.ld]=2048,R);
C.Input=sb;
function Qb(a,b,c){N.call(this,a,b,c,["color","backgroundColor"]);a=this.V[Rb];if(!a)throw Error("LED "+this.m.V[Rb]+" binding for '"+Rb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Ca=Ja(this,Rb)+".canvas";b.setAttribute("id",this.Ca);this.type=Ma(I(this,"type",Sb,Tb),Ub,Vb);this.j=Wb[this.type][0];this.u=Wb[this.type][1];this.width=I(this,"width",this.j,void 0);
this.height=I(this,"height",this.u,void 0);this.l=I(this,"cols",1,void 0);this.M=this.l+I(this,"colsExtra",0,void 0);this.Y=I(this,"rows",1,void 0);this.R=this.Y+I(this,"rowsExtra",0,void 0);this.ea=this.width*this.l;this.Z=this.height*this.Y;this.s=Xb("black",0);this.i=Yb(this.m.color)||this.s;this.ra=Xb(this.i,1,.25);this.pa=Xb(this.i,1,2);this.o=Yb(this.m.backgroundColor);this.xa=I(this,"fixed",!1);this.xa||(b.style.width="100%",b.style.height="auto");this.na=I(this,"hexagonal",!1);this.ya=I(this,
"highlight",!0);this.X=I(this,"persistent",this.type<Vb);b.setAttribute("width",this.ea.toString());b.setAttribute("height",this.Z.toString());b.style.backgroundColor=this.s;a.appendChild(b);this.ga=b.getContext("2d");if(this.H=document.createElement("canvas"))this.H.width=this.da=this.j*this.l,this.H.height=this.J=this.u*this.Y,this.g=this.H.getContext("2d");this.Sa=(this.R+1)*this.M*4;this.h=Array(this.Sa);this.Ua=this.l<this.M?4*(this.M-this.l):0;this.S=this.U=!1;this.L=this.$=0;this.ja=-1;var d=
this;this.time=P(this,"Time");Zb(this.time,function(e){$b(d,!1,e)});ac(d)}y(Qb,N);function ac(a){for(var b=a.h,c=0;c<b.length;c+=4){var d=a,e=b,g=c;e[g]=d.type<Vb?bc:" ";e[g+1]=d.i==d.s?null:d.i;e[g+2]=0;e[g+3]=cc}a.S=a.U=!0;$b(a,!0)}function dc(a){a.o?(a.g.fillStyle=a.o,a.g.fillRect(0,0,a.da,a.J)):a.g.clearRect(0,0,a.da,a.J)}
function $b(a,b,c){b=void 0===b?!1:b;c=void 0===c?0:c;if(a.S||b){if(a.type<Vb){var d=0;if(!a.X||b)dc(a);else if(a.L){d=a.l-a.L;var e=a.j*d;a.g.drawImage(a.H,a.j*a.L,0,e,a.J,0,0,e,a.J)}for(var g=e=0;g<a.R;g++){for(var f=0;f<a.l;f++){var h=a.h[e],k=a.h[e+1]||a.s,n=a.ya&&e==a.ja;if(a.h[e+3]&cc||n||b){if(f>=d)a:{var p=a,m=h;h=k;var r=f;k=g;var w=n;r=void 0===r?0:r;k=void 0===k?0:k;w=void 0===w?!1:w;var x=0;if(p.na&&!(k&1)&&(x=p.j>>1,r==p.l-1))break a;if(h&&h!=p.i){w=w?Xb(h,1,2):h;var v=Xb(h,1,.25)}else w=
w?p.pa:p.i,v=p.ra;h=!1;m=m?w:v;w==p.s&&(m=p.o,h=!0);w=r*p.j+x;v=k*p.u;p.X&&(r=r*p.j+x,k*=p.u,p.o?(p.g.fillStyle=p.o,p.g.fillRect(r,k,p.j,p.u)):p.g.clearRect(r,k,p.j,p.u));p.g.fillStyle=m;k=ec[p.type];3==k.length?(p.g.beginPath(),p.g.arc(w+k[0],v+k[1],k[2],0,2*Math.PI),h?(p.g.globalCompositeOperation="destination-out",p.g.fill(),p.g.globalCompositeOperation="source-over"):p.g.fill()):p.g.fillRect(w+k[0],v+k[1],k[2],k[3])}a.h[e+3]=n?a.h[e+3]|cc:a.h[e+3]&~cc}e+=4}e+=a.Ua}a.L=0}else{b="";for(d=0;d<a.h.length;d+=
4)b+=a.h[d]||" ",a.h[d+3]&fc&&(b+=".");dc(a);for(g=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;f=a;n=e;p=g;n=void 0===n?0:n;p=void 0===p?0:p;if(k=gc[k])for(h=0;h<k.length;h++)if(r=f,x=hc[k[h]]){m=(void 0===n?0:n)*r.j;w=(void 0===p?0:p)*r.u;r.g.fillStyle=r.i;r.g.beginPath();if(3==x.length)r.g.arc(m+x[0],w+x[1],x[2],0,2*Math.PI);else for(v=0;v<x.length;v+=2)v?r.g.lineTo(m+x[v],w+x[v+1]):r.g.moveTo(m+x[v],w+x[v+1]);r.g.closePath();r.g.fill()}if(++e==a.l&&(e=0,++g==a.R))break}}a.ga.globalCompositeOperation=
a.o&&a.i!=a.s?"source-over":"copy";a.ga.drawImage(a.H,0,0,a.da,a.J,0,0,a.ea,a.Z);a.S=!1;a.ja=-1}else a.X||a.U||(!c||!a.$||c-a.$>=(1E3/60|0))&&ac(a);a.U=!1;c&&(a.$=c)}function Yb(a){return(a=a||void 0)&&gb[a]||a}
function Xb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=gb[a]||a;var e=16;var g=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);g||(e=10,g=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(g){var f;for(f=1;f<g.length;f++)d[f-1]=Number.parseInt(g[f],e);d.length=f-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)g=Math.round(d[e]*c),g=0>g?0:255<g?255:g,a+=g+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Qb.prototype.ua=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.i&&c==this.o&&a&&a.length==this.h.length){this.h=a;for(b=0;b<=this.h.length-4;b+=4)this.h[b+1]==this.s&&(this.h[b+1]=null);$b(this,!0);return!0}return!1};Qb.prototype.va=function(a){this.h&&(a.push(this.i),a.push(this.o),a.push(this.h))};
var Ub=0,Sb=1,Vb=3,Tb={small:Ub,round:Sb,square:2,digit:Vb},Rb="container",bc=0,fc=1,cc=128,ic={},ec=(ic[Ub]=[4,4,4],ic[Sb]=[16,16,14],ic[2]=[2,2,28,28],ic),Wb=[[8,8],[32,32],[32,32],[96,128]],hc={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},gc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C",
"D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};C.LED=Qb;
function S(a,b,c){N.call(this,a,b,c);var d=this;this.da=this.m.touchType;this.Z=this.m.diagnostics;this.u=this.m.monitorWidth||640;this.o=this.m.monitorHeight||480;this.i=this.V[T.Ra];if(!this.i)throw Error("unable to find binding: "+T.Ra);this.g=this.sa(T.Ac)||this.i;b=this.V[T.dc];if(!b){b=document.createElement("canvas");if(a=Ja(this,T.dc))this.V[a]=b,b.setAttribute("id",a);b.setAttribute("class","pcjs-surface");b.setAttribute("width",this.m.monitorWidth);b.setAttribute("height",this.m.monitorHeight);
b.style.backgroundColor=this.m.monitorColor||"black";this.i.appendChild(b)}this.j=b;this.s=a=b.getContext("2d");Ra("MSIE")&&(this.i.onresize=function(f,h,k,n){return function(){h.style.height=(f.clientWidth*n/k|0)+"px"}}(this.i,b,this.m.monitorWidth,this.m.monitorHeight),this.i.onresize());(c=+(this.m.aspect||Oa().aspect))&&.3<=c&&3.33>=c&&(Ua(function(f,h,k){return function(){h.style.height=(f.clientWidth/k|0)+"px"}}(this.i,b,c)),window.onresize());this.J=this.H=this.I.Oa=!1;if(c=this.V[T.Lb])if(b=
Ha(this.g,"requestFullscreen")){this.g.Ya=this.g[b];this.J=!0;this.H=document.fullscreenEnabled||Ra("Edge/");if(b=Ha(document,"on","fullscreenchange")){var e=Ha(document,"fullscreenElement");document.addEventListener(b,function(){jc(d,null!=document[e])},!1)}(b=Ha(document,"on","fullscreenerror"))&&document.addEventListener(b,function(){jc(d)},!1)}else this.K("Full-screen API not available\n"),c.parentNode.removeChild(c);if(this.da||this.Z||this.J&&!Ra("iOS")){var g=document.createElement("textarea");
if(b=Ja(this,T.bd))this.V[b]=g,g.setAttribute("id",b);g.setAttribute("class","pcjs-overlay");Ra("iOS")&&(Da(g),g.style.fontSize="16px");this.i.appendChild(g)}(this.l=P(this,"Input",!1))&&ub(this.l,g||this.i,this.sa(this.m.focusBinding,!0));Oa();if(this.h=this.m.monitorRotate)this.h=this.h%360,0<this.h&&(this.h-=360),-90!=this.h?(this.K("unsupported monitor rotation: %d\n",this.h),this.h=0):(a.translate(0,this.o),a.rotate(this.h*Math.PI/180),a.scale(this.o/this.u,this.u/this.o))}y(S,N);
S.prototype.za=function(a,b){var c=this;switch(a){case T.Lb:b.onclick=function(){c.I.Oa=1>=window.outerHeight-window.innerHeight;c.I.Oa||c.Ya()}}N.prototype.za.call(this,a,b)};function kc(a){a.s&&(a.s.fillStyle="black",a.s.fillRect(0,0,a.j.width,a.j.height))}
S.prototype.Ya=function(){var a=!1;if(this.g&&this.g.Ya){a="100%";if(screen&&screen.width&&screen.height){var b=screen.width/screen.height,c=this.u/this.o;b>c&&(a=Math.round(c/b*100)+"%")}this.H?(this.j.style.width=a,this.j.style.height="auto",this.j.style.display="block",this.j.style.margin="auto"):(this.g.style.width=a,this.g.style.height="auto");this.L=this.g.style.backgroundColor;this.g.style.backgroundColor="black";this.g.Ya();this.l&&(a=this.l,a.u=!0,Pb(a));a=!0}return a};
function jc(a,b){a.I.Oa=!0;b||(a.g&&(a.H?a.j.style.width=a.j.style.height="":a.g.style.width=a.g.style.height="",a.L&&(a.g.style.backgroundColor=a.L)),a.I.Oa=!1);a.l&&!b&&(a=a.l,a.u=!1,Pb(a))}S.prototype.ia=function(a){a?this.$=!1:kc(this)};S.prototype.ma=function(){kc(this)};var T={Ac:"container",dc:"surface",Ra:"monitor",bd:"overlay",Lb:"fullScreen"};C.Monitor=S;
function lc(a,b,c){N.call(this,a,b,c);this.ra=I(this,"cyclesMinimum",1E5,void 0);this.Sa=I(this,"cyclesMaximum",1E9,void 0);this.ea=Ma(I(this,"cyclesPerSecond",1E6,void 0),this.ra,this.Sa);this.Z=1E3/60;this.Ua=I(this,"updatesPerSecond",2,void 0)||2;this.sd=1E3/this.Ua;this.Ca=0;this.zd=I(this,"timeLock",!0);this.pa=this.M=0;this.na=this.l=1;this.ya=this.s=this.ea/1E4/100;this.ga=[];this.J=[];this.h=[];this.U=[];this.xa=this.g=this.X=this.H=!1;this.L=this.j=0;a=Ha(window,"requestAnimationFrame");
if(!a){a="setTimeout";var d=this.Z}this.$b=window[a].bind(window,this.Td.bind(this),d);this.jd=window[Ha(window,"cancelAnimationFrame")||"clearTimeout"].bind(window);this.Y=this.$=this.o=this.i=this.da=0;mc(this)||nc(this,this.na)}y(lc,N);function Zb(a,b){a.ga.push(b)}l=lc.prototype;
l.za=function(a,b){var c=this;switch(a){case oc:b.onclick=function(){pc(c)&&(c.g?qc(c):c.start())};break;case rc:b.onclick=function(){nc(c,c.l<<1);sc(c,tc(c.s))};break;case uc:b.onclick=function(){vc(c)};break;case wc:b.addEventListener("mousedown",function(){c.H=!0}),b.addEventListener("mouseup",function(){mc(c);c.H=!1}),b.addEventListener("mousemove",function(){c.H&&mc(c)}),b.addEventListener("change",function(){c.H=!0;mc(c);c.H=!1})}N.prototype.za.call(this,a,b)};
function Ab(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,Dd:c,ab:d,ha:-1});0<=d&&Fb(a,e,d);return e}
function xc(a,b,c,d){var e=0,g=a.s,f=1E6*g;b&&c&&(g=b/(10*c)/100,a.K(B.Va,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,g),d>a.Z&&(1<a.l&&(a.l>>=1,a.K(B.Wa,"warning: frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.Z,a.l)),e=d));a.M=g;a.pa=g/a.ya;b=a.pa/a.l;a.da=f/b/60+1E-8;a.K(B.Va,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.da,f,b,60);return e}
function yc(a,b){a.$=a.o=b;if(!a.J.length)return a.o=0,a.$;for(var c=0;0<a.o;){if(c<a.J.length){var d=a.J[c++];b=d.Ud.call(d,b)||1}else c=b=0;a.o-=b}return a.$-a.o}function Ac(a,b){b=void 0===b?a.$-a.o:b;if(!a.g){if(a.i)for(var c=0;c<a.J.length;c++){var d=a.J[c];d.Vd.call(d)}a.i=b}a.i-=b;1>a.i&&(a.X=!0);a.Y+=b;a.$=a.o=0;a.g||(a.Y=0);return b}
function Bc(a,b){b=void 0===b?0:b;if(b){var c=b;a.i+=b}else for(c=a.i,1>c&&(c=a.i+=a.da),0>c&&(a.K(B.Wa,"warning: cycle count dropped below zero: %f\n",c),c=a.i=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.ha)&&c>d.ha&&(c=d.ha)}return c}function tc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Cc(a){a.K(B.Va,"getSpeedCurrent(%5.3fhz)\n",1E6*a.M);return a.g&&a.M?tc(a.M):"Stopped"}
function pc(a){return a.xa?!0:(G(a,"not powered"),!1)}function Dc(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.ha||(d.ha-=b,0>=d.ha&&(d.ha=-1,d.Dd(),0<=d.ab&&Fb(a,c,d.ab)))}}l.ia=function(a){this.xa=a;void 0===this.ba&&(this.ba=P(this,"Debugger",!1))&&this.ba.mb(this,"time","dump time state",this.Qd)};function vc(a,b){pc(a)&&(a.g?G(a,"already running"):a.j?qc(a):Ec(a,b))}
l.Td=function(a){a=void 0===a?Date.now():a;this.L=0;if(this.g){var b=Date.now();if(this.R){var c=b-this.S-this.Z;c>this.Z&&(this.u+=c,this.K(B.Wa,"warning: browser throttling detected, compensating by %5.3fms\n",c))}this.S=b;this.u||(this.u=b);this.ja=0;try{this.X=!1;do Dc(this,Ac(this,yc(this,Bc(this))));while(this.g&&!this.X)}catch(d){G(this,d.message),qc(this)}this.R=Date.now();this.ja&&(this.u+=this.ja,this.S+=this.ja);this.S+=xc(this,this.Y,this.R-this.u,this.R-this.S);this.R-this.Ca>=this.sd&&
this.update();for(b=0;b<this.ga.length;b++)this.ga[b](a);this.L=this.$b()}};function nc(a,b){if(void 0!==b){if(1>b||!a.H&&0<a.M&&a.M<.9*a.s)b=a.na;a.l=b;b=a.ya*a.l;a.s!=b&&(a.s=b,sc(a,tc(a.s)))}a.u=a.R=0;a.i=a.Y=0;xc(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.ab&&Fb(a,b,c.ab,!0)}}function mc(a){var b=a.V[wc];return b?(nc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Sa-a.ra)+a.ra)/a.ea|0),!0):!1}
function Fb(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.ha)&&(c=Math.ceil(a.ea*(a.zd?a.na:a.pa)/1E3*(void 0===c?1E3:c)),a.g&&(c+=Ac(a)),b.ha=c)}l.start=function(){if(this.g||this.j)return!1;this.g=!0;this.u=this.R=0;this.update(!0);this.L=this.$b();return!0};function Ec(a,b){b=void 0===b?1:b;a.g||(b&&!a.j&&(a.j=b),a.j&&(a.j--,Dc(a,Ac(a,yc(a,Bc(a,1)))),a.update(!1),a.j&&setTimeout(function(){Ec(a,0)},0)))}
function qc(a){return a.g?(a.g=!1,Ac(a),a.L&&(a.jd(a.L),a.L=0),a.update(!0),!0):a.j?(a.j=0,a.update(!0),!0):!1}l.update=function(a){a&&G(this,this.g?"started with "+tc(this.s)+" target":"stopped");ab(this,oc,this.g?"Halt":"Run");ab(this,uc,this.j?"Stop":"Step");this.H||sc(this,Cc(this));for(var b=0;b<this.U.length;b++){var c=this.U[b];c.sc.call(c,void 0!=a)}this.Ca=Date.now();this.X=!0};function sc(a,b){ab(a,Fc,b);ab(a,rc,b)}
l.Qd=function(){var a=this.v("nCyclesPerSecond: %f\n",this.ea);a+=this.v("nUpdatesPerSecond: %f\n",this.Ua);a+=this.v("nTargetMultiplier: %f\n",this.l);return a+=this.v("nCyclesDepositPerFrame: %f\n",this.da)};var oc="run",rc="setSpeed",Fc="speed",uc="step",wc="throttle";C.Time=lc;
function Gc(a,b,c){N.call(this,a,b,c);this.type="static"==this.m.type?Hc:Ic;this.aa=this.m.addrWidth||16;this.j=Math.pow(2,this.aa);this.s=this.j-1|0;this.blockSize=this.m.blockSize||(16<this.aa?4096:1024);this.blockSize>this.j&&(this.blockSize=this.j);this.u=this.j/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.l=(1<<this.h)-1;this.i=this.m.dataWidth||8;this.g=Array(this.u);this.o=0;a=new U(a,b+"[NONE]",{size:this.blockSize,bus:this.W});for(b=0;b<this.j;b+=this.blockSize)Jc(this,b,this.blockSize,
V.NONE,a);Kc(this,this.type)}y(Gc,N);function Jc(a,b,c,d,e){for(var g=b>>>a.h;0<c&&g<a.g.length;){var f=g*a.blockSize,h=a.blockSize-(b-f);h>c&&(h=c);var k=a.g[g];if(b!=f||h!=a.blockSize||k&&k.type!=V.NONE)break;k=a.W+"["+D(a,b,16,a.aa)+"]";b=e?e.size==a.blockSize?e:new U(a.N,k,{type:d,Aa:b,size:h,bus:a.W}):new U(a.N,k,{type:d,Aa:b,size:h,bus:a.W});a.g[g]=b;b=f+a.blockSize;c-=h;g++}}function Lc(a,b){for(var c=V.hd,d=0,e=0;e<a.g.length;e++){var g=a.g[e];g&&g.type&c&&(b(g),d++)}return d}l=Gc.prototype;
l.ia=function(){void 0===this.ba&&(this.ba=P(this,"Debugger",!1))};l.ma=function(){};l.qb=function(a){return a&&this.ua(a)?!0:!1};l.Ma=function(a){this.va(a)};l.ua=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==Ic||c.type&V.Ha)&&c.ua){var d=a.shift();if(!c.ua(d))return!1}}return!0};l.va=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==Ic||c.type&V.Ha)&&c.va){var d=[];c.va(d);a.push(d)}}};l.rb=function(a){return this.g[a>>>this.h].rb(a&this.l)};
l.xb=function(a,b){this.g[a>>>this.h].xb(a&this.l,b)};l.Ea=function(a,b){this.g[a>>>this.h].qa(a&this.l,b)};function Kc(a,b){var c=a.o;a.o+=b;c&&a.o||(a.qa=a.Ea)}l.cb=function(a,b){return this.g[a>>>this.h].cb(b)?(Kc(this,1),!0):!1};l.ub=function(a,b){return this.g[a>>>this.h].ub(b)?(Kc(this,1),!0):!1};l.eb=function(a,b){return this.g[a>>>this.h].eb(b)?(Kc(this,-1),!0):!1};l.wb=function(a,b){return this.g[a>>>this.h].wb(b)?(Kc(this,-1),!0):!1};var Hc=0,Ic=1;C.Bus=Gc;
function U(a,b,c){N.call(this,a,b,c);this.Aa=this.m.addr;this.size=this.m.size;this.type=this.m.type||V.NONE;this.h=(a=this.m.bus)?ib(this,a):P(this,a="Bus");if(!this.h)throw Error(this.v("unable to find bus '%s'",a));this.R=this.h.i;this.o=this.M=!1;this.values=this.l=null;a=this.Ea;this.h.type==Hc&&(a=this.yb,8==this.R&&!1!==lb(this,"ArrayBuffer")&&(this.M=!0));switch(this.type){case V.NONE:this.qa=this.tc;break;case V.bc:this.qa=this.tc;break;case V.Ha:this.qa=a}this.s=this.i=0;this.j=this.J=this.u=
null;Mc(this,this.m.values);Nc(this)}y(U,N);function Mc(a,b){"string"==typeof b?(ob(a,!1),Na(b,function(c,d,e,g){if(4==e)if(!g&&d){try{var f=JSON.parse(d);Mc(a,f.values)}catch(h){a.K("error (%s) parsing resource: %s\n",h.message,c)}ob(a,!0)}else a.K("error (%d) loading resource: %s\n",g,c)})):a.m.values=b}
function Nc(a,b){if(a.type>V.NONE&&(a.M?(a.l=new ArrayBuffer(a.size),new DataView(a.l,0,a.size),a.values=new Uint8Array(a.l,0,a.size),new Uint16Array(a.l,0,a.size>>1),new Int32Array(a.l,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}l=U.prototype;
l.ma=function(){if(this.m.values)a:{var a=this.h,b=this.Aa,c=this.size,d=this.m.values,e=0,g=b&a.l;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var f=a.g[b++];if(!f)break a;for(;0<c&&g<f.size;)f.Ea(g++,d[e++]),c--;g=0}}else this.type&V.Ha&&this.values&&this.values.fill(0)};l.rb=function(a){return this.values?this.values[a]:0};l.tc=function(){};l.xb=function(a,b){this.values&&(this.values[a]=b)};l.Ea=function(a,b){this.values[a]=b};
l.yb=function(a,b){this.values[a]=b;this.o=!0;this.i?this.j=this.Ea:this.qa=this.Ea};l.cb=function(a){return this.s?this.J==a?(this.s++,!0):!1:(this.s++,this.J=a,!0)};l.ub=function(a){if(!this.i){var b=this;this.i++;this.u=a;this.j=this.qa;this.qa=function(c,d){b.u(b.Aa,c,d);b.j(c,d)};return!0}return this.u==a?(this.i++,!0):!1};l.eb=function(a){return this.s&&this.J==a?(--this.s||(this.J=null),!0):!1};l.wb=function(a){return this.i&&this.u==a?(--this.i||(this.qa=this.j,this.j=this.u=null),!0):!1};
l.ua=function(a){if(a){var b=a.shift();if(this.W==b){this.o=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],g=a[d++];e--;)c[b++]=g;a=c}Nc(this,a)}return!0}}return!1};
l.va=function(a){a.push(this.W);a.push(this.o);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var g=b[c],f=c+1;f<b.length&&b[f]===g;)f++;e[d++]=f-c;e[d++]=g;c=f}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var V={NONE:1,bc:2,Ha:4,hd:14,mf:12};C.Memory=U;function Oc(a,b,c){c.type=V.NONE;U.call(this,a,b,c);Jc(this.h,this.m.addr,this.m.size,V.Ha);pb(this,this.ma.bind(this))}y(Oc,U);C.RAM=Oc;
function Pc(a,b,c){c.type=V.bc;U.call(this,a,b,c);Jc(this.h,this.m.addr,this.m.size,this.m.type,this);pb(this,this.ma.bind(this));this.T=this.ba=void 0;if(C.LED&&this.V[Qc]){var d=this;this.H=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.L=this.values.length/this.H|0;this.g=new Qb(a,b+"LEDs",{"class":"LED",bindings:{container:Ja(this,Qc)},type:Sb,cols:this.H,rows:this.L,color:I(this,"colorROM","green"),backgroundColor:I(this,"backgroundColorROM","black"),persistent:!0}),ac(this.g);this.S=
new sb(a,b+"Input",{"class":"Input",location:[0,0,this.g.ea,this.g.Z,this.H,this.L],bindings:{surface:Ja(this,Qc)}});this.U=Ka(this)||"";vb(this.S,function(e,g){if(d.T){var f=d.U;0<=e&&0<=g&&(e=g*d.H+e,f=d.T.Bf(d.Aa+e,d.values[e]));ab(d,La,f)}})}}y(Pc,U);
Pc.prototype.ua=function(a){var b=!0,c=a.shift();if(c&&this.g){var d=c.length;this.g.h.length==d?(this.g.h=c,$b(this.g,!0)):(this.K("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.K("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};Pc.prototype.ia=function(){void 0===this.T&&(this.T=P(this,"CPU"));void 0===this.ba&&(this.ba=P(this,"Debugger",!1))&&this.ba.nb&&this.ba.nb(this.m.symbols)};
Pc.prototype.va=function(a){this.g&&(a.push(this.g.h),a.push(this.values))};var Qc="array",La="cellDesc";C.ROM=Pc;function Rc(a,b,c){c["class"]="CPU";N.call(this,a,b,c);this.ba=void 0;this.i=this.sb=0;this.time=P(this,"Time");this.time.J.push(this);this.time.U.push(this);this.h=this.g=0}y(Rc,N);Rc.prototype.abort=function(a){this.i=this.sb;G(this,a.message);qc(this.time)};function Sc(a,b){a.ba=b;return a.Qa}Rc.prototype.Ud=function(a){this.h=this.g=void 0===a?0:a;return this.h-this.g};
Rc.prototype.Vd=function(){this.h-=this.g;this.g=0};
function Tc(a,b,c){c["class"]="Debugger";N.call(this,a,b,c);var d=this;this.ca=this.m.defaultRadix||16;this.Z=["(",")"];ta(this,"a",function(g,f,h,k,n){return D(d,n.O,d.ca,h)});ta(this,"n",function(g,f,h,k,n){return D(d,n,d.ca,h,0>f.indexOf("#")?"":void 0)});this.J=0;this.ja=B.NONE;this.M={};this.na=[];this.pa=[];this.T=P(this,"CPU");this.Qa=Sc(this.T,this);this.ra=P(this,"Input",!1);if(a=this.T.m.busMemory||this.m.busMemory){this.g=ib(this,a);if(a=this.T.m.busIO||this.m.busIO)this.j=ib(this,a,!1);
this.j||(this.j=this.g)}else this.g=this.j=P(this,"Bus");this.L=this.g.aa;this.Ca=Math.pow(2,this.L)-1|0;this.u=this.ea=0;this.s=[];for(var e in W)this.s[W[e]]=[];this.o=[];this.o[W.ka]=this.g;this.o[W.Ja]=this.g;this.o[W.oa]=this.j;this.o[W.Ga]=this.j;this.l=[];this.l[W.ka]=this.Gd.bind(this);this.l[W.Ja]=this.Hd.bind(this);this.l[W.oa]=this.Ed.bind(this);this.l[W.Ga]=this.Fd.bind(this);this.i=[];this.R=void 0;this.X=null;this.$=0;this.time=P(this,"Time");this.time.U.push(this);this.Y=0;this.H=[];
this.U="";this.mb(this,"state","dump machine state",this.Pd);this.da=Uc();this.xa=Uc();this.ga=!1;this.S=0;this.h=[];Fa(this,this.Rd.bind(this));(e=lb(this,"commands"))&&Ta(this,e)}y(Tc,N);l=Tc.prototype;l.mb=function(a,b,c,d){this.H.push({Od:a,name:b,Nd:c,Za:d})};function Vc(a,b,c){for(var d,e=0;e<a.H.length;e++){var g=a.H[e];if(g.name==b){d=g.Za.call(g.Od,c);break}}return d}
l.nb=function(a){if(a&&a.length)for(var b=0;b<a.length-2;b+=3){var c=Wc(this,a[b]);if(c){var d=Xc[a[b+1]];if(d){c={Ba:c,type:d,name:a[b+2]};d=this.na;var e=c,g=Yc(d,e,this.mc);0>g&&d.splice(-(g+1),0,e);d=this.pa;e=Yc(d,c,this.nc);0>e&&d.splice(-(e+1),0,c)}}}};function Yc(a,b,c){var d=0,e=a.length,g=0;for(void 0===c&&(c=function(k,n){return k>n?1:k<n?-1:0});d<e;){var f=d+e>>1,h=void 0;h=c(b,a[f]);0<h?d=f+1:(e=f,g=!h)}return g?d:~d}l.mc=function(a,b){return a.name>b.name?1:a.name<b.name?-1:0};
l.nc=function(a,b){return a.Ba.O>b.Ba.O?1:a.Ba.O<b.Ba.O?-1:0};function Zc(a,b,c){b=Yc(a.pa,{Ba:b,type:0,name:void 0},a.nc);if(0<=b&&(a=a.pa[b],!c||a.type==c))var d=a.name;return d}function $c(a,b,c,d){d=void 0===d?a.g:d;b.O=b.O+c&d.s}function Uc(a){a=void 0===a?0:a;var b=ad.dd;return"number"==typeof a?{O:a,tb:-1,type:b}:{O:a.O,tb:a.tb,type:a.type}}
function Wc(a,b,c){if(b){var d=Uc();var e=0,g=b.charAt(e);switch(g){case "&":e++;break;case "#":e++;d.type=ad.fd;break;case "%":e++,g=b.charAt(e),"%"==g?e++:d.type=ad.ic}g=b.indexOf(":",e);if(0<=g){var f=bd(a,b.substring(e,g),c);void 0==f?d=null:(d.tb=f,e=g+1)}d&&(b=bd(a,b.substring(e),c),void 0==b?d=null:d.O=b&a.Ca)}return d}function cd(a,b,c,d){d=void 0===d?a.g:d;a.u++;var e=d.rb(b.O);c&&$c(a,b,c,d);a.u--;return e}
function dd(a,b,c){if(32>=a.L)return b&c;b=X(a,b,0,!0);c=X(a,c,0,!0);return((b/E|0)&(c/E|0))*E+((b&c)>>>0)}function ed(a,b,c){if(32>=a.L)return b^c;b=X(a,b,0,!0);c=X(a,c,0,!0);return((b/E|0)^(c/E|0))*E+((b^c)>>>0)}
function fd(a,b,c,d){for(d=void 0===d?-1:d;d--&&c.length;){var e=c.pop();if(2>b.length)return!1;var g=b.pop();var f=b.pop();switch(e){case "*":f*=g;break;case "/":if(!g)return!1;f=Math.trunc(f/g);break;case "^/":if(!g)return!1;f%=g;break;case "+":f+=g;break;case "-":f-=g;break;case "<<":f<<=g;break;case ">>":f>>=g;break;case ">>>":f>>>=g;break;case "<":f=f<g?1:0;break;case "<=":f=f<=g?1:0;break;case ">":f=f>g?1:0;break;case ">=":f=f>=g?1:0;break;case "==":f=f==g?1:0;break;case "!=":f=f!=g?1:0;break;
case "&":f=dd(a,f,g);break;case "!":case "|":e=f;32>=a.L?f=e|g:(e=X(a,e,0,!0),g=X(a,g,0,!0),f=(e/E|0|g/E|0)*E+((e|g)>>>0));break;case "^!":f=ed(a,f,g);break;case "&&":f=f&&g?1:0;break;case "||":f=f||g?1:0;break;case ",,":f=X(a,f,18,!0)*Math.pow(2,18)+X(a,g,18,!0);break;case "_":case "^_":"^_"==e&&(g=35-(g&255));g&&(f=X(a,f,0,!0),f=0<g?f*Math.pow(2,g):Math.trunc(f/Math.pow(2,-g)));break;default:return!1}b.push(X(a,f))}return!0}
function gd(a,b,c,d,e,g){var f,h=!1,k=0,n=[],p=[],m=a.ca;for(a.ca=e;c<d;){var r=b[c++].trim();var w=c<d?b[c++]:"";if(r){var x=void 0;var v=a;var z=r,u=g;k=void 0===k?0:k;if(void 0!=z){x=mb(v,z.toUpperCase());if(void 0==x){x=void 0;var yb=v,zc=Yc(yb.na,{Ba:null,type:0,name:z},yb.mc);0<=zc&&(x=yb.na[zc].Ba.O);if(void 0==x)if(x=z,v.M[x]?x=v.M[x].value:(x=x.substr(0,6),x=v.M[x]&&v.M[x].value),void 0==x)x=ra(z,1<z.length||10<v.ca?v.ca:10);else if(z=v.M[z]&&v.M[z].zf)u?u.push(z):(u=bd(v,z,u),void 0!==u?
x+=u:x=void 0)}void 0!=x&&(x=X(v,hd(v,x,k)))}v=x}else if("{"==w){r=1;for(v=c;c<d;)if(c++,w=c<b.length?b[c++]:"","{"==w)r++;else if("}"==w&&!--r)break;v=gd(a,b,v,c-1,a.ca,g);null!=v&&k&&(v=hd(a,v,k));r=c<d?b[c++].trim():"";w=c<d?b[c++]:""}else{if(" "==w)continue;if("^B"==w){a.ca=2;continue}if("^O"==w){a.ca=8;continue}if("^D"==w){a.ca=10;continue}if(!(k&-1073741824)){if("+"==w)continue;if("-"==w){k=k<<2|1;continue}if("~"==w||"^-"==w){k=k<<2|2;continue}if("^L"==w){k=k<<2|3;continue}}h=!0;break}if(void 0===
v)if(g)g.push(r),v=0;else{h=!0;break}n.push(X(a,v));if(" "==w)if(c<b.length-1&&!b[c])c++,w=b[c++];else{h=!0;break}if(!w)break;v="<"==a.Z[0]?id:jd;if(!v[w]){h=!0;break}p.length&&v[w]<=v[p[p.length-1]]&&fd(a,n,p,1);p.push(w);a.ca="^_"==w?10:e;k=0}if(h||!fd(a,n,p)||1!=n.length)h=!0;h?g||a.K("parse error (%s)\n",r||w):f=n.pop();a.ca=m;return f}
function kd(a,b,c,d){for(var e,g=a.L/d|0;0<=(e=b.indexOf(c));){for(var f=0,h=e+1,k=g;h<b.length;){var n=b[h++];if(n==c){k=-1;break}if(!k)break;k--;n=n.charCodeAt(0);6==d&&(n-=32);n&=(1<<d)-1;f=X(a,f*Math.pow(2,d)+n,d*g,!0)}if(0<=k){a.K("parse error (%c%s%c)\n",c,b,c);return}b=b.substr(0,e)+D(a,f)+b.substr(h)}return b}
function bd(a,b,c){if(b){"{"!=a.Z[0]&&(b=b.split(a.Z[0]).join("{").split(a.Z[1]).join("}"));b=kd(a,b,'"',8);if(!b)return d;b=kd(a,b,"'",6);if(!b)return d;16!=a.ca&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);var d=gd(a,b,0,b.length,a.ca,c)}return d}
function hd(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-X(a,b);break;case 2:b=ed(a,b,-1);break;case 3:for(d=35;0<=d&&!dd(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function X(a,b,c,d){var e=b;c=c||a.L;if(d)if(32==c)e=b>>>0;else if(32>c)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),0>b||b>=a)e=b%a,0>e&&(e+=a)}else 32>=c?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}
l.ob=function(a){function b(h){for(var k=0;k<h.length;k++)if(void 0!=h[k])return!1;return!0}if(-1>a)return ld(this,this.ob);var c="";if(0<=a){var d=this.i[a];if(void 0!=d){c=d>>8;d&=255;var e=this.o[c];if(e){var g=this.s[c],f=g[d];(c&1?e.wb(f.O,this.l[c]):e.eb(f.O,this.l[c]))?(g[d]=void 0,this.i[a]=void 0,b(g)&&(g.length=0,b(this.i)&&(this.i.length=0)),c=this.v("%2d: %s %*a cleared\n",a,md[c],e.aa,f),--this.ea||this.ga||(c+=nd(this,!1))):c=this.v("invalid break address: %*a\n",e.aa,f)}else c="invalid bus"}else c=
this.v("invalid break index: %d\n",a)}else c="missing break index\n";return c};function od(a,b){if(a.X&&(void 0==b||a.X.O==b)){var c=void 0===c?W.ka:c;b=-1;var d=pd(a.X,a.s[c]);if(0<=d)for(var e=0;e<a.i.length;e++){var g=a.i[e];if(void 0!=g&&c==g>>8&&d==(g&255)){b=e;break}}c=b;0<=c&&a.ob(c);a.X=null}}
l.pb=function(a,b){b=void 0===b?!1:b;if(-1>a)return ld(this,this.pb,b);if(0<=a){var c=this.i[a];if(void 0!=c){var d=c>>8;c=this.s[d][c&255];if(void 0!=c){var e=b?"enabled":"disabled",g=this.o[d];!c.disabled==!b?(c.disabled=!b,a=this.v("%2d: %s %*a %s\n",a,md[d],g.aa,c,e)):a=this.v("%2d: %s %*a already %s\n",a,md[d],g.aa,c,e)}else a=this.v("no break address at index: %d\n",a)}else a=this.v("invalid break index: %d\n",a)}else a="missing break index\n";return a};
function ld(a,b,c){for(var d="",e=0;e<a.i.length;e++)void 0!=a.i[e]&&(d+=b.call(a,e,c));d||(d="no break addresses found");return d}function qd(a,b,c){c=void 0===c?W.ka:c;a=a.s[c];for(c=0;c<a.length;c++){var d=a[c];if(d.O==b)return d}}function pd(a,b){for(var c=0;c<b.length;c++)if(b[c].O==a.O)return c;return-1}
function rd(a,b){b=void 0===b?!1:b;for(var c="",d=0;d<a.i.length;d++){var e=a.i[d];if(void 0!=e){var g=e>>8;e=a.s[g][e&255];g=a.v("%s %*a",md[g],a.o[g].aa,e);b?(c&&(c+=";"),c+=g,e.disabled&&(c+=";bd "+d)):c+=a.v("%2d: %s %s\n",d,g,e.disabled?"disabled":"enabled")}}c||b||(c="no break addresses found\n");return c}
function sd(a,b,c){c=void 0===c?W.ka:c;if(b){var d=a.o[c];if(d){var e=a.s[c];var g=pd(b,e);if(0<=g)g=-(g+1);else{for(g=0;g<e.length&&void 0!=e[g];g++);e[g]=b}e=g;if(0<=e)if(g=c&1?d.ub(b.O,a.l[c]):d.cb(b.O,a.l[c])){for(g=0;g<a.i.length&&void 0!=a.i[g];g++);a.i[g]=c<<8|e;b=a.v("%2d: %s %*a set\n",g,md[c],d.aa,b);a.ea++||a.h.length||(b+=nd(a,!0))}else b=a.v("invalid break address: %*a\n",d.aa,b),a.s[c][e]=void 0;else b=a.v("%s %*a already set\n",md[c],d.aa,b)}else b="invalid bus"}else b="missing break address\n";
return b}function td(a,b){0<=b&&(a.J=b);var c="instruction break count: "+(0<a.J?a.J:"disabled")+"\n";0<b&&(a.h.length||(c+=nd(a,!0)),a.ga=!0);return c}function ud(a,b){var c;if(b){var d=Va(b);void 0!=d?a.ja=d?B.Ab:B.NONE:c=a.v("unrecognized message option: %s\n",b)}c||(c=a.v("break on message: %b\n",!!a.ja));return c}l.Ed=function(a,b){this.u||(void 0==a?Y(this,"break on unknown input %#0x: %#0x",b):(a=qd(this,a+b,W.oa))&&!a.disabled&&Y(this,"break on input %*a: %#0x",this.j.aa))};
l.Fd=function(a,b){this.u||(void 0==a?Y(this,"break on unknown output %#0x: %#0x",b):(a=qd(this,a+b,W.Ga))&&!a.disabled&&Y(this,"break on output %*a: %#0x",this.j.aa))};l.Gd=function(a,b){this.u||(void 0==a?Y(this,"break on unknown read %#0x: %#0x",b):(a+=b,this.h.length&&a==this.T.sb&&(this.$++,0<this.J&&(--this.J||Y(this,"break on instruction count")),this.h[this.S++]=a,this.S==this.h.length&&(this.S=0)),(b=qd(this,a,W.ka))&&!b.disabled&&(Y(this,"break on read %*a: %#0x",this.g.aa),od(this,a))))};
l.Hd=function(a,b){this.u||(void 0==a?Y(this,"break on unknown write %#0x: %#0x",b):(a=qd(this,a+b,W.Ja))&&!a.disabled&&Y(this,"break on write %*a: %#0x",this.g.aa))};function Y(a,b,c){b=a.v.apply(a,[b].concat(q(c)));G(a,b);qc(a.time)}function vd(a,b,c){c=void 0===c?a.g:c;return D(a,b.O,a.ca,c.aa,"")}
function wd(a,b,c){c=void 0===c?10:c;var d="";if(a.h.length){var e,g=[];c>a.h.length&&(c=a.h.length);0>b&&(b=c);var f=a.S-b;for(0>f&&(f+=a.h.length);0<=f&&f<a.h.length&&0<c;){var h=a.h[f++];if(void 0==h)break;f==a.h.length&&(f=0);e?e.O=h:e=Uc(h);for(h=0;1>h;h++)g[h]=cd(a,e,1);$c(a,e,-g.length);d+=a.vb(e,g,a.v("[%6d]",b--));c--}}return d||"no history"}
function xd(a,b,c){var d=[],e="";for(b="number"==typeof b?Uc(b):b;c--;){for($c(a,b,d.length);1>d.length;)d.push(cd(a,b,1));$c(a,b,-d.length);e+=a.vb(b,d)}return e}
function yd(a,b,c,d,e,g){var f="";g=g?a.j:a.g;c||(c=g.i);var h=c>>3;d||(d=128);var k=0,n=d+15>>4||1,p=4==h?16:a.ca;"y"==e&&(p=h,n=d,k=8*h);b||(b=a.xa);for(;n--&&0<d;){var m=e=0,r,w="",x="",v=vd(a,b,g);for(r=p;0<r&&0<d;r--){var z=cd(a,b,1,g);e|=z<<(m++<<3);m==h&&(w+=D(a,e,0,c,""),w+=1==h?9==r?"-":" ":" ",k&&(x+=D(a,e,2,c,"")),e=m=0);k||(x+=32<=z&&127>z?String.fromCharCode(z):".");d--}f&&(f+="\n");f+=v+"  "+w+" "+x}a.xa=b;return f}
l.Pd=function(){var a=[];kb(this,function(b){b.Ma&&b.Ma(a);return!0});return JSON.stringify(a,null,2)};function zd(a,b,c,d){var e=0,g="";d=d?a.j:a.g;for(var f=0;void 0!=b&&f<c.length;f++){var h=cd(a,b,0,d);if(void 0==h)break;var k=a,n=b,p=c[f],m=d;m=void 0===m?k.g:m;k.u++;m.xb(n.O,p);k.u--;g+=a.v("%*a: %#*n changed to %#*n\n",a.g.aa,b,a.g.i,h,a.g.i,c[f]);$c(a,b,1,d);e++}e||(g+=a.v("%d locations updated\n",e));a.time.update();return g}
function nd(a,b){var c="";void 0!=b&&b==!a.h.length&&Lc(a.g,function(d){b?a.g.cb(d.Aa,a.l[W.ka]):a.g.eb(d.Aa,a.l[W.ka])})&&(b?(a.S=0,a.h=Array(Ad)):a.h=[]);return c+=a.v("instruction history %s\n",a.h.length?"enabled":"disabled")}l.ua=function(a){var b=a.shift();return this.W==b?(Ta(this,a.shift()),this.I.fa=a.shift(),!0):!1};l.rc=function(a){sa(this.ja,a)?Y(this,"break on message"):this.time.X=!0};
l.Rd=function(a){var b=a[1],c=a[2],d=[],e=[],g=!1,f="";this.R=void 0;if("*"==c)var h=-2;else{h=ra(c);void 0==h&&(h=-1);var k=Wc(this,c,e);if(null===k)return}var n=0;a[3]&&(n=ra(a[3].substr("l"==a[3][0]?1:0))||8);for(var p=3;p<a.length;p++)d.push(ra(a[p],16));if("d"==b){p=Vc(this,c,d);if(void 0!=p)return p;b=this.U||b}if("s"!=b[0]&&e.length)return"unrecognized symbol(s): "+e;switch(b[0]){case "b":"c"==b[1]?f=this.ob(h):"d"==b[1]?f=this.pb(h):"e"==b[1]?f=this.pb(h,!0):"i"==b[1]?f=sd(this,k,W.oa):"l"==
b[1]?f=rd(this):"m"==b[1]?f=ud(this,c):"n"==b[1]?f=td(this,h):"o"==b[1]?f=sd(this,k,W.Ga):"r"==b[1]?f=sd(this,k,W.ka):"w"==b[1]?f=sd(this,k,W.Ja):"?"==b[1]?(f="break commands:\n",Bd.forEach(function(m){f+=m+"\n"})):b[1]&&(f=void 0);break;case "d":this.U=b;if("b"!=b[1]&&b[1])if("w"==b[1])c=16;else if("d"==b[1])c=32;else if("i"==b[1]){if(!this.j){f="invalid bus";break}c=this.j.i;n=n||1;g=!0}else{if("h"==b[1])this.U="",f=wd(this,h,n);else if("?"==b[1]){if(this.U="",f="dump commands:\n",Cd.forEach(function(m){f+=
m+"\n"}),this.H.length)for(f+="dump extensions:\n",b=0;b<this.H.length;b++)k=this.H[b],f+=this.v("d   %-12s%s\n",k.name,k.Nd)}else this.U="",f=void 0;break}else c=8;f=yd(this,k,c,n,b[2],g);break;case "e":if("o"==b[1]){if(!this.j){f="invalid bus";break}g=!0}else if(b[1]){f=void 0;break}f=zd(this,k,d,g);break;case "g":if(this.time.start()){if(void 0!=k){od(this);f=sd(this,k);if(2!=f.indexOf(":"))break;this.X=k;f=""}break}f="already started\n";break;case "h":qc(this.time)||(f="already stopped\n");break;
case "p":a.shift();a.shift();b=a.join(" ");f+=this.v("%s = %s\n",b,D(this,bd(this,b)));break;case "r":if(b=b.substr(1).toUpperCase()){if(void 0==mb(this.T,b)){f+=this.v("unrecognized register: %s\n",b);break}void 0!=k&&rb(this.T,b,k.O)}this.da.O=this.T.i;f+=this.T.toString();break;case "s":k=Va(c);if("h"==b[1]){if(this.ea||0<this.J)k=void 0;f=nd(this,k);void 0!=k&&(this.ga=k)}else"p"==b[1]?0<h?(nc(this.time,h),f="target speed:  "+tc(this.time.s)):f="current speed: "+Cc(this.time):"s"==b[1]&&this.ya?
(h=this.ya.indexOf(c),0<=h&&(this.style=this.ya[h]),f="style: "+this.style):"?"==b[1]?(f="set commands:\n",Dd.forEach(function(m){f+=m+"\n"})):f=void 0;break;case "t":n=ra(c,10)||1;this.R=!0;if(b[1]){if("r"!=b[1]){f=void 0;break}this.R=!1}vc(this.time,n);break;case "u":if(b[1]){f=void 0;break}n||(n=8);k||(k=this.da);f+=xd(this,k,n);this.da=k;break;case "?":f="debugger commands:\n";Ed.forEach(function(m){f+=m+"\n"});break;default:f=void 0}void 0==f&&a[0]&&(f="unrecognized command '"+a[0]+"' (try '?')\n");
return f};l.qb=function(a){return a&&this.ua(a[0])?(a.shift(),!0):!1};l.Ma=function(a){var b=[];this.va(b);a.push(b);this.Y=0};l.sc=function(a){a&&(this.time.g?this.Y&&this.ra&&Pb(this.ra):this.R?this.wa(xd(this,this.T.i,1)):(this.$&&(G(this.T,this.$+" instructions executed"),this.$=0),this.T.wa(this.T.toString()),void 0==this.R&&this.Y&&(a=this.sa(Ca.Ta,!0))&&a.focus()),this.Y++)};l.va=function(a){a.push(this.W);a.push(rd(this,!0));a.push(this.I.fa)};
l.vb=function(a,b,c){var d=this.v,e=vd(this,a);b=b.shift();$c(this,a,1);return d.call(this,"%s %02x       unsupported       ; %s\n",e,b,c||"")};
var Ed="b?\t\tbreak commands;d?\t\tdump commands;e[o] [addr] ...\tedit memory/ports;g    [addr]\trun (to addr);h\t\thalt;p    [expr]\tparse expression;r?   [value]\tdisplay/set registers;s?\t\tset commands;t[r] [n]\tstep (n instructions);u    [addr] [n]\tunassemble (at addr)".split(";"),Bd="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write;bm [on|off]\tbreak on message;bn [count]\tbreak on instruction count".split(";"),Cd=
"db  [addr]\tdump bytes (8 bits);dw  [addr]\tdump words (16 bits);dd  [addr]\tdump dwords (32 bits);di  [addr]\tdump input ports;d*y [addr]\tdump values in binary;dh  [n] [l]\tdump instruction history buffer;ds\t\tdump machine state".split(";"),Dd=["sh [on|off]\tset instruction history","sp [n]\t\tset speed multiplier","ss\t\tset debugger style"],ad={ic:1,dd:0,fd:2,kf:0},W={ka:0,Ja:1,oa:2,Ga:3},Fd={},md=(Fd[W.ka]="br",Fd[W.Ja]="bw",Fd[W.oa]="bi",Fd[W.Ga]="bo",Fd),Z={BYTE:1,cd:2,gd:4,Tb:5,Gb:6,Bd:7},
Xc={"=":Z.Bd,1:Z.BYTE,2:Z.cd,4:Z.gd,"@":Z.Tb,";":Z.Gb},Ad=1E5,jd={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},id={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};function Gd(a,b,c){Rc.call(this,a,b,c)}y(Gd,Rc);C.CPUx86=Gd;
function Hd(a,b,c){Tc.call(this,a,b,c)}y(Hd,Tc);Hd.prototype.vb=function(a,b,c){var d=vd(this,a),e="",g=Zc(this,a,Z.Tb),f=Zc(this,a,Z.Gb);b=b.shift();e+=D(this,b,16,8,"");$c(this,a,1);a=this.v("%#02x",b);d=this.v("%s %-7s %-7s %s",d,e,a,"");c?f&&(c+=" "+f):f&&(c=f);c&&(d=this.v("%-32s; %s",d,c));g&&(d=g+":\n"+d);return d+"\n"};C.Dbgx86=Hd;
function Id(a,b,c){S.call(this,a,b,c);this.X=this.m.bufferAddr;this.M=this.m.interruptRate;this.R=this.m.refreshRate||60;this.U=ib(this,this.m.bus);this.T=P(this,"CPU");this.time=P(this,"Time");this.S=Ab(this.time,this.W,this.ea.bind(this));this.time.U.push(this);Fb(this.time,this.S,1E3/Math.max(this.R,this.M))}y(Id,S);Id.prototype.sc=function(){};
Id.prototype.ea=function(a){if(!a){if(this.$&&this.Y){a=this.U;var b=this.X,c=this.Y,d=b>>>a.h;for(b=a.blockSize-(b&a.l);0<c&&d<a.g.length;){var e=a.g[d];e.o&&(e.o=!1,e.h.type==Hc&&(e.i?e.j=e.yb:e.qa=e.yb));c-=b;b=a.blockSize;d++}}Fb(this.time,this.S,1E3/Math.max(this.R,this.M))}};C.PCx86Video=Id;
function Jd(a,b,c){N.call(this,a,a);var d=this;this.i=!1;this.s=c;this.h="";this.o=this.l=!1;ob(this,!1);this.fa=B.Ec;b=b.trim();"{"==b[0]?Kd(this,b):(this.h=b,Na(this.h,function(e,g,f,h){4==f&&(!h&&g?(Kd(d,g),Ld(d)):d.K("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.o=!0;Ld(d)});window.addEventListener(Ra("iOS")?"pagehide":Ra("Opera")?"unload":"beforeunload",function(){Md(d)});window.addEventListener("pageshow",function(){d.i||d.ia(!0)})}y(Jd,N);
Jd.prototype.za=function(a,b){var c=this;switch(a){case Nd:b.onclick=function(){c.ia()};break;case Od:b.onclick=function(){c.ma()}}N.prototype.za.call(this,a,b)};
function Ld(a){var b=!0;if(a.l&&a.o){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],C[d]?"Machine"==d?(a.K("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2022 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.K("Configuration: %s\n",a.h)):new C[d](a.N,c,e):a.K('unrecognized %s device "%s"\n',d,c)}catch(f){e.optional||(a.K('error initializing %s device "%s": %s\n',d,c,f.message),b=!1),qb(a,c)}}if(a.j){var g=Sa(a);kb(a,function(f){return f.qb&&!f.qb(g)?(f.K('unable to restore state for device "%s"\n',
f.W),!1):!0})}ob(a,!0);pb(a,a.ia.bind(a,b))||a.K("machine %s not ready to power, waiting for device(s)\n",a.N)}}
function Kd(a,b){try{a.g=JSON.parse(b);var c=a.g[a.N];if(!c){c=a.g[va(a.h)];if(!c)throw Error("configuration missing machine ID");a.g[a.N]=c}jb(a,c,["autoSave","autoStart"]);a.j=!1!==a.m.autoSave;a.u=!1!==a.m.autoStart;if(a.s){var d=eval("("+a.s+")"),e;for(e in d)a.m[e]=d[e]}a.l=!0}catch(g){c=g.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),G(a,"machine '"+a.N+"' initialization error: "+c)}}
Jd.prototype.ia=function(a){a=void 0===a?!this.i:a;if(nb(this)){var b=this;a&&G(this,"power on");kb(this,function(c){c.ia&&c!=b&&("CPU"!=c.m["class"]||b.u&&nb(b)?c.ia(a):c.time.update(!0));return!0});(this.i=a)||G(this,"power off")}};Jd.prototype.ma=function(){if(nb(this)){var a=this;kb(this,function(b){b.ma&&b!=a&&b.ma();return!0});G(this,"reset")}};function Md(a){if(a.j){var b=[];kb(a,function(c){c.Ma&&c.Ma(b);return!0});$a(a,b)}a.ia(!1)}var Nd="power",Od="reset";
window.PCx86v3=function(a,b,c){var d=new Jd(a,b,c);window.command=function(e){return Ta(d,e)};return d};C.Machine=Jd;})()

//# sourceMappingURL=pcx86v3.js.map
