(function(){/*
 https://www.pcjs.org/machines/modules/v3/defines.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/message.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v2/format.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdlib.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/stdio.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/webio.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/device.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/input.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/led.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/monitor.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/time.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/bus.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/memory.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/ram.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/rom.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/cpu.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/debugger.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/pcx86/modules/v3/cpux86.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/pcx86/modules/v3/dbgx86.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/pcx86/modules/v3/video.js (C) 2012-2024 Jeff Parsons
 https://www.pcjs.org/machines/modules/v3/machine.js (C) 2012-2024 Jeff Parsons
*/
var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function r(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)a=b.call(a);else if("number"==typeof a.length)a={next:aa(a)};else throw Error(String(a)+" is not an iterable or ArrayLike");for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function w(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function z(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.$e=b.prototype}function la(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
w("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
w("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});w("String.prototype.repeat",function(a){return a?a:function(b){if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");var c=this;if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});
w("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});w("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});
w("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,f){this.u=g;ca(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.u};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
w("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ea[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(aa(this))}})}return a});function ma(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function na(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}w("Array.prototype.keys",function(a){return a?a:function(){return na(this,function(b){return b})}});
w("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function A(a){return a?a:Array.prototype.fill}w("Int8Array.prototype.fill",A);w("Uint8Array.prototype.fill",A);w("Uint8ClampedArray.prototype.fill",A);w("Int16Array.prototype.fill",A);w("Uint16Array.prototype.fill",A);w("Int32Array.prototype.fill",A);
w("Uint32Array.prototype.fill",A);w("Float32Array.prototype.fill",A);w("Float64Array.prototype.fill",A);w("Number.parseInt",function(a){return a||parseInt});w("Array.prototype.values",function(a){return a?a:function(){return na(this,function(b,c){return c})}});function oa(){this.U=""}var pa=new ArrayBuffer(2);(new DataView(pa)).setUint16(0,256,!0);new Uint16Array(pa);
var C={Le:"undefined"!=typeof window,node:"undefined"!=typeof window?{}:global,process:"undefined"!=typeof process?process:{},window:"undefined"!=typeof window?window:global,document:"undefined"!=typeof document?document:{},Ya:{machines:{},components:[],commands:{},files:null}};C.window.PCjs?C.Ya=C.window.PCjs:C.window.PCjs=C.Ya;var qa=C.process,D=C.Ya.machines,ra=C.Ya.components,E={};E.Defines=oa;
var sa={all:0xffffffffffff,addr:1,bus:2,fault:4,memory:8,ports:16,chips:32,kbd:64,serial:128,misc:256,cpu:512,mmu:2048,"int":1024,trap:4096,video:8192,monitor:16384,screen:32768,disk:131072,file:65536,time:262144,timer:524288,event:1048576,input:2097152,key:4194304,mouse:8388608,touch:16777216,info:274877906944,warn:549755813888,error:1099511627776,halt:70368744177664,buffer:0x800000000000};function ta(){this.u={};for(var a=0;23>a;a++)this.u["ACDFGHMNSTWYBbdfjcsoXx%"[a]]=null}
ta.prototype.g=function(a,b){return this.u[a]?!1:(this.u[a]=b,!0)};function ua(){var a=la.apply(0,arguments);if(void 0===a[0])a=new Date(Date.now());else if("string"===typeof a[0]){var b=a[0];0>b.indexOf(":")?b+=" "+(a[1]||"00:00:00 UTC"):b.match(/^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$/)&&(a[1]||(b+=" UTC"));a=new Date(b)}else a=void 0===a[1]?new Date(a[0]):new Date(Date.UTC.apply(Date,r(a)));return a}
ta.prototype.I=function(a){var b=la.apply(1,arguments);if(!b||!b.length)return a;var c="",d=a.split(/%([-+ 0#]*)([0-9]*|\*)(\.[0-9]+|)([bwhlL]?)([A-Za-z%])/),e=0,g;for(g=0;g<d.length-6;g+=6){c+=d[g];var f=d[g+5];if(void 0===this.u[f])c+="%"+d[g+1]+d[g+2]+d[g+3]+d[g+4]+f;else{if(e<b.length){var h=b[e];"%"!=f&&e++}else h=b[b.length-1];var k=!1,p=d[g+1],l=0<=p.indexOf("#"),u=0<=p.indexOf("0"),m=d[g+2];"*"==m?(m=h,h=e<b.length?b[e++]:b[b.length-1]):m=+m||0;var q=d[g+3];q=q?+q.substr(1):-1;var v=d[g+4],
t=null,x=0,y="",B=0<="ACDFGHMNSTWY".indexOf(f)&&"object"!=typeof h?ua(h):h;switch(f){case "C":c+=isNaN(B.getTime())?void 0:this.I("%#W, %#F %#D, %#Y".replaceAll("#",l?"#":""),B);continue;case "D":h=l?B.getUTCDate():B.getDate();f="d";break;case "A":case "G":case "H":h=l?B.getUTCHours():B.getHours();"A"==f?(h=12>h?"am":"pm",f="s"):("G"==f&&(h=h?12<h?h-12:h:12),f="d");break;case "F":case "M":h=l?B.getUTCMonth():B.getMonth();"F"==f?(h=va[h],f="s"):(h++,f="d");break;case "N":h=l?B.getUTCMinutes():B.getMinutes();
f="d";break;case "S":h=l?B.getUTCSeconds():B.getSeconds();f="d";break;case "T":c+=isNaN(B.getTime())?void 0:this.I("%#Y-%#02M-%#02D %#02H:%#02N:%#02S".replaceAll("#",l?"#":""),B);continue;case "W":h=wa[l?B.getUTCDay():B.getDay()];f="s";break;case "Y":h=l?B.getUTCFullYear():B.getFullYear(),0<q&&(h%=Math.pow(10,q)),f="d"}switch(f){case "b":c+=h?"true":"false";break;case "d":h=Math.trunc(h),0<=q&&(u=!0,m<q&&(m=q),q=-1);case "f":h=+h;f=h+"";0<=q&&(f=h.toFixed(q));f.length<m&&(u?(0>h&&(m--,f=f.substr(1)),
f=("0".repeat(m)+f).slice(-m),0>h&&(f="-"+f)):f=(" ".repeat(m)+f).slice(-m));c+=f;break;case "j":c+=JSON.stringify(h,null,m||void 0);break;case "c":h="string"==typeof h?h[0]:String.fromCharCode(h);case "s":if(void 0!=h)for("string"!=typeof h&&(h=h.toString()),0<=q&&(h=h.substr(0,q));h.length<m;)h=0<=p.indexOf("-")?h+" ":" "+h;c+=h;break;case "B":x=2,l&&(y="0b");case "o":x||(x=8),!y&&l&&(y="0o");case "X":t=xa;case "x":f="";x||(x=16);!y&&l&&(y="0x");t||(t=ya);"string"==typeof h&&"-"==h[0]&&(k=!0,h=
h.slice(1));h=Math.trunc(h);k&&(h=-h);0>h&&((h|0)==h?h>>>=0:Math.abs(h)<=Math.pow(2,53)&&(h+=Math.pow(2,53)));0<=q&&(u=!0,m<q&&(m=q));u&&!m&&("b"==v?m=2:"h"==v||"w"==v?m=4:"l"==v?m=8:(m=Math.abs(h),m=255>=m?2:65535>=m?4:4294967295>=m?8:9),m+=y.length);m-=y.length;do k=16,Number.isNaN(h)||(k=h&x-1,h=Math.trunc(h/x)),u||!f||k||h?f=t[k]+f:(y&&(f=y+f,y=""),0<m&&(f=" "+f));while(0<--m||h);c+=y+f;break;case "%":c+="%";break;default:c=this.u[f]?c+this.u[f](f,p,m,q,h):c+("(unimplemented sprintf type: %"+
f+")")}}}return c+=d[g]};var wa="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),va="January February March April May June July August September October November December".split(" "),ya="0123456789abcdef?",xa="0123456789ABCDEF?";function za(){oa.apply(this,arguments)}z(za,oa);
function Aa(a,b){if(a){b||(b=10);var c,d=0<a.indexOf(",");d&&(a=a.replace(/,/g,""));var e=c=a.charAt(0);"#"==c?(b=8,c=""):"$"==c&&(b=16,c="");e!=c?a=a.substr(1):(e=c=a.substr(0,2),"0b"==c&&d||"^B"==c?(b=2,c=""):"0o"==c||"^O"==c?(b=8,c=""):"^D"==c?(b=10,c=""):"0x"==c&&(b=16,c=""),e!=c&&(a=a.substr(2)));e=c=a.slice(-1);"Y"==c||"y"==c?(b=2,c=""):"."==c?(b=10,c=""):"H"==c||"h"==c?(b=16,c=""):"K"==c?c="000":"M"==c?c="000000":"G"==c&&(c="000000000");e!=c&&(a=a.slice(0,-1)+c);var g;e=0;10>=b&&(c=a.match(/(-?[0-9]+)B([0-9]*)$/))&&
(a=c[1],e=35-((c[2]||35)&255));if((b&&10!=b?16==b?null!==a.match(/^-?[0-9a-f]+$/i):8==b?null!==a.match(/^-?[0-7]+$/):2==b&&null!==a.match(/^-?[01]+$/):null!==a.match(/^[+-]?[0-9]+$/))&&!isNaN(g=parseInt(a,b))){e&&(0>g&&(g+=Math.pow(2,36)),g=0<e?g*Math.pow(2,e):Math.trunc(g/Math.pow(2,-e)));var f=g}}return f}
function F(a,b,c,d,e){d=void 0===d?0:d;var g=void 0===g?0:g;var f="",h="",k=-1;c||(c=a.ea||10);d&&(k=Math.ceil(d/Math.log2(c)));if(void 0==e)switch(c){case 8:e="0o";break;case 16:e="0x";break;case 10:h=".";default:e=""}isNaN(b)||"number"!=typeof b?(b=void 0,e=h=""):(0>b&&-1<b&&(b=-1),d&&(0>b&&(b+=Math.pow(2,d)),b>=Math.pow(2,d)&&(k=Math.ceil(Math.log(b)/Math.log(c)))));for(a=g||-1;k--;){a||(f=","+f,a=g);if(void 0==b){if(f="?"+f,0>k)break}else if(d=b%c,b=Math.trunc(b/c),d+=0<=d&&9>=d?48:55,f=String.fromCharCode(d)+
f,!b&&0>k)break;a--}return e+f+h}function Ba(a,b){var c=a/G|0,d=b/G|0;return(a&b)==(b|0)&&(c&d)==d}var G=Math.pow(2,32);E.StdLib=za;function H(){za.call(this);this.Ma=new ta;this.Qb=this.Ma.g.bind(this.Ma);this.u=this.Ma.I.bind(this.Ma)}z(H,za);H.prototype.flush=function(){var a=Ca;Ca="";this.za(a)};function Da(a){var b=a,c=a.lastIndexOf("/");0<=c&&(b=a.substr(c+1));c=b.indexOf("&");0<c&&(b=b.substr(0,c));c=b.lastIndexOf(".");0<c&&(b=b.substring(0,c));return b}
H.prototype.za=function(a,b){var c=a.length,d=a.lastIndexOf("\n");b?0<=d&&(b=Date.now(),Ea||(Ea=b),a=((b-Ea)/1E3).toFixed(3)+": "+a,c=a.length):"node"==this.U?(qa.Ze.write(a),a=""):(0<=d&&(console.log(Ca+a.slice(0,d)),Ca="",a=a.slice(d+1)),Ea=null);Ca+=a;return c};H.prototype.s=function(a){return this.za(this.u.apply(this,[a].concat(r(la.apply(1,arguments)))))};var Ca="",Ea=null;E.StdIO=H;
function I(a){H.call(this);this.W={};this.ga=0;this.I=this;a&&(this.I.ga=0,this.I.va=[],this.I.la=0,this.I.Na={},this.I.La=!1)}var Fa;z(I,H);n=I.prototype;n.xa=function(a,b){var c=this,d=this;this.W[a]=b;switch(a){case Ga.tc:b.onclick=function(){var e=c.ta(Ga.Pa,!0);e&&(e.value="")};break;case Ga.Pa:Ha(b),b.addEventListener("keydown",function(e){Ia(d,e,!0)}),b.addEventListener("keypress",function(e){Ia(d,e)})}};function Ja(a,b){var c=Ka.zb;a.I.Na[c]||(a.I.Na[c]=[]);a.I.Na[c].push(b)}
function Ha(a){a.setAttribute("autocapitalize","off");a.setAttribute("autocomplete","off");a.setAttribute("autocorrect","off");a.setAttribute("spellcheck","false");a.value=""}n.error=function(a,b){b=this.u.apply(this,[a].concat(r(b)));var c="%s";a=!1;"boolean"==typeof c&&(a=c,c=b.shift());if(b=this.u.apply(this,[c].concat(r(b))))this.s("%s\n",b),a||alert(b)};n.ta=function(a){return this.W[a]};
function La(a,b,c){if(a){do{for(var d=0;d<Ma.length;d++){var e=Ma[d];if(c){if(e+=c,b+e in a)return e}else if(e=e?e+b[0].toUpperCase():b[0],e+=b.substr(1),e in a)return e}if(0>b.indexOf("screen"))break;b=b.replace("screen","Screen")}while(1)}return null}function Na(a,b){return a.m.bindings&&a.m.bindings[b]}function Oa(a){if(a=a.W[Pa])var b=a.textContent;return b}function Qa(a,b,c){a=+a||0;a<b&&(a=b);a>c&&(a=c);return a}
function J(a,b,c,d){a=a.m[b];void 0===a?a=c:(d&&void 0!==d[a]&&(a=d[a]),d=typeof c,typeof a!=d&&("boolean"==d?a=!!a:"number"==typeof c&&(a=+a)));return a}
function Ra(a,b){var c=0,d=null,e=window.XMLHttpRequest?new window.XMLHttpRequest:new window.ActiveXObject("Microsoft.XMLHTTP");e.onreadystatechange=function(){4!==e.readyState?b(a,d,e.readyState,c):(d=e.responseText,200==e.status||!e.status&&d.length&&"file:"==(window?window.location.protocol:"file:")||(c=e.status||-1),b(a,d,e.readyState,c))};e.open("GET",a,!0);e.send()}
function Sa(){var a,b=Fa;if(!b){b={};if(window){a||(a=window.location.search.slice(1));for(var c,d=/\+/g,e=/([^&=]+)=?([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1].replace(d," ")).trim()]=decodeURIComponent(c[2].replace(d," ")).trim()}Fa=b}return b}function Ta(a){if(void 0===K.eb){var b=!1;if(window)try{window.localStorage.setItem(K.Fa,K.Fa),b=window.localStorage.getItem(K.Fa)==K.Fa,window.localStorage.removeItem(K.Fa)}catch(c){a.s("%s\n",c.message),b=!1}K.eb=b}return!!K.eb}
function Ua(a,b){b=void 0===b?0:b;1<b&&b%2&&b--;b=b||a.ga;return-1==(b|1)||Ba(a.I.ga,b)?!0:!1}function Va(a){if(window){var b=window.navigator.userAgent;return"iOS"==a&&(!!b.match(/(iPod|iPhone|iPad)/)||"MacIntel"===window.navigator.platform&&1<window.navigator.maxTouchPoints)||"MSIE"==a&&!!b.match(/(MSIE|Trident)/)||0<=b.indexOf(a)}return!1}function Wa(a){var b=null;if(Ta(a)){var c;if(window)try{(c=window.localStorage.getItem(a.N))&&(b=JSON.parse(c))}catch(d){a.s("%s\n",d.message)}}return b}
function Ia(a,b,c){b=b||window.event;var d=b.which||b.keyCode;if(d){var e=a.I,g=b.target;if(c){a=!1;var f;c=g.value;var h=c.lastIndexOf("\n");d==L.wb&&g.selectionStart<=h+1&&(a=!0);d==L.Yc?(a=!0,0<e.la&&(f=e.va[--e.la])):d==L.xc&&(a=!0,e.la<e.va.length&&(f=e.va[++e.la]||""));a&&b.preventDefault();void 0!=f&&(g.value=c.substr(0,h+1)+f)}else d=String.fromCharCode(d),f=g.value,c=f.lastIndexOf("\n"),g.selectionStart<=c&&g.setSelectionRange(f.length,f.length),b.stopPropagation(),"@"==d&&0<e.la&&c+1==f.length&&
(g.value+=e.va[--e.la],d="\r"),"\r"==d&&(b.preventDefault(),f=g.value+="\n",g.blur(),g.focus(),(b=Xa(a,f.slice(f.lastIndexOf("\n",f.length-2)+1,-1)||""))&&a.s("%s\n",b.replace(/\n$/,"")))}}function Ya(a){window&&window.addEventListener("resize",a)}function Za(a){return"true"==a||"on"==a?!0:"false"==a||"off"==a?!1:void 0}
function $a(a,b){if(void 0!=b){var c=a.I;try{if(b=b.trim())c.la<c.va.length&&b==c.va[c.la]?c.la++:(c.va.push(b),c.la=c.va.length);var d=b.split(" "),e=d[0],g=a.I.Na[Ka.zb];switch(e[0]){case "m":if("?"==e[1]){var f="";ab.forEach(function(u){f+=u+"\n"});f&&(f="message commands:\n"+f);break}f="";var h=void 0;e=d[d.length-1].toLowerCase();var k=Za(e);void 0!=k&&d.pop();1>=d.length&&(void 0!=k&&(h=k,k=void 0),d[1]="all");"all"==d[1]&&(d=Object.keys(sa));for(g=1;g<d.length;g++){e=d[g];var p=sa[e];if(!p){f+=
"unrecognized message: "+e+"\n";break}void 0!=k&&bb(a,p,k);if(void 0==h||h==Ua(a,p))f+=a.u("%8s: %b\n",e,Ua(a,p))}Ua(a,0x800000000000)&&(f+="all messages will be buffered until buffer is turned off\n");f||(f="no messages\n");break;case "?":f="",cb.forEach(function(u){f+=u+"\n"}),f&&(f="default commands:\n"+f);default:if(d.unshift(b),g)for(a=0;a<g.length;a++){var l=g[a](d);if(void 0!=l){f=f?f+l:l;break}}}}catch(u){f="error: "+u.message+"\n"}}return f}
function Xa(a,b){b=void 0===b?"?":b;if(b){var c="";b=b.split(/(?:\n|;\s*)/);for(var d=0;d<b.length;d++)c+=$a(a,b[d])}return c}
n.za=function(a,b){void 0==b&&(b=Ua(this,0x800000000000));if(!b){var c=this.ta(Ga.Pa,!0);if(c){b=c.selectionStart;for(var d=a.split(/([\n\r\b])/),e=0;e<d.length;e++){var g=d[e];if(g)if("\b"==g||"\r"==g)for(;0<b&&"\n"!=c.value.slice(b-1,b)&&(b--,"\b"!=g););else if("\n"==g){for(g="";b<c.value.length&&(g=c.value[b],b++,"\n"!=g););"\n"!=g&&(c.value+="\r\n",b=c.value.length)}else c.value=c.value.slice(0,b)+g+c.value.slice(b+g.length),b+=g.length}c.focus();c.setSelectionRange(b,b);8192<=c.value.length&&
(c.value=c.value.slice(c.value.length-8192+4096));c.scrollTop=c.scrollHeight;return a.length}}return H.prototype.za.call(this,a,b)};n.s=function(a){var b=la.apply(1,arguments),c=0;"number"==typeof a&&(c=a,a=b.shift());return Ua(this,c)?(Ba(c,1099511627776)&&(a="error: "+a),Ba(c,549755813888)&&(a="warning: "+a),H.prototype.s.call.apply(H.prototype.s,[this,a].concat(r(b)))):0};function db(a,b){if(Ta(a)){b=JSON.stringify(b);try{window.localStorage.setItem(a.N,b)}catch(c){a.s("%s\n",c.message)}}}
function eb(a,b,c){(a=a.W[b])&&a.textContent!=c&&(a.textContent=c)}function bb(a,b,c){var d=!1;c?(c=a.I.ga,a.I.ga=(c|b)+(c/G|0|b/G|0)*G):(d=Ba(a.I.ga,0x800000000000)&&Ba(b,0x800000000000),c=a.I.ga,a.I.ga=(c&~b)+((c/G|0)&~(b/G|0))*G);d&&a.flush()}
var Ga={tc:"clear",Pa:"print"},cb=["\u2191 \u2193\t\trecall commands","@\t\trepeat last command","m?\t\tmessage commands"],ab=["m\t\tdisplay all messages","m on\t\tdisplay all active messages","m off\t\tdisplay all inactive messages","m all [on|off]\tturn all messages on or off","m ... [on|off]\tturn selected messages on or off"],Ka={zb:"command"},fb={Bb:13,cb:65,vb:66,xb:67,Cb:68,E:69,Db:70,Fb:71,Gb:72,Hb:73,Ib:74,Jb:75,Kb:76,Nb:77,Pb:78,Rb:79,Sb:80,Q:81,Ub:82,Wb:83,Zb:84,ac:85,cc:86,ec:87,fc:88,
hc:89,hb:90,a:97,b:98,c:99,d:100,e:101,f:102,Qe:103,Re:104,Se:105,Te:106,k:107,Ue:108,Ve:109,n:110,We:111,p:112,q:113,r:114,Xe:115,t:116,bf:117,cf:118,w:119,x:120,y:121,z:122},L={wb:8,Vc:9,Gc:10,Bb:13,Sc:16,vc:17,sc:18,Ae:19,fb:20,Cd:27,Uc:32,De:33,Ce:34,Bd:35,Xd:36,Mb:37,Yc:38,gb:39,Ud:39,xc:40,Rd:44,Ee:44,Yd:45,Ad:46,Td:46,Wd:47,ZERO:48,ONE:49,Xc:50,Wc:51,Fc:52,Ec:53,Tc:54,Rc:55,yc:56,Hc:57,Dc:59,Cc:61,cb:65,vb:66,xb:67,Cb:68,E:69,Db:70,Fb:71,Gb:72,Hb:73,Ib:74,Jb:75,Kb:76,Nb:77,Pb:78,Rb:79,Sb:80,
Q:81,Ub:82,Wb:83,Zb:84,ac:85,cc:86,ec:87,fc:88,hc:89,hb:90,yb:91,Sd:91,Qd:92,He:93,Vd:93,be:96,se:96,Pd:96,ce:97,qe:97,de:98,pe:98,ee:99,ve:99,fe:100,te:100,ge:101,me:101,he:102,xe:102,ie:103,re:103,je:104,ze:104,ke:105,we:105,ue:106,le:107,ye:109,ne:110,oe:111,Dd:112,Hd:113,Id:114,Jd:115,Kd:116,Ld:117,Md:118,Nd:119,Od:120,Ed:121,Fd:122,Gd:123,Ic:144,Pc:145,Bc:173,Qc:186,zc:187,zd:188,wc:189,Be:190,Je:191,xd:192,Zd:219,yd:220,Ge:221,Fe:222,Ac:224,$d:901,dc:1E3},gb={},hb=(gb[L.Dc]=L.Qc,gb[L.Cc]=L.zc,
gb[L.Bc]=L.wc,gb[L.Ac]=L.yb,gb),ib={Mb:1,gb:2,ae:3},M={},jb=(M[L.wb]="\b",M[L.Vc]="\t",M[L.Gc]="\n",M[L.Bb]="\r",M[L.Uc]=" ",M[L.ZERO]="0",M[L.ONE]="1",M[L.Xc]="2",M[L.Wc]="3",M[L.Fc]="4",M[L.Ec]="5",M[L.Tc]="6",M[L.Rc]="7",M[L.yc]="8",M[L.Hc]="9",M[L.cb]="A",M[L.vb]="B",M[L.xb]="C",M[L.Cb]="D",M[L.E]="E",M[L.Db]="F",M[L.Fb]="G",M[L.Gb]="H",M[L.Hb]="I",M[L.Ib]="J",M[L.Jb]="K",M[L.Kb]="L",M[L.Nb]="M",M[L.Pb]="N",M[L.Rb]="O",M[L.Sb]="P",M[L.Q]="Q",M[L.Ub]="R",M[L.Wb]="S",M[L.Zb]="T",M[L.ac]="U",M[L.cc]=
"V",M[L.ec]="W",M[L.fc]="X",M[L.hc]="Y",M[L.hb]="Z",M[L.Mb]="Left",M[L.gb]="Right",M),Ma=["","moz","ms","webkit"],kb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",
darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",
fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",
lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",
navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",rebeccapurple:"#663399",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"},K={eb:void 0,Fa:"PCjs.localStorage"};E.WebIO=I;
function N(a,b,c,d){a=void 0===a?"default":a;b=void 0===b?a:b;c=void 0===c?{}:c;d=void 0===d?[]:d;I.call(this,a==b);this.N=a;this.U=b;D[this.N]||(D[this.N]={});D[this.N][this.U]&&this.s("warning: machine configuration contains multiple '%s' devices\n",this.U);D[this.N][this.U]=this;this.id=this.N==this.U?this.N:this.N+"."+this.U;ra.push(this);this.I=O(this,this.N);this.ready=!0;lb(this,c,d);this.Oa={};this.Tb=[]}z(N,I);n=N.prototype;n.ib=function(){};n.jb=function(){};
function lb(a,b,c){c=b.overrides||c;if(c.length){var d=Sa();for(h in d)if(0<=c.indexOf(h)){var e=d[h],g=Aa(e,10);void 0==g&&("true"==e?g=!0:"false"==e?g=!1:(g=e,e='"'+e+'"'));b[h]=g;a.s("overriding %s property '%s' with %s\n",a.U,h,e)}}a.m=b;c=b.bindings;c=void 0===c?{}:c;if("undefined"!=typeof document){a.m.W||(a.m.W=c);(d=Array.isArray(c))?0>c.indexOf("container")&&c.push("container"):c.container||(c.container=a.U);for(var f in c){e=c[f];if(d)f=e;else if(e.match(/^[0-9]+$/)){var h=+e;a.W[f]=[];
do{e=f+h++;e=document.getElementById(e);if(!e)break;a.W[f].push(e)}while(1);continue}(h=document.getElementById(e))&&a.xa(f,h)}}b=void 0===b?{}:b;a.version=3;if(a.version){f="";var k;a.N!=a.U&&(k=O(a,a.N).version)&&k!=a.version&&(f="Machine");f||(k=b.version)&&k>a.version&&(f="Config");f&&(k=a.u("%s Device version (%3.2f) incompatible with %s version (%3.2f)",b.Me,a.version,f,k),a.error("%s\n\nClearing your browser's cache may resolve the issue.",k))}}
function mb(a,b){var c;try{var d=D[a.N];if(d)for(c in d){var e=d[c];if(e.U!=e.N&&!b(e))return!1}return!0}catch(g){a.s("error while enumerating device '%s': %s\n",c,g.message)}return!1}n.ta=function(a,b){b=void 0===b?!1:b;if(a){var c=I.prototype.ta.call(this,a,b);if(void 0===c&&b){b=D[this.N];for(var d in b)if(c=b[d].W[a])break;c||(c=null);this.W[a]=c}}return c};
function O(a,b,c){var d=b,e=a.N,g=e.indexOf(".");0<g&&(e=e.substr(0,g),b=b.substr(g+1));b=(g=D[e])&&g[b]||null;if(!b){for(g=0;g<ra.length;g++)if(ra[g].id===d){b=ra[g];break}if(!b&&(void 0===c||c))throw Error(a.u('no "%s" device',d));}return b}function P(a,b,c){var d=null,e=D[a.N];if(e)for(var g in e)if(e[g].m["class"]==b){if(d){d=null;break}d=e[g]}if(!d&&(void 0===c||c))throw Error(a.u("no %s device",b));return d}function nb(a,b){var c=O(a,a.N);return c&&c.m&&c.m[b]||a.m[b]}
function ob(a,b){return(a=a.Oa[b])&&a.get()}function pb(a){return a==a.I&&a.ready?mb(a,function(b){return pb(b)}):a.ready}function qb(a,b){b=void 0===b?a.ready:b;a.ready=b;if(pb(a)){for(;b=a.Tb.pop();)b();a!=a.I&&qb(a.I)}}function rb(a,b){if(pb(a))return b(),!0;a.Tb.push(b);return!1}n.nc=function(){};
n.s=function(a){var b=la.apply(1,arguments);return"number"==typeof a&&Ua(this,a)&&(void 0===this.Z&&(this.Z=P(this,"Debugger",!1)),this.Z&&this.Z.nc(a),this.I.ga&1&&(void 0===this.T&&(this.T=P(this,"CPU")),this.T))?(a=b.shift(),I.prototype.s.call(this,"%#06x: %s.%s\n",this.T.ob,this.U,this.u.apply(this,[a].concat(r(b))).trim())):I.prototype.s.call.apply(I.prototype.s,[this,a].concat(r(b)))};function sb(a,b){(a=D[a.N])&&delete a[b]}function tb(a,b,c){(a=a.Oa[b])&&a.set&&a.set(c)}E.Device=N;
function ub(a,b,c){N.call(this,a,b,c);this.ga=2097152;this.$=this.M=null;this.time=P(this,"Time");this.I=P(this,"Machine");this.da=J(this,"drag",!1);this.X=J(this,"scroll",!1);this.ca=J(this,"hexagonal",!1);this.l=J(this,"releaseDelay",0);this.o=!1;a=this.m.map;this.h=this.j=null;if(a)if(a.length)this.h=a;else{this.j={};b=Object.keys(a);for(var d=0;d<b.length;d++){var e=[],g=b[d],f=a[g];"string"==typeof f?f=[f]:void 0==f.length&&(e=f.grid,f=f.keys,"string"==typeof f&&(f=[f]));this.j[g]={keys:f,grid:e,
state:0}}}this.R=[];this.S=[];this.H=!1;this.i=this.J=null;(a=this.W[vb])&&wb(this,a,this.ta(c.focusBinding,!0),this.m.location);this.ma()}z(ub,N);function xb(a,b){a.M=b}function yb(a,b,c){for(var d=0;d<a.R.length;d++){var e=a.R[d];e.id===b&&e.Ua(b,c)}}
function wb(a,b,c,d){d=void 0===d?[]:d;if(d.length||a.h||a.j){var e={};e.vd=d[0]||0;e.wd=d[1]||0;e.Ha=d[2]||b.clientWidth;e.Sa=d[3]||b.clientHeight;e.Va=d[4]||1;e.ab=d[5]||1;e.kd=d[6]||b.naturalWidth||e.Ha;e.md=d[7]||b.naturalHeight||e.Sa;e.qc=d[8]||0;e.rc=d[9]||0;e.jd=d[10]||0;e.ld=d[11]||0;a.h?(e.Xa=a.h.length,e.Ia=a.h[0].length):(e.Ia=e.Va,e.Xa=e.ab,e.Va=e.ab=0);e.kc=e.Ha/(e.Ia+e.Ia*e.Va)|0;e.lc=e.Sa/(e.Xa+e.Xa*e.ab)|0;e.hd=e.kc*e.Va|0;e.mc=e.lc*e.ab|0;e.Ka=e.bb=-1;zb(a,b,e);Ab(a,b,e);a.time&&
a.l&&(a.Y=Bb(a.time,"timerInputRelease",function(){0>e.Ka&&0>e.bb&&Cb(a,-1,-1)}))}if(a.h||a.j)a.time&&a.l&&(a.fa=Bb(a.time,"timerKeyRelease",function(){Db(a)})),a.v=0,a.L="",a.K=[],d=b,c&&(d=c,a.i||"BUTTON"!=c.nodeName||(d=document,a.i=c,Eb(a,b),a.J=b)),Eb(a,d),a.i||(a.i=d)}function Fb(a){a.l?Gb(a.time,a.fa,a.l):Db(a)}
function Eb(a,b){function c(e,g,f){var h=document.activeElement;a.s(5242880,"%s.onKey%s(%d): %5.2f (%s)\n",h.id||h.nodeName,e,g,Date.now()/1E3%60,void 0!=f?f?"used":"unused":"ignored")}function d(e,g){e=document.activeElement;return a.i&&e!=a.i&&e!=a.J?null:g||window.event}b.addEventListener("keydown",function(e){if(e=d(this,e)){var g=e.which||e.keyCode,f=Hb(a,g,!0,e);c("Down",g,f);f&&e.preventDefault()}});b.addEventListener("keypress",function(e){if(e=d(this,e)){var g=e.which||e.charCode,f=Hb(a,
g);c("Press",g,f);f&&e.preventDefault()}});b.addEventListener("keyup",function(e){if(e=d(this,e)){var g=e.which||e.keyCode,f=Hb(a,g,!1,e);c("Up",g);f&&e.preventDefault();"TEXTAREA"==b.nodeName&&(b.value="")}})}
function zb(a,b,c){b.addEventListener("mousedown",function(d){if(!a.o){var e=a.H?a.J:a.i;if(e){var g=window.scrollX,f=window.scrollY;e.focus();window.scrollTo(g,f)}d.button||Q(a,b,Ib,d,c)}});b.addEventListener("mousemove",function(d){a.o||Q(a,b,Jb,d,c)});b.addEventListener("mouseup",function(d){a.o||d.button||Q(a,b,Kb,d,c)});b.addEventListener("mouseout",function(d){a.o||(0>c.Ka?Q(a,b,Jb,d,c):Q(a,b,Kb,d,c))})}
function Ab(a,b,c){b.addEventListener("touchstart",function(d){a.X&&(a.o=!0);Q(a,b,Ib,d,c)});b.addEventListener("touchmove",function(d){Q(a,b,Jb,d,c)});b.addEventListener("touchend",function(d){Q(a,b,Kb,d,c)})}
function Hb(a,b,c,d){if(void 0!=c){var e=hb[b]||b;var g=jb[b];var f=Lb[e];d=d&&d.location==ib.gb;f&Mb&&d&&(f>>=1);f&&(f&Nb&&(c=!(a.g&f)),a.g=c?a.g|f:a.g&~f,yb(a,e,c))}else g=String.fromCharCode(b).toUpperCase(),b>=fb.cb&&b<=fb.hb?a.g&(Ob|Pb)||(a.g|=Pb,yb(a,L.fb,!0)):b>=fb.a&&b<=fb.z&&a.g&Pb&&(a.g&=~Pb,yb(a,L.fb,!1));if(a.h){if(void 0!=c)return!1;for(e=0;e<a.h.length;e++)for(f=a.h[e],d=0;d<f.length;d++)if(0<=f[d].split("|").indexOf(g))return a.v?16>a.K.length&&a.K.push(b):(a.v=1,a.L=g,Cb(a,d,e),yb(a,
g,!0),Fb(a)),!0}if(a.j){if(void 0==c)return!0;b=Object.keys(a.j);for(e=0;e<b.length;e++)if(f=b[e],0<=a.j[f].keys.indexOf(g))return yb(a,f,c),a.j[f].state=c?1:0,!0}return!1}function Db(a){1==a.v?(a.v++,yb(a,a.L,!1),a.L="",Cb(a,-1,-1),Fb(a)):(a.v=0,a.K.length&&Hb(a,a.K.shift()))}ub.prototype.ma=function(){this.g=0;this.V=this.aa=-1};
function Q(a,b,c,d,e){var g=-1,f=-1,h=!1,k=-1,p=-1;if(c<Kb){d=d||window.event;d.targetTouches&&d.targetTouches.length?(k=d.targetTouches[0].clientX,p=d.targetTouches[0].clientY,h=1<d.targetTouches.length):(k=d.clientX,p=d.clientY);var l=d.target.getBoundingClientRect();k-=l.left;p-=l.top;k=e.kd/b.offsetWidth*k|0;p=e.md/b.offsetHeight*p|0;var u=k-e.vd;var m=p-e.wd;var q=l=!1;var v=k>=e.qc&&k<e.qc+e.jd&&p>=e.rc&&p<e.rc+e.ld;if(0<=u&&u<e.Ha&&0<=m+e.mc||v)if(h||a.X||d.preventDefault(),0<=u&&u<e.Ha&&0<=
m&&m<e.Sa){q=!0;d=e.Ha/e.Ia|0;var t=e.Sa/e.Xa|0,x=u/d|0,y=m/t|0;!a.ca||y&1||(u-=d>>1,x=u/d|0,x==e.Ia-1&&(u=-1));t=y*t+(e.mc>>1);u-=x*d+(e.hd>>1);m-=t;0<=u&&u<e.kc&&0<=m&&m<e.lc&&(g=x,f=y,l=!0)}}u=u||0;m=m||0;d=b.offsetWidth;b=b.offsetHeight;if(c==Ib||c==Kb)for(x=0;x<a.S.length;x++)y=a.S[x],c==Kb?y.Ua(y.id,!1):(t=m/(b/y.Oe|0)|0,(u/(d/y.Ne|0)|0)==y.df&&t==y.ef&&y.Ua(y.id,!0));if(!h)if(c==Ib)e.Ka=k,e.bb=p,q?(Cb(a,g,f),l&&a.l&&Gb(a.time,a.Y,a.l,!0)):v&&a.I.ja();else if(c==Jb)0<=e.Ka&&0<=e.bb&&a.da?Cb(a,
g,f):a.M&&a.M(g,f);else if(c==Kb){if(c=a.l)c=a.time,g=a.Y,c=c.g&&0<g&&g<=c.h.length?0<=c.h[g-1].ia:!1;c||Cb(a,-1,-1);e.Ka=e.bb=-1}else a.s("unrecognized action: %d\n",c)}function Qb(a){var b=a.H?a.J:a.i;b&&pb(a.I)&&(a.s(2097152,'setFocus("%s")\n',b.id||b.nodeName),b.focus(),b.scrollIntoView())}function Cb(a,b,c){if(b!=a.V||c!=a.aa)a.V=b,a.aa=c,a.$&&a.$(b,c)}
var Ib=1,Jb=2,Kb=3,vb="surface",Ob=3,Mb=170,Pb=512,Nb=3584,R={},Lb=(R[L.Sc]=2,R[L.vc]=8,R[L.sc]=32,R[L.yb]=128,R[L.fb]=Pb,R[L.Ic]=1024,R[L.Pc]=2048,R);E.Input=ub;
function Rb(a,b,c){N.call(this,a,b,c,["color","backgroundColor"]);a=this.W[Sb];if(!a)throw Error("LED "+this.m.W[Sb]+" binding for '"+Sb+"' missing");b=document.createElement("canvas");if(!b||!b.getContext)throw a.innerHTML="LED device requires HTML5 canvas support",Error("LED device requires HTML5 canvas support");this.Aa=Na(this,Sb)+".canvas";b.setAttribute("id",this.Aa);this.type=Qa(J(this,"type",Tb,Ub),Vb,Wb);this.j=Xb[this.type][0];this.H=Xb[this.type][1];this.width=J(this,"width",this.j);this.height=
J(this,"height",this.H);this.l=J(this,"cols",1);this.M=this.l+J(this,"colsExtra",0);this.Y=J(this,"rows",1);this.R=this.Y+J(this,"rowsExtra",0);this.da=this.width*this.l;this.$=this.height*this.Y;this.v=Yb("black",0);this.i=Zb(this.m.color)||this.v;this.qa=Yb(this.i,1,.25);this.oa=Yb(this.i,1,2);this.o=Zb(this.m.backgroundColor);this.ra=J(this,"fixed",!1);this.ra||(b.style.width="100%",b.style.height="auto");this.na=J(this,"hexagonal",!1);this.sa=J(this,"highlight",!0);this.X=J(this,"persistent",
this.type<Wb);b.setAttribute("width",this.da.toString());b.setAttribute("height",this.$.toString());b.style.backgroundColor=this.v;a.appendChild(b);this.fa=b.getContext("2d");if(this.J=document.createElement("canvas"))this.J.width=this.ca=this.j*this.l,this.J.height=this.K=this.H*this.Y,this.g=this.J.getContext("2d");this.Qa=(this.R+1)*this.M*4;this.h=Array(this.Qa);this.Ra=this.l<this.M?4*(this.M-this.l):0;this.S=this.V=!1;this.L=this.aa=0;this.ha=-1;var d=this;this.time=P(this,"Time");$b(this.time,
function(e,g){ac(d,!1,e,g)});bc(d)}z(Rb,N);function bc(a){for(var b=a.h,c=0;c<b.length;c+=4){var d=a,e=b,g=c;e[g]=d.type<Wb?cc:" ";e[g+1]=d.i==d.v?null:d.i;e[g+2]=0;e[g+3]=dc}a.S=a.V=!0;ac(a,!0)}function ec(a){a.o?(a.g.fillStyle=a.o,a.g.fillRect(0,0,a.ca,a.K)):a.g.clearRect(0,0,a.ca,a.K)}
function ac(a,b,c,d){b=void 0===b?!1:b;c=void 0===c?0:c;d=void 0===d?60:d;if(a.S||b){if(a.type<Wb){d=0;if(!a.X||b)ec(a);else if(a.L){d=a.l-a.L;var e=a.j*d;a.g.drawImage(a.J,a.j*a.L,0,e,a.K,0,0,e,a.K)}for(var g=e=0;g<a.R;g++){for(var f=0;f<a.l;f++){var h=a.h[e],k=a.h[e+1]||a.v,p=a.sa&&e==a.ha;if(a.h[e+3]&dc||p||b){if(f>=d)a:{var l=a,u=h;h=k;var m=f;k=g;var q=p;m=void 0===m?0:m;k=void 0===k?0:k;q=void 0===q?!1:q;var v=0;if(l.na&&!(k&1)&&(v=l.j>>1,m==l.l-1))break a;if(h&&h!=l.i){q=q?Yb(h,1,2):h;var t=
Yb(h,1,.25)}else q=q?l.oa:l.i,t=l.qa;h=!1;u=u?q:t;q==l.v&&(u=l.o,h=!0);q=m*l.j+v;t=k*l.H;l.X&&(m=m*l.j+v,k*=l.H,l.o?(l.g.fillStyle=l.o,l.g.fillRect(m,k,l.j,l.H)):l.g.clearRect(m,k,l.j,l.H));l.g.fillStyle=u;k=fc[l.type];3==k.length?(l.g.beginPath(),l.g.arc(q+k[0],t+k[1],k[2],0,2*Math.PI),h?(l.g.globalCompositeOperation="destination-out",l.g.fill(),l.g.globalCompositeOperation="source-over"):l.g.fill()):l.g.fillRect(q+k[0],t+k[1],k[2],k[3])}a.h[e+3]=p?a.h[e+3]|dc:a.h[e+3]&~dc}e+=4}e+=a.Ra}a.L=0}else{b=
"";for(d=0;d<a.h.length;d+=4)b+=a.h[d]||" ",a.h[d+3]&gc&&(b+=".");ec(a);for(g=e=d=0;d<b.length;d++){k=b[d];"."==k&&e&&e--;f=a;p=e;l=g;p=void 0===p?0:p;l=void 0===l?0:l;if(k=hc[k])for(h=0;h<k.length;h++)if(m=f,v=ic[k[h]]){u=(void 0===p?0:p)*m.j;q=(void 0===l?0:l)*m.H;m.g.fillStyle=m.i;m.g.beginPath();if(3==v.length)m.g.arc(u+v[0],q+v[1],v[2],0,2*Math.PI);else for(t=0;t<v.length;t+=2)t?m.g.lineTo(u+v[t],q+v[t+1]):m.g.moveTo(u+v[t],q+v[t+1]);m.g.closePath();m.g.fill()}if(++e==a.l&&(e=0,++g==a.R))break}}a.fa.globalCompositeOperation=
a.o&&a.i!=a.v?"source-over":"copy";a.fa.drawImage(a.J,0,0,a.ca,a.K,0,0,a.da,a.$);a.S=!1;a.ha=-1}else a.X||a.V||(!c||!a.aa||c-a.aa>=(1E3/d|0))&&bc(a);a.V=!1;c&&(a.aa=c)}function Zb(a){return(a=a||void 0)&&kb[a]||a}
function Yb(a,b,c){b=void 0===b?1:b;c=void 0===c?1:c;if(a){var d=[];a=kb[a]||a;var e=16;var g=a.match(/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i);g||(e=10,g=a.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,?\s*(\d+|)\)$/i));if(g){var f;for(f=1;f<g.length;f++)d[f-1]=Number.parseInt(g[f],e);d.length=f-1;e=!0}else e=!1;if(e){a="rgba(";for(e=0;3>e;e++)g=Math.round(d[e]*c),g=0>g?0:255<g?255:g,a+=g+",";a+=(e<d.length?d[e]:b)+")"}}return a}
Rb.prototype.ua=function(a){var b=a.shift(),c=a.shift();a=a.shift();if(b==this.i&&c==this.o&&a&&a.length==this.h.length){this.h=a;for(b=0;b<=this.h.length-4;b+=4)this.h[b+1]==this.v&&(this.h[b+1]=null);ac(this,!0);return!0}return!1};Rb.prototype.wa=function(a){this.h&&(a.push(this.i),a.push(this.o),a.push(this.h))};
var Vb=0,Tb=1,Wb=3,Ub={small:Vb,round:Tb,square:2,digit:Wb},Sb="container",cc=0,gc=1,dc=128,jc={},fc=(jc[Vb]=[4,4,4],jc[Tb]=[16,16,14],jc[2]=[2,2,28,28],jc),Xb=[[8,8],[32,32],[32,32],[96,128]],ic={A:[30,8,79,8,67,19,37,19],B:[83,10,77,52,67,46,70,22],C:[77,59,71,100,61,89,64,64],D:[28,91,58,91,69,104,15,104],E:[18,59,28,64,25,88,12,100],F:[24,10,34,21,31,47,18,52],G:[24,56,34,50,60,50,71,56,61,61,33,61],P:[80,102,8]},hc={" ":[],0:"ABCDEF".split(""),1:["B","C"],2:["A","B","D","E","G"],3:["A","B","C",
"D","G"],4:["B","C","F","G"],5:["A","C","D","F","G"],6:"ACDEFG".split(""),7:["A","B","C"],8:"ABCDEFG".split(""),9:"ABCDFG".split(""),A:"ABCEFG".split(""),B:["C","D","E","F","G"],C:["A","D","E","F"],D:["B","C","D","E","G"],E:["A","D","E","F","G"],F:["A","E","F","G"],"-":["G"],".":["P"]};E.LED=Rb;
function S(a,b,c){N.call(this,a,b,c);var d=this;this.ca=this.m.touchType;this.$=this.m.diagnostics;this.H=this.m.monitorWidth||640;this.o=this.m.monitorHeight||480;this.i=this.W[T.Ob];if(!this.i)throw Error("unable to find binding: "+T.Ob);this.g=this.ta(T.uc)||this.i;b=this.W[T.Xb];if(!b){b=document.createElement("canvas");if(a=Na(this,T.Xb))this.W[a]=b,b.setAttribute("id",a);b.setAttribute("class","pcjs-surface");b.setAttribute("width",this.m.monitorWidth);b.setAttribute("height",this.m.monitorHeight);
b.style.backgroundColor=this.m.monitorColor||"black";this.i.appendChild(b)}this.j=b;this.v=a=b.getContext("2d");Va("MSIE")&&(this.i.onresize=function(f,h,k,p){return function(){h.style.height=(f.clientWidth*p/k|0)+"px"}}(this.i,b,this.m.monitorWidth,this.m.monitorHeight),this.i.onresize());(c=+(this.m.aspect||Sa().aspect))&&.3<=c&&3.33>=c&&(Ya(function(f,h,k){return function(){h.style.height=(f.clientWidth/k|0)+"px"}}(this.i,b,c)),window.onresize());this.K=this.J=this.I.La=!1;if(c=this.W[T.Eb])if(b=
La(this.g,"requestFullscreen")){this.g.Ta=this.g[b];this.K=!0;this.J=document.fullscreenEnabled||Va("Edge/");if(b=La(document,"on","fullscreenchange")){var e=La(document,"fullscreenElement");document.addEventListener(b,function(){kc(d,null!=document[e])},!1)}(b=La(document,"on","fullscreenerror"))&&document.addEventListener(b,function(){kc(d)},!1)}else this.s("Full-screen API not available\n"),c.parentNode.removeChild(c);if(this.ca||this.$||this.K&&!Va("iOS")){var g=document.createElement("textarea");
if(b=Na(this,T.Jc))this.W[b]=g,g.setAttribute("id",b);g.setAttribute("class","pcjs-overlay");Va("iOS")&&(Ha(g),g.style.fontSize="16px");this.i.appendChild(g)}(this.l=P(this,"Input",!1))&&wb(this.l,g||this.i,this.ta(this.m.focusBinding,!0));Sa();if(this.h=this.m.monitorRotate)this.h=this.h%360,0<this.h&&(this.h-=360),-90!=this.h?(this.s("unsupported monitor rotation: %d\n",this.h),this.h=0):(a.translate(0,this.o),a.rotate(this.h*Math.PI/180),a.scale(this.o/this.H,this.H/this.o))}z(S,N);
S.prototype.xa=function(a,b){var c=this;switch(a){case T.Eb:b.onclick=function(){c.I.La=1>=window.outerHeight-window.innerHeight;c.I.La||c.Ta()}}N.prototype.xa.call(this,a,b)};function lc(a){a.v&&(a.v.fillStyle="black",a.v.fillRect(0,0,a.j.width,a.j.height))}
S.prototype.Ta=function(){var a=!1;if(this.g&&this.g.Ta){a="100%";if(screen&&screen.width&&screen.height){var b=screen.width/screen.height,c=this.H/this.o;b>c&&(a=Math.round(c/b*100)+"%")}this.J?(this.j.style.width=a,this.j.style.height="auto",this.j.style.display="block",this.j.style.margin="auto"):(this.g.style.width=a,this.g.style.height="auto");this.L=this.g.style.backgroundColor;this.g.style.backgroundColor="black";this.g.Ta();this.l&&(a=this.l,a.H=!0,Qb(a));a=!0}return a};
function kc(a,b){a.I.La=!0;b||(a.g&&(a.J?a.j.style.width=a.j.style.height="":a.g.style.width=a.g.style.height="",a.L&&(a.g.style.backgroundColor=a.L)),a.I.La=!1);a.l&&!b&&(a=a.l,a.H=!1,Qb(a))}S.prototype.ja=function(a){a?this.aa=!1:lc(this)};S.prototype.ma=function(){lc(this)};var T={uc:"container",Xb:"surface",Ob:"monitor",Jc:"overlay",Eb:"fullScreen"};E.Monitor=S;
function mc(a,b,c){N.call(this,a,b,c);this.sa=J(this,"cyclesMinimum",1E5);this.Yb=J(this,"cyclesMaximum",1E9);this.ha=Qa(J(this,"cyclesPerSecond",1E6),this.sa,this.Yb);this.da=60;this.$=0;this.aa=1E3/this.da;this.$b=J(this,"updatesPerSecond",2)||2;this.ad=1E3/this.$b;this.Ra=0;this.bd=J(this,"timeLock",!0);this.ra=this.M=0;this.qa=this.l=1;this.Qa=this.v=this.ha/1E4/100;this.na=[];this.K=[];this.h=[];this.V=[];this.Aa=this.g=this.X=this.J=!1;this.L=this.j=0;a=La(window,"requestAnimationFrame");if(!a){a=
"setTimeout";var d=this.aa}this.bc=window[a].bind(window,this.sd.bind(this),d);this.$c=window[La(window,"cancelAnimationFrame")||"clearTimeout"].bind(window);this.ca=this.Y=this.o=this.i=this.fa=0;nc(this)||oc(this,this.qa)}z(mc,N);function $b(a,b){a.na.push(b)}n=mc.prototype;
n.xa=function(a,b){var c=this;switch(a){case pc:b.onclick=function(){qc(c)&&(c.g?rc(c):c.start())};break;case sc:b.onclick=function(){oc(c,c.l<<1);tc(c,uc(c.v))};break;case vc:b.onclick=function(){wc(c)};break;case xc:b.addEventListener("mousedown",function(){c.J=!0}),b.addEventListener("mouseup",function(){nc(c);c.J=!1}),b.addEventListener("mousemove",function(){c.J&&nc(c)}),b.addEventListener("change",function(){c.J=!0;nc(c);c.J=!1})}N.prototype.xa.call(this,a,b)};
function Bb(a,b,c){var d=void 0===d?-1:d;var e=a.h.length+1;a.h.push({id:b,cd:c,Wa:d,ia:-1});0<=d&&Gb(a,e,d);return e}
function zc(a,b,c,d){var e=0,g=a.v,f=1E6*g;b&&c&&(g=b/(10*c)/100,a.s(262144,"calcSpeed(%d cycles, %5.3fms): %5.3fMhz\n",b,c,g),d>a.aa&&(1<a.l&&(a.l>>=1,a.s(549755813888,"frame time (%5.3fms) exceeded maximum (%5.3fms), target multiplier now %d\n",d,a.aa,a.l)),e=d));a.M=g;a.ra=g/a.Qa;b=a.ra/a.l;a.fa=f/b/a.da+1E-8;a.s(262144,"nCyclesDepositPerFrame(%5.3f) = nCyclesPerSecond(%d) / nDivisor(%5.3f) / nFramesPerSecond(%d)\n",a.fa,f,b,a.da);return e}
function Ac(a,b){a.Y=a.o=b;if(!a.K.length)return a.o=0,a.Y;for(var c=0;0<a.o;){if(c<a.K.length){var d=a.K[c++];b=d.td.call(d,b)||1}else c=b=0;a.o-=b}return a.Y-a.o}function Bc(a,b){b=void 0===b?a.Y-a.o:b;if(!a.g){if(a.i)for(var c=0;c<a.K.length;c++){var d=a.K[c];d.ud.call(d)}a.i=b}a.i-=b;1>a.i&&(a.X=!0);a.ca+=b;a.Y=a.o=0;a.g||(a.ca=0);return b}
function Cc(a,b){b=void 0===b?0:b;if(b){var c=b;a.i+=b}else for(c=a.i,1>c&&(c=a.i+=a.fa),0>c&&(a.s(262144,"warning: cycle count dropped below zero: %f\n",c),c=a.i=0),c|=0,b=a.h.length;0<b;b--){var d=a.h[b-1];!(0>d.ia)&&c>d.ia&&(c=d.ia)}return c}function uc(a){1<=a?a=a.toFixed(2)+"Mhz":(a=Math.round(1E6*a),a=999>=a?a+"Hz":Math.ceil(a/1E3)+"Khz");return a}function Dc(a){a.s(262144,"getSpeedCurrent(%5.3fhz)\n",1E6*a.M);return a.g&&a.M?uc(a.M):"Stopped"}
function qc(a){return a.Aa?!0:(a.s("not powered\n"),!1)}function Ec(a,b){if(1<=b)for(var c=a.h.length;0<c;c--){var d=a.h[c-1];0>d.ia||(d.ia-=b,0>=d.ia&&(d.ia=-1,d.cd(),0<=d.Wa&&Gb(a,c,d.Wa)))}}n.ja=function(a){this.Aa=a;void 0===this.Z&&(this.Z=P(this,"Debugger",!1))&&this.Z.ib(this,"time","dump time state",this.qd)};function wc(a,b){qc(a)&&(a.g?a.s("already running\n"):a.j?rc(a):Fc(a,b))}
n.sd=function(a){a=void 0===a?Date.now():a;this.L=0;if(this.g){if(this.$){var b=a-this.$;1>b&&(b=16.67);this.da=1E3/b}this.$=a;a=Date.now();this.R&&(b=a-this.S-this.aa,b>this.aa&&(this.H+=b,this.s(549755813888,"browser throttling detected, compensating by %5.3fms\n",b)));this.S=a;this.H||(this.H=a);this.oa=0;try{this.X=!1;do Ec(this,Bc(this,Ac(this,Cc(this))));while(this.g&&!this.X)}catch(c){this.s("%s\n",c.message),rc(this)}this.R=Date.now();this.oa&&(this.H+=this.oa,this.S+=this.oa);this.S+=zc(this,
this.ca,this.R-this.H,this.R-this.S);this.R-this.Ra>=this.ad&&this.update();for(a=0;a<this.na.length;a++)this.na[a](this.$,this.da);this.L=this.bc()}};function oc(a,b){if(void 0!==b){if(1>b||!a.J&&0<a.M&&a.M<.9*a.v)b=a.qa;a.l=b;b=a.Qa*a.l;a.v!=b&&(a.v=b,tc(a,uc(a.v)))}a.H=a.R=0;a.i=a.ca=0;zc(a);for(b=a.h.length;0<b;b--){var c=a.h[b-1];0<=c.Wa&&Gb(a,b,c.Wa,!0)}}function nc(a){var b=a.W[xc];return b?(oc(a,Math.floor((b.value-b.min)/(b.max-b.min)*(a.Yb-a.sa)+a.sa)/a.ha|0),!0):!1}
function Gb(a,b,c,d){0<b&&b<=a.h.length&&(b=a.h[b-1],d||0>b.ia)&&(c=Math.ceil(a.ha*(a.bd?a.qa:a.ra)/1E3*(void 0===c?1E3:c)),a.g&&(c+=Bc(a)),b.ia=c)}n.start=function(){if(this.g||this.j)return!1;this.g=!0;this.H=this.R=this.$=0;this.update(!0);this.L=this.bc();return!0};function Fc(a,b){b=void 0===b?1:b;a.g||(b&&!a.j&&(a.j=b),a.j&&(a.j--,Ec(a,Bc(a,Ac(a,Cc(a,1)))),a.update(!1),a.j&&setTimeout(function(){Fc(a,0)},0)))}
function rc(a){return a.g?(a.g=!1,Bc(a),a.L&&(a.$c(a.L),a.L=0),a.update(!0),!0):a.j?(a.j=0,a.update(!0),!0):!1}n.update=function(a){a&&this.s(this.g?"started with %s target\n":"stopped\n",uc(this.v));eb(this,pc,this.g?"Halt":"Run");eb(this,vc,this.j?"Stop":"Step");this.J||tc(this,Dc(this));for(var b=0;b<this.V.length;b++){var c=this.V[b];c.oc.call(c,void 0!=a)}this.Ra=Date.now();this.X=!0};function tc(a,b){eb(a,Gc,b);eb(a,sc,b)}
n.qd=function(){var a=this.u("nCyclesPerSecond: %f\n",this.ha);a+=this.u("nUpdatesPerSecond: %f\n",this.$b);a+=this.u("nTargetMultiplier: %f\n",this.l);return a+=this.u("nCyclesDepositPerFrame: %f\n",this.fa)};var pc="run",sc="setSpeed",Gc="speed",vc="step",xc="throttle";E.Time=mc;
function Hc(a,b,c){N.call(this,a,b,c);this.type="static"==this.m.type?Ic:Jc;this.ba=this.m.addrWidth||16;this.j=Math.pow(2,this.ba);this.v=this.j-1|0;this.blockSize=this.m.blockSize||(16<this.ba?4096:1024);this.blockSize>this.j&&(this.blockSize=this.j);this.H=this.j/this.blockSize|0;this.h=Math.log2(this.blockSize)|0;this.l=(1<<this.h)-1;this.i=this.m.dataWidth||8;this.g=Array(this.H);this.o=0;a=new U(a,b+"[NONE]",{size:this.blockSize,bus:this.U});for(b=0;b<this.j;b+=this.blockSize)Kc(this,b,this.blockSize,
V.NONE,a);Lc(this,this.type)}z(Hc,N);function Kc(a,b,c,d,e){for(var g=b>>>a.h;0<c&&g<a.g.length;){var f=g*a.blockSize,h=a.blockSize-(b-f);h>c&&(h=c);var k=a.g[g];if(b!=f||h!=a.blockSize||k&&k.type!=V.NONE)break;k=a.U+"["+F(a,b,16,a.ba)+"]";b=e?e.size==a.blockSize?e:new U(a.N,k,{type:d,ya:b,size:h,bus:a.U}):new U(a.N,k,{type:d,ya:b,size:h,bus:a.U});a.g[g]=b;b=f+a.blockSize;c-=h;g++}}function Mc(a,b){for(var c=V.Oc,d=0,e=0;e<a.g.length;e++){var g=a.g[e];g&&g.type&c&&(b(g),d++)}return d}n=Hc.prototype;
n.Pe=function(a,b){this.Z&&this.Z.s(4,"bus fault (%d) at %n\n",b,a)};n.ja=function(){void 0===this.Z&&(this.Z=P(this,"Debugger",!1))};n.ma=function(){};n.mb=function(a){return a&&this.ua(a)?!0:!1};n.Ja=function(a){this.wa(a)};n.ua=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==Jc||c.type&V.Ea)&&c.ua){var d=a.shift();if(!c.ua(d))return!1}}return!0};
n.wa=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if((this.type==Jc||c.type&V.Ea)&&c.wa){var d=[];c.wa(d);a.push(d)}}};n.nb=function(a){return this.g[a>>>this.h].nb(a&this.l)};n.tb=function(a,b){this.g[a>>>this.h].tb(a&this.l,b)};n.Ba=function(a,b){this.g[a>>>this.h].pa(a&this.l,b)};function Lc(a,b){var c=a.o;a.o+=b;c&&a.o||(a.pa=a.Ba)}n.Za=function(a,b){return this.g[a>>>this.h].Za(b)?(Lc(this,1),!0):!1};n.qb=function(a,b){return this.g[a>>>this.h].qb(b)?(Lc(this,1),!0):!1};
n.$a=function(a,b){return this.g[a>>>this.h].$a(b)?(Lc(this,-1),!0):!1};n.sb=function(a,b){return this.g[a>>>this.h].sb(b)?(Lc(this,-1),!0):!1};var Ic=0,Jc=1;E.Bus=Hc;
function U(a,b,c){N.call(this,a,b,c);this.ya=this.m.addr;this.size=this.m.size;this.type=this.m.type||V.NONE;this.h=(a=this.m.bus)?O(this,a):P(this,a="Bus");if(!this.h)throw Error(this.u("unable to find bus '%s'",a));this.R=this.h.i;this.o=this.M=!1;this.values=this.l=null;a=this.Ba;this.h.type==Ic&&(a=this.ub,8==this.R&&!1!==nb(this,"ArrayBuffer")&&(this.M=!0));switch(this.type){case V.NONE:this.pa=this.pc;break;case V.Vb:this.pa=this.pc;break;case V.Ea:this.pa=a}this.v=this.i=0;this.j=this.K=this.H=
null;Nc(this,this.m.values);Oc(this)}z(U,N);function Nc(a,b){"string"==typeof b?(qb(a,!1),Ra(b,function(c,d,e,g){if(4==e)if(!g&&d){try{var f=JSON.parse(d);Nc(a,f.values)}catch(h){a.s("error (%s) parsing resource: %s\n",h.message,c)}qb(a,!0)}else a.s("error (%d) loading resource: %s\n",g,c)})):a.m.values=b}
function Oc(a,b){if(a.type>V.NONE&&(a.M?(a.l=new ArrayBuffer(a.size),new DataView(a.l,0,a.size),a.values=new Uint8Array(a.l,0,a.size),new Uint16Array(a.l,0,a.size>>1),new Int32Array(a.l,0,a.size>>2)):a.values=Array(a.size).fill(0),b))for(var c=0;c<b.length;c++)a.values[c]=b[c]}n=U.prototype;
n.ma=function(){if(this.m.values)a:{var a=this.h,b=this.ya,c=this.size,d=this.m.values,e=0,g=b&a.l;b>>>=a.h;c>d.length&&(c=d.length);for(;0<c&&b<a.g.length;){var f=a.g[b++];if(!f)break a;for(;0<c&&g<f.size;)f.Ba(g++,d[e++]),c--;g=0}}else this.type&V.Ea&&this.values&&this.values.fill(0)};n.nb=function(a){return this.values?this.values[a]:0};n.pc=function(){};n.tb=function(a,b){this.values&&(this.values[a]=b)};n.Ba=function(a,b){this.values[a]=b};
n.ub=function(a,b){this.values[a]=b;this.o=!0;this.i?this.j=this.Ba:this.pa=this.Ba};n.Za=function(a){return this.v?this.K==a?(this.v++,!0):!1:(this.v++,this.K=a,!0)};n.qb=function(a){if(!this.i){var b=this;this.i++;this.H=a;this.j=this.pa;this.pa=function(c,d){b.H(b.ya,c,d);b.j(c,d)};return!0}return this.H==a?(this.i++,!0):!1};n.$a=function(a){return this.v&&this.K==a?(--this.v||(this.K=null),!0):!1};n.sb=function(a){return this.i&&this.H==a?(--this.i||(this.pa=this.j,this.j=this.H=null),!0):!1};
n.ua=function(a){if(a){var b=a.shift();if(this.U==b){this.o=a.shift();a.shift();if(a=a.shift()){var c=this.size;c=void 0===c?0:c;if(a.length!=c){b=0;c=c?Array(c):[];for(var d=0;d<a.length-1;)for(var e=a[d++],g=a[d++];e--;)c[b++]=g;a=c}Oc(this,a)}return!0}}return!1};
n.wa=function(a){a.push(this.U);a.push(this.o);a.push(!1);if(this.values){var b=this.values;for(var c=0,d=0,e=[];c<b.length;){for(var g=b[c],f=c+1;f<b.length&&b[f]===g;)f++;e[d++]=f-c;e[d++]=g;c=f}b=e.length>=b.length?b:e}else b=this.values;a.push(b)};var V={NONE:1,Vb:2,Ea:4,Oc:14,Ke:12};E.Memory=U;function Pc(a,b,c){c.type=V.NONE;U.call(this,a,b,c);Kc(this.h,this.m.addr,this.m.size,V.Ea);rb(this,this.ma.bind(this))}z(Pc,U);E.RAM=Pc;
function Qc(a,b,c){c.type=V.Vb;U.call(this,a,b,c);Kc(this.h,this.m.addr,this.m.size,this.m.type,this);rb(this,this.ma.bind(this));this.T=this.Z=void 0;if(E.LED&&this.W[Rc]){var d=this;this.J=Math.pow(2,Math.ceil(Math.log2(this.values.length)/2));this.L=this.values.length/this.J|0;this.g=new Rb(a,b+"LEDs",{"class":"LED",bindings:{container:Na(this,Rc)},type:Tb,cols:this.J,rows:this.L,color:J(this,"colorROM","green"),backgroundColor:J(this,"backgroundColorROM","black"),persistent:!0}),bc(this.g);this.S=
new ub(a,b+"Input",{"class":"Input",location:[0,0,this.g.da,this.g.$,this.J,this.L],bindings:{surface:Na(this,Rc)}});this.V=Oa(this)||"";xb(this.S,function(e,g){if(d.T){var f=d.V;0<=e&&0<=g&&(e=g*d.J+e,f=d.T.af(d.ya+e,d.values[e]));eb(d,Pa,f)}})}}z(Qc,U);
Qc.prototype.ua=function(a){var b=!0,c=a.shift();if(c&&this.g){var d=c.length;this.g.h.length==d?(this.g.h=c,ac(this.g,!0)):(this.s("inconsistent saved LED state (%d), unable to load\n",d),b=!1)}a.length&&(d=(a=a.shift())&&a.length||-1,this.values.length==d?this.values=a:(this.s("inconsistent saved ROM state (%d), unable to load\n",d),b=!1));return b};Qc.prototype.ja=function(){void 0===this.T&&(this.T=P(this,"CPU"));void 0===this.Z&&(this.Z=P(this,"Debugger",!1))&&this.Z.jb&&this.Z.jb(this.m.symbols)};
Qc.prototype.wa=function(a){this.g&&(a.push(this.g.h),a.push(this.values))};var Rc="array",Pa="cellDesc";E.ROM=Qc;function Sc(a,b,c){c["class"]="CPU";N.call(this,a,b,c);this.Z=void 0;this.i=this.ob=0;this.time=P(this,"Time");this.time.K.push(this);this.time.V.push(this);this.h=this.g=0}z(Sc,N);Sc.prototype.abort=function(a){this.i=this.ob;this.s("%s\n",a.message);rc(this.time)};function Tc(a,b){a.Z=b;return a.Oa}Sc.prototype.td=function(a){this.h=this.g=void 0===a?0:a;return this.h-this.g};
Sc.prototype.ud=function(){this.h-=this.g;this.g=0};
function Uc(a,b,c){c["class"]="Debugger";N.call(this,a,b,c);var d=this;this.ea=this.m.defaultRadix||16;this.$=["(",")"];this.Qb("a",function(g,f,h,k,p){return F(d,p.O,d.ea,h)});this.Qb("n",function(g,f,h,k,p){return F(d,p,d.ea,h,0>f.indexOf("#")?"":void 0)});this.ha=this.K=0;this.M={};this.na=[];this.oa=[];this.T=P(this,"CPU");this.Oa=Tc(this.T,this);this.qa=P(this,"Input",!1);if(a=this.T.m.busMemory||this.m.busMemory){this.g=O(this,a);if(a=this.T.m.busIO||this.m.busIO)this.j=O(this,a,!1);this.j||
(this.j=this.g)}else this.g=this.j=P(this,"Bus");this.L=this.g.ba;this.Aa=Math.pow(2,this.L)-1|0;this.H=this.da=0;this.v=[];for(var e in W)this.v[W[e]]=[];this.o=[];this.o[W.ka]=this.g;this.o[W.Ga]=this.g;this.o[W.Ca]=this.j;this.o[W.Da]=this.j;this.l=[];this.l[W.ka]=this.fd.bind(this);this.l[W.Ga]=this.gd.bind(this);this.l[W.Ca]=this.dd.bind(this);this.l[W.Da]=this.ed.bind(this);this.i=[];this.R=void 0;this.X=null;this.aa=0;this.time=P(this,"Time");this.time.V.push(this);this.Y=0;this.J=[];this.V=
"";this.ib(this,"state","dump machine state",this.pd);this.ca=Vc();this.ra=Vc();this.fa=!1;this.S=0;this.h=[];Ja(this,this.rd.bind(this));(e=nb(this,"commands"))&&Xa(this,e)}z(Uc,N);n=Uc.prototype;n.ib=function(a,b,c,d){this.J.push({od:a,name:b,nd:c,Ua:d})};function Wc(a,b,c){for(var d,e=0;e<a.J.length;e++){var g=a.J[e];if(g.name==b){d=g.Ua.call(g.od,c);break}}return d}
n.jb=function(a){if(a&&a.length)for(var b=0;b<a.length-2;b+=3){var c=Xc(this,a[b]);if(c){var d=Yc[a[b+1]];if(d){c={address:c,type:d,name:a[b+2]};d=this.na;var e=c,g=Zc(d,e,this.ic);0>g&&d.splice(-(g+1),0,e);d=this.oa;e=Zc(d,c,this.jc);0>e&&d.splice(-(e+1),0,c)}}}};function Zc(a,b,c){var d=0,e=a.length,g=0;for(void 0===c&&(c=function(k,p){return k>p?1:k<p?-1:0});d<e;){var f=d+e>>1,h=void 0;h=c(b,a[f]);0<h?d=f+1:(e=f,g=!h)}return g?d:~d}n.ic=function(a,b){return a.name>b.name?1:a.name<b.name?-1:0};
n.jc=function(a,b){return a.address.O>b.address.O?1:a.address.O<b.address.O?-1:0};function $c(a,b,c){b=Zc(a.oa,{address:b,type:0,name:void 0},a.jc);if(0<=b&&(a=a.oa[b],!c||a.type==c))var d=a.name;return d}function ad(a,b,c,d){d=void 0===d?a.g:d;b.O=b.O+c&d.v}function Vc(a){a=void 0===a?0:a;var b=bd.Lc;return"number"==typeof a?{O:a,pb:-1,type:b}:{O:a.O,pb:a.pb,type:a.type}}
function Xc(a,b,c){if(b){var d=Vc();var e=0,g=b.charAt(e);switch(g){case "&":e++;break;case "#":e++;d.type=bd.Mc;break;case "%":e++,g=b.charAt(e),"%"==g?e++:d.type=bd.dc}g=b.indexOf(":",e);if(0<=g){var f=cd(a,b.substring(e,g),c);void 0==f?d=null:(d.pb=f,e=g+1)}d&&(b=cd(a,b.substring(e),c),void 0==b?d=null:d.O=b&a.Aa)}return d}function dd(a,b,c,d){d=void 0===d?a.g:d;a.H++;var e=d.nb(b.O);c&&ad(a,b,c,d);a.H--;return e}
function ed(a,b,c){if(32>=a.L)return b&c;b=X(a,b,0,!0);c=X(a,c,0,!0);return((b/G|0)&(c/G|0))*G+((b&c)>>>0)}function fd(a,b,c){if(32>=a.L)return b^c;b=X(a,b,0,!0);c=X(a,c,0,!0);return((b/G|0)^(c/G|0))*G+((b^c)>>>0)}
function gd(a,b,c,d){for(d=void 0===d?-1:d;d--&&c.length;){var e=c.pop();if(2>b.length)return!1;var g=b.pop();var f=b.pop();switch(e){case "*":f*=g;break;case "/":if(!g)return!1;f=Math.trunc(f/g);break;case "^/":if(!g)return!1;f%=g;break;case "+":f+=g;break;case "-":f-=g;break;case "<<":f<<=g;break;case ">>":f>>=g;break;case ">>>":f>>>=g;break;case "<":f=f<g?1:0;break;case "<=":f=f<=g?1:0;break;case ">":f=f>g?1:0;break;case ">=":f=f>=g?1:0;break;case "==":f=f==g?1:0;break;case "!=":f=f!=g?1:0;break;
case "&":f=ed(a,f,g);break;case "!":case "|":e=f;32>=a.L?f=e|g:(e=X(a,e,0,!0),g=X(a,g,0,!0),f=(e/G|0|g/G|0)*G+((e|g)>>>0));break;case "^!":f=fd(a,f,g);break;case "&&":f=f&&g?1:0;break;case "||":f=f||g?1:0;break;case ",,":f=X(a,f,18,!0)*Math.pow(2,18)+X(a,g,18,!0);break;case "_":case "^_":"^_"==e&&(g=35-(g&255));g&&(f=X(a,f,0,!0),f=0<g?f*Math.pow(2,g):Math.trunc(f/Math.pow(2,-g)));break;default:return!1}b.push(X(a,f))}return!0}
function hd(a,b,c,d,e,g){var f,h=!1,k=0,p=[],l=[],u=a.ea;for(a.ea=e;c<d;){var m=b[c++].trim();var q=c<d?b[c++]:"";if(m){var v=void 0;var t=a;var x=m,y=g;k=void 0===k?0:k;if(void 0!=x){v=ob(t,x.toUpperCase());if(void 0==v){v=void 0;var B=t,yc=Zc(B.na,{address:null,type:0,name:x},B.ic);0<=yc&&(v=B.na[yc].address.O);if(void 0==v)if(v=x,t.M[v]?v=t.M[v].value:(v=v.substr(0,6),v=t.M[v]&&t.M[v].value),void 0==v)v=Aa(x,1<x.length||10<t.ea?t.ea:10);else if(x=t.M[x]&&t.M[x].Ye)y?y.push(x):(y=cd(t,x,y),void 0!==
y?v+=y:v=void 0)}void 0!=v&&(v=X(t,id(t,v,k)))}t=v}else if("{"==q){m=1;for(t=c;c<d;)if(c++,q=c<b.length?b[c++]:"","{"==q)m++;else if("}"==q&&!--m)break;t=hd(a,b,t,c-1,a.ea,g);null!=t&&k&&(t=id(a,t,k));m=c<d?b[c++].trim():"";q=c<d?b[c++]:""}else{if(" "==q)continue;if("^B"==q){a.ea=2;continue}if("^O"==q){a.ea=8;continue}if("^D"==q){a.ea=10;continue}if(!(k&-1073741824)){if("+"==q)continue;if("-"==q){k=k<<2|1;continue}if("~"==q||"^-"==q){k=k<<2|2;continue}if("^L"==q){k=k<<2|3;continue}}h=!0;break}if(void 0===
t)if(g)g.push(m),t=0;else{h=!0;break}p.push(X(a,t));if(" "==q)if(c<b.length-1&&!b[c])c++,q=b[c++];else{h=!0;break}if(!q)break;t="<"==a.$[0]?jd:kd;if(!t[q]){h=!0;break}l.length&&t[q]<=t[l[l.length-1]]&&gd(a,p,l,1);l.push(q);a.ea="^_"==q?10:e;k=0}if(h||!gd(a,p,l)||1!=p.length)h=!0;h?g||a.s("parse error (%s)\n",m||q):f=p.pop();a.ea=u;return f}
function ld(a,b,c,d){for(var e,g=a.L/d|0;0<=(e=b.indexOf(c));){for(var f=0,h=e+1,k=g;h<b.length;){var p=b[h++];if(p==c){k=-1;break}if(!k)break;k--;p=p.charCodeAt(0);6==d&&(p-=32);p&=(1<<d)-1;f=X(a,f*Math.pow(2,d)+p,d*g,!0)}if(0<=k){a.s("parse error (%c%s%c)\n",c,b,c);return}b=b.substr(0,e)+F(a,f)+b.substr(h)}return b}
function cd(a,b,c){if(b){"{"!=a.$[0]&&(b=b.split(a.$[0]).join("{").split(a.$[1]).join("}"));b=ld(a,b,'"',8);if(!b)return d;b=ld(a,b,"'",6);if(!b)return d;16!=a.ea&&(b=b.replace(/(^|[^A-Z0-9$%.])([0-9]+)B/,"$1$2^_").replace(/\s+/g," "));b=b.split(/({|}|\|\||&&|\||\^!|\^B|\^O|\^D|\^L|\^-|~|\^_|_|&|!=|!|==|>=|>>>|>>|>|<=|<<|<|-|\+|\^\/|\/|\*|,,| )/);var d=hd(a,b,0,b.length,a.ea,c)}return d}
function id(a,b,c){for(;c;){var d;switch(c&3){case 1:b=-X(a,b);break;case 2:b=fd(a,b,-1);break;case 3:for(d=35;0<=d&&!ed(a,b,Math.pow(2,d));)d--;b=35-d}c>>>=2}return b}function X(a,b,c,d){var e=b;c=c||a.L;if(d)if(32==c)e=b>>>0;else if(32>c)e=b&(1<<c)-1;else{if(a=Math.pow(2,c),0>b||b>=a)e=b%a,0>e&&(e+=a)}else 32>=c?e=b<<32-c>>32-c:(a=Math.pow(2,c-1),b>=a?(e=b%a,(b/a|0)&1&&(e-=a)):b<-a&&(e=b%a,((-b-1)/a|0)&1?e&&(e+=a):e||(e-=a)));b!=e&&(b=e);return b}
n.kb=function(a){function b(h){for(var k=0;k<h.length;k++)if(void 0!=h[k])return!1;return!0}if(-1>a)return md(this,this.kb);var c="";if(0<=a){var d=this.i[a];if(void 0!=d){c=d>>8;d&=255;var e=this.o[c];if(e){var g=this.v[c],f=g[d];(c&1?e.sb(f.O,this.l[c]):e.$a(f.O,this.l[c]))?(g[d]=void 0,this.i[a]=void 0,b(g)&&(g.length=0,b(this.i)&&(this.i.length=0)),c=this.u("%2d: %s %*a cleared\n",a,nd[c],e.ba,f),--this.da||this.fa||(c+=od(this,!1))):c=this.u("invalid break address: %*a\n",e.ba,f)}else c="invalid bus"}else c=
this.u("invalid break index: %d\n",a)}else c="missing break index\n";return c};function pd(a,b){if(a.X&&(void 0==b||a.X.O==b)){var c=void 0===c?W.ka:c;b=-1;var d=qd(a.X,a.v[c]);if(0<=d)for(var e=0;e<a.i.length;e++){var g=a.i[e];if(void 0!=g&&c==g>>8&&d==(g&255)){b=e;break}}c=b;0<=c&&a.kb(c);a.X=null}}
n.lb=function(a,b){b=void 0===b?!1:b;if(-1>a)return md(this,this.lb,b);if(0<=a){var c=this.i[a];if(void 0!=c){var d=c>>8;c=this.v[d][c&255];if(void 0!=c){var e=b?"enabled":"disabled",g=this.o[d];!c.disabled==!b?(c.disabled=!b,a=this.u("%2d: %s %*a %s\n",a,nd[d],g.ba,c,e)):a=this.u("%2d: %s %*a already %s\n",a,nd[d],g.ba,c,e)}else a=this.u("no break address at index: %d\n",a)}else a=this.u("invalid break index: %d\n",a)}else a="missing break index\n";return a};
function md(a,b,c){for(var d="",e=0;e<a.i.length;e++)void 0!=a.i[e]&&(d+=b.call(a,e,c));d||(d="no break addresses found");return d}function rd(a,b,c){c=void 0===c?W.ka:c;a=a.v[c];for(c=0;c<a.length;c++){var d=a[c];if(d.O==b)return d}}function qd(a,b){for(var c=0;c<b.length;c++)if(b[c].O==a.O)return c;return-1}
function sd(a,b){b=void 0===b?!1:b;for(var c="",d=0;d<a.i.length;d++){var e=a.i[d];if(void 0!=e){var g=e>>8;e=a.v[g][e&255];g=a.u("%s %*a",nd[g],a.o[g].ba,e);b?(c&&(c+=";"),c+=g,e.disabled&&(c+=";bd "+d)):c+=a.u("%2d: %s %s\n",d,g,e.disabled?"disabled":"enabled")}}c||b||(c="no break addresses found\n");return c}
function td(a,b,c){c=void 0===c?W.ka:c;if(b){var d=a.o[c];if(d){var e=a.v[c];var g=qd(b,e);if(0<=g)g=-(g+1);else{for(g=0;g<e.length&&void 0!=e[g];g++);e[g]=b}e=g;if(0<=e)if(g=c&1?d.qb(b.O,a.l[c]):d.Za(b.O,a.l[c])){for(g=0;g<a.i.length&&void 0!=a.i[g];g++);a.i[g]=c<<8|e;b=a.u("%2d: %s %*a set\n",g,nd[c],d.ba,b);a.da++||a.h.length||(b+=od(a,!0))}else b=a.u("invalid break address: %*a\n",d.ba,b),a.v[c][e]=void 0;else b=a.u("%s %*a already set\n",nd[c],d.ba,b)}else b="invalid bus"}else b="missing break address\n";
return b}function ud(a,b){0<=b&&(a.K=b);var c="instruction break count: "+(0<a.K?a.K:"disabled")+"\n";0<b&&(a.h.length||(c+=od(a,!0)),a.fa=!0);return c}function vd(a,b){var c;if(b){var d=Za(b);void 0!=d?a.ha=d?0xffffffffffff:0:c=a.u("unrecognized message option: %s\n",b)}c||(c=a.u("break on message: %b\n",!!a.ha));return c}n.dd=function(a,b){this.H||(void 0==a?Y(this,"break on unknown input %#0x: %#0x",b):(a=rd(this,a+b,W.Ca))&&!a.disabled&&Y(this,"break on input %*a: %#0x",this.j.ba))};
n.ed=function(a,b){this.H||(void 0==a?Y(this,"break on unknown output %#0x: %#0x",b):(a=rd(this,a+b,W.Da))&&!a.disabled&&Y(this,"break on output %*a: %#0x",this.j.ba))};n.fd=function(a,b){this.H||(void 0==a?Y(this,"break on unknown read %#0x: %#0x",b):(a+=b,this.h.length&&a==this.T.ob&&(this.aa++,0<this.K&&(--this.K||Y(this,"break on instruction count")),this.h[this.S++]=a,this.S==this.h.length&&(this.S=0)),(b=rd(this,a,W.ka))&&!b.disabled&&(Y(this,"break on read %*a: %#0x",this.g.ba),pd(this,a))))};
n.gd=function(a,b){this.H||(void 0==a?Y(this,"break on unknown write %#0x: %#0x",b):(a=rd(this,a+b,W.Ga))&&!a.disabled&&Y(this,"break on write %*a: %#0x",this.g.ba))};function Y(a,b,c){b=a.u.apply(a,[b].concat(r(c)));a.s("%s\n",b);rc(a.time)}function wd(a,b,c){c=void 0===c?a.g:c;return F(a,b.O,a.ea,c.ba,"")}
function xd(a,b,c){c=void 0===c?10:c;var d="";if(a.h.length){var e,g=[];c>a.h.length&&(c=a.h.length);0>b&&(b=c);var f=a.S-b;for(0>f&&(f+=a.h.length);0<=f&&f<a.h.length&&0<c;){var h=a.h[f++];if(void 0==h)break;f==a.h.length&&(f=0);e?e.O=h:e=Vc(h);for(h=0;1>h;h++)g[h]=dd(a,e,1);ad(a,e,-g.length);d+=a.rb(e,g,a.u("[%6d]",b--));c--}}return d||"no history"}
function yd(a,b,c){var d=[],e="";for(b="number"==typeof b?Vc(b):b;c--;){for(ad(a,b,d.length);1>d.length;)d.push(dd(a,b,1));ad(a,b,-d.length);e+=a.rb(b,d)}return e}
function zd(a,b,c,d,e,g){var f="";g=g?a.j:a.g;c||(c=g.i);var h=c>>3;d||(d=128);var k=0,p=d+15>>4||1,l=4==h?16:a.ea;"y"==e&&(l=h,p=d,k=8*h);b||(b=a.ra);for(;p--&&0<d;){var u=e=0,m,q="",v="",t=wd(a,b,g);for(m=l;0<m&&0<d;m--){var x=dd(a,b,1,g);e|=x<<(u++<<3);u==h&&(q+=F(a,e,0,c,""),q+=1==h?9==m?"-":" ":" ",k&&(v+=F(a,e,2,c,"")),e=u=0);k||(v+=32<=x&&127>x?String.fromCharCode(x):".");d--}f&&(f+="\n");f+=t+"  "+q+" "+v}a.ra=b;return f}
n.pd=function(){var a=[];mb(this,function(b){b.Ja&&b.Ja(a);return!0});return JSON.stringify(a,null,2)};function Ad(a,b,c,d){var e=0,g="";d=d?a.j:a.g;for(var f=0;void 0!=b&&f<c.length;f++){var h=dd(a,b,0,d);if(void 0==h)break;var k=a,p=b,l=c[f],u=d;u=void 0===u?k.g:u;k.H++;u.tb(p.O,l);k.H--;g+=a.u("%*a: %#*n changed to %#*n\n",a.g.ba,b,a.g.i,h,a.g.i,c[f]);ad(a,b,1,d);e++}e||(g+=a.u("%d locations updated\n",e));a.time.update();return g}
function od(a,b){var c="";void 0!=b&&b==!a.h.length&&Mc(a.g,function(d){b?a.g.Za(d.ya,a.l[W.ka]):a.g.$a(d.ya,a.l[W.ka])})&&(b?(a.S=0,a.h=Array(Bd)):a.h=[]);return c+=a.u("instruction history %s\n",a.h.length?"enabled":"disabled")}n.ua=function(a){var b=a.shift();return this.U==b?(Xa(this,a.shift()),this.I.ga=a.shift(),!0):!1};n.nc=function(a){Ba(this.ha,a)?Y(this,"break on message"):this.time.X=!0};
n.rd=function(a){var b=a[1],c=a[2],d=[],e=[],g=!1,f="";this.R=void 0;if("*"==c)var h=-2;else{h=Aa(c);void 0==h&&(h=-1);var k=Xc(this,c,e);if(null===k)return}var p=0;a[3]&&(p=Aa(a[3].substr("l"==a[3][0]?1:0))||8);for(var l=3;l<a.length;l++)d.push(Aa(a[l],16));if("d"==b){l=Wc(this,c,d);if(void 0!=l)return l;b=this.V||b}if("s"!=b[0]&&e.length)return"unrecognized symbol(s): "+e;switch(b[0]){case "b":"c"==b[1]?f=this.kb(h):"d"==b[1]?f=this.lb(h):"e"==b[1]?f=this.lb(h,!0):"i"==b[1]?f=td(this,k,W.Ca):"l"==
b[1]?f=sd(this):"m"==b[1]?f=vd(this,c):"n"==b[1]?f=ud(this,h):"o"==b[1]?f=td(this,k,W.Da):"r"==b[1]?f=td(this,k,W.ka):"w"==b[1]?f=td(this,k,W.Ga):"?"==b[1]?(f="break commands:\n",Cd.forEach(function(u){f+=u+"\n"})):b[1]&&(f=void 0);break;case "d":this.V=b;if("b"!=b[1]&&b[1])if("w"==b[1])c=16;else if("d"==b[1])c=32;else if("i"==b[1]){if(!this.j){f="invalid bus";break}c=this.j.i;p=p||1;g=!0}else{if("h"==b[1])this.V="",f=xd(this,h,p);else if("?"==b[1]){if(this.V="",f="dump commands:\n",Dd.forEach(function(u){f+=
u+"\n"}),this.J.length)for(f+="dump extensions:\n",b=0;b<this.J.length;b++)k=this.J[b],f+=this.u("d   %-12s%s\n",k.name,k.nd)}else this.V="",f=void 0;break}else c=8;f=zd(this,k,c,p,b[2],g);break;case "e":if("o"==b[1]){if(!this.j){f="invalid bus";break}g=!0}else if(b[1]){f=void 0;break}f=Ad(this,k,d,g);break;case "g":if(this.time.start()){if(void 0!=k){pd(this);f=td(this,k);if(2!=f.indexOf(":"))break;this.X=k;f=""}break}f="already started\n";break;case "h":rc(this.time)||(f="already stopped\n");break;
case "p":a.shift();a.shift();b=a.join(" ");f+=this.u("%s = %s\n",b,F(this,cd(this,b)));break;case "r":if(b=b.substr(1).toUpperCase()){if(void 0==ob(this.T,b)){f+=this.u("unrecognized register: %s\n",b);break}void 0!=k&&tb(this.T,b,k.O)}this.ca.O=this.T.i;f+=this.T.toString();break;case "s":k=Za(c);if("h"==b[1]){if(this.da||0<this.K)k=void 0;f=od(this,k);void 0!=k&&(this.fa=k)}else"p"==b[1]?0<h?(oc(this.time,h),f="target speed:  "+uc(this.time.v)):f="current speed: "+Dc(this.time):"s"==b[1]&&this.sa?
(h=this.sa.indexOf(c),0<=h&&(this.style=this.sa[h]),f="style: "+this.style):"?"==b[1]?(f="set commands:\n",Ed.forEach(function(u){f+=u+"\n"})):f=void 0;break;case "t":p=Aa(c,10)||1;this.R=!0;if(b[1]){if("r"!=b[1]){f=void 0;break}this.R=!1}wc(this.time,p);break;case "u":if(b[1]){f=void 0;break}p||(p=8);k||(k=this.ca);f+=yd(this,k,p);this.ca=k;break;case "?":f="debugger commands:\n";Fd.forEach(function(u){f+=u+"\n"});break;default:f=void 0}void 0==f&&a[0]&&(f="unrecognized command '"+a[0]+"' (try '?')\n");
return f};n.mb=function(a){return a&&this.ua(a[0])?(a.shift(),!0):!1};n.Ja=function(a){var b=[];this.wa(b);a.push(b);this.Y=0};n.oc=function(a){a&&(this.time.g?this.Y&&this.qa&&Qb(this.qa):this.R?this.za(yd(this,this.T.i,1)):(this.aa&&(this.T.s("%d instructions executed\n",this.aa),this.aa=0),this.T.za(this.T.toString()),void 0==this.R&&this.Y&&(a=this.ta(Ga.Pa,!0))&&a.focus()),this.Y++)};n.wa=function(a){a.push(this.U);a.push(sd(this,!0));a.push(this.I.ga)};
n.rb=function(a,b,c){var d=this.u,e=wd(this,a);b=b.shift();ad(this,a,1);return d.call(this,"%s %02x       unsupported       ; %s\n",e,b,c||"")};
var Fd="b?\t\tbreak commands;d?\t\tdump commands;e[o] [addr] ...\tedit memory/ports;g    [addr]\trun (to addr);h\t\thalt;p    [expr]\tparse expression;r?   [value]\tdisplay/set registers;s?\t\tset commands;t[r] [n]\tstep (n instructions);u    [addr] [n]\tunassemble (at addr)".split(";"),Cd="bc [n|*]\tclear break address;bd [n|*]\tdisable break address;be [n|*]\tenable break address;bl [n]\t\tlist break addresses;bi [addr]\tbreak on input;bo [addr]\tbreak on output;br [addr]\tbreak on read;bw [addr]\tbreak on write;bm [on|off]\tbreak on message;bn [count]\tbreak on instruction count".split(";"),Dd=
"db  [addr]\tdump bytes (8 bits);dw  [addr]\tdump words (16 bits);dd  [addr]\tdump dwords (32 bits);di  [addr]\tdump input ports;d*y [addr]\tdump values in binary;dh  [n] [l]\tdump instruction history buffer;ds\t\tdump machine state".split(";"),Ed=["sh [on|off]\tset instruction history","sp [n]\t\tset speed multiplier","ss\t\tset debugger style"],bd={dc:1,Lc:0,Mc:2,Ie:0},W={ka:0,Ga:1,Ca:2,Da:3},Gd={},nd=(Gd[W.ka]="br",Gd[W.Ga]="bw",Gd[W.Ca]="bi",Gd[W.Da]="bo",Gd),Z={BYTE:1,Kc:2,Nc:4,Lb:5,Ab:6,Zc:7},
Yc={"=":Z.Zc,1:Z.BYTE,2:Z.Kc,4:Z.Nc,"@":Z.Lb,";":Z.Ab},Bd=1E5,kd={"||":5,"&&":6,"!":7,"|":7,"^!":8,"&":9,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,_:19,"^_":19,"{":20,"}":20},jd={",,":1,"||":5,"&&":6,"!=":10,"==":10,">=":11,">":11,"<=":11,"<":11,">>>":12,">>":12,"<<":12,"-":13,"+":13,"^/":14,"/":14,"*":14,"!":15,"|":15,"^!":15,"&":15,_:19,"^_":19,"{":20,"}":20};function Hd(a,b,c){Sc.call(this,a,b,c)}z(Hd,Sc);E.CPUx86=Hd;
function Id(a,b,c){Uc.call(this,a,b,c)}z(Id,Uc);Id.prototype.rb=function(a,b,c){var d=wd(this,a),e="",g=$c(this,a,Z.Lb),f=$c(this,a,Z.Ab);b=b.shift();e+=F(this,b,16,8,"");ad(this,a,1);a=this.u("%#02x",b);d=this.u("%s %-7s %-7s %s",d,e,a,"");c?f&&(c+=" "+f):f&&(c=f);c&&(d=this.u("%-32s; %s",d,c));g&&(d=g+":\n"+d);return d+"\n"};E.Dbgx86=Id;
function Jd(a,b,c){S.call(this,a,b,c);this.X=this.m.bufferAddr;this.M=this.m.interruptRate;this.R=this.m.refreshRate||60;this.V=O(this,this.m.bus);this.T=P(this,"CPU");this.time=P(this,"Time");this.S=Bb(this.time,this.U,this.da.bind(this));this.time.V.push(this);Gb(this.time,this.S,1E3/Math.max(this.R,this.M))}z(Jd,S);Jd.prototype.oc=function(){};
Jd.prototype.da=function(a){if(!a){if(this.aa&&this.Y){a=this.V;var b=this.X,c=this.Y,d=b>>>a.h;for(b=a.blockSize-(b&a.l);0<c&&d<a.g.length;){var e=a.g[d];e.o&&(e.o=!1,e.h.type==Ic&&(e.i?e.j=e.ub:e.pa=e.ub));c-=b;b=a.blockSize;d++}}Gb(this.time,this.S,1E3/Math.max(this.R,this.M))}};E.PCx86Video=Jd;
function Kd(a,b,c){N.call(this,a,a);var d=this;this.i=!1;this.v=c;this.h="";this.o=this.l=!1;qb(this,!1);this.ga=0;b=b.trim();"{"==b[0]?Ld(this,b):(this.h=b,Ra(this.h,function(e,g,f,h){4==f&&(!h&&g?(Ld(d,g),Md(d)):d.s("error (%d) loading configuration: %s\n",h,e))}));window.addEventListener("load",function(){d.o=!0;Md(d)});window.addEventListener(Va("iOS")?"pagehide":Va("Opera")?"unload":"beforeunload",function(){Nd(d)});window.addEventListener("pageshow",function(){d.i||d.ja(!0)})}z(Kd,N);
Kd.prototype.xa=function(a,b){var c=this;switch(a){case Od:b.onclick=function(){c.ja()};break;case Pd:b.onclick=function(){c.ma()}}N.prototype.xa.call(this,a,b)};
function Md(a){var b=!0;if(a.l&&a.o){for(var c in a.g){var d=void 0,e=a.g[c];try{d=e["class"],E[d]?"Machine"==d?(a.s("PCjs %s v%3.2f\n%s\n",e.name,3,"Copyright \u00a9 2012-2024 Jeff Parsons <Jeff@pcjs.org>"),a.h&&a.s("Configuration: %s\n",a.h)):new E[d](a.N,c,e):a.s('unrecognized %s device "%s"\n',d,c)}catch(f){e.optional||(a.s('error initializing %s device "%s": %s\n',d,c,f.message),b=!1),sb(a,c)}}if(a.j){var g=Wa(a);mb(a,function(f){return f.mb&&!f.mb(g)?(f.s('unable to restore state for device "%s"\n',
f.U),!1):!0})}qb(a,!0);rb(a,a.ja.bind(a,b))||a.s("machine %s not ready to power, waiting for device(s)\n",a.N)}}
function Ld(a,b){try{a.g=JSON.parse(b);var c=a.g[a.N];if(!c){c=a.g[Da(a.h)];if(!c)throw Error("configuration missing machine ID");a.g[a.N]=c}lb(a,c,["autoSave","autoStart"]);a.j=!1!==a.m.autoSave;a.H=!1!==a.m.autoStart;if(a.v){var d=eval("("+a.v+")"),e;for(e in d)a.m[e]=d[e]}a.l=!0}catch(g){c=g.message,(d=c.match(/position ([0-9]+)/))&&(c+=" ('"+b.substr(+d[1],40).replace(/\s+/g," ")+"...')"),a.s("machine '%s' initialization error: %s\n",a.N,c)}}
Kd.prototype.ja=function(a){a=void 0===a?!this.i:a;if(pb(this)){var b=this;a&&this.s("power on\n");mb(this,function(c){c.ja&&c!=b&&("CPU"!=c.m["class"]||b.H&&pb(b)?c.ja(a):c.time.update(!0));return!0});(this.i=a)||this.s("power off\n")}};Kd.prototype.ma=function(){if(pb(this)){var a=this;mb(this,function(b){b.ma&&b!=a&&b.ma();return!0});this.s("reset\n")}};function Nd(a){if(a.j){var b=[];mb(a,function(c){c.Ja&&c.Ja(b);return!0});db(a,b)}a.ja(!1)}var Od="power",Pd="reset";
window.PCx86v3=function(a,b,c){var d=new Kd(a,b,c);window.command=function(e){return Xa(d,e)};return d};E.Machine=Kd;})()

//# sourceMappingURL=pcx86v3.js.map
